### ISSUE TITLE
Deserializing MapProperty fails with instant execution

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#10003]
Task with

```
abstract MyTask : DefaultTask() {
  @get: Input
  val values = objects.mapProperty(String.class, Object.class)
}
```
serializes successfully, but loading the task graph fails with:

```
org.gradle.api.GradleException: Could not load the value of field `manifestPlaceholders` of task `:common:processDebugManifest` of type `com.android.build.gradle.tasks.ProcessLibraryManifest`.
        at org.gradle.instantexecution.serialization.beans.BeanPropertyReaderKt.readEachProperty(BeanPropertyReader.kt:177)
        at org.gradle.instantexecution.serialization.beans.BeanPropertyReader.readFieldsOf(BeanPropertyReader.kt:81)
        at org.gradle.instantexecution.serialization.codecs.TaskGraphCodec.readTask(TaskGraphCodec.kt:124)
        ...
Caused by: java.util.NoSuchElementException: Key hashTable is missing in the map.
        at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
        at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:294)
        at org.gradle.instantexecution.serialization.beans.BeanPropertyReader$readFieldsOf$2.invoke(BeanPropertyReader.kt:82)
        at org.gradle.instantexecution.serialization.beans.BeanPropertyReader$readFieldsOf$2.invoke(BeanPropertyReader.kt:47)
        at org.gradle.instantexecution.serialization.beans.BeanPropertyReaderKt.readEachProperty(BeanPropertyReader.kt:179)
        at org.gradle.instantexecution.serialization.beans.BeanPropertyReader.readFieldsOf(BeanPropertyReader.kt:81)
        at org.gradle.instantexecution.serialization.codecs.BeanCodec.decode(BeanCodec.kt:60)
        at org.gradle.instantexecution.serialization.CombinatorsKt$reentrant$1$decodeLoop$1.invokeSuspend(Combinators.kt:129)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:114)
        at org.gradle.instantexecution.serialization.CombinatorsKt$reentrant$1.decodeLoop(Combinators.kt:131)
        at org.gradle.instantexecution.serialization.CombinatorsKt$reentrant$1.decode(Combinators.kt:98)
        at org.gradle.instantexecution.serialization.codecs.Codecs.decode(Codecs.kt:156)
        at org.gradle.instantexecution.serialization.DefaultReadContext.read(Contexts.kt:110)
        at org.gradle.instantexecution.serialization.beans.BeanPropertyReaderKt.readEachProperty(BeanPropertyReader.kt:169)
        ... 98 more
```

**Comment by gavra0** [comment]
The root cause is that serialization and deserialization of `RegularImmutableMap` is not implemented yet, and that is the type used for the evaluated value of `MapProperty`.

**Comment by eskatos** [comment]
Fixed in https://github.com/gradle/gradle/pull/10007
