### ISSUE TITLE
Clean fails with NPE with instant execution

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#10011]
Running clean fails with NPE:
```
Caused by: java.lang.NullPointerException
        at org.gradle.language.base.plugins.LifecycleBasePlugin$1.call(LifecycleBasePlugin.java:58)
        at org.gradle.language.base.plugins.LifecycleBasePlugin$1.call(LifecycleBasePlugin.java:55)
        at org.gradle.util.GUtil.uncheckedCall(GUtil.java:461)
        at org.gradle.util.DeferredUtil.unpackNestableDeferred(DeferredUtil.java:64)
        at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:69)
        at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:79)
        at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:79)
        at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.visitContents(DefaultConfigurableFileCollection.java:209)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.add(DefaultFileCollectionResolveContext.java:61)
        at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:43)
        at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:71)
        at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:79)
        at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.visitContents(DefaultConfigurableFileCollection.java:209)
        at org.gradle.api.internal.file.CompositeFileCollection.getSourceCollections(CompositeFileCollection.java:191)
        at org.gradle.api.internal.file.CompositeFileCollection.iterator(CompositeFileCollection.java:59)
        at org.gradle.execution.plan.DefaultExecutionPlan.canonicalizedPaths(DefaultExecutionPlan.java:729)
        at org.gradle.execution.plan.DefaultExecutionPlan.access$800(DefaultExecutionPlan.java:90)
        at org.gradle.execution.plan.DefaultExecutionPlan$8$3.run(DefaultExecutionPlan.java:647)
        at org.gradle.execution.plan.DefaultExecutionPlan.withDeadlockHandling(DefaultExecutionPlan.java:679)
        at org.gradle.execution.plan.DefaultExecutionPlan.access$900(DefaultExecutionPlan.java:90)
        at org.gradle.execution.plan.DefaultExecutionPlan$8.visitDestroyableProperty(DefaultExecutionPlan.java:644)
        at org.gradle.api.internal.tasks.properties.annotations.DestroysPropertyAnnotationHandler.visitPropertyValue(DestroysPropertyAnnotationHandler.java:53)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode.visitProperties(AbstractNestedRuntimeBeanNode.java:59)
        at org.gradle.api.internal.tasks.properties.bean.RootRuntimeBeanNode.visitNode(RootRuntimeBeanNode.java:32)
        at org.gradle.api.internal.tasks.properties.DefaultPropertyWalker.visitProperties(DefaultPropertyWalker.java:41)
        at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:42)
        at org.gradle.execution.plan.DefaultExecutionPlan.resolveMutations(DefaultExecutionPlan.java:609)

```

It seems that the `Project.getBuildDir()` is used in the `LifecycleBasePlugin` to determine the directory to be deleted, which is causing the issue.

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/10018
