### ISSUE TITLE
Unable to determine task dependencies with Gradle 5.6-rc-1

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#10177]
To reproduce:
`git clone https://github.com/gavra0/santa-tracker-android.git && cd santa-tracker-android && ./gradlew :common:connectedDebugAndroidTest`

fails with
```
Caused by: java.lang.IllegalStateException: No value has been specified for this provider.
        at org.gradle.api.internal.provider.Providers$1.get(Providers.java:32)
        at org.gradle.api.internal.provider.DefaultProperty.get(DefaultProperty.java:157)
        at org.gradle.api.internal.provider.AbstractMinimalProvider$FlatMapProvider.get(AbstractMinimalProvider.java:138)
        at org.gradle.api.internal.tasks.DefaultTaskDependency.visitDependencies(DefaultTaskDependency.java:96)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:111)
        at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmptyEdges.getNodeValues(CachingDirectedGraphWalker.java:213)
        at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:121)
        at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:73)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:66)
        ... 109 more
```

Reverting to Gradle 5.5.1 fixes the issue.

**Comment by gavra0** [comment]
Reduced repro. It fails with 5.6-rc-1, and passes with 5.5.
```
def myTask = tasks.create("myTask")
myTask.dependsOn(objects.directoryProperty())
```

**Comment by gavra0** [comment]
Unless there are other use-cases, feel free to close this issue, as we fixed this in AGP.
