### ISSUE TITLE
Updatung Gradle returns Error: Entry name contains invalid characters: ../../tmplMrzJR/.empty

### ISSUE THREAD

**Issue by 28development** [gradle/gradle#10175]
After migrating my current app to AndroidX and updating the gradle version to: 3.4.2

I get this error if I try to run the app:

> java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.nio.file.InvalidPathException: Entry name contains invalid characters: ../../tmplMrzJR/.empty
    at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
    at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)...
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.android.build.api.transform.TransformException: java.nio.file.InvalidPathException: Entry name contains invalid characters: ../../tmplMrzJR/.empty
    at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.transform(DexArchiveBuilderTransform.java:442)
    at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
    at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
    at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
    ... 77 more
Caused by: java.nio.file.InvalidPathException: Entry name contains invalid characters: ../../tmplMrzJR/.empty
    at com.android.builder.desugaring.DesugaringClassAnalyzer.analyzeJar(DesugaringClassAnalyzer.java:94)
    at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:68)
    at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.lambda$getInitalGraphData$4(DesugarIncrementalTransformHelper.java:150)
    at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

My build gradle (project) looks like this:

```
buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath 'com.google.gms:google-services:4.2.0'
    }
}

allprojects {
    repositories {
        maven { url "https://jitpack.io" }
        maven { url "https://maven.google.com" }
        jcenter()
        flatDir {
            dirs 'libs'
        }
        google()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

And my build.gradle(module app) looks like this:

```

apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    useLibrary 'org.apache.http.legacy'
    defaultConfig {
        multiDexEnabled true
        applicationId 'de.myapp.appname'
        minSdkVersion 22
        targetSdkVersion 28
        versionCode 13
        versionName "2.3.42"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
    compileOptions {
        targetCompatibility JavaVersion.VERSION_1_8
        sourceCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0'
    implementation 'androidx.annotation:annotation:1.1.0'
    annotationProcessor 'androidx.lifecycle:lifecycle-compiler:2.0.0'
    implementation 'com.github.GrenderG:Toasty:1.4.2'
    implementation 'com.jakewharton:butterknife:8.1.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.1.0'
    implementation 'com.squareup.retrofit2:retrofit:2.3.0'
    implementation 'com.squareup.retrofit2:converter-moshi:2.3.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
    implementation 'com.basgeekball:awesome-validation:2.0'
    implementation 'com.github.apl-devs:appintro:v4.2.2'
    implementation 'com.github.KyleBanks:animated-line-graph-view:v1.0.1'
    implementation 'com.hbb20:ccp:2.2.2'
    implementation 'com.google.android.gms:play-services-base:17.0.0'
    implementation 'com.google.firebase:firebase-core:17.0.1'
    implementation 'com.google.firebase:firebase-messaging:19.0.1'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'com.jakewharton.picasso:picasso2-okhttp3-downloader:1.1.0'
    implementation 'com.koushikdutta.async:androidasync:2.2.1'    
    implementation 'com.pubnub:pubnub-android:3.7.4'
    implementation 'com.pubnub:pubnub-gson:4.18.0'
    implementation 'io.pristine:libjingle:9694@aar'
    implementation project(':pnwebrtc')
}

apply plugin: 'com.google.gms.google-services'

repositories {
    mavenCentral()
    google()
}

```

I also tried to clean and rebuild the project, but it did not help.
Further I migrated using Refactor -> Migrate to Android X...

**Comment by kaushikkhambhadiya** [comment]
i got the same error and i'm able resolve by upgrading my android studio build path to:
 classpath 'com.android.tools.build:gradle:3.5.0'
and i have also upgraded my gradel-wrapper properties to :
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip 
after successfully Sync ....clean and rebuild your project and boom error gone.
