### ISSUE TITLE
gradle 5.4.1 not compatible with java11 and jaxb

### ISSUE THREAD

**Issue by aamitnsw** [gradle/gradle#10336]
Even after using these configs with gradle 5.4.1
implementation 'javax.xml.bind:jaxb-api:2.3.1'
implementation 'com.sun.xml.bind:jaxb-core:2.3.0.1'
    implementation 'com.sun.xml.bind:jaxb-impl:2.3.2'
    implementation 'javax.activation:activation:1.1.1'

Getting the error
                Caused by:
                javax.xml.bind.UnmarshalException
                 - with linked exception:
                [org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.]
                    at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:340)
                    at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:548)
                    at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:234)
                    at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:199)
                    at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:153)
                    at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:136)
                    at org.springframework.http.converter.xml.Jaxb2RootElementHttpMessageConverter.readFromSource(Jaxb2RootElementHttpMessageConverter.java:129)
                    at org.springframework.http.converter.xml.AbstractXmlHttpMessageConverter.readInternal(AbstractXmlHttpMessageConverter.java:68)
                    ... 10 more

**Comment by blindpirate** [comment]
Can you provide a minimal reproducible example? Does it work with previous Gradle version?

**Comment by aamitnsw** [comment]
I am not sure if it ever worked ? Now when jaxb is no longer part of java11 ,I am not sure how to code the solution ,when we have hard dependency on xml un/marshalling

**Comment by blindpirate** [comment]
You probably need to adjust some configurations on Java 11 to make JAXB work again. We can't help with only a few lines of build script and a stacktrace.

**Comment by blindpirate** [comment]
https://stackoverflow.com/questions/52502189/java-11-package-javax-xml-bind-does-not-exist
