### ISSUE TITLE
Gradle 5.6 - RuntimeException: Unable to load FastStringService

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#10347]
https://discuss.gradle.org/t/gradle-5-6-runtimeexception-unable-to-load-faststringservice/32865

### Expected Behavior
Should not crash.

### Current Behavior
Crashes, sometimes?

### Context
This needs more investigation.

### Your Environment

Build scan URL:

**Comment by DPUkyle** [comment]
Here's a small ST we see when invoking `new groovy.json.JsonSlurper().parseText(String)` from an initialization script:

```
java.lang.RuntimeException: Unable to load FastStringService
       at org.apache.groovy.json.internal.FastStringUtils.getService(FastStringUtils.java:57)
       at org.apache.groovy.json.internal.FastStringUtils.toCharArray(FastStringUtils.java:67)
       at org.apache.groovy.json.internal.BaseJsonParser.parse(BaseJsonParser.java:112)
    ...
```

I'll try to create a reproducible, shareable example.

**Comment by blindpirate** [comment]
I can reproduce it locally, investigating.

**Comment by pp-lucaal-sportsbet** [comment]
I could reproduce this easily running "yarn android" with gradle 5.6
