### ISSUE TITLE
vm_stat occasionally fails and causes build failures

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#1039]
This seems to be broken again (only on master, not in 3.3): https://github.com/gradle/gradle/issues/897

This only happens locally on macOS.  I have it randomly causing local build failures:
```
Failed to collect memory status: Unable to read memory info from /usr/bin/vm_stat
java.lang.UnsupportedOperationException: Unable to read memory info from /usr/bin/vm_stat
	at org.gradle.process.internal.health.memory.VmstatAvailableMemory.getVmstatOutput(VmstatAvailableMemory.java:74)
	at org.gradle.process.internal.health.memory.VmstatAvailableMemory.get(VmstatAvailableMemory.java:50)
	at org.gradle.process.internal.health.memory.MemoryInfo.getFreePhysicalMemory(MemoryInfo.java:66)
	at org.gradle.process.internal.health.memory.MemoryInfo.getOsSnapshot(MemoryInfo.java:78)
	at org.gradle.process.internal.health.memory.MemoryStatusBroadcaster$MemoryCheck.run(MemoryStatusBroadcaster.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/usr/bin/vm_stat''
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:198)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:329)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:86)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	... 3 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not start '/usr/bin/vm_stat'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:68)
	... 5 more
Caused by: java.io.IOException: Cannot run program "/usr/bin/vm_stat" (in directory "/Users/sterling/gits/gradle/subprojects/language-native/build/tmp/test files/CppLangPluginIntegrationTest/can_apply_plugin_unqualified/kodpa"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 more
```

There was a lot of work done recently to move the way we monitor memory around by @eskatos or @ghale I think.

We really just need to push collecting this into `native-platform` and be done with it.

**Comment by eskatos** [comment]
Could be that the working directory does not exist anymore.
I'll move it from `.` to `/` as a first step.

Effort in `native-platform` is in progress, e.g. see https://github.com/adammurdoch/native-platform/pull/21

**Comment by eriwen** [comment]
Moving to Flaky Test Quarantine given that 3333096 is on master

**Comment by eskatos** [comment]
The flakiness was first alleviated by https://github.com/gradle/gradle/commit/33330963b8e35e9bfc171988d4093eb40a042460 and is now fixed by https://github.com/gradle/gradle/commit/b64e1d0.

@big-guy, can you confirm that it did not happen to you recently?

**Comment by big-guy** [comment]
I haven't noticed it for awhile and it looks like any places that could throw an exception are handled.

**Comment by eskatos** [comment]
Thanks! 
Closing.
