### ISSUE TITLE
gradle-api-5.6.1.jar is an invalid module

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle#10408]
`jdeps` reports that `gradle-api-5.6.1.jar` is an invalid module (see the error at end of this issue).

It seems to be caused by `META-INF/services/java.security.Provider` including the following line:

```
org.bouncycastle.pqc.jcajce.provider.BouncyCastlePQCProvider
```

But `gradle-api-5.6.1.jar` does not contain that class.  It does, however, contain the following class:

```
org.gradle.internal.impldep.org.bouncycastle.jce.provider.BouncyCastleProvider
```

Should the class name in `META-INF/services/java.security.Provider` be changed to the one that is actually in the jar?

```
jdeps -v --module-path ~/.gradle/caches/5.6.1/generated-gradle-jars/gradle-api-5.6.1.jar some.jar 
Exception in thread "main" java.lang.module.FindException: Unable to derive module descriptor for /Users/ross.goldberg/.gradle/caches/5.6.1/generated-gradle-jars/gradle-api-5.6.1.jar
	at java.base/jdk.internal.module.ModulePath.readJar(ModulePath.java:646)
	at java.base/jdk.internal.module.ModulePath.readModule(ModulePath.java:329)
	at java.base/jdk.internal.module.ModulePath.scan(ModulePath.java:235)
	at java.base/jdk.internal.module.ModulePath.scanNextEntry(ModulePath.java:188)
	at java.base/jdk.internal.module.ModulePath.findAll(ModulePath.java:164)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:558)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:603)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:557)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:533)
	at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)
Caused by: java.lang.module.InvalidModuleDescriptorException: Provider class org.bouncycastle.pqc.jcajce.provider.BouncyCastlePQCProvider not in module
	at java.base/jdk.internal.module.ModulePath.deriveModuleDescriptor(ModulePath.java:553)
	at java.base/jdk.internal.module.ModulePath.readJar(ModulePath.java:642)
	... 9 more
```

**Comment by rgoldberg** [comment]
This has been fixed by now.
