### ISSUE TITLE
Pass-through Environment Variables to Gradle Daemon Processes

### ISSUE THREAD

**Issue by eaaltonen** [gradle/gradle#10483]
Currently daemon builds are prone to not working when build uses a tool that is typically used via environment variables (`PATH` being a key variable).

### Expected Behavior
1. Gradle daemon is started in a system default shell.
2. A seconds shell executes the tools setup script, which includes adding a program to the `PATH`.
3. Second shell starts Gradle build and passes the _it's own environment_ to the daemon.
4. Daemon examines the **build configuration** and executes the build program from the `PATH` of the second shell.

### Current Behavior
Currently step 4) in above fails with the build program not found.

### Context
I use two tools suites that are designed to be used via the environment:
* Yocto **bitbake** _(includes a cross-compiler)_
* Xilinx Vivado

This functionality would be required for gradle-native Yocto support [issue 1032](https://github.com/gradle/gradle-native/issues/1032).

**Comment by eaaltonen** [comment]
The incubating [environmentVariable Provider](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/ProviderFactory.html#environmentProperty-java.lang.String-) might support this.

**Comment by mlopatkin** [comment]
The interesting thing here is that the updated PATH variable is visible to the daemon but it isn't considered when starting a native process:
```
task runSomeProgram(type: Exec) {
    doFirst {
        println System.getenv('PATH')
    }
    commandLine 'printhello.sh'
}
```

```
$ export PATH=$PATH:.
$ ./gradlew runSomeProgram
> Task :runSomeProgram FAILED
/home/mlopatkin/.jenv/versions/11/bin:/home/mlopatkin/.jenv/libexec:/home/mlopatkin/.jenv/shims:/home/mlopatkin/depot_tools:/home/mlopatkin/.cargo/bin:/home/mlopatkin/bin:/home/mlopatkin/depot_tools:/home/mlopatkin/.cargo/bin:/home/mlopatkin/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/mlopatkin/tools/texlive/2020/bin/x86_64-linux:/home/mlopatkin/tools/texlive/2020/bin/x86_64-linux:.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runSomeProgram'.
> A problem occurred starting process 'command 'printhello.sh''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 346ms
1 actionable task: 1 executed
```

**Comment by mlopatkin** [comment]
We do all we can to update the PATH variable (and other environment variables) in the daemon, we even update the native storage with `setenv`. However, JDK doesn't use this environment when starting a child process, it has [its own cache](https://github.com/openjdk/jdk11u/blob/master/src/java.base/unix/native/libjava/childproc.h#L129) for this purposes. The reason for this seems to be the lack of `execvpe` in POSIX, so you can either have PATH lookup or provide environment variables.

There is no API to update/reset this cache, so the easiest possible way out is to consider the PATH variable immutable and spawn a new daemon if there is no suitable existing daemon with the same PATH. Other workarounds (for example, resolving the PATH ourselves or using a trampoline process) may fail if third-party code (build script, plugins) uses `java.lang.ProcessBuilder` API directly. We can try to rewrite this during classloading though.

**Comment by eaaltonen** [comment]
Interesting indeed.

It looks like the Windows Processthreadsapi.h does have a call with similar functionality, `CreateProcessA( ..., LPVOID lpEnvironment, ...)

* https://docs.microsoft.com/en-us/windows/win32/procthread/environment-variables
* https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessa

I think that would leave two ways to pursue this:

a) Move towards adding this feature to the JDK
b) Implement in the Gradle daemon by using the native calls there

### Add to JDK Path

I suppose this path might start with an extension using either JNI / JNA and later drive a _ JDK Enhancement Proposal_ (JEP) to get the feature in to the standard JRE & JDK.

### Implement in the Gradle daemon

Probably quicker, the Gradle daemon could do the necessary native calls directly.

**Comment by Ribesg** [comment]
I encountered this issue too. I have to disable the daemon.

**Comment by mhsmith** [comment]
> the easiest possible way out is to consider the PATH variable immutable and spawn a new daemon if there is no suitable existing daemon with the same PATH

Yes, this would be basically be an addition to the list of "effectively immutable" JVM properties listed [here](https://docs.gradle.org/current/userguide/gradle_daemon.html).

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before it gets implemented.

***

The feature in Gradle would be to support a mode where a new daemon is spawned when `PATH` changes.
This should be done from the outside for now for builds where it matters.

**Comment by mhsmith** [comment]
On macOS, the daemon is not currently receiving updates of any environment variables at all (https://github.com/gradle/gradle/issues/12905#issuecomment-675193289).

**Comment by goafabric** [comment]
@goafabric remindme

**Comment by abdulowork** [comment]
One way to bypass this limitation right now could to spawn the subprocess through an indirection such as `env`. For example on macOS, given `build.gradle.kts`:
```Kotlin
tasks.register<Exec>("runMe") {
  commandLine = listOf("/usr/bin/env", "runMe.sh")
  // Force JVM to cache PATH by setting some environment variables
  environment["FOO"] = "BAR"
}
```
and the layout:
```
/a
  /runMe.sh
/b
  /runMe.sh
```
running either `PATH="$(realpath a):$PATH" gradle --daemon runMe` or `PATH="$(realpath b):$PATH" gradle --daemon runMe` calls the right `runMe.sh` since the subprocess is now spawned by `/usr/bin/env` instead of the JVM `PATH`-cached `execvpe`.

**Comment by bcalmac** [comment]
I would like to add a use case for this issue. I use the `gradle-docker-compose-plugin` that invokes `docker` at some point. On MacOS with DockerDesktop it is located in `usr/local/bin`. As of Java 21, the invocation through a gradle daemon fails with:

```
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'docker''
	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:241)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:218)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:386)
	at org.gradle.process.internal.ExecHandleRunner.lambda$run$3(ExecHandleRunner.java:102)
	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:101)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'docker'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:122)
	at org.gradle.process.internal.ExecHandleRunner.lambda$run$0(ExecHandleRunner.java:80)
	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:79)
	... 2 more
Caused by: java.io.IOException: Cannot run program "docker" (in directory "/Users/bcalmac/code/ccp/lca3-2"): error=2, No such file or directory
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
	... 8 more
```

This works OK on Java 17 or if the gradle daemon is disabled with `org.gradle.daemon=false`. The issue with Java 21 seems to be that the gradle daemon cannot invoke the `docker` executable the same way the original gradle process does, because it doesn't consider the `/usr/local/bin` location for some reason or another.

**Comment by goafabric** [comment]
@bcalmac thats nearly an identical issue i created initially .. so i support that, and wondering while there is still no solution 

Unfortunately it just seems to be the combi of java21, mac + shellexecute (not only docker)

**Comment by goeh** [comment]
I tried to upgrade a few Micronaut projects to use Java 21 and Gradle 8.6 this week (was Java 17 and Gradle 7.5). My build.gradle tries to exec 'docker' but it fails with the same stacktrace as above (No such file or directory). Docker command is in /usr/local/bin and it's in my PATH. Running with `--no-daemon` works.

**Comment by Siedlerchr** [comment]
Still happens with gradle 8.7 on macOS

**Comment by dvaske** [comment]
I'm having the same problem when the gradle daemon is started from IntelliJ with java 21, then the executables can't be found. When the gradle daemon is started from the terminal everything works fine, probably due to PATH is "correct"
A workaround (for me at least) is to update _system/user_ path with `usr/local/bin`:
`sudo launchctl config user path /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin`

**Comment by aav7fl** [comment]
> I'm having the same problem when the gradle daemon is started from IntelliJ with java 21, then the executables can't be found. When the gradle daemon is started from the terminal everything works fine, probably due to PATH is "correct" A workaround (for me at least) is to update _system/user_ path with `usr/local/bin`: `sudo launchctl config user path /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin`

I have a similar issue with Java 21 inside Intellij with Gradle where it can't access a docker credential binary in the `/usr/local/bin`, but updating the `system/user` did not seem to resolve it for me. (Confirmed that I tried rebooting the machine).

Were there any other workarounds that you tried, or is it possible that our Intellij instances aren't being run with the same user?

**Comment by tagae** [comment]
Dear Gradle team: this issue has way wider impact than [you might be realising](https://github.com/gradle/gradle/issues/10483#issuecomment-1517503382). Many people are having to overcome this problem in not-so-great ways. The worst consequence is that IntelliJ's integration with Gradle becomes unusable for a wide variety of tasks: anything that needs Docker credentials such as building images, running `helm`, and other similar utilities. So we all have to come back to the command line to execute our Gradle commands with daemons disabled. If not launched from the IDE, it becomes hard to debug whatever we launch as a Gradle task.

**Comment by big-guy** [comment]
related https://github.com/gradle/gradle/issues/28110

**Comment by big-guy** [comment]
This is a real problem that needs to be addressed holistically. 

Some ideas:
- Treat `PATH` as a compatibility criteria for Gradle daemons. This would mean we would start more daemons.
- Resolve paths to executables via `PATH` ourselves. This would mean we'd start executables with absolute paths. This means we need to re-implement what the JDK does when spawning a new process.
- Resolve path by jumping through another process/script that does not cache PATH. This would mean we could rely on the OS to interpret the PATH. But this requires a trampoline process that needs to be maintained by us. 
- Require absolute paths (for completeness)

**Comment by mhsmith** [comment]
Note that on macOS at least, this affects not only PATH, but *all* environment variables (#12905).

**Comment by big-guy** [comment]
@mhsmith I don't see that with newer versions of Gradle.  I can reproduce it with 6.5.

Putting this in build.gradle:
```
println "ENV_VAR=" + System.env.ENV_VAR
```
And running with Java 11 and Java 17 and Gradle 8.4, I see changes to ENV_VAR reflected in the build without restarting the daemon, even in child processes spawned by the Gradle daemon.

**Comment by tagae** [comment]
@big-guy I only observe this problem on Java 21. Java 17 works fine (on macOS).

**Comment by big-guy** [comment]
@tagae Are you referring to problems with PATH or any environment variable?

Using macOS, Java 21.0.1, 8.8-rc-1, I have this in a build.gradle:
```
println "ENV_VAR=" + System.env.ENV_VAR

project.exec { 
   commandLine "env"
}
```

I then run:
```
./gradlew --stop
export ENV_VAR=foo
./gradlew help | grep ENV_VAR
export ENV_VAR=bar
./gradlew help | grep ENV_VAR
```
I see the value of ENV_VAR change from foo to bar within the Gradle process and in the forked (env) process. I think that means that the environment variables are passed along correctly. 

If I change the value of PATH, that will also appear to change, but the JVM won't honor it when using ProcessBuilder.

**Comment by tagae** [comment]
@big-guy I was considering only the `PATH` env var (sorry for the noise). With Java 17, Gradle plugins find executables that are in custom PATH locations (say, `$HOME/.local/bin/helm`). With Java 21, those executables are not found. When daemons are disabled, they are found, even with Java 21. This is the behaviour that I have observed.

Of the [ideas you shared](https://github.com/gradle/gradle/issues/10483#issuecomment-2135736533), this seems the simplest:
> Treat PATH as a compatibility criteria for Gradle daemons. This would mean we would start more daemons.

and we would have to live with the inefficiency.

I didn't get this one:
> Require absolute paths (for completeness)

**Comment by big-guy** [comment]
> I was considering only the `PATH` env var (sorry for the noise).

Ah, thanks!  I thought that might be what you meant.

> Of the https://github.com/gradle/gradle/issues/10483#issuecomment-2135736533, this seems the simplest:

The problem with this is that it would pretty much guarantee that the IDE and CLI would never share their daemons, which is something we want to try to do.

> I didn't get this one:

This wasn't a serious suggestion, but basically instead of allowing someone to specify `foo.sh` as an executable for `project.exec` or `Exec` tasks and relying on PATH look-ups, you'd have to specify the absolute path to it (`/path/to/foo.sh`) always.

**Comment by mhsmith** [comment]
>> Note that on macOS at least, this affects not only PATH, but all environment variables (https://github.com/gradle/gradle/issues/12905).
>
> I don't see that with newer versions of Gradle. I can reproduce it with 6.5.
> 
> Putting this in build.gradle:
> 
> ```
> println "ENV_VAR=" + System.env.ENV_VAR
> ```
> 
> And running with Java 11 and Java 17 and Gradle 8.4, I see changes to ENV_VAR reflected in the build without restarting the daemon, even in child processes spawned by the Gradle daemon.

Yes, it looks like you're right. I've tried this with the versions I was using around the time I posted my comment last year: Java 8 and 11, and Gradle 7.2 and 7.4, and I can't reproduce any problem with non-PATH environment variables on macOS. So I guess https://github.com/gradle/gradle/issues/12905#issuecomment-675193289 had been fixed by then.

**Comment by pandradedev** [comment]
@tagae and @big-guy. I also had the same problem using Java 21.0.1 and updating the java version to Java 21.0.2 or 21.0.3 solved my problem and executables are now being found when using the gradle exec task.

**Comment by tagae** [comment]
> Hey @tagae and @big-guy. I also had the same problem using Java 21.0.1 and updating the java version to Java 21.0.2 or 21.0.3 solved my problem and executables are now being found when using the gradle exec task.

Thanks for the tip. Unfortunately doesn't work in my case. This is my current `java -version` output, for which Gradle daemons fail to find executables:
```
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Zulu21.34+19-CA (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Zulu21.34+19-CA (build 21.0.3+9-LTS, mixed mode, sharing)
```

**Comment by crogoz** [comment]
Hi all, 

I am also hitting the same issue as described in this [comment](https://github.com/gradle/gradle/issues/10483#issuecomment-1960432723)
From my observations, the task fails on **_Macos_**, when running **_exec_** tasks with **_Java21_** through **_Intellij_** (the gradle daemon is started using `Intellij` which doesn’t have the full `PATH` env variable set). Spinning the Gradle daemon from commandLine (instead of Intellij), it makes the task successful. 

Example of such a task: 
```
tasks.register("execTask", Exec) {
    setCommandLine("docker")
    environment("PATH", System.getenv()) //same failure if I don't set the PATH
}
```
- `docker` is located at `/usr/local/bin` on mac. 
- Inspecting the env variable of the `Gradle Daemon JVM` using `Azul mission control` yields: `PATH=/usr/bin:/bin:/usr/sbin:/sbin` (I think this is inherited from Intellij process), The same value is shown for both `Java21` and `Java20`:
```
Environment Variables:
PATH=/usr/bin:/bin:/usr/sbin:/sbin
SHELL=/bin/bash
LC_CTYPE=
TMPDIR=/var/folders/zc/.../T/

Active Locale:
LC_ALL=C
LC_COLLATE=C
LC_CTYPE=C
LC_MESSAGES=C
LC_MONETARY=C
LC_NUMERIC=C
LC_TIME=C
```
- Looking into the implementation of the [Exec task](https://github.com/gradle/gradle/blob/1130e5f58eb8de48b42033902ac8f19eba56f7c5/subprojects/core/src/main/java/org/gradle/process/internal/ProcessBuilderFactory.java#L36-L38), Gradle is doing an `environment.clear()` and an `environment.set()`. So, I tried to reproduce this directly in a task that simply runs a `ProcessBuilder`. What I observed is: 
    -  **fails**  with `docker` is not found when I change _anything_ related to the `environment()` (_clearing_ the environment, _adding_ a dummy environment variable, _changing_ the “PATH” env variable, etc.)
    - **succeeds** when  _not_ changing the environment at all
 ```
    tasks.register("processBuilderTask") {
     doFirst {
        println(System.getenv())
        ProcessBuilder processBuilder = new ProcessBuilder();
        processBuilder.command("docker"); // located in: /usr/local/bin on mac
        processBuilder.inheritIO();
        // commenting the 2 lines below, makes the task successful
        // basically any change to the environment will lead to "docker" Cause: error=2, No such file or directory
        processBuilder.environment().clear();
        processBuilder.environment().put("PATH", "/usr/local/bin");
        processBuilder.start();
     }
  }
```
- I was not able to reproduce the issue outside of gradle. eg. this code is successful: https://github.com/palantir/gradle-jdks/pull/477/files#diff-5b641a26ec5523337253cd58d566385b90d0794a36fee6c25e8dc70ca5da92fdR48 

I’ve reproduced the issue here: https://github.com/palantir/gradle-jdks/pull/477/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R64 (see execTask and processBuilderTask)
* Use Java21 for Gradle JVM 
* Make sure that you run `./gradlew --stop` to stop the current daemons before running the tasks via Intellij

Any ideas how to proceed with the investigation further ?

**Comment by yyy33** [comment]
I will say that as a newbie, I fumbled around for a whole day before realizing this, and was almost desperate during that time

**Comment by crogoz** [comment]
hey @mlopatkin and @big-guy did you get the chance to look over the investigation in https://github.com/gradle/gradle/issues/10483#issuecomment-2507620705 ? 

re: https://github.com/gradle/gradle/issues/10483#issuecomment-879184153. Are there any plans to implement one of the fixes suggested in this comment ? Thanks!

**Comment by luongvo** [comment]
I'm facing the same issue where the Gradle command detects the default Ruby version 2.6, while I'm setting it 3.4.6 from the zsh using asdf.

<img width="1092" height="845" alt="Image" src="https://github.com/user-attachments/assets/27acbde7-9bed-4a21-9826-bee346eadf85" />

**Comment by patricklucas** [comment]
I've been working around this issue in one way or another for a few years now, it would be very appreciated to see some movement on it.

It's particularly acute if you need to support both UNIXy OSs as well as Windows. In that case, I've had to put together a relatively complex provider chain that invokes either `which` or `where.exe` depending on the OS in order to discover a target executable's absolute path for use in a subsequent exec.

**Comment by crogoz** [comment]
hey, in case it helps we have implemented a workaround for this issue [here](https://github.com/palantir/better-exec/blob/develop/better-exec/src/main/java/com/palantir/gradle/betterexec/BetterExecAction.java#L150-L197). We are using this library (usage [here](https://github.com/palantir/better-exec/tree/develop?tab=readme-ov-file#usage)) to execute commands.

**Comment by diegourban** [comment]
I have bumped into a similar issue.

The trigger for me was IntelliJ: it started Gradle daemon with the minimal PATH. Than `EstablishBuildEnvironment` patches `System.getenv("PATH")` in the JVM, but that change never get to the OS-level `environ` array that native process uses to resolve command names. 

So Exec tasks fail with "command not found" even though `System.getenv("PATH")` contains the right directory.

I added a contained MRE: 
https://github.com/diegourban/gradle-exec-path-mre (see README.md with steps to reproduce)
