### ISSUE TITLE
java.lang.OutOfMemoryError: Metaspace while running plugin tests on Travis CI

### ISSUE THREAD

**Issue by martinbonnin** [gradle/gradle#10527]
Following https://github.com/gradle/gradle/issues/8354#issuecomment-529666227, a more detailed description of the problem:

This error happens systematically on Travis CI (works fine on my machine) when running the apollo-gradle-plugin-incubating tests:
```
./gradlew :apollo-gradle-plugin-incubating:test
```
After ~10min the tests fail (full logs at https://travis-ci.org/apollographql/apollo-android/builds/582181815):
```    
com.apollographql.apollo.gradle.KotlinDSLTests > project configures correctly and generates something FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in /home/travis/build/apollographql/apollo-android/apollo-gradle-plugin-incubating/build/testProject with arguments [generateApolloClasses, --stacktrace]
    Output:
    Daemon will be stopped at the end of the build after running out of JVM memory
    FAILURE: Build failed with an exception.
    * What went wrong:
    A problem occurred configuring root project 'testProject'.
    > Could not open cache directory 5pj9vcbz7mfs0olb6tql927ze (/tmp/.gradle-test-kit-travis/caches/5.6/gradle-kotlin-dsl/5pj9vcbz7mfs0olb6tql927ze).
       > Metaspace

[...]

Caused by: java.lang.OutOfMemoryError: Metaspace
    	at org.jetbrains.kotlin.com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:105)
    	at org.jetbrains.kotlin.com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:162)
    	at org.jetbrains.kotlin.com.intellij.openapi.util.Disposer.dispose(Disposer.java:129)
    	at org.jetbrains.kotlin.com.intellij.openapi.util.Disposer.dispose(Disposer.java:125)
    	at org.gradle.kotlin.dsl.support.KotlinCompilerKt.compileToDirectory(KotlinCompiler.kt:624)
    	at org.gradle.kotlin.dsl.codegen.ApiExtensionsJarKt.compileKotlinApiExtensionsTo(ApiExtensionsJar.kt:113)
    	at org.gradle.kotlin.dsl.codegen.ApiExtensionsJarKt.compileKotlinApiExtensionsTo$default(ApiExtensionsJar.kt:130)
    	at org.gradle.kotlin.dsl.codegen.ApiExtensionsJarGenerator.compileExtensionsTo(ApiExtensionsJar.kt:64)
    	at org.gradle.kotlin.dsl.codegen.ApiExtensionsJarGenerator.generate(ApiExtensionsJar.kt:52)
    	at org.gradle.kotlin.dsl.codegen.ApiExtensionsJarKt.generateApiExtensionsJar(ApiExtensionsJar.kt:39)
```

The history of what I tried (Xmx4096m, -XX:MaxMetaspaceSize=512m, oraclejdk vs openjdk) is there: https://github.com/apollographql/apollo-android/pull/1577/commits

Most of the red crosses are MetaSpace OOMs except the 3 first ones which were a different issue. This commit for an example, should have the error: https://github.com/apollographql/apollo-android/pull/1577/commits/040770a5b3c686861a87d109975097c2029f49b7

Ultimately, I was able to make the tests pass by splitting them in 2 gradle invocations but that doesn't sound super robust: https://github.com/apollographql/apollo-android/pull/1577/commits/5ccdae8dbbff7cb64d556e8491b44741aaabcda8

The plugin tests use the `GradleRunner` APIs to run on 34 test projects. Most of them use groovy buildscripts but the one who fails uses `build.gradle.kts` kotlin buildscripts, that might be a lead.

**Comment by martinbonnin** [comment]
Build scan there: https://scans.gradle.com/s/vgoygq6oiacsy/

**Comment by martinbonnin** [comment]
Hi Stale Bot 👋 . Can we keep this one open a bit more? Finding the root of the MetaSpace error would allow to keep the daemon alive longer and have tests run faster

**Comment by big-andy-coates** [comment]
I'm seeing the `OutOfMemoryError: Metaspace` when running tests for a custom plugin on our build servers (AWS CodeBuild).  Maybe the same thing.

**Comment by utsav0209** [comment]
@martinbonnin I am facing a similar issue with sonarqube. Have you found any workaround or root cause for this?

**Comment by martinbonnin** [comment]
@utsav0209 I ended up increasing the Java heap and metaspace:

https://github.com/apollographql/apollo-android/blob/59bc9ca38ea9bc4b9fbe2b01ba8f4d38340c260a/apollo-gradle-plugin/src/test/kotlin/com/apollographql/apollo3/gradle/util/TestUtils.kt#L31

**Comment by hql1991** [comment]
Saw this in a gradle project too. Upgrading from gradle 2.13 to 6.5 and such java metaspace error happen. Sometimes also complain heap exhausted.

Sus: saw Xmx Xms both set to 64m, but that shouldn't affect metaspace, it's in native memory...

**Comment by dsaff** [comment]
Just keeping this alive, saw this just today consistently on just the 8th invocation of GradleRunner, all fairly simple projects with build.gradle

**Comment by vlsi** [comment]
@martinbonnin , I see you attempted [increasing metaspace](https://github.com/gradle/gradle/issues/10527#issuecomment-887704062) via `gradle.properties`, however, it does not help me. Do you know if it really helped you?

What worked for me was casing `GradleRunner` to `org.gradle.testkit.runner.internal.DefaultGradleRunner` and adding metaspace:

```
this as DefaultGradleRunner
withJvmArguments("-XX:MaxMetaspaceSize=1g")
```

**Comment by martinbonnin** [comment]
> Do you know if it really helped you?

I think it did ? I'm not 100% certain TBH but I haven't had any issue in a while now so I'm not really eager to open this pandora box... 
FWIW, the `gradle.properties` is in the project under test so I'm assuming the `GradleRunner` will be able to pick this one up too so it's technically equivalent to your commit. But since this not always reproducible, it's hard to tell for sure.

**Comment by vlsi** [comment]
> the gradle.properties is in the project under test so I'm assuming the GradleRunner will be able to pick this one up too so it's technically equivalent to your commit

I tried creating `gradle.properties` in project under test, and it did not work for me for unknown reason.

**Comment by martinbonnin** [comment]
Thank for the update! I removed the `-XX:MaxMetaspaceSize=1g` from `gradle.properties` ([here](https://github.com/apollographql/apollo-kotlin/pull/4403)). I'll report here if the build fails again.

**Comment by ov7a** [comment]
Sorry for the late reply.

Given the last reply, closing this as obsolete. If anyone stumbles across this issue, please open a new issue with a reproducer.

Some related issues:
* https://github.com/gradle/gradle/issues/19750
* https://github.com/gradle/gradle/pull/20054
