### ISSUE TITLE
NullPointerException in `DefaultBuildOutputCleanupRegistry.isOutputOwnedByBuild()`

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#10749]
Originally reported by @seshness in #9174.

### Context
On a large, multi-project gradle build we see some non-deterministic failures in our CI system.

About 1 in every 4 builds fails with this stack trace (on Gradle 4.7 so line numbers differ from master):
```
FAILURE: Build failed with an exception.

* What went wrong:
java.lang.NullPointerException (no error message)

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.NullPointerException
 at org.gradle.internal.cleanup.DefaultBuildOutputCleanupRegistry.isOutputOwnedByBuild(DefaultBuildOutputCleanupRegistry.java:54)
 at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:65)
 at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
 at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
 at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
 at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
 at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
 at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
 at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
 at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
 at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
 at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
 at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
 at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
 at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
 at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
 at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
 at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
 at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:596)
 at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
 at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
 at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
 at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
```

I tried adding a log line and building with a custom build:
```
logger.info("safeToDelete: {} absoluteFile: {}", safeToDelete, absoluteFile);
if (safeToDelete.contains(absoluteFile.getPath())) {
```
and this showed that the `safeToDelete` variable was `null`.
```
safeToDelete: null absoluteFile: <some path>
```

I suspect this comes from the accessor for `resolvedPaths` not being `synchronized`.

**Comment by seshness** [comment]
Thanks @wolfs for taking the time to investigate this! I'm sorry I wasn't able to create an independent, reproducible example at the time. I looked back through our git history and found the workaround we used to alleviate this for us. Our original CI script looked something like
```
./gradlew -Dorg.gradle.parallel=true tasks assemble
```
and this produced the failure with the accompanying stack trace for us, non-deterministically.

We changed that to two separate commands:
```
./gradlew tasks
./gradew -Dorg.gradle.parallel=true assemble
```
and we haven't seen the failure since.

We run `gradle tasks` in our CI builds as a way to ensure all tasks have their inputs properly specified, even if they aren't connected in the task graph to `assemble`.

I know this isn't a build scan, and I'm not able to run against gradle 5.6.2 because I think we still use constructs that are now deprecated, but I hope this helps.

**Comment by wolfs** [comment]
@seshness Can you see if you can reproduce the problem in your build with the Gradle version you are using? Which one is it (4.7?)?

Are you maybe using `Task.execute` in your build?

It would also be helpful to see the stacktraces of the callers of `registerOutputs` and `isOutputOwnedByBuild`. Can you add the logging to a custom Gradle version and then share the results?

**Comment by wolfs** [comment]
@seshness Any news on this?

**Comment by wolfs** [comment]
I'll close this now. @seshness Please re-open if it comes up again.
