### ISSUE TITLE
gradle 5.6.2 Could not determine java version from '12.0.1'.

### ISSUE THREAD

**Issue by dmitry-saritasa** [gradle/gradle#10804]
I am trying to compile latest thrift 0.12.0 and get gradle error

```
code/experiments/thrift-0.12.0 
➜ lib/java/gradlew -version --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '12.0.1'.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.IllegalArgumentException: Could not determine java version from '12.0.1'.
        at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:72)
        at org.gradle.api.JavaVersion.current(JavaVersion.java:82)
        at org.gradle.internal.jvm.UnsupportedJavaRuntimeException.assertUsingVersion(UnsupportedJavaRuntimeException.java:42)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:32)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:257)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:191)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)


* Get more help at https://help.gradle.org

```
```
code/experiments/thrift-0.12.0 
➜ env G JAVA
41:JAVA_HOME=/usr/java/latest

```

when I run ./configure in thrift root folder I get:

```
Java Library:
   Using gradlew ............. : lib/java/gradlew
   Using java ................ : java
   Using javac ............... : javac

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '12.0.1'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
   Using Gradle version ...... : 
   Using java version ........ : java version "12.0.1" 2019-04-16
```

**Installed java packages**

```
➜ _ dnf list installed G java
61:abrt-java-connector.x86_64                        1.1.2-1.fc30                                @updates                        
643:graphviz-java.x86_64                              2.40.1-46.fc30                              @updates                        
849:java-1.8.0-openjdk.x86_64                         1:1.8.0.222.b10-0.fc30                      @updates                        
850:java-1.8.0-openjdk-devel.x86_64                   1:1.8.0.222.b10-0.fc30                      @updates                        
851:java-1.8.0-openjdk-headless.x86_64                1:1.8.0.222.b10-0.fc30                      @updates                        
852:java-11-openjdk-headless.x86_64                   1:11.0.4.11-0.fc30                          @updates                        
853:java-latest-openjdk-headless.x86_64               1:12.0.2.9-1.rolling.fc30                   @updates                        
854:java-openjdk-headless.x86_64                      1:12.0.0.33-4.rolling.fc30                  @updates                        
855:javapackages-filesystem.noarch                    5.3.0-4.fc30                                @fedora                         
856:javapackages-tools.noarch                         5.3.0-4.fc30                                @fedora                         
2601:tzdata-java.noarch
```

**Comment by ljacomet** [comment]
> Using Gradle version ...... : 

Is suspicious in not reporting a Gradle version.

Could you add the output of `.gradlew -version` on your machine?
My first guess would be that you have a Linux distribution packaged version of Gradle which is usually a rebuilt version with selected patches and not something that matches the official Gradle releases.

In addition, when looking at the [thrift repo gradle wrapper](https://github.com/apache/thrift/blob/master/lib/java/gradle/wrapper/gradle-wrapper.properties) I see they are still using `5.1.1` which was not Java 12 compatible. You need at least Gradle 5.4.

**Comment by big-guy** [comment]
I agree with Louis, this looks like the version of Gradle distributed with Fedora.

You can get our official releases from https://gradle.org/install/
