### ISSUE TITLE
DuplicateFileCopyingException for certain dependencies in gradle 6.0 current build

### ISSUE THREAD

**Issue by urferr** [gradle/gradle#10814]
### Summary
I use gradle 6.0 disribution snapshot build 20190919220024+0000 for trying to build our application with Java 13. Certain dependencies can not be resolved because tey fail with the followinf error:

Could not expand ZIP 'D:\Java\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpclient\4.3.6\4c47155e3e6c9a41a28db36680b828ced53b8af4\httpclient-4.3.6.jar'.
.
.
Caused by: org.gradle.api.file.DuplicateFileCopyingException: Encountered duplicate path "META-INF/DEPENDENCIES" during copy operation configured with DuplicatesStrategy.FAIL
        at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator$1$1.processFile(DuplicateHandlingCopyActionDecorator.java:56)
        at org.gradle.api.internal.file.copy.CopyFileVisitorImpl.processFile(CopyFileVisitorImpl.java:64)
        at org.gradle.api.internal.file.copy.CopyFileVisitorImpl.visitFile(CopyFileVisitorImpl.java:48)
        at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTreeImpl$1.visitFile(AbstractFileTree.java:208)
        at org.gradle.api.internal.file.archive.ZipFileTree.visit(ZipFileTree.java:98)

### Expected Behavior
with gradle 5.6.2 the problem did not happen.

### Steps to Reproduce 
It happens in a large multi module build, but unfortunately after breaken it down into a small test project it works fine

### Your Environment
Build scan URL: https://gradle.com/s/qgw53dgwkk2co

**Comment by ljacomet** [comment]
This is indeed an expected breaking change in Gradle 6.0, triggered by security risks associated with the older behaviour. See #10039 and related issues.

**Comment by urferr** [comment]
But what is duplicated in this case? When i open the jar in the gradle cache the path "META-INF/DEPENDENCIES" only exists once. Also this is a thirdparty from maven central, nothing i have under control. 
And as i mentioned, if i create a simple gradle project having this dependency the project can be built. The problem only occurs in context of a large multi module build.
Is there a way to switch this new check off because now i completly stuck testing the build of out application with JDK13?
