### ISSUE TITLE
Print meaningful project name/filename in stacktraces instead of "build.gradle.kts"

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#10823]
### Expected Behavior

Stacktrace should provide enough information to figure out which `build.gradle` is present in the stacktrace.

Note: I know I can customize build script name, however customized file names do confuse tooling (e.g. shell scripts like https://github.com/dougborg/gdub), and it looks like Gradle could provide enough debug information, so custom script naming is not required.

### Current Behavior

Note how `Build_gradle.<init>(build.gradle.kts:60)` provides no clue to the file that failed.

Some suggestions: `build.gradle.kts` could include path relative to `$rootDir`.
`Build_gradle` could be `Build_$projectPath`

```
* Exception is:
java.lang.IllegalStateException: asdf
        at Build_gradle.<init>(build.gradle.kts:60)
        at Program.execute(Unknown Source)
        at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.eval(Interpreter.kt:506)
        at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.evaluateSecondStageOf(Interpreter.kt:422)
        at Program.execute(Unknown Source)
        at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.eval(Interpreter.kt:506)
        at org.gradle.kotlin.dsl.execution.Interpreter.eval(Interpreter.kt:206)
        at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator.evaluate(Kotl
```

### Context

Exceptions in multi-module Gradle projects make it complicated to understand what really failed.

**Comment by big-guy** [comment]
👎 I don't think the stack trace is the right place to encode this information.  This should be visible whether or not a user uses --stacktrace. 

We already decorate the failure with location information if we have it, so just before the "Exception" section there should be a "Where" section.  If not, we should fix this.

It does look like we do something slightly different between the Kotlin and Groovy DSLs.   Exceptions originating from Groovy build scripts include the absolute path to the file while Kotlin only includes the base name.

If you have suggestions for how we could make the end-of-build output easier to understand, that would be appreciated.

**Comment by vlsi** [comment]
@big-guy , would you please clarify why do you intend to make stacktraces unreadable?

I happen to have some code in `build.gradle.kts` files, and it is really not that fun to find which of them failed with `property not set` or `NPE` or `ClassCastException`.

Stacktrace does have information like `class name`, `method name` and `file name`, and it makes little sense to obscure it by always putting `build.gradle.kts` there.

**Comment by vlsi** [comment]
>I don't think the stack trace is the right place to encode this information. This should be visible whether or not a user uses --stacktrace.

Let me please clarify: I do not suggest to use stacktrace as the only source of that information.
It is great that in many cases one can identify the root cause without `--stacktrace`. However, if `--stacktrace` is used, then it would be so much better if the stacktrace in question was helpful rather than "guess which build.gradle script is in question".

**Comment by Vampire** [comment]
@big-guy please consider reopening this issue, it is really annoying.

If you have 50 projects and all have build script name build.gradle.kts and there is some exception, the exception stack trace always only contains the plain name. This makes it very hard to determine in which actual file the problem is and navigating from the stack trace most likely leads to the wrong file. The same for debugging the script if you have a breakpoint or navigate in the stack frames you are often taken to the wrong file.

Renaming the build script names is the only viable work-around.
I usually do that anyway except for the root build script but it is still unnice, especially if you work with other peoples builds where you are not allowed to change that.

**Comment by big-guy** [comment]
from Rodrigo...
> I think that’s how the Kotlin compiler encodes the source information in the bytecode.
> Just a simple name for scripts.
> Given that we cache compiled Kotlin scripts, we would need to do like we do for Groovy scripts, and rewrite the compiled script bytecode to rebase all source location information.

**Comment by vlsi** [comment]
This is still needed

**Comment by ov7a** [comment]
Sorry for the late reply.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

**Comment by tresat** [comment]
> 👎 I don't think the stack trace is the right place to encode this information. This should be visible whether or not a user uses --stacktrace.

I agree with @vlsi here.  Whether or not this information is encoded elsewhere is a separate question.  Every other class listed in the stack trace contains functioning clickable links that navigate to the source.  The build script elements should also be clickable links that work the same way.  This is a UX issue.  See https://github.com/gradle/gradle/issues/32276 for an example.
