### ISSUE TITLE
java-test-fixtures plugin causes classes to be present on the test classpath twice

### ISSUE THREAD

**Issue by esz** [gradle/gradle#10872]
### Expected Behavior
The fact of applying the `java-test-fixtures` plugin to my project, should not cause classes of my project's `sourceSets.main` to be present on the test-classpath twice.

### Current Behavior

When `java-test-fixtures` is applied to a project, classes from `sourceSets.main` are present on the test-classpath twice. Within `src/test/java` the code snippet

```
List<URL> urlList = Collections.list(MyTest.class.getClassLoader().getResources("at/myorg/MyClassInMainSources.class"));
		urlList.forEach(System.out::println);
```
yields

* `file:/.../testfixtures/build/classes/java/main/at/myorg/MyClassInMainSources.class`
* `jar:file:/.../testfixtures/build/libs/testfixtures.jar!/at/myorg/MyClassInMainSources.class`

### Context

We're using `java-test-fixtures` in one of our (spring-boot + hibernate) projects, where `sourceSets.main` contains implementations of `javax.persistence.AttributeConverter`:

```
@javax.persistence.Converter
public class MySuperAwesomeConverter implements AttributeConverter<A, B> {
...
}
```
It seems like the behavior described above causes `AttributeConverters` to be registered twice during initialization of the persistence provider in our integration tests:
```
Caused by: org.hibernate.AssertionFailure: AttributeConverter class [class com.acme.MySuperAwesomeConverter ] registered multiple times
	at org.hibernate.boot.model.convert.internal.AttributeConverterManager.addConverter(AttributeConverterManager.java:48)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.addAttributeConverter(InFlightMetadataCollectorImpl.java:403)
	at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl$AttributeConverterManager.addAttributeConverter(AnnotationMetadataSourceProcessorImpl.java:333)
	at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.categorizeAnnotatedClass(AnnotationMetadataSourceProcessorImpl.java:119)
	at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.<init>(AnnotationMetadataSourceProcessorImpl.java:106)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.<init>(MetadataBuildingProcess.java:156)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:150)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:904)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:935)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:57)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:390)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:377)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774)
	... 103 more
```
If we remove the `java-test-fixtures` plugin the problem disappears.

### Steps to Reproduce 

I created a minimal example which reproduces the problem. Please have a look at [esz/testfixtures](https://github.com/esz/testfixtures)

### Your Environment
Gradle 5.6.2

**Comment by ljacomet** [comment]
Thanks for the report.

There is indeed a duplication caused by the way the resolution result of `testRuntimeClasspath` is combined with the main `sourceSet.output`. The first one already contains the later one when the `java-test-fixtures` plugin is applied as the `test-fixtures` depends by default on the main sources.

**Comment by melix** [comment]
As a workaround you can configure the `test` class this way:

```
test {
   classpath = configurations.testRuntimeClasspath + sourceSets.test.output
}
```

**Comment by deanhiller** [comment]
Hmmmm, this broke some build.gradle code we were using 'I think'.  We had something like this in each build.gradle file(sometimes for src/main/java and sometimes for src/test/java) -> 

`sourceSets {
    test {
        resources {
            //This ADDS src/main/java/**/*.html and we still read in src/test/resources/**
            srcDirs = ["src/test/java", "src/test/resources"]
            excludes = ["**/*.java"]
        }
    }
}`

IDEALLY, we just want the plugin we have to add to the test runtime path so the tests can read the 'not compiled' *.html files for when in test mode of development server (vs. production mode which tests on top of compiled html->groovy-> *.class files).   

I see this line in JavaTestFixturesPlugin

        // Overwrite what the Java plugin defines for test, in order to avoid duplicate classes
        // see gradle/gradle#10872
        ConfigurationContainer configurations = project.getConfigurations();
        testSourceSet.setCompileClasspath(project.getObjects().fileCollection().from(configurations.getByName(TEST_COMPILE_CLASSPATH_CONFIGURATION_NAME)));
        testSourceSet.setRuntimeClasspath(project.getObjects().fileCollection().from(testSourceSet.getOutput(), configurations.getByName(TEST_RUNTIME_CLASSPATH_CONFIGURATION_NAME)));

and am wondering if this is what broke our code ?  (obviously fixing some duplicate problem in the process - work that seems pretty useful to not end up with duplicates on classpath).

**Comment by deanhiller** [comment]
I am realizing how blind I really am.  I thought this was a plugin brought in by java plugin like JavaBasePlugin.  we are not even using this plugin :(.   Man, going through gradle code is rough to reverse engineer some of this.

**Comment by hakanai** [comment]
The change done for this one broke this plugin for us, so I have raised that as #19946.
