### ISSUE TITLE
NPE with Gradle 3.3 and Ear task

### ISSUE THREAD

**Issue by SilverJan** [gradle/gradle#1092]
I updated from Gradle 3.1 to 3.3 today and my Ear task is not running properly anymore. An NPE occurs with the following error

    Error while evaluating property 'rootSpec$3.destPath' of task ':earProductionTask'
    > java.lang.NullPointerException (no error message)

See the full stacktrace

	org.gradle.api.InvalidUserDataException: Error while evaluating property 'rootSpec$3.destPath' of task ':earProductionTask'
			at org.gradle.api.internal.tasks.DefaultTaskInputs.getProperties(DefaultTaskInputs.java:176)
			at org.gradle.api.internal.changedetection.rules.InputPropertiesTaskStateChanges.<init>(InputPropertiesTaskStateChanges.java:34)
			at org.gradle.api.internal.changedetection.rules.TaskUpToDateState.<init>(TaskUpToDateState.java:49)
			at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates(DefaultTaskArtifactStateRepository.java:164)
			at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.isUpToDate(DefaultTaskArtifactStateRepository.java:79)
			at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:51)
			at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
			at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
			at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
			at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
			at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
			at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
			at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
			at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
			at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
			at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
			at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
			at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
			at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
			at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
			at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
			at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
			at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
			at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
			at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
			at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
			at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
			at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
			at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
			at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
			at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
			at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:196)
			at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:193)
			at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
			at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
			at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
			at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:193)
			at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
			at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
			at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
			at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
			at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
			at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
			at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
			at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
			at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
			at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
			at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
			at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
			at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
			at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
			at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
			at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
			at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
			at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
			at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
			at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
			at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
			at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
			at org.gradle.util.Swapper.swap(Swapper.java:38)
			at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
			at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
			at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
			at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
			at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
			at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
			at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
			at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
			at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
			at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
			at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
			at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
			at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
			at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	Caused by: java.lang.NullPointerException
			at org.gradle.api.internal.file.copy.DefaultCopySpec$DefaultCopySpecResolver.getDestPath(DefaultCopySpec.java:517)
			at org.gradle.api.tasks.AbstractCopyTask$1$2.call(AbstractCopyTask.java:97)
			at org.gradle.api.tasks.AbstractCopyTask$1$2.call(AbstractCopyTask.java:94)
			at org.gradle.util.GUtil.uncheckedCall(GUtil.java:402)
			at org.gradle.api.internal.tasks.DefaultTaskInputs.prepareValue(DefaultTaskInputs.java:186)
			at org.gradle.api.internal.tasks.DefaultTaskInputs.getProperties(DefaultTaskInputs.java:173)

Maybe this is related to this issue: #1086 

### Expected Behavior

I expect the ear task to be executed like it has been in Gradle 3.1.

### Current Behavior

A NPE occurs.

### Context

This is my task

    tasks.create('earProductionTask', Ear) {
	    from buildWar
	    exclude "${buildWar}/WEB-INF/lib/commons-logging*.jar", "${buildWar}/WEB-INF/lib/log4j*.jar"
	    baseName applicationName
	    version = "${buildVersion}-${buildRevision}"
    }

### Steps to Reproduce (for bugs)

Just execute the task.

### Your Environment

Gradle 3.3 on Windows 10.

**Comment by bmuschko** [comment]
Thanks for reporting. We'll look into it. The issue can be reproduced by just the following code:

    task ear(type: Ear)

I don't see this error if I apply the `ear` plugin. Is there a specific reason for not doing that in your project? Are you creating multiple EAR files per project?

**Comment by bmuschko** [comment]
The issue occurs if the property [`libDirName`](https://docs.gradle.org/current/javadoc/org/gradle/plugins/ear/Ear.html#getLibDirName()) is not set. You can work around the issue by declaring it:

```
task ear(type: Ear) {
    libDirName = 'lib'
}
```

**Comment by SilverJan** [comment]
Thanks for the workaround. I cannot use the ear plugin as I'm creating multiple EAR files.

**Comment by big-guy** [comment]
@SilverJan what do the `application.xml` look like for the EAR files you create with 3.1?  Is the library directory just not set for them?

**Comment by big-guy** [comment]
A fix will be released in 3.4.

As a workaround, you can set `libDirName = 'lib'`.  Even with older versions of Gradle (like 3.2), this task would still have failed if you added any libraries to copy into the libs dir in the ear (e.g., if you did `lib { from("some.war") }`).

**Comment by SilverJan** [comment]
The application.xml has no library-directory value as we use the default lib folder for our libraries.
