### ISSUE TITLE
Multi module fails with FileNotFoundException 

### ISSUE THREAD

**Issue by niqo01** [gradle/gradle#10951]
### Expected Behavior
Build should always succeed.

### Current Behavior
Building fails all the time on CircleCI and sometimes on my laptop with the following exception:
```
Caused by: java.io.UncheckedIOException: Failed to create MD5 hash for file '/home/circleci/social-cats-playground/aws-request-signing/build/classes/java/main' as it does not exist.
	at org.gradle.internal.hash.DefaultFileHasher.hash(DefaultFileHasher.java:38)
	at org.gradle.api.internal.changedetection.state.CachingFileHasher.snapshot(CachingFileHasher.java:83)
	at org.gradle.api.internal.changedetection.state.CachingFileHasher.hash(CachingFileHasher.java:65)
	at org.gradle.api.internal.changedetection.state.SplitFileHasher.hash(SplitFileHasher.java:54)
	at org.gradle.internal.snapshot.FileSystemSnapshotBuilder.addFile(FileSystemSnapshotBuilder.java:51)
	at org.gradle.internal.fingerprint.impl.DefaultFileCollectionSnapshotter$1.visitFile(DefaultFileCollectionSnapshotter.java:90)
	at org.gradle.api.internal.file.collections.AbstractSingletonFileTree.visit(AbstractSingletonFileTree.java:37)
	at org.gradle.api.internal.file.archive.ZipFileTree.visitTreeOrBackingFile(ZipFileTree.java:212)
	at org.gradle.api.internal.file.collections.FileTreeAdapter.visitTreeOrBackingFile(FileTreeAdapter.java:146)
	at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTreeImpl.visitTreeOrBackingFile(AbstractFileTree.java:226)
	at org.gradle.internal.fingerprint.impl.DefaultFileCollectionSnapshotter.snapshotFileTree(DefaultFileCollectionSnapshotter.java:82)
	at org.gradle.internal.fingerprint.impl.DefaultFileCollectionSnapshotter.access$200(DefaultFileCollectionSnapshotter.java:38)
	at org.gradle.internal.fingerprint.impl.DefaultFileCollectionSnapshotter$FileCollectionLeafVisitorImpl.visitGenericFileTree(DefaultFileCollectionSnapshotter.java:67)
	at org.gradle.api.internal.file.AbstractFileTree.visitLeafCollections(AbstractFileTree.java:176)
	at org.gradle.api.internal.file.CompositeFileCollection.visitLeafCollections(CompositeFileCollection.java:205)
	at org.gradle.internal.fingerprint.impl.DefaultFileCollectionSnapshotter.snapshot(DefaultFileCollectionSnapshotter.java:50)
	at org.gradle.internal.fingerprint.impl.AbstractFileCollectionFingerprinter.fingerprint(AbstractFileCollectionFingerprinter.java:46)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.lambda$visitInputFileProperties$0(ExecuteActionsTaskExecuter.java:283)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.lambda$fingerprintInputFiles$3(CaptureStateBeforeExecutionStep.java:154)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.visitInputFileProperties(ExecuteActionsTaskExecuter.java:281)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.fingerprintInputFiles(CaptureStateBeforeExecutionStep.java:150)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.createExecutionState(CaptureStateBeforeExecutionStep.java:114)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:67)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	... 121 more
Caused by: java.io.FileNotFoundException: /home/circleci/social-cats-playground/aws-request-signing/build/classes/java/main (Is a directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.gradle.internal.hash.DefaultFileHasher.hash(DefaultFileHasher.java:36)
```
Full logs here: https://circleci.com/gh/niqo01/social-cats-playground/53

### Context
Simply trying to build a multi module project.

### Steps to Reproduce 
1. Checkout the Github project: https://github.com/niqo01/social-cats-playground
2. Run `./gradlew build -x lint`

Notice that sometimes the build fails with the exception above, re running the same command fix the issue on my laptop. The CIrcleCI setup associated to this open source project fails all the time:
https://circleci.com/gh/niqo01/social-cats-playground/53

### Your Environment
CircleCi build setup available in the same open source project above https://github.com/niqo01/social-cats-playground/blob/master/.circleci/config.yml

My laptop is a Ubuntu 19.04.

**Comment by ljacomet** [comment]
So I did not look at the project, but the error clearly indicates that for some reason the `signing` plugin attempts to sign a class directory instead of a JAR.
Did you by any chance configure something that could explain that?

**Comment by niqo01** [comment]
Not from my knowledge. My module's configurations are relatively straight forward.
I am not too versed in Gradle though, I can't say for sure.
