### ISSUE TITLE
NullPointerException when using empty value in map

### ISSUE THREAD

**Issue by bender316** [gradle/gradle#11036]
### Expected Behavior
I expected that I could use null values (not keys) in a Map used in a task. At least I expected a real error message and not just a NullPointerException with no more information.

### Current Behavior
A NullPointerException is thrown (because of a null access) without any furhter information.

### Steps to Reproduce 
Use the provided gradle project in [gradle-param-bug.zip](https://github.com/gradle/gradle/files/3724808/gradle-param-bug.zip) and run gradle hello

### Your Environment
$ gradle -version
------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.4 (AdoptOpenJDK 11.0.4+11)
OS:           Windows 10 10.0 amd64

**Comment by bender316** [comment]
From my POV it needs to be clarified how null should be handled. Should it be allowed in maps (than the call to isInstance in [ValidatingMapEntryCollector](https://github.com/gradle/gradle/blob/master/subprojects/model-core/src/main/java/org/gradle/api/internal/provider/ValidatingMapEntryCollector.java#L45) is wrong. Or null is not allowed then the error message needs to be extended and the NPE avoided.

**Comment by lptr** [comment]
Here's a build scan reproducing the problem: https://e.grdev.net/s/f5rz6tcgti55g/failure?openFailures=WzBd&openStackTraces=WzFd#top=0

The exception:

```text
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':hello'.Open stacktrace
Caused by: java.lang.NullPointerException: (No message provided)Close stacktrace
at org.gradle.api.internal.provider.ValidatingMapEntryCollector.add(ValidatingMapEntryCollector.java:46)
at org.gradle.api.internal.provider.ValidatingMapEntryCollector.addAll(ValidatingMapEntryCollector.java:55)
at org.gradle.api.internal.provider.MapCollectors$EntriesFromMap.collectInto(MapCollectors.java:189)
at org.gradle.api.internal.provider.MapCollectors$EntriesFromMap.maybeCollectInto(MapCollectors.java:194)
at org.gradle.api.internal.provider.DefaultMapProperty.doGetOrNull(DefaultMapProperty.java:131)
at org.gradle.api.internal.provider.DefaultMapProperty.makeFinal(DefaultMapProperty.java:332)
at org.gradle.api.internal.provider.AbstractProperty.beforeRead(AbstractProperty.java:74)
at org.gradle.api.internal.provider.DefaultMapProperty.isPresent(DefaultMapProperty.java:98)
at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue.call(AbstractNestedRuntimeBeanNode.java:123)
at org.gradle.api.internal.tasks.properties.AbstractValidatingProperty.validate(AbstractValidatingProperty.java:37)
at org.gradle.api.internal.tasks.properties.DefaultTaskProperties.validate(DefaultTaskProperties.java:184)
at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:54)
at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
at org.gradle.api.internal.tasks.execution.StartSnapshotTaskInputsBuildOperationTaskExecuter.execute(StartSnapshotTaskInputsBuildOperationTaskExecuter.java:62)
at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:73)
at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
```

**Comment by lptr** [comment]
We don't handle `null` values in a map in `ValidatingMapEntryCollector`?

**Comment by big-guy** [comment]
I think this is just an oversight.  We don't allow you to add individual entries with null values, so we shouldn't allow you to use a map with null values either.

We might have a similar hole with a map with a provider that returns a map with null values.

@bender316 would you be interested in contributing a fix?

**Comment by kiwi-oss** [comment]
I have stumbled upon this problem myself, so I made a PR to fix it.

I hope that writing this comment reopens the issue, so the maintainers will be aware that the issue persists until the PR is merged.

**Comment by donat** [comment]
Closing as stale.
