### ISSUE TITLE
Investigate unexpected socket disappearance in daemon on Windows

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#1111]
We see unexpected socket disappearances in Tooling API integration tests on Windows. It is not clear if this is a test only issue. 

### Examples of Failing Tests
- https://builds.gradle.org/viewLog.html?buildId=1918412
- https://builds.gradle.org/viewLog.html?buildId=2031840
- https://builds.gradle.org/viewLog.html?buildId=1918412

### Error on Client Side

```
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
    at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
    at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
    at sun.nio.ch.IOUtil.write(IOUtil.java:51)
    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:492)
    at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeWithNonBlockingRetry(SocketConnection.java:259)
```
### Error on Daemon Side

```
Caused by: java.net.SocketException: Socket operation on nonsocket: no further information
	at sun.nio.ch.IOUtil.configureBlocking(Native Method)
	at sun.nio.ch.SocketChannelImpl.implConfigureBlocking(SocketChannelImpl.java:579)
	at java.nio.channels.spi.AbstractSelectableChannel.configureBlocking(AbstractSelectableChannel.java:288)
	at org.gradle.internal.remote.internal.inet.SocketConnection.<init>(SocketConnection.java:56)
```

or 

```
Caused by: java.io.IOException: An operation was attempted on something that is not a socket
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:384)
	at org.gradle.messaging.remote.internal.inet.SocketConnection$SocketInputStream.read(SocketConnection.java:158)
```

or

```
java.io.IOException: An operation was attempted on something that is not a socket
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.gradle.internal.remote.internal.inet.TcpIncomingConnector$Receiver.run(TcpIncomingConnector.java:102)
```

or (Gradle 2.0)

```
java.net.SocketException: Socket operation on nonsocket: getsockname
	at sun.nio.ch.Net.localInetAddress(Native Method)
	at sun.nio.ch.Net.localAddress(Net.java:479)
	at sun.nio.ch.SocketChannelImpl.<init>(SocketChannelImpl.java:133)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:266)
	at org.gradle.messaging.remote.internal.inet.TcpIncomingConnector$Receiver.run(TcpIncomingConnector.java:100)
```

**Comment by jjohannes** [comment]
Retry rules, which can potentially be removed if this issue is fixed in a way that also fixes it when connecting to older Gradle versions:

`ToolingApiSpecification `
https://github.com/gradle/gradle/blob/7e5372d9ca3dfe82247aa41ad42705d405039e96/subprojects/tooling-api/src/testFixtures/groovy/org/gradle/integtests/tooling/fixture/ToolingApiSpecification.groovy#L105-L105

`BaseGradleRunnerIntegrationTest`
https://github.com/gradle/gradle/blob/856fed99ee1b1d5d383b4721811cae7df12ccc8e/subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/BaseGradleRunnerIntegrationTest.groovy#L150

**Comment by eriwen** [comment]
Is this still an issue @jjohannes?

**Comment by jjohannes** [comment]
We always suspected this to be some kind of issue with certain Java versions on Windows as it only appears there. Unfortunately, several hours of investigation have not yielded any results.

We still have the retry rule pointed out above in our tests. Which is ok for cross-version tests with older Gradle versions.

The rule is limited to executing on Java 7 or 8 on Windows. We do not run cross-version tests on Java 9 yet but testing the _current_ Gradle version with Java 9 has not shown this problem so far. Still if it persists on Java 9, it will eventually surfaces again. If not, I think we are good.

Since there has also been no reports from the community that this is an issue outside out test suite I do not believe this is actionable. Closing.
