### ISSUE TITLE
ScalaCompile new task failure

### ISSUE THREAD

**Issue by tnielens** [gradle/gradle#11275]
Run `gradle alternativeScalaCompile` with the following gradle build file with some scala code in the src/main/scala folder.
Gradle version 5.6.4 

```gradle 
plugins {
    id 'scala'
}

group 'bugreport'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

task alternativeScalaCompile(type: ScalaCompile) {
    source = compileScala.source
    destinationDir = compileScala.destinationDir
    classpath = compileScala.classpath
}

dependencies {
    compile "org.scala-lang:scala-library:2.11.12"
}
```

Error:
```
Caused by: java.lang.IllegalStateException: No value has been specified for this provider.
        at org.gradle.api.internal.provider.Providers$1.get(Providers.java:32)
        at org.gradle.api.internal.provider.DefaultPropertyState.get(DefaultPropertyState.java:133)
        at org.gradle.api.internal.provider.AbstractMappingProvider.get(AbstractMappingProvider.java:49)
        at org.gradle.language.scala.tasks.AbstractScalaCompile.configureIncrementalCompilation(AbstractScalaCompile.java:137)
        at org.gradle.language.scala.tasks.AbstractScalaCompile.compile(AbstractScalaCompile.java:102)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:705)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:672)
```

**Comment by ov7a** [comment]
Sorry for the late reply.

This issue is still reproducible with 9.5.1, but the error is slightly better:
```
Execution failed for task ':alternativeScalaCompile' (registered in build file 'build.gradle').
> Cannot query the value of this provider because it has no value available.
  The value of this provider is derived from:
    - task ':alternativeScalaCompile' property 'scalaCompileOptions.incrementalOptions.analysisFile'
```

Scala plugin (`ScalaBasePlugin`) wires `scalaCompileOptions.incrementalOptions.analysisFile`only for the convention `compileScala` task. Hand-created `ScalaCompile` task gets no default → provider empty → `configureIncrementalCompilation` throws when task runs.

As a workaround, you can wire properties manually
```groovy
tasks.register('alternativeScalaCompile', ScalaCompile) {
    source = compileScala.source
    destinationDirectory = compileScala.destinationDirectory
    classpath = compileScala.classpath
    scalaClasspath = compileScala.scalaClasspath
    scalaCompileOptions.incrementalOptions.analysisFile.set(
        layout.buildDirectory.file("tmp/scala/compilerAnalysis/alternativeScalaCompile.analysis"))
    scalaCompileOptions.incrementalOptions.classfileBackupDir.set(
        layout.buildDirectory.file("tmp/scala/classfileBackup/alternativeScalaCompile.bak"))
}
```
