### ISSUE TITLE
Regression when root composite project refers to included builds

### ISSUE THREAD

**Issue by jrodbx** [gradle/gradle#11301]
I have a composite build that has _two separate clones of the same repo_ as included builds.  One is a baseline, the other is an experimental project to test ABI changes using japicmp.  When bumping the gradle-wrapper.properties from 5.6.4 to 6.x, the build fails.

### Expected Behavior
The build should succeed.

### Current Behavior
The build fails with the following message: 
```
Caused by: org.gradle.api.GradleException: Included build /Users/jrod/Development/dcto19-cash-app-baseline has build path :dcto19-cash-app-baseline which is the same as included build /Users/jrod/Development/dcto19-cash-app-baseline
```
### Context

Stops working as of 6.0-rc-3.
Works with 5.6.4

My builds no longer work

### Steps to Reproduce 
1) Clone this repository twice: https://github.com/Egorand/dcto19-cash-app
one named `dcto19-cash-app-baseline`
the other named `dcto19-cash-app-latest`
2) then clone this repository: https://github.com/jrodbx/DroidconToronto2019Prep
at the same level as the other two directories
3) cd into root dir from #2
4) run `./gradlew kcompare:japicmp --console=plain --rerun-tasks --stacktrace --no-build-cache`.  Build should pass.
5) Change japicmp/gradle/wrapper/gradle-wrapper.properties from gradle-5.6.4-bin.zip to gradle-6.0-rc-3-bin.zip
6) Run #4 again.  Build should fail.

### Your Environment
Passing Build scan URL: https://scans.gradle.com/s/nc5emsh4tleac
Failing Build scan URL: https://scans.gradle.com/s/4tqc7bef6tzyq

**Comment by big-guy** [comment]
I believe you're being caught up by this in some way:
https://docs.gradle.org/current/userguide/upgrading_version_5.html#changes_to_build_and_task_names_in_composite_builds

It looks like previous versions of Gradle allowed the `GradleBuild` task to sneak in duplicate builds in the composite. That's why this error says dcto19-cash-app-latest is being included twice.

I'm a little confused by your example and what you're trying to do with the combination of included builds and GradleBuilds.  The build in DroidconToronto2019Prep/japicmp includes both dcto19-cash-app-latest and dcto19-cash-app-baseline as included builds, but it doesn't seem like it actually uses either of them as included builds.  Instead, it uses the GradleBuild task to run particular tasks from those builds.

I think you could replace the GradleBuild tasks with:
```
def compileBaseline = tasks.register("compileBaseline") {
    dependsOn gradle.includedBuild("dcto19-cash-app-baseline").task(":app:writeAppDebugProjectJarFiles")
}
def compileLatest = tasks.register("compileLatest") {
    dependsOn gradle.includedBuild("dcto19-cash-app-latest").task(":app:writeAppDebugProjectJarFiles")
}
```
Or you could do something through dependency management, but I think this is going to be difficult because we won't be able to choose between the two included builds (they both produce the same publications).

Would that work for you?

**Comment by ijuma** [comment]
We ran into a similar issue in our attempt to upgrade Apache Kafka to Gradle 6.0.1:

> Included build /Users/mkumar/workspace/kafka has build path :kafka which is the same as included build /Users/mkumar/workspace/kafka

https://github.com/apache/kafka/pull/7677#issuecomment-557761348

We create new `GradleBuild` tasks to support multiple Scala versions. For example, a developer can run `jarAll` to run `jar` for each supported Scala version with a single command.

@big-guy Any suggestions on how to fix this?

**Comment by denis111** [comment]
The same here with 6.0.1 with custom GradleBuild task
```gradle
tasks.register('customTask', GradleBuild) {
  doFirst {
    ...
  }
  dir = project.projectDir
  startParameter.projectProperties = ...
  ...
}
```
Included build in /home/user/project/subproject has name 'subproject' which is the same as a project of the main build.
Worked fine in 5.x.

**Comment by jrodbx** [comment]
@big-guy 

> I'm a little confused by your...

Ah, I see what you mean.  I think I was just writing some bad Gradle -- I had thought the `includeBuild` directive in `settings.gradle` was needed in order for the `GradleBuild` task to work. Consequently, I also wasn't aware of `gradle.includedBuild`.  Thanks for clarifying!

> I think you could replace...

Indeed, this worked.

**Comment by ijuma** [comment]
@big-guy I see that this has been bumped to Gradle 6.2. Would you be able to comment on whether we are using Gradle incorrectly in Kafka (https://github.com/gradle/gradle/issues/11301#issuecomment-557943783) or if there is an actual bug in Gradle that will be fixed at some point?

Since Gradle 6.0 is required for Java 13 support, it's not ideal that Kafka is stuck with Gradle 5.x at this point.

**Comment by ijuma** [comment]
Looks like this has been bumped to 6.3. I guess we should assume that the new behavior is here to stay.

**Comment by denis111** [comment]
@big-guy Why it's removed from milestone but the issue is not closed? Should we finally assume that the new behavior is here to stay?

**Comment by kojilin** [comment]
Curious if this is the same issue.
There is the same error message when running the task with GradleBuild type,If there is a module directory name that is the same as another directory in the root project. 
"example-multi/foo/bar has name 'bar' which is the same as a project of the main build."

Example project is 
https://github.com/kojilin/example-multi/blob/master/foo/bar/build.gradle#L18

Gradle 5.x doesn't have this problem.

**Comment by kojilin** [comment]
Curious if this will be fixed or become correct behavior. Looks like multimodule project has same restriction like composite build.

**Comment by michelau** [comment]
The restriction makes little sense in my context.  I have two separate subprojects in a multi-project build that each create a GradleBuild of the same name, and it won't allow this.  Why do they share a namespace?

`Included build /workspace/abc/solutions/x/deployment/build/tmp/createXxx has build path :createParametersXxx which is the same as included build /workspace/abc/solutions/y/deployment/build/tmp/createParametersXxx`

**Comment by mikey-t** [comment]
I have a situation that's possibly similar to what's been mentioned by @kojilin and @michelau . I have included modules with duplicate names. As mentioned by @big-guy , this link mentions specifying an included build's name: [https://docs.gradle.org/current/userguide/upgrading_version_5.html#changes_to_build_and_task_names_in_composite_builds](https://docs.gradle.org/current/userguide/upgrading_version_5.html#changes_to_build_and_task_names_in_composite_builds)

So with a monorepo with similarly "shaped" multi-projects where each project is developed separately but references other project's sub-modules:

```
/project-a
    /service
    /model
    /client
/project-b
    /service
    /model
    /client
/project-c
    /service
    /model
    /client
```
project-a:service can reference it's own model/client modules and the model/client module from project-b using includeBuild and specifying the name to be something else (project-a settings.gradle):

```
include 'service', 'model', 'client'
includeBuild('../project-b/model') {
    name = 'model-b'
    dependencySubstitution {
        substitute module('org.example.projectb:model-b') with project(':')
    }
}
```

This works. However, if you try to include both project-b AND project-c model modules, gradle will sync ok but the compile java task will result in an error like this:

```
Included build /my/path/mono-test/project-c/model has build path :model which is the same as included build
```
I don't know if this is actually related to the posted issue, but it seems related. If this is completely the wrong way to handle my situation, I'd be super grateful if someone pointed me to the right way to do this.

**Comment by renatoathaydes** [comment]
This is also causing my build to fail. Like other people in this thread, I run a separate build multiple times using different properties on each run (this is usually done because Gradle can't handle properties changing during a single build - specially when that affects tool versions being used).

Here's approximately what I am trying to do, from a project A:

* run task b in a separate project B (has its own settings.gradle) using properties P.
* run task b in B again, this time with properties Q.

This actually works until I add this:

* run task c in the parent of B, which happens to be in the parent folder of A (but is not included by B's `settings.gradle`, and as I mentioned, `A` has its own settings.gradle file). Why should this fail with this error?

**Comment by adrian-skybaker** [comment]
So far I've been able to workaround this by assigning the name explicitly as mentioned in some earlier comments:

```gradle
includeBuild ("blue/client") { name = "blue-client" }
includeBuild ("red/client") ( name = "red-client" }
```

But when adding nested composite builds to the mix (abc includes xyz , and xyz includes blue/client and red/client), unfortunately this unique name doesn't seem to propagate to the IntellIiJ idea plugin, and you get an exception like:

```
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin 'org.gradle.idea'.
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:173)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:137)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.lambda$applyPlugins$0(DefaultPluginRequestApplicator.java:129)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:185)
        ... 147 more
Caused by: java.lang.IllegalArgumentException: Duplicate root element abc-client
        at org.gradle.plugins.ide.internal.configurer.HierarchicalElementDeduplicator$StatefulDeduplicator.deduplicate(HierarchicalElementDeduplicator.java:135)
        at org.gradle.plugins.ide.internal.configurer.HierarchicalElementDeduplicator$StatefulDeduplicator.calculateNewNames(HierarchicalElementDeduplicator.java:104)
        at org.gradle.plugins.ide.internal.configurer.HierarchicalElementDeduplicator$StatefulDeduplicator.getNewNames(HierarchicalElementDeduplicator.java:91)
        at org.gradle.plugins.ide.internal.configurer.HierarchicalElementDeduplicator$StatefulDeduplicator.access$100(HierarchicalElementDeduplicator.java:73)
```

I guess at this point there's no option other than trying to name every leaf project with a globally unique name.
