### ISSUE TITLE
java.io.IOException: No locks available

### ISSUE THREAD

**Issue by tapatio** [gradle/gradle#1133]
I am building a project. I receive this exception during the build. I have RWX privileges for cache.properties.lock. 

### Expected Behavior

I expect locks to be available. I should not see this exception.

### Current Behavior

I am unable to lock this file.

`gradle build --debug` output:

14:25:34.050 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':jar'
14:25:34.059 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':jar' is up-to-date
14:25:34.061 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on task history cache (/home/XXXXX/.gradle/2.13/taskArtifacts).
14:25:34.063 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':jar'
14:25:34.064 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :jar (Thread[main,5,main]) completed. Took 0.014 secs.
14:25:34.064 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 0.024 secs, idle: 0.002 secs
14:25:34.070 [ERROR] [org.gradle.BuildExceptionReporter] 
14:25:34.070 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
14:25:34.070 [ERROR] [org.gradle.BuildExceptionReporter] 
14:25:34.070 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
14:25:34.070 [ERROR] [org.gradle.BuildExceptionReporter] java.io.IOException: No locks available
14:25:34.070 [ERROR] [org.gradle.BuildExceptionReporter] > No locks available
14:25:34.070 [ERROR] [org.gradle.BuildExceptionReporter] 
14:25:34.070 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
14:25:34.070 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
14:25:34.070 [LIFECYCLE] [org.gradle.BuildResultLogger] 
14:25:34.070 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
14:25:34.071 [LIFECYCLE] [org.gradle.BuildResultLogger] 
14:25:34.071 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 5.568 secs
14:25:34.074 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache task history cache (/home/XXXXX/.gradle/2.13/taskArtifacts) was closed 0 times.
14:25:34.075 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
14:25:34.075 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
14:25:34.075 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.ResolutionResultsStoreFactory] Deleted 2 resolution results binary files in 0.0 secs
14:25:34.075 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedRepositoryFactory] In-memory dependency metadata cache closed. Repos cached: 28, cache instances: 3, modules served from cache: 411, artifacts: 161
14:25:34.075 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Generated Gradle JARs cache (/tmp/caches/2.13/generated-gradle-jars) was closed 0 times.
14:25:34.076 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-metadata.bin (/tmp/caches/modules-2/metadata-2.16/module-metadata.bin)
14:25:34.076 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache artifact-at-repository.bin (/tmp/caches/modules-2/metadata-2.16/artifact-at-repository.bin)
14:25:34.076 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on artifact cache (/tmp/caches/modules-2).
14:25:34.076 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Plugin Resolution Cache (/tmp/caches/2.13/plugin-resolution) was closed 0 times.
14:25:34.077 [DEBUG] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonManager] Stopping 0 compiler daemon(s).
14:25:34.077 [INFO] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonManager] Stopped 0 compiler daemon(s).
[XXXXX]# 

### Context

I cannot build my project.

### Your Environment

RHEL 7.3
OpenJDK 1.8
Gradle 2.13

**Comment by big-guy** [comment]
You seem to have GRADLE_USER_HOME set to `/tmp` and permissions there are causing problems.

**Comment by tapatio** [comment]
Thanks for the prompt reply!

I set GRADLE_USER_HOME to the root directory of my Gradle install and I'm still getting the same error:

[XXXXX-rhel7 YYYYY]# echo $GRADLE_USER_HOME
/root/.sdkman/candidates/gradle/
[XXXXX-rhel7 YYYYY]# gradle build
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar

FAILURE: Build failed with an exception.

* What went wrong:
java.io.IOException: No locks available
> No locks available

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.796 secs

Any other ideas?

**Comment by big-guy** [comment]
Hmm... could you run that again with `--debug` and see if you see these sorts of messages again:

> 14:25:34.075 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Generated Gradle JARs cache (/tmp/caches/2.13/generated-gradle-jars) was closed 0 times.
> 14:25:34.076 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-metadata.bin (/tmp/caches/modules-2/metadata-2.16/module-metadata.bin)
> 14:25:34.076 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache artifact-at-repository.bin (/tmp/caches/modules-2/metadata-2.16/artifact-at-repository.bin)
> 14:25:34.076 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on artifact cache (/tmp/caches/modules-2).
> 14:25:34.076 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Plugin Resolution Cache (/tmp/caches/2.13/plugin-resolution) was closed 0 times.

I'm looking to see if those paths reflect your new GRADLE_USER_HOME.

And could you run with `-s` to get a full stacktrace?

Thanks!

**Comment by tapatio** [comment]
`gradle --debug build` output:

16:25:43.080 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':jar'
16:25:43.088 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':jar' is up-to-date
16:25:43.095 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on task history cache (/home/WWWWW/XXXXX.ZZZZZ/dev/LLLLL-apps/.gradle/2.13/taskArtifacts).
16:25:43.099 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':jar'
16:25:43.099 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :jar (Thread[main,5,main]) completed. Took 0.019 secs.
16:25:43.099 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 0.057 secs, idle: 0.001 secs
16:25:43.105 [ERROR] [org.gradle.BuildExceptionReporter] 
16:25:43.105 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
16:25:43.105 [ERROR] [org.gradle.BuildExceptionReporter] 
16:25:43.105 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
16:25:43.105 [ERROR] [org.gradle.BuildExceptionReporter] java.io.IOException: No locks available
16:25:43.105 [ERROR] [org.gradle.BuildExceptionReporter] > No locks available
16:25:43.105 [ERROR] [org.gradle.BuildExceptionReporter] 
16:25:43.105 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
16:25:43.105 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
16:25:43.106 [LIFECYCLE] [org.gradle.BuildResultLogger] 
16:25:43.106 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
16:25:43.106 [LIFECYCLE] [org.gradle.BuildResultLogger] 
16:25:43.106 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 7.706 secs
16:25:43.111 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache task history cache (/home/WWWWW/XXXXX.ZZZZZ/dev/LLLLL-apps/.gradle/2.13/taskArtifacts) was closed 0 times.
16:25:43.112 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
16:25:43.112 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
16:25:43.112 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.ResolutionResultsStoreFactory] Deleted 2 resolution results binary files in 0.001 secs
16:25:43.112 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedRepositoryFactory] In-memory dependency metadata cache closed. Repos cached: 28, cache instances: 3, modules served from cache: 411, artifacts: 161
16:25:43.112 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Generated Gradle JARs cache (/root/.sdkman/candidates/gradle/caches/2.13/generated-gradle-jars) was closed 0 times.
16:25:43.113 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache artifact-at-repository.bin (/root/.sdkman/candidates/gradle/caches/modules-2/metadata-2.16/artifact-at-repository.bin)
16:25:43.113 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-metadata.bin (/root/.sdkman/candidates/gradle/caches/modules-2/metadata-2.16/module-metadata.bin)
16:25:43.113 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on artifact cache (/root/.sdkman/candidates/gradle/caches/modules-2).
16:25:43.114 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Plugin Resolution Cache (/root/.sdkman/candidates/gradle/caches/2.13/plugin-resolution) was closed 0 times.
16:25:43.114 [DEBUG] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonManager] Stopping 0 compiler daemon(s).
16:25:43.114 [INFO] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonManager] Stopped 0 compiler daemon(s).

`gradle -s build` output:

[root@WWWWW-rhel7 XXXXX-apps]# gradle -s build
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar

FAILURE: Build failed with an exception.

* What went wrong:
java.io.IOException: No locks available
> No locks available

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.UncheckedIOException: java.io.IOException: No locks available
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:43)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:83)
	at org.gradle.cache.internal.DefaultCacheAccess.onStartWork(DefaultCacheAccess.java:349)
	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:187)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:102)
	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.useCache(DefaultCacheFactory.java:183)
	at org.gradle.api.internal.changedetection.state.DefaultTaskArtifactStateCacheAccess.useCache(DefaultTaskArtifactStateCacheAccess.java:56)
	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.loadHistory(CacheBackedTaskHistoryRepository.java:99)
	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.getHistory(CacheBackedTaskHistoryRepository.java:45)
	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository.getStateFor(DefaultTaskArtifactStateRepository.java:57)
	at org.gradle.api.internal.changedetection.changes.ShortCircuitTaskArtifactStateRepository.getStateFor(ShortCircuitTaskArtifactStateRepository.java:47)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:241)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:214)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:207)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: java.io.IOException: No locks available
	at org.gradle.cache.internal.filelock.LockStateAccess.tryLock(LockStateAccess.java:83)
	at org.gradle.cache.internal.filelock.LockFileAccess.tryLockState(LockFileAccess.java:83)
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.lockStateRegion(DefaultFileLockManager.java:312)
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.lock(DefaultFileLockManager.java:255)
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.<init>(DefaultFileLockManager.java:127)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:80)
	... 64 more


BUILD FAILED

Total time: 4.917 secs

**Comment by big-guy** [comment]
Ah, it's in the project's `.gradle/` directory...

Is `/home/XXXXX/.gradle/2.13/taskArtifacts` on a NFS mount?  Do you have a nfslock daemon running?

**Comment by tapatio** [comment]
Well, I think you may have found the issue. I started the nfslock daemon and this is the status:

[root@LLLLL-rhel7 ZZZZZ-apps]# service nfslock status
Redirecting to /bin/systemctl status  nfslock.service
● rpc-statd.service - NFS status monitor for NFSv2/3 locking.
   Loaded: loaded (/usr/lib/systemd/system/rpc-statd.service; static; vendor preset: disabled)
   Active: active (running) since Mon 2017-01-09 16:46:48 PST; 4min 56s ago
  Process: 10610 ExecStart=/usr/sbin/rpc.statd --no-notify $STATDARGS (code=exited, status=0/SUCCESS)
 Main PID: 10612 (rpc.statd)
   CGroup: /system.slice/rpc-statd.service
           └─10612 /usr/sbin/rpc.statd --no-notify

Jan 09 16:46:48 LLLLL-rhel7 rpc.statd[10612]: Version 1.3.0 starting
Jan 09 16:46:48 LLLLL-rhel7 rpc.statd[10612]: Flags: TI-RPC
Jan 09 16:46:48 LLLLL-rhel7 rpc.statd[10612]: Failed to create listener xprt (statd, 1, udp6)
Jan 09 16:46:48 LLLLL-rhel7 rpc.statd[10612]: Failed to create listener xprt (statd, 1, tcp6)

**Comment by tapatio** [comment]
I moved my dev directory off the NFS and to a local file system and now I am able to compile! Thanks for your help.
