### ISSUE TITLE
GenerateDebugRFile task fails in Gradle 6.0: "java.nio.charset.MalformedInputException: Input length = 1"

### ISSUE THREAD

**Issue by alixwar** [gradle/gradle#11381]
Building my project using Gradle 6.0 fails due to an exception that is hard to troubleshoot.

### Expected Behavior
Building my project should succeed

### Current Behavior
Building my project fails due to `java.nio.charset.MalformedInputException: Input length = 1`

### Context
Building the project with Gradle 5.6.3 and 5.6.4 works fine.

### Steps to Reproduce 
TBD. What is relevant here? I cannot give you the source code as it is proprietary but I can post snippets.
Log: [11381.log](https://github.com/gradle/gradle/files/3850800/11381.log)

### Your Environment
Android Gradle Plugin 3.5.2
Gradle 6.0

**Comment by alixwar** [comment]
[11381.log](https://github.com/gradle/gradle/files/3850800/11381.log)

**Comment by blindpirate** [comment]
Hi @alixwar thanks for reporting. Reading the stacktrace, it's clear that Android Gradle Plugin is reading some non-UTF8 file with the UTF-8 encoding: 

```
Caused by: java.io.UncheckedIOException: java.nio.charset.MalformedInputException: Input length = 1
        at com.android.ide.common.symbols.SymbolIo.readWithPackage(SymbolIo.java:205)
```

[SymbolIo.readWithPackage() method](https://android.googlesource.com/platform/tools/base/+/studio-master-dev/sdk-common/src/main/java/com/android/ide/common/symbols/SymbolIo.java#202)

I think something in `C:\Users\alix\.gradle\caches\modules-2\files-2.1\com.alix\my-library-android-core\1.0.0-SNAPSHOT\1e91652dc410fd990240c145641e67678750cce7\my-library-android-core-1.0.0-SNAPSHOT.aar` is swedish encoding (as I saw the swedish error message `InnehÕllet õr inte tillÕtet i prologen`). I understand this failure on 6.0, but I don't understand why it doesn't fail on 5.6.3/5.6.4. Did you change anything other than Gradle version? Can you share `C:\Users\alix\.gradle\caches\modules-2\files-2.1\com.alix\my-library-android-core\1.0.0-SNAPSHOT\1e91652dc410fd990240c145641e67678750cce7\my-library-android-core-1.0.0-SNAPSHOT.aar` library?

**Comment by alixwar** [comment]
> This looks like your own library, right? Did you accidentally use incorrect encoding?

Yes, this is my library. I have looked inside and could only find ASCII-encoded files except for some certificate files (binary encoded) in the assets folder. That should be OK, right?

> Did you change anything other than Gradle version? Can you share C:\Users\alix\.gradle\caches\modules-2\files-2.1\com.alix\my-library-android-core\1.0.0-SNAPSHOT\1e91652dc410fd990240c145641e67678750cce7\my-library-android-core-1.0.0-SNAPSHOT.aar library?

No. Nothing else. I am bit reluctant to share the code for the reasons that I specified in my first post. But I would gladly answer any questions or post snippets if needed.

**Comment by blindpirate** [comment]
@alixwar I spent some time on this issue but only had confusing discoveries. In your build, AGP seems to be reading binary file (the aar file) as UTF-8 encoded text file, which confused me a lot. Maybe you can try removing confidential code from your project, but it's really hard to investigate it without a minimum reproducible sample.

**Comment by alixwar** [comment]
Hi, sorry for not getting back to you earlier. I found something in the stacktrace (using Gradle 6.0.1) which I find interesting:

`Caused by: com.android.build.gradle.tasks.ResourceException: C:\Users\alix\.gradle\caches\modules-2\files-2.1\com.alix\my-library-android-core\1.0.0-beta01\b0984f17c9aa89b4e26a211a2975ae30396c7c1c\my-library-android-core-1.0.0-beta01.aar: Error: The file name must end with .xml`

**Comment by alixwar** [comment]
The build.gradle file that references the library file (transitively) looks like this:

```
apply plugin: 'com.android.library'

android {
    compileSdkVersion 29

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 29
        versionName getCalculatedVersionName()
    }
    testOptions {
        unitTests.includeAndroidResources = true
        unitTests.all {
            // https://stackoverflow.com/questions/35735085/jacoco-doesnt-work-with-robolectric-tests
            //noinspection GrDeprecatedAPIUsage
            jacoco {
                includeNoLocationClasses = true
            }
        }
    }
    lintOptions {
        abortOnError false
    }
    testOptions {
        unitTests.returnDefaultValues = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildTypes {
        release {
            debuggable false
        }
        debug {
            debuggable true
        }
    }
}

dependencies {
    testImplementation 'androidx.test:monitor:1.2.0'
    testImplementation 'org.robolectric:robolectric:4.2.1'
    testImplementation 'org.hamcrest:hamcrest-core:2.2'
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.mockito:mockito-core:3.1.0'
    testImplementation 'com.alix.android:common-test:2.5.0@aar'
    testImplementation 'com.alix.android:testutil:0.7.0@aar'
    testImplementation 'nl.jqno.equalsverifier:equalsverifier:2.5.1'
    api('com.alix:my-library-android:1.0.0-beta01@aar') {
        transitive = true
    }
    api('com.alix:my-library-android-usb:1.0.0-beta01@aar') {
        transitive = true
    }
    implementation 'org.apache.commons:commons-lang3:3.9'
    implementation 'org.apache.commons:commons-collections4:4.4'
    implementation 'com.alix:common-util:2.6.0@aar'
    implementation 'androidx.appcompat:appcompat:1.1.0'
}

```

**Comment by alixwar** [comment]
Here is a screenshot of the content of `my-library-android-core.aar`. 

<img width="1158" alt="my-library-android-core" src="https://user-images.githubusercontent.com/5415786/69240267-62e1f280-0b9c-11ea-80e1-1a1f6c5ec142.png">

**Comment by blindpirate** [comment]
@alixwar What's your AGP version?

**Comment by alixwar** [comment]
> @alixwar What's your AGP version?

3.5.2

**Comment by blindpirate** [comment]
> Hi, sorry @blindpirate for not getting back to you earlier. I found something in the stacktrace (using Gradle 6.0.1) which I find interesting:
> 
> `Caused by: com.android.build.gradle.tasks.ResourceException: C:\Users\alix\.gradle\caches\modules-2\files-2.1\com.alix\my-library-android-core\1.0.0-beta01\b0984f17c9aa89b4e26a211a2975ae30396c7c1c\my-library-android-core-1.0.0-beta01.aar: Error: The file name must end with .xml`

Can I see the full stacktrace of this exception?

**Comment by alixwar** [comment]
Sorry,
had missed this. I seem to have reposted a finding that I have already previously mentioned in this thread. I don't have any news on this unfortunately.

**Comment by gildor** [comment]
@alixwar Do you use `digital.wup.android-maven-publish` plugin for publishing?
Most probably you have this issue because of it and the fact that Gradle 6+ publish Gradle Metadata, see this issue on Android issue tracker for details:
https://issuetracker.google.com/issues/144240061

**Comment by alixwar** [comment]
Hi @gildor ,
actually I was using the maven-publish plugin.

I have since updated AGP to 3.6 and Gradle to 6.2.1 and I can see this when trying to just compile the project:

```
* What went wrong:
Execution failed for task ':domain:generateDebugRFile'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > java.nio.charset.MalformedInputException: Input length = 1

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':domain:generateDebugRFile'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:205)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:203)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
        at org.gradle.workers.internal.DefaultWorkerExecutor$WorkItemExecution.waitForCompletion(DefaultWorkerExecutor.java:334)
        at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForItemsAndGatherFailures(DefaultAsyncWorkTracker.java:142)
        at org.gradle.internal.work.DefaultAsyncWorkTracker.access$000(DefaultAsyncWorkTracker.java:34)
        at org.gradle.internal.work.DefaultAsyncWorkTracker$1.run(DefaultAsyncWorkTracker.java:106)
        at org.gradle.internal.Factories$1.create(Factories.java:26)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withoutLocks(DefaultWorkerLeaseService.java:260)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withoutProjectLock(DefaultWorkerLeaseService.java:171)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withoutProjectLock(DefaultWorkerLeaseService.java:165)
        at org.gradle.internal.work.StopShieldingWorkerLeaseService.withoutProjectLock(StopShieldingWorkerLeaseService.java:95)
        at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForItemsAndGatherFailures(DefaultAsyncWorkTracker.java:102)
        at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForAll(DefaultAsyncWorkTracker.java:80)
        at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForCompletion(DefaultAsyncWorkTracker.java:68)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:576)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:553)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:536)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:276)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:265)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$0(ExecuteStep.java:32)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:32)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:67)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:36)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:153)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:67)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:41)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:192)
        ... 30 more
Caused by: java.io.UncheckedIOException: java.nio.charset.MalformedInputException: Input length = 1
        at com.android.ide.common.symbols.SymbolIo.readWithPackage(SymbolIo.java:231)
        at com.android.ide.common.symbols.SymbolIo.readSymbolListWithPackageName(SymbolIo.java:209)
        at com.android.ide.common.symbols.SymbolUtils.loadDependenciesSymbolTables(SymbolUtils.kt:192)
        at com.android.builder.symbols.SymbolExportUtils.processLibraryMainSymbolTable(SymbolExportUtils.kt:73)
        at com.android.build.gradle.internal.res.GenerateLibraryRFileTask$GenerateLibRFileRunnable.run(GenerateLibraryRFileTask.kt:202)
        at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:348)
        at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:57)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
        at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:198)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
        ... 3 more
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        ... 30 more
```
