### ISSUE TITLE
StackOverflowError in ManagedPropertyName.getDisplayName()

### ISSUE THREAD

**Issue by EtienneMiret** [gradle/gradle#11466]
When using the [Plugin Publishing Plugin][1] in combination with the [FreeFair Lombok Plugin][2], running the `publishPlugins` task throws a StackOverflowError. While this could be an issue within any of those two plugins, I believe the culprit is the [ManagedPropertyName.getDisplayName()][3] gradle method.

### Expected Behavior

My plugin should be published to the Gradle Plugin Portal.

### Current Behavior

The `publishPlugins` task throws a StackOverflowError with the below (shortened) stacktrace:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':publishPlugins'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:187)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:185)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:166)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:374)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:361)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:354)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:340)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.StackOverflowError
        at org.gradle.internal.instantiation.generator.ManagedObjectFactory.attachOwner(ManagedObjectFactory.java:54)
        at io.freefair.gradle.plugins.lombok.LombokExtension_Decorated.getVersion(Unknown Source)
        at io.freefair.gradle.plugins.lombok.LombokExtension.toString(LombokExtension.java:14)
        at org.gradle.internal.instantiation.generator.ManagedObjectFactory$ManagedPropertyName.getDisplayName(ManagedObjectFactory.java:137)
        at org.gradle.internal.instantiation.generator.ManagedObjectFactory$ManagedPropertyName.toString(ManagedObjectFactory.java:126)
        at org.gradle.api.internal.provider.AbstractProperty.toString(AbstractProperty.java:76)
        at io.freefair.gradle.plugins.lombok.LombokExtension.toString(LombokExtension.java:14)
```

### Context

I’m currently authoring a Gradle plugin where I’m using [Lombok][4] to generate boilerplate code. While writing the code, I just had the following dependencies setup, without any Lombok related plugin:

```
dependencies {
	compileOnly 'org.projectlombok:lombok:1.18.10'
	annotationProcessor 'org.projectlombok:lombok:1.18.10'
}
```

However, with this setup, the `javadoc` task failed, as the code it was scanning wasn’t delomboked. So when I wanted to publish my plugin, I switch to using a Lombok plugin, as the `publishPlugins` task depends on the `javadoc` task. Only to get a failure a bit latter.

### Steps to Reproduce 

 1. Check out [EtienneMiret/gradle-StackOverflowError][5] (which is an [MCVE][6]).
 2. Make sure your `~/.gradle/gradle.properties` DO NOT contain any gradle publish secret (you don’t want to publish this dummy plugin by accident) (you just need to comment out the line with your secret if you have one).
 3. Run `./gradlew publishPlugins`.

### Your Environment

```
------------------------------------------------------------
Gradle 6.0.1
------------------------------------------------------------

Build time:   2019-11-18 20:25:01 UTC
Revision:     fad121066a68c4701acd362daf4287a7c309a0f5

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          13 (Oracle Corporation 13+33)
OS:           Mac OS X 10.14.6 x86_64
```

Build scan URL: https://gradle.com/s/lanbe2lqswnnk

### Thoughts

What I understand (I not sure though), is that something is trying to display a `version` property and calls it's `toString()` method. Since it is a "managed property" (whatever that means), the `ManagedPropertyName.getDisplayName()` method is called. This method, in addition of stringifying this property, will stringify this property's owner object by calling the `toString()` method of this owner object. And, as could be expected, the owner object’s `toString()` iterate over all it's properties and call each’s `toString()` method. Causing an infinite loop.

My humble opinion is that it is normal for an object `toString ()` to recursively call `toString ()` on its properties, but that it is not normal for a property `toString ()` to call `toString ()` on its parent object.

[1]: https://plugins.gradle.org/plugin/com.gradle.plugin-publish
[2]: https://plugins.gradle.org/plugin/io.freefair.lombok
[3]: https://github.com/gradle/gradle/blob/v6.0.1/subprojects/model-core/src/main/java/org/gradle/internal/instantiation/generator/ManagedObjectFactory.java#L137
[4]: https://projectlombok.org/
[5]: https://github.com/EtienneMiret/gradle-StackOverflowError
[6]: https://meta.stackoverflow.com/questions/366988/what-does-mcve-mean

**Comment by larsgrefer** [comment]
Adding my two cents here (I'm the maintainer of the FreeFair lombok plugin)

The same issue was raised at our repository: freefair/gradle-plugins#155

I can (and I will) work around this issue by not implementing a `toString()` method in `LombokExtension`, but I think that this is actually a Gradle core issue.

This is (effectively) the current implementation which produces the error but should work fine in my opinion:

```java
public class LombokExtension {
    /**
     * The version of Lombok which will be used.
     */
    private final Property<String> version;
    /**
     * Additional Entries for the lombok.config file.
     */
    private final MapProperty<String, String> config;

    @Inject
    public LombokExtension(ObjectFactory objectFactory) {
        version = objectFactory.property(String.class).convention("1.18.10");
        config = objectFactory.mapProperty(String.class, String.class);
    }

    /**
     * The version of Lombok which will be used.
     */
    public Property<String> getVersion() {
        return this.version;
    }

    /**
     * Additional Entries for the lombok.config file.
     */
    public MapProperty<String, String> getConfig() {
        return this.config;
    }

    @Override
    public boolean equals(final Object o) {
        if (o == this) return true;
        if (!(o instanceof LombokExtension)) return false;
        final LombokExtension other = (LombokExtension) o;
        if (!other.canEqual((Object) this)) return false;
        final Object this$version = this.getVersion();
        final Object other$version = other.getVersion();
        if (this$version == null ? other$version != null : !this$version.equals(other$version)) return false;
        final Object this$config = this.getConfig();
        final Object other$config = other.getConfig();
        if (this$config == null ? other$config != null : !this$config.equals(other$config)) return false;
        return true;
    }

    protected boolean canEqual(final Object other) {
        return other instanceof LombokExtension;
    }

    @Override
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final Object $version = this.getVersion();
        result = result * PRIME + ($version == null ? 43 : $version.hashCode());
        final Object $config = this.getConfig();
        result = result * PRIME + ($config == null ? 43 : $config.hashCode());
        return result;
    }

    @Override
    public String toString() {
        return "LombokExtension(version=" + this.getVersion() + ", config=" + this.getConfig() + ")";
    }
}
```

**Comment by adammurdoch** [comment]
This is fixed via https://github.com/gradle/gradle/pull/12601
