### ISSUE TITLE
Gradle does not unlock executionHistory when trying to run an Exec task

### ISSUE THREAD

**Issue by burdoto** [gradle/gradle#11520]
### Expected Behavior
I tried running `docker-compose` using these custom tasks:
```groovy
task dockerCompose(type: Exec, dependsOn: 'dockerComposePre') {
    executable = 'docker-compose'
    args = ['up', '-d', '--build', '--force-recreate']
}

task dockerComposePre(type: Sync, dependsOn: installDist) {
    from "$buildDir/install/$rootProject.name"
    from "$rootDir/Dockerfile"
    from "/var/bots/$rootProject.name"

    into "$rootDir/docker/"
}
```

### Current Behavior
An OSError gets thrown:
```error
> Task :dockerCompose FAILED
Building cobalton
[3684] Failed to execute script docker-compose
Traceback (most recent call last):
  File "site-packages\docker\utils\build.py", line 97, in create_archive
  File "tarfile.py", line 1980, in addfile
  File "tarfile.py", line 255, in copyfileobj
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 127, in perform_command
  File "compose\cli\main.py", line 1085, in up
  File "compose\cli\main.py", line 1081, in up
  File "compose\project.py", line 527, in up
  File "compose\service.py", line 344, in ensure_image_exists
  File "compose\service.py", line 1084, in build
  File "site-packages\docker\api\build.py", line 159, in build
  File "site-packages\docker\utils\build.py", line 31, in tar
  File "site-packages\docker\utils\build.py", line 100, in create_archive
OSError: Can not read file in context: \\?\D:\Workspaces\Cobalton\.gradle\5.2.1\executionHistory\executionHistory.lock

Execution failed for task ':dockerCompose'.
> Process 'command 'docker-compose'' finished with non-zero exit value -1
```

### Your Environment
- IntelliJ IDEA
- Docker
- Gradle
Build state URL: https://github.com/comroid-git/Cobalton/commit/c21ce9f72249eefaecb4af67cabe479cf51d5abd

**Comment by big-guy** [comment]
I think this is working as intended, we lock that cache during task execution.

It seems a little weird to me that you'd want to include the `.gradle` directory in your docker container, could you add `.gradle` to `.dockerignore`?
