### ISSUE TITLE
CCE When custom Property subclass is used

### ISSUE THREAD

**Issue by aalmiray** [gradle/gradle#11522]
Usage of a custom `Property` subclass results in a CCE when compiling a project. See attached stacktrace

	Caused by: java.lang.ClassCastException: org.kordamp.gradle.PropertyUtils$StringPropertyDecorator cannot be cast to org.gradle.api.internal.tasks.TaskDependencyContainer
	        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue.getTaskDependencies(AbstractNestedRuntimeBeanNode.java:100)
	        at org.gradle.api.internal.tasks.DefaultTaskInputs$6.visitInputProperty(DefaultTaskInputs.java:194)
	        at org.gradle.api.internal.tasks.properties.annotations.InputPropertyAnnotationHandler.visitPropertyValue(InputPropertyAnnotationHandler.java:57)
	        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode.visitProperties(AbstractNestedRuntimeBeanNode.java:59)
	        at org.gradle.api.internal.tasks.properties.bean.RootRuntimeBeanNode.visitNode(RootRuntimeBeanNode.java:32)
	        at org.gradle.api.internal.tasks.properties.DefaultPropertyWalker.visitProperties(DefaultPropertyWalker.java:41)
	        at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:42)
	        at org.gradle.api.internal.tasks.DefaultTaskInputs.visitDependencies(DefaultTaskInputs.java:191)
	        at org.gradle.api.internal.tasks.DefaultTaskDependency.visitDependencies(DefaultTaskDependency.java:99)
	        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:111)
	        at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmptyEdges.getNodeValues(CachingDirectedGraphWalker.java:213)
	        at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:121)
	        at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:73)
	        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:66)

The `StringPropertyDecorator` class attempts to resolve a value from environment/sysprops before any actual value has been set or not (for this reason `convention()` does not work as once a value is set then the custom logic will be omitted). No internal APIs were used on this decorator subclass.

### Expected Behavior
No exception at all.

### Current Behavior
A CCE exception is thrown based on implementation details out of my control. When task dependencies resolution is attempted the following code will be called

	public TaskDependencyContainer getTaskDependencies() {
	    if (this.isProvider()) {
	        return (TaskDependencyContainer)this.valueSupplier.get();
	    }
		...
	}

### Context
It appears that implementation details assume that a ` Provider` can be casted to `TaskDependencyContainer` even thought the latter type is not found in the class hierarchy of the former type.

### Steps to Reproduce 
gist -> https://gist.github.com/aalmiray/194bb6bef491cd02c0c999d75fd1fd47

### Your Environment
------------------------------------------------------------
Gradle 6.0.1
------------------------------------------------------------

Build time:   2019-11-18 20:25:01 UTC
Revision:     fad121066a68c4701acd362daf4287a7c309a0f5

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_222 (AdoptOpenJDK 25.222-b10)
OS:           Mac OS X 10.15.1 x86_64

**Comment by aalmiray** [comment]
If I change `StringPropertyDecorator`so that it implements `TaskDependencyContainer` then I get another error

	Caused by: java.lang.ClassCastException: org.kordamp.gradle.PropertyUtils$StringPropertyDecorator cannot be cast to org.gradle.api.internal.provider.HasConfigurableValueInternal
	        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue.maybeFinalizeValue(AbstractNestedRuntimeBeanNode.java:129)
	        at org.gradle.api.internal.tasks.properties.AbstractValidatingProperty.prepareValue(AbstractValidatingProperty.java:49)
	        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:43)
	        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
	        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	        ... 27 more

**Comment by aalmiray** [comment]
The following gist contains the updated code with workarounds to make it work

   https://gist.github.com/aalmiray/c2a77641c2fa2636d27f18b3093cf63a

Note the usage of internal APIs (yuck).

**Comment by big-guy** [comment]
The Provider and Property interfaces aren't intended to be implemented by users or plugins. 

If I understand what you're trying to do, I think you can get close with this:
```
project.objects.property(String.class).convention(project.providers.provider(() -> {
    String value = System.getenv(envKey);
    if (isBlank(value)) value = System.getProperty(propertyKey);
    return isNotBlank(value) ? value : null;
}));
```

**Comment by aalmiray** [comment]
If I understand how `convention` works, it will provide a value as long as no explicit value has been set on the property, right? Well that's not exactly what I need. I need a property that can determine a value from env/sysprops even if an explicit value has been set on it, that is, env/sysprops have precedence over explicit property value.

@big-guy Can this be done with `convention` and `provider`?

**Comment by eskatos** [comment]
You get conventions right.

For what you need you'd have to use env/sysprop when consuming the property. Doing so as late as at task execution time would work but I suppose you need the overridden value to be treated as an input.

Here's one way to do it:

```groovy
@Internal
Property<String> compartmentId = project.objects.property(String.class)

@Input
Provider<String> conventionalCompartmentId = project.providers.provider {
    String value = System.getenv(envKey)
    if (isBlank(value)) value = System.getProperty(propertyKey)
    return isNotBlank(value) ? value : compartmentId.get()
}
```

Users of your task would configure `compartmentId` but Gradle input snapshotting and your task action would consume `conventionalCompartmentId`.

BTW, beware that the Kotlin compiler doesn't like Groovy traits, make sure to check that you can configure your tasks from Kotlin code.

**Comment by aalmiray** [comment]
Thank you @eskatos. This approach requires an additional provider per property but allows me to let go of internal APIs 😅.

Regarding the usage of traits, they are used in this particular project to define properties and an occasional validating method. Inspecting the generated bytecode of a task with the `VerboseAwareTrait` applied yields

	  public void setVerbose(boolean);
	  public org.gradle.api.provider.Property<java.lang.Boolean> isVerbose();
	  public void org_kordamp_gradle_plugin_oci_tasks_traits_VerboseAwareTraittrait$super$setVerbose(boolean);
	  public org.gradle.api.provider.Property<java.lang.Boolean> org_kordamp_gradle_plugin_oci_tasks_traits_VerboseAwareTraittrait$super$isVerbose();
	  public org.gradle.api.provider.Property<java.lang.Boolean> org_kordamp_gradle_plugin_oci_tasks_traits_VerboseAwareTrait__verbose$get();
	  public org.gradle.api.provider.Property<java.lang.Boolean> org_kordamp_gradle_plugin_oci_tasks_traits_VerboseAwareTrait__verbose$set(org.gradle.api.provider.Property<java.lang.Boolean>);

The first two methods being the ones I expect to see. The others should be adapter/bridge methods that i hope the Kotlin compiler will ignore as there are impl details generated by the Groovy compiler.

Finally, event though https://docs.gradle.org/current/userguide/lazy_configuration.html states that explicit setters should not be used I found no other way to combine properties with `@Option`.
