### ISSUE TITLE
StackOverFlowError during incremental Java compilation with annotation processors

### ISSUE THREAD

**Issue by Sipkab** [gradle/gradle#11559]
The following contains two issues, but I report them in a single issue due to being related to the same codebase. Feel free to create a separate issue for the compilation error part.

### Expected Behavior
1. When recompiling the project the incremental compilation should succeed.
2. The project compilation should succeed.

### Current Behavior
1. The compilation results in a StackOverFlowError
2. The compilation fails.

### Context
I'm trying to compile the project with the included annotation processors:
[annotation-processing-test.zip](https://github.com/gradle/gradle/files/3920953/annotation-processing-test.zip)
The project contains generated files in the `annottestgen` directory. These sources are compiled with the presence of the annotation processors in `processors.jar`. The source for the annotation processors are in `src_processors`, I included a compiled version of them in the JAR.

There are two annotation processors:

`ExtractProcessor`: That extracts an `interface` definition based on the annotated methods. (isolating)
`GroupProcessor`: Creates a group class that aggregates the annotated types. (aggregating)

There's also a commented out part in `testpackage0.TestClass1023` that removes a field definition. The `groups.Group7` class is generated by the `GroupProcessor` in the last round of annotation processing and an appropriate constructor is added to it. However, the compilation fails.

### Steps to Reproduce 
Stackoverflow:
I'm using the `path\to\gradle-6.0.1\bin\gradle.bat compileJava -i --stacktrace` command
1. Compile the project.
2. Add a new line at the start of the `testpackage0.TestClass1023` class.
3. Run the compilation again, and fail with the following stacktrace:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:187)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:185)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:166)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:374)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:361)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:354)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:340)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.StackOverflowError
        at com.google.common.collect.Sets$1.size(Sets.java:669)
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:251)
        at org.gradle.api.internal.tasks.compile.incremental.deps.DependentsSet.dependents(DependentsSet.java:37)
        at org.gradle.api.internal.tasks.compile.incremental.deps.ClassSetAnalysis.getDependents(ClassSetAnalysis.java:169)
        at org.gradle.api.internal.tasks.compile.incremental.deps.ClassSetAnalysis.processDependentClasses(ClassSetAnalysis.java:151)
        at org.gradle.api.internal.tasks.compile.incremental.deps.ClassSetAnalysis.processDependentClasses(ClassSetAnalysis.java:154)
        at org.gradle.api.internal.tasks.compile.incremental.deps.ClassSetAnalysis.processDependentClasses(ClassSetAnalysis.java:154)
        at org.gradle.api.internal.tasks.compile.incremental.deps.ClassSetAnalysis.processDependentClasses(ClassSetAnalysis.java:154)
        at org.gradle.api.internal.tasks.compile.incremental.deps.ClassSetAnalysis.processDependentClasses(ClassSetAnalysis.java:154)
        at org.gradle.api.internal.tasks.compile.incremental.deps.ClassSetAnalysis.processDependentClasses(ClassSetAnalysis.java:154)
...
```

Compilation error:
1. Uncomment the field definition in `testpackage0.TestClass1023`.
2. Compile the project, and fail:

```
annottestgen\testpackage0\TestClass1023.java:7: error: package groups does not exist
        groups.Group7 group = new groups.Group7(this);
              ^
```

It shouldn't, as the generated file at `build\generated\sources\annotationProcessor\java\main\groups\Group7.java` contains an appropriate constructor: `public Group7(testpackage0.TestClass1023 param) { } `.

See the attached archive at Context.

### Your Environment

```
------------------------------------------------------------
Gradle 6.0.1
------------------------------------------------------------

Build time:   2019-11-18 20:25:01 UTC
Revision:     fad121066a68c4701acd362daf4287a7c309a0f5

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_221 (Oracle Corporation 25.221-b11)
OS:           Windows 10 10.0 amd64
```

The bugs are present in 5.1 and 5.6.4 as well.

**Comment by melix** [comment]
Would you mind checking if this still happens with Gradle 6.5 or 6.6? There have been improvements to the incremental compiler and it shouldn't recurse anymore. I've tried your project locally but it's way too slow for a reproducer (45 minutes `compileJava` and still not done)

**Comment by Sipkab** [comment]
The project compiles in 47 seconds when performing clean builds. (5 year old PC, 16GB memory, 4 cores)
I've tried 6.5 and 6.6-rc-1, both failing for incremental build.
The stacktrace is similar, I include it for 6.6-rc-1.

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:208)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:206)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:187)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.execution.plan.DefaultPlanExecutor.process(DefaultPlanExecutor.java:72)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.executeWithServices(DefaultTaskExecutionGraph.java:184)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.execute(DefaultTaskExecutionGraph.java:177)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:39)
        at org.gradle.execution.DefaultBuildWorkExecutor.execute(DefaultBuildWorkExecutor.java:40)
        at org.gradle.execution.DefaultBuildWorkExecutor.access$000(DefaultBuildWorkExecutor.java:24)
        at org.gradle.execution.DefaultBuildWorkExecutor$1.proceed(DefaultBuildWorkExecutor.java:48)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:49)
        at org.gradle.execution.DefaultBuildWorkExecutor.execute(DefaultBuildWorkExecutor.java:40)
        at org.gradle.execution.DefaultBuildWorkExecutor.execute(DefaultBuildWorkExecutor.java:33)
        at org.gradle.execution.IncludedBuildLifecycleBuildWorkExecutor.execute(IncludedBuildLifecycleBuildWorkExecutor.java:36)
        at org.gradle.execution.DeprecateUndefinedBuildWorkExecutor.execute(DeprecateUndefinedBuildWorkExecutor.java:42)
        at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.run(BuildOperationFiringBuildWorkerExecutor.java:57)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:395)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:387)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:84)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor.execute(BuildOperationFiringBuildWorkerExecutor.java:42)
        at org.gradle.initialization.DefaultGradleLauncher.runWork(DefaultGradleLauncher.java:272)
        at org.gradle.initialization.DefaultGradleLauncher.doClassicBuildStages(DefaultGradleLauncher.java:179)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:155)
        at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:131)
        at org.gradle.internal.invocation.GradleBuildController$1.create(GradleBuildController.java:72)
        at org.gradle.internal.invocation.GradleBuildController$1.create(GradleBuildController.java:67)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:180)
        at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:40)
        at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:67)
        at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:56)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:31)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:63)
        at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
        at org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run(FileSystemWatchingBuildActionRunner.java:52)
        at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:41)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:49)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:44)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:44)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:50)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
        at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:87)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:31)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:44)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:87)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:55)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:60)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:38)
        at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:68)
        at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:38)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:37)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:60)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:32)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:56)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:42)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:48)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:32)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:68)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.StackOverflowError
        at org.gradle.api.internal.tasks.compile.incremental.deps.ClassSetAnalysisData.getDependents(ClassSetAnalysisData.java:56)
        at org.gradle.api.internal.tasks.compile.incremental.deps.ClassSetAnalysis.getDependents(ClassSetAnalysis.java:160)
        at org.gradle.api.internal.tasks.compile.incremental.deps.ClassSetAnalysis.processDependentClasses(ClassSetAnalysis.java:151)
        at org.gradle.api.internal.tasks.compile.incremental.deps.ClassSetAnalysis.processDependentClasses(ClassSetAnalysis.java:154)
        at org.gradle.api.internal.tasks.compile.incremental.deps.ClassSetAnalysis.processDependentClasses(ClassSetAnalysis.java:154)
        at org.gradle.api.internal.tasks.compile.incremental.deps.ClassSetAnalysis.processDependentClasses(ClassSetAnalysis.java:154)
        at org.gradle.api.internal.tasks.compile.incremental.deps.ClassSetAnalysis.processDependentClasses(ClassSetAnalysis.java:154)
```

```
------------------------------------------------------------
Gradle 6.6-rc-1
------------------------------------------------------------

Build time:   2020-07-13 13:53:25 UTC
Revision:     1ed79f4fbe18d90df8cb759235804f95a99b30a2

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_221 (Oracle Corporation 25.221-b11)
OS:           Windows 10 10.0 amd64
```

The example project is significantly smaller than the [single-large-project](https://github.com/gradle/performance-comparisons/tree/master/single-large-project) Gradle benchmark project.

> There have been improvements to the incremental compiler and it shouldn't recurse anymore. 

May it have been that the infinite recursion got converted to an infinite loop? That 45 min sure didn't spend all time compiling. I recommend try taking a thread dump after a few minutes to see where it is stuck.

I've tried it with a smaller project (like 100 or 1000 source files), but the bug didn't happen that times. Not sure how it could relate to the size of the project though.

**Comment by melix** [comment]
Thanks @Sipkab . Turns out I was wrong about the recursion. I still don't know why you can compile in seconds while it takes minutes here (on a high end laptop), but I have prepared a branch which might fix your issue. Would you be able to try this out?

https://services.gradle.org/distributions-snapshots/gradle-6.7-branch-cc_jvm_issue_11559-20200716162937+0000-bin.zip

Thanks!

**Comment by Sipkab** [comment]
The StackOverflowError no longer happens. However, the incremental build (just adding the new line) takes 2x amount of time to finish.
Clean build took 50s, incremental took 1m 45s.

The task manager has shown very high kernel activity:
![image](https://user-images.githubusercontent.com/10866741/87701920-f48c1900-c798-11ea-9fb3-c75730f20f1a.png)

I've made two thread dump during the execution. Not sure if that helps, but still. It was run on an SSD and no significant disk activity was shown.

[threaddump-1594919676791.txt](https://github.com/gradle/gradle/files/4933085/threaddump-1594919676791.txt)
[threaddump-1594919693573.txt](https://github.com/gradle/gradle/files/4933086/threaddump-1594919693573.txt)

Hope this helps.

**Comment by melix** [comment]
Thanks, when I profiled your project most of the time was spent in the annotation processor itself, which is a blackbox for me. The repro missed a `settings.gradle` file, which I added. Maybe the repro isn't good?

**Comment by Sipkab** [comment]
The sources for the processors are in the `src_processors` directory. I just precompiled them to avoid complexity of the project.
It works fine without a `settings.gradle` for me. Any test I've run today was by downloading the project again that I've previously uploaded. 
The command line was simply `path/to/gradle/bin/gradle compileJava`, nothing extra. I'm not sure if any user settings in my home directory may interfere, but I didn't change anything there manually.

I go run plain javac just to see how much that takes, and report back in a bit.

**Comment by Sipkab** [comment]
Simply running javac takes approximately the same amount of time for clean build. (45s)

The command line: 

```
javac -d bin -cp processors.jar -processorpath processors.jar -Xlint:processing  annottestgen\testpackage0\*.java annottestgen\testpackage1\*.java annottestgen\testpackage10\*.java annottestgen\testpackage11\*.java annottestgen\testpackage12\*.java annottestgen\testpackage13\*.java annottestgen\testpackage14\*.java annottestgen\testpackage15\*.java annottestgen\testpackage16\*.java annottestgen\testpackage17\*.java annottestgen\testpackage18\*.java annottestgen\testpackage19\*.java annottestgen\testpackage2\*.java annottestgen\testpackage20\*.java annottestgen\testpackage21\*.java annottestgen\testpackage22\*.java annottestgen\testpackage23\*.java annottestgen\testpackage24\*.java annottestgen\testpackage25\*.java annottestgen\testpackage26\*.java annottestgen\testpackage27\*.java annottestgen\testpackage28\*.java annottestgen\testpackage29\*.java annottestgen\testpackage3\*.java annottestgen\testpackage30\*.java annottestgen\testpackage31\*.java annottestgen\testpackage32\*.java annottestgen\testpackage33\*.java annottestgen\testpackage34\*.java annottestgen\testpackage35\*.java annottestgen\testpackage36\*.java annottestgen\testpackage37\*.java annottestgen\testpackage38\*.java annottestgen\testpackage39\*.java annottestgen\testpackage4\*.java annottestgen\testpackage40\*.java annottestgen\testpackage41\*.java annottestgen\testpackage42\*.java annottestgen\testpackage43\*.java annottestgen\testpackage44\*.java annottestgen\testpackage45\*.java annottestgen\testpackage46\*.java annottestgen\testpackage47\*.java annottestgen\testpackage48\*.java annottestgen\testpackage49\*.java annottestgen\testpackage5\*.java annottestgen\testpackage6\*.java annottestgen\testpackage7\*.java annottestgen\testpackage8\*.java annottestgen\testpackage9\*.java
```

However, it's still strange that the incremental build took so much time.

**About the second part of the issue**

The one about the compilation error with the `groups` package not being found. You can disregard it.

The `GroupProcessor` that is part of the project is an aggregating processor that generates new class files based on the types annotated with `GroupBy`. It generates the classes in the last annotation processing round.
I assumed that they should be part of the compiled source set and their types should be visible from the input sources.

Trying it with plain `javac`, this is not true. Somewhy the types generated in the last round are not visible for the input sources? Strange. The above javac command threw the same exception as I mentioned in the original issue, even tried on Java 14 to see if it was some bug in an earlier version.

You can mark this issue as completed if you wish so.

**Comment by melix** [comment]
Ok that's extremely interesting. I switched to JDK 8 and it only took 37s. With JDK 11 it never completes.

**Comment by Sipkab** [comment]
Forgot about build scans. Here they are:

Clean: https://scans.gradle.com/s/bsx6e4gtrtq3c
Incremental: https://scans.gradle.com/s/5osis3c5szyq4
