### ISSUE TITLE
6.0+ NullPointerException when resolving

### ISSUE THREAD

**Issue by dansanduleac** [gradle/gradle#11635]
A repo whose configurations resolved correctly under gradle-6.0-20190910220033+0000 now fails with the below error in:
* 6.0
* 6.0.1
* 6.1-20191021220025

### Expected Behavior

Configurations should resolve correctly.

### Current Behavior

```
org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':conjure-java:compileJava'.
...
Caused by: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':conjure-java-core:compileClasspath'.
...
Caused by: java.lang.NullPointerException
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.SelectorState.hasStrongOpinion(SelectorState.java:345)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.VirtualPlatformState.getForcedVersion(VirtualPlatformState.java:67)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.VirtualPlatformState.isGreaterThanForcedVersion(VirtualPlatformState.java:153)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.selectors.SelectorStateResolverResults.isVersionAllowedByPlatform(SelectorStateResolverResults.java:90)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.selectors.SelectorStateResolver.selectBest(SelectorStateResolver.java:79)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.ModuleResolveState.maybeUpdateSelection(ModuleResolveState.java:372)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.performSelection(DependencyGraphBuilder.java:290)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.performSelectionSerially(DependencyGraphBuilder.java:271)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.resolveEdges(DependencyGraphBuilder.java:247)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.traverseGraph(DependencyGraphBuilder.java:186)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:145)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:123)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolveGraph(DefaultConfigurationResolver.java:175)
	at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveGraph(ShortCircuitEmptyConfigurationResolver.java:86)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:74)
	... 168 more
```

### Context

PR: https://github.com/palantir/conjure-java/pull/669/files
Failure: https://circleci.com/gh/palantir/conjure-java/6597?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

### Additional notes

This error seems to come from the virtual platform alignment logic.
Note that this repo uses [gradle-consistent-versions](https://github.com/palantir/gradle-consistent-versions) which automatically creates virtual platforms around modules matching globs found in versions.props. It then adds require constraints on those virtual platforms to enforce minimum versions.
For example, `com.fasterxml.jackson.*:* = 2.9.9` creates a virtual platform `com.fasterxml.jackson._:_` that captures all components matching the glob, and adds a constraint on it.

This functionality works fine on all other public and internal repos, including on gradle 6.

### Steps to Reproduce 

Upgrade gradle wrapper to 6.0 or 6.0.1

### Your Environment
Build scan URL: https://scans.gradle.com/s/pycj2dg2w6j4w

**Comment by ljacomet** [comment]
There was a basic issue with accessing a nullable field ... fix scheduled for 6.2.
Thanks for the report.
