### ISSUE TITLE
Tooling API versus native run difference

### ISSUE THREAD

**Issue by rnc** [gradle/gradle#11690]
### Expected Behavior

Error messages should be visible through the tooling API

### Current Behavior

When I run a project that uses exec/commandLine and the exec'd external process errors (originaly it was `pkg-config` but is reproducible with e.g. `ls foobar`) then I would expect to see the error message. I **can** see the error if I run Gradle locally but I have (so far) not been able to reveal the error when running through the tooling api.

### Context

I want to use the tooling api to execute the gradle build which allows me to inject 'actions' prior to the model being parsed and built. Secondly, when running a project through IntelliJ this problem of the errors being lost also applies.

### Steps to Reproduce 

Using a sample project e.g.
```

task foo {
    doLast {
        exec {
            commandLine("ls", "foobar")
//            ignoreExitValue(true)
//            commandLine("pkg-config", "--libs", "gtk+-2.0")
        }
        println ("### AFTER COMMAND")
    }
}
```
running locally I get (as expected)
```
 $ gradle foo
> Task :foo FAILED
ls: cannot access 'foobar': No such file or directory

FAILURE: Build failed with an exception.

* Where:
Build file '/home/rnc/Work/Gradle/error-test/build.gradle' line: 10

* What went wrong:
Execution failed for task ':foo'.
> Process 'command 'ls'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

However, if I run the project in IntelliJ I get
```
Build file '/home/rnc/Work/Gradle/error-test/build.gradle' line: 10

Execution failed for task ':foo'.
> Process 'command 'ls'' finished with non-zero exit value 2
```

If I run the project using my CLI (that uses the tooling api ) - see https://github.com/project-ncl/gradle-manipulator/blob/master/cli/src/main/java/org/jboss/gm/cli/Main.java then I get
```
DEBUG o.g.t.i.c.l.DefaultToolingImplementationLoader - Using tooling provider classpath: [/home/rnc/Software/gradle-4.8/lib/annotations-13.0.jar, /home/rnc/Software/gradle-4.8/lib/ant-1.9.11.jar, /home/rnc/Software/gradle-4.8/lib/ant-launcher-1.9.11.jar, /home/rnc/Software/gradle-4.8/lib/asm-6.1.1.jar, /home/rnc/Software/gradle-4.8/lib/asm-analysis-6.1.1.jar, /home/rnc/Software/gradle-4.8/lib/asm-commons-6.1.1.jar, /home/rnc/Software/gradle-4.8/lib/asm-tree-6.1.1.jar, /home/rnc/Software/gradle-4.8/lib/commons-collections-3.2.2.jar, /home/rnc/Software/gradle-4.8/lib/commons-compress-1.14.jar, /home/rnc/Software/gradle-4.8/lib/commons-io-2.4.jar, /home/rnc/Software/gradle-4.8/lib/commons-lang-2.6.jar, /home/rnc/Software/gradle-4.8/lib/fastutil-7.2.1-min.jar, /home/rnc/Software/gradle-4.8/lib/gradle-base-services-4.8.jar, /home/rnc/Software/gradle-4.8/lib/gradle-base-services-groovy-4.8.jar, /home/rnc/Software/gradle-4.8/lib/gradle-build-cache-4.8.jar, /home/rnc/Software/gradle-4.8/lib/gradle-build-option-4.8.jar, /home/rnc/Software/gradle-4.8/lib/gradle-cli-4.8.jar, /home/rnc/Software/gradle-4.8/lib/gradle-core-4.8.jar, /home/rnc/Software/gradle-4.8/lib/gradle-core-api-4.8.jar, /home/rnc/Software/gradle-4.8/lib/gradle-docs-4.8.jar, /home/rnc/Software/gradle-4.8/lib/gradle-installation-beacon-4.8.jar, /home/rnc/Software/gradle-4.8/lib/gradle-jvm-services-4.8.jar, /home/rnc/Software/gradle-4.8/lib/gradle-kotlin-dsl-0.17.5.jar, /home/rnc/Software/gradle-4.8/lib/gradle-kotlin-dsl-provider-plugins-0.17.5.jar, /home/rnc/Software/gradle-4.8/lib/gradle-kotlin-dsl-provider-spi-0.17.5.jar, /home/rnc/Software/gradle-4.8/lib/gradle-kotlin-dsl-tooling-builders-0.17.5.jar, /home/rnc/Software/gradle-4.8/lib/gradle-kotlin-dsl-tooling-models-0.17.5.jar, /home/rnc/Software/gradle-4.8/lib/gradle-launcher-4.8.jar, /home/rnc/Software/gradle-4.8/lib/gradle-logging-4.8.jar, /home/rnc/Software/gradle-4.8/lib/gradle-messaging-4.8.jar, /home/rnc/Software/gradle-4.8/lib/gradle-model-core-4.8.jar, /home/rnc/Software/gradle-4.8/lib/gradle-model-groovy-4.8.jar, /home/rnc/Software/gradle-4.8/lib/gradle-native-4.8.jar, /home/rnc/Software/gradle-4.8/lib/gradle-persistent-cache-4.8.jar, /home/rnc/Software/gradle-4.8/lib/gradle-process-services-4.8.jar, /home/rnc/Software/gradle-4.8/lib/gradle-resources-4.8.jar, /home/rnc/Software/gradle-4.8/lib/gradle-runtime-api-info-4.8.jar, /home/rnc/Software/gradle-4.8/lib/gradle-tooling-api-4.8.jar, /home/rnc/Software/gradle-4.8/lib/gradle-wrapper-4.8.jar, /home/rnc/Software/gradle-4.8/lib/groovy-all-2.4.12.jar, /home/rnc/Software/gradle-4.8/lib/guava-jdk5-17.0.jar, /home/rnc/Software/gradle-4.8/lib/jansi-1.14.jar, /home/rnc/Software/gradle-4.8/lib/javax.inject-1.jar, /home/rnc/Software/gradle-4.8/lib/jcip-annotations-1.0.jar, /home/rnc/Software/gradle-4.8/lib/jcl-over-slf4j-1.7.16.jar, /home/rnc/Software/gradle-4.8/lib/jsr305-2.0.1.jar, /home/rnc/Software/gradle-4.8/lib/jul-to-slf4j-1.7.16.jar, /home/rnc/Software/gradle-4.8/lib/kotlin-compiler-embeddable-1.2.41.jar, /home/rnc/Software/gradle-4.8/lib/kotlin-reflect-1.2.41.jar, /home/rnc/Software/gradle-4.8/lib/kotlin-sam-with-receiver-compiler-plugin-1.2.41.jar, /home/rnc/Software/gradle-4.8/lib/kotlin-script-runtime-1.2.41.jar, /home/rnc/Software/gradle-4.8/lib/kotlin-stdlib-1.2.41.jar, /home/rnc/Software/gradle-4.8/lib/kotlin-stdlib-jdk7-1.2.41.jar, /home/rnc/Software/gradle-4.8/lib/kotlin-stdlib-jdk8-1.2.41.jar, /home/rnc/Software/gradle-4.8/lib/kryo-2.20.jar, /home/rnc/Software/gradle-4.8/lib/log4j-over-slf4j-1.7.16.jar, /home/rnc/Software/gradle-4.8/lib/minlog-1.2.jar, /home/rnc/Software/gradle-4.8/lib/native-platform-0.14.jar, /home/rnc/Software/gradle-4.8/lib/native-platform-freebsd-amd64-libcpp-0.14.jar, /home/rnc/Software/gradle-4.8/lib/native-platform-freebsd-amd64-libstdcpp-0.14.jar, /home/rnc/Software/gradle-4.8/lib/native-platform-freebsd-i386-libcpp-0.14.jar, /home/rnc/Software/gradle-4.8/lib/native-platform-freebsd-i386-libstdcpp-0.14.jar, /home/rnc/Software/gradle-4.8/lib/native-platform-linux-amd64-0.14.jar, /home/rnc/Software/gradle-4.8/lib/native-platform-linux-amd64-ncurses5-0.14.jar, /home/rnc/Software/gradle-4.8/lib/native-platform-linux-amd64-ncurses6-0.14.jar, /home/rnc/Software/gradle-4.8/lib/native-platform-linux-i386-0.14.jar, /home/rnc/Software/gradle-4.8/lib/native-platform-linux-i386-ncurses5-0.14.jar, /home/rnc/Software/gradle-4.8/lib/native-platform-linux-i386-ncurses6-0.14.jar, /home/rnc/Software/gradle-4.8/lib/native-platform-osx-amd64-0.14.jar, /home/rnc/Software/gradle-4.8/lib/native-platform-osx-i386-0.14.jar, /home/rnc/Software/gradle-4.8/lib/native-platform-windows-amd64-0.14.jar, /home/rnc/Software/gradle-4.8/lib/native-platform-windows-i386-0.14.jar, /home/rnc/Software/gradle-4.8/lib/objenesis-1.2.jar, /home/rnc/Software/gradle-4.8/lib/reflectasm-1.07-shaded.jar, /home/rnc/Software/gradle-4.8/lib/slf4j-api-1.7.16.jar, /home/rnc/Software/gradle-4.8/lib/xml-apis-1.4.01.jar]
The client will now receive all logging from the daemon (pid: 2812337). The daemon log file: /home/rnc/.gradle/daemon/4.8/daemon-2812337.out.log
Starting build in new daemon [memory: 5.5 GB]
Closing daemon's stdin at end of input.
The daemon will no longer process any standard input.
Using 8 worker leases.
Starting Build
Settings evaluated using settings file '/home/rnc/Work/Gradle/error-test/settings.gradle'.
Projects loaded. Root project using build file '/home/rnc/Work/Gradle/error-test/build.gradle'.
Included projects: [root project 'error-test']

> Configure project :
Evaluating root project 'error-test' using build file '/home/rnc/Work/Gradle/error-test/build.gradle'.
All projects evaluated.
Selected primary task 'foo' from project :
Tasks to be executed: [task ':foo']
:foo (Thread[Task worker for ':',5,main]) started.

> Task :foo FAILED
Task ':foo' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Starting process 'command 'ls''. Working directory: /home/rnc/Work/Gradle/error-test Command: ls foobar
:foo (Thread[Task worker for ':',5,main]) completed. Took 0.167 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':foo'.
> A problem occurred starting process 'command 'ls''

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':foo'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
....
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'ls''
        at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:231)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:209)
        at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:355)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:85)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        ... 3 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'ls'
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
        at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:67)
        ... 4 more
Caused by: java.io.IOException: Cannot run program "ls" (in directory "/home/rnc/Work/Gradle/error-test"): error=2, No such file or directory
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
        ... 6 more
Caused by: java.io.IOException: error=2, No such file or directory
        ... 7 more
```

In the latter, I do not see `ls: cannot access 'foobar': No such file or directory`. I have tried with various versions (e.g. 5.6.2).

Thanks!

### Your Environment

Build scan URL:

**Comment by rnc** [comment]
I have just tried to replicate this under Gradle 6.0.1 and I get the same results.

**Comment by rnc** [comment]
Given that the same issue appears in IntelliJ it would appear to be a bug in the Tooling API that it is masking error output?

**Comment by rnc** [comment]
This is still valid.

**Comment by mlopatkin** [comment]
Sorry that you're having trouble with Gradle!

Could you please provide a minimal reproducer (with a tooling API launcher too) as a self-contained project in the archive or Github repo? A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it. 

I suspect that there might be two different issues. One is that the IDEA hides the command's output. The other one, as suggested by `IOException` in the stack trace, is that the build cannot find `ls` executable at all. It might be beneficial to log the content of the `PATH` environment variable in the reproducer to track the second problem down.

This issue will be closed after 7 days unless you can provide more information.

**Comment by rnc** [comment]
@mlopatkin Thanks for the reply. Obviously its been a while so I've done further testing on this with a variety of Gradle versions and with my current usage of the tooling API (See below, a rather hacked up extract from my CLI tool referenced above) then while it does print the exception `Caused by: org.gradle.process.internal.ExecException: Process 'command 'ls'' finished with non-zero exit value 2`  it does correctly print in the console output the cause `ls: cannot access 'foobar': No such file or directory` if the setStandardOutput/setStandardError are enabled correctly. 

However I cannot persuade IntelliJ to display that output so my current thought is this is not a bug in Gradle as such but a bug in IntelliJ's _use_ of the Tooling API. So apologies for the noise :-) 

A more reproducible problem (with test case) also related to tooling is https://github.com/gradle/gradle/issues/15269 if you have time please :-) 

```


apply plugin: 'java'
repositories {
    maven { url 'https://repo.gradle.org/gradle/libs-releases' }
}
dependencies {
    implementation "org.gradle:gradle-tooling-api:5.6.4"
    runtimeOnly 'org.slf4j:slf4j-simple:1.7.10'
}
import org.gradle.tooling.*

task foo {
    doLast {
        exec {
            commandLine("ls", "foobar")
//            ignoreExitValue(true)
//            commandLine("pkg-config", "--libs", "gtk+-2.0")
        }
        println ("### AFTER COMMAND")
    }
}
task bar {
    doLast {
        ProjectConnection connection = GradleConnector.newConnector()
                .forProjectDirectory(new File("${rootProject.projectDir}"))
                .useBuildDistribution()
                .connect();

        try {
            BuildLauncher build = connection.newBuild();

            build.forTasks("foo");
            build.setStandardOutput(System.out);
            build.setStandardError(System.err);

            build.run();
        } catch (BuildException e) {
            logger.error("Caught exception running build", e.getCause());
            throw new GradleException(e.toString());
        } finally {
            connection.close();
        }
    }
}
```

**Comment by mlopatkin** [comment]
Thanks for the reply. Sorry that it took us so much time to actually get to this issue. I'm glad you've found at least a partial solution.
As you've mentioned the integration with IDEA is likely out of the scope of the Gradle project so I'm closing this issue then.

I can't promise any timeline for the other issue you've mentioned but it is on our radars.
