### ISSUE TITLE
Failures when building Java web app with gradle 6.0.1

### ISSUE THREAD

**Issue by zx2233** [gradle/gradle#11843]
When I tried [this article](https://guides.gradle.org/building-java-web-applications/) and switch `gradle wrapper --gradle-version = 5.1.1` or `gradle wrapper --gradle-version = 4.10.3`, it works well. But if I use `gradle wrapper --gradle-version = 6.0.1`, an error occurs: `The configuration :runtimeClasspath was resolved from a thread not managed by Gradle.`

**Comment by blindpirate** [comment]
Please ask questions in English. Can you please provide a stacktrace? You can get the stacktrace by adding an extra `-s` to your gradle commands, for example `./gradlew XXX -s`.

**Comment by zx2233** [comment]
Thanks for your reply,It's my error when I use  gradle6.0.1,but 4.10.3 or 5.1.1 is correct,I followed the exercises in this passage,https://guides.gradle.org/building-java-web-applications/.

./gradlew appRun  --stacktrace -info
Initialized native services in: D:\gradle\.gradle\native
The client will now receive all logging from the daemon (pid: 8436). The daemon log file: D:\gradle\.gradle\daemon\6.0.1\daemon-8436.out.log
Starting 38th build in daemon [uptime: 4 hrs 51 mins 55.366 secs, performance: 100%, non-heap usage: 33% of 268.4 MB]
Using 4 worker leases.
Starting Build
Settings evaluated using settings file 'C:\Users\xuan\Desktop\xiaoduo\webdemo\settings.gradle'.
Projects loaded. Root project using build file 'C:\Users\xuan\Desktop\xiaoduo\webdemo\build.gradle'.
Included projects: [root project 'webdemo']

> Configure project :
Evaluating root project 'webdemo' using build file 'C:\Users\xuan\Desktop\xiaoduo\webdemo\build.gradle'.
All projects evaluated.
Selected primary task 'appRun' from project :
Tasks to be executed: [task ':prepareInplaceWebAppFolder', task ':createInplaceWebAppFolder', task ':compileJava', task ':processResources', task ':classes', task ':prepareInplaceWebAppClasses', task ':prepareInplaceWebApp', task ':appRun']
:prepareInplaceWebAppFolder (Thread[Daemon worker Thread 24,5,main]) started.

> Task :prepareInplaceWebAppFolder UP-TO-DATE
Caching disabled for task ':prepareInplaceWebAppFolder' because:
  Build cache is disabled
Skipping task ':prepareInplaceWebAppFolder' as it is up-to-date.
:prepareInplaceWebAppFolder (Thread[Daemon worker Thread 24,5,main]) completed. Took 0.006 secs.
:createInplaceWebAppFolder (Thread[Daemon worker Thread 24,5,main]) started.

> Task :createInplaceWebAppFolder UP-TO-DATE
Caching disabled for task ':createInplaceWebAppFolder' because:
  Build cache is disabled
Skipping task ':createInplaceWebAppFolder' as it is up-to-date.
:createInplaceWebAppFolder (Thread[Daemon worker Thread 24,5,main]) completed. Took 0.0 secs.
:compileJava (Thread[Daemon worker Thread 24,5,main]) started.

> Task :compileJava UP-TO-DATE
Caching disabled for task ':compileJava' because:
  Build cache is disabled
Skipping task ':compileJava' as it is up-to-date.
:compileJava (Thread[Daemon worker Thread 24,5,main]) completed. Took 0.013 secs.
:processResources (Thread[Execution worker for ':',5,main]) started.

> Task :processResources NO-SOURCE
file or directory 'C:\Users\xuan\Desktop\xiaoduo\webdemo\src\main\resources', not found
Skipping task ':processResources' as it has no source files and no previous output files.
:processResources (Thread[Execution worker for ':',5,main]) completed. Took 0.002 secs.
:classes (Thread[Execution worker for ':',5,main]) started.

> Task :classes UP-TO-DATE
Skipping task ':classes' as it has no actions.
:classes (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:prepareInplaceWebAppClasses (Thread[Execution worker for ':',5,main]) started.

> Task :prepareInplaceWebAppClasses UP-TO-DATE
Skipping task ':prepareInplaceWebAppClasses' as it has no actions.
:prepareInplaceWebAppClasses (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:prepareInplaceWebApp (Thread[Execution worker for ':',5,main]) started.

> Task :prepareInplaceWebApp UP-TO-DATE
Skipping task ':prepareInplaceWebApp' as it has no actions.
:prepareInplaceWebApp (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:appRun (Thread[Execution worker for ':',5,main]) started.

> Task :appRun
Caching disabled for task ':appRun' because:
  Build cache is disabled
Task ':appRun' is not up-to-date because:
  Task.upToDateWhen is false.

Exception in thread "Thread-716" java.lang.IllegalStateException: The configuration :runtimeClasspath was resolved from a thread not managed by Gradle.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:580)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$2400(DefaultConfiguration.java:140)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getSelectedArtifacts(DefaultConfiguration.java:1276)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.visitFiles(DefaultConfiguration.java:1267)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:1256)
        at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:97)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.iterator(DefaultConfiguration.java:494)
        at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:405)
        at com.google.common.collect.ImmutableCollection$ArrayBasedBuilder.addAll(ImmutableCollection.java:497)
        at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.java:517)
        at org.gradle.api.internal.file.CompositeFileCollection.getFiles(CompositeFileCollection.java:79)
        at org.gradle.api.internal.file.CompositeFileCollection.getFiles(CompositeFileCollection.java:53)
        at sun.reflect.GeneratedMethodAccessor742.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:76)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:63)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298)
        at org.akhikhl.gretty.scanner.BaseScannerManager.collectScanDirs(BaseScannerManager.groovy:67)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:149)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:100)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:224)
        at org.akhikhl.gretty.scanner.BaseScannerManager.getEffectiveScanDirs(BaseScannerManager.groovy:107)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:160)
        at org.akhikhl.gretty.JettyScannerManager.startScanner(JettyScannerManager.groovy:60)
        at org.akhikhl.gretty.ScannerManager$startScanner.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:82)
        at org.akhikhl.gretty.DefaultLauncher.beforeJavaExec(DefaultLauncher.groovy:52)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:64)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:160)
        at org.akhikhl.gretty.LauncherBase$_launchThread_closure4.doCall(LauncherBase.groovy:240)
        at org.akhikhl.gretty.LauncherBase$_launchThread_closure4.doCall(LauncherBase.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:399)
        at groovy.lang.Closure.run(Closure.java:486)
        at java.lang.Thread.run(Thread.java:745)
<===========--> 87% EXECUTING [4m 13s]
> :appRun

**Comment by blindpirate** [comment]
Issue confirmed. Looking at the stacktrace, it seems liket the community plugin `id 'org.gretty' version '2.2.0'` has some compatibility issues with Gradle 6. You can use `id 'org.gretty' version '3.0.1'` instead. I tested `3.0.1` and it works well.

CC @gradle/build-tool Shall we update the documentation to latest version?

**Comment by zx2233** [comment]
Thanks for your answer. It is very helpful to me
