### ISSUE TITLE
Re-evaluate VFS retention tests after known issues are fixed

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#11850]
When those issues are fixed, we should see what keeps failing with VFS-Retention enabled:
- Fixes for the executor and some individual tests: https://github.com/gradle/gradle/pull/11848
- Support long paths on Windows: https://github.com/gradle/gradle/issues/11832
- Investigate failing play test: https://github.com/gradle/gradle/issues/11849
- File change on macOS not recognized when whole watched directory is removed: https://github.com/gradle/gradle/issues/11833

---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
Looks like now the macOS builds hand on `stopWatching`: https://builds.gradle.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=31155838&_focus=5194

```
[19:49:36][Step 2/5] "Daemon worker" #19 prio=5 os_prio=31 tid=0x00007f900a5cb800 nid=0xa703 runnable [0x000070000e38e000]
[19:49:36][Step 2/5]    java.lang.Thread.State: RUNNABLE
[19:49:36][Step 2/5] 	at net.rubygrapefruit.platform.internal.jni.OsxFileEventFunctions.stopWatching(Native Method)
[19:49:36][Step 2/5] 	at net.rubygrapefruit.platform.internal.jni.OsxFileEventFunctions.access$100(OsxFileEventFunctions.java:26)
[19:49:36][Step 2/5] 	at net.rubygrapefruit.platform.internal.jni.OsxFileEventFunctions$WatcherImpl.stop(OsxFileEventFunctions.java:80)
[19:49:36][Step 2/5] 	at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$AbstractFileWatcher.close(AbstractFileEventFunctions.java:75)
[19:49:36][Step 2/5] 	at org.gradle.internal.vfs.AbstractEventDrivenFileWatcherRegistry.close(AbstractEventDrivenFileWatcherRegistry.java:45)
[19:49:36][Step 2/5] 	at org.gradle.internal.vfs.impl.DefaultWatchingVirtualFileSystem.close(DefaultWatchingVirtualFileSystem.java:111)
[19:49:36][Step 2/5] 	at org.gradle.internal.concurrent.CompositeStoppable$2.stop(CompositeStoppable.java:90)
[19:49:36][Step 2/5] 	at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:106)
[19:49:36][Step 2/5] 	- locked <0x00000007d8cf6e08> (a org.gradle.internal.concurrent.CompositeStoppable)
[19:49:36][Step 2/5] 	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.stop(DefaultServiceRegistry.java:583)
[19:49:36][Step 2/5] 	- locked <0x00000007dfb21368> (a org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService)
[19:49:36][Step 2/5] 	at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:106)
[19:49:36][Step 2/5] 	- locked <0x00000007d8cf6438> (a org.gradle.internal.concurrent.CompositeStoppable)
[19:49:36][Step 2/5] 	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.stop(DefaultServiceRegistry.java:583)
[19:49:36][Step 2/5] 	- locked <0x00000007dfc71ab8> (a org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService)
[19:49:36][Step 2/5] 	at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:106)
[19:49:36][Step 2/5] 	- locked <0x00000007d8cf6388> (a org.gradle.internal.concurrent.CompositeStoppable)
[19:49:36][Step 2/5] 	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.stop(DefaultServiceRegistry.java:583)
[19:49:36][Step 2/5] 	- locked <0x00000007dfc71a38> (a org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService)
[19:49:36][Step 2/5] 	at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:106)
[19:49:36][Step 2/5] 	- locked <0x00000007d8cf62e8> (a org.gradle.internal.concurrent.CompositeStoppable)
[19:49:36][Step 2/5] 	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.stop(DefaultServiceRegistry.java:583)
[19:49:36][Step 2/5] 	- locked <0x00000007dfccb308> (a org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService)
[19:49:36][Step 2/5] 	at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:106)
[19:49:36][Step 2/5] 	- locked <0x00000007dfccce08> (a org.gradle.internal.concurrent.CompositeStoppable)
[19:49:36][Step 2/5] 	at org.gradle.internal.service.DefaultServiceRegistry$OwnServices.stop(DefaultServiceRegistry.java:470)
[19:49:36][Step 2/5] 	at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:106)
[19:49:36][Step 2/5] 	- locked <0x00000007d8cf6188> (a org.gradle.internal.concurrent.CompositeStoppable)
[19:49:36][Step 2/5] 	at org.gradle.internal.service.DefaultServiceRegistry$CompositeServiceProvider.stop(DefaultServiceRegistry.java:962)
[19:49:36][Step 2/5] 	at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:106)
[19:49:36][Step 2/5] 	- locked <0x00000007d8cf60f0> (a org.gradle.internal.concurrent.CompositeStoppable)
[19:49:36][Step 2/5] 	at org.gradle.internal.service.DefaultServiceRegistry.close(DefaultServiceRegistry.java:259)
[19:49:36][Step 2/5] 	at org.gradle.internal.concurrent.CompositeStoppable$2.stop(CompositeStoppable.java:90)
[19:49:36][Step 2/5] 	at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:106)
[19:49:36][Step 2/5] 	- locked <0x00000007d8cf6048> (a org.gradle.internal.concurrent.CompositeStoppable)
[19:49:36][Step 2/5] 	at org.gradle.internal.service.scopes.DefaultGradleUserHomeScopeServiceRegistry.release(DefaultGradleUserHomeScopeServiceRegistry.java:125)
[19:49:36][Step 2/5] 	at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter$1.stop(SessionScopeBuildActionExecuter.java:79)
[19:49:36][Step 2/5] 	at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:106)
[19:49:36][Step 2/5] 	- locked <0x00000007d8cf5f48> (a org.gradle.internal.concurrent.CompositeStoppable)
[19:49:36][Step 2/5] 	at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:81)
[19:49:36][Step 2/5] 	at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:38)
[19:49:36][Step 2/5] 	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:37)
[19:49:36][Step 2/5] 	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:26)
[19:49:36][Step 2/5] 	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
[19:49:36][Step 2/5] 	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
[19:49:36][Step 2/5] 	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:60)
[19:49:36][Step 2/5] 	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:32)
[19:49:36][Step 2/5] 	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
[19:49:36][Step 2/5] 	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:41)
[19:49:36][Step 2/5] 	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:48)
[19:49:36][Step 2/5] 	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:32)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:68)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
[19:49:36][Step 2/5] 	at org.gradle.util.Swapper.swap(Swapper.java:38)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
[19:49:36][Step 2/5] 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
[19:49:36][Step 2/5] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[19:49:36][Step 2/5] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[19:49:36][Step 2/5] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[19:49:36][Step 2/5] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[19:49:36][Step 2/5] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[19:49:36][Step 2/5] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by wolfs** [comment]
On macOS, it seems the daemon crashed: https://builds.gradle.org/viewLog.html?buildId=31155811&buildTypeId=Gradle_Check_VfsRetention_31_bucket6
```
BUILD SUCCESSFUL in 775ms
1 actionable task: 1 executed
Watching 1 directory hierarchies to track changes between builds in 2 directories
Spent 2 ms registering watches for file system events
 
-----
Error:
The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=a43c2cd2-a9d1-40ad-b5ab-29ed982fd07d, currentDir=/Users/tcagent/agent/work/a16b87e0a70f8c6e/subprojects/dependency-management/build/tmp/test files/ComponentMetadataRulesIntegrationTest/changes_made_by_a_r...ot_cached/xtrzo}
```

**Comment by wolfs** [comment]
The remaining problems are:
- Kotlin compiler daemon not starting on Windows due to long path issues https://github.com/gradle/gradle/issues/12184
- Symlinks are not handled https://github.com/gradle/gradle/issues/11851
- Changing files while the build is running https://github.com/gradle/gradle/issues/11837
- Subst on Windows causes problems https://github.com/gradle/gradle/issues/12135

**Comment by wolfs** [comment]
And there is a crash on macOS when running `ArtifactTransformInputArtifactIntegrationTest` https://github.com/gradle/gradle/issues/12219
