### ISSUE TITLE
Gradle Wrapper is behaving weird

### ISSUE THREAD

**Issue by MBurchard** [gradle/gradle#11879]
I've put Gradle 6.0.1 on my computer.
Now there are two ways to initialize the Gradle Wrapper for a new project.

    /opt/gradle/latest/bin/gradle wrapper --gradle-version=6.0.1 --distribution-type=all

This works fine. With `./gradlew -v` the download starts and the version is shown.

The second way is to have the Wrapper task in the _build.gradle_.

	wrapper {
		description "Regenerates the Gradle Wrapper files"
		gradleVersion = '6.0.1'
		distributionUrl = "http://services.gradle.org/distributions/gradle-${gradleVersion}-all.zip"
	}

The initialization then is done by `/opt/gradle/latest/bin/gradle wrapper`.  
But `./gradlew -v` leads to an error.

	./gradlew -v
	Downloading http://services.gradle.org/distributions/gradle-6.0.1-all.zip

	Could not unzip /home/mburchard/.gradle/wrapper/dists/gradle-6.0.1-all/6298f6turtwy8nm2vprrgfznr/gradle-6.0.1-all.zip to /home/mburchard/.gradle/wrapper/dists/gradle-6.0.1-all/6298f6turtwy8nm2vprrgfznr.
	Reason: zip file is empty
	Exception in thread "main" java.util.zip.ZipException: zip file is empty
		at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1535)
		at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1349)
		at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1443)
		at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274)
		at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1237)
		at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
		at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
		at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
		at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
		at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
		at org.gradle.wrapper.Install.unzip(Install.java:235)
		at org.gradle.wrapper.Install.access$900(Install.java:27)
		at org.gradle.wrapper.Install$1.call(Install.java:81)
		at org.gradle.wrapper.Install$1.call(Install.java:48)
		at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
		at org.gradle.wrapper.Install.createDist(Install.java:48)
		at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
		at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)

Investigation shows, that the first approach creates another id under the local .gradle folder then the second.

    /home/mburchard/.gradle/wrapper/dists/gradle-6.0.1-all
        - 99d3u8wxs16ndehh90lbbir67
        - 6298f6turtwy8nm2vprrgfznr

The problem also exists under Windows 10.

**Comment by big-guy** [comment]
This is happening because the wrapper doesn't follow the redirect from http -> https when downloading the wrapper.  See https://blog.gradle.org/decommissioning-http

You need to use `https://...` instead of `http://`.  Even better is to not set the distributionUrl at all, you can just set the distribution type to ALL:
```
wrapper { 
   gradleVersion = '6.0.1'
   distributionType = Wrapper.DistributionType.ALL
}
```
