### ISSUE TITLE
Intermittent build failures due to a loader constraint violation

### ISSUE THREAD

**Issue by wilkinsona** [gradle/gradle#11914]
### Expected Behavior

Build should complete successfully.

### Current Behavior

Builds fail intermittently with a loader constraint violation:

```
FAILURE: Build failed with an exception.
* What went wrong:
loader constraint violation: when resolving method "org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.putArchiveEntry(Lorg/apache/commons/compress/archivers/ArchiveEntry;)V" the class loader (instance of org/gradle/internal/classloader/VisitableURLClassLoader) of the current class, org/gradle/caching/internal/packaging/impl/TarBuildCacheEntryPacker, and the class loader (instance of org/gradle/internal/classloader/VisitableURLClassLoader) for the method's defining class, org/apache/commons/compress/archivers/tar/TarArchiveOutputStream, have different Class objects for the type org/apache/commons/compress/archivers/ArchiveEntry used in the signature
```

### Context

Spring Boot's build fails very occasionally with the above loader constraint violation. Both @philwebb and I have experienced the problem. When it happened to me, once the failure started occurring it would cause every build to fail. Stopping the daemon fixed the problem and I haven't seen it since. When it happened to @philwebb, he was able to move past it by running with `--no-daemon` and `--no-build-cache`. I don't believe he tried the two options individually so I'm not sure which one avoided it.

### Steps to Reproduce

Unfortunately, I don't have any reliable steps to reproduce the problem. Sorry. FWIW, we've never seen the problem on CI where we have the daemon disabled (we use Concourse where each build runs in a fresh Docker container so the daemon doesn't benefit us).

### Your Environment

Gradle 6.0.1 building https://github.com/spring-projects/spring-boot on macOS with Java 8. I haven't captured a scan of this exact problem. We do have one of a similar problem that seemed to be caused by having a `GradleBuild` task with the cache enabled: https://ge.spring.io/s/ktaglmbawkbgq/failure?openFailures=WzBd#top=0. We worked around that by disabling the cache for that nested build. I will update this issue if/when we see the problem again and we're able to capture a scan.

**Comment by dreis2211** [comment]
@wilkinsona I've seen this on Concourse in the pull request pipeline: https://ci.spring.io/teams/spring-boot/pipelines/spring-boot-2.3.x/jobs/build-pull-requests/builds/175#L5e179a3f:2396

**Comment by wilkinsona** [comment]
Thank you, @dreis2211.

That information invalidates my theory that it's a problem with the daemon as the build ran with the daemon disabled. The scan is here: https://ge.spring.io/s/kc3p5sdqiz7na.

**Comment by wilkinsona** [comment]
I've just seen this happen again. Things got into a state where stopping the daemon fixed the loader constraint violation:

```
$ ./gradlew build

FAILURE: Build completed with 4 failures.

1: Task failed with an exception.
-----------
* What went wrong:
loader constraint violation: when resolving method "org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.putArchiveEntry(Lorg/apache/commons/compress/archivers/ArchiveEntry;)V" the class loader (instance of org/gradle/internal/classloader/VisitableURLClassLoader) of the current class, org/gradle/caching/internal/packaging/impl/TarBuildCacheEntryPacker, and the class loader (instance of org/gradle/internal/classloader/VisitableURLClassLoader) for the method's defining class, org/apache/commons/compress/archivers/tar/TarArchiveOutputStream, have different Class objects for the type org/apache/commons/compress/archivers/ArchiveEntry used in the signature

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
loader constraint violation: when resolving method "org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.putArchiveEntry(Lorg/apache/commons/compress/archivers/ArchiveEntry;)V" the class loader (instance of org/gradle/internal/classloader/VisitableURLClassLoader) of the current class, org/gradle/caching/internal/packaging/impl/TarBuildCacheEntryPacker, and the class loader (instance of org/gradle/internal/classloader/VisitableURLClassLoader) for the method's defining class, org/apache/commons/compress/archivers/tar/TarArchiveOutputStream, have different Class objects for the type org/apache/commons/compress/archivers/ArchiveEntry used in the signature

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
loader constraint violation: when resolving method "org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.putArchiveEntry(Lorg/apache/commons/compress/archivers/ArchiveEntry;)V" the class loader (instance of org/gradle/internal/classloader/VisitableURLClassLoader) of the current class, org/gradle/caching/internal/packaging/impl/TarBuildCacheEntryPacker, and the class loader (instance of org/gradle/internal/classloader/VisitableURLClassLoader) for the method's defining class, org/apache/commons/compress/archivers/tar/TarArchiveOutputStream, have different Class objects for the type org/apache/commons/compress/archivers/ArchiveEntry used in the signature

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

4: Task failed with an exception.
-----------
* What went wrong:
loader constraint violation: when resolving method "org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.putArchiveEntry(Lorg/apache/commons/compress/archivers/ArchiveEntry;)V" the class loader (instance of org/gradle/internal/classloader/VisitableURLClassLoader) of the current class, org/gradle/caching/internal/packaging/impl/TarBuildCacheEntryPacker, and the class loader (instance of org/gradle/internal/classloader/VisitableURLClassLoader) for the method's defining class, org/apache/commons/compress/archivers/tar/TarArchiveOutputStream, have different Class objects for the type org/apache/commons/compress/archivers/ArchiveEntry used in the signature

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
46 actionable tasks: 12 executed, 34 up-to-date

Publishing build scan...
https://ge.spring.io/s/q5apeysofuejw

$: ./gradlew --stop
Stopping Daemon(s)
1 Daemon stopped
$: ./gradlew build
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

> Task :spring-boot-project:spring-boot-test:compileJava
Note: /Users/awilkinson/dev/spring-projects/spring-boot/master/spring-boot-project/spring-boot-test/src/main/java/org/springframework/boot/test/mock/mockito/MockitoPostProcessor.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/awilkinson/dev/spring-projects/spring-boot/master/spring-boot-project/spring-boot-test/src/main/java/org/springframework/boot/test/context/runner/AbstractApplicationContextRunner.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :spring-boot-project:spring-boot-autoconfigure:compileTestKotlin
w: /Users/awilkinson/dev/spring-projects/spring-boot/master/spring-boot-project/spring-boot-autoconfigure/src/test/kotlin/org/springframework/boot/autoconfigure/diagnostics/analyzer/KotlinNoSuchBeanFailureAnalyzerNoKotlinReflectTests.kt: (32, 111): Unnecessary non-null assertion (!!) on a non-null receiver of type Class<String>
w: /Users/awilkinson/dev/spring-projects/spring-boot/master/spring-boot-project/spring-boot-autoconfigure/src/test/kotlin/org/springframework/boot/autoconfigure/diagnostics/analyzer/KotlinNoSuchBeanFailureAnalyzerNoKotlinReflectTests.kt: (33, 22): Unnecessary non-null assertion (!!) on a non-null receiver of type FailureAnalysis
w: /Users/awilkinson/dev/spring-projects/spring-boot/master/spring-boot-project/spring-boot-autoconfigure/src/test/kotlin/org/springframework/boot/autoconfigure/diagnostics/analyzer/KotlinNoSuchBeanFailureAnalyzerNoKotlinReflectTests.kt: (34, 220): Unnecessary non-null assertion (!!) on a non-null receiver of type Class<KotlinNoSuchBeanFailureAnalyzerNoKotlinReflectTests.ConstructorBoundProperties>

> Task :spring-boot-project:spring-boot:compileTestJava
Note: /Users/awilkinson/dev/spring-projects/spring-boot/master/spring-boot-project/spring-boot/src/test/java/org/springframework/boot/web/embedded/netty/NettyReactiveWebServerFactoryTests.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/awilkinson/dev/spring-projects/spring-boot/master/spring-boot-project/spring-boot/src/test/java/org/springframework/boot/json/JacksonJsonParserTests.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :spring-boot-project:spring-boot-autoconfigure:compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/awilkinson/dev/spring-projects/spring-boot/master/spring-boot-project/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/cache/support/MockCachingProvider.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :spring-boot-project:spring-boot-tools:spring-boot-antlib:integrationTest
Trying to override old definition of task fail
Trying to override old definition of datatype resources
Trying to override old definition of task buildnumber

> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-ant:antcompile
[ant:javac] /Users/awilkinson/dev/spring-projects/spring-boot/master/spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-ant/build.xml:32: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds

> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-ant:antbuild
[ant:echo] Using start class smoketest.ant.SampleAntApplication
[ant:echo] Using destination directory /Users/awilkinson/dev/spring-projects/spring-boot/master/spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-ant/build/ant/libs
[ant:echo] Extracting spring-boot-loader to /Users/awilkinson/dev/spring-projects/spring-boot/master/spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-ant/build/ant/libs/dependency
[ant:echo] Embedding spring-boot-loader v2.3.0.BUILD-SNAPSHOT...

> Task :spring-boot-project:spring-boot-docs:asciidoctorPdf
Failed to parse formatted text: Whether to disable the escaping of HTML characters such as '<', '>', etc.
Failed to parse formatted text: Whether to disable the escaping of HTML characters such as '<', '>', etc.
Failed to parse formatted text: JNDI location of the datasource. Class, url, username & password are ignored when set.
Failed to parse formatted text: JNDI location of the datasource. Class, url, username & password are ignored when set.
Failed to parse formatted text: Comma-separated list of additional unencoded characters that should be allowed in URI paths. Only "< > [ \ ] ^ ` { | }" are allowed.
Failed to parse formatted text: Comma-separated list of additional unencoded characters that should be allowed in URI query strings. Only "< > [ \ ] ^ ` { | }" are allowed.
Failed to parse formatted text: Comma-separated list of additional unencoded characters that should be allowed in URI paths. Only "< > [ \ ] ^ ` { | }" are allowed.
Failed to parse formatted text: Comma-separated list of additional unencoded characters that should be allowed in URI query strings. Only "< > [ \ ] ^ ` { | }" are allowed.

> Task :spring-boot-project:spring-boot-docs:javadoc
javadoc: warning - Multiple sources of package comments found for package "javax.transaction"
javadoc: warning - Multiple sources of package comments found for package "javax.servlet"
javadoc: warning - Multiple sources of package comments found for package "javax.servlet.http"
javadoc: warning - Multiple sources of package comments found for package "javax.servlet.annotation"
javadoc: warning - Error fetching URL: https://www.thymeleaf.org/apidocs/thymeleaf/3.0.11.RELEASE/
/Users/awilkinson/.gradle/caches/modules-2/files-2.1/com.samskivert/jmustache/1.15/7b3b15951d13b774c76db2f4e14d977952f8b4d8/jmustache-1.15.jar(com/samskivert/mustache/Mustache.java):319: warning: no @param for ctx
        VariableFetcher createFetcher (Object ctx, String name);
                        ^
/Users/awilkinson/.gradle/caches/modules-2/files-2.1/com.samskivert/jmustache/1.15/7b3b15951d13b774c76db2f4e14d977952f8b4d8/jmustache-1.15.jar(com/samskivert/mustache/Mustache.java):319: warning: no @param for name
        VariableFetcher createFetcher (Object ctx, String name);
                        ^
/Users/awilkinson/.gradle/caches/modules-2/files-2.1/com.samskivert/jmustache/1.15/7b3b15951d13b774c76db2f4e14d977952f8b4d8/jmustache-1.15.jar(com/samskivert/mustache/Mustache.java):319: warning: no @return
        VariableFetcher createFetcher (Object ctx, String name);
                        ^
/Users/awilkinson/.gradle/caches/modules-2/files-2.1/com.samskivert/jmustache/1.15/7b3b15951d13b774c76db2f4e14d977952f8b4d8/jmustache-1.15.jar(com/samskivert/mustache/Mustache.java):306: warning: no @param for name
        Reader getTemplate (String name) throws Exception;
               ^
/Users/awilkinson/.gradle/caches/modules-2/files-2.1/com.samskivert/jmustache/1.15/7b3b15951d13b774c76db2f4e14d977952f8b4d8/jmustache-1.15.jar(com/samskivert/mustache/Mustache.java):306: warning: no @return
        Reader getTemplate (String name) throws Exception;
               ^
10 warnings

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 3m 55s
1552 actionable tasks: 782 executed, 770 up-to-date

Publishing build scan...
https://ge.spring.io/s/ra5f56lhgzysi
```

**Comment by wolfs** [comment]
I tried reproducing this today, with no success. What I tried was to add a root build with the `java-library` plugin applied, which has a `GradleBuild` task which depends on `assemble`. The `GradleBuild` task invokes `assemble` on a nested build with the `java-library` plugin applied. The nested build also has a `buildSrc` project which depends on Apache `commons-compress`. I also tried applying the Spring boot plugin `2.2.3.RELEASE` and the dependency management plugin to the nested build.

I ran the build with the build cache enabled and then made source changes in the root build and the nested build, so that the output of those tasks will be stored in the build cache.

All of the above didn't help me reproduce the problem.

In your setup, which plugin depends on commons compress? For which task does the build fail? The build scan doesn't seem to capture the task which is executing in the nested build. Can you maybe run with `--console verbose` to see the tasks in the nested build as well?

**Comment by wilkinsona** [comment]
I don't think the `GradleBuild` task is the cause of this particular problem. We had a similar problem there in the past so the cache is now disabled for that nested build.

> In your setup, which plugin depends on commons compress?

We have dependencies on `commons-compress` in a few places: https://ge.spring.io/s/f7z44e7as3jso/dependencies?dependencies=commons-compress&expandAll.

> For which task does the build fail? The build scan doesn't seem to capture the task which is executing in the nested build.

I don't know as it's not apparent from the output that Gradle produces. However, I do know that, as far as I can tell, the nested build is not involved at this point.

Is it worth opening a separate issue to improve the diagnostics? It's apparent from the console output above that 4 tasks failed, but the associated build scan [lists 0 failed tasks](https://ge.spring.io/s/q5apeysofuejw/timeline?outcomeFilter=FAILED).

> Can you maybe run with `--console verbose` to see the tasks in the nested build as well?

Should the problem occur again, I'll run with `--console=verbose` and make the output available.

**Comment by dreis2211** [comment]
I currently have this locally when running via IDEA. From what I can see this isn't particular bound to a specific task, but it fails with different ones.

I don't have a reproduction as well, though I can fairly often see this when something in `spring-boot-smoke-test-ant` is run. In this case `checkFormat`, for example. 

Running with --full-stacktrace at the moment gives me the following:
```
16:16:34: Executing task 'checkFormat --full-stacktrace'...

> Task :buildSrc:compileJava UP-TO-DATE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:checkFormatMain UP-TO-DATE
> Task :buildSrc:checkFormatTest UP-TO-DATE
> Task :buildSrc:checkFormat UP-TO-DATE
> Task :buildSrc:checkstyleMain UP-TO-DATE
> Task :buildSrc:compileTestJava UP-TO-DATE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources UP-TO-DATE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:checkstyleTest UP-TO-DATE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:test UP-TO-DATE
> Task :buildSrc:validatePlugins UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-ant:checkFormatTest

FAILURE: Build failed with an exception.

* What went wrong:
loader constraint violation: when resolving method 'void org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.putArchiveEntry(org.apache.commons.compress.archivers.ArchiveEntry)' the class loader org.gradle.internal.classloader.VisitableURLClassLoader @4f2410ac of the current class, org/gradle/caching/internal/packaging/impl/TarBuildCacheEntryPacker, and the class loader org.gradle.internal.classloader.VisitableURLClassLoader @15327b79 for the method's defining class, org/apache/commons/compress/archivers/tar/TarArchiveOutputStream, have different Class objects for the type org/apache/commons/compress/archivers/ArchiveEntry used in the signature (org.gradle.caching.internal.packaging.impl.TarBuildCacheEntryPacker is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @4f2410ac, parent loader org.gradle.internal.classloader.VisitableURLClassLoader @15327b79; org.apache.commons.compress.archivers.tar.TarArchiveOutputStream is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @15327b79, parent loader 'platform')

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.LinkageError: loader constraint violation: when resolving method 'void org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.putArchiveEntry(org.apache.commons.compress.archivers.ArchiveEntry)' the class loader org.gradle.internal.classloader.VisitableURLClassLoader @4f2410ac of the current class, org/gradle/caching/internal/packaging/impl/TarBuildCacheEntryPacker, and the class loader org.gradle.internal.classloader.VisitableURLClassLoader @15327b79 for the method's defining class, org/apache/commons/compress/archivers/tar/TarArchiveOutputStream, have different Class objects for the type org/apache/commons/compress/archivers/ArchiveEntry used in the signature (org.gradle.caching.internal.packaging.impl.TarBuildCacheEntryPacker is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @4f2410ac, parent loader org.gradle.internal.classloader.VisitableURLClassLoader @15327b79; org.apache.commons.compress.archivers.tar.TarArchiveOutputStream is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @15327b79, parent loader 'platform')
	at org.gradle.caching.internal.packaging.impl.TarBuildCacheEntryPacker.createTarEntry(TarBuildCacheEntryPacker.java:156)
	at org.gradle.caching.internal.packaging.impl.TarBuildCacheEntryPacker.packMetadata(TarBuildCacheEntryPacker.java:128)
	at org.gradle.caching.internal.packaging.impl.TarBuildCacheEntryPacker.pack(TarBuildCacheEntryPacker.java:119)
	at org.gradle.caching.internal.packaging.impl.GZipBuildCacheEntryPacker.pack(GZipBuildCacheEntryPacker.java:42)
	at org.gradle.caching.internal.command.BuildCacheCommandFactory$StoreCommand.store(BuildCacheCommandFactory.java:177)
	at org.gradle.caching.internal.controller.DefaultBuildCacheController$Pack$1.run(DefaultBuildCacheController.java:205)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.caching.internal.controller.DefaultBuildCacheController$Pack.execute(DefaultBuildCacheController.java:201)
	at org.gradle.caching.internal.controller.DefaultBuildCacheController.lambda$store$1(DefaultBuildCacheController.java:179)
	at org.gradle.caching.local.internal.DefaultBuildCacheTempFileStore.withTempFile(DefaultBuildCacheTempFileStore.java:46)
	at org.gradle.caching.local.internal.DirectoryBuildCacheService$4.run(DirectoryBuildCacheService.java:178)
	at org.gradle.internal.Factories$1.create(Factories.java:26)
	at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.withFileLock(LockOnDemandCrossProcessCacheAccess.java:90)
	at org.gradle.cache.internal.DefaultCacheAccess.withFileLock(DefaultCacheAccess.java:186)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.withFileLock(DefaultPersistentDirectoryStore.java:177)
	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.withFileLock(DefaultCacheFactory.java:201)
	at org.gradle.caching.local.internal.DirectoryBuildCacheService.withTempFile(DirectoryBuildCacheService.java:175)
	at org.gradle.caching.internal.controller.DefaultBuildCacheController.store(DefaultBuildCacheController.java:178)
	at org.gradle.internal.execution.steps.CacheStep.store(CacheStep.java:139)
	at org.gradle.internal.execution.steps.CacheStep.lambda$executeAndStoreInCache$6(CacheStep.java:131)
	at org.gradle.internal.Try$Success.ifSuccessfulOrElse(Try.java:187)
	at org.gradle.internal.execution.steps.CacheStep.executeAndStoreInCache(CacheStep.java:130)
	at org.gradle.internal.execution.steps.CacheStep.lambda$executeWithCache$2(CacheStep.java:107)
	at java.base/java.util.Optional.orElseGet(Optional.java:362)
	at org.gradle.internal.execution.steps.CacheStep.lambda$executeWithCache$3(CacheStep.java:107)
	at org.gradle.internal.Try$Success.map(Try.java:162)
	at org.gradle.internal.execution.steps.CacheStep.executeWithCache(CacheStep.java:76)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:66)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:41)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
	at java.base/java.util.Optional.map(Optional.java:258)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
	at java.base/java.util.Optional.orElseGet(Optional.java:362)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:192)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:830)


* Get more help at https://help.gradle.org

BUILD FAILED in 1s
16:16:39: Task execution finished 'checkFormat --full-stacktrace'.
```

`--console verbose` doesn't seem to add anything to the picture for me.

Let me know if I can try something else.

**Comment by dreis2211** [comment]
Running the above with `--no-build-cache` runs through normally.

**Comment by wolfs** [comment]
OK, so the `antresolve` task [is changing a global Gradle classloader](https://github.com/spring-projects/spring-boot/blob/714a187d8ffcacb90face67c2946bd1fe31dcba5/spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-ant/build.gradle#L53-L59):
```
antresolve {
	dependsOn syncTestRepository, configurations.antDependencies
	doFirst {
		ClassLoader antClassLoader = org.apache.tools.ant.Project.class.classLoader
		configurations.antDependencies.each { antClassLoader.addURL it.toURI().toURL() }
	}
}
```

I can see how that could cause the `LinkageError`. Why are you adding those dependencies to the classloader of `org.apache.tools.ant.Project`?

**Comment by wilkinsona** [comment]
Thanks, @wolfs. Those dependencies need to be on Ant's classpath. With Maven's Ant Run plugin, that can be achieved by adding dependencies to the plugin declaration. As far as I know, the above is the only way to do it in Gradle. Note that there's no taskdef in the build script (and nor should there be) so I don't have an opportunity to provide a classpath that way. If there's a better way to do it that doesn't require a taskdef, I'll gladly get rid of the class loader hack.

**Comment by wolfs** [comment]
@wilkinsona I added the `taskdef` in a `doFirst` via this PR: https://github.com/spring-projects/spring-boot/pull/19825

Would that be acceptable?

**Comment by wilkinsona** [comment]
Thanks again, @wolfs. As I've just said in a comment on the PR, I was deliberately trying to avoid any taskdefs as it prevents the test from covering what it is supposed to cover. I think what we really need is a way of adding to Ant's classpath that does not have any additional side-effects, be those defining tasks or breaking the build cache.

**Comment by wolfs** [comment]
> I think what we really need is a way of adding to Ant's classpath that does not have any additional side-effects, be those defining tasks or breaking the build cache.

I don't think you can do that when importing the Ant build into Gradle. What you can do is to use your own task type which uses a worker with an isolated classloader (or a separate process) to run Ant on the build file.

**Comment by wilkinsona** [comment]
Thanks again, @wolfs. I have something close to working using a `JavaExec` task, other than it using the JRE rather than the JDK which prevents Ant from being able to compile. My `JAVA_HOME` points to the JDK, but Gradle appears to use the JRE anyway. Is there anything in Gradle for identifying the home of the JDK when running with a JRE?

**Comment by wolfs** [comment]
I really don't understand why Ant picks up the JRE. Gradle [runs the JDK's `java` command](https://ge.spring.io/s/qkvgxii3xi6bk/console-log#L161).

Could you point me to some code what you are trying to do?

**Comment by wilkinsona** [comment]
That confused me too. I think I have a fix. I've told Ant to fork its `javac` invocation which appears to do the trick: https://ge.spring.io/s/xaei4vj5pncyo.

Thanks for all your help here, @wolfs. I think we can probably close this one as it was really our fault due to us messing around with the class loader. I'll leave it for you to decide if you want to open a separate issue that improves the diagnostics.

**Comment by wolfs** [comment]
@wilkinsona Great that it works now! I currently can't think of a good way to improve diagnostics that someone changed a Gradle classloader, so I won't open a follow up issue.
