### ISSUE TITLE
NoClassDefFoundError error when passing lambda expression to `ProviderFactory.provider`

### ISSUE THREAD

**Issue by breskeby** [gradle/gradle#12069]
Since the gradle master nightly snapshot from tuesday night (28.1.2020) we see a NoClassDefFoundError in our build:

```
Caused by: java.lang.NoClassDefFoundError: Build_agent_gradle_test_func_gradle$3$2
        at org.gradle.api.internal.provider.DefaultProvider.getType(DefaultProvider.java:39)
        at org.gradle.api.internal.provider.DefaultMapProperty.put(DefaultMapProperty.java:202)
        at com.gradle.dotcom.build.testcontext.TestContextExtension$core$2.invoke(TestContextExtension.kt:16)
```

### Steps to Reproduce 

The issue can be reproduced from that GE branch: https://github.com/gradle/dotcom/commit/821dd616b9bcc1e4c3e9427cf1c2afdc4db5818a

### Your Environment

Build scan URL:

**Comment by adammurdoch** [comment]
A simplified reproducer is here: https://github.com/adammurdoch/kotlin-dsl-provider

**Comment by big-guy** [comment]
Rodrigo put in a workaround for now and reported this to JetBrains: https://github.com/gradle/gradle/pull/12097
