### ISSUE TITLE
Not a valid class name: *.package-info

### ISSUE THREAD

**Issue by justin-michel-boeing** [gradle/gradle#12109]
We must use package-info.java files to set JAXB package level annotations so that our project can read our XML data files. 
Everything works until you try to enable gradle incremental compilation. The full recompile builds successfully, but when you make a change and an incremental compile happens then it fails with...

java.lang.IllegalArgumentException: Not a valid class name: foo.package-info

Gradle 6.1.1 on Windows 10 with JDK 8.0.202

here's a snippet from the stack trace:
`
Caused by: java.lang.IllegalArgumentException: Not a valid class name: foo.package-info
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:129)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:107)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:64)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.createCompileTask(JdkJavaCompiler.java:70)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:53)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:39)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkAction.execute(AbstractDaemonCompiler.java:128)`

**Comment by melix** [comment]
Can you provide a simple reproducer?  We're using `package-info.java` classes ourselves in the Gradle build with incremental compilation and don't see this problem.

Thanks!

**Comment by justin-michel-boeing** [comment]
I've spent a few hours trying to reproduce it without success. It fails 100% of the time in my real project, but never fails in a trivial example. I even brought over all the annotated java files, after stripping out dependencies and it's fine. 
There is a real bug here, but I'm not sure how to go about debugging it. I can't share my 3 million lines of code project. 
Can anyone tell any useful hints from the stack trace?

**Comment by justin-michel-boeing** [comment]
One thing I can confirm is that the same error occurs using OpenJDK11 latest.

**Comment by justin-michel-boeing** [comment]
Somehow this issue was caused by [a micronaut issue with source annotations](https://github.com/micronaut-projects/micronaut-core/issues/2718).
Upgrading to Micronaut 1.3.0 (from 1.3.0 RC1) solves this issue as well.
