### ISSUE TITLE
Filenames of JUnit test results with non-ASCII characters get too long

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#1217]
JUnit test reports are generated in files named using the tests FQCNs.
Class names can contain arbitrary unicode glyphs.
Test reports files names are escaped by replacing all non-ASCII entries by their hexadecimal encoded form. This approach can create very long file names that bump into filesystems limits as seen by the original issue reporter.

### Expected Behavior
Too long file names are alleviated, to some extend.

### Current Behavior
With a test named, e.g., `com.cybozu.sample.SampleTest$内部のクラス名_ファイル名が長すぎるとテスト結果のｘｍｌファイルの生成に失敗することを確認するためのテスト`, the corresponding JUnit test result file name will be `build/test-results/TEST-com.cybozu.sample.SampleTest$#5185#90e8#306e#30af#30e9#30b9#540d_#30d5#30a1#30a4#30eb#540d#304c#9577#3059#304e#308b#3068#30c6#30b9#30c8#7d50#679c#306e#ff58#ff4d#ff4c#30d5#30a1#30a4#30eb#306e#751f#6210#306b#5931#6557#3059#308b#3053#3068#3092#78ba#8a8d#3059#308b#305f#3081#306e#30c6#30b9#30c8.xml` which gets longer than Windows filesystem limit.

Here is a complete stack-trace:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> Could not write XML test results for com.cybozu.sample.SampleTest$内部のクラス名_ファイル名が長すぎるとテスト結果のｘｍｌファイルの生成に失敗することを確認するためのテスト to file /home/matsu/idea/sample/build/test-results/TEST-com.cybozu.sample.SampleTest$#5185#90e8#306e#30af#30e9#30b9#540d_#30d5#30a1#30a4#30eb#540d#304c#9577#3059#304e#308b#3068#30c6#30b9#30c8#7d50#679c#306e#ff58#ff4d#ff4c#30d5#30a1#30a4#30eb#306e#751f#6210#306b#5931#6557#3059#308b#3053#3068#3092#78ba#8a8d#3059#308b#305f#3081#306e#30c6#30b9#30c8.xml.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.api.GradleException: Could not write XML test results for com.cybozu.sample.SampleTest$内部のクラス名_ファイル名が長すぎるとテスト結果のｘｍｌファイルの生成に失敗することを確認するためのテスト to file /home/matsu/idea/sample/build/test-results/TEST-com.cybozu.sample.SampleTest$#5185#90e8#306e#30af#30e9#30b9#540d_#30d5#30a1#30a4#30eb#540d#304c#9577#3059#304e#308b#3068#30c6#30b9#30c8#7d50#679c#306e#ff58#ff4d#ff4c#30d5#30a1#30a4#30eb#306e#751f#6210#306b#5931#6557#3059#308b#3053#3068#3092#78ba#8a8d#3059#308b#305f#3081#306e#30c6#30b9#30c8.xml.
	at org.gradle.api.internal.tasks.testing.junit.result.Binary2JUnitXmlReportGenerator$1.execute(Binary2JUnitXmlReportGenerator.java:58)
	at org.gradle.api.internal.tasks.testing.junit.result.Binary2JUnitXmlReportGenerator$1.execute(Binary2JUnitXmlReportGenerator.java:49)
	at org.gradle.api.internal.tasks.testing.junit.result.InMemoryTestResultsProvider.visitClasses(InMemoryTestResultsProvider.java:52)
	at org.gradle.api.internal.tasks.testing.junit.result.Binary2JUnitXmlReportGenerator.generate(Binary2JUnitXmlReportGenerator.java:49)
	at org.gradle.api.tasks.testing.Test.executeTests(Test.java:554)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 60 more
Caused by: java.io.FileNotFoundException: /home/matsu/idea/sample/build/test-results/TEST-com.cybozu.sample.SampleTest$#5185#90e8#306e#30af#30e9#30b9#540d_#30d5#30a1#30a4#30eb#540d#304c#9577#3059#304e#308b#3068#30c6#30b9#30c8#7d50#679c#306e#ff58#ff4d#ff4c#30d5#30a1#30a4#30eb#306e#751f#6210#306b#5931#6557#3059#308b#3053#3068#3092#78ba#8a8d#3059#308b#305f#3081#306e#30c6#30b9#30c8.xml (ファイル名が長すぎます)
	at org.gradle.api.internal.tasks.testing.junit.result.Binary2JUnitXmlReportGenerator$1.execute(Binary2JUnitXmlReportGenerator.java:54)
	... 72 more


BUILD FAILED
```

### Context
The issue was reported in the [forums](https://discuss.gradle.org/t/filenotfoundexception-is-thrown-when-i-use-japanese-letters-in-java-class-name/14743), filled in Jira as [GRADLE-3421](https://issues.gradle.org/browse/GRADLE-3421) and a [pull-request](https://github.com/gradle/gradle/pull/601) was proposed but rejected as we agreed that using a black-list approach to fix this was too risky.

### Steps to Reproduce (for bugs)
See above for a sample test-name that leads to very long file names.

### Your Environment
Windows

**Comment by pjskyboy** [comment]
Any movement on this that I could preview? This is really killing us in builds where we use cucumber-jvm with tables of examples - the test results are named based on the examples' data so can easily blow windows and linux filename lengths. 

test.reports.junitXml.enabled = false does not have the desired effect of muting the unwanted XML; the JSON results file seem to work fine.

**Comment by opyate** [comment]
@pjskyboy I use Gradle/Groovy/Cucumber and it was especially bad considering spaces get "exploded" to `#20`. This is what I did to shorten filename lengths:
```
@CucumberOptions(
    // ... all my usual options ... AND:
    junit = {"--filename-compatible-names"})
```

You can [dig](https://github.com/cucumber/cucumber-jvm/blob/8512b101b68020df8c7fad2c0a30f9bcdc8d88ce/junit/src/main/java/cucumber/runtime/junit/JUnitOptions.java#L42) to see what that option does.

**Comment by romerorsp** [comment]
@opyate Thanks for the tip, it contributed to fix the issue for me, but I'm still stuck because on my Cucumber tests the example payload is quite big, so Cucumber will take that in account as part of the report file name, I wonder is there a way to lead either cucumber or gradle to minify the file name?

Cheers.

**Comment by sakthsa** [comment]
@romerorsp Is there any update on the error that we face when the cucumber test example payload is big???

**Comment by saurabh0624** [comment]
@sakthsa Where you able to resolve the issue?

**Comment by saurabh0624** [comment]
@sakthsa Were you able to resolve this issue.

@romerorsp How did you resolve this issue.
