### ISSUE TITLE
ClassCastException in incremental build, DescriptiveChange to InputFileDetails

### ISSUE THREAD

**Issue by mondrejko** [gradle/gradle#1224]
In performing an incremental build in which no input files have changed, we are experiencing the following ClassCastException. This happens with Gradle 3.2, 3.2.1, and 3.3 (note that it did NOT happen with Gradle 2.14.1).

This is from a custom task class with a List<ConfigurableFileTree> instance variable is annotated with @InputFiles. The list then contains several elements including filetrees created from source directories, and filestrees created based upon the output directory of other custom tasks in the build.

```text
Caused by: java.lang.ClassCastException: Cannot cast class org.gradle.api.internal.changedetection.rules.DescriptiveChange to interface org.gradle.api.tasks.incremental.InputFileDetails
        at org.gradle.api.internal.changedetection.changes.ChangesOnlyIncrementalTaskInputs.doOutOfDate(ChangesOnlyIncrementalTaskInputs.java:42)
        at org.gradle.api.internal.changedetection.changes.StatefulIncrementalTaskInputs.outOfDate(StatefulIncrementalTaskInputs.java:39)
        at org.gradle.api.internal.changedetection.changes.ChangesOnlyIncrementalTaskInputs.outOfDate(ChangesOnlyIncrementalTaskInputs.java:27)
        at org.gradle.api.internal.changedetection.changes.ChangesOnlyIncrementalTaskInputs_Decorated.outOfDate(Unknown Source)
        at org.gradle.api.internal.changedetection.changes.ChangesOnlyIncrementalTaskInputs_Decorated$outOfDate.call(Unknown Source)
        at com.successfactors.buildsystem.webmodule.js.DirectiveParserTask.processFiles(DirectiveParserTask.groovy:42)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 70 more
```

**Comment by big-guy** [comment]
Can you provide the source for com.successfactors.buildsystem.webmodule.js.DirectiveParserTask? Or at least the method `DirectiveParserTask.processFiles()`?

**Comment by mondrejko** [comment]
@InputFilesList<ConfigurableFileTree> inputTrees = [] as List@TaskActionvoid processFiles(IncrementalTaskInputs inputs) {    final String outputPath = "$outputDir/WEB-INF/classes/rmgmt/deps"    final Set<File> validatePath = inputTrees.collect { it.dir } + project.configurations.webappContent.files    final String[] validateFiles = validatePath*.absolutePath    final CommandDirectiveProcessorHelper helper = new CommandDirectiveProcessorHelper(sfext.versionMap as Properties, outputPath, '', validateFiles)    if (!inputs.incremental) {        project.delete outputDir.listFiles()    }    inputs.outOfDate { change ->        if (change.file.isFile()) {            project.logger.debug "DirectiveParser: ${change.file.absolutePath}"            helper.checkFile(getBaseDir(change.file), change.file)        }    }    inputs.removed { change ->        String inputPath = change.file.absolutePath - getBaseDir(change.file)        File outputFile = project.file(outputPath + inputPath + '.generated.xml')        outputFile.delete()    }}


-------- Original Message --------
Subject: Re: [gradle/gradle] ClassCastException in incremental build,
DescriptiveChange to InputFileDetails (#1224)

**Comment by big-guy** [comment]
Hrm, I have some idea what could be happening, but I'm not sure how to reproduce it.

Could you send me the full task class and an example of how it's being used?  If you don't want to post it here, you can email me sterling@gradle.com

**Comment by mondrejko** [comment]
I found that there were extraneous task input files that were causing this issue in my case. Once I cleaned up these inputs the issue was cleared.

The inputs causing the issue was set to someproject.jar.outputs (I know, not how it should be setup, but that is what the developer did… told you it was extraneous anyway).

**Comment by CannedYerins** [comment]
Hi @big-guy, I sent you an email with what is hopefully enough to reproduce.

**Comment by farmerjohngit** [comment]
Hi @big-guy , I got same problem. when I add some input files to a task, then the error will occur when the task been executed next time.

Such as this:

`
packageTask.inputs.dir(fileProvider.getMiniChangedDexDir())
`

**Comment by farmerjohngit** [comment]
gralde 3.5 

`Caused by: java.lang.ClassCastException: org.gradle.api.internal.changedetection.rules.DescriptiveChange cannot be cast to org.gradle.api.tasks.incremental.InputFileDetails
        at org.gradle.api.internal.changedetection.changes.ChangesOnlyIncrementalTaskInputs.doOutOfDate(ChangesOnlyIncrementalTaskInputs.java:42)
        at org.gradle.api.internal.changedetection.changes.StatefulIncrementalTaskInputs.outOfDate(StatefulIncrementalTaskInputs.java:39)
        at org.gradle.api.internal.changedetection.changes.ChangesOnlyIncrementalTaskInputs.outOfDate(ChangesOnlyIncrementalTaskInputs.java:27)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:93)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:115)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:90)
        ... 70 more`

**Comment by CannedYerins** [comment]
Hi @big-guy, any update on this?

**Comment by gavra0** [comment]
We are hitting this with Gradle 4.1, as we have tasks that have dynamic inputs (transform tasks).

The issues seems to be that `TaskUpToDateState.rebuildChanges` does not account for `InputFilesTaskStateChanges` that might contain `DescriptiveChange` (https://github.com/gradle/gradle/blob/a191d29a511bcac0165a68afbe50c4a17ec35a56/subprojects/core/src/main/java/org/gradle/api/internal/changedetection/rules/AbstractNamedFileSnapshotTaskStateChanges.java#L72).

This means that file inputs might be added/removed, and this would still trigger an incremental build.

**Comment by wolfs** [comment]
Here is the task from the comment above:

```groovy
@InputFilesList<ConfigurableFileTree> inputTrees = [] as List
@TaskAction
void processFiles(IncrementalTaskInputs inputs) {
    final String outputPath = "$outputDir/WEB-INF/classes/rmgmt/deps"
    final Set<File> validatePath = inputTrees.collect { it.dir } + project.configurations.webappContent.files
    final String[] validateFiles = validatePath*.absolutePath
    final CommandDirectiveProcessorHelper helper = new CommandDirectiveProcessorHelper(sfext.versionMap as Properties, outputPath, '', validateFiles)    
    if (!inputs.incremental) {
        project.delete outputDir.listFiles()
    }
    inputs.outOfDate { change ->
        if (change.file.isFile()) {
            project.logger.debug "DirectiveParser: ${change.file.absolutePath}"            
            helper.checkFile(getBaseDir(change.file), change.file)
        }
    }
    inputs.removed { change ->
        String inputPath = change.file.absolutePath - getBaseDir(change.file)
        File outputFile = project.file(outputPath + inputPath + '.generated.xml')        
        outputFile.delete()
    }
}
```

**Comment by blindpirate** [comment]
This issue can be reproduced as follows:

```
    @Issue('https://github.com/gradle/gradle/issues/1224')
    def 'can change input properties dynamically'(){
        given:
        buildFile<<'''
    class T extends DefaultTask{
        @TaskAction
        void processFiles(IncrementalTaskInputs inputs) {
            inputs.outOfDate {println it}
        }
    }
    
    task myTask (type: T){
        project.ext.inputDirs.split(',').each {inputs.dir(it)}
    }
'''

        when:
        args('-PinputDirs=a,b')

        then:
        succeeds('myTask')

        when:
        args('-PinputDirs=a')

        then:
        succeeds('myTask')
    }
```

The reason is `InputFilesTaskStateChanges` contains input file properties change, which isn't treated as "properties change" here:

https://github.com/gradle/gradle/blob/da1fa8d15a5762f3ea693562615686251c2bbbc8/subprojects/core/src/main/java/org/gradle/api/internal/changedetection/rules/TaskUpToDateState.java#L54

and 

https://github.com/gradle/gradle/blob/da1fa8d15a5762f3ea693562615686251c2bbbc8/subprojects/core/src/main/java/org/gradle/api/internal/changedetection/rules/AbstractNamedFileSnapshotTaskStateChanges.java#L64

Therefore, in the tests above, when a file property is added into inputs dynamically, `DescriptiveChange`s are added into `inputFileChanges`, and rebuild aren't triggered.

I've submitted a fix, let's see if it can pass CI builds.
