### ISSUE TITLE
ConcurrentModificationException in ConsumerProvidedVariantFinder.findProducersFor

### ISSUE THREAD

**Issue by dahlstrom-g** [gradle/gradle#12362]
We're seeing this during automated tests in the Android Studio project:

```
java.util.ConcurrentModificationException
	at org.gradle.api.internal.artifacts.transform.ConsumerProvidedVariantFinder.findProducersFor(ConsumerProvidedVariantFinder.java:66)
	at org.gradle.api.internal.artifacts.transform.ConsumerProvidedVariantFinder.lambda$collectConsumerVariants$0(ConsumerProvidedVariantFinder.java:56)
	at org.gradle.api.internal.artifacts.transform.ConsumerProvidedVariantFinder.collectConsumerVariants(ConsumerProvidedVariantFinder.java:55)
	at org.gradle.api.internal.artifacts.transform.ConsumerProvidedVariantFinder.findProducersFor(ConsumerProvidedVariantFinder.java:83)
	at org.gradle.api.internal.artifacts.transform.ConsumerProvidedVariantFinder.lambda$collectConsumerVariants$0(ConsumerProvidedVariantFinder.java:56)
	at org.gradle.api.internal.artifacts.transform.ConsumerProvidedVariantFinder.collectConsumerVariants(ConsumerProvidedVariantFinder.java:55)
	at org.gradle.api.internal.artifacts.transform.ConsumerProvidedVariantFinder.findProducersFor(ConsumerProvidedVariantFinder.java:83)
	at org.gradle.api.internal.artifacts.transform.ConsumerProvidedVariantFinder.lambda$collectConsumerVariants$0(ConsumerProvidedVariantFinder.java:56)
	at org.gradle.api.internal.artifacts.transform.ConsumerProvidedVariantFinder.collectConsumerVariants(ConsumerProvidedVariantFinder.java:55)
	at org.gradle.api.internal.artifacts.transform.AttributeMatchingVariantSelector.doSelect(AttributeMatchingVariantSelector.java:98)
	at org.gradle.api.internal.artifacts.transform.AttributeMatchingVariantSelector.select(AttributeMatchingVariantSelector.java:76)
	... 30 more
```

**Comment by big-guy** [comment]
@dahlstrom-g which version of Gradle are you using?

**Comment by dahlstrom-g** [comment]
@big-guy: I'm told we use 6.2.

**Comment by bmuskalla** [comment]
@dahlstrom-g In case you still have it around, would you be able to share [a full stacktrace](https://docs.gradle.org/current/userguide/logging.html#stacktraces) with us? How often do you see this happening? Do you happen to have a build scan for a build with this issue?

**Comment by bmuskalla** [comment]
@dahlstrom-g We were partially successful reproducing this. We see two potential ways how this can happen even though both of them are deprecated/discouraged. What needs to happen is that (concurrently), something registers an `ArtifactTransform` while something else resolves the files of a configuration that uses those transformations (and those two events must happen on the same `Configuration`). Two ways this can happen either during configuration or execution phase:
a) [Configuration Phase] a project resolves the configuration of another project (deprecated), e.g. `project.parent.configurations.myConfiguration.getFiles()` 
b) [Execution Phase] a task dynamically registers an `ArtifactTransformation` (discouraged). Transforms should be registered during the configuration phase 

Given both ways are deprecated, we'll close this as wontfix for now. If you happen to have more information or a different non-discouraged way to reproduce this, please feel free to reopen. [Here is our reproducer](https://gist.github.com/bmuskalla/5d6bdb5822206223a38486efafcd2e57) that you can adapt to your usecase in case you can trigger this exception differently.
