### ISSUE TITLE
Gradle incompatibility with JDK 11

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#12387]
Gradle appears to use a removed JDK class that fails on JDK 11. Possibly a previously serialized `Serializable` object not able to be deserialized in a newer JVM?

### Expected Behavior
Gradle should be compatible with JDK 11

### Current Behavior
It fails when using the worker API

### Context
```
java.lang.NoClassDefFoundError: jdk/internal/reflect/GeneratedSerializationConstructorAccessor1
	at jdk.internal.reflect.GeneratedSerializationConstructorAccessor1.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.io.ObjectStreamClass.newInstance(ObjectStreamClass.java:1081)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2126)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:122)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:68)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:73)
```

### Steps to Reproduce 
Unfortunately project is our internal project and I haven't been able to reproduce it on an external one.

### Your Environment
MacOS 10.14
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)

**Comment by big-guy** [comment]
@ZacSweers do you have any other context around when this fails? Is this a test task failing or something custom? 

This looks a lot like this failure (which happened on Java 9): https://github.com/gradle/gradle/issues/5184

**Comment by ZacSweers** [comment]
None that I can share publicly, but I can send a scan dump to you on the Gradle community slack via DM if that works?

**Comment by big-guy** [comment]
Sure

**Comment by ZacSweers** [comment]
I've tried the workaround in the issue you linked and it seems to be helping now, but it wasn't enough to disable just via android's `testOptions` block alone (vs looking for _all_ test tasks)
