### ISSUE TITLE
Use of Kotlin Sequence/Java Stream in custom Tooling Model causes StackOverflow

### ISSUE THREAD

**Issue by mchalabine** [gradle/gradle#12454]
### Expected Behavior
Kotlin Sequences/Java Streams should be supported. 

### Current Behavior
Use of Kotlin Sequence/Java Streams in custom Tooling Model causes StackOverflow due to self-recurring looping in the Gradle's TypeInspector. 

### Context
Create a simple plugin that would use Kotlin Sequence/Java Stream as return type. The TypeInspector spins and fails with a StackOverflow exception.

[plugin.kt.txt](https://github.com/gradle/gradle/files/4297062/plugin.kt.txt)

========================
org.gradle.tooling.internal.adapter.TypeInspector.visit(TypeInspector.java:87)
2020-03-06T05:35:41.738+0100 [DEBUG] [TestEventLogger]             at org.gradle.tooling.internal.adapter.TypeInspector.visit(TypeInspector.java:103)
2020-03-06T05:35:41.738+0100 [DEBUG] [TestEventLogger]             at org.gradle.tooling.internal.adapter.TypeInspector.visit(TypeInspector.java:95)
2020-03-06T05:35:41.738+0100 [DEBUG] [TestEventLogger]             at org.gradle.tooling.internal.adapter.TypeInspector.visit(TypeInspector.java:87)
2020-03-06T05:35:41.738+0100 [DEBUG] [TestEventLogger]             at org.gradle.tooling.internal.adapter.TypeInspector.visit(TypeInspector.java:103)
2020-03-06T05:35:41.738+0100 [DEBUG] [TestEventLogger]             at org.gradle.tooling.internal.adapter.TypeInspector.visit(TypeInspector.java:95)
2020-03-06T05:35:41.739+0100 [DEBUG] [TestEventLogger]             at org.gradle.tooling.internal.adapter.TypeInspector.visit(TypeInspector.java:87)
2020-03-06T05:35:41.739+0100 [DEBUG] [TestEventLogger]             at org.gradle.tooling.internal.adapter.TypeInspector.visit(TypeInspector.java:103)
2020-03-06T05:35:41.739+0100 [DEBUG] [TestEventLogger]             at org.gradle.tooling.internal.adapter.TypeInspector.visit(TypeInspector.java:95)
2020-03-06T05:35:41.739+0100 [DEBUG] [TestEventLogger]             at org.gradle.tooling.internal.adapter.TypeInspector.visit(TypeInspector.java:87)

**Comment by donat** [comment]
I was able to reproduce the issue with adding a `Stream` return type to the custom model [snippet](https://github.com/gradle/gradle/blob/88fe915/subprojects/docs/src/snippets/toolingApi/customModel/plugin/src/main/java/org/gradle/sample/plugin/CustomModel.java#L11).
