### ISSUE TITLE
Copy file to UNIX group writable (664) files fails if not the owner

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1245]
The copy file actually works, but for some reason the code tries to chmod 644 the file immediately afterwards. It fails because I don't own the file and am not allowed to chmod it.

### Context
From https://discuss.gradle.org/t/copy-file-to-unix-group-writable-664-files-fails-if-not-the-owner/8773

Here's the code in `AbstractFileTreeElement.copyTo`:
```java
        if (isDirectory()) {
            GFileUtils.mkdirs(target);
        } else {
            GFileUtils.mkdirs(target.getParentFile());
            copyFile(target);
        }
        chmod.chmod(target, getMode());
```

Notice that it chmods the file even though it may not be necessary. getMode() is like this:
```java
public int getMode() {
    return isDirectory()
        ? FileSystem.DEFAULT_DIR_MODE
        : FileSystem.DEFAULT_FILE_MODE;
}
```

FileSystem.DEFAULT_FILE_MODE = 644.

I've tried setting "fileMode 0664" (which is the file's current permissions) and even "fileMode null" in the task and it makes no difference since it is using this static final variable. This has to be a bug, especially since there really isn't a workaround except to change ownership to myself as root.

I'm aware I could just delete all the files and then recopy, which would give myself ownership but this seems to run counter to the whole idea of the Sync task.

### Steps to Reproduce (for bugs)
```groovy
task deployTest(dependsOn: jar, type: Sync) {
    description 'Deploy Test'
    fileMode null
    from configurations.runtime
    into "/tmp/java_lib"
}
```

Produces this error if the files in /tmp/java_lib are group writable but owned by someone else.

```
Caused by: org.gradle.internal.nativeintegration.filesystem.FileException: Could not set file mode  644 on '/tmp/java_lib/annotations-5.1.jar'.
at org.gradle.internal.nativeintegration.filesystem.services.GenericFileSystem.chmod(GenericFileSystem.java:71)
at org.gradle.api.internal.file.AbstractFileTreeElement.copyTo(AbstractFileTreeElement.java:76)
... 77 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not set UNIX mode on /tmp/java_lib/annotations-5.1.jar: could not chmod file (errno 1)
at net.rubygrapefruit.platform.internal.DefaultPosixFiles.setMode(DefaultPosixFiles.java:41)
at org.gradle.internal.nativeintegration.filesystem.services.NativePlatformBackedChmod.chmod(NativePlatformBackedChmod.java:32)
at org.gradle.internal.nativeintegration.filesystem.services.GenericFileSystem.chmod(GenericFileSystem.java:69)
... 78 more
```

### Your Environment

 * Build scan URL:

**Comment by novaterata** [comment]
Does anyone know a workaround for this? I'm running in a docker container and My Copy destination is a samba mounted as a docker volume. I suppose I could switch to an Exec task.

**Comment by trecloux** [comment]
@eriwen Did you find a workaround to this problem ?

**Comment by cobexer** [comment]
Sorry for the late reply.

Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.
***
Related:
* #14556

**Comment by thomas-k-git** [comment]
any chance on getting this looked into?
also having this issue in a repo with two local users working on it (AI/non-AI + setgid) and only  one of them being owner, then the chmod fails..
