### ISSUE TITLE
Timeout on wrapper JVM connecting to daemon

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#12463]
### Context

```
[01:29:27]Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out)
[01:29:27]	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
[01:29:27]	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
[01:29:27]	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
[01:29:27]	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
[01:29:27]	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
[01:29:27]	at java.base/java.net.Socket.connect(Socket.java:591)
[01:29:27]	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285)
[01:29:27]	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[01:29:27]	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
[01:29:27]	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
[01:29:27]	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
[01:29:27]	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
[01:29:27]	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
[01:29:27]	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[01:29:27]	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
[01:29:27]	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
[01:29:27]	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[01:29:27]	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
[01:29:27]	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
[01:29:27]	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[01:29:27]	at org.gradle.wrapper.Download.downloadInternal(Download.java:78)
[01:29:27]	at org.gradle.wrapper.Download.download(Download.java:63)
[01:29:27]	at org.gradle.wrapper.Install$1.call(Install.java:68)
[01:29:27]	at org.gradle.wrapper.Install$1.call(Install.java:48)
[01:29:27]	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
[01:29:27]	at org.gradle.wrapper.Install.createDist(Install.java:48)
[01:29:27]	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
[01:29:27]	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
```

https://builds.gradle.org/viewLog.html?buildId=32256002&buildTypeId=Gradle_Check_Quick_1_bucket40

https://builds.gradle.org/viewLog.html?buildId=32254925&buildTypeId=Gradle_Check_IndividualPerformanceScenarioWorkersLinux

**Comment by blindpirate** [comment]
It seems like an infrastructure issue as these two issues happens almost at the same time.
