### ISSUE TITLE
Unexpected authentication token in command Build

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#12530]
### Context

```
[09:17:37][Gradle failure report] org.gradle.launcher.daemon.server.BadlyFormedRequestException: Unexpected authentication token in command Build{id=2d7fd22a-a992-423c-a678-326fa67b061e, currentDir=/home/tcagent1/agent/work/70b200cedd9dc965} received from socket connection from /127.0.0.1:44493 to /127.0.0.1:52364
[09:17:37][Gradle failure report] 	at org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler$ConnectionWorker.handleCommand(DefaultIncomingConnectionHandler.java:161)
[09:17:37][Gradle failure report] 	at org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler$ConnectionWorker.receiveAndHandleCommand(DefaultIncomingConnectionHandler.java:136)
[09:17:37][Gradle failure report] 	at org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler$ConnectionWorker.run(DefaultIncomingConnectionHandler.java:124)
[09:17:37][Gradle failure report] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[09:17:37][Gradle failure report] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[09:17:37][Gradle failure report] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[09:17:37][Gradle failure report] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[09:17:37][Gradle failure report] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[09:17:37][Gradle failure report] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

https://builds.gradle.org/viewLog.html?buildId=32563287&buildTypeId=Enterprise_Release_MainProject_Components_GradleCom_DotcomSiteTestBrowser&tab=buildLog&_focus=147#_state=147

**Comment by blindpirate** [comment]
In very rare cases, the daemon registry will contain corrupted value:

- Daemon 1 starts on 54321 port, and it crashes, now daemon registry has entry {Daemon 1, 54321 port }
- Daemon 2 starts, it happens to allocate the same 54321 port. Now daemon registry has entries: 
  - {Daemon 1, 54321 port }
  - {Daemon 2, 54321 port }
- A client tries to connect, and it selects Daemon 1. BOOM!

**Comment by big-guy** [comment]
This appears to be happening again or still on some internal builds (@pbielicki can share).

Although, this doesn't appear to be a new problem (this is Gradle 4.6): https://ge.gradle.org/s/vwz7c42tmpgny/tests/:tooling-api:forkingIntegTest/org.gradle.integtests.tooling.ToolingApiClientCurrentJdkCompatibilityTest/tapi%20client%20can%20run%20build%20action%20with%20Gradle%204.6%20on%20Java%208?anchor=e30&focused-exception-line=0-38#1

**Comment by pbielicki** [comment]
ftr https://github.com/gradle/dotcom/issues/8252

**Comment by blindpirate** [comment]
This seems not happen for a long time (>1 year).
