### ISSUE TITLE
Unexpected type tag 71 found

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#12566]
```Unable to receive command from client socket connection from /127.0.0.1:49403 to /127.0.0.1:52263. Discarding connection.
org.gradle.internal.remote.internal.MessageIOException: Could not read message from '/127.0.0.1:52263'.
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:94)
	at org.gradle.launcher.daemon.server.SynchronizedDispatchConnection.receive(SynchronizedDispatchConnection.java:70)
	at org.gradle.launcher.daemon.server.DefaultDaemonConnection$1.run(DefaultDaemonConnection.java:65)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Unexpected type tag 71 found.
	at org.gradle.internal.serialize.DefaultSerializerRegistry$TaggedTypeSerializer.read(DefaultSerializerRegistry.java:144)
	at org.gradle.internal.serialize.Serializers$StatefulSerializerAdapter$1.read(Serializers.java:36)
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
	... 8 more
```

https://builds.gradle.org/viewLog.html?buildId=32693502&buildTypeId=Gradle_Check_Platform_14_bucket4

https://e.grdev.net/s/aorbpawc6lets

**Comment by blindpirate** [comment]
https://builds.gradle.org/viewLog.html?buildId=32749592&buildTypeId=Gradle_Check_Platform_14_bucket4


https://e.grdev.net/s/47j34j4rsqvxu

**Comment by jjohannes** [comment]
This has not had any reaction since a year. Please reopen or create a new issue if there is anything concrete we should do.

**Comment by blindpirate** [comment]
https://builds.gradle.org/viewLog.html?buildId=42846215&buildTypeId=Gradle_Master_Check_Platform_14_bucket3

**Comment by blindpirate** [comment]
It has recurred.

**Comment by rpygithub** [comment]
I have hit this too: https://e.grdev.net/s/6u45fzxh3xdlc

**Comment by bavani-ally** [comment]
Do we have a solution for this? i have a similar issue with different tag number (Unexpected type tag 22 found.). 

`Unable to receive command from client socket connection from /127.0.0.1:34079 to /127.0.0.1:47042. Discarding connection.
**org.gradle.internal.remote.internal.MessageIOException: Could not read message from '/127.0.0.1:47042'.**
    at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:94)
    at org.gradle.launcher.daemon.server.SynchronizedDispatchConnection.receive(SynchronizedDispatchConnection.java:70)
    at org.gradle.launcher.daemon.server.DefaultDaemonConnection$1.run(DefaultDaemonConnection.java:65)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
    at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: **Unexpected type tag 22 found.**
    at org.gradle.internal.serialize.DefaultSerializerRegistry$TaggedTypeSerializer.read(DefaultSerializerRegistry.java:145)
    at org.gradle.internal.serialize.Serializers$StatefulSerializerAdapter$1.read(Serializers.java:36)
    at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)`

**Comment by ndtreviv** [comment]
I just started getting this error (or a similar one) this morning:

```
Unable to receive command from client socket connection from /127.0.0.1:62928 to /127.0.0.1:64718. Discarding connection.
org.gradle.internal.remote.internal.MessageIOException: Could not read message from '/127.0.0.1:64718'.
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:94)
	at org.gradle.launcher.daemon.server.SynchronizedDispatchConnection.receive(SynchronizedDispatchConnection.java:70)
	at org.gradle.launcher.daemon.server.DefaultDaemonConnection$1.run(DefaultDaemonConnection.java:73)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Unexpected type tag 74 found.
	at org.gradle.internal.serialize.DefaultSerializerRegistry$TaggedTypeSerializer.read(DefaultSerializerRegistry.java:158)
	at org.gradle.internal.serialize.Serializers$StatefulSerializerAdapter$1.read(Serializers.java:36)
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
	... 7 more
Caused by: java.lang.IllegalArgumentException: Unexpected type tag 74 found.
```

**Comment by Alluseri** [comment]
Still an issue in 2026!
```
Unable to receive command from client socket connection from /127.0.0.1:9229 to /127.0.0.1:5113. Discarding connection.
org.gradle.internal.remote.internal.MessageIOException: Could not read message from '/127.0.0.1:5113'.
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:96)
	at org.gradle.launcher.daemon.server.SynchronizedDispatchConnection.receive(SynchronizedDispatchConnection.java:70)
	at org.gradle.launcher.daemon.server.DefaultDaemonConnection$1.run(DefaultDaemonConnection.java:74)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalArgumentException: Unexpected type tag 71 found.
	at org.gradle.internal.serialize.DefaultSerializerRegistry$TaggedTypeSerializer.read(DefaultSerializerRegistry.java:162)
	at org.gradle.internal.serialize.Serializers$StatefulSerializerAdapter$1.read(Serializers.java:36)
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:83)
	... 7 more
```

**Comment by Alluseri** [comment]
Reproduction is really easy: use sing-box and force IDEA to use it as the proxy. The fix is just as easy: tell IDEA to use no proxy.
