### ISSUE TITLE
Gradle wrapper can't recover from corrupted download

### ISSUE THREAD

**Issue by stepango** [gradle/gradle#12593]
### Expected Behavior
Wrapper redownloads Gradle archive if it was corrupted

### Current Behavior
If Gradle archive is corrupted during download - the wrapper is not operational

```Unzipping /Users/stepango/.gradle/wrapper/dists/gradle-5.6.4-all/ankdp27end7byghfw1q2sw75f/gradle-5.6.4-all.zip to /Users/stepango/.gradle/wrapper/dists/gradle-5.6.4-all/ankdp27end7byghfw1q2sw75f
Exception in thread "main" java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1535)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1436)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1443)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1237)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
	at org.gradle.wrapper.Install.unzip(Install.java:215)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:75)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

In IDE is super confusing, I see the following message, which is misleading. If I actually try to redownload dependencies I end up having the same error message.

```ERROR: Failed to open zip file.
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)
```

### Context
I had an internet connection issue during gradle archive download which resulted in me spending 15 min trying to figure out what went wrong

### Steps to Reproduce 
Turn off internet during archive download and try to call any task on wrapper

**Comment by big-guy** [comment]
@stepango Do you know which version of the wrapper jar you're using (not the version of Gradle you're downloading)? 

The error you're seeing in the IDE isn't from Gradle unfortunately, so we can't do much about changing that.

**Comment by stepango** [comment]
How to check wrapper version?

**Comment by big-guy** [comment]
Sorry, I missed your reply.

If you could attach the gradle-wrapper.jar here, I can check.

**Comment by stepango** [comment]
I don't remember the exact version I was using. I believe the way to check if this behavior still persists is to get the latest Gradle wrapper and supply corrupted `gradle.zip` to see what will happen

**Comment by sstock** [comment]
This has been an issue for a long time with versions up to and including Gradle 6.7.

```
$ gradle --version

------------------------------------------------------------
Gradle 6.7
------------------------------------------------------------

Build time:   2020-10-14 16:13:12 UTC
Revision:     312ba9e0f4f8a02d01854d1ed743b79ed996dfd3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.8 (Amazon.com Inc. 11.0.8+10-LTS)
OS:           Mac OS X 10.14.6 x86_64

$ gradle wrapper --gradle-version=6.7

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed

$ ./gradlew --version
Downloading https://services.gradle.org/distributions/gradle-6.7-bin.zip
.........10%..........
Could not unzip /Users/sstock/.gradle/wrapper/dists/gradle-6.7-bin/efvqh8uyq79v2n7rcncuhu9sv/gradle-6.7-bin.zip to /Users/sstock/.gradle/wrapper/dists/gradle-6.7-bin/efvqh8uyq79v2n7rcncuhu9sv.
Reason: zip END header not found
Exception in thread "main" java.util.zip.ZipException: zip END header not found
[stack trace removed]

$ ./gradlew --version
Could not unzip /Users/sstock/.gradle/wrapper/dists/gradle-6.7-bin/efvqh8uyq79v2n7rcncuhu9sv/gradle-6.7-bin.zip to /Users/sstock/.gradle/wrapper/dists/gradle-6.7-bin/efvqh8uyq79v2n7rcncuhu9sv.
Reason: zip END header not found
Exception in thread "main" java.util.zip.ZipException: zip END header not found
[stack trace removed]

$ cd $HOME/.gradle/wrapper/dists/gradle-6.7-bin/efvqh8uyq79v2n7rcncuhu9sv/

$ ls -l
total 40968
-rw-r--r--  1 sstock  INFOR\Domain Users  20248930 Oct 21 12:44 gradle-6.7-bin.zip
-rw-r--r--  1 sstock  INFOR\Domain Users         0 Oct 21 12:35 gradle-6.7-bin.zip.lck
```

It is possible to resume the download using curl.  I've done this with prior Gradle versions because my Internet connection is slow so I don't want to waste the data already downloaded:
```
$ curl --location -O -C - https://services.gradle.org/distributions/gradle-6.7-bin.zip
** Resuming transfer from byte position 20248930
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 77 78.7M   77 60.6M    0     0  66745      0  0:20:36  0:15:53  0:04:43 70731
```
