### ISSUE TITLE
Cannot delete project directory on Windows when watching the file system is enabled

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#12614]
When not using isolated daemons for running the VFS retention tests, we seem to be getting `AccessDeniedException`s when trying to delete the watched directory on Windows, see for example [VfsRetention Java14 Openjdk Windows (compositeBuilds,languageGroovy,modelGroovy,signing)](https://builds.gradle.org/viewLog.html?buildId=32861908&buildTypeId=Gradle_Check_VfsRetention_30_bucket41&tab=queuedBuildOverviewTab)

```
org.gradle.api.GradleException: Couldn't delete test dir for `can apply a transform to the outputs of included builds(org.gradle.integtests.composite.CompositeBuildArtifactTransformIntegrationTest)` (test is holding files open). In order to find out which files are held open you may find http://file-leak-detector.kohsuke.org/ useful.
	at org.gradle.test.fixtures.file.AbstractTestDirectoryProvider$TestDirectoryCleaningStatement.evaluate(AbstractTestDirectoryProvider.java:106)
	at org.spockframework.runtime.extension.builtin.TestRuleInterceptor.intercept(TestRuleInterceptor.java:39)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:97)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:413)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.nio.file.AccessDeniedException: C:\tcagent1\work\a16b87e0a70f8c6e\subprojects\composite-builds\build\tmp\test files\CompositeBuildArtifactTransformIntegrationTest\hyu14\buildA
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:86)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:520)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:476)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:300)
	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:373)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2840)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2876)
	at org.gradle.test.fixtures.file.TestFile.forceDeleteDir(TestFile.java:686)
	at org.gradle.test.fixtures.file.AbstractTestDirectoryProvider$1.doCall(AbstractTestDirectoryProvider.java:72)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:399)
	at org.gradle.test.fixtures.ConcurrentTestUtil.poll(ConcurrentTestUtil.groovy:77)
	at org.gradle.test.fixtures.file.AbstractTestDirectoryProvider.cleanup(AbstractTestDirectoryProvider.java:69)
	at org.gradle.test.fixtures.file.TestNameTestDirectoryProvider.cleanup(TestNameTestDirectoryProvider.java:25)
	at org.gradle.test.fixtures.file.AbstractTestDirectoryProvider$TestDirectoryCleaningStatement.evaluate(AbstractTestDirectoryProvider.java:100)
	... 23 more
```

---
cc: @gradle/build-cache

**Comment by lptr** [comment]
Is this still an issue? Parents of watched directories cannot be deleted, and that's just how Windows works. If this is still a problem, we need to find a workaround. Moving to Sprint backlog.

**Comment by wolfs** [comment]
This still is an issue for our integration tests when not using isolated daemons. How much this is a problem for actual end users is a different question.

**Comment by lptr** [comment]
FTR, @wolfs will ask on #build-tool if we can easily solve this problem for our test cleanup.

**Comment by lptr** [comment]
BTW, would it be an option to delay test directory cleanup until all tests for the project have finished, and all test daemons are killed?

**Comment by wolfs** [comment]
#13127 allows deleting the project directory, by stopping the watches when nothing is left to watch.
