### ISSUE TITLE
Issue with duplicate class files in Intellij and Gradle Project

### ISSUE THREAD

**Issue by yschimke** [gradle/gradle#12638]
Breaks on Android, but I think it's an underlying issue with Intellij and Gradle.  The issue only manifests when switching between IDE and CLI.  presumably this is generally not observable (apart from out of sync results) because only the D8 plugin fails on duplicates.

```
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:81)
        at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:45)
        at com.android.tools.r8.D8.run(D8.java:94)
        at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:99)
        ... 8 more
Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: okhttp3.CallEvent$CallFailed
        at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:101)
        at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:72)
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:66)
        ... 11 more
```

```
find . -name \*CallFailed\*
./okhttp-testing-support/build/classes/java/main/okhttp3/CallEvent$CallFailed.class
./okhttp-testing-support/build/classes/kotlin/main/okhttp3/CallEvent$CallFailed.class
```

**Comment by yschimke** [comment]
More discussion on https://github.com/square/okhttp/issues/5902

**Comment by big-guy** [comment]
If you can find a reproducer for this problem, please open a new issue with it and link back to this one.

Thanks!
