### ISSUE TITLE
Provider API regression 6.2.1 -> 6.3

### ISSUE THREAD

**Issue by pun-ky** [gradle/gradle#12677]
### Expected Behavior

Build working after upgrading from 6.2.1 to 6.3

### Current Behavior

https://github.com/Cognifide/gradle-aem-plugin/issues/667#issue-590445484

```
Caused by: java.lang.UnsupportedOperationException: Should not be called
        at org.gradle.api.internal.provider.AbstractProperty$FinalizedValue.finalState(AbstractProperty.java:407)
        at org.gradle.api.internal.provider.AbstractProperty.beforeRead(AbstractProperty.java:195)
        at org.gradle.api.internal.provider.AbstractProperty.calculateOwnValue(AbstractProperty.java:103)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:109)
        at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:68)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:80)
        at com.cognifide.gradle.aem.pkg.tasks.PackageCompose$fromArchive$1.invoke(PackageCompose.kt:154)
        at com.cognifide.gradle.aem.pkg.tasks.PackageCompose$fromArchive$1.invoke(PackageCompose.kt:23)
        at com.cognifide.gradle.common.build.ObjectFactory$sam$java_util_concurrent_Callable$0.call(ObjectFactory.kt)
        at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:66)

```

### Context

Custom plugin user reported an [issue](https://github.com/Cognifide/gradle-aem-plugin/issues/667) when using recent version of Gradle.
I checked that the issue only occurs on Gradle 6.3

### Steps to Reproduce 

https://github.com/sabberworm/gradle-aem-plugin-multi-project-issue-reproducible-example
Build via command `sh gradlew packageCompose` - it will fail (the issue visible).

Then change Gradle version in wrapper properties file from 6.3 to 6.2.1, repeat.build command - issue is gone.

### Your Environment

------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_242 (AdoptOpenJDK 25.242-b08)
OS:           Mac OS X 10.15.3 x86_64

**Comment by pun-ky** [comment]
Seems that some Gradle mechanism is now finalizing properties which values are provided by `project.provider {}` and such providers have no overridden method which is finalizing value.

**Comment by pun-ky** [comment]
what is strange, when disabling parallelism by `org.gradle.parallel=false` build is also working :/

**Comment by pun-ky** [comment]
what could be a little bit custom here is that the relationship between tasks is assigned in phase `gradle.projectsEvaluated`. When I change my plugin code a little bit and now `dependsOn` is set when first build script is evaluated, the issue is also gone.
