### ISSUE TITLE
IntelliJ IDEA Gradle sync with Zulu 11.0.7 JDK on macOS throws newly created daemon process has a different context than expected

### ISSUE THREAD

**Issue by ant-druha** [gradle/gradle#12840]
From this report: https://youtrack.jetbrains.com/issue/IDEA-238037

Create the simplest possible gradle project and add a gradle wrapper (I tried 6.3 and 6.2.2).

```
plugins {
    java
}
```

Open the project (I used "Open..." and selected the directory containing the gradle files).

When Intellij does its Gradle sync using the Zulu distribution of 11.0.7, the sync fails:

```
2020-04-17 07:29:20,907 [44554852]   INFO - s.plugins.gradle.GradleManager - Instructing gradle to use java from /Users/mbp/.sdkman/candidates/java/11.0.7-zulu 
2020-04-17 07:29:20,908 [44554853]   INFO - s.plugins.gradle.GradleManager - Instructing gradle to use java from /Users/mbp/.sdkman/candidates/java/11.0.7-zulu 
2020-04-17 07:29:20,918 [44554863]   INFO - xecution.GradleExecutionHelper - Passing command-line args to Gradle Tooling API: -Didea.sync.active=true -Didea.resolveSourceSetDependencies=true -Porg.gradle.kotlin.dsl.provider.cid=46801207603351 -Pkotlin.include.android.dependencies=true --init-script /private/var/folders/14/gq1jbz355v3f9zx3mc1j0bz00000gn/T/ijinit1.gradle 
2020-04-17 07:29:22,593 [44556538]   INFO - .project.GradleProjectResolver - Gradle project resolve error 
org.gradle.tooling.GradleConnectionException: Could not run phased build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-6.3-bin.zip'.
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:55)
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:43)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor.lambda$run$0(DefaultAsyncConsumerActionExecutor.java:57)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.gradle.launcher.daemon.client.DaemonConnectionException: The newly created daemon process has a different context than expected.
It won't be possible to reconnect to this daemon. Context mismatch: 
Java home is different.
Wanted: DefaultDaemonContext[uid=null,javaHome=/Users/mbp/.sdkman/candidates/java/11.0.7-zulu,daemonRegistryDir=/Users/mbp/.gradle/daemon,pid=31959,idleTimeout=null,priority=NORMAL,daemonOpts=-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]
Actual: DefaultDaemonContext[uid=a2b6b868-028b-4718-bbed-fce8e71f89c3,javaHome=/Users/mbp/.sdkman/candidates/java/11.0.7-zulu/zulu-11.jdk/Contents/Home,daemonRegistryDir=/Users/mbp/.gradle/daemon,pid=33905,idleTimeout=10800000,priority=NORMAL,daemonOpts=-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]

	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connectToDaemonWithId(DefaultDaemonConnector.java:253)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.doStartDaemon(DefaultDaemonConnector.java:222)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.startDaemon(DefaultDaemonConnector.java:211)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connect(DefaultDaemonConnector.java:133)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:145)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:99)
	at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:51)
	at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:35)
	at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:60)
	at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:38)
	at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:203)
	at org.gradle.tooling.internal.provider.ProviderConnection.runPhasedAction(ProviderConnection.java:171)
	at org.gradle.tooling.internal.provider.DefaultConnection.run(DefaultConnection.java:249)
	at org.gradle.tooling.internal.consumer.connection.PhasedActionAwareConsumerConnection.run(PhasedActionAwareConsumerConnection.java:56)
	at org.gradle.tooling.internal.consumer.connection.ParameterValidatingConsumerConnection.run(ParameterValidatingConsumerConnection.java:62)
	at org.gradle.tooling.internal.consumer.DefaultPhasedBuildActionExecuter$1.run(DefaultPhasedBuildActionExecuter.java:78)
	at org.gradle.tooling.internal.consumer.DefaultPhasedBuildActionExecuter$1.run(DefaultPhasedBuildActionExecuter.java:70)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:87)
	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:61)
	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor.lambda$run$0(DefaultAsyncConsumerActionExecutor.java:55)
	... 6 more
2020-04-17 07:29:22,594 [44556539]   INFO - System.util.ExternalSystemUtil - External project [/Users/mbp/tmp/parent-proj/gradle-proj] resolution task executed in 1728 ms. 
2020-04-17 07:29:22,959 [44556904]   INFO - ge.ExternalProjectsDataStorage - Save external projects data in 4 ms 
```

However, this only happens with 11.0.7-zulu. Not 11.0.6-zulu, not 12, 13, or 14 from zulu, not 11.0.7 from Amazon (all installed via sdkman). I'm inclined to say it's a JDK bug, yet the gradle build works just fine on the command line with 11.0.7-zulu. The only issue I can find is that invoking gradle from IntelliJ fails, and only on macOS. The same trivial build works just fine with IntelliJ 2020.1 with 11.0.7-zulu on Linux.
```
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Licensed to rust-base64 / Marshall Pierce
Subscription is active until December 26, 2020
For non-commercial open source development only.
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 8
Registry: ide.max.recent.projects=100, debugger.click.disable.breakpoints=true
Non-Bundled Plugins: Key Promoter X, com.andrewbrookins.wrap_to_column, mobi.hsz.idea.gitignore, com.jetbrains.plugins.ini4idea, com.mnr.java.intellij.idea.plugin.base64helper, io.protostuff.protostuff-jetbrains-plugin, lermitage.intellij.extra.icons, name.kropp.intellij.makefile, org.antlr.jetbrains.st4plugin, org.intellij.plugins.hcl, org.jetbrains.plugins.rest, Pythonid, ru.adelf.idea.dotenv, ru.meanmail.plugin.requirements, org.jetbrains.kotlin, ru.yole.jitwatch-intellij, org.asciidoctor.intellij.asciidoc, org.toml.lang, some.awesome
```

I have also reproduced this with this Zulu JDK version.
![image](https://user-images.githubusercontent.com/3117044/79633987-81124580-8170-11ea-9ba7-a90c9ab4df56.png)

**Comment by ant-druha** [comment]
Similar to #11200 and #10041

**Comment by soloturn** [comment]
@ant-druha do you have JAVA_HOME set or not? in linux it is not set any more nowadays.

**Comment by clemstoquart** [comment]
Hi, same issue for me on macOS. Everything was fine with JDK 11.0.6.

**Comment by soloturn** [comment]
@clemstoquart do you have JAVA_HOME set or not on macos?

**Comment by clemstoquart** [comment]
@soloturn JAVA_HOME is setted. I tried to unset it and it doesn't change anything.

**Comment by clemstoquart** [comment]
Hard to believe but it works properly with the JDK 11.0.7 AdoptOpjenJDK flavour 🤔

**Comment by nimitagr** [comment]
I have been struggling with the same issue with 11.0.7-zulu and @clemstoquart's finding with JDK 11.0.7 AdoptOpenJDK flavour seems to work.

**Comment by efibe** [comment]
After struggling a bit with this issue, I found that I had my PATH set to `/opt/java/bin`, which was a symbolic link pointing to `/opt/zulu11.39.15-ca-fx-jdk11.0.7-macosx_x64/bin`, which is also a symbolic link that in turn pointed `/opt/zulu11.39.15-ca-fx-jdk11.0.7-macosx_x64/zulu-11.jdk/Contents/Home/bin`

After I set the path directly to the actual directory `/opt/zulu11.39.15-ca-fx-jdk11.0.7-macosx_x64/zulu-11.jdk/Contents/Home/bin`, the problem was gone.

Now I can load & run my project in both Netbeans and IntelliJ IDEA.

The problem is that

1. Zulu hides the JVM inside the MacOS specific bundle structure because of the digital signatures required by MacOS
2. Gradle apparently has a problem with symbolic links.

**Comment by pauIomartins** [comment]
Uninstalling java zulu and installing open JDK worked for me.

**Comment by jeffj55374** [comment]
> Uninstalling java zulu and installing open JDK worked for me.

I use sdkman and had the same problem with Zulu 11.0.7 JDK.  Using sdkman I switched to AdoptOpenJDK 11.0.7 and things work.

**Comment by fluxlife** [comment]
@efibe's method worked for me! I only wish I would have found this thread/issue sooner.

**Comment by nimitagr** [comment]
Heads up, faced the same issue with Zulu Java 13 JDK

**Comment by mrduckieduck** [comment]
Heads up, faced the same issue with Zulu Java 14.0.2 JDK

**Comment by migueldeandaJC** [comment]
thank you! this drove me crazy for a few days and i finally spent a few hours on it to ultimately find this. switched to the amazon jdk and it works now for 11. haven't had issues with other zulu jdk's though but i'm only at 14.0.1 so i'm not going to switch to 14.0.2 as i see @mrduckieduck had issues.

**Comment by z0mb1ek** [comment]
same with zulu 15.0.1 and gradle 6.7

**Comment by nikoskitmeridis** [comment]
same with zulu 11.0.9 and gradle 6.5 (was working with zulu 11.0.6)

**Comment by snimavat** [comment]
Had same issue, worked after changing gradle jvm as below.

<img width="971" alt="Screenshot 2021-01-08 at 5 23 42 PM" src="https://user-images.githubusercontent.com/623295/104012728-507aac00-51d6-11eb-95dd-f2475c1460f2.png">

Also make sure jdk path in project sdk is set properly like below.

`/Users/xxx/.sdkman/candidates/java/8.0.272-zulu/zulu-8.jdk/Contents/Home` /Contents/Home is important
