### ISSUE TITLE
Gradle 6.5-milestone-2: build crashes while generating a jar file

### ISSUE THREAD

**Issue by cesar1000** [gradle/gradle#13155]
I'm getting a crash shortly after starting a build in Gradle 6.5-milestone-2:

```
Caused by: org.gradle.api.GradleException: Failed to create /Users/cpuerta/.gradle/caches/jars-8/6cb328fbe9fe298af10c6d2e1e9302bf/lombok-ast-0.2.3.jar.
        at org.gradle.internal.classpath.ClasspathBuilder.jar(ClasspathBuilder.java:44)
        at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.transform(InstrumentingClasspathFileTransformer.java:71)
        at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.transform(InstrumentingClasspathFileTransformer.java:65)
        at org.gradle.internal.classpath.DefaultCachedClasspathTransformer$TransformFile.lambda$schedule$0(DefaultCachedClasspathTransformer.java:270)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.util.zip.ZipException: duplicate entry: LICENSE
        at org.gradle.internal.classpath.ClasspathBuilder$ZipEntryBuilder.put(ClasspathBuilder.java:83)
        at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.lambda$transform$0(InstrumentingClasspathFileTransformer.java:98)
        at org.gradle.internal.classpath.ClasspathWalker.visitJarContents(ClasspathWalker.java:88)
        at org.gradle.internal.classpath.ClasspathWalker.visit(ClasspathWalker.java:52)
        at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.lambda$transform$1(InstrumentingClasspathFileTransformer.java:71)
        at org.gradle.internal.classpath.ClasspathBuilder.buildJar(ClasspathBuilder.java:55)
        at org.gradle.internal.classpath.ClasspathBuilder.jar(ClasspathBuilder.java:42)
        ... 6 more
```

The original artifact is `com.android.tools.external.lombok:lombok-ast:0.2.3`, which does contain a couple of duplicate entries. The issue doesn't repro in 6.4.

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/13180
