### ISSUE TITLE
Build fails with Gradle 6.4.1 (UnknownModuleException) - Appveyor-Windows

### ISSUE THREAD

**Issue by marandaneto** [gradle/gradle#13157]
Build fails with Gradle 6.4.1 (UnknownModuleException) - Appveyor-Windows

### Expected Behavior
Upgrade Gradle 6.4 to 6.4.1 and build pass on Appveyor - Windows.

### Current Behavior
org.gradle.api.internal.classpath.UnknownModuleException: Cannot locate JAR for module 'ant' in classpath: [C:\Users\appveyor.gradle\wrapper\dists\gradle-6.4.1-all\13imxtezgn9nwzqt8rgtkunh1\gradle-6.4.1\lib\gradle-launcher-6.4.1.jar, C:\Users\appveyor.gradle\wrapper\dists\gradle-6.4.1-all\13imxtezgn9nwzqt8rgtkunh1\gradle-6.4.1\lib\gradle-bootstrap-6.4.1.jar, C:\Users\appveyor.gradle\wrapper\dists\gradle-6.4.1-all\13imxtezgn9nwzqt8rgtkunh1\gradle-6.4.1\lib\gradle-base-services-6.4.1.jar, C:\Users\appveyor.gradle\wrapper\dists\gradle-6.4.1-all\13imxtezgn9nwzqt8rgtkunh1\gradle-6.4.1\lib\gradle-core-api-6.4.1.jar, C:\Users\appveyor.gradle\wrapper\dists\gradle-6.4.1-all\13imxtezgn9nwzqt8rgtkunh1\gradle-6.4.1\lib\gradle-core-6.4.1.jar].
at org.gradle.api.internal.classpath.DefaultModuleRegistry.loadExternalModule(DefaultModuleRegistry.java:106)
at org.gradle.api.internal.classpath.DefaultModuleRegistry.getExternalModule(DefaultModuleRegistry.java:96)
at org.gradle.api.internal.DefaultClassPathProvider.findClassPath(DefaultClassPathProvider.java:63)
at org.gradle.api.internal.DefaultClassPathRegistry.getClassPath(DefaultClassPathRegistry.java:35)
at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:48)
at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Command exited with code 1

### Context
appveyor/ci/issues/3437

### Steps to Reproduce 
Upgrade Gradle from 6.4 to 6.4.1 on Appveyor - Windows

### Your Environment
https://github.com/getsentry/sentry-android/blob/master/.appveyor.yml

**Comment by big-guy** [comment]
This looks like it might be a partial install of the distribution.  

Could you try running without `"%USERPROFILE%\\.gradle\\wrapper"` in your appveyor.yml to see if it makes any difference?

**Comment by marandaneto** [comment]
sure, let me try.

**Comment by marandaneto** [comment]
@big-guy yeah build is ongoing.
I think I should keep appveyor/ci/issues/3437 open and close this one then, thanks a lot.
Keep the great work!
