### ISSUE TITLE
Applying older versions of enterprise plugin is not possible from init script

### ISSUE THREAD

**Issue by sacchettom** [gradle/gradle#13201]
### Expected Behavior
Following the instructions given here https://docs.gradle.com/enterprise/gradle-plugin/#gradle_enterprise I should be able to apply the enterprise plugin in the desired version to the project through an init script without having to manually edit all of the projects' settings files.

### Current Behavior
When attempting to run a scan the older version (3.1.1) specified in the `initscript {}` block gets ignored and a scan with the latest is attempted:
`----------
Gradle version: 6.4.1
Plugin version: 3.3.1
Request URL: https://gradle-******************/scans/publish/gradle/3.3.1/token
Request ID: d324a707-2fc4-4ab9-b0a3-65f3c7579fd8
Response status code: 401
Response content type: text/html;charset=UTF-8
Response server type: nginx/1.16.1
----------`

### Context
Our server is not updated to the latest versions and plugin version 3.1.1 is the latest we can use at the moment. Since with gradle 6 it's now required to edit `settings.gradle` to apply the plugin (before we used to apply it through a plugin of our own automatically from the root project), I'm attempting to get it applied with an init script as per instructions. Note that of course we removed the scan server configuration part from the init script, as that's already done in our root project, and only left the part that applies the plugin. Applying the plugin through the settings file works fine. Tried applying a constraint(`strictly`) to the dependency in the init file with no success.

### Steps to Reproduce 
Pass the following init script to the build
```
import com.gradle.enterprise.gradleplugin.GradleEnterprisePlugin
import com.gradle.scan.plugin.BuildScanPlugin
import org.gradle.util.GradleVersion

initscript {
    def pluginVersion = "3.1.1"

    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath("com.gradle:gradle-enterprise-gradle-plugin:${pluginVersion}")
    }
}

def isTopLevelBuild = gradle.getParent() == null

if (isTopLevelBuild) {
    def gradleVersion = GradleVersion.current().baseVersion
    def atLeastGradle5 = gradleVersion >= GradleVersion.version("5.0")
    def atLeastGradle6 = gradleVersion >= GradleVersion.version("6.0")

    if (atLeastGradle6) {
        settingsEvaluated {
            if (!it.pluginManager.hasPlugin("com.gradle.enterprise")) {
                it.pluginManager.apply(GradleEnterprisePlugin)
            }
        }
    } else if (atLeastGradle5) {
        rootProject {
            pluginManager.apply(BuildScanPlugin)
        }
    }
}
```
Try running a build with a scan passing that script, you should see that plugin 3.3.1 gets used instead of 3.1.1.
In our case giving a failure as it's not supported by the server.

### Your Environment
Gradle 6.4.1
JDK 1.8_144
Scan plugin 3.1.1 is among the dependencies of a plugin of ours. That plugin applies the scan plugin when it sees a major version of Gradle <6. It also configures the plugin from the root project if the BuildScan extension is present. I can see plugin 3.1.1 as a dependency in the buildscript's classpath.

**Comment by ldaley** [comment]
@sacchettom does this happen only when you run with `--scan`? Or always?

**Comment by sacchettom** [comment]
@ldaley it works but raises an exception on a handler.
Configured the extension with this block after the plugin has been applied
```
void configureExtension(extension) {
    extension.with {
        buildScan {
            server = "https://gradle-***********.com"
            publishAlways()
        }
    }
}
```
Then executing the build without `--scan` arrives successfully up to publishing the scan.
Unluckily it raises an exception later. Our own plugin adds and handle to the plugin configuration in the root project, of the type
```
buildScanPublished { PublishedBuildScan scan ->
  if (condition) {
    ....
  }
}
```
The condition above is always false on my laptop so it will do nothing there, it's true on our CI systems (haven't tried it there).
`PublishedBuildScan` is imported with `import com.gradle.scan.plugin.PublishedBuildScan`
That also works as expected locally when applying the plugin from the settings file instead of using an init script.
When it's done through the init script, the build is successful but launches an exception as the very end like this:
```
WARNING: Error invoking build scan buildScanPublished action
org.gradle.api.InvalidActionClosureException: The closure 'com.*******************ProjectPlugin$_apply_closure2$_closure4$_closure15@9d6a69b' is not valid as an action for argument 'com.gradle.scan.plugin.internal.a$3@4d1caf70'. It should accept no parameters, or one compatible with type 'com.gradle.scan.plugin.internal.a$3'. It accepts (com.gradle.scan.plugin.PublishedBuildScan).
        at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:76)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:105)
        at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:166)
        at com.gradle.scan.plugin.internal.api.b.a(SourceFile:47)
        at com.gradle.scan.plugin.internal.api.f.a(SourceFile:5)
        at com.gradle.scan.plugin.internal.f.c.d.a(SourceFile:72)
        at com.gradle.scan.plugin.internal.a.a(SourceFile:714)
        at com.gradle.scan.plugin.internal.e.a$a.a(SourceFile:21)
        at org.gradle.internal.scan.eob.DefaultBuildScanEndOfBuildNotifier.fireBuildComplete(DefaultBuildScanEndOfBuildNotifier.java:35)
        at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:43)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:51)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:45)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:50)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
        at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:80)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:31)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:42)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:28)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:87)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:55)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:60)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:38)
        at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:68)
        at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:38)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:37)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:60)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:32)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:41)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:48)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:32)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:68)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by ldaley** [comment]
@sacchettom this is a classloading problem, and is pretty nasty.

Each init script has its own classloader. When you load the plugin through that loader, it's not in the classloader hierarchy for the build scripts. So your `PublishedBuildScan` reference in your build script is to a _different class_ than what the plugin is using as far as the JVM is concerned.

You either need to move your `buildScanPublished` to the init script, or don't reference any types here and rely on Groovy's dynamic typing, or use Kotlin's GroovyBuilder if using Kotlin.

**Comment by sacchettom** [comment]
@ldaley thanks for your input. What about the issue with `--gradle` loading the newer plugin instead? I could of course use a project or system property as a workaround to manually trigger the scan, but if it's identified as a bug I'd rather wait for the fix to come and stick to the standard command line options.

**Comment by ldaley** [comment]
@sacchettom In your init script, can you please replace `settingsEvaluated {` with `beforeSettings {`. That should resolve it for you, but it's difficult to say definitively without knowing which code is where.

**Comment by ljacomet** [comment]
Closing as obsolete.
