### ISSUE TITLE
C++ compilation gets an error when you run it for Japanese version of Microsoft Visual Studio 2019

### ISSUE THREAD

**Issue by MamoruAsagami** [gradle/gradle#13339]
### Expected Behavior
It should compile a source code.

### Current Behavior
Any try of compilation gets the following error.
/*
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 't'.
> com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 16 column 39 path $[0].description

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
... (omitted) ...
Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 16 column 39 path $[0].description
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1559)
	at com.google.gson.stream.JsonReader.skipQuotedValue(JsonReader.java:1109)
	at com.google.gson.stream.JsonReader.skipValue(JsonReader.java:1252)
	at org.gradle.nativeplatform.toolchain.internal.msvcpp.version.CommandLineToolVersionLocator.readInstall(CommandLineToolVersionLocator.java:129)
	at org.gradle.nativeplatform.toolchain.internal.msvcpp.version.CommandLineToolVersionLocator.parseJson(CommandLineToolVersionLocator.java:100)
	... 147 more
 */

### Steps to Reproduce 
"gradle tasks" command with build.gradle below:

plugins {id 'cpp-application'}
version = '1.2.1'
application {
}
### Your Environment
Microsoft Visual Studio 2019 Japanese version
Windows 10 Home edition Japanese version

### Fix up
If you apply the following change, it works perfectly.
org.gradle.nativeplatform.toolchain.internal.msvcpp.version.CommandLineToolVersionLocator(Line: 58)
before: List<String> args = Lists.newArrayList("-all", "-legacy", "-format", "json");
    after: List<String> args = Lists.newArrayList("-all", "-legacy", "-format", "json", "-utf8");

It seems the default output character code of Microsoft Visual Studio/Installer/vswhere.exe is MS932(Shift_JIS) rather than UTF-8 unless "-utf8" is specified.

**Comment by lacasseio** [comment]
Thanks for this great issue. Usually, native issues are handled on https://github.com/gradle/gradle-native. I'm sure someone from the Gradle team can move the issue. I will consider this as part of the [Nokee plugins](https://nokee.dev).
