### ISSUE TITLE
C++ gets an error when you run it with Japanese version of Windows 10

### ISSUE THREAD

**Issue by MamoruAsagami** [gradle/gradle#13338]
<!--- 
Please follow the instructions below. 
We receive dozens of issues every week, so to stay productive, we will close issues that don't provide enough information. 

### Expected Behavior
C++ compiler should run.

### Current Behavior
/*
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 't'.
> com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 16 column 39 path $[0].description
...
<omitted some lines>
...
Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 16 column 39 path $[0].description
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1559)
	at com.google.gson.stream.JsonReader.skipQuotedValue(JsonReader.java:1109)
	at com.google.gson.stream.JsonReader.skipValue(JsonReader.java:1252)
	at org.gradle.nativeplatform.toolchain.internal.msvcpp.version.CommandLineToolVersionLocator.readInstall(CommandLineToolVersionLocator.java:129)
	at org.gradle.nativeplatform.toolchain.internal.msvcpp.version.CommandLineToolVersionLocator.parseJson(CommandLineToolVersionLocator.java:100)
	... 147 more

### Context
I'm trying to compile C++ source code.

### Steps to Reproduce 
plugins {id 'cpp-application'}
version = '1.2.1'
application {
}

### Your Environment
Microsoft Visual Studio 2019
Windows 10 Japanese version

### Fix up
If you apply the following change, it works perfectly
[t.zip](https://github.com/gradle/gradle/files/4731149/t.zip)
.
org.gradle.nativeplatform.toolchain.internal.msvcpp.version.CommandLineToolVersionLocator(Line:58)
before: List<String> args = Lists.newArrayList("-all", "-legacy", "-format", "json");
   after: List<String> args = Lists.newArrayList("-all", "-legacy", "-format", "json", "-utf8");
        
Unless "-utf8" is specified, Microsoft Visual Studio/Installer/vswhere.exe's output seems coded in local character code which is MS932(Shift_JIS) rather than UTF-8.

**Comment by MamoruAsagami** [comment]
Description didn't show up.  I will report again
