### ISSUE TITLE
ApiGroovyCompiler throws NoClassDefFoundError due to incorrect user classpath

### ISSUE THREAD

**Issue by ldaley** [gradle/gradle#13358]
I was in the middle of extracting some code from core to a new module in gradle/gradle, and got the following exception during a Groovy compile:

```
Caused by: java.lang.NoClassDefFoundError: org.gradle.internal.buildoption.BooleanBuildOption
	at groovyjarjarasm.asm.signature.SignatureReader.parseType(SignatureReader.java:206)
	at groovyjarjarasm.asm.signature.SignatureReader.accept(SignatureReader.java:122)
	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:277)
```

As I'm moving modules around, there are classpath problems. I think the error is legitimate, but the failure mode is poor. There is nothing to tell me about the problematic use site. There are no other diagnostics from “the compiler”.

This can be reproduced with https://github.com/gradle/gradle/tree/ldaley/groovy-api-compiler-bug, by running `:enterprise:compileIntegTestGroovy`.

### Expected Behavior

Error diagnostics providing some insight into _where_ the problem is at least.

### Current Behavior
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':enterprise:compileIntegTestGroovy'.
> org.gradle.internal.buildoption.BooleanBuildOption
```

**Comment by ljacomet** [comment]
This requires a change to the Groovy compiler, like identifying what it is trying to compile. There is nothing that can be done in Gradle alone for this.
