### ISSUE TITLE
cache executionHistory.bin might be corrupted

### ISSUE THREAD

**Issue by rhibiscusc** [gradle/gradle#13381]
gradle build failed with "Could not read entry ':stopA' from cache executionHistory.bin " exception.

using gradle 5.6.4

### Expected Behavior

no exception like "Could not read entry ':stopA' from cache executionHistory.bin "  should be thrown 

### Current Behavior

the build failed with the following exception

[09:46:12]	FAILURE: Build failed with an exception.
[09:46:12]	Total time to verify server down: 0 seconds
[09:46:12]	
[09:46:12]	* What went wrong:
[09:46:12]	Execution failed for task ':stopA'.
[09:46:12]	> Could not read entry ':stopA' from cache executionHistory.bin (/data/master/.gradle/5.6.4/executionHistory/executionHistory.bin).
[09:46:12]	
[09:46:12]	* Try:
[09:46:12]	
[09:46:12]	Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[09:46:12]	
[09:46:12]	> Task :stopA FAILED
[09:46:12]	* Exception is:
[09:46:12]	org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':stopSearchbox'.
[09:46:12]	:stopA
[09:46:12]		at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
[09:46:12]		at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
[09:46:12]	
[09:46:12]		at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
[09:46:12]		at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
[09:46:12]		at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
[09:46:12]		at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
[09:46:12]		at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
[09:46:12]		at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
[09:46:12]		at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
[09:46:12]		at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
[09:46:12]		at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
[09:46:12]		at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
[09:46:13]	Execution failed for task ':stopA'. org.gradle.api.UncheckedIOException: Could not read entry ':stopA' from cache executionHistory.bin (/data/master/.gradle/5.6.4/executionHistory/executionHistory.bin).
[09:46:12]		at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
[09:46:12]		at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
[09:46:12]		at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
[09:46:12]		at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
[09:46:12]	Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
[09:46:12]		at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
[09:46:12]	Use '--warning-mode all' to show the individual deprecation warnings.
[09:46:12]		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
[09:46:12]	See https://docs.gradle.org/5.6.4/userguide/command_line_interface.html#sec:command_line_warnings
[09:46:12]	4 actionable tasks: 4 executed
[09:46:12]		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
[09:46:12]		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
[09:46:12]		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
[09:46:12]		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
[09:46:12]		at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[09:46:12]		at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[09:46:12]		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[09:46:12]		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[09:46:12]		at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[09:46:12]		at java.lang.Thread.run(Thread.java:748)
[09:46:12]	Caused by: org.gradle.api.UncheckedIOException: Could not read entry ':stopA' from cache executionHistory.bin (/data/master/.gradle/5.6.4/executionHistory/executionHistory.bin).
[09:46:12]		at org.gradle.cache.internal.btree.BTreePersistentIndexedCache.get(BTreePersistentIndexedCache.java:137)
[09:46:12]		at org.gradle.cache.internal.DefaultMultiProcessSafePersistentIndexedCache$1.create(DefaultMultiProcessSafePersistentIndexedCache.java:48)
[09:46:12]		at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.readFile(DefaultFileLockManager.java:194)
[09:46:12]		at org.gradle.cache.internal.DefaultCacheAccess$UnitOfWorkFileAccess.readFile(DefaultCacheAccess.java:406)
[09:46:12]		at org.gradle.cache.internal.DefaultMultiProcessSafePersistentIndexedCache.get(DefaultMultiProcessSafePersistentIndexedCache.java:45)
[09:46:12]		at org.gradle.cache.internal.AsyncCacheAccessDecoratedCache$1.create(AsyncCacheAccessDecoratedCache.java:47)
[09:46:12]		at org.gradle.cache.internal.CacheAccessWorker$1.call(CacheAccessWorker.java:81)
[09:46:12]		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[09:46:12]		at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[09:46:12]		at org.gradle.cache.internal.CacheAccessWorker$2.run(CacheAccessWorker.java:180)
[09:46:12]		at org.gradle.internal.Factories$1.create(Factories.java:26)
[09:46:12]		at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:223)
[09:46:12]		at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:204)
[09:46:12]		at org.gradle.cache.internal.CacheAccessWorker.flushOperations(CacheAccessWorker.java:175)
[09:46:12]		at org.gradle.cache.internal.CacheAccessWorker.run(CacheAccessWorker.java:145)
[09:46:12]		... 6 more
[09:46:12]	Caused by: org.gradle.api.UncheckedIOException: java.io.EOFException: Unexpected EOF
[09:46:13]		at org.gradle.cache.internal.btree.FileBackedBlockStore.read(FileBackedBlockStore.java:115)
[09:46:13]		at org.gradle.cache.internal.btree.CachingBlockStore.read(CachingBlockStore.java:100)
[09:46:13]		at org.gradle.cache.internal.btree.FreeListBlockStore.read(FreeListBlockStore.java:86)
[09:46:13]		at org.gradle.cache.internal.btree.StateCheckBlockStore.read(StateCheckBlockStore.java:67)
[09:46:13]		at org.gradle.cache.internal.btree.BTreePersistentIndexedCache$IndexBlock.get(BTreePersistentIndexedCache.java:466)
[09:46:13]		at org.gradle.cache.internal.btree.BTreePersistentIndexedCache.get(BTreePersistentIndexedCache.java:127)
[09:46:13]		... 20 more
[09:46:13]	Caused by: java.io.EOFException: Unexpected EOF
[09:46:13]		at org.gradle.internal.io.StreamByteBuffer.readFrom(StreamByteBuffer.java:115)
[09:46:13]		at org.gradle.internal.io.StreamByteBuffer.of(StreamByteBuffer.java:78)
[09:46:13]		at org.gradle.cache.internal.btree.BTreePersistentIndexedCache$DataBlock.read(BTreePersistentIndexedCache.java:701)
[09:46:13]		at org.gradle.cache.internal.btree.FileBackedBlockStore$BlockImpl.read(FileBackedBlockStore.java:241)
[09:46:13]		at org.gradle.cache.internal.btree.FileBackedBlockStore.read(FileBackedBlockStore.java:110)
[09:46:13]		... 25 more
[09:46:13]

### Context

this is an intermittent issue we encounter. greatly impact our build pipeline success rate.

### Steps to Reproduce 

intermittent issue. not reproducible currently.

### Your Environment

Build scan URL:

**Comment by lptr** [comment]
Can you reproduce this with a more recent Gradle version, even if only intermittently? It's unlikely that we'd release a patch release even if we found a bug, and it might already be gone with a newer release.

**Comment by rhibiscusc** [comment]
reasonable. It might be significant effort for us to upgrade to current release version v6.5. It will take a while for me to report back here.

**Comment by lptr** [comment]
Understood. Let's close this for the time being. Please reopen if after the upgrade the problem persists.
