### ISSUE TITLE
Compile scala error

### ISSUE THREAD

**Issue by idontusenumbers** [gradle/gradle#13414]
We use scala for our unit tests. While trying to upgrade from Gradle `5.4.1` to `6.4` or `6.5` I get this gradle error:
```
Execution failed for task ':core:compileTestScala'.
> Cannot find any files starting with compiler-bridge in [/Users/charlie.hayes/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-compiler/2.13.2/c6cfcfc333a4c37a3445aec11a90a22bb1b8f35b/scala-compiler-2.13.2.jar, /Users/charlie.hayes/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-reflect/2.13.2/2a6dd4989a27aba0dd43bc297045cff633d70064/scala-reflect-2.13.2.jar, /Users/charlie.hayes/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-library/2.13.2/280d2a51b3130cf869cb416404b2c0e44e433f3e/scala-library-2.13.2.jar, /Users/charlie.hayes/.gradle/caches/modules-2/files-2.1/org.jline/jline/3.14.1/eb84f44d0f8494a3d3b6200f69b58f9f8104ac9f/jline-3.14.1.jar, /Users/charlie.hayes/.gradle/caches/modules-2/files-2.1/net.java.dev.jna/jna/5.3.1/6eb9d07456c56b9c2560722e90382252f0f98405/jna-5.3.1.jar]
```
With stacktrace:

```
Caused by: java.lang.IllegalStateException: Cannot find any files starting with compiler-bridge in [/Users/charlie.hayes/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-compiler/2.12.11/b93a7407c66f94ebe76c25a1fef17b0b8ecdaf1/scala-compiler-2.12.11.jar, /Users/charlie.hayes/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-reflect/2.12.11/7695010d1f4309a9c4b65be33528e382869ab3c4/scala-reflect-2.12.11.jar, /Users/charlie.hayes/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-library/2.12.11/1a0634714a956c1aae9abefc83acaf6d4eabfa7d/scala-library-2.12.11.jar, /Users/charlie.hayes/.gradle/caches/modules-2/files-2.1/org.scala-lang.modules/scala-xml_2.12/1.0.6/e22de3366a698a9f744106fb6dda4335838cf6a7/scala-xml_2.12-1.0.6.jar]
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory.findFile(ZincScalaCompilerFactory.java:192)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory.getCompiler(ZincScalaCompilerFactory.java:102)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFacade.execute(ZincScalaCompilerFacade.java:47)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFacade.execute(ZincScalaCompilerFacade.java:31)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkAction.execute(AbstractDaemonCompiler.java:135)
```

cut-down build.gradle:
```
plugins {
    id 'scala'
}
dependencies {
    testImplementation "org.scala-lang:scala-library:2.13.2"
    scalaCompiler "org.scala-lang:scala-compiler:2.13.2}"
}
```
I've tried adding a normal `implementation` with the scala library, gradle 6.4, scala 2.12, pinning newer zinc, deleting my `~/.gradle`, `gradle clean`, and many other things. Searching google for the error didn't help me much.

**Comment by jaisonpjohn** [comment]
Any work arounds for this issue?

**Comment by SheliakLyr** [comment]
Adding scala-library to `implementation` *should* work. It does for me. `testImplementation` is not enough enough because automatic `scalaClasspath` configuration does not use test dependencies.

Workaround idea: you can try to setup scalaClasspath by adding required dependencies. I think that gradle adds by default:
```
                "org.scala-sbt:compiler-bridge_" + scalaMajorMinorVersion + ":" + zincVersion
                "org.scala-sbt:compiler-interface:" + zincVersion
```
I guess scalaCompiler in your example is a configuration that might be used for this.

Disclaimer: **Not tested**. Just sharing an idea.
