### ISSUE TITLE
Could not transfer artifact to maven repository  org.apache.http.NoHttpResponseException: failed to respond

### ISSUE THREAD

**Issue by zayacV** [gradle/gradle#13537]
I have multi module gradle project
I want upload one of my module - jar-file,  to the our company maven repository.
When I run task deploy( uploadArchives) i get faile -

> Could not transfer artifact com.pb.ppls:PplsGeneric:pom:0.0.1-20200619.133519-31 from/to remote (http://our.company.repo/content/repositories/snapshots/): our.company.repo:80 failed to respond

 The same situation with  other modules of my project
I get error with gradle 6.4. When I come back to version 4.8, all work perfectly. java version "1.8.0_251"  for both case
This is stacktrace

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':PplsGeneric:deploy'
Caused by: org.gradle.api.artifacts.PublishException: Could not publish configuration 'archives'
Caused by: org.gradle.api.GradleException: Failed to deploy artifacts: Could not transfer artifact com.pb.ppls:PplsGeneric:pom:0.0.1-20200619.133519-31 from/to remote (http://our.company.repo/content/repositories/snapshots/): our.company.repo:80 failed to respond
	at org.gradle.api.publication.maven.internal.action.AbstractMavenPublishAction.publish(AbstractMavenPublishAction.java:112)
	at org.gradle.api.publication.maven.internal.action.MavenDeployAction.publish(MavenDeployAction.java:36)
	at org.gradle.api.publication.maven.internal.deployer.AbstractMavenResolver.execute(AbstractMavenResolver.java:137)
	at org.gradle.api.publication.maven.internal.deployer.AbstractMavenResolver.publish(AbstractMavenResolver.java:130)
	at org.gradle.api.publication.maven.internal.deployer.AbstractMavenResolver.publish(AbstractMavenResolver.java:109)
	at org.gradle.api.publication.maven.internal.deployer.BaseMavenDeployer.publish(BaseMavenDeployer.java:36)
	at org.gradle.internal.component.external.ivypublish.DefaultArtifactPublisher.publish(DefaultArtifactPublisher.java:77)
	at org.gradle.api.internal.artifacts.ivyservice.IvyContextualArtifactPublisher.lambda$publish$0(IvyContextualArtifactPublisher.java:39)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:139)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:64)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:41)
	at org.gradle.api.internal.artifacts.ivyservice.IvyContextualArtifactPublisher.publish(IvyContextualArtifactPublisher.java:38)
	at org.gradle.api.tasks.Upload.upload(Upload.java:66)
	... 186 more
Caused by: org.sonatype.aether.deployment.DeploymentException: Failed to deploy artifacts: Could not transfer artifact com.pb.ppls:PplsGeneric:pom:0.0.1-20200619.133519-31 from/to remote (http://our.company.repo/content/repositories/snapshots/): our.company.repo:80 failed to respond
	at org.sonatype.aether.impl.internal.DefaultDeployer.deploy(DefaultDeployer.java:280)
	at org.sonatype.aether.impl.internal.DefaultDeployer.deploy(DefaultDeployer.java:211)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.deploy(DefaultRepositorySystem.java:443)
	at org.gradle.api.publication.maven.internal.action.MavenDeployAction.publishArtifacts(MavenDeployAction.java:71)
	at org.gradle.api.publication.maven.internal.action.AbstractMavenPublishAction.publish(AbstractMavenPublishAction.java:110)
	... 198 more
Caused by: org.sonatype.aether.transfer.ArtifactTransferException: Could not transfer artifact com.pb.ppls:PplsGeneric:pom:0.0.1-20200619.133519-31 from/to remote (http://our.company.repo/content/repositories/snapshots/): our.company.repo:80 failed to respond
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:951)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:941)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$PutTask.run(WagonRepositoryConnector.java:837)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.put(WagonRepositoryConnector.java:467)
	at org.sonatype.aether.impl.internal.DefaultDeployer.deploy(DefaultDeployer.java:274)
	... 202 more
Caused by: org.apache.maven.wagon.TransferFailedException: our.company.repo:80 failed to respond
	at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:654)
	at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:557)
	at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:539)
	at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:533)
	at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:513)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$PutTask.run(WagonRepositoryConnector.java:811)
	... 204 more
Caused by: org.apache.http.NoHttpResponseException: our.company.repo:80 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:838)
	at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:600)
	... 209 more

```
This is my parent build.gtadle

```
buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath 'org.hidetake:gradle-ssh-plugin:2.10.1'
  }
}

plugins {
  id 'io.spring.dependency-management' version '1.0.6.RELEASE'
}


allprojects {
    apply plugin: 'eclipse-wtp'
    apply plugin: 'maven'
    apply plugin: 'project-report'
	apply plugin: 'org.hidetake.ssh'
	apply plugin: 'io.spring.dependency-management'
    apply plugin: 'maven-publish'    

	dependencyManagement {
	  imports {
	    mavenBom "org.springframework:spring-framework-bom:5.1.2.RELEASE"	    
	    mavenBom "org.hibernate.ogm:hibernate-ogm-bom:5.4.0.Final"
	    mavenBom "org.springframework.security:spring-security-bom:5.1.1.RELEASE"	    
	    mavenBom "com.fasterxml.jackson:jackson-bom:2.9.8"	    
	  }
	}

    version = '0.0.1-SNAPSHOT'
    group = 'com.pb.ppls'

    repositories {     
       mavenLocal()
       maven { url "http://our.company.repo/content/repositories/releases/" }
       maven { url "http://our.company.repo/content/repositories/snapshots/" }
       maven { url "http://our.company.repo/content/repositories/thirdparty/" }
       jcenter()
    }
}

subprojects {
    task deploy (type : Upload) {
   repositories {
       configuration = configurations.archives
   	uploadDescriptor = true
   	mavenDeployer {
            repository(url: "http://our.company.repo/content/repositories/snapshots/"){
           	authentication(userName: getProperty('systemProp.http.proxyUser') , password: getProperty('systemProp.http.proxyPassword'))            
           }
        }
   }
 }

 deploy.dependsOn.add(build)
 def date
 deploy.doFirst({ date = new Date().getTime()
 				 println "######################### Start uploadArchives to NEXUS !  #########################"
 				 })
 deploy.doLast({println "#########################  Finish uploadArchives to NEXUS at  "+(new Date().getTime() - date)+" ms !!! #########################"})
}

```

This is build.gtadle of my module

```
plugins {
   id 'java-library'
}

dependencies {
	compile "org.springframework:spring-core"
	compile "org.springframework:spring-context"
	compile "org.springframework:spring-context-support"
	compile "org.springframework:spring-orm"
	compile "org.springframework.security.oauth:spring-security-oauth2:2.3.3.RELEASE"
	compile "org.springframework.data:spring-data-redis:2.1.1.RELEASE", withoutLog
    compile "org.springframework.data:spring-data-cassandra:2.1.4.RELEASE", withoutLog

	compile "javax:javaee-web-api:8.0"
	compile "commons-io:commons-io:2.6"
	
    compile "com.pb.util.bpn:com.pb.util.bpn:${property('com.pb.util.bpn.version')}", withoutArtifacts

    compile "org.hibernate:hibernate-core"
    compile "org.hibernate:hibernate-validator:${property('hibernate.version')}"
    compile "org.hibernate.javax.persistence:hibernate-jpa-2.1-api:1.0.2.Final"

    compile "com.fasterxml.jackson.core:jackson-core"
    compile "com.fasterxml.jackson.core:jackson-databind"
    compile "com.fasterxml.jackson.core:jackson-annotations"
    compile "com.fasterxml.jackson.datatype:jackson-datatype-jsr310"
    compile 'com.datastax.cassandra:cassandra-driver-core:3.2.0'
        
    testImplementation 'junit:junit:4.12'
    testImplementation 'com.zaxxer:HikariCP:2.6.1'
    testImplementation 'org.apache.httpcomponents:httpasyncclient:4.1.3'
    testImplementation "org.postgresql:postgresql:${property('postgresDriver.version')}"    
}


jar {
    manifest {
        attributes('Implementation-Title': project.name,
                   'Implementation-Version': project.version)
    }
}


afterEvaluate {
    publishing {
        publications {
            Generic(MavenPublication) {
                from components.java
            }
        }

        repositories {
            maven {
                def releasesRepoUrl = "http://our.company.repo/content/repositories/releases/"
                def snapshotsRepoUrl = "http://our.company.repo/content/repositories/snapshots/"
                url = version.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
                credentials {
                    username = getProperty('systemProp.http.proxyUser')
                    password = getProperty('systemProp.http.proxyPassword')
                }
            }
        }
    }
}
```
 
As you can see in build.gradle of module I decide try to use Maven Publish Plugin, but i have the same problem with it. 
For my opinion, this problem is related with HttpClient, but what can i do in this situation ?

**Comment by tigerich** [comment]
hit the very same issue with `Sonatype Nexus Repository ManagerOSS 3.30.0-01` installed via docker.

anyone has an update of this? if no solution I would have to fall back to nexus 2.0 again.

**Comment by ThorJay** [comment]
any suggetion for this? the same issue happened on me;I use maven-publish plugin with Gradle 7.0+ to upload file to Nexus 3，the  'failed to respond' log will show;but i use maven plugin with Gradle 6.5, it success erveytime;
> id：'maven-publish'
> gradle-7.3-rc-3-bin
> com.android.tools.build:gradle:7.0.3
> Nexus:nexus-3.35.0-02

**Comment by mdres** [comment]
This also started to happen to us when we upgraded to gradle 7.4.

Not only happens on publishing, but also sometimes (although rarer) on dependency resolution:
```
            > Could not resolve com.google.code.gson:gson-parent:2.8.6.
               > Could not resolve com.google.code.gson:gson-parent:2.8.6.
                  > Could not get resource 'https://****/com/google/code/gson/gson-parent/2.8.6/gson-parent-2.8.6.pom'.
                     > Could not HEAD 'https://****/com/google/code/gson/gson-parent/2.8.6/gson-parent-2.8.6.pom'.
                        > ****:443 failed to respond
```
