### ISSUE TITLE
Unable to download gradle zip by using  gradlew

### ISSUE THREAD

**Issue by gudipudipradeep** [gradle/gradle#13637]
When we are running following command we are getting issue.
`bash -x gradlew clean`
we can able to download the url using curl.
Downloading https://xx-na.zz.com/artifactory/yyy-maven-stable-local/gradle/gradle-4.4-all.zip

`java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
        at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2142)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
        at org.gradle.wrapper.Download.download(Download.java:51)
        at org.gradle.wrapper.Install$1.call(Install.java:62)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
`
But I haven't added any proxy for this system and check the proxy configuration also.
by using 
env | grep -i proxy
printenv

please help on this

I tried to solve the following way by adding as env variables.
jdk.http.auth.tunneling.disabledSchemes=
jdk.http.auth.proxying.disabledSchemes=
export JAVA_OPTS='-Djdk.http.auth.tunneling.disabledSchemes="" -Djdk.http.auth.proxying.disabledSchemes=""'
but not working for me.

**Comment by ljacomet** [comment]
This is likely a proxy configuration problem. You will need to check the default of the Java installed on your machine or the network requirements of your organization.
Unfortunately, nothing can be done in Gradle for this aside from configuration - see https://docs.gradle.org/current/userguide/build_environment.html#sec:accessing_the_web_via_a_proxy
