### ISSUE TITLE
Gracefully handle symbolic links pointing to non-existing files in output directories

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1365]
Original issue: https://issues.gradle.org/browse/GRADLE-1843

**Highly voted issue: 21**

### Expected Behavior

Ignore dangling symlinks when calculating the outputs for UP-TO-DATE checking. Potentially introduce a property that allows for configuring if a symlink should be followed.

### Current Behavior

Gradle fails with an exception when a dangling symlink is found.

### Context

Gradle should handle dangling symlinks more gracefully.

### Steps to Reproduce (for bugs)

Given the following tasks:

```
task testCopy(type: Copy) {
    from "test"
    into "$buildDir/test"
}

task testSync(type: Sync) {
    from "test"
    into "$buildDir/test"
}
```

And the following file structure:

```
mkdir -p build/test
[:~/tmp/test] % ln -s ../foo build/test
[:~/tmp/test] % touch build/test/valid
[:~/tmp/test] % ln -s valid build/test/valid_link
[:~/tmp/test] % ls -l build/test test
build/test:
total 0
-rw-r--r-- 1 alpar users 0 Oct 12 11:44 file.txt
lrwxrwxrwx 1 alpar users 6 Oct 12 11:46 foo -> ../foo
-rw-r--r-- 1 alpar users 0 Oct 12 11:46 valid
lrwxrwxrwx 1 alpar users 5 Oct 12 11:46 valid_link -> valid

test:
total 0
-rw-r--r-- 1 alpar users 0 Oct 12 09:18 file.txt
```

The following exception is thrown:

```
[:~/tmp/test] 1 % ./gradlew -s testCopy
* Exception is:
org.gradle.api.GradleException: Could not list contents of '/tmp/alpar/test/build/test/foo'. Couldn't follow symbolic link.
	at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalker$1.visitFile(Jdk7DirectoryWalker.java:79)
	at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalker$1.visitFile(Jdk7DirectoryWalker.java:54)
	at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalker.walkDir(Jdk7DirectoryWalker.java:54)
	at org.gradle.api.internal.file.collections.DirectoryFileTree.walkDir(DirectoryFileTree.java:146)
	at org.gradle.api.internal.file.collections.DirectoryFileTree.visitFrom(DirectoryFileTree.java:130)
	at org.gradle.api.internal.file.collections.DirectoryFileTree.visit(DirectoryFileTree.java:115)
	at org.gradle.api.internal.file.collections.DirectoryFileTree.visitTreeOrBackingFile(DirectoryFileTree.java:111)
	at org.gradle.api.internal.file.collections.FileTreeAdapter.visitTreeOrBackingFile(FileTreeAdapter.java:114)
	at org.gradle.api.internal.changedetection.state.DefaultFileCollectionSnapshotter.visitFiles(DefaultFileCollectionSnapshotter.java:42)
	at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter.snapshot(AbstractFileCollectionSnapshotter.java:62)
	at org.gradle.api.internal.changedetection.state.DefaultFileCollectionSnapshotter.snapshot(DefaultFileCollectionSnapshotter.java:31)
	at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter.snapshot(AbstractFileCollectionSnapshotter.java:100)
	at org.gradle.api.internal.changedetection.state.DefaultFileCollectionSnapshotter.snapshot(DefaultFileCollectionSnapshotter.java:31)
	at org.gradle.api.internal.changedetection.state.OutputFilesCollectionSnapshotter.snapshot(OutputFilesCollectionSnapshotter.java:60)
	at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapshotTaskStateChanges.buildSnapshots(AbstractNamedFileSnapshotTaskStateChanges.java:85)
	at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapshotTaskStateChanges.<init>(AbstractNamedFileSnapshotTaskStateChanges.java:53)
	at org.gradle.api.internal.changedetection.rules.OutputFilesTaskStateChanges.<init>(OutputFilesTaskStateChanges.java:31)
	at org.gradle.api.internal.changedetection.rules.TaskUpToDateState.<init>(TaskUpToDateState.java:54)
	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates(DefaultTaskArtifactStateRepository.java:162)
	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.isUpToDate(DefaultTaskArtifactStateRepository.java:82)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:233)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:74)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:55)
	at org.gradle.execution.taskgraph.ParallelTaskPlanExecutor.process(ParallelTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:186)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:183)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:33)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:112)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:92)
	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:79)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:51)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:59)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.HintGCAfterBuild.execute(HintGCAfterBuild.java:44)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:293)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
```

**Comment by gaganis** [comment]
Hello all!

## Background

I have given a shot to this issue but I was not able to reach a fix I was happy with.

Changing Jdk7DirectoryWalker to not throw exception when encountering broken(dangling) symlinks is pretty straightforward.

The problem lies in the fact we want to only ingore for UP-TO-DATE as is both described in the issue description and in how I undestand the problem more generally.

The above means that we need a way to "parameterize" how the DirectoryWalker behaves when it is called from the UpToDateTask.

This has proved to be deceptively difficult and non-straightforward.  I must admit that I was unable to reach a good understanding of what goes on bwtween  UpToDateTask and the walker. I had a hint of the challenge when I saw the stack trace being 17 levels deep between the two classes.

I made two efforts to tackle the problem with an _Ariadne's thread_ approach, one adding a boolean parameter and the other adding a function to the Visitor interface but even after changing a very high number of files they both reached a dead end.

## Questions 

It would be really helpful if I got a better understanding of how the area of snapshotting works, is wired together and I was wondering:
- Are there any design documents that provide this information?
- Are there any other issues where this area was discussed, which we might take a look at to get a better understanding?
- Maybe someone could write a few tips to help us understand this area

Thanks!
Giorgos

**Comment by KidDaedalus** [comment]
I'd just like to offer that in our large multi-project build this bug has forced us to write non-incremental broken symlink cleaning tasks like this one (written in Kotlin):

Perhaps it will be of use to others who grapple with this issue.

```kotlin
import org.gradle.api.DefaultTask
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.TaskAction
import java.io.File
import kotlin.collections.*
import java.nio.file.Files
import java.nio.file.Path
/**
 * This task type exists to work around Gradle following broken symlinks during task inputs/outputs checks and dying
 * if those symlinks are broken
 *
 * Therefore this task cannot itself be incremental or it would invoke the same behavior it seeks to work around
 */
open class CleanBrokenSymlinksTask : DefaultTask() {
    @Internal
    val directoriesToClean : MutableList<File> = mutableListOf()
    /**
     * Adds a directory to be cleaned of broken symlinks
     */
    fun clean(dir: File) {
        directoriesToClean.add(dir)
    }
    /**
     * Adds a directory to be cleaned of broken symlinks
     */
    fun clean(dir: String) {
        clean(project.file(dir))
    }
    @TaskAction
    fun cleanSymlinks() {
        val brokenLinks : List<Path> = directoriesToClean
                .filter { it.exists() }
                .flatMap { it.listFiles().toList() }
                .map { it.toPath() }
                .filter { path -> Files.isSymbolicLink(path) && !Files.exists(path) }
        brokenLinks.forEach {
            try {
                logger.info("Deleting broken symlink '$it'")
                Files.delete(it)
            } catch (e : Exception) {
                logger.warn("Couldn't delete broken symlink '$it' ", e)
            }
        }
    }
}
```

Personally I'd be super happy, upon encountering a broken symlink, an up-to-date check marked the task as out-of-date. I haven't looked through the source or otherwise experimented with this... but could that be done in a catch() block for the up-to-date check?

**Comment by rkrisztian** [comment]
I think the real problem is that the Copy task comes with an **incorrect UP-TO-DATE check configuration**. I'm using Gradle 4.3 and the following is my test project:

```groovy
task generateConfigFile(type: Copy) {
	from '.'
	into '.'
	include 'config.file.template'
	rename { fileName -> 'config.file' }
	expand a: 'b'
}

task clean(type: Delete) {
	delete 'config.file'
}

// =============
// For debugging
// =============
private void printTaskDetails(Task task) {
	StringBuffer taskDetails = new StringBuffer()
	taskDetails << """-------------
name: $task.name group:$task.group : $task.description
conv: $task.convention.plugins
inputs:
"""
	task.inputs.files.each { it ->
		taskDetails << "\t${it.absolutePath}\n"
	}
	taskDetails << "outputs:\n"
	task.outputs.files.each { it ->
		taskDetails << "\t${it.absolutePath}\n"
	}
	taskDetails << "-------------\n"
	println taskDetails
}

gradle.taskGraph.afterTask { task ->
	printTaskDetails task
}
```

Then I execute the following commands:

```none
$ gw generateConfigFile
(...)
> Task :generateConfigFile 
-------------
name: generateConfigFile group:null : null
conv: [:]
inputs:
        /home/rkrisztian/projects/gradletest/config.file.template
outputs:
        /home/rkrisztian/projects/gradletest
-------------



BUILD SUCCESSFUL in 4s
1 actionable task: 1 executed

$ ln -s /a/b build/broken.symlink

$ gw generateConfigFile
(...)
> Task :generateConfigFile FAILED
-------------
name: generateConfigFile group:null : null
conv: [:]
inputs:
        /home/rkrisztian/projects/gradletest/config.file.template
outputs:
        /home/rkrisztian/projects/gradletest
-------------



FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of output files for task ':generateConfigFile' property 'destinationDir' during up-to-date check.
> Could not list contents of '/home/rkrisztian/projects/gradletest/build/broken.symlink'. Couldn't follow symbolic link.
(...)
```

I think it is just plain wrong to define the whole directory as an output, when in fact it should be a single file. Please correct me if I'm wrong.

**Comment by rkrisztian** [comment]
One very ugly workaround would be the use of the following task, and then manually registering outputs for each copy task (warning: it uses internal classes!). I guess a more intelligent solution would calculate the output files by executing the `rename` callback for each input file, or just let the user define the outputs...

```groovy
import org.gradle.api.internal.file.copy.CopyAction
import org.gradle.api.internal.file.copy.CopySpecInternal
import org.gradle.api.internal.file.copy.DestinationRootCopySpec
import org.gradle.api.internal.file.copy.FileCopyAction

/**
 * Like the original Copy task, but without declaring the destination dir as output. Solves the problem of breaking the build
 * due to invalid symlinks. To be used as a temporary workaround.
 */
class CopyWithCustomOutputs extends AbstractCopyTask {

	@Override
	protected CopyAction createCopyAction() {
		if (!destinationDir) {
			throw new InvalidUserDataException('No copy destination directory has been specified, use \'into\' to specify a target directory.')
		}

		new FileCopyAction(fileLookup.getFileResolver(destinationDir))
	}

	@Override
	protected CopySpecInternal createRootSpec() {
		instantiator.newInstance DestinationRootCopySpec.class, fileResolver, super.createRootSpec()
	}

	@Override
	DestinationRootCopySpec getRootSpec() {
		(DestinationRootCopySpec) super.rootSpec
	}

	File getDestinationDir() {
		rootSpec.destinationDir
	}

	void setDestinationDir(File destinationDir) {
		into destinationDir
	}

}
```

**Comment by wimdeblauwe** [comment]
I am having the same issue with the `Exec` task. I defined this class:

    class UnTar extends Exec {
      @OutputDirectory
      File destinationDir
    }

Using it like this:

    task unzipRootfs(type: UnTar, dependsOn: 'downloadProductDependencies') {
      workingDir "${buildDir}"
      commandLine 'tar'
      destinationDir file("${buildDir}/product-distribution")
      args 'xf', 'product-dependencies/rootfs.tar', '-C', "${buildDir}/product-distribution"
    }

This has the advantage that the `destinationDir` is created automatically by Gradle. However, due to the up-to-date check that fails on the dangling symlink that is part of the tar file, the build fails. As a workaround, I now manually create the output directory:

    project.file("${buildDir}/product-distribution").mkdirs();

(I also tried the Gradle Copy task with `tarTree()` but that failed untarring for some reason)

**Comment by lptr** [comment]
Plan for resolving this problem along with a few others: https://github.com/gradle/gradle/issues/9708

**Comment by paplorinc** [comment]
Fixed https://github.com/gradle/gradle/pull/9878 and https://github.com/gradle/gradle/pull/9727
