### ISSUE TITLE
System.getProperty(...) with null default value triggers NPE

### ISSUE THREAD

**Issue by catharsis** [gradle/gradle#13652]
As of https://github.com/gradle/gradle/commit/514bb62508425ff202b0d678b4c7c3e8ebf90b4b#diff-9a634a2c6cb77e7ae0ef28cbc3f230d7R435 passing `null`, or something that evaluates to `null` as the default argument to `System.getProperty()` triggers a `NullPointerException`.

### Expected Behavior

`System.getProperty()` should not throw a `NullPointerException` when `default` is `null`.
### Current Behavior

`System.getProperty()` does throw a `NullPointerException` when `default` is `null`.
### Context

We're using `System.getProperty()` to get some properties from the environment to configure some tasks, where the default value is fetched from the environment (via `System.getenv()`). If the environment variable is unset, the default value will effectively be `null`, triggering the NPE.

### Steps to Reproduce 

Do `System.getProperty('whatever', null)` in a `build.gradle`, and run a task.
### Your Environment

Relevant part of stacktrace:
```
Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project '<myproject>'.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.lambda$apply$0(DefaultScriptPluginFactory.java:133)
        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
------- 8< -------
Caused by: java.lang.NullPointerException
        at org.gradle.internal.classpath.Instrumented$SystemPropertyCallSite.call(Instrumented.java:435)
        at build_6v133y2sn0csh0hzr6jbqjs43$_run_closure7.doCall(<redacted-path-to-build.gradle>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/13674
