### ISSUE TITLE
The remote host closed an existing connection while starting the daemon

### ISSUE THREAD

**Issue by loecker-rupert** [gradle/gradle#13691]
### Expected Behavior
Call to 'gradlew --help' ends successful.

### Current Behavior
Every call to 'gradlew' fails with the same error after downloading the gradle wrapper.

```text
C:\prj\Trunk2>gradlew --stacktrace
Downloading https://services.gradle.org/distributions/gradle-6.5-all.zip
.............10%..............20%..............30%..............40%..............50%..............60%..............70%..............80%..............90%..............100%

Welcome to Gradle 6.5!

Here are the highlights of this release:
 - Experimental file-system watching
 - Improved version ordering
 - New samples

For more details see https://docs.gradle.org/6.5/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not dispatch a message to the daemon.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.launcher.daemon.client.DaemonConnectionException: Could not dispatch a message to the daemon.
        at org.gradle.launcher.daemon.client.DaemonClientConnection.dispatch(DaemonClientConnection.java:69)
        at org.gradle.launcher.daemon.client.DaemonClientConnection.dispatch(DaemonClientConnection.java:35)
        at org.gradle.launcher.daemon.client.DaemonClientInputForwarder$ForwardTextStreamToConnection.endOfStream(DaemonClientInputForwarder.java:81)
        at org.gradle.launcher.daemon.client.InputForwarder$1.run(InputForwarder.java:96)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.gradle.internal.remote.internal.MessageIOException: Could not write '/127.0.0.1:49856'.
        at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:140)
        at org.gradle.launcher.daemon.client.DaemonClientConnection.dispatch(DaemonClientConnection.java:60)
        ... 9 more
Caused by: java.io.IOException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
        at sun.nio.ch.SocketDispatcher.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:51)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:468)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeWithNonBlockingRetry(SocketConnection.java:279)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeBufferToChannel(SocketConnection.java:267)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.flush(SocketConnection.java:261)
        at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:138)
        ... 10 more


* Get more help at https://help.gradle.org
```

The message which is added to the IOException (german) means:
'An existing connection was closed by the remote host'

### Context
I try to build our project. It works for 20 other people but strangely enough not for me.

I tried the following:
- I deleted all caches several times.
- Redirect gradle cache via gradle.properties, GRADLE_USER_HOME and GRADLE_HOME.
- Different Gradle versions (4 - 6)
- Start with flag --no-daemon and --daemon
- Deactivated firewall and other network adapters

### Steps to Reproduce 
Every call to 'gradlew' failed.

### Your Environment
Build scan doesn't work and ends with the same exception as described above.

OS: Windows 10.0.18362.900

Processor: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz 2.71 GHz
31.8 GH used memory (RAM)

Gradle: 6.5 and older versions too.

Java:
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (Zulu 8.44.0.14-SA-win32) (build 1.8.0_242-b20)
OpenJDK Client VM (Zulu 8.44.0.14-SA-win32) (build 25.242-b20, mixed mode)

**Comment by lptr** [comment]
Do you have file system watching enabled? (`--watch-fs` or `org.gradle.unsafe.watch-fs=true`)?

**Comment by loecker-rupert** [comment]
No

**Comment by loecker-rupert** [comment]
Solution: Reinstalled Windows 10 ;)
