### ISSUE TITLE
OutOfMemory Exception of Gradle Listener when running large test suite

### ISSUE THREAD

**Issue by incaseoftrouble** [gradle/gradle#13723]
I'm running a large test suite of JUnit 5 `@ParameterizedTest`s with gradle (~300k randomly generated tests). When running with IntelliJ or gradle + JUnit 4 `@Theory`, these tests complete just fine. However, with JUnit 5, a daemon of gradle dies because it runs out of memory after ~30k tests. I'm running with `maxHeapSize = "16g"`, this does not affect the problem since it seems the gradle runner itself has an issue.

Output:
```
Unexpected exception thrown.
org.gradle.internal.remote.internal.MessageIOException: Could not read message from '/127.0.0.1:56714'.
        at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:94)
        at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionReceive.run(MessageHub.java:270)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.base/java.lang.StringUTF16.compress(StringUTF16.java:161)
        at java.base/java.lang.String.<init>(String.java:3651)
        at java.base/java.lang.String.<init>(String.java:294)
        at com.esotericsoftware.kryo.io.Input.readString(Input.java:466)
        at org.gradle.internal.serialize.kryo.KryoBackedDecoder.readNullableString(KryoBackedDecoder.java:150)
        at org.gradle.internal.serialize.kryo.KryoBackedDecoder.readString(KryoBackedDecoder.java:144)
        at org.gradle.api.internal.tasks.testing.worker.TestEventSerializer$DefaultTestDescriptorSerializer.read(TestEventSerializer.java:205)
        at org.gradle.api.internal.tasks.testing.worker.TestEventSerializer$DefaultTestDescriptorSerializer.read(TestEventSerializer.java:196)
        at org.gradle.internal.serialize.DefaultSerializerRegistry$TaggedTypeSerializer.read(DefaultSerializerRegistry.java:147)
        at org.gradle.internal.remote.internal.hub.DefaultMethodArgsSerializer$ArraySerializer.read(DefaultMethodArgsSerializer.java:72)
        at org.gradle.internal.remote.internal.hub.DefaultMethodArgsSerializer$ArraySerializer.read(DefaultMethodArgsSerializer.java:61)
        at org.gradle.internal.remote.internal.hub.MethodInvocationSerializer$MethodInvocationReader.readArguments(MethodInvocationSerializer.java:128)
        at org.gradle.internal.remote.internal.hub.MethodInvocationSerializer$MethodInvocationReader.read(MethodInvocationSerializer.java:123)
        at org.gradle.internal.remote.internal.hub.MethodInvocationSerializer$MethodInvocationReader.read(MethodInvocationSerializer.java:102)
        at org.gradle.internal.serialize.kryo.TypeSafeSerializer$1.read(TypeSafeSerializer.java:36)
        at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:67)
        at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:52)
        at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
<===========--> 85% EXECUTING [2m 18s]
> :test > 35462 tests completed, 30 skipped
> :test > Executing test de.tum.in.jbdd.BddTheories
```
I also got the following once:
```
Unexpected exception thrown.
java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1604)
        at org.gradle.internal.remote.internal.hub.queue.EndPointQueue.take(EndPointQueue.java:49)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:403)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:832)
Unexpected exception thrown.
java.lang.OutOfMemoryError: Java heap space
Exception in thread "Thread-145" java.lang.OutOfMemoryError: Java heap space
<===========--> 85% EXECUTING [1m 31s]
> :test > 25434 tests completed, 1359 skipped
> :test > Executing test de.tum.in.jbdd.BddTheories
```

The main gradle process does not pick up that the runner died and just idly waits for the tests to continue (I killed it after waiting for ~5 min). A .hprof file of ~500MB is created in the working directory. It lists ~120k `byte[]` objects with equally many `String` ones. The `byte[]` objects use the vast majority of memory (~500MB), the next largest type (`String`) only uses 3MB in total (see below).

![hprof](https://user-images.githubusercontent.com/13201506/86907427-48ea2580-c115-11ea-8446-020b526c0911.png)

I suspect that gradle is gathering a lot of metadata for each of the parameterized tests, which leads to a lot of memory consumption. This probably is fine in most scenarios, however it would be nice if one can turn this behaviour off for larger tests.

What makes me wonder is that the IntelliJ execution (which also keeps results) completes just fine. So there might be a leak somewhere. Additionally, the main process should probably not get stuck when one of its threads dies.

### Steps to Reproduce 

Clone [the repo](https://github.com/incaseoftrouble/jbdd/tree/upgrade) and run `gradlew test`.

### Your Environment

[Build scan](https://gradle.com/s/mvjefm3p2vl7g) (with massively reduced test suite)

**Comment by incaseoftrouble** [comment]
I poked around a little, it seems that the issue stems from the `toString` representation of the method arguments (and thus the test names) causes the issues. So probably this means that the error is on my side. However, I guess that it might make sense if the `toString` is not called eagerly?

In any case, the main gradle process should be aware that one of its children / daemons dies and notify the user (sometimes the run is just stuck without any exception).

**Comment by h908714124** [comment]
Guava has about 850k tests which run fine in maven, but in gradle the suite fails with OutOfMemoryError. I had to split the tests into smaller batches to make it work, see [here](https://github.com/jbock-java/guava/blob/master/build.gradle).

**Comment by asodja** [comment]
Adding something like this in `gradle.properties` makes it pass for me:
`org.gradle.jvmargs=-Xmx2g`.

Also to speed up tests you might want to set `maxParallelForks` in `test {}` since default is 1, e.g.: `maxParallelForks = 8`.

**Comment by ljacomet** [comment]
Sorry for the late reply!

Closing this as a question, as there does not seem to be any indication of attempting to increase the [test worker memory](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html).
Also since the reproducer branch is gone, not possible to investigate.

If you believe the issue is with Gradle, please open a new issue with an updated reproducer and indicate the different steps taken to ensure the test process has enough memory to run that many tests.
