### ISSUE TITLE
Cryptic message about daemon failure if temp directory does not exist

### ISSUE THREAD

**Issue by fejese** [gradle/gradle#1375]
Accidently noticed that in case the default temp directory (or the one specified by the ``java.io.tmpdir`` system property) does not exist, gradle fails to launch. Interestingly if it exists but not writable or even if it's a regular file, gradle has no problem (at least with the startup)

### Expected Behavior
If default temporary directory does not exist gradle should either attempt to create it or fail with a meaningful message.

### Current Behavior
If default temporary directory does not exist gradle fails to start up with the following message (when setting ``/tmp/NONEXISTENT`` as ``java.io.tempdir``:

```
15:49:43.469 [LIFECYCLE] [org.gradle.launcher.daemon.client.DefaultDaemonConnector] Starting a Gradle Daemon, 2 stopped Daemons could not be reused, use --status for details
15:49:43.493 [DEBUG] [org.gradle.launcher.daemon.client.DefaultDaemonStarter] Using daemon args: [/usr/java/jdk1.8.0_121/bin/java, -XX:MaxPermSize=256m, -XX:+HeapDumpOnOutOfMemoryError, -Xmx1024m, -Dfile.encoding=UTF-8, -Djava.io.tmpdir=/tmp/NONEXISTENT, -Duser.country=US, -Duser.language=en, -Duser.variant, -cp, /opt/gradle/gradle-3.4-rc-2/lib/gradle-launcher-3.4.jar]
15:49:43.499 [INFO] [org.gradle.launcher.daemon.client.DefaultDaemonStarter] Starting daemon process: workingDir = /tmp/gradle-3.4-rc-2/daemon/3.4-rc-2, daemonArgs: [/usr/java/jdk1.8.0_121/bin/java, -XX:MaxPermSize=256m, -XX:+HeapDumpOnOutOfMemoryError, -Xmx1024m, -Dfile.encoding=UTF-8, -Djava.io.tmpdir=/tmp/NONEXISTENT, -Duser.country=US, -Duser.language=en, -Duser.variant, -cp,/opt/gradle/gradle-3.4-rc-2/lib/gradle-launcher-3.4.jar, org.gradle.launcher.daemon.bootstrap.GradleDaemon, 3.4-rc-2]
15:49:43.522 [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'Gradle build daemon'. Working directory: /tmp/gradle-3.4-rc-2/daemon/3.4-rc-2 Command: /usr/java/jdk1.8.0_121/bin/java -XX:MaxPermSize=256m -XX:+HeapDumpOnOutOfMemoryError -Xmx1024m -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/tmp/NONEXISTENT -Duser.country=US -Duser.language=en -Duser.variant -cp /opt/gradle/gradle-3.4-rc-2/lib/gradle-launcher-3.4.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 3.4-rc-2
15:49:43.522 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Environment for process 'Gradle build daemon': {PATH=/usr/sue/bin:/opt/WinCC_OA/3.11/bin:/usr/lib64/qt-3.3/bin:/usr/NX/bin:/home/user/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/opt/bin:/acc/local/Linux/bin:/home/user/bin, HISTCONTROL=ignoredups, DTMPATH=/acc/dsc/tst/data/dtm, HISTSIZE=1000, TERM=screen, XFILESEARCHPATH=/usr/dt/app-defaults/%L/Dt, LANG=en_US.UTF-8, G_BROKEN_FILENAMES=1, GRADLE_HOME=/opt/gradle/gradle-3.4-rc-2, PLATFORM=linux_RHEL4, GRADLE_USER_HOME=/tmp/gradle-3.4-rc-2, MAIL=/var/spool/mail/user, KRB5CCNAME=FILE:/tmp/krb5cc_77880_YSWIs19249, API_ROOT=/opt/WinCC_OA/3.11/api, NXDIR=/usr/NX, STY=20602.dev, LOGNAME=user, PWD=/home/user/gradle-test, diamon_broker_url=cs-ccr-dmnpgp1:61681, LESSOPEN=||/usr/bin/lesspipe.sh %s, SHELL=/bin/bash, OS=Linux, QTINC=/usr/lib64/qt-3.3/include, CVS_RSH=ssh, SSH_TTY=/dev/pts/0, SSH_CLIENT=188.184.94.102 55912 22, TWO_TASK=dbabco, OLDPWD=/opt/gradle/gradle-3.4-rc-2, USER=user, NLS_LANG=AMERICAN_AMERICA.WE8ISO8859P1, WINDOW=15, SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass, SSH_CONNECTION=188.184.94.102 55912 188.184.77.21 22, HOSTNAME=cwe-513-vol154.cern.ch, WCCOA_DIR=/opt/WinCC_OA/3.11, QTDIR=/usr/lib64/qt-3.3, NLSPATH=/usr/dt/lib/nls/msg/%L/%N.cat, TERMCAP=<REDACTED>, DBRTPATH=/usr/errlog/../dbrt, KDEDIRS=/usr, LS_COLORS=<REDACTED>, QTLIB=/usr/lib64/qt-3.3/lib, HOME=/home/user, SHLVL=2, KDE_IS_PRELINKED=1}
15:49:43.523 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
15:49:43.525 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: Gradle build daemon.
15:49:43.539 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
15:49:43.539 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
15:49:43.539 [DEBUG] [org.gradle.launcher.daemon.bootstrap.DaemonOutputConsumer] Starting consuming the daemon process output.
15:49:43.539 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'Gradle build daemon'
15:49:43.540 [DEBUG] [org.gradle.launcher.daemon.client.DefaultDaemonStarter] Gradle daemon process is starting. Waiting for the daemon to detach...
15:49:43.545 [DEBUG] [org.gradle.launcher.daemon.bootstrap.DaemonOutputConsumer] daemon out: Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
15:49:44.570 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: DETACHED
15:49:44.572 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'Gradle build daemon' finished with exit value 0 (state: DETACHED)
15:49:44.573 [DEBUG] [org.gradle.launcher.daemon.client.DefaultDaemonStarter] Gradle daemon process is now detached.
15:49:44.573 [INFO] [org.gradle.launcher.daemon.client.DefaultDaemonStarter] An attempt to start the daemon took 1.074 secs.
15:49:44.579 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
15:49:44.581 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:49:44.581 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
15:49:44.581 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
15:49:44.581 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Unable to start the daemon process.
15:49:44.581 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] This problem might be caused by incorrect configuration of the daemon.
15:49:44.581 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] For example, an unrecognized jvm option is used.
15:49:44.581 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Please refer to the user guide chapter on the daemon at https://docs.gradle.org/3.4-rc-2/userguide/gradle_daemon.html
15:49:44.581 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Please read the following process output to find out more:
15:49:44.581 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] -----------------------
15:49:44.581 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
15:49:44.582 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
15:49:44.582 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
15:49:44.582 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
15:49:44.583 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.GradleException: Unable to start the daemon process.
15:49:44.583 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] This problem might be caused by incorrect configuration of the daemon.
15:49:44.583 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] For example, an unrecognized jvm option is used.
15:49:44.583 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Please refer to the user guide chapter on the daemon at https://docs.gradle.org/3.4-rc-2/userguide/gradle_daemon.html
15:49:44.584 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Please read the following process output to find out more:
15:49:44.584 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] -----------------------
15:49:44.584 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
15:49:44.584 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
15:49:44.584 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.bootstrap.DaemonGreeter.parseDaemonOutput(DaemonGreeter.java:34)
15:49:44.584 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startProcess(DefaultDaemonStarter.java:152)
15:49:44.584 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startDaemon(DefaultDaemonStarter.java:135)
15:49:44.584 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.client.DefaultDaemonConnector.startDaemon(DefaultDaemonConnector.java:208)
15:49:44.584 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connect(DefaultDaemonConnector.java:130)
15:49:44.584 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:127)
15:49:44.584 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:81)
15:49:44.584 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
15:49:44.584 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
15:49:44.584 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:244)
15:49:44.585 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:217)
15:49:44.585 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:33)
15:49:44.591 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
15:49:44.592 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
15:49:44.592 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
15:49:44.592 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:210)
15:49:44.596 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:174)
15:49:44.596 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.Main.doAction(Main.java:33)
15:49:44.596 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
15:49:44.597 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:49:44.597 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:49:44.597 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:49:44.597 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.lang.reflect.Method.invoke(Method.java:498)
15:49:44.597 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
15:49:44.597 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
15:49:44.597 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
15:49:44.597 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
```

### Context
This issue surfaced when our CI server passed along this ``java.io.tempdir`` property to a worker that did not have the per-build (``/tmp/<JOB-NAME>``) temporary directory created. Probably this is usually a mistake but a better feedback would be nice.

### Steps to Reproduce (for bugs)
 - clear ``$GRADLE_USER_HOME``
 - run gradle (tested with 2.14.1 and 3.4-rc-2) with passing ``-Djava.io.tempdir=/tmp/NONEXISTENT``

Note that it seems that this is only triggered if the daemon has to do _something_. Following the steps below the problem does not surface:
 - create temporary directory ``/tmp/volatile``
 - run ``gradle -Djava.io.tempdir=/tmp/volatile``
 - remove temporary directory
 - run same command again

### Your Environment
 - RHEL based linux
 - Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
 - gradle 2.14.1 / 3.4-rc-2

### Investigation
To narrow down in what step the gradle daemon fails I've set up monitoring of an empty directory and passed that as temporary directory when starting up gradle in an also empty directory. The only file that popped up was: **``gradle_fs_probing_....``**. As far as I can see this temporary file is created in [GenericFileSystem.java](https://github.com/gradle/gradle/blob/da7130f/subprojects/native/src/main/java/org/gradle/internal/nativeintegration/filesystem/services/GenericFileSystem.java)

There's is actually already a check in place whether the directory defined by ``java.io.tmpdir`` exists however if not a runtime exception is thrown which is clearly not handled with too much detail and no useful information is logged - not even in debug mode. It's called only from [FileSystemServices.createFileSystem(...)](https://github.com/gradle/gradle/blob/90d720/subprojects/native/src/main/java/org/gradle/internal/nativeintegration/filesystem/services/FileSystemServices.java#L40) to which I actually did not find any reference.

**Comment by eriwen** [comment]
Thank you very much for the well written issue @fejese! It sounds like you've dug pretty deep in the code here; would you be comfortable submitting a PR to improve this?

**Comment by fejese** [comment]
I'd like to, however I'm not sure when I will have time. Hence the issue not a PR straight away. If no one jumps on it I'll as soon as I can.

**Comment by fejese** [comment]
I've looked into this a bit further. From what I see, this might be a bit more general error reporting issue that handling one exception.

- There is actually a semi-useful message in the daemon log that I've finally discovered in ``USER_GRADLE_HOME/daemon/<gradle-ver>/daemon-<pid>.out.log``. When the build fails because the daemon could not start, maybe it would make sense to display this log file or at least point the user to it?
- Even in the damon log file there's only a short message:
```
07:56:31.413 [DEBUG] [org.gradle.launcher.daemon.bootstrap.DaemonMain] Assuming the daemon was started with following jvm opts: [-XX:MaxPermSize=256m, -XX:+HeapDumpOnOutOfMemoryError, -Xmx1
024m, -Dfile.encoding=UTF-8, -Djava.io.tmpdir=/foo/bar, -Duser.country=US, -Duser.language=en, -Duser.variant]
07:56:31.535 [ERROR] [system.err]
07:56:31.536 [ERROR] [system.err] FAILURE: Build failed with an exception.
07:56:31.539 [ERROR] [system.err]
07:56:31.539 [ERROR] [system.err] * What went wrong:
07:56:31.540 [ERROR] [system.err] Could not create service of type FileSystem using FileSystemServices.createFileSystem().
07:56:31.540 [ERROR] [system.err]
07:56:31.540 [ERROR] [system.err] * Try:
07:56:31.541 [ERROR] [system.err] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Daemon vm is shutting down... The daemon has exited normally or was terminated in response to a user interrupt.
```
- Even though the message in the daemon log suggests that ``--info`` or ``--stacktrace`` should give more output it seems that the daemon logging ignores (or does not get) these flags.

For the second problem I see and easy fix by adding the caught exceptions' messages to the default error messages in the [DefaultServiceRegistry](https://github.com/gradle/gradle/blob/da7130f/subprojects/base-services/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java) when it fails to initialise or invoke services or providers. What do you think?

For the other two problems (pointing the user to the daemon log and making sure that the daemon's logging respects the log options), I need some more time to look into and maybe it's worth breaking then into separate issues as well.

**Comment by tcfurrer** [comment]
We see a similar "Could not create service" failure signature whenever GRADLE_USER_HOME is a broken symlink on Linux.  Would the resolution on this issue also provide a less cryptic error in that case?  Or is a separate issue needed?

**Comment by SocieteCiss** [comment]
Can also happen on non-existing /var/cache/gradle
