### ISSUE TITLE
Gradle should fail early when publishing or reading invalid metadata

### ISSUE THREAD

**Issue by mkmaier** [gradle/gradle#13797]
It is possible to publish invalid metadata (possibly related to enforced platforms, see also #13699) which will cause consumers to fail in obscure ways that require debugging gradle. **It is highly likely that this is due to our own manipulation of what is published, but should still not be possible.**

### Expected Behavior
1. Gradle should **never produce invalid metadata** (see also #11047). There should be checks that prevent this, so errors will be noticed on publication.
1. Gradle should **fail fast when consuming invalid metadata**, not somewhere in the bowels of dependency resolution.

### Current Behavior
When using an enforced platform and publishing metadata, gradle can be made to publish invalid metadata when no version is specified and depedencies are manipulated manually.
When trying to consume this metadata, the build fails with a totally unhelpful NPE that I could only resolve by debugging gradle, which should never be necessary. The effects are similar to #13699, but I think the root-causes are different enough for a separate issue.

### Context
We have an enforced platform that had a typo like this: `api "com.squareup.okhttp3:okhttp-urlconnection${version}` (missing second colon) With gradle 5 and no metadata published, this was not a problem, because the version was specified again on use (which we don't usually do any more), so the platform declaration was simply unused.
When upgrading to gradle 6 and publishing metadata, this resulted in invalid metadata without a version:

        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection3.4.2"
        },

When consumed with a metadata-aware gradle version, this causes the following NPE:

	Caused by: java.lang.NullPointerException
			at org.gradle.api.internal.artifacts.ModuleComponentSelectorSerializer.writeVersionConstraint(ModuleComponentSelectorSerializer.java:88)
			at org.gradle.api.internal.artifacts.ModuleComponentSelectorSerializer.write(ModuleComponentSelectorSerializer.java:82)
			at org.gradle.api.internal.artifacts.ivyservice.modulecache.ModuleMetadataSerializer$Writer.writeVariantConstraints(ModuleMetadataSerializer.java:150)
			at org.gradle.api.internal.artifacts.ivyservice.modulecache.ModuleMetadataSerializer$Writer.writeVariants(ModuleMetadataSerializer.java:141)
			at org.gradle.api.internal.artifacts.ivyservice.modulecache.ModuleMetadataSerializer$Writer.write(ModuleMetadataSerializer.java:132)
			at org.gradle.api.internal.artifacts.ivyservice.modulecache.ModuleMetadataSerializer$Writer.write(ModuleMetadataSerializer.java:118)
			at org.gradle.api.internal.artifacts.ivyservice.modulecache.ModuleMetadataSerializer.write(ModuleMetadataSerializer.java:98)
			at org.gradle.api.internal.artifacts.ivyservice.modulecache.ModuleMetadataStore.lambda$putModuleDescriptor$0(ModuleMetadataStore.java:76)
			at org.gradle.internal.resource.local.DefaultPathKeyFileStore$1.execute(DefaultPathKeyFileStore.java:99)

### Steps to Reproduce
Sadly, I could _not_ reproduce this minimally, gradle correctly refused to publish version-less dependencies in the following example:

	plugins {
		id 'java-platform'
		id 'maven-publish'
	}

	javaPlatform {
		allowDependencies()
	}

	dependencies {
		constraints {
			api 'com.squareup.okhttp3:okhttp-urlconnection3.4.2' // <<< intentionally wrong!
		}
	}

	publishing {
		publications {
			maven(MavenPublication) {
				groupId = 'gradle'
				artifactId = 'metadata'
				version = '1.0'

				from components.javaPlatform
			}
		}
	}

	tasks.named('wrapper', Wrapper).configure {
		gradleVersion = '6.2.2'
	}

**Comment by jamesbassett** [comment]
We ran into the same issue when incorrectly specifying a constraint without a version for an artifact that was already defined via an imported platform. It published fine, but blew up with the same NPE when trying to consume the artifact.

**Comment by pedrolamarao** [comment]
I have arrived here from a Google search on a Gradle stack trace. We are precisely making changes on how our product declares internal dependencies. We are still trying to figure out what rule we have violated. My best guess is that it has something to do with our attempt to centralize dependency version in an internal private "platform" so that our products components may configure dependencies without versions -- including the public "platform" meant for user consumption.

**Comment by msiemens** [comment]
I had the same issue with a multi-project build with Kotlin where I followed the example in https://docs.gradle.org/current/samples/sample_building_kotlin_applications_multi_project.html#review_the_project_files (see `buildSrc/src/main/kotlin/demo.kotlin-common-conventions.gradle.kts` there):

```kotlin
dependencies {
    constraints {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    }
    ...
}
```

This resulted in the same error as above:

```
> Could not resolve all dependencies for configuration ':comadapter-chirpstack:runtimeClasspath'.
   > Could not resolve internal:package:0.0.1-SNAPSHOT.
     Required by:
         project :comadapter-chirpstack
      > Could not resolve internal:package:0.0.1-SNAPSHOT.
         > Failed to add into filestore '/home/siemens/.gradle/caches/modules-2/metadata-2.97/descriptors' at 'internal/package/0.0.1-SNAPSHOT/428e8671c592886319d350c9274bf774/descriptor.bin'
            > Cannot invoke "org.gradle.api.artifacts.VersionConstraint.getRequiredVersion()" because "cst" is null
```

Removing the `constraint` section made it work again.

From the looks of it, the constraint section added this to the Gradle metadata:

```
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
```

But this seems to break the Gradle build when the dependency is consumed by another project.

**Comment by DPUkyle** [comment]
@msiemens thank you for reporting. My concern is that the constraint imposed in a kotlin DSL-backed `buildSrc` folder fails as documented.

> But this seems to break the Gradle build when the dependency is consumed by another project.

I created a toy repo following the instructions from [the docs](https://docs.gradle.org/7.2/samples/sample_building_kotlin_applications_multi_project.html#review_the_project_files) but couldn't find any errors. I'm a bit confused as you mentioned consuming the output of an `application` project, which sounds unorthodox.

I'll add you as a collaborator on https://github.com/DPUkyle/gradle-13797-doc-reproducer so feel free to make changes to help reproduce the error.

**Comment by msiemens** [comment]
@DPUkyle Sorry for taking so long to reply. I actually refactored the project and moved the convention plugins to a separate repository. I don't really remember if that was what fixed the issue for me or if there was some other change that made it work. I checked the repo you created and cannot reproduce this issue either so for me I guess that at least as far as I am concerned everything works fine now. Sorry I can't help down to track down the issue the others are having.

**Comment by donat** [comment]
Sorry for the late reply! It seems the issue was fixed by https://github.com/gradle/gradle/pull/13792. If the problem persists, please open another issue.
