### ISSUE TITLE
OutOfMemoryError with AGP 4.0.0 + gradle 6.1.1

### ISSUE THREAD

**Issue by diousk** [gradle/gradle#13809]
In order to use the new DI framework Hilt in Android development, I upgradle AGP to 4.0.0 + gradle 6.1.1,
and use Android Studio 4.0 to build my project (I also tried Android Studio 4.1-beta3 with the same result)

the **OutOfMemoryError** happened from time to time after build project a few times (usually 3~5 rebuilds with some files changes), 
the error logs is like:
```
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.sun.tools.javac.file.ZipFileIndex.openFile(ZipFileIndex.java:203)
	at com.sun.tools.javac.file.ZipFileIndex.read(ZipFileIndex.java:358)
	at com.sun.tools.javac.file.ZipFileIndexArchive$ZipFileIndexFileObject.openInputStream(ZipFileIndexArchive.java:151)
	at com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:2583)
```

From system activity monitor, I can see that the spawned java processes consumed a lot of memory
<img width="524" alt="螢幕快照 2020-07-18 上午11 36 38" src="https://user-images.githubusercontent.com/2510682/87843943-ff56c300-c8ea-11ea-8fb9-2eb194d3a060.png">

From the dumped file .hprof, the package "com.sun.tools.javac.code" has the most instances listed,
but I don't know how to analyze it: 
(hprof file access: https://drive.google.com/file/d/18Bdianv2XMBBf0438yDiaP6N9Wp0T7Zy/view?usp=sharing)
<img width="818" alt="螢幕快照 2020-07-15 下午10 35 31" src="https://user-images.githubusercontent.com/2510682/87843603-835b7b80-c8e8-11ea-87fc-9d2dbab5e330.png">
<img width="832" alt="螢幕快照 2020-07-15 下午10 35 16" src="https://user-images.githubusercontent.com/2510682/87843605-86566c00-c8e8-11ea-974f-890bc3bd84b0.png">

### Expected Behavior
Build successfully without OutOfMemoryError

### Current Behavior
OutOfMemoryError happened from time to time after build project a few times

I also tried to set max java heap to 4g with the changes in the following files
gradle.properties:
```
org.gradle.jvmargs=-Xms512M -Xmx4608m -XX:MaxPermSize=1024m -XX:MaxMetaspaceSize=1g -Dkotlin.daemon.jvm.options="-Xmx1g" -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
```
build.gradle: (app level)
```
dexOptions {
    javaMaxHeapSize "4g"
    preDexLibraries true
}
```
but same error happened

### My Environment
gradle.properties:
```
org.gradle.daemon=true
org.gradle.jvmargs=-Xms512M -Xmx2600m -XX:MaxPermSize=1024m -XX:MaxMetaspaceSize=1g -Dkotlin.daemon.jvm.options="-Xmx1g" -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configureondemand=true

android.useDeprecatedNdk=true
android.useAndroidX=true
android.enableJetifier=true
android.injected.testOnly=false
android.bundle.enableUncompressedNativeLibs=false
```

build.gradle: (app level)
```
kapt {
    generateStubs = true
    correctErrorTypes = true
}
kotlinOptions {
    jvmTarget = '1.8' 
}
compileOptions {
    sourceCompatibility javaVersion
    targetCompatibility javaVersion
}
dexOptions {
    javaMaxHeapSize "2g"
    preDexLibraries true
}
debug {
    signingConfig signingConfigs.config

    ndk {
        abiFilters "armeabi-v7a"
    }
}
dependencies {
    implementation "com.google.dagger:hilt-android:2.28-alpha"
    kapt "com.google.dagger:hilt-android-compiler:2.28-alpha"
    implementation 'androidx.hilt:hilt-lifecycle-viewmodel:1.0.0-alpha01'
    implementation 'androidx.hilt:hilt-work:1.0.0-alpha01'
    kapt 'androidx.hilt:hilt-compiler:1.0.0-alpha01'
    kapt 'com.squareup:javapoet:1.13.0'
}
```
equipment:
```
Mackbook Pro
CPU: 2.3 GHz Intel Core i5
MEMORY: 16 GB 2133 MHz LPDDR3
```

Is there configuration I missed to help reduce the OutOfMemoryError?

**Comment by diousk** [comment]
issue can not be reproduced after update Hilt version to 2.28.3-alpha
