### ISSUE TITLE
Allow byte array to be used as a build service parameter

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#13824]
### Expected Behavior

A byte array can be used as a parameter for isolated work, such as a build service.

### Current Behavior

A byte array cannot be used as a parameter for isolated work.

**Comment by bamboo** [comment]
This is still relevant.

**Comment by abstratt** [comment]
This used to fail in 6.9, but works fine since 7.0. For completeness, here is the stack with 6.9.1:

```
* What went wrong:
[B

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.InstantiationError: [B
        at java.base/jdk.internal.reflect.GeneratedSerializationConstructorAccessor17.newInstance(Unknown Source)
        at org.gradle.configurationcache.serialization.beans.BeanPropertyReader.newBean(BeanPropertyReader.kt:57)
        at org.gradle.configurationcache.serialization.beans.BeanStateReader$DefaultImpls.newBeanWithId(BeanStateReader.kt:25)
        at org.gradle.configurationcache.serialization.beans.BeanPropertyReader.newBeanWithId(BeanPropertyReader.kt:36)
        at org.gradle.configurationcache.serialization.codecs.BeanCodec.readBeanOf(BeanCodec.kt:66)
        at org.gradle.configurationcache.serialization.codecs.BeanCodec.decode(BeanCodec.kt:47)
        at org.gradle.configurationcache.serialization.CombinatorsKt$reentrant$1$decodeLoop$1.invokeSuspend(Combinators.kt:162)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
        at org.gradle.configurationcache.serialization.CombinatorsKt$reentrant$1.decodeLoop(Combinators.kt:163)
        at org.gradle.configurationcache.serialization.CombinatorsKt$reentrant$1.decode(Combinators.kt:127)
        at org.gradle.configurationcache.serialization.codecs.BindingsBackedCodec.decode(BindingsBackedCodec.kt:64)
        at org.gradle.configurationcache.serialization.DefaultReadContext.read(Contexts.kt:247)
        at org.gradle.configurationcache.serialization.CombinatorsKt.readCollectionInto(Combinators.kt:235)
        at org.gradle.configurationcache.serialization.codecs.CollectionCodecsKt$collectionCodec$2.invokeSuspend(CollectionCodecs.kt:65)
        at org.gradle.configurationcache.serialization.codecs.CollectionCodecsKt$collectionCodec$2.invoke(CollectionCodecs.kt)
        at org.gradle.configurationcache.serialization.CombinatorsKt$codec$1.decode(Combinators.kt:87)
        at org.gradle.configurationcache.serialization.codecs.BindingsBackedCodec.decode(BindingsBackedCodec.kt:64)
        at org.gradle.configurationcache.serialization.DefaultReadContext.read(Contexts.kt:247)
        at org.gradle.configurationcache.serialization.beans.BeanPropertyReaderKt.readPropertyValue(BeanPropertyReader.kt:102)
        at org.gradle.configurationcache.serialization.beans.BeanPropertyReader.readStateOf(BeanPropertyReader.kt:67)
        at org.gradle.configurationcache.serialization.codecs.TaskNodeCodec.readTask(TaskNodeCodec.kt:123)
        at org.gradle.configurationcache.serialization.codecs.TaskNodeCodec.decode(TaskNodeCodec.kt:74)
        ...
```

**Comment by abstratt** [comment]
Test case:

```
        abstract class ByteArrayParameters implements org.gradle.api.services.BuildServiceParameters, Serializable {
            byte[] bytes
            String toString() {
                return new String(bytes)
            }
        }
        
            abstract class CountingService implements BuildService<ByteArrayParameters> {
                int value

                CountingService() {
                    value = 0
                    println("service: created with value = ${value}")
                    println("service: created with parameters = ${parameters}")
                }

                // Service must be thread-safe
                synchronized int increment() {
                    value++
                    println("service: value is ${value}")
                    return value
                }
            }
        
            def provider = gradle.sharedServices.registerIfAbsent("counter", CountingService) {
                parameters.bytes = "Hello".getBytes()
            }
            task tryIt {
                doFirst {
                    provider.get().increment()
                }
            }
```
