### ISSUE TITLE
Crashes on macOs with new FSEventStream handling

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#13831]
When trying to run watchFs tests without isolated daemons, many tests (more than 1000) started failing: https://builds.gradle.org/buildConfiguration/Gradle_Check_WatchFs_31_Trigger/36715393

I looked to some of the tests, and the log is mostly like this (from [here](https://builds.gradle.org/buildConfiguration/Gradle_Check_WatchFs_31_bucket42/36715384?buildTab=tests&pager.currentPage=1&name=ear)):
```
Error:
Caught exception: Execution timed out
The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=8dcda660-3529-402b-bb88-016966ce58ba, currentDir=/Users/tcagent1/agent/work/e67123fb5b9af0ac/subprojects/ear/build/tmp/test files/EarPluginIn.Test/can_use_Ear.ugin/8ypfd}
Attempting to read last messages from the daemon log...
Daemon pid: 37723
  log file: /Users/tcagent1/agent/work/e67123fb5b9af0ac/build/daemon/distributions-jvm/6.7-20200717070034+0000/daemon-37723.out.log
----- Last  20 lines from daemon log file - daemon-37723.out.log -----
Caught exception: Execution timed out
Unable to watch the file system for changes
net.rubygrapefruit.platform.NativeException: Execution timed out
	at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$NativeFileWatcher.stopWatching0(Native Method)
	at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$NativeFileWatcher.stopWatching(AbstractFileEventFunctions.java:196)
	at org.gradle.internal.watch.registry.impl.HierarchicalFileWatcherUpdater.updateWatchedHierarchies(HierarchicalFileWatcherUpdater.java:142)
	at org.gradle.internal.watch.registry.impl.HierarchicalFileWatcherUpdater.determineAndUpdateWatchedHierarchies(HierarchicalFileWatcherUpdater.java:116)
	at org.gradle.internal.watch.registry.impl.HierarchicalFileWatcherUpdater.changed(HierarchicalFileWatcherUpdater.java:86)
	at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem.lambda$new$0(WatchingVirtualFileSystem.java:72)
	at org.gradle.internal.vfs.impl.SnapshotCollectingDiffListener.publishSnapshotDiff(SnapshotCollectingDiffListener.java:40)
	at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem$1.lambda$handleChange$0(WatchingVirtualFileSystem.java:193)
	at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem.withWatcherChangeErrorHandling(WatchingVirtualFileSystem.java:224)
	at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem.access$500(WatchingVirtualFileSystem.java:55)
	at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem$1.lambda$handleChange$1(WatchingVirtualFileSystem.java:191)
	at org.gradle.internal.snapshot.AtomicSnapshotHierarchyReference.update(AtomicSnapshotHierarchyReference.java:38)
	at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem$1.handleChange(WatchingVirtualFileSystem.java:188)
	at org.gradle.internal.watch.registry.impl.DefaultFileWatcherRegistry$1.handleChangeEvent(DefaultFileWatcherRegistry.java:69)
	at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$ChangeEvent.handleEvent(AbstractFileEventFunctions.java:254)
	at org.gradle.internal.watch.registry.impl.DefaultFileWatcherRegistry.lambda$createAndStartEventConsumerThread$0(DefaultFileWatcherRegistry.java:65)
	at java.lang.Thread.run(Thread.java:748)
----- End of the daemon log -----

```

This is from the [crash log](): 
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000010f38820c, pid=37723, tid=0x0000000000009903
#
# JRE version: Java(TM) SE Runtime Environment (8.0_231-b11) (build 1.8.0_231-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.231-b11 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libnative-platform-file-events.dylib+0x1b20c]  _ZNSt3__1L10__loadwordImEET_PKv+0xc

...

Stack: [0x0000700005ebe000,0x0000700005fbe000],  sp=0x0000700005fbc490,  free space=1017k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libnative-platform-file-events.dylib+0x1b20c]  _ZNSt3__1L10__loadwordImEET_PKv+0xc
C  [libnative-platform-file-events.dylib+0x1a97b]  _ZNSt3__121__murmur2_or_cityhashImLm64EEclEPKvm+0x9b
C  [libnative-platform-file-events.dylib+0x1a8cb]  _ZNSt3__1L16__do_string_hashIPKDsEEmT_S3_+0x3b
C  [libnative-platform-file-events.dylib+0x1a864]  _ZNKSt3__14hashINS_12basic_stringIDsNS_11char_traitsIDsEENS_9allocatorIDsEEEEEclERKS6_+0x44
C  [libnative-platform-file-events.dylib+0x1a678]  _ZNKSt3__122__unordered_map_hasherINS_12basic_stringIDsNS_11char_traitsIDsEENS_9allocatorIDsEEEENS_17__hash_value_typeIS6_15WatchPointStateEENS_4hashIS6_EELb1EEclERKS6_+0x28
C  [libnative-platform-file-events.dylib+0x1a4dc]  _ZNSt3__112__hash_tableINS_17__hash_value_typeINS_12basic_stringIDsNS_11char_traitsIDsEENS_9allocatorIDsEEEE15WatchPointStateEENS_22__unordered_map_hasherIS7_S9_NS_4hashIS7_EELb1EEENS_21__unordered_map_equalIS7_S9_NS_8equal_toIS7_EELb1EEENS5_IS9_EEE4findIS7_EENS_15__hash_iteratorIPNS_11__hash_nodeIS9_PvEEEERKT_+0x2c
C  [libnative-platform-file-events.dylib+0x1f2ef]  _ZNSt3__112__hash_tableINS_17__hash_value_typeINS_12basic_stringIDsNS_11char_traitsIDsEENS_9allocatorIDsEEEE15WatchPointStateEENS_22__unordered_map_hasherIS7_S9_NS_4hashIS7_EELb1EEENS_21__unordered_map_equalIS7_S9_NS_8equal_toIS7_EELb1EEENS5_IS9_EEE14__erase_uniqueIS7_EEmRKT_+0x2f
C  [libnative-platform-file-events.dylib+0x1f2ad]  _ZNSt3__113unordered_mapINS_12basic_stringIDsNS_11char_traitsIDsEENS_9allocatorIDsEEEE15WatchPointStateNS_4hashIS6_EENS_8equal_toIS6_EENS4_INS_4pairIKS6_S7_EEEEE5eraseERSD_+0x1d
C  [libnative-platform-file-events.dylib+0x1f140]  _ZZN6Server15unregisterPathsERKNSt3__16vectorINS0_12basic_stringIDsNS0_11char_traitsIDsEENS0_9allocatorIDsEEEENS5_IS7_EEEEENK3$_1clEv+0x140
C  [libnative-platform-file-events.dylib+0x1efdd]  _ZNSt3__1L8__invokeIRZN6Server15unregisterPathsERKNS_6vectorINS_12basic_stringIDsNS_11char_traitsIDsEENS_9allocatorIDsEEEENS6_IS8_EEEEE3$_1JEEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOSF_DpOSG_+0x1d
C  [libnative-platform-file-events.dylib+0x1ef8d]  _ZNSt3__128__invoke_void_return_wrapperIbE6__callIJRZN6Server15unregisterPathsERKNS_6vectorINS_12basic_stringIDsNS_11char_traitsIDsEENS_9allocatorIDsEEEENS8_ISA_EEEEE3$_1EEEbDpOT_+0x1d
C  [libnative-platform-file-events.dylib+0x1ef5d]  _ZNSt3__110__function12__alloc_funcIZN6Server15unregisterPathsERKNS_6vectorINS_12basic_stringIDsNS_11char_traitsIDsEENS_9allocatorIDsEEEENS7_IS9_EEEEE3$_1NS7_ISE_EEFbvEEclEv+0x1d
C  [libnative-platform-file-events.dylib+0x1dc89]  _ZNSt3__110__function6__funcIZN6Server15unregisterPathsERKNS_6vectorINS_12basic_stringIDsNS_11char_traitsIDsEENS_9allocatorIDsEEEENS7_IS9_EEEEE3$_1NS7_ISE_EEFbvEEclEv+0x19
C  [libnative-platform-file-events.dylib+0x70d5]  _ZNKSt3__110__function12__value_funcIFbvEEclEv+0x35
C  [libnative-platform-file-events.dylib+0x2cb5]  _ZNKSt3__18functionIFbvEEclEv+0x15
C  [libnative-platform-file-events.dylib+0x2bf5]  _ZN14AbstractServer14executeCommandEP7Command+0x15
C  [libnative-platform-file-events.dylib+0x1125f]  _ZN6Server14handleCommandsEv+0x9f
C  [libnative-platform-file-events.dylib+0x111ad]  _Z13acceptTriggerPv+0x1d
C  [CoreFoundation+0x848f4]  __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__+0x11
```

---
cc: @gradle/execution

**Comment by wolfs** [comment]
You can also look at the failures in the test dashboard: https://ge.gradle.org/scans/tests?list.size=50&list.sortColumn=startTime&list.sortOrder=desc&search.buildToolType=gradle&search.buildToolType=maven&search.names=coverageOs&search.startTimeMax=1594986232304&search.startTimeMin=1594899832304&search.tasks=watchFsTest&search.timeZoneId=Europe/Berlin&search.values=macOs&tests.sortField=FAILED&tests.unstableOnly=true

**Comment by wolfs** [comment]
We don't use the new handling any more, so let's close this.
