### ISSUE TITLE
Random NullPointerException when executed in --parallel mode (Jenkins)

### ISSUE THREAD

**Issue by messyOne** [gradle/gradle#13830]
As we run our Gradle (6.5.1) build script in `--parallel` mode it randomly (~3/5) fails with a `NullPointerException` on our Jenkins slave:
```
07:56:09  java.lang.NullPointerException
07:56:09  	at org.gradle.internal.logging.sink.ProgressLogEventGenerator$Operation.access$002(ProgressLogEventGenerator.java:91)
07:56:09  	at org.gradle.internal.logging.sink.ProgressLogEventGenerator.completeOperation(ProgressLogEventGenerator.java:79)
07:56:09  	at org.gradle.internal.logging.sink.ProgressLogEventGenerator.onComplete(ProgressLogEventGenerator.java:75)
07:56:09  	at org.gradle.internal.logging.sink.ProgressLogEventGenerator.onOutput(ProgressLogEventGenerator.java:57)
07:56:09  	at org.gradle.internal.logging.console.BuildLogLevelFilterRenderer.onOutput(BuildLogLevelFilterRenderer.java:41)
07:56:09  	at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
07:56:09  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
07:56:09  	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
07:56:09  	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
07:56:09  	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
07:56:09  	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:231)
07:56:09  	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:150)
07:56:09  	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
07:56:09  	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:325)
07:56:09  	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:235)
07:56:09  	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:141)
07:56:09  	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
07:56:09  	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
07:56:09  	at com.sun.proxy.$Proxy0.onOutput(Unknown Source)
07:56:09  	at org.gradle.internal.logging.sink.OutputEventTransformer.onOutput(OutputEventTransformer.java:88)
07:56:09  	at org.gradle.internal.logging.sink.OutputEventRenderer.onOutput(OutputEventRenderer.java:431)
07:56:09  	at org.gradle.internal.logging.sink.OutputEventListenerManager$1.onOutput(OutputEventListenerManager.java:36)
07:56:09  	at org.gradle.internal.logging.services.ProgressLoggingBridge.completed(ProgressLoggingBridge.java:34)
07:56:09  	at org.gradle.internal.logging.progress.DefaultProgressLoggerFactory$ProgressLoggerImpl.completed(DefaultProgressLoggerFactory.java:270)
07:56:09  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$3.stop(DefaultBuildOperationExecutor.java:266)
07:56:09  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:170)
07:56:09  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
07:56:09  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
07:56:09  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
07:56:09  	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
07:56:09  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
07:56:09  	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
07:56:09  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
07:56:09  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
07:56:09  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
07:56:09  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
07:56:09  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
07:56:09  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
07:56:09  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
07:56:09  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
07:56:09  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
07:56:09  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
07:56:09  	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
07:56:09  	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
```

It's not always the same task that gets marked as failed. We could not locate the root cause so far. A clear error description would be nice.

### Expected Behavior
It should show a clear error message instead of a `NullPointerException`. 

### Current Behavior
Throws a `NullPointerException`.

### Context
We had to disable the `--parallel` mode which slowed down our builds by the factor of ~3. 

### Steps to Reproduce 
I'm sorry but I'm not allowed to share any of the code here. I hope the stack trace helps you.  

### Your Environment
The build script gets executed on Jenkins 2.244.

Build scan URL: I'm not allowed to share the internals of the project.

**Comment by dreis2211** [comment]
I'm wondering if https://github.com/gradle/gradle/commit/e6826fc51adc54d54f24ae3df6aeb5ff396be33a#diff-a9a01132b6a91da019ef997b56e7a2dbL75-L87 was removed too optimistically here.

**Comment by jjohannes** [comment]
I wonder if this is a regression that was introduced in 6.5.x

Did anyone see this with an older Gradle version already?

**Comment by dreis2211** [comment]
It happened also before 6.5.x.

**Comment by dreis2211** [comment]
While #13972 will protect us from symptomatic NPEs and fixes the issue for us, we seem to have found a reproducer in our project.

- Have `org.gradle.parallel=true` so things run in parallel
- In a multimodule project we run `./gradlew test -s` which is successful
- For the next run we break one submodule by introducing an exception in a test
- The second `./gradlew test -s` run only sees the submodule changes and obviously fails due to the failing test
- Fix the test and run again `./gradlew test -s`
- As before, Gradle only detects changes in the submodule and only builds that
- The NPE occurs at the end of the build

Unfortunately, I can't share the project, but maybe this is bringing us closer to also finding the root cause and not just fixing the symptoms via #13972
