### ISSUE TITLE
Zip exception while downloading gradle wrapper 6.5.1

### ISSUE THREAD

**Issue by maahi247** [gradle/gradle#13878]
Getting below exception while downloading gradle wrapper 6.5.1, even after using a timeout of 10 minutes.
What can be solution for this? Our network is slow and we want this to work for low bandwidth. Hence we tried using timeout but think it did not work.
```
call gradlew -Dorg.gradle.internal.http.socketTimeout=600000 -Dorg.gradle.internal.http.connectionTimeout=600000 installAll -i --no-daemon --rerun-tasks --refresh-dependencies
Downloading https://nexus:8080/repository/gradle-distributions-raw-proxy/gradle-6.5.1-bin.zip
.........
Unzipping C:\Users\userprofile\GRADLE_HOME\wrapper\dists\gradle-6.5.1-bin\c8f4ewv9vu03n99jiz8aespp9\gradle-6.5.1-bin.zip to C:\Users\userprofile\GRADLE_HOME\wrapper\dists\gradle-6.5.1-bin\c8f4ewv9vu03n99jiz8aespp9
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:230)
        at java.util.zip.ZipFile.<init>(ZipFile.java:160)
        at java.util.zip.ZipFile.<init>(ZipFile.java:174)
        at org.gradle.wrapper.Install.unzip(Install.java:215)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:75)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

```

**Comment by ljacomet** [comment]
Looks like you are using a custom URL for downloading the Gradle distributions. Can't you cache the distribution in your Nexus instance?

Also the reported error does not seem to be a timeout but a content issue. Do you have a firewall that could be messing with the archive?

In the end this looks like an infrastructure issue on your end and nothing something Gradle can resolve.

**Comment by nitishborade** [comment]
Yes, we already have the Gradle distribution in Nexus, from which we download using the Gradle wrapper files.
The issue is due to a poor network unable to download the distribution zip which eventually corrupts due to downloading failure. I believe the Gradle wrapper assumes that the zip is downloaded and tries to unzip the corrupted distribution, which results in the error. On a good or high-speed network, this is not an issue.
Our question is that is there a way to prevent download failure to occur if the network is unable to download the distribution due to low bandwidth, something like re-try which resumes download after a failure, and eventually completes the download, no matter the amount of time it takes?
