### ISSUE TITLE
Enhance error messages when a worker's parameter is not serializable

### ISSUE THREAD

**Issue by stephanenicolas** [gradle/gradle#13894]
Using Gradle 6.7 nightly (or, I assume, any previous version), when a worker's parameter is not serializable, it's not possible to see the name of the parameter, which would help a lot to debug. We can only see his type, which is confusing if a few fields of the parameter interface have the same declared type.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':api:itemsorter:analyzeClassUsageMain'.
> A failure occurred while executing com.autonomousapps.tasks.ClassListAnalysisWorkAction
   > Could not isolate value com.autonomousapps.tasks.ClassListAnalysisParameters_Decorated@75e41c3d of type ClassListAnalysisParameters
      > Could not serialize value of type CompositeFileCollection.
```

```
Caused by: org.gradle.internal.snapshot.impl.IsolationException: Could not isolate value com.autonomousapps.tasks.ClassListAnalysisParameters_Decorated@75e41c3d of type ClassListAnalysisParameters
        at org.gradle.internal.snapshot.impl.DefaultValueSnapshotter.isolate(DefaultValueSnapshotter.java:68)
        at org.gradle.workers.internal.DefaultActionExecutionSpecFactory.newIsolatedSpec(DefaultActionExecutionSpecFactory.java:49)
        at org.gradle.workers.internal.DefaultWorkerExecutor.submitWork(DefaultWorkerExecutor.java:186)
        ... 109 more
Caused by: org.gradle.internal.snapshot.ValueSnapshottingException: Could not serialize value of type CompositeFileCollection.
        at org.gradle.internal.snapshot.impl.DefaultValueSnapshotter.serialize(DefaultValueSnapshotter.java:178)
        at org.gradle.internal.snapshot.impl.DefaultValueSnapshotter.processValue(DefaultValueSnapshotter.java:164)
        at org.gradle.internal.snapshot.impl.DefaultValueSnapshotter.processValue(DefaultValueSnapshotter.java:142)
        at org.gradle.internal.snapshot.impl.DefaultValueSnapshotter.processValue(DefaultValueSnapshotter.java:155)
        at org.gradle.internal.snapshot.impl.DefaultValueSnapshotter.isolate(DefaultValueSnapshotter.java:66)
        ... 111 more
Caused by: java.io.NotSerializableException: org.gradle.api.internal.file.CompositeFileCollection$1
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at org.gradle.internal.snapshot.impl.DefaultValueSnapshotter.serialize(DefaultValueSnapshotter.java:172)
        ... 115 more
```

**Comment by ov7a** [comment]
We appreciate the effort, but we must ask for more information so that we can triage it. 

We do not see an immediate root cause, and we need a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) for the triage. If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***

Sorry for the late reply.

Can anybody please share a reproducer with us so we can verify if that's still an issue?
