### ISSUE TITLE
TestKit should support running Gradle on a different version of Java

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#13957]
### Expected Behavior

When using test kit with a `gradle.properties` file that contains a setting for `org.gradle.java.home`, test kit should run the triggered build as usual using the configured Java home.

### Current Behavior

Currently, the run fails with an exception if the build triggered via test kit fails:
https://scans.gradle.com/s/t3hanflqwtf4e/tests/:test-func:test/org.example.GradleTestkitCrossJavaVersionPluginFunctionalTest/canRunTask#1

### Context

We'd like to compile our test classes against Java 11 and use libraries on Java 11 but would like to ensure our plugin works on Java 8.

### Steps to Reproduce 

1. Clone https://github.com/marcphilipp/gradle-sandbox/tree/master/testkit-cross-java-version
2. Run `./gradlew check`

### Your Environment

Build scan URL: https://scans.gradle.com/s/t3hanflqwtf4e

**Comment by marcphilipp** [comment]
As it turns out, we tried applying a plugin class that was compiled for Java 11 when running on Java 8. After [splitting project](https://github.com/marcphilipp/gradle-sandbox/commit/8b9e71e9336cf2059183954cf0410b56ce6b5ad0) into two subprojects: `plugin` (which targets Java 8) and `test-func` (which targets Java 11), we could not longer reproduce the issue.

However, we're still seeing an issue in the real-world project we're trying this with:
```
    java.lang.IllegalStateException: An error occurred executing build with args '-s test' in directory '<redacted>/build/tmp/test_gradle_5_4_1_JDK_1.8/workspace250735439619662788'. Output before error:
    > Task :compileJava NO-SOURCE
    > Task :processResources NO-SOURCE
    > Task :classes UP-TO-DATE
    > Task :compileTestJava
    > Task :processTestResources NO-SOURCE
    > Task :testClasses
[...]

    * What went wrong:
    Execution failed for task ':test'.
    > There were failing tests. See the report at: file:///<redacted>/build/tmp/test_gradle_5_4_1_JDK_1.8/workspace250735439619662788/build/reports/tests/test/index.html

    * Try:
    Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    * Exception is:
    org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:151)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:148)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:141)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:75)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
    Caused by: org.gradle.api.GradleException: There were failing tests. See the report at: file:///<redacted>/build/tmp/test_gradle_5_4_1_JDK_1.8/workspace250735439619662788/build/reports/tests/test/index.html
        at org.gradle.api.tasks.testing.AbstractTestTask.handleTestFailures(AbstractTestTask.java:626)
        at org.gradle.api.tasks.testing.AbstractTestTask.executeTests(AbstractTestTask.java:498)
        at org.gradle.api.tasks.testing.Test.executeTests(Test.java:594)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:702)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:669)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:404)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:393)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:376)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:213)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:201)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:77)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:120)
        ... 35 more


    * Get more help at https://help.gradle.org

    BUILD FAILED in 11s
    2 actionable tasks: 2 executed
        at org.gradle.testkit.runner.internal.ToolingApiGradleExecutor.run(ToolingApiGradleExecutor.java:162)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:310)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner.buildAndFail(DefaultGradleRunner.java:263)
        at com.gradle.testlib.use.workspace.GradleRunnerBuildExec$GradleRunnerWrapperWithFakeBootstrapJavaVersion.buildAndFail_closure2(GradleRunnerBuildExec.groovy:140)
        at com.gradle.testlib.use.workspace.GradleRunnerBuildExec$GradleRunnerWrapperWithFakeBootstrapJavaVersion.buildAndFail_closure2(GradleRunnerBuildExec.groovy)
        at groovy.lang.Closure.call(Closure.java:405)
        at com.gradle.testlib.use.workspace.GradleRunnerBuildExec$GradleRunnerWrapperWithFakeBootstrapJavaVersion.withFakeJavaVersion(GradleRunnerBuildExec.groovy:146)
        at com.gradle.testlib.use.workspace.GradleRunnerBuildExec$GradleRunnerWrapperWithFakeBootstrapJavaVersion.buildAndFail(GradleRunnerBuildExec.groovy:140)
        at com.gradle.testlib.use.workspace.GradleRunnerBuildExec.runAndFail(GradleRunnerBuildExec.groovy:64)
        at com.gradle.testlib.use.workspace.GradleRunnerBuildExec.runAndFail(GradleRunnerBuildExec.groovy:59)
        at com.gradle.testlib.use.workspace.GradleWorkspace.runAndFail(GradleWorkspace.groovy:16)
        at com.gradle.enterprise.gradleplugin.testdistribution.TestDistributionPluginFuncTestBase.runAndFail(TestDistributionPluginFuncTestBase.groovy:29)
        at com.gradle.enterprise.gradleplugin.testdistribution.TestDistributionPluginFuncTest.executes tests in distributed mode when activated on the test task(TestDistributionPluginFuncTest.groovy:83)

        Caused by:
        org.gradle.tooling.GradleConnectionException: Could not execute build using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-5.4.1-bin.zip'.
            at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:55)
            at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
            at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:43)
            at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor.lambda$run$0(DefaultAsyncConsumerActionExecutor.java:64)
            at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
            at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
            at java.base/java.lang.Thread.run(Thread.java:834)
            at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
            at org.gradle.tooling.internal.consumer.DefaultBuildLauncher.run(DefaultBuildLauncher.java:83)
            at org.gradle.testkit.runner.internal.ToolingApiGradleExecutor.run(ToolingApiGradleExecutor.java:138)
            ... 12 more

            Caused by:
            org.gradle.api.UncheckedIOException: java.io.StreamCorruptedException: invalid type code: 00
                at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:61)
                at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
                at org.gradle.tooling.internal.provider.serialization.PayloadSerializer.deserialize(PayloadSerializer.java:76)
                at org.gradle.tooling.internal.provider.ProviderConnection.throwFailure(ProviderConnection.java:208)
                at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:196)
                at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:138)
                at org.gradle.tooling.internal.provider.DefaultConnection.getModel(DefaultConnection.java:193)
                at org.gradle.tooling.internal.consumer.connection.CancellableModelBuilderBackedModelProducer.produceModel(CancellableModelBuilderBackedModelProducer.java:54)
                at org.gradle.tooling.internal.consumer.connection.PluginClasspathInjectionSupportedCheckModelProducer.produceModel(PluginClasspathInjectionSupportedCheckModelProducer.java:38)
                at org.gradle.tooling.internal.consumer.connection.AbstractConsumerConnection.run(AbstractConsumerConnection.java:64)
                at org.gradle.tooling.internal.consumer.connection.ParameterValidatingConsumerConnection.run(ParameterValidatingConsumerConnection.java:49)
                at org.gradle.tooling.internal.consumer.DefaultBuildLauncher$1.run(DefaultBuildLauncher.java:97)
                at org.gradle.tooling.internal.consumer.DefaultBuildLauncher$1.run(DefaultBuildLauncher.java:89)
                at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:130)
                at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
                at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:61)
                at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
                at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor.lambda$run$0(DefaultAsyncConsumerActionExecutor.java:62)
                at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
                at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
                at java.base/java.lang.Thread.run(Thread.java:834)

                Caused by:
                java.io.StreamCorruptedException: invalid type code: 00
                    at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1677)
                    at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
                    at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
                    at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
                    at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
                    at java.base/java.io.ObjectInputStream.readArray(ObjectInputStream.java:2050)
                    at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1634)
                    at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
                    at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
                    at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
                    at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
                    at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
                    at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
                    at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
                    at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
                    at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
                    at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
                    at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
                    at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
                    at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
                    at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
                    at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
                    at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
                    at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
                    at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
                    at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
                    at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
                    at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
                    at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
                    at org.gradle.tooling.internal.provider.serialization.PayloadSerializer.deserialize(PayloadSerializer.java:74)
                    ... 21 more
```

**Comment by marcphilipp** [comment]
Good news, I finally have a reproducer. The problem is only present if the build triggered via test kit fails. Thus, it seems there's a problem sending the build failure to the client.

**Comment by ldaley** [comment]
This is odd, because we do this for the gradle plugin functional tests. Perhaps those tests just don't fail.

**Comment by ldaley** [comment]
Related: https://github.com/gradle/gradle/issues/9339

**Comment by ldaley** [comment]
Also related: https://github.com/redhat-developer/vscode-java/issues/1594

**Comment by ldaley** [comment]
Also related: https://youtrack.jetbrains.com/issue/KTIJ-15351

**Comment by oehme** [comment]
The problem is that the Tooling API uses `java.lang.StackTraceElement` in its [ExceptionPlaceholder](https://github.com/gradle/gradle/blob/52e83a13e4d225c5110ea794c51f2e5c1e78f40a/subprojects/messaging/src/main/java/org/gradle/internal/serialize/ExceptionPlaceholder.java#L63) model. This class has changed with Java 9 (to include module information), which makes deserialization fail if client and daemon are on opposite sides of that change. 

This derserialization happens in the ProviderConnection, so there's no way to fix this for already released Gradle versions. The best I could do is fix this for future Gradle versions.

**Comment by paplorinc** [comment]
I've spent 2 days investigating it, here's a short summary:
* I've experimented with injecting the latest serializer (actually just `ExceptionPlaceholder` where the`stackTrace` field is adjusted) in legacy Gradle versions - serialization works, but it overrides too much (inclusion is parent package based)
* Talked with Donat and Sterling - they've recommended e.g. https://gradle.slack.com/archives/C593ELF5K/p1627053858077700, but it wasn't viable in the end
* Asked Adam in https://gradle.slack.com/archives/C03A0MT6S/p1627100311354300, he thinks there's a more fundamental issue that should be tackled - we've been patching the invalid serializations for some time now
* Tried extracting the serializer to standalone project to be able to inject only it - depends on too many externals (e.g. from `base-services`)
* Tried  adding a `StackTraceElement`-to-`StackTraceElementPlaceholder` replacer to `ExceptionReplacingObjectInputStream#resolveObject` and `ExceptionReplacingObjectOutputStream#replaceObject` manually, and it seems to fix the problem if we revert Stefan's change on latest.
But if I do it from ByteBuddy dynamically, for some reason only `ExceptionReplacingObjectOutputStreamAdvice` is intercepted, `ExceptionReplacingObjectOutputStream` is not.
See: https://github.com/gradle/gradle/pull/17827/files#diff-c7ac68fddfd07bee401897892b5a19b90d83e9e96d528dd81a4491827ed6da8aR60 for the changes on the gradle code and https://github.com/gradle/dotcom/pull/10157/files#diff-cef6f31bb85cc82dc61336e48575e7641f199783180e9aa6a4dc7c6d6c55a07fR26-R56
* Tried the `TapiAgent` with with an around-advice at first, but since that's not inlined I had to inject the Advice classes to the correct classloader which turned out to be problematic.
* Replaced it with an inline `@OnMethodExit`, but still had problems with the `StackTraceElementPlaceholder` not being on the correct classpath(s?), so I've replaced it with a `ConcurrentSkipListMap` as a placeholder for `StackTraceElement` - but this still only replaces for `ExceptionReplacingObjectOutputStream`, not for `ExceptionReplacingObjectInputStream` for some reason.

I can't spend more time on this currently, but the two mentioned drafts can be used for further investigation.

**Comment by paplorinc** [comment]
Reverting @oehme's fix temporarily on `master` (to make absolutely sure the tests are failing) and replacing the `ExceptionReplacingObject(Output|Input)Stream`s where the `StackTraceElement` is serialized to a `Map` and back (via an instrumentation agent through a premain, applying to the affected daemon and client JVMs) makes the tests pass on every version since `2.6`:
<img src="https://user-images.githubusercontent.com/1841944/128848472-a27dcd31-c8e1-474c-ba8f-b876b0c59f67.png">

I'm not sure whether we can do this automatically through TestKit or not (or through the IDE), but it should satisfy our cross-version needs in GE.
