### ISSUE TITLE
Check file system watching support on Windows SMB

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#14002]
---
cc: @gradle/execution

**Comment by lptr** [comment]
## SMB

Seems like we can't start a build from an SMB share:

```text
PS Microsoft.PowerShell.Core\FileSystem::\\WINDOWS45\Users\vmadmin\Workspace\shared\native-platform> ./gradlew :test
'\\WINDOWS45\Users\vmadmin\Workspace\shared\native-platform'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.

FAILURE: Build failed with an exception.

* What went wrong:
Task 'test' not found in root project 'Windows'.
```

I tried mapping the share to a drive (`S:`), and then I got this error:

```text
Error while receiving file changes
net.rubygrapefruit.platform.NativeException: Error received when handling events, error = 87: S:\native-platform
        at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$NativeFileWatcher.executeRunLoop0(Native Method)
        at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$NativeFileWatcher.access$100(AbstractFileEventFunctions.java:156)
        at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$NativeFileWatcher$1.run(AbstractFileEventFunctions.java:169)
```

Windows error code `87` is **ERROR_INVALID_PARAMETER**:

> `ReadDirectoryChangesW` fails with `ERROR_INVALID_PARAMETER` when the buffer length is greater than 64 KB and the application is monitoring a directory over the network. This is due to a packet size limitation with the underlying file sharing protocols.

https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-readdirectorychangesw

This is because we use a 128 kB buffer. We could decrease this to 64 kB, or make it configurable.

**Comment by lptr** [comment]
Seems like we have more problems with SMB drives. Even with a 16 kB buffer:

```text
net.rubygrapefruit.platform.file.BasicFileEventFunctionsTest > can detect file created STANDARD_ERROR
    10:34:08.194  INFO    >>> Running 'can detect file created'
    10:34:08.209  INFO    > Creating ...\root\created.txt
    10:34:08.213  INFO    < Created ...\root\created.txt
    10:34:08.234  INFO    > Expecting CREATED ...\root\created.txt
    10:34:08.235  INFO    > Received CREATED S:\native-platform\build\test files\junit7612490621405826418\can detect file created\root\created.txt
    10:34:08.265  WARNING Watch point S:\native-platform\build\test files\junit7612490621405826418\can detect file created\root did not finish before termination timeout (status = 2)
    10:34:08.269  INFO    <<< Finished 'can detect file created'
```

**Comment by lptr** [comment]
The notifications seem to arrive properly, but the watch points stay in `CANCELLED` state, i.e. they don't receive the `ERROR_OPERATION_ABORTED` event during the `SleepEx(0, true)` call after the run loop has finished:

https://github.com/gradle/native-platform/blob/6a4a4d4f6fe6665993c400f0486fd7b7a1539728/src/file-events/cpp/win_fsnotifier.cpp#L320-L349

**Comment by lptr** [comment]
Looks like raising the timeout to `SleepEx(1000, true)` fixes the issue. We don't want to do this in general, though. We could add a configuration parameter for how long to wait on `close()` but it's not something that seems worth doing now.
