### ISSUE TITLE
GStringImpl cannot be cast to String

### ISSUE THREAD

**Issue by urferr** [gradle/gradle#14077]
Starting with gradle 6.4 up to 6.5.1 our build always fails with the error "GStringImpl cannot be cast to String"

One sesuence which now always fails is:
`jar {
    manifest {
        attributes(
        	"Class-Path": configurations.runtimeClasspath.collect {"$it.name"}.join(" "),
        	"Main-Class": "com.profidata.configservice.setup.ApplicationCommand"
        )
    }
}`
It fails on the line creating the "Class-Path" manifest entry.

Also the following task execution always fails:
`task("fatjar", type: Jar) {
	dependsOn(jar)
	with(jar)
	archiveName = "test-tools.jar"
	from(configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) })
	exclude("**/FIX*.xml")
}`
Here it is the line "from(configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) })" which always fails

The stacktrace is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':myproject'.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.lambda$apply$0(DefaultScriptPluginFactory.java:133)
        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:136)
        at org.gradle.configuration.BuildOperationScriptPlugin$1$1.run(BuildOperationScriptPlugin.java:69)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)        at org.gradle.configuration.BuildOperationScriptPlugin$1.execute(BuildOperationScriptPlugin.java:66)

**Comment by ljacomet** [comment]
@gradle/instant-execution Could that be a regression from the configuration cache work?

**Comment by bamboo** [comment]
@urferr could you please check if you can still reproduce the problem with the latest [Gradle 6.6 RC6](https://github.com/gradle/gradle/releases/tag/v6.6.0-RC6)?

I wasn't able to reproduce the problem with a simple script:
```groovy
    plugins {
        id('java')
    }

    dependencies {
        runtimeOnly(files('./lib.jar'))
    }

    jar {
        manifest {
            attributes('Class-Path': configurations.runtimeClasspath.collect {"$it.name"}.join(" "))
        }
        destinationDirectory = buildDir
        archiveFileName = 'test.jar'
    }
```

A build scan for the failure would be helpful as well.

**Comment by urferr** [comment]
with the latest Gradle 6.6 RC6 it works again, thanks

**Comment by ljacomet** [comment]
Thanks for checking, closing then.
