### ISSUE TITLE
Buildship 2.0 does not work with spaces in eclipse install path

### ISSUE THREAD

**Issue by Horcrux7** [gradle/gradle#1411]
If Eclipse is installed in a location with a space in it (for example c:\Program Files\eclipse) then Buildship 2.0 can not refresh any projects. It is work with the Buildship latest 1.x. The used Eclipse version was Luna.

The stacktrace of the error message is:
```
org.gradle.tooling.GradleConnectionException: Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-3.3-bin.zip'.
                at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:55)
                at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
                at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:41)
                at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57)
                at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
                at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
                at java.lang.Thread.run(Unknown Source)
                at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
                at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter.run(DefaultBuildActionExecuter.java:48)
                at com.gradleware.tooling.toolingclient.internal.DefaultToolingClient.executeAndWait(DefaultToolingClient.java:106)
                at com.gradleware.tooling.toolingclient.internal.DefaultBuildActionRequest.executeAndWait(DefaultBuildActionRequest.java:51)
                at com.gradleware.tooling.toolingmodel.repository.internal.DefaultModelRepository$13.get(DefaultModelRepository.java:287)
                at com.gradleware.tooling.toolingmodel.repository.internal.DefaultModelRepository.executeAndWait(DefaultModelRepository.java:355)
                at com.gradleware.tooling.toolingmodel.repository.internal.DefaultModelRepository.access$100(DefaultModelRepository.java:49)
                at com.gradleware.tooling.toolingmodel.repository.internal.DefaultModelRepository$14.call(DefaultModelRepository.java:313)
                at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4724)
                at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
                at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
                at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
                at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
                at com.google.common.cache.LocalCache.get(LocalCache.java:3932)
                at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4721)
                at com.gradleware.tooling.toolingmodel.repository.internal.DefaultModelRepository.getFromCache(DefaultModelRepository.java:330)
                at com.gradleware.tooling.toolingmodel.repository.internal.DefaultModelRepository.executeRequest(DefaultModelRepository.java:309)
                at com.gradleware.tooling.toolingmodel.repository.internal.DefaultModelRepository.executeRequest(DefaultModelRepository.java:280)
                at com.gradleware.tooling.toolingmodel.repository.internal.DefaultModelRepository.fetchEclipseGradleProjects(DefaultModelRepository.java:238)
                at org.eclipse.buildship.core.workspace.internal.DefaultModelProvider.fetchEclipseGradleProjects(DefaultModelProvider.java:66)
                at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.fetchEclipseProjects(SynchronizeGradleBuildsJob.java:83)
                at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.synchronizeBuild(SynchronizeGradleBuildsJob.java:75)
                at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.runToolingApiJob(SynchronizeGradleBuildsJob.java:68)
                at org.eclipse.buildship.core.util.progress.ToolingApiJob$1.run(ToolingApiJob.java:73)
                at org.eclipse.buildship.core.util.progress.ToolingApiInvoker.invoke(ToolingApiInvoker.java:62)
                at org.eclipse.buildship.core.util.progress.ToolingApiJob.run(ToolingApiJob.java:70)
                at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: org.gradle.api.GradleException: Could not determine the class-path for class org.gradle.tooling.internal.consumer.connection.InternalBuildActionAdapter.
                at org.gradle.tooling.internal.provider.serialization.ClasspathInferer.find(ClasspathInferer.java:143)
                at org.gradle.tooling.internal.provider.serialization.ClasspathInferer.getClassPathFor(ClasspathInferer.java:61)
                at org.gradle.tooling.internal.provider.serialization.ClientSidePayloadClassLoaderRegistry$1.visitClass(ClientSidePayloadClassLoaderRegistry.java:78)
                at org.gradle.tooling.internal.provider.serialization.WellKnownClassLoaderRegistry$1.visitClass(WellKnownClassLoaderRegistry.java:65)
                at org.gradle.tooling.internal.provider.serialization.PayloadSerializerObjectOutputStream.writeClassLoader(PayloadSerializerObjectOutputStream.java:63)
                at org.gradle.tooling.internal.provider.serialization.PayloadSerializerObjectOutputStream.writeClass(PayloadSerializerObjectOutputStream.java:55)
                at org.gradle.tooling.internal.provider.serialization.PayloadSerializerObjectOutputStream.writeClassDescriptor(PayloadSerializerObjectOutputStream.java:43)
                at java.io.ObjectOutputStream.writeNonProxyDesc(Unknown Source)
                at java.io.ObjectOutputStream.writeClassDesc(Unknown Source)
                at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
                at java.io.ObjectOutputStream.writeObject0(Unknown Source)
                at java.io.ObjectOutputStream.writeObject(Unknown Source)
                at org.gradle.tooling.internal.provider.serialization.PayloadSerializer.serialize(PayloadSerializer.java:45)
                at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:121)
                at org.gradle.tooling.internal.provider.DefaultConnection.run(DefaultConnection.java:208)
                at org.gradle.tooling.internal.consumer.connection.CancellableConsumerConnection$CancellableActionRunner.run(CancellableConsumerConnection.java:99)
                at org.gradle.tooling.internal.consumer.connection.AbstractConsumerConnection.run(AbstractConsumerConnection.java:62)
                at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter$1.run(DefaultBuildActionExecuter.java:59)
                at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:79)
                at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
                at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
                at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
                at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
                at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
                at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
                at java.lang.Thread.run(Unknown Source)
Caused by: org.gradle.internal.UncheckedException: java.net.URISyntaxException: Illegal character in path at index 16: file:/C:/Program Files/luna/plugins/org.gradle.toolingapi_3.3.0.v20170103170240.jar
                at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:45)
                at org.gradle.internal.classloader.ClasspathUtil.getClasspathForClass(ClasspathUtil.java:88)
                at org.gradle.tooling.internal.provider.serialization.ClasspathInferer.find(ClasspathInferer.java:92)
                ... 27 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 16: file:/C:/Program Files/luna/plugins/org.gradle.toolingapi_3.3.0.v20170103170240.jar
                at java.net.URI$Parser.fail(Unknown Source)
                at java.net.URI$Parser.checkChars(Unknown Source)
                at java.net.URI$Parser.parseHierarchical(Unknown Source)
                at java.net.URI$Parser.parse(Unknown Source)
                at java.net.URI.<init>(Unknown Source)
                at java.net.URL.toURI(Unknown Source)
                at org.gradle.internal.classloader.ClasspathUtil.getClasspathForClass(ClasspathUtil.java:74)
                ... 28 more
```

**Comment by donat** [comment]
Thank you for the report!
This was [already reported](https://github.com/eclipse/buildship/issues/242) and has been fixed in the snapshot releases. Can you please verify if the latest [2.0.1](https://github.com/eclipse/buildship/blob/master/docs/user/Installation.md) snapshot works for you?

**Comment by donat** [comment]
Hi! This is an issue it the Tooling API. The fix was already implemented and is part of the Gradle 3.4-rc-1 release. For the details check out https://github.com/gradle/gradle/issues/1180.

**Comment by Horcrux7** [comment]
I have try 3.4-rc-3 and it work.

**Comment by donat** [comment]
Awesome, thanks @Horcrux7 for checking!
