### ISSUE TITLE
GradleRunner.withDebug(true) causes tests using --configuration-cache to fail with org.apache.groovy.json.FastStringServiceFactory: Provider org.apache.groovy.json.DefaultFastStringServiceFactory not a subtype

### ISSUE THREAD

**Issue by wilkinsona** [gradle/gradle#14125]
### Expected Behavior
Tests can be run with debug enabled without failing

### Current Behavior
Tests fail with the following:

```
FAILURE: Build failed with an exception.
* What went wrong:
Failed to notify build listener.
> org.apache.groovy.json.FastStringServiceFactory: Provider org.apache.groovy.json.DefaultFastStringServiceFactory not a subtype
* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Exception is:
org.gradle.internal.event.ListenerNotificationException: Failed to notify build listener.
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:86)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:346)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:249)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:141)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy253.buildFinished(Unknown Source)
…
```

### Context

I'm trying to add tests to Spring Boot's Gradle plugin that use `--configuration-cache` as part of addressing https://github.com/spring-projects/spring-boot/issues/22922,

### Steps to Reproduce 

1. Clone https://github.com/wilkinsona/spring-boot
2. Check out with-debug-cache-configuration-problem
3. Run `./gradlew spring-boot-project:spring-boot-tools:spring-boot-gradle-plugin:build`

### Your Environment

Build scan URL: https://ge.spring.io/s/uyg5ntm6wg4na

**Comment by ivan5737** [comment]
That issue is when you use a groovy-json library with a version from 2.5 to up, you could try to use a old version like 2.4.20

**Comment by wilkinsona** [comment]
Still relevant, AFAIK.

**Comment by ov7a** [comment]
Sorry for the late reply.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by jbartok** [comment]
I can no longer reproduce this issue (the fork specified in the issue description is very old, the branch is missing, so I've tried on the latest official spring-boot repo; I've modified tests with CC enabled, turned on debugging, but no failures).
