### ISSUE TITLE
Gradle fails obscurely if ProjectCacheDir is not owned by build user

### ISSUE THREAD

**Issue by ldaley** [gradle/gradle#14200]
A user reported a problem that eventually boiled down to this root cause: https://github.com/gradle/gradle/issues/8673

```
Caused by: org.gradle.api.GradleException: Could not write cache value to '/builds/astradot/java-app-agent/.gradle/workspace-id.txt'.
	at org.gradle.cache.internal.SimpleStateCache.serialize(SimpleStateCache.java:133)
	at org.gradle.cache.internal.SimpleStateCache.access$100(SimpleStateCache.java:34)
	at org.gradle.cache.internal.SimpleStateCache$2.run(SimpleStateCache.java:62)
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.doWriteAction(DefaultFileLockManager.java:215)
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.writeFile(DefaultFileLockManager.java:205)
	at org.gradle.cache.internal.OnDemandFileAccess.writeFile(OnDemandFileAccess.java:63)
	at org.gradle.cache.internal.SimpleStateCache.set(SimpleStateCache.java:59)
	at org.gradle.cache.internal.FileIntegrityViolationSuppressingPersistentStateCacheDecorator.set(FileIntegrityViolationSuppressingPersistentStateCacheDecorator.java:42)
	at org.gradle.cache.internal.FileIntegrityViolationSuppressingPersistentStateCacheDecorator.doUpdate(FileIntegrityViolationSuppressingPersistentStateCacheDecorator.java:70)
	at org.gradle.cache.internal.FileIntegrityViolationSuppressingPersistentStateCacheDecorator.maybeUpdate(FileIntegrityViolationSuppressingPersistentStateCacheDecorator.java:57)
	at org.gradle.internal.scopeids.DefaultPersistentScopeIdLoader.get(DefaultPersistentScopeIdLoader.java:77)
	at org.gradle.internal.scopeids.DefaultPersistentScopeIdLoader.getWorkspace(DefaultPersistentScopeIdLoader.java:58)
	at org.gradle.internal.service.scopes.BuildSessionScopeServices.createWorkspaceScopeId(BuildSessionScopeServices.java:161)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
	at org.gradle.internal.service.ReflectionBasedServiceMethod.invoke(ReflectionBasedServiceMethod.java:34)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:841)
	... 163 more
Caused by: org.gradle.internal.file.FileException: Could not set file mode 700 on '/builds/astradot/java-app-agent/.gradle'.
	at org.gradle.internal.nativeintegration.filesystem.services.GenericFileSystem.chmod(GenericFileSystem.java:90)
	at org.gradle.cache.internal.SimpleStateCache.serialize(SimpleStateCache.java:124)
	... 178 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not set UNIX mode on /builds/astradot/java-app-agent/.gradle: could not chmod file (errno 1: Operation not permitted)
	at net.rubygrapefruit.platform.internal.DefaultPosixFiles.setMode(DefaultPosixFiles.java:65)
	at org.gradle.internal.nativeintegration.filesystem.services.NativePlatformBackedChmod.chmod(NativePlatformBackedChmod.java:33)
	at org.gradle.internal.nativeintegration.filesystem.services.GenericFileSystem.chmod(GenericFileSystem.java:88)
	... 179 more

```

They are using Gitlab and trying to persist the .gradle project cache dir across builds. Gitlab restores such files as being owned by root, not the user running the build (https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1782). This causes a failure on the first attempt to write to this dir because we try to change the permissions:

https://github.com/gradle/gradle/blob/89eb255a57394348ce439ea7c91dfdadd4900c05/subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/SimpleStateCache.java#L124

1. Why we are doing the chmod in the first place. Why is writability not enough?
2. The failure could be more graceful in that we check early in the build process that we are going to be able to use this dir and fail informatively if we can't
3. We should clarify our position on trying to persist/reuse this directory in an ephemeral CI context

### Your Environment

Build scan URL:

**Comment by big-guy** [comment]
> 1. Why we are doing the chmod in the first place. Why is writability not enough?

This is setting the permissions on the directory. You need +x to be able to cd into the directory.  This same cache is used for the daemon registry and we restrict that to only the owner (vs world readable).

> 2. The failure could be more graceful in that we check early in the build process that we are going to be able to use this dir and fail informatively if we can't

+1, was this with a recentish version of Gradle? 

> 3. We should clarify our position on trying to persist/reuse this directory in an ephemeral CI context

I don't believe there's any reason to ever cache this directory. [We only talk about caching parts of the dependency cache](https://docs.gradle.org/current/userguide/dependency_resolution.html#sub:ephemeral-ci-cache).

**Comment by ldaley** [comment]
>> Why we are doing the chmod in the first place. Why is writability not enough?
> This is setting the permissions on the directory. You need +x to be able to cd into the directory. This same cache is used for the daemon registry and we restrict that to only the owner (vs world readable).

The daemon registry is in the gradle user home. This issue is about the project cache dir. If we already have the permission we need, we don't need to chmod AFAICT.

> +1, was this with a recentish version of Gradle?

Yes, latest.

> I don't believe there's any reason to ever cache this directory

We could make that documentation clearer by stating that you should _only_ share that directory.

**Comment by azerbe** [comment]
The same thing happens, when you try to run gradle in an OpenShift environment (rootless). OpenShift uses arbitrary user-ids for pod/container execution and this results in a mismatch between directory owner and process executor.

```
Initialized native services in: /code/.gradle/native
Initialized jansi services in: /code/.gradle/native
Received JVM installation metadata from '/usr/lib/jvm/java-17-openjdk-17.0.7.0.7-1.el8_7.x86_64': {JAVA_HOME=/usr/lib/jvm/java-17-openjdk-17.0.7.0.7-1.el8_7.x86_64, JAVA_VERSION=17.0.7, JAVA_VENDOR=Red Hat, Inc., RUNTIME_NAME=OpenJDK Runtime Environment, RUNTIME_VERSION=17.0.7+7-LTS, VM_NAME=OpenJDK 64-Bit Server VM, VM_VERSION=17.0.7+7-LTS, VM_VENDOR=Red Hat, Inc., OS_ARCH=amd64}
Removing daemon from the registry due to communication failure. Daemon information: DaemonInfo{pid=57, address=[666c336d-ccf9-424d-a8ba-ca717203d09a port:45575, addresses:[/127.0.0.1]], state=Idle, lastBusy=1686126974837, context=DefaultDaemonContext[uid=2c41b1be-4d63-4e3f-9286-aa97566b680c,javaHome=/usr/lib/jvm/java-17-openjdk-17.0.7.0.7-1.el8_7.x86_64,daemonRegistryDir=/code/.gradle/daemon,pid=57,idleTimeout=10800000,priority=NORMAL,daemonOpts=--add-opens=java.base/java.util=ALL-UNNAMED,--add-opens=java.base/java.lang=ALL-UNNAMED,--add-opens=java.base/java.lang.invoke=ALL-UNNAMED,--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens=java.base/java.nio.charset=ALL-UNNAMED,--add-opens=java.base/java.net=ALL-UNNAMED,--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country,-Duser.language=en,-Duser.variant]}
FAILURE: Build failed with an exception.

* What went wrong:
Could not write cache value to '/code/.gradle/daemon/7.6/registry.bin'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
```

This is reproducible if you build an Docker Image with gradle, set the folder permissions like [explained in the  OpenShift documentation ](https://docs.openshift.com/container-platform/4.13/openshift_images/create-images.html#use-uid_create-images )and run that image locally with a random user-id. Then execute any gradle task.

Example:
```
docker run --rm -it -u 1000:0 --entrypoint /bin/bash <IMAGE>
```
