### ISSUE TITLE
Android Gradle plugin v4.0.0 and Gradle v6.1.1 causes AbstractMethodError

### ISSUE THREAD

**Issue by BabuinGH** [gradle/gradle#14277]
Upgrading the Gradle plugin from v3.6.0 (gradle v5.6.4)  to v4.0.0(gradle v6.1.1) is causing AbstractMethodError crash

### Expected Behavior
 By upgrading Gradle plugin to v4.0.0, it is expected to work fine without crashing.

### Current Behavior
Causing the below crash
   ``` 
   E/AndroidRuntime: FATAL EXCEPTION: main  
    java.lang.AbstractMethodError: abstract method "java.lang.String b.a.a.b.b.b(java.lang.String)"
        at b.a.a.b.a.a(:11)
        at com.example.testproguard.MainActivity.onCreate(:17)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) -->
```

### Context
It was working fine until Gradle plugin v3.6.0 (gradle v5.6.4)
With this issue, we are blocked to upgrade to Gradle plugin v4.0.0
The method where crash was found was designed to have a `protected` access. However, by converting it to `public`, the crash can be avoided. Since, this method and some other methods in the `KeyValueContainer.java` needs to have `protected` access, we could not change the design but wondering why is it crashing in the latest versions of Gradle.
``` 
 protected String get(String key) {
        return map.get(key);
 }
```

### Steps to Reproduce 

[TestProguard.zip](https://github.com/gradle/gradle/files/5125445/TestProguard.zip)

Please refer to files `KeyValueContainer.java`, `Event.java` and `PageParams.java`

### Your Environment
Android Studio - 4.0.1
Android Gradle plugin - 4.0.0
Gradle version - 6.1.1

Build scan URL: https://gradle.com/s/7zrxzepy7bmvu

**Comment by big-guy** [comment]
This looks like it might be an Android only issue, so I'm not sure if we can be of much help.

Have you tried looking for a similar bug on the [Android issue tracker](https://source.android.com/setup/contribute/report-bugs)?
