### ISSUE TITLE
Could not load module metadata : gradle 5.4.1 

### ISSUE THREAD

**Issue by nevermore-debug** [gradle/gradle#14420]
gradle 5.4.1

error when sync:

> Could not resolve all dependencies for configuration ':classpath'.
   > Could not load module metadata from C:\Users\c00297161\.gradle\caches\modules-2\metadata-2.71\descriptors\com.fasterxml.jackson.core\jackson-databind\2.10.4\bc771024157fd76ccd80a6832457a164\descriptor.bin

And i found 
C:\Users\xxxxxx\.gradle\caches\modules-2\metadata-2.71\descriptors\com.fasterxml.jackson.core\jackson-databind\2.10.4\bc771024157fd76ccd80a6832457a164\descriptor.bin 
is wrong.

[descriptor.zip](https://github.com/gradle/gradle/files/5172219/descriptor.zip)

**Comment by nevermore-debug** [comment]
Caused by: java.lang.RuntimeException: Could not load module metadata from C:\Users\c00297161\.gradle\caches\modules-2\metadata-2.71\descriptors\com.fasterxml.jackson.core\jackson-databind\2.10.4\bc771024157fd76ccd80a6832457a164\descriptor.bin
	at org.gradle.api.internal.artifacts.ivyservice.modulecache.ModuleMetadataStore.getModuleDescriptor(ModuleMetadataStore.java:63)
	at org.gradle.api.internal.artifacts.ivyservice.modulecache.PersistentModuleMetadataCache$1.create(PersistentModuleMetadataCache.java:81)
	at org.gradle.api.internal.artifacts.ivyservice.modulecache.PersistentModuleMetadataCache$1.create(PersistentModuleMetadataCache.java:71)
	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:223)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:180)
	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.useCache(DefaultCacheFactory.java:204)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultArtifactCacheLockingManager.useCache(DefaultArtifactCacheLockingManager.java:89)
	at org.gradle.api.internal.artifacts.ivyservice.modulecache.PersistentModuleMetadataCache.get(PersistentModuleMetadataCache.java:71)
	at org.gradle.api.internal.artifacts.ivyservice.modulecache.InMemoryModuleMetadataCache.get(InMemoryModuleMetadataCache.java:40)
	at org.gradle.api.internal.artifacts.ivyservice.modulecache.AbstractModuleMetadataCache.getCachedModuleDescriptor(AbstractModuleMetadataCache.java:35)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$LocateInCacheRepositoryAccess.estimateMetadataFetchingCost(CachingModuleComponentRepository.java:295)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.estimateMetadataFetchingCost(ErrorHandlingModuleComponentRepository.java:309)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.isFetchingMetadataCheap(RepositoryChainComponentMetaDataResolver.java:71)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.ComponentResolversChain$ComponentMetaDataResolverChain.isFetchingMetadataCheap(ComponentResolversChain.java:102)
	at org.gradle.api.internal.artifacts.ivyservice.clientmodule.ClientModuleResolver.isFetchingMetadataCheap(ClientModuleResolver.java:81)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.maybeDownloadMetadataInParallel(DependencyGraphBuilder.java:304)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.resolveEdges(DependencyGraphBuilder.java:240)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.traverseGraph(DependencyGraphBuilder.java:180)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:141)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:122)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolveGraph(DefaultConfigurationResolver.java:171)
	at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveGraph(ShortCircuitEmptyConfigurationResolver.java:86)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:73)
	... 151 more
Caused by: java.lang.IllegalArgumentException: Unexpected metadata type found.
	at org.gradle.api.internal.artifacts.ivyservice.modulecache.ModuleMetadataSerializer$Reader.read(ModuleMetadataSerializer.java:408)
	at org.gradle.api.internal.artifacts.ivyservice.modulecache.ModuleMetadataSerializer.read(ModuleMetadataSerializer.java:89)
	at org.gradle.api.internal.artifacts.ivyservice.modulecache.ModuleMetadataStore.getModuleDescriptor(ModuleMetadataStore.java:58)
	... 173 more

**Comment by ljacomet** [comment]
Deleting the file will most likely unblock you, if you have not tried that already. This file simply is a [more efficient format](https://docs.gradle.org/current/userguide/dependency_resolution.html#sec:dependency_cache) for Gradle to load instead of parsing the metadata (Maven, Ivy or Gradle).

What could be interesting is a set of instructions for reproducing the issue.

**Comment by ljacomet** [comment]
Without more information, this cannot be investigated further.

**Comment by mahmood1328** [comment]
the solution is very simple you dont have to uninstall android studio. the issue ussually happens because you gradles cannot load data in the metadata folder or you have multiple data folder in the gradle file. follow the following steps 1.go to "C:\Users\pc.gradle\caches\modules-2\" 2.delete any metadata folder availabe. 3.return to android studio and rebuild your project ensuring that you have internet connections 5.wait for the gradle to download some files and sync then 6.everything should wwork well after doing that

**Comment by hterrolle** [comment]
But what appends when old depedencies were deleted ? Project is dead ?
