### ISSUE TITLE
IncludeBuild of plugin creates instrumented gradle-api.jar with recursive loop breaking workers

### ISSUE THREAD

**Issue by bennofs** [gradle/gradle#14497]
### Expected Behavior
The Gradle instrumentation of `System.getProperty` should not create a infinite recursive call.

### Current Behavior
When using `--include-build some-gradle-plugin` and applying that plugin to a build, the classpath of the buildscript will contain an instrumented version of `gradle-api.jar`. `gradle-api.jar` contains the function `org.gradle.internal.classpath.Instrumented.systemProperty`, which is called by instrumented `System.getProperty` calls. When `gradle-api.jar` itself is instrumented, that instrumentation then produces an infinite recursion, as can be observed in the decompiled output of the jar file in `/home/.gradle/caches/jars-8/ae4a20b43053358f77e2ec26c6483b17/gradle-api-6.6.jar`:

```java
public static String systemProperty(String key, String consumer) {
      return systemProperty(key, (String)null, consumer);
}

public static String systemProperty(String key, @Nullable String defaultValue, String consumer) {
      // LOOK HERE: This is System.getProperty call in the source, but the instrumentation changed it to call systemProperty, which of course leads to the recursive loop because this is the implementation of that very method
      String value = systemProperty(key, "org.gradle.internal.classpath.Instrumented");
      ((org.gradle.internal.classpath.Instrumented.Listener)LISTENER.get()).systemPropertyQueried(key, value, consumer);
      return value == null ? defaultValue : value;
}
```

### Context
I first observed this when using the [`ratpack-gradle`](https://github.com/ratpack/ratpack/tree/master/ratpack-gradle). The plugin spawns a new gradle worker process to provide continuous reloading support for ratpack applications (it is very similar to the play application plugin, which I assume would also be affected by this issue). Because the worker process inherits the classpath of the buildscript, it results in the following exception after launching the worker:

```
...
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:77)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:82)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:77)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:82)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:77)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:82)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:77)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:82)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:77)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:82)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:77)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:82)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:77)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:82)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:77)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:82)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:77)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:82)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:77)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:82)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:77)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:82)

FAILURE: Build failed with an exception.
```

### Steps to Reproduce 
I created a minimal example to reproduce this issue at https://github.com/bennofs/repros/tree/master/gradle/incorrect-instrumented-worker-classpath. We have a plugin and a simple user of that plugin. Running `gradle classpath` on the user project prints:

```
file:/home/.gradle/caches/jars-8/59c36ef902fa91ee8d620f5653e0d0ca/plugin-0.1.0.jar
file:/home/.gradle/caches/jars-8/ae4a20b43053358f77e2ec26c6483b17/gradle-api-6.6.jar
file:/home/.gradle/caches/jars-8/018fb4f470dae255aab10520d685d1fd/groovy-all-1.3-2.5.12.jar
file:/home/.gradle/caches/jars-8/70d15c94187de212f9a927dc262ddd63/kotlin-stdlib-1.3.72.jar
file:/home/.gradle/caches/jars-8/18e6bc6874baa1a066bce674522f54bf/kotlin-stdlib-common-1.3.72.jar
file:/home/.gradle/caches/jars-8/421b0c68a25f5d684ea66be525dfcf66/kotlin-stdlib-jdk7-1.3.72.jar
file:/home/.gradle/caches/jars-8/768cf1021ee3bdc425b9b2ae1289f2f1/kotlin-stdlib-jdk8-1.3.72.jar
file:/home/.gradle/caches/jars-8/dde97575a599bd3e140dd938a7aed4fa/kotlin-reflect-1.3.72.jar
file:/home/.gradle/caches/jars-8/e1ec607f8744a112c320d440a1efa764/gradle-installation-beacon-6.6.jar
file:/usr/share/java/gradle/lib/plugins/gradle-workers-6.6.jar
file:/usr/share/java/gradle/lib/failureaccess-1.0.1.jar
file:/usr/share/java/gradle/lib/guava-27.1-android.jar
...
```

Checking the bytecode of `file:/home/.gradle/caches/jars-8/ae4a20b43053358f77e2ec26c6483b17/gradle-api-6.6.jar` with a decompiler confirms that this file is incorrectly instrumented.

### Your Environment
Build scan URL (for the reproducer project): https://gradle.com/s/q6rzhrslvp2tu

**Comment by big-guy** [comment]
I think this may be the same problem I came across and fixed last week.  Could you give the latest nightly (what will be 6.7) a try? 

`./gradlew wrapper --gradle-version=6.7-20200910233038+0000`

**Comment by bennofs** [comment]
@big-guy that was fast, that fixes it! thanks
