### ISSUE TITLE
Setting system properties throws a StackOverflowException

### ISSUE THREAD

**Issue by guylabs** [gradle/gradle#14639]
When using the latest nightly Gradle version we get the following error during the execution of a continuous task:

```
java.lang.StackOverflowError
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:77)
        at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:82)
...
```

This has already been discussed with @adammurdoch.

**Comment by facewindu** [comment]
This also happens in dotcom with latest 6.7 nightly

**Comment by eskatos** [comment]
@adammurdoch this is blocking GE folks, could you please take a look?

**Comment by ldaley** [comment]
I found an easy workaround on our side. If we change the dependency on gradleApi() in buildSrc from implementation to compileOnly we no longer have the problem.

We have some build logic using the worker process API. Looks like in that forked process, we are getting an instrumented `gradleApi()` being used.

**Comment by mlopatkin** [comment]
We should probably put some safeguards to avoid instrumenting the Gradle runtime.
