### ISSUE TITLE
Gradle 3.4 does not work with IntelliJ on MacOS

### ISSUE THREAD

**Issue by cluehr** [gradle/gradle#1468]
### Expected Behavior
I should be able to run the project from within IntelliJ on both, Linux and MacOS.

### Current Behavior
I'm trying to run a gradle project from within IntelliJ 2016.3.4. When doing this on a Ubuntu 16.10 with all updates installed everything works like a charm. But when importing the very same project into an IntelliJ on a Mac and trying to run the application from within IntelliJ I get some exceptions:
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/inject/Injector
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
    at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
    at java.lang.Class.getMethod0(Class.java:3018)
    at java.lang.Class.getMethod(Class.java:1784)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:126)
Caused by: java.lang.ClassNotFoundException: com.google.inject.Injector
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 6 more

Process finished with exit code 1
```
The configuration for IntelliJ is as similar as possible. The project contains the gradle wrapper. Compiling and running the project from the command line works on both systems like a charm. When I downgrade to gradle 3.3, without changing anything else in the project it works.

### Context
This issue prevents me from upgrading to gradle 3.4 as I neither can run the project nor debug it in IntelliJ

### Your Environment

 * Build scan URL:

**Comment by oehme** [comment]
See https://github.com/gradle/gradle/issues/1276 for an explanation and workaround.

**Comment by cluehr** [comment]
@oehme, thanks for pointing me to the other issue. This solved my issue.
