### ISSUE TITLE
Improve support for sharing services and configuration across the whole build tree

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#14697]
Although it should be avoided in general, there are cases where you need to share a certain _state_ across the whole build. In a single multi-project build, we currently recommend two features for this:

1. Caching computational intensive data globally or setting up a reusable runtime environment (e.g. for testing):
**-> Use a [Build Service](https://docs.gradle.org/current/userguide/build_services.html)**
2. Global configuration: sometimes you need configuration information shared over the whole build which is not static. That us, it changes frequently, potentially on each build invocation, and can thus not be statically defined in a _convention plugin_. An example of this is setting the version of all your projects to the same _version with timestamp_.
**-> Use an extension registered on the _root project_ (`rootProject.extensions`)**

If you setup a build as a hierarchy of included builds instead, these approaches do not work very well anymore, due to the classloader isolation. You can still use them, by going to the root of the composite and using that as a "central" place:

```
// helper to access the root, could be part of gradle API
fun Gradle.rootBuild(): Gradle = parent.let { it?.rootBuild() ?: this }

// conditionally register and get service (this works, because the type is not actually checked, only the name
val myService: BuildService = gradle.rootBuild.sharedServices.registerIfAbsent("myService", MyService.class) {}

// conditionally register and get extension (don't use getByType as that already checks the type and breaks)
var myExtension = gradle.rootBuild.rootProject.extensions.findByName("myExtension");
if (myExtension == null) {
    gradle.rootBuild.rootProject.extensions.create("myExtension", MyExtension::class);
}

/ / Now, to do something with the service or the extension, we cannot cast to the specific type as each project has the type in a different class loader. We need to use reflection.
// The generic type for a builds service is `BuildService` and for an extension it is `Object`.
```

There are different directions to solve this:
1. Make sure we don't use different classloaders. Maybe use one central classloader and filtering loaders on top instead of loading classes several time. (could also improve performance).
2. Do some kind of coercing so that  `sharedServices` and `extensions` can handle different instances of the same class object.
3. Solve the two use cases in a different way.

**Comment by marcphilipp** [comment]
As this sample project shows the same problem exists when two subprojects apply a different set of external plugins that are not applied by the root project (i.e. even without included builds): https://github.com/marcphilipp/gradle-sandbox/tree/master/td-class-loading-issue

**Comment by CK50** [comment]
Thank you for the above sample code. It helped a lot to understand the build issues we were facing.

Has anybody had a chance to actually try out the above work-around for sharing build services for included builds?

For us the registration worked fine (all services were registered to the root Gradle.sharedServices) and task.usesService() calls also went well, but when it comes to actual execution, the build fails with

```
org.gradle.api.UnknownDomainObjectException: BuildServiceRegistration with name 'xyzService' not found.	

		at org.gradle.api.internal.DefaultNamedDomainObjectCollection.createNotFoundException(DefaultNamedDomainObjectCollection.java:504)	
		at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:333)	
		at org.gradle.api.services.internal.DefaultBuildServicesRegistry.forService(DefaultBuildServicesRegistry.java:80)	
		at org.gradle.api.internal.AbstractTask.getSharedResources(AbstractTask.java:968)	
		at org.gradle.execution.plan.LocalTaskNode.getResourcesToLock(LocalTaskNode.java:86)	
		at org.gradle.execution.plan.DefaultExecutionPlan.tryLockSharedResourceFor(DefaultExecutionPlan.java:616)	
		at org.gradle.execution.plan.DefaultExecutionPlan.tryAcquireLocksForNode(DefaultExecutionPlan.java:579)	
		at org.gradle.execution.plan.DefaultExecutionPlan.selectNext(DefaultExecutionPlan.java:556)	
		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$executeNextNode$1(DefaultPlanExecutor.java:166)	
		at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)	
		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:155)	
		at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)	
		at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)	
		at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)	
		at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
```

From the above stack trace and from DefaultBuildServiceRegistry.java :
```
    public SharedResource forService(Provider<? extends BuildService<?>> service) {
        ...
        BuildServiceProvider<?, ?> provider = (BuildServiceProvider<?, ?>) service;
        DefaultServiceRegistration<?, ?> registration = (DefaultServiceRegistration<?, ?>) registrations.getByName(provider.getName());
```
it looks like during resource acquisition a service is located by its name (and not by its service registration object) *and* this name lookup is done on the **included** build's service registry only.

Anything I have overlooked? If not, can anybody see any other way for sharing build services in composite build scenarios?

To me this looks like a major limitation for build services, as particularly in large and composite builds we need to have control over use of common resources like for example port numbers used during (integration) tests.

Any thoughts much appreciated.

**Comment by jjohannes** [comment]
@CK50 Did you use the service registry of the **root build** everywhere? Currently each build has its own registry. That's one of the reasons why we need workarounds right now.

You need to navigate to the root build by navigating up the parents of `gradle`. E.g. like this in Kotlin:
`fun Gradle.rootBuild(): Gradle = parent.let { it?.rootBuild() ?: this }`

And the use `gradle.rootBuild().sharedServices...`.

**Comment by CK50** [comment]
Thank you for the quick response, @jjohannes !

Yes, we have applied all registrations to the gradle.parent.sharedServices and are able to see that all our services got registered there. As we are using Groovy, our code looks slightly different `build-parallelism.gradle`:
```
...
import com.oracle.dicom.gradle.Semaphore

// Fetch root build object
rootProject.ext.rootBuild = {  return ( gradle.parent != null )? gradle.parent:gradle }

// Create class object only once using top-level classloader
if ( !project.hasProperty('SemaphoreClass') || rootProject.rootBuild().ext.SemaphoreClass == null ) {
    rootProject.rootBuild().ext.SemaphoreClass = Semaphore.class
}
def semaphoreClass = rootProject.rootBuild().ext.SemaphoreClass

// Register a service and tell Gradle that these task need this build service
rootProject.ext.registerResourceUsage = {
    String resourceName,
    List<Task> tasks ->
        def semaphoreBuildService = rootProject.rootBuild().getSharedServices().registerIfAbsent( resourceName, semaphoreClass
                ,  { spec -> spec.getMaxParallelUsages().set(1) })
        def semRegis = rootProject.rootBuild().getSharedServices().getRegistrations()
        tasks*.usesService semaphoreBuildService
}
```

This allows us to simplify the declaration of tasks using port8080 to just:
```
registerResourceUsage( "port8080", [...,cTest] )
```

**Comment by jjohannes** [comment]
Looks like `usesService(...)` indeed does not work then yet in this setup. Could you make it work without that?

We have a branch where our build is turned into a composite. There we pass the service to a task though an internal property of the tasks. As in this example:
https://docs.gradle.org/current/userguide/build_services.html#registering_a_build_service

Register service:
https://github.com/gradle/gradle/blob/0863e59b909d6e5b70545d86a95922a646c88d5f/build-logic/build-logic/integration-testing/src/main/kotlin/gradlebuild.distribution-testing.gradle.kts#L30-L33

Pass the service to tasks:
https://github.com/gradle/gradle/blob/0863e59b909d6e5b70545d86a95922a646c88d5f/build-logic/build-logic/integration-testing/src/main/kotlin/gradlebuild.distribution-testing.gradle.kts#L53-L55

Could that work for you?

**Comment by CK50** [comment]
Thank you, @jjohannes - just a quick update: we could not get it to work and due to other prios we unfortunately cannot continue on this problem currently.

Once we get time to take up this composite build blocker, we were considering to patch Gradle distro until official fix/enhancement is avail: 

change `AbstractTask.gradle` from
```
@Override
    public List<ResourceLock> getSharedResources() {
        if (requiredServices == null) {
            return Collections.emptyList();
        }
        ImmutableList.Builder<ResourceLock> locks = ImmutableList.builder();
        BuildServiceRegistryInternal serviceRegistry = getServices().get(BuildServiceRegistryInternal.class);
        for (Provider<? extends BuildService<?>> service : requiredServices) {
            SharedResource resource = serviceRegistry.forService(service);
            if (resource.getMaxUsages() > 0) {
                locks.add(resource.getResourceLock(1));
            }
        }
        return locks.build();
    }
```

to 

```
@Override
    public List<ResourceLock> getSharedResources() {
        if (requiredServices == null) {
            return Collections.emptyList();
        }
        ImmutableList.Builder<ResourceLock> locks = ImmutableList.builder();
        BuildServiceRegistryInternal serviceRegistry = getServices().get(BuildServiceRegistryInternal.class);
        for (Provider<? extends BuildService<?>> service : requiredServices) {
            SharedResource resource;
            try {
                // Try finding shared resources on current gradle build object
                resource = serviceRegistry.forService(service);
            } catch (UnknownDomainObjectException e) {
                // Are we on some includedBuild ?
                if (project.getGradle().getParent()!=null) {
                    // Let us also consult the parent build's shared build services
                    resource = project.getGradle().getParent().getServices().get(BuildServiceRegistryInternal.class).forService(service)
                } else {
                    throw e;
                }
            }
            if (resource.getMaxUsages() > 0) {
                locks.add(resource.getResourceLock(1));
            }
        }
        return locks.build();
    }
```

We have **not** tried, yet and we do not know whether this will actually "solve" the issue. - just sharing in case anybody comes across this and finds this useful.

**Comment by jjohannes** [comment]
Is this part from the description still valid? 

> Global configuration: sometimes you need configuration information shared over the whole build which is not static. That is, it changes frequently, potentially on each build invocation, and can thus not be statically defined in a convention plugin. An example of this is setting the version of all your projects to the same version with timestamp.
-> Use an extension registered on the root project (rootProject.extensions)

Or should everything be shared via a _Build Service_? I recently saw this discussion that implied it:

https://twitter.com/_aurimas/status/1516071200924979202

> ... using a BuildService instead of a root project for the properties loading. Root project access will be turned down when Gradle project isolation is turned on.

Are there plans to make build services reusable across several builds in the build tree without the classloading problems this issue describes?

If there are different solutions for the use case described in this issue by now, an update on what the best practice is (or will be) would be appreciated.

**Comment by eskatos** [comment]
About global configuration, if you want to be future proof (configuration caching & project isolation) use a build service to share the state across projects of a build. For convenience you could have extensions registered on projects to access the shared service easily from the DSL for example.

Shared build services are shared across a single build. There are currently no plans for "_shared **build tree** services_" but the use case looks valid to me.
