### ISSUE TITLE
Module version parser cannot handle plus (+) in artifact names

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#1472]
The following module in Maven Central fails to parse:
```
Caused by: org.gradle.internal.typeconversion.UnsupportedNotationException: Cannot convert the provided notation to an object of type ModuleIdentifier: org.bouncycastle:bcmail-jdk15+.
The following types/formats are supported:
  - Instances of ModuleIdentifier.
  - String describing the module in 'group:name' format, for example 'org.gradle:gradle-core'..
        at org.gradle.internal.typeconversion.ErrorHandlingNotationParser.parseNotation(ErrorHandlingNotationParser.java:56)
        at org.gradle.api.internal.artifacts.dsl.ComponentModuleMetadataContainer.module(ComponentModuleMetadataContainer.java:40)
        at org.gradle.api.internal.artifacts.dsl.DefaultComponentModuleMetadataHandler.module(DefaultComponentModuleMetadataHandler.java:27)
        at org.gradle.api.internal.artifacts.dsl.DefaultComponentModuleMetadataHandler_Decorated.module(Unknown Source)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:464)
        at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:176)
        at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:59)
        at build_21nf2vm9lly06eaiqf6pv9p6l$_run_closure1$_closure2.doCall(/private/tmp/reduced/build.gradle:3)
```

### Expected Behavior
Module should be parsed.

### Current Behavior
Exception is thrown.

### Context
Note: That the suggestion of providing an instance of `ModuleIdentifier` requires the use of the internal Gradle API, as the `equals` methods for both default implementations `ModuleIdentifier` and `ModuleVersionIdentifier` are coupled to the concrete class, instead of comparing by interface, making it impossible for any non-Gradle implementation of this interface to work.

Believe both of these implementations should be public, with appropriate factories exposed to ease creation of the ids.

### Steps to Reproduce

Create a build with the following configuration:

```
dependencies {
        modules {
                module('org.bouncycastle:bcmail-jdk15+') {
                        it.replacedBy('org.bouncycastle:bcmail-jdk15on')
                }
        }
}

```

### Your Environment
Gradle 3.4

**Comment by eriwen** [comment]
Thanks for the great bug report as always, Danny.
