### ISSUE TITLE
Transformed build logic cache gets corrupted if the daemon is killed at a bad time

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#14773]
Gradle instruments the classpath of build logic and store the resulting jars in a global cache.
If the daemon gets killed, either by a user or a system, it can happen that this cache gets corrupted.

### Expected Behavior

Whenever the daemon is killed, the cache doesn't get corrupted.

### Current Behavior

The cache can get into a corrupted state leading to hard to troubleshoot build errors.

<details><summary>Stacktrace</summary>
<p>

```
Failed to execute org.gradle.cache.internal.AsyncCacheAccessDecoratedCache$2@63674c73.
    org.gradle.api.UncheckedIOException: Could not add entry '/some/buildagent/.client-android-docker-isolated-gradle/caches/jars-8/5b154448518a2210446b7870556c4a30' to cache file-access.bin (/some/buildagent/.client-android-docker-isolated-gradle/caches/journal-1/file-access.bin).
      at org.gradle.cache.internal.btree.BTreePersistentIndexedCache.put(BTreePersistentIndexedCache.java:162)
      at org.gradle.cache.internal.DefaultMultiProcessSafePersistentIndexedCache$2.run(DefaultMultiProcessSafePersistentIndexedCache.java:74)
      at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.doWriteAction(DefaultFileLockManager.java:215)
      at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.writeFile(DefaultFileLockManager.java:205)
      at org.gradle.cache.internal.DefaultCacheAccess$UnitOfWorkFileAccess.writeFile(DefaultCacheAccess.java:449)
      at org.gradle.cache.internal.DefaultMultiProcessSafePersistentIndexedCache.put(DefaultMultiProcessSafePersistentIndexedCache.java:71)
      at org.gradle.cache.internal.AsyncCacheAccessDecoratedCache$2.run(AsyncCacheAccessDecoratedCache.java:64)
      at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
      at org.gradle.cache.internal.CacheAccessWorker$2.run(CacheAccessWorker.java:185)
      at org.gradle.internal.Factories$1.create(Factories.java:26)
      at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:220)
      at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:201)
      at org.gradle.cache.internal.CacheAccessWorker.flushOperations(CacheAccessWorker.java:175)
      at org.gradle.cache.internal.CacheAccessWorker.run(CacheAccessWorker.java:145)
      at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
      at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
      at java.lang.Thread.run(Thread.java:748)
    Caused by: org.gradle.cache.internal.btree.CorruptedCacheException: Corrupted FreeListBlock 20459601 found in cache '/some/buildagent/.client-android-docker-isolated-gradle/caches/journal-1/file-access.bin'.
      at org.gradle.cache.internal.btree.FileBackedBlockStore$BlockImpl.blockCorruptedException(FileBackedBlockStore.java:267)
      at org.gradle.cache.internal.btree.FileBackedBlockStore$BlockImpl.read(FileBackedBlockStore.java:260)
      at org.gradle.cache.internal.btree.FileBackedBlockStore.read(FileBackedBlockStore.java:123)
      at org.gradle.cache.internal.btree.CachingBlockStore.read(CachingBlockStore.java:100)
      at org.gradle.cache.internal.btree.FreeListBlockStore.read(FreeListBlockStore.java:86)
      at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.getNextBlock(FreeListBlockStore.java:215)
      at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:232)
      at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:232)
      at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:232)
      at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:232)
      at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:232)
      at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:232)
      at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:232)
      at org.gradle.cache.internal.btree.FreeListBlockStore.attach(FreeListBlockStore.java:98)
      at org.gradle.cache.internal.btree.FreeListBlockStore.write(FreeListBlockStore.java:91)
      at org.gradle.cache.internal.btree.StateCheckBlockStore.write(StateCheckBlockStore.java:73)
      at org.gradle.cache.internal.btree.BTreePersistentIndexedCache.put(BTreePersistentIndexedCache.java:157)
      ... 19 more
```

</p>
</details>

### Context

This was reported to happen on CI where the system kills the daemon right at a time that lead to a corrupted cache.

**Comment by eskatos** [comment]
We have a similar problem with other caches where we handle this in an ad-hoc way. There should be an uniform way to solve this problem for all of our caches. See https://github.com/gradle/gradle/issues/14774

**Comment by lptr** [comment]
It would be interesting to understand why the build doesn't fail due to this corrupted cache entry, though. Seems like the exception just falls through...
