### ISSUE TITLE
Gradle 3.4 java-library plugin cannot be applied

### ISSUE THREAD

**Issue by hierynomus** [gradle/gradle#1485]
I was trying to migrate [sshj](https://github.com/hierynomus/sshj) to use the newly released Gradle 3.4 `java-library` plugin. However it seems that when using that together with the `org.ajoberstar.release-opinion` plugin (from: @ajoberstar), it fails with the following message:

    An exception occurred applying plugin request [id: 'java-library']
    > Failed to apply plugin [id 'org.gradle.java-library']
       > Cannot invoke method status() on null object

When running with `-s` you get the following stacktrace:

```
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'org.gradle.java-library']
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:155)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:104)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$6.run(DefaultPluginRequestApplicator.java:185)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:212)
        ... 61 more
Caused by: java.lang.NullPointerException: Cannot invoke method status() on null object
        at org.ajoberstar.gradle.git.release.semver.RebuildVersionStrategy.selector(RebuildVersionStrategy.groovy:55)
        at org.ajoberstar.gradle.git.release.base.VersionStrategy$selector$0.call(Unknown Source)
        at org.ajoberstar.gradle.git.release.base.ReleasePluginExtension$_DelayedVersion_infer_closure1.doCall(ReleasePluginExtension.groovy:102)
        at org.ajoberstar.gradle.git.release.base.ReleasePluginExtension$DelayedVersion.infer(ReleasePluginExtension.groovy:101)
        at org.ajoberstar.gradle.git.release.base.ReleasePluginExtension$DelayedVersion.toString(ReleasePluginExtension.groovy:127)
        at org.gradle.api.internal.artifacts.ProjectBackedModule.getVersion(ProjectBackedModule.java:38)
        at org.gradle.api.internal.artifacts.dsl.PublishArtifactNotationParserFactory$FileNotationConverter.parseType(PublishArtifactNotationParserFactory.java:109)
        at org.gradle.api.internal.artifacts.dsl.PublishArtifactNotationParserFactory$FileMapNotationConverter.parseMap(PublishArtifactNotationParserFactory.java:97)
        at org.gradle.internal.typeconversion.MapNotationConverter.parseType(MapNotationConverter.java:90)
        at org.gradle.internal.typeconversion.MapNotationConverter.parseType(MapNotationConverter.java:38)
        at org.gradle.internal.typeconversion.TypedNotationConverter.convert(TypedNotationConverter.java:43)
        at org.gradle.internal.typeconversion.CompositeNotationConverter.convert(CompositeNotationConverter.java:33)
        at org.gradle.internal.typeconversion.NotationConverterToNotationParserAdapter.parseNotation(NotationConverterToNotationParserAdapter.java:30)
        at org.gradle.internal.typeconversion.ErrorHandlingNotationParser.parseNotation(ErrorHandlingNotationParser.java:47)
        at org.gradle.api.internal.artifacts.configurations.DefaultVariant.artifact(DefaultVariant.java:95)
        at org.gradle.api.plugins.JavaLibraryPlugin.addVariant(JavaLibraryPlugin.java:68)
        at org.gradle.api.plugins.JavaLibraryPlugin.addApiToMainSourceSet(JavaLibraryPlugin.java:62)
        at org.gradle.api.plugins.JavaLibraryPlugin.apply(JavaLibraryPlugin.java:48)
        at org.gradle.api.plugins.JavaLibraryPlugin.apply(JavaLibraryPlugin.java:39)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
        at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:139)
        ... 64 more
```

The following snippet can be used to reproduce this issue

```groovy
plugins {
	id 'java-library'
	id 'org.ajoberstar.release-opinion' version '1.6.0'
}

release {
	grgit = org.ajoberstar.grgit.Grgit.open(project.projectDir)
}
```

It seems to be that when it tries to apply the plugin it has already applied the other plugins (the release plugin being one of them), but somehow the project configuration, which sets the `grgit` field on the extension has not been applied yet, causing it to call `status()` on a null reference.

Note: This only happens with the `java-library` plugin, the `java` plugin works fine still.

**Comment by hierynomus** [comment]
Just had a look at the code. I see that some work has been done on the exact lines which were hit in the stacktrace in this commit: 559a9f8a693ca0fca216155ee59a1a77129d11ee

**Comment by hierynomus** [comment]
After checking this indeed seems to have been fixed by 559a9f8. Looking forward to a new release which includes that!

**Comment by oehme** [comment]
Indeed this has been fixed by "accidentally" by using a different code path. `artifact(Map)` or `artifact(File)` evaluate `Project.version` eagerly.

I think the release plugin by @ajoberstar needs a small fix to avoid similar situations with other plugins that add artifacts: It adds a "DelayedVersion" which needs a non-null `grgit` instance. But the `grgit` instance is only created later, so it might be null if `DelayedVersion#toString()` is called early.

**Comment by ajoberstar** [comment]
I'll have to look more closely at what happens in this situation, but the only way I could get this to work before is just delay version inference until the first time something toString's the version. If something needs the version, I need to figure it out right away or else the build's going to use inconsistent values. If the `java-library` plugin is calling that too early now, I think that's going to be problematic for my plugin's use case. Unless there's a reliable non-internal way to handle this ordering with Gradle (which there hasn't been in the past).
