### ISSUE TITLE
HttpBuildCacheService doesn't cope well with stale connections

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#14943]
We're seeing these exceptions occasionally that seems to indicate the `HttpBuildCacheService` is reusing a stale connection:

```
Caused by: org.apache.http.NoHttpResponseException: gradle.netflix.net:443 failed to respond	
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)	
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)	
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)	
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)	
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)	
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)	
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)	
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)	
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)	
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)	
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)	
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)	
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:141)	
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:117)	
	at org.gradle.caching.http.internal.HttpBuildCacheService.store(HttpBuildCacheService.java:159)	
	at org.gradle.caching.internal.controller.service.BaseBuildCacheServiceHandle.storeInner(BaseBuildCacheServiceHandle.java:93)
```

### Expected Behavior
Stale connections should be tolerated.

### Current Behavior
The pool can return stale connections and attempt to use them.

### Context
Build caching is disabled for a build.

### Steps to Reproduce 
Unclear. We're running a default Varnish configuration for timeouts, which has a generous 60 second connection idle timeout - https://info.varnish-software.com/blog/understanding-timeouts-varnish-cache.

### Your Environment
Gradle 6.4.1

**Comment by DanielThomas** [comment]
We see the same on fetches, which impacts the effectiveness of the cache as it turns off for the remainder of the build:

```
I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://gradle.netflix.net:443: The target server failed to respond
Retrying request to {s}->https://gradle.netflix.net:443
I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://gradle.netflix.net:443: The target server failed to respond
Retrying request to {s}->https://gradle.netflix.net:443
I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://gradle.netflix.net:443: The target server failed to respond
Retrying request to {s}->https://gradle.netflix.net:443
Could not load entry 7f255528692e6b8306a02828ffd93128 from remote build cache: gradle.netflix.net:443 failed to respond
```

**Comment by ldaley** [comment]
@DanielThomas this indicates that how your proxy is closing connections is not visible to the client. Do you have any details on exactly what your proxy is doing when it closes a connection?

**Comment by DanielThomas** [comment]
It would appear that `timeout_idle` is the prevailing timeout, it's 5s by default (https://info.varnish-software.com/blog/understanding-timeouts-varnish-cache), but Varnish received the whole request here.

Here's that session, two requests:
```
{
  "tag": "Begin",
  "value": "sess 0 PROXY"
},
{
  "tag": "SessOpen",
  "value": "0.0.0.0 0 a2 0.0.0.0 0 1605223476.669103 755"
},
{
  "tag": "Proxy",
  "value": "2 172.24.0.39 61006 100.70.72.14 443"
},
{
  "tag": "Link",
  "value": "req 188125996 rxreq"
},
{
  "tag": "Link",
  "value": "req 186631459 rxreq"
},
{
  "tag": "SessClose",
  "value": "RX_TIMEOUT 10.060"
},
{
  "tag": "End",
  "value": ""
}
```

First request:
```
{
  "tag": "Begin",
  "value": "req 188125995 rxreq"
},
{
  "tag": "Timestamp",
  "value": "Start: 1605223476.669175 0.000000 0.000000"
},
```

Second request, literally `5.007522` between them:
```
{
  "tag": "Begin",
  "value": "req 188125995 rxreq"
},
{
  "tag": "Timestamp",
  "value": "Start: 1605223481.676697 0.000000 0.000000"
},
```

Those errors do seem to indicate that the retries are trying to reuse a stale connections. _Maybe_ we got really unlucky and the pool returned three similarly stale connections in a row. I only see one request, but may be those second and third attempts didn't get that far (but the error seems to indicate the request was sent)?

This is also the same infrastructure that serves all our artifact traffic and we don't see outright failures like this at all, but maybe we're seeing some retries - I'll go look at our metrics. I'll open a case with Varnish to understand the behaviour better too before we increase the setting.

Is 30s still the default idle timeout for Gradle HTTP client connections?

**Comment by DanielThomas** [comment]
Some background on the stale connections with httpclient. The repeated failures make me thing it's is those connections with RX_TIMEOUT are not reset, as I'd think the connection check would catch those (unless it was a race between the check and the request being made, but doesn't feel like it):

http://hc.apache.org/httpcomponents-client-ga/tutorial/html/connmgmt.html#d5e418

Sounds like we can also control this behaviour with the response, which is good to know:

> Some HTTP servers use a non-standard `Keep-Alive` header to communicate to the client the period of time in seconds they intend to keep the connection alive on the server side. HttpClient makes use of this information if available.

**Comment by DanielThomas** [comment]
In fact I bet we're seeing this with artifact requests too, but connection reuse is rapid enough that timeouts are rarer and retries are enough to stop the issue bubbling up.

**Comment by DanielThomas** [comment]
It is a regular close on this timeout, so HttpClient should be seeing those connection closures. Let me run some tests with debug logging for HttpClient and see if I can get some more clarity on what's going on before I make any changes to the timeouts:

> Good catch. It looks like the blog post is a bit unclear on that particular point. It says `timeout_idle` is from `accept()` until we receive the start of a request and then at the very end it mentions that `timeout_idle` also applies in between requests for keepalive.
> 
> On `RX_TIMEOUT` we do a regular `close()` which will trigger the `FIN/FIN-ACK`. 
> 
> Worth mentioning is that there is a potential for a race condition here, if the client sends a request just close enough to the timeout. Varnish could even have  the `FIN` in flight as the client sends the next request. 
> 
> To summarize, the `timeout_idle` is the prevailing timeout. It applies both to the initial request and also to the in between requests before we have received any data. 
> `RX_TIMEOUT` does a `close()`, which should result in a regular `FIN` shutdown (i.e. the other end should see this).

**Comment by DanielThomas** [comment]
The debug logs indicate we are hitting three seperate stale connections when this bubbles up, they're being correctly closed on error. There's quite a bit of outdated information about the staleness checks. The staleness check on every connection lease was removed some time ago:

https://github.com/apache/httpcomponents-client/commit/c5c0bc680180c3ccac90430a6380901dc1e968df

That's been replaced with `getValidateAfterInactivity` and as of 4.4 that appears to be 2s by default, which means I'd expect those should catch the 5s timeouts:

https://github.com/apache/httpcomponents-client/blob/4.5.x/httpclient/src/main/java/org/apache/http/impl/conn/PoolingHttpClientConnectionManager.java#L183

I can reproduce the retries easily enough, though all three retries for a single request hitting stale connections is rarer. Here's a complete session with a single retry:

```
2020-11-16T08:57:26.679+1100 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Load entry d6ceb730b5a490bea6c9b135a93d7fbd from remote build cache' started
2020-11-16T08:57:26.679+1100 [DEBUG] [org.gradle.internal.resource.transport.http.HttpClientHelper] Performing HTTP GET: https://gradle.netflix.net/cache/d6ceb730b5a490bea6c9b135a93d7fbd
2020-11-16T08:57:27.245+1100 [DEBUG] [org.apache.http.impl.conn.DefaultHttpClientConnectionOperator] Connection established 172.24.0.45:53505<->100.70.101.191:443
2020-11-16T08:57:27.246+1100 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnection] http-outgoing-32: set socket timeout to 30000
2020-11-16T08:57:27.246+1100 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Executing request GET /cache/d6ceb730b5a490bea6c9b135a93d7fbd HTTP/1.1
2020-11-16T08:57:27.246+1100 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Target auth state: UNCHALLENGED
2020-11-16T08:57:27.246+1100 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Proxy auth state: UNCHALLENGED
2020-11-16T08:57:27.415+1100 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Connection can be kept alive indefinitely
2020-11-16T08:57:27.419+1100 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Connection can be kept alive indefinitely
2020-11-16T08:57:27.442+1100 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Connection can be kept alive indefinitely
2020-11-16T08:57:27.443+1100 [DEBUG] [org.gradle.caching.http.internal.HttpBuildCacheService] Response for GET https://gradle.netflix.net/cache/d6ceb730b5a490bea6c9b135a93d7fbd: HTTP/1.1 200 OK
2020-11-16T08:57:33.541+1100 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection [id: 32][route: {s}->https://gradle.netflix.net:443] can be kept alive indefinitely
2020-11-16T08:57:33.542+1100 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnection] http-outgoing-32: set socket timeout to 0
2020-11-16T08:57:33.543+1100 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection released: [id: 32][route: {s}->https://gradle.netflix.net:443][total kept alive: 7; route allocated: 8 of 20; total allocated: 8 of 20]
2020-11-16T08:57:33.548+1100 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Load entry d6ceb730b5a490bea6c9b135a93d7fbd from remote build cache'
2020-11-16T08:57:33.549+1100 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Load entry d6ceb730b5a490bea6c9b135a93d7fbd from remote build cache' completed
```

There's less than two seconds between the connection being returned and leased again, so it's not checked for staleness, but it also shouldn't have timed out yet. `HttpBuildCacheService` isn't doing anything unusual with the connection, it's streaming the response entity directly so the connection should have been returned to the pool immediately after the response was finished being read:
```
2020-11-16T08:57:35.243+1100 [DEBUG] [org.gradle.caching.internal.controller.service.OpFiringBuildCacheServiceHandle] Load entry 7f255528692e6b8306a02828ffd93128 from remote build cache
2020-11-16T08:57:35.243+1100 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Load entry 7f255528692e6b8306a02828ffd93128 from remote build cache' started
2020-11-16T08:57:35.244+1100 [DEBUG] [org.gradle.internal.resource.transport.http.HttpClientHelper] Performing HTTP GET: https://gradle.netflix.net/cache/7f255528692e6b8306a02828ffd93128
2020-11-16T08:57:35.244+1100 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection request: [route: {s}->https://gradle.netflix.net:443][total kept alive: 7; route allocated: 8 of 20; total allocated: 8 of 20]
2020-11-16T08:57:35.244+1100 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection leased: [id: 32][route: {s}->https://gradle.netflix.net:443][total kept alive: 6; route allocated: 8 of 20; total allocated: 8 of 20]
2020-11-16T08:57:35.244+1100 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnection] http-outgoing-32: set socket timeout to 30000
2020-11-16T08:57:35.245+1100 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnection] http-outgoing-32: set socket timeout to 30000
2020-11-16T08:57:35.245+1100 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Executing request GET /cache/7f255528692e6b8306a02828ffd93128 HTTP/1.1
2020-11-16T08:57:35.245+1100 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Target auth state: UNCHALLENGED
2020-11-16T08:57:35.245+1100 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Proxy auth state: UNCHALLENGED
2020-11-16T08:57:35.246+1100 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnection] http-outgoing-32: Close connection
2020-11-16T08:57:35.247+1100 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnection] http-outgoing-32: Shutdown connection
2020-11-16T08:57:35.247+1100 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Connection discarded
2020-11-16T08:57:35.247+1100 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection released: [id: 32][route: {s}->https://gradle.netflix.net:443][total kept alive: 6; route allocated: 7 of 20; total allocated: 7 of 20]
2020-11-16T08:57:35.247+1100 [DEBUG] [org.apache.http.impl.execchain.RetryExec] The target server failed to respond
```

Which is caused by the same timeout as before:
```
{
  "tag": "Begin",
  "value": "sess 0 PROXY"
},
{
  "tag": "SessOpen",
  "value": "0.0.0.0 0 a2 0.0.0.0 0 1605477447.419865 532"
},
{
  "tag": "Proxy",
  "value": "2 172.24.0.45 53505 100.70.110.221 443"
},
{
  "tag": "Link",
  "value": "req 332558867 rxreq"
},
{
  "tag": "SessClose",
  "value": "RX_TIMEOUT 5.249"
},
{
  "tag": "End",
  "value": ""
}
```

Which lead me back to the Varnish blog post:

> In the other cases `timeout_idle` starts ticking after the request handling is done, and that implements the keepalive timeout in Varnish Cache.

That seems to indicate that the timeout starts when request handling is finished, not when the response has been read. If I rate limit keep alive requests, that's what I see:

```
curl -o /tmp/test --http1.1 --limit-rate 250K -v https://gradle.netflix.net/cache/d6ceb730b5a490bea6c9b135a93d7fbd https://gradle.netflix.net/cache/7f255528692e6b8306a02828ffd93128

...

* Connection #0 to host gradle.netflix.net left intact
* Connection 0 seems to be dead!
* Closing connection 0
```

I'll follow up with Varnish on that. I think HttpClient could do a better job of checking for closed connections, curl appears to do this really cheaply and effectively, but this makes keep alive ineffective for requests with large responses.

**Comment by DanielThomas** [comment]
Looks like that also makes the {{Keep-Alive}} header support ineffective too - it (correctly) starts that duration ticking when the connection is released back to the pool:

https://github.com/apache/httpcomponents-client/blob/4.5.x/httpclient/src/main/java/org/apache/http/impl/execchain/MainClientExec.java#L275-L289
https://github.com/apache/httpcomponents-client/blob/4.5.x/httpclient/src/main/java/org/apache/http/impl/execchain/ConnectionHolder.java#L99-L100

**Comment by DanielThomas** [comment]
The default 2s idle check threshold seems incredibly conservative, I can't imagine that it's worst case performance for this method could be more than a ms or two:

https://github.com/apache/httpcomponents-core/blob/4.4.x/httpcore/src/main/java-deprecated/org/apache/http/impl/AbstractHttpClientConnection.java#L314-L330

In fact I ran a quick test setting the threshold to 1ms with a 1ms sleep to ensure the check ran for every lease and the overhead for open connections (which I guess _is_ the worst case, I bet closed connections wouldn't need for wait for the 1ms timeout) and the overhead is tiny:

<img width="1338" alt="Screen Shot 2020-11-16 at 1 14 14 pm" src="https://user-images.githubusercontent.com/1479220/99205925-19a79b80-280e-11eb-9d0d-232d9e41d6df.png">

So you might consider decreasing this threshold so you can keep retries for failures unrelated to the pooled connection state.

**Comment by ldaley** [comment]
@DanielThomas thank you very much for the investigation and wealth of information.

**Comment by DanielThomas** [comment]
To mitigate this with Varnish we increase `timeout_idle` from the default `5s` to `30s` for a session following a delivered requests to allow connection reuse for that period and put us well inside the test on lease threshold for HttpClient:
```
sub vcl_deliver {
    // increase timeout_idle for subsequent requests
    set sess.timeout_idle = 30s;
}
```

**Comment by ldaley** [comment]
@DanielThomas is that a satisfactory result for you? Or do you still see a need for a more aggressive aliveness check?

**Comment by DanielThomas** [comment]
@ldaley I would have said this is fine for us, but we're also seeing this during publishing. Still unclear if it's stale connections however, but does seem like non-retryable requests like this are more likely to see failures that cause this to fail outright:

https://github.com/Netflix/mantis-gradle-plugin/runs/2079912807?check_suite_focus=true

FWIW I also looked at what OkHttp does for comparison, and it's far more aggressive doing an extensive check for every connection except if it's a `GET` request, using similar method to Apache HttpClient if the Socket is still believed to be open:

https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/internal/connection/ExchangeFinder.kt#L80
https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/internal/connection/RealConnection.kt#L646-L671
https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/internal/Util.kt#L377-L400

**Comment by ldaley** [comment]
@DanielThomas I'll work this into our plans. 

We are also going to make the writes retryable in an upcoming round of work.

**Comment by JLLeitschuh** [comment]
This may be improved by https://github.com/gradle/gradle/pull/19196
