### ISSUE TITLE
Watching the file system is not supported on this operating system.

### ISSUE THREAD

**Issue by devcken** [gradle/gradle#14944]
### Expected Behavior
Watching file system enabled

### Current Behavior
Watching file system disabled

### Context
I tried to build my project on Jenkins. After Gradle 6.7 is downloaded, Gradle Daemon is started. But, watching file system is NOT enabled with a message:

```
Watching the file system is not supported on this operating system.
```

### Steps to Reproduce 
Just try to build

### Your Environment
OS system: CentOS Linux release 7.6.1810(core)
Build scan URL: -

**Comment by lptr** [comment]
This is interesting. We should be supporting CentOS 7 (but not 6). And we shouldn't print that message unless you somehow enabled watching... Can you maybe share a build scan?

**Comment by devcken** [comment]
> This is interesting. We should be supporting CentOS 7 (but not 6). And we shouldn't print that message unless you somehow enabled watching... Can you maybe share a build scan?

Impossible :(  CI/CD server is in private network.

**Comment by devcken** [comment]
I got this log:

```
Native file system watching is not available for this operating system.
net.rubygrapefruit.platform.NativeIntegrationLinkageException: Native library 'libnative-platform-file-events.so' could not be loaded for Linux amd64.
	at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:61)
	at net.rubygrapefruit.platform.file.FileEvents.init(FileEvents.java:35)
	at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:120)
	at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:84)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:42)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:240)
	at org.gradle.launcher.Main.doAction(Main.java:35)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Caused by: java.lang.UnsatisfiedLinkError: /home/deploy/.gradle/native/12488b8bf47d2d4c9fbf2f6322a914ad602e24e48041cd04a747c6da556b65c4/linux-amd64/libnative-platform-file-events.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/deploy/.gradle/native/12488b8bf47d2d4c9fbf2f6322a914ad602e24e48041cd04a747c6da556b65c4/linux-amd64/libnative-platform-file-events.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:51)
	... 24 more
```

**Comment by wolfs** [comment]
@devcken File system watching needs at least CentOs 8 to work (see the [user manual](https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:daemon_watch_fs)).

If I understand correctly, you did enable file system watching for your build, right? Gradle should not print `Watching the file system is not supported on this operating system.` when file system watching is not enabled.

**Comment by devcken** [comment]
@wolfs 
Oh, I should have looked up carefully at OS support.
I appreciate your help.
Have a nice day!
