### ISSUE TITLE
Unhelpful error message during IDE sync with the Kotlin DSL

### ISSUE THREAD

**Issue by melix** [gradle/gradle#15007]
If a Kotlin build script contains an error, IDE sync fails in IntelliJ with an error which starts with:

```
org.gradle.cache.CacheOpenException: Could not open cache directory 9zgtqu5vj1kdsa2qaghbh3m5d (/home/cchampeau/.gradle/caches/6.8-20201028092701+0000/gradle-kotlin-dsl/9zgtqu5vj1kdsa2qaghbh3m5d).
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:80)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:42)
	at org.gradle.cache.internal.DefaultCacheFactory.doOpen(DefaultCacheFactory.java:95)
	at org.gradle.cache.internal.DefaultCacheFactory.open(DefaultCacheFactory.java:68)
```

It takes a large amount of scrolling to get to the _actual_ problem, which is:

```
Caused by: org.gradle.internal.exceptions.LocationAwareException: Build file '/home/cchampeau/DEV/PROJECTS/repros/mylib/lib/build.gradle.kts' line: 23
Script compilation error:
  Line 23:     testImplementation(testLibs.junit)
                                           ^ Unresolved reference: junit
1 error
```

The fact that the cache couldn't be open is a _consequence_ of the compilation error and this is what is shown to the user first. However, this isn't helpful because what we really want to know is that there's a compilation error.

**Comment by donat** [comment]
I quickly tried to reproduce the problem with the latest IntelliJ version, but it seems to produce the correct `Unresolved reference` error message during sync. If this is still an issue, please provide a minimal reproducer and I'll continue investigating.

**Comment by donat** [comment]
Closing as stale.
