### ISSUE TITLE
Unit tests fail on Windows when 8dot3name is disabled

### ISSUE THREAD

**Issue by jacobilsoe** [gradle/gradle#1500]
I am trying to run the unit tests on Windows on a volume where 8dot3name is disabled. Two tests fail though. The current 8dot3name can be found by issuing this from a command prompt:
```
fsutil.exe 8dot3name query c: 
```
### Expected Behavior
The tests should succeed regardless of the 8dot3name configuration.

### Current Behavior
The following two tests fail when 8dot3name is disabled:
```
org.gradle.api.internal.file.BaseDirFileResolverSpec > normalizes path which uses windows 8.3 name
org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalkerTest > both DirectoryWalker implementations return same set of files and attributes
```
### Steps to Reproduce (for bugs)
Run gradlew :core:test on Windows on a volume where 8dot3name is disabled

### Your Environment
Windows 8

**Comment by lacasseio** [comment]
Thanks for reporting this @jacobilsoe. Could you [submit a build scan](https://gradle.com/scans/get-started) for your scenario?

**Comment by jacobilsoe** [comment]
@lacasseio: Sure, here's a [build scan](https://scans.gradle.com/s/qmaz5kwi3atsu). I ran the tests on a different OS than last time and now only the 8.3 name test fails. I will look into making the other fail as well. To reproduce the error I issued this from a command prompt: ```fsutil.exe 8dot3name set c: 1```.

**Comment by jacobilsoe** [comment]
Here's some test output from the other test:
```
Condition not satisfied:

detailsFromJdk7Walker != null && millisToSeconds(details.lastModified) == millisToSeconds(detailsFromJdk7Walker.lastModified) && details.directory == detailsFromJdk7Walker.directory && (details.directory || details.size == detailsFromJdk7Walker.size)
|                     |       |  |               |       |             |  |               |                     |             |                                                       |
|                     true    |  1488708124      |       1488708124075 |  1488708123      |                     1488708123960 false                                                   false
|                             false              |                     false              file 'D:\GIT\gradle-jacobilsoe\subprojects\core\build\tmp\test files\Jdk7DirectoryWalkerTest\both_DirectoryWalke...ttributes\fs3gl\root\dir275\dir297'
|                                                file 'D:\GIT\gradle-jacobilsoe\subprojects\core\build\tmp\test files\Jdk7DirectoryWalkerTest\both_DirectoryWalke...ttributes\fs3gl\root\dir275\dir297'
file 'D:\GIT\gradle-jacobilsoe\subprojects\core\build\tmp\test files\Jdk7DirectoryWalkerTest\both_DirectoryWalke...ttributes\fs3gl\root\dir275\dir297'

	at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalkerTest.checkFileVisitDetailsEqual_closure1(Jdk7DirectoryWalkerTest.groovy:135)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalkerTest.checkFileVisitDetailsEqual(Jdk7DirectoryWalkerTest.groovy:129)
	at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalkerTest.both DirectoryWalker implementations return same set of files and attributes(Jdk7DirectoryWalkerTest.groovy:125)
```
