### ISSUE TITLE
Make dependenciesModel.fromFile error message more helpful if file is missing

### ISSUE THREAD

**Issue by ducrohet** [gradle/gradle#15029]
Gradle nightly: 6.8-20201028230040+0000

settings.gradle:
```
dependencyResolutionManagement {
    dependenciesModel("libs") {
    }

    dependenciesModel("testLibs") {
        from(file("../gradle/test-dependencies.toml"))
    }
}
```

I get the following error, whether the toml file exists or not:

```
org.gradle.api.GradleScriptException: A problem occurred evaluating settings 'NewPluginDsl'.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.lambda$apply$0(DefaultScriptPluginFactory.java:133)
        at org.gradle.configuration.DefaultScriptTarget.addConfiguration(DefaultScriptTarget.java:74)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:136)
        at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:65)
        at ...
Caused by: org.gradle.api.internal.provider.MissingValueException: Cannot query the value of this provider because it has no value available.
        at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:86)
        at org.gradle.api.internal.std.DefaultDependenciesModelBuilder.from(DefaultDependenciesModelBuilder.java:115)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:484)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:196)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
        at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:34)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:56)
        at settings_6ac4g0nrcs0pgtfuhoia0w520$_run_closure1$_closure4.doCall(/Users/xxx/MyProject/settings.gradle:21)
        at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:105)
        at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:166)
        at org.gradle.internal.management.DefaultDependencyResolutionManagement.dependenciesModel(DefaultDependencyResolutionManagement.java:150)
        at org.gradle.internal.management.DefaultDependencyResolutionManagement_Decorated.dependenciesModel(Unknown Source)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:484)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:196)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
        at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:34)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:56)
        at settings_6ac4g0nrcs0pgtfuhoia0w520$_run_closure1.doCall(/Users/xav/AndroidStudioProjects/NewPluginDsl/settings.gradle:20)
        at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:105)
        at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:166)
        at org.gradle.initialization.DefaultSettings.dependencyResolutionManagement(DefaultSettings.java:371)
        at org.gradle.initialization.DefaultSettings_Decorated.dependencyResolutionManagement(Unknown Source)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:484)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:196)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
        at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:34)
        at org.gradle.groovy.scripts.BasicScript$ScriptDynamicObject.tryInvokeMethod(BasicScript.java:135)
        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
        at org.gradle.groovy.scripts.BasicScript.invokeMethod(BasicScript.java:84)
        at settings_6ac4g0nrcs0pgtfuhoia0w520.run(/Users/xav/AndroidStudioProjects/NewPluginDsl/settings.gradle:8)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
        ... 133 more
```

**Comment by melix** [comment]
Apparently you're using the main settings file (        at NewPluginDsl/settings.gradle:8)). 

This code would work for the `buildSrc/settings.gradle` file (this is why you need the `../`).

**Comment by melix** [comment]
I guess you were trying to use it in the main settings file actually, so you just need to remove the `../` to make it work.

**Comment by ducrohet** [comment]
🤦  Thanks!

But yeah, the error could be better :)
