### ISSUE TITLE
Bundled Kotlin stdlib preferred over classpath dependencies 

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#15020]
We ran into a compatibility issue with a plugin that used okhttp3/okio on the classpath caused by the bundled Kotlin version on the classpath:

```
Caused by: java.lang.NoSuchMethodError: kotlin.collections.ArraysKt.copyInto([B[BIII)[B
        at okio.Segment.writeTo(Segment.kt:169)
        at okio.Segment.compact(Segment.kt:152)
        at okio.Buffer.write(Buffer.kt:1842)
        at okio.Buffer.read(Buffer.kt:1854)
        at okio.Buffer.writeAll(Buffer.kt:1642)
        at okio.Options$Companion.buildTrieRecursive(Options.kt:187)
        at okio.Options$Companion.buildTrieRecursive(Options.kt:174)
        at okio.Options$Companion.buildTrieRecursive$default(Options.kt:113)
        at okio.Options$Companion.of(Options.kt:72)
        at okhttp3.internal.Util.<clinit>(Util.kt:71)
        at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309)
        at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41)
        at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
        at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471)
```

That means when developing plugins in Kotlin we have to be very aware of not exceeding stdlib compatibility for the bundled Gradle Kotlin standard library version.

### Expected Behavior
The buildscript classpath should win over any default dependencies.

### Current Behavior
Default dependencies win over buildscript classpath dependencies.

### Context
It makes maintaining plugins difficult and makes adoption of later Kotlin features difficult, causing us to resort to shading to provide classpath isolation, which comes with its own problems.

### Steps to Reproduce 
Take the following build:
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-stdlib:1.4.10"
    }
}

// Kotlin 1.x class
println Class.forName("kotlin.SynchronizedLazyImpl").package.implementationVersion
// Kotlin 1.4-only class
println Class.forName("kotlin.properties.PropertyDelegateProvider").package.implementationVersion
```

Run `./gradlew help` and note the output:
```
1.3.72-release-468 (1.3.72)
1.4.10-release-411 (1.4.10)
```

### Your Environment
Gradle 6.7

**Comment by DanielThomas** [comment]
I'll add this also happens at development time, because the bundled classpath leaks in `gradleApi()`:

```> Task :nebula:compileKotlin
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /Users/dannyt/.gradle/wrapper/dists/gradle-6.7.1-all/2moa8rlfac5eqlcfgk98k0deb/gradle-6.7.1/lib/kotlin-stdlib-1.3.72.jar (version 1.3)
    /Users/dannyt/.gradle/wrapper/dists/gradle-6.7.1-all/2moa8rlfac5eqlcfgk98k0deb/gradle-6.7.1/lib/kotlin-stdlib-common-1.3.72.jar (version 1.3)
    /Users/dannyt/.gradle/wrapper/dists/gradle-6.7.1-all/2moa8rlfac5eqlcfgk98k0deb/gradle-6.7.1/lib/kotlin-stdlib-jdk7-1.3.72.jar (version 1.3)
    /Users/dannyt/.gradle/wrapper/dists/gradle-6.7.1-all/2moa8rlfac5eqlcfgk98k0deb/gradle-6.7.1/lib/kotlin-stdlib-jdk8-1.3.72.jar (version 1.3)
    /Users/dannyt/.gradle/wrapper/dists/gradle-6.7.1-all/2moa8rlfac5eqlcfgk98k0deb/gradle-6.7.1/lib/kotlin-reflect-1.3.72.jar (version 1.3)
    /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.4.10/e2b3c6695eee6085e606d96d685396dce23a3a06/kotlin-reflect-1.4.10.jar (version 1.4)
    /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.4.10/998caa30623f73223194a8b657abd2baec4880ea/kotlin-stdlib-jdk8-1.4.10.jar (version 1.4)
    /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.4.10/30e46450b0bb3dbf43898d2f461be4a942784780/kotlin-stdlib-jdk7-1.4.10.jar (version 1.4)
    /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.10/ea29e063d2bbe695be13e9d044dcfb0c7add398e/kotlin-stdlib-1.4.10.jar (version 1.4)
    /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.4.10/6229be3465805c99db1142ad75e6c6ddeac0b04c/kotlin-stdlib-common-1.4.10.jar (version 1.4)
w: Consider providing an explicit dependency on kotlin-reflect 1.4 to prevent strange errors
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
w: Some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath
w: /Users/dannyt/.gradle/caches/modules-2/files-2.1/com.netflix.nebula/nebula-alerts-plugin/1.1.7/49f4882c4669cb3fa7775d6119d05439072fd06a/nebula-alerts-plugin-1.1.7.jar: Library has Kotlin runtime bundled into it
w: /Users/dannyt/Projects/bb/nebula/nebula/subprojects/core/src/main/kotlin/netflix/nebula/nebulaTasks.kt: (55, 54): Unnecessary safe call on a non-null receiver of type String!
```

**Comment by martinbonnin** [comment]
Related issue: https://github.com/gradle/gradle/issues/16345
