### ISSUE TITLE
Dependency verification cause failure for build dependencies from initscript block

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#15114]
When dependency verification is enabled, any dependency added via an initscript block (inside an init script) causes the build to fail.

### Expected Behavior

No crash should happen because of a build dependency inside an init script.

### Current Behavior

Failing with: `GradleProperties has not been loaded yet.`

The top of the stacktrace shows:

```
java.lang.IllegalStateException: GradleProperties has not been loaded yet.
	at org.gradle.initialization.DefaultGradlePropertiesController$NotLoaded.gradleProperties(DefaultGradlePropertiesController.java:80)
	at org.gradle.initialization.DefaultGradlePropertiesController$SharedGradleProperties.gradleProperties(DefaultGradlePropertiesController.java:63)
	at org.gradle.initialization.DefaultGradlePropertiesController$SharedGradleProperties.find(DefaultGradlePropertiesController.java:54)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.verification.report.DependencyVerificationReportWriter.isVerboseConsoleReport(DependencyVerificationReportWriter.java:62)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.verification.report.DependencyVerificationReportWriter.createConsoleRenderer(DependencyVerificationReportWriter.java:67)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.verification.report.DependencyVerificationReportWriter.lambda$new$5(DependencyVerificationReportWriter.java:56)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.verification.report.DependencyVerificationReportWriter.assertInitialized(DependencyVerificationReportWriter.java:87)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.verification.report.DependencyVerificationReportWriter.generateReport(DependencyVerificationReportWriter.java:76)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.verification.ChecksumAndSignatureVerificationOverride.artifactsAccessed(ChecksumAndSignatureVerificationOverride.java:174)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.StartParameterResolutionOverride$DisablingVerificationOverride.artifactsAccessed(StartParameterResolutionOverride.java:274)
```

### Context

Init scripts are useful to create tight integration with other projects, such as [Nokee](https://nokee.dev).

### Steps to Reproduce 

Using the following initscript in the Gradle user home:
```
initscript {
    repositories {
        maven { url = 'https://dl.bintray.com/nokeedev/distributions-initialization' }
    }
    dependencies {
        classpath 'dev.nokee.init:init.nokee.dev:latest.integration'
    }
}
println 'in init'
```
And executing `./gradlew :help` in the Gradle build (https://github.com/gradle/gradle).

If you execute `./gradlew :help --dependency-verification=off` then everything works as expected.

### Your Environment

Build scan URL: too early

**Comment by lacasseio** [comment]
I can somewhat work around it by using an initscript block like this, but it isn't a good workaround:

```
initscript {
    if (gradle.startParameter.dependencyVerificationMode == org.gradle.api.artifacts.verification.DependencyVerificationMode.OFF) {
        repositories {
            maven { url = 'https://dl.bintray.com/nokeedev/distributions-initialization' }
        }
        dependencies {
            classpath 'dev.nokee.init:init.nokee.dev:latest.release'
        }
    } else {
        println "Dependency verification cannot be on... sorry"
    }
}
```

**Comment by lacasseio** [comment]
It is also possible to disable the dependency verification on `classpath`. A better way would be to allow a configuration that classpath extends to disable dependency verification but that is not possible as it seems it's the resolving configuration that needs to be disabled.

**Comment by Vampire** [comment]
@ov7a I'm seeing a very similar problem.
I have an init script that works around https://youtrack.jetbrains.com/issue/IJPL-156792 for IJ 2026.1+ and Gradle projects by applying the `idea-ext` plugin and causing the integration to persist the project settings at least on Gradle sync.

I just tried to open the Gradle project in IJ and got a dependency verification error during sync as `idea-ext` is not part of the dependency verification metadata.

Checking `gradle.startParameter.dependencyVerificationMode` alone as work-around also was not enough, as even without metadata file this returned `STRICT`.

So what I use as work-around right now is
```groovy
initscript {
    def rootGradle = gradle
    while (rootGradle.parent != null) {
        rootGradle = rootGradle.parent
    }
    if (new File(rootGradle.startParameter.currentDir, 'gradle/verification-metadata.xml').file &&
            (rootGradle.startParameter.dependencyVerificationMode == STRICT)) {
        return
    }

    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath('org.jetbrains.gradle.plugin.idea-ext:org.jetbrains.gradle.plugin.idea-ext.gradle.plugin:1.4.1')
    }
}

def rootGradle = gradle
while (rootGradle.parent != null) {
    rootGradle = rootGradle.parent
}
if (new File(rootGradle.startParameter.currentDir, 'gradle/verification-metadata.xml').file &&
        (rootGradle.startParameter.dependencyVerificationMode == STRICT)) {
    return
}

// remaining init script logic
```

**Comment by ov7a** [comment]
@Vampire I interpreted your comment as:
1. There's no way to exempt init-script classpath deps from verification. 
2. dependencyVerificationMode returns STRICT even with no metadata file → there's no solid way to detect if verification is active.

If that's correct, can you open a new bug report for №2, please?
As for 1 - I'm not sure if this is something we would want to do. I'll discuss it during the next triage session.

**Comment by Vampire** [comment]
Correct.
At least I did not see a way for 1.
#38514 for 2.

**Comment by Vampire** [comment]
Ah, forget what I said, I can just do `configurations.classpath.resolutionStrategy.disableDependencyVerification()`, sorry.
