### ISSUE TITLE
Kotlin build fails when run with Gradle daemon

### ISSUE THREAD

**Issue by GuidoDechamps** [gradle/gradle#15196]
###Description

When I build my multimodule kotlin project.

```
./gradlew build  --stacktrace
```
The build fails. 

When I run the build with the flag -no--daemon everything works fine.
When I set the kotlin version to 1.3.72 then the build succeeds with the daemon.

### Expected Behavior

The build should succeed.

### Current Behavior

The build fails with an error

```
Caused by: java.util.ServiceConfigurationError: Error loading service [io.micronaut.validation.validator.DefaultAnnotatedElementValidator]: null
        at io.micronaut.core.io.service.DefaultServiceDefinition.lambda$load$0(DefaultServiceDefinition.java:71)
        at io.micronaut.core.io.service.DefaultServiceDefinition.load(DefaultServiceDefinition.java:67)
        at io.micronaut.annotation.processing.AnnotationUtils.<init>(AnnotationUtils.java:102)
        at io.micronaut.annotation.processing.AbstractInjectAnnotationProcessor.init(AbstractInjectAnnotationProcessor.java:145)
        at io.micronaut.annotation.processing.TypeElementVisitorProcessor.init(TypeElementVisitorProcessor.java:73)
        at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.init(incrementalProcessors.kt:38)
        at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.init(annotationProcessing.kt:170)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:686)
        ... 43 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at io.micronaut.core.io.service.DefaultServiceDefinition.lambda$load$0(DefaultServiceDefinition.java:69)
        ... 50 more
Caused by: java.io.UncheckedIOException: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
        at io.micronaut.core.io.service.SoftServiceLoader$ServiceLoaderIterator.hasNext(SoftServiceLoader.java:212)
        at io.micronaut.core.io.service.SoftServiceLoader$1.hasNext(SoftServiceLoader.java:144)
        at io.micronaut.core.beans.DefaultBeanIntrospector.getIntrospections(DefaultBeanIntrospector.java:93)
        at io.micronaut.core.beans.DefaultBeanIntrospector.findIntrospection(DefaultBeanIntrospector.java:64)
        at io.micronaut.core.beans.BeanWrapper.findWrapper(BeanWrapper.java:240)
        at io.micronaut.validation.validator.constraints.DefaultConstraintValidators.<init>(DefaultConstraintValidators.java:335)
        at io.micronaut.validation.validator.constraints.DefaultConstraintValidators.<init>(DefaultConstraintValidators.java:324)
        at io.micronaut.validation.validator.DefaultAnnotatedElementValidator$LocalConstraintValidators.<init>(DefaultAnnotatedElementValidator.java:56)
        at io.micronaut.validation.validator.DefaultAnnotatedElementValidator$LocalConstraintValidators.<init>(DefaultAnnotatedElementValidato
```

### Your Environment

I have a Multimodule kotlin project.

kotlinVersion 4.1.10
micronautVersion=2.1.3
gradle 6.7
jvm 11

Build scan URL: https://gradle.com/s/3tjsov3kaxib2

**Comment by mlopatkin** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.
