### ISSUE TITLE
Gradle build in Azure Devops Failure

### ISSUE THREAD

**Issue by aafnan10** [gradle/gradle#15234]
I'm using Gradle task in Azure Devops build pipeline. Since today I'm facing failures in Gradle build. Please assess the build log mentioned below:

```
Starting: Run Build PROJ
==============================================================================
Task         : Gradle
Description  : Build using a Gradle wrapper script
Version      : 2.178.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/gradle
==============================================================================
##[warning]Resource file has already set to: /home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json
##[warning]Resource file has already set to: /home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json
##[warning]Resource file has already set to: /home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json
##[warning]Resource file has already set to: /home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json
##[warning]Resource file has already set to: /home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json
SYSTEMVSSCONNECTION exists true
/home/vsts/work/1/s/proj/gradlew -PbuildEnv=alpha -PsetUp=cloud build
Downloading https://services.gradle.org/distributions/gradle-5.4.1-bin.zip
...................................................................................

Welcome to Gradle 5.4.1!

Here are the highlights of this release:
 - Run builds with JDK12
 - New API for Incremental Tasks
 - Updates to native projects, including Swift 5 support

For more details see https://docs.gradle.org/5.4.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':proj'.
> Could not resolve all dependencies for configuration ':proj:classpath'.
   > Could not determine artifacts for org.springframework.boot:spring-boot-gradle-plugin:2.2.0.RELEASE: Skipped due to earlier error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 4s
Error: The process '/home/vsts/work/1/s/proj/gradlew' failed with exit code 1
    at ExecState._setResult (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-task-lib/toolrunner.js:816:25)
    at ExecState.CheckComplete (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-task-lib/toolrunner.js:799:18)
    at ChildProcess.<anonymous> (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-task-lib/toolrunner.js:721:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
No test result files matching /home/vsts/work/1/s/**/TEST-*.xml were found, so publishing JUnit test results is being skipped.
##[error]Error: The process '/home/vsts/work/1/s/proj/gradlew' failed with exit code 1
Finishing: Run Build PROJ
```

### Expected Behavior

This build task usually takes almost 5 mins. And it was working fine till yesterday.

### Current Behavior

Currently, build task is taking more than 20 minutes to complete and still fails.

### Your Environment

Azure Devops

**Comment by bmuskalla** [comment]
Thank you for your interest in Gradle!

This issue lacks information and/or a reproducer to track down the problem. Also please consider upgrading to a more recent version of Gradle and see if you can reproduce the problem.
