### ISSUE TITLE
ParseException processing Java 15 records with PMD plugin

### ISSUE THREAD

**Issue by dragonjuggler** [gradle/gradle#15280]
### Expected Behavior
These exceptions should not be occurring.

### Current Behavior
The following types of exceptions are seen when processing Java 15 records.
Caused by: net.sourceforge.pmd.lang.java.ast.ParseException: Line 3, Column 8: Records are only supported with Java 14 Preview and Java 15 Preview
	at net.sourceforge.pmd.lang.java.ast.JavaParser.throwParseException(JavaParser.java:30)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.checkForRecordType(JavaParser.java:247)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.RecordDeclaration(JavaParser.java:1323)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.TypeDeclaration(JavaParser.java:796)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.CompilationUnit(JavaParser.java:502)
	at net.sourceforge.pmd.lang.java.AbstractJavaParser.parse(AbstractJavaParser.java:62)
	at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:121)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:185)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:107)
	... 247 more

The high level of the exception starts like this:
net.sourceforge.pmd.PMDException: Error while parsing <path to my file here>
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:110)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:89)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
	at net.sourceforge.pmd.processor.MonoThreadProcessor.runAnalysis(MonoThreadProcessor.java:29)
	at net.sourceforge.pmd.processor.AbstractPMDProcessor.processFiles(AbstractPMDProcessor.java:122)
	at net.sourceforge.pmd.PMD.processFiles(PMD.java:309)
	at net.sourceforge.pmd.ant.internal.PMDTaskImpl.doTask(PMDTaskImpl.java:196)
	at net.sourceforge.pmd.ant.internal.PMDTaskImpl.execute(PMDTaskImpl.java:281)
	at net.sourceforge.pmd.ant.PMDTask.execute(PMDTask.java:50)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)

It seems that somehow the "--enable-preview" and "-version" switches need to get passed through PMD to the JVM(?), specifically specifying a specific level of language support (13-preview, 14-preview, 15-preview).  I have tried setting PMD_JAVA_OPTS environment variable but this does not seem to help.

There seem to be instructions on how to do this for PMD from the command line, but instructions cannot be found for doing this from the PMD Gradle plugin.

Excluding the "record" types from the scan might be a workaround, but I have not found a way to exclude files either.  Since the exceptions are reported during parse, excluding them from the report would not appear to work - I think they would need to be excluded from the scan entirely.

### Context
This problem results in very large blocks of exceptions in the PMD HTML report, which makes it very unreadable.

### Steps to Reproduce 
This exception can be encountered running the PMD Gradle plugin on the simplest Java 15 record.

### Your Environment
Using Gradle 6.6.1 with PMD 6.29.0

**Comment by Mark-Palmer-Imprivata** [comment]
Is there any guidance on getting around this issue, or is a bugfix needed?

**Comment by McPringle** [comment]
I think this issue is very closely related to #11107
