### ISSUE TITLE
application plugin hard to use, especially with a cli app

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#15358]
given the [documentation for the application plugin](https://docs.gradle.org/current/userguide/application_plugin.html), it's really hard to use. Here's my default results.

my configuration, as described

```kts
import com.github.spotbugs.snom.Confidence
import com.github.spotbugs.snom.Effort
import com.github.spotbugs.snom.SpotBugsTask
import net.ltgt.gradle.errorprone.CheckSeverity
import net.ltgt.gradle.errorprone.errorprone
import net.ltgt.gradle.nullaway.nullaway

plugins {
  application
  checkstyle
  // NOTE: external plugin version is specified in implementation dependency artifact of the project's build file
  id("com.github.spotbugs").version("4.6.0")
  id("com.diffplug.spotless").version("5.8.2")
  id("net.ltgt.errorprone").version("1.3.0")
  id("net.ltgt.nullaway").version("1.0.2")
}

group = "com.xenoterracide.scaf"
version = "0.1.0-SNAPSHOT"

repositories {
  mavenCentral()
}

dependencyLocking {
  lockAllConfigurations()
}

dependencies {
  errorprone("com.google.errorprone:error_prone_core:2.4.+")
  errorprone("com.uber.nullaway:nullaway:0.8.+")
  implementation("org.tomlj:tomlj:1.+")
  implementation("org.thymeleaf:thymeleaf:3.+")
  implementation("info.picocli:picocli:4.+")
  testImplementation(platform("org.junit:junit-bom:5.+"))
  testImplementation("org.junit.jupiter:junit-jupiter-params")
  testImplementation("org.assertj:assertj-core:3.+")
  testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
}

application {
  mainClass.set("com.xenoterracide.scaf.Application")
}
```

the main class

```java
/* Copyright © 2020 Caleb Cushing. All rights reserved */
package com.xenoterracide.scaf;

import picocli.CommandLine;

import java.util.List;

@CommandLine.Command(name = "skaf")
public final class Application implements Runnable {

  @CommandLine.Parameters(description = "template directories")
  private List<String> args = List.of();

  @Override
  public void run(
  ) {
    System.out.println(args);
  }

  public static void main(String... args) {
    var cli = new CommandLine(new Application());
    System.exit(cli.execute(args));
  }
}
```

this is what the output should look like

```
> ./scaf-0.1.0-SNAPSHOT/bin/scaf --help                                                  # ppm/scaf -> 75-migrations — » ! +
Unknown option: '--help'
Usage: skaf [<args>...]
      [<args>...]   template directories
```

but here's the output I get if I use run, not really unsurprisingly, but it makes it harder to test the app

```
> ../gradlew run --help                                                                  # ppm/scaf -> 75-migrations — » ! +

USAGE: gradlew [option...] [task...]
....
```

I tried running it as a fatjar

```
> java -jar build/libs/scaf-0.1.0-SNAPSHOT.jar                                           # ppm/scaf -> 75-migrations — » ! +
Exception in thread "main" java.lang.NoClassDefFoundError: picocli/CommandLine
        at com.xenoterracide.scaf.Application.main(Application.java:21)
Caused by: java.lang.ClassNotFoundException: picocli.CommandLine
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 1 more
```

tried running the script output into the `build` directory

```
> ./build/scripts/scaf --help                                                       # ppm/scaf -> 75-migrations — » ! + RC=1
Error: Could not find or load main class com.xenoterracide.scaf.Application
Caused by: java.lang.ClassNotFoundException: com.xenoterracide.scaf.Application
```

honestly I'd change 3 things.

1.  I think it'd be better to rename `application` to `java-application` the naming seems very generic, even though it's java specific.
1. I'd improve the documentation to say how to run/install the app
1. I'd provide some way of using `:run` to take options and arguments, in fact I'd go as far as having it terminate cli processing in for gradle.

**Comment by swpalmer** [comment]
The current application plugin is a disaster and there doesn’t appear to be any will to make it do what most developers expect it to do given the closure of issue #13125 (that was number 4 on the above list). We need a new “java-application” plugin that builds applications the way they are expected to be done with modern Java.  That means use of jpackage and jimage to produce applications that “just work”, with support for embedded JREs, native launchers (possibly more than one), and installers or .deb/.rpm packages as appropriate for the platform.

**Comment by BjoernPetersen** [comment]
Not stale

**Comment by pantherdd** [comment]
@swpalmer, do you mean something like the _Application plugin for Gradle_ we've open-sourced? Take a look, I'd actually like to contribute it to Gradle if there is interest 🙂
* https://github.com/morganstanley/gradle-plugin-application
* https://plugins.gradle.org/plugin/com.ms.gradle.application

_(I also added this to https://github.com/gradle/gradle/issues/13125)_

**Comment by swpalmer** [comment]
@pantherdd Yes! That is what the application plugin should have been all along!

**Comment by ljacomet** [comment]
Sorry for the late reply!

This feature request is in the backlog of the relevant team and is prioritized by them.

***

As indicated by @pantherdd, there is a plugin out there doing some of what is requested here. Keeping this open if at some point Gradle would consider merging those features to the core application plugin.

Another point that would be for Gradle to fix is the ability to separate `gradle` flags from other flags, like those passed to `run`.

**Comment by ov7a** [comment]
> Another point that would be for Gradle to fix is the ability to separate gradle flags from other flags, like those passed to run.

There is `--` for that already, see [this documentation entry](https://docs.gradle.org/current/userguide/command_line_interface.html#disambiguate_task_options_from_built_in_options).

**Comment by octylFractal** [comment]
FWIW, you can run `gradle installDist` and then use `./build/install/scaf/bin/scaf` and it will work as you expect. It's even possible to use `gradle installDist -t` to continuously rebuild it, so you only need to run the start script after you make changes.

**Comment by Flowdalic** [comment]
> > Another point that would be for Gradle to fix is the ability to separate gradle flags from other flags, like those passed to run.
> 
> There is `--` for that already, see [this documentation entry](https://docs.gradle.org/current/userguide/command_line_interface.html#disambiguate_task_options_from_built_in_options).

Unfortunately, that does not have the desired affect. As the linked documentation entry states, Gradle uses `--` to distinguish between task options and built-in options. Not to pass arguments down to the `main` method of the application started by run.

Consider
```java
public static void main(String[] args) {
	for (int i = 0; i < args.length; i++)
		System.out.println(i + ": " + args[i]);
}
```

then 

```bash
$ ./gradlew run --args="foo bar"
0: foo
1: bar
```

but

```bash
$ ./gradlew run -- foo bar
FAILURE: Build failed with an exception.
Task 'foo' not found in root project 'Example' and its subprojects.
```

As I wrote in [my original issue](https://github.com/gradle/gradle/issues/35275#issuecomment-3403187313), application argument passing via `gradle run` is a major pain point I have with gradle. Passing multi component arguments in a quoted argument like `--args` is a design flaw that should have you end up in quoting hell.

Assume I want to pass `foo 'bar baz'` as first argument and `qox` as second. This is not possible with the the current `run --args=` design. But it would be possible if `gradle run` would follow the convention to separate arguments for the invoking application and the invoked application via `--`:

```bash
$ ./gradlew run -- "foo 'bar baz'" baz
0: foo 'bar baz'
1: qox
```
