### ISSUE TITLE
Gradle build failed with : Could not create an instance of type org.gradle.invocation.DefaultGradle

### ISSUE THREAD

**Issue by gupta-lakshay** [gradle/gradle#15419]
Gradle Build fails with following exception (adding --stacktrace)
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not create an instance of type org.gradle.invocation.DefaultGradle.
Could not configure services using GradleScopeCompileServices.configure().

 Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Exception is:
org.gradle.api.reflect.ObjectInstantiationException: Could not create an instance of type org.gradle.invocation.DefaultGradle.
        at org.gradle.internal.instantiation.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:54)
        at org.gradle.initialization.DefaultGradleLauncherFactory.doNewInstance(DefaultGradleLauncherFactory.java:133)
        at org.gradle.initialization.DefaultGradleLauncherFactory.newInstance(DefaultGradleLauncherFactory.java:79)
        at org.gradle.composite.internal.DefaultRootBuildState.<init>(DefaultRootBuildState.java:45)
        at org.gradle.composite.internal.DefaultIncludedBuildRegistry.createRootBuild(DefaultIncludedBuildRegistry.java:85)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:46)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:31)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:42)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:28)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:52)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:68)
        at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:38)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:37)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:60)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:32)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:41)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:48)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:32)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:68)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:27)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.internal.service.ServiceLookupException: Could not configure services using GradleScopeCompileServices.configure().
        at org.gradle.internal.service.DefaultServiceRegistry.applyConfigureMethod(DefaultServiceRegistry.java:195)
        at org.gradle.internal.service.DefaultServiceRegistry.findProviderMethods(DefaultServiceRegistry.java:171)
        at org.gradle.internal.service.DefaultServiceRegistry.addProvider(DefaultServiceRegistry.java:248)
        at org.gradle.internal.service.DefaultServiceRegistry$1.addProvider(DefaultServiceRegistry.java:229)
        at org.gradle.api.internal.tasks.CompileServices.registerGradleServices(CompileServices.java:41)
        at org.gradle.internal.service.scopes.GradleScopeServices$1.execute(GradleScopeServices.java:125)
        at org.gradle.internal.service.scopes.GradleScopeServices$1.execute(GradleScopeServices.java:121)
        at org.gradle.internal.service.DefaultServiceRegistry.register(DefaultServiceRegistry.java:206)
        at org.gradle.internal.service.scopes.GradleScopeServices.<init>(GradleScopeServices.java:121)
        at org.gradle.internal.service.scopes.BuildScopeServiceRegistryFactory.createFor(BuildScopeServiceRegistryFactory.java:38)
        at org.gradle.invocation.DefaultGradle.<init>(DefaultGradle.java:88)
        at org.gradle.invocation.DefaultGradle_Decorated.<init>(Unknown Source)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at org.gradle.internal.instantiation.AsmBackedClassGenerator.newInstance(AsmBackedClassGenerator.java:179)
        at org.gradle.internal.instantiation.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:395)
        at org.gradle.internal.instantiation.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:49)
        ... 51 more
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$PlatformClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$PlatformClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at org.gradle.initialization.DefaultJdkToolsInitializer.initializeJdkTools(DefaultJdkToolsInitializer.java:41)
        at org.gradle.api.internal.tasks.CompileServices$GradleScopeCompileServices.configure(CompileServices.java:52)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
        at org.gradle.internal.service.ReflectionBasedServiceMethod.invoke(ReflectionBasedServiceMethod.java:34)
        at org.gradle.internal.service.DefaultServiceRegistry.applyConfigureMethod(DefaultServiceRegistry.java:193)
        ... 68 more
* Get more help at https://help.gradle.org
```

**Gradle Version**
------------------------------------------------------------
Gradle 5.6.3
------------------------------------------------------------
```
Build time:   2019-10-18 00:28:36 UTC
Revision:     bd168bbf5d152c479186a897f2cea494b7875d13
Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          11.0.9 (Oracle Corporation 11.0.9+7-LTS)
OS:           Linux 5.4.0-42-generic amd64
```

**Java Version**
```
java -version
java version "11.0.9" 2020-10-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)
```

Build was executing perfectly fine, but after deleting generated build folder, when I try to rebuild it fails with above exception. I have upgraded **gradle version from v3.4 to v5.6.3 and Java version from JDK8 to JDK11**. I have already tried deleting .gradle folder but no results.

Build passed if I run gradle build with JDK 8 and gradle v5.6.3
I have added gradle-5.6.3-all.zip under gradle/wrapper/ folder and in gradle-wrapper-properties file specified distributionUrl=gradle-5.6.3-all.zip. Also, I downloaded gradle and placed the unzip folder under /public/gradle and have set environment variable. **I am working on Virtual Box not having access to internet.**

**Comment by BlackHarold** [comment]
------------------------------------------------------------
Same problem:
------------------------------------------------------------

> [+1538 ms] FAILURE: Build failed with an exception.
> [   +2 ms] * What went wrong:
> [        ] Could not create an instance of type org.gradle.invocation.DefaultGradle.
> [        ] > Could not configure services using GradleScopeCompileServices.configure().
> [        ] * Try:
> [        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> [        ] * Get more help at https://help.gradle.org
> [        ] BUILD FAILED in 1s
> [{"event":"app.progress","params":{"appId":"28abc714-e4ac-482b-b080-172ffab5d21b","id":"0","progressId":null,"finished":true}}]
> [+4918 ms] Exception: Gradle task assembleDebug failed with exit code 1
> [   +2 ms] 
>            0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
>            1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:492:9)
>            <asynchronous suspension>
>            2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:12)
>            <asynchronous suspension>
>            3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)
>            <asynchronous suspension>
>            4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
>            <asynchronous suspension>
>            6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
>            <asynchronous suspension>
>            7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)
>            <asynchronous suspension>
>            8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
>            <asynchronous suspension>
>            10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
>            <asynchronous suspension>
>            11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
>            <asynchronous suspension>
>            12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
>            <asynchronous suspension>
>            13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
>            <asynchronous suspension>
>            15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
>            <asynchronous suspension>
>            16     main (package:flutter_tools/executable.dart:88:3)
>            <asynchronous suspension>

------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

> Build time:   2020-11-16 17:09:24 UTC
> Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0
> 
> Kotlin:       1.3.72
> Groovy:       2.5.12
> Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
> JVM:          15.0.1 (Oracle Corporation 15.0.1+9-18)
> OS:           Windows 10 10.0 amd64

**Comment by ionansantos** [comment]
conseguiu resolver ? to com  o mesmo problema , so que no caso nao consigo iniciar o projeto com o android studio

**Comment by celciusjj** [comment]
I have the same issue.
