### ISSUE TITLE
gradle init to kotlin, NPE in DefaultMetadataResolver

### ISSUE THREAD

**Issue by soloturn** [gradle/gradle#15431]
gradle-6.7, gradle init on this small springboot application gives a nullpointer exception:
https://github.com/awconstable/deployservice

```
Caused by: java.lang.NullPointerException
        at org.sonatype.aether.impl.internal.DefaultMetadataResolver.resolve(DefaultMetadataResolver.java:279)
        at org.sonatype.aether.impl.internal.DefaultMetadataResolver.resolveMetadata(DefaultMetadataResolver.java:173)
        at org.apache.maven.repository.internal.DefaultVersionResolver.resolveVersion(DefaultVersionResolver.java:225)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:272)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:193)
        at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:286)
        at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:155)
        at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement(DefaultModelBuilder.java:953)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:400)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:371)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:362)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:232)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:142)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:102)
        at org.gradle.buildinit.plugins.internal.maven.MavenProjectsCreator.createNow(MavenProjectsCreator.java:90)
        at org.gradle.buildinit.plugins.internal.maven.MavenProjectsCreator.create(MavenProjectsCreator.java:59)

```

**Comment by soloturn** [comment]
works with gradle-7.0.2.
