### ISSUE TITLE
Gradle crashes when running on Java 9

### ISSUE THREAD

**Issue by jonatan-kazmierczak** [gradle/gradle#1549]
I execute `gradle` v3.4.1 on Java 9-ea+158 on Ubuntu 14.04.
The result - command `gradle` crashes as follows:
```
FAILURE: Build failed with an exception.

* What went wrong:
java.lang.ExceptionInInitializerError (no error message)

...
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.Package[] java.lang.ClassLoader.getPackages() accessible: module java.base does not "opens java.lang" to unnamed module @3e62d773
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:335)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:278)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:196)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:190)
        at org.gradle.internal.reflect.JavaMethod.<init>(JavaMethod.java:42)
        at org.gradle.internal.reflect.JavaMethod.<init>(JavaMethod.java:32)
        at org.gradle.internal.reflect.JavaMethod.<init>(JavaMethod.java:36)
        at org.gradle.internal.reflect.JavaReflectionUtil.method(JavaReflectionUtil.java:223)
        at org.gradle.internal.classloader.FilteringClassLoader.<clinit>(FilteringClassLoader.java:49)
        ... 40 more
```

### Expected Behavior
`gradle` prints a standard info.

### Current Behavior
Crash as shown above.

### Context
I'd like to build Java 9 project.

### Steps to Reproduce
1. set `JAVA_HOME` pointing to Java 9-ea+158
2. run `gradle --stacktrace`

### Your Environment
Ubuntu 14.04, Java 9-ea+158, Gradle 3.4.1

**Comment by Mistic92** [comment]
Similar problem on 9-ea+162 windows10
`H:\ProgramowanieProjekty\Java9Fun\test>gradle init --stacktrace --debug
23:25:06.390 [INFO] [org.gradle.internal.nativeintegration.services.NativeServices] Initialized native services in: C:\Users\Lukasz\.gradle\native
23:25:06.636 [DEBUG] [org.gradle.internal.nativeintegration.services.NativeServices] Native-platform posix files is not available.  Continuing with fallback.
23:25:06.643 [DEBUG] [org.gradle.internal.nativeintegration.filesystem.services.FileSystemServices] Using JDK 7 file service org.gradle.internal.nativeintegration.filesystem.jdk7.WindowsJdk7Symlink
23:25:06.817 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
23:25:06.819 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
23:25:06.821 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
23:25:06.821 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
23:25:06.821 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] java.lang.ExceptionInInitializerError (no error message)
23:25:06.822 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
23:25:06.822 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
23:25:06.824 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] java.lang.ExceptionInInitializerError
23:25:06.824 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultClassLoaderRegistry.restrictToGradleApi(DefaultClassLoaderRegistry.java:48)`

**Comment by jonatan-kazmierczak** [comment]
The same problem with Gradle 3.5.

**Comment by miho** [comment]
Same problem here :(

**Comment by mlchung** [comment]
This looks like a duplicate of https://github.com/gradle/gradle/issues/1095

**Comment by eljobe** [comment]
Yup, closing as a duplicate of #1095
