### ISSUE TITLE
ConsumerProvidedVariantFinder can crash with an IllegalStateException: Recursive Update

### ISSUE THREAD

**Issue by LunNova** [gradle/gradle#15602]
Register transforms for an attr with these from/to values:

* a -> b
* b -> a
* b -> c
* c -> b

Try requesting an artifact which has attr value a but needs value c.

### Expected Behavior
Should select the chain through transformer a -> b then b -> c.

### Current Behavior
Results in an `IllegalStateException: Recursive Update` (which gets swallowed) and then the usual No matching variant message.

The exception is swallowed even at debug log level, you'll need to use a debugger / add a catch around `inputVariants = collectConsumerVariants(actual, requestedPrevious);`.

https://github.com/gradle/gradle/blob/18a8474756ffc5b05976cff756a9ef03f79978fd/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/ConsumerProvidedVariantFinder.java#L81

```
java.lang.IllegalStateException: Recursive update
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1763)
        at org.gradle.api.internal.artifacts.transform.ConsumerProvidedVariantFinder.collectConsumerVariants(ConsumerProvidedVariantFinder.java:55)
        at org.gradle.api.internal.artifacts.transform.ConsumerProvidedVariantFinder.findProducersFor(ConsumerProvidedVariantFinder.java:86)
        at org.gradle.api.internal.artifacts.transform.ConsumerProvidedVariantFinder.lambda$collectConsumerVariants$0(ConsumerProvidedVariantFinder.java:55)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at org.gradle.api.internal.artifacts.transform.ConsumerProvidedVariantFinder.collectConsumerVariants(ConsumerProvidedVariantFinder.java:55)
        at org.gradle.api.internal.artifacts.transform.ConsumerProvidedVariantFinder.findProducersFor(ConsumerProvidedVariantFinder.java:86)
        at org.gradle.api.internal.artifacts.transform.ConsumerProvidedVariantFinder.lambda$collectConsumerVariants$0(ConsumerProvidedVariantFinder.java:55)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at org.gradle.api.internal.artifacts.transform.ConsumerProvidedVariantFinder.collectConsumerVariants(ConsumerProvidedVariantFinder.java:55)
        at org.gradle.api.internal.artifacts.transform.ConsumerProvidedVariantFinder.findProducersFor(ConsumerProvidedVariantFinder.java:86)
        at org.gradle.api.internal.artifacts.transform.ConsumerProvidedVariantFinder.lambda$collectConsumerVariants$0(ConsumerProvidedVariantFinder.java:55)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at org.gradle.api.internal.artifacts.transform.ConsumerProvidedVariantFinder.collectConsumerVariants(ConsumerProvidedVariantFinder.java:55)
        at org.gradle.api.internal.artifacts.transform.AttributeMatchingVariantSelector.doSelect(AttributeMatchingVariantSelector.java:122)
        at org.gradle.api.internal.artifacts.transform.AttributeMatchingVariantSelector.select(AttributeMatchingVariantSelector.java:90)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.DefaultArtifactSet.select(DefaultArtifactSet.java:187)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.DefaultVisitedArtifactResults.select(DefaultVisitedArtifactResults.java:48)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.select(DefaultLenientConfiguration.java:117)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getSelectedArtifacts(DefaultConfiguration.java:1399)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.visitContents(DefaultConfiguration.java:1386)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.visitContents(DefaultConfiguration.java:498)
        at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:326)
        at org.gradle.api.internal.file.CompositeFileCollection.lambda$visitContents$0(CompositeFileCollection.java:119)
        at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:61)
        at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:86)
        at org.gradle.api.internal.file.DefaultFileCollectionFactory$ResolvingFileCollection.visitChildren(DefaultFileCollectionFactory.java:312)
        at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:119)
        at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:326)
        at org.gradle.api.internal.file.CompositeFileCollection.lambda$visitContents$0(CompositeFileCollection.java:119)
        at org.gradle.api.internal.tasks.PropertyFileCollection.visitChildren(PropertyFileCollection.java:48)
        at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:119)
        at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:326)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.lambda$detectMissingDependencies$3(LocalTaskNodeExecutor.java:81)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.detectMissingDependencies(LocalTaskNodeExecutor.java:81)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.lambda$execute$0(LocalTaskNodeExecutor.java:62)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.validate(ExecuteActionsTaskExecuter.java:434)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:62)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:42)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:86)
        at java.base/java.util.Optional.orElseGet(Optional.java:362)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:86)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:32)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:43)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:31)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:40)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution$2.withWorkspace(ExecuteActionsTaskExecuter.java:283)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:40)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:49)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:35)
        at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:73)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:65)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:408)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:395)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:388)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:374)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

### Context
I have registered transforms which can transform between many different variants of the same attribute, including back and forth.
Similar context as #13044.

### Steps to Reproduce 
Steps to Reproduce

Use the MappingTest subfolder at https://github.com/MinimallyCorrect/Mapping/tree/gradle-15602

### Your Environment
Build scan URL:
https://gradle.com/s/jntwy6x5unxcc

**Comment by TransLunarInjection** [comment]
The current API for transforms doesn't provide a way to register a transform which handles all transforms for a given attribute and is parameterised on the from/to value. Trying to approximate this by registering transforms back/forth from every variant seems suboptimal, but it should still be possible.

I feel like a better solution would allow registering a transform which can handle transformations between a larger selection of attribute values.

After this bug is fixed the current solution will still be somewhat inefficient as performing a single transform from a -> c would be faster than a -> b -> c (due to avoiding needing to create a jar with value b rather than performing both sets of changes in memory), but I can't register separate optimised transforms from every possible combination of start/end points as the total number of combinations becomes ridiculously large. (There are more attributes than just a/b/c in a real world usecase).

**Comment by TransLunarInjection** [comment]
Tried to add something to replicate it in ConsumerProvidedVariantFinderTest but it seems to work fine. 

```groovy

    def "selects transform that can produce variant that is compatible with requested when loops exist"() {
        def requested = attributes().attribute(a1, "requested")
        def intermediary = attributes().attribute(a1, "intermediary")
        def source = attributes().attribute(a1, "source")
        def reg1 = registration(source, intermediary, {})
        def reg2 = registration(intermediary, source, {})
        def reg3 = registration(intermediary, requested, {})
        def reg4 = registration(requested, intermediary, {})

        given:
        transformRegistrations.transforms >> [reg1, reg3, reg2, reg4]

        when:
        def result = matchingCache.collectConsumerVariants(source, requested)

        then:
        result.matches.size() == 1
        result.matches[0].attributes.asMap() == requested.asMap()

        and:
        _ * schema.matcher() >> matcher
        _ * matcher.ignoreAdditionalProducerAttributes() >> matcher
        _ * matcher.ignoreAdditionalConsumerAttributes() >> matcher
        _ * matcher.isMatching(_ as AttributeContainerInternal, _ as AttributeContainerInternal) >> {
            AttributeContainerInternal a, AttributeContainerInternal b ->
                a.asMap() == b.asMap()
        }

        0 * matcher._
    }
 ```

Tried to debug the more complete example which fails but my breakpoints aren't hit and not sure what I'm doing wrong there.

**Comment by TransLunarInjection** [comment]
The issue I had with transforms not running was actually unrelated to this error, and I have a new MVCE for that which doesn't involve it. Leaving this issue open as it is still broken in some way.

**Comment by jvandort** [comment]
Is this still a problem?

**Comment by jvandort** [comment]
Closing. I've added the linked is to our triage queue
