### ISSUE TITLE
IllegalArgumentException for jars having too short name

### ISSUE THREAD

**Issue by mvilliger** [gradle/gradle#15628]
Gradle 6.7.1 ClasspathBuilder fails for jars having a name shorter than 3 characters:

```
org.gradle.api.GradleException: Failed to create Jar file /home/user/.gradle/caches/jars-8/8535adf040d7c5fdb7fd6bc28bb0ef3f/ok.
	at org.gradle.internal.classpath.ClasspathBuilder.jar(ClasspathBuilder.java:47)
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.transform(InstrumentingClasspathFileTransformer.java:76)
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.transform(InstrumentingClasspathFileTransformer.java:70)
	at org.gradle.internal.classpath.DefaultCachedClasspathTransformer$TransformFile.lambda$schedule$0(DefaultCachedClasspathTransformer.java:261)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.IllegalArgumentException: Prefix string "ok" too short: length must be at least 3
	at org.gradle.internal.classpath.ClasspathBuilder.buildJar(ClasspathBuilder.java:53)
	at org.gradle.internal.classpath.ClasspathBuilder.jar(ClasspathBuilder.java:45)
	... 6 more
```

This is because File.createTempFile requires that the prefix is at least 3 characters long.
See https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/File.html#createTempFile(java.lang.String,java.lang.String,java.io.File)

This is probably still an issue on the master branch e.g. in org.gradle.internal.file.TempFiles (and maybe others).

**Comment by mvilliger** [comment]
Any news on this?

**Comment by bmuskalla** [comment]
@mvilliger This code has been revisited heavily in 7.0. Can you check if this is still an issue in 7.0 and/or provide a small reproducer? Thank you

**Comment by mvilliger** [comment]
@bmuskalla Of course, I will check again with Gradle 7 and come back to you.

**Comment by mvilliger** [comment]
@bmuskalla The issue described here still exists. I am getting the following Stacktrace now with Gradle 7:
```
org.gradle.api.GradleException: Failed to create Jar file /home/jenkins/.gradle/caches/jars-8/331b97956d956a7573658631f8941fea/ok.
	at org.gradle.internal.classpath.ClasspathBuilder.jar(ClasspathBuilder.java:55)
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.instrument(InstrumentingClasspathFileTransformer.java:137)
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.transform(InstrumentingClasspathFileTransformer.java:132)
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.transform(InstrumentingClasspathFileTransformer.java:96)
	at org.gradle.internal.classpath.DefaultCachedClasspathTransformer$TransformFile.lambda$schedule$0(DefaultCachedClasspathTransformer.java:274)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.IllegalArgumentException: Prefix string "ok" too short: length must be at least 3
	at org.gradle.api.internal.file.temp.TempFiles.createTempFile(TempFiles.java:42)
	at org.gradle.api.internal.file.temp.DefaultTemporaryFileProvider.createTemporaryFile(DefaultTemporaryFileProvider.java:47)
	at org.gradle.internal.classpath.ClasspathBuilder.buildJar(ClasspathBuilder.java:61)
	at org.gradle.internal.classpath.ClasspathBuilder.jar(ClasspathBuilder.java:53)
	... 7 more
```

**Comment by mvilliger** [comment]
I get the error above when building the project located here: https://git.eclipse.org/c/scout/org.eclipse.scout.sdk.git/tree/org.eclipse.scout.sdk.s2i?h=releases/12.0
using the following command: `clean buildPlugin -s -i -b build.gradle.kts`

**Comment by mvilliger** [comment]
Please note: I only get the error on Linux. The same project built on Windows seems to work. I assume the dependency in question ("ok") is not downloaded for Windows. But that's only a guess.

**Comment by mvilliger** [comment]
It seems the issue is related to the Artifactory Plugin: https://github.com/jfrog/jenkins-artifactory-plugin/issues/349
Which seems to be fixed in Version 3.9.0

See also: https://github.com/jfrog/jenkins-artifactory-plugin/pull/353
And: https://stackoverflow.com/questions/64431801/jenkins-gradle-build-with-wrapper-using-artifactory-plugin

Still I think the implementation of `org.gradle.api.internal.file.temp.TempFiles.createTempFile` should be more robust to handle such cases?

**Comment by bmuskalla** [comment]
@mvilliger thanks for checking and the additional context. This is also fixed on the gradle side so other builds and plugins don't run into this.

**Comment by mvilliger** [comment]
@bmuskalla Thank you very much for your effort and the fix!
