### ISSUE TITLE
Gradle should create "Unique" XML test result file even when testclass has no tests

### ISSUE THREAD

**Issue by jayanmn** [gradle/gradle#15644]
### Expected Behavior
We are migrating from Ant to gradle.  There are multiple test classes without tests in them (Junit3 tests). 

[ Junit4 test no tests does not run at all. That is different problem anyway ]

### Current Behavior
Gradle creates only one "build/test-results/test/TEST-junit.framework.TestSuite$1.xml".  This means only one case is detected by tools such as Jenkins. The classname inside the generated file is not correct either

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="junit.framework.TestSuite$1" tests="3" skipped="0" failures="3" errors="0" timestamp="2020-12-23T04:13:32" hostname="INH-JNAMBOOD-LT" time="0.047">
  <properties/>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0.041">
    <failure message="junit.framework.AssertionFailedError: No tests found in org.sample.numberutils.TestNumbers1AEmptyTest" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.sample.numberutils.TestNumbers1AEmptyTest
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.TestCase.fail(TestCase.java:227)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:97)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
```
### Context

We have a framework that splits tests across 1000+ machines.  We are moving  this from ant to Gradle.
This migration to gradle is taking too long(Actually blocked).  

Gradle should create  XML result file that follows ant convention (which I believe has become defacto standard).  Jenkins too (test result) cannot report as there is only one file.

 Having the testclassname in the filename will ensure unique result files when there are multiple bad tests. Having the content corrected will help tools to report the offending testname in HTML or other reports. (That includes Gradle.  I consider Gradle html report in correct in this case)

### Steps to Reproduce 
Please clone https://github.com/jayanmn/gradle-missing-test-does-not-create-uniq-files
Run ```gradle  test --tests "TestNumbers*" ```
Observe files in test result area

### Your Environment
WIndows, 64G ram. Java 11.0.4. 

Build scan URL:
not available.

**Comment by jayanmn** [comment]
==Workaround:
 The file has all the information in <testcase> section , as textdata.  We can improve the parser in our code to extract the classname.    See sample below.

$ grep junit.framework.AssertionFailedError:  'build/test-results/test/TEST-junit.framework.TestSuite$1.xml'

'''

    <failure message="junit.framework.AssertionFailedError: No tests found in org.sample.numberutils.TestNumbers1AEmptyTest" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.sample.numberutils.TestNumbers1AEmptyTest
    <failure message="junit.framework.AssertionFailedError: No tests found in org.sample.numberutils.TestNumbers3AEmptyTest" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.sample.numberutils.TestNumbers3AEmptyTest
    <failure message="junit.framework.AssertionFailedError: No tests found in org.sample.numberutils.TestNumbers3EmptyTest" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.sample.numberutils.TestNumbers3EmptyTest
'''
