### ISSUE TITLE
Jacoco Instrument Issue on Gradle 6.5

### ISSUE THREAD

**Issue by seasuresh** [gradle/gradle#15668]
I recently migrated our app from Spring boot 2.2.2 to Spring Boot 2.4.1, as part of the upgrade we had to migrate the Gradle version to 6.5. We noticed there are JUnit tests with powerbock that were not showing coverage on sonarQube.
The sonar coverage for powerMock was working fine with Gradle 6.0 and Springboot 2.2.2 but after this migration, it is not working, though the tests are successful it doesn't show the coverage on sonarqube.

By looking at Gradle doc, I used below to do offline instrumenting but I get the following error. Any help or suggestion pls?

```
Execution failed for task ':instrument'.
> Cannot convert the provided notation to a File or URI: main classesDirs.
  The following types/formats are supported:
    - A String or CharSequence path, for example 'src/main/java' or '/usr/include'.
    - A String or CharSequence URI, for example 'file:/usr/include'.
```

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':instrument'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:207)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
```

Here is the Gradle config

```

jacoco {
    toolVersion = "0.8.4"
    reportsDir = file("$buildDir/reports/jacoco")
}

jacocoTestReport {
    reports {
        xml.enabled = true
        html.enabled = true
        html.destination file("${buildDir}/reports/jacocoHtml")
    }
}

project.ext.jacocoOfflineSourceSets = ['main']

task instrument(dependsOn: [classes, project.configurations.jacocoAnt]) {
    inputs.files classes.outputs.files
    File outputDir = new File(project.buildDir, 'instrumentedClasses')
    outputs.dir outputDir
    doFirst {
        project.delete(outputDir)
        ant.taskdef(
                resource: 'org/jacoco/ant/antlib.xml',
                classpath: project.configurations.jacocoAnt.asPath,
                uri: 'jacoco'
        )
        def instrumented = false
        jacocoOfflineSourceSets.each { sourceSetName ->
            logger.info("jacoco: instrumenting source set " , sourceSetName)
            if (file(sourceSets[sourceSetName].output.classesDirs).exists()) {
                def instrumentedClassedDir = "${outputDir}/${sourceSetName}"
                ant.'jacoco:instrument'(destdir: instrumentedClassedDir) {
                    fileset(dir: sourceSets[sourceSetName].output.classesDirs, includes: '**/*.class')
                }
                //Replace the classes dir in the test classpath with the instrumented one
                sourceSets.test.runtimeClasspath -= files(sourceSets[sourceSetName].output.classesDirs)
                sourceSets.test.runtimeClasspath += files(instrumentedClassedDirs)
                instrumented = true
            }
        }
        if (instrumented) {
            //Disable class verification based on https://github.com/jayway/powermock/issues/375
            test.jvmArgs += '-noverify'
        }
    }
}
test.dependsOn instrument

// INSTRUMENTATION END....

sonarqube {
    properties {
        property 'sonar.exclusions',
                "**/com/gvpe/exception/test/**"
    
    }
}

test {
    useJUnitPlatform()
}
```

**Comment by bmuskalla** [comment]
Thank you for your interest in Gradle!

Please ask such a [usage question](https://github.com/gradle/gradle#need-help) on discuss.gradle.org or stackoverflow.com where to get answers by the community of Gradle users.

If, after investigation, it turns out to be a Gradle bug or missing feature, please file another issue describing the problem or use case and add a reproducer.
