### ISSUE TITLE
CreateOutputsStep attempts to call mkdirs on existing file when OutputFiles annotation on FileTree

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#15679]
### Expected Behavior

A task that extends `SourceTask` and that source is both an input and an output, when declaring that source set to be two files, the task should execute successfully.

### Current Behavior

```kotlin
val ktlintScriptSourceSets = files("build.gradle.kts", "settings.gradle.kts")

tasks.ktlintKotlinScriptFormat {
    setSource(ktlintScriptSourceSets)
}
```

https://github.com/JLLeitschuh/ktlint-gradle/blob/0c2b0353ecfe8c95f675646376bd417ef4c18bcc/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintFormatTask.kt#L26-L33

The above fails on the master branch of `gradle/graddle` with the following exception:

`Caused by: org.gradle.api.UncheckedIOException: Cannot create directory '/Users/jonathanleitschuh/code/work/gradle/build-logic/integration-testing/build.gradle.kts' as it already exists, but is not a directory`

<details>
  <summary>Full Stack Trace (clicky)</summary>
<pre>
10: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':build-logic:integration-testing:ktlintKotlinScriptFormat'.
> Cannot create directory '/Users/jonathanleitschuh/code/work/gradle/build-logic/integration-testing/build.gradle.kts' as it already exists, but is not a directory

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':build-logic:integration-testing:ktlintKotlinScriptFormat'.
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:60)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:408)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:395)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:388)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:374)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.gradle.api.UncheckedIOException: Cannot create directory '/Users/jonathanleitschuh/code/work/gradle/build-logic/integration-testing/build.gradle.kts' as it already exists, but is not a directory
        at org.gradle.util.GFileUtils.mkdirs(GFileUtils.java:291)
        at org.gradle.internal.execution.steps.CreateOutputsStep.ensureOutput(CreateOutputsStep.java:58)
        at org.gradle.internal.execution.steps.CreateOutputsStep.access$000(CreateOutputsStep.java:29)
        at org.gradle.internal.execution.steps.CreateOutputsStep$1.visitOutputProperty(CreateOutputsStep.java:43)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.visitOutputs(ExecuteActionsTaskExecuter.java:328)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:40)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:29)
        at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:54)
        at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:35)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:60)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:27)
        at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:174)
        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:74)
        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:45)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:29)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:22)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:99)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:92)
        at java.base/java.util.Optional.map(Optional.java:265)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:52)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:83)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:40)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:96)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:77)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:48)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:95)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:43)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:86)
        at java.base/java.util.Optional.orElseGet(Optional.java:369)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:86)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:32)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:42)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:30)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:39)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution$2.withWorkspace(ExecuteActionsTaskExecuter.java:281)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:39)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:29)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:48)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:34)
        at org.gradle.internal.execution.impl.DefaultExecutionEngine.execute(DefaultExecutionEngine.java:41)
        at org.gradle.internal.execution.impl.DefaultExecutionEngine.execute(DefaultExecutionEngine.java:32)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:182)
        at java.base/java.util.Optional.orElseGet(Optional.java:369)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:182)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:172)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:60)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:408)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:395)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:388)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:374)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:834)
</pre>
</details>

### Context

This issue currently blocks this PR:

https://github.com/gradle/gradle/pull/15669

### Steps to Reproduce 

Checkout #15669

Run `./gradlew sanityFix --dry-run --stacktrace`

### Your Environment

Build scan URL: https://ge.gradle.org/s/3zl6bpfybzbse

**Comment by lptr** [comment]
Tasks that have the same directory as input and output is not currently supported. This is a use case (e.g. code formatters) that we would like to address sometime in the near future, but it will require some dedicated changes in how we declare inputs and outputs.

**Comment by wolfs** [comment]
This seems to be an actual bug: 
We consider file trees always as type output directory. Though there is the rare case when a file tree is a single file, and in that case the root of the file tree is an actual file.

https://github.com/gradle/gradle/blob/2db7fc6b55044374a60b6c9c9cfbac49b3422153/subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/FileParameterUtils.java#L163-L172

So we need to decide whether or not the output is a directory or not. For inputs, we don't try to resolve the file collections, so that is not a problem.

**Comment by cortinico** [comment]
> We consider file trees always as type output directory. Though there is the rare case when a file tree is a single file, and in that case the root of the file tree is an actual file.

I stumbled upon this issue as well while working on: https://github.com/cortinico/ktfmt-gradle/issues/12

It seems there is no easy way to specify the `source` as a list of files rather than being a directory.

**Comment by wolfs** [comment]
I thought a little bit more about this. This is the current situation for outputs: Each output property has one [`TreeType`](https://github.com/gradle/gradle/blob/a80c0ec30b70ad55ed84d0f85fe17d98af3073b3/subprojects/files/src/main/java/org/gradle/internal/file/TreeType.java#L24-L28), `FILE` or `DIRECTORY`. We resolve things annotated with `@OutputFile` or `@OutputFiles` to output properties with tree type `FILE`, and things annotated with `@OutputDirectory` or `OutputDirectories` to output properties with tree type `DIRECTORY`. The only exception to this rule is directory trees in output file collections, which are resolved to `DirectoryTreeOutputFilePropertySpec` with tree type `DIRECTORY`.

Now the output location preparation and the validation is bound to the tree type:
- For `FILE`, we ensure that the parent directory of the output location is a directory (possibly creating it), and ensure that after task execution the location is a file if it exists.
- For `DIRECTORY`, we ensure that the output location is a directory (possibly creating it), and ensure that after task execution the location is a directory if it exists.

One option to support file trees as outputs which have a file as its roots is to introduce a new tree type, which then ensures that the parent directory of the output location is a directory (possibly creating it) and then doesn't do any validation on the actual created file type after task execution, because the output could be a directory or a file.

Doing so is also a slightly breaking change: Now, Gradle creates a directory for the root of the output file tree, so if your task relies on Gradle to create that directory, then it will break after introducing the new tree type.

The simpler solution is to detect whether the root of the file tree is a file or not, and then select the corresponding tree type for the `DirectoryTreeOutputFilePropertySpec`.

The current problem happens, since the tasks above use the sources of a `SourceTask` as the output. The `SourceTask` creates file trees of all the sources, so we are in a situation where we have file trees rooted in regular files if you add regular files as sources to a file tree. The tasks which want to support this can move away from extending `SourceTask` and declare a regular `ConfigurableFileCollection` as their inputs. You can still add filtered file trees to that file collection, though you can also add regular files without running into the problem above. The problem somewhat remains that `@OutputFiles` means that you can only have files in the outputs, and not directories, and file trees would somewhat violate that.

**Comment by cortinico** [comment]
> The tasks which want to support this can move away from extending `SourceTask` and declare a regular `ConfigurableFileCollection` as their inputs. You can still add filtered file trees to that file collection, though you can also add regular files without running into the problem above

Agree that this is probably the best workaround as of today. However moving away from `SourceTask` makes us lose several features that we would have to handle manually (Mostly `@SkipWhenEmpty` and Incremental support).

**Comment by wolfs** [comment]
> Agree that this is probably the best workaround as of today. However moving away from SourceTask makes us lose several features that we would have to handle manually (Mostly @SkipWhenEmpty and Incremental support).

You only need to add `@SkipWhenEmpty` on your new input property and you still have incremental support.

**Comment by wolfs** [comment]
Instead of supporting this use-case, we decided to improve the error message: https://github.com/gradle/gradle/pull/17053

I'll close the issue now since there is a workaround: Use directories with `includes` instead. Or do not extend `SourceTask` and use a regular `ConfigurableFileCollection` as `@OutputFiles` for your task.
