### ISSUE TITLE
Toolchain property compatibility check failure in 6.8 for compileGroovy

### ISSUE THREAD

**Issue by anuraaga** [gradle/gradle#15752]
### Expected Behavior

Toolchains can be used with project that uses Groovy without losing support for IntelliJ automatically detecting the JVM level for sources.

### Current Behavior

Trying to use toolchains (to control build environment) and `sourceCompatibility` (to support IntelliJ detecting JVM level) fails for Groovy when using `sourceCompatibility`. `IdeaProject.languageLevel` could possibly be used but the docs discourage it

https://docs.gradle.org/current/dsl/org.gradle.plugins.ide.idea.model.IdeaProject.html#org.gradle.plugins.ide.idea.model.IdeaProject:languageLevel

### Context
This was working in 6.7, but stopped working in 6.8. 

Configuration is here: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/gradle/java.gradle#L42

It seems to be intentional in #14850. But because of it, I don't see how to have an easy-to-use build where IntelliJ detects the JVM level correctly without using `IdeaProject.languageLevel` - is this intended usage when using toolchains?

### Steps to Reproduce 

I think the issue is relatively obvious but this would repo if you need

```
git clone https://github.com/anuraaga/opentelemetry-java-instrumentation.git
cd opentelemetry-java-instrumentation
git fetch origin gradle-6.8
git checkout gradle-6.8
./gradlew :testing-common:compileGroovy
```

Fails with

```
Caused by: org.gradle.api.InvalidUserDataException: The new Java toolchain feature cannot be used at the project level in combination with source and/or target compatibility
        at org.gradle.api.plugins.JavaBasePlugin.checkToolchainAndCompatibilityUsage(JavaBasePlugin.java:346)
        at org.gradle.api.plugins.JavaBasePlugin.lambda$determineCompatibility$8(JavaBasePlugin.java:336)
        at org.gradle.util.GUtil.uncheckedCall(GUtil.java:452)
        at org.gradle.internal.extensibility.ConventionAwareHelper$2.doGetValue(ConventionAwareHelper.java:82)
        at org.gradle.internal.extensibility.ConventionAwareHelper$MappedPropertyImpl.getValue(ConventionAwareHelper.java:128)
        at org.gradle.internal.extensibility.ConventionAwareHelper.getConventionValue(ConventionAwareHelper.java:110)
        at org.gradle.api.tasks.compile.GroovyCompile_Decorated.getSourceCompatibility(Unknown Source)
        at jdk.internal.reflect.GeneratedMethodAccessor619.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue$1$1.create(AbstractNestedRuntimeBeanNode.java:77)
        at org.gradle.internal.deprecation.DeprecationLogger.whileDisabled(DeprecationLogger.java:236)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue$1.get(AbstractNestedRuntimeBeanNode.java:73)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
```

### Your Environment

Build scan URL: https://gradle.com/s/rehgrrtzcjycq

**Comment by ljacomet** [comment]
There is a confusion there I believe.
If you leverage toolchains, you indeed cannot use `sourceCompatibility` in the `java` extension. But the java version that the toolchain represents will be visible to IntelliJ during import which should result in the right language level selected.

Can you try this setup?
And if does not work update your reproducer with what you tried and what you expect to see in the IDE.

**Comment by anuraaga** [comment]
@ljacomet Ok I will try to investigate a bit. I had a report on Slack that after removing those, IntelliJ stopped working until restoring in a different repo here - https://github.com/gradle/gradle/issues/15752. I didn't personally reproduce it though.

> But the java version that the toolchain represents will be visible to IntelliJ during import which should result in the right language level selected.

One question, did you mean the version of the `options.release` flag? The toolchain version can't be used since you may use a newer JDK to target older bytecode.

**Comment by ljacomet** [comment]
> One question, did you mean the version of the `options.release` flag? The toolchain version can't be used since you may use a newer JDK to target older bytecode.

In that case, you can specify the `sourceCompatibility` at the compilation task level and still use toolchains to get the JDK.

**Comment by ljacomet** [comment]
Closing as there is nothing to change in Gradle.

Please add more information if you think the information provided does not resolve the issue.
