### ISSUE TITLE
java.lang.IllegalArgumentException: MALFORMED from DefaultClasspathEntryHasher in 3.6 nightlies

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#1581]
We're hitting a corrupted jar on the buildscript classpath, and rather than a friendly exception we get the underlying exception with no context:

        Caused by: java.lang.IllegalArgumentException: MALFORMED
                at org.gradle.api.internal.changedetection.state.DefaultClasspathEntryHasher.hashJar(DefaultClasspathEntryHasher.java:73)
                at org.gradle.api.internal.changedetection.state.DefaultClasspathEntryHasher.hash(DefaultClasspathEntryHasher.java:59)
                at org.gradle.api.internal.changedetection.state.CachingClasspathEntryHasher.hash(CachingClasspathEntryHasher.java:46)
                at org.gradle.api.internal.changedetection.state.DefaultClasspathSnapshotter.normaliseFileElement(DefaultClasspathSnapshotter.java:76)
                at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter$FileCollectionVisitorImpl.visitCollection(AbstractFileCollectionSnapshotter.java:144)
                at org.gradle.api.internal.file.AbstractFileCollection.visitRootElements(AbstractFileCollection.java:234)
                at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter.snapshot(AbstractFileCollectionSnapshotter.java:71)
                at org.gradle.api.internal.initialization.loadercache.DefaultClasspathHasher.hash(DefaultClasspathHasher.java:40)
                at org.gradle.api.internal.initialization.loadercache.DefaultClassLoaderCache.get(DefaultClassLoaderCache.java:59)
                at org.gradle.api.internal.initialization.loadercache.DefaultClassLoaderCache.get(DefaultClassLoaderCache.java:53)
                at org.gradle.api.internal.initialization.DefaultClassLoaderScope.loader(DefaultClassLoaderScope.java:164)
                at org.gradle.api.internal.initialization.DefaultClassLoaderScope.buildLockedLoader(DefaultClassLoaderScope.java:58)
                at org.gradle.api.internal.initialization.DefaultClassLoaderScope.buildLockedLoader(DefaultClassLoaderScope.java:72)
                at org.gradle.api.internal.initialization.DefaultClassLoaderScope.buildEffectiveLoaders(DefaultClassLoaderScope.java:108)
                at org.gradle.api.internal.initialization.DefaultClassLoaderScope.getLocalClassLoader(DefaultClassLoaderScope.java:142)
                at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:166)
                at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
                at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
                at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
                at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:70)
                ... 55 more

## Environment

Gradle 3.6-20170314000035+0000

**Comment by lptr** [comment]
@DanielThomas thanks for reporting this. Is `MALFORMED` the actual message you get? And is the stacktrace and the Gradle version number accurate? I'm trying to reproduce this, but I can't figure out how such a message could be produced at that specific location.

Can you create a build scan? Or submit a minimal test project that helps us reproduce this?

**Comment by DanielThomas** [comment]
Yep, that's the actual message, I think the stacktrace must have been filtered by you guys? I set an exception breakpoint and saw it was coming from underlying zip code, let me see if I can reproduce again and give you the exact location. That's definitely the right Gradle version.

**Comment by DanielThomas** [comment]
This happens with specifically malformed UTF-8 zips, and I don't have the original zip to hand unfortunately, but I can prove that this code can receive an exception it can't handle.

This exception originates in `java.util.zip.ZipCoder#toString(byte[], int)`, line 58:

        if (isUTF8 && cd instanceof ArrayDecoder) {
            int clen = ((ArrayDecoder)cd).decode(ba, 0, length, ca);
            if (clen == -1)    // malformed
                throw new IllegalArgumentException("MALFORMED");
            return new String(ca, 0, clen);
        }

Backtrace from there:

- `java.util.zip.ZipInputStream#readLOC` line 298
- `java.util.zip.ZipInputStream#getNextEntry` line 122
- `org.gradle.api.internal.changedetection.state.DefaultClasspathEntryHasher#hashJar` calls `zipInput.getNextEntry()` at line 73

There's no exception handling in `ZipInputStream` to wrap that in a `ZipException` or `IOException` so the `IllegalStateException` can get by your exception handling code here:

        } catch (ZipException e) {
            DeprecationLogger.nagUserWith("Malformed jar [" + fileDetails.getName() + "] found on classpath. Gradle 5.0 will no longer allow malformed jars on a classpath.");
            return hashFile(fileDetails, hasher, classpathContentHasher);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        } finally {
            IOUtils.closeQuietly(zipInput);
        }

**Comment by wolfs** [comment]
@DanielThomas Thanks again for reporting. This has been fixed for 3.5 and is part of a release branch snapshot: 3.5-20170317172546+0000
Could you try the fix and see if you can build your project now?

**Comment by bmuschko** [comment]
@wolfs Can the issue be closed?
