### ISSUE TITLE
Source file path of a filtered CopySpec not available in eachFile

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#1588]
If you have a `CopySpec` with `filter` and you try to use the `file` property of the `FileCopyDetails`, you get an exception. There is no easy way to get hold of the full source path in this case, just the relative one, relative to the copy spec root. But that is not too helpful if the `eachFile` is in a parent copy spec. Is there a reason the file is not returned in this case? If not, please make it available. If the reason is, that the user is prevented to do something with the unfiltered file, that is not a too good reason in my opinion. The docs for `getFile` could make clear that filterings will not be done in the file returned here as it is the source file, but I see no reason to not provide the source file to the user.

**Comment by bmuschko** [comment]
Can you please provide some sample code to illustrate the issue? The following works fine for me:

```
task copy(type: Copy) {
    from 'content'
    into 'target'
    
    eachFile { FileCopyDetails details ->
        println details.file
    }
}
```

**Comment by Vampire** [comment]
@bmuschko you missed the `filter` part. You need a filter in the copyspec, then it fails.

**Comment by bmuschko** [comment]
I add the following `filter(org.apache.tools.ant.filters.ReplaceTokens, tokens: [version: '2.3.1'])` and still don't see an issue. Please provide an example that will help me reproduce it. You can simply extend the one I already provided.

**Comment by Vampire** [comment]
Have the `filter` before the `eachFile` and it will fail:

```
task copy(type: Copy) {
    from 'content'
    into 'target'

    filter(org.apache.tools.ant.filters.ReplaceTokens, tokens: [version: '2.3.1'])

    eachFile { FileCopyDetails details ->
        println details.file
    }
}
```

**Comment by Vampire** [comment]
Also interesting, it is not really consistent. If you have the filter in a subspec like

```
task copy(type: Copy) {
    from 'content'
    into 'target'

    eachFile { FileCopyDetails details ->
        println details.file
    }

    from('content') {
       filter(org.apache.tools.ant.filters.ReplaceTokens, tokens: [version: '2.3.1'])
    }
}
```

or

```
task copy(type: Copy) {
    from 'content'
    into 'target'

    from('content') {
       filter(org.apache.tools.ant.filters.ReplaceTokens, tokens: [version: '2.3.1'])
    }

    eachFile { FileCopyDetails details ->
        println details.file
    }
}
```

it works fine. It only fails with `UnsupportedOperationException` and without message (also not too helpful) if one of the following is true:

- the `filter` is in the same copy spec and before the `eachFile`
- the `filter` is in a parent copy spec, no matter if before or after

so the following two fail and show the second point of this list:

```
task copy(type: Copy) {
    from 'content'
    into 'target'

    from('content') {
       eachFile { FileCopyDetails details ->
           println details.file
       }
    }

    filter(org.apache.tools.ant.filters.ReplaceTokens, tokens: [version: '2.3.1'])
}
```
```
task copy(type: Copy) {
    from 'content'
    into 'target'

    filter(org.apache.tools.ant.filters.ReplaceTokens, tokens: [version: '2.3.1'])

    from('content') {
       eachFile { FileCopyDetails details ->
           println details.file
       }
    }
}
```

**Comment by bmuschko** [comment]
OK, that looks like a bug then.

Sample stack trace:

```
Caused by: java.lang.UnsupportedOperationException
        at org.gradle.api.internal.file.copy.DefaultFileCopyDetails.getFile(DefaultFileCopyDetails.java:62)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:213)
        at org.gradle.internal.metaobject.BeanDynamicObject.getProperty(BeanDynamicObject.java:156)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:60)
        at org.gradle.api.internal.file.copy.DefaultFileCopyDetails_Decorated.getProperty(Unknown Source)
        at build_9p7sqtuu1e36tlqmo3thrlr8y$_run_closure1$_closure2.doCall(/Users/bmuschko/dev/projects/gradle-playground/copyspec-filte/build.gradle:8)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.api.internal.file.copy.CopyFileVisitorImpl.processFile(CopyFileVisitorImpl.java:57)
        at org.gradle.api.internal.file.copy.CopyFileVisitorImpl.visitFile(CopyFileVisitorImpl.java:46)
        at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalker$1.visitFile(Jdk7DirectoryWalker.java:85)
        at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalker$1.visitFile(Jdk7DirectoryWalker.java:58)
        at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalker.walkDir(Jdk7DirectoryWalker.java:58)
        at org.gradle.api.internal.file.collections.DirectoryFileTree.walkDir(DirectoryFileTree.java:171)
        at org.gradle.api.internal.file.collections.DirectoryFileTree.visitFrom(DirectoryFileTree.java:149)
        at org.gradle.api.internal.file.collections.DirectoryFileTree.visit(DirectoryFileTree.java:134)
        at org.gradle.api.internal.file.collections.FileTreeAdapter.visit(FileTreeAdapter.java:110)
        at org.gradle.api.internal.file.CompositeFileTree.visit(CompositeFileTree.java:87)
        at org.gradle.api.internal.file.copy.CopySpecActionImpl.execute(CopySpecActionImpl.java:39)
        at org.gradle.api.internal.file.copy.CopySpecActionImpl.execute(CopySpecActionImpl.java:24)
        at org.gradle.api.internal.file.copy.DefaultCopySpec$DefaultCopySpecResolver.walk(DefaultCopySpec.java:648)
        at org.gradle.api.internal.file.copy.DefaultCopySpec$DefaultCopySpecResolver.walk(DefaultCopySpec.java:650)
        at org.gradle.api.internal.file.copy.DefaultCopySpec.walk(DefaultCopySpec.java:458)
        at org.gradle.api.internal.file.copy.DelegatingCopySpecInternal.walk(DelegatingCopySpecInternal.java:236)
        at org.gradle.api.internal.file.copy.CopySpecBackedCopyActionProcessingStream.process(CopySpecBackedCopyActionProcessingStream.java:38)
        at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator$1.process(DuplicateHandlingCopyActionDecorator.java:44)
        at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator$1.process(NormalizingCopyActionDecorator.java:57)
        at org.gradle.api.internal.file.copy.FileCopyAction.execute(FileCopyAction.java:35)
        at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator.execute(NormalizingCopyActionDecorator.java:53)
        at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator.execute(DuplicateHandlingCopyActionDecorator.java:42)
        at org.gradle.api.internal.file.copy.CopyActionExecuter.execute(CopyActionExecuter.java:40)
        at org.gradle.api.tasks.AbstractCopyTask.copy(AbstractCopyTask.java:179)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 20 more
```

Would you be interested in providing a fix?

**Comment by Vampire** [comment]
Well, it was introduced intentionally by Adam with commit 988e40aa, so I'm not sure whether there is a sane reason to do so. I would simply remove the if acutally. :-D

**Comment by bmuschko** [comment]
@adammurdoch Would mind comment on the change?

**Comment by Vampire** [comment]
@bmuschko shouldn't this have label waiting-for-gradle or how it was called?

**Comment by Vampire** [comment]
wow, that was fast :-D

**Comment by wszeboreq** [comment]
I hit the same or very similar problem with Gradle 4.10.1 in the following CopySpec scenario ('filter()' in the parent CopySpec):

```
{
    from(...) {
        ...
        eachFile {
            ...
            f.relativePath = new RelativePath(!f.file.isDirectory(), newPath as String[])
            ...
        }
    }

    from(...) {
        ...
        eachFile {
            ...
            f.relativePath = new RelativePath(!f.file.isDirectory(), newPath as String[])
            ...
        }
    }

    filter(FixCrLfFilter, eol: FixCrLfFilter.CrLf.newInstance('asis'), fixlast: false)
}
```

The error is for the line with 'f.relativePath', the stack trace is:

```
Caused by: java.lang.UnsupportedOperationException
        at org.gradle.api.internal.file.copy.DefaultFileCopyDetails.getFile(DefaultFileCopyDetails.java:67)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:228)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:171)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:59)
        at org.gradle.api.internal.file.copy.DefaultFileCopyDetails_Decorated.getProperty(Unknown Source)
        at cpptest_professional_distro_27ovixm53hlvdhd06klp3kygs$_run_closure3$_closure9$_closure20$_closure77$_closure78$_closure79$_closure82$_closure85.doCall(...)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:167)
        at org.gradle.api.internal.file.copy.CopyFileVisitorImpl.processFile(CopyFileVisitorImpl.java:57)
        at org.gradle.api.internal.file.copy.CopyFileVisitorImpl.visitFile(CopyFileVisitorImpl.java:46)
        at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTreeImpl$1.visitFile(AbstractFileTree.java:198)
        at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTreeImpl$1.visitFile(AbstractFileTree.java:198)
        at org.gradle.api.internal.file.archive.ZipFileTree.visit(ZipFileTree.java:97)
        ... 69 more
```

Using 'filter' in the end of each of the child CopySpecs (so, after the 'eachFile()') resolves the problem.

**Comment by wszeboreq** [comment]
It's quite easy to hit this issue when using bigger CopySpec with hierarchies, e.g. ones for 'distribution' plugin 'contents' specifications. Workaround with avoiding the specific order of 'eachFile' and 'filter' is not always viable. What are the plans for fixing it, is it possible to schedule this bug to some milestone?

**Comment by Vampire** [comment]
Still happening with 6.5.1 and no comment by @adammurdoch :-(

**Comment by cloudshiftchris** [comment]
Still occurs on Gradle 8.2.1.  Conditional makes no sense - so there is a filter processing the content, that doesn't pertain to the file itself.  Its an eachFile, not having the file available is... odd.
