### ISSUE TITLE
Cannot run composite build in Windows mount point root

### ISSUE THREAD

**Issue by davidburstrom** [gradle/gradle#15974]
Given a project situated in a Windows mount point root (e.g. on a shared drive):

`settings.gradle.kts` (required because of https://github.com/gradle/gradle/issues/15655):
```kotlin
rootProject.name = "bug"
```

`build.gradle.kts`:
```kotlin
tasks.register("composite", GradleBuild::class.java) {
    tasks = listOf("help")
}
```

### Expected Behaviour

It should be possible to run `gradle :composite` successfully.

### Current Behaviour

The build fails with the following truncated stack trace:

```
Caused by: org.gradle.api.InvalidUserDataException: A path must be specified!
        at org.gradle.util.Path.path(Path.java:35)
        at org.gradle.composite.internal.DefaultIncludedBuildRegistry.assignPath(DefaultIncludedBuildRegistry.java:276)
        at org.gradle.composite.internal.DefaultIncludedBuildRegistry.addNestedBuildTree(DefaultIncludedBuildRegistry.java:205)
        at org.gradle.api.tasks.GradleBuild.build(GradleBuild.java:195)
```

### Context

Basically, it makes cross-platform verification harder, since the bulk of my coding take place on a Mac and I verify Windows compatibility in a virtual environment by sharing the repo folder. A workaround is of course to share the parent folder of the repo and build in `Z:\repo\.

### Your Environment

Gradle 6.8.1, 6.7.1, 6.4.1
Windows 10
Build scan URL: https://scans.gradle.com/s/bkv4wkz6pbae2

**Comment by davidburstrom** [comment]
I can confirm the same issue persists in 7.0.2 and in 7.1.0-rc1

**Comment by jbartok** [comment]
@davidburstrom Given that #15655 was fixed in Gradle `8.1`, is this still an issue?

**Comment by ov7a** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team, but the existence of a workaround makes it non-critical, so it might take a while before a fix is made.

**Comment by davidburstrom** [comment]
Thank you!
