### ISSUE TITLE
Using dependencyResolutionManagement with a custom build script file fails

### ISSUE THREAD

**Issue by pbarnoux** [gradle/gradle#16073]
When build script file is not named `build.gradle`, `dependencyResolutionManagement` fails with: Mutation of repositories declared in settings is only allowed during settings evaluation.

`foo.gradle`:
```gradle
println "building (foo.gradle)..."
```

`init.gradle`:
```gradle
println "registering hook on settingsEvaluated (init.gradle)..."
settingsEvaluated { settings ->
	settings.dependencyResolutionManagement {
		repositories {
			mavenLocal()
		}
	}
}
```

### Expected Behavior
`$ gradle -I init.gradle -b foo.gradle build`
should print:
registering hook on settingsEvaluated (init.gradle)...

> Configure project :
building (foo.gradle)...
[...]

### Current Behavior
registering hook on settingsEvaluated (init.gradle)...

FAILURE: Build failed with an exception.

* Where:
Initialization script '/tmp/init-script/init.gradle' line: 5

* What went wrong:
Mutation of repositories declared in settings is only allowed during settings evaluation

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.InvalidUserCodeException: Mutation of repositories declared in settings is only allowed during settings evaluation
        at org.gradle.internal.management.DefaultDependencyResolutionManagement.mutationDisallowed(DefaultDependencyResolutionManagement.java:148)
        at org.gradle.internal.ImmutableActionSet$SetWithFewActions.execute(ImmutableActionSet.java:285)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:264)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.doAdd(DefaultNamedDomainObjectCollection.java:113)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:253)
        at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.access$101(DefaultArtifactRepositoryContainer.java:35)
        at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.lambda$new$0(DefaultArtifactRepositoryContainer.java:38)
        at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.addWithUniqueName(DefaultArtifactRepositoryContainer.java:101)
        at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.addRepository(DefaultArtifactRepositoryContainer.java:89)
        at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.addRepository(DefaultArtifactRepositoryContainer.java:84)
        at org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.mavenLocal(DefaultRepositoryHandler.java:127)
        at jdk.internal.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

### Context
I have an init.d/init.gradle script in my GRADLE_USER_HOME installation dir with that directive to globally configure my repositories on all projects and was trying to run a build file that was not named `build.gradle`.

### Steps to Reproduce 
[mutable-repository-ex.zip](https://github.com/gradle/gradle/files/5945669/mutable-repository-ex.zip)

### Your Environment
$ uname -a
Linux 5.4.95-1-lts x86_64 GNU/Linux
$ java --version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9)
OpenJDK 64-Bit Server VM (build 11.0.10+9, mixed mode)
$ gradle --version

------------------------------------------------------------
Gradle 6.8.1
------------------------------------------------------------

Build time:   2021-01-23 22:42:21 UTC
Revision:     <unknown>

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.10 (Oracle Corporation 11.0.10+9)
OS:           Linux 5.4.95-1-lts amd64

**Comment by ljacomet** [comment]
Your Gradle version output is not normal. It should indicate the commit it was created from in `Revision`.
Can you first redo your test with a Gradle version downloaded from [the Gradle website](https://gradle.org/releases/)?

**Comment by ljacomet** [comment]
I suspect you are running a modified Gradle version from a package manager which for some reason does not contain the fix for #15772

**Comment by pbarnoux** [comment]
Hi, indeed I delegate installation of system gradle to my package manager.
I used the wrapper with version 6.8.1 and 6.8.2 to reproduce the issue:

```
$ ./gradlew -I init.gradle -b foo.gradle build
Starting a Gradle Daemon (subsequent builds will be faster)
registering hook on settingsEvaluated (init.gradle)...

FAILURE: Build failed with an exception.

* Where:
Initialization script '/tmp/issue/init.gradle' line: 5

* What went wrong:
Mutation of repositories declared in settings is only allowed during settings evaluation

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
$ ./gradlew --version

------------------------------------------------------------
Gradle 6.8.2
------------------------------------------------------------

Build time:   2021-02-05 12:53:00 UTC
Revision:     b9bd4a5c6026ac52f690eaf2829ee26563cad426

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.10 (Oracle Corporation 11.0.10+9)
OS:           Linux 5.4.96-1-lts amd64
```
