### ISSUE TITLE
Gradle throws java.lang.StackOverflowError if there are multiple JCEs defined in same java.security entry

### ISSUE THREAD

**Issue by razgon** [gradle/gradle#16182]
### Expected Behavior
Gradle should not throw exception

### Current Behavior
Gradle throws java.lang.StackOverflowError immedeatly

### Context
Trying to compile any project

### Steps to Reproduce 
1. Edit security.provider in ...../conf/security/java.security
2. Set 
```
security.provider.1=com.safelogic.cryptocomply.jcajce.provider.CryptoComplyFipsProvider
security.provider.2=SunJSSE CCJ
```
3. Run gradle
4. Observe Exception
`* Exception is:
java.lang.StackOverflowError
        at java.base/java.util.Dictionary.<init>(Dictionary.java:55)
        at java.base/java.util.Hashtable.<init>(Hashtable.java:239)
        at java.base/java.util.Properties.<init>(Properties.java:206)
        at java.base/java.util.Properties.<init>(Properties.java:174)
        at java.base/java.security.Provider.<init>(Provider.java:262)
        at java.base/sun.security.ssl.SunJSSE.<init>(SunJSSE.java:138)
        at java.base/sun.security.ssl.SunJSSE.<init>(SunJSSE.java:126)
        at java.base/com.sun.net.ssl.internal.ssl.Provider.<init>(Provider.java:52)
        at java.base/sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:183)
        at java.base/sun.security.jca.ProviderList.getProvider(ProviderList.java:266)
        at java.base/sun.security.jca.ProviderList.getIndex(ProviderList.java:296)
        at java.base/sun.security.jca.ProviderList.getProviderConfig(ProviderList.java:280)
        at java.base/sun.security.jca.ProviderList.getProvider(ProviderList.java:286)
        at java.base/java.security.Security.getProvider(Security.java:473)
        at java.base/sun.security.ssl.SunJSSE.<init>(SunJSSE.java:143)
        at java.base/sun.security.ssl.SunJSSE.<init>(SunJSSE.java:126)
        at java.base/com.sun.net.ssl.internal.ssl.Provider.<init>(Provider.java:52)
        at java.base/sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:183)
        at java.base/sun.security.jca.ProviderList.getProvider(ProviderList.java:266)
        at java.base/sun.security.jca.ProviderList.getIndex(ProviderList.java:296)
        at java.base/sun.security.jca.ProviderList.getProviderConfig(ProviderList.java:280)
        at java.base/sun.security.jca.ProviderList.getProvider(ProviderList.java:286)
        at java.base/java.security.Security.getProvider(Security.java:473)
        at java.base/sun.security.ssl.SunJSSE.<init>(SunJSSE.java:143)
        at java.base/sun.security.ssl.SunJSSE.<init>(SunJSSE.java:126)
        at java.base/com.sun.net.ssl.internal.ssl.Provider.<init>(Provider.java:52)
        at java.base/sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:183)
        at java.base/sun.security.jca.ProviderList.getProvider(ProviderList.java:266)
        at java.base/sun.security.jca.ProviderList.getIndex(ProviderList.java:296)
        at java.base/sun.security.jca.ProviderList.getProviderConfig(ProviderList.java:280)
        at java.base/sun.security.jca.ProviderList.getProvider(ProviderList.java:286)
        at java.base/java.security.Security.getProvider(Security.java:473)
        at java.base/sun.security.ssl.SunJSSE.<init>(SunJSSE.java:143)
        at java.base/sun.security.ssl.SunJSSE.<init>(SunJSSE.java:126)
        at java.base/com.sun.net.ssl.internal.ssl.Provider.<init>(Provider.java:52)
        at java.base/sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:183)
        at java.base/sun.security.jca.ProviderList.getProvider(ProviderList.java:266)
        at java.base/sun.security.jca.ProviderList.getIndex(ProviderList.java:296)
        at java.base/sun.security.jca.ProviderList.getProviderConfig(ProviderList.java:280)
        at java.base/sun.security.jca.ProviderList.getProvider(ProviderList.java:286)
        at java.base/java.security.Security.getProvider(Security.java:473)
        at java.base/sun.security.ssl.SunJSSE.<init>(SunJSSE.java:143)
        at java.base/sun.security.ssl.SunJSSE.<init>(SunJSSE.java:126)
`

### Your Environment
Mac OS Version 11.2.1 (20D74)

Gradle version 6.5.1

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

Build scan URL: Gradle doesn't work.

Note: Problem is second provider SunJSSE CCJ where we want Jsse to send crypto calls to CCJ

**Comment by mlopatkin** [comment]
If I understand correctly, `com.safelogic.cryptocomply.jcajce.provider.CryptoComplyFipsProvider` is a proprietary implementation of the Java crypto API. I don't have access to it, so I cannot reproduce the issue locally with 100% confidence. However, I suspect a potential misconfiguration. The provider `SunJSSE CCJ` syntax requires a provider with the name `CCJ` to be specified before (I. e. with the lower number) this one. As I don't have access to the CryptoComply library, I cannot check what is the name of the `CryptoComplyFipsProvider`. If it isn't equal to `CCJ` then the StackOverflowError is guaranteed.

Either way, the issue seems to have little to do with Gradle itself and can be reproduced with any Java program that tries to retrieve a security provider by name, e.g. by calling `java.security.Security.getProvider("BC")`. I'm closing the issue but feel free to reply if you disagree with this, please.
