### ISSUE TITLE
Gradle misconfigures java util logging when running tests 

### ISSUE THREAD

**Issue by vyazelenko** [gradle/gradle#16257]
While running JUnit 5 tests with Gradle we observed that we were getting some extra output from JUnit that we didn't expect, e.g.:
```
Gradle Test Executor 8 STANDARD_ERROR
    Feb 22, 2021 7:52:26 PM org.junit.platform.launcher.core.EngineDiscoveryOrchestrator lambda$logTestDescriptorExclusionReasons$7
    INFO: 3 containers and 75 tests were excluded because tags match tag expression(s): [slow,topology]
```
That is JUnit is logging at `Level.INFO` information about which tests were excluded due to the tags used. However since we are running Gradle with default `LIFECYCLE` log level we expect that no `INFO` messages should be logged. Moreover that `INFO` message is logged into the `STANDARD_ERROR` stream.  

### Expected Behavior
No messages from JUnit 5 should be logged at `Level.INFO` and no output from JUL should go to the `STANDARD_ERROR` stream.  

### Current Behavior
We are seeing those messages.

### Context
Getting unexpected output in tests.

### Steps to Reproduce
A standalone project to reproduce the issue can be found [here](https://github.com/vyazelenko/gradle-logging-bug).
Clone project and run `./gradlew test`.

### Your Environment
Observed output:
```
> Task :test FAILED

JavaUtilLoggingOutput > test() STANDARD_OUT
    Standard out

JavaUtilLoggingOutput > test() STANDARD_ERROR
    Feb 22, 2021 10:46:12 PM test.JavaUtilLoggingOutput test
    INFO: You should not see me!

JavaUtilLoggingOutput > test() FAILED
    java.lang.RuntimeException: But this you should!
        at test.JavaUtilLoggingOutput.test(JavaUtilLoggingOutput.java:17)

1 test completed, 1 failed
```
Expected output:
```
> Task :test FAILED

JavaUtilLoggingOutput > test() STANDARD_OUT
    Standard out

JavaUtilLoggingOutput > test() FAILED
    java.lang.RuntimeException: But this you should!
        at test.JavaUtilLoggingOutput.test(JavaUtilLoggingOutput.java:17)

1 test completed, 1 failed
```

I tried to debug this and it seems that Gradle is initializing JUL twice:
# First when the `DefaultLoggingManager` is initialized:
```java
      at java.util.logging.Logger.updateEffectiveLevel(Logger.java:2125)
      at java.util.logging.Logger.setLevel(Logger.java:1692)
      at org.gradle.internal.logging.source.JavaUtilLoggingSystem.install(JavaUtilLoggingSystem.java:110)
      at org.gradle.internal.logging.source.JavaUtilLoggingSystem.startCapture(JavaUtilLoggingSystem.java:73)
      at org.gradle.internal.logging.services.DefaultLoggingManager$StartableLoggingSystem.start(DefaultLoggingManager.java:330)
      at org.gradle.internal.logging.services.DefaultLoggingManager.start(DefaultLoggingManager.java:81)
      at org.gradle.internal.logging.services.DefaultLoggingManager.start(DefaultLoggingManager.java:38)
      at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:127)
      at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
      at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
      at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```
# And the second time before starting tests:
```
      at org.gradle.api.internal.tasks.testing.JULRedirector.start(JULRedirector.java:37)
      at org.gradle.api.internal.tasks.testing.processors.TestOutputRedirector.startRedirecting(TestOutputRedirector.java:41)
      at org.gradle.api.internal.tasks.testing.processors.CaptureTestOutputTestResultProcessor.started(CaptureTestOutputTestResultProcessor.java:54)
      at org.gradle.api.internal.tasks.testing.results.AttachParentTestResultProcessor.started(AttachParentTestResultProcessor.java:38)
      at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.startProcessing(SuiteTestClassProcessor.java:40)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
      at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
      at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
      at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
      at com.sun.proxy.$Proxy2.startProcessing(Unknown Source:-1)
      at org.gradle.api.internal.tasks.testing.worker.TestWorker.startProcessing(TestWorker.java:112)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
      at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
      at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
      at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
      at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
      at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
      at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
      at java.lang.Thread.run(Thread.java:748)
```

**Comment by misssonder** [comment]
Hi,In the relevant documentation of gradle, I did not see that testLogging.events can be set to'INFO'.[here](https://mkyong.com/gradle/gradle-display-test-results-in-console/)
![image](https://user-images.githubusercontent.com/44472482/109390095-8a506f00-794a-11eb-9816-1855537b21a4.png)

**Comment by ov7a** [comment]
Sorry for the late reply!

The issue is in the backlog of the relevant team and is prioritized by them.

***

This issue is still reproducible with Gradle 8.14 and 9.0.0-M4. Potentially related (see [this comment](https://github.com/gradle/gradle/issues/30554#issuecomment-2352333736)):
* https://github.com/gradle/gradle/issues/30554
