### ISSUE TITLE
Cyclic project dependencies fail to resolve for copied Configuration

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#1638]
Given a cycle-like multi-project configurations, copied configurations fail to resolve with the following exception:

```
Caused by: org.gradle.internal.component.model.ConfigurationNotFoundException: Project :b declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :a.
	at org.gradle.internal.component.model.LocalComponentDependencyMetadata.selectConfigurations(LocalComponentDependencyMetadata.java:124)
	at org.gradle.internal.component.local.model.DslOriginDependencyMetadataWrapper.selectConfigurations(DslOriginDependencyMetadataWrapper.java:65)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$DependencyEdge.calculateTargetConfigurations(DependencyGraphBuilder.java:303)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$DependencyEdge.attachToTargetConfigurations(DependencyGraphBuilder.java:270)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.traverseGraph(DependencyGraphBuilder.java:167)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:104)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:92)
	at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver$1.run(CacheLockingArtifactDependencyResolver.java:45)
	at org.gradle.internal.Factories$1.create(Factories.java:25)
	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:189)
	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:175)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:134)
	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.useCache(DefaultCacheFactory.java:199)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultCacheLockingManager.useCache(DefaultCacheLockingManager.java:65)
	at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver.resolve(CacheLockingArtifactDependencyResolver.java:43)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolveGraph(DefaultConfigurationResolver.java:134)
	at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveGraph(ShortCircuitEmptyConfigurationResolver.java:74)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:67)
	... 126 more
```

Leading us to use this workaround:

https://github.com/nebula-plugins/gradle-resolution-rules-plugin/blob/master/src/main/kotlin/nebula/plugin/resolutionrules/gradleInterop.kt#L63

### Steps to reproduce

Reproducible using the following reduced test:

```
subprojects {
	apply plugin: 'java'
}

project(':a') {
	dependencies {
		testCompile project(':b')
	}

	task testCase {
		doFirst {
			configurations.testCompile.copyRecursive().incoming.resolutionResult.allDependencies
		}
	}
}

project(':b') {
	dependencies {
		compile project(':a')
	}
}
```

### Your Environment
Gradle 2.x and 3.x

**Comment by bigdaz** [comment]
Similar to #1555, we'd rather address this by removing the need to copy and resolve configurations. But we are happy to consider PRs that address any issues in the meantime.

**Comment by DanielThomas** [comment]
@bigdaz unless you're planning on removing configuration copying completely, I'd still consider this a bug (even though it's pretty funky). Your call on it's merits though.

**Comment by bigdaz** [comment]
Good point. Reopening.

**Comment by bigdaz** [comment]
I've confirmed this issue: it's the result of a dependency cycle that references back to the copied `Configuration`. The root node for the copied `Configuration` is different from the root node for the original `Configuration`: it's backed by a `ConfigurationProvider` with only a single named configuration. Thus a cycle back to the root will fail to find named configurations that are different.

Since copied configurations are widely used in the Spring DM plugin as well as the Nebula resolution rules plugin, I'm reluctant to make any changes to the way they are structured. Instead, we aim to eliminate the need to resolve copied configurations.

**Comment by bigdaz** [comment]
https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/46

**Comment by jjohannes** [comment]
If I read this correctly, we do not want to "fix" this as it would change the existing behavior, on which the above mentioned plugins rely. In that case, there is no point in keeping this issue open.

Please re-open the issue if there are concrete changes we should do and want to do.
