### ISSUE TITLE
Gradle 3.5 RC1 breaks the error prone plugin

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#1645]
When applying the [error prone Gradle plugin](https://github.com/tbroyer/gradle-errorprone-plugin) the build fails with the following exception:

```
Caused by: java.lang.UnsupportedOperationException
        at org.gradle.api.tasks.compile.JavaCompile.setToolChain(JavaCompile.java:141)
        at org.gradle.api.tasks.compile.JavaCompile_Decorated.setToolChain(Unknown Source)
        at net.ltgt.gradle.errorprone.ErrorPronePlugin$1.execute(ErrorPronePlugin.java:20)
        at net.ltgt.gradle.errorprone.ErrorPronePlugin$1.execute(ErrorPronePlugin.java:17)
```

See https://github.com/tbroyer/gradle-errorprone-plugin/issues/37.

### Expected Behavior
The error prone Gradle plugin works and is able to set the Java toolchain.

### Current Behavior
The error prone Gradle plugin cannot be applied due to the above exception

### Your Environment
Gradle: 3.5-RC1

**Comment by wolfs** [comment]
Now that we detect the toolchain from fork options and do not allow to set the toolchain manually I see why the plugin fails.
Note that even fixing the possibility to set the toolchain I am pretty sure the plugin will fail afterwards since we changed then interface of JavaToolChain and JavaToolChainInternal, which are both not part of the public API.
@tbroyer If we re-add the possibility to set the Java tool chain manually on JavaCompile, would you adjust the plugin to implement the new types? It would still be somewhat brittle since it is possible that we change those internal interfaces again in the not so distant future.

**Comment by tbroyer** [comment]
> @tbroyer If we re-add the possibility to set the Java tool chain manually on JavaCompile, would you adjust the plugin to implement the new types?

Yeah sure!

> It would still be somewhat brittle since it is possible that we change those internal interfaces again in the not so distant future.

I always knew the plugin would be fragile until there's official support for plugging custom compilers, and I acknowledge it in the README; this is also why I use a v0.0.x versioning scheme.

That said, yesterday, I looked a bit closer to Gradle's internals and its registry and factory mechanisms, and I wondered if I couldn't possibly leverage the `PluginServiceRegistry` (another internal API…) to register a `Factory<JavaCompiler>` shadowing the `JavaHomeBasedJavaCompilerFactory` (it would have to be a _project service_ rather than _build session service_ though), or possibly a `JavaCompilerFactory` shadowing the `DefaultJavaCompilerFactory`. That wouldn't change the reliance on internal APIs (particularly the latter option), but would not require changing the `JavaCompile` task back to having a settable `JavaToolChain`.  
WDYT?

**Comment by wolfs** [comment]
@tbroyer We will make it possible to set `JavaToolChain` on the `JavaCompile` task as it was possible before. For providing a public API I think this will need some deeper thoughts. I opened an issue to track these: #1652. Could you please comment there?
Would you be willing to work on making a public API for Java tool chains and contribute it to Gradle?

**Comment by kageiit** [comment]
Alternatively Error Prone now can also be run as a java compiler plugin without relying on internal apis - https://github.com/google/error-prone/issues/535

Maybe this would be a better long term approacj

**Comment by tbroyer** [comment]
> Maybe this would be a better long term approacj

Not sure; `com.sun.source.util.Plugin` is specific to Oracle JDK and OpenJDK (i.e. I believe it's not available in IBM JDK for instance), so Gradle probably shouldn't rely on it.

Anyway, better discuss this in #1652

**Comment by kageiit** [comment]
error prone relies on open jdk to work already so I dont think IBM jdk makes any sense here.
The bootclasspath needs to be set to the javac from error prone based on openjdk9 for ep to even work

**Comment by tbroyer** [comment]
Oh sorry, you meant a better approach for the gradle-errorprone-plugin internal implementation.

Actually, Error Prone works great with the IBM JDK, as it brings its own OpenJDK: I could build the gradle-errorprone-plugin (which itself uses errorprone), including the tests, with the IBM JDK within Docker:
```
$ docker run --rm -it -v "$PWD:/myapp" -w /myapp ibmjava:8-sdk ./gradlew clean build -Ptest.gradle-versions=3.5-rc-2
Downloading https://services.gradle.org/distributions/gradle-3.5-rc-2-bin.zip
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /root/.gradle/wrapper/dists/gradle-3.5-rc-2-bin/7ktl4k9rdug30mawecgppf5ms/gradle-3.5-rc-2-bin.zip to /root/.gradle/wrapper/dists/gradle-3.5-rc-2-bin/7ktl4k9rdug30mawecgppf5ms
Set executable permissions for: /root/.gradle/wrapper/dists/gradle-3.5-rc-2-bin/7ktl4k9rdug30mawecgppf5ms/gradle-3.5-rc-2/bin/gradle
Starting a Gradle Daemon (subsequent builds will be faster)
Download https://plugins.gradle.org/m2/com/gradle/publish/plugin-publish-plugin/0.9.5/plugin-publish-plugin-0.9.5.pom
Download https://jitpack.io/com/github/tbroyer/gradle-errorprone-plugin/052a7aedb2/gradle-errorprone-plugin-052a7aedb2.pom
Download https://plugins.gradle.org/m2/gradle/plugin/com/github/sherter/google-java-format/google-java-format-gradle-plugin/0.6/google-java-format-gradle-plugin-0.6.pom
Download https://plugins.gradle.org/m2/org/apache/maven/maven-model/3.0.4/maven-model-3.0.4.pom
Download https://plugins.gradle.org/m2/org/apache/maven/maven/3.0.4/maven-3.0.4.pom
Download https://plugins.gradle.org/m2/org/apache/maven/maven-parent/21/maven-parent-21.pom
Download https://plugins.gradle.org/m2/org/apache/apache/10/apache-10.pom
Download https://plugins.gradle.org/m2/com/gradle/publish/plugin-publish-plugin/0.9.5/plugin-publish-plugin-0.9.5.jar
Download https://jitpack.io/com/github/tbroyer/gradle-errorprone-plugin/052a7aedb2/gradle-errorprone-plugin-052a7aedb2.jar
Download https://plugins.gradle.org/m2/gradle/plugin/com/github/sherter/google-java-format/google-java-format-gradle-plugin/0.6/google-java-format-gradle-plugin-0.6.jar
Download https://plugins.gradle.org/m2/org/apache/maven/maven-model/3.0.4/maven-model-3.0.4.jar
Generating JAR file 'gradle-api-3.5-rc-2.jar'
Generating JAR file 'gradle-test-kit-3.5-rc-2.jar'
:clean
:compileJava
Download https://jcenter.bintray.com/com/google/errorprone/error_prone_core/2.0.19/error_prone_core-2.0.19.pom
Download https://jcenter.bintray.com/com/google/errorprone/error_prone_parent/2.0.19/error_prone_parent-2.0.19.pom
Download https://jcenter.bintray.com/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
Download https://jcenter.bintray.com/com/google/errorprone/error_prone_annotation/2.0.19/error_prone_annotation-2.0.19.pom
Download https://jcenter.bintray.com/com/google/errorprone/error_prone_check_api/2.0.19/error_prone_check_api-2.0.19.pom
Download https://jcenter.bintray.com/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.pom
Download https://jcenter.bintray.com/org/pcollections/pcollections/2.1.2/pcollections-2.1.2.pom
Download https://jcenter.bintray.com/com/google/guava/guava/21.0/guava-21.0.pom
Download https://jcenter.bintray.com/com/google/guava/guava-parent/21.0/guava-parent-21.0.pom
Download https://jcenter.bintray.com/com/google/auto/auto-common/0.7/auto-common-0.7.pom
Download https://jcenter.bintray.com/com/google/auto/auto-parent/3/auto-parent-3.pom
Download https://jcenter.bintray.com/com/google/code/findbugs/jFormatString/3.0.0/jFormatString-3.0.0.pom
Download https://jcenter.bintray.com/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.pom
Download https://jcenter.bintray.com/org/checkerframework/dataflow/1.8.10/dataflow-1.8.10.pom
Download https://jcenter.bintray.com/com/google/errorprone/javac/9-dev-r3297-4/javac-9-dev-r3297-4.pom
Download https://jcenter.bintray.com/com/google/errorprone/error_prone_annotations/2.0.19/error_prone_annotations-2.0.19.pom
Download https://jcenter.bintray.com/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.pom
Download https://jcenter.bintray.com/org/checkerframework/javacutil/1.8.10/javacutil-1.8.10.pom
Download https://jcenter.bintray.com/com/google/errorprone/error_prone_core/2.0.19/error_prone_core-2.0.19.jar
Download https://jcenter.bintray.com/com/google/errorprone/error_prone_annotation/2.0.19/error_prone_annotation-2.0.19.jar
Download https://jcenter.bintray.com/com/google/errorprone/error_prone_check_api/2.0.19/error_prone_check_api-2.0.19.jar
Download https://jcenter.bintray.com/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.jar
Download https://jcenter.bintray.com/org/pcollections/pcollections/2.1.2/pcollections-2.1.2.jar
Download https://jcenter.bintray.com/com/google/guava/guava/21.0/guava-21.0.jar
Download https://jcenter.bintray.com/com/google/auto/auto-common/0.7/auto-common-0.7.jar
Download https://jcenter.bintray.com/com/google/code/findbugs/jFormatString/3.0.0/jFormatString-3.0.0.jar
Download https://jcenter.bintray.com/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar
Download https://jcenter.bintray.com/org/checkerframework/dataflow/1.8.10/dataflow-1.8.10.jar
Download https://jcenter.bintray.com/com/google/errorprone/javac/9-dev-r3297-4/javac-9-dev-r3297-4.jar
Download https://jcenter.bintray.com/com/google/errorprone/error_prone_annotations/2.0.19/error_prone_annotations-2.0.19.jar
Download https://jcenter.bintray.com/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.jar
Download https://jcenter.bintray.com/org/checkerframework/javacutil/1.8.10/javacutil-1.8.10.jar
:compileGroovy NO-SOURCE
:pluginDescriptors
:processResources
:classes
:jar
:groovydoc NO-SOURCE
:publishPluginGroovyDocsJar
:publishPluginJar
:javadoc
:publishPluginJavaDocsJar
:assemble
:pluginUnderTestMetadata
:compileTestJava NO-SOURCE
:compileTestGroovy
Download https://jcenter.bintray.com/com/netflix/nebula/nebula-test/4.0.0/nebula-test-4.0.0.pom
Download https://jcenter.bintray.com/org/spockframework/spock-core/1.0-groovy-2.4/spock-core-1.0-groovy-2.4.pom
Download https://jcenter.bintray.com/cglib/cglib-nodep/2.2.2/cglib-nodep-2.2.2.pom
Download https://jcenter.bintray.com/junit/junit/4.12/junit-4.12.pom
Download https://jcenter.bintray.com/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom
Download https://jcenter.bintray.com/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom
Download https://jcenter.bintray.com/com/netflix/nebula/nebula-test/4.0.0/nebula-test-4.0.0.jar
Download https://jcenter.bintray.com/org/spockframework/spock-core/1.0-groovy-2.4/spock-core-1.0-groovy-2.4.jar
Download https://jcenter.bintray.com/cglib/cglib-nodep/2.2.2/cglib-nodep-2.2.2.jar
Download https://jcenter.bintray.com/junit/junit/4.12/junit-4.12.jar
Download https://jcenter.bintray.com/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
:processTestResources
:testClasses
:test
:validateTaskProperties
:verifyGoogleJavaFormat
Download https://jcenter.bintray.com/com/google/googlejavaformat/google-java-format/1.3/google-java-format-1.3.pom
Download https://jcenter.bintray.com/com/google/googlejavaformat/google-java-format-parent/1.3/google-java-format-parent-1.3.pom
Download https://jcenter.bintray.com/com/google/guava/guava/19.0/guava-19.0.pom
Download https://jcenter.bintray.com/com/google/guava/guava-parent/19.0/guava-parent-19.0.pom
Download https://jcenter.bintray.com/com/google/errorprone/javac/9-dev-r3297-1-shaded/javac-9-dev-r3297-1-shaded.pom
Download https://jcenter.bintray.com/com/google/googlejavaformat/google-java-format/1.3/google-java-format-1.3.jar
Download https://jcenter.bintray.com/com/google/guava/guava/19.0/guava-19.0.jar
Download https://jcenter.bintray.com/com/google/errorprone/javac/9-dev-r3297-1-shaded/javac-9-dev-r3297-1-shaded.jar
Version 0.6 of google-java-format-gradle-plugin is not tested against version 1.3 of google-java-format. This should not be a problem if the task is executed without failures.
:check
:build

BUILD SUCCESSFUL

Total time: 3 mins 33.611 secs
```
