### ISSUE TITLE
ListProperty<RegularFile> cannot be fed with mapped Provider<>

### ISSUE THREAD

**Issue by jdochez** [gradle/gradle#16485]
I run into more issues related to ListProperty<>. 

take simple example like below : 
```
abstract class ProducerTask extends DefaultTask {
    @OutputDirectory
    abstract DirectoryProperty getOutput()

    @TaskAction
    def action() {
        def outputDir = getOutput().get().asFile
        new File(outputDir, "foo.txt").write("some text")
        new File(outputDir, "bar.txt").write("some other text")
    }
}

abstract class SomeTask extends DefaultTask {
    @InputFiles
    abstract ListProperty<RegularFile> getInputFiles()
    @TaskAction
    def action() {
        getInputFiles().get().each {
            println("action! on " + it)
        }
    }
}
def producerTask = tasks.register("producer", ProducerTask) {
    it.getOutput().set(
        layout.buildDir.dir("out"))
}


tasks.register("some", SomeTask) {
    Provider<Directory> mappedOutput = producerTask.map { it.getOutput() }
    it.getInputFiles().add(mappedOutput.map { it.file("foo.txt")})
}
```
build without configuration-cache : 
`gradlew --rerun-tasks --warning-mode all some --stacktrace --console plain`

when running the code without configuration-cache (or the first time with configuration-cache) produces the following error : 

```
Caused by: java.lang.IllegalArgumentException: Cannot get the value of a property of type java.util.List with element type org.gradle.api.file.RegularFile as the source value contains an element of type org.gradle.api.internal.provider.MappingProvider.
	at org.gradle.api.internal.provider.ValidatingValueCollector.add(ValidatingValueCollector.java:38)
	at org.gradle.api.internal.provider.Collectors$ElementFromProvider.collectEntries(Collectors.java:102)
	at org.gradle.api.internal.provider.AbstractCollectionProperty$CollectingSupplier.calculateValue(AbstractCollectionProperty.java:337)
	at org.gradle.api.internal.provider.AbstractCollectionProperty.finalValue(AbstractCollectionProperty.java:189)
	at org.gradle.api.internal.provider.AbstractCollectionProperty.finalValue(AbstractCollectionProperty.java:37)
	at org.gradle.api.internal.provider.AbstractProperty.finalizeNow(AbstractProperty.java:236)
```

now run it again (with configuration-cache) of course : 
`gradlew --configuration-cache --rerun-tasks --warning-mode all some --stacktrace --console plain`

will produce the expected results : 

```
Configuration cache is an incubating feature.
Reusing configuration cache.
> Task :producer

> Task :some
action! on fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedFile, /home/jedo/bugs/gradle/build/out/foo.txt)

BUILD SUCCESSFUL in 721ms
2 actionable tasks: 2 executed
Configuration cache entry reused.```

**Comment by eskatos** [comment]
Thanks for the report @jdochez 

This problem isn't new in 7.0, I can reproduce with both
* 7.0 nightly https://scans.gradle.com/s/2xadzjfjpssdk/failure#1
* 6.8 https://scans.gradle.com/s/qu7dcecukk57s/failure#1

**Comment by eskatos** [comment]
Changing from .map {} to .flatMap {} when mapping the task output fixes the issue with 7.0:

```groovy
tasks.register("some", SomeTask) {
    Provider<Directory> mappedOutput = producerTask.flatMap { it.getOutput() }
    it.getInputFiles().add(mappedOutput.map { it.file("foo.txt")})
}
```

**Comment by jdochez** [comment]
yes, I can use the flatmap but it does not really fix the issue, meaning it does not seem fine to fail the first time and succeed the second time :)

**Comment by eskatos** [comment]
Using flatmap does fix the issue described.

But you're right that it doesn't fix the configuration cache behavior which stores the CC entry if the build fails for a reason that is not a CC serialization issue. I extracted that problem in https://github.com/gradle/gradle/issues/16582
