### ISSUE TITLE
Non trivial error in case of collision between DSL extension and version catalog name

### ISSUE THREAD

**Issue by ducrohet** [gradle/gradle#16693]
Steps to reproduce:
- Create an Android Project
- add a version catalog called `android`.

This will make project configuration failed with 
```
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > java.lang.IllegalArgumentException: Cannot add extension with name 'android', as there is an extension already registered with that name.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'com.android.application']
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.exceptionOccurred(DefaultPluginRequestApplicator.java:207)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:189)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.lambda$applyPlugins$1(DefaultPluginRequestApplicator.java:127)
	...
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin 'com.android.internal.application'.
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:163)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:136)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:167)
	...
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Cannot add extension with name 'android', as there is an extension already registered with that name.
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:71)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:54)
	at com.android.build.gradle.internal.profile.AnalyticsResourceManager.recordBlockAtConfiguration(AnalyticsResourceManager.kt:207)
	...
Caused by: java.lang.IllegalArgumentException: Cannot add extension with name 'android', as there is an extension already registered with that name.
	at org.gradle.internal.extensibility.ExtensionsStorage.add(ExtensionsStorage.java:40)
	at org.gradle.internal.extensibility.DefaultConvention.add(DefaultConvention.java:120)
	at org.gradle.internal.extensibility.DefaultConvention.addWithDefaultPublicType(DefaultConvention.java:212)
	at org.gradle.internal.extensibility.DefaultConvention.create(DefaultConvention.java:126)
	at com.android.build.gradle.internal.plugins.AppPlugin.createExtension(AppPlugin.java:124)
	at com.android.build.gradle.internal.plugins.BasePlugin.configureExtension(BasePlugin.java:508)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:69)
	... 196 more
```

It is not going to be obvious to users where this collision comes from. It used to not be a problem because users generally don't create top level project extensions (only plugins do it and it's generally not an issue it seems). But now people will create them via catalogs and this could become a problem.

It would be nice if the error could indicate that the extension is coming from a version catalog and indicate that they (hopefully) can fix this by renaming the catalog, rather than trying to fix the code that throws the exception which in most cases is not owned by them.

**Comment by melix** [comment]
I'm not sure we can easily give more context here. If it was the other way around, the catalog extension created _after_ the Android one, it would be easier because we could capture the fact that an extension already exists before creating it. But here the Android extension is created _after_.

**Comment by ducrohet** [comment]
(By the way I filed this after someone filed a bug on our tracker because of this exact issue)

**Comment by orcchg** [comment]
> (By the way I filed this after someone filed a bug on our tracker because of this exact issue)

actually, here it is: https://issuetracker.google.com/issues/182571147
prior to version Gradle-7.0.0.-milestone-3 (for milestone-1 in particular) an error message was even more obscure. 
It was hard to figure out the reason, but when an update has come, an error message has become less misleading.

**Comment by melix** [comment]
It feels this should be fixed in a generic fashion in domain object collections. Although I'm a bit worried about keeping track of all origins there because there are many of those in Gradle.

**Comment by melix** [comment]
I'm removing the 7.0-rc2 milestone because there's nothing we can do easily for 7.0. It's actually nothing specific to version catalogs either: it's something which should be done in a more generic way.

**Comment by ducrohet** [comment]
Sounds good.
