### ISSUE TITLE
`DirectoryNotEmptyException` on Windows with file watching enabled

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#16786]
After updating to `7.0-rc-1`, Android Studio sync integration tests on Windows became flaky. About ~10% of the time they'd fail with
```
java.nio.file.DirectoryNotEmptyException: C:\botcode\w\_tmp\df9f16d66599773b6eb4ced6e9bf787c\unitTest_noMatchingDimensionInTarget_1qa9CDgGbF0tQFgajAkzhyt4PvA\1617306703177
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1180)
	at com.intellij.util.io.PathKt$doDelete$1.postVisitDirectory(path.kt:119)
	at com.intellij.util.io.PathKt$doDelete$1.postVisitDirectory(path.kt:108)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2817)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2871)
	at com.intellij.util.io.PathKt.doDelete(path.kt:108)
	at com.intellij.util.io.PathKt.delete(path.kt:88)
	at com.intellij.util.io.PathKt.delete$default(path.kt:86)
	at com.intellij.util.io.PathKt.delete(path.kt)
	at com.intellij.testFramework.UsefulTestCase.removeGlobalTempDirectory(UsefulTestCase.java:270)
	at com.intellij.testFramework.UsefulTestCase.lambda$tearDown$5(UsefulTestCase.java:289)
	at com.intellij.testFramework.RunAll.collectExceptions(RunAll.java:58)
	at com.intellij.testFramework.RunAll.run(RunAll.java:51)
	at com.intellij.testFramework.UsefulTestCase.tearDown(UsefulTestCase.java:294)
	at org.jetbrains.android.AndroidTestBase.tearDown(AndroidTestBase.java:106)
	at com.android.tools.idea.testing.AndroidGradleTestCase.tearDown(AndroidGradleTestCase.java:211)
```

After the sync test finishes directory which was temporarily created for the project should be deleted, but that'd fail with the exception above.

Environment: tests are running on Docker image `mcr.microsoft.com/windows/servercore:10.0.17763.1040`, using Gradle TAPI. Also, Gradle daemons are reused across tests.

I've added additional logging to print the content of the directory that fails to be deleted, but using `Files.walk()` prints no files inside the directory.

Disabling the file watching fixed the issue.

**Comment by hungvietnguyen** [comment]
FYI, this issue is usually fixed by retrying to delete the directory after a short time. Here are some examples: [Android Gradle plugin](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-master-dev:common/src/main/java/com/android/utils/PathUtils.java?q=%22DirectoryNotEmptyException%20exception%22), [Gradle](https://github.com/gradle/gradle/blob/3dc80197fdc09fbf36e909951bd95aac4b769bc3/subprojects/files/src/main/java/org/gradle/internal/file/impl/DefaultDeleter.java#L148), [Apache Flink](https://github.com/zentol/flink/blob/edbccbb5c28b83b469385d8683b6751810598246/flink-core/src/main/java/org/apache/flink/util/FileUtils.java#L179).

The stack trace above doesn't seem to have that retry logic.

That said, it's still unclear why file watching makes this issue more likely to appear.

**Comment by wolfs** [comment]
On Windows, having to delete twice is somewhat to be expected. Gradle watches project directories on Windows and Mac. On Windows, you can't delete a directory which is being watched. Gradle stops watching the directory when nothing is left to watch in the directory. So if you delete all the contents of a directory, then Gradle will stop watching it. It takes some time though for that to happen. Trying to delete the directory twice is an option which should work.

In Gradle's tests, we also try to delete the test directory a few times: https://github.com/gradle/gradle/blob/c0f43f2cea1c3eaf822020907520ee2d6a9fdbed/subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/file/AbstractTestDirectoryProvider.java#L71-L80

**Comment by wolfs** [comment]
So we ended up doing the following: When TestKit launches a build on Windows, then it will disable file system watching, while you still can enable file system watching manually. That should help plugin developers. For your use-case starting a build via the tooling API we suggest you either retry to delete the directory as you suggested or to disable file system watching on Windows as well.
