### ISSUE TITLE
Gradle fails the build by analyzing task outputs even in the case the task did not execute

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#16789]
### Expected Behavior

Gradle should not attempt to analyze task outputs in case the task was skipped.

### Current Behavior

Gradle 6 produces a warning, and Gradle 7 fails the build.

### Context

I guess https://github.com/gradle/gradle/issues/11100 is related, yet it is different.
I need the feature to skip checksum computation and signing of the custom-generated artifacts in case the task that produces the base archive was skipped manually (e.g. with `-x ...` on the command line)

### Steps to Reproduce 

Command line: `./gradlew computeSha --rerun-tasks -x buildZip --scan`

```kotlin
val buildZip by tasks.registering(Zip::class) {
    destinationDir = buildDir
    archiveBaseName.set("buildZip")
    from("build.gradle.kts")
}

val archiveFile = buildZip.flatMap { it.archiveFile }
val sha512File = archiveFile.map { File(it.asFile.absolutePath + ".sha512") }

val computeSha by tasks.registering {
    onlyIf {
      // alternative: buildZip.get().state.run { executed && !skipped }
      false
    }
    inputs.file(archiveFile)
    outputs.file(sha512File)
    doLast {
      println("buildZip.didWork ${buildZip.get().didWork}, buildZip.executed: ${buildZip.get().state.executed}; archiveFile: ${archiveFile.get()}; sha: ${sha512File.get()}")
    }
}
```

Exception:

```
* What went wrong:
Execution failed for task ':computeSha'.
> Querying the mapped value of flatmap(provider(task 'buildZip', class org.gradle.api.tasks.bundling.Zip)) before task ':buildZip' has completed is not supported

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':computeSha'.
        at org.gradle.api.internal.tasks.properties.DefaultTaskProperties.resolve(DefaultTaskProperties.java:74)
        at org.gradle.execution.plan.LocalTaskNode.resolveMutations(LocalTaskNode.java:202)
        at org.gradle.execution.plan.DefaultExecutionPlan.getResolvedMutationInfo(DefaultExecutionPlan.java:654)
        at org.gradle.execution.plan.DefaultExecutionPlan.selectNext(DefaultExecutionPlan.java:577)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$executeNextNode$1(DefaultPlanExecutor.java:166)
        at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:155)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.api.InvalidUserCodeException: Querying the mapped value of flatmap(provider(task 'buildZip', class org.gradle.api.tasks.bundling.Zip)) before task ':buildZip' has completed is not supported
        at org.gradle.api.internal.provider.TransformBackedProvider.lambda$beforeRead$0(TransformBackedProvider.java:84)
        at org.gradle.api.internal.provider.ValueSupplier$TaskProducer.visitContentProducerTasks(ValueSupplier.java:136)
        at org.gradle.api.internal.provider.TransformBackedProvider.beforeRead(TransformBackedProvider.java:81)
        at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:63)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.getOrNull(AbstractMinimalProvider.java:93)
        at org.gradle.api.internal.tasks.properties.FileParameterUtils.resolveOutputFilePropertySpecs(FileParameterUtils.java:115)
        at org.gradle.api.internal.tasks.properties.GetOutputFilesVisitor.visitOutputFileProperty(GetOutputFilesVisitor.java:44)
        at org.gradle.api.internal.tasks.properties.CompositePropertyVisitor.visitOutputFileProperty(CompositePropertyVisitor.java:64)
        at org.gradle.api.internal.tasks.DefaultTaskOutputs.visitRegisteredProperties(DefaultTaskOutputs.java:74)
        at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:46)
        at org.gradle.api.internal.tasks.properties.DefaultTaskProperties.resolve(DefaultTaskProperties.java:65)
        at org.gradle.execution.plan.LocalTaskNode.resolveMutations(LocalTaskNode.java:202)
        at org.gradle.execution.plan.DefaultExecutionPlan.getResolvedMutationInfo(DefaultExecutionPlan.java:654)
        at org.gradle.execution.plan.DefaultExecutionPlan.selectNext(DefaultExecutionPlan.java:577)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$executeNextNode$1(DefaultPlanExecutor.java:166)
        at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:155)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
```

### Your Environment
Build scan URL for 6.8.3: https://gradle.com/s/krrwxw2zdjbjq
Build scan URL for 7.0: https://gradle.com/s/dmkun7yj5mm6g

**Comment by ljacomet** [comment]
Build scan for 6.8.3 is not activated.

What would be the expected behavior with Gradle 7? `computeSha` should be skipped?

**Comment by vlsi** [comment]
`onlyIf { false }` => I assume the task should be skipped.

**Comment by vlsi** [comment]
The intention here is to write `computeSha` task in such a way so it gracefully handles the absence of the input file.

For instance, I can have several distributions (e.g. Windows, macOS, Linux), and I have a set of checksum tasks.
What I want is to run `./gradlew -x buildWindowsDist` so `checksumWindows` skips automatically based on `executed && !skipped` condition of the corresponding archive task.

**Comment by vlsi** [comment]
This is still relevant: it would be nice if there was a possibility to automatically skip tasks that depend on outputs of tasks disabled via -x
