### ISSUE TITLE
Gradle 7.0 Failing with shared Java Home Directory

### ISSUE THREAD

**Issue by jjathman** [gradle/gradle#16816]
### Expected Behavior
Gradle Daemon is able to launch successfully.

### Current Behavior
Gradle Daemon does not start and fails with the message `Supplied javaHome must be a valid directory. You supplied: /usr/lib/jvm/zulu8-ca-amd64`

Even if `--no-daemon` is passed in to the Gradle command, this exception is printed, though the build does not stop.

```
 Problem in daemon expiration check
 java.lang.IllegalArgumentException: Supplied javaHome must be a valid directory. You supplied: /usr/lib/jvm/zulu8-ca-amd64
 	at org.gradle.internal.jvm.Jvm.forHome(Jvm.java:115)
 	at org.gradle.launcher.daemon.context.DaemonCompatibilitySpec.javaHomeMatches(DaemonCompatibilitySpec.java:62)
 	at org.gradle.launcher.daemon.context.DaemonCompatibilitySpec.whyUnsatisfied(DaemonCompatibilitySpec.java:40)
 	at org.gradle.launcher.daemon.context.DaemonCompatibilitySpec.isSatisfiedBy(DaemonCompatibilitySpec.java:35)
 	at org.gradle.launcher.daemon.context.DaemonCompatibilitySpec.isSatisfiedBy(DaemonCompatibilitySpec.java:25)
 	at org.gradle.launcher.daemon.server.CompatibleDaemonExpirationStrategy$1.isSatisfiedBy(CompatibleDaemonExpirationStrategy.java:51)
 	at org.gradle.launcher.daemon.server.CompatibleDaemonExpirationStrategy$1.isSatisfiedBy(CompatibleDaemonExpirationStrategy.java:48)
 	at org.gradle.util.CollectionUtils.filter(CollectionUtils.java:154)
 	at org.gradle.util.CollectionUtils.filter(CollectionUtils.java:126)
 	at org.gradle.launcher.daemon.server.CompatibleDaemonExpirationStrategy.checkExpiration(CompatibleDaemonExpirationStrategy.java:54)
 	at org.gradle.launcher.daemon.server.expiry.AllDaemonExpirationStrategy.checkExpiration(AllDaemonExpirationStrategy.java:46)
 	at org.gradle.launcher.daemon.server.expiry.AnyDaemonExpirationStrategy.checkExpiration(AnyDaemonExpirationStrategy.java:43)
 	at org.gradle.launcher.daemon.server.MasterExpirationStrategy.checkExpiration(MasterExpirationStrategy.java:73)
 	at org.gradle.launcher.daemon.server.Daemon$DaemonExpirationPeriodicCheck.run(Daemon.java:268)
 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
 	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Context
We build many applications on Jenkins using Java images that are based off of the Azul Zulu OpenJDK images, specifically for Java 8 and 11. Each Docker container would only have either Java 8 or Java 11 installed, not both.

What appears to be happening with Gradle 7 is that when the build starts it attempts to check if an existing daemon can be used, in that check it appears to use the Java installation directory from a previous build to check if it matches what is requested. For example a previous build was using Java 8, so the javaHome will be set to `/usr/lib/jvm/zulu8-ca-amd64`. But this directory does not even exist in the currently executing docker container, it seems to cause an exception and the build fails immediately.

Previously, this worked as expected, the existing daemon could not be reused because it was run from within a different container and has since exited. 

I believe this issue would also happen for someone who only had Java 8 installed, ran Gradle 7. Uninstall Java 8, installed Java 11, and then tried to run Gradle again. 

### Steps to Reproduce 
Still working on a concise way to reproduce this. 

### Your Environment
Jenkins 2 using Docker containers for builds. Azul Java 8 and 11 containers. Gradle 7.0.

**Comment by EdGue42** [comment]
Same thing here, same problem: when "mixing" different "setups" on the same machine, gradle complains about that invalid javaHome. As in: inside our docker container, it should see a java in some /usr/... folder, but gradle tries to go for a /Users/... folder that is only valid on the host running the docker container.

We have a setup that allows users to either invoke gradlew directly, but they can also run our "old" build tool within a docker container, and that tool then invokes gradlew inside the docker container.

**Comment by bmuskalla** [comment]
@big-guy you recently reworked some of this, was this an intentional change? It seems some of those changes broke the "daemon expiration check" usecase

**Comment by big-guy** [comment]
I think I've reproduced this in a test. @jjathman would you be able to test a nightly once it's ready?

**Comment by jjathman** [comment]
I’ve never used a nightly before. Is it as easy as changing the distribution URL?

**Comment by ljacomet** [comment]
The fix will be in 7.0.1

**Comment by shoaniki** [comment]
I love it when I come to report a bug and find it's already been fixed, good job!

**Comment by rompic** [comment]
@big-guy 
Does the fix also take relative paths into account? e.g. we start
gradlew with
-Dorg.gradle.java.home=path/to/jdk/
in folder a.
and later in folder b.
but it complains that a/path/to/jdk/ does not exist anymore.

**Comment by rompic** [comment]
@big-guy any update? shall i create a new issue?

**Comment by kashyap-bhatt-by** [comment]
If anyone wants a work around, this worked for me:
```
$ echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
$ ./gradlew clean build
$ sed -i "s/org.gradle.daemon=false/# org.gradle.daemon=false/" ~/.gradle/gradle.properties
$ ./gradlew clean build
```

Before setting that option in `gradle.properties` I also killed all the existing daemons (`./gradlew  --status` to list them). But $ `./gradlew clean build` continued to failed until I added that option to disable daemon mode in config file.

**Comment by hpr1999** [comment]
I have recently experienced a very similar error. This was tested on gradle 7.5.1.

> The supplied javaHome seems to be invalid. I cannot find the java executable. Tried location `<path of recently uninstalled jvm>`

If I read the commit in https://github.com/gradle/gradle/commit/0355a386caa46d17763835d73a4ae103b68506d8 correctly, you are simply checking, whether the old `JAVA_HOME` folder still exists.

My error occured on a Windows machine and after uninstalling, the folder was not completely removed. Instead, there remained an empty folder of the same name, so the check from above commit did not work and gradle failed a while after, when trying to get the `java` executable from this installation.

**Comment by GCSBOSS** [comment]
Having this issue. No JAVA_HOME is set whatsoever. Not sure where Gradle is getting the directory from.

**Comment by atennapel** [comment]
I also ran in to this issue like @hpr1999 mentioned. An empty JDK directory was left behind after updating. Gradle still tries to use this directory even though I set the `JAVA_HOME` environment variable to the correct JDK directory.
