### ISSUE TITLE
StackOverflowError while importing project into Android Studio

### ISSUE THREAD

**Issue by baramisko** [gradle/gradle#16851]
### Expected Behavior
Project import into Android Studio should not crash

### Current Behavior
Project import occasionally crashes with `java.lang.StackOverflowError`. Here is the stacktrace:

```
FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify build listener.
> java.lang.StackOverflowError (no error message)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.internal.event.ListenerNotificationException: Failed to notify build listener.
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:89)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:346)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:249)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:141)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy20.projectsEvaluated(Unknown Source)
	at org.gradle.initialization.ProjectsEvaluatedNotifier$NotifyProjectsEvaluatedListeners.run(ProjectsEvaluatedNotifier.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:71)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:71)
	at org.gradle.initialization.ProjectsEvaluatedNotifier.notify(ProjectsEvaluatedNotifier.java:35)
	at org.gradle.configuration.DefaultProjectsPreparer.prepareProjects(DefaultProjectsPreparer.java:47)
	at org.gradle.configuration.BuildTreePreparingProjectsPreparer.prepareProjects(BuildTreePreparingProjectsPreparer.java:57)
	at org.gradle.configuration.BuildOperationFiringProjectsPreparer$ConfigureBuild.run(BuildOperationFiringProjectsPreparer.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:71)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:71)
	at org.gradle.configuration.BuildOperationFiringProjectsPreparer.prepareProjects(BuildOperationFiringProjectsPreparer.java:40)
	at org.gradle.initialization.DefaultGradleLauncher.prepareProjects(DefaultGradleLauncher.java:228)
	at org.gradle.initialization.DefaultGradleLauncher.doClassicBuildStages(DefaultGradleLauncher.java:165)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
	at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:126)
	at org.gradle.internal.invocation.GradleBuildController$1.create(GradleBuildController.java:72)
	at org.gradle.internal.invocation.GradleBuildController$1.create(GradleBuildController.java:67)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:178)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:67)
	at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:56)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedPhasedActionRunner.run(ClientProvidedPhasedActionRunner.java:60)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:63)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run(FileSystemWatchingBuildActionRunner.java:67)
	at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:41)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:49)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:44)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:44)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.lambda$execute$0(InProcessBuildActionExecuter.java:54)
	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:87)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:53)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:29)
	at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.lambda$execute$0(BuildTreeScopeLifecycleBuildActionExecuter.java:33)
	at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:49)
	at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.execute(BuildTreeScopeLifecycleBuildActionExecuter.java:32)
	at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.execute(BuildTreeScopeLifecycleBuildActionExecuter.java:27)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:104)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:55)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:64)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:37)
	at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.lambda$execute$0(SessionScopeLifecycleBuildActionExecuter.java:54)
	at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:67)
	at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.execute(SessionScopeLifecycleBuildActionExecuter.java:50)
	at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.execute(SessionScopeLifecycleBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:41)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.StackOverflowError
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2053)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3851)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3875)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4800)
	at org.gradle.api.internal.plugins.DefaultPluginRegistry.uncheckedGet(DefaultPluginRegistry.java:151)
	at org.gradle.api.internal.plugins.DefaultPluginRegistry.maybeInspect(DefaultPluginRegistry.java:102)
	at org.gradle.api.internal.plugins.DefaultPluginRegistry.maybeInspect(DefaultPluginRegistry.java:95)
	at org.gradle.api.internal.plugins.DefaultPluginRegistry.maybeInspect(DefaultPluginRegistry.java:95)
	at org.gradle.api.internal.plugins.DefaultPluginRegistry.maybeInspect(DefaultPluginRegistry.java:95)
	at org.gradle.api.internal.plugins.DefaultPluginRegistry.maybeInspect(DefaultPluginRegistry.java:95)
	at org.gradle.api.internal.plugins.DefaultPluginRegistry.inspect(DefaultPluginRegistry.java:110)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:141)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:82)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
	at org.gradle.plugins.ide.internal.tooling.IdeaModelBuilder.applyIdeaPlugin(IdeaModelBuilder.java:86)
```

### Context
I'm using Android Studio, Gradle Plugin, composite builds and sometimes build crashes with StackOverflowError. 

### Steps to Reproduce 
It happens randomly so I'm not able to provide test case

### Your Environment

Build scan URL: I'm not able to provide build scan as it crashes before generating it.
But my environment is
Studio Build:
Android Studio 4.2 RC 1
Build #AI-202.7660.26.42.7231092, built on March 24, 2021
Runtime version: 11.0.8+0-b944-P17168821 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Linux 4.15.0-136-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.thoughtworks.gauge, org.jetbrains.kotlin, org.intellij.plugins.markdown
Current Desktop: GNOME

Version of Gradle Plugin: 4.2.0-rc01
Version of Gradle: 6.7.1
Version of Java: 11
OS: Ubuntu Linux

**Comment by bmuskalla** [comment]
Thanks for the report @baramisko 

I assume you're not able to share the original project with us. But would you be able to share the structure of the build (projects, subprojects, included builds, ..).

**Comment by bmuskalla** [comment]
I believe this has been fixed with https://github.com/gradle/gradle/commit/04a24415108bc5e002f4ef0003ec66cc6de0a792 (part of 6.8). Please let us know if you can reproduce this with a newer version.
