### ISSUE TITLE
Exception in thread "main" java.io.FileNotFoundException: https://downloads.gradle-dn.com/distributions/gradle-7.0.0-bin.zip

### ISSUE THREAD

**Issue by tribbloid** [gradle/gradle#16871]
When upgrading gradle 6.8.3 into 7.0.0. gradlew encounter the following error:

```
Downloading https://services.gradle.org/distributions/gradle-7.0.0-bin.zip

Exception in thread "main" java.io.FileNotFoundException: https://downloads.gradle-dn.com/distributions/gradle-7.0.0-bin.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1896)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:87)
	at org.gradle.wrapper.Download.download(Download.java:67)
	at org.gradle.wrapper.Install$1.call(Install.java:68)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Downloading https://services.gradle.org/distributions/gradle-7.0.0-bin.zip
```

### Expected Behavior
Should download gradle

### Current Behavior
not downloading

### Context
java 8, fedora 33

**Comment by melix** [comment]
Hi,

The version number for the 7 release is `7.0`, not `7.0.0`. May I ask how you upgraded?

**Comment by tribbloid** [comment]
sorry you are right. The version pattern has changed.

No longer a problem, case should be close
