### ISSUE TITLE
Unable to use project dependency accessors if a project has spaces in its name

### ISSUE THREAD

**Issue by LouisCAD** [gradle/gradle#16942]
### Expected Behavior
Project dependency accessor is generated with backticks so spaces are supported, just like in other parts of Gradle:

Project with name "Stuff Some Name" leads to \`Stuff Some Name\` generated as its accessor symbol.

### Current Behavior
Failure:
```stacktrace
Caused by: org.gradle.api.InvalidUserDataException: Cannot generate project dependency accessors:
  - Cannot generate project dependency accessors because project 'Stuff Some Name' doesn't follow the naming convention: [a-zA-Z]([A-Za-z0-9\-_])*
	at org.gradle.api.internal.catalog.DefaultDependenciesAccessors.assertCanGenerateAccessors(DefaultDependenciesAccessors.java:191)
	at org.gradle.api.internal.catalog.DefaultDependenciesAccessors.writeProjectAccessors(DefaultDependenciesAccessors.java:145)
	at org.gradle.api.internal.catalog.DefaultDependenciesAccessors.generateAccessors(DefaultDependenciesAccessors.java:133)
	```

**Comment by grndvl1** [comment]
Getting the same issue here ... seems no other solution but to rip out the project.

**Comment by TWiStErRob** [comment]
See also (for SEO) https://github.com/gradle/gradle/issues/18971
