### ISSUE TITLE
Allow plugin authors to customize the reason configuration can't be consumed/resolved

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#17221]
### Expected Behavior

There should be a way to provide human-friendly explanations why a specific configuration can't be resolved.
The core configurations should provide meaningful explanations.

For instance:

>testImplementation is intended for dependency declaration only, and it is just a subset of the test classpath. If you need to query test classpath, then you might better try resolving testCompileClasspath or testRuntimeClasspath configurations

For instance:

```kotlin
val testImplementation by configurations.creating {
    nonResolvableReason = "$name is intended for dependency declaration only, " +
        "and it is just a subset of the test classpath. If you need to query test classpath, " +
        "then you might better try resolving testCompileClasspath or testRuntimeClasspath configurations"
    ...
}
```

### Current Behavior

Unfortunately, `canBeResolved` and `canBeResolved` are just boolean fields, so Gradle can't really come up with an actionable [help](https://twitter.com/CedricChampeau/status/1092753316134748160) [message](https://twitter.com/CedricChampeau/status/1385489671669571586).

```
Caused by: java.lang.IllegalStateException: Resolving dependency configuration 'testImplementation' is 
ot allowed as it is defined as 'canBeResolved=false'.
Instead, a resolvable ('canBeResolved=true') dependency configuration that 
xtends 'testImplementation' should be resolved.
```

**Comment by osyanin** [comment]
```
Caused by: java.lang.IllegalStateException: Resolving dependency configuration 'testImplementation' is not allowed as it is defined as 'canBeResolved=false'.
Instead, a resolvable ('canBeResolved=true') dependency configuration that extends 'testImplementation' should be resolved.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.assertIsResolvable(DefaultConfiguration.java:1425)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.visitDependencies(DefaultConfiguration.java:869)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:114)
        at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmptyEdges.getNodeValues(CachingDirectedGraphWalker.java:213)
        at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:121)
        at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:73)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:69)
        ... 113 more

```

**Comment by vlsi** [comment]
This is still relevant

**Comment by ov7a** [comment]
Sorry for the late reply.

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

One thing that Gradle can do is to list the configurations that extend the configuration in question and are marked as resolvable.

**Comment by big-guy** [comment]
Given the direction we're going with the introduction of the type-specific configurations, we don't think we need to add this kind of API.  The description of the configuration should describe what it's purpose is and the type of the configuration describes what it can do.

WRT the extendsFrom relationship, I think we'll deprecate and forbid resolving configurations that are not dependency scopes.
