### ISSUE TITLE
Exception in version 7.0.28: os.logback.classic.Logger cannot be cast to org.gradle.api.logging.Logger

### ISSUE THREAD

**Issue by leolux** [gradle/gradle#17438]
I have downloaded a fresh version of Gradle on my Windows 10 PC from https://gradle.org/next-steps/?version=7.0.2&format=all.

Running the command "gradle -v" in CMD results in this error message:

```
* Exception is:
java.lang.ClassCastException: ch.qos.logback.classic.Logger cannot be cast to org.gradle.api.logging.Logger
        at org.gradle.api.logging.Logging.getLogger(Logging.java:39)
        at org.gradle.launcher.cli.DebugLoggerWarningAction.<init>(DebugLoggerWarningAction.java:57)
        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:235)
        at org.gradle.launcher.Main.doAction(Main.java:35)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
```

Has anybody faced this issue already?

**Comment by ljacomet** [comment]
This is the first time I see a report like this.
Did you try in an existing Gradle project?
What happens in a non Gradle project?

**Comment by leolux** [comment]
I have only setup Gradle iteslef, no wrapper no project.. 
This means I have only unzipped the files and added the path to the bin-driectory into the Windows system PATH.

Would you expect the command "gradle -v" to work after this setup?

**Comment by ljacomet** [comment]
Yes it should.
Could you share the output of `java --version`?

**Comment by ljacomet** [comment]
Closing as not reproducible
