### ISSUE TITLE
Gradle's up-to-date checks do not work on Windows FAT drives

### ISSUE THREAD

**Issue by DimaCrafter** [gradle/gradle#17551]
### Expected Behavior
Gradle should produce new class files to `build/classes/java` directory.

### Current Behavior
1. `gradle build` creates `.gradle` and `build` directories;
2. I change output string in main class;
3. Second build only just removes previously compiled files.

### Context

I created new Java project with Gradle in IntelliJ IDEA and it not works.
Same project can be successfully compiled on macOS.

### Steps to Reproduce
https://github.com/DimaCrafter/clean-gradle-project

### Your Environment
* OS: Windows 10 Pro 21H1 19043.1081
* Java 8: AdoptOpenJDK 1.8.0_292-b10
* Gradle wrapper v7.1 (building with globally installed Gradle doesn't affect)

**Comment by mlopatkin** [comment]
Unfortunately I'm unable to reproduce the issue. Could you please provide debug logs from the first and second compilations?
You can capture the logs with `gradle build --debug > build.log` where `build.log` is the name of the file to store the log at. The logs may contain sensitive information (though it should be limited to paths and network interfaces for the reproducer project) so you can email the logs to mlopatkin[at]gradle.com.

**Comment by DimaCrafter** [comment]
I checked the logs and found no sensitive information. I think I can publish logs for the community.

- [first-build.log](https://github.com/gradle/gradle/files/6741416/first-build.log)
- [second-build.log](https://github.com/gradle/gradle/files/6741417/second-build.log)

**Comment by mlopatkin** [comment]
Thanks for the logs. The activity in the second log is suspicious:
compileJava is considered up-to-date:
```
2021-06-30T17:39:58.906+0400 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :compileJava UP-TO-DATE
```

but "stale outputs" are still cleaned up:
```
2021-06-30T17:39:58.908+0400 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Clean stale outputs' started
```

And output directories are deleted
```
2021-06-30T17:39:58.908+0400 [INFO] [org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter] Deleting stale output file: D:\Projects\Java\clean-gradle-project\build\generated\sources\headers\java\main
2021-06-30T17:39:58.908+0400 [DEBUG] [org.gradle.internal.file.impl.DefaultDeleter] Deleting D:\Projects\Java\clean-gradle-project\build\generated\sources\headers\java\main
2021-06-30T17:39:58.909+0400 [INFO] [org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter] Deleting stale output file: D:\Projects\Java\clean-gradle-project\build\tmp\compileJava\previous-compilation-data.bin
2021-06-30T17:39:58.909+0400 [DEBUG] [org.gradle.internal.file.impl.DefaultDeleter] Deleting D:\Projects\Java\clean-gradle-project\build\tmp\compileJava\previous-compilation-data.bin
2021-06-30T17:39:58.909+0400 [INFO] [org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter] Deleting stale output file: D:\Projects\Java\clean-gradle-project\build\generated\sources\annotationProcessor\java\main
2021-06-30T17:39:58.909+0400 [DEBUG] [org.gradle.internal.file.impl.DefaultDeleter] Deleting D:\Projects\Java\clean-gradle-project\build\generated\sources\annotationProcessor\java\main
2021-06-30T17:39:58.911+0400 [INFO] [org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter] Deleting stale output file: D:\Projects\Java\clean-gradle-project\build\classes\java\main
2021-06-30T17:39:58.911+0400 [DEBUG] [org.gradle.internal.file.impl.DefaultDeleter] Deleting D:\Projects\Java\clean-gradle-project\build\classes\java\main
```

The compilation doesn't happen afterwards:
```
2021-06-30T17:39:58.939+0400 [DEBUG] [org.gradle.internal.execution.steps.SkipUpToDateStep] Determining if task ':compileJava' is up-to-date
2021-06-30T17:39:58.940+0400 [INFO] [org.gradle.internal.execution.steps.SkipUpToDateStep] Skipping task ':compileJava' as it is up-to-date.
```

**Comment by mlopatkin** [comment]
@gradle/execution could you please take a look at this?

**Comment by ljacomet** [comment]
@DimaCrafter Can you share what type of filesystem `D:` is?

Asking as we have reports of Gradle not working well on FAT.

**Comment by DimaCrafter** [comment]
My `D:` drive is exFAT formatted.

**Comment by wolfs** [comment]
@DimaCrafter Can you try out if the build works if you disable file system watching? Aka if you run both builds with `--no-watch-fs`?

**Comment by DimaCrafter** [comment]
@wolfs Still same behaviour.

**Comment by wolfs** [comment]
@DimaCrafter When you first ran the project, did it already contain a non-empty build directory? Can you try if you can reproduce the problem
- on a clean checkout,
- without file system watching (`--no-watch-fs`),
- and a fresh daemon (run `./gradlew --stop` before the first build)?

Please capture the debug logs for those runs as well.

**Comment by DimaCrafter** [comment]
1. Removed `.gradle` and `build` directories
2. `gradlew --stop`
3. `gradlew --no-watch-fs build --debug > first-build.log`
4. Checked `build/classes/java`, exists and contents are correct.
5. Changed output string in main class
6. `gradlew --stop`
7. `gradlew --no-watch-fs build --debug > second-build.log`
8. Now `build/classes/java` is empty

- [first-build.log](https://github.com/gradle/gradle/files/6792353/first-build.log)
- [second-build.log](https://github.com/gradle/gradle/files/6792354/second-build.log)

**Comment by wolfs** [comment]
I was able to reproduce the problem. It seems like the stat from native platform does not work on exfat and always throws an exception - causing the stat to return missing file: https://github.com/gradle/gradle/blob/30cab53062b32ad61d48031c4faec6756bd115da/subprojects/native/src/main/java/org/gradle/internal/nativeintegration/filesystem/services/NativePlatformBackedFileMetadataAccessor.java#L39-L43

This is why we don't detect the outputs. In Gradle 6.5 we switched to using the native stat implementation for Windows, so the issue exists since then.

**Comment by wolfs** [comment]
@DimaCrafter Can you try out if `7.2-20210719134544+0000` fixes your problems?

**Comment by DimaCrafter** [comment]
Now it creates a new class after second build, but all builds prints this error:

```
2021-07-19T21:31:44.159+0400 [ERROR] [org.gradle.internal.watch.registry.impl.DefaultFileWatcherRegistry] Error while receiving file changes
net.rubygrapefruit.platform.NativeException: Error received when handling events, error = 1: D:\Projects\Java\clean-gradle-project
        at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$NativeFileWatcher.executeRunLoop0(Native Method)
        at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$NativeFileWatcher.access$100(AbstractFileEventFunctions.java:157)
        at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$NativeFileWatcher$1.run(AbstractFileEventFunctions.java:171)
2021-07-19T21:31:44.159+0400 [ERROR] [org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem] Stopping file watching and invalidating VFS after an error happened
```

[Full log of first build](https://github.com/gradle/gradle/files/6842877/build.log)

**Comment by wolfs** [comment]
If you run with `--no-watch-fs` everything works fine?

**Comment by wolfs** [comment]
@DimaCrafter Can you try out the nightly `7.2-20210720234250+0000`? This one now disables file system watching on FAT automatically, so you shouldn't have the above warning.

**Comment by DimaCrafter** [comment]
Same error with same log's contents, but works fine with `--no-watch-fs`.
