### ISSUE TITLE
Gradle sometimes deadlocks at the start of task execution

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#17812]
### Expected Behavior

Gradle should either detect & fail or avoid the deadlock situation.

### Current Behavior

Gradle deadlocks at the start of task execution.

### Context

This was raised in the context of a Kotlin/Android build, but I think something similar could happen with any task behaving this way.

Periodically, builds just hang and never fail or seem to get started (execution is at 0%). 

We see a stacktrace like this in the daemon:

```
	at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:51)
	locked <0x000000070295bd90> (a java.lang.Object)
	at org.gradle.internal.work.DefaultWorkerLeaseService$2.run(DefaultWorkerLeaseService.java:228)
	at org.gradle.internal.work.DefaultWorkerLeaseService$ProjectLockStatisticsImpl.measure(DefaultWorkerLeaseService.java:492)
	at org.gradle.internal.work.DefaultWorkerLeaseService.acquireLocks(DefaultWorkerLeaseService.java:225)
	at org.gradle.internal.work.DefaultWorkerLeaseService.releaseWorkerLeaseAndWaitFor(DefaultWorkerLeaseService.java:300)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withoutLocks(DefaultWorkerLeaseService.java:287)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.fromMutableState(DefaultProjectStateRegistry.java:318)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:595)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:573)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
	at org.jetbrains.kotlin.gradle.tasks.JarSearchingUtilKt.findKotlinModuleDependency(jarSearchingUtil.kt:159)
	at org.jetbrains.kotlin.gradle.tasks.JarSearchingUtilKt.findPotentialModuleJars(jarSearchingUtil.kt:143)
	at org.jetbrains.kotlin.gradle.tasks.JarSearchingUtilKt.access$findPotentialModuleJars(jarSearchingUtil.kt:1)
	at org.jetbrains.kotlin.gradle.tasks.JarSearchingUtilKt$findKotlinModuleJar$$inlined$Sequence$1.iterator(Sequences.kt:681)
	at kotlin.sequences.SequencesKt__SequencesKt$flatten$1.invoke(Sequences.kt:82)
	at kotlin.sequences.SequencesKt__SequencesKt$flatten$1.invoke(Sequences.kt)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at org.jetbrains.kotlin.gradle.tasks.JarSearchingUtilKt.findKotlinModuleJar(jarSearchingUtil.kt:177)
	at org.jetbrains.kotlin.gradle.tasks.JarSearchingUtilKt.findKotlinStdlibClasspath(jarSearchingUtil.kt:99)
	at org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask.<init>(KaptWithoutKotlincTask.kt:82)
	at org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask_Decorated.<init>(Unknown Source)
```

Other task execution threads are blocked:

```
	at org.gradle.internal.cleanup.DefaultBuildOutputCleanupRegistry.doResolvePaths(DefaultBuildOutputCleanupRegistry.java:72)
	waiting to lock <0x0000000708a61b10> (a org.gradle.internal.cleanup.DefaultBuildOutputCleanupRegistry)
	at org.gradle.internal.cleanup.DefaultBuildOutputCleanupRegistry.getResolvedPaths(DefaultBuildOutputCleanupRegistry.java:66)
	at org.gradle.internal.cleanup.DefaultBuildOutputCleanupRegistry.isOutputOwnedByBuild(DefaultBuildOutputCleanupRegistry.java:48)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:79)
```

This appears to be caused by a task resolving configurations in its constructor and that task being created as part of resolving stale output file paths.

### Steps to Reproduce 

I think something like this is happening...
1. `:a:task` is about to execute. It holds a lock on project `:a`.
2. `:b:task` is also about to execute. It holds a lock on project `:b`.
3. Before executing a task, we need to check for stale output with DefaultBuildOutputCleanupRegistry and this needs to be initialized.
4. The execution thread for `:a:task` locks DefaultBuildOutputCleanupRegistry.
5. The execution thread for `:b:task` waits for the lock on DefaultBuildOutputCleanupRegistry.
6. To resolve the outputs in DefaultBuildOutputCleanupRegistry, we end up creating a KaptWithoutKotlincTask task which does some dependency resolution.
7. To resolve dependencies, Gradle needs to look into `:b`. This requires a project lock on `:b`.

So `:a:task` is blocked on a lock for project `:b` and the lock for project `:b` is held by `:b:task` which is blocked waiting for a lock on DefaultBuildOutputCleanupRegistry.

This probably happens repeatedly because the DefaultBuildOutputCleanupRegistry needs to be resolved at the start of execution every time.

As a workaround, it looks like if all `KaptWithoutKotlincTask` tasks are created during the configuration phase, the deadlock does not occur.

When a build is successful, it produces a deprecation warning:
> Resolution of the configuration `:a:myconf` was attempted from a context different than the project context. Have a look at the documentation to understand why this is a problem and how it can be resolved. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. 

I think this is related to https://github.com/gradle/gradle/issues/16405 and https://github.com/gradle/gradle/issues/17013

Reproducer is here: https://github.com/gradle/gradle/commit/a69845d55022581730af1e19b7c87a89a0018c38

This doesn't always produce a deprecation warning, but it always seems to deadlock for me.

**Comment by big-guy** [comment]
I've reproduced this on master, but I assume it goes back several versions.

**Comment by ZacSweers** [comment]
Filed the KGP issue for kapt here https://youtrack.jetbrains.com/issue/KT-47853
