### ISSUE TITLE
Gradle cannot find `JAVA_HOME/jre/lib/security/cacerts`

### ISSUE THREAD

**Issue by jpountz** [gradle/gradle#1782]
I got the below exception with Gradle 3.3:

```
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: org.apache.http.ssl.SSLInitializationException: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-10.b14.fc25.x86_64/jre/lib/security/cacerts (No such file or directory)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at org.gradle.internal.resource.transport.http.DefaultSslContextFactory.createSslContext(DefaultSslContextFactory.java:57)
	at org.gradle.internal.resource.transport.http.HttpClientConfigurer.configureSslSocketConnectionFactory(HttpClientConfigurer.java:78)
	at org.gradle.internal.resource.transport.http.HttpClientConfigurer.configure(HttpClientConfigurer.java:69)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.getClient(HttpClientHelper.java:134)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:113)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.executeGetOrHead(HttpClientHelper.java:89)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performRequest(HttpClientHelper.java:80)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performRawGet(HttpClientHelper.java:66)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performGet(HttpClientHelper.java:70)
	at org.gradle.internal.resource.transport.http.HttpResourceAccessor.openResource(HttpResourceAccessor.java:43)
	at org.gradle.internal.resource.transport.http.HttpResourceAccessor.openResource(HttpResourceAccessor.java:29)
	at org.gradle.internal.resource.transfer.DefaultExternalResourceConnector.openResource(DefaultExternalResourceConnector.java:56)
	at org.gradle.internal.resource.transfer.ProgressLoggingExternalResourceAccessor.openResource(ProgressLoggingExternalResourceAccessor.java:36)
	at org.gradle.internal.resource.transport.DefaultExternalResourceRepository.getResource(DefaultExternalResourceRepository.java:63)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.getResource(DefaultCacheAwareExternalResourceAccessor.java:76)
	at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.downloadStaticResource(DefaultExternalResourceArtifactResolver.java:97)
	... 134 more
Caused by: org.apache.http.ssl.SSLInitializationException: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-10.b14.fc25.x86_64/jre/lib/security/cacerts (No such file or directory)
	at org.gradle.internal.resource.transport.http.DefaultSslContextFactory$SslContextCacheLoader.load(DefaultSslContextFactory.java:177)
	at org.gradle.internal.resource.transport.http.DefaultSslContextFactory$SslContextCacheLoader.load(DefaultSslContextFactory.java:69)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 154 more
Caused by: java.io.FileNotFoundException: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-10.b14.fc25.x86_64/jre/lib/security/cacerts (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.gradle.internal.resource.transport.http.DefaultSslContextFactory$SslContextCacheLoader.load(DefaultSslContextFactory.java:120)
```

This seems to be due to the fact that the Fedora OpenJDK package [no longer creates that symlink](http://pkgs.fedoraproject.org/cgit/rpms/java-1.8.0-openjdk.git/commit/?id=4821c37ebebfb8c8d5837258b968356dfe689d25) since the JDK [checks the system cacerts dadabase first](http://pkgs.fedoraproject.org/cgit/rpms/java-1.8.0-openjdk.git/tree/pr2888.patch?id=4821c37ebebfb8c8d5837258b968356dfe689d25). A full log is available at https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-intake/983/consoleFull.

**Comment by vbraun** [comment]
I've opened https://bugzilla.redhat.com/show_bug.cgi?id=1448802

**Comment by judovana** [comment]
Please try to fix this in gradle. I dont have intentions to return the symlink to JDK packages  unless really necessary. GnuAndrew was right - nothing should (any longer) depend on jdk internals. This was good bad habbit, but the times are over.

**Comment by craigotis** [comment]
Leaving here a temporary workaround for Fedora 25, which involves *downgrading to a less-secure version of the JDK*. If you're just on a development machine like me, it's probably worth the risk, as otherwise I can't really get anything done.

`dnf` still lists JDK 1.8.0-111-1.b16 as available, which you can confirm with:
```
[craig@localhost java]$ dnf --showduplicates list java-1.8.0-openjdk
Last metadata expiration check: 1:06:01 ago on Thu May 11 07:49:04 2017.
Installed Packages
java-1.8.0-openjdk.x86_64                                                         1:1.8.0.131-1.b12.fc25                                                         @updates
Available Packages
java-1.8.0-openjdk.i686                                                           1:1.8.0.111-1.b16.fc25                                                         fedora  
java-1.8.0-openjdk.x86_64                                                         1:1.8.0.111-1.b16.fc25                                                         fedora  
java-1.8.0-openjdk.i686                                                           1:1.8.0.131-1.b12.fc25                                                         updates 
java-1.8.0-openjdk.x86_64                                                         1:1.8.0.131-1.b12.fc25                                                         @updates
java-1.8.0-openjdk.x86_64                                                         1:1.8.0.131-1.b12.fc25                                                         updates 
```
To downgrade, use:
```
sudo dnf install java-1.8.0-openjdk-1:1.8.0.111-1.b16.fc25 --allowerasing
```
You should now see:
```
[craig@localhost java]$ java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b16)
OpenJDK 64-Bit Server VM (build 25.111-b16, mixed mode)
```
And Gradle should again be functional, without whatever improvements happened between 111-1 and 131-1.

**Comment by judovana** [comment]
Then maybe "dnf downgrade java-..." is bettter?

But *best* (but still workaround)  is to recreate missing symlink?

**Comment by craigotis** [comment]
What should the manual creation of that symlink look like? I see (somewhat watered-down by me)...
```
pushd $RPM_BUILD_ROOT%{_jvmdir}/%{jredir $suffix}/lib/security
RELATIVE=$(%{abs2rel} %{_sysconfdir}/pki/java %{_jvmdir}/%{jredir $suffix}/lib/security)
ln -sf $RELATIVE/cacerts .
```
But I'm still putting the pieces together to have a nice one-liner.

**Comment by judovana** [comment]
You are on good trace. no need to make it relative wen it is workaroudn, so feel free to:
ln -s %{_sysconfdir}/pki/java/cacerts  %{_jvmdir}/%{jredir $suffix}/lib/security 
which resolves to : 
ln -s  /etc/pki/java/cacerts  /usr/lib/jvm/desired:java/jre/lib/security

**Comment by craigotis** [comment]
And actually, by just installing the Sun/Oracle JDK (1.8.0.131) from their website as opposed to going through the Fedora repo/OpenJDK, resolves the issue.

That's good enough for me.

**Comment by djablonski** [comment]
Same problem with openjdk-9. Now with JDK9 there really should be no more access to such internals...

**Comment by judovana** [comment]
Helllo. That was packaging human-error. It is fixed in latest builds (they are still running, I fixed it yesterday noon). Sorry!

**Comment by gnu-andrew** [comment]
No, it wasn't a packaging error. We added the symlink back because of this breakage, but the bug itself remains: this Apache code is relying on an implementation detail of the JDK, which is exposed when jre/lib/security/cacerts doesn't exist.
We now patch the JDK itself to use /etc/pki/java/cacerts itself, so only third-party code like this uses that symlink.

**Comment by artem-zinnatullin** [comment]
We're getting this exception **sometimes** running Gradle (4.10) in a Docker container from a stable image with Oracle JDK 8, and I'm very confused on why it happens sometimes (during dependency resolution) 🤔

**Comment by felipecsl** [comment]
https://github.com/gradle/gradle/issues/1782#issuecomment-419541272 we're seeing exactly the same here, @artem-zinnatullin, running in a docker container with oracle jdk8 too

**Comment by artem-zinnatullin** [comment]
Ok, here is PR with fix for this issue https://github.com/gradle/gradle/pull/6721

**Comment by artem-zinnatullin** [comment]
While we're waiting for the fix #6721 to land, I was looking for a way to workaround it since we're having more and more occurrences of this issue in our setup.

The workaround I've found reading the faulty code in [DefaultSslContextFactory](https://github.com/gradle/gradle/blob/v4.10.0/subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/DefaultSslContextFactory.java#L71) is to set a System Property `javax.net.ssl.trustStore` and point it to a keystore with custom list of trusted CAs (or leafs if you want).

Keystore can be produced with Java's `keytool` or a GUI tool like [KeyStore Explorer](https://keystore-explorer.org/downloads.html).

System property can be set in the `gradle.properties` of the project like that:

```properties
# Override bad SSLContext lookup in Gradle with custom list of trusted CAs, remove once upstream fix is merged: https://github.com/gradle/gradle/pull/6721
systemProp.javax.net.ssl.trustStore=relative/or/absolute/path/trusted-cacerts.jks
```

Or otherhow (like JVM args with `-D`).

---

Below is not a legal advice nor am I a lawyer.

Since [JEP 319](http://openjdk.java.net/jeps/319) landed, OpenJDK ships with `lib/security/cacerts` that contains list of commonly trusted CAs.

OpenJDK is licensed under GPL v2 which should allow you to use `cacerts` data file as long as you are not distributing your software with it.

However, I built a custom list of trusted CAs just to be sure.

**Comment by staffanf** [comment]
@mark-vieira I saw that you had reservations for the pull request? Is this planned for a fix by the gradle team?
This is one of those issues that spuriously fails our builds and any work-around must be applied to all projects that use gradle making it a management mess.
I even fails our builds sometimes for requests to our artifactory with our own root certificate.

**Comment by mark-vieira** [comment]
@staffanf Yes, quite simply that PR will not work in the presence of the daemon. That would cause an `SSLContext` to get initialized and then cached for the lifetime of the daemon, effectively ignoring any subsequent changes you made to any of the SSL related system properties in the meantime. I certainly agree we should fix this, but that PR won't work in this case. I have no other opinion regarding prioritization here.

I'd instead suggest the owner of that PR to adapt it to fix the root problem as mentioned in the PR.
