### ISSUE TITLE
NPE when running tests with IntelliJ using gradle 3.4.1 and 3.5 but 3.3 works fine

### ISSUE THREAD

**Issue by adhamhf** [gradle/gradle#1790]
I'm using IntelliJ Ultimate 2016 to develop a Spring Boot application.  When I try to upgrade gradle to 3.4.1 or 3.5 I get an NPE when running the test.  If I use gradle 3.3 then I don't have the NPE in Intellij.

This problem does not occur if I run the tests from the command line using gradlew, it only happens when I use IntelliJ and its gradle integrations.  Note, that even if I use `gradlew idea` the NPE will happen in IntelliJ.

### Expected Behavior
my tests would run correctly in IntelliJ just like they do from the command line with gradlew.

### Current Behavior
`
java.lang.NullPointerException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
	at org.springframework.boot.test.mock.mockito.MockitoApi$Mockito2Api.getMockSettings(MockitoApi.java:186)
	at org.springframework.boot.test.mock.mockito.MockReset.get(MockReset.java:108)
	at org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener.resetMocks(ResetMocksTestExecutionListener.java:69)
	at org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener.resetMocks(ResetMocksTestExecutionListener.java:55)
	at org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener.afterTestMethod(ResetMocksTestExecutionListener.java:50)
	at org.springframework.test.context.TestContextManager.afterTestMethod(TestContextManager.java:319)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:94)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
`
### Context

Making it impossible to use IntelliJ.

### Steps to Reproduce (for bugs)
Try to use MockMvc in a Spring Boot test using gradle 3.4.1 or later.

### Your Environment

No sure I can provide much....

**Comment by adhamhf** [comment]
This is an issue with using @Autowired, I think.  For some reason the IntelliJ running is setting this up differently so when tests run dependency injection has not happened in the same order as when running gradlew.  Its pretty odd and a very odd error message.

**Comment by bmuschko** [comment]
Looking at the stack trace it seems that the issue does not come from Gradle but from IntelliJ classes.

**Comment by adhamhf** [comment]
This was fixed by upgrading to IntelliJ 2016.3.6.
