### ISSUE TITLE
Script can't be compiled if `gradlePlugin.plugins {}` is used

### ISSUE THREAD

**Issue by CommanderTvis** [gradle/gradle#17971]
### Expected Behavior
The script containing `gradlePlugin.plugins {}` can be compiled successfully. 

### Current Behavior
It fails with exception:
```
Caused by: org.gradle.kotlin.dsl.execution.UnexpectedDuplicateBlock: Unexpected `plugins` block found. Only one `plugins` block is allowed per script.
	at org.gradle.kotlin.dsl.execution.LexerKt.singleBlockSectionOrNull(Lexer.kt:256)
	at org.gradle.kotlin.dsl.execution.ProgramParser.checkForSingleBlocksOf(ProgramParser.kt:114)
	at org.gradle.kotlin.dsl.execution.ProgramParser.access$checkForSingleBlocksOf(ProgramParser.kt:25)
	at org.gradle.kotlin.dsl.execution.ProgramParser$programFor$1.invoke(ProgramParser.kt:40)
	at org.gradle.kotlin.dsl.execution.ProgramParser$programFor$1.invoke(ProgramParser.kt:25)
	at org.gradle.kotlin.dsl.execution.Packaged.map(Lexer.kt:51)
	at org.gradle.kotlin.dsl.execution.ProgramParser.programFor(ProgramParser.kt:38)
	at org.gradle.kotlin.dsl.execution.ProgramParser.parse(ProgramParser.kt:28)
	... 226 more
```

### Steps to Reproduce 

Try to compile the following script with Gradle 7.1.1:
```
plugins { `kotlin-dsl` }

gradlePlugin.plugins {
}
```

**Comment by mlopatkin** [comment]
This issue is specific to the Kotlin DSL and cannot be reproduced with Groovy DSL (though the stacktrace already suggests that).
In the meantime, some workarounds exist. First, it is possible to use block syntax to configure the plugin
```
gradlePlugin {
  plugins {
  }
}
```

Another option is to use backticks:
```
gradlePlugin.`plugins` {
}
```

**Comment by MBelniak** [comment]
Bump
2 years and issue still exists, which is so annoying it makes me want to go back to Groovy DSL <sigh>
