### ISSUE TITLE
Malicious test causes gradle build to succeed despite test failure

### ISSUE THREAD

**Issue by dpeger** [gradle/gradle#17978]
Currently it is possible to write a Java unit test case (with TestNG - not sure if JUnit is also affected) that will make all other test cases skip and will result in a successful build. Despite the lack of execution of the skipped tests this might be used to poison build caches or add malicious code to repositories that rely on gradle build status.

I only managed to reproduce the problem using JMock and the problem is probably also related to TestNG, but gradle should ensure proper build results even if some components don't behave well.

### Expected Behavior
Gradle build should fail for whatever reason tests during the build might fail.

### Current Behavior
After adding the below `EvilTest` to any project. The test execution is aborted on executing `EvilTest` and all tests after `EvilTest` are skipped. This stacktrace is printed to console but nevertheless the gradle build finishes with status success!

```
Unexpected exception thrown.
org.gradle.internal.remote.internal.MessageIOException: Could not read message from '/127.0.0.1:50488'.
        at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:94)
        at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionReceive.run(MessageHub.java:270)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ClassCastException: cannot assign instance of org.gradle.internal.serialize.TopLevelExceptionPlaceholder to field org.gradle.internal.serialize.ExceptionPlaceholder.toStringRuntimeExec of type java.lang.Throwable in instance of org.gradle.internal.serialize.TopLevelExceptionPlaceholder
        at java.base/java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2291)
        at java.base/java.io.ObjectStreamClass$FieldReflector.checkObjectFieldValueTypes(ObjectStreamClass.java:2254)
        at java.base/java.io.ObjectStreamClass.checkObjFieldValueTypes(ObjectStreamClass.java:1473)
        at java.base/java.io.ObjectInputStream.defaultCheckFieldValues(ObjectInputStream.java:2556)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2463)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2235)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1712)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:519)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:477)
        at org.gradle.internal.serialize.Message.receive(Message.java:53)
        at org.gradle.internal.serialize.BaseSerializerFactory$ThrowableSerializer.read(BaseSerializerFactory.java:316)
        at org.gradle.internal.serialize.BaseSerializerFactory$ThrowableSerializer.read(BaseSerializerFactory.java:313)
        at org.gradle.internal.remote.internal.hub.DefaultMethodArgsSerializer$ArraySerializer.read(DefaultMethodArgsSerializer.java:72)
        at org.gradle.internal.remote.internal.hub.DefaultMethodArgsSerializer$ArraySerializer.read(DefaultMethodArgsSerializer.java:61)
        at org.gradle.internal.remote.internal.hub.MethodInvocationSerializer$MethodInvocationReader.readArguments(MethodInvocationSerializer.java:128)
        at org.gradle.internal.remote.internal.hub.MethodInvocationSerializer$MethodInvocationReader.read(MethodInvocationSerializer.java:123)
        at org.gradle.internal.remote.internal.hub.MethodInvocationSerializer$MethodInvocationReader.read(MethodInvocationSerializer.java:102)
        at org.gradle.internal.serialize.kryo.TypeSafeSerializer$1.read(TypeSafeSerializer.java:36)
        at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:67)
        at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:52)
        at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
```

### Context
I stumbled across this issue while writing a test for a spring `AsyncHandlerInterceptor`. The http request was mocked and also accessed in another object's `toString()` method. I was surprised that the build succeeded despite obviously missing expectations and wrong assertions.

### Steps to Reproduce

I tried to reproduce the problem with plain Java (without JMock) but wasn't able to reproduce the exact behavior. I only managed to make the build run forever by throwing an exception with malicious `toString()` and `printStackTrace(...)` methods.

But adding the test below to a project will reproduce in 100% of the cases. It will cause all tests that are alphabetically after `EvilTest` to be skipped and the build will succeed despite test failure.

```java
import org.jmock.Expectations;
import org.jmock.Mockery;
import org.jmock.lib.concurrent.Synchroniser;
import org.testng.annotations.Test;

public class EvilTest {
    public static interface MockMe {
        public void expected(final ArgumentWithBadToString aArg);

        public String breakTest();
    }

    public static class ArgumentWithBadToString {
        private final MockMe mMockMe;

        public ArgumentWithBadToString(final MockMe aMockMe) {
            mMockMe = aMockMe;
        }

        @Override
        public String toString() {
            return mMockMe.breakTest(); // access to mocked instance in 'toString' causes test to abort
        }
    }

    public static class ClassUnderTest {
        private final MockMe mMockMe;

        public ClassUnderTest(final MockMe aMockMe) {
            mMockMe = aMockMe;
        }

        public void toBeTested(final ArgumentWithBadToString aArg) {
            mMockMe.expected(aArg);
            mMockMe.expected(aArg); // second call to 'expected' without matching Expectation will cause ExpectationError
        }
    }

    @Test
    public void breakGradleTestExecution() throws Exception {
        final Mockery mockery = new Mockery();
        mockery.setThreadingPolicy(new Synchroniser()); // using 'Synchroniser' seems to cause this particular problem
        final MockMe mock = mockery.mock(MockMe.class);

        mockery.checking(new Expectations() {{
            oneOf(mock).expected(with(any(ArgumentWithBadToString.class)));
        }});

        final ClassUnderTest cut = new ClassUnderTest(mock);
        cut.toBeTested(new ArgumentWithBadToString(mock));
    }
}
```

### Your Environment
Windows 2019
Gradle 7.0.1
JMock 2.12.0
TestNG 7.4.0

**Comment by jbartok** [comment]
@dpeger I can reproduce the problem you describe. What seems to happen in this "malicious" test is that an `org.jmock.api.ExpectationError` is thrown. For what reason, that's a JMock, not a Gradle concern. 

Gradle indeed does not handle this situation well, ie. following tests are skipped and the build succeeded. But the same thing happens, if you don't use Gradle, for example if you run your tests in IntelliJ, with the JUnit runner. 

Plus even the documentation of `java.lang.Error` starts with the statement that "An Error is a subclass of Throwable that indicates serious problems that a reasonable application should not try to catch."

This doesn't seem to be an issue which requires fixing in Gradle.

**Comment by dpeger** [comment]
I agree that this is a JMock or perhaps actually a TestNG concern. I think however gradle should ensure build failure on any kind of issue/error and not continue unnoticed and even finish successfully.

There are already several catch `Throwable` statements in `ExceptionPlaceholder` for a good reason. I was not able to investigate why this special kind of `ExpectationError` completely breaks the gradle messaging with TestNG but other `Error`s are handled correctly and make the build fail.

One can probably craft a special `Exception` that will make gradle break the same way without JMock or any other external dependency. As mentioned I was able to make gradle run indefinitely by throwing an `Exception` that itself throws errors on `printStackTrace` and `toString`. This could already be used to DOS a CI system. With a little more tweaking - once the reason for the problem in the gradle messaging is understood - making the build succeed despite test failures should not be much of a problem.
