### ISSUE TITLE
oom build with gradle 6.7.1

### ISSUE THREAD

**Issue by beyondckw** [gradle/gradle#18012]
STEPS TO REPRODUCE:
1.update agp from 4.0.1 to 4.2.2
2.run bundleRelease or bundleDebug
3.then build failure

Studio Build: Arctic Fox 2020.3.1
Version of Gradle Plugin: 4.2.2
Version of Gradle: 6.7.1
Version of Java: 8 or 11
OS: mac/linux

```
21:37:10 * What went wrong:
21:37:10 Could not receive a message from the daemon.
21:37:10
21:37:10 * Try:
21:37:10 Run with --debug option to get more log output. Run with --scan to get full insights.
21:37:10
21:37:10 * Exception is:
21:37:10 org.gradle.launcher.daemon.client.DaemonConnectionException: Could not receive a message from the daemon.
21:37:10        at org.gradle.launcher.daemon.client.DaemonClientConnection.receive(DaemonClientConnection.java:83)
21:37:10        at org.gradle.launcher.daemon.client.DaemonClientConnection.receive(DaemonClientConnection.java:35)
21:37:10        at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:215)
21:37:10        at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:184)
21:37:10        at org.gradle.launcher.daemon.client.SingleUseDaemonClient.execute(SingleUseDaemonClient.java:54)
21:37:10        at org.gradle.launcher.daemon.client.SingleUseDaemonClient.execute(SingleUseDaemonClient.java:37)
21:37:10        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:57)
21:37:10        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:212)
21:37:10        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:275)
21:37:10        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:247)
21:37:10        at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:82)
21:37:10        at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:30)
21:37:10        at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:92)
21:37:10        at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:38)
21:37:10        at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:44)
21:37:10        at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)
21:37:10        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
21:37:10        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
21:37:10        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:240)
21:37:10        at org.gradle.launcher.Main.doAction(Main.java:35)
21:37:10        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
21:37:10        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:37:10        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:37:10        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:37:10        at java.lang.reflect.Method.invoke(Method.java:498)
21:37:10        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
21:37:10        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
21:37:10        at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
21:37:10 Caused by: org.gradle.internal.remote.internal.MessageIOException: Could not read message from '/127.0.0.1:38233'.
21:37:10        at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:94)
21:37:10        at org.gradle.launcher.daemon.client.DaemonClientConnection.receive(DaemonClientConnection.java:77)
21:37:10        ... 27 more
21:37:10 Caused by: java.lang.OutOfMemoryError: Java heap space
21:37:10        at java.io.DataInputStream.<init>(DataInputStream.java:59)
21:37:10        at java.io.ObjectInputStream$BlockDataInputStream.<init>(ObjectInputStream.java:2707)
21:37:10        at java.io.ObjectInputStream.<init>(ObjectInputStream.java:344)
21:37:10        at org.gradle.internal.io.ClassLoaderObjectInputStream.<init>(ClassLoaderObjectInputStream.java:27)
21:37:10        at org.gradle.internal.serialize.ExceptionReplacingObjectInputStream.<init>(ExceptionReplacingObjectInputStream.java:39)
21:37:10        at org.gradle.internal.serialize.Message.receive(Message.java:52)
21:37:10        at org.gradle.internal.serialize.BaseSerializerFactory$ThrowableSerializer.read(BaseSerializerFactory.java:316)
21:37:10        at org.gradle.internal.serialize.BaseSerializerFactory$ThrowableSerializer.read(BaseSerializerFactory.java:313)
21:37:10        at org.gradle.internal.logging.serializer.LogEventSerializer.read(LogEventSerializer.java:56)
21:37:10        at org.gradle.internal.logging.serializer.LogEventSerializer.read(LogEventSerializer.java:26)
21:37:10        at org.gradle.internal.serialize.DefaultSerializerRegistry$TaggedTypeSerializer.read(DefaultSerializerRegistry.java:147)
21:37:10        at org.gradle.launcher.daemon.protocol.DaemonMessageSerializer$OutputMessageSerializer.read(DaemonMessageSerializer.java:243)
21:37:10        at org.gradle.launcher.daemon.protocol.DaemonMessageSerializer$OutputMessageSerializer.read(DaemonMessageSerializer.java:229)
21:37:10        at org.gradle.internal.serialize.DefaultSerializerRegistry$TaggedTypeSerializer.read(DefaultSerializerRegistry.java:147)
21:37:10        at org.gradle.internal.serialize.Serializers$StatefulSerializerAdapter$1.read(Serializers.java:36)
21:37:10        at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
21:37:10        at org.gradle.launcher.daemon.client.DaemonClientConnection.receive(DaemonClientConnection.java:77)
21:37:10        at org.gradle.launcher.daemon.client.DaemonClientConnection.receive(DaemonClientConnection.java:35)
21:37:10        at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:215)
21:37:10        at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:184)
21:37:10        at org.gradle.launcher.daemon.client.SingleUseDaemonClient.execute(SingleUseDaemonClient.java:54)
21:37:10        at org.gradle.launcher.daemon.client.SingleUseDaemonClient.execute(SingleUseDaemonClient.java:37)
21:37:10        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:57)
21:37:10        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:212)
21:37:10        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:275)
21:37:10        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:247)
21:37:10        at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:82)
21:37:10        at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:30)
21:37:10        at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:92)
21:37:10        at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:38)
21:37:10        at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:44)
21:37:10        at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)
```

**Comment by donat** [comment]
Can you try adjusting the [memory settings](https://docs.gradle.org/current/userguide/build_environment.html#sec:configuring_jvm_memory)?

**Comment by donat** [comment]
Closing as inactive.

**Comment by beyondckw** [comment]
gradle 6.9 is ok
