### ISSUE TITLE
guava-27.1-android.jar leaks on to classpath

### ISSUE THREAD

**Issue by carl-mastrangelo** [gradle/gradle#18036]
This bug looks similar to this issue:  https://github.com/gradle/gradle/issues/9897

When running Gradle 7.1.1 with the ErrorProne plugin `id "net.ltgt.errorprone" version "2.0.2"`, it appears that the wrong version of Guava ends up on the classpath. This manifests as a missing method error:

`java.lang.NoSuchMethodError: 'java.util.stream.Collector com.google.common.collect.ImmutableSet.toImmutableSet()`

The Error shown (with `--debug`) is:

```
2021-08-15T10:01:15.058-0700 [DEBUG] [org.gradle.workers.internal.WorkerDaemonStarter] Starting Gradle worker daemon with fork options DaemonForkOptions{executable=/home/carl/.gradle/jdks/jdk-16.0.1+9/bin/java, minHeapSize=null, maxHeapSize=null, jvmArgs=[--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED, --add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED, --add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED], keepAliveMode=SESSION}.
2021-08-15T10:01:15.065-0700 [DEBUG] [org.gradle.internal.remote.internal.inet.TcpIncomingConnector] Listening on [5ed3d040-0e84-4515-b848-5f9fc81c008b port:44013, addresses:[localhost/127.0.0.1]].
2021-08-15T10:01:15.072-0700 [DEBUG] [org.gradle.process.internal.worker.DefaultWorkerProcessBuilder] Creating Gradle Worker Daemon 3
2021-08-15T10:01:15.073-0700 [DEBUG] [org.gradle.process.internal.worker.DefaultWorkerProcessBuilder] Using application classpath [/home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/gradle-base-services-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/guava-27.1-android.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/gradle-messaging-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/gradle-model-core-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/gradle-logging-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/gradle-core-api-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/plugins/gradle-workers-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/native-platform-0.22-milestone-16.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/gradle-core-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/gradle-native-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/gradle-file-collections-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/gradle-worker-processes-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/gradle-process-services-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/slf4j-api-1.7.30.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/gradle-persistent-cache-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/gradle-files-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/gradle-hashing-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/gradle-snapshots-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/groovy-3.0.7.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/groovy-ant-3.0.7.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/groovy-json-3.0.7.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/groovy-xml-3.0.7.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/kryo-2.24.0.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/gradle-cli-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/jul-to-slf4j-1.7.30.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/javax.inject-1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/gradle-jvm-services-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/asm-9.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/plugins/gradle-dependency-management-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/gradle-file-temp-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/gradle-base-annotations-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/gradle-build-operations-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/commons-lang-2.6.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/plugins/gradle-language-java-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/plugins/gradle-language-jvm-7.1.1.jar, /home/carl/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/lib/plugins/gradle-platform-base-7.1.1.jar]
2021-08-15T10:01:15.073-0700 [DEBUG] [org.gradle.process.internal.worker.DefaultWorkerProcessBuilder] Using application module path []
2021-08-15T10:01:15.073-0700 [DEBUG] [org.gradle.process.internal.worker.DefaultWorkerProcessBuilder] Using implementation classpath []
2021-08-15T10:01:15.073-0700 [DEBUG] [org.gradle.process.internal.worker.DefaultWorkerProcessBuilder] Using implementation module path null
2021-08-15T10:01:15.073-0700 [DEBUG] [org.gradle.process.internal.worker.child.WorkerProcessClassPathProvider] Using worker process classpath: [/home/carl/.gradle/caches/7.1.1/workerMain/gradle-worker.jar]
2021-08-15T10:01:15.075-0700 [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'Gradle Worker Daemon 3'. Working directory: /home/carl/.gradle/workers Command: /home/carl/.gradle/jdks/jdk-16.0.1+9/bin/java --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED @/home/carl/.gradle/.tmp/gradle-worker-classpath16409082812400609454txt -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Worker Daemon 3'
2021-08-15T10:01:15.075-0700 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
2021-08-15T10:01:15.076-0700 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: Gradle Worker Daemon 3.
2021-08-15T10:01:15.086-0700 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
2021-08-15T10:01:15.087-0700 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
2021-08-15T10:01:15.088-0700 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'Gradle Worker Daemon 3'
2021-08-15T10:01:15.416-0700 [INFO] [org.gradle.workers.internal.WorkerDaemonStarter] Started Gradle worker daemon (0.357 secs) with fork options DaemonForkOptions{executable=/home/carl/.gradle/jdks/jdk-16.0.1+9/bin/java, minHeapSize=null, maxHeapSize=null, jvmArgs=[--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED, --add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED, --add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED], keepAliveMode=SESSION}.
2021-08-15T10:01:15.668-0700 [INFO] [org.gradle.api.internal.tasks.compile.JdkJavaCompiler] Compiling with JDK Java compiler API.
2021-08-15T10:01:16.179-0700 [ERROR] [system.err] An exception has occurred in the compiler (16.0.1). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
2021-08-15T10:01:16.179-0700 [ERROR] [system.err] java.lang.NoSuchMethodError: 'java.util.stream.Collector com.google.common.collect.ImmutableSet.toImmutableSet()'
2021-08-15T10:01:16.180-0700 [ERROR] [system.err]       at com.google.errorprone.scanner.BuiltInCheckerSuppliers.getSuppliers(BuiltInCheckerSuppliers.java:540)
2021-08-15T10:01:16.180-0700 [ERROR] [system.err]       at com.google.errorprone.scanner.BuiltInCheckerSuppliers.getSuppliers(BuiltInCheckerSuppliers.java:533)
2021-08-15T10:01:16.180-0700 [ERROR] [system.err]       at com.google.errorprone.scanner.BuiltInCheckerSuppliers.<clinit>(BuiltInCheckerSuppliers.java:567)
2021-08-15T10:01:16.180-0700 [ERROR] [system.err]       at com.google.errorprone.ErrorProneJavacPlugin.init(ErrorProneJavacPlugin.java:35)
2021-08-15T10:01:16.180-0700 [ERROR] [system.err]       at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugin(BasicJavacTask.java:255)
2021-08-15T10:01:16.181-0700 [ERROR] [system.err]       at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugins(BasicJavacTask.java:229)
2021-08-15T10:01:16.181-0700 [ERROR] [system.err]       at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.prepareCompiler(JavacTaskImpl.java:204)
2021-08-15T10:01:16.181-0700 [ERROR] [system.err]       at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:101)
2021-08-15T10:01:16.181-0700 [ERROR] [system.err]       at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
2021-08-15T10:01:16.181-0700 [ERROR] [system.err]       at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
2021-08-15T10:01:16.181-0700 [ERROR] [system.err]       at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
2021-08-15T10:01:16.181-0700 [ERROR] [system.err]       at org.gradle.internal.compiler.java.IncrementalCompileTask.call(IncrementalCompileTask.java:89)
2021-08-15T10:01:16.182-0700 [ERROR] [system.err]       at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.call(AnnotationProcessingCompileTask.java:94)
2021-08-15T10:01:16.182-0700 [ERROR] [system.err]       at org.gradle.api.internal.tasks.compile.ResourceCleaningCompilationTask.call(ResourceCleaningCompilationTask.java:57)
2021-08-15T10:01:16.182-0700 [ERROR] [system.err]       at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:54)
2021-08-15T10:01:16.182-0700 [ERROR] [system.err]       at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:39)
2021-08-15T10:01:16.182-0700 [ERROR] [system.err]       at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkAction.execute(AbstractDaemonCompiler.java:135)
2021-08-15T10:01:16.182-0700 [ERROR] [system.err]       at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
2021-08-15T10:01:16.182-0700 [ERROR] [system.err]       at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
2021-08-15T10:01:16.182-0700 [ERROR] [system.err]       at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
2021-08-15T10:01:16.182-0700 [ERROR] [system.err]       at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
2021-08-15T10:01:16.182-0700 [ERROR] [system.err]       at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
2021-08-15T10:01:16.182-0700 [ERROR] [system.err]       at org.gradle.workers.internal.FlatClassLoaderWorker.run(FlatClassLoaderWorker.java:32)
2021-08-15T10:01:16.182-0700 [ERROR] [system.err]       at org.gradle.workers.internal.FlatClassLoaderWorker.run(FlatClassLoaderWorker.java:22)
2021-08-15T10:01:16.182-0700 [ERROR] [system.err]       at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:85)
2021-08-15T10:01:16.182-0700 [ERROR] [system.err]       at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:55)
2021-08-15T10:01:16.182-0700 [ERROR] [system.err]       at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
2021-08-15T10:01:16.183-0700 [ERROR] [system.err]       at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
2021-08-15T10:01:16.183-0700 [ERROR] [system.err]       at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
2021-08-15T10:01:16.183-0700 [ERROR] [system.err]       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-08-15T10:01:16.183-0700 [ERROR] [system.err]       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
2021-08-15T10:01:16.183-0700 [ERROR] [system.err]       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-08-15T10:01:16.183-0700 [ERROR] [system.err]       at java.base/java.lang.reflect.Method.invoke(Method.java:567)
2021-08-15T10:01:16.183-0700 [ERROR] [system.err]       at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
2021-08-15T10:01:16.183-0700 [ERROR] [system.err]       at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
2021-08-15T10:01:16.183-0700 [ERROR] [system.err]       at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
2021-08-15T10:01:16.183-0700 [ERROR] [system.err]       at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
2021-08-15T10:01:16.184-0700 [ERROR] [system.err]       at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
2021-08-15T10:01:16.184-0700 [ERROR] [system.err]       at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
2021-08-15T10:01:16.184-0700 [ERROR] [system.err]       at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
2021-08-15T10:01:16.184-0700 [ERROR] [system.err]       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
2021-08-15T10:01:16.184-0700 [ERROR] [system.err]       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
2021-08-15T10:01:16.187-0700 [ERROR] [system.err]       at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
2021-08-15T10:01:16.187-0700 [ERROR] [system.err]       at java.base/java.lang.Thread.run(Thread.java:831)
2021-08-15T10:01:16.204-0700 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'compiler daemon' completed
2021-08-15T10:01:16.204-0700 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Compile Java for :compileJava' completed
2021-08-15T10:01:16.204-0700 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Execute compile for :compileJava' completed
2021-08-15T10:01:16.204-0700 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Executing task ':compileJava'' completed
``` 

I am running with 

```
$ java -version
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment Zulu16.28+11-CA (build 16+36)
OpenJDK 64-Bit Server VM Zulu16.28+11-CA (build 16+36, mixed mode, sharing)
```

**Comment by donat** [comment]
Could you please create a reproducer project and upload it here?

**Comment by donat** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.

**Comment by donat** [comment]
Closing as inactive.
