### ISSUE TITLE
Test worker can't connect to daemon

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#18046]
I'm not sure if this is a Gradle issue, but would appreciate any advice on what the cause might be. I'm seeing this about once a month on a customer's CI machines. Not sure how the connection can be refused if the daemon itself opened the port before starting the test process?

```
org.gradle.internal.remote.internal.ConnectException: Could not connect to server [46b08111-3f5f-4229-8a64-983d8a282b0b port:44425, addresses:[/127.0.0.1]]. Tried addresses: [/127.0.0.1].
	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.connect(TcpOutgoingConnector.java:67)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedClient.getConnection(MessageHubBackedClient.java:36)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:123)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:776)
	at java.base/sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:120)
	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.tryConnect(TcpOutgoingConnector.java:81)
	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.connect(TcpOutgoingConnector.java:54)
	... 5 more
```

**Comment by donat** [comment]
Although they're not the same, we've seen similar issues that were due to misconfigured network interfaces: https://github.com/gradle/gradle/issues/12232. We identified that the NAT masquerade cause daemon connection issues: https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/userguide/troubleshooting.adoc#troubleshooting-daemon-connection-issues.

I'm happy to continue the conversation if you have a way to reproduce the issue.

**Comment by donat** [comment]
Closing as inactive.

**Comment by oehme** [comment]
Since the issue is intermittent, I doubt it is due to a misconfiguration. Thanks for taking a look anyway. I don't have a way to reproduce it, since it only happens every few thousand builds.
