### ISSUE TITLE
FindBugs plugin: text report does not work

### ISSUE THREAD

**Issue by thejohnfreeman** [gradle/gradle#1809]
https://issues.gradle.org/browse/GRADLE-2994
https://discuss.gradle.org/t/findbugs-text-report-doesnt-work/2332

**Comment by thejohnfreeman** [comment]
FindBugs has an "emacs format" for reports that is probably intended.

**Comment by bmuschko** [comment]
@thejohnfreeman Could you please fill in the fields we usually require in the issue template? At the moment it's really hard to know what problem this issue is supposed to address based on the title.

**Comment by bmuschko** [comment]
@thejohnfreeman The following code does not work and is a bug in the FindBugs plugin:

```
apply plugin: 'java'
apply plugin: 'findbugs'

repositories {
    mavenCentral()
}

tasks.withType(FindBugs) {
    reports {
        xml.enabled = false
        text.enabled = true
    }
}
```

Maybe `-text` was provided by FindBugs in some version and is not supported anymore. The stack trace you get is the following:

```
* What went wrong:
Execution failed for task ':findbugsMain'.
> Unknown option: -text

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':findbugsMain'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:98)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:68)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
Caused by: java.lang.IllegalArgumentException: Unknown option: -text
        at edu.umd.cs.findbugs.config.CommandLine.parse(CommandLine.java:330)
        at edu.umd.cs.findbugs.config.CommandLine.expandOptionFiles(CommandLine.java:180)
        at edu.umd.cs.findbugs.FindBugs.processCommandLine(FindBugs.java:340)
        at org.gradle.api.plugins.quality.internal.findbugs.FindBugsExecuter.runFindbugs(FindBugsExecuter.java:38)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:88)
        at org.gradle.process.internal.worker.request.WorkerAction.runThenStop(WorkerAction.java:72)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        ... 2 more
```

If you change the report format to `emacs` then it works properly:

```
tasks.withType(FindBugs) {
    reports {
        xml.enabled = false
        emacs.enabled = true
    }
}
```

It's still not fully clear to me what you are asking for. Are you 1) saying that the `text` report type is not working and that's the one you need or 2) you are actually looking for `emacs` and that's the one you want?

**Comment by thejohnfreeman** [comment]
The answer is (2), I was looking for emacs "report type" and did not know `emacs.enabled` even existed. It doesn't seem to be mentioned [anywhere](https://docs.gradle.org/current/userguide/findbugs_plugin.html) in the [documentation](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.FindBugsExtension.html). Thanks for the help!

**Comment by bmuschko** [comment]
You can navigate from the page you linked to the [Javadocs of the type that allows you to configure the report type](https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/quality/FindBugsReports.html). I'd agree that it could be easier to find.

**Comment by JLLeitschuh** [comment]
The `FindBugsReports::getText` method should probably be deprecated as it is non working.
In Gradle Kotlin Script this method exists but is, as such, invalid.
