### ISSUE TITLE
Flaky ToolingApiClientMinJdkCompatibilityTest with 2.14 distributions

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#18244]
```
Error:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
org.gradle.tooling.GradleConnectionException: Could not run build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-2.14.1-bin.zip'.
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:55)
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:43)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:69)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
	at java.lang.Thread.run(Thread.java:748)
	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
	at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter.run(DefaultBuildActionExecuter.java:67)
	at ToolingApiCompatibilityClient.buildAction(ToolingApiCompatibilityClient.java:82)
	at ToolingApiCompatibilityClient.main(ToolingApiCompatibilityClient.java:31)
Caused by: org.gradle.api.UncheckedIOException: java.io.IOException: Unable to delete file: C:\tcagent1\work\e67123fb5b9af0ac\intTestHomeDir\distributions-full\caches\jars-1\jsp3brzfdkxot7cou2nz35z07u3e8a3\gradle-tooling-api-7.3.jar
	at org.gradle.util.GFileUtils.forceDelete(GFileUtils.java:208)
	at org.gradle.cache.internal.DefaultPersistentDirectoryCache$Initializer.initialize(DefaultPersistentDirectoryCache.java:93)
	at org.gradle.cache.internal.DefaultCacheAccess$4.run(DefaultCacheAccess.java:353)
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.doWriteAction(DefaultFileLockManager.java:179)
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.writeFile(DefaultFileLockManager.java:169)
	at org.gradle.cache.internal.DefaultCacheAccess.onStartWork(DefaultCacheAccess.java:351)
	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:187)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:102)
	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.useCache(DefaultCacheFactory.java:183)
	at org.gradle.tooling.internal.provider.DaemonSidePayloadClassLoaderFactory.getClassLoaderFor(DaemonSidePayloadClassLoaderFactory.java:70)
	at org.gradle.tooling.internal.provider.DefaultPayloadClassLoaderRegistry$ClassLoaderToDetailsTransformer.transform(DefaultPayloadClassLoaderRegistry.java:132)
	at org.gradle.tooling.internal.provider.DefaultPayloadClassLoaderRegistry$ClassLoaderToDetailsTransformer.transform(DefaultPayloadClassLoaderRegistry.java:120)
	at org.gradle.tooling.internal.provider.ClassLoaderCache.getClassLoader(ClassLoaderCache.java:47)
	at org.gradle.tooling.internal.provider.DefaultPayloadClassLoaderRegistry.getClassLoader(DefaultPayloadClassLoaderRegistry.java:83)
	at org.gradle.tooling.internal.provider.DefaultPayloadClassLoaderRegistry.access$300(DefaultPayloadClassLoaderRegistry.java:32)
	at org.gradle.tooling.internal.provider.DefaultPayloadClassLoaderRegistry$2.resolveClass(DefaultPayloadClassLoaderRegistry.java:76)
	at org.gradle.tooling.internal.provider.PayloadSerializer$2.readClass(PayloadSerializer.java:126)
	at org.gradle.tooling.internal.provider.PayloadSerializer$2.readClassDescriptor(PayloadSerializer.java:106)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1578)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1494)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1748)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1327)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:349)
```

**Comment by blindpirate** [comment]
https://ge.gradle.org/s/5pgaqpx6i3bqi

An attempt to fix: https://github.com/gradle/gradle/pull/18060

**Comment by blindpirate** [comment]
Move to gradle-private.
