### ISSUE TITLE
InputStreams inside a WorkAction<?> is unexpectedly closed when using classloaderIsolation

### ISSUE THREAD

**Issue by enaess** [gradle/gradle#18305]
### Expected Behavior
I should be able to load a resource inside my .jar file via the new ClassLoader without it being closed. 

The issue is closely related to https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8205976. A close on one URLClassLoader impacts that of a different URLClassLoader

### Current Behavior
I arrange for a WorkQueue to process a set of WorkQueue items (WorkAction<?>). This WorkAction attempts to load a file inside a dependent .jar file (using a custom classpath setup via project dependencies), e.g. Item.getClass().getResourceAsStream("some-file"). 

This works for the most part, but I run into a situation where I happen to obtain a JarFile.JarFileInputStream which wraps a ZipFile.ZipInflatorInputStream. Mysteriously, this InputStream throws an IOException (reason: stream closed) during the processing of this. In certain cases when this scenario occur, the ZipFile.ZipInflatorInputStream returned from getResource() function is already closed.

Having that said, I've spent hours chasing this issue down. The normal execution path hits the InputStream's close() method as expected. Trying to catch the initial close on this stream by wrapping it in a new class proved unsuccessful. 

### Context
Further investigations indicate that the ClassLoader being used via IsolatedClassloaderWorker.run() method does the execution of the WorkAction<?> item by:

```
    public DefaultWorkResult run(TransportableActionExecutionSpec spec) {
        GroovySystemLoader workerClasspathGroovy = this.groovySystemLoaderFactory.forClassLoader(this.workerClassLoader);

        DefaultWorkResult var3;
        try {
            var3 = this.executeInClassLoader(spec, this.workerClassLoader);
        } finally {
            workerClasspathGroovy.shutdown();
            if (!this.reuseClassloader) {
                CompositeStoppable.stoppable(new Object[]{this.workerClassLoader}).stop();  // <-- this ends up closing my InputStream
                this.workerClassLoader = null;
            }

        }

        return var3;
```

This is gathered from the following stacktrace
```
run:773, ZipFile$CleanableResource (java.util.zip)
clean:862, ZipFile$CleanableResource$FinalizableResource (java.util.zip)
close:892, ZipFile (java.util.zip)
close:170, URLJarFile (sun.net.www.protocol.jar)
close:389, URLClassLoader (java.net)
stop:90, CompositeStoppable$2 (org.gradle.internal.concurrent)
stop:106, CompositeStoppable (org.gradle.internal.concurrent)
run:54, IsolatedClassloaderWorker (org.gradle.workers.internal)
run:30, IsolatedClassloaderWorker (org.gradle.workers.internal)
lambda$execute$0:57, IsolatedClassloaderWorkerFactory$1 (org.gradle.workers.internal)
execute:-1, 1519940818 (org.gradle.workers.internal.IsolatedClassloaderWorkerFactory$1$$Lambda$1498)
call:44, AbstractWorker$1 (org.gradle.workers.internal)
call:41, AbstractWorker$1 (org.gradle.workers.internal)
execute:200, DefaultBuildOperationRunner$CallableBuildOperationWorker (org.gradle.internal.operations)
execute:195, DefaultBuildOperationRunner$CallableBuildOperationWorker (org.gradle.internal.operations)
execute:75, DefaultBuildOperationRunner$3 (org.gradle.internal.operations)
execute:68, DefaultBuildOperationRunner$3 (org.gradle.internal.operations)
execute:153, DefaultBuildOperationRunner (org.gradle.internal.operations)
execute:68, DefaultBuildOperationRunner (org.gradle.internal.operations)
call:62, DefaultBuildOperationRunner (org.gradle.internal.operations)
lambda$call$2:79, DefaultBuildOperationExecutor (org.gradle.internal.operations)
apply:-1, 457058266 (org.gradle.internal.operations.DefaultBuildOperationExecutor$$Lambda$89)
callWithUnmanagedSupport:54, UnmanagedBuildOperationWrapper (org.gradle.internal.operations)
call:79, DefaultBuildOperationExecutor (org.gradle.internal.operations)
executeWrappedInBuildOperation:41, AbstractWorker (org.gradle.workers.internal)
execute:49, IsolatedClassloaderWorkerFactory$1 (org.gradle.workers.internal)
lambda$submitWork$2:206, DefaultWorkerExecutor (org.gradle.workers.internal)
call:-1, 1257227150 (org.gradle.workers.internal.DefaultWorkerExecutor$$Lambda$1497)
run:264, FutureTask (java.util.concurrent)
runExecution:214, DefaultConditionalExecutionQueue$ExecutionRunner (org.gradle.internal.work)
runBatch:164, DefaultConditionalExecutionQueue$ExecutionRunner (org.gradle.internal.work)
run:131, DefaultConditionalExecutionQueue$ExecutionRunner (org.gradle.internal.work)
call:515, Executors$RunnableAdapter (java.util.concurrent)
run:264, FutureTask (java.util.concurrent)
onExecute:64, ExecutorPolicy$CatchAndRecordFailures (org.gradle.internal.concurrent)
run:48, ManagedExecutorImpl$1 (org.gradle.internal.concurrent)
runWorker:1128, ThreadPoolExecutor (java.util.concurrent)
run:628, ThreadPoolExecutor$Worker (java.util.concurrent)
run:61, ThreadFactoryImpl$ManagedThreadRunnable (org.gradle.internal.concurrent)
run:834, Thread (java.lang)
```

The execution of WorkAction<?> within class loader works fine. However, somehow this causes a problem for other items still processing in the queue. 

See the issue:
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8205976.

### Steps to Reproduce

I am working on a Gist for this.

```
Caused by: org.gradle.api.GradleException: Translation error: java.io.IOException: Stream closed
	at com.nmwco.build.tasks.xlf.Translate.execute(Translate.java:149)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
	at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
	at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
	at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
	at org.gradle.workers.internal.IsolatedClassloaderWorkerFactory$1.lambda$execute$0(IsolatedClassloaderWorkerFactory.java:57)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:79)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:79)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.IsolatedClassloaderWorkerFactory$1.execute(IsolatedClassloaderWorkerFactory.java:49)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:206)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:214)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	... 3 more
Caused by: net.sf.okapi.common.exceptions.OkapiIOException: java.io.IOException: Stream closed
	at net.sf.okapi.filters.its.Parameters.load(Parameters.java:221)
	at net.sf.okapi.common.filters.FilterConfigurationMapper.createFilter(FilterConfigurationMapper.java:188)
	at net.sf.okapi.lib.merge.step.OriginalDocumentXliffMergerStep.handleRawDocument(OriginalDocumentXliffMergerStep.java:119)
	at net.sf.okapi.common.pipeline.BasePipelineStep.handleEvent(BasePipelineStep.java:75)
	at net.sf.okapi.common.pipeline.Pipeline.execute(Pipeline.java:117)
	at net.sf.okapi.common.pipeline.Pipeline.process(Pipeline.java:227)
	at net.sf.okapi.common.pipeline.Pipeline.process(Pipeline.java:199)
	at net.sf.okapi.common.pipelinedriver.PipelineDriver.processBatch(PipelineDriver.java:182)
	at com.nmwco.tools.multitran.OkapiUtils.translateFile(OkapiUtils.java:439)
	at com.nmwco.tools.multitran.OkapiUtils.translateVia(OkapiUtils.java:540)
	at com.nmwco.tools.multitran.OkapiUtils.translateViaDiffLeverage(OkapiUtils.java:474)
	at com.nmwco.build.tasks.xlf.Translate.execute(Translate.java:142)
	... 29 more
Caused by: java.io.IOException: Stream closed
	at org.apache.xerces.impl.XMLEntityManager$RewindableInputStream.readAndBuffer(XMLEntityManager.java:3174)
	at org.apache.xerces.impl.XMLEntityManager$RewindableInputStream.read(XMLEntityManager.java:3207)
	at org.apache.xerces.impl.io.UTF8Reader.read(UTF8Reader.java:306)
	at org.apache.xerces.impl.XMLEntityScanner.load(XMLEntityScanner.java:1741)
	at org.apache.xerces.impl.XMLEntityScanner.skipDeclSpaces(XMLEntityScanner.java:1339)
	at org.apache.xerces.impl.XMLScanner.scanXMLDeclOrTextDecl(XMLScanner.java:475)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanXMLDeclOrTextDecl(XMLDocumentFragmentScannerImpl.java:661)
	at org.apache.xerces.impl.XMLDocumentScannerImpl$XMLDeclDispatcher.dispatch(XMLDocumentScannerImpl.java:686)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:324)
	at org.apache.xerces.parsers.XML11Configuration.parse(XML11Configuration.java:875)
	at org.apache.xerces.parsers.XML11Configuration.parse(XML11Configuration.java:798)
	at org.apache.xerces.parsers.XMLParser.parse(XMLParser.java:108)
	at org.apache.xerces.parsers.DOMParser.parse(DOMParser.java:230)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:298)
	at net.sf.okapi.filters.its.Parameters.load(Parameters.java:218)
	... 40 more
```

### Your Environment

I have this reproduced on Java 11 and Java 16 using Amazon Corretto Java tool chain.

**Comment by enaess** [comment]
I'd be very curious if the ClassLoaderWorkerSpec could include a parameter to specify to re-use the class loader inside the IsolatedClassloaderWorker. It's already a parameter to the constructor, but grepping through the code; it seems like it is unused.

**Comment by ljacomet** [comment]
Thanks for the detailed analysis. Unfortunately, without a reproducer, it will be a while before someone can look deep enough into that issue.

**Comment by enaess** [comment]
I'll work on that next @ljacomet - Just didn't have time to assemble it all at once.

**Comment by enaess** [comment]
I've produced a sample application and published the code on github. This is a minimum snipped of code to reproduce the issue.

[IsolatedClassLoaderTest](https://github.com/enaess/IsolatedClassLoaderTest)

**Comment by enaess** [comment]
Just to have this on record for this bug. If I use a DocumentBuilder object, and then try to use a resource in a .jar file; i.e. use the DocumentBuilder.parse() on an .xml (or .xsl) object. Then the problem manifest itself. This is to show that okapi-lib isn't the culprit here. 

It's sufficient to change the TestAction.execute() method to the following:

```
            MyTest test = new MyTest();
            DocumentBuilderFactory factory1 = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory1.newDocumentBuilder();
            builder.parse(new InputSource(test.getClass().getResourceAsStream(test.getLocation())));
```

To cause the IOException to be thrown.

**Comment by enaess** [comment]
@ljacomet let me know what you think about the bug now.

**Comment by enaess** [comment]
@ljacomet Do you need anything else for this bug?

**Comment by dgeissl** [comment]
for anyone looking for a solution, a colleage of mine just found the same issue here https://github.com/detekt/detekt/issues/4364, that has been fixed by:
https://github.com/detekt/detekt/blob/main/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/extensions/DetektExtension.kt#L81-L93
note the deactivation of caches on the `URLConnection`

**Comment by enaess** [comment]
Thanks for your update @dgeissl
