### ISSUE TITLE
Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean. - with Gradle distributiongradle-6.9.1

### ISSUE THREAD

**Issue by kswat** [gradle/gradle#18390]
Spring Boot application 2.5.4, is unable to start and throws Servlet container error, when using gradle wrapper version 6.9.1
### Expected Behavior
The application should run the spring boot app

### Current Behavior
Caused by: org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:210)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:180)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:160)

### Context
Trying to test application before deploying to cloud 

### Steps to Reproduce 
Create a spring boot app using https://start.spring.io/

Gradle 
Java 8
Boot 2.5.4

The version of wrapper is 7.2, but in existing applications it could be 6.x. So update  gralde wrapper properties to use 6.9.1

Refresh Gradle project

Try to run Spring boot app

### Your Environment
Gradle 
Java 8
Boot 2.5.4
Build scan URL:

**Comment by tresat** [comment]
Hi @kswat, this appears to be an issue with Spring boot, not Gradle.  You can try opening an issue at https://github.com/spring-projects/spring-boot/issues.
