### ISSUE TITLE
JDK17 + JUnit broken test scanning

### ISSUE THREAD

**Issue by ben-manes** [gradle/gradle#18465]
Tested using:
- Gradle 7.4-20210928222738+0000
- JUnit4

Updating a build matrix from JDK16 to 17 resulted in non unit-test classes being picked up by the scanner and throws an `InvalidTestClassError`. In the stacktrace below, an annotation that includes a nested enum is incorrectly matched on. The source project primarily uses TestNG, but includes JUnit3 tests from alternative sources (e.g. Guava's testlib collection suite). Unfortunately that means it is not possible to simply upgrade to JUnit5 (and unrelated failure on the vintage engine).

<details closed>
<summary><b>Example initialization error</b></summary>

```
com.github.benmanes.caffeine.cache.testing.CacheSpec$Loader > initializationError FAILED
    org.junit.runners.model.InvalidTestClassError: Invalid test class 'com.github.benmanes.caffeine.cache.testing.CacheSpec$Loader':
      1. Test class should have exactly one public constructor
      2. No runnable methods
        at org.junit.runners.ParentRunner.validate(ParentRunner.java:525)
        at org.junit.runners.ParentRunner.<init>(ParentRunner.java:102)
        at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:84)
        at org.junit.runners.JUnit4.<init>(JUnit4.java:23)
        at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
        at org.junit.internal.builders.AllDefault PossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
        at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
        at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
```
</details>

A simple workaround is to use test filtering,
```gradle
filter.includeTestsMatching '*Test*'
```

Please see this [minimal reproducer](https://github.com/junit-team/junit4/files/7193199/junit-test.zip).

This may be closed due to #16857, but that does not refer to this problem and claims that JDK17 support is ready in nightly.
A previous discussion on a JUnit4 issue for reference, https://github.com/junit-team/junit4/issues/1717

**Comment by big-guy** [comment]
@ben-manes could you give `7.3-20210930052426+0000` a try?

**Comment by ben-manes** [comment]
LGTM, thanks!

**Comment by akarnokd** [comment]
I've run into the same errors with RxJava when building with JDK 18b27 and gradle-7.4-20211210001706+0000-bin.zip, any tips?

**Comment by sormuras** [comment]
[ASM 9.2](https://asm.ow2.io/versions.html) is required to scan classes compiled to Java 18. Gradle seems to include/provide [ASM 9.1](https://github.com/gradle/gradle/blob/09aaf1675bdd9ba62598302fac82901fc9ebdbb9/subprojects/distributions-dependencies/build.gradle.kts#L18): _creating an issue to "Support JDK 18"..._
