### ISSUE TITLE
`is` prefix in extension property leads to "Cannot have abstract method extension.isXYZ()" on Kotlin and Gradle 7.x

### ISSUE THREAD

**Issue by pshakhov** [gradle/gradle#18543]
### Expected Behavior
The property in Kotlin can have prefix `is`.

### Current Behavior
The "Cannot have abstract method ReleaseExtension.isNeedUpdateFixVersion()" error is reported when the method name is prefixed by "is":
```
abstract class ReleaseExtension : SelfConfiguration {
...
abstract val isNeedUpdateFixVersion: Property<Boolean>```

### Context
https://stackoverflow.com/a/69443041/13171598

### Your Environment
Gradle 7.0.2, Kotlin 1.4.31, jdk8.
Build scan URL:
https://scans.gradle.com/s/vmyjzkjbt65ww

**Comment by TWiStErRob** [comment]
I just ran into this, it was really confusing, could the error message be improved at least? Especially since it's a convention in Kotlin is to name Boolean properties `is...`. Now I understand why AGP kept renaming their incubating properties early in the 7.x versions.

I reproduced by grabbing this example: https://docs.gradle.org/current/userguide/custom_plugins.html#sec:getting_input_from_the_build

and changing `message` to be `isMessage: Property<Boolean>`, which is a perfectly reasonable thing to do... and it "just" fails.

Stack trace for the record:
```
* What went wrong:
Failed to apply plugin class 'Build_gradle$GreetingPlugin'.
> Could not create an instance of type Build_gradle$GreetingPluginExtension.
   > Could not generate a decorated class for type Build_gradle.GreetingPluginExtension.
      > Cannot have abstract method GreetingPluginExtension.isMessage().

* Exception is:
org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin class 'Build_gradle$GreetingPlugin'.
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:173)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:151)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:177)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:161)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$100(DefaultObjectConfigurationAction.java:43)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$2.run(DefaultObjectConfigurationAction.java:87)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:190)
        at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:42)
        at org.gradle.kotlin.dsl.support.CompiledKotlinBuildScript.apply(CompiledKotlinBuildScript.kt)
        at Build_gradle.<init>(build.gradle.kts:26)
        at <truncated Gradle internals for general startup>
Caused by: org.gradle.api.reflect.ObjectInstantiationException: Could not create an instance of type Build_gradle$GreetingPluginExtension.
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:69)
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.newInstanceWithDisplayName(DependencyInjectingInstantiator.java:50)
        at org.gradle.internal.extensibility.DefaultConvention.instantiate(DefaultConvention.java:217)
        at org.gradle.internal.extensibility.DefaultConvention.create(DefaultConvention.java:126)
        at Build_gradle$GreetingPlugin.apply(build.gradle.kts:26)
        at Build_gradle$GreetingPlugin.apply(build.gradle.kts:6)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:187)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$100(DefaultPluginManager.java:52)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:282)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
        at org.gradle.api.internal.plugins.DefaultPluginManager.lambda$doApply$0(DefaultPluginManager.java:167)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:44)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:166)
        ... 181 more
Caused by: org.gradle.internal.instantiation.ClassGenerationException: Could not generate a decorated class for type Build_gradle.GreetingPluginExtension.
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:248)
        at org.gradle.cache.internal.DefaultCrossBuildInMemoryCacheFactory$AbstractCrossBuildInMemoryCache.get(DefaultCrossBuildInMemoryCacheFactory.java:130)
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator.generate(AbstractClassGenerator.java:174)
        at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator.generate(AsmBackedClassGenerator.java:107)
        at org.gradle.internal.instantiation.generator.ParamsMatchingConstructorSelector.forParams(ParamsMatchingConstructorSelector.java:44)
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:61)
        ... 202 more
Caused by: java.lang.IllegalArgumentException: Cannot have abstract method GreetingPluginExtension.isMessage().
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator.assertNotAbstract(AbstractClassGenerator.java:389)
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:326)
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:217)
        ... 207 more
```

**Comment by EdricChan03** [comment]
If it helps the Gradle team, I've managed to reproduce it myself and produced a [Gradle build scan](https://scans.gradle.com/s/kd4rsdsui6j3o/failure) with the full stacktrace.

Reproduction code:

```kotlin
import org.gradle.api.provider.Property

abstract class LibraryMaven {
    abstract val groupId: Property<String>

    abstract val artifactId: Property<String>

    abstract val version: Property<String>

    abstract val isReleaseVersion: Property<Boolean>
}
```

I'm guessing the reflection code that checks if the properties are managed properties doesn't include the possibility of Kotlin `is*` methods being generated as `is*` in the resulting Java bytecode? (This is what the generated bytecode looks like according to the output of Tools -> Kotlin -> Show Kotlin Bytecode, then clicking on the "Decompile to Java" button:)

```java
public abstract class LibraryMaven {
    @NotNull
    public abstract Property getGroupId();

    @NotNull
    public abstract Property getArtifactId();

    @NotNull
    public abstract Property getVersion();

    @NotNull
    public abstract Property isReleaseVersion();
}
```

**Comment by ljacomet** [comment]
Sorry for the late reply!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by mlopatkin** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.
