### ISSUE TITLE
Incorrect result when TestNG 7.x test times out

### ISSUE THREAD

**Issue by alexei-osipov** [gradle/gradle#18566]
TestNG test that times out because of `timeOut` option produces exception:
```
org.gradle.internal.reflect.NoSuchMethodException: Could not find method onTestFailedWithTimeout(interface org.testng.ITestResult) on TestNGTestResultProcessorAdapter.
```
Test code:
```java
public class SlowTest {
    @Test(timeOut = 10)
    public void testThatTimesOut() throws InterruptedException {
	    // We expect to get a timeout but we get NoSuchMethodException
        Thread.sleep(1000);		
    }
}
```

### Expected Behavior
Test should fail with `org.testng.internal.thread.ThreadTimeoutException` or other exception that indicates a timed out test.

### Current Behavior
Gradle reports test failure but with wrong message:
```
org.gradle.internal.reflect.NoSuchMethodException: Could not find method onTestFailedWithTimeout(interface org.testng.ITestResult) on TestNGTestResultProcessorAdapter.
	at org.gradle.internal.reflect.JavaMethod.findMethod(JavaMethod.java:88)
	at org.gradle.internal.reflect.JavaMethod.findMethod(JavaMethod.java:90)
	at org.gradle.internal.reflect.JavaMethod.<init>(JavaMethod.java:63)
	at org.gradle.internal.reflect.JavaMethod.<init>(JavaMethod.java:67)
	at org.gradle.internal.reflect.JavaMethod.of(JavaMethod.java:36)
	at org.gradle.api.internal.tasks.testing.testng.TestNGListenerAdapterFactory$AdaptedListener.invoke(TestNGListenerAdapterFactory.java:100)
	at org.gradle.api.internal.tasks.testing.testng.TestNGListenerAdapterFactory$AdaptedListener.invoke(TestNGListenerAdapterFactory.java:95)
```

### Context
When the issue happens it's difficult to find out what's actually wrong with test.

### Steps to Reproduce 
Minimal repository with issue https://github.com/alexei-osipov/gradle-issue-testng-timeout
Run `gradlew test` to reproduce the issue.

### Your Environment
Gradle 7.1, 7.2
TestNG 7.4.0
Java 11.0.10
Windows 10

**Comment by alexei-osipov** [comment]
Problem is reproducible with
TestNG 7.0.0
TestNG 7.4.0

Problem is NOT reproducible with
TestNG 6.14.3
