### ISSUE TITLE
7.3-rc-1: Incubating test framework breaks existing build

### ISSUE THREAD

**Issue by ben-manes** [gradle/gradle#18606]
Updating from 7.2, the build fails immediately when setting the `useTestNG()` on the `test` task.

### Expected Behavior
Continues to work, perhaps with a warning and migration steps if backwards incompatible changes are planned.

```gradle
test {
  useTestNG()
}
```

### Current Behavior
```java
FAILURE: Build failed with an exception.

* Where:
Script '/Users/ben/projects/caffeine/caffeine/testing.gradle' line: 5
...
Caused by: java.lang.IllegalStateException: The value for task ':caffeine:test' property 'testFrameworkProperty' is final and cannot be changed any further.
        at org.gradle.api.internal.provider.AbstractProperty$FinalizedValue.beforeMutate(AbstractProperty.java:489)
        at org.gradle.api.internal.provider.AbstractProperty.assertCanMutate(AbstractProperty.java:263)
        at org.gradle.api.internal.provider.AbstractProperty.setSupplier(AbstractProperty.java:212)
        at org.gradle.api.internal.provider.DefaultProperty.set(DefaultProperty.java:71)
        at org.gradle.api.tasks.testing.Test.useTestFramework(Test.java:979)
        at org.gradle.api.tasks.testing.Test.useTestNG(Test.java:1081)
        at org.gradle.api.tasks.testing.Test.useTestNG(Test.java:1058)
```

### Steps to Reproduce 
Upgrade the `gradle/wrapper/gradle-wrapper.properties` to use `7.3-rc-1` on the [caffeine](https://github.com/ben-manes/caffeine) project.

### Context
The build specifies its universal quality configuration in [codeQuality.gradle](https://github.com/ben-manes/caffeine/blob/master/gradle/codeQuality.gradle) with subproject-specific customization as needed. The most complex customization is in [testing.gradle](https://github.com/ben-manes/caffeine/blob/master/caffeine/testing.gradle) to break up testing into multiple tasks (too large or framework options). Moving these to the incubating test suites feature would be fine, but this should continue to work inho.

**Comment by tresat** [comment]
After investigating, this is actually **not** a regression, but rather a usage which was always disallowed, but happened to "work" (sort of) in earlier versions.  The work to implement test suites surfaced this potential problem, and Gradle was changed to "fail fast" when it occurred, rather than produce unexpected behavior.

Here's what's happening.

If you look at the `Test` task's `options {}` block here: https://docs.gradle.org/7.2/dsl/org.gradle.api.tasks.testing.Test.html#N2F6B3 you can see it says that you shouldn't call `useTestNG()` on a test task **after** setting the options.  This is because the options are potentially different per testing framework used, so setting options "locks in" the choice of framework.  In versions <= 7.2, calling one of the `useXYZFramework()` methods would silently **discard** any previously set options.

In this build, the problem occurs because the `codeQuality.gradle` file, which is the first configuration block to be applied to the `test` task in the caffiene project, sets options on that task like this:

```
options {
    jvmArgs '-XX:SoftRefLRUPolicyMSPerMB=0'
  }
```

and the `testing.gradle` file afterwards configures the `test` task like so:

```
test {
  useTestNG()
  exclude 'com/github/benmanes/caffeine/cache/**'
}
```

At this point Gradle 7.3 confirms that the testing framework hasn't already been locked in, either by setting it explicitly or by configuring options - but it unfortunately **has**, so now the build fails.

Previously, as that jvmArg would **not** have been honored anyway (since options are reset upon selecting a testFramework), it can be safely deleted without changing the build's behavior - or moved to the options configuration further down in the `testing.gradle` file:

```
tasks.withType(Test) {
  if (options instanceof TestNGOptions) {
  ...
```

which will run **after** the testing framework is set.

Hope this clears everything up!

FYI @big-guy

**Comment by ben-manes** [comment]
Thank you @tresat.

It looks like this was a typo as `options` does not have a `jvmArgs` and that is on the test task itself, so this worked by setting the task property and the `options` was safe to throw away. Simply removing the `options` block is a good fix. The change to a hard error is great to avoid surprises.
