### ISSUE TITLE
org.gradle.testfixtures.ProjectBuilder + Test Distribution are not compatible with JDK 17 and Gradle 7.3-rc.1

### ISSUE THREAD

**Issue by rpalcolea** [gradle/gradle#18647]
Hi folks, 

I found that running tests that use `org.gradle.testfixtures.ProjectBuilder` + JDK 17 + test distribution (local or remote agents) results in the following:

```
[com.gradle.enterprise.testdistribution] Test was part of session 2 and ran on a local executor named 'localhost-executor-1' on host 'localhost'.

Could not inject synthetic classes.
org.gradle.api.GradleException: Could not inject synthetic classes.
	at app//org.gradle.initialization.DefaultLegacyTypesSupport.injectEmptyInterfacesIntoClassLoader(DefaultLegacyTypesSupport.java:91)
	at app//org.gradle.testfixtures.internal.ProjectBuilderImpl.getGlobalServices(ProjectBuilderImpl.java:181)
	at app//org.gradle.testfixtures.internal.ProjectBuilderImpl.createProject(ProjectBuilderImpl.java:112)
	at app//org.gradle.testfixtures.ProjectBuilder.build(ProjectBuilder.java:120)
	at app//nebula.test.AbstractProjectSpec.setup(AbstractProjectSpec.groovy:42)
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: module java.base does not open java.lang to unnamed module @7825f19b
	at app//org.gradle.internal.classloader.ClassLoaderUtils$AbstractClassLoaderLookuper.invoke(ClassLoaderUtils.java:150)
	at app//org.gradle.internal.classloader.ClassLoaderUtils$LookupClassDefiner.defineClass(ClassLoaderUtils.java:206)
	at app//org.gradle.internal.classloader.ClassLoaderUtils.define(ClassLoaderUtils.java:77)
	at app//org.gradle.initialization.DefaultLegacyTypesSupport.injectEmptyInterfacesIntoClassLoader(DefaultLegacyTypesSupport.java:88)
	... 4 more
Caused by: java.lang.IllegalAccessException: module java.base does not open java.lang to unnamed module @7825f19b
	at java.base@17/java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:259)
	at app//org.gradle.internal.classloader.ClassLoaderUtils$AbstractClassLoaderLookuper.getLookupForClassLoader(ClassLoaderUtils.java:159)
	at app//org.gradle.internal.classloader.ClassLoaderUtils$AbstractClassLoaderLookuper.invoke(ClassLoaderUtils.java:146)
	... 7 more

``` 

You can find a reproducible here: https://github.com/nebula-plugins/gradle-nebula-integration/tree/master/gradle-jdk17-issues. The interesting part is that only one test fails

### Your Environment

Operating system | Mac OS X 11.4 |  
-- | -- | --
CPU cores | 16 cores |  
Max Gradle workers | 16 workers |  
Java runtime | Azul OpenJDK Runtime Environment 17+35-LTS |  
Java VM | Azul OpenJDK 64-Bit Server VM 17+35-LTS (mixed mode) |  

### Screen recording

https://user-images.githubusercontent.com/1625920/137353115-ffdfeb39-3d31-4855-945d-816477c69dee.mov

**Comment by snoopcheri** [comment]
### Analysis from the Test Distribution team

We could reproduce this problem with JDK 16 and above. It is also not related to Gradle `7.3-rc-1`. The test also fails with Gradle `7.2`.

The reason for the observed problem is, that the Gradle's test fixture `ProjectBuilder` injects empty interfaces into the class loader for backwards compatibility of older plugins (see [here](https://github.com/gradle/gradle/blob/4a482a4c36576fafe8398e4717bd779f7f76a3e5/subprojects/base-services/src/main/java/org/gradle/internal/jvm/JpmsConfiguration.java#L39-L42)). Gradle's Vanilla test executor opens the modules `java/util` and `java/lang` for internal reasons (see [here](https://github.com/gradle/gradle/blob/4a482a4c36576fafe8398e4717bd779f7f76a3e5/subprojects/base-services/src/main/java/org/gradle/internal/jvm/JpmsConfiguration.java#L39-L42)).

The Test Distribution Gradle plugin replaces Gradle's test executor with its own version. This version does not openJava modules on purpose.

* For JDK 15 and below this is not a problem, because `--illegal-access=permit` is set by default.
* JDK 16 changes the default value to `--illegal-access=deny`. That's why manually opening the modules with `--add-opens` is required. You could also overwrite the default value `--illegal-acccess=permit`.
* For JDK 17 and above, `--illegal-access` is basically a no-op. Therefore, opening the modules manually is required there.

We will document this fact in the [troubleshooting section](https://docs.gradle.com/enterprise/test-distribution-gradle-plugin/#dealing_with_common_problems) of the Test Distribution Gradle plugin.

**Comment by remal** [comment]
Reproducible on Gradle 7.5 and JDK 11.

**Comment by marcphilipp** [comment]
@remal Could you please post a stacktrace or, preferably, a link to a Build Scan?

**Comment by marcphilipp** [comment]
@gradle/bt-support I think it should be documented that `ProjectBuilder` requires this flag. WDYT?

**Comment by remal** [comment]
@marcphilipp besides documenting the requirement, I think it makes sense to catch the exception and add some meaningful message with a link to docs or smth like this. WDYT?

**Comment by dmdashenkov** [comment]
Hi. Are there updates for this? I'm having the same issue with Gradle v7.6.1 and JDK 19.

**Comment by armiol** [comment]
Any updates?
