### ISSUE TITLE
Reporting of failures of nested "suites" drops class name

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#18682]
When a nested "suite" reports an error before any of its children are started, it is currently reported as a standalone test class in the default package instead of belonging to the test class it is declared in.

### Expected Behavior

The failing "suite" method is reported as a child of its test class.

**build/reports/tests/test/classes/org.example.LibraryTest.html**
<img width="745" alt="image" src="https://user-images.githubusercontent.com/214207/137734424-9ceb37e5-6a86-4974-862f-e78e86c3c97c.png">

**build/test-results/test/TEST-org.example.LibraryTest.xml**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.example.LibraryTest" tests="1" skipped="0" failures="1" errors="0" timestamp="2021-10-18T12:45:14" hostname="Marcs-MBP-2.fritz.box" time="0.41">
  <properties/>
  <testcase name="nested suite" classname="org.example.LibraryTest" time="0.41">
    <failure message="java.lang.RuntimeException: boom" type="java.lang.RuntimeException">java.lang.RuntimeException: boom
	at org.example.LibraryTest.params(LibraryTest.groovy:24)
	at org.example.LibraryTest.nested suite(LibraryTest.groovy:20)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
```

### Current Behavior

The failing "suite" method is reported as a standalone test class in the default package.

**build/reports/tests/test/classes/nested#20suite.html**
<img width="765" alt="image" src="https://user-images.githubusercontent.com/214207/137733378-75245cb6-1311-4721-a4a7-11f671c0f376.png">

**build/test-results/test/TEST-nested#20suite.xml**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="nested suite" tests="1" skipped="0" failures="1" errors="0" timestamp="2021-10-18T12:45:14" hostname="Marcs-MBP-2.fritz.box" time="0.049">
  <properties/>
  <testcase name="failed to execute tests" classname="nested suite" time="0.049">
    <failure message="java.lang.RuntimeException: boom" type="java.lang.RuntimeException">java.lang.RuntimeException: boom
	at org.example.LibraryTest.params(LibraryTest.groovy:24)
	at org.example.LibraryTest.nested suite(LibraryTest.groovy:20)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
```

### Context

That neither XML nor HTML report point to the test class is confusing when investigating why the test task failed.

### Steps to Reproduce 

1. clone https://github.com/marcphilipp/gradle-sandbox
2. `cd nested-suite-reporting`
3. `./gradlew test`

### Your Environment

Build scan URL: https://scans.gradle.com/s/vv6gjegf2pc5g

**Comment by marcphilipp** [comment]
Still relevant.

**Comment by octylFractal** [comment]
This was resolved with #32672.
