### ISSUE TITLE
Print better error message when Gradle wrapper class loader fails to load classes

### ISSUE THREAD

**Issue by dsaff** [gradle/gradle#18683]
### Expected Behavior

[nsjail](https://github.com/google/nsjail) is a tool that creates a cloned namespace on Linux, in our case to be 100% sure no plugins are using the host system's network.  When gradle is run under nsjail with what seem to us to be the right set of options (details below), it should produce the same build results as it would on a computer that has been disconnected from the network at the hardware level.

### Current Behavior

More details in steps to reproduce below, but when any gradle build is run under nsjail, it throws this stacktrace:

```
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.gradle.internal.concurrent.CompositeStoppable.<clinit>(CompositeStoppable.java:37)
	at org.gradle.internal.classloader.ClassLoaderUtils.tryClose(ClassLoaderUtils.java:51)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:64)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:590)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:523)
	... 12 more
```

### Context

We need to run our CI builds with 0 network activity, for reproducibility and security reasons, among others.  The --offline flag helps with this, but it is not enforced (for example, kotlin-native will download dependencies [ignoring --offline](https://youtrack.jetbrains.com/issue/KT-49247) ).  So we'd like to use OS-level tools, like nsjail, to guarantee offline building.

### Steps to Reproduce 

1) Checkout and build [nsjail](https://github.com/google/nsjail)
2) export NSJAIL=path/to/bin/nsjail
3) unpack the attached tarball project [gradle-minimal.tar.gz](https://github.com/gradle/gradle/files/7366062/gradle-minimal.tar.gz)
4) ./nsjail.sh ./gradlew tasks

### Your Environment

uname -a = 5.10.46-4rodete4-amd64 #1 SMP Debian 5.10.46-4rodete4 (2021-09-06) x86_64 GNU/Linux

I can't think of much else that's relevant, but happy to add more.

**Comment by jbartok** [comment]
Could you pls. send us a Docker based reproducer to make investigating this a bit easier?

**Comment by donat** [comment]
Sorry for the late reply; I meant `~/.gradle`.

**Comment by dsaff** [comment]
FWIW, I discovered that the problem is not permissions.  It's file descriptors.  If I add --rlimit_nofile=soft to the shell script, then the build continues.  I think that gradle's classloader is using more than 32 file descriptors (the nsjail default), and this is leading classloading to fail.  Then, when classloading fails, the exception handling logic tries to load a logging class, which then throws a new error obscuring the original error.

Would a proposed fix for this classloader error reporting issue be of interest?
