### ISSUE TITLE
Feedback on TYPESAFE_PROJECT_ACCESSORS: rootProject naming

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#18971]
Feedback on enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

### Expected Behavior
rootProject.name = "net.twisterrob.foo" just works.

### Current Behavior
Adding `enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")` to my projects fails the build:
```
org.gradle.api.InvalidUserDataException: Cannot generate project dependency accessors:
  - Cannot generate project dependency accessors because project 'net.twisterrob.foo' doesn't follow the naming convention: [a-zA-Z]([A-Za-z0-9\-_])*
> Cannot generate project dependency accessors:
    - Cannot generate project dependency accessors because project 'net.twisterrob.foo' doesn't follow the naming convention: [a-zA-Z]([A-Za-z0-9\-_])*

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
java.lang.RuntimeException: org.gradle.api.InvalidUserDataException: Cannot generate project dependency accessors:
  - Cannot generate project dependency accessors because project 'net.twisterrob.foo' doesn't follow the naming convention: [a-zA-Z]([A-Za-z0-9\-_])*
	at org.gradle.api.internal.catalog.DefaultDependenciesAccessors.generateAccessors(DefaultDependenciesAccessors.java:140)
	at org.gradle.configuration.BuildTreePreparingProjectsPreparer.generateDependenciesAccessorsAndAssignPluginVersions(BuildTreePreparingProjectsPreparer.java:87)
	at org.gradle.configuration.BuildTreePreparingProjectsPreparer.prepareProjects(BuildTreePreparingProjectsPreparer.java:54)
	at org.gradle.configuration.BuildOperationFiringProjectsPreparer$ConfigureBuild.run(BuildOperationFiringProjectsPreparer.java:52)
	at org.gradle.configuration.BuildOperationFiringProjectsPreparer.prepareProjects(BuildOperationFiringProjectsPreparer.java:40)
	at org.gradle.initialization.VintageBuildModelController.lambda$prepareProjects$1(VintageBuildModelController.java:93)
	...
Caused by: org.gradle.api.InvalidUserDataException: Cannot generate project dependency accessors:
  - Cannot generate project dependency accessors because project 'net.twisterrob.foo' doesn't follow the naming convention: [a-zA-Z]([A-Za-z0-9\-_])*
	at org.gradle.api.internal.catalog.DefaultDependenciesAccessors.assertCanGenerateAccessors(DefaultDependenciesAccessors.java:195)
	at org.gradle.api.internal.catalog.DefaultDependenciesAccessors.writeProjectAccessors(DefaultDependenciesAccessors.java:149)
	at org.gradle.api.internal.catalog.DefaultDependenciesAccessors.generateAccessors(DefaultDependenciesAccessors.java:137)
	... 121 more
```
(also note the double-messaging on top, but that's a different issue)

### Workaround
Mandatory definition of rootProject.name
Follow the strict naming and use a different separator.

### Context
In Gradle 4.x you deprecated forbidden characters.
In Gradle 5 you have removed support for "forbidden" characters: #6915
All my personal projects follow the naming convention: "net.twisterrob.x", they're in the same named GitHub repos.
They're all in the Java ecosystem ([group ID](https://maven.apache.org/guides/mini/guide-naming-conventions.html)) or Android apps ([application ID](https://developer.android.com/studio/build/configure-app-module)).
`rootProject.name` is either explicitly set or is inferred from the repository name (as `git clone` creates the same named folder by default).
In my 8 years Gradle usage I never needed to reference `project(":")` in my or seen in others' builds.

These facts leave me in a bad place: I cannot use the conventional name for the projects because of a limitation on an arbitrary thing, that doesn't even get used in any of my projects.

### More background
_Please don't make `rootProject.name` mandatory for the TYPESAFE_PROJECT_ACCESSORS feature. We developers want to use tools, not the tools let use us._

Note that while the recommendation is to define `rootProject.name` I frequently omit it, because it's better without it.
 * When I import a project in IntelliJ IDEA, it uses `rootProject.name` in the title bar, which means that having multiple clones open in different window (of the same project) gives me immediate disambiguation of projects.
 * The same happens for logs, or errors, because if the rootProject.name is mentioned anywhere they'll inherit the folder name and immediately help figure out which one it is.
 * if there's a defined `rootProject.name` and it's different than the folder name there's extra noise in IntelliJ IDEA Project view:

| folder net.twisterrob.gradle, `rootProject.name = "net.twisterrob.gradle"` (or omitted) | folder net.twisterrob.gradle, `rootProject.name = "net-twisterrob-gradle"` to satisfy type-safe accessors |
| - | - |
| ![image](https://user-images.githubusercontent.com/2906988/141660481-46b23647-8767-40b3-8c3a-5454d740d6f9.png) | ![image](https://user-images.githubusercontent.com/2906988/141660472-88f1c647-5d66-4285-941c-5fa7cc01e3cd.png) |

### Recommendations

---

#### Alternative 1: camels FTW
Based on
> A project name with kebab case (some-lib) or snake case (some_lib) will be converted to camel case in accessors: projects.someLib. -- [docs](https://docs.gradle.org/7.0/userguide/declaring_dependencies.html#sec:type-safe-project-accessors)

Treat `.` the same as `_` or `-` and camel-case along it.
Treat ` ` the same as `_` or `-` and camel-case along it.
These come naturally,
also, potentially rinse and repeat for any other non-forbidden (by org.gradle.util.internal.NameValidator), but unsupported (by Kotlin) character.

---

#### Alternative 2: backticks
Kotlin has a built-in syntax for reference special names, Gradle is using Kotlin. I don't see why ``projects.`special-name``` is bad. If someone wants to use their names like that, let them.

---

#### Alternative 3: well-known name
Alternatively for `rootProject` generate a type-safe accessor with a well-known name: e.g. `projects.root` or `projects.projectRoot` or `projects.rootProject`.
If there's a conflict with one of the subProjects, error out, or warn and omit the accessor.

---

Mix of the above 3? 🤞

### References
Type-safe accessors documentation: https://docs.gradle.org/7.0/userguide/declaring_dependencies.html#sec:type-safe-project-accessors
Maven Group ID docs: https://maven.apache.org/guides/mini/guide-naming-conventions.html
Android Application ID docs: https://developer.android.com/studio/build/configure-app-module
Discussion on disallowing spaces in `rootProject.name`: https://discuss.gradle.org/t/space-character-in-build-name/24164/2?u=twisterrob

**Comment by TWiStErRob** [comment]
Hmm, is it possible that Alternative 3 is already implemented (chosen name: `gradle`) and the name validation check is a left-over from an early implementation?

**Comment by TWiStErRob** [comment]
@ljacomet what are your thoughts on the above? I understand implementation might be low priority, but please express opinion at least and you might get a contribution. 🤞🏻

**Comment by ov7a** [comment]
Sorry for the late reply.

The issue is in the backlog of the relevant team and is prioritized by them.

***

We are aware of multiple issues in that area and [plan to address them](https://github.com/gradle/gradle/issues/24295#issuecomment-2250291176) but unfortunately, we don't have the capacity for that right now. And we don't accept contributions in that area for now.
