### ISSUE TITLE
DefaultTestResult incorrectly reports number of (failed) test for JUnit Platform engine initialization related errors

### ISSUE THREAD

**Issue by szpak** [gradle/gradle#18992]
Since Gradle [6.7](https://github.com/gradle/gradle/pull/13879), thanks to @marcphilipp, the test engine initialization errors are properly presented in the generated test report. However, it turns out, that `DefaultTestResult` still reports 0 as total (and failed) test count which makes it harder to detect test misconfiguration in Gradle (see https://github.com/gradle/gradle/issues/7452 for context).

### Expected Behavior

`DefaultTestResult` for the "artificial" `Gradle Test Executor X` test, reports 1 as total (and failed) test count to be consistent with the generated test report.

### Current Behavior

`DefaultTestResult` for also for "artificial" `Gradle Test Executor X` reports 0 as total (and failed) test count.

```
$ gw check

> Task :test FAILED
Execute 'Gradle Test Executor 20' 0 test(s)
Execute 'Gradle Test Run :test' 0 test(s)

FAILURE: Build failed with an exception.
...
```
It is inconsistent with:
![image](https://user-images.githubusercontent.com/148013/141864361-621573ed-69ba-44cf-b6c6-fc345d114d01.png)

```
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 20.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:63)
	at java.base@15.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@15.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base@15.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@15.0.2/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: org.junit.platform.commons.JUnitException: TestEngine with ID 'spock' failed to discover tests
	at app//org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:111)
	at app//org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:85)
	at app//org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:92)
	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	... 18 more
Caused by: groovy.lang.MissingMethodException: No signature of method: SpockConfig.broken() is applicable for argument types: (SpockConfig$_run_closure1) values: [SpockConfig$_run_closure1@30e03755]
Possible solutions: run(), run(), grep(), grep(java.lang.Object)
	at app//org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
	at app//org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:80)
	at app//org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at app//org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at app//org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at SpockConfig.run(SpockConfig.groovy:1)
	at app//org.spockframework.builder.DelegatingScriptBlueprint.evaluate(DelegatingScriptBlueprint.java:36)
	at app//org.spockframework.builder.Sculpturer.$form(Sculpturer.java:33)
	at app//org.spockframework.builder.GestaltBuilder.build(GestaltBuilder.java:19)
	at app//org.spockframework.runtime.ConfigurationBuilder.build(ConfigurationBuilder.java:30)
	at app//org.spockframework.runtime.RunContext.start(RunContext.java:59)
	at app//org.spockframework.runtime.RunContext.get(RunContext.java:167)
	at app//org.spockframework.runtime.SpockEngine.discover(SpockEngine.java:21)
	at app//org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:103)
	... 25 more
```

### Context

Presented in the short issue description - see also https://github.com/gradle/gradle/issues/7452.

### Steps to Reproduce 

Call `./gradlew test` in the following project:
TODO

There should be at least `DefaultTestResult` instante with 1 as total (and failed) test count.

Btw, that test is generated with Spock as I hit it in that configuration, but could be replaced with anything that triggers the JUnit Platform engine initialization error.

### Your Environment

Tested with Gradle 6.9 and .7.3.

**Comment by octylFractal** [comment]
I would prefer having the report show 0 tests, rather than changing the console to match, but that may not be possible depending on how the report is made.

**Comment by szpak** [comment]
> I would prefer having the report show 0 tests, rather than changing the console to match, but that may not be possible depending on how the report is made.

@octylFractal How would you like to detect that kind of low level errors vs misconfigured tests which are not executed at all without exposing that 1 failing test? See #7452 for the context and #13879 which made them not longer hidden.

**Comment by octylFractal** [comment]
My preference, if possible (I have not looked into the code) is that this would be reported as an execution failure, and no report would be generated, i.e. it would act like any other task where an unexpected failure occurs. The "test" here is not really a test, it is just an artificial entry representing the failure of a test executor. As for your reproducer, I would expect `afterSuite` to not be run at all in this case.

**Comment by szpak** [comment]
> and no report would be generated, i.e. it would act like any other task where an unexpected failure occurs.

The problem I see, is to get the failure reason - in my case some Spock misconfiguration. Should it be included in the general stacktrace (`-s`)?

**Comment by szpak** [comment]
I've just retested it with Gradle 7.5.1 and Spock 2.3 (which pulls in newer JUnit Platform) and the result is the same:

```
$ gw test

> Task :test FAILED
Execute 'Gradle Test Executor 4' 0 test(s)
Execute 'Gradle Test Run :test' 0 test(s)
```

It would be better to be able to detect failure using the `result.testCount` value.
