### ISSUE TITLE
AdoptOpenJdkRemoteBinary.determineArch fails on AIX, Linux PPCLE and Windows

### ISSUE THREAD

**Issue by quijote** [gradle/gradle#19295]
AdoptOpenJdkRemoteBinary.determineArch fails on AIX, Linux PPCLE and Windows

I am using Gradle 7.3 to build a library with Java 11 toolchain:

```
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}
```

I wanted to use auto-download:

```
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=true
```

This works on Linux x86 but failed on AIX, Linux PPCLE and Windows with the following error:

```
Caused by: org.gradle.internal.nativeintegration.NativeIntegrationUnavailableException: SystemInfo is not supported on this operating system.
	at org.gradle.internal.nativeintegration.services.NativeServices$BrokenService.invoke(NativeServices.java:445)
	at com.sun.proxy.$Proxy52.getArchitecture(Unknown Source)
	at org.gradle.jvm.toolchain.install.internal.AdoptOpenJdkRemoteBinary.determineArch(AdoptOpenJdkRemoteBinary.java:105)
	at org.gradle.jvm.toolchain.install.internal.AdoptOpenJdkRemoteBinary.toFilename(AdoptOpenJdkRemoteBinary.java:90)
	at org.gradle.jvm.toolchain.install.internal.DefaultJavaToolchainProvisioningService.provisionInstallation(DefaultJavaToolchainProvisioningService.java:72)
	at org.gradle.jvm.toolchain.install.internal.DefaultJavaToolchainProvisioningService.tryInstall(DefaultJavaToolchainProvisioningService.java:67)
	at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.downloadToolchain(JavaToolchainQueryService.java:88)
	at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.lambda$query$3(JavaToolchainQueryService.java:84)
	at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService$$Lambda$1195.00000000298E7670.get(Unknown Source)
	at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.query(JavaToolchainQueryService.java:84)
	at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.lambda$findMatchingToolchain$0(JavaToolchainQueryService.java:62)
	at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService$$Lambda$804.000000002647F4F0.apply(Unknown Source)
	at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.lambda$findMatchingToolchain$1(JavaToolchainQueryService.java:62)
	at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService$$Lambda$570.0000000025E5F390.call(Unknown Source)
	at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:66)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
	at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:64)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
	at org.gradle.api.internal.provider.MappingProvider.calculateOwnValue(MappingProvider.java:55)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.withFinalValue(AbstractMinimalProvider.java:151)
	at org.gradle.api.internal.provider.DefaultProperty.finalValue(DefaultProperty.java:133)
	at org.gradle.api.internal.provider.DefaultProperty.finalValue(DefaultProperty.java:26)
	at org.gradle.api.internal.provider.AbstractProperty.finalizeNow(AbstractProperty.java:236)
	... 187 more

```

Debug logs show the following:

AIX:
```
2021-12-13T16:45:25.757+0100 [DEBUG] [org.gradle.internal.nativeintegration.services.NativeServices] Native-platform is not available.
net.rubygrapefruit.platform.NativeIntegrationUnavailableException: Native integration is not available for AIX ppc64.
	at net.rubygrapefruit.platform.internal.Platform.getLibraryName(Platform.java:117)
	at net.rubygrapefruit.platform.Native.init(Native.java:56)
	at org.gradle.internal.nativeintegration.services.NativeServices.initializeNativeIntegrations(NativeServices.java:170)
	at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:155)
	at org.gradle.internal.nativeintegration.services.NativeServices.initializeOnClient(NativeServices.java:135)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:42)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:240)
	at org.gradle.launcher.Main.doAction(Main.java:35)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
```

Linux PPCLE:
```
2021-12-13T15:50:01.832+0000 [DEBUG] [org.gradle.internal.nativeintegration.services.NativeServices] Native-platform is not available.
net.rubygrapefruit.platform.NativeIntegrationUnavailableException: Native integration is not available for Linux ppc64le.
	at net.rubygrapefruit.platform.internal.Platform.getLibraryName(Platform.java:117)
	at net.rubygrapefruit.platform.Native.init(Native.java:56)
	at org.gradle.internal.nativeintegration.services.NativeServices.initializeNativeIntegrations(NativeServices.java:170)
	at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:155)
	at org.gradle.internal.nativeintegration.services.NativeServices.initializeOnClient(NativeServices.java:135)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:42)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:240)
	at org.gradle.launcher.Main.doAction(Main.java:35)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
```

Windows:
```
2021-12-13T16:45:49.054+0100 [DEBUG] [org.gradle.internal.nativeintegration.services.NativeServices] Native-platform is not available.
net.rubygrapefruit.platform.NativeIntegrationLinkageException: Native library 'native-platform.dll' could not be loaded for Windows Server 2016 amd64.
	at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:61)
	at net.rubygrapefruit.platform.Native.init(Native.java:56)
	at org.gradle.internal.nativeintegration.services.NativeServices.initializeNativeIntegrations(NativeServices.java:170)
	at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:155)
	at org.gradle.internal.nativeintegration.services.NativeServices.initializeOnClient(NativeServices.java:135)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:42)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:240)
	at org.gradle.launcher.Main.doAction(Main.java:35)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\labuser\.gradle\native\e1d6ef7f7dcc3fd88c89a11ec53ec762bb8ba0a96d01ffa2cd45eb1d1d8dd5c5\windows-amd64-min\native-platform.dll: Access is denied
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:51)
	... 25 more
```

Error seems to come from here:
https://github.com/gradle/gradle/blob/b67064e9c4ff9c720023964c4adc6476066d08ec/subprojects/native/src/main/java/org/gradle/internal/nativeintegration/services/NativeServices.java#L445

Originating from here:
https://github.com/gradle/gradle/blob/b67064e9c4ff9c720023964c4adc6476066d08ec/subprojects/native/src/main/java/org/gradle/internal/nativeintegration/services/NativeServices.java#L321

Actual OS detection seems to happen here:
https://github.com/gradle/native-platform/tree/8a0dc3935d24ab119d0b87d9b3c76cbd5257594b/native-platform/src/main/cpp

I am unsure if this behavior is expected from `native-platform`. I am also unsure if it is necessary to run native code before downloading a JVM. An alternative could be to detect OS from system properties `os.name`, `os.version` and `os.arch`. See below for actual values on my test systems.

For completeness I will also mention that I got the same error on Solaris x86 and Solaris SPARC. But there is no AdoptOpenJDK for those platforms. Gradle could however also download a JVM from some other vendor with Solaris support (like Liberica JDK). 

### Expected Behavior
AdoptOpenJDK does provide JVMs for all those platforms. I expected that Gradle downloads the correct JVM and uses it during the build.

### Current Behavior
Download fails with exception above.

### Your Environment

The following shows available system properties on each OS:

AIX
```
os.name = AIX
os.version = 7.1
os.arch = ppc64
```

Linux PPCLE
```
os.name = Linux
os.version = 5.11.0-40-generic
os.arch = ppc64le
```

Windows:
```
os.name = Windows Server 2016
os.version = 10.0
os.arch = amd64
```

**Comment by romani** [comment]
run into this problem , here is link to build https://app.travis-ci.com/github/sevntu-checkstyle/checkstyle-samples/builds/249768273#L258

**Comment by uschindler** [comment]
It also fails in the same way for S390x platforms.

**Comment by siom79** [comment]
It also fails on Raspberry Pi with gradle 8.0.1.

**Comment by Richard-Rogalski** [comment]
Running into this on ppc64le. Why does it even need to download a JDK, when I have several installed? Is there not even a workaround for this?

**Comment by quijote** [comment]
@Richard-Rogalski: If you have the correct JDK installed already, you can use it by e.g. putting the following into `gradle.properties`:
```
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.fromEnv=JAVA_HOME_17
```

**Comment by quijote** [comment]
I verified this week that this problem still exists in Gradle 8.5 on Linux PPC64, Linux PPC64LE, Linux s390x, Solaris SPARC, Solaris x86 and AIX.

**Comment by quijote** [comment]
I have not contributed to Gradle source code before and I am not yet familiar with the processes. 

But I made auto-download work now on some Linux PPC64, Linux PPC64LE, Linux s390x, Solaris SPARC, Solaris x86 and AIX machines by first patching Gradle master, and then writing my own `JavaToolchainResolver`.

I introduced AIX in enum `org.gradle.platform.OperatingSystem` and `org.gradle.internal.os.OperatingSystem`.

I also extended enum `org.gradle.platform.Architecture` by `PPC64`, `PPC64LE`, `S390X`, and `SPARC_V9`.

Toolchain provisioning code is now independent from OS support in `net.rubygrapefruit.platform.SystemInfo`.

https://github.com/quijote/gradle/tree/patch-2
https://github.com/quijote/gradle/commit/d290d1b1bc815502695886330d5ece7ec6d5befa

**Comment by cobexer** [comment]
Sorry for the late reply!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.
***
@gradle/bt-jvm please also note there is a pr:
* #27293

**Comment by Tingel24** [comment]
> There is a workaround available: provision a compatible JVM first and then it should be detected and used as expected.

@cobexer Could you elaborate on the workaround? I do not know how to provision a JVM and was not able to research how that might be done. I am currently trying to get Gradle running on a RaspberryPi4.

**Comment by big-guy** [comment]
@gradle/bt-architecture-council what should our policy be for supporting these architectures?

**Comment by Richard-Rogalski** [comment]
yeah..... I have the correct JDK already. I do not want any build tool downloading an executable JDK on my machine. Is there a flag or something I can pass to make gradle **never** pull in a JDK or any other machine code, and always use things provided by the base system??

**Comment by octylFractal** [comment]
There is not a flag for "any other machine code", but you can set [`org.gradle.java.installations.auto-download=false`](https://docs.gradle.org/current/userguide/toolchains.html#sub:disable_auto_provision).

**Comment by jvandort** [comment]
Fixed by https://github.com/gradle/gradle/pull/27293

**Comment by ljacomet** [comment]
RE-opening as we need to revert the changes for 8.11

**Comment by octylFractal** [comment]
In order to make this work better, I want to make changes to how `Architecture` is implemented, however even though it's incubating it's in heavy use by the Foojay resolver plugin, and I'd rather not introduce incompatible changes to it in a minor version. So I've marked this for 9.0 and will work on it later.
