### ISSUE TITLE
NamedObjectDomainContainer does not properly instantiate named managed types

### ISSUE THREAD

**Issue by akainth015** [gradle/gradle#19460]
I have a `NamedObjectDomainContainer` defined in an `Extension` as follows.

```kotlin
abstract class TapePluginExtension @Inject constructor(projectLayout: ProjectLayout) {
    @get:Input
    abstract val dimensions: NamedDomainObjectContainer<Dimension>
```

`Dimension` is a named managed type, defined as follows.
```kotlin
abstract class Dimension @Inject constructor() : Named {
    @get:Input
    abstract var baseUnit: Property<TapeUnit>

    @get:Input
    abstract var units: NamedDomainObjectContainer<TapeUnit>

    @get:Inject
    abstract val objectFactory: ObjectFactory

    fun baseUnit(baseUnitName: String, singular: String = baseUnitName): TapeUnit
```

### Expected Behavior
I would expect that the following code runs without issue.
```kotlin
        dimensions.apply {
            create("Time").apply {
                baseUnit("seconds", "second")
                units.apply {
                    create("minute").apply {
                        singularName.set("foot")
                        ratioToBase.set(60.0)
                    }
                    create("inches").apply {
                        singularName.set("inch")
                        ratioToBase.set(60.0 * 60.0)
                    }
                }
            }
        }
```

### Current Behavior
Instead of running correctly, the code fails with the following exception (in short, the `Dimension` returned by `create("Time")` does not initialize the `Property` and `NamedDomainObjectContainer`, causing a `NullPointerException` at the `baseUnit` function call (line 3).

```
java.lang.NullPointerException: Cannot invoke "org.gradle.api.provider.Property.set(Object)" because the return value of "me.akainth.tape.Dimension.getBaseUnit()" is null
	at me.akainth.tape.Dimension.baseUnit(Dimension.kt:30)
	at me.akainth.tape.TapePluginExtension$length$2.invoke(TapePluginExtension.kt:35)
	at me.akainth.tape.TapePluginExtension$length$2.invoke(TapePluginExtension.kt:32)
```

### Context
This issue is a bit of a pain, since I would prefer to use a managed type instead of having to rewrite the DSL later on. You may have also noticed all the `.apply` calls in the code above. That's because the Gradle API doesn't appear to be working with Kotlin 1.5.31, but that's a separate issue.

### Steps to Reproduce 
[This branch](https://github.com/akainth015/tape/tree/gradle7) contains the code that I am working on, which may be used a test-bed for this issue.

### Your Environment

Build scan URL: https://scans.gradle.com/s/oanlviesrwoyc

**Comment by ljacomet** [comment]
What is the result if you use plain Java instead of Kotlin for these types?
