### ISSUE TITLE
Support multiple --group for TaskReportTask

### ISSUE THREAD

**Issue by apalopta** [gradle/gradle#19509]
### One should be able to pass several groups to the task report task

Working with complex builds and many subprojects you might give hints which tasks are the most convenient for a project.
Often tasks from several groups are important.

### Current Behavior
Currently you can display one group only or _all_ groups. Nothing in between.

### Context

I am writing example projects for my colleagues.
Each combines various topics of interest.
Those example projects shall display only tasks of groups that are important for that specfic use case.
Those tasks are not always contained in one single group.
It would be nice to have all examples in one repository and make each project display the essential stuff.

I'd appreciate an interface similar to _--tests_ which is a repeatable option.

*edit*
I could try to do it by myself with a little help...

**Comment by jbartok** [comment]
Thanks for volunteering, contributions are always welcome. Consider adding a `groups` (notice the plural, as opposed to current singular) option to `TaskReportTask` with a `List<String>` type. We also need to preserve the old option so that we don't introduce a breaking change.

**Comment by apalopta** [comment]
I just started to dig into the issue, forked and tried a first build.
However, I am facing trouble with the build. It fails with:

```
Caused by: org.gradle.api.internal.artifacts.configurations.ResolveExceptionWithHints: Could not resolve all dependencies for configuration ':build-logic-commons:build-scan:compileClasspath'.
The project declares repositories, effectively ignoring the repositories you have declared in the settings.
You can figure out how project repositories are declared by configuring your build to fail on project repositories.
See https://docs.gradle.org/7.5-20220113070244+0000/userguide/declaring_repositories.html#sub:fail_build_on_project_repositories for details.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.failuresWithHint(DefaultConfiguration.java:759)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1498)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$3800(DefaultConfiguration.java:160)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$DefaultResolutionHost.rethrowFailure(DefaultConfiguration.java:2212)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.visitDependencies(DefaultConfiguration.java:1462)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:114)
        at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmptyEdges.getNodeValues(CachingDirectedGraphWalker.java:213)
        at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:121)
        at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:73)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:69)
        ... 254 more
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.gradle:gradle-enterprise-gradle-plugin:3.8.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/com/gradle/gradle-enterprise-gradle-plugin/3.8/gradle-enterprise-gradle-plugin-3.8.pom
If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
Required by:
    project :build-logic-commons:build-scan
```

I am somehow lost.
No changes to the code done yet, built on Windows, JDK 11.

Did I miss any further documentation?
