### ISSUE TITLE
JVM argument -Djava.net.preferIPv4Stack is not passed to the java process starting gradle

### ISSUE THREAD

**Issue by ogmios-voice** [gradle/gradle#19534]
### Expected Behavior
Gradle script should start the java process along w/ the specified `-Djava.net.preferIPv4Stack` parameter.

### Current Behavior
from `daemon-....out.log`: argument not present:
```
[INFO] [org.gradle.launcher.daemon.server.Daemon] start() called on daemon - DefaultDaemonContext[...,daemonOpts=-XX:+CMSClassUnloadingEnabled,-Xms123m,-Xmx456m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant]
```

### Context
Trying to use gradle behind a VPN that does not support IPv6.

**Note**: please, also extend https://docs.gradle.org/current/userguide/troubleshooting.html#network_connection w/ the usually VPN related issue: **java.net.BindException: Cannot assign requested address: Cannot bind**:

from `daemon-....out.log`:
```
[...]
[DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding IP addresses for network interface Software Loopback Interface 1
[DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Is this a loopback interface? true
[DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding loopback address /127.0.0.1
[DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding loopback address /0:0:0:0:0:0:0:1
[...]
[INFO] [org.gradle.launcher.daemon.server.DaemonRegistryUpdater] Advertising the daemon address to the clients: [..., addresses:[localhost/127.0.0.1]]
[DEBUG] [org.gradle.launcher.daemon.server.DaemonRegistryUpdater] Advertised daemon context: DefaultDaemonContext[uid=...,javaHome=...,daemonRegistryDir=...,pid=...,idleTimeout=120000,priority=NORMAL,daemonOpts=-XX:+CMSClassUnloadingEnabled,-Xms123m,-Xmx456m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant]
[DEBUG] [org.gradle.launcher.daemon.registry.PersistentDaemonRegistry] Storing daemon address: [..., addresses:[localhost/127.0.0.1]], context: DefaultDaemonContext[uid=...,javaHome=...,daemonRegistryDir=...,pid=...,idleTimeout=120000,priority=NORMAL,daemonOpts=-XX:+CMSClassUnloadingEnabled,-Xms123m,-Xmx456m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant]
Daemon vm is shutting down... The daemon has exited normally or was terminated in response to a user interrupt.
[DEBUG] [org.gradle.launcher.daemon.registry.PersistentDaemonRegistry] Removing daemon address: [..., addresses:[localhost/127.0.0.1]]
[DEBUG] [org.gradle.launcher.daemon.server.Daemon] VM shutdown hook was unable to remove the daemon address from the registry. It will be cleaned up later.
org.gradle.api.UncheckedIOException: java.net.BindException: Cannot assign requested address: Cannot bind
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:62)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
	at org.gradle.cache.internal.locklistener.FileLockCommunicator.<init>(FileLockCommunicator.java:51)
	at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler.getCommunicator(DefaultFileLockContentionHandler.java:263)
	at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler.reservePort(DefaultFileLockContentionHandler.java:255)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:109)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:96)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:91)
	at org.gradle.cache.internal.OnDemandFileAccess.updateFile(OnDemandFileAccess.java:51)
	at org.gradle.cache.internal.SimpleStateCache.update(SimpleStateCache.java:87)
	at org.gradle.cache.internal.FileIntegrityViolationSuppressingPersistentStateCacheDecorator$1.create(FileIntegrityViolationSuppressingPersistentStateCacheDecorator.java:50)
	at org.gradle.cache.internal.FileIntegrityViolationSuppressingPersistentStateCacheDecorator.doUpdate(FileIntegrityViolationSuppressingPersistentStateCacheDecorator.java:67)
	at org.gradle.cache.internal.FileIntegrityViolationSuppressingPersistentStateCacheDecorator.update(FileIntegrityViolationSuppressingPersistentStateCacheDecorator.java:47)
	at org.gradle.launcher.daemon.registry.PersistentDaemonRegistry.remove(PersistentDaemonRegistry.java:133)
	at org.gradle.launcher.daemon.server.Daemon$1.run(Daemon.java:127)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.BindException: Cannot assign requested address: Cannot bind
	at java.net.DualStackPlainDatagramSocketImpl.socketBind(Native Method)
	at java.net.DualStackPlainDatagramSocketImpl.bind0(DualStackPlainDatagramSocketImpl.java:84)
	at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:93)
	at java.net.DatagramSocket.bind(DatagramSocket.java:392)
	at java.net.DatagramSocket.<init>(DatagramSocket.java:242)
	at java.net.DatagramSocket.<init>(DatagramSocket.java:299)
	at org.gradle.cache.internal.locklistener.FileLockCommunicator.<init>(FileLockCommunicator.java:49)
	... 13 more
```

**Solution** (should be, but not working for now): add `-Djava.net.preferIPv4Stack=true` to `org.gradle.jvmargs` in `gradle.properties`.

**Workaround** (till fixed): add `-Djava.net.preferIPv4Stack=true` to the following env. vars (source: https://support.citrix.com/article/CTX209237):

* `javaws.exe`: `JAVAWS_VM_ARGS`
* `java.exe`: `_JAVA_OPTIONS`
* `javaw.exe`: `_JPI_VM_OPTIONS`

### Steps to Reproduce

1. empty folder
2. `gradle.properties`:
    ```
    org.gradle.jvmargs=-Xms123m -Xmx456m -XX:+CMSClassUnloadingEnabled -Djava.net.preferIPv4Stack=true
    ````
3. run gradle

### Your Environment
Windows 10 x64 21H1 b19043.1415
Jdk build 1.8.0_181-b13
Gradle 7.3.3

**Comment by ljacomet** [comment]
Can you try the same with a more recent Java version like 11 or 17?

**Comment by ogmios-voice** [comment]
(oracle) jdk `8.0.311`, `11.0.13`, `17.0.1`: all the same error.
And the workaround also works for all of them.

jdk 11, 17: (note: -XX:+CMSClassUnloadingEnabled removed from jvmargs)
```
[INFO] [org.gradle.launcher.daemon.server.Daemon] start() called on daemon - DefaultDaemonContext[...,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.base/java.nio.charset=ALL-UNNAMED,--add-opens,java.base/java.net=ALL-UNNAMED,--add-opens,java.base/java.util.concurrent.atomic=ALL-UNNAMED,-Xms123m,-Xmx456m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant]
```

jdk 17: exception message slightly different
```
Caused by: java.net.BindException: Cannot assign requested address: bind
```
