### ISSUE TITLE
Improve outputContains output for integration testing

### ISSUE THREAD

**Issue by tresat** [gradle/gradle#19608]
Continuation of work on https://github.com/gradle/gradle/pull/19561.

The core team is in agreement that the `AbstractIntegrationTest#outputContains()` method produces output that is difficult to understand.  In particular, finding exactly where a mismatch has occurred in a large comparison leave much to be desired.

An early attempt to provide an alternative is below.  See if the spirit of this code can be added into `outputContains` directly to change and clarify its output and improve its usefulness.

```
    /**
     * Given a string containing a first line which is <strong>unique within the expected output</strong>, checks
     * if every line in the output matches the lines in the given string, reporting the failing line and number
     * within both the actual and expected outputs.
     *
     * @param string the expected output
     */
    void outputContainsLinewise(String string) {
        outputContainsLinewise(string.readLines())
    }

    /**
     * Given a collection of lines beginning with a line which is <strong>unique within the expected output</strong>, checks
     * if every line in the output matches the lines in the given string, reporting the failing line and number
     * within both the actual and expected outputs.
     *
     * @param lines the expected output
     */
    void outputContainsLinewise(List<String> lines) {
        List<String> outputLines = result.output.readLines()
        def firstIndex = outputLines.findIndexOf {lines[0] == it }
        (0..<lines.size()).each {
            def actual = outputLines[firstIndex + it].trim()
            def expected = lines[it].trim()
            if (actual != expected) {
                throw new AssertionError("Output line ${firstIndex + it}: '$actual'\ndid not match expected line $it: '$expected'")
            }
        }
    }
```

**Comment by DPUkyle** [comment]
Naming suggestion: `outputContainsUniqueLine(String)` or `outputContainsLineOnce(String)`

**Comment by tresat** [comment]
Current state of output: If you edit a test which uses `outputContains()` in `org.gradle.api.tasks.diagnostics.AbstractIntegrationSpec` such as `org.gradle.api.tasks.diagnostics.OutgoingVariantsReportTaskIntegrationTest#prints explicit capabilities()" to include lines in the expected output which do not match what is produced (for example, I added "This line should NOT be here!" below the first line beginning with "Description = ") you get the following printed to the test Console:

**ACTUAL TASK OUTPUT OMITTED**
```
Condition failed with Exception:

outputContains """> Task :outgoingVariants -------------------------------------------------- Variant runtimeElements -------------------------------------------------- Description = Elements of runtime for main. This line should NOT be here! Capabilities - org.test:extra:1.0 - org.test:other:3.0 """
|
org.junit.ComparisonFailure: Did not find expected text in build output.
Expected: > Task :outgoingVariants
--------------------------------------------------
Variant runtimeElements
--------------------------------------------------
Description = Elements of runtime for main.
This line should NOT be here!
 
Capabilities
    - org.test:extra:1.0
    - org.test:other:3.0
 
Build output:
=======
 ```
**REPEAT OF ACTUAL TASK OUTPUT OMITTED**
 ```
Output:
=======
 ```
**REPEAT OF ACTUAL TASK OUTPUT OMITTED**
 ```
Error:
======
 expected:<[> Task :outgoingVariants
--------------------------------------------------
Variant runtimeElements
--------------------------------------------------
Description = Elements of runtime for main.
This line should NOT be here!
 
Capabilities
    - org.test:extra:1.0
    - org.test:other:3.0]> but was:<[
> Task :outgoingVariants
--------------------------------------------------
Variant runtimeElements
--------------------------------------------------
Description = Elements of runtime for main.
 
Capabilities
    - org.test:extra:1.0
    - org.test:other:3.0
 
Attributes
    - org.gradle.category            = library
    - org.gradle.dependency.bundling = external
    - org.gradle.jvm.version         = 11
    - org.gradle.libraryelements     = jar
    - org.gradle.usage               = java-runtime
 
Artifacts
    - build/libs/myLib.jar (artifactType = jar)
 
Secondary variants (*)
    - Variant : classes
       - Attributes
          - org.gradle.category            = library
          - org.gradle.dependency.bundling = external
          - org.gradle.jvm.version         = 11
          - org.gradle.libraryelements     = classes
          - org.gradle.usage               = java-runtime
       - Artifacts
          - build/classes/java/main (artifactType = java-classes-directory)
    - Variant : resources
       - Attributes
          - org.gradle.category            = library
          - org.gradle.dependency.bundling = external
          - org.gradle.jvm.version         = 11
          - org.gradle.libraryelements     = resources
          - org.gradle.usage               = java-runtime
       - Artifacts
          - build/resources/main (artifactType = java-resources-directory)
 
 
(*) Secondary variants are variants created via the Configuration#getOutgoing(): ConfigurationPublications API which also participate in selection, in addition to the configuration itself.
]>
	at org.gradle.integtests.fixtures.executer.OutputScrapingExecutionResult.failOnMissingOutput(OutputScrapingExecutionResult.java:394)
	at org.gradle.integtests.fixtures.executer.OutputScrapingExecutionResult.assertContentContains(OutputScrapingExecutionResult.java:227)
	at org.gradle.integtests.fixtures.executer.OutputScrapingExecutionResult.assertOutputContains(OutputScrapingExecutionResult.java:234)
	at org.gradle.integtests.fixtures.executer.InProcessGradleExecuter$InProcessExecutionResult.assertOutputContains(InProcessGradleExecuter.java:532)
	at org.gradle.integtests.fixtures.AbstractIntegrationSpec.outputContains(AbstractIntegrationSpec.groovy:594)
	at org.gradle.api.tasks.diagnostics.OutgoingVariantsReportTaskIntegrationTest.prints explicit capabilities(OutgoingVariantsReportTaskIntegrationTest.groovy:853)

Condition failed with Exception:
```
**REPEAT EVERYTHING BETWEEN THE FIRST TWO "Condition failed with Exception" LINES OMITTED**

This is extremely noisy.

**Comment by tresat** [comment]
Note that `result.groupedOutput.task(":outgoingVariants").assertOutputContains("""THE EXPECTED TEXT BLOCK""") results in output that is better, but still repeats the actual output needlessly and is difficult to use to find the mismatched line.

This can be improved somewhat by overriding `toString()` on `GroupedOutputFixture` to something like:

```
@Override
public String toString() {
    return "GroupedOutputFixture for tasks: " + Arrays.deepToString(tasks.keySet().toArray());
}
```

and on `GroupedTaskFixture` to something like:

```
@Override
public String toString() {
  return "Output for: " + taskName + " " + taskOutcome;
}
```

and then updating `GroupedTaskFixture#assertOutputContains(String...)` to:

```
public GroupedTaskFixture assertOutputContains(String... text) {
    String output = getOutput();
    for (String s : text) {
        if (!output.contains(s)) {
            throw new RuntimeException("Line 2 in expected output: [EXPECTED LINE] did not match actual line 5: in context: [CONTEXT LINES, with mismatch highlighted]");
        }
    }
    return this;
}
```

yields this:

```
Condition failed with Exception:

result.groupedOutput.task(":outgoingVariants").assertOutputContains """> Task :outgoingVariants -------------------------------------------------- Variant runtimeElements -------------------------------------------------- Description = Elements of runtime for main. Capabilities - org.test:extra:1.0 - org.test:other:3.0 """
|      |             |                         |
|      |             |                         java.lang.RuntimeException: Line 2 in expected output: [EXPECTED LINE] did not match actual line 5: in context: [CONTEXT LINES, with mismatch highlighted]
|      |             |                         	at org.gradle.integtests.fixtures.logging.GroupedTaskFixture.assertOutputContains(GroupedTaskFixture.java:75)
|      |             |                         	at org.gradle.api.tasks.diagnostics.OutgoingVariantsReportTaskIntegrationTest.prints explicit capabilities(OutgoingVariantsReportTaskIntegrationTest.groovy:853)
|      |             Output for: :outgoingVariants null
|      GroupedOutputFixture for tasks: [:outgoingVariants]
<org.gradle.integtests.fixtures.executer.InProcessGradleExecuter$InProcessExecutionResult@2ffef644 executedTasks=[:outgoingVariants] skippedTasks=[] outputResult=org.gradle.integtests.fixtures.executer.OutputScrapingExecutionResult@223a2e4a>
```

which is still repeated twice, but I think could be the starting point for much clearer output.  We could find the first mismatched line, throwing a different custom exception containing this message, and a different message still if NONE of the lines in expected matched actual.

**Comment by tresat** [comment]
Hi @leonard84 - I was searching for a way to disable Spock’s power assertions in order provide cleaner output when testing doing large block test comparisons fail.

I couldn’t find a way to do this.  I found this Spock commit: https://github.com/spockframework/spock/issues/922 and wondered if you had any ideas?  I wanted to disable the behavior changed by this commit https://github.com/spockframework/spock/pull/928/commits/79492021985944d7d4a3f4154106d6618af1a319#diff-925956eb662970e7d2d34da347e3588870ec74dba162589013bd2250156da854 and provide a more readable custom error message which entirely replaced the power assertion output.  What we are hoping to do is isolate the mismatched lines (I’m assuming there is usually only a single line of mismatch) and provide a couple of context lines without repeating the complete expected or actual text blocks involved in the comparison.

**Comment by tresat** [comment]
@leonard84 - Hi Leonard, when you have a chance, I'd like to hear your thoughts on this.

**Comment by tresat** [comment]
Continued here: https://github.com/gradle/gradle/issues/19608
