### ISSUE TITLE
GradleProperties has not been loaded yet Error.

### ISSUE THREAD

**Issue by akar1492** [gradle/gradle#19614]
Unit test Case failure

Using Gradle 6.8.1 and springboot 2.6.2.
```
Caused by: org.gradle.api.tasks.TaskInstantiationException: Could not create task of type 'BuildInfo'.
    at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:97)
    at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:84)
    at org.gradle.util.GUtil.uncheckedCall(GUtil.java:452)
    at org.gradle.api.internal.AbstractTask.injectIntoNewInstance(AbstractTask.java:202)
    at org.gradle.api.internal.project.taskfactory.TaskFactory.create(TaskFactory.java:84)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory.create(AnnotationProcessingTaskFactory.java:48)
    at org.gradle.api.internal.tasks.DefaultTaskContainer.createTask(DefaultTaskContainer.java:326)
    at org.gradle.api.internal.tasks.DefaultTaskContainer.access$200(DefaultTaskContainer.java:77)
    at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider.createDomainObject(DefaultTaskContainer.java:701)
    at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider.createDomainObject(DefaultTaskContainer.java:658)
    at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.tryCreate(DefaultNamedDomainObjectCollection.java:941)
... 19 more
Caused by: java.lang.IllegalStateException: GradleProperties has not been loaded yet.
    at org.gradle.initialization.DefaultGradlePropertiesController$NotLoaded.gradleProperties(DefaultGradlePropertiesController.java:80)
    at org.gradle.initialization.DefaultGradlePropertiesController$SharedGradleProperties.gradleProperties(DefaultGradlePropertiesController.java:63)
    at org.gradle.initialization.DefaultGradlePropertiesController$SharedGradleProperties.find(DefaultGradlePropertiesController.java:54)
    at org.gradle.api.internal.provider.sources.GradlePropertyValueSource.obtain(GradlePropertyValueSource.java:36)
    at org.gradle.api.internal.provider.sources.GradlePropertyValueSource.obtain(GradlePropertyValueSource.java:24)
    at org.gradle.api.internal.provider.DefaultValueSourceProviderFactory$LazilyObtainedValue.lambda$obtainValueForThe1stTime$0(DefaultValueSourceProviderFactory.java:344)
    at org.gradle.internal.Try.ofFailable(Try.java:39)
    at org.gradle.api.internal.provider.DefaultValueSourceProviderFactory$LazilyObtainedValue.obtainValueForThe1stTime(DefaultValueSourceProviderFactory.java:344)
    at org.gradle.api.internal.provider.DefaultValueSourceProviderFactory$LazilyObtainedValue.obtain(DefaultValueSourceProviderFactory.java:333)
    at org.gradle.api.internal.provider.DefaultValueSourceProviderFactory$ValueSourceProvider.calculateOwnValue(DefaultValueSourceProviderFactory.java:299)
    at org.gradle.api.internal.provider.AbstractMinimalProvider.getOrNull(AbstractMinimalProvider.java:93)
    at org.springframework.boot.gradle.tasks.buildinfo.BuildInfoProperties.projectVersion(BuildInfoProperties.java:72)
    at org.springframework.boot.gradle.tasks.buildinfo.BuildInfoProperties.(BuildInfoProperties.java:63)
    at org.springframework.boot.gradle.tasks.buildinfo.BuildInfo.(BuildInfo.java:46)
    at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:1969)
    at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:468)
    at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:64)
    at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.newInstanceWithDisplayName(DependencyInjectingInstantiator.java:50)
    at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:90)
```

**Comment by akar1492** [comment]
@oehme - any thoughts on this error?

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.
