### ISSUE TITLE
JVM Test Suite plugin errors when jar disabled

### ISSUE THREAD

**Issue by countableSet** [gradle/gradle#19684]
### Expected Behavior

Running the task created through the `jvm-test-suite` plugin should pass without any errors.

### Current Behavior

* Task fails with `ClassNotFoundException` when using the `java-library` plugin
* Task fails to compile when using the `java` plugin
* The normal `test` task passes with the same test

When `jar { enabled = false }`

### Context

Trying to create an integration test suite for spring boot tests. However, I also would like to disable the plain archives jar pre the [spring documentation](https://docs.spring.io/spring-boot/docs/2.5.1/gradle-plugin/reference/htmlsingle/#packaging-executable.and-plain-archives) by setting `jar { enabled = false }`.

### Steps to Reproduce 

Sample repo to reproduce the issue: https://github.com/countableSet/gradle-jvm-test-suite-bug and failed action https://github.com/countableSet/gradle-jvm-test-suite-bug/actions/runs/1741836118

Summary:
Running `./gradlew testIntegration` fails with error:
```
java.lang.NoClassDefFoundError: com/example/demo/SampleComponent
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2371)
	at org.junit.platform.commons.util.ReflectionUtils.getDeclaredFields(ReflectionUtils.java:1470)
	at org.junit.platform.commons.util.ReflectionUtils.findAllFieldsInHierarchy(ReflectionUtils.java:1200)
	at org.junit.platform.commons.util.ReflectionUtils.findFields(ReflectionUtils.java:1188)
	at org.junit.jupiter.engine.descriptor.ExtensionUtils.registerExtensionsFromFields(ExtensionUtils.java:96)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.prepare(ClassBasedTestDescriptor.java:150)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.prepare(ClassBasedTestDescriptor.java:80)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.ClassNotFoundException: com.example.demo.SampleComponent
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 55 more
```

However if you comment out below in the `build.gradle.kts` file It will pass.
```
jar {
    enabled = false
}
```

Also if you switch from `java-library` plugin to use `java` plugin. It results in a compile time error instead
```
> Task :compileTestIntegrationJava FAILED
demo/src/testIntegration/java/com/example/demo/SampleComponentTest.java:18: error: cannot find symbol
    private SampleComponent sampleComponent;
            ^
  symbol:   class SampleComponent
  location: class SampleComponentTest
demo/src/testIntegration/java/com/example/demo/SampleComponentTest.java:14: error: cannot find symbol
@ContextConfiguration(classes = { SampleComponent.class })
                                  ^
  symbol: class SampleComponent
2 errors
```

### Your Environment

Build scan URL: 

MacOS 11.6.1
java --version
openjdk 17.0.1 2021-10-19 LTS
OpenJDK Runtime Environment Zulu17.30+15-CA (build 17.0.1+12-LTS)
OpenJDK 64-Bit Server VM Zulu17.30+15-CA (build 17.0.1+12-LTS, mixed mode, sharing)
Gradle wrapper 7.3.3

**Comment by lkadalski** [comment]
I have similar issue on Linux, running Spring Boot 2.5.6.
Also with this setting
`jar {
    enabled = false
}`

**Comment by lkadalski** [comment]
@countableSet If you need immediate resolution this helps:
`jar {
    //From Spring Boot 2.5.0. Two jars are created, this setting provides only one.
    archiveClassifier = '' //use empty string
    enabled = true
}
` 
:rocket:

**Comment by zadeluca** [comment]
I just ran into this problem today, and it took me _forever_ to determine that this was the cause. Have any fixes or workarounds been discovered in the past year?

**Comment by zadeluca** [comment]
I updated the sample repo that @countableSet created to use gradle 8.0.1 and remove everything spring related. Not sure if that helps, but it shows that the problem is caused only by `jar { enabled = false }` and not some weird interaction with spring stuff.
https://github.com/zadeluca/gradle-jvm-test-suite-bug

**Comment by zadeluca** [comment]
Poking around, trying to learn and understand. If I print the classpath for each task, here are the important differences:

test
```
/home/zdeluca/gradle-jvm-test-suite-bug/build/classes/java/test
/home/zdeluca/gradle-jvm-test-suite-bug/build/resources/test
/home/zdeluca/gradle-jvm-test-suite-bug/build/classes/java/main
/home/zdeluca/gradle-jvm-test-suite-bug/build/resources/main
```
testIntegration
```
/home/zdeluca/gradle-jvm-test-suite-bug/build/classes/java/testIntegration
/home/zdeluca/gradle-jvm-test-suite-bug/build/resources/testIntegration
/home/zdeluca/gradle-jvm-test-suite-bug/build/libs/demo-0.0.1-SNAPSHOT.jar
```

So test has classes compiled from src/main and src/test, whereas testIntegration only has the built jar. Of course it won't work if jar is disabled. The workaround I came up with is to add the output dirs of the main sourceSet to the testIntegration classpath:

```diff
testing {
     suites {
         val test by getting(JvmTestSuite::class) {
             useJUnitJupiter()
         }
         val testIntegration by registering(JvmTestSuite::class) {
             dependencies {
                 implementation(project())
             }
+            sources {
+                compileClasspath += sourceSets.main.get().output
+                runtimeClasspath += sourceSets.main.get().output
+            }
         }
     }
 }
```

And all green: https://github.com/zadeluca/gradle-jvm-test-suite-bug/actions/runs/4300404066

What do you think about this? Is it okay or a hack? If it is worth getting added to the official docs let me know and I will look into how to do that.

**Comment by zadeluca** [comment]
Just realized this is probably better/cleaner:

```diff
testing {
     suites {
         val test by getting(JvmTestSuite::class) {
             useJUnitJupiter()
         }
         val testIntegration by registering(JvmTestSuite::class) {
             dependencies {
                 implementation(project())
+                implementation(sourceSets.main.get().output)
             }
         }
     }
 }
 ```

**Comment by dgeissl** [comment]
any action from the gradle team to fix that issue?

**Comment by jochenberger** [comment]
Could this be related to #24050 / #23477?

**Comment by asodja** [comment]
Sorry for late reply. The issue is in the backlog of the relevant team and is prioritized by them.

***

We should improve the error on a failed build.

Adding:
```
implementation(project())
```
is adding a dependency on a project jar. So disabling it means that the configution is incorrect.

See `5.` in example in our documentation where:
https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html#sec:declare_an_additional_test_suite
