### ISSUE TITLE
Using java.nio.file.Path causes infinite loops

### ISSUE THREAD

**Issue by stovocor** [gradle/gradle#1973]
### Expected Behavior
Using a path object of the class `java.nio.file.Path` should provide the same result as `java.io.File`.

### Current Behavior
Defining inputs or outputs with `java.nio.file.Path` causes an infinite loop or a `java.lang.StackOverflowError`.

```
java.lang.StackOverflowError
	at org.gradle.api.internal.file.collections.BuildDependenciesOnlyFileCollectionResolveContext.add(BuildDependenciesOnlyFileCollectionResolveContext.java:78)
	at org.gradle.api.internal.file.collections.BuildDependenciesOnlyFileCollectionResolveContext.add(BuildDependenciesOnlyFileCollectionResolveContext.java:79)
	at org.gradle.api.internal.file.collections.BuildDependenciesOnlyFileCollectionResolveContext.add(BuildDependenciesOnlyFileCollectionResolveContext.java:79)
```

### Context
Since #813 has been resolved, the project API also accepts `java.nio.file.Path`. However, it looks like this class is treated as an `Iterable`.

In one project I saw an infinite loop causing full CPU load on one core, in the demo project (see below) a `StackOverflowError` is raised. The difference seems to be if the `Path` is used as an input or output.

### Steps to Reproduce (for bugs)

```
task demo {
        def path = Paths.get("/home/user/demo")
        inputs.dir(path)
}
```

Please see my [demo project](https://github.com/stovocor/gradle-infinite-loop).

### Your Environment
Arch Linux, Oracle JDK 1.8.0_131, Gradle 3.5

**Comment by adammurdoch** [comment]
This is fixed now.

**Comment by bmuschko** [comment]
@adammurdoch Can you please add the milestone so the automatically generated release notes can pick it up?
