### ISSUE TITLE
Configuration cache - lateinit property projectProvider has not been initialized

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#19839]
Using [fingerprint_check.zip](https://github.com/gradle/gradle/files/8014459/fingerprint_check.zip) project and running
```
./gradlew lintRelease --configuration-cache && ./gradlew lintRelease --configuration-cache
```
fails with
```
kotlin.UninitializedPropertyAccessException: lateinit property projectProvider has not been initialized
        at org.gradle.configurationcache.serialization.DefaultReadContext.getProject(Contexts.kt:305)
        at org.gradle.configurationcache.serialization.codecs.transform.TransformationStepCodec.decode(TransformationStepCodec.kt:49)
        at org.gradle.configurationcache.serialization.codecs.transform.TransformationStepCodec$decode$1.invokeSuspend(TransformationStepCodec.kt)
```
The failure comes from checking the cache fingerprint on the 2nd run.

Context: There were some changes in AGP 7.3 around usage of `ValueSource`, so this issue exists in only in AGP 7.3. 

Gradle version: 7.4-rc-2
AGP: 7.3.0-alpha01

**Comment by gavra0** [comment]
Here is a reduced example:
[configuration_cache_inputs.zip](https://github.com/gradle/gradle/files/8014865/configuration_cache_inputs.zip)

Running:
```
./gradlew mytask --configuration-cache && ./gradlew mytask --configuration-cache
```
fails, while
```
./gradlew mytask2 --configuration-cache && ./gradlew mytask2 --configuration-cache
```
succeeds.

The root cause is eager evaluation of a file collection in `getComputedFaulty` method, but spotting this in a general case is quite hard. Do you see a way to help plugin authors in catching these issues early on?

**Comment by ov7a** [comment]
Sorry for the late reply.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by mlopatkin** [comment]
We're hitting the issue highlighted in this semi-TODO comment:
https://github.com/gradle/gradle/blob/646db55a5f12f362780923dac2ccbbad1aa97eda/platforms/core-configuration/core-serialization-codecs/src/main/kotlin/org/gradle/internal/serialize/codecs/core/FileCollectionCodec.kt#L229-L234

When we try to serialize a transform-backed file collection as part of the CC fingerprint, it works, but we don't really have enough context to properly restore those on the other side, hence the failure.

It got slightly better, now it complains about `Cannot resolve project path ':' because project structure is not yet loaded for build ':'`, but it still requires quite a bit of Gradle knowledge to make the connection.

A viable course of action (other than implementing proper transform serialization), would be to forbid `TransformedArtifactSet` in the fingerprint with clear failure message, similar to what we do with build services today.
