### ISSUE TITLE
Toolchain API checks for targetCompatibility in all/unrelated scopes

### ISSUE THREAD

**Issue by kiwiwings** [gradle/gradle#20045]
If a plugin uses the "targetCompatibility" as a property, the toolchain API won't allow it to be set and gradle quits early.
As example [forbiddenApis](https://github.com/policeman-tools/forbidden-apis) is such a case and its issue [#191](https://github.com/policeman-tools/forbidden-apis/issues/191), where we think it's gradle handling to be modified.

### Expected Behavior
Gradle should ignore targetCompatibility properties outside the usual suspects like compile, javadoc, javaexec.
Maybe check for the availability of an JavaCompiler, JavaLauncher, JavadocTool type in that scope, to see if the targetCompatibility tag needs to conform to the existing policy.

### Current Behavior
If the toolchain settings are used and a plugin uses the property "targetCompatibility", gradle quits early.

### Context
In the [POI project](https://svn.apache.org/viewvc/poi/trunk/build.gradle?view=log) I was trying to limit the targetCompatibility of the forbiddenApis plugin. The code was compiled with JDK-18, but forbiddenApis only supports up to JDK-14 and fails beyond that, because it doesn't check for availability of the necessary resource bundles and simply uses the value gradle gives it.
If you look at [#191](https://github.com/policeman-tools/forbidden-apis/issues/191), there are arguably workarounds, but gradles behaviour is also not straight forward. 

### Steps to Reproduce 

Take an empty gradle project and use the gradle.build of the following:
https://github.com/kiwiwings/gradleToolchainConflict/tree/groovy-dsl

### Your Environment
Gradle 7.3

**Comment by uschindler** [comment]
The problem is that Gradle complains about a plugin that uses a property "targetCompatibility" when Toolchain Support is enabled. Every plugin should be free to name the properties as they like. This breaks compatibility of Gradle with Forbiddenapis because there is no way to pass the Java API level to forbiddenapis.

**Comment by ljacomet** [comment]
This is an issue with the concept of convention properties that exist in Gradle.
Having such a property on the project object will wire it inside `java.targetCompatibility` behind the scenes. Unfortunately, for technical limitations, toolchains are not compatible with that setting.

You will have to move away the plugin from this convention property or not use toolchain in that context.

**Comment by ljacomet** [comment]
Thank you for the nice reply and tweet, as a reminder, we have a [code of conduct](https://gradle.org/conduct/).

I did make a mistake by reading to fast the linked issue: the `forbiddenapis` plugin does need to change anything.

However the problem described here, not illustrated by the reproducer AFAICT, remains a [documented limitation](https://docs.gradle.org/current/userguide/building_java_projects.html#sec:java_cross_compilation).

If a reproducer can show that Gradle interprets any `targetCompatibility` property on any extension as invalid, I will re-open this issue.

**Comment by uschindler** [comment]
> Thank you for the nice reply and tweet, as a reminder, we have a [code of conduct](https://gradle.org/conduct/).

I have no relationship with Gradle and I have ongoing bad communication with Gradle employees because the same happens with almost every issue we open at Gradle. The first reaction is alays to close an issue. If you don't want constructive feedback you can proceed with this behaviour! I don't care about code of conduct because I personally did not start any contract, I just reponded to an issue by somebody else because it affects a plugin I am maintaining together with others from ASF. If you want to get me out just block me from Gradle, in the same time I will remove support for Gradle from forbiddenapis.

To say it hard: It gets more an more a desaster to maintain build plugins or make builds with modern projects using the Java module system (e.e., Apache Lucene) work correctly. Gradle did not understand how the module system works and in combination with using Groovy and its limitations in cooperation with the module system it is almost impossible to use Gradle. The toolchain API and its limitations do the rest. In Apache Lucene and Apache Solr we tried it out and stopped to use it - just because it does not work at all. See tons of still open issues at your side without any progress.

As said before the issue here is about somehow disallowing to use a (String!!!!) property named targetCompatibility in an external plugin. From my understand it looks like the Toolchain API just greps through all build files and fails if it finds a target compatibility. What is so complicated in just iterating thorugh the known ones like JavaCompile, Javadocs and other to check if the toolchain api is enabled and at same time the target compatibility is set?

Nevertheless it is also unclear why this is an issue at all. What's wrong with setting targetCompatibility or sourceCompatibility in combination with toolchains? Toolschains are just there to provide the location of java compiler to the build. targetCompatibility/sourceCompatibility and release are just some flags directly passed to the compile and have NOTHING to do with toolchains. The only thing to check is if the target/source/release version cannot be supported by the used toolchain.

**Comment by uschindler** [comment]
> If a reproducer can show that Gradle interprets any targetCompatibility property on any extension as invalid, I will re-open this issue.

This build file sets "targetCompatibility" on the "forbiddenApis" extension (and on the corresponding task forbiddenApisMain, forbiddenapisTest): https://github.com/kiwiwings/gradleToolchainConflict/blob/groovy-dsl/build.gradle

The reproducer by @kiwiwings seems incomplete as it has no Java files to compile, so the tasks are not running at all (NO-SOURCE). So I agree with you that this should be reopened if it reproduces.

**Comment by uschindler** [comment]
The repro for reproducing was updated to actually contain a class file so it triggers the bug.

**Comment by uschindler** [comment]
Here is the build output:

```
> Configure project :
Evaluating root project 'reproducer-project' using build file 'C:\Users\Uwe Schindler\Desktop\gradleToolchainConflict-groovy-dsl\build.gradle'.
All projects evaluated.
Selected primary task 'check' from project :
Tasks to be executed: [task ':compileJava', task ':processResources', task ':classes', task ':forbiddenApisMain', task ':compileTestJava', task ':processTestResources', task ':testClasses', task ':forbiddenApisTest', task ':forbiddenApis', task ':test', task ':check']
Tasks that were excluded: []
:compileJava (Thread[Execution worker for ':',5,main]) started.

> Task :compileJava FAILED
:compileJava (Thread[Execution worker for ':',5,main]) completed. Took 0.006 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Error while evaluating property 'targetCompatibility' of task ':compileJava'
   > The new Java toolchain feature cannot be used at the project level in combination with source and/or target compatibility

* Try:
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:402)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:389)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:382)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:368)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
Caused by: org.gradle.api.internal.tasks.properties.PropertyEvaluationException: Error while evaluating property 'targetCompatibility' of task ':compileJava'
        at org.gradle.api.internal.tasks.properties.InputParameterUtils.prepareInputParameterValue(InputParameterUtils.java:33)
        at org.gradle.api.internal.tasks.execution.TaskExecution.lambda$visitRegularInputs$1(TaskExecution.java:312)
        at org.gradle.internal.execution.fingerprint.impl.DefaultInputFingerprinter$InputCollectingVisitor.visitInputProperty(DefaultInputFingerprinter.java:95)
        at org.gradle.api.internal.tasks.execution.TaskExecution.visitRegularInputs(TaskExecution.java:312)
        at org.gradle.internal.execution.fingerprint.impl.DefaultInputFingerprinter.fingerprintInputProperties(DefaultInputFingerprinter.java:54)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.captureExecutionStateWithOutputs(CaptureStateBeforeExecutionStep.java:193)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.lambda$captureExecutionState$1(CaptureStateBeforeExecutionStep.java:141)
        at org.gradle.internal.execution.steps.BuildOperationStep$1.call(BuildOperationStep.java:37)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.internal.execution.steps.BuildOperationStep.operation(BuildOperationStep.java:34)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.captureExecutionState(CaptureStateBeforeExecutionStep.java:130)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.lambda$execute$0(CaptureStateBeforeExecutionStep.java:75)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:75)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:50)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:93)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:93)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:43)
        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:31)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:40)
        at org.gradle.api.internal.tasks.execution.TaskExecution$3.withWorkspace(TaskExecution.java:284)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:40)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:44)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:33)
        at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:76)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:142)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:402)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:389)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:382)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:368)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
Caused by: org.gradle.api.InvalidUserDataException: The new Java toolchain feature cannot be used at the project level in combination with source and/or target compatibility
        at org.gradle.api.plugins.JavaBasePlugin.checkToolchainAndCompatibilityUsage(JavaBasePlugin.java:309)
        at org.gradle.api.plugins.JavaBasePlugin.lambda$determineCompatibility$7(JavaBasePlugin.java:292)
        at org.gradle.util.internal.GUtil.uncheckedCall(GUtil.java:454)
        at org.gradle.internal.extensibility.ConventionAwareHelper$2.doGetValue(ConventionAwareHelper.java:96)
        at org.gradle.internal.extensibility.ConventionAwareHelper$MappedPropertyImpl.getValue(ConventionAwareHelper.java:147)
        at org.gradle.internal.extensibility.ConventionAwareHelper.getConventionValue(ConventionAwareHelper.java:129)
        at org.gradle.api.tasks.compile.JavaCompile_Decorated.getTargetCompatibility(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue$1$1.create(AbstractNestedRuntimeBeanNode.java:77)
        at org.gradle.internal.deprecation.DeprecationLogger.whileDisabled(DeprecationLogger.java:244)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue$1.get(AbstractNestedRuntimeBeanNode.java:73)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue.call(AbstractNestedRuntimeBeanNode.java:133)
        at org.gradle.util.internal.GUtil.uncheckedCall(GUtil.java:454)
        at org.gradle.util.internal.DeferredUtil.unpackNestableDeferred(DeferredUtil.java:83)
        at org.gradle.util.internal.DeferredUtil.unpack(DeferredUtil.java:57)
        at org.gradle.util.internal.DeferredUtil.unpackOrNull(DeferredUtil.java:49)
        at org.gradle.api.internal.tasks.properties.InputParameterUtils.prepareInputParameterValue(InputParameterUtils.java:39)
        at org.gradle.api.internal.tasks.properties.InputParameterUtils.prepareInputParameterValue(InputParameterUtils.java:31)
        ... 67 more
```

The stack trace does not contain any classes of forbiddenapis, so the bug is purely in Gradle.

**Comment by uschindler** [comment]
What the project shows: If you set the property directly on the task, not the extension, it works:

This works:
```
forbiddenApisMain {
    bundledSignatures = [ 'jdk-unsafe', 'jdk-deprecated', 'jdk-internal', 'jdk-non-portable', 'jdk-reflection' ]
    ignoreFailures = false
    // forbiddenapis bundled signatures max supported version is 14
    targetCompatibility = JavaVersion.VERSION_14
}
```

This not:

```
forbiddenApis {
    bundledSignatures = [ 'jdk-unsafe', 'jdk-deprecated', 'jdk-internal', 'jdk-non-portable', 'jdk-reflection' ]
    ignoreFailures = false
    // forbiddenapis bundled signatures max supported version is 14
    targetCompatibility = JavaVersion.VERSION_14
}
```

**Comment by uschindler** [comment]
So basically the analysis by @ljacomet is partly correct it seems to have to do with how extensions work, but there should be a workaround inside gradle be implemented to not populate extension properties on top-level, too.

**Comment by melix** [comment]
Just passing by: it seems that you are mistaken about what the extension provides. It does _not_ have a `targetCompatibility` property: https://github.com/policeman-tools/forbidden-apis/blob/main/src/main/java/de/thetaphi/forbiddenapis/gradle/CheckForbiddenApisExtension.java while the _task_ does: https://github.com/policeman-tools/forbidden-apis/blob/main/src/main/java/de/thetaphi/forbiddenapis/gradle/CheckForbiddenApis.java#L375

Therefore if you configure the extension and say `targetCompatibility = ...`, it won't find it on the extension and therefore it will be called on the `project`, so it sets the project `targetCompatibility`. The fix should be on the plugin side to put a `targetCompatibility` on the extension if it makes sense.

**Comment by uschindler** [comment]
If you make a good suggestion how to change the code in forbiddenapis minimally to prevent the forbiddenapis extension to leak their properties, I am happy to apply ut.

**Comment by uschindler** [comment]
@melix you are right, so seems like a "user error".

There was some reason to not have targetCompatibility on the extension....

**Comment by uschindler** [comment]
OK, let's deescalate this and open new issues:
- why the hell does Gradle populate properties that are explicitely only set on the extension to the project? This is a bug and makes life hard. This is not the first time this happens. This is clearly not in the intention of the user writing the gradle file
- the documentation of forbiddenapis will be changed to clearly state that targetCompatibility should set on the java project AND/OR the tasks only.

**Comment by melix** [comment]
> why the hell does Gradle populate properties that are explicitely only set on the extension to the project? This is a bug and makes life hard. This is not the first time this happens. This is clearly not in the intention of the user writing the gradle file

This is a backwards compatibility issue. I agree that it would be easier if the "inner blocks" didn't let the user access outer scope properties. This is how the Groovy DSL works, though, and if the DSL was to be designed _today_, I guess choices would be different.

**Comment by uschindler** [comment]
Maybe a good idea would be to make a "really useful" deprecation warning out of it (many of those are just annoying). If you accidentally try to set a nonexisting property on an inner extension block it should print warning.

**Comment by ljacomet** [comment]
Glad that the situation is clear now.

Given that, I do not think re-opening this issue makes sense as it is hitting a limitation of the toolchain integration. Note that in order to lift this specific limitation, #16242 (and the linked issue) need to be resolved.

**Comment by uschindler** [comment]
I will open a low priority bug to maybe support Toolchains in forbiddenapis, but if there are no changes in Gradle's support for external plugin authors and long needed cleanup in their APIs, I will close all further issues with #notanissue and refer to: https://twitter.com/thetaph1/status/1498631483887689732?s=20&t=cr1P9cI1pKgnrouTlY5PUg

I would also like to give away the Gradle integration of forbiddenapis and delete the Gradle code from my project and instead hope that Gradle writes their own plugin that they can maintain in their own codebase.
