### ISSUE TITLE
The request for this plugin could not be satisfied because the plugin is already on the classpath with an unknown version

### ISSUE THREAD

**Issue by Goooler** [gradle/gradle#20084]
### Expected Behavior
Can `implementation` plugins declared in version catalogs under `buildSrc`.

### Current Behavior
Throw:
```
Build file 'C:\Users\Administrator\AndroidStudioProjects\I18nDemo\build.gradle.kts' line: 1

Error resolving plugin [id: 'com.android.application', version: '7.1.2', apply: false]
> The request for this plugin could not be satisfied because the plugin is already on the classpath with an unknown version, so compatibility cannot be checked.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleException: Error resolving plugin [id: 'com.android.application', version: '7.1.2', apply: false]
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:237)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.lambda$resolvePluginRequests$3(DefaultPluginRequestApplicator.java:169)
	at org.gradle.util.internal.CollectionUtils.collect(CollectionUtils.java:207)
	at org.gradle.util.internal.CollectionUtils.collect(CollectionUtils.java:201)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolvePluginRequests(DefaultPluginRequestApplicator.java:167)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:102)
	at org.gradle.kotlin.dsl.provider.PluginRequestsHandler.handle(PluginRequestsHandler.kt:48)
	at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost.applyPluginsTo(KotlinScriptEvaluator.kt:195)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.applyPluginsTo(Interpreter.kt:398)
	at Program.execute(Unknown Source)
```

### Context
My root `build.gradle.kts`:
```kotlin
plugins {
  alias(libs.plugins.android.application) apply false
  alias(libs.plugins.android.library) apply false
  alias(libs.plugins.kotlin.android) apply false
}
```
My `build.gradle.kts` in `buildSrc`:
```kotlin
plugins {
  `kotlin-dsl`
}

repositories {
  google()
  mavenCentral()
  gradlePluginPortal()
}

dependencies {
  implementation(libs.gradlePlugin.android)
  implementation(libs.gradlePlugin.kotlin)
}
```

My version catalog:
```toml
[versions]
agp = "7.1.2"
kotlin = "1.6.10"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
```

### Steps to Reproduce 
In this PR https://github.com/Goooler/I18nDemo/pull/4.

### Your Environment
Gradle 7.4

**Comment by jbartok** [comment]
The reproducer link is invalid. Could you pls. give us the right link?

**Comment by Goooler** [comment]
It's right now, I made it private before.

**Comment by ljacomet** [comment]
This is a known limitation of the `plugins` block. A plugin declaration cannot use a version if the plugin is already on the classpath.
With Gradle 7.4, this limitation was constrained even more to cases where Gradle does not know the version already on the classpath.

Unfortunately, the combination of `buildSrc` and `plugins.alias` remains problematic. You will have to replace the `alias` declaration with one that removes the version from the generated accessor.

Something like:
```
plugins {
  id(libs.plugins.android.application.get().pluginId) apply false
  id(libs.plugins.android.library.get().pluginId) apply false
  id(libs.plugins.kotlin.android.get().pluginId) apply false
}
```

See #17968

**Comment by Goooler** [comment]
It works, thanks.

**Comment by sschuberth** [comment]
Also see https://github.com/gradle/gradle/issues/18236.
