### ISSUE TITLE
Not all declared repositories are used for resolving dependencies in pluginManagement.includeBuild build

### ISSUE THREAD

**Issue by eugene-krivobokov** [gradle/gradle#20259]
Build in `pluginManagement.includeBuild` doesn't search dependency through all repositories
in his own `dependencyResolutionManagement\pluginManagement` repositories.

### Current Behavior

See "Steps to reproduce" and "Context" before.

Dependency is searched only in plugins portal:

```
Could not resolve all files for configuration 'classpath'.
> Could not find com.avito.android:build-trace:local.
  Searched in the following locations:
    - https://plugins.gradle.org/m2/com/avito/android/build-trace/local/build-trace-local.pom
  If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
  Required by:
      unspecified:unspecified:unspecified > project :build-logic-settings:scan-plugin

org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of null.
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:71)
        at org.gradle.api.internal.tasks.AbstractTaskDependency.getDependencies(AbstractTaskDependency.java:50)
        at org.gradle.composite.internal.CompositeBuildClassPathInitializer.execute(CompositeBuildClassPathInitializer.java:41)
        at org.gradle.composite.internal.CompositeBuildClassPathInitializer.execute(CompositeBuildClassPathInitializer.java:29)
        at org.gradle.api.internal.initialization.DefaultScriptClassPathResolver.resolveClassPath(DefaultScriptClassPathResolver.java:40)
        at org.gradle.api.internal.initialization.DefaultScriptHandler.getNonInstrumentedScriptClassPath(DefaultScriptHandler.java:96)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.defineScriptHandlerClassScope(DefaultPluginRequestApplicator.java:177)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:142)
        at org.gradle.kotlin.dsl.provider.PluginRequestsHandler.handle(PluginRequestsHandler.kt:48)
        at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost.applyPluginsTo(KotlinScriptEvaluator.kt:195)

```

build-logic-settings/settings.gradle.kts defines other repositories:

```kotlin
pluginManagement {

    repositories {
        gradlePluginPortal()
        mavenLocal()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositories {
        gradlePluginPortal()
        mavenLocal()
        mavenCentral()
    }
}
```

Also worth to mention: 

- `exclusiveContent` for this dependency doesn't help to change behavior
- Dependencies from mavenCentral are resolved without any issues
- Intercepted http requests also shows requests only to plugin portal:
```
HEAD https://plugins.gradle.org/m2/com/avito/android/build-trace/local/build-trace-local.pom
--> 303

HEAD https://repo.gradle.org/artifactory/jcenter/com/avito/android/build-trace/local/build-trace-local.pom
--> 404
```

### Expected Behavior

Dependencies are resolved from declared repositories in `dependencyResolutionManagement`.

### Context

I'll explain some details about the test project.
It contains two included builds:

- `build-logic-settings` - for settings
- `build-logic` - for buildscripts

Root project:

settings.gradle.kts:

```kotlin
pluginManagement {
    includeBuild("build-logic-settings")
}
...
includeBuild("build-logic")
```

`build-logic` project also uses `build-logic-settings`:

```
pluginManagement {
    includeBuild("../build-logic-settings")
}
```

### Steps to Reproduce 

- Checkout https://github.com/avito-tech/avito-android/tree/pluginManagement-repository-issue
- `make publish_to_maven_local`
- Uncomment dependency in build-logic-settings/scan-plugin/build.gradle.kts
- `./gradlew help`

### Your Environment

- Gradle 7.4.1

Can't make a build scan because it fails too early.

**Comment by eugene-krivobokov** [comment]
I've found the cause in logic. It's a chicken and egg problem.

In the root project:
```
pluginManagement {
    // at this moment we have no custom repositories for `build-logic-settings`
    includeBuild("build-logic-settings") 
}
// plugins from build-logic-settings modifies pluginManagement in this project 
plugins {
    id("convention-plugins")
    id("convention-dependencies")
    id("convention-enterprise")
    id("convention-cache")
}
```
Fix:
```
pluginManagement {
    repositories { // repos to build included builds
        gradlePluginPortal()
        mavenLocal()
        mavenCentral()
    }
    includeBuild("build-logic-settings")
}
```

**Comment by donat** [comment]
I'm glad you found the solution.
