### ISSUE TITLE
Build with included builds fails with "Unable to make progress running work"

### ISSUE THREAD

**Issue by breskeby** [gradle/gradle#20254]
When running our plugin examples with our elasticsearch build included using the latest 7.5 snapshot the build fails with the following error:

```
> Task :custom-suggester:yamlRestTest
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.gradle.api.internal.tasks.testing.worker.TestWorker (file:/Users/rene/.gradle/wrapper/dists/gradle-7.5-20220318231621+0000-all/aqjfveoxemck6xhxte170t4aj/gradle-7.5-20220318231621+0000/lib/plugins/gradle-testing-base-7.5.jar)
WARNING: Please consider reporting this to the maintainers of org.gradle.api.internal.tasks.testing.worker.TestWorker
WARNING: System::setSecurityManager will be removed in a future release
Unable to make progress running work. The following items are queued for execution but none of them can be started:
  - :elasticsearch-master:distribution:archives:buildDarwinTar (not ready)
  - SymbolicLinkPreservingUntarTransform (dependencies not complete)
  - :painless-whitelist:yamlRestTest (dependencies not complete)
  - :painless-whitelist:check (dependencies not complete)
  - :painless-whitelist:build (dependencies not complete)
  - SymbolicLinkPreservingUntarTransform (dependencies not complete)
  - :security-authorization-engine:javaRestTest (dependencies not complete)
  - :security-authorization-engine:check (dependencies not complete)
  - :security-authorization-engine:build (dependencies not complete)
  - producer locations for task group 0 (dependencies not complete)
<============-> 98% EXECUTING [5m 53s]
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> :elasticsearch-master:distribution:archives:buildDarwinTar
> IDLE
> IDLE
> IDLE
```

We never saw this with Gradle 7.4.1. I've also attached a build scan dump as our regular build scan is too large for gradle.com. As you can See
from the build scan the task `:elasticsearch-master:distribution:archives:buildDarwinTar` has been executed successfully. 
Though this complaint. Also notice that the root project of the included build is named `:elasticsearch-master` though it is configured
as `elasticsearch` in its settings.gradle file.

We do not hit this issue in all builds. It's more likely to happen when more work is done during the build like building against a clean repo and an empty gradle user home. 

To reproduce this this should work:

1. git clone https://github.com/breskeby/elasticsearch.git
2. git checkout update-to-gradle-7-5
3. cd plugins/example
4. ./gradlew build --include-build ../.. -g .guh

The build scan dump:
- just rename to dj34bn6lpv6de.scandump

[dj34bn6lpv6de.scandump.zip](https://github.com/gradle/gradle/files/8331134/dj34bn6lpv6de.scandump.zip)

**Comment by big-guy** [comment]
@adammurdoch does this sound familiar?

**Comment by ljacomet** [comment]
@breskeby Can you try with a recent nightly?
This might have been fixed already.

**Comment by ljacomet** [comment]
Ok thanks, raised it for attention

**Comment by adammurdoch** [comment]
The reproducer does not fail for me (running it many many times). Does it fail with an exception or deadlock? If it deadlocks, can you grab a thread dump?

**Comment by breskeby** [comment]
It fails with an exception:

```

> Task :custom-suggester:check
> Task :custom-suggester:build
Unable to make progress running work. The following items are queued for execution but none of them can be started:
  - :elastic+elasticsearch+pull-request+example-plugins:distribution:archives:buildLinuxTar (dependencies not complete)
  - work action resolve elasticsearch-linux-x86_64.tar.gz (project :elastic+elasticsearch+pull-request+example-plugins:distribution:archives:linux-tar) (dependencies not complete)
  - SymbolicLinkPreservingUntarTransform (dependencies not complete)
  - :painless-whitelist:yamlRestTest (dependencies not complete)
  - :painless-whitelist:check (dependencies not complete)
  - :painless-whitelist:build (dependencies not complete)
  - SymbolicLinkPreservingUntarTransform (dependencies not complete)
  - :security-authorization-engine:javaRestTest (dependencies not complete)
  - :security-authorization-engine:check (dependencies not complete)
  - :security-authorization-engine:build (dependencies not complete)
  - producer locations for task group 0 (dependencies not complete)
build complete, generating: /dev/shm/elastic+elasticsearch+pull-request+example-plugins/build/772.tar.bz2

FAILURE: Build failed with an exception.

* What went wrong:
Unable to make progress running work. There are items queued for execution but none of them can be started

* Try:
> Run with --info or --debug option to get more log output.

* Exception is:
java.lang.IllegalStateException: Unable to make progress running work. There are items queued for execution but none of them can be started
	at org.gradle.execution.plan.DefaultPlanExecutor$Queue.assertHealthy(DefaultPlanExecutor.java:286)
	at org.gradle.internal.resources.DefaultResourceLockCoordinationService$2.transform(DefaultResourceLockCoordinationService.java:83)
	at org.gradle.internal.resources.DefaultResourceLockCoordinationService$2.transform(DefaultResourceLockCoordinationService.java:80)
	at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:110)
	at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:80)
	at org.gradle.execution.plan.DefaultPlanExecutor.assertHealthy(DefaultPlanExecutor.java:105)
	at org.gradle.composite.internal.DefaultBuildControllers.awaitCompletion(DefaultBuildControllers.java:123)
	at org.gradle.composite.internal.DefaultBuildControllers.execute(DefaultBuildControllers.java:96)
	at org.gradle.composite.internal.DefaultIncludedBuildTaskGraph$DefaultBuildTreeWorkGraph.runWork(DefaultIncludedBuildTaskGraph.java:191)
	at org.gradle.internal.buildtree.DefaultBuildTreeWorkExecutor.execute(DefaultBuildTreeWorkExecutor.java:24)
	at org.gradle.internal.buildtree.BuildOperationFiringBuildTreeWorkExecutor$1.call(BuildOperationFiringBuildTreeWorkExecutor.java:40)
	at org.gradle.internal.buildtree.BuildOperationFiringBuildTreeWorkExecutor$1.call(BuildOperationFiringBuildTreeWorkExecutor.java:37)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.internal.buildtree.BuildOperationFiringBuildTreeWorkExecutor.execute(BuildOperationFiringBuildTreeWorkExecutor.java:37)
	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.lambda$doScheduleAndRunTasks$2(DefaultBuildTreeLifecycleController.java:90)
	at org.gradle.composite.internal.DefaultIncludedBuildTaskGraph.withNewWorkGraph(DefaultIncludedBuildTaskGraph.java:100)
	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.doScheduleAndRunTasks(DefaultBuildTreeLifecycleController.java:88)
	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.lambda$runBuild$4(DefaultBuildTreeLifecycleController.java:106)
	at org.gradle.internal.model.StateTransitionController.lambda$transition$5(StateTransitionController.java:166)
	at org.gradle.internal.model.StateTransitionController.doTransition(StateTransitionController.java:247)
	at org.gradle.internal.model.StateTransitionController.lambda$transition$6(StateTransitionController.java:166)
	at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
```

trying to get a thread dumb

**Comment by breskeby** [comment]
@adammurdoch I can't reproduce it _every time_ on my MacBook anymore with the latest nightly but on our beefy ci machines (gcloud n1-standard-16) with ubuntu and centos8 I see this every time when running 

```
./gradlew --include-build ../.. clean build --parallel --max-workers=4 -Dorg.gradle.jvmargs=-Xmx8g --rerun-tasks
``` 
If I skip the `--rerun-tasks` section, I can see the error on the first run, but often not on a 2nd or 3rd invocation.

If there is there anything else I can provide that helps nailing this down?

**Comment by eskatos** [comment]
@breskeby could you please try with `7.5-20220504092701+0000`?

**Comment by eskatos** [comment]
@breskeby, could you please test with `7.5-20220504102347+0000`?

**Comment by breskeby** [comment]
Unfortunately this snapshot version contains a regression in artifact transforms ( see https://github.com/gradle/gradle/issues/20659 ) that blocks us from reproducing the error above

**Comment by ice1000** [comment]
Is this going to block 7.5 RC-1?

**Comment by breskeby** [comment]
@adammurdoch find attached the console output for the `7.5-branch-am_comp_build_deadlock-20220506081633+0000` snapshot

[consoleText-2.txt](https://github.com/gradle/gradle/files/8639175/consoleText-2.txt)

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/20727

**Comment by ice1000** [comment]
New release candidate when!!

**Comment by adammurdoch** [comment]
@ice1000 as soon as we can. This was the last blocker so the RC shouldn't be too much longer.

**Comment by breskeby** [comment]
@adammurdoch I have bad news. I've just run 1.0-milestone-1 and see that problem again. I'll ping you on slack for details

**Comment by breskeby** [comment]
[consoleText-4.txt](https://github.com/gradle/gradle/files/8681861/consoleText-4.txt)

Here's the console output

**Comment by big-guy** [comment]
I replied on Slack, but FYI, 7.5-milestone-1 is different enough from 7.5-RC1 that I would try that first. RC1 should be available today.
