### ISSUE TITLE
SpringBoot DSL breaks configuration cache

### ISSUE THREAD

**Issue by wyhasany** [gradle/gradle#20469]
Using Spring Boot Gradle's DSL API breaks configuration cache. While manually creating task mitigates this issue.

aka that fails:
```groovy
springBoot {
    buildInfo {
        properties {
            time = EPOCH
        }
    }
}
```

while this works smoothlessly:
```groovy
def bootBuildInfo = tasks.register("bootBuildInfo", BuildInfo) {
    properties {
        time = java.time.Instant.EPOCH
    }
    destinationDir = new File(sourceSets.main.output.resourcesDir.toString(), "META-INF")
}

classes.dependsOn bootBuildInfo
```

### Expected Behavior
DSL should work in the very same way as explicit tasks creation

### Current Behavior
Using DSL end ups with NPEs

### Steps to Reproduce 
to reproduce issue, clone project:
https://github.com/wyhasany/reproduce-spring-boot-gradle-bootbuildinfo-config-cache-incompatibility

```
git clone https://github.com/wyhasany/reproduce-spring-boot-gradle-bootbuildinfo-config-cache-incompatibility.git
cd reproduce-spring-boot-gradle-bootbuildinfo-config-cache-incompatibility
./gradlew bootBuildInfo --console=plain -i #first run works correctly
./gradlew bootBuildInfo --console=plain -i #second run fails
```

Second run fails with following error:
```
* What went wrong:
Execution failed for task ':bootBuildInfo'.
> Cannot invoke "org.gradle.api.file.DirectoryProperty.getAsFile()" because "this.destinationDir" is null

* Try:
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':bootBuildInfo'.
	at org.gradle.api.internal.tasks.properties.DefaultTaskProperties.resolve(DefaultTaskProperties.java:76)
	at org.gradle.execution.plan.LocalTaskNode.resolveMutations(LocalTaskNode.java:231)
	at org.gradle.execution.plan.DefaultExecutionPlan.getResolvedMutationInfo(DefaultExecutionPlan.java:737)
	at org.gradle.execution.plan.DefaultExecutionPlan.selectNext(DefaultExecutionPlan.java:649)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$executeNextNode$2(DefaultPlanExecutor.java:197)
	at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:186)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:140)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
Caused by: java.lang.NullPointerException: Cannot invoke "org.gradle.api.file.DirectoryProperty.getAsFile()" because "this.destinationDir" is null
	at org.springframework.boot.gradle.tasks.buildinfo.BuildInfo.getDestinationDir(BuildInfo.java:80)
	at org.springframework.boot.gradle.tasks.buildinfo.BuildInfo_Decorated.getDestinationDir(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue$1$1.create(AbstractNestedRuntimeBeanNode.java:77)
	at org.gradle.internal.deprecation.DeprecationLogger.whileDisabled(DeprecationLogger.java:244)
	at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue$1.get(AbstractNestedRuntimeBeanNode.java:73)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
	at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue.getUnprocessedValue(AbstractNestedRuntimeBeanNode.java:139)
	at org.gradle.api.internal.tasks.properties.FileParameterUtils.resolveOutputFilePropertySpecs(FileParameterUtils.java:116)
	at org.gradle.api.internal.tasks.properties.OutputUnpacker.visitOutputFileProperty(OutputUnpacker.java:67)
	at org.gradle.api.internal.tasks.properties.CompositePropertyVisitor.visitOutputFileProperty(CompositePropertyVisitor.java:69)
	at org.gradle.api.internal.tasks.properties.annotations.AbstractOutputPropertyAnnotationHandler.visitPropertyValue(AbstractOutputPropertyAnnotationHandler.java:50)
	at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode.visitProperties(AbstractNestedRuntimeBeanNode.java:56)
	at org.gradle.api.internal.tasks.properties.bean.RootRuntimeBeanNode.visitNode(RootRuntimeBeanNode.java:32)
	at org.gradle.api.internal.tasks.properties.DefaultPropertyWalker.visitProperties(DefaultPropertyWalker.java:41)
	at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:42)
	at org.gradle.api.internal.tasks.properties.DefaultTaskProperties.resolve(DefaultTaskProperties.java:67)
	at org.gradle.execution.plan.LocalTaskNode.resolveMutations(LocalTaskNode.java:231)
	at org.gradle.execution.plan.DefaultExecutionPlan.getResolvedMutationInfo(DefaultExecutionPlan.java:737)
	at org.gradle.execution.plan.DefaultExecutionPlan.selectNext(DefaultExecutionPlan.java:649)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$executeNextNode$2(DefaultPlanExecutor.java:197)
	at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:186)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:140)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
```
It seems that for some reason constructor:
https://github.com/spring-projects/spring-boot/blob/b0fb2128366a63e66abaf228ab5627e3ad0152b9/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/tasks/buildinfo/BuildInfo.java#L52-L55
is not executed once configuration cache is enabled.

### Your Environment
Reproducible on every env

The bug originally was reported at Spring Boot repo:
https://github.com/spring-projects/spring-boot/issues/30663

**Comment by ov7a** [comment]
Sorry for the late reply.

Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by ov7a** [comment]
This issue was reproducible with Gradle 7.1--7.5.1 and was fixed in Gradle 7.6
