### ISSUE TITLE
NPE with managed custom property

### ISSUE THREAD

**Issue by henniger** [gradle/gradle#20506]
Writing a custom task with custom input type for list property as managed properties in combination with a RegularFileProperty fails with NPE on task execution - see example below.

Removing outputFile: RegularFileProperty or set value to non-null succeeds.

Example build.gradle.kts to reproduce
```
plugins {
    id("java")
}

interface PropertySpec {
    @get:Input
    val key: Property<String>

    @get:Input
    @get:Optional
    val value: Property<String?>
}

abstract class TestTask : DefaultTask() {
    @get:Input
    abstract val properties: ListProperty<PropertySpec>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun doSomething() {
    }
}

tasks.register("dummy", TestTask::class.java) {
    outputFile.set(file("file.xml"))
    properties.addAll(provider {
        val objectFactory = project.objects
        listOf(
            objectFactory.newInstance(PropertySpec::class.java).apply {
                key.set("key")
                value.set(null as String?)
            }
        )
    })
}
```

My build environment:
```
------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.2 (Oracle Corporation 17.0.2+8-86)
OS:           Linux 5.13.0-39-generic amd64
```

**Comment by jbartok** [comment]
```
org.gradle.api.UncheckedIOException: Could not add entry ':dummy' to cache executionHistory.bin (/Users/jozsef/Work/bt-support/20506/.gradle/7.4.2/executionHistory/executionHistory.bin).
        at org.gradle.cache.internal.btree.BTreePersistentIndexedCache.put(BTreePersistentIndexedCache.java:162)
        at org.gradle.cache.internal.DefaultMultiProcessSafePersistentIndexedCache.lambda$put$1(DefaultMultiProcessSafePersistentIndexedCache.java:67)
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.doWriteAction(DefaultFileLockManager.java:216)
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.writeFile(DefaultFileLockManager.java:206)
        at org.gradle.cache.internal.DefaultCacheAccess$UnitOfWorkFileAccess.writeFile(DefaultCacheAccess.java:449)
        at org.gradle.cache.internal.DefaultMultiProcessSafePersistentIndexedCache.put(DefaultMultiProcessSafePersistentIndexedCache.java:67)
        at org.gradle.cache.internal.AsyncCacheAccessDecoratedCache.lambda$putLater$1(AsyncCacheAccessDecoratedCache.java:56)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.cache.internal.CacheAccessWorker$2.run(CacheAccessWorker.java:185)
        at org.gradle.internal.Factories$1.create(Factories.java:31)
        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:220)
        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:201)
        at org.gradle.cache.internal.CacheAccessWorker.flushOperations(CacheAccessWorker.java:175)
        at org.gradle.cache.internal.CacheAccessWorker.run(CacheAccessWorker.java:145)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
Caused by: java.lang.IllegalArgumentException: Cannot encode a null string.
        at org.gradle.internal.serialize.kryo.KryoBackedEncoder.writeString(KryoBackedEncoder.java:79)
        at org.gradle.internal.snapshot.impl.SnapshotSerializer.write(SnapshotSerializer.java:255)
        at org.gradle.internal.snapshot.impl.SnapshotSerializer.write(SnapshotSerializer.java:260)
        at org.gradle.internal.snapshot.impl.SnapshotSerializer.write(SnapshotSerializer.java:248)
        at org.gradle.internal.snapshot.impl.SnapshotSerializer.write(SnapshotSerializer.java:260)
        at org.gradle.internal.snapshot.impl.SnapshotSerializer.write(SnapshotSerializer.java:164)
        at org.gradle.internal.snapshot.impl.SnapshotSerializer.write(SnapshotSerializer.java:32)
        at org.gradle.internal.execution.history.impl.DefaultPreviousExecutionStateSerializer.writeValueSnapshot(DefaultPreviousExecutionStateSerializer.java:178)
        at org.gradle.internal.execution.history.impl.DefaultPreviousExecutionStateSerializer.writeInputProperties(DefaultPreviousExecutionStateSerializer.java:131)
        at org.gradle.internal.execution.history.impl.DefaultPreviousExecutionStateSerializer.write(DefaultPreviousExecutionStateSerializer.java:104)
        at org.gradle.internal.execution.history.impl.DefaultPreviousExecutionStateSerializer.write(DefaultPreviousExecutionStateSerializer.java:39)
        at org.gradle.cache.internal.btree.BTreePersistentIndexedCache$DataBlock.setValue(BTreePersistentIndexedCache.java:680)
        at org.gradle.cache.internal.btree.BTreePersistentIndexedCache$DataBlock.<init>(BTreePersistentIndexedCache.java:667)
        at org.gradle.cache.internal.btree.BTreePersistentIndexedCache.put(BTreePersistentIndexedCache.java:154)
        ... 15 more
```

**Comment by henniger** [comment]
here is a project to reproduce:  https://github.com/henniger/gradle-issue-20506

The problem presents itself in a slightly different form depending on the type of execution.

Running with Java 17:
``
$ ./gradlew dummy
> Task :dummy FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':dummy'.
> Cannot invoke "java.lang.CharSequence.length()" because "value" is null
``

Running with Java 11:
``
$ ./gradlew dummy
> Task :dummy FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':dummy'.
> java.lang.NullPointerException (no error message)
``

**Comment by wolfs** [comment]
@henniger You should use `@Nested` and not `@Input` for the `ListProperty`. Then Gradle will take into account  the annotations on `PropertySpec`, and I suppose that is what you want. The error message is pretty misleading, I wonder if we could make it better.

**Comment by ov7a** [comment]
It looks like a duplicate of
* https://github.com/gradle/gradle/issues/24405

which was fixed in 8.3 by
* https://github.com/gradle/gradle/pull/25608

I can no longer reproduce it.
