### ISSUE TITLE
Gradle 7.5/Gradle Enterprise 3.10: Cannot run background tasks which run a separate process

### ISSUE THREAD

**Issue by AlecStrong** [gradle/gradle#20563]
### Expected Behavior
Following [this example](https://docs.gradle.com/enterprise/gradle-plugin/#adding_expensive_data) (the kotlin version) I should be able to run an external process to collect additional data for a build scan.

### Current Behavior
Here is the stack trace I get when I follow that example: 
```
org.gradle.api.InvalidUserCodeException: Starting an external process 'git rev-parse --verify HEAD' during configuration time is unsupported.
        at org.gradle.configurationcache.initialization.DefaultConfigurationCacheProblemsListener.onExternalProcessStarted(ConfigurationCacheProblemsListener.kt:78)
        at jdk.internal.reflect.GeneratedMethodAccessor2882.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:464)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:446)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:61)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:434)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:221)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:192)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy31.onExternalProcessStarted(Unknown Source)
        at org.gradle.process.internal.DefaultExecActionFactory$DecoratingExecActionFactory$1.beforeExecutionStarted(DefaultExecActionFactory.java:395)
        at jdk.internal.reflect.GeneratedMethodAccessor2881.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:43)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:245)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:157)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:141)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy226.beforeExecutionStarted(Unknown Source)
        at org.gradle.process.internal.DefaultExecHandle.start(DefaultExecHandle.java:266)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:36)
        at org.gradle.process.internal.DefaultExecActionFactory.exec(DefaultExecActionFactory.java:202)
        at org.gradle.process.internal.DefaultExecOperations.exec(DefaultExecOperations.java:37)
        at com.squareup.cash.BuildScansGradlePlugin.addGitMetadata$lambda-14$lambda-13(BuildScansGradlePlugin.kt:255)
        at com.gradle.enterprise.gradleplugin.internal.extension.b$4.run(SourceFile:183)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### Context

This is in a custom configuration plugin, so I'm not using kotlin script but normal kotlin. My actual code looks like:

```kotlin
buildScan.run {
  val execOps = objects.newInstance(ScriptServices::class.java).execOps
  background {
    val os = java.io.ByteArrayOutputStream()
    execOps.exec {
      it.commandLine("git", "rev-parse", "--verify", "HEAD")
      it.standardOutput = os
    }
    value("Git Commit ID", os.toString())
  }
}
```

which should be identical to the example linked

**Comment by mlopatkin** [comment]
Thank you for the report! We're aware of this problem and working on a solution in #20563. I'm closing this issue as a duplicate.

**Comment by mlopatkin** [comment]
> Sounds good! That link is just this issue again, is there a public issue or something i could subscribe to?

My bad, #20536 is the proper one. I've updated my comment above.
