### ISSUE TITLE
Jacoco reports error after changing Gradle version

### ISSUE THREAD

**Issue by manymonsters** [gradle/gradle#20845]
When I was using Gradle 7.2, there was no problem with code coverage, but after I recently upgraded Gradle to 7.3.3, the .ec files are all 0 Bytes

### Current Behavior
Throwing exception when writing .ec file

### Steps to Reproduce 
This problem only occurs after upgrading the Gradle version to 7.3.3. Before the 7.3.3 version, there was no problem. I only upgraded Gradle.

### Your Environment
Jacoco Version : 0.8.2
Gradle Version : 7.3.3

### Error info when writing .ec file

```
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.monster.test.appium.espresso.TestApplication.onTestFinished(TestApplication.kt:60)
        at com.monster.test.appium.espresso.jacoco.UITestBroadcastReceiver.onReceive(UITestBroadcastReceiver.kt:19)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1558)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at com.monster.libcrashhandler.CrashHandler.setCrashHandler$lambda-6(CrashHandler.kt:230)
        at com.monster.libcrashhandler.CrashHandler.$r8$lambda$QnsRQAjU9rzH-m6zacxgeGWFy5Y(Unknown Source:0)
        at com.monster.libcrashhandler.CrashHandler$$ExternalSyntheticLambda1.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.IllegalStateException: JaCoCo agent not started.
        at org.jacoco.agent.rt.internal_3570298.Agent.getInstance(Agent.java:77)
        at org.jacoco.agent.rt.RT.getAgent(RT.java:33)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.monster.test.appium.espresso.TestApplication.onTestFinished(TestApplication.kt:60) 
        at com.monster.test.appium.espresso.jacoco.UITestBroadcastReceiver.onReceive(UITestBroadcastReceiver.kt:19) 
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1558) 
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:224) 
        at com.monster.libcrashhandler.CrashHandler.setCrashHandler$lambda-6(CrashHandler.kt:230) 
        at com.monster.libcrashhandler.CrashHandler.$r8$lambda$QnsRQAjU9rzH-m6zacxgeGWFy5Y(Unknown Source:0) 
        at com.monster.libcrashhandler.CrashHandler$$ExternalSyntheticLambda1.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7562) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
```

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

You can use the following as a base for your reproducer: https://github.com/gradle/gradle-issue-reproducer

This issue will be closed after 7 days unless you can provide more information.

Also, this is most likely an Android and Jacoco configuration problem.
