### ISSUE TITLE
Make `maven-publish` `artifact()` silently accept a `Provider` with no value 

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#20875]
From my experimentation it looks like `MavenPublication.artifact` resolves `Provider` which make it hard to have a plugin that takes a `Provider` via extension and uses it to configure artifacts. 

I would like to be able to create plugin with this style of configuration: 

```kotlin
plugins {
    id("maven-publish")
}

abstract class MyPluginExtension {
    abstract val artifactDsl: Property<Task>
}
val myPluginExtension = extensions.create<MyPluginExtension>("myPlugin")

publishing {
       publications {
           register<MavenPublication>("maven") {
                from(components["java"])
                artifact(myPluginExtension.artifactDsl) 
            }
       }
 }
```

Then use it like: 
```kotlin
plugins {
   id("my-plugin")
}

myPlugin {
    artifactDsl.set(tasks.distTar)
}
```

**Current behavior**
It works as expected when `artifactDsl` is set, but *if* `artifactDsl` is *never set*, it will fail with this error:

```
Caused by: org.gradle.api.internal.provider.MissingValueException: Cannot query the value of extension 'myPlugin' property 'artifactDsl' because it has no value available.
	at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:86)
	at org.gradle.api.internal.artifacts.dsl.LazyPublishArtifact.getDelegate(LazyPublishArtifact.java:108)
	at org.gradle.api.internal.artifacts.dsl.LazyPublishArtifact.getFile(LazyPublishArtifact.java:98)
	at org.gradle.api.publish.maven.internal.artifact.PublishArtifactBasedMavenArtifact.getFile(PublishArtifactBasedMavenArtifact.java:34)
	at org.gradle.api.publish.maven.internal.artifact.PublishArtifactBasedMavenArtifact_Decorated.getFile(Unknown Source)
	at org.gradle.api.publish.maven.internal.validation.MavenPublicationErrorChecker.checkThatArtifactIsPublishedUnmodified(MavenPublicationErrorChecker.java:47)
	at org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.getPublishedFile(DefaultMavenPublication.java:778)
```

**Desired behavior**

If the provider that is passed to `artifact(...)` returns null, just ignore it.

**Comment by ov7a** [comment]
Sorry for the late reply.

Thank you for your interest in Gradle!

This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***

We don't want to silently ignore missing values. You can use `.getOrElse` or similar methods to explicitly express the "default" behavior (e.g. providing the default value). Another way to do that is to wrap this logic in a function instead of Property.

***

Note that usage of `artifact` breaks Gradle module metadata compatibility and its use is discouraged. You should properly register a consumable configuration as an outgoing variant.
