### ISSUE TITLE
gradle can not download sources.jar in Android Studio

### ISSUE THREAD

**Issue by farmerjohngit** [gradle/gradle#2090]
When I update my gradle version from 3.3 to 3.5. Then the sources.jar have not been download,So I can't see java source for other library in Android Studio.
I try to find out why sources.jar can't be downloaded by debugging gradle.
And I found the `plusConfigurations` is empty when method `getExternalDependencies` in class `org.gradle.plugins.ide.idea.model.internal.IdeaDependenciesProvider` is executed, so the sources.jar will not be downloaded.

### Expected Behavior

Android Studio can auto download and attach the source code. 
### Current Behavior

Android Studio can't auto download and attach the source code. 
### Steps to Reproduce (for bugs)

1. Create a project  by Android Studio(2.3.2)
2. add a dependencies that has sources.jar in repository
3. sync the project
4. you can not found sources.jar in local cache dir(such as  ~/.gradle/caches/modules-2/files-2.1/groupId/artId/version)

### Your Environment

 * Build scan URL: 
gradle 3.5
Android Studio 2.3.2
Mac Os 10.10.4
android gradle plugin (com.android.tools.build:gradle) 2.3.1

**Comment by bmuschko** [comment]
The issue you are experiencing might be a bug in the Android plugin. Would you mind [opening an issue with Google on the respective forum](https://code.google.com/p/android/issues)? They are creating the plugin as well as Android Studio and are far more likely you help you with this.

**Comment by shaishav-mtech** [comment]
Facing similar issue with gradle version: 3.3 and Android plugin version: 2.3.2

**Comment by kongnanlive** [comment]
@bmuschko me too!

**Comment by farmerjohngit** [comment]
I have opened an issue on  https://issuetracker.google.com/issues/62109624. They have fixed it.

**Comment by chalup** [comment]
Not exactly fixed, they simply force the sources download during sync. Can someone from Gradle team confirm if that's a proper fix or maybe there is some other issue in Android Studio/Intellij code?

**Comment by farmerjohngit** [comment]
@chalup  You are right.

**Comment by charlesdurham** [comment]
@farmerjohngit Do you have any information on the gradle and android-plugin versions where this was working correctly?

**Comment by farmerjohngit** [comment]
@charlesdurham I can work correctly  with Android Studio 2.3.3+  gradle 3.3 or 3.4 .

**Comment by farmerjohngit** [comment]
@charlesdurham  But if your project can't work correctly already, you should do something (new project can work correctly in my environment):
1.change the gradle version to 3.3 or 3.4
2.delete the .idea/ dir in your project
3.delete *.iml file in your all module 
4.re-import your project

**Comment by androidmalin** [comment]
I use Android Studio 3.0 Beta 7. 
use `com.android.tools.build:gradle:3.0.0-beta7`,
delete the .idea/ dir
re-import your project
gradle can download sources.jar

**Comment by RyanYans** [comment]
I think the core problem is that the Gradle Version incompatiable with Android Plugin: 
see [https://developer.android.com/studio/releases/gradle-plugin](https://developer.android.com/studio/releases/gradle-plugin)

**Comment by mimers** [comment]
Facing the same problem with Android Studio 3.3.1
Gradle Plugin 2.3.3
Gradle 3.3


Tried delete**, but failed after re-import project and click the 'Downlaod Sources':

java.util.NoSuchElementException
        at java.util.Collections$EmptyIterator.next(Collections.java:4189)
        at org.jetbrains.plugins.gradle.util.GradleAttachSourcesProvider.getSourceFile(GradleAttachSourcesProvider.java:160)
        at org.jetbrains.plugins.gradle.util.GradleAttachSourcesProvider.access$100(GradleAttachSourcesProvider.java:59)
        at org.jetbrains.plugins.gradle.util.GradleAttachSourcesProvider$1$1.onSuccess(GradleAttachSourcesProvider.java:126)
        at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$7.execute(ExternalSystemUtil.java:943)
        at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$9.run(ExternalSystemUtil.java:972)
        at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
        at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
        at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by wzes** [comment]
java.util.NoSuchElementException
	at java.util.Collections$EmptyIterator.next(Collections.java:4189)
	at org.jetbrains.plugins.gradle.util.GradleAttachSourcesProvider.getSourceFile(GradleAttachSourcesProvider.java:160)
	at org.jetbrains.plugins.gradle.util.GradleAttachSourcesProvider.access$100(GradleAttachSourcesProvider.java:59)
	at org.jetbrains.plugins.gradle.util.GradleAttachSourcesProvider$1$1.onSuccess(GradleAttachSourcesProvider.java:126)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$7.execute(ExternalSystemUtil.java:943)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$9.run(ExternalSystemUtil.java:972)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by zmeeagain** [comment]
Same here, Android Plugin Version 3.3.2, Gradle 4.10.1

java.util.NoSuchElementException
	at java.util.Collections$EmptyIterator.next(Collections.java:4189)
	at org.jetbrains.plugins.gradle.util.GradleAttachSourcesProvider.getSourceFile(GradleAttachSourcesProvider.java:160)
	at org.jetbrains.plugins.gradle.util.GradleAttachSourcesProvider.access$100(GradleAttachSourcesProvider.java:59)
	at org.jetbrains.plugins.gradle.util.GradleAttachSourcesProvider$1$1.onSuccess(GradleAttachSourcesProvider.java:126)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$7.execute(ExternalSystemUtil.java:943)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$9.run(ExternalSystemUtil.java:972)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by tennkou** [comment]
> @charlesdurham But if your project can't work correctly already, you should do something (new project can work correctly in my environment):
> 1.change the gradle version to 3.3 or 3.4
> 2.delete the .idea/ dir in your project
> 3.delete *.iml file in your all module
> 4.re-import your project

It not work for me(studio and plugin 3.4.1, gradle 5.1.1)
how to "re-import" my project.
it mean re-open my project?

**Comment by tennkou** [comment]
I cannot see source code for support library like "RecyclerView.java" or "AppBarLayout"...

**Comment by Macilias** [comment]
I updated to latest gradle: com.android.tools.build:gradle:3.5.0
I'm using the distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip

When importing Tensorflow Lite example (Object Detection) from `https://github.com/tensorflow/examples` in particular: 
`https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection` 
and than navigating to org.tensorflow.lite.Interpreter
I can not absolutely get the sources in place :(
When i click download sources in Android Studio: first it says
1. downloading sources 
then:
2. Attaching ...
and than nothing else happens ;(
