### ISSUE TITLE
 Jacoco gradle plugin throws a NoClassDefFoundError

### ISSUE THREAD

**Issue by aljohnston112** [gradle/gradle#20911]
### Expected Behavior

The class def should be found.

### Current Behavior
```
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jacoco/agent/rt/internal_3570298/Offline;
    at androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity.$jacocoInit(Unknown Source:13)
    at androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity.<clinit>(Unknown Source:0)
    at java.lang.Class.newInstance(Native Method)
    at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
    at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3725)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:246)
    at android.app.ActivityThread.main(ActivityThread.java:8653)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
 Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jacoco.agent.rt.internal_3570298.Offline" on path: DexPathList[[zip file "/data/app/~~h8MxzSzcV5J1qu2yJeU5Dg==/com.example.inventory_manager.test-OTl1KcxOXWG6CFw7svj1Pg==/base.apk"],nativeLibraryDirectories=[/data/app/~~h8MxzSzcV5J1qu2yJeU5Dg==/com.example.inventory_manager.test-OTl1KcxOXWG6CFw7svj1Pg==/lib/arm64, /system/lib64, /system/system_ext/lib64]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity.$jacocoInit(Unknown Source:13) 
    at androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity.<clinit>(Unknown Source:0) 
    at java.lang.Class.newInstance(Native Method) 
    at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95) 
    at android.app.Instrumentation.newActivity(Instrumentation.java:1253) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3725) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022) 
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336) 
    at android.os.Handler.dispatchMessage(Handler.java:106) 
    at android.os.Looper.loop(Looper.java:246) 
    at android.app.ActivityThread.main(ActivityThread.java:8653) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
```

### Context
Unable to get coverage for Android tests with instrumentation.

### Steps to Reproduce 
Follow the steps here to get Jacoco coverage for tests

https://about.codecov.io/blog/code-coverage-for-android-development-using-kotlin-jacoco-github-actions-and-codecov/

Try to run this Android test

```
@RunWith(AndroidJUnit4::class)
class StringAdapterTest {

    @Test
    fun testStringAdapter() {
        ActivityScenario.launch(
            TestActivity::class.java
        ).onActivity { activity ->

            }

        }

}
```

### Your Environment
Build scan URL:
https://gradle.com/s/k7h3cqmbgvwkm

**Comment by eskatos** [comment]
Sorry that you're having trouble with Gradle!

A complete reproducer would help reproduce the problem you're having, please consider providing one.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue seems related to Android instrumented tests, you can also report this issue to the Android issue tracker at https://source.android.com/source/report-bugs

**Comment by aljohnston112** [comment]
Here's the issue posted to the Android test repo. 
https://github.com/android/android-test/issues/1377

Here is a minimal reproducible example
https://github.com/aljohnston112/TestJacocoBug/tree/main

**Comment by eskatos** [comment]
Thanks. I see in the linked issue that you figured it out and that it is not a Gradle issue. I'm closing this issue.

**Comment by eskatos** [comment]
Closing
