### ISSUE TITLE
Prevent or help to diagnose accidental recursion to itself in a property

### ISSUE THREAD

**Issue by eugene-krivobokov** [gradle/gradle#20932]
Property allows to set itself as a value.

```kotlin
val myProperty = "..."

configure<Extension> {
    myProperty.set(myProperty)
}
```

```
java.lang.StackOverflowError
        at org.gradle.api.internal.provider.AbstractProperty.getProducer(AbstractProperty.java:174)
        at org.gradle.api.internal.provider.AbstractProperty.getProducer(AbstractProperty.java:178)
        at org.gradle.api.internal.provider.AbstractProperty.getProducer(AbstractProperty.java:178)
        ...
```

https://github.com/eugene-krivobokov/gradle-reproducer-property-recursion

### Expected Behavior

- Fail-fast check which prevents to refer to itself
- Error message contains the name of the problematic property

### Current Behavior

Property allows to set itself and will fail while configuration.

### Context

The problem is it can be diagnosed only in debugger. It may take a lot of time to reproduce the configuration locally and find the reason. I'd like to avoid this at all.

**Comment by lptr** [comment]
We have a similar issue with `ConfigurableFileCollection`s.

**Comment by asodja** [comment]
A more complex reproducer but a real life example what can happen with `MapProperty`:
```
val myMap: MapProperty<String, String> = objects.mapProperty()
val myLazyProp = provider {
    myMap.getting("foo").getOrElse("not_there")
}
myMap.put("bar", myLazyProp.map { "barbar" })
myLazyProp.get()
```

throws:
```
java.lang.StackOverflowError
        at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:72)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:108)
        at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:82)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:108)
        at org.gradle.api.internal.provider.MapCollectors$EntryWithValueFromProvider.collectEntries(MapCollectors.java:100)
        at org.gradle.api.internal.provider.DefaultMapProperty$CollectingSupplier.calculateValue(DefaultMapProperty.java:442)
        at org.gradle.api.internal.provider.DefaultMapProperty.calculateValueFrom(DefaultMapProperty.java:240)
        at org.gradle.api.internal.provider.DefaultMapProperty.calculateValueFrom(DefaultMapProperty.java:35)
        at org.gradle.api.internal.provider.AbstractProperty.doCalculateValue(AbstractProperty.java:142)
        at org.gradle.api.internal.provider.AbstractProperty.calculateOwnValue(AbstractProperty.java:136)
        at org.gradle.api.internal.provider.DefaultMapProperty$EntryProvider.calculateOwnValue(DefaultMapProperty.java:275)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.getOrElse(AbstractMinimalProvider.java:103)
        at Build_gradle$myLazyProp$1.call(build.gradle.kts:3)
        at Build_gradle$myLazyProp$1.call(build.gradle.kts:2)
        at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:72)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:108)
        at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:82)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:108)
        at org.gradle.api.internal.provider.MapCollectors$EntryWithValueFromProvider.collectEntries(MapCollectors.java:100)
        at org.gradle.api.internal.provider.DefaultMapProperty$CollectingSupplier.calculateValue(DefaultMapProperty.java:442)
        at org.gradle.api.internal.provider.DefaultMapProperty.calculateValueFrom(DefaultMapProperty.java:240)
        at org.gradle.api.internal.provider.DefaultMapProperty.calculateValueFrom(DefaultMapProperty.java:35)
        at org.gradle.api.internal.provider.AbstractProperty.doCalculateValue(AbstractProperty.java:142)
        at org.gradle.api.internal.provider.AbstractProperty.calculateOwnValue(AbstractProperty.java:136)
        at org.gradle.api.internal.provider.DefaultMapProperty$EntryProvider.calculateOwnValue(DefaultMapProperty.java:275)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.getOrElse(AbstractMinimalProvider.java:103)
        at Build_gradle$myLazyProp$1.call(build.gradle.kts:3)
        at Build_gradle$myLazyProp$1.call(build.gradle.kts:2)
        ```
