### ISSUE TITLE
Using exec inside a onlyIf/upToDateWhen spec results in "CreateProcess error=267, The directory name is invalid"

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#21007]
### Current Behaviour

I have a custom build service that returns ExecOutput providers. When I use it inside of an `onlyIf { }` or `outputs.upToDateWhen { }` spec, then I get a strange `IOException`

The Spec successfully executes when invoked inside the main task action.

### Steps to Reproduce 

```kotlin
// build.gradle.kts
plugins {
  kotlin("jvm") version "1.7.0"
}


// I have a task that uses my custom build service
// the task has an 'only if' condition
abstract class GitRepoInitTask : DefaultTask() {

  @get:OutputDirectory
  abstract val localRepoDir: DirectoryProperty

  @get:Internal
  abstract val gitService: Property<GitService>

  init {
    group = "git repo manager"
    // both of these cause the failure
    //outputs.upToDateWhen(IsRepoDitGitInitializedSpec)
    super.onlyIf(IsRepoDitGitInitializedSpec)
  }

  @TaskAction
  fun exec() {
    logger.lifecycle("GitRepoInitTask executing")
    // this line works (if onlyIf and upToDateWhen are commented out)
    logger.lifecycle("is satisfied : ${IsRepoDitGitInitializedSpec.isSatisfiedBy(this)}")
  }

  // this spec uses the build service
  object IsRepoDitGitInitializedSpec : Spec<Task> {

    override fun isSatisfiedBy(task: Task?): Boolean = when (task) {
      !is GitRepoInitTask -> false
      else                -> with(task) {
        val gitService = gitService.get()
        val localRepoFile: File = localRepoDir.asFile.get()

        val isInsideWorkTree = gitService.isInsideWorkTree(localRepoFile)
        val isRepoDirTopLevel = gitService.isRepoDirTopLevel(localRepoFile)
        val gitCacheDirExists = localRepoFile.resolve(".git").exists()

        val isRepoDirInitialized =
          isInsideWorkTree.get() && isRepoDirTopLevel.get() && gitCacheDirExists

        logger.lifecycle(
          "isRepoDirInitialized:$isRepoDirInitialized " +
              "(" +
              "isInsideWorkTree:${isInsideWorkTree.get()}, " +
              "isRepoDirTopLevel:${isRepoDirTopLevel.get()}, " +
              "gitCacheDirExists:${gitCacheDirExists}" +
              ")"
        )

        !isRepoDirInitialized
      }
    }
  }
}

// I have a build service that uses the new providers.exec functionality.
@Suppress("UnstableApiUsage") // providers.exec is incubating
abstract class GitService @Inject constructor(
  private val providers: ProviderFactory,
) : BuildService<GitService.Params> {

  private val logger: Logger = Logging.getLogger(GitService::class.java)

  interface Params : BuildServiceParameters {
    val gitExec: Property<String>
  }

  fun isInsideWorkTree(
    repoDir: File,
  ): Provider<Boolean> {
    val result = repoDir git "rev-parse --is-inside-work-tree"
    return result.standardOutput.asText.map { it.trim().toBoolean() }
  }


  fun isRepoDirTopLevel(
    repoDir: File,
  ): Provider<Boolean> {
    val topLevel = repoDir git "rev-parse --show-toplevel"
    return topLevel.standardOutput.asText.map {
      val topLevelFile = File(it)
      topLevelFile.exists()
          && topLevelFile.isDirectory
          && topLevelFile.canonicalPath == repoDir.canonicalPath
    }
  }

  private infix fun File.git(
    cmd: String
  ): ExecOutput {
      val gitExec: String = parameters.gitExec.get()

    logger.lifecycle("GitService git exec $canonicalPath $gitExec $cmd")
    return providers.exec {
      isIgnoreExitValue = true
      workingDir(canonicalPath)
      commandLine(
        org.jetbrains.kotlin.util.parseSpaceSeparatedArgs("$gitExec $cmd")
      )
    }
  }
}

val gitServiceProvider =  gradle.sharedServices.registerIfAbsent(
  "GitService",
  GitService::class,
) {
  maxParallelUsages.set(1)

  parameters {
    gitExec.set("git")
  }
}

tasks.register<GitRepoInitTask>("initGit") {
  localRepoDir.convention(layout.projectDirectory.dir(".gradle/test-checkout"))
  gitService.convention(gitServiceProvider)
}
```

This causes an error. I can't determine what the cause is.

```stacktrace

> Task :initGit FAILED
GitService git exec ...\.gradle\test-checkout git rev-parse --is-inside-work-tree
GitService git exec ...\.gradle\test-checkout git rev-parse --show-toplevel
1 actionable task: 1 executed
Configuration cache entry reused.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':initGit'.
> A problem occurred starting process 'command 'git''

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':initGit'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:69)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:327)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:314)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:307)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:293)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:417)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:339)
	at org.gradle.execution.plan.DefaultPlanExecutor.process(DefaultPlanExecutor.java:96)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.executeWithServices(DefaultTaskExecutionGraph.java:140)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.execute(DefaultTaskExecutionGraph.java:125)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:39)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:51)
	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:54)
	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:43)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor.execute(BuildOperationFiringBuildWorkerExecutor.java:40)
	at org.gradle.internal.build.DefaultBuildLifecycleController.lambda$executeTasks$7(DefaultBuildLifecycleController.java:161)
	at org.gradle.internal.model.StateTransitionController.doTransition(StateTransitionController.java:247)
	at org.gradle.internal.model.StateTransitionController.lambda$tryTransition$7(StateTransitionController.java:174)
	at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
	at org.gradle.internal.model.StateTransitionController.tryTransition(StateTransitionController.java:174)
	at org.gradle.internal.build.DefaultBuildLifecycleController.executeTasks(DefaultBuildLifecycleController.java:161)
	at org.gradle.internal.build.DefaultBuildWorkGraphController$DefaultBuildWorkGraph.runWork(DefaultBuildWorkGraphController.java:156)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:249)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:109)
	at org.gradle.composite.internal.DefaultBuildController.doRun(DefaultBuildController.java:164)
	at org.gradle.composite.internal.DefaultBuildController.access$000(DefaultBuildController.java:45)
	at org.gradle.composite.internal.DefaultBuildController$BuildOpRunnable.run(DefaultBuildController.java:183)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'git''
	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:241)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:218)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:370)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:87)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'git'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(WindowsProcessLauncher.java:22)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:98)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:71)
	... 3 more
Caused by: java.io.IOException: Cannot run program "git" (in directory "...\.gradle\test-checkout"): CreateProcess error=267, The directory name is invalid
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 7 more
Caused by: java.io.IOException: CreateProcess error=267, The directory name is invalid
	... 8 more


* Get more help at https://help.gradle.org

BUILD FAILED in 58ms
12:39:58: Execution finished ':initGit --stacktrace'.
```

### Your Environment

* Windows 10
* Gradle 7.5-rc-2
* Kotlin 1.7.0

```properties
# gradle.properties
org.gradle.caching=true
org.gradle.unsafe.configuration-cache=true
org.gradle.unsafe.configuration-cache-problems=warn

org.gradle.kotlin.dsl.precompiled.accessors.strict=true
```

**Comment by h0tk3y** [comment]
Were there any configuration cache warning reported from the build?

**Comment by eskatos** [comment]
Hi @aSemy,
I see you use `org.gradle.unsafe.configuration-cache-problems=warn` and show only the output of the build reusing the configuration cache.
Could you share what CC problems were reported?
What happens without that option?

**Comment by aSemy** [comment]
I've stripped it down and it's a lot less dramatic than I thought

```kotlin
abstract class GitRepoInitTask @Inject constructor(
  private val executor: ExecOperations
) : DefaultTask() {

  @get:OutputDirectory
  abstract val localRepoDir: DirectoryProperty

  @TaskAction
  fun exec() {
    logger.lifecycle(
      "GitRepoInitTask executing " +
            executor.exec {
              workingDir(localRepoDir.dir("i-do-not-exist"))
              commandLine("git", "status")
            }.exitValue
      )
  }
}

tasks.register<GitRepoInitTask>("example") {
  group = "blah"
  localRepoDir.convention(layout.projectDirectory.dir(".gradle/test-checkout"))
}
```

Basically it's a very unclear error message when the working dir hasn't been created.

The error message is unclear because the stacktrace doesn't lead to the exec that I had defined, so I couldn't track down where the problem was, or begin to see what was going wrong.

I would like to see something like 

```none
ExecSpec failed, working directory does not exist. 
commandLine: git status
workingDir: /path/to/i-do-not-exist
...
```

**Comment by eskatos** [comment]
Thanks. Yep, you can't execute a command in a non existing working directory.
Good you narrowed it down.
I agree the error message is not helpful. A help message would be much better!
Could you please rephrase the issue title and possibly its description?

**Comment by aSemy** [comment]
> Thanks. Yep, you can't execute a command in a non existing working directory.

Unless it's in a `@TaskAction` and the working dir is an `@InputDirectory`?
