### ISSUE TITLE
Could not load the value of field `patterns` of DirectoryTreeSpec error while compiling AndroidX

### ISSUE THREAD

**Issue by yigit** [gradle/gradle#21088]
We are seeing an interesting serialization related error on github builds:
```
Run ./gradlew buildOnServer zipTestConfigsWithApks test 
  ./gradlew buildOnServer zipTestConfigsWithApks test 
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
    GRADLE_BUILD_ACTION_CACHE_KEY_PREFIX: GoldBlooded
    artifact-id: activity
    project-root: activity
    GRADLE_BUILD_CACHE_PASSWORD: ***
    GRADLE_ENTERPRISE_ACCESS_KEY: ***
    JAVA_HOME_8.0.332_x64: /opt/hostedtoolcache/jdk/8.0.332/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/11.0.15/x64
    JAVA_HOME_8_0_332_X64: /opt/hostedtoolcache/jdk/8.0.332/x64
    JAVA_HOME_11.0.15_x64: /opt/hostedtoolcache/jdk/11.0.15/x64
    JAVA_HOME_11_0_15_X64: /opt/hostedtoolcache/jdk/11.0.15/x64
    DIST_DIR: /home/runner/dist
    GRADLE_BUILD_ACTION_SETUP_COMPLETED: true
    GRADLE_BUILD_ACTION_CACHE_RESTORED: true
    JAVA_TOOLS_JAR: /opt/hostedtoolcache/jdk/8.0.332/x64/lib/tools.jar
Starting a Gradle Daemon (subsequent builds will be faster)
Configuration cache is an incubating feature.
Configuration on demand is an incubating feature.
FAILURE: Build failed with an exception.
* What went wrong:
Could not load the value of field `patterns` of `org.gradle.configurationcache.serialization.codecs.DirectoryTreeSpec` bean found in field `fileSystemInputs` of `org.gradle.configurationcache.fingerprint.ConfigurationCacheFingerprint$WorkInputs` bean found in Gradle runtime.
> org.jetbrains.kotlin.gradle.tasks.KotlinCompile$ScriptFilterSpec
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org/
```
https://github.com/androidx/androidx/runs/7026501447?check_suite_focus=true

We do have build scans enabled but for some reasons it doesn't include any of the failed run scans:

https://ge.androidx.dev/scans?search.names=CI%20run&search.timeZoneId=America/Los_Angeles&search.values=2550116603

### Expected Behavior
The project should compile fine. 

### Current Behavior
Fails with the exception above

### Context
An interesting observation is the lack of build scans from these failures, maybe this can be related to that.
Unfortunately, our github CI was broken for a while so we cannot pinpoint it to a change yet.

We are also trying a "#yolo" PR to invalidate cache, will report back if that fixes the issue:
https://github.com/androidx/androidx/pull/424

### Steps to Reproduce 
```
checkout github/androidx/androidx (commit `7ceaf16196501b05c80f5035b44f5fb1da68a3b4`)
cd activity
./gradlew buildOnServer zipTestConfigsWithApks test 
```
Unfortunately, I cannot reproduce this locally even when running with `--scan`. (which is why we are suspecting some corrupted cache)
### Your Environment

Build scan URL: https://ge.androidx.dev/scans?search.names=CI%20run&search.timeZoneId=America/Los_Angeles&search.values=2550116603

Note that the build scans for the failure is missing from the server. The build artifacts here includes daemon logs if that is helpful:
https://github.com/androidx/androidx/actions/runs/2550116603#artifacts

**Comment by jbartok** [comment]
Could you pls. try to get us a stack trace? That would help a lot...

**Comment by yigit** [comment]
Hi,
sorry for the low quality report. We had a type in CI that didn't pass the arguments (and i thought there was a different reason why stacktrace didn't show up).

I forked from the broken build to try to repro but i'm not sure if it will as it was most likely a bad cache problem that is likely invalidated by now.

https://github.com/androidx/androidx/actions/runs/2573751764

I'll update this issue if I can figure out a way to reproduce.

**Comment by jimgoog** [comment]
I managed to get my machine into the failing state.

Ran `./gradlew :benchmark:benchmark-common:dependencies --no-daemon --stacktrace --info --stacktrace --debug --scan &> gradle-issue-21088.log` to get a log file: 
[gradle-issue-21088.log](https://github.com/gradle/gradle/files/9262677/gradle-issue-21088.log)

Deleting ~/.gradle/ didn't seem to resolve the issue, but moving the output directory did resolve the issue.  I saved my old/broken output directory, will keep it around for a few days in case you need something from it.

**Comment by yigit** [comment]
We've hit this problem again:

https://github.com/androidx/androidx-ci-action/actions/runs/4029310419/jobs/6927078624

you can find the build logs in the attachment.

[logs_367.zip](https://github.com/gradle/gradle/files/10524033/logs_367.zip)

**Comment by dniHze** [comment]
This is something we encountered at Cuvva when updating our project to the latest AGP and Gradle. The stacktrace is the very same as the one @yigit attached to his last comment. We were not able to reproduce it locally, only on our CI.

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/actions/runs/4260124424/jobs/7412980728


We had the same issue after [enable gradle configuration cache](https://github.com/topjohnwu/Magisk/pull/6626) and it only triggered on Windows.

**Comment by IGR2014** [comment]
Same when trying to cache build on GitLab CI/CD

**Comment by ansman** [comment]
It feels like it's caused by us not backing up all required directories perhaps.

Looking at [the official Gradle action for Github](https://github.com/gradle/gradle-build-action/blob/main/src/cache-extract-entries.ts#L350) it only seems to back up the config cache directory for the project `.gradle` directory.

For us the exception is: 
```
* Exception is:
org.gradle.api.GradleException: Could not load the value of field `patterns` of `org.gradle.configurationcache.serialization.codecs.DirectoryTreeSpec` bean found in field `fileSystemInputs` of `org.gradle.configurationcache.fingerprint.ConfigurationCacheFingerprint$WorkInputs` bean found in Gradle runtime.
	at org.gradle.configurationcache.serialization.beans.BeanPropertyReaderKt.readPropertyValue(BeanPropertyReader.kt:108)
	at org.gradle.configurationcache.serialization.beans.BeanPropertyReaderKt$readPropertyValue$1.invokeSuspend(BeanPropertyReader.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:41)
	at org.gradle.configurationcache.serialization.CombinatorsKt$reentrant$1$decodeLoop$$inlined$Continuation$1.resumeWith(Continuation.kt:167)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at org.gradle.configurationcache.serialization.CombinatorsKt$reentrant$1.decodeLoop(Combinators.kt:166)
	at org.gradle.configurationcache.serialization.CombinatorsKt$reentrant$1.decode(Combinators.kt:130)
	at org.gradle.configurationcache.serialization.codecs.BindingsBackedCodec.decode(BindingsBackedCodec.kt:59)
	at org.gradle.configurationcache.serialization.DefaultReadContext.read(Contexts.kt:267)
	at org.gradle.configurationcache.fingerprint.ConfigurationCacheFingerprintChecker.checkBuildScopedFingerprint(ConfigurationCacheFingerprintChecker.kt:58)
	at org.gradle.configurationcache.fingerprint.ConfigurationCacheFingerprintController.checkBuildScopedFingerprint(ConfigurationCacheFingerprintController.kt:246)
	at org.gradle.configurationcache.DefaultConfigurationCache$checkBuildScopedFingerprint$1.invokeSuspend(DefaultConfigurationCache.kt:463)
	at org.gradle.configurationcache.DefaultConfigurationCache$checkBuildScopedFingerprint$1.invoke(DefaultConfigurationCache.kt)
	at org.gradle.configurationcache.DefaultConfigurationCache$checkBuildScopedFingerprint$1.invoke(DefaultConfigurationCache.kt)
	at org.gradle.configurationcache.DefaultConfigurationCache$readFingerprintFile$1$1.invokeSuspend(DefaultConfigurationCache.kt:482)
	at org.gradle.configurationcache.DefaultConfigurationCache$readFingerprintFile$1$1.invoke(DefaultConfigurationCache.kt)
	at org.gradle.configurationcache.DefaultConfigurationCache$readFingerprintFile$1$1.invoke(DefaultConfigurationCache.kt)
	at org.gradle.configurationcache.ConfigurationCacheIO$withReadContextFor$1$1$1$1.invokeSuspend(ConfigurationCacheIO.kt:250)
	at org.gradle.configurationcache.ConfigurationCacheIO$withReadContextFor$1$1$1$1.invoke(ConfigurationCacheIO.kt)
	at org.gradle.configurationcache.ConfigurationCacheIO$withReadContextFor$1$1$1$1.invoke(ConfigurationCacheIO.kt)
	at org.gradle.configurationcache.serialization.RunningKt$runReadOperation$2.invokeSuspend(Running.kt:34)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at org.gradle.configurationcache.serialization.RunningKt.runToCompletion(Running.kt:56)
	at org.gradle.configurationcache.serialization.RunningKt.runReadOperation(Running.kt:33)
	at org.gradle.configurationcache.ConfigurationCacheIO.withReadContextFor$configuration_cache(ConfigurationCacheIO.kt:249)
	at org.gradle.configurationcache.DefaultConfigurationCache.readFingerprintFile(DefaultConfigurationCache.kt:480)
	at org.gradle.configurationcache.DefaultConfigurationCache.checkBuildScopedFingerprint(DefaultConfigurationCache.kt:461)
	at org.gradle.configurationcache.DefaultConfigurationCache.checkFingerprintAgainstLoadedProperties(DefaultConfigurationCache.kt:443)
	at org.gradle.configurationcache.DefaultConfigurationCache.checkFingerprint(DefaultConfigurationCache.kt:431)
	at org.gradle.configurationcache.DefaultConfigurationCache.access$checkFingerprint(DefaultConfigurationCache.kt:53)
	at org.gradle.configurationcache.DefaultConfigurationCache$checkFingerprint$1.invoke(DefaultConfigurationCache.kt:280)
	at org.gradle.configurationcache.DefaultConfigurationCache$checkFingerprint$1.invoke(DefaultConfigurationCache.kt:273)
	at org.gradle.configurationcache.ConfigurationCacheRepository$StoreImpl$useForStateLoad$2.invoke(ConfigurationCacheRepository.kt:167)
	at org.gradle.configurationcache.ConfigurationCacheRepository$StoreImpl$useForStateLoad$2.invoke(ConfigurationCacheRepository.kt:166)
	at org.gradle.configurationcache.ConfigurationCacheRepository$withExclusiveAccessToCache$1.create(ConfigurationCacheRepository.kt:249)
	at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.withFileLock(LockOnDemandCrossProcessCacheAccess.java:90)
	at org.gradle.cache.internal.DefaultCacheAccess.withFileLock(DefaultCacheAccess.java:218)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.withFileLock(DefaultPersistentDirectoryStore.java:188)
	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.withFileLock(DefaultCacheFactory.java:214)
	at org.gradle.configurationcache.ConfigurationCacheRepository.withExclusiveAccessToCache(ConfigurationCacheRepository.kt:247)
	at org.gradle.configurationcache.ConfigurationCacheRepository.access$withExclusiveAccessToCache(ConfigurationCacheRepository.kt:49)
	at org.gradle.configurationcache.ConfigurationCacheRepository$StoreImpl.useForStateLoad(ConfigurationCacheRepository.kt:166)
	at org.gradle.configurationcache.DefaultConfigurationCache.checkFingerprint(DefaultConfigurationCache.kt:273)
	at org.gradle.configurationcache.DefaultConfigurationCache.determineCacheAction(DefaultConfigurationCache.kt:223)
	at org.gradle.configurationcache.DefaultConfigurationCache.initializeCacheEntry(DefaultConfigurationCache.kt:116)
	at org.gradle.configurationcache.ConfigurationCacheBuildTreeLifecycleControllerFactory.createRootBuildController(ConfigurationCacheBuildTreeLifecycleControllerFactory.kt:52)
	at org.gradle.composite.internal.DefaultRootBuildState.<init>(DefaultRootBuildState.java:73)
	at org.gradle.composite.internal.BuildStateFactory.createRootBuild(BuildStateFactory.java:66)
	at org.gradle.composite.internal.DefaultIncludedBuildRegistry.createRootBuild(DefaultIncludedBuildRegistry.java:87)
	at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.execute(RootBuildLifecycleBuildActionExecutor.java:39)
	at org.gradle.internal.buildtree.DefaultBuildTreeContext.execute(DefaultBuildTreeContext.java:40)
	at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.lambda$execute$0(BuildTreeLifecycleBuildActionExecutor.java:65)
	at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:53)
	at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.execute(BuildTreeLifecycleBuildActionExecutor.java:65)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:61)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:57)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor.execute(RunAsBuildOperationBuildActionExecutor.java:57)
	at org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.lambda$execute$0(RunAsWorkerThreadBuildActionExecutor.java:36)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:249)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:109)
	at org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.execute(RunAsWorkerThreadBuildActionExecutor.java:36)
	at org.gradle.tooling.internal.provider.continuous.ContinuousBuildActionExecutor.execute(ContinuousBuildActionExecutor.java:110)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecutor.execute(SubscribableBuildActionExecutor.java:64)
	at org.gradle.internal.session.DefaultBuildSessionContext.execute(DefaultBuildSessionContext.java:46)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter$ActionImpl.apply(BuildSessionLifecycleBuildActionExecuter.java:100)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter$ActionImpl.apply(BuildSessionLifecycleBuildActionExecuter.java:88)
	at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:69)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildActionExecuter.java:62)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildActionExecuter.java:41)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:63)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:50)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:38)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
	at org.gradle.util.internal.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:64)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.kotlin.gradle.tasks.KotlinCompile$ScriptFilterSpec
	at org.gradle.configurationcache.serialization.DefaultReadContext.readClass(Contexts.kt:293)
	at org.gradle.configurationcache.serialization.codecs.BeanCodec.decode(BeanCodec.kt:44)
	at org.gradle.configurationcache.serialization.CombinatorsKt$reentrant$1$decodeLoop$1.invokeSuspend(Combinators.kt:165)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	... 106 more
```

**Comment by ansman** [comment]
I just tried restoring exactly what the GH Action saves/restores and it make no difference:
```
~/.gradle/wrapper/
~/.gradle/caches/modules-2/
~/.gradle/caches/8.0.2/
.gradle/configuration-cache/
```
I also deleted all `.lock` and `gc.properties` files before saving.

**Comment by ansman** [comment]
I found the issue, I think. We were switching to the binary distribution of Gradle in the beginning of our CI run. If I changed so that we keep the -all distribution it works just fine.

**Comment by IGR2014** [comment]
> I found the issue, I think. We were switching to the binary distribution of Gradle in the beginning of our CI run. If I changed so that we keep the -all distribution it works just fine.

Hmm, I will try that ASAP, thanks for the hint!

**Comment by mlopatkin** [comment]
This could be caused by cache eviction. Configuration cache may not check presence of all classpath JARs.

**Comment by mlopatkin** [comment]
Hopefully, this has been fixed in 9.0 with:
* #28727

I'm closing this issue as no longer reproducible. Please file a new issue if it happens again with a recent Gradle version.
