### ISSUE TITLE
Execution failed for task ':app:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by Claudioibe** [gradle/gradle#21138]
I'm trying to run the default flutter app and there is an error with the Gradle build
Here is the full output from the terminal

```
[ +530 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+2970 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] cd41fdd495f6944ecd3506c21e94c6567b073278
[   +8 ms] executing: [C:\src\flutter/] git tag --points-at cd41fdd495f6944ecd3506c21e94c6567b073278
[ +452 ms] Exit code 0 from: git tag --points-at cd41fdd495f6944ecd3506c21e94c6567b073278
[   +1 ms] 3.0.2
[  +19 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +218 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[ +267 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +396 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[ +222 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +5 ms] stable
[ +475 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +36 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +49 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +48 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +28 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +26 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +381 ms] executing: C:\Users\USER\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[+1807 ms] List of devices attached
                    emulator-5554          device product:sdk_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:2
[  +94 ms] C:\Users\USER\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[ +662 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +43 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +31 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +514 ms] Skipping pub get: version match.
[+1624 ms] Generating C:\Claudio\Code\myflutterapp\learningdart\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +705 ms] ro.hardware = ranchu
[ +203 ms] Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling software rendering with                    "--enable-software-rendering".
[ +222 ms] Initializing file store
[ +166 ms] Skipping target: gen_localizations
[  +65 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
C:\Claudio\Code\myflutterapp\learningdart\.dart_tool\package_config_subset}
[ +104 ms] gen_dart_plugin_registrant: Complete
[  +13 ms] Skipping target: _composite
[ +121 ms] complete
[  +24 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[  +27 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\src\flutter\bin\cache\dart-sdk\bin\snapshots\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\USER\AppData\Local\Temp\flutter_tools.976a3f8\flutter_tool.5ffea4c8\app.dill --packages
C:\Claudio\Code\myflutterapp\learningdart\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill     
--enable-experiment=alternative-invalidation-strategy
[ +665 ms] executing: C:\Users\USER\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[ +184 ms] <- compile package:learningdart/main.dart
[+3512 ms] --------- beginning of main
                    06-24 17:24:31.727 E/wifi_forwarder(  406): RemoteConnection failed to initialize: RemoteConnection failed to open pipe
[  +28 ms] executing: C:\Users\USER\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +915 ms] Android Debug Bridge version 1.0.41
                    Version 33.0.2-8557947
                    Installed as C:\Users\USER\AppData\Local\Android\sdk\platform-tools\adb.exe
[  +12 ms] executing: C:\Users\USER\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[+13273 ms] Building APK
[  +92 ms] Running Gradle task 'assembleDebug'...
[ +751 ms] Using gradle from C:\Claudio\Code\myflutterapp\learningdart\android\gradlew.bat.
[+1325 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[+9876 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "11.0.12" 2021-07-20
           OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
           OpenJDK 64-Bit Server VM (build 11.0.12+7-b1504.28-7817840, mixed mode)
[   +4 ms] executing: [C:\Claudio\Code\myflutterapp\learningdart\android/] C:\Claudio\Code\myflutterapp\learningdart\android\gradlew.bat
-Pverbose=true -Ptarget-platform=android-x86 -Ptarget=C:\Claudio\Code\myflutterapp\learningdart\lib\main.dart
-Pbase-application-name=android.app.Application -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false
-Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+37641 ms] Welcome to Gradle 7.4!
[   +2 ms] Here are the highlights of this release:
[   +1 ms]  - Aggregated test and JaCoCo reports
[   +5 ms]  - Marking additional test source directories as tests in IntelliJ
[  +19 ms]  - Support for Adoptium JDKs in Java toolchains
[  +89 ms] For more details see https://docs.gradle.org/7.4/release-notes.html
[+9096 ms] Starting a Gradle Daemon, 2 busy Daemons could not be reused, use --status for details
[+164840 ms] > Task :app:preBuild UP-TO-DATE
[ +161 ms] > Task :app:preDebugBuild UP-TO-DATE
[ +372 ms] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[ +974 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[   +4 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[ +269 ms] > Task :app:compileDebugAidl NO-SOURCE
[ +101 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[   +2 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[+9302 ms] > Task :app:checkDebugAarMetadata UP-TO-DATE
[ +202 ms] > Task :app:cleanMergeDebugAssets
[   +2 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:compileDebugShaders NO-SOURCE
[ +233 ms] > Task :app:generateDebugAssets UP-TO-DATE
[ +338 ms] > Task :app:mergeDebugAssets
[+13090 ms] > Task :app:copyFlutterAssetsDebug
[   +2 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +4 ms] > Task :app:generateDebugResources UP-TO-DATE
[+1118 ms] > Task :app:mergeDebugResources UP-TO-DATE
[   +6 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[   +3 ms] > Task :app:extractDeepLinksDebug UP-TO-DATE
[ +467 ms] > Task :app:processDebugMainManifest UP-TO-DATE
[   +1 ms] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[+1024 ms] > Task :app:processDebugResources UP-TO-DATE
[+10036 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[ +285 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[  +14 ms] > Task :app:compileDebugJavaWithJavac FAILED
[ +521 ms] FAILURE: Build failed with an exception.
[ +395 ms] * What went wrong:
[  +56 ms] Execution failed for task ':app:compileDebugJavaWithJavac'.
[   +5 ms] > Could not create service of type UserHomeScopedCompileCaches using UserHomeScopeServices.createCompileCaches().
[   +2 ms]    > Unexpected lock protocol found in lock file. Expected 3, found 0.
[   +1 ms] * Try:
[   +1 ms] > Run with --stacktrace option to get the stack trace.
[   +1 ms] > Run with --info or --debug option to get more log output.
[   +1 ms] > Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 3m 56s
[   +1 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[   +1 ms] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.  
[   +2 ms] See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
[   +5 ms] 19 actionable tasks: 4 executed, 15 up-to-date
[ +988 ms] Running Gradle task 'assembleDebug'... (completed in 263.4s)
[   +7 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +5 ms] "flutter run" took 289,477ms.
[  +78 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:699:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +369 ms] ensureAnalyticsSent: 283ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1
```
As you can see it fails when it tries to run ':app:compileDebugJavaWithJavac'

Any solutions

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the Gradle Build Tool project.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/docs/setup/contribute/report-bugs#filing-a-bug

***

This is Flutter related, you might have a better chance for a resolution by talking to their community directly.
