### ISSUE TITLE
Gradle is trying to use a JDK that has been uninstalled from my system

### ISSUE THREAD

**Issue by blackears** [gradle/gradle#21170]
### Expected Behavior
Gradle should be able to handle uninstalling one JDK and installing another.

### Current Behavior
Gradle refused to use the JDK pointed to by JAVA_HOME and instead kept trying to use the old no  longer installed version of the JDK.

### Context
Unable to run Gradle.  Keep getting the error message 
```
D:\dev\starling2\game\2022\androidExportTest\android\build>"C:\Program Files\Eclipse Adoptium\jdk-11.0.15.10-hotspot/bin/java.exe" "-Xmx64m" "-Xms64m"   "-Dorg.gradle.appname=gradlew" -classpath "D:\dev\starling2\game\2022\androidExportTest\android\build\\gradle\wrapper\gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain --stacktrace  --info
Initialized native services in: C:\Users\kitfox\.gradle\native
Initialized jansi services in: C:\Users\kitfox\.gradle\native

FAILURE: Build failed with an exception.

* What went wrong:
The supplied javaHome seems to be invalid. I cannot find the java executable. Tried location: C:\Program Files\Java\jdk1.8.0_151\bin\java.exe

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.internal.jvm.JavaHomeException: The supplied javaHome seems to be invalid. I cannot find the java executable. Tried location: C:\Program Files\Java\jdk1.8.0_151\bin\java.exe
        at org.gradle.internal.jvm.Jvm.findExecutable(Jvm.java:183)
        at org.gradle.internal.jvm.Jvm.getJavaExecutable(Jvm.java:208)
        at org.gradle.internal.jvm.Jvm.forHome(Jvm.java:119)
        at org.gradle.launcher.daemon.context.DaemonCompatibilitySpec.javaHomeMatches(DaemonCompatibilitySpec.java:64)
        at org.gradle.launcher.daemon.context.DaemonCompatibilitySpec.whyUnsatisfied(DaemonCompatibilitySpec.java:40)
        at org.gradle.launcher.daemon.context.DaemonCompatibilitySpec.isSatisfiedBy(DaemonCompatibilitySpec.java:35)
        at org.gradle.launcher.daemon.context.DaemonCompatibilitySpec.isSatisfiedBy(DaemonCompatibilitySpec.java:25)
        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.getCompatibleDaemons(DefaultDaemonConnector.java:192)
        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connectToIdleDaemon(DefaultDaemonConnector.java:157)
        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connect(DefaultDaemonConnector.java:125)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:144)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:98)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:57)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:210)
        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:275)
        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:247)
        at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:82)
        at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:30)
        at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:92)
        at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:38)
        at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:44)
        at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:240)
        at org.gradle.launcher.Main.doAction(Main.java:35)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)


* Get more help at https://help.gradle.org
```

### Steps to Reproduce 
This issue has been resolved and is discussed in the thread https://discuss.gradle.org/t/gradle-is-trying-to-use-a-jdk-that-has-been-uninstalled-from-my-system/43202/3.  However, someone suggested I make a bug report of it here.  I was able to resolve the issue by deleting the registry.bin file that Gradle demon creates.

### Your Environment
Windows 10

**Comment by eskatos** [comment]
Hi,

This looks like https://github.com/gradle/gradle/issues/16816 that was fixed in Gradle 7.0.1.
Can you confirm what version of Gradle you are using?

**Comment by blackears** [comment]
Looks like its version 4.5.1.  At least at the command line.  I think my IDEs might be using a different version.

**Comment by VladRassokhin** [comment]
I've checked latest gradle sources and code around `AvailableJavaHomes#discoverLocalInstallations` still checks intallations quite poorly. Just that java_home exist, it doesn't check whether it's a good instalation (at least `bin/java.exe`).

I've situation that I've leftover directory `C:\Tools\x64\jdk1.8.0_322` and registry key `HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Development Kit\1.8`
But in directory there's only one file `jre\lib\tzdb.dat.tzdata2021e` - left by tzdata update.  Obviously such `JvmInstallationMetadata` should be considered as `isValidInstallation==false`
