### ISSUE TITLE
Incremental Annotation Processing Issue when recompiling annotated source dependency

### ISSUE THREAD

**Issue by danysantiago** [gradle/gradle#21203]
Hi - It seems Gradle's incremental compilation is failing to reprocess the originating source of a generated class that needs to be recompiled.

Let me go through an example. First, we have our annotated source:
```
@Component
interface MyComponent {
  Lazy<Library> getLibrary();
}
```
Then we have an `ISOLATING` annotation processor that processes the annotation called `@Component` and generates the following:
```
final class DaggerMyComponent {
    private DaggerMyComponent() {
    }

    public static DaggerMyComponent.Builder builder() {
        return new DaggerMyComponent.Builder();
    }

    public static MyComponent create() {
        return (new DaggerMyComponent.Builder()).build();
    }

    private static final class MyComponentImpl implements MyComponent {
        private final DaggerMyComponent.MyComponentImpl myComponentImpl = this;
        private Provider<Library> libraryProvider;

        private MyComponentImpl() {
            this.initialize();
        }

        private void initialize() {
            this.libraryProvider = new DaggerMyComponent.MyComponentImpl.SwitchingProvider(this.myComponentImpl, 0);
        }

        public Lazy<Library> getLibrary() {
            return DoubleCheck.lazy(this.libraryProvider);
        }

        private static final class SwitchingProvider<T> implements Provider<T> {
            private final DaggerMyComponent.MyComponentImpl myComponentImpl;
            private final int id;

            SwitchingProvider(DaggerMyComponent.MyComponentImpl myComponentImpl, int id) {
                this.myComponentImpl = myComponentImpl;
                this.id = id;
            }

            public T get() {
                switch(this.id) {
                case 0:
                    return new Library();
                default:
                    throw new AssertionError(this.id);
                }
            }
        }
    }

    static final class Builder {
        private Builder() {
        }

        public MyComponent build() {
            return new DaggerMyComponent.MyComponentImpl();
        }
    }
}
```
The originating element of `DaggerMyComponent.java` is `MyComponent`. Now, if I make ABI incompatible changes to `Library`, then Gradle for some reason does not recompile `MyComponent` and instead it seems to consider `DaggerMyComponent.class` and `DaggerMyComponent.java` stale and deletes them without invoking the processor which leads to `DaggerMyComponent.java` not being regenerated and ultimately to a `ClassNotFoundException` because no class is compiled for the missing generated source.

This exact behaviour can be reproduced with the following project: https://github.com/danysantiago/DaggerGradleIncrementalIssue

To reproduce:
1. Do a full build and run: `./gradlew clean run`
2. Change the [method](https://github.com/danysantiago/DaggerGradleIncrementalIssue/blob/main/library/src/main/java/Library.java#L12) in `Library.java` from `something1()` to `something2()` (or anything else different).
3. Do an incremental build and run `./gradlew run`

You should see the project fail with:
```
> Task :run FAILED
Exception in thread "main" java.lang.NoClassDefFoundError: DaggerMyComponent$MyComponentImpl$SwitchingProvider
        at DaggerMyComponent$MyComponentImpl.initialize(DaggerMyComponent.java:50)
        at DaggerMyComponent$MyComponentImpl.<init>(DaggerMyComponent.java:44)
        at DaggerMyComponent$Builder.build(DaggerMyComponent.java:33)
        at DaggerMyComponent.create(DaggerMyComponent.java:25)
        at Maincito.main(Maincito.java:3)
Caused by: java.lang.ClassNotFoundException: DaggerMyComponent$MyComponentImpl$SwitchingProvider
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
```

The project is using:

- Gradle 7.4.2
- Java 11
- [Dagger](https://github.com/google/dagger) 2.42

Let me know if you need more information!

**Comment by danysantiago** [comment]
## Further debugging information

I was able to attach a debugger in [ClassSetAnalysis](https://github.com/gradle/gradle/blob/master/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java) and specifically in the `getTypesToReprocess()` method, and what I am observing is as follow:

- Gradle was able to identify it needs to recompile `DaggerMyComponent$MyComponentImpl$SwitchingProvider`
- Gradle knows that the originating type of `DaggerMyComponent` is `MyComponent`, this is available in `annotationProcessingData.getGeneratedTypesByOrigin()`
- Gradle knows that from `DaggerMyComponent.java` 4 classes were generated: `[DaggerMyComponent, DaggerMyComponent$Builder, DaggerMyComponent$MyComponentImpl, DaggerMyComponent$MyComponentImpl$SwitchingProvider]`, this information is available in `compilerApiData.getSourceToClassMapping()`

However, when finding types to reprocess by [matching classes to recompile with the generated type to origin mapping](https://github.com/gradle/gradle/blob/master/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java#L164-L168) it seems as if there is a missing intermediate step of first mapping the inner class to the top level class, i.e. `DaggerMyComponent$MyComponentImpl$SwitchingProvider` -> `DaggerMyComponent`.

But besides that, one big question I have is: **why is `MyComponent` not being considered for recompilation since it has a direct reference to `Library` (albeit in a type argument).**

Alternatively, I was expecting that `compiledClasses` would contain the class hierarchy from the inner class to the top-level class, since those too need to recompile. It seems that is later determined and the files become stale (and deleted) in the [`AbstractRecompilationSpecProvider`](https://github.com/gradle/gradle/blob/master/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java#L87-L94). 

If you take a deep look at the generated source `build/generated/sources/annotationProcessor/java/main/DaggerMyComponent.java` there should be a reference path from `DaggerMyComponent` to the `DaggerMyComponent.MyComponentImpl.SwithingProvider` and to `Library`. If I am understanding things well I think I can observe this when looking at the `ClassSetAnalysisData` of the previous compilation and noticing `DaggerMyComponent$MyComponentImpl$SwitchingProvider` has as `privateDependantClasses` both `DaggerMyComponent` and `DaggerMyComponent$MyComponentImpl`, while `Library` has `DaggerMyComponent$MyComponentImpl$SwitchingProvider` as a `privateDependantClasses`. So when asked to ['find dependents of `Library`'](https://github.com/gradle/gradle/blob/master/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/PreviousCompilation.java#L41) I think `DaggerMyComponent` should be in the result, but it is not due to [transitive dependents finding stopping short when encountering private dependents, only continuing with public ones](https://github.com/gradle/gradle/blob/master/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java#L131).

Anyway, I hope this is somehow useful, thanks!

**Comment by danysantiago** [comment]
A bit more info... I know I should leave it to the experts, but I just keep getting curious.

I think the answer to my earlier question: 

> ... why is MyComponent not being considered for recompilation since it has a direct reference to Library (albeit in a type argument).

Is because [Gradle uses the descriptors in the class analysis](https://github.com/gradle/gradle/blob/d587d9a43b99491b540c43db4153dbf78d96683b/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/asm/ClassDependenciesVisitor.java#L173-L174) and thus `Library` is not added as a dependency of `MyComponent`, since the descriptor for the method is `()Ldagger/Lazy;` (notice the erasure), where as the signature is `()Ldagger/Lazy<LLibrary;>;` (it has one because there are generics).

My question above is now transformed to: **Should types declared as type arguments be considered dependencies?**

**Comment by asodja** [comment]
Thanks for the analysis. Yes, it looks like you pinpointed the bug nicely. We should read the signature, not just the descriptor. We fixed a bunch of [similar cases for 7.6](https://github.com/gradle/gradle/pull/20499), but I see we missed this one.  

> Should types declared as type arguments be considered dependencies?


Yes, they should be. One example that comes to my mind is, that when some type is deleted, we should recompile all classes that have that type as a dependency so compilation can fail in case the user doesn't fix all usages.

**Comment by danysantiago** [comment]
Thanks for the update! FWIW, I do agree type arguments should be considered dependencies, thanks for confirming that.

As for Dagger, you can find the code that generates `MyComponentImpl` here: https://github.com/google/dagger/tree/master/java/dagger/internal/codegen. Is there something specifically you are looking with regards to how parameters are read?

In essence Dagger reads from `MyComponent` the getter `Lazy<Library> getLibrary()`, it reads the return type and it records that `Library` is a dependency that needs to be provided and it knows how to build one because the empty constructor of `Library` is annotated with `@Inject`. The type `Lazy` is just a wrapper, and the code generated is a bit funky because it is full of optimizations and the `new` instance statement ends up in that `SwitchingProvider` (and optimization for class loading).

**Comment by donat** [comment]
@asodja Do you have time to look into this for Gradle 7.6?

**Comment by asodja** [comment]
@donat Yes, I can take a look.

@danysantiago I was wondering if I could create some simple annotation processor with similar logic to use it as a reproducer for the integration test. Although the issue is actually not directly related to ann. processors, but still.
