### ISSUE TITLE
Gradle wrapper 7.5 does no longer accept proxy config via command line parameters

### ISSUE THREAD

**Issue by JotBePunkt** [gradle/gradle#21341]
We have a build server behind the corporate proxy. Within the build scripts we provide the proxy parametes via command line parameters `-Dhttps.proxy=...`. Now after we switched to gradle 7.5 it behaves as no proxy was configured at all. In contrast our developers have the proxy configured in `~/.gradle/gradle.properties` which works fine.

### Expected Behavior
When I call gradle wrapper the following way, the proxy is used to download grade (and its dependencies)
```
./gradlew build -Dhttps.proxyHost=172.17.0.1  -Dhttps.proxyPort=3128
```
gradle should be downloaded and the build the project

### Current Behavior
The following error occurs (typical same issue when no proxy is configured)
```
Downloading https://services.gradle.org/distributions/gradle-7.5-bin.zip
Error: Exception in thread "main" java.net.UnknownHostException: services.gradle.org

	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:305)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:508)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:207)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:100)
	at org.gradle.wrapper.Download.download(Download.java:80)
	at org.gradle.wrapper.Install$1.call(Install.java:82)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:62)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Error: Process completed with exit code 1.
```

### Context

- With the upgrade from 7.4 to 7.5 the error was introduced. 
- Providing the proxy settings in the gradle.properties, it works fine

### Steps to Reproduce 

(see above)
Run the following command on the machine, that has no direct internet connection (proxy required) and an empty `gradle.properties`
```
./gradlew build -Dhttps.proxyHost=172.17.0.1  -Dhttps.proxyPort=3128
```

**Comment by big-guy** [comment]
Hi @JotBePunkt 

I'm reproducing something like what you're seeing, but I'm unsure.

If I run (the `-g gradle-user-home` is just to ensure there's no other configuration):
`./gradlew -g gradle-user-home help -Dhttps.proxyHost=127.0.0.1`

I see that the proxy settings appear to be ignored; however, if I move the `help` to after the system properties:
`./gradlew -g gradle-user-home -Dhttps.proxyHost=127.0.0.1 help`

I see that it does try to use the proxy. Do you see the same thing if you move the `build` to the end?

I agree that this seems broken.

**Comment by JotBePunkt** [comment]
I can confirm when I put the proxy config before the tasks, it works. When the proxy config is after the tasks, the built fails:

does not work:
```
./gradlew build -Dhttps.proxyHost=172.17.0.1  -Dhttps.proxyPort=3128
```

does work:
```
./gradlew -Dhttps.proxyHost=172.17.0.1  -Dhttps.proxyPort=3128 build
```

**Comment by big-guy** [comment]
OK, I see the same behavior back to Gradle 5.0, so I don't think this is something new.

**Comment by ov7a** [comment]
This issue is still reproducible with 8.2
