### ISSUE TITLE
Cannot extract contents of Renjin 3.5 beta76 archive

### ISSUE THREAD

**Issue by DaveJarvis** [gradle/gradle#21465]
# Environment

```
$ gradle --version

------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          18.0.2 (BellSoft 18.0.2+10)
OS:           Linux 5.18.10-arch1-1 amd64

$ java -version
openjdk version "18.0.2" 2022-07-19
OpenJDK Runtime Environment (build 18.0.2+10)
OpenJDK 64-Bit Server VM (build 18.0.2+10, mixed mode, sharing)
```

# Replicate

``` bash
mkdir -p $HOME/dev/fail
cd $HOME/dev/fail
cat << EOF > build.gradle
plugins { id 'java' }

repositories {
  mavenCentral()
  maven { url "https://nexus.bedatadriven.com/content/groups/public" }
}

dependencies { implementation 'org.renjin:renjin-script-engine:3.5-beta76' }

jar {
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE

  from {
    (configurations.runtimeClasspath.findAll { !it.path.endsWith(".pom") })
    .collect {
      it.isDirectory() ? it : zipTree(it)
    }
  }
}
EOF
gradle jar
```

# Expected

No error.

# Actual

```
Configuration on demand is an incubating feature.
> Task :jar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jar'.
> Could not expand ZIP '/home/username/.gradle/caches/modules-2/files-2.1/org.renjin/renjin-core/3.5-beta76/52ccd406ab3306df0d37929939d1e28b457057c7/renjin-core-3.5-beta76.jar'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
```

# Regression

Is this a regression? The same `gradle.build` file works with Gradle 7.3.

Both `jar` and `zip` commands can open the file successfully.

``` bash
$ zip --test /home/username/.gradle/caches/modules-2/files-2.1/org.renjin/renjin-core/3.5-beta76/52ccd406ab3306df0d37929939d1e28b457057c7/renjin-core-3.5-beta76.jar 
test of /home/username/.gradle/caches/modules-2/files-2.1/org.renjin/renjin-core/3.5-beta76/52ccd406ab3306df0d37929939d1e28b457057c7/renjin-core-3.5-beta76.jar OK
$ jar -tvf /home/username/.gradle/caches/modules-2/files-2.1/org.renjin/renjin-core/3.5-beta76/52ccd406ab3306df0d37929939d1e28b457057c7/renjin-core-3.5-beta76.jar | wc -l
2253
```

# Stacktrace

```
Caused by: org.gradle.api.GradleException: Could not expand ZIP '/home/username/.gradle/caches/modules-2/files-2.1/org.renjin/renjin-core/3.5-beta76/52ccd406ab3306df0d37929939d1e28b457057c7/renjin-core-3.5-beta76.jar'.
        at org.gradle.api.internal.file.archive.ZipFileTree.visit(ZipFileTree.java:108)
        at org.gradle.api.internal.file.collections.FilteredMinimalFileTree.visit(FilteredMinimalFileTree.java:89)
        at org.gradle.api.internal.file.collections.FileTreeAdapter.visit(FileTreeAdapter.java:96)
```

**Comment by jbartok** [comment]
Confirmed that it works in Gradle `7.3.3`, fails in more recent versions.

Root cause:
```
Caused by: java.lang.IllegalArgumentException: 'org/renjin/base/..getNamespace.RData' is not a safe zip entry name.
        at org.gradle.util.internal.ZipSlip.safeZipEntryName(ZipSlip.java:37)
        at org.gradle.api.internal.file.archive.ZipFileTree$DetailsImpl.safeEntryName(ZipFileTree.java:172)
        at org.gradle.api.internal.file.archive.ZipFileTree$DetailsImpl.getRelativePath(ZipFileTree.java:201)
        at org.gradle.api.tasks.util.internal.CachingPatternSpecFactory$CachingSpec.isSatisfiedBy(CachingPatternSpecFactory.java:72)
        at org.gradle.api.tasks.util.internal.CachingPatternSpecFactory$CachingSpec.isSatisfiedBy(CachingPatternSpecFactory.java:61)
        at org.gradle.api.specs.NotSpec.isSatisfiedBy(NotSpec.java:36)
        at org.gradle.api.internal.file.collections.FilteredMinimalFileTree$2.visitFile(FilteredMinimalFileTree.java:99)
        at org.gradle.api.internal.file.archive.ZipFileTree.visit(ZipFileTree.java:104)
        ... 136 more
```

**Comment by jbartok** [comment]
Seems like our ZipSlip check is incorrect, because `..` in this case is just a part of the name (bad idea, but valid).

**Comment by DaveJarvis** [comment]
In particular:

https://github.com/gradle/gradle/pull/19592/commits/38c00e48bbad598910d6b3cb50d68b406d5f1432#diff-99b7c47adc4fd245b2e9c50847bd7660785d5e9342202cddc7740d974ccb3328R45

https://github.com/gradle/gradle/pull/19592/commits/38c00e48bbad598910d6b3cb50d68b406d5f1432#diff-0987d9713a5f12119c6b9df6f367319f3aeb5a0c4863a8e1c998b357b6cf80dbR44

https://github.com/gradle/gradle/pull/19592/commits/38c00e48bbad598910d6b3cb50d68b406d5f1432#diff-0987d9713a5f12119c6b9df6f367319f3aeb5a0c4863a8e1c998b357b6cf80dbR45
