### ISSUE TITLE
Groovy compilation is missing transitive implementation dependencies

### ISSUE THREAD

**Issue by yawkat** [gradle/gradle#21539]
### Expected Behavior

On the groovy compile classpath, transitive implementation dependencies of a direct dependency should be present.

### Current Behavior

Transitive implementation dependencies are missing. This leads to a compilation error if the direct dependency has a groovy ASTTransformer that requires the transitive dependency.

### Context

In micronaut, we have an annotation processor module `io.micronaut:micronaut-http-validation` that requires a dependency `io.micronaut:micronaut-http-server` to function. This works fine with java projects, where we include it as an `annotationProcessor` dependency, but groovy projects where we declare the processor as `compileOnly` fail.

I have made a reproducer project that does not require micronaut or any special plugins, see below.

### Steps to Reproduce 

```
git clone git@github.com:yawkat/reproducer-gradle-groovy-transitive.git
cd reproducer-gradle-groovy-transitive
./gradlew :main:run
```

This leads to the following error (with `--stacktrace`):

```
> Task :main:compileGroovy FAILED
Initializing MyTransformation

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':main:compileGroovy'.
> transitiveDep/MyLogger

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':main:compileGroovy'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:140)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:128)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:69)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:327)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:314)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:307)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:293)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:420)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:342)
        at org.gradle.execution.plan.DefaultPlanExecutor.process(DefaultPlanExecutor.java:96)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.executeWithServices(DefaultTaskExecutionGraph.java:140)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.execute(DefaultTaskExecutionGraph.java:125)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:39)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:51)
        at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:54)
        at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:43)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor.execute(BuildOperationFiringBuildWorkerExecutor.java:40)
        at org.gradle.internal.build.DefaultBuildLifecycleController.lambda$executeTasks$7(DefaultBuildLifecycleController.java:161)
        at org.gradle.internal.model.StateTransitionController.doTransition(StateTransitionController.java:247)
        at org.gradle.internal.model.StateTransitionController.lambda$tryTransition$7(StateTransitionController.java:174)
        at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
        at org.gradle.internal.model.StateTransitionController.tryTransition(StateTransitionController.java:174)
        at org.gradle.internal.build.DefaultBuildLifecycleController.executeTasks(DefaultBuildLifecycleController.java:161)
        at org.gradle.internal.build.DefaultBuildWorkGraphController$DefaultBuildWorkGraph.runWork(DefaultBuildWorkGraphController.java:156)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:249)
        at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:109)
        at org.gradle.composite.internal.DefaultBuildController.doRun(DefaultBuildController.java:164)
        at org.gradle.composite.internal.DefaultBuildController.access$000(DefaultBuildController.java:45)
        at org.gradle.composite.internal.DefaultBuildController$BuildOpRunnable.run(DefaultBuildController.java:183)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
Caused by: java.lang.NoClassDefFoundError: transitiveDep/MyLogger
        at compileDep.MyTransformation.visit(MyTransformation.groovy:21)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:270)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:64)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:97)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:76)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkAction.execute(AbstractDaemonCompiler.java:135)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
        at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:87)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:56)
        at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
        at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
Caused by: java.lang.ClassNotFoundException: transitiveDep.MyLogger
        ... 28 more
```

You can see in [the example project](https://github.com/yawkat/reproducer-gradle-groovy-transitive) three modules with a simple dependency graph:

`main --(compileOnly)-> compileDep --(implementation)-> transitiveDep`

It is `transitiveDep` that is missing during the compilation of `main`, leading to the CNFE.

My theory (without much knowledge of gradle internals) is that gradle incorrectly assumes that transitive implementation dependencies do not matter during compilation, since they should not be exposed as API by the direct dependency. However for groovy this assumption is incorrect, since with an ASTTransformer, code from the direct dependency can *run* during compilation, which can require the transitive dependencies.

To test this hypothesis, I tried changing the `compileDep -> transitiveDep` relation from `implementation` to `api` (this requires adding the `java-library` plugin). Gradle now thinks that transitiveDep may be exposed as API by compileDep, and thus includes it in the compilation classpath for `main`. And indeed this fixes the error. However this is not a good solution for multiple reasons:

- `api` dependency scope is only available with the `java-library` plugin, which should not be required for a pure groovy project
- it is semantically incorrect, since the transitiveDep is still only used internally by the compileDep, and so *should* be an implementation dependency
- it affects java usages of the `compileDep` module as well, where this workaround is not necessary
- it can get messy for deep dependency graphs, since you have to ensure the path to all deps is fully `api`.

### Your Environment

- Gradle 7.5.1
- `Linux yawkat-oracle 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Ubuntu 22.04.1 LTS

**Comment by ljacomet** [comment]
Thanks for your interest in Gradle and the bug report.

1. `java-library` should be applied to a `groovy` project that actually defines a Groovy library, to be consumed by other projects. The `java-library` name should have been `jvm-library` to indicate this better, but changing the name at this stage is not really an option. This is illustrated in [the Groovy library sample](https://docs.gradle.org/current/samples/sample_building_groovy_libraries.html#review_the_project_files) in the documentation. But this could be made more explicit in the `java-library` plugin documentation.
2. Gradle has rudimentary support for your use case, where you can [add specific dependencies](https://docs.gradle.org/current/userguide/groovy_plugin.html#sec:groovy_compilation_avoidance) on the consumer side to indicate they are needed by AST transform. You can use that as a workaround for now.

However that above example is limited, does not leverage variant aware dependency management, and should be handled on the producer side instead of the consumer.

The ideal setup would be as follows:
* Groovy library with AST transform requiring non API dependencies
  * Creation of a dedicated variant, and its related bucket configuration, to list those dependencies
  * The bucket configuration could be defined in a way that `implementation` extends it, in order to not have to declare twice the dependency.
  * The variant will need to have a definition that allows it to be selected in place of the regular compile variant
* Groovy projects would be enhanced _as consumers_ to automatically resolve these variants for their compile dependencies and add them to the `astTransformationClasspath` property of the `GroovyCompile` task.

From the user's perspective, it would be handled as follows:
```
plugins {
    // Regular plugins and then:
    id("gradle.groovy.ast-dependencies") version "1.0"
}

dependencies {
    // Automatically added to compilation and runtime classpath. Visible at runtime for consumption
    astTransformImplementation("some:library:1.0") 
}
```

... and that's it, because the rest can be inferred. Of course the hypothetical plugin would need to be applied to any consumer of a library leveraging it.

@britter @jjohannes Would a plugin providing such a feature be welcome to GradleX?

**Comment by yawkat** [comment]
@melix can you take over this issue (and https://github.com/micronaut-projects/micronaut-core/issues/7624 ) from me, now that you're back?

**Comment by britter** [comment]
@ljacomet we're open to accept new plugins to GradleX, but we're still bootstrapping the project so I think it's a little to early to accept new code. We'll definitely come back to you about this.

**Comment by melix** [comment]
So I took a look at this, and indeed the problem is how Gradle considers AST transformations. IMHO, the code snippet:

```


configurations { astTransformation }
dependencies {
    astTransformation(project(":ast-transformation"))
}
tasks.withType(GroovyCompile).configureEach {
    astTransformationClasspath.from(configurations.astTransformation)
}

```

Should be turned into a proper plugin, so that Micronaut _can_ declare the dependencies properly as `astTransformation` instead of `compileOnly` (which they are not). I don't think such a plugin's responsibility is in the community: that should, IMHO, be a feature of the `groovy` plugin, just like `annotationProcessor` is a configuration which comes with the java plugin.

I don't think having users declare an external plugin to be able to use a language feature is a reasonable thing to have.
