### ISSUE TITLE
StackOverflowError in FinalizerGroup.isCanCancel when handling build failure.

### ISSUE THREAD

**Issue by mlopatkin** [gradle/gradle#21542]
Run task `e` of the following build file:
```gradle
task a {
  dependsOn "b"
}

task b {
  finalizedBy a
}

task e {
  doLast {
	throw new RuntimeException("HaHa")
  }

  finalizedBy a
}
```

### Expected Behavior
Build fails because of the RuntimeException only.

### Current Behavior
Build fails with RuntimeException and StackOverflowError:
```
> Task :e FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/tmp/123/build.gradle' line: 11

* What went wrong:
Execution failed for task ':e'.
> HaHa

==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

==============================================================================

BUILD FAILED in 711ms
```

### Steps to Reproduce 
`./gradlew e`
### Your Environment

Build scan URL: https://scans.gradle.com/s/3f3f6q5p2grig

This build works as expected in Gradle 7.5 and 7.4.

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/21581

**Comment by PetrGlad** [comment]
I can also reproduce this in Gradle 7.5.1 - I think the problem is in [this change](https://github.com/gradle/gradle/pull/21384).
I see StackOverflowError after running `./gradlew test` with failed tests.

The stack trace is
```
java.lang.StackOverflowError
        at java.base/java.util.TreeMap$KeyIterator.<init>(TreeMap.java:1259)
        at java.base/java.util.TreeMap.keyIterator(TreeMap.java:1107)
        at java.base/java.util.TreeMap$KeySet.iterator(TreeMap.java:1120)
        at java.base/java.util.TreeSet.iterator(TreeSet.java:181)
        at org.gradle.execution.plan.FinalizerGroup.isCanCancel(FinalizerGroup.java:153)
        at org.gradle.execution.plan.CompositeNodeGroup.isCanCancel(CompositeNodeGroup.java:101)
        at org.gradle.execution.plan.Node.isCanCancel(Node.java:232)
        at org.gradle.execution.plan.FinalizerGroup.isCanCancel(FinalizerGroup.java:155)
        at org.gradle.execution.plan.CompositeNodeGroup.isCanCancel(CompositeNodeGroup.java:101)
        at org.gradle.execution.plan.Node.isCanCancel(Node.java:232)
        at org.gradle.execution.plan.FinalizerGroup.isCanCancel(FinalizerGroup.java:155)
        at org.gradle.execution.plan.CompositeNodeGroup.isCanCancel(CompositeNodeGroup.java:101)
        at org.gradle.execution.plan.Node.isCanCancel(Node.java:232)
        at org.gradle.execution.plan.FinalizerGroup.isCanCancel(FinalizerGroup.java:155)
        at org.gradle.execution.plan.CompositeNodeGroup.isCanCancel(CompositeNodeGroup.java:101)
        at org.gradle.execution.plan.Node.isCanCancel(Node.java:232)
        at org.gradle.execution.plan.FinalizerGroup.isCanCancel(FinalizerGroup.java:155)
        at org.gradle.execution.plan.CompositeNodeGroup.isCanCancel(CompositeNodeGroup.java:101)
        at org.gradle.execution.plan.Node.isCanCancel(Node.java:232)
        at org.gradle.execution.plan.FinalizerGroup.isCanCancel(FinalizerGroup.java:155)
  . . . . .
```
