### ISSUE TITLE
wrapper task not found when referenced from a plugin applied from a precompiled script plugin

### ISSUE THREAD

**Issue by hakanai** [gradle/gradle#21686]
### Expected Behavior

If I have a precompiled script plugin like this:

```kotlin
plugins {
    id("com.github.rmee.jdk-bootstrap")
}

// Other config would follow
```

It should be possible to generate the precompiled script plugin accessors for this plugin.

### Current Behavior

The build succeeds, **but** the `:generatePrecompiledScriptPluginAccessors` task fails with:

```
org.gradle.internal.exceptions.LocationAwareException: Precompiled script plugin 'path\to\jdk-bootstrap-wrapper-issue\src\main\kotlin\convention.jdk-bootstrap.gradle.kts' line: 1
An exception occurred applying plugin request [id: 'com.github.rmee.jdk-bootstrap']
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:208)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:147)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.access$200(DefaultPluginRequestApplicator.java:61)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$1$1.lambda$add$1(DefaultPluginRequestApplicator.java:120)
	....
Caused by: org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'com.github.rmee.jdk-bootstrap']
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.exceptionOccurred(DefaultPluginRequestApplicator.java:223)
Caused by: org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'com.github.rmee.jdk-bootstrap']

	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:205)
	... 165 more
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin 'com.github.rmee.jdk-bootstrap'.
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin 'com.github.rmee.jdk-bootstrap'.

	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:173)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:137)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.lambda$applyPlugin$1(DefaultPluginRequestApplicator.java:149)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:201)
	... 165 more
Caused by: org.gradle.api.UnknownTaskException: Task with name 'wrapper' not found in project ':generatePrecompiledScriptPluginAccessors:accessors3244999083211933265'.
Caused by: org.gradle.api.UnknownTaskException: Task with name 'wrapper' not found in project ':generatePrecompiledScriptPluginAccessors:accessors3244999083211933265'.

	at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:102)
	at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:46)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:333)
	at org.gradle.api.internal.tasks.DefaultTaskCollection.getByName(DefaultTaskCollection.java:46)
	at com.github.rmee.jdk.bootstrap.JdkBootstrapPlugin.apply(JdkBootstrapPlugin.java:13)
	...
```

### Context
When applying some external plugin where we disagree with their defaults, we like to make our own plugin which pulls in their plugin and then corrects the defaults, so that we can just pull ours in instead. Writing them as precompiled script plugins is currently the lowest line count way to do so.

### Steps to Reproduce 

* [Minimal repro repo](https://github.com/hakanai/jdk-bootstrap-wrapper-issue)
* Run the `build` task and watch for the output of the `:generatePrecompiledScriptPluginAccessors` task.

### Workaround

Apply `wrapper` explicitly first, i.e.:
```kotlin
plugins {
    wrapper
    id("com.github.rmee.jdk-bootstrap")
}
```

### Your Environment
* Gradle versions tried: 6.8, 7.5.1
* Happens across multiple OS

**Comment by reinsch82** [comment]
Sorry for the late reply.

This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***

Since the `wrapper` task is only available on the root project and the applied plugin attempts to use it, the setup is valid only on the root project. In the context of a precompiled script plugin this is not guaranteed. So having to explicitly declare the need of the wrapper plugin seems to be the right generalization.
