### ISSUE TITLE
Signing plugin: sign(publications) should be idempotent

### ISSUE THREAD

**Issue by gabrielittner** [gradle/gradle#21857]
### Expected Behavior

Calling `sign(publications)` ([docs](https://docs.gradle.org/current/javadoc/org/gradle/plugins/signing/SigningExtension.html#sign-org.gradle.api.publish.Publication...-)) multiple times should work

### Current Behavior

Calling it a second time will throw an exception because the signing task already exists:
```
* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'dexcount-gradle-plugin'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:84)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:77)
	...
Caused by: org.gradle.api.internal.tasks.DefaultTaskContainer$DuplicateTaskException: Cannot add task 'signDexcountPluginMarkerMavenPublication' as a task with that name already exists.
	at org.gradle.api.internal.tasks.DefaultTaskContainer.failOnDuplicateTask(DefaultTaskContainer.java:257)
	...
	at org.gradle.plugins.signing.SigningExtension.sign(SigningExtension.java:395)
	at com.vanniktech.maven.publish.MavenPublishBaseExtension.signAllPublications(MavenPublishBaseExtension.kt:114)
	at com.vanniktech.maven.publish.MavenPublishPlugin.apply$lambda-0(MavenPublishPlugin.kt:65)
        ...
```

### Context

Multiple plugins follow the convention over configuration approach and automatically apply the signing plugin. One of these is the official `com.gradle.plugin-publish` which internally will check if the task already exists before calling `sign` for a `publication`. This is what the code looks like
```
private void wireInSigningTask(Project project, SigningExtension signing, Publication publication) {
    String signTaskName = determineSignTaskNameForPublication(publication);
    Task signTask = project.getTasks().findByName(signTaskName);
    if (signTask == null) {
        signTask = signing.sign(publication).get(0);
    }
    dependsOn(signTask);
}
```

Currently other plugins would need to apply the same logic to check if the task already exists and only call `sign` conditionally. This has 2 issues however:
- `tasks.findByName` does not have a lazy version so the siging task would get created/configured
- `determineSignTaskNameForPublication` relies on the implementation of the signing plugin, in fact that method inside `PublishTask` of the plugin publish plugin looks like it is a direct copy of the method with the same name inside `SigningExtension`

I don't think it should be the goal to have this logic duplicated everywhere and the best way to solve it would be to make `sign` idempotent.

### Steps to Reproduce 

1. apply `com.gradle.plugin-publish` 1.0.0
2. apply `com.vanniktech.maven.publish` 0.21.0

(order needs to be kept 

### Your Environment

Can provide a build scan if needed.

**Comment by jbartok** [comment]
Yes, would make sense to make signing idempotent.
