### ISSUE TITLE
CommandLineToolVersionLocator fails with an NPE on (broken visual studio) in Windows

### ISSUE THREAD

**Issue by dweiss** [gradle/gradle#21993]
This has been reported to Apache Lucene mailing list - a stack trace like this one when firing up gradle on Windows:
```
Caused by: java.lang.NullPointerException
        at org.gradle.nativeplatform.toolchain.internal.msvcpp.version.CommandLineToolVersionLocator.parseJson(CommandLineToolVersionLocator.java:94)
        at org.gradle.nativeplatform.toolchain.internal.msvcpp.version.CommandLineToolVersionLocator.locateInstalls(CommandLineToolVersionLocator.java:60)
```

If you look at that stack trace (the bug is still present on master), gradle clearly just happily logs a missing output from vswhere and returns null:

https://github.com/gradle/gradle/blob/v7.3.3/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/msvcpp/version/CommandLineToolVersionLocator.java#L86-L89

which then propagates up as NPE in parseJson:

https://github.com/gradle/gradle/blob/v7.3.3/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/msvcpp/version/CommandLineToolVersionLocator.java#L59-L60

The returned null value should be guarded with an if in locateInstalls and ignored:

https://github.com/gradle/gradle/blob/v7.3.3/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/msvcpp/version/CommandLineToolVersionLocator.java#L59-L60

**Comment by lkasso** [comment]
Apologies for the late reply.

---

The issue is in the backlog of the relevant team and is prioritized by them.

***

Thank you for the investigation. The reference code hasn't been changed, so the problem still exists.
