### ISSUE TITLE
Provider.zip combiner function cannot return null

### ISSUE THREAD

**Issue by zml2008** [gradle/gradle#22075]
### Expected Behavior
The combiner function in `Property#zip(a, b, combiner)` returning null should result in the zipped property having a missing value. This matches the behavior from ProviderFactory#provider and Provider#map.

### Current Behavior
Returning `null` from the combiner function throws an `IllegalArgumentException`:

```
Caused by: java.lang.IllegalArgumentException
    at org.gradle.api.internal.provider.ValueSupplier$Value.of(ValueSupplier.java:215)
    at org.gradle.api.internal.provider.BiProvider.calculateOwnValue(BiProvider.java:56)
    at org.gradle.api.internal.provider.AbstractMinimalProvider.calculatePresence(AbstractMinimalProvider.java:79)
    at org.gradle.api.internal.provider.MappingProvider.calculatePresence(MappingProvider.java:50)
    at org.gradle.api.internal.provider.AbstractProperty.calculatePresence(AbstractProperty.java:58)
```

### Context

I currently have a plugin configuring the CompileJava task like so:

```java
options.getRelease().set(bytecodeVersion.zip(toolchainVersion, (bytecode, toolchain) -> {
        if (toolchain >= 9) {
          return bytecode;
        } else {
          return null;
        }
      }));
```
which fails while returning null and have used this as a temporary workaround (even if octy golfed something a bit nicer :p):

```java
      final Provider<Integer> releaseFlagToolchain = toolchainVersion.map(v -> {
        if (v > 9) {
          return v;
        } else {
          return null;
        }
      });

      options.getRelease().set(bytecodeVersion.zip(releaseFlagToolchain, (bytecode, toolchain) -> bytecode));
```

**Comment by Vampire** [comment]
This issue misses the 7.6 milestone
