### ISSUE TITLE
Linking external Javadocs fails with Gradle 4.0 (was working with 3.5)

### ISSUE THREAD

**Issue by ddimtirov** [gradle/gradle#2235]
### Expected Behavior
Build should pass, Javadoc should be generated with external links pointing to docs published on Internet 

### Current Behavior
Javadoc generation fails

### Context
No big deal for this project. Blocking upgrade to 4.0 for others.

### Steps to Reproduce (for bugs)
Checkout https://github.com/ddimtirov/nuggets/ and run `gradle javadoc` with Gradle 4.0

### Your Environment
 * https://scans.gradle.com/s/zy46rwxid2364
 * https://github.com/ddimtirov/nuggets/blob/master/gradle/javadoc.gradle#L21 
 * Wondows 10, Java 1.8.0_112

**Comment by bmuschko** [comment]
The project uses the method `javadoc.options.linksOffline` to set multiple offline links:

```
javadoc {
    options.with {
        linksOffline 'https://docs.oracle.com/javase/8/docs/api/', 'gradle/javadocs/jdk'
        linksOffline 'http://javadox.com/org.jetbrains/annotations/15.0/', 'gradle/javadocs/jetbrains-annotations'
    }
}
```

The build fails with the following error message if more than one offline link was declared:

```
> Task :javadoc
javadoc: error - Illegal package name: "http://javadox.com/org.jetbrains/annotations/15.0/' 'gradle/javadocs/jetbrains-annotations"
1 error
```

This is the stack trace:

```
Caused by: org.gradle.api.GradleException: Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/Users/bmuschko/dev/projects/gradle-playground/nuggets/build/tmp/javadoc/javadoc.options'
        at org.gradle.api.tasks.javadoc.internal.JavadocGenerator.execute(JavadocGenerator.java:58)
        at org.gradle.api.tasks.javadoc.internal.JavadocGenerator.execute(JavadocGenerator.java:31)
        at org.gradle.api.tasks.javadoc.Javadoc.executeExternalJavadoc(Javadoc.java:156)
        at org.gradle.api.tasks.javadoc.Javadoc.generate(Javadoc.java:144)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:711)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:694)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:303)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:295)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:177)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 27 more
Caused by: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/javadoc'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:370)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:31)
        at org.gradle.api.tasks.javadoc.internal.JavadocGenerator.execute(JavadocGenerator.java:53)
        ... 43 more
```

**Comment by ddimtirov** [comment]
Btw the generated options file was missing when I checked.

**Comment by eriwen** [comment]
Very nice issue writing @ddimtirov ⭐️  👍
