### ISSUE TITLE
Can't use `kotlin-dsl` inside a precompiled script plugin that is applied to other precompiled script plugins

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#22428]
Consider this setup: 

<img width="459" alt="image" src="https://user-images.githubusercontent.com/1195562/195957947-3664c68b-f4ba-47c5-a484-9b54d04cd442.png">

`repro/settings.gradle.kts`
```kotlin
pluginManagement.includeBuild("build-logic")
```

`repro/build.gradle.kts` 
```
plugins {
    id("apply-java")
}
```

`repro/build-logic/settings.gradle.kts`
```kotlin
rootProject.name = "my-repro-project-build-logic"

pluginManagement.includeBuild("meta")
dependencyResolutionManagement.repositories.gradlePluginPortal()
```

`repro/build-logic/build.gradle.kts`
```kotlin
plugins {
    id("my.kotlin-dsl")
}
```

`repro/build-logic/src/main/kotlin/apply-java.gradle.kts`
```kotlin
plugins {
    `java-library`
}
```

`repro/build-logic/meta/settings.gradle.kts`
```kotlin
rootProject.name = "my-repro-project-build-logic-meta"

dependencyResolutionManagement.repositories.gradlePluginPortal()
```

`repro/build-logic/meta/build.gradle.kts`
```kotlin
import org.gradle.kotlin.dsl.support.expectedKotlinDslPluginsVersion

plugins {
    `kotlin-dsl`
}

dependencies {
    implementation("org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:$expectedKotlinDslPluginsVersion")
}
```

`repro/build-logic/meta/src/main/kotlin/my.kotlin-dsl.gradle.kts`
```
plugins {
    `kotlin-dsl`
}
```

Do `gradle build` with gradle 7.5.1

### Expected Behavior

It "just works", build succeeds. 
```
BUILD SUCCESSFUL in 6s
21 actionable tasks: 21 executed
```

### Current Behavior

It says "Please remove the version from the offending request"
but as you can see there is not a version in any of the `plugins {}` blocks

This fails with this error:

```
> Task :meta:generatePrecompiledScriptPluginAccessors FAILED

FAILURE: Build failed with an exception.

* Where:
repro/build-logic/meta/src/main/kotlin/my.kotlin-dsl.gradle.kts line: 1

* What went wrong:
Invalid plugin request [id: 'org.gradle.kotlin.kotlin-dsl', version: '2.3.3']. Plugin requests from precompiled scripts must not include a version number. Please remove the version from the offending request and make sure the module containing the requested plugin 'org.gradle.kotlin.kotlin-dsl' is an implementation dependency of project ':meta'.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
java.lang.IllegalArgumentException: Invalid plugin request [id: 'org.gradle.kotlin.kotlin-dsl', version: '2.3.3']. Plugin requests from precompiled scripts must not include a version number. Please remove the version from the offending request and make sure the module containing the requested plugin 'org.gradle.kotlin.kotlin-dsl' is an implementation dependency of project ':meta'.
        at org.gradle.kotlin.dsl.provider.plugins.precompiled.tasks.GeneratePrecompiledScriptPluginAccessors.validatePluginRequestsOf(GeneratePrecompiledScriptPluginAccessors.kt:239)
        at org.gradle.kotlin.dsl.provider.plugins.precompiled.tasks.GeneratePrecompiledScriptPluginAccessors.scriptPluginPluginsFor(GeneratePrecompiledScriptPluginAccessors.kt:227)
        at org.gradle.kotlin.dsl.provider.plugins.precompiled.tasks.GeneratePrecompiledScriptPluginAccessors.access$scriptPluginPluginsFor(GeneratePrecompiledScriptPluginAccessors.kt:79)
        at org.gradle.kotlin.dsl.provider.plugins.precompiled.tasks.GeneratePrecompiledScriptPluginAccessors$scriptPluginPluginsFor$1.invokeSuspend(GeneratePrecompiledScriptPluginAccessors.kt:208)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:140)
        at org.gradle.kotlin.dsl.provider.plugins.precompiled.tasks.GeneratePrecompiledScriptPluginAccessors.resolvePluginGraphOf(GeneratePrecompiledScriptPluginAccessors.kt:496)
        at org.gradle.kotlin.dsl.provider.plugins.precompiled.tasks.GeneratePrecompiledScriptPluginAccessors.generateTypeSafeAccessorsFor(GeneratePrecompiledScriptPluginAccessors.kt:166)
        at org.gradle.kotlin.dsl.provider.plugins.precompiled.tasks.GeneratePrecompiledScriptPluginAccessors.generate(GeneratePrecompiledScriptPluginAccessors.kt:152)
```

### Workaround

If you make this change, it will work:

`repro/build-logic/meta/src/main/kotlin/my.kotlin-dsl.gradle.kts`
```kotlin
plugins {
    id("org.gradle.kotlin.kotlin-dsl")
}
```

### Context

I want to have precompiled script plugins that apply `kotlin-dsl` with a certain config to other precompiled script plugins. 
Related: https://github.com/gradle/gradle/issues/17825

### Your Environment
Gradle 7.5.1
macOS 12.6
JDK 11

**Comment by yogurtearl** [comment]
Might just need a better error message here. 
This error message isn't helpful here: `Please remove the version from the offending request `

Maybe it should say this instead `` please use id("org.gradle.kotlin.kotlin-dsl") instead of `kotlin-dsl` ``

**Comment by jbartok** [comment]
I can confirm the problem and that it exists in all versions newer than `7.5.1`.
