### ISSUE TITLE
Build Finished with an exception: java.io.Exception: Unable to establish loopback connection

### ISSUE THREAD

**Issue by thebatman1** [gradle/gradle#2243]
When I execute gradle tasks or any other command like gradle wrapper, it says FAILURE: Build finished with an exception, as mentioned in the title

### Expected Behavior
If I execute the command gradle tasks, it should show me the tasks as mentioned in the website.

### Current Behavior
It gives the java.io.Exception: Unable to establish loopback behaviour

###Stacktrace
 Exception is:
org.gradle.api.UncheckedIOException: java.io.IOException: Unable to establish loopback connection
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:43)
        at org.gradle.internal.remote.internal.inet.SocketConnection.<init>(SocketConnection.java:61)
        at org.gradle.internal.remote.internal.inet.SocketConnectCompletion.create(SocketConnectCompletion.java:39)
        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connectToDaemon(DefaultDaemonConnector.java:255)
        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connectToDaemonWithId(DefaultDaemonConnector.java:241)
        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.startDaemon(DefaultDaemonConnector.java:213)
        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connect(DefaultDaemonConnector.java:130)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:127)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:81)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:281)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:254)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:33)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:247)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:182)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: java.io.IOException: Unable to establish loopback connection
        at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
        at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.nio.ch.PipeImpl.<init>(Unknown Source)
        at sun.nio.ch.SelectorProviderImpl.openPipe(Unknown Source)
        at java.nio.channels.Pipe.open(Unknown Source)
        at sun.nio.ch.WindowsSelectorImpl.<init>(Unknown Source)
        at sun.nio.ch.WindowsSelectorProvider.openSelector(Unknown Source)
        at java.nio.channels.Selector.open(Unknown Source)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketInputStream.<init>(SocketConnection.java:151)
        at org.gradle.internal.remote.internal.inet.SocketConnection.<init>(SocketConnection.java:59)
        ... 26 more
Caused by: java.net.ConnectException: Connection timed out: connect
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Unknown Source)
        at sun.nio.ch.Net.connect(Unknown Source)
        at sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
        at java.nio.channels.SocketChannel.open(Unknown Source)
        at sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(Unknown Source)
        ... 37 more

### Context
I am not able to work with gradle. Although right now I'm using a workaround by using --no-daemon, but I'd like to know how to fix this issue

### Steps to Reproduce (for bugs)
I was following the tutorial on the website https://guides.gradle.org/creating-new-gradle-builds/

### Your Environment

------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_112 (Oracle Corporation 25.112-b15)
OS:           Windows 8.1 6.3 amd64

**Comment by eriwen** [comment]
@thebatman1 What environment are you running Gradle in? Could you consider sending a [build scan](https://gradle.com/build-scans)?

**Comment by thebatman1** [comment]
@eriwen Here is the build scan that you requested. 
https://scans.gradle.com/s/5a6d6lzxbt4yq

**Comment by eriwen** [comment]
@thebatman1 Thank you. According to the build scan, this is with Gradle 3.2. Is it the same for Gradle 3.5?

**Comment by thebatman1** [comment]
@eriwen Oh Sorry, by mistake I used the older version of build scan. Here's the build scan for Gradle 3.5 and build scan version 1.7
https://scans.gradle.com/s/3ioq2l7xeq554

**Comment by trsr99** [comment]
Hi eriwen,
Can you please help me on the issue (loopback issue with Jetty  #3362 )

your help is required.

Thanks
Raj

**Comment by LionelBergen** [comment]
@trsr99 I am having this same issue with Gradle 5.4, Java 8.
Were you ever able to solve the issue?

**Comment by LaxmaReddy-Nalla** [comment]
It happens because anti-virus in the system block i/o data transfer from mobile to pc while JRE requires to establish the connection to t/f while gradle build and further processes make sure firewall allows you to transfer data otherwise turnoff your firewall try once...
