### ISSUE TITLE
File system events ignored on Linux after file watcher error

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#22467]
During a performance test that was supposed to make ABI changes to some source file changes ended up being ignored by Gradle. We noticed this because the baseline build became much faster (as it was now measuring a fully up-to-date build instead) and hence the test failed with a weird result. (See cyan line below.)

<img width="696" alt="image" src="https://user-images.githubusercontent.com/495366/196983920-fdc88794-68e2-475a-9fab-3199077e1abd.png">

https://builds.gradle.org/buildConfiguration/Gradle_Experimental_Util_Performance_AdHocPerformanceScenarioLinuxAmd64/57151620

When looking at the logs it shows that there was an error while polling for events during the 5th measured build:

```text
> Task :doodles-lib:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :doodles-lib:createFullJarDebug UP-TO-DATE
> Task :tracker:kaptGenerateStubsDebugKotlin
Caught exception: Couldn't poll for events, error = 4
net.rubygrapefruit.platform.NativeException: Couldn't poll for events, error = 4
	at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$NativeFileWatcher.executeRunLoop0(Native Method)
	at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$NativeFileWatcher.access$100(AbstractFileEventFunctions.java:159)
	at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$NativeFileWatcher$1.run(AbstractFileEventFunctions.java:173)
> Task :tracker:kaptDebugKotlin
> Task :tracker:compileDebugKotlin
> Task :tracker:bundleLibResDebug UP-TO-DATE
```

The expected behavior would be for Gradle to stop relying on file system events after this, but for some reason it doesn't happen. We even probe the file system at each build's start to see if we are receiving events as expected, and should disable file system watching if we don't.

For some reason, though, Gradle thinks that it's receiving file system events, but it's actually not.

Issue in `native-platform`:
- https://github.com/gradle/native-platform/issues/319
 
PRs:
- https://github.com/gradle/native-platform/pull/320
- https://github.com/gradle/native-platform/pull/321

---
cc: @gradle/execution

**Comment by lptr** [comment]
One explanation might be that it's receiving events for most of the file system, but not for the directory where the file being changed lives.

**Comment by lptr** [comment]
Now, this explains why the build stops receiving events, and makes the fix quite simple: we should either report termination or failure, not both, when the run loop exits.

It still doesn't explain why consecutive builds also have problems detecting changes...

**Comment by lptr** [comment]
OK, so I think I also understand now why subsequent builds don't detect changes.

Yes, we do have file system probes, but we only probe a new hierarchy when it is first registered, and we start watching it. If it returns an event, we will keep relying on it for all the following builds.

https://github.com/gradle/gradle/blob/aec0c2e8ebe99f24c8dcdbf563351c9c810cf469/subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdater.java#L147-L157
