### ISSUE TITLE
Don't cast public interface `MutableVersionConstraint` to internal internal implementations (`DefaultMutableVersionConstraint`). 

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#22557]
I want to implement a custom implementation of the `VersionCatalog` interface, I may also need to also implement `MinimalExternalModuleDependency` and `VersionConstraint`

But this causes error like this: 
```text
Caused by: java.lang.ClassCastException: class com.example.MyCustomVersionConstraint cannot be cast to class org.gradle.api.internal.artifacts.dependencies.DefaultMutableVersionConstraint (com.example.MyCustomVersionConstraint is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @41a95ba7; org.gradle.api.internal.artifacts.dependencies.DefaultMutableVersionConstraint is in unnamed module of loader org.gradle.initialization.MixInLegacyTypesClassLoader @1f760b47)
        at org.gradle.api.internal.artifacts.dependencies.AbstractExternalModuleDependency.<init>(AbstractExternalModuleDependency.java:54)
        at org.gradle.api.internal.artifacts.dependencies.DefaultExternalModuleDependency.<init>(DefaultExternalModuleDependency.java:35)
        at org.gradle.api.internal.artifacts.dependencies.DefaultExternalModuleDependency_Decorated.<init>(Unknown Source)
        at jdk.internal.reflect.GeneratedConstructorAccessor79.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:1913)
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:506)
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:64)
        ... 214 more
```

This is because gradle is casting the public interface (`MutableVersionConstraint`) to an internal implementation (`org.gradle.api.internal.artifacts.dependencies.DefaultMutableVersionConstraint`) here: 
https://github.com/gradle/gradle/blob/c267a7d2c0c658eb92e8a6f65c5321e4c5a3f59c/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/AbstractExternalModuleDependency.java#L54

It defeats the purpose of the `interface` if you assume that it is always an instance of `DefaultMutableVersionConstraint` (internal API)

If you change that line to: 
```java
        this.versionConstraint = new DefaultMutableVersionConstraint(version);
```

that should fix it.

**Comment by jbartok** [comment]
Could you please explain to us what your use case is?
`MutableVersionConstraint` is annotated with `@HasInternalProtocol`, which means it's not something designed to be implemented by build authors.

**Comment by yogurtearl** [comment]
`@HasInternalProtocol` is not visible in the javadocs: 
https://docs.gradle.org/7.6-rc-3/javadoc/org/gradle/api/artifacts/MutableVersionConstraint.html

For doing a custom implementation of `VersionCatalog`, you need to be able to implement this: 

```java
Optional<Provider<MinimalExternalModuleDependency>> findLibrary(String alias);
```

`MinimalExternalModuleDependency` needs an impl of: 

```java
VersionConstraint getVersionConstraint();
```

If you try to just implement `VersionConstraint` you hit issue #22718 , which means you need to implement `MutableVersionConstraint` instead. 


If  #22718 is fixed, this issue becomes less relevant.

**Comment by yogurtearl** [comment]
Mostly working around issues like these: 

- https://github.com/gradle/gradle/issues/22468
- https://github.com/gradle/gradle/issues/15383
- https://github.com/gradle/gradle/issues/21637

But implementing public interfaces is also useful for making `Fake` objects for use in tests. 

You can avoid these types of issues if you wrap the interfaces with internal impls instead of casting them to internal impls, to avoid these type of issues.  

As noted above, wrapping instead of casting solves this issue: 
```
this.versionConstraint = new DefaultMutableVersionConstraint(version);
```
