### ISSUE TITLE
Regression in 7.6-rc-1 when using invalid Maven repository name

### ISSUE THREAD

**Issue by pkoenig10** [gradle/gradle#22582]
Given the following Gradle configuration:

```gradle
plugins {
    id 'maven-publish'
}

publishing {
    repositories {
        maven {
            name = 'maven-jar'
            url = 'https://example.com/'
            credentials {
                username = 'username'
                password = 'password'
            }
        }
    }

    publications {
        maven(MavenPublication) {
            groupId = 'org.example'
            artifactId = 'example'
            version = '1.0.0'
        }
    }
}
```

Publishing succeeds on Gradle 7.5.1 (assuming the repository URL, etc. is valid).

Publishing fails on Gradle 7.6-rc-1 with the following error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishMavenPublicationToMaven-jarRepository'.
> Identity may contain only letters and digits, received: maven-jar

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':publishMavenPublicationToMaven-jarRepository'.
	...
Caused by: java.lang.IllegalArgumentException: Identity may contain only letters and digits, received: maven-jar
	at org.gradle.api.internal.provider.CredentialsProviderFactory.validateIdentity(CredentialsProviderFactory.java:185)
	at org.gradle.api.internal.provider.CredentialsProviderFactory.provide(CredentialsProviderFactory.java:57)
	at org.gradle.api.internal.provider.DefaultProviderFactory.credentials(DefaultProviderFactory.java:203)
	at org.gradle.api.publish.maven.tasks.PublishToMavenRepository.areCredentialsSafe(PublishToMavenRepository.java:136)
	at org.gradle.api.publish.maven.tasks.PublishToMavenRepository.checkCredentialSafety(PublishToMavenRepository.java:122)
	at org.gradle.api.publish.maven.tasks.PublishToMavenRepository.computeSpec(PublishToMavenRepository.java:110)
	at org.gradle.internal.Try.ofFailable(Try.java:41)
	at org.gradle.internal.serialization.Cached$Deferred.result(Cached.java:53)
	at org.gradle.internal.serialization.Cached$Deferred.get(Cached.java:48)
	at org.gradle.api.publish.maven.tasks.PublishToMavenRepository.publish(PublishToMavenRepository.java:95)
```

### Expected Behavior
Publication configurations that worked on Gradle 7.5.1 continue to work on Gradle 7.6-rc-1.

### Current Behavior
Publication configurations that worked on Gradle 7.5.1 do not to work on Gradle 7.6-rc-1.

### Context

This regression was introduced in https://github.com/gradle/gradle/pull/21282, Specifically, it was introduced in https://github.com/gradle/gradle/commit/7c98f022e19db4898d8c608abea715307ec6b686.

Previously the publishing tasks did not call `CredentialsProviderFactory.validateIdentity`. It's not clear to me whether this was intentional or accidental.

### Steps to Reproduce 
See the `build.gradle` reproduction example above.

**Comment by abstratt** [comment]
Thanks for detailed problem report. A fix has now been merged.
