### ISSUE TITLE
Local file based ivy artifacts not resolving in Gradle 4.0

### ISSUE THREAD

**Issue by cmuchinsky** [gradle/gradle#2262]
Local file based ivy artifacts not resolving in Gradle 4.0

### Expected Behavior
Local file based artifacts would continue to resolve from another project as they did in Gradle 3.5. These artifacts are extracted from a tarball, written to the local file based ivy repository, and declared as runtime dependencies of that project during the configuration phase and then consumed by other projects as transitive dependencies. All of these hoops were required to get Buildship to play nice with jars extracted from thirdparty tarball distributions. If there is a better way I would love to hear suggestions.

### Current Behavior
```
* What went wrong:
Could not determine the dependencies of task ‘:foo:war'.
> Could not resolve all task dependencies for configuration ‘:foo:runtimeClasspath'.
   > No variants of project :bar match the consumer attributes:
       - Configuration ‘:bar:runtimeElements' variant classes:
           - Found artifactType 'java-classes-directory' but wasn't required.
           - Required org.gradle.api.attributes.Usage 'java-runtime' and found incompatible value 'java-runtime-classes'.
       - Configuration ‘:bar:runtimeElements' variant resources:
           - Found artifactType 'java-resources-directory' but wasn't required.
           - Required org.gradle.api.attributes.Usage 'java-runtime' and found incompatible value 'java-runtime-resources'.
```

### Your Environment
Gradle 4.0-rc2

**Comment by bmuschko** [comment]
Could you please provide a sample project that demonstrates the issue?

**Comment by cmuchinsky** [comment]
I will try to, however it will take some time to tease one apart from our enterprise builds

**Comment by bmuschko** [comment]
Could you please also explain you issue you are facing with Buildship? At the moment I do not have a good grasp of the problem.

**Comment by cmuchinsky** [comment]
IIRC when we tried to simply explode a tarball and declare local file dependencies on its contents from one project and then have another project depend on that project everything worked fine from Gradle, however as soon as we imported that project into Buildship it has problems putting those jars on the compiler classpath. We had to change things so all of the jars from the tarball could be resolved as artifacts coming from a repository to get it to work. Keep in mind this logic was put in about a year ago and was tested against Buildship 1.x, we are now running Buildship 2.x but the same technique seemed to be appropriate up til Gradle 4.0.

**Comment by bmuschko** [comment]
@donat Would you mind commenting here?

**Comment by cmuchinsky** [comment]
I have attached a small test project that demonstrates the behavior I'm seeing.

[2262test.tar.gz](https://github.com/gradle/gradle/files/1061114/2262test.tar.gz)

**Comment by oehme** [comment]
There's a lot going on in that build, but here's the gist:

```
apply plugin: 'java'
configurations.each { configuration ->
  configuration.artifacts.removeAll { it.archiveTask.is jar }
}
```

You're removing all artifacts, making this `java` project unusable. If you don't want a normal `java` project, don't apply the `java` plugin. Instead you can add things to the `default` configuration.

As for the original question: There should be no problem with plain file dependencies, please give them another try and open a bug if it doesn't work. What you're currently doing is slow and error prone.

**Comment by oehme** [comment]
Just for the record: This is caused by a recent change that prevents Gradle from automatically falling back to the `default` configuration when no match is found. This fallback was very confusing and we accepted the breakage, given that this is a major release.

**Comment by cmuchinsky** [comment]
I wasn't able to get things fully working using the suggestions provided. Switching back to pure file based dependencies and replacing the `java` plugin with the `base` plugin wasn't a problem, however within Eclipse it wasn't setting the dependent project's classpath properly as the project wasn't a Java project.

I ended up abandoning the use of local jar files and manually uploaded them to my artifact repository which solved the problem. Unfortunately this led me to my next issue, which is that the Buildship plugin doesn't seem to be playing nice with Gradle 4.0 (works fine with 3.5). I suspect this needs to be opened as a separate issue but I'll go ahead and drop the stacktraces here in case anybody can identify if this is a Gradle or Buildship specific problem. It doesn't return the same error every time, but it does error out every time with exceptions similar to these:

```
Caused by: java.util.ConcurrentModificationException
	at org.gradle.model.internal.registry.RuleBindings$ScopeIndex.addNode(RuleBindings.java:183)
	at org.gradle.model.internal.registry.RuleBindings$TypePredicateIndex.addNodeToScope(RuleBindings.java:222)
	at org.gradle.model.internal.registry.RuleBindings.nodeDiscovered(RuleBindings.java:46)
	at org.gradle.model.internal.registry.DefaultModelRegistry$NotifyDiscovered.apply(DefaultModelRegistry.java:1167)
	at org.gradle.model.internal.registry.DefaultModelRegistry.transitionTo(DefaultModelRegistry.java:360)
	at org.gradle.model.internal.registry.DefaultModelRegistry.transition(DefaultModelRegistry.java:439)
	at org.gradle.model.internal.registry.DefaultModelRegistry.atStateOrMaybeLater(DefaultModelRegistry.java:203)
	at org.gradle.model.internal.registry.DefaultModelRegistry.atStateOrLater(DefaultModelRegistry.java:190)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.discoverTasks(DefaultTaskContainer.java:226)
	at org.gradle.api.internal.project.DefaultProjectAccessListener.evaluateProjectAndDiscoverTasks(DefaultProjectAccessListener.java:33)
	at org.gradle.api.internal.project.DefaultProjectAccessListener.beforeResolvingProjectDependency(DefaultProjectAccessListener.java:28)
	at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency.beforeResolved(DefaultProjectDependency.java:100)
	at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.ProjectIvyDependencyDescriptorFactory.createDependencyDescriptor(ProjectIvyDependencyDescriptorFactory.java:43)
	at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.DefaultDependencyDescriptorFactory.createDependencyDescriptor(DefaultDependencyDescriptorFactory.java:36)
	at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.DefaultDependenciesToModuleDescriptorConverter.addDependencies(DefaultDependenciesToModuleDescriptorConverter.java:52)
	at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.DefaultDependenciesToModuleDescriptorConverter.addDependencyDescriptors(DefaultDependenciesToModuleDescriptorConverter.java:43)
	at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.DefaultConfigurationComponentMetaDataBuilder.addConfigurations(DefaultConfigurationComponentMetaDataBuilder.java:37)
	at org.gradle.api.internal.artifacts.ivyservice.projectmodule.DefaultProjectLocalComponentProvider.getLocalComponentMetaData(DefaultProjectLocalComponentProvider.java:68)
	at org.gradle.api.internal.artifacts.ivyservice.projectmodule.DefaultProjectLocalComponentProvider.getComponent(DefaultProjectLocalComponentProvider.java:56)
	at org.gradle.api.internal.artifacts.ivyservice.projectmodule.DefaultLocalComponentRegistry.getComponent(DefaultLocalComponentRegistry.java:43)
	at org.gradle.api.internal.artifacts.ivyservice.projectmodule.ProjectDependencyResolver.resolve(ProjectDependencyResolver.java:96)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.ComponentResolversChain$DependencyToComponentIdResolverChain.resolve(ComponentResolversChain.java:149)
	at org.gradle.api.internal.artifacts.ivyservice.dependencysubstitution.DependencySubstitutionResolver.resolve(DependencySubstitutionResolver.java:50)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$SelectorState.resolveModuleRevisionId(DependencyGraphBuilder.java:1209)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$EdgeState.resolveModuleRevisionId(DependencyGraphBuilder.java:403)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.performSelectionSerially(DependencyGraphBuilder.java:245)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.resolveEdges(DependencyGraphBuilder.java:210)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.traverseGraph(DependencyGraphBuilder.java:148)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:121)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:86)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolveGraph(DefaultConfigurationResolver.java:138)
	at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveGraph(ShortCircuitEmptyConfigurationResolver.java:73)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:66)
	... 132 more
```

```
Caused by: java.lang.IllegalStateException: Cannot add rule BinaryBasePlugin.Rules#copyBinaryTasksToTaskContainer(TaskContainer, BinaryContainer) for model element 'tasks' at state Initialized as this element is already at state SelfClosed.
	at org.gradle.model.internal.registry.RuleBinder$1.execute(RuleBinder.java:50)
	at org.gradle.model.internal.registry.RuleBinder$1.execute(RuleBinder.java:44)
	at org.gradle.model.internal.registry.OneOfTypeBinderCreationListener.doOnBind(OneOfTypeBinderCreationListener.java:39)
	at org.gradle.model.internal.registry.ModelBinding.onBind(ModelBinding.java:79)
	at org.gradle.model.internal.registry.RuleBindings.bound(RuleBindings.java:51)
	at org.gradle.model.internal.registry.RuleBindings.access$400(RuleBindings.java:27)
	at org.gradle.model.internal.registry.RuleBindings$PredicateMatches.match(RuleBindings.java:134)
	at org.gradle.model.internal.registry.RuleBindings$ScopeIndex.addReference(RuleBindings.java:211)
	at org.gradle.model.internal.registry.RuleBindings$TypePredicateIndex.addReference(RuleBindings.java:231)
	at org.gradle.model.internal.registry.RuleBindings.addRule(RuleBindings.java:84)
	at org.gradle.model.internal.registry.RuleBindings.add(RuleBindings.java:65)
	at org.gradle.model.internal.registry.DefaultModelRegistry.bindInternal(DefaultModelRegistry.java:165)
	at org.gradle.model.internal.registry.DefaultModelRegistry.configure(DefaultModelRegistry.java:100)
	at org.gradle.model.internal.registry.DefaultModelRegistry.configure(DefaultModelRegistry.java:40)
	at org.gradle.model.internal.inspect.RuleExtractorUtils.configureRuleAction(RuleExtractorUtils.java:30)
	at org.gradle.model.internal.inspect.AbstractMutationModelRuleExtractor$ExtractedMutationRule.apply(AbstractMutationModelRuleExtractor.java:59)
	at org.gradle.model.internal.inspect.ModelRuleExtractor$DefaultExtractedRuleSource.apply(ModelRuleExtractor.java:407)
	at org.gradle.model.internal.registry.ModelNodeInternal.applyToSelf(ModelNodeInternal.java:255)
	at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyRules(RuleBasedPluginTarget.java:60)
	at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperativeRulesHybrid(RuleBasedPluginTarget.java:66)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:163)
	at org.gradle.api.internal.plugins.DefaultPluginManager.access$200(DefaultPluginManager.java:47)
	at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:252)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
	... 137 more
```

**Comment by oehme** [comment]
> however within Eclipse it wasn't setting the dependent project's classpath properly as the project wasn't a Java project.

I would have just removed that project. It was just a container for dependencies. Instead, just add the dependencies to the projects that actually need them.

> Unfortunately this led me to my next issue, which is that the Buildship plugin doesn't seem to be playing nice with Gradle 4.0 (works fine with 3.5).

Yes, please open a bug for [Buildship](https://github.com/eclipse/buildship).

**Comment by cmuchinsky** [comment]
Opened https://github.com/eclipse/buildship/issues/502
