### ISSUE TITLE
PublishToMavenRepository.getRepository is discarded by the configuration cache and cannot be used at execution time

### ISSUE THREAD

**Issue by cloudshiftchris** [gradle/gradle#22641]
### Expected Behavior

Publishing using `maven-publish` works with configuration cache.  Specifically, running subsequent publish tasks pulls from configuration cache and successfully publishes.

### Current Behavior

Exception occurs on second+ publish invocation:

```
➜  gradle-safe-credentials ./gradlew publish -PmySecureRepositoryUsername=secret-user -PmySecureRepositoryPassword=secret-password --stacktrace
Configuration cache is an incubating feature.
Reusing configuration cache.
> Task :publishLibraryPublicationToMySecureRepositoryRepository FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not evaluate onlyIf predicate for task ':publishLibraryPublicationToMySecureRepositoryRepository'.
> Could not evaluate spec for 'publishing available in this environment'.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleException: Could not evaluate onlyIf predicate for task ':publishLibraryPublicationToMySecureRepositoryRepository'.
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:69)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:309)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:302)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:288)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:462)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:379)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
Caused by: org.gradle.api.GradleException: Could not evaluate spec for 'publishing available in this environment'.
        at org.gradle.api.internal.tasks.execution.SelfDescribingSpec.isSatisfiedBy(SelfDescribingSpec.java:42)
        at org.gradle.api.specs.AndSpec.findUnsatisfiedSpec(AndSpec.java:67)
        at org.gradle.api.internal.tasks.execution.DescribingAndSpec.findUnsatisfiedSpec(DescribingAndSpec.java:58)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:44)
        ... 22 more
Caused by: java.lang.IllegalStateException: The value of this property has been discarded during serialization.
        at org.gradle.internal.serialization.Transient$Discarded.get(Transient.java:99)
        at org.gradle.api.publish.maven.tasks.PublishToMavenRepository.getRepository(PublishToMavenRepository.java:69)
        at org.gradle.api.publish.maven.tasks.PublishToMavenRepository_Decorated.getRepository(Unknown Source)
        at Build_gradle$2$1.isSatisfiedBy(build.gradle.kts:27)
        at Build_gradle$2$1.isSatisfiedBy(build.gradle.kts:1)
        at org.gradle.api.internal.tasks.execution.SelfDescribingSpec.isSatisfiedBy(SelfDescribingSpec.java:40)
        ... 25 more


* Get more help at https://help.gradle.org

BUILD FAILED in 287ms
4 actionable tasks: 3 executed, 1 up-to-date
Configuration cache entry reused.
```

### Context
Unable to use `maven-publish` with configuration cache.  Running with --no-configuration-cache works.

### Steps to Reproduce 

Details below.  It's the addition of an `onlyIf` spec to publish tasks that trips this up.

Sample build script:

```
plugins {
    `java-library`
    `maven-publish`
}

version = "0.1.0-SNAPSHOT"

group = "cloudshift.repro"

publishing {
    publications {
        create<MavenPublication>("library") {
            from(components.getByName("java"))
        }
    }
    repositories {
        maven {
            name = "mySecureRepository"
            credentials(PasswordCredentials::class)
            url = uri("https://repo.maven.apache.org/maven2/")
        }

    }
}

tasks.withType<PublishToMavenRepository>().configureEach {
    onlyIf("publishing available in this environment") { repository.name.isNotBlank() }
}
```

First invocation: (this is expected to fail to publish with a 405 error)

`rm -rf .gradle/configuration-cache;  ./gradlew publish -PmySecureRepositoryUsername=secret-user -PmySecureRepositoryPassword=secret-password`

Second invocation: (this fails with the aforementioned exception):

`./gradlew publish -PmySecureRepositoryUsername=secret-user -PmySecureRepositoryPassword=secret-password --stacktrace`

### Your Environment
Gradle 7.6-rc-2, Java 17, MacOS 13

**Comment by mlopatkin** [comment]
Wrapping the predicate into `provider` helps to work around the issue:
```kotlin
tasks.withType<PublishToMavenRepository>().configureEach {
    val predicate = provider {
        repository.name.isNotBlank()
    }

    onlyIf("publishing available in this environment") { predicate.get() }
}
```

This is also suggested in [8.0 docs](https://docs.gradle.org/nightly/userguide/publishing_customization.html#sec:publishing_maven:conditional_publishing).

**Comment by eygraber** [comment]
Is that working as intended, or a workaround until the issue is fixed?

**Comment by jvandort** [comment]
This [PR](https://github.com/gradle/gradle/pull/38423) pulls out the fields from the repositories that Gradle uses at execution time and makes them properly accessible on the task as normal task inputs. We will be deprecating the `repository` property. 

These new properties are `Property` types. The `onlyIf`/`get` problem is still present, and is tracked by https://github.com/gradle/gradle/issues/16080
