### ISSUE TITLE
when apply `idea` and `scala` plugin  throw "A dependency must not be empty" error

### ISSUE THREAD

**Issue by Xcorpio** [gradle/gradle#2275]
i need to apply `scala` and `idea` plugin at the same time in my project.
### Expected Behavior
i am doing some test on gRpc and gatling, i need to tell idea where source file `protoc` generated is. 
Here is my full `build.gradle`:
```groovy
apply plugin: 'idea'
apply plugin: 'scala'
apply plugin: 'application'
apply plugin: 'com.google.protobuf'

buildscript {
    repositories {
        mavenLocal()
        maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.1'
    }
}

repositories {
    mavenLocal()
    maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }
    mavenCentral()
    jcenter()
}
}

ext {
    grpcVersion = "1.4.0"
}

dependencies {
    compile group: 'com.typesafe.akka', name: 'akka-http_2.11', version: '10.0.7'
    compile (group: 'io.gatling.highcharts', name: 'gatling-charts-highcharts', version: '2.2.5') {
        exclude group: 'org.asynchttpclient', module: 'async-http-client'
    }
    compile group: 'io.grpc', name: 'grpc-netty', version: "$grpcVersion"
    compile group: 'io.grpc', name: 'grpc-protobuf', version: "$grpcVersion"
    compile group: 'io.grpc', name: 'grpc-stub', version: "$grpcVersion"

    // Log
    compile group: 'org.slf4j', name: 'slf4j-api', version: '1.7.25'
    compile group: 'ch.qos.logback', name: 'logback-classic', version: '1.2.3'

    testCompile 'junit:junit:4.12'
    testCompile group: 'com.typesafe.akka', name: 'akka-http-testkit_2.11', version: '10.0.7'
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.3.0"
    }
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:$grpcVersion"
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
    }
}

idea {
    module {
        // Not using generatedSourceDirs because of
        // https://discuss.gradle.org/t/support-for-intellij-2016/15294/8
        sourceDirs += file("${projectDir}/build/generated/source/proto/main/java");
        sourceDirs += file("${projectDir}/build/generated/source/proto/main/grpc");
    }
}

startScripts.enabled = false
task helloWorldServer(type: CreateStartScripts) {
    mainClassName = 'com.guazi.qa.pea.grpc.helloworld.HelloWorldServer'
    applicationName = 'hello-world-server'
    outputDir = new File(project.buildDir, 'tmp')
    classpath = jar.outputs.files + project.configurations.runtime
}

task helloWorldClient(type: CreateStartScripts) {
    mainClassName = 'com.guazi.qa.pea.grp.helloworld.HelloWorldClient'
    applicationName = 'hello-world-client'
    outputDir = new File(project.buildDir, 'tmp')
    classpath = jar.outputs.files + project.configurations.runtime
}

applicationDistribution.into('bin') {
    from(helloWorldServer)
    from(helloWorldClient)
    fileMode = 0755
}
```

### Current Behavior
Here is the log and stacktrace:
```
18:05:16.101 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Registering model element 'tasks.idea' (hidden = false)
18:05:16.101 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Registering model element 'tasks.cleanIdea' (hidden = false)
18:05:16.101 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Registering model element 'tasks.ideaModule' (hidden = false)
18:05:16.102 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Registering model element 'tasks.cleanIdeaModule' (hidden = false)
18:05:16.104 [INFO] [org.gradle.internal.operations.DefaultBuildOperationWorkerRegistry] Using 4 worker leases.
18:05:16.105 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Registering model element 'tasks.clean' (hidden = false)
18:05:16.105 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Registering model element 'tasks.assemble' (hidden = false)
18:05:16.105 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Registering model element 'tasks.check' (hidden = false)
18:05:16.105 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Registering model element 'tasks.build' (hidden = false)
18:05:16.108 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Transitioning model element 'tasks.assemble' from state Registered to Initialized
18:05:16.108 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Running model element 'tasks.assemble' rule action tasks.addPlaceholderAction(assemble)
18:05:16.108 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Mutating tasks.assemble using tasks.addPlaceholderAction(assemble)
18:05:16.108 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Transitioning model element 'tasks.assemble' to state Discovered.
18:05:16.109 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Running model element 'tasks.assemble' rule action tasks.addPlaceholderAction(assemble)
18:05:16.109 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Mutating tasks.assemble using tasks.addPlaceholderAction(assemble)
18:05:16.109 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Transitioning model element 'tasks.assemble' to state Created.
18:05:16.109 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Transitioning model element 'tasks.assemble' to state DefaultsApplied.
18:05:16.110 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Running model element 'tasks.assemble' rule action copyToTaskContainer
18:05:16.112 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Mutating tasks.assemble using copyToTaskContainer
18:05:16.112 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Transitioning model element 'tasks.assemble' to state Initialized.
18:05:16.113 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Registering model element 'componentSpecFactory' (hidden = true)
18:05:16.113 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Registering model element 'components' (hidden = false)
18:05:16.114 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Registering model element 'sources' (hidden = false)
18:05:16.116 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Registering model element 'binaries' (hidden = false)
18:05:16.117 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Registering model element 'bridgedBinaries' (hidden = true)
18:05:16.117 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Registering model element 'tasks.buildNeeded' (hidden = false)
18:05:16.118 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :core - Registering model element 'tasks.buildDependents' (hidden = false)
18:05:16.120 [DEBUG] [org.gradle.configuration.project.BuildScriptProcessor] Timing: Running the build script took 0.282 secs
18:05:16.131 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
18:05:16.131 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
18:05:16.133 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
18:05:16.133 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Where:
18:05:16.133 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Build file '/Users/*/Workspace/guazi/pea/core/build.gradle' line: 2
18:05:16.133 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
18:05:16.133 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
18:05:16.133 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] A problem occurred evaluating project ':core'.
18:05:16.133 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Failed to apply plugin [class 'org.gradle.api.plugins.scala.ScalaBasePlugin']
18:05:16.133 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > A dependency must not be empty
18:05:16.134 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
18:05:16.134 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
18:05:16.135 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.GradleScriptException: A problem occurred evaluating project ':core'.
18:05:16.135 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:92)
18:05:16.135 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:176)
18:05:16.136 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
18:05:16.136 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:181)
18:05:16.136 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
18:05:16.136 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
18:05:16.136 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
18:05:16.136 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:70)
18:05:16.136 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
18:05:16.136 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
18:05:16.136 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
18:05:16.136 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
18:05:16.136 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
18:05:16.136 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
18:05:16.136 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
18:05:16.137 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:628)
18:05:16.137 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:129)
18:05:16.137 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
18:05:16.137 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
18:05:16.137 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
18:05:16.137 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:161)
18:05:16.137 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:158)
18:05:16.137 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
18:05:16.137 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
18:05:16.137 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
18:05:16.137 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:158)
18:05:16.137 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
18:05:16.137 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
18:05:16.137 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
18:05:16.137 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
18:05:16.137 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
18:05:16.137 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
18:05:16.137 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
18:05:16.138 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
18:05:16.138 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
18:05:16.138 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
18:05:16.138 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
18:05:16.138 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
18:05:16.138 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
18:05:16.138 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:05:16.138 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
18:05:16.138 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:05:16.138 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
18:05:16.138 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:05:16.138 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
18:05:16.139 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:05:16.139 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
18:05:16.139 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
18:05:16.139 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.util.Swapper.swap(Swapper.java:38)
18:05:16.139 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
18:05:16.139 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:05:16.139 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
18:05:16.139 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:05:16.139 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
18:05:16.139 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
18:05:16.139 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:05:16.139 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
18:05:16.139 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
18:05:16.139 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:05:16.139 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
18:05:16.139 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
18:05:16.139 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
18:05:16.139 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
18:05:16.139 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [class 'org.gradle.api.plugins.scala.ScalaBasePlugin']
18:05:16.140 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:155)
18:05:16.140 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:116)
18:05:16.140 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.plugins.scala.ScalaPlugin.apply(ScalaPlugin.java:43)
18:05:16.140 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.plugins.scala.ScalaPlugin.apply(ScalaPlugin.java:38)
18:05:16.140 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
18:05:16.140 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
18:05:16.140 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:139)
18:05:16.140 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
18:05:16.140 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:113)
18:05:16.140 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
18:05:16.140 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
18:05:16.140 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
18:05:16.140 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:44)
18:05:16.140 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34)
18:05:16.140 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
18:05:16.140 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at build_4rbaxmte7mtxqhb3j5jn5zvmd.run(/Users/*/Workspace/guazi/pea/core/build.gradle:2)
18:05:16.140 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
18:05:16.140 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 62 more
18:05:16.140 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.api.InvalidUserDataException: A dependency must not be empty
18:05:16.140 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.DefaultTaskDependency.addValue(DefaultTaskDependency.java:152)
18:05:16.141 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.DefaultTaskDependency.add(DefaultTaskDependency.java:145)
18:05:16.141 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask$11.run(AbstractTask.java:359)
18:05:16.141 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.TaskMutator.mutate(TaskMutator.java:40)
18:05:16.141 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask.dependsOn(AbstractTask.java:357)
18:05:16.141 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.plugins.ide.idea.IdeaPlugin.ideaModuleDependsOnRoot(IdeaPlugin.java:432)
18:05:16.141 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.plugins.ide.idea.IdeaPlugin.access$500(IdeaPlugin.java:62)
18:05:16.141 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.plugins.ide.idea.IdeaPlugin$19.execute(IdeaPlugin.java:415)
18:05:16.141 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.plugins.ide.idea.IdeaPlugin$19.execute(IdeaPlugin.java:412)
18:05:16.141 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:205)
18:05:16.141 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.listener.ActionBroadcast.execute(ActionBroadcast.java:39)
18:05:16.141 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:172)
18:05:16.141 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:166)
18:05:16.141 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
18:05:16.141 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 78 more
18:05:16.141 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
18:05:16.141 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger]
18:05:16.141 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED
18:05:16.141 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger]
18:05:16.141 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] Total time: 1.485 secs
```

### Your Environment
```
➜  pea git:(master) gradle -v

------------------------------------------------------------
Gradle 3.3
------------------------------------------------------------

Build time:   2017-01-03 15:31:04 UTC
Revision:     075893a3d0798c0c1f322899b41ceca82e4e134b

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_91 (Oracle Corporation 25.91-b14)
OS:           Mac OS X 10.12.5 x86_64
```
IDEA `2017.1`
Scala Plugin: `Version: 2017.1.15.49`

**Comment by joserobjr** [comment]
Is there any workaround? I can't remove the idea plugin because it is coming as dependency from an other plugin that I need to use.

**Comment by bmuschko** [comment]
Your sample build script works fine with Gradle 4.0. Could you please consider upgrading your Gradle version?

**Comment by Xcorpio** [comment]
I upgrade my Gradle version, and add `apply plugin: 'idea'` to root build.gradle 。
it works

**Comment by bmuschko** [comment]
Thanks, I am going to close the issue.
