### ISSUE TITLE
Groovy compilation failure with traits

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#22814]
It seems there is another Groovy compiler or incremental bug that we should investigate. It seems this one is triggered just for `.groovy` files and interestingly it fails for a class inside a trait.

Error message: 
```
Unable to load class org.gradle.smoketests.WithPluginValidation$AllPluginsValidation due to missing dependency Lorg/gradle/smoketests/AbstractSmokeTest;
```

Recompiled sources:
```
smokeTest/groovy/org/gradle/smoketests/KotlinPluginAndroidKotlinDSLSmokeTest.groovy 
smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy 
smokeTest/groovy/org/gradle/smoketests/GradleBuildExternalPluginsValidationSmokeTest.groovy
smokeTest/groovy/org/gradle/smoketests/KotlinPluginAndroidGroovyDSLSmokeTest.groovy 
smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy 
smokeTest/groovy/org/gradle/smoketests/AbstractGradleceptionSmokeTest.groovy 
smokeTest/groovy/org/gradle/smoketests/BuildScanPluginSmokeTest.groovy 
smokeTest/groovy/org/gradle/smoketests/AbstractGradleBuildConfigurationCacheSmokeTest.groovy
smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
```

Recompiled classes:
```
Recompiled classes [org.gradle.smoketests.AbstractGradleceptionSmokeTest$_closure1, org.gradle.smoketests.AbstractGradleBuildConfigurationCacheSmokeTest$_closure1, org.gradle.smoketests.AndroidPluginsSmokeTest$__spock_feature_2_1_closure4, org.gradle.smoketests.AndroidPluginsSmokeTest$__spock_feature_2_1_closure6, org.gradle.smoketests.AndroidPluginsSmokeTest$__spock_feature_2_1_closure5, org.gradle.smoketests.BuildScanPluginSmokeTest, org.gradle.smoketests.GradleBuildExternalPluginsValidationSmokeTest$_closure1, org.gradle.smoketests.AbstractSmokeTest, org.gradle.smoketests.KotlinPluginSmokeTest$_configureValidation_closure1, org.gradle.smoketests.KotlinPluginSmokeTest$__spock_feature_2_3_closure6, org.gradle.smoketests.KotlinPluginSmokeTest, org.gradle.smoketests.KotlinPluginSmokeTest$__spock_feature_2_2_closure4, org.gradle.smoketests.KotlinPluginSmokeTest$__spock_feature_2_0_closure2, org.gradle.smoketests.KotlinPluginSmokeTest$__spock_feature_2_2_closure5, org.gradle.smoketests.KotlinPluginSmokeTest$KotlinDeprecations, org.gradle.smoketests.KotlinPluginSmokeTest$__spock_feature_2_1_closure3, org.gradle.smoketests.KotlinPluginAndroidKotlinDSLSmokeTest, org.gradle.smoketests.KotlinPluginAndroidGroovyDSLSmokeTest, org.gradle.smoketests.AbstractGradleceptionSmokeTest$GradleBuildJvmSpec, org.gradle.smoketests.AbstractGradleceptionSmokeTest$__clinit__closure3, org.gradle.smoketests.AbstractGradleceptionSmokeTest$_newTimestampDateFormat_closure2, org.gradle.smoketests.AbstractGradleceptionSmokeTest, org.gradle.smoketests.AbstractGradleBuildConfigurationCacheSmokeTest, org.gradle.smoketests.AndroidPluginsSmokeTest$_configureValidation_closure2$_closure8$_closure9, org.gradle.smoketests.AndroidPluginsSmokeTest, org.gradle.smoketests.AndroidPluginsSmokeTest$_configureValidation_closure2, org.gradle.smoketests.AndroidPluginsSmokeTest$__spock_feature_2_1_closure3, org.gradle.smoketests.AndroidPluginsSmokeTest$AndroidDeprecations, org.gradle.smoketests.AndroidPluginsSmokeTest$_androidLibraryAndApplicationBuild_closure1, org.gradle.smoketests.AndroidPluginsSmokeTest$_configureValidation_closure2$_closure8, org.gradle.smoketests.AndroidPluginsSmokeTest$_configureValidation_closure2$_closure7, org.gradle.smoketests.AndroidPluginsSmokeTest$_configureValidation_closure2$_closure8$_closure10, org.gradle.smoketests.GradleBuildExternalPluginsValidationSmokeTest$ProjectValidation, org.gradle.smoketests.GradleBuildExternalPluginsValidationSmokeTest, org.gradle.smoketests.GradleBuildExternalPluginsValidationSmokeTest$_setup_closure2, org.gradle.smoketests.GradleBuildExternalPluginsValidationSmokeTest$__spock_feature_2_0_closure3, org.gradle.smoketests.AbstractSmokeTest$Versions, org.gradle.smoketests.AbstractSmokeTest$Versions$_latestStartsWith_closure2, org.gradle.smoketests.AbstractSmokeTest$Versions$_latestStable_closure1, org.gradle.smoketests.AbstractSmokeTest$TestedVersions$__clinit__closure1, org.gradle.smoketests.AbstractSmokeTest$_toolchainParameters_closure1, org.gradle.smoketests.AbstractSmokeTest$TestedVersions, org.gradle.smoketests.AbstractSmokeTest$_replaceVariablesInFile_closure2, org.gradle.smoketests.KotlinPluginAndroidKotlinDSLSmokeTest$__spock_feature_1_0_closure2, org.gradle.smoketests.KotlinPluginAndroidKotlinDSLSmokeTest$__spock_feature_1_0_closure1, org.gradle.smoketests.KotlinPluginAndroidGroovyDSLSmokeTest$__spock_feature_1_0_closure2, org.gradle.smoketests.KotlinPluginAndroidGroovyDSLSmokeTest$__spock_feature_1_0_closure1]
```

Stacktrace:
```
2022-11-18T17:59:09.263+0100 [ERROR] [system.err] startup failed:
2022-11-18T17:59:09.263+0100 [ERROR] [system.err] General error during instruction selection: java.lang.NoClassDefFoundError: Unable to load class org.gradle.smoketests.WithPluginValidation$AllPluginsValidation due to missing dependency Lorg/gradle/smoketests/AbstractSmokeTest;
2022-11-18T17:59:09.263+0100 [ERROR] [system.err] 
2022-11-18T17:59:09.264+0100 [ERROR] [system.err] java.lang.RuntimeException: java.lang.NoClassDefFoundError: Unable to load class org.gradle.smoketests.WithPluginValidation$AllPluginsValidation due to missing dependency Lorg/gradle/smoketests/AbstractSmokeTest;
2022-11-18T17:59:09.264+0100 [ERROR] [system.err]       at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:976)
2022-11-18T17:59:09.265+0100 [ERROR] [system.err]       at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:671)
2022-11-18T17:59:09.265+0100 [ERROR] [system.err]       at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:635)
2022-11-18T17:59:09.265+0100 [ERROR] [system.err]       at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:610)
2022-11-18T17:59:09.265+0100 [ERROR] [system.err]       at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:271)
2022-11-18T17:59:09.265+0100 [ERROR] [system.err]       at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:64)
2022-11-18T17:59:09.265+0100 [ERROR] [system.err]       at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:97)
2022-11-18T17:59:09.266+0100 [ERROR] [system.err]       at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:76)
2022-11-18T17:59:09.267+0100 [ERROR] [system.err]       at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkAction.execute(AbstractDaemonCompiler.java:135)
2022-11-18T17:59:09.267+0100 [ERROR] [system.err]       at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
2022-11-18T17:59:09.267+0100 [ERROR] [system.err]       at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
2022-11-18T17:59:09.267+0100 [ERROR] [system.err]       at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
2022-11-18T17:59:09.267+0100 [ERROR] [system.err]       at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
2022-11-18T17:59:09.267+0100 [ERROR] [system.err]       at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
2022-11-18T17:59:09.267+0100 [ERROR] [system.err]       at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
2022-11-18T17:59:09.267+0100 [ERROR] [system.err]       at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
2022-11-18T17:59:09.268+0100 [ERROR] [system.err]       at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:87)
2022-11-18T17:59:09.268+0100 [ERROR] [system.err]       at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:56)
2022-11-18T17:59:09.268+0100 [ERROR] [system.err]       at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
2022-11-18T17:59:09.268+0100 [ERROR] [system.err]       at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
2022-11-18T17:59:09.268+0100 [ERROR] [system.err]       at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
2022-11-18T17:59:09.268+0100 [ERROR] [system.err]       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-11-18T17:59:09.268+0100 [ERROR] [system.err]       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-11-18T17:59:09.268+0100 [ERROR] [system.err]       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-11-18T17:59:09.268+0100 [ERROR] [system.err]       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-11-18T17:59:09.268+0100 [ERROR] [system.err]       at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
2022-11-18T17:59:09.269+0100 [ERROR] [system.err]       at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
2022-11-18T17:59:09.269+0100 [ERROR] [system.err]       at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
2022-11-18T17:59:09.269+0100 [ERROR] [system.err]       at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
2022-11-18T17:59:09.269+0100 [ERROR] [system.err]       at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
2022-11-18T17:59:09.269+0100 [ERROR] [system.err]       at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
2022-11-18T17:59:09.269+0100 [ERROR] [system.err]       at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
2022-11-18T17:59:09.269+0100 [ERROR] [system.err]       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-11-18T17:59:09.269+0100 [ERROR] [system.err]       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-11-18T17:59:09.269+0100 [ERROR] [system.err]       at java.base/java.lang.Thread.run(Thread.java:829)
2022-11-18T17:59:09.270+0100 [ERROR] [system.err] Caused by: java.lang.NoClassDefFoundError: Unable to load class org.gradle.smoketests.WithPluginValidation$AllPluginsValidation due to missing dependency Lorg/gradle/smoketests/AbstractSmokeTest;
2022-11-18T17:59:09.270+0100 [ERROR] [system.err]       at org.codehaus.groovy.vmplugin.v8.Java8.configureClassNode(Java8.java:447)
2022-11-18T17:59:09.270+0100 [ERROR] [system.err]       at org.codehaus.groovy.ast.ClassNode.lazyClassInit(ClassNode.java:273)
2022-11-18T17:59:09.270+0100 [ERROR] [system.err]       at org.codehaus.groovy.ast.ClassNode.getUnresolvedSuperClass(ClassNode.java:1014)
2022-11-18T17:59:09.270+0100 [ERROR] [system.err]       at org.codehaus.groovy.ast.ClassNode.getUnresolvedSuperClass(ClassNode.java:1006)
2022-11-18T17:59:09.270+0100 [ERROR] [system.err]       at org.codehaus.groovy.ast.ClassNode.getSuperClass(ClassNode.java:1000)
2022-11-18T17:59:09.270+0100 [ERROR] [system.err]       at org.codehaus.groovy.ast.ClassNode.isDerivedFrom(ClassNode.java:911)
2022-11-18T17:59:09.270+0100 [ERROR] [system.err]       at org.codehaus.groovy.classgen.asm.InvocationWriter.castToNonPrimitiveIfNecessary(InvocationWriter.java:1144)
2022-11-18T17:59:09.270+0100 [ERROR] [system.err]       at org.codehaus.groovy.classgen.asm.OperandStack.doConvertAndCast(OperandStack.java:363)
2022-11-18T17:59:09.270+0100 [ERROR] [system.err]       at org.codehaus.groovy.classgen.asm.OperandStack.doGroovyCast(OperandStack.java:300)
2022-11-18T17:59:09.270+0100 [ERROR] [system.err]       at org.codehaus.groovy.classgen.AsmClassGenerator.storeThisInstanceField(AsmClassGenerator.java:1259)
2022-11-18T17:59:09.270+0100 [ERROR] [system.err]       at org.codehaus.groovy.classgen.AsmClassGenerator.visitFieldExpression(AsmClassGenerator.java:1196)
2022-11-18T17:59:09.270+0100 [ERROR] [system.err]       at org.codehaus.groovy.ast.expr.FieldExpression.visit(FieldExpression.java:41)
2022-11-18T17:59:09.271+0100 [ERROR] [system.err]       at org.codehaus.groovy.classgen.AsmClassGenerator.visitPropertyExpression(AsmClassGenerator.java:1124)
2022-11-18T17:59:09.271+0100 [ERROR] [system.err]       at org.codehaus.groovy.ast.expr.PropertyExpression.visit(PropertyExpression.java:63)
2022-11-18T17:59:09.271+0100 [ERROR] [system.err]       at org.codehaus.groovy.classgen.AsmClassGenerator.visitVariableExpression(AsmClassGenerator.java:1339)
2022-11-18T17:59:09.271+0100 [ERROR] [system.err]       at org.codehaus.groovy.ast.expr.VariableExpression.visit(VariableExpression.java:71)
2022-11-18T17:59:09.271+0100 [ERROR] [system.err]       at org.codehaus.groovy.classgen.asm.BinaryExpressionHelper.evaluateEqual(BinaryExpressionHelper.java:472)
2022-11-18T17:59:09.272+0100 [ERROR] [system.err]       at org.codehaus.groovy.classgen.asm.BinaryExpressionHelper.eval(BinaryExpressionHelper.java:150)
2022-11-18T17:59:09.272+0100 [ERROR] [system.err]       at org.codehaus.groovy.classgen.AsmClassGenerator.visitBinaryExpression(AsmClassGenerator.java:708)
2022-11-18T17:59:09.272+0100 [ERROR] [system.err]       at org.codehaus.groovy.ast.expr.BinaryExpression.visit(BinaryExpression.java:58)
2022-11-18T17:59:09.272+0100 [ERROR] [system.err]       at org.codehaus.groovy.classgen.asm.StatementWriter.writeExpressionStatement(StatementWriter.java:637)
2022-11-18T17:59:09.272+0100 [ERROR] [system.err]       at org.codehaus.groovy.classgen.asm.OptimizingStatementWriter.writeExpressionStatement(OptimizingStatementWriter.java:363)
2022-11-18T17:59:09.272+0100 [ERROR] [system.err]       at org.codehaus.groovy.classgen.AsmClassGenerator.visitExpressionStatement(AsmClassGenerator.java:687)
2022-11-18T17:59:09.272+0100 [ERROR] [system.err]       at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
2022-11-18T17:59:09.272+0100 [ERROR] [system.err]       at org.codehaus.groovy.classgen.asm.StatementWriter.writeBlockStatement(StatementWriter.java:95)
2022-11-18T17:59:09.272+0100 [ERROR] [system.err]       at org.codehaus.groovy.classgen.asm.OptimizingStatementWriter.writeBlockStatement(OptimizingStatementWriter.java:169)
2022-11-18T17:59:09.273+0100 [ERROR] [system.err]       at org.codehaus.groovy.classgen.AsmClassGenerator.visitBlockStatement(AsmClassGenerator.java:618)
2022-11-18T17:59:09.273+0100 [ERROR] [system.err]       at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
2022-11-18T17:59:09.273+0100 [ERROR] [system.err]       at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:138)
2022-11-18T17:59:09.273+0100 [ERROR] [system.err]       at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:111)
2022-11-18T17:59:09.273+0100 [ERROR] [system.err]       at org.codehaus.groovy.classgen.AsmClassGenerator.visitStdMethod(AsmClassGenerator.java:462)
2022-11-18T17:59:09.273+0100 [ERROR] [system.err]       at org.codehaus.groovy.classgen.AsmClassGenerator.visitConstructorOrMethod(AsmClassGenerator.java:409)
2022-11-18T17:59:09.273+0100 [ERROR] [system.err]       at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructor(ClassCodeVisitorSupport.java:101)
2022-11-18T17:59:09.273+0100 [ERROR] [system.err]       at org.codehaus.groovy.classgen.AsmClassGenerator.visitConstructor(AsmClassGenerator.java:551)
2022-11-18T17:59:09.273+0100 [ERROR] [system.err]       at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1084)
2022-11-18T17:59:09.273+0100 [ERROR] [system.err]       at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:52)
2022-11-18T17:59:09.273+0100 [ERROR] [system.err]       at org.codehaus.groovy.classgen.AsmClassGenerator.visitClass(AsmClassGenerator.java:273)
2022-11-18T17:59:09.274+0100 [ERROR] [system.err]       at org.codehaus.groovy.control.CompilationUnit$3.call(CompilationUnit.java:797)
2022-11-18T17:59:09.274+0100 [ERROR] [system.err]       at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:942)
2022-11-18T17:59:09.274+0100 [ERROR] [system.err]       ... 34 more
2022-11-18T17:59:09.274+0100 [ERROR] [system.err] 
2022-11-18T17:59:09.274+0100 [ERROR] [system.err] 1 error
```

**Comment by asodja** [comment]
A simple reproducer can be found [here](https://github.com/asodja/groovy-traits-compilation-reproducer). I posted the issue on [Groovy slack](https://groovy-community.slack.com/archives/C2NEFCM55/p1676028392464979).

**Comment by lptr** [comment]
Reported as https://issues.apache.org/jira/browse/GROOVY-10932

**Comment by leonard84** [comment]
Another issue is with using `@AnnotationCollector`, which works fine when the custom collector is compiled with the users but fails when the users are compiled alone incrementally.
