### ISSUE TITLE
Assertion failed in FinalizerGroup with Kotlin 1.7.21

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#22853]
### Expected Behavior

No failed assertion

### Current Behavior

```
* What went wrong:
A problem occurred configuring project ':server-application:app'.
> Build completed with 1 failures.
   > java.lang.AssertionError (no error message)

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':server-application:app'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:84)
        ..........
Caused by: org.gradle.execution.MultipleBuildFailures: Build completed with 1 failures.
	at org.gradle.internal.build.ExecutionResult$Failure.getFailure(ExecutionResult.java:191)
        ..........
Caused by: java.lang.AssertionError
	at org.gradle.execution.plan.FinalizerGroup.removeMember(FinalizerGroup.java:125)
	at org.gradle.execution.plan.CompositeNodeGroup.removeMember(CompositeNodeGroup.java:93)
	at org.gradle.execution.plan.Node.setGroup(Node.java:120)
	at org.gradle.execution.plan.Node.maybeInheritFinalizerGroups(Node.java:159)
	at org.gradle.execution.plan.DetermineExecutionPlanAction.updateFinalizerGroups(DetermineExecutionPlanAction.java:131)
	at org.gradle.execution.plan.DetermineExecutionPlanAction.run(DetermineExecutionPlanAction.java:92)
	at org.gradle.execution.plan.DefaultExecutionPlan.determineExecutionPlan(DefaultExecutionPlan.java:225)
	at org.gradle.internal.build.DefaultBuildWorkPreparer.populateWorkGraph(DefaultBuildWorkPreparer.java:43)
        ........

* Get more help at https://help.gradle.org

BUILD FAILED in 51s
```

Full stracktrace in the build scan:
https://ge.gradle.org/s/zfvlxi4quy2pe/tests/overview

### Context

Trying to upgrade the embedded Kotlin from 1.7.20 to 1.7.21.

### Steps to Reproduce 

* `git checkout eskatos/kotlin/embedded-1.7.21`
* `./gradlew :docs:docsTest --tests "*.structuring-software-projects_kotlin_umbrella-build*"`
* or `./gradlew :distribution-integ-tests:forkingIntegTest --tests=SrcDistributionIntegrationSpec`

**Comment by eskatos** [comment]
Fixed by 

* https://github.com/gradle/gradle/pull/22898
