### ISSUE TITLE
Gradle 7.6 is having an issue with PKIX path validation failed: validity check failed

### ISSUE THREAD

**Issue by nico-arianto** [gradle/gradle#22864]
This issue only happens after upgrading the Gradle from `7.5.1` to `7.6`

### Expected Behavior

The Gradle `7.6` build should be able to download the libraries from Maven central (or JCenter) and continue with the build

### Current Behavior

The Gradle `7.6` is failing to download the resources from JCenter with an error as below:
```
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
        at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:369)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:263)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
        ... 282 more
Caused by: java.security.cert.CertPathValidatorException: validity check failed
        at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:224)
        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:144)
        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:83)
        at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
        at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:364)
        ... 287 more
Caused by: java.security.cert.CertificateExpiredException: NotAfter: Sat Nov 26 07:59:59 SGT 2022
        at java.base/sun.security.x509.CertificateValidity.valid(CertificateValidity.java:277)
        at java.base/sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:619)
        at java.base/sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)
        at java.base/sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
        at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
        ... 292 more
```

### Context

Not able to use the latest Gradle `7.6`, and kept to continue with `7.5.1`

### Steps to Reproduce 

```
gradle build
```

### Your Environment

Build scan URL: https://gradle.com/s/xlcfvbj3axyty
```
------------------------------------------------------------
Gradle 7.6
------------------------------------------------------------

Build time:   2022-11-25 13:35:10 UTC
Revision:     daece9dbc5b79370cc8e4fd6fe4b2cd400e150a8

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.5 (Eclipse Adoptium 17.0.5+8)
OS:           Mac OS X 13.0.1 aarch64
```

**Comment by Kurru** [comment]
I'm seeing this will `Gradle 7.2` running in Github Actions. 

Specifically I'm failing to retrieve `com.google.gradle:osdetector-gradle-plugin:1.7.1` which seems to be resolving to `https://jcenter.bintray.com` whose certificate just expired.

```
> Could not resolve all artifacts for configuration ':api:classpath'.
   > Could not resolve com.google.gradle:osdetector-gradle-plugin:1.7.1.
     Required by:
         project :api > com.google.protobuf:com.google.protobuf.gradle.plugin:0.9.1 > com.google.protobuf:protobuf-gradle-plugin:0.9.1
      > Could not resolve com.google.gradle:osdetector-gradle-plugin:1.7.1.
         > Could not get resource 'https://plugins.gradle.org/m2/com/google/gradle/osdetector-gradle-plugin/1.7.1/osdetector-gradle-plugin-1.7.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/google/gradle/osdetector-gradle-plugin/1.7.1/osdetector-gradle-plugin-1.7.1.pom'.
               > PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
```

```

Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	... 257 more
Caused by: java.security.cert.CertPathValidatorException: validity check failed
	... 257 more
Caused by: java.security.cert.CertificateExpiredException: NotAfter: Fri Nov 25 23:59:59 UTC 2022
	... 257 more
```

**Comment by Ahoo-Wang** [comment]
The problem also occurs in my GitHub CI
https://github.com/Ahoo-Wang/CosId/actions/runs/3551487351/jobs/5966111402

**Comment by rpalcolea** [comment]
This in a issue with jfrog 

SSL Certs have expired again.

jcenter.bintray.com

        Validity
            Not Before: Oct 25 00:00:00 2021 GMT
            Not After : Nov 25 23:59:59 2022 GMT
            

Unfortunately, the plugin portal still relies on some jcenter portions and it is impacted 

Hopefully jfrog will fix it soon

**Comment by kobe2000** [comment]
I solved it by adjusting my PC time prior to  Nov 26 07:59:59 SGT 2022

**Comment by jonathanlermitage** [comment]
As mentioned [here](https://github.com/spring-projects/spring-boot/issues/33368#issuecomment-1327966338), you can use Maven repositories instead of JCenter. This is safer than modifying your clock ;-)
```
buildscript {
	repositories {
		maven(url = "https://repo1.maven.org/maven2") 
	}
}
```

**Comment by ben-manes** [comment]
Unfortunately there are [quirks](https://github.com/gradle/plugin-portal-requests/issues/165) when the module metadata is missing.

```
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve me.champeau.jmh:jmh-gradle-plugin:0.6.8.
     Required by:
         project :
      > Could not resolve me.champeau.jmh:jmh-gradle-plugin:0.6.8.
         > Could not get resource 'https://plugins.gradle.org/m2/me/champeau/jmh/jmh-gradle-plugin/0.6.8/jmh-gradle-plugin-0.6.8.module'.
            > Could not GET 'https://jcenter.bintray.com/me/champeau/jmh/jmh-gradle-plugin/0.6.8/jmh-gradle-plugin-0.6.8.module'.
               > PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
```

If it is not needed by your build (e.g. no usages of variant selection) then you can do,

```patch
   repositories {
-    gradlePluginPortal()
     mavenCentral()
+    maven {
+      url 'https://plugins.gradle.org/m2'
+      metadataSources {
+        ignoreGradleMetadataRedirection()
+        mavenPom()
+        artifact()
+      }
+    }
   }
```

**Comment by xic1151-krishnaprasad** [comment]
Certificate issue was solved by Jcenter

**Comment by nico-arianto** [comment]
Closed this issue, as it's working as expected after JCenter have resolved the expired certification.
