### ISSUE TITLE
JacocoReportAggregationPlugin doesn't work with lockfiles

### ISSUE THREAD

**Issue by Toldry** [gradle/gradle#22918]
`JacocoReportAggregationPlugin` doesn't work with lockfiles; attempting to use both causes a failure.

### Expected Behavior
Running `gradle resolveAndLockAll --write-locks` should create lockfiles and result in a succesful build.

### Current Behavior
Build fails. Full error can be seen [here](https://github.com/Toldry/jacoco-aggregation-lockfiles-bug-replicator#expected-output).

### Context

I am trying to use `JacocoReportAggregationPlugin` and lockfiles concurrently in my build.

### Steps to Reproduce 
Here is a reproducer. Instructions how to reproduce in the README:
https://github.com/Toldry/jacoco-aggregation-lockfiles-bug-replicator

### Your Environment

Gradle 7.5.1
macOS  Monterey Version 12.6.1

Build scan URL:
I am unable to provide a build scan.

**Comment by big-guy** [comment]
I suspect this is fixed in 8.0.

Could you give the latest nightly a try? https://gradle.org/nightly/
> ./gradlew wrapper --gradle-version=8.0-20221130035948+0000

**Comment by Toldry** [comment]
I ran:
```
gradle wrapper --gradle-version=8.0-20221130035948+0000
./gradlew resolveAndLockAll --write-locks 
```

and got this output:
```
Downloading https://services.gradle.org/distributions-snapshots/gradle-8.0-20221130035948+0000-bin.zip

Exception in thread "main" java.net.ConnectException: Network is unreachable (connect failed)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:288)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1572)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:100)
        at org.gradle.wrapper.Download.download(Download.java:80)
        at org.gradle.wrapper.Install$1.call(Install.java:83)
        at org.gradle.wrapper.Install$1.call(Install.java:63)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:63)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
```

which is strange because I am connected to the internet (that's how I'm posting this comment) and when I open [the URL](https://services.gradle.org/distributions-snapshots/gradle-8.0-20221130035948+0000-bin.zip) directly in the browser, it downloads the zip file without issue.

**Comment by Toldry** [comment]
Never mind, it _is_ a local network issue. I'll update once I resolve it.

**Comment by Toldry** [comment]
That worked. I ran:

```
gradle wrapper --gradle-version=8.0-20221130035948+0000
./gradlew rALA --write-locks
./gradlew build
```

and the build was succesful.

**Comment by big-guy** [comment]
Ah, great. Thanks for checking.
