### ISSUE TITLE
Sporadic NPEs when compiling Java code

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#22999]
NullPointerExceptions are thrown when compiling Java code _sometimes_. This seems to be a recent regression.

### Expected Behavior
Java compilation completes successfully.

### Current Behavior
Java compilation fails with an internal Gradle NPE error.

### Context
This seems to only happen if there is a listener for the build operation. This is the case when running from TAPI or when the build scan plugin is applied.

This is the stack trace reported by build scans:
```
Caused by: java.lang.NullPointerException: (No message provided)    
at org.gradle.api.internal.tasks.compile.tooling.JavaCompileTaskSuccessResultPostProcessor.findTaskOperationId(JavaCompileTaskSuccessResultPostProcessor.java:65)   
at org.gradle.api.internal.tasks.compile.tooling.JavaCompileTaskSuccessResultPostProcessor.findTaskOperationId(JavaCompileTaskSuccessResultPostProcessor.java:69)   
at org.gradle.api.internal.tasks.compile.tooling.JavaCompileTaskSuccessResultPostProcessor.finished(JavaCompileTaskSuccessResultPostProcessor.java:58)  
at org.gradle.tooling.internal.provider.runner.TaskOperationMapper$PostProcessors.finished(TaskOperationMapper.java:156)    
at org.gradle.tooling.internal.provider.runner.ClientBuildEventGenerator.finished(ClientBuildEventGenerator.java:106)   
at org.gradle.internal.operations.DefaultBuildOperationListenerManager$ProgressShieldingBuildOperationListener.finished(DefaultBuildOperationListenerManager.java:127)  
at org.gradle.internal.operations.DefaultBuildOperationListenerManager$1.finished(DefaultBuildOperationListenerManager.java:60) 
at org.gradle.internal.operations.DefaultBuildOperationExecutor$ListenerAdapter.stop(DefaultBuildOperationExecutor.java:214)    
at org.gradle.internal.operations.DefaultBuildOperationRunner$BuildOperationTrackingListener.stop(DefaultBuildOperationRunner.java:243) 
at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:73)    
at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)    
at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157) 
at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)  
at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53) 
at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73) 
at org.gradle.api.internal.tasks.compile.CompileJavaBuildOperationReportingCompiler.execute(CompileJavaBuildOperationReportingCompiler.java:51) 
at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:221)    
at org.gradle.api.tasks.compile.JavaCompile.performIncrementalCompilation(JavaCompile.java:162) 
at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:147)
```

However, this is stripping out the actual line of the NPE, which is in `java.util.concurrent.ConcurrentHashMap#get`. 

The underlying NPE occurs when `null` is passed as an `id` on this line:
https://github.com/gradle/gradle/blob/1c3ff71dee7ce26ee61e153ab31efa1f939d7d2a/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/tooling/JavaCompileTaskSuccessResultPostProcessor.java#L65

I was able to confirm that we get a similar stacktrace when I explicitly pass `null`:
https://ge.gradle.org/s/mdbxuyiimzrau/tests/:tooling-api:embeddedCrossVersionTest/org.gradle.integtests.tooling.r76.TestLauncherTestSpecCrossVersionSpec/can%20select%20test%20classes%20TAPI%20current%20-%3E%20Gradle%20current?expanded-stacktrace=WyIwLTEtMi0zIl0&focused-exception-line=0-1-2-3-0&top-execution=1

### Steps to Reproduce 

I believe the sequence is:
1. `finished` is called with a `CompileJavaBuildOperationType.Result` result.
2. We call `findTaskOperationId` with the parent of the result. This is non-null.
3. The `id` does not exist in `parentsOfOperationsWithJavaCompileTaskAncestor`.  parent is null.
4. We call `findTaskOperationId` with a null id. 
5. NPE is thrown in the `get(...)`.

I'm not sure if the parent never existed in `parentsOfOperationsWithJavaCompileTaskAncestor` or if it was removed. 

### Your Environment

There are more private build scans available.

**Comment by Sineaggi** [comment]
Is this issue the same issue? https://github.com/diffplug/spotless/issues/1087

**Comment by britter** [comment]
It looks like it's coming from the same code.

**Comment by big-guy** [comment]
@britter I think we've fixed this in 8.1

**Comment by Sineaggi** [comment]
Does `8.1-20230309020000+0000` contain this fix, or we have to wait for tonights snapshot?

**Comment by octylFractal** [comment]
It does not.

**Comment by Sineaggi** [comment]
We ran using `8.1-20230310013051+0000` and our builds are green (after yesterdays `8.1-20230309020000+0000` failed).

We were previously working around this issue by disabling parallel, but now our parallel builds succeed.
