### ISSUE TITLE
V7.5.1: java.io. FileNotFoundException

### ISSUE THREAD

**Issue by bodhili** [gradle/gradle#23098]
### Expected Behavior

- BUILD SUCCESSFUL 

### Current Behavior

`Downloading https://services.gradle.org/distributions-snapshots/gradle-7.5.1-20220727220835+0000-bin.zip

Exception in thread "main" java.io.FileNotFoundException: https://downloads.gradle-dn.com/distributions-snapshots/gradle-7.5.1-20220727220835+0000-bin.zip
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1920)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:100)
        at org.gradle.wrapper.Download.download(Download.java:80)
        at org.gradle.wrapper.Install$1.call(Install.java:83)
        at org.gradle.wrapper.Install$1.call(Install.java:63)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:63)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
`
### Steps to Reproduce 

- git branch 751 v7.5.1
- git checkout 751
- ./gradlew install -Pgradle_installPath=/any/path

### Your Environment

- os: mac Apple M1 Pro (version 12.2)
- java version: 11.0.17 
- IntelliJ IDEA 2022.1.4 (Community Edition)

Build scan URL:

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!
Sorry you're having trouble.

Your build is using a Gradle nightly.
Gradle nightlies are deleted periodically.
This is the intended behavior and there’s no plan to change it. This issue will be closed.

You should use released versions of Gradle.

**Comment by bodhili** [comment]
> Thank you for your interest in Gradle! Sorry you're having trouble.
> 
> Your build is using a Gradle nightly. Gradle nightlies are deleted periodically. This is the intended behavior and there’s no plan to change it. This issue will be closed.
> 
> You should use released versions of Gradle.

Hmm, that's my fault and I thought it was possible to assemble a gradle version from an arbitrary tag.   I’m sorry
