### ISSUE TITLE
Missing console output when TestNG fails to initialize test classes

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#23268]
### Expected Behavior

Console output should include the reasons for the failure.
For instance, if something fails in CI, there should be at least something besides "There were failing tests. See the report at: file:///.../build/reports/tests/test/index.html"

### Current Behavior

When TestNG initialization fails, Gradle output includes no clue on what has changed.

### Context

I'm using TestNG

### Steps to Reproduce 

```gradle
plugins {
    id("java-library")
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation("org.testng:testng:7.7.0")
}

tasks.test {
    useTestNG()
}
```

```java
package acme;

import org.testng.annotations.Test;

class SimpleTest {
  @Test(dependsOnGroups = {"prepare"})
  public void testA() {
    System.out.println("testA");
  }
}
```

Actual output:

```
% ./gradlew test --scan
> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///.../build/reports/tests/test/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 837ms
2 actionable tasks: 2 executed
```

### Your Environment
Gradle 7.6
TestNG 7.7

Build scan URL: https://scans.gradle.com/s/jp2xzx35da2ta

**Comment by xaviarias** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days, unless you can provide more information.

---

The provided test seems not to be possibly failing. Could you please provide a full reproducer? Thanks.

**Comment by vlsi** [comment]
@xaviarias , I'm afraid I provided all the needed files for reproducing the failure.

Here are the same files in form of a zip archive.

[issue-23268-tesng-missing-failure.zip](https://github.com/gradle/gradle/files/10294944/issue-23268-tesng-missing-failure.zip)

**Comment by vlsi** [comment]
Just in case: I **do expect** the test to fail since it `dependsOnGroups` on a non-existing group.
However, I expect that Gradle would report the failure reason appropriately in the console log.

**Comment by xaviarias** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before a fix is made.

---

Thank you @vlsi and apologies for my ignorance on Test NG, the issue makes totally sense.

**Comment by vlsi** [comment]
Here's a workaround:

```kotlin
tasks.test {
    useTestNG()

    afterSuite(
        KotlinClosure2<TestDescriptor, TestResult, Any>({ descriptor, result ->
            if (result.resultType == TestResult.ResultType.FAILURE) {
                result.exceptions.forEach {
                    val ex = if ((it.message ?: "").startsWith("Could not complete execution for")) {
                        it.cause ?: it
                    } else {
                        it
                    }
                    ex.printStackTrace()
                }
            }
        })
    )
}
```

=>

```
> Task :test FAILED
org.testng.TestNGException: 
DependencyMap::Method "SimpleTest.testA()[pri:0, instance:acme.SimpleTest@5d43661b]" depends on nonexistent group "prepare"
	at app//org.testng.DependencyMap.getMethodsThatBelongTo(DependencyMap.java:47)
	at app//org.testng.internal.DynamicGraphHelper.lambda$createDynamicGraph$2(DynamicGraphHelper.java:71)
	at java.base@11.0.13/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base@11.0.13/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base@11.0.13/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base@11.0.13/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base@11.0.13/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base@11.0.13/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base@11.0.13/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base@11.0.13/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base@11.0.13/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base@11.0.13/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base@11.0.13/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base@11.0.13/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base@11.0.13/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
	at app//org.testng.internal.DynamicGraphHelper.lambda$createDynamicGraph$3(DynamicGraphHelper.java:69)
	at java.base@11.0.13/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base@11.0.13/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at app//org.testng.internal.DynamicGraphHelper.createDynamicGraph(DynamicGraphHelper.java:38)
	at app//org.testng.TestRunner.lambda$privateRun$1(TestRunner.java:756)
	at app//org.testng.util.TimeUtils.computeAndShowTime(TimeUtils.java:45)
	at app//org.testng.TestRunner.privateRun(TestRunner.java:752)
	at app//org.testng.TestRunner.run(TestRunner.java:602)
	at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
	at app//org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
	at app//org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
	at app//org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at app//org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at app//org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at app//org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at app//org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at app//org.testng.TestNG.runSuites(TestNG.java:1099)
	at app//org.testng.TestNG.run(TestNG.java:1067)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:146)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:91)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.13/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.13/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///.../issue-23268-tesng-missing-failure/build/reports/tests/test/index.html
```
