### ISSUE TITLE
Delegated Properties (by settings) only works for String unless predefined

### ISSUE THREAD

**Issue by yschimke** [gradle/gradle#23349]
Delegated Properties (by settings) only works for String unless predefined.

Test https://github.com/gradle/gradle/blob/5ec3f672ed600a86280be490395d70b7bc634862/subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/DelegatedGradlePropertiesExtensionsTest.kt#L28

Presumable only works because the test provides 42 as a literal int.  If in gradle.properties it is only supported as a String.

### Expected Behavior

NonNullDynamicPropertyDelegate should covert to primitive types like boolean, int.

### Current Behavior

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')
	at Settings_gradle.getXyz(settings.gradle.kts)
	at Settings_gradle.<init>(settings.gradle.kts:18)
	at Program.execute(Unknown Source)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.eval(Interpreter.kt:532)
	at org.gradle.kotlin.dsl.execution.Interpreter.eval(Interpreter.kt:205)
```

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days, unless you can provide more information.

**Comment by yschimke** [comment]
Repro: https://github.com/yschimke/gradle-delegated-properties/tree/repro

Failure: https://github.com/yschimke/gradle-delegated-properties/actions/runs/3805965011/jobs/6474349552

**Comment by xaviarias** [comment]
Thank you for your interest in Gradle!

This is the intended behavior and there’s no plan to change it. This issue will be closed.

**Comment by yschimke** [comment]
Maybe worth updating documentation, from kotlin dsl and the examples it's seems like advertised functionality. So I was surprised it doesn't work.

**Comment by sschuberth** [comment]
> So I was surprised it doesn't work.

Same here! And with the "you can do the conversion in your script" argument you'd not need *any* convenience functions at all...
