### ISSUE TITLE
Shared Build Service can't have parameters of domain types

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#23539]
### Expected Behavior

Shared build service parameters should support managed domain objects.

### Current Behavior

```
Caused by: java.lang.NullPointerException
	at org.gradle.api.internal.provider.ManagedFactories$PropertyManagedFactory.fromState(ManagedFactories.java:70)
	at org.gradle.internal.snapshot.impl.IsolatedManagedValue.isolate(IsolatedManagedValue.java:42)
	at org.gradle.internal.snapshot.impl.IsolatedArray.isolate(IsolatedArray.java:52)
	at org.gradle.internal.snapshot.impl.IsolatedArray.isolate(IsolatedArray.java:26)
	at org.gradle.internal.snapshot.impl.IsolatedManagedValue.isolate(IsolatedManagedValue.java:42)
	at org.gradle.api.services.internal.BuildServiceProvider.instantiate(BuildServiceProvider.java:137)
	at org.gradle.api.services.internal.BuildServiceProvider.getInstance(BuildServiceProvider.java:128)
	at org.gradle.api.services.internal.BuildServiceProvider.calculateOwnValue(BuildServiceProvider.java:121)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:83)
```

I suspect the root cause is that `org.gradle.api.internal.provider.ManagedFactories` uses `type.isAssignableFrom(PUBLIC_TYPE)`, however, most likely the proper call is `PUBLIC_TYPE.isAssignableFrom(type)`.

### Context

I have trouble with moving Sigstore signing to a shared service.

### Steps to Reproduce 

```kotlin
abstract class Entity: Named
val entities = objects.domainObjectContainer(Entity::class)
val testEntity: Provider<Entity> by entities.registering

abstract class TestService: BuildService<TestService.Params> {
    interface Params: BuildServiceParameters {
        val entity: Property<Entity>
    }
}

val testService = gradle.sharedServices.registerIfAbsent("testService", TestService::class) {
    parameters {
        entity.set(testEntity)
    }
}

println("testService: ${testService.get()}")
```

See
<img width="1254" alt="breakpoint in ManagedFactories" src="https://user-images.githubusercontent.com/213894/212475959-b2c8b4fc-709c-44e9-898b-03965d623fbc.png">

### Your Environment

Gradle 7.6

**Comment by vlsi** [comment]
The workaround is to map `testEntity` provider.

In other words, this somehow works:

```kotlin
abstract class Entity: Named
val entities = objects.domainObjectContainer(Entity::class)
val testEntity: Provider<Entity> by entities.registering

abstract class TestService: BuildService<TestService.Params> {
    interface Params: BuildServiceParameters {
        val entity: Property<Entity>
    }
}

val testService = gradle.sharedServices.registerIfAbsent("testService", TestService::class) {
    parameters {
        entity.set(testEntity.map { it }) // map { it } fixes NPE
    }
}

println("testService: ${testService.get()}")

```

**Comment by ljacomet** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and prioritized by them.
