### ISSUE TITLE
Consider supporting assignment overload for ConfigurableFileCollection

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#23546]
Let's check out if it works already with Groovy. Even if we don't support `FileCollection = [File]`, we could consider adding it.

Let's consider supporting `+=` in Kotlin as well. Groovy already supports `FileCollection += FileCollection`.

---
cc: @gradle/bt-execution

**Comment by asodja** [comment]
Note that Groovy doesn't support `ConfigurableFileCollection = FileCollection` or `ConfigurableFileCollection += FileCollection`.  It throws:
```
Caused by: groovy.lang.GroovyRuntimeException: Cannot set the value of read-only property 'col' for task ':app2:myTask' of type MyTask.
        at org.gradle.internal.metaobject.AbstractDynamicObject.setReadOnlyProperty(AbstractDynamicObject.java:134)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.setProperty(BeanDynamicObject.java:372)
        at org.gradle.internal.metaobject.BeanDynamicObject.trySetProperty(BeanDynamicObject.java:181)
        at org.gradle.internal.metaobject.CompositeDynamicObject.trySetProperty(CompositeDynamicObject.java:66)
        at org.gradle.internal.metaobject.AbstractDynamicObject.setProperty(AbstractDynamicObject.java:74)
        at MyTask_Decorated.setProperty(Unknown Source)
```

**Comment by asodja** [comment]
Note: for `+=` there is a different issue now: https://github.com/gradle/gradle/issues/23637. This will be tackled later.
