### ISSUE TITLE
Expiring daemon: Overall build fails and stops

### ISSUE THREAD

**Issue by manoj7shekhawat** [gradle/gradle#2357]
Whiles running tests on Jenkins my builds stops abruptly in between tests some times due to below:

`Daemon registry /home/user/.gradle/daemon became unreadable. Expiring daemon.
Cannot nest operations in the same thread. Each nested operation must run in its own thread.
java.lang.UnsupportedOperationException: Cannot nest operations in the same thread. Each nested operation must run in its own thread.
	at org.gradle.internal.operations.DefaultBuildOperationWorkerRegistry.doStartOperation(DefaultBuildOperationWorkerRegistry.java:65)
	at org.gradle.internal.operations.DefaultBuildOperationWorkerRegistry.access$400(DefaultBuildOperationWorkerRegistry.java:30)
	at org.gradle.internal.operations.DefaultBuildOperationWorkerRegistry$DefaultOperation.operationStart(DefaultBuildOperationWorkerRegistry.java:163)
	at org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor.processTestClass(ForkingTestClassProcessor.java:68)
	at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.processTestClass(RestartEveryNTestClassProcessor.java:47)
	at sun.reflect.GeneratedMethodAccessor154.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:29)
	at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:132)
	at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:33)
	at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:72)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

### Expected Behavior

I suspect this relates to https://github.com/gradle/gradle/issues/897

I'm using gradle-3.2.1 wrapper.

I also see this in logs:
`Starting a Gradle Daemon, 1 busy and 1 stopped Daemons could not be reused, use --status for details`  
### Your Environment

 * Build scan URL:

**Comment by bmuschko** [comment]
It might be the same issue as https://github.com/gradle/gradle/issues/897. Can you please upgrade to at least version 3.3 that fixes the issue?
