### ISSUE TITLE
org.gradle.internal.io.ClassLoaderObjectInputStream class not found when running junit test with jmockit on mac

### ISSUE THREAD

**Issue by jim-gish-at-oracle-com** [gradle/gradle#2358]
Test receives the following error when running on a Mac, but works fine on all other OSs tested:
mockit.internal.ClassFile$NotFoundException: Unable to find class file for org.gradle.internal.io.ClassLoaderObjectInputStream
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
### Expected Behavior
Test should run w/o that exception :-)

### Current Behavior
see above

### Context
This bug started immediately upon upgrading to gradle 3.5 from 3.0

### Your Environment
Mac, jdk180121b13, jmockit 1.25, gradle 3.5

**Comment by oehme** [comment]
Looks like JMockit is inspecting things it shouldn't be touching. Could you provide a reproducible example please?

**Comment by jim-gish-at-oracle-com** [comment]
Here is a simple reproducer:
`
import java.io.InputStream;
import mockit.Capturing;
import mockit.Injectable;
import org.junit.Test;

public class TestNotFoundExceptionWithMockit {

  @Test // fails with "mockit.internal.ClassFile$NotFoundException: Unable to find class file for org.gradle.internal.io.ClassLoaderObjectInputStream"
  public void testFailsWithNotFoundException( @Capturing @Injectable final InputStream inputStream ) {
      // execution fails when doing gradle test --info (or --debug)
      // but passes without --info
  }
}
`

One interesting aspect of this failure is that it only occurs when invoking gradle with --info (or --debug), but works fine without it.  Also, the original test had other instances of @Capturing @Injectable, but it only gets NotFoundException for InputStream.

Here's the environment info:
gradle --version

------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Mac OS X 10.12.5 x86_64

It's using jmockit 1.25 and junit 4.11

**Comment by oehme** [comment]
Thank you for the example Jim. Could you please create a repo with a minimal Gradle project containing that code? I know it sounds pedantic, but with the large number of issues we get, every minute we save on reproducing makes a big difference.

**Comment by jim-gish-at-oracle-com** [comment]
Here is the reproducer with a project.
[gradleIssue2358.zip](https://github.com/gradle/gradle/files/1188812/gradleIssue2358.zip)

Thanks,
Jim

**Comment by jim-gish-at-oracle-com** [comment]
Any updates on this?  Thanks.

**Comment by oehme** [comment]
I debugged this a bit and it's an issue in JMockit: It instruments all classes loaded in the VM through an Agent and then assumes that all these classes are visible from the test class.

This is not the case for Gradle, as we have a filtering classloader in place which prevents Gradle's infrastructure (like test logging) to leak into the tests. 

JMockit should be more lenient here and ignore subtypes which the test can never reference anyway.

**Comment by oehme** [comment]
More specifically `CapturedType#isToBeCaptured` should check whether the current test class can actually see that subtype.

**Comment by jim-gish-at-oracle-com** [comment]
Thanks. I've filed jmockit bug: https://github.com/jmockit/jmockit1/issues/446
Feel free to comment if I've misquoted/misrepresented you there.

**Comment by rliesenfeld** [comment]
@oehme What do you mean with "whether the current test class can actually see that subtype"? Perhaps whether the subtype is defined by a class loader completelly unconnected (not the same and not having a common parent) with the one which defined the test class? Is that it?

**Comment by oehme** [comment]
I mean whether `MyTestClass.classloader.loadClass(theClass)` will succeed. JMockit tries to load Gradle infrastructure types, which cannot succeed, because they are filtered by our parent classloader.

**Comment by rliesenfeld** [comment]
I don't think that can be done from inside a call to `ClassFileTransformer#transform` method (implemented by `CaptureTransformer`), since the class hasn't been loaded by the JVM yet (the call to `transform` is so the class file transformer may transform its bytecode, or not).

**Comment by oehme** [comment]
As I pointed out above, I didn't say to put the check in `ClassFileTransformer`, but in `CapturedType#isToBeCaptured`. This takes a `Class` object. That means the class has already been loaded. All you need to do check is whether the test class' classloader can see a class of the same name.

**Comment by rliesenfeld** [comment]
Yes, that's true, for classes *already* loaded. There are also the calls to the `transform` method which happen just before the JVM loads each new class. I don't agree with the idea to check that already loaded classes are loadable with the test's class loader, but that's not needed; the problem has already been solved in a simpler way (JMockit now simply disregards everything under "org.gradle", as was already done for "org.junit", etc.).
