### ISSUE TITLE
`FileNotFoundException` when setting capital `RC` when using the `wrapper --gradle-version`

### ISSUE THREAD

**Issue by bric3** [gradle/gradle#23865]
The gradle `wrapper` task incorrectly accepts capitals like `RC` and this eventually results in an `FileNotFoundException`.

```shell
$ ./gradlew wrapper --gradle-version=8.0-RC-5
Configuration on demand is an incubating feature.
Type-safe project accessors is an incubating feature.

> Configure project :jmh-panama
Directory '/Users/brice.dutheil/opensource/jdk/build/macosx-x86_64-server-release/jdk' (system property 'org.gradle.java.installations.paths') used for java installations does not exist

BUILD SUCCESSFUL in 934ms
1 actionable task: 1 executed
```

However when running the first gradle command after results in a `FileNotFoundException`

```shell
$ ./gradlew wrapper --gradle-version=8.0-RC-5
Downloading https://services.gradle.org/distributions/gradle-8.0-RC-5-bin.zip

Exception in thread "main" java.io.FileNotFoundException: https://downloads.gradle-dn.com/distributions/gradle-8.0-RC-5-bin.zip
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1989)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1585)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:109)
        at org.gradle.wrapper.Download.download(Download.java:89)
        at org.gradle.wrapper.Install$1.call(Install.java:83)
        at org.gradle.wrapper.Install$1.call(Install.java:63)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:63)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:109)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:66)
```

Trying to fix that by `./gradlew wrapper --gradle-version=8.0-rc-5`, results in the same `FileNotFoundException`.
The workaround is easy by modifying manually the `gradle/wrapper/gradle-wrapper.properties` and change

```diff
- distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-RC-5-bin.zip
+ distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-rc-5-bin.zip
```

### Expected Behavior

I think there's several leads to fix that usability issue
* The wrapper task should either accept the capitals, but properly change the case of the letters.
* The wrapper task fails when passing capital letters.
* The server that host the gradle distribution could be case insensitive.

### Current Behavior

`FileNotFoundException` on each new gradle command.

### Context

Upgrading gradle from version 7.6.1 to 8.0 RC5

### Steps to Reproduce 

Listed above in the description.

### Your Environment

N/A

**Comment by eskatos** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.

----

The first time the wrapper task is run it should `HEAD` the resource to validate it is present and not update the wrapper properties file. In that case it could make suggestions.
