### ISSUE TITLE
Plugin [id: 'kotlin-dsl'] was not found in any of the following sources

### ISSUE THREAD

**Issue by ianbrandt** [gradle/gradle#23884]
### Expected Behavior
The Kotlin DSL plugin applies via `id("kotlin-dsl")`, as it would via `` `kotlin-dsl` ``.

### Current Behavior
Using `id("kotlin-dsl")`, or `id("org.gradle.kotlin.kotlin-dsl")`, results in:

```
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'kotlin-dsl'] was not found in any of the following sources:

- Gradle Core Plugins (not a core plugin, please see https://docs.gradle.org/8.0/userguide/plugin_reference.html for available core plugins)
- Included Builds (None of the included builds contain this plugin)
- Plugin Repositories (plugin dependency must include a version number for this source)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:237)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.lambda$resolvePluginRequests$3(DefaultPluginRequestApplicator.java:167)
	at org.gradle.util.internal.CollectionUtils.collect(CollectionUtils.java:212)
	at org.gradle.util.internal.CollectionUtils.collect(CollectionUtils.java:206)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolvePluginRequests(DefaultPluginRequestApplicator.java:165)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:100)
	at org.gradle.kotlin.dsl.provider.PluginRequestsHandler.handle(PluginRequestsHandler.kt:48)
	at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost.applyPluginsTo(KotlinScriptEvaluator.kt:202)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.applyPluginsTo(Interpreter.kt:405)
```

### Context
The [version 8 release notes](https://docs.gradle.org/8.0/release-notes.html#kotlin-dsl) say, "Gradle 8.0 introduces an interpreter for the declarative plugins {} blocks in .gradle.kts scripts that make the overall build time around 20% faster.", and, "...plugin specification type-safe accessors (e.g. ``plugins { `acme-plugin` })`` is not supported by the plugins {} block interpreter." I was able to replace all my other `` `plugin-id` `` references with `id("plugin-id")` okay, except for `` `kotlin-dsl` `` in my 'build-logic/build.gradle.kts'.

If the Kotlin DSL plugin is an exception for this performance improvement, it would be helpful for that to be clarified in the release notes and documentation.

### Steps to Reproduce 
1. Change  `` `kotlin-dsl` `` to `id("kotlin-dsl")`.

### Your Environment
Gradle 8.0

**Comment by madhead** [comment]
Isn't it a `org.gradle.kotlin.kotlin-dsl`. Plugin ID is not the same as a plugin name. I guess it is defined in the `kotlin-dsl-plugins` subproject.

https://github.com/gradle/gradle/blob/3ce0539b0f9b357d6794d5f8bddceb84490ffefa/subprojects/kotlin-dsl-plugins/build.gradle.kts#L73-L78

**Comment by ianbrandt** [comment]
I tried `id("org.gradle.kotlin.kotlin-dsl")`, but get the same result:

```
* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'org.gradle.kotlin.kotlin-dsl'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (None of the included builds contain this plugin)
- Plugin Repositories (plugin dependency must include a version number for this source)
```

Regarding bullet <span>#</span>1 there, I guess it's not considered a [core Gradle plugin](https://docs.gradle.org/current/userguide/plugin_reference.html).

The docs say, ["Avoid specifying a version for the kotlin-dsl plugin"](https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin), so bullet <span>#</span>3's version guidance doesn't seem like the right answer.

**Comment by TWiStErRob** [comment]
> Plugin ID is not the same as a plugin name.

I also tried `kotlin.kotlin-dsl` to mimic `java` for example, but same problem:
```
Plugin [id: 'kotlin.kotlin-dsl'] was not found in any of the following sources:
```

Yeah, Kotlin DSL plugins are special, compare with "real" core plugins:
```kotlin
inline val org.gradle.plugin.use.PluginDependenciesSpec.`java`: org.gradle.plugin.use.PluginDependencySpec
    get() = id("org.gradle.java")
```
```kotlin
val PluginDependenciesSpec.`kotlin-dsl`: PluginDependencySpec
    get() = id("org.gradle.kotlin.kotlin-dsl") version "4.0.6"
```
<details><summary>also noteworthy that <code>org.gradle.kotlin.kotlin-dsl</code> is not part of <code>gradle-api.8.0.jar</code></summary>

![image](https://user-images.githubusercontent.com/2906988/219678223-35e3c794-2b01-4ba0-9dea-0034037b6692.png)

</details>

---

That "avoid specifying" warning is there to prevent cases where someone specifies the version, but then when updating Gradle to the next version, the version mismatches and breaks the builds in unexpected ways.

https://github.com/gradle/gradle/blob/v8.0.0/subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPlugin.kt#L56-L65

I think this^ warning message should also be updated to allow specifying the version and only asking for updating the version to the Gradle X-compatible one.

**Comment by eskatos** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by rohandhruva** [comment]
I'm running into this issue -- is there a workaround that I can use?
