### ISSUE TITLE
providers.exec failures do not give the gradle line the failure occurred on

### ISSUE THREAD

**Issue by mcclure** [gradle/gradle#23902]
### Expected Behavior

On both Android Studio and command line gradle, if providers.exec is told to execute a nonexistent file or otherwise fails, it should show the line in build.gradle where the faulty providers.exec was called and stack trace in build.gradle of how it got called (the user code)

### Current Behavior

A stack trace is accessible by using --stacktrace or --full-stacktrace at the command line or by clicking the stacktrace link in the Android Studio problem description; however, the resulting stack trace is made up entirely of stacks internal to the build tooling, like:

net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)

From the user perspective it is not actionable to get stacks in Google-internal code.

### Context

On open source Android Mastodon client [Tusky](https://github.com/Tuskyapp/Tusky/) we use providers.exec in our build.gradle to invoke git and get a git hash to include as part of the version (an operation common to many projects). However sometimes the build is invoked on systems without command line git (say, Windows) and we want to support these users. After a code refactor, and due to [another apparent Android Studio/Gradle bug](https://issuetracker.google.com/issues/268961150), we started getting a sporadic but persistent "could not find git" failure in a place where this should have been "impossible". I lost a whole day to debugging this, and a major inhibitor was that I could not get the line number where the failure was occurring. This meant I was unsure whether the failure was on the providers.exec line (which, in the absence of Android Studio bug 268961150, "couldn't" fail), some other line in a different build.gradle I had not identified, or (in crazy world) a previous version of build.gradle which somehow was getting run instead of the one that appeared to be on disk. This meant a lot of time lost in unnecessary clean builds.

### Steps to Reproduce 

Check out this branch https://github.com/mcclure/Tusky/tree/providers-exec-gradle-bug (git df087bd) of Tusky. This is the code where I encountered the problem, BUT to demonstrate the problem better, build.gradle in this branch has been modded to call a nonexistent program named "gggiiittt".

Open in Android Studio and build variant blueDebug or greenDebug. On the first build this will succeed but on the second build and subsequent builds it will fail. (I apologize for this strange repro method, but I am inhibited by the aforementioned bug [268961150](https://issuetracker.google.com/issues/268961150) as well as bug [268596607](https://issuetracker.google.com/issues/268596607), both in the Android Studio tracker, from making a more straightforward repro.)

On the second build, you will get two build failures, "CreateProcess error=2, The system cannot find the file specified" and "Could not start 'gggiiittt'". The second failure will offer to give a stacktrace if you click the --stacktrace link. There is a screenshot of this in the first attachment below. All stack frames are inside Android build tooling, and the stack frame is not even complete.

It is possible to get a --full-stacktrace by bypassing Android Studio and doing this build in the gradle command line, for example by using "gradlew assembleGreenDebug". This is attached as the second attachment. However, the stacks are still rooted in org.gradle.internal, and not useful.

### Notes

This bug was initially filed on the Android Studio tracker as bug [269010527](https://issuetracker.google.com/issues/269010527). That bug was closed as "WONTFIX" and I was told to refile the bug on Gradle.

It is possible the other two Android-Studio-tracker bugs I mention above, [268961150](https://issuetracker.google.com/issues/268961150) and [268596607](https://issuetracker.google.com/issues/268596607), are also Gradle bugs rather than Android Studio bugs and should be refiled here. (I encountered all of these three bugs at the same time but they have different symptoms and probably different root causes.) If so please let me know. I have not received responses from Android Studio on those two bugs.

### Your Environment

```
Build: AI-221.6008.13.2211.9514443, 202301210135,

AI-221.6008.13.2211.9514443, JRE 11.0.15+0-b2043.56-9505619x64 JetBrains s.r.o., OS Windows 10(amd64) v10.0 , screens 1920.0x1080.0, 1024.0x600.0

AS: Electric Eel | 2022.1.1 Patch 1
Kotlin plugin: 221-1.8.0-release-for-android-studio-AS5591.52
Android Gradle Plugin: 7.4.1
Gradle: 7.6
Gradle JDK: JetBrains Runtime version 11.0.15
NDK: from local.properties: (not specified), latest from SDK: 21.0.6113669
CMake: from local.properties: (not specified), latest from SDK: 3.6.0-rc2, from PATH: (not found)
```

### Attachments/screenshots

![Sun Feb 12 2023 12_59_01 GMT-0500 (Eastern Standard Time)](https://user-images.githubusercontent.com/277318/218829644-c617a3e9-9e27-4cf7-a31d-b67ce2a426da.png)

![Sun Feb 12 2023 13_00_38 GMT-0500 (Eastern Standard Time)](https://user-images.githubusercontent.com/277318/218829658-61baead3-d506-4fd8-9f29-033168c20758.png)

**Comment by eskatos** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by mlopatkin** [comment]
I filed #23997 to track improvements to the rather unhelpful stack trace coming from the configuration cache. However, if you consider the stack traces coming from `exec` (not only providers, but of any kind), they all are lacking build script line numbers, e.g. for
```gradle
project.exec {
    commandLine "non-existent"
}
```

you get
```
* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project '2'.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.lambda$apply$0(DefaultScriptPluginFactory.java:135)
        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:79)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:138)
        at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:65)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
        at org.gradle.configuration.BuildOperationScriptPlugin.lambda$apply$0(BuildOperationScriptPlugin.java:62)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:44)
        at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:62)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.lambda$applyToMutableState$1(DefaultProjectStateRegistry.java:395)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.fromMutableState(DefaultProjectStateRegistry.java:413)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.applyToMutableState(DefaultProjectStateRegistry.java:394)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:46)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:27)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:35)

... Lots of Gradle internals in the stack trace removed for brewity ...

        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'non-existent''
        at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:241)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:218)
        at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:370)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:87)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        ... 5 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'non-existent'
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
        at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
        at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:98)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:71)
        ... 6 more
Caused by: java.io.IOException: Cannot run program "non-existent" (in directory "/tmp/test/2"): error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
        ... 9 more
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 11 more
```

I'd suggest repurposing this issue to track improvements in this area instead.
