### ISSUE TITLE
OutOfMemoryError when using GradleRunner to test task log output

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#23965]
I want to test a task using Gradle TestKit. However, the tests regularly fail with `java.lang.OutOfMemoryError: Java heap space` errors.

This error occurs even if `.forwardOutput()` is disabled.

I have created a minimal example task that works when run manually (albeit slowly!)

```kotlin
// build.gradle.kts

val foo by tasks.registering {
  doLast {
    repeat(Int.MAX_VALUE) {
      println("$it aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
    }
  }
}
```

However, when I create a GradleRunner project to run this task, the test fails.

```kotlin
val runner: GradleRunner = GradleRunner.create().withProjectDir(projectDir.toFile())

projectDir.resolve("build.gradle.kts").writeText(
  """
    val foo by tasks.registering {
      doLast {
        repeat(Int.MAX_VALUE) {
          println("${'$'}it aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
        }
      }
    }
  """.trimIndent()
)

val result = runner.withArguments("foo").build()
// ERROR: failed to execute tests
// Caused by: java.lang.OutOfMemoryError: Java heap space
```

### Expected Behavior

Gradle TestKit should not run out of memory when running tasks that produce a lot of log output.

The OOM error seems to be exacerbated by having multiple, independent GradleRunner tests. I expect that independent GradleRunner tests do not share the same memory, so a OOM in one test does not trigger a failure in others.

I can see that Gradle TestKit stores the logs into files in `build/tmp/test/work/.gradle-test-kit/test-kit-daemon/8.0.1`

![image](https://user-images.githubusercontent.com/897017/219940661-f2c376cb-1ca3-4f26-9364-4b2ce4b5ecf8.png)

I expect that if Gradle TestKit uses files to store the logs that the logs should not be stored in-memory.

### Current Behavior

```
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 1.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

### Context

I am writing tests for a Gradle Plugin which using the Worker API to run an external tool. I need to be able to get the output of the external tool so that on a test failure I can diagnose any problems. However, 

### Steps to Reproduce 

```kotlin
import java.nio.file.Files
import kotlin.io.path.writeText
import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class DemoTest {

  @Test
  fun `a test`() {
    val projectDir = Files.createTempDirectory("demo")

    val runner: GradleRunner = GradleRunner.create().withProjectDir(projectDir.toFile())

    projectDir.resolve("settings.gradle.kts").writeText(
      """
        rootProject.name = "a-test"
      """.trimIndent()
    )
    projectDir.resolve("build.gradle.kts").writeText(
      """
        val foo by tasks.registering {
          doLast {
            repeat(Int.MAX_VALUE) {
              println("${'$'}it aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
            }
          }
        }
      """.trimIndent()
    )

    val result = runner
      //.forwardOutput()
      .withArguments(
        "foo",
      ).build()

    assertTrue("SUCCESSFUL" in result.output)
  }
}
```

### Your Environment

* Windows 10
* Gradle 8.0.1

**Comment by eskatos** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before a fix is made.

----

This is caused by TestKit holding the output in memory for later assertions.
This could be fixed by e.g. spooling the output to disk.
One possibly hard to implement workaround would be to have the tested task write its output to a file instead.

**Comment by aSemy** [comment]
Thanks @eskatos 

> One possibly hard to implement workaround would be to have the tested task write its output to a file instead.

I have attempted this https://github.com/adamko-dev/dokkatoo/pull/13, but unfortunately I still get memory issues because the standard Gradle output is still quite noisy and I am running many tests.
