### ISSUE TITLE
Maven artifact referenced only in dependency constraints raises `IllegalStateException: Corrupt serialized resolution result`

### ISSUE THREAD

**Issue by alanv** [gradle/gradle#24037]
Initially found using Gradle 8.0 in the AndroidX repository, but we're seeing similar reports from external users on earlier Gradle versions.

### Expected Behavior
When an artifact is referenced only from Gradle metadata dependency constraints but never as a regular dependency, e.g. a task has a dependency tree where the artifact only appears with `(c)`, Gradle correctly resolves dependencies.

For example, `androidx.lifecycle:lifecycle-common-java8:2.6.0 (c)` shows up in:

```
./gradlew :compose:material3:material3:dependencies --no-configuration-cache --stacktrace

debugRuntimeClasspath - Runtime classpath of compilation 'debug' (target  (androidJvm)).

+--- project :compose:foundation:foundation
|    +--- androidx.compose.animation:animation:1.2.1
|    |    +--- androidx.compose.animation:animation-core:1.2.1 -> 1.3.1
|    |    |    +--- androidx.compose.ui:ui:1.2.0 -> project :compose:ui:ui
|    |    |    |    +--- project :compose:ui:ui-text
|    |    |    |    |    +--- androidx.core:core:1.7.0 -> 1.9.0
|    |    |    |    |    |    +--- androidx.lifecycle:lifecycle-runtime:2.3.1 -> 2.6.0
|    |    |    |    |    |    |    +--- androidx.lifecycle:lifecycle-common:2.6.0
|    |    |    |    |    |    |    |    +--- androidx.lifecycle:lifecycle-common-java8:2.6.0 (c)
```

### Current Behavior
Gradle fails to resolve dependencies unless the constraint-only artifact is added as a regular dependency.

```
./gradlew :compose:material3:material3:dependencies --no-configuration-cache --stacktrace

Caused by: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':compose:material3:material3:debugRuntimeClasspath'.
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.wrapException(ErrorHandlingConfigurationResolver.java:107)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolutionResult.getAllComponents(ErrorHandlingConfigurationResolver.java:248)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationResolvableDependencies$LenientResolutionResult.getAllComponents(DefaultConfiguration.java:2050)
        ...
Caused by: java.lang.RuntimeException: Problems reading data from Binary store in /usr/local/google/home/alanv/.gradle/.tmp/gradle7073241088892806121.bin offset 22066 exists? true
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:136)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.lambda$create$0(StreamingResolutionResultBuilder.java:190)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory$SimpleStore.load(CachedStoreFactory.java:101)
        ...
Caused by: java.lang.IllegalStateException: Corrupt serialized resolution result. Cannot find selected module (147) for constraint runtimeElements -> androidx.lifecycle:lifecycle-common-java8:2.6.0
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.DefaultResolutionResultBuilder.visitOutgoingEdges(DefaultResolutionResultBuilder.java:83)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.deserialize(StreamingResolutionResultBuilder.java:240)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:134)
        ... 242 more
```

### Context
Android Jetpack has started publishing dependency constraints to ensure that related artifacts are correctly versioned; however, this yields confusing errors when constrained artifacts are not present as regular dependencies.

Original bug report on Google Issue Tracker: https://issuetracker.google.com/issues/270635903

### Steps to Reproduce 
Generally, create artifact A that references artifact B as a constraint. Use artifact A as a dependency _without_ using artifact B.

Specifically, this can be reproduced in patch set #7 of https://android-review.git.corp.google.com/c/platform/frameworks/support/+/2449500/7 within the AndroidX repository.

I can work on a minimal repro ZIP if that would be more helpful.

### Your Environment
Gradle version: 8.0
Build scan URL: https://ge.androidx.dev/s/cob7tgpyntvik

**Comment by alanv** [comment]
Note that we're also seeing `Corrupt serialized resolution result.` for constraints that reference artifacts that simply have not been published, e.g. cannot be resolved at all even if they were regular dependencies.

The [linked issue](https://github.com/google/accompanist/pull/1523) above, however, is failing with:

```
Caused by: java.lang.IllegalStateException: Corrupt serialized resolution result. Cannot find selected module (222) for releaseVariantReleaseRuntimePublication -> androidx.lifecycle:lifecycle-runtime-ktx:2.6.0-beta01
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.DefaultResolutionResultBuilder.visitOutgoingEdges(DefaultResolutionResultBuilder.java:83)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.deserialize(StreamingResolutionResultBuilder.java:240)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:130)
	... 165 more
```

Where `lifecycle-runtime-ktx:2.6.0-beta01` is a [published artifact](https://maven.google.com/web/index.html#androidx.lifecycle:lifecycle-runtime-ktx:2.6.0-beta01) that's available on Google Maven but is only referenced as a constraint and not a regular dependency.

**Comment by mathjeff** [comment]
Simpler repro case: https://github.com/mathjeff/gradle-samples/tree/master/problem-reading-binary-store

**Comment by mathjeff** [comment]
Thanks!

AndroidX is also working on removing duplicate constraints ( https://issuetracker.google.com/274465172 ) and looking into moving each group of constraints into a platform ( https://issuetracker.google.com/274797108 )
