### ISSUE TITLE
Allow expensive operations during task scheduling

### ISSUE THREAD

**Issue by rkrisztian** [gradle/gradle#2406]
Calling `FileCollection.getSingleFile` inside a method annotated with `OutputFiles` can cause a `ResourceDeadlockException` in Gradle 4.0. This was not the case with Gradle 3.4.1.

### Expected Behavior
The example below should just build successfully.

### Current Behavior
The example below throws a `ResourceDeadlockException`:

```
java.lang.IllegalStateException: A deadlock was detected while resolving the task outputs for :myTestTask.  This can be caused, for instance, by a task output causing dependency resolution.
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.getOutputPaths(DefaultTaskExecutionPlan.java:774)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.recordTaskStarted(DefaultTaskExecutionPlan.java:802)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.access$2700(DefaultTaskExecutionPlan.java:91)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan$9.transform(DefaultTaskExecutionPlan.java:588)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan$9.transform(DefaultTaskExecutionPlan.java:577)
        at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:46)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.selectNextTask(DefaultTaskExecutionPlan.java:577)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.access$2300(DefaultTaskExecutionPlan.java:91)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan$8.transform(DefaultTaskExecutionPlan.java:551)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan$8.transform(DefaultTaskExecutionPlan.java:532)
        at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:46)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:532)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:96)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.internal.resources.ResourceDeadlockException: An attempt was made to execute build operations inside of a resource lock transform.  Aborting to avoid a deadlock.
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.failIfInResourceLockTransform(DefaultBuildOperationExecutor.java:217)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:461)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:437)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1600(DefaultConfiguration.java:114)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getSelectedArtifacts(DefaultConfiguration.java:850)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:838)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(DefaultConfiguration.java:382)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
        at org.gradle.api.internal.file.AbstractFileCollection.getSingleFile(AbstractFileCollection.java:57)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getSingleFile(Unknown Source)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:228)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:171)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryGetProperty(CompositeDynamicObject.java:55)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:59)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getProperty(Unknown Source)
        at MyTestTask.getMyOutputs(/home/rkrisztian/projects/myTest/build.gradle:22)
        at MyTestTask_Decorated.getMyOutputs(Unknown Source)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.TaskPropertyInfo$4.create(TaskPropertyInfo.java:99)
        at org.gradle.util.SingleMessageLogger.whileDisabled(SingleMessageLogger.java:217)
        at org.gradle.api.internal.project.taskfactory.TaskPropertyInfo.getValue(TaskPropertyInfo.java:97)
        at org.gradle.api.internal.project.taskfactory.TaskClassValidator$FutureValue.call(TaskClassValidator.java:65)
        at org.gradle.util.GUtil.uncheckedCall(GUtil.java:402)
        at org.gradle.util.GFileUtils.unpack(GFileUtils.java:187)
        at org.gradle.api.internal.tasks.CompositeTaskOutputPropertySpec.resolveToOutputProperties(CompositeTaskOutputPropertySpec.java:49)
        at org.gradle.api.internal.tasks.DefaultTaskOutputs$5.apply(DefaultTaskOutputs.java:194)
        at org.gradle.api.internal.tasks.DefaultTaskOutputs$5.apply(DefaultTaskOutputs.java:190)
        at com.google.common.collect.Iterators$8.transform(Iterators.java:794)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
        at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
        at org.gradle.api.internal.tasks.TaskPropertyUtils.collectFileProperties(TaskPropertyUtils.java:34)
        at org.gradle.api.internal.tasks.DefaultTaskOutputs.getFileProperties(DefaultTaskOutputs.java:200)
        at org.gradle.api.internal.tasks.DefaultTaskOutputs$TaskOutputUnionFileCollection.visitContents(DefaultTaskOutputs.java:277)
        at org.gradle.api.internal.file.CompositeFileCollection.getSourceCollections(CompositeFileCollection.java:171)
        at org.gradle.api.internal.file.CompositeFileCollection.getFiles(CompositeFileCollection.java:55)
        at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:68)
        at com.google.common.collect.Iterables$8.iterator(Iterables.java:713)
        at com.google.common.collect.Sets.newHashSet(Sets.java:219)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.canonicalizedPaths(DefaultTaskExecutionPlan.java:696)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.getOutputPaths(DefaultTaskExecutionPlan.java:772)
        ... 15 more

```

### Context
The example below was fabricated to provide a minimalistic way to reproduce the bug. In a real use case we define the output files based on the home directory of a zip installer, the path of which is taken from project dependency configuration.

### Steps to Reproduce (for bugs)
I created a new Gradle project with IDEA, and then edited `build.gradle` like this:

```
group 'myTest'
version '1.0-SNAPSHOT'

task wrapper(type: Wrapper) {
  gradleVersion = '4.0'
  distributionUrl = "https://services.gradle.org/distributions/gradle-$gradleVersion-all.zip"
}

apply plugin: 'groovy'

repositories {
    mavenCentral()
}
dependencies {
    compile 'org.codehaus.groovy:groovy-all:2.4.11'
}

class MyTestTask extends DefaultTask {
    @OutputFiles
    List<File> getMyOutputs() {
        project.configurations.findByName('compile').singleFile
        []
    }

    @TaskAction
    void printHello() {
        println 'Hello!'
    }
}

task myTestTask(type: MyTestTask) {
}
```

### Your Environment
Linux (RHEL6). Not sending a build scan because I think the example should just work everywhere. Let me know if not.

**Comment by rkrisztian** [comment]
Note: `getAt` also triggers a visit with build operations.

**Comment by oehme** [comment]
Output files should only be files that the task *creates*. In this regard, using a `Configuration` as an output does not make sense, because the task does not create any of those files. They are resolved/downloaded by the dependency resolution engine.

**Comment by oehme** [comment]
> we define the output files based on the home directory of a zip installer, the path of which is taken from project dependency configuration.

I don't understand this use case, why does that path come from a `Configuration`? Could you create a more realistic example to explain the use case?

**Comment by high-stakes** [comment]
@oehme, the configuration (input file) is not used as an output but it is used to determine what is the output directory.
In our use-case: we have a wildfly plugin which takes the wildfly zip as an input and extracts it -> this is the input file. Then we have wildfly configurations which needs to be placed into the extracted directory -> these are the output files. They depend on the input to determine the output files location.

**Comment by oehme** [comment]
> They depend on the input to determine the output files location.

Could you elaborate why they depend on the input file? It seems that this could be solved by having a single `@OutputDirectory` into which the zip is extracted. That directory can be independent from what the name of the input file is.

**Comment by oehme** [comment]
To give you some more context: Output files are analyzed during task scheduling, a highly time-critical code path. Doing any kind of expensive work there can significantly slow down Gradle. Resolving dependencies is a rather costly operation, which is why we forbid it at that time. If this disables an important use case then we can reconsider that of course. I just need to understand it better first.

**Comment by high-stakes** [comment]
@oehme , yes this could work as a workaround (if we made input and output static). 

The question is though, should Gradle not allow outputs to depend on inputs in general? Think of a more dynamic context: I want to for example split up a .properties file into X number of environment dependent .properties files that are defined in the input file. I need to read the file and act based on the contents. 
I understand this can be an impact on performance (you have to manage concurrency), but it could be explicitly defined.

**Comment by oehme** [comment]
> I want to for example split up a .properties file into X number of environment dependent .properties files that are defined in the input file. I need to read the file and act based on the contents.

For this kind of use case we generally recommend a single `@OutputDirectory`. Otherwise you'll end up doing a lot of the task's work inside the scheduling loop, which means that nothing else can be scheduled/run in parallel in the meantime.

**Comment by oehme** [comment]
I've rephrased this issue a bit. There are ways we can allow this, but we haven't seen a use case yet that would make us prioritize that work. The use cases so far were better served by using `@OutputDirectory`.
