### ISSUE TITLE
`GenerateMavenPom` seems to be incompatible with CC in Gradle 8.0

### ISSUE THREAD

**Issue by Goooler** [gradle/gradle#24097]
- Context: https://github.com/gradle/gradle/issues/21926#issuecomment-1450345200
- Reproducer: https://github.com/Goooler/shadow/pull/15

```
* What went wrong:
Configuration cache problems found in this build.

1 problem was found storing the configuration cache.
- Task `:generatePomFileForTestPublication` of type `org.gradle.api.publish.maven.tasks.GenerateMavenPom`: cannot serialize object of type 'org.gradle.api.internal.artifacts.DefaultDependencySet', a subtype of 'org.gradle.api.artifacts.DependencySet', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.0.1/userguide/configuration_cache.html#config_cache:requirements:disallowed_types

See the complete report at file:///home/circleci/shadow/build/reports/configuration-cache/63a4xikguon0pcj98808joey4/4hkeu1c3zn8rz20v6jxnhzicn/configuration-cache-report.html

* Try:
> Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.configurationcache.ConfigurationCacheProblemsException: Configuration cache problems found in this build.

1 problem was found storing the configuration cache.
- Task `:generatePomFileForTestPublication` of type `org.gradle.api.publish.maven.tasks.GenerateMavenPom`: cannot serialize object of type 'org.gradle.api.internal.artifacts.DefaultDependencySet', a subtype of 'org.gradle.api.artifacts.DependencySet', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.0.1/userguide/configuration_cache.html#config_cache:requirements:disallowed_types

See the complete report at file:///home/circleci/shadow/build/reports/configuration-cache/63a4xikguon0pcj98808joey4/4hkeu1c3zn8rz20v6jxnhzicn/configuration-cache-report.html
	at org.gradle.configurationcache.problems.ConfigurationCacheProblems.report(ConfigurationCacheProblems.kt:161)
	at org.gradle.internal.buildtree.ProblemReportingBuildActionRunner.reportProblems(ProblemReportingBuildActionRunner.java:61)
	at org.gradle.internal.buildtree.ProblemReportingBuildActionRunner.run(ProblemReportingBuildActionRunner.java:52)
	at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:65)
	at org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run(FileSystemWatchingBuildActionRunner.java:140)
	at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:41)
	at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.lambda$execute$0(RootBuildLifecycleBuildActionExecutor.java:40)
	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:122)
	at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.execute(RootBuildLifecycleBuildActionExecutor.java:40)
	at org.gradle.internal.buildtree.DefaultBuildTreeContext.execute(DefaultBuildTreeContext.java:40)
	at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.lambda$execute$0(BuildTreeLifecycleBuildActionExecutor.java:65)
	at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:53)
	at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.execute(BuildTreeLifecycleBuildActionExecutor.java:65)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:61)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:57)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor.execute(RunAsBuildOperationBuildActionExecutor.java:57)
	at org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.lambda$execute$0(RunAsWorkerThreadBuildActionExecutor.java:36)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:249)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:109)
	at org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.execute(RunAsWorkerThreadBuildActionExecutor.java:36)
	at org.gradle.tooling.internal.provider.continuous.ContinuousBuildActionExecutor.execute(ContinuousBuildActionExecutor.java:110)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecutor.execute(SubscribableBuildActionExecutor.java:64)
	at org.gradle.internal.session.DefaultBuildSessionContext.execute(DefaultBuildSessionContext.java:46)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter$ActionImpl.apply(BuildSessionLifecycleBuildActionExecuter.java:100)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter$ActionImpl.apply(BuildSessionLifecycleBuildActionExecuter.java:88)
	at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:69)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildActionExecuter.java:62)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildActionExecuter.java:41)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:63)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:50)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:38)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
	at org.gradle.util.internal.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:64)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
```

**Comment by abstratt** [comment]
@Goooler Thanks for the reproducer. I was indeed able to see the problem happening with that repository. However, I was unable to reproduce it with a simpler project that combined `maven-publish` and the `shadow`  plugins, which seems to be the trigger for the issue here.

Looking at the report though:

```

 1. ⌄ task:generatePomFileForTestPublication📋 of type org.gradle.api.publish.maven.tasks.GenerateMavenPom📋
      □ ⌄ fieldmavenPomSpec📋 of org.gradle.api.publish.maven.tasks.GenerateMavenPom📋
          ☆ ⌄ bean of type org.gradle.internal.serialization.Cached$Fixed📋
              ○ ⌄ fieldresult📋 of org.gradle.internal.serialization.Cached$Fixed📋
                  ■ ⌄ bean of type org.gradle.internal.Try$Success📋
                      ★ ⌄ fieldvalue📋 of org.gradle.internal.Try$Success📋
                          ◎ ⌄ bean of type org.gradle.api.publish.maven.internal.tasks.MavenPomFileGenerator$MavenPomSpec📋
                              ● ⌄ fieldxmlTransformer📋 of org.gradle.api.publish.maven.internal.tasks.MavenPomFileGenerator$MavenPomSpec📋
                                  △ ⌄ bean of type org.gradle.internal.xml.XmlTransformer📋
                                      • ⌄ fieldactions📋 of org.gradle.internal.xml.XmlTransformer📋
                                          □ ⌄ bean of type org.gradle.internal.MutableActionSet📋
                                          ☆ ⌄ fieldactions📋 of org.gradle.internal.MutableActionSet📋
                                          ○ ⌄ bean of type org.gradle.internal.ImmutableActionSet$SingletonSet📋
                                          ■ ⌄ fieldsingleAction📋 of org.gradle.internal.ImmutableActionSet$SingletonSet📋
                                          ★ ⌄ bean of type org.gradle.api.internal.UserCodeAction📋
                                          ◎ ⌄ fielddelegate📋 of org.gradle.api.internal.UserCodeAction📋
                                          ● ⌄ bean of type org.gradle.util.internal.ConfigureUtil$WrappedConfigureAction📋
                                          △ ⌄ fieldconfigureClosure📋 of org.gradle.util.internal.ConfigureUtil$WrappedConfigureAction📋
                                          • ⌄ bean of type com.github.jengelman.gradle.plugins.shadow.ShadowExtension$_component_closure2$_closure3📋
                                          □ ⌄ fieldallDependencies📋 of com.github.jengelman.gradle.plugins.shadow.ShadowExtension$_component_closure2$_closure3📋
                                          ☆ ⌄ bean of type groovy.lang.Reference📋
                                          ○ ⌄ fieldvalue📋 of groovy.lang.Reference📋
                                          ■ ■⚠️cannot serialize object of type org.gradle.api.internal.artifacts.DefaultDependencySet📋, a subtype of org.gradle.api.artifacts.DependencySet📋, as these are not supported with the configuration cache. ?

```

we can see that ShadowExtension is holding references to a dependency set, which is not supported by configuration cache.

**Comment by Goooler** [comment]
Yeah, but I wrapped it with `provider`, still can't work, see https://github.com/Goooler/shadow/pull/15#discussion_r1122215837.

**Comment by abstratt** [comment]
If you need to access data from dependency set at execution time, you need to collect the data you need as objects that do not reference CC-incompatible types (such as DepedencySet). Your provider still returns a dependency set.  

But it seems you actually want to mutate the dependency sets  - in order to do that, you would need to do that at configuration time, before the configuration cache is stored.

**Comment by Goooler** [comment]
You are right, thanks for your suggestions!

**Comment by Goooler** [comment]
You are right, thanks for your suggestions!

**Comment by Goooler** [comment]
I was addressing some fixes to https://github.com/johnrengelman/shadow/pull/835, can you take a look?
