### ISSUE TITLE
A way to set-up repository credentials withou breaking configuration cache

### ISSUE THREAD

**Issue by audkar** [gradle/gradle#24203]
### Expected Behavior

Configuration cache hit when setting repository credentials. 
Via Env variables
```
ORG_GRADLE_PROJECT_repoAuthHeaderName: "username"
ORG_GRADLE_PROJECT_repoAuthHeaderValue: "value"
```
or `gradle.properties`

### Current Behavior

Configuration cache can't be re-used:
```
Calculating task graph as configuration cache cannot be reused because the set of environment variables prefixed by 'ORG_GRADLE_PROJECT_' has changed.
``` 
or 
```
Calculating task graph as configuration cache cannot be reused because file '../../../.gradle/gradle.properties' has changed.
```

### Context

Our CI server generates a short-lived 'JOB_TOKEN' that is generated for each job to access Maven repositories. But setting Gradle's repository credential for each job makes configuration caches non-reusable between CI jobs. It would be nice to have a way to set the repository credential without breaking the configuration cache.

Repositories configured like this in `settings.gradle.kts`: 
```kotlin
dependencyResolutionManagement {
    repositories {
        <...>
        exclusiveContent {
            forRepository {
                maven {
                    name = "repo"
                    setUrl("<...>")
                    credentials(HttpHeaderCredentials::class)
                    authentication {
                        create<HttpHeaderAuthentication>("header")
                    }
                }
            }
            filter { includeGroup("some.group") }
        }
}
```

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed, response time may vary.

***
To CC team:
In our understanding, the reporter wants to reuse CC-entry while using different credentials for jobs.

**Comment by xenoterracide** [comment]
This is how GitHub works too... Makes me think that the credentials are still getting stuck and the configuration cache.

**Comment by duzinkie** [comment]
We face a similar problem with AWS CodeArtifact which doesn't allow credentials to last longer than 12h approx, so the longest we can get our configuration cache to stay valid is that. Being able to have those credentials change and now invalidate the cache would be great.

We currently have a daily setup script that stores all those temp creds in files, and then `settings.gradle` just reads those files, but I think we could easily adjust to use env variables/properties or whatever the options are.

**Comment by ixtli** [comment]
This is still really harming our ability to scale in a large, old monorepo because we use CodeArtifact and the token changes somewhat rapidly.

**Comment by mlopatkin** [comment]
Leaving some breadcrumbs for future me/someone else who looks into this. This doesn't guarantee that the issue will be solved soon, and doesn't really outline the fix we want, just some ideas.

As of commit 731f4f65d1a4e6c151b0b34ff8d45578571ad0e4 this is where we record gradle properties for automatically picked up credentials (`<reponame>Username`, `<reponame>Password` project properties):
<details>
<summary>Callstack</summary>

```
at org.gradle.internal.cc.impl.fingerprint.ConfigurationCacheFingerprintWriter.reportGradlePropertyInput(ConfigurationCacheFingerprintWriter.kt:1037)
at org.gradle.internal.cc.impl.fingerprint.ConfigurationCacheFingerprintWriter.reportGradlePropertyInput$default(ConfigurationCacheFingerprintWriter.kt:1032)
at org.gradle.internal.cc.impl.fingerprint.ConfigurationCacheFingerprintWriter.onGradlePropertyAccess(ConfigurationCacheFingerprintWriter.kt:1027)
at org.gradle.internal.cc.impl.fingerprint.ConfigurationCacheFingerprintEventHandler.onGradlePropertyAccess(ConfigurationCacheFingerprintEventHandler.kt:232)
at org.gradle.api.internal.properties.DefaultGradlePropertiesController$ScopedGradleProperties.onGradleProperty(DefaultGradlePropertiesController.java:170)
at org.gradle.api.internal.properties.DefaultGradlePropertiesController$ScopedGradleProperties.find(DefaultGradlePropertiesController.java:134)
at org.gradle.api.internal.provider.DefaultProviderFactory.lambda$gradleProperty$91b6a6df$1(DefaultProviderFactory.java:151)
at org.gradle.api.internal.provider.DefaultProviderFactory$$Lambda/0x0000007001822000.call(Unknown Source:-1)
at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:73)
at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:115)
at org.gradle.api.internal.provider.Providers$MemoizingProvider.calculateOwnValue(Providers.java:174)
at org.gradle.api.internal.provider.AbstractMinimalProvider.calculatePresence(AbstractMinimalProvider.java:95)
at org.gradle.api.internal.provider.AbstractMinimalProvider.isPresent(AbstractMinimalProvider.java:90)
at org.gradle.api.internal.provider.CredentialsProviderFactory$CredentialsProvider.getRequiredProperty(CredentialsProviderFactory.java:103)
at org.gradle.api.internal.provider.CredentialsProviderFactory$PasswordCredentialsProvider.call(CredentialsProviderFactory.java:145)
at org.gradle.api.internal.provider.CredentialsProviderFactory$PasswordCredentialsProvider.call(CredentialsProviderFactory.java:137)
at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:73)
at org.gradle.api.internal.provider.CredentialsProviderFactory$InterceptingProvider.calculateOwnValue(CredentialsProviderFactory.java:233)
at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:80)
at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:100)
at org.gradle.api.internal.provider.CredentialsProviderFactory.lambda$provide$3(CredentialsProviderFactory.java:79)
at org.gradle.api.internal.provider.CredentialsProviderFactory$$Lambda/0x0000007001921998.call(Unknown Source:-1)
at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:73)
at org.gradle.api.internal.provider.CredentialsProviderFactory$InterceptingProvider.calculateOwnValue(CredentialsProviderFactory.java:233)
at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:115)
at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:81)
at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:115)
at org.gradle.api.internal.provider.DefaultProperty.calculateValueFrom(DefaultProperty.java:158)
at org.gradle.api.internal.provider.DefaultProperty.calculateValueFrom(DefaultProperty.java:33)
at org.gradle.api.internal.provider.AbstractProperty.doCalculateValue(AbstractProperty.java:176)
at org.gradle.api.internal.provider.AbstractProperty.calculateOwnValue(AbstractProperty.java:169)
at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:80)
at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:100)
at org.gradle.api.internal.artifacts.repositories.AuthenticationSupporter.getConfiguredAuthentication(AuthenticationSupporter.java:123)
at org.gradle.api.internal.artifacts.repositories.AbstractAuthenticationSupportedRepository.getConfiguredAuthentication(AbstractAuthenticationSupportedRepository.java:107)
at org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository_Decorated.getConfiguredAuthentication(Unknown Source:-1)
at org.gradle.api.internal.artifacts.repositories.AbstractAuthenticationSupportedRepository.getAuthenticationSchemes(AbstractAuthenticationSupportedRepository.java:126)
at org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository_Decorated.getAuthenticationSchemes(Unknown Source:-1)
at org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.createDescriptor(DefaultMavenArtifactRepository.java:230)
at org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.createDescriptor(DefaultMavenArtifactRepository.java:83)
at org.gradle.api.internal.artifacts.repositories.AbstractResolutionAwareArtifactRepository.getDescriptor(AbstractResolutionAwareArtifactRepository.java:34)
at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationDetails$RepositoryImpl.lambda$transform$0(ResolveConfigurationResolutionBuildOperationDetails.java:164)
at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationDetails$RepositoryImpl$$Lambda/0x00000070017e1bc8.apply(Unknown Source:-1)
at org.gradle.util.internal.CollectionUtils.collect(CollectionUtils.java:191)
at org.gradle.util.internal.CollectionUtils.collect(CollectionUtils.java:183)
at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationDetails$RepositoryImpl.transform(ResolveConfigurationResolutionBuildOperationDetails.java:164)
at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationDetails.<init>(ResolveConfigurationResolutionBuildOperationDetails.java:63)
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$1.description(DefaultConfiguration.java:728)
at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:60)
at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:54)
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphInBuildOperation(DefaultConfiguration.java:667)
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.lambda$resolveExclusivelyIfRequired$0(DefaultConfiguration.java:659)
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$$Lambda/0x00000070017e0fc0.apply(Unknown Source:-1)
at org.gradle.api.internal.project.DefaultProjectState$CalculatedModelValueImpl.update(DefaultProjectState.java:350)
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveExclusivelyIfRequired(DefaultConfiguration.java:654)
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:647)
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ResolverResultsResolutionResultProvider.getValue(DefaultConfiguration.java:629)
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ResolverResultsResolutionResultProvider.getValue(DefaultConfiguration.java:615)
at org.gradle.api.internal.artifacts.configurations.ResolutionResultProvider$1.getValue(ResolutionResultProvider.java:54)
at org.gradle.api.internal.artifacts.configurations.ResolutionResultProviderBackedSelectedArtifactSet.visitArtifacts(ResolutionResultProviderBackedSelectedArtifactSet.java:50)
at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.SelectedArtifactSet.visitFiles(SelectedArtifactSet.java:34)
at org.gradle.api.internal.artifacts.configurations.ResolutionBackedFileCollection.visitContents(ResolutionBackedFileCollection.java:75)
at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:358)
at org.gradle.internal.serialize.codecs.core.CollectingVisitor.startVisit(FileCollectionCodec.kt:198)
at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:357)
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.visitContents(DefaultConfiguration.java:529)
at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:358)
at org.gradle.internal.serialize.codecs.core.FileCollectionCodec.encodeViaCollectingVisitor(FileCollectionCodec.kt:80)
at org.gradle.internal.serialize.codecs.core.FileCollectionCodec.encodeContents(FileCollectionCodec.kt:73)
at org.gradle.internal.serialize.codecs.core.FileCollectionCodec.encode(FileCollectionCodec.kt:62)
at org.gradle.internal.serialize.graph.codecs.BindingsBackedCodec.encode(BindingsBackedCodec.kt:66)
at org.gradle.internal.serialize.graph.BeanPropertyExtensionsKt.writePropertyValue(BeanPropertyExtensions.kt:34)
at org.gradle.internal.serialize.beans.services.BeanPropertyWriter.writeStateOf(BeanPropertyWriter.kt:54)
at org.gradle.internal.serialize.graph.codecs.BeanCodec.encode(BeanCodec.kt:34)
at org.gradle.internal.serialize.graph.CombinatorsKt$reentrant$1$encodeLoop$1.invokeSuspend(Combinators.kt:99)
at org.gradle.internal.serialize.codecs.core.FileCollectionCodec.encode(FileCollectionCodec.kt:54)
at org.gradle.internal.serialize.graph.DefaultWriteContext.write(Contexts.kt:111)
at org.gradle.internal.serialize.graph.DefaultWriteContext.write(Contexts.kt:110)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:30)
at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:41)
at org.gradle.internal.serialize.graph.CombinatorsKt$reentrant$1$encodeLoop$$inlined$Continuation$1.resumeWith(Combinators.kt:109)
at org.gradle.internal.serialize.graph.CombinatorsKt$reentrant$1$encodeLoop$$inlined$Continuation$1.resumeWith(Continuation.kt:71)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:47)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:30)
at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
at org.gradle.internal.serialize.graph.CombinatorsKt$reentrant$1.encodeLoop(Combinators.kt:101)
at org.gradle.internal.serialize.graph.CombinatorsKt$reentrant$1.encode(Combinators.kt:68)
at org.gradle.internal.serialize.graph.DefaultWriteContext.write(Contexts.kt:111)
at org.gradle.internal.serialize.graph.DefaultWriteContext.write(Contexts.kt:110)
at org.gradle.internal.serialize.codecs.core.TaskNodeCodec.access$writeCacheabilitySpecs(TaskNodeCodec.kt:73)
at org.gradle.internal.serialize.codecs.core.TaskNodeCodec$writeTask$3$2$1.invoke(TaskNodeCodec.kt:-1)
at org.gradle.internal.serialize.codecs.core.TaskNodeCodec$writeTask$3$2$1.invoke(TaskNodeCodec.kt:-1)
at org.gradle.internal.serialize.codecs.core.TaskNodeCodecKt.access$withTaskOf(TaskNodeCodec.kt:1)
at org.gradle.internal.serialize.codecs.core.TaskNodeCodec.encode(TaskNodeCodec.kt:79)
at org.gradle.internal.serialize.codecs.core.TaskNodeCodec.encode(TaskNodeCodec.kt:73)
at org.gradle.internal.serialize.graph.DefaultWriteContext.write(Contexts.kt:111)
at org.gradle.internal.serialize.graph.DefaultWriteContext.write(Contexts.kt:110)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$writeGroupedNodes$1$1$1.invoke(WorkNodeCodec.kt:-1)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$writeGroupedNodes$1$1$1.invoke(WorkNodeCodec.kt:-1)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$safeRunnerFor$2$1$1.invoke(WorkNodeCodec.kt:-1)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$safeRunnerFor$2$1$1.invoke(WorkNodeCodec.kt:-1)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:30)
at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
at org.gradle.internal.serialize.graph.RunningKt.runToCompletion(Running.kt:58)
at org.gradle.internal.serialize.graph.RunningKt.runWriteOperation(Running.kt:42)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$safeRunnerFor$2$1.accept(WorkNodeCodec.kt:399)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$safeRunnerFor$2$1.accept(WorkNodeCodec.kt:398)
at org.gradle.api.internal.project.DefaultProjectState.lambda$applyToMutableState$0(DefaultProjectState.java:241)
at org.gradle.api.internal.project.DefaultProjectState$$Lambda/0x00000070017008d8.apply(Unknown Source:-1)
at org.gradle.api.internal.project.DefaultProjectState.lambda$fromMutableState$0(DefaultProjectState.java:248)
at org.gradle.api.internal.project.DefaultProjectState$$Lambda/0x0000007001700b20.get(Unknown Source:-1)
at org.gradle.api.internal.project.DefaultProjectState$$Lambda/0x00000070016fada0.create(Unknown Source:-1)
at org.gradle.internal.work.DefaultWorkerLeaseService.lambda$runAndReleaseLocks$0(DefaultWorkerLeaseService.java:302)
at org.gradle.internal.work.DefaultWorkerLeaseService$$Lambda/0x000000700128d508.create(Unknown Source:-1)
at org.gradle.internal.work.ResourceLockStatistics$1.measure(ResourceLockStatistics.java:43)
at org.gradle.internal.work.DefaultWorkerLeaseService.runAndReleaseLocks(DefaultWorkerLeaseService.java:300)
at org.gradle.internal.work.DefaultWorkerLeaseService.withLocksAcquired(DefaultWorkerLeaseService.java:296)
at org.gradle.internal.work.DefaultWorkerLeaseService.lambda$withReplacedLocks$0(DefaultWorkerLeaseService.java:452)
at org.gradle.internal.work.DefaultWorkerLeaseService$$Lambda/0x00000070016f75c0.create(Unknown Source:-1)
at org.gradle.internal.work.DefaultWorkerLeaseService.withoutLocks(DefaultWorkerLeaseService.java:374)
at org.gradle.internal.work.DefaultWorkerLeaseService.withReplacedLocks(DefaultWorkerLeaseService.java:451)
at org.gradle.api.internal.project.DefaultProjectState.runWithModelLock(DefaultProjectState.java:276)
at org.gradle.api.internal.project.DefaultProjectState.fromMutableState(DefaultProjectState.java:248)
at org.gradle.api.internal.project.DefaultProjectState.applyToMutableState(DefaultProjectState.java:240)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$safeRunnerFor$2.invoke(WorkNodeCodec.kt:-1)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$safeRunnerFor$2.invoke(WorkNodeCodec.kt:-1)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$writeGroupedNodes$1.invoke(Unknown Source:-1)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$writeGroupedNodes$1.invoke(Unknown Source:-1)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:30)
at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
at org.gradle.internal.serialize.graph.RunningKt.runToCompletion(Running.kt:58)
at org.gradle.internal.serialize.graph.RunningKt.runWriteOperation(Running.kt:42)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec.writeGroupedNodes(WorkNodeCodec.kt:327)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec.writeNodeBatchesInParallel$lambda$1$0$0(WorkNodeCodec.kt:248)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec.writeNodeBatchesInParallel$lambda$1$0$0(AutoCloseableExtensions.kt:21)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec.writeNodeBatchesInParallel$lambda$1$0$0(AutoCloseableExtensions.kt:21)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec.writeNodeBatchesInParallel$lambda$1$0$0(WorkNodeCodec.kt:247)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$$Lambda/0x00000070019d2000.invoke(Unknown Source:-1)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$runBuildOperations$1$1.execute$lambda$1(WorkNodeCodec.kt:597)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$runBuildOperations$1$1.execute$lambda$1(_Collections.kt:2068)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$runBuildOperations$1$1.execute$lambda$1(WorkNodeCodec.kt:597)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$runBuildOperations$1$1$$Lambda/0x00000070019cb3d8.invoke(Unknown Source:-1)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodecKt$asBuildOperation$1.run(WorkNodeCodec.kt:640)
at org.gradle.internal.operations.DefaultBuildOperationExecutor$$Lambda/0x00000070019cfd48.execute(Unknown Source:-1)
at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:67)
at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:60)
at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:167)
at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:60)
at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$executeInParallel$0(DefaultBuildOperationExecutor.java:106)
at org.gradle.internal.operations.DefaultBuildOperationExecutor$$Lambda/0x00000070019d4408.execute(Unknown Source:-1)
at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runOperation(DefaultBuildOperationQueue.java:416)
at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.doRunBatch(DefaultBuildOperationQueue.java:407)
at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable$$Lambda/0x00000070019d6898.create(Unknown Source:-1)
at org.gradle.internal.operations.DefaultBuildOperationQueue.withProjectLockChangePolicy(DefaultBuildOperationQueue.java:209)
at org.gradle.internal.operations.DefaultBuildOperationQueue.access$900(DefaultBuildOperationQueue.java:38)
at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.executePendingWork(DefaultBuildOperationQueue.java:378)
at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable$$Lambda/0x00000070019d6250.create(Unknown Source:-1)
at org.gradle.internal.work.DefaultWorkerLeaseService.tryRunAsWorkerThread(DefaultWorkerLeaseService.java:145)
at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.lambda$runBatchWithLeaseRetry$0(DefaultBuildOperationQueue.java:353)
at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable$$Lambda/0x00000070019d5e00.run(Unknown Source:-1)
at org.gradle.internal.time.ExponentialBackoff.retryUntil(ExponentialBackoff.java:69)
at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runBatchWithLeaseRetry(DefaultBuildOperationQueue.java:352)
at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runBatch(DefaultBuildOperationQueue.java:338)
at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.lambda$runOperations$0(DefaultBuildOperationQueue.java:269)
at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable$$Lambda/0x00000070019d5788.run(Unknown Source:-1)
at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:84)
at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runOperations(DefaultBuildOperationQueue.java:266)
at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.access$000(DefaultBuildOperationQueue.java:245)
at org.gradle.internal.operations.DefaultBuildOperationQueue.waitForCompletion(DefaultBuildOperationQueue.java:146)
at org.gradle.internal.operations.DefaultBuildOperationExecutor.executeInParallel(DefaultBuildOperationExecutor.java:119)
at org.gradle.internal.operations.DefaultBuildOperationExecutor.runAllWithAccessToProjectState(DefaultBuildOperationExecutor.java:83)
at org.gradle.internal.operations.DefaultBuildOperationExecutor.runAllWithAccessToProjectState(DefaultBuildOperationExecutor.java:78)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec.runBuildOperations$lambda$0(WorkNodeCodec.kt:588)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$$Lambda/0x00000070019caf88.invoke(Unknown Source:-1)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec.handleBuildOperationExceptions(WorkNodeCodec.kt:286)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec.runBuildOperations(WorkNodeCodec.kt:587)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec.writeNodeBatchesInParallel(WorkNodeCodec.kt:243)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec.writeNodes(WorkNodeCodec.kt:209)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec.doWrite(WorkNodeCodec.kt:122)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec.writeWork(WorkNodeCodec.kt:94)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec.writeWork(IsolateContextExtensions.kt:31)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec.writeWork(Codec.kt:242)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec.writeWork(IsolateContextExtensions.kt:30)
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec.writeWork(WorkNodeCodec.kt:93)
at org.gradle.internal.cc.impl.ConfigurationCacheState.writeWorkGraphOf(ConfigurationCacheState.kt:567)
at org.gradle.internal.cc.impl.ConfigurationCacheState.writeWorkGraphOf(ConfigurationCacheState.kt:566)
at org.gradle.internal.cc.impl.ConfigurationCacheState.writeBuildState(ConfigurationCacheState.kt:366)
at org.gradle.internal.cc.impl.DefaultConfigurationCacheIO$writeRootBuildStateTo$1.invoke(DefaultConfigurationCacheIO.kt:-1)
at org.gradle.internal.cc.impl.DefaultConfigurationCacheIO$writeRootBuildStateTo$1.invoke(DefaultConfigurationCacheIO.kt:-1)
at org.gradle.internal.cc.impl.DefaultConfigurationCacheIO$writeConfigurationCacheStateWithSpecialEncoders$1.invoke(DefaultConfigurationCacheIO.kt:-1)
at org.gradle.internal.cc.impl.DefaultConfigurationCacheIO$writeConfigurationCacheStateWithSpecialEncoders$1.invoke(DefaultConfigurationCacheIO.kt:-1)
at org.gradle.internal.serialize.graph.CodecKt$writeWith$1$1.invoke(Codec.kt:-1)
at org.gradle.internal.serialize.graph.CodecKt$writeWith$1$1.invoke(Codec.kt:-1)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:30)
at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
at org.gradle.internal.serialize.graph.RunningKt.runToCompletion(Running.kt:58)
at org.gradle.internal.serialize.graph.RunningKt.runWriteOperation(Running.kt:42)
at org.gradle.internal.serialize.graph.CodecKt.writeWith(Codec.kt:83)
at org.gradle.internal.serialize.graph.CodecKt.writeWith(AutoCloseableExtensions.kt:21)
at org.gradle.internal.serialize.graph.CodecKt.writeWith(AutoCloseableExtensions.kt:21)
at org.gradle.internal.serialize.graph.CodecKt.writeWith(Codec.kt:82)
at org.gradle.internal.cc.impl.DefaultConfigurationCacheIO.withWriteContextFor(DefaultConfigurationCacheIO.kt:519)
at org.gradle.internal.cc.impl.DefaultConfigurationCacheIO.withWriteContextFor(DefaultConfigurationCacheIO.kt:518)
at org.gradle.internal.cc.impl.ConfigurationCacheBuildTreeIO.withWriteContextFor(ConfigurationCacheBuildTreeIO.kt:131)
at org.gradle.internal.cc.impl.DefaultConfigurationCacheIO.withWriteContextFor(DefaultConfigurationCacheIO.kt:100)
at org.gradle.internal.cc.impl.ConfigurationCacheBuildTreeIO.withWriteContextFor$default(ConfigurationCacheBuildTreeIO.kt:124)
at org.gradle.internal.cc.impl.DefaultConfigurationCacheIO.writeConfigurationCacheStateWithSpecialEncoders(DefaultConfigurationCacheIO.kt:366)
...<snip>...
```
</details>

The relevant buildscript is basically:
```kotlin
repositories {
    maven {
        name = "GitHubPackages"
        url = uri("...")
        credentials(PasswordCredentials::class)
    }
}
```

So when we're obtaining `PasswordCredentials` while storing/resolving the input configuration, we go through `providers.gradleProperty("GitHubPackagesUsername").get()`. We probably cannot or don't want to exempt `PasswordCredentials` from tracking, as these can be used outside of dependency resolution. That would be unsafe for build logic actually relying on the values. So we should handle exemption at a higher level.

**Comment by trevjonez** [comment]
Adding my situation and current workaround for SEO and usecase information to the Gradle team.

Current company policy is that all dependency downloads are to be ran through our private artifactory instance. Compound that detail with the secret policy requiring all GHA -> JFrog authentication to be handled via OIDC and we are left in a perpetual cache miss situation.

So the trivial setup is the same as previous commenters.
```kotlin
pluginManagement {
    repositories {
        maven {
            name = "companyJfrog"
            setUrl("https://company.jfrog.io/artifactory/company-maven/")
            credentials(org.gradle.api.credentials.PasswordCredentials::class)
        }
    }
}
```

Only workaround I have been able to figure out is to spin up a proxy at the start of my job and redirect Gradle through that so the creds don't end up in the Gradle config state.

```kotlin
pluginManagement {
    repositories {
        maven {
            name = "companyJfrog"
            val jfrogUrl = providers.gradleProperty("companyJfrogUrl")
                .getOrElse("https://company.jfrog.io/artifactory/company-maven/")
            setUrl(jfrogUrl)
            if (jfrogUrl.startsWith("http://127.0.0.1")) {
                isAllowInsecureProtocol = true
            } else {
                credentials(org.gradle.api.credentials.PasswordCredentials::class)
            }
        }
    }
}
```

Given how bad supply chains attacks have gotten combined with modern options for using short lived credentials I think this pattern of company policy isn't going to be rare and only become more common.

**Comment by xenoterracide** [comment]
Currently I feel like none of the job of products are taking security seriously with all of the supply chain attacks and now I'm looking at AI reading credential files because they are also storing other necessary things. Yeah let's just transmit all of our credentials over to AI instead of storing them securely in the OS keychain where they're actually encrypted.
