### ISSUE TITLE
Unable to add configurations with artifacts after archives configuration has been resolved

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#2435]
If a configuration with artifacts is added to a configuration container after the `archives` configuration has been resolved, the operation will fail with:

```
Caused by: org.gradle.api.InvalidUserDataException: Cannot change artifacts of configuration ':archives' after it has been resolved.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.validateMutation(DefaultConfiguration.java:745)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$2.execute(DefaultConfiguration.java:233)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$2.execute(DefaultConfiguration.java:230)
        at org.gradle.internal.ImmutableActionSet$SingletonSet.execute(ImmutableActionSet.java:155)
        at org.gradle.api.internal.DefaultDomainObjectCollection.assertMutable(DefaultDomainObjectCollection.java:320)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:197)
        at org.gradle.api.internal.DelegatingDomainObjectSet.add(DelegatingDomainObjectSet.java:82)
        at org.gradle.api.internal.plugins.DefaultArtifactPublicationSet.addCandidate(DefaultArtifactPublicationSet.java:49)
        at org.gradle.api.plugins.BasePlugin$3$1.execute(BasePlugin.java:167)
        at org.gradle.api.plugins.BasePlugin$3$1.execute(BasePlugin.java:165)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:136)
        at org.gradle.api.internal.DelegatingDomainObjectSet.all(DelegatingDomainObjectSet.java:50)
        at org.gradle.api.plugins.BasePlugin$3.execute(BasePlugin.java:165)
        at org.gradle.api.plugins.BasePlugin$3.execute(BasePlugin.java:163)
        at org.gradle.internal.ImmutableActionSet$SingletonSet.execute(ImmutableActionSet.java:155)
        at org.gradle.internal.MutableActionSet.execute(MutableActionSet.java:35)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:204)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:198)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.add(DefaultNamedDomainObjectCollection.java:93)
        at org.gradle.api.NamedDomainObjectCollection$add.call(Unknown Source)
        at build_21nf2vm9lly06eaiqf6pv9p6l$_run_closure2$_closure3.doCall(/private/tmp/reduced/build.gradle:15)
```

### Expected Behavior
Probably should not be fatal, given this is an implementation detail.

### Context
Yet another side-effect of using copied configurations for calculating version alignments.

### Steps to Reproduce (for bugs)
Run the `reproduce` task in the following build:
```
plugins {
	id 'java'
}

task myZip(type: Zip)

artifacts {
    runtime myZip
}

task reproduce() {
	doFirst {
		configurations.archives.resolve()
		def runtimeCopy = configurations.runtime.copy()
		configurations.add(runtimeCopy)
	}
}
```

### Your Environment
Gradle 4.0.0

**Comment by eriwen** [comment]
@melix @adammurdoch Would one of you be most appropriate to triage this regression?

**Comment by ljacomet** [comment]
@DanielThomas Is this still an issue? Or is it now obsolete?

**Comment by ljacomet** [comment]
Closing as obsolete
