### ISSUE TITLE
Cannot close gracefully standard input stream in Tooling API

### ISSUE THREAD

**Issue by HackerMadCat** [gradle/gradle#24369]
Gradle Tooling API doesn't close and doesn't give possibility to close a input stream which is provided into Gradle as standard input for execution `org.gradle.tooling.LongRunningOperation#setStandardInput`. It happens because Gradle starts an asynchornus reading in background executor and doesn't wait for it after `BuildLauncher.run`. Also, `DisconnectableInputStream` isn't closes the stream after reading.

On IDEA side we create [DiscardingInputStream](https://github.com/JetBrains/intellij-community/blob/master/platform/external-system-impl/src/com/intellij/openapi/externalSystem/util/DiscardingInputStream.kt) which tries to close the input stream without exception if `DisconnectableInputStream` is reading data from this stream.

Without our workaround we see an exception on every Gradle execution from IDEA, without any possibility to catch or ignore it.
```
Exception in thread "DisconnectableInputStream source reader" org.gradle.api.UncheckedIOException: java.nio.channels.AsynchronousCloseException
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:62)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
	at org.gradle.util.internal.DisconnectableInputStream$1.run(DisconnectableInputStream.java:127)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.nio.channels.AsynchronousCloseException
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at java.base/sun.nio.ch.SourceChannelImpl.endRead(SourceChannelImpl.java:263)
	at java.base/sun.nio.ch.SourceChannelImpl.read(SourceChannelImpl.java:285)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:59)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:107)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:101)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:282)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
	at org.gradle.util.internal.DisconnectableInputStream$1.run(DisconnectableInputStream.java:98)
	... 1 more
```

**Comment by donat** [comment]
This is something we wanted to fix for a long time, although we couldn't allocate any resources to it yet. You already implemented a reasonable workaround. Are there any additional reasons for us to prioritise the fix?
