### ISSUE TITLE
Communication between client and daemon is broken due to file encoding issues on s390x

### ISSUE THREAD

**Issue by Crosswind** [gradle/gradle#24498]
### Expected Behavior
When running a simple `gradle init` a daemon should start and I should be presented with the regular options when running init.

### Current Behavior
The client fails with a `GradleException: Could not start Gradle daemon.`
The stack trace that is produced with the --stacktrace option:
```
2023-03-24T18:42:08.145-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
2023-03-24T18:42:08.145-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2023-03-24T18:42:08.145-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
2023-03-24T18:42:08.145-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Could not start Gradle daemon.
2023-03-24T18:42:08.145-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2023-03-24T18:42:08.145-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
2023-03-24T18:42:08.145-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Run with --scan to get full insights.
2023-03-24T18:42:08.145-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2023-03-24T18:42:08.145-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
2023-03-24T18:42:08.145-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.GradleException: Could not start Gradle daemon.
2023-03-24T18:42:08.145-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startProcess(DefaultDaemonStarter.java:185)
2023-03-24T18:42:08.145-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startDaemon(DefaultDaemonStarter.java:137)
2023-03-24T18:42:08.145-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.doStartDaemon(DefaultDaemonConnector.java:222)
2023-03-24T18:42:08.145-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.startDaemon(DefaultDaemonConnector.java:216)
2023-03-24T18:42:08.145-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:164)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:99)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:57)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:167)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:259)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:230)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:82)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:30)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:96)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:40)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:44)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:361)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.Main.doAction(Main.java:35)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.lang.reflect.Method.invoke(Method.java:508)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.lang.reflect.Method.invoke(Method.java:508)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.GradleMain.main(GradleMain.java:34)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.api.UncheckedIOException: java.io.EOFException
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.bootstrap.DaemonStartupCommunication.readDiagnostics(DaemonStartupCommunication.java:87)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.client.DaemonGreeter.parseDaemonOutput(DaemonGreeter.java:43)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startProcess(DefaultDaemonStarter.java:181)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 31 more
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.io.EOFException
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.io.DataInputStream.readFully(DataInputStream.java:208)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.io.DataInputStream.readUTF(DataInputStream.java:618)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.io.DataInputStream.readUTF(DataInputStream.java:573)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.serialize.InputStreamBackedDecoder.readString(InputStreamBackedDecoder.java:59)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.bootstrap.DaemonStartupCommunication.readDiagnostics(DaemonStartupCommunication.java:84)
2023-03-24T18:42:08.146-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 33 more

```

I am new to Gradle development but I was able to configure a debug session to figure out what is happening. Let me try to explain:
1. Gradle client starts and spins up a second JVM to start the daemon process
2. Daemon starts up successfully and creates a log file under `~/.gradle/daemon/8.0.2`. The daemon is by default provided the argument -Dfile.encoding=IBM1047. IBM1047 refers to the standard USS encoding, more commonly known as EBCDIC.
3. The log file is written in EBCDIC (instead of ASCII or UTF-8). I can confirm this by cat'ing the file with cat -W filecodeset=IBM1047 <name-of-log-file>
4. At some point the content of the log file is transferred back to the client to acknowledge that it was started successfully and the previously written log file is appended. This happens here: [DaemonStartupCommunication.java](https://github.com/gradle/gradle/blob/master/subprojects/launcher/src/main/java/org/gradle/launcher/daemon/bootstrap/DaemonStartupCommunication.java#L58)
5. I digged into the OutputStream logic and found the 'culprit': [OutputStreamBackedEncoder.java ](https://github.com/gradle/gradle/blob/master/subprojects/messaging/src/main/java/org/gradle/internal/serialize/OutputStreamBackedEncoder.java#L51). .writeUTF() is used which interprets the content of the file as UTF-8 and doesn't care about the actual file encoding or even the one which was is set through the daemon startup arguments (-Dfile.encoding).
6. This leads to the client eventually receiving an EOFException because one of the characters in EBCDIC is interpreted in UTF-8 as an EOF. This very often happens, when text is interpreted incorrectly.

I was able to monitor the variable and I can see that a lot of garbage is printed. Working on the Mainframe and having to work with file encoding this is very common to me.
There are two ideas on how to potentially resolve this:
1. Make sure that writing the log file is also done in UTF-8 and don't honour the -Dfile.encoding variable at all. That way the process could later read the file in UTF-8: `result = new PrintStream(new FileOutputStream(daemonLog), true, "UTF-8")`
2. Change reading the file to honour the file encoding and not default to UTF-8

I tried changing the PrintStream to be UTF-8 which made the log file end up in UTF-8. However, the log is also written to STDOUT of the daemon which in term is read by the client and that for some reason still has encoding issues and I have no idea how change that.

The output variable in parseDaemonOutput looks like this:
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/4413512/227679686-9eeb29bb-76b5-4c0b-81ce-6873e30d22a9.png">
This is due to GFileUtils.tail() not caring about file encoding either. I assume that if this would also care about the file encoding it should get the output correctly from the file and have the rest of the logic interpret it correctly.

I am open to trying to fix this myself. It's probably going to need some time. I wanted to open this first to check whether I am looking at the right places or if anyone has more details if there are any specific strategies to cope with file encoding in Gradle. Especially, the .writeUTF() confuses me the most as everywhere else where things are read and written the default is just assumed.

### Context
I am trying to use Gradle on a Mainframe s390x to be able to build my Java applications on the system. The command is running in the so-called USS (Unix System Services) which is a POSIX compliant UNIX hosted inside the Mainframe operating system z/OS. If needed, I can go into way more detail on what that means.

### Your Environment
This might be special but I am running this on a Mainframe which is referred to as the s390x architecture. It runs an IBM J9 JVM:
```
/usr/lpp/java/J8.0_64/bin/java -version
java version "1.8.0_351"
Java(TM) SE Runtime Environment (build 8.0.7.20 - pmz6480sr7fp20-20221020_01(SR7 FP20))
IBM J9 VM (build 2.9, JRE 1.8.0 z/OS s390x-64-Bit Compressed References 20220929_37824 (JIT enabled, AOT enabled)
OpenJ9   - 02180fe
OMR      - 48fc32a
IBM      - bf759bf)
JCL - 20220922_01 based on Oracle jdk8u351-b10
```

Gradle generally runs, i.e., I can get the version:
```
gradle --version           

------------------------------------------------------------
Gradle 8.0.2
------------------------------------------------------------

Build time:   2023-03-03 16:41:37 UTC
Revision:     7d6581558e226a580d91d399f7dfb9e3095c2b1d

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_351 (IBM Corporation 2.9)
OS:           z/OS 02.04.00 s390x
```

**Comment by ov7a** [comment]
Thank you for providing a detailed report on that.

The issue is in the backlog of the relevant team but the existence of a workaround makes it non-critical so it might take a while before a fix is made.

****

If you are interested in contributing to Gradle, this issue is actionable and ready for contribution but might be challenging for first-time contributors.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

***

Looks like you got a system and environment to test that and found the culprit already. Would you be interested to open a PR with a fix to this issue?

**Comment by Crosswind** [comment]
Here is some more information on what is causing the issues: By default the JVM on the Mainframe runs in EBCDIC (IBM-1047) which will encode String variables in EBCDIC as well. This causes issues when writing the DaemonStartupMessage in printDaemonStarted(). daemonGreeting().getBytes() will return EBCDIC byte values for the message. The encoder which runs afterwards print UTF-8 content to the outputStream. This obviously doesn't work as we have two different encodings in one outputStream.

This can be worked around with by starting the client with -Dfile.encoding=UTF-8 which will also start the daemon JVM with the same encoding. Doing this the daemon is successfully started / the client can correctly read the StartupMessage.

Instead of changing anything about the Java code I have added a change to the Gradle startup script which will check if Gradle is running on s390x and in that case add the -Dfile.encoding to the JVM arguments. I have tried to test this as much as I could and couldn't find any issues. Obviously, this is not exactly unit-testable.

Let me know what you think / if this is acceptable. I hope I did all the steps required to contribute code back to Gradle.

**Comment by jbartok** [comment]
Unfortunately, were we to accept the PR, that would enforce `UTF-8` encoding for applications that might be relying on the default system encoding, thus breaking them.

One thing you could do is to use environment variables, like `GRADLE_OPTS` to set the encoding. 

Another thing that you could do is what we do for the `gradle/gradle` build, see [here](https://github.com/gradle/gradle/blob/49b08a784881331df351a4451d6e72cf454ad182/build-logic/build-update-utils/src/main/kotlin/gradlebuild.wrapper.gradle.kts#L9).

An alternative fix, via a PR, would be to enhance the wrapper task to add such a parameter via a task parameter, but at the moment we don't have the capacity to do that.

**Comment by jbartok** [comment]
The confusion comes from the fact that what you are changing doesn't just affect the wrapper scripts but also all the scripts generated for applications created via the application plugin.

**Comment by MarcBauer-LM** [comment]
We, from Living Mainframe, think that the solution mentioned by David is absolutely correct. Do you have customers of gradle on z/OS who disagree?
Please re-validate Davids PR?

**Comment by cietpfm** [comment]
One could argue that Gradle should not assume a particular file.encoding value.

**Comment by Crosswind** [comment]
I know it has been some time since the last update but I want to follow up on this.
First: @cietpfm It depends, really. Based on the current implementation there are cases where UTF-8 is implicitly assumed in the code because some methods write UTF-8 content by default.

Second: @jbartok I understand that my change affects all the scripts because it targets the gradle/gradlew files - at least syntactically. Semantically, it only changes something for people running on OS/390. OS/390 want that change. Just like AIX people apparently used (or uses?) strange locations for their Java.

However, there is case handling for cygwin, Darwin, MinGW, even NonStop already. This is exactly the same thing I am proposing to do. The OS/390 perfectly falls into the category of ["specific operating systems"](https://github.com/gradle/gradle/blob/bd217917be4797f41a1f25e847b600ebe7656b2a/platforms/jvm/plugins-application/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt#L56-L57). 

Why is it possible to implement a case for other operating systems but not OS/390? (Especially, since AIX is also from IBM and HP NonStop falls into the same category of computers compared to computers running OS/390, just a different vendor.)

In case, somebody requires a different encoding (which I think is impossible to want on a OS/390 system) they could use JAVA_OPTS or GRADLE_OPTS. I have had the time to try my proposed fix on multiple OS/390 systems and talked to different people and everyone agreed that UTF-8 is the correct encoding.

By now, we are not running on Java 8 anymore. I am running my tests against Java 11 and Java 17. The issue persists but is solvable with `-Dfile.encoding=UTF-8`. A fix remains relevant.

Let me know if I am missing something. I have seen that the unixStartScript.txt lives in a different directory today and also the syntax has slightly changed. I am always open to recreate my PR based on the current version of Gradle.
