### ISSUE TITLE
`NegativeArraySizeException` during progress rendering

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#24576]
Due to issues like #24370, it can happen that the done work is more than the total work.
If this is "over-enough", the calculation of the progress bar visualization causes a `NegativeArraySizeException`.
And this then causes the console output to hang completely with 8.0.2 as reported in #24575.

So as formula, currently as soon as `ceil((14 / 13 * totalWork) - totalWork)` work items too many are reported, the calculation will cause the `NegativeArraySizeException`. With total work of 1225 as in #24370 this makes for a buffer of 94 additional work items or 107.7 %. While investigating and reproducing the total work was reduced to 1, which then has a puffer of 0 and stalls the output as soon as one work item is repoted too much. And for a buffer of 1 additional work item without exception you need a total work amount of 14.

```plain
java.lang.NegativeArraySizeException: -52
	at org.gradle.internal.logging.console.ProgressBar.fill(ProgressBar.java:90)
	at org.gradle.internal.logging.console.ProgressBar.formatProgress(ProgressBar.java:76)
	at org.gradle.internal.logging.console.BuildStatusRenderer.renderNow(BuildStatusRenderer.java:122)
	at org.gradle.internal.logging.console.BuildStatusRenderer.onOutput(BuildStatusRenderer.java:114)
	at org.gradle.internal.logging.console.AbstractUserInputRenderer.onOutput(AbstractUserInputRenderer.java:56)
	at org.gradle.internal.logging.console.ThrottlingOutputEventListener.renderNow(ThrottlingOutputEventListener.java:95)
	at org.gradle.internal.logging.console.ThrottlingOutputEventListener.onOutput(ThrottlingOutputEventListener.java:72)
	at org.gradle.internal.logging.console.ThrottlingOutputEventListener$1.run(ThrottlingOutputEventListener.java:61)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ov7a** [comment]
Thank you for the detailed analysis of that.

The issue is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before a fix is made.
