### ISSUE TITLE
Print actionable error message when junit dependencies are not available

### ISSUE THREAD

**Issue by jvandort** [gradle/gradle#24678]
https://github.com/gradle/gradle/pull/24189 deprecates Gradle's automatic loading of `junit-platform-launcher` and `junit` dependencies from the Gradle distribution upon test execution. Instead, users who are not using test suites are expected to declare a dependency on `junit-platform-launcher` or `junit` manually. This is already the case for TestNG. 

For TestNG, if a user does not provide the dependency on the test runtime classpath manually, the following [error is printed](https://github.com/gradle/gradle/blob/109f5f8070c6c24272d803eef02b78062682df59/subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/ForkingTestClassProcessor.java#L158-L161):
```
This problem might be caused by incorrect test process configuration.
Please refer to the test execution section in the User Manual at https://docs.gradle.org/.../userguide/java_testing.html#sec:test_execution
```

Starting in 9.0, we should throw an exception with an actionable error message whenever a test worker is started without the proper test framework dependencies on the test runtime classpath. 

A proper solution would detect when missing TestNG, junit, or junit-platform test framework dependencies are missing from the test runtime classpath and would inform the user to add these dependencies by referencing the relevant documentation section.

**Comment by ljacomet** [comment]
@jvandort Can you please add labels to this issue?

**Comment by TWiStErRob** [comment]
+1 for this, I was about to report the same.

I got this deprecation:
> \> Task :feature:base:testDebugUnitTest
The automatic loading of test framework implementation dependencies has been deprecated. This is scheduled to be removed in Gradle 9.0. Declare the desired test framework directly on the test suite or explicitly declare the test framework implementation dependencies on the test's runtime classpath. Consult the upgrading guide for further information: https://docs.gradle.org/8.2-milestone-1/userguide/upgrading_version_8.html#test_framework_implementation_dependencies
> at org.gradle.api.internal.tasks.testing.detection.ForkedTestClasspathFactory.getClasspathWithAdditionalModules(ForkedTestClasspathFactory.java:130)
> at org.gradle.api.internal.tasks.testing.detection.ForkedTestClasspathFactory.create(ForkedTestClasspathFactory.java:113)

and I had no idea what to do.

Only after debugging Gradle internals I was able to very clearly see in memory what's missing:
![image](https://github.com/gradle/gradle/assets/2906988/5e92108b-dd24-4ee8-a50a-880f639f5708)

So please do this sooner, rather than later so users have an actionable deprecation warning.

Note: Android/AGP users cannot use test suites, so they'll have to go through the manual path. And with https://github.com/gradle/gradle/issues/25045, it's even more likely people will have to / opt to go for the manual path.

**Comment by apetrichkovich** [comment]
I've added all dependencies and removed `tasks.withType<Test> {
    useJUnitPlatform()
},` but still watching the warninig:
`testImplementation("org.junit:junit-bom:5.9.3")
testImplementation("org.junit.jupiter:junit-jupiter:5.9.3")
testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.10.0")`

> The automatic loading of test framework implementation dependencies has been deprecated. This is scheduled to be removed in Gradle 9.0. Declare the desired test framework directly on the test suite or explicitly declare the test framework implementation dependencies on the test's runtime classpath. Consult the upgrading guide for further information: https://docs.gradle.org/8.2.1/userguide/upgrading_version_8.html#test_framework_implementation_dependencies

**Comment by alejandrolorefice** [comment]
> I've added all dependencies and removed `tasks.withType<Test> { useJUnitPlatform() },` but still watching the warninig: `testImplementation("org.junit:junit-bom:5.9.3") testImplementation("org.junit.jupiter:junit-jupiter:5.9.3") testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.10.0")`
> 
> > The automatic loading of test framework implementation dependencies has been deprecated. This is scheduled to be removed in Gradle 9.0. Declare the desired test framework directly on the test suite or explicitly declare the test framework implementation dependencies on the test's runtime classpath. Consult the upgrading guide for further information: https://docs.gradle.org/8.2.1/userguide/upgrading_version_8.html#test_framework_implementation_dependencies

Yeah, cause the warning isn't about configuring your `Test` tasks to use `JUnitPlatform`, it's about doing so without explicitly defining your dependencies (TL;DR: you need to do both cause)

**Comment by AnrDaemon** [comment]
The message is still not useful at all.

```kt
plugins {
    id("java")
    id("application")
    id("jvm-test-suite")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit4 test framework
            useJUnit("4.13.2")

            dependencies {
                implementation("junit:junit:4.13.2")
                runtimeOnly("org.junit.vintage:junit-vintage-engine:5.8.2")
            }
        }
    }
}

tasks.test {
    useJUnitPlatform()
    testLogging {
        events("PASSED", "FAILED", "SKIPPED")
    }
}
```

The tests are running, but for the life of me I'm unable to deduce, what else it wants me to specify.

```
> Task :test
The automatic loading of test framework implementation dependencies has been deprecated. This is scheduled to be removed in Gradle 9.0. Declare the desired test framework directly on the test suite or explicitly declare the test framework implementation dependencies on the test's runtime classpath. 
Consult the upgrading guide for further information: https://docs.gradle.org/8.8/userguide/upgrading_version_8.html#test_framework_implementation_dependencies
```

Documentation talking at length about features, but giving exactly zero working example of a fully working configuration.
