### ISSUE TITLE
No owner attachment on `@Nested` properties marked as `final` coming from super class

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#24747]
### Expected Behavior

Gradle should correctly attach implicit task dependencies on nested output properties (provider) marked `final`. See context, for a reproducer.

### Current Behavior

Gradle fails to attach the owner on the `@Nested` property breaking the chain when providers try to find the producer task as the provider owner has no owner. The owner of the provider's owner should normally be the task. However, because the property on the super task is final, Gradle must not see the property; hence doesn't execute the owner attachment code in that very specific case.

### Context (optional)

Trying to write a generic, always worker-enabled task. The idea here is to provide an alternative to `DefaultTask` that my project can extend and get all the benefits of the worker API with minimal setup and configuration. The code is sound as it marks the `@Nested getParameters()` as final because no users should further overwrite the getter.

It's an understatement to say this issue is very sneaky and probably hit more people than reported. I spent well over two days debugging and reproducing the issue. I haven't narrowed it down further as to where in the Gradle codebase this issue is happening, but the best-educated guess is somewhere around the owner attachment (follow `OwnerAware`) and/or `@Nested` visitors (there are several, so most likely the one in the task properties discovery). In either case, the owner is not present after creating the `Parameters` instance in the constructor, so the attachment happens later.

### Steps to Reproduce

Suppose the following `build.gradle`:
```
interface Parameters {
	@OutputFile
	RegularFileProperty getOutputFile()
}

abstract class ParameterizedTask<P> extends DefaultTask {
	private final P params;

	protected ParameterizedTask(Class<P> paramType) {
		this.params = objects.newInstance(paramType)
	}

	@Nested
	final P getParameters() { // <1>
		return params
	}

	@Inject // private, do not use in subclasses
	protected abstract ObjectFactory getObjects()
}

abstract class MyTask extends ParameterizedTask<Parameters> {
	@Inject
	MyTask() {
		super(Parameters)
	}

	@TaskAction
	void doAction() {
		parameters.outputFile.get().asFile.text = 'kthxbye'
	}
}

abstract class VerifyTask extends DefaultTask {
	@InputFile
	abstract RegularFileProperty getInputFile()
}

def task = tasks.register('myTask', MyTask) {
	parameters.outputFile = file('out.txt')
}

tasks.register('verify', VerifyTask) {
	inputFile = task.flatMap { it.parameters.outputFile }
}
```

If you execute the verify task, it will fail with the following bottom stack trace:
```
Caused by: java.lang.IllegalStateException: Property 'outputFile' is declared as an output property of an object with type Parameters but does not have a task associated with it.
        at org.gradle.api.internal.provider.AbstractProperty.getProducerTask(AbstractProperty.java:278)
        at org.gradle.api.internal.provider.AbstractProperty.getProducer(AbstractProperty.java:174)
        at org.gradle.api.internal.provider.FlatMapProvider.getProducer(FlatMapProvider.java:77)
        at org.gradle.api.internal.provider.MappingProvider.getProducer(MappingProvider.java:58)
        at org.gradle.api.internal.provider.AbstractProperty.getProducer(AbstractProperty.java:178)
        at org.gradle.api.internal.file.collections.ProviderBackedFileCollection.visitDependencies(ProviderBackedFileCollection.java:50)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:103)
        at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmptyEdges.getNodeValues(CachingDirectedGraphWalker.java:213)
        at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:121)
        at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:73)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:66)
        ... 140 more
```

Commenting the `final` keyword mark by `<1>` will allow everything to work correctly. You can verify my claim by inspecting the `_gr_owner_` on the `parameters` property. Note this field is added by Gradle ASM generator but using Groovy, you can access it without issue.

### Gradle version

Most likely all Gradle are affected, feel free to try it out

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by mlopatkin** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but the existence of a workaround makes it non-critical, so it might take a while before a fix is made.
