### ISSUE TITLE
Kotlin DSL precompiled script plugins built with Gradle 8.1 cannot be used with earlier versions of Gradle

### ISSUE THREAD

**Issue by twarner-sofi** [gradle/gradle#24754]
### Issue type

Wrong or misleading information

### Problem description

The documentation claims "Kotlin DSL precompiled script plugins built with Gradle 6.0 cannot be used with earlier versions of Gradle." However, this is now true of 8.1 as well, so the documentation should be updated mention that. Release notes should also be changed to mention this breaking change, if that's possible.

### Context (optional)

Attempting to apply a kotlin script plugin built with 8.1 to a project using 8.0.2 gives the following error:

```
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin 'com.sofi.application'.
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:173)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:146)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.lambda$applyLegacyPlugin$2(DefaultPluginRequestApplicator.java:159)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:199)
	... 174 more
Caused by: java.lang.ClassCastException: class org.gradle.kotlin.dsl.precompile.v1.PrecompiledProjectScript$plugins$1 cannot be cast to class org.gradle.kotlin.dsl.PluginDependenciesSpecScope (org.gradle.kotlin.dsl.precompile.v1.PrecompiledProjectScript$plugins$1 and org.gradle.kotlin.dsl.PluginDependenciesSpecScope are in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @2b05039f)
	at Com_sofi_application_gradle$1.invoke(com.sofi.application.gradle.kts:6)
	at org.gradle.kotlin.dsl.precompile.v1.PrecompiledProjectScript.plugins(PrecompiledScriptTemplates.kt:182)
	at Com_sofi_application_gradle.<init>(com.sofi.application.gradle.kts:6)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at Com_sofi_applicationPlugin.apply(Com_sofi_applicationPlugin.kt:13)
	at Com_sofi_applicationPlugin.apply(Com_sofi_applicationPlugin.kt:6)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
	at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:187)
	at org.gradle.api.internal.plugins.DefaultPluginManager.access$100(DefaultPluginManager.java:52)
	at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:282)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
	at org.gradle.api.internal.plugins.DefaultPluginManager.lambda$doApply$0(DefaultPluginManager.java:167)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:44)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:166)
	... 177 more
```

### Page with the problem

https://docs.gradle.org/8.1/userguide/custom_plugins.html#sec:precompiled_plugins

**Comment by twarner-sofi** [comment]
Digging further into this, I found this only seems to apply to script plugins that apply the `java` plugin. Script plugins that do not, work fine.

That seems uninteded, so now this might be a bug instead of a documentation issue?

Reproducer: https://github.com/twarner-sofi/gradle-repro/tree/f930297765c5633ef1f29f7b6ed28d2626ad62fc

**Comment by eskatos** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by eskatos** [comment]
PR with the fix
* https://github.com/gradle/gradle/pull/24803

**Comment by eskatos** [comment]
Fix will ship in 8.1.1

**Comment by eygraber** [comment]
Is it expected that precompiled script plugins built with Gradle 8.1 won't work with projects that are using Gradle 8.1.1?

**Comment by eskatos** [comment]
@eygraber, unfortunately yes, 8.1 is broken in this regard, Kotlin DSL precompiled script plugins built with Gradle 8.1 cannot be used with any other versions of Gradle.
