### ISSUE TITLE
Nested BuildService Usages don't automatically get propagated with @ServiceReference 

### ISSUE THREAD

**Issue by mgroth0** [gradle/gradle#24780]
### Expected Behavior

Nested BuildServices should be supported automatically

### Current Behavior

From my testing, it seems nested BuildService usage is not suppoted. In other words, even if I use a `@ServiceReference`  inside OuterService in order to get `innerService`, a task that uses `OuterService`  still needs to manually call `usesService` on `InnerService` . Otherwise, using `enableFeaturePreview("STABLE_CONFIGURATION_CACHE")` I get an error:

```
Build service 'innerService' is being used by task ':myTask' without the corresponding declaration via 'Task#usesService'. This behavior has been deprecated. This will fail with an error in Gradle 9.0. Declare the association between the task and the build service using 'Task#usesService'. Consult the upgrading guide for further information: https://docs.gradle.org/8.1/userguide/upgrading_version_7.html#undeclared_build_service_usage
	at org.gradle.api.services.internal.BuildServiceProviderNagger.nagAboutUndeclaredUsageOf(BuildServiceProviderNagger.java:56)
	at org.gradle.api.services.internal.BuildServiceProviderNagger.lambda$beforeGet$0(BuildServiceProviderNagger.java:38)
```

### Steps to Reproduce

**settings.gradle.kts**
```kotlin
enableFeaturePreview("STABLE_CONFIGURATION_CACHE")
```

**build.gradle.kts**
```kotlin
abstract class MyTask: DefaultTask(){
	@get:ServiceReference(OuterService.NAME)
	abstract val outerService: Property<OuterService>
}

abstract class OuterService: BuildService<None> {
	@get:ServiceReference(InnerService.NAME)
	abstract val innerService: Property<InnerService>
}

abstract class InnerService: BuildService<None> {

}
```

### Gradle version

8.1

**Comment by abstratt** [comment]
That is a limitation that is also present when we use `Task#usesService()` - a task needs to explicitly declare it uses the services indirectly uses as well, or you will get that warning/error.

One (admittedly ugly) workaround may be to change the task so it also holds a reference to the service indirectly used.
