### ISSUE TITLE
Gradle 8.1 appears to eagerly inspect Kotlin lambdas and load classes that are otherwise conditionally used within them

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#24871]
### Expected Behavior

In our Gradle plugin, we have code like this

```kotlin
if (!multiplatform.get()) {
  // ...
} else {
  project.pluginManager.apply("org.jetbrains.compose")
  project.configure<ComposeExtension> {
    //...
  }
}
```

The expectation is that `ComposeExtension` is only used IFF the else block is entered at runtime. This is important because we may not have the plugin that provides this class available on the classpath in all projects, so we have some extra configuration available for it. When we compile with `class` for SAM conversions, this works as expected.

### Current Behavior

If we compile the plugin without `class` SAM conversions and use native kotlin lambdas (as is supported in Gradle 8.1), this no longer works because it appears that gradle inspects the lambda and attempts to load all classes referenced within it, even those conditionally referenced. This makes it more or less impossible to safely use kotlin lambdas because we expect conditional class usage to work.

### Steps to Reproduce

Use 0.8.5 of [this plugin](https://github.com/slackhq/slack-gradle-plugin) with [this project](https://github.com/zacsweers/catchup). The version catalog key to update is `sgp`. Repro PR: https://github.com/ZacSweers/CatchUp/pull/655

### Gradle version

8.1.1

**Comment by ZacSweers** [comment]
Here is the stacktrace of the failure

```
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin 'com.slack.gradle.base'.
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:173)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:137)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.lambda$applyPlugin$1(DefaultPluginRequestApplicator.java:148)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:199)
        ... 182 more
Caused by: org.gradle.api.reflect.ObjectInstantiationException: Could not create an instance of type slack.gradle.SlackExtension.
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:69)
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.newInstanceWithDisplayName(DependencyInjectingInstantiator.java:50)
        at org.gradle.internal.extensibility.DefaultConvention.instantiate(DefaultConvention.java:217)
        at org.gradle.internal.extensibility.DefaultConvention.create(DefaultConvention.java:126)
        at slack.gradle.StandardProjectConfigurations.applyJvmConfigurations(StandardProjectConfigurations.kt:173)
        at slack.gradle.StandardProjectConfigurations.applyTo(StandardProjectConfigurations.kt:112)
        at slack.gradle.SlackBasePlugin.apply(SlackBasePlugin.kt:45)
        at slack.gradle.SlackBasePlugin.apply(SlackBasePlugin.kt:38)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:187)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$100(DefaultPluginManager.java:52)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:282)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
        at org.gradle.api.internal.plugins.DefaultPluginManager.lambda$doApply$0(DefaultPluginManager.java:167)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:44)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:166)
        ... 185 more
Caused by: org.gradle.api.reflect.ObjectInstantiationException: Could not create an instance of type slack.gradle.FeaturesHandler.
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:69)
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:55)
        at org.gradle.api.internal.model.DefaultObjectFactory.newInstance(DefaultObjectFactory.java:89)
        at slack.gradle.SlackExtension.<init>(SlackExtension.kt:853)
        at slack.gradle.SlackExtension_Decorated.<init>(Unknown Source)
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
        at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:1993)
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:512)
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:64)
        ... 208 more
Caused by: org.gradle.api.reflect.ObjectInstantiationException: Could not create an instance of type slack.gradle.ComposeHandler.
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:69)
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:55)
        at org.gradle.api.internal.model.DefaultObjectFactory.newInstance(DefaultObjectFactory.java:89)
        at slack.gradle.FeaturesHandler.<init>(SlackExtension.kt:854)
        at slack.gradle.FeaturesHandler_Decorated.<init>(Unknown Source)
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
        at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:1993)
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:512)
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:64)
        ... 216 more
Caused by: org.gradle.internal.instantiation.ClassGenerationException: Could not generate a decorated class for type ComposeHandler.
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:247)
        at org.gradle.cache.internal.DefaultCrossBuildInMemoryCacheFactory$AbstractCrossBuildInMemoryCache.get(DefaultCrossBuildInMemoryCacheFactory.java:130)
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator.generate(AbstractClassGenerator.java:173)
        at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator.generate(AsmBackedClassGenerator.java:118)
        at org.gradle.internal.instantiation.generator.Jsr330ConstructorSelector.lambda$forType$0(Jsr330ConstructorSelector.java:56)
        at org.gradle.cache.Cache.lambda$get$0(Cache.java:31)
        at org.gradle.cache.internal.DefaultCrossBuildInMemoryCacheFactory$AbstractCrossBuildInMemoryCache.get(DefaultCrossBuildInMemoryCacheFactory.java:130)
        at org.gradle.cache.Cache.get(Cache.java:31)
        at org.gradle.internal.instantiation.generator.Jsr330ConstructorSelector.forType(Jsr330ConstructorSelector.java:53)
        at org.gradle.internal.instantiation.generator.Jsr330ConstructorSelector.forParams(Jsr330ConstructorSelector.java:48)
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:61)
        ... 224 more
Caused by: java.lang.NoClassDefFoundError: org/jetbrains/compose/ComposeExtension
        at org.gradle.internal.reflect.ClassInspector.inspectClass(ClassInspector.java:70)
        at org.gradle.internal.reflect.ClassInspector.visitGraph(ClassInspector.java:56)
        at org.gradle.internal.reflect.ClassInspector.inspect(ClassInspector.java:36)
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:276)
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:216)
        ... 234 more
Caused by: java.lang.ClassNotFoundException: org.jetbrains.compose.ComposeExtension
        at org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader.findClass(VisitableURLClassLoader.java:186)
        ... 239 more
```

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***

That's the way the JVM works.
Classes referenced by a lambda are immediately loaded when the enclosing class is loaded.
The only way to defer loading is by using a separate class.
