### ISSUE TITLE
Update bundled TestNG to a recent version

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#24930]
We should update TestNG to a more recent version in Gradle. `6.3.1` was released in 2011 and latest version at time of writing is `7.7.1`

Constraints:
* https://github.com/gradle/gradle/blob/cb195c7f59c9007b1efa00f1f2bb48808323bbb4/subprojects/distributions-dependencies/build.gradle.kts#L145
* #24062

**Comment by effad** [comment]
We're currently using gradle 7.3 and TestNG 7.7.0.
When trying to update gradle to 7.6.3 the build breaks:
```
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 2.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:64)
	at java.base@17.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.3/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.3/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: org.gradle.internal.reflect.NoSuchMethodException: Could not find method setConfigFailurePolicy(class org.testng.xml.XmlSuite$FailurePolicy) on TestNG.
	at org.gradle.internal.reflect.JavaMethod.findMethod(JavaMethod.java:86)
	at org.gradle.internal.reflect.JavaMethod.<init>(JavaMethod.java:63)
	at org.gradle.internal.reflect.JavaMethod.<init>(JavaMethod.java:67)
	at org.gradle.internal.reflect.JavaMethod.of(JavaMethod.java:36)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.invokeVerifiedMethod(TestNGTestClassProcessor.java:197)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:117)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:91)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	... 18 more
```

So as long as this issue is not tackled, we're stuck with 7.3 (which in turn is bad since we must upgrade gradle for another library).

**Comment by dlandis** [comment]
Would be great if this could be resolved at some point. `6.3.1` is showing up on various container security scan reports.
