### ISSUE TITLE
Config Cache support for serializing `java.lang.invoke.SerializedLambda`

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#24981]
### Expected Behavior

`java.lang.invoke.SerializedLambda` is built to be serializable, and config cache should handle it according to the docs. 

[From the JavaDoc](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/invoke/SerializedLambda.html): 
```
Serialized form of a lambda expression. The properties of this class represent the information that is present at the lambda factory site, including static metafactory arguments such as the identity of the primary functional interface method and the identity of the implementation method, as well as dynamic metafactory arguments such as values captured from the lexical scope at the time of lambda capture.
Implementors of serializable lambdas, such as compilers or language runtime libraries, are expected to ensure that instances deserialize properly. One means to do so is to ensure that the writeReplace method returns an instance of SerializedLambda, rather than allowing default serialization to proceed.

SerializedLambda has a readResolve method that looks for a (possibly private) static method called $deserializeLambda$(SerializedLambda) in the capturing class, invokes that with itself as the first argument, and returns the result. Lambda classes implementing $deserializeLambda$ are responsible for validating that the properties of the SerializedLambda are consistent with a lambda actually captured by that class.

The identity of a function object produced by deserializing the serialized form is unpredictable, and therefore identity-sensitive operations (such as reference equality, object locking, and System.identityHashCode() may produce different results in different implementations, or even upon different deserializations in the same implementation.
```

### Current Behavior (optional)

Gradle fails with variations of this error: 

See https://github.com/gradle/gradle/issues/22765#issuecomment-1346635528

```
   Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.Object[] java.lang.invoke.SerializedLambda.capturedArgs accessible: module java.base does not "opens java.lang.invoke" to unnamed module @4ca6ecad
    	at org.gradle.configurationcache.serialization.beans.BeanSchemaKt.makeAccessible(BeanSchema.kt:208)
    	at org.gradle.configurationcache.serialization.beans.BeanSchemaKt$relevantFieldsOf$2.invoke(BeanSchema.kt:59)
    	at org.gradle.configurationcache.serialization.beans.BeanSchemaKt$relevantFieldsOf$2.invoke(BeanSchema.kt:59)
    	at kotlin.sequences.SequencesKt___SequencesKt$onEach$1.invoke(_Sequences.kt:1978)
    	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
    	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
    	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
    	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
    	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
```

### Context

See discussion on https://github.com/gradle/gradle/issues/22765

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team and is prioritized by them.

**Comment by mlopatkin** [comment]
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/25898

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

The described problem is not specific to `SerializedLambda`, but rather to all serializable JDK classes when using TestKit's `withDebug` mode. In that case, Gradle doesn't fully control the JVM process running build logic and cannot apply necessary `--add-opens` switches. Gradle should give clearer guidance instead of throwing an internal exception.

inb4 "just use Java Serialization" - Gradle doesn't actually use Java Serialization to store CC state for various reasons (like performance, security, versatility). However, for `Serializable` classes there is a compatibility layer that respects protocol methods like `readResolve` and provides e.g. `ObjectInputStream`/`ObjectOutputStream` compatibility shims that delegate Java Serialization calls to CC serialization under the hood. Unfortunately, this requires unsafe reflection.
