### ISSUE TITLE
Gradle 8.2 milestone 1: Build Scan uses deprecated BuildIdentifier.getName

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#24994]
### Expected Behavior

nothing.

### Current Behavior

```
The ProjectComponentSelector.getBuildName() method has been deprecated. This is scheduled to be removed in Gradle 9.0. Use getBuildPath() to get a unique identifier for the build. Consult the upgrading guide for further information: https://docs.gradle.org/8.2-milestone-1/userguide/upgrading_version_8.html#build_identifier_name_and_current_deprecation
        at org.gradle.internal.component.local.model.DefaultProjectComponentSelector.getBuildName(DefaultProjectComponentSelector.java:83)
        at com.gradle.scan.plugin.internal.c.f.k.a(SourceFile:58)
        at com.gradle.scan.plugin.internal.c.f.k.a(SourceFile:26)
        at com.gradle.scan.plugin.internal.c.f.k.a(SourceFile:15)
        at com.gradle.scan.plugin.internal.c.f.c.a(SourceFile:64)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at com.gradle.scan.plugin.internal.c.f.c.a(SourceFile:64)
        at com.gradle.scan.plugin.internal.c.f.c.a(SourceFile:48)
        at com.gradle.scan.plugin.internal.c.i.a.d.a(SourceFile:139)
        at com.gradle.scan.plugin.internal.c.i.a.e$a.a(SourceFile:128)
        at com.gradle.scan.plugin.internal.f.b.a(SourceFile:26)
        at com.gradle.scan.plugin.internal.c.i.a.e$a.a(SourceFile:126)
        at com.gradle.scan.plugin.internal.c.i.a.e$a.a(SourceFile:105)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at com.gradle.scan.plugin.internal.c.i.a.e$a.<init>(SourceFile:105)
        at com.gradle.scan.plugin.internal.c.i.a.e$a.b(SourceFile:116)
        at com.gradle.scan.plugin.internal.c.i.a.e$a.a(SourceFile:72)
        at com.gradle.scan.plugin.internal.c.i.a.e.a(SourceFile:51)
        at com.gradle.scan.plugin.internal.c.i.a.d.a(SourceFile:176)
        at com.gradle.scan.plugin.internal.c.i.c.a(SourceFile:140)
        at com.gradle.scan.plugin.internal.m.b$c.finished(SourceFile:154)
        at com.gradle.scan.plugin.internal.m.b.a(SourceFile:65)
        at com.gradle.scan.plugin.internal.m.n.a(SourceFile:56)
        at com.gradle.scan.plugin.internal.m.d.a(SourceFile:109)
        at com.gradle.scan.plugin.internal.m.h.a(SourceFile:51)
        at com.gradle.scan.plugin.internal.r.a$a.a(SourceFile:31)
        at com.gradle.scan.plugin.internal.r.a$a.a(SourceFile:20)
        at com.gradle.scan.plugin.internal.r.a.c(SourceFile:67)
        at java.base/java.lang.Thread.run(Thread.java:833)
The BuildIdentifier.getName() method has been deprecated. This is scheduled to be removed in Gradle 9.0. Use getBuildPath() to get a unique identifier for the build. Consult the upgrading guide for further information: https://docs.gradle.org/8.2-milestone-1/userguide/upgrading_version_8.html#build_identifier_name_and_current_deprecation
        at org.gradle.api.internal.artifacts.DefaultBuildIdentifier.getName(DefaultBuildIdentifier.java:48)
        at com.gradle.scan.plugin.internal.c.f.h$b.a(SourceFile:103)
        at com.gradle.scan.plugin.internal.c.f.h.a(SourceFile:23)
        at com.gradle.scan.plugin.internal.c.i.a.d$c.a(SourceFile:118)
        at com.gradle.scan.plugin.internal.c.i.a.d.a(SourceFile:100)
        at com.gradle.scan.plugin.internal.c.i.a.e$a.a(SourceFile:137)
        at com.gradle.scan.plugin.internal.f.b.a(SourceFile:26)
        at com.gradle.scan.plugin.internal.c.i.a.e$a.a(SourceFile:126)
        at com.gradle.scan.plugin.internal.c.i.a.e$a.a(SourceFile:105)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at com.gradle.scan.plugin.internal.c.i.a.e$a.<init>(SourceFile:105)
        at com.gradle.scan.plugin.internal.c.i.a.e$a.b(SourceFile:116)
        at com.gradle.scan.plugin.internal.c.i.a.e$a.a(SourceFile:72)
        at com.gradle.scan.plugin.internal.c.i.a.e.a(SourceFile:51)
        at com.gradle.scan.plugin.internal.c.i.a.d.a(SourceFile:176)
        at com.gradle.scan.plugin.internal.c.i.c.a(SourceFile:140)
        at com.gradle.scan.plugin.internal.m.b$c.finished(SourceFile:154)
        at com.gradle.scan.plugin.internal.m.b.a(SourceFile:65)
        at com.gradle.scan.plugin.internal.m.n.a(SourceFile:56)
        at com.gradle.scan.plugin.internal.m.d.a(SourceFile:109)
        at com.gradle.scan.plugin.internal.m.h.a(SourceFile:51)
        at com.gradle.scan.plugin.internal.r.a$a.a(SourceFile:31)
        at com.gradle.scan.plugin.internal.r.a$a.a(SourceFile:20)
        at com.gradle.scan.plugin.internal.r.a.c(SourceFile:67)
        at java.base/java.lang.Thread.run(Thread.java:833)

* Exception is:
org.gradle.api.GradleException: Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0
        at org.gradle.internal.featurelifecycle.LoggingDeprecatedFeatureHandler.displayDeprecationIfSameMessageNotDisplayedBefore(LoggingDeprecatedFeatureHandler.java:90
        at org.gradle.internal.featurelifecycle.LoggingDeprecatedFeatureHandler.featureUsed(LoggingDeprecatedFeatureHandler.java:75)
        at org.gradle.internal.deprecation.DeprecationLogger.nagUserWith(DeprecationLogger.java:347)
        at org.gradle.internal.deprecation.DeprecationLogger.nagUserWith(DeprecationLogger.java:246)
        at org.gradle.internal.deprecation.DeprecationMessageBuilder$WithDocumentation.nagUser(DeprecationMessageBuilder.java:130)
        at org.gradle.api.internal.artifacts.DefaultBuildIdentifier.getName(DefaultBuildIdentifier.java:48)
        at com.gradle.scan.plugin.internal.c.f.h$b.a(SourceFile:103)
        at com.gradle.scan.plugin.internal.c.f.h.a(SourceFile:23)
        at com.gradle.scan.plugin.internal.c.i.a.d$c.a(SourceFile:118)
        at com.gradle.scan.plugin.internal.c.i.a.d.a(SourceFile:100)
        at com.gradle.scan.plugin.internal.c.i.a.e$a.a(SourceFile:100)
        at com.gradle.scan.plugin.internal.c.i.a.e$a.<init>(SourceFile:100)
        at com.gradle.scan.plugin.internal.c.i.a.e$a.b(SourceFile:116)
        at com.gradle.scan.plugin.internal.c.i.a.e$a.a(SourceFile:72)
        at com.gradle.scan.plugin.internal.c.i.a.e.a(SourceFile:51)
        at com.gradle.scan.plugin.internal.c.i.a.d.a(SourceFile:176)
        at com.gradle.scan.plugin.internal.c.i.c.a(SourceFile:140)
        at com.gradle.scan.plugin.internal.m.b$c.finished(SourceFile:154)
        at com.gradle.scan.plugin.internal.m.b.a(SourceFile:65)
        at com.gradle.scan.plugin.internal.m.n.a(SourceFile:56)
        at com.gradle.scan.plugin.internal.m.d.a(SourceFile:109)
        at com.gradle.scan.plugin.internal.m.h.a(SourceFile:51)
        at com.gradle.scan.plugin.internal.r.a$a.a(SourceFile:31)
        at com.gradle.scan.plugin.internal.r.a$a.a(SourceFile:20)
        at com.gradle.scan.plugin.internal.r.a.c(SourceFile:67)


BUILD FAILED in 1m 3s
67 actionable tasks: 67 executed
```

### Context (optional)

cc [alllex](https://github.com/alllex)

### Steps to Reproduce

Coming soon, if necessary. So far all I know is `--scan` triggers this behavior, and exception is in obfuscated code.

### Gradle version

`gradle-8.2-milestone-1-all + com.gradle:gradle-enterprise-gradle-plugin:3.13`

### Gradle version that used to work

`gradle-8.1.1-all`

**Comment by wolfs** [comment]
> Hmm, sorry, I'll have to check why Renovate didn't pick it up yet.

It has just been released.

**Comment by TWiStErRob** [comment]
Yeah, some of my repos have updated it. But in this repo I don't have explicit reference to this plugin. Gradle itself adds the plugin because of `--scan`, so it must be coming hard-coded from Gradle, so only M2 will fix this or have to add the plugin manually.

**Comment by TWiStErRob** [comment]
@wolfs will the `unreproducible` label cause problem with Release notes generation?

**Comment by wolfs** [comment]
No idea, I removed the label.

**Comment by ov7a** [comment]
@wolfs @TWiStErRob I apologize for the hassle, I was cleaning the triage queue and messed up with this label.

**Comment by ThadHouse** [comment]
Did this break again in 8.4? Getting the following errors upgrading from 8.1 to 8.4

```
The BuildIdentifier.getName() method has been deprecated. This is scheduled to be removed in Gradle 9.0. Use getBuildPath() to get a unique identifier for the build. Consult the upgrading guide for further information: https://docs.gradle.org/8.4/userguide/upgrading_version_8.html#build_identifier_name_and_current_deprecation
        at org.gradle.api.internal.artifacts.DefaultBuildIdentifier.getName(DefaultBuildIdentifier.java:48)
        at com.gradle.scan.plugin.internal.b.e.m$a.a(SourceFile:169)
        at com.gradle.scan.plugin.internal.b.e.m$a.a(SourceFile:147)
        at com.gradle.scan.plugin.internal.b.e.m$a.a(SourceFile:142)
        at com.gradle.scan.plugin.internal.b.e.m.a(SourceFile:72)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at com.gradle.scan.plugin.internal.b.e.m.a(SourceFile:72)
        at com.gradle.scan.plugin.internal.b.e.m.a(SourceFile:64)
        at com.gradle.scan.plugin.internal.b.e.n$a.b(SourceFile:107)
        at com.gradle.scan.plugin.internal.b.e.n$a.a(SourceFile:58)
        at com.gradle.scan.plugin.internal.b.e.n.a(SourceFile:49)
        at com.gradle.scan.plugin.internal.b.e.i.a(SourceFile:185)
        at com.gradle.scan.plugin.internal.k.a.f.a(SourceFile:12)
        at com.gradle.scan.plugin.internal.k.a$c.finished(SourceFile:154)
        at com.gradle.scan.plugin.internal.k.a.a(SourceFile:65)
        at com.gradle.scan.plugin.internal.k.i.a(SourceFile:58)
        at com.gradle.scan.plugin.internal.k.d.a(SourceFile:103)
        at com.gradle.scan.plugin.internal.k.f.a(SourceFile:48)
        at com.gradle.scan.plugin.internal.p.a$a.a(SourceFile:31)
        at com.gradle.scan.plugin.internal.p.a$a.a(SourceFile:20)
        at com.gradle.scan.plugin.internal.p.a.c(SourceFile:67)
        at java.base/java.lang.Thread.run(Thread.java:833)
The ProjectComponentSelector.getBuildName() method has been deprecated. This is scheduled to be removed in Gradle 9.0. Use getBuildPath() to get a unique identifier for the build. Consult the upgrading guide for further information: https://docs.gradle.org/8.4/userguide/upgrading_version_8.html#build_identifier_name_and_current_deprecation
        at org.gradle.internal.component.local.model.DefaultProjectComponentSelector.getBuildName(DefaultProjectComponentSelector.java:84)
        at com.gradle.scan.plugin.internal.b.e.m$b.a(SourceFile:208)
        at com.gradle.scan.plugin.internal.b.e.m$b.a(SourceFile:178)
        at com.gradle.scan.plugin.internal.b.e.m$b.a(SourceFile:173)
        at com.gradle.scan.plugin.internal.b.e.m.a(SourceFile:72)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at com.gradle.scan.plugin.internal.b.e.m.a(SourceFile:72)
        at com.gradle.scan.plugin.internal.b.e.m.a(SourceFile:68)
        at com.gradle.scan.plugin.internal.b.e.n$a.a(SourceFile:131)
        at com.gradle.scan.plugin.internal.b.e.n$a.<init>(SourceFile:93)
        at com.gradle.scan.plugin.internal.b.e.n$a.b(SourceFile:112)
        at com.gradle.scan.plugin.internal.b.e.n$a.a(SourceFile:58)
        at com.gradle.scan.plugin.internal.b.e.n.a(SourceFile:49)
        at com.gradle.scan.plugin.internal.b.e.i.a(SourceFile:185)
        at com.gradle.scan.plugin.internal.k.a.f.a(SourceFile:12)
        at com.gradle.scan.plugin.internal.k.a$c.finished(SourceFile:154)
        at com.gradle.scan.plugin.internal.k.a.a(SourceFile:65)
        at com.gradle.scan.plugin.internal.k.i.a(SourceFile:58)
        at com.gradle.scan.plugin.internal.k.d.a(SourceFile:103)
        at com.gradle.scan.plugin.internal.k.f.a(SourceFile:48)
        at com.gradle.scan.plugin.internal.p.a$a.a(SourceFile:31)
        at com.gradle.scan.plugin.internal.p.a$a.a(SourceFile:20)
        at com.gradle.scan.plugin.internal.p.a.c(SourceFile:67)
        at java.base/java.lang.Thread.run(Thread.java:833)
The BuildIdentifier.getName() method has been deprecated. This is scheduled to be removed in Gradle 9.0. Use getBuildPath() to get a unique identifier for the build. Consult the upgrading guide for further information: https://docs.gradle.org/8.4/userguide/upgrading_version_8.html#build_identifier_name_and_current_deprecation
        at org.gradle.api.internal.artifacts.DefaultBuildIdentifier.getName(DefaultBuildIdentifier.java:48)
        at com.gradle.scan.plugin.internal.b.e.m$a.a(SourceFile:169)
        at com.gradle.scan.plugin.internal.b.e.m$a.a(SourceFile:147)
        at com.gradle.scan.plugin.internal.b.e.m$a.a(SourceFile:142)
        at com.gradle.scan.plugin.internal.b.e.m.a(SourceFile:72)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at com.gradle.scan.plugin.internal.b.e.m.a(SourceFile:72)
        at com.gradle.scan.plugin.internal.b.e.m.a(SourceFile:64)
        at com.gradle.scan.plugin.internal.b.e.n$a.a(SourceFile:140)
        at com.gradle.scan.plugin.internal.b.e.n$a.<init>(SourceFile:93)
        at com.gradle.scan.plugin.internal.b.e.n$a.b(SourceFile:112)
        at com.gradle.scan.plugin.internal.b.e.n$a.a(SourceFile:58)
        at com.gradle.scan.plugin.internal.b.e.n.a(SourceFile:49)
        at com.gradle.scan.plugin.internal.b.e.i.a(SourceFile:185)
        at com.gradle.scan.plugin.internal.k.a.f.a(SourceFile:12)
        at com.gradle.scan.plugin.internal.k.a$c.finished(SourceFile:154)
        at com.gradle.scan.plugin.internal.k.a.a(SourceFile:65)
        at com.gradle.scan.plugin.internal.k.i.a(SourceFile:58)
        at com.gradle.scan.plugin.internal.k.d.a(SourceFile:103)
        at com.gradle.scan.plugin.internal.k.f.a(SourceFile:48)
        at com.gradle.scan.plugin.internal.p.a$a.a(SourceFile:31)
        at com.gradle.scan.plugin.internal.p.a$a.a(SourceFile:20)
        at com.gradle.scan.plugin.internal.p.a.c(SourceFile:67)
        at java.base/java.lang.Thread.run(Thread.java:833)

```

We don't explicitly include the build scan plugin anywhere, so its whatever is built into gradle.
