### ISSUE TITLE
Stopping MessageHub hangs indefinitely on OutOfMemoryError

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#25085]
### Expected Behavior

If there was some failure during tests, Gradle does not hang indefinitely but cleanly fails.

### Current Behavior

After there was an `OutOfMemoryError`, the test task is hanging indefinitely until manually cancelled.
This is most probably not on any average `OutOfMemoryError` error.

We had - considering just the effect, not the cause - the same problem in older Gradle versions too.
It did not happen on an arbitrarily enforced `OutOfMemoryError` by just consuming all heap in a test.
But it it happens somewhere while running CDI tests using `weld-junit4` with some unsatisfied dependencies.
I did not intend this short summary as a way to reproduce the issue, as I don't know how to reliably reproduce the error outside our big proprietary build, or even just outside the CI server.

In the past this was caused by a `CountDownLatch` that was not always counted down in certain situations, which was fixed in Gradle 7.2 with commit 7bcc1f140b5 that removed this latch.

Now with Gradle 7.5.1 the same failure situation still causes Gradle to hang indefinitely, just at a different spot.

The "Test worker" thread is trying to stop the message hub backed object connection but that does not finish while waiting `Integer.MAX_VALUE` seconds for the termination.
Here the thread dump for this thread:
```plain
"Test worker" #1 prio=5 os_prio=0 cpu=16343.51ms elapsed=35145.49s tid=0x00007f408403f000 nid=0x8563a waiting on condition  [0x00007f408955e000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.11/Native Method)
	- parking to wait for  <0x00000000e16d4ee8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.11/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.11/AbstractQueuedSynchronizer.java:2123)
	at java.util.concurrent.ThreadPoolExecutor.awaitTermination(java.base@11.0.11/ThreadPoolExecutor.java:1454)
	at org.gradle.internal.concurrent.ManagedExecutorImpl.stop(ManagedExecutorImpl.java:87)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$TrackedManagedExecutor.stop(DefaultExecutorFactory.java:96)
	at org.gradle.internal.concurrent.ManagedExecutorImpl.stop(ManagedExecutorImpl.java:77)
	at org.gradle.internal.remote.internal.hub.MessageHub.stop(MessageHub.java:225)
	at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:106)
	- locked <0x00000000fff1d6e0> (a org.gradle.internal.concurrent.CompositeStoppable)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection.stop(MessageHubBackedObjectConnection.java:150)
	at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:106)
	- locked <0x00000000fff0ff00> (a org.gradle.internal.concurrent.CompositeStoppable)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:137)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

The thread it is waiting on according to naming pattern is this one:
```plain
"/127.0.0.1:40264 to /127.0.0.1:45539 workers Thread 3" #15 prio=5 os_prio=0 cpu=28.92ms elapsed=41873.28s tid=0x00007f4085e00800 nid=0x85653 runnable  [0x00007f40466db000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPoll.wait(java.base@11.0.11/Native Method)
	at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@11.0.11/EPollSelectorImpl.java:120)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.11/SelectorImpl.java:124)
	- locked <0x00000000e16cbb48> (a sun.nio.ch.Util$2)
	- locked <0x00000000e16cb908> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(java.base@11.0.11/SelectorImpl.java:141)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketInputStream.read(SocketConnection.java:185)
	at com.esotericsoftware.kryo.io.Input.fill(Input.java:146)
	at com.esotericsoftware.kryo.io.Input.require(Input.java:178)
	at com.esotericsoftware.kryo.io.Input.readByte(Input.java:295)
	at org.gradle.internal.serialize.kryo.KryoBackedDecoder.readByte(KryoBackedDecoder.java:88)
	at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:64)
	at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:52)
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
	at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionReceive.run(MessageHub.java:270)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.11/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.11/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.11/Thread.java:829)
```
The process on port 40264 is the `worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 51'` process.
The process on port 45539 is the `org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.5.1` process.

So it seems that executor task tries to read one byte from this IPC connection but the byte is never delivered and thus it hangs forever and the executor cannot cleanly shut down which is waited for though.

### Steps to Reproduce

n/a

### Gradle version

7.5.1

**Comment by Vampire** [comment]
Here the four threads from the Gradle daemon side:

```plain
"/127.0.0.1:45539 to /127.0.0.1:40264 workers" #958 prio=5 os_prio=0 cpu=0.52ms elapsed=41874.43s tid=0x00007fa3fc032000 nid=0x8564d waiting on condition  [0x00007fa3bca1e000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.11/Native Method)
	- parking to wait for  <0x000000078c905528> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.11/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.11/AbstractQueuedSynchronizer.java:2081)
	at org.gradle.internal.remote.internal.hub.queue.EndPointQueue.take(EndPointQueue.java:49)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:403)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.11/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.11/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.11/Thread.java:829)
```
```plain
"/127.0.0.1:45539 to /127.0.0.1:40264 workers Thread 2" #959 prio=5 os_prio=0 cpu=2.28ms elapsed=41874.43s tid=0x00007fa3f084c800 nid=0x8564e waiting on condition  [0x00007fa3bc71b000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.11/Native Method)
	- parking to wait for  <0x000000078c905ae0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.11/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.11/AbstractQueuedSynchronizer.java:2081)
	at org.gradle.internal.remote.internal.hub.queue.EndPointQueue.take(EndPointQueue.java:49)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:403)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.11/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.11/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.11/Thread.java:829)
```
```plain
"/127.0.0.1:45539 to /127.0.0.1:40264 workers Thread 3" #960 prio=5 os_prio=0 cpu=0.66ms elapsed=41874.43s tid=0x00007fa3f0851000 nid=0x8564f waiting on condition  [0x00007fa3a96fd000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.11/Native Method)
	- parking to wait for  <0x000000078c90aec8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.11/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.11/AbstractQueuedSynchronizer.java:2081)
	at org.gradle.internal.remote.internal.hub.queue.EndPointQueue.take(EndPointQueue.java:49)
	at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionDispatch.run(MessageHub.java:322)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.11/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.11/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.11/Thread.java:829)
```
```plain
"/127.0.0.1:45539 to /127.0.0.1:40264 workers Thread 4" #961 prio=5 os_prio=0 cpu=30.80ms elapsed=41874.43s tid=0x00007fa3f046f800 nid=0x85650 runnable  [0x00007fa3ca8b7000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPoll.wait(java.base@11.0.11/Native Method)
	at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@11.0.11/EPollSelectorImpl.java:120)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.11/SelectorImpl.java:124)
	- locked <0x000000078c906248> (a sun.nio.ch.Util$2)
	- locked <0x000000078c906008> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(java.base@11.0.11/SelectorImpl.java:141)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketInputStream.read(SocketConnection.java:185)
	at com.esotericsoftware.kryo.io.Input.fill(Input.java:146)
	at com.esotericsoftware.kryo.io.Input.require(Input.java:178)
	at com.esotericsoftware.kryo.io.Input.readByte(Input.java:295)
	at org.gradle.internal.serialize.kryo.KryoBackedDecoder.readByte(KryoBackedDecoder.java:88)
	at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:64)
	at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:52)
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
	at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionReceive.run(MessageHub.java:270)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.11/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.11/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.11/Thread.java:829)
```

Most interesting imho is the last one, that also waits for an incoming byte on the IPC connection.
So both processes wait for a byte from the other side and thus do not continue.

**Comment by jbartok** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.
