### ISSUE TITLE
Support `@Option` with ListProperty

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#25097]
### Expected Behavior

It is possible to annotation a JavaBean property of type `List<String>` with `@Option` and supply it with values from the command-line. We should have feature parity for properties of type `ListProperty<String>` etc.

### Current Behavior (optional)

Currently an error is thrown if `@Option` is used on `ListProperty<String>`:

```text
Caused by: org.gradle.cli.CommandLineArgumentException: Command-line option '--serial' does not take an argument.
	at app//org.gradle.cli.CommandLineParser$KnownOptionParserState.onArgument(CommandLineParser.java:423)
	at app//org.gradle.cli.CommandLineParser.parse(CommandLineParser.java:93)
	at app//org.gradle.execution.commandline.CommandLineTaskConfigurer.configureTasksNow(CommandLineTaskConfigurer.java:67)
	... 123 more
```

### Context

When migrating eager multi-valued properties from `List<T>` to lazy `ListProperty<T>` types we need to keep `@Option` working for them.

**Comment by lptr** [comment]
Duplicate of https://github.com/gradle/gradle/issues/10517.
