### ISSUE TITLE
Exception java.lang.NullPointerException in the middle of native Gradle build

### ISSUE THREAD

**Issue by FranzKrainer** [gradle/gradle#2509]
In the middle of a native Gradle build (with Gradle 2.14.1 still) we see the following error message:
<<<
FAILURE: Build failed with an exception.
12:40:16 
12:40:16 * What went wrong:
12:40:16 java.lang.NullPointerException (no error message)
12:40:16 
12:40:16 * Try:
12:40:16 Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
12:40:16 
12:40:16 
12:40:16 BUILD FAILED
>>>
The error is not reproducible and randomly appearing, esp. in Jenkins automation (CI server).
Question is mainly if this behavior was seen by others and might be fixed in later Gradle versions.

### Expected Behavior
Running-through build :)

### Current Behavior
Most of the time 99% the build is working as expected. In 1% we get the above-described error message.

### Context
Affects mainly CI Server (Jenkins). Might be related to destroyed Gradle caches. The error we see more often when we had to restart Jenkins master and Jenkins clients thus aborted execution. 

### Steps to Reproduce (for bugs)
Arbitrary native C and ASM build. Breaks randomly in between.

### Your Environment
Gradle version is 2.14.1. Jenkins ver. 1.580.3, Java VM 1.8.0_25-b18.

**Comment by lacasseio** [comment]
Thanks for reporting this issue @FranzKrainer. Could you turn on the stack trace for all CI build by passing `--stacktrace` to Gradle? This would help us get more context. Alternatively, if you can use [build scan](https://scans.gradle.com/get-started) it would be even better.

Here's a couple more question to help with the debugging:
* Do you use [configure on demand](https://docs.gradle.org/3.3/userguide/multi_project_builds.html#sec:configuration_on_demand) in your native build?
* What recently changed in your build logic?
* Did you upgrade to Gradle 2.14.1 recently?

**Comment by FranzKrainer** [comment]
Hi,

thanks for the fast reply! Much appreciated :-)!

I will answer one by one:
@ --stacktrace: Yes, that's what we gonna do for CI builds as default. Question here: Does this have any negative side effects? Is there something slowed down etc. in normal execution? If no, why is not the default in Gradle execution :-)? Guess it is too verbose...
@ Build Scan: Nope, we are not Gradle Enterprise users and bec. of sec. limitations not allowed to use free-variant of it (upload to net)

@ Configure on Demand: Yes, we use it. So far it caused no issues.
@ Recent Changes: Actually nothing. We kept the actual structures stable. The problem 'just' appeared.
@ Gradle 2.14.1: Nope, we have this for several months now. All stable. also no complaints from human users.

One further question: Could parallel execution lead to such effects here? so, we have not modeled something correctly and in some very rare cases not all preconditions are met e.g.?

**Comment by bmuschko** [comment]
> --stacktrace: Yes, that's what we gonna do for CI builds as default.

Seems like it is not properly configured. At least the Gradle error message seems to indicate that. Maybe you can try to reproduce the issue locally. We'll need to have the stack trace to be able to pinpoint the issue.

> Does this have any negative side effects? Is there something slowed down etc. in normal execution?
There's no performance impact.

> Guess it is too verbose...

Correct. Most user would rather have less information or only the relevant information. A `NullPointerException` is most certainly a bug in Gradle core.

> Gradle 2.14.1: Nope, we have this for several months now. All stable. also no complaints from human users.

I'd strongly recommend upgrading to Gradle 4.0.1. It's possible that the issue has already been fixed. BTW: It looks like you are concerned about performance. Gradle 4 is much, much faster than Gradle 2. That by itself is a good argument to upgrade.

> One further question: Could parallel execution lead to such effects here? so, we have not modeled something correctly and in some very rare cases not all preconditions are met e.g.?

Yes, there could be an issue with parallel execution.

**Comment by FranzKrainer** [comment]
Hi,

thanks a lot for the precise answers!
We were really able to catch a build using --stacktrace.
The error log / stacktrace:
<<<
FAILURE: Build failed with an exception.

* What went wrong:
java.lang.NullPointerException (no error message)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.NullPointerException
        at org.gradle.api.internal.changedetection.state.TreeSnapshotRepository.removeTreeSnapshotUsage(TreeSnapshotRepo
sitory.java:85)
        at org.gradle.api.internal.changedetection.state.CacheBackedFileSnapshotRepository.remove(CacheBackedFileSnapsho
tRepository.java:47)
        at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository$1$1.run(CacheBackedTaskHistory
Repository.java:81)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:192)
        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:175)
        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:106)
        at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.useCache(DefaultCacheFactory.java:187)
        at org.gradle.api.internal.changedetection.state.DefaultTaskArtifactStateCacheAccess.useCache(DefaultTaskArtifac
tStateCacheAccess.java:60)
        at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository$1.update(CacheBackedTaskHistor
yRepository.java:66)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.afte
rTask(DefaultTaskArtifactStateRepository.java:135)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:68)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExec
uter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.j
ava:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.j
ava:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecute
r.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecute
r.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecut
or.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:
50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)


BUILD FAILED

Total time: 12.81 secs
>>>
Any idea what stands behind this stacktrace? Sounds/feels like a cache issue, right?
How can such issues with Cache been triggered (so, what are we doing wrongly that causes this behavior)?

@Move to Gradle 4.0.1: Yes, indeed, that's what we gonna do and are preparing currently :).
And yes, we are hoping for an even better performance - it can never be fast enough ;-)!

BR,
Franz

**Comment by FranzKrainer** [comment]
Hi @bmuschko and @lacasseio,

any update on the stack trace I provided? Any ideas here?
Should we let this topic go and concentrate on the fact if we see similar things in Gradle 4.0.2?
Am eager to know if it is worth investing into this random issue (and if there is a likelihood that this persists in many/later Gradle versions).

Thanks a lot in advance!
BR,
Franz

**Comment by lacasseio** [comment]
@FranzKrainer I think the best step forward would be to migrate to Gradle 4.0.2 and soon to be released 4.1. Lots have changed in that part of the code base (the class `TreeSnapshotRepository` doesn't exist anymore) that it wouldn't surprise me the flaky issue has already been fixed. With the latest version, we would be in a better position to help find the issue and roll a fix if needed.

**Comment by FranzKrainer** [comment]
Hi,
sounds great and fair to me. In the meantime we switched to Gradle 4.0.2 and did not yet see this there. Let's refrain from analyzing old stuff and concentrate on new one :-).
Will come back to you if this re-appears in new Gradle versions of course.

Think we can close this one!
Thanks & bye,
Franz
