### ISSUE TITLE
Cannot specify "plugin" in version-catalog without version

### ISSUE THREAD

**Issue by ChristianCiach** [gradle/gradle#25222]
### Expected Behavior

I want to generate a typesafe-accessor for a gradle plugin using a version-catalog. I want to force the user to explicitly state the plugin version when *using* the accessor. This seems to work for normal libraries, but not for plugins.

### Current Behavior

Even when explicitly declaring a plugin version at usage-side, Gradle fails:

Usage side:

`build.gradle`:
```groovy
plugins {
    id 'java'
    alias(libs.plugins.springBoot) version "3.1.0"
}
```

Error on `./gradlew build`:

```
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':example-project'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:111)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:65)
...
Caused by: org.gradle.plugin.internal.InvalidPluginVersionException: plugin version '' is invalid: cannot be null or empty
	at org.gradle.plugin.use.internal.PluginRequestCollector$PluginDependencySpecImpl.version(PluginRequestCollector.java:143)
	at org.gradle.plugin.use.internal.PluginRequestCollector$PluginDependenciesSpecImpl.alias(PluginRequestCollector.java:116)
...
```

### Steps to Reproduce

`libs.versions.toml`:
```toml
[plugins]
springBoot = { id = "org.springframework.boot" }
```

The same error happens when explicitly declaring an empty version inside the catalog:

```toml
[plugins]
springBoot = { id = "org.springframework.boot", version = "" }
```

The user **can** override the plugin version if I use a non-empty version inside the catalog:

```toml
[plugins]
springBoot = { id = "org.springframework.boot", version = "0.0.0" }
```

When doing the above, the version can be overridden like this:
`build.gradle`:
```groovy
plugins {
    id 'java'
    alias(libs.plugins.springBoot) version "3.1.0"
}
```

I'd expect this to work also if the version catalog does not contain a version for the plugin.

### Gradle version

8.1.1

### Your Environment (optional)

Fedora Linux 38, Current OpenJDK 17 (eclipse temurin)

**Comment by ChristianCiach** [comment]
Oops. I think this is a duplicate of https://github.com/gradle/gradle/issues/17968. Closing.
