### ISSUE TITLE
Integration tests failing with non-ASCII characters

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#25429]
When https://github.com/gradle/gradle/pull/25261 was merged, some ready-for-release tests started to fail.

---
cc: @gradle/bt-execution

**Comment by lptr** [comment]
The problems only occur for integration tests in the following circumstances:

- The test passes `-Dfile.encoding=...` to a build they trigger with a non-Unicode character set.
- The test does not explicitly ask for a non-embedded executor (e.g. via `    @Requires(IntegTestPreconditions.NotEmbeddedExecutor)`).
- The test is executed as part of one of the following CI jobs:
    
<img width="1006" alt="image" src="https://github.com/gradle/gradle/assets/495366/4fe5ee7e-f8f7-4a09-a0ae-f955a5df7c4a">

**Comment by lptr** [comment]
This piece of code is at the core of the problem:

https://github.com/gradle/gradle/blob/69b99f34a53d2fcdd2864d093e67058bf45e107c/subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleContextualExecuter.java#L172-L179

When the embedded executor is used, and the build being triggered sets the default character set to something other than what the embedded executor is running with, we switch to isolated daemon mode automatically.

So despite the tests not asking for a forked execution explicitly, that's what they get for calling `GradleExecuter.withDefaultCharacterEncoding("ASCII")` etc.

So all of the failing tests are executed via a forked process. However, there are two more factors that determine if these tests fail or succeed:

1) When executed with Java 19, the tests pass with the embedded executor alright. That's why the original PR could be merged, because the QuickFeedbackLinux/QuickFeedback run with the latest Java release. This is probably due to how in Java 18 the default character encoding is set to UTF-8, and perhaps something else was changed as part of this: https://medium.com/@andbin/jdk-18-and-the-utf-8-as-default-charset-8451df737f90. The failing CI builds all use Java 8.

2) When executed via the `forkingIntegTest` task instead of via `embeddedIntegTest`, the tests pass, even on Java 8.

**Comment by lptr** [comment]
Actually, this is only about problems encountered in the [ForceRealizeDependencyManagement Java8 Oracle Linux Amd64](https://builds.gradle.org/project/Gradle_Master_Check_ForceRealizeDependencyManagement_15) builds that run with the embedded executer. The other test failures are either legitimate or flaky, but not caused by the embedded executer vs encoding problem...

**Comment by lptr** [comment]
OK, so it looks like the Swift compiler (or the way we invoke it?) has issues with non-ASCII paths, disabled it for now.

Also moved out all tests using `GradleExecuter.withDefaultCharacterEncoding()` to test classes that are now annotated with `@DoesNotSupportNonAsciiPaths`.

**Comment by lptr** [comment]
Moving the tests out is just a workaround for now. The tests should be able to run with the embedded executor, too, just like the run with the forked executor, but they do not.

I tried to check the difference between what gets executed:

https://gist.github.com/lptr/9729c227683edd3a7f9883f7d892c8c4

The only real difference I found is that embedded runs the `java` binary, while forking runs the `gradle` shell script from the distribution root.

When playing around with debugging test execution, I managed to get a failing embedded execution pass only by removing all arguments that contain the non-ASCII characters (`-Dorg.gradle.daemon.registry.base=...` and `-Dmaven.repo.local=...`). If I did this, it worked fine. With these parameters I got the following error:

```text
* Exception is:
org.gradle.process.internal.ExecException: A problem occurred starting process 'Gradle build daemon'
	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:241)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:218)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:370)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:87)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:38)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: net.rubygrapefruit.platform.NativeException: Could not start '/Users/lptr/.sdkman/candidates/java/11.0.15-corretto/amazon-corretto-11.jdk/Contents/Home/bin/java'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:98)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:71)
	... 6 more
Caused by: java.io.IOException: Cannot run program "/Users/lptr/.sdkman/candidates/java/11.0.15-corretto/amazon-corretto-11.jdk/Contents/Home/bin/java" (in directory "/Users/lptr/Workspace/gradle/gradle/subprojects/core/build/tmp/te?t files/CopySpecEnc.Spec/wrwpw/daemon/8.3-20230620220000+0000"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 9 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 11 more
```

The weird thing is that the forking executor also takes a parameter with non-ASCII characters (`-Dmaven.repo.local=...`) and it works just fine.

Note that the working directory path containing non-ASCII characters is not a cause for the failure: it's the command-line arguments that cause the failure.

It seems that both on macOS and on Linux, the OS or something handles non-ASCII characters passed in command-line arguments differently when executing a binary vs executing a shell script. But this sounds... unlikely.
