### ISSUE TITLE
Config Cache: Provide a message with more details: `cannot be reused because an input to unknown location has changed`

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#25469]
### Expected Behavior

Provide ALL the required details needed  in order to fully understand config cache miss.
Details should be in the error message and in the config cache HTML report.

### Current Behavior

Gradle prints this which is not helpful. 

```
Calculating task graph as configuration cache cannot be reused because an input to unknown location has changed.
```

### Context (optional)

Related to this code: 

https://github.com/gradle/gradle/blob/004b9a327fffca057a11386d3798220ec1e99787/subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintChecker.kt#L154-L157

Which is related to this issue: 
https://github.com/gradle/configuration-cache/issues/282

### Steps to Reproduce

I don't know... because all the error message says is `because an input to unknown location has changed`

Need a better message to help with repro.

### Gradle version

8.1.1

### Your Environment (optional)

AGP 8.0.2
macOS 12.6.5
JDK 17

**Comment by eskatos** [comment]
Thank you for the report.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by marcphilipp** [comment]
I'm also seeing this in the JUnit build and it's not very actionable. :confused:

**Comment by SimonMarquis** [comment]
👋 I also reproduced this behavior consistantly with Gradle's build validation script experiments that are currently running weekly on one of my projects. Here are the logs where it fails: https://github.com/SimonMarquis/SealedObjectInstances/actions/runs/12864638057/job/35863558069#step:4:259

I'm not 100% sure why this happened, but here is a diff where before it worked, and after it no longer does: https://github.com/SimonMarquis/SealedObjectInstances/compare/c551e67ad359434eaa4a8b2a4e5c4b30fb9bda0f...3b61831776c71603525608190b6eec950df1d22c
The main changes are:
-  Bump gradle/develocity-build-validation-scripts from v2.7.2 to v2.7.3 (they are not expecting any change with this update)
- Upgrade `com.diffplug.spotless` to a "configuration cache compatible" version 7.0.1
- Upgrade Dokka to a "configuration cache compatible" version 2.0.0
- Upgrade Gradle 8.12

From my experience, running this from a PR branch would almost always succeed (probably also related to caching differences).

**Comment by SimonMarquis** [comment]
And here is the configuration cache report diff of the 2 Gradle executions:

- environment variables:
  ```diff
  - `GIT_TRACE_PERFORMANCE`
  ```
- system property (this change might be the root cause, spotless 👀):
  ```diff
  - `durian.plugins.com.diffplug.common.base.Errors.Plugins.Log`
  ```
- file: (`.editorconfig` at the end might also be indicating this is related to spotless is some way)
  ```diff
  - `../../../.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.3.14/.../logback-classic-1.3.14.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-core/1.3.14/.../d12d0f97df6f275e4a/logback-core-1.3.14.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.github.ajalt.clikt/clikt-core-jvm/5.0.2/.../clikt-jvm.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.github.ajalt.clikt/clikt-jvm/5.0.2/.../0d997cd678373922cf/clikt-mordant-jvm.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.github.ajalt.colormath/colormath-jvm/3.6.0/.../colormath-jvm.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.github.ajalt.mordant/mordant-core-jvm/3.0.1/.../mordant-jvm.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.github.ajalt.mordant/mordant-jvm-ffm-jvm/3.0.1/.../mordant-jvm-ffm-jvm.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.github.ajalt.mordant/mordant-jvm-graal-ffi-jvm/3.0.1/.../mordant-jvm-graal-ffi-jvm.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.github.ajalt.mordant/mordant-jvm-jna-jvm/3.0.1/.../mordant-jvm-jna-jvm.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.github.ajalt.mordant/mordant-jvm/3.0.1/.../mordant-omnibus-jvm.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.pinterest.ktlint/ktlint-cli-reporter-baseline/1.5.0/.../ktlint-cli-reporter-baseline-1.5.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.pinterest.ktlint/ktlint-cli-reporter-checkstyle/1.5.0/.../ktlint-cli-reporter-checkstyle-1.5.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.pinterest.ktlint/ktlint-cli-reporter-core/1.5.0/.../ktlint-cli-reporter-core-1.5.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.pinterest.ktlint/ktlint-cli-reporter-format/1.5.0/.../ktlint-cli-reporter-format-1.5.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.pinterest.ktlint/ktlint-cli-reporter-html/1.5.0/.../ktlint-cli-reporter-html-1.5.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.pinterest.ktlint/ktlint-cli-reporter-json/1.5.0/.../ktlint-cli-reporter-json-1.5.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.pinterest.ktlint/ktlint-cli-reporter-plain-summary/1.5.0/.../ktlint-cli-reporter-plain-summary-1.5.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.pinterest.ktlint/ktlint-cli-reporter-plain/1.5.0/.../ktlint-cli-reporter-plain-1.5.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.pinterest.ktlint/ktlint-cli-reporter-sarif/1.5.0/.../ktlint-cli-reporter-sarif-1.5.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.pinterest.ktlint/ktlint-cli-ruleset-core/1.5.0/.../ktlint-cli-ruleset-core-1.5.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.pinterest.ktlint/ktlint-cli/1.5.0/.../ktlint-cli-1.5.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.pinterest.ktlint/ktlint-logger/1.5.0/.../ktlint-logger-1.5.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.pinterest.ktlint/ktlint-rule-engine-core/1.5.0/.../ktlint-rule-engine-core-1.5.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.pinterest.ktlint/ktlint-rule-engine/1.5.0/.../ktlint-rule-engine-1.5.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/com.pinterest.ktlint/ktlint-ruleset-standard/1.5.0/.../ktlint-ruleset-standard-1.5.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/dev.drewhamilton.poko/poko-annotations-jvm/0.18.0/.../poko-annotations-jvm-0.18.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/io.github.detekt.sarif4k/sarif4k-jvm/0.6.0/.../sarif4k-jvm-0.6.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/io.github.oshai/kotlin-logging-jvm/7.0.3/.../kotlin-logging-jvm-7.0.3.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/net.java.dev.jna/jna/5.14.0/.../jna-5.14.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/org.ec4j.core/ec4j-core/1.1.0/.../ec4j-core-1.1.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/org.jetbrains.intellij.deps/trove4j/1.0.20200330/.../trove4j-1.0.20200330.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/2.1.0/.../kotlin-compiler-embeddable-2.1.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-daemon-embeddable/2.1.0/.../kotlin-daemon-embeddable-2.1.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.6.10/.../kotlin-reflect-1.6.10.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-script-runtime/2.1.0/.../kotlin-script-runtime-2.1.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.8.0/.../kotlin-stdlib-jdk7-1.8.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.8.0/.../kotlin-stdlib-jdk8-1.8.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/2.1.0/.../kotlin-stdlib-2.1.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-jvm/1.6.4/.../kotlinx-coroutines-core-jvm-1.6.4.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-serialization-core-jvm/1.4.1/.../kotlinx-serialization-core-jvm-1.4.1.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-serialization-json-jvm/1.4.1/.../kotlinx-serialization-json-jvm-1.4.1.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/.../annotations-13.0.jar`
  - `../../../.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/2.0.7/.../slf4j-api-2.0.7.jar`
  - `.editorconfig`
  ```

**Comment by ZacSweers** [comment]
I also see this with spotless, I think your hunch is correct

**Comment by ZacSweers** [comment]
Filed https://github.com/diffplug/spotless/issues/2416

**Comment by runningcode** [comment]
@eskatos is there a possibility to look at improving this error message? It is clearly something that is debuggable by looking at the configuration cache diff.

**Comment by jjohannes** [comment]
Today I had this consistently and it looks somehow related to "build logic include" in my case. It is probably something else than the Spotless related issue discussed above. Although, Spotless is involved in the build where I see this.

If I diff the reports, I see three ENV variables in different order (but same values) which I guess should be okay.

But then there is this:

<img width="1250" height="197" alt="Image" src="https://github.com/user-attachments/assets/38ef6d1a-693a-4a5d-9062-b0e0c622e6a1" />

This is with Gradle `9.1.0`. Reproduce:

* clone https://github.com/gradlex-org/java-module-dependencies
* switch to commit https://github.com/gradlex-org/java-module-dependencies/commit/3568aee216f1dbeb0791797138cc3e429529b6f0
* clone https://github.com/gradlex-org/internal-build-conventions inside `java-module-dependencies/build`
* switch to commit https://github.com/gradlex-org/internal-build-conventions/pull/60/commits/9d77628d4dcaf4c4b23a5b03f4ee733256b241d6
* In `java-module-dependencies` run `./gradlew build` repeatedy
   * See `Calculating task graph as configuration cache cannot be reused because an input to unknown location has changed.` in every run

**Comment by jjohannes** [comment]
Alright, I think my issue was caused by Spotless, which emphasizes that the `unknown location` thing can lead to quite some confusion. I ran into other weird behavior on CI where it tried to hash a number of files where I was surprised that it did. This time, I saw a connection to spotless. I then took a closer look on the config cache report again. I noticed that it used git and looked for `.gitattributes` files everywhere. In my setup, I don't need the build to do anything with `git` during config time. Turns out, by default Spotless searches for the line ending definition in those files. Which can likely lead to weird behavior as it seems to search huge parts of the file tree.

Adding this to all my spotless steps seems to have fixed it:

```
setLineEndings(LineEnding.UNIX)
```

**Comment by abstratt** [comment]
This is what I could find out:
- Spotless configures a provider whose value is an object of a type (`LazyForwardingEquality`) that has a custom `writeObject` ([code](https://github.com/diffplug/spotless/blob/main/lib/src/main/java/com/diffplug/spotless/LazyForwardingEquality.java#L70))
- this custom `writeObject` triggers the computation of some lazy state, as defined by the subclass implementation of `LazyForwardingEquality`, for example [this one](https://github.com/diffplug/spotless/blob/88c83de2450b8fad8174ff08a5c95fa18a915617/lib-extra/src/main/java/com/diffplug/spotless/extra/GitAttributesLineEndings.java#L91) 
- if the computation itself access a file collection, we register this file collection as an undeclared input, but fail to include any information about the collection

However, I doubt that including a display string for the file collection would be enough for users to make sense of it. A stacktrace would be very verbose, however may be the only way to provide enough insight to users.

Here is a stacktrace I obtained while debugging running `gradle spotlessApply` under `zacsweers/metro` (see  spotless tracker - https://github.com/diffplug/spotless/issues/2416#issuecomment-3203869417)


```
at org.gradle.internal.configuration.problems.DefaultProblemFactory.locationForCaller(DefaultProblemFactory.kt:114)
at org.gradle.internal.configuration.problems.DefaultProblemFactory.locationForCaller(DefaultProblemFactory.kt:37)
at org.gradle.internal.cc.impl.fingerprint.ConfigurationCacheFingerprintController$CacheFingerprintWriterHost.location(ConfigurationCacheFingerprintController.kt:441)
at org.gradle.internal.cc.impl.fingerprint.ConfigurationCacheFingerprintWriter.fileCollectionObserved(ConfigurationCacheFingerprintWriter.kt:362)
...
at org.gradle.api.internal.file.collections.DefaultConfigurableFileTree.getFiles(DefaultConfigurableFileTree.java:63)
at org.gradle.api.internal.file.SubtractingFileCollection.getIntrinsicFiles(SubtractingFileCollection.java:57)
at org.gradle.api.internal.file.AbstractOpaqueFileCollection.iterator(AbstractOpaqueFileCollection.java:54)
at com.diffplug.spotless.extra.GitAttributesLineEndings$LazyAllTheSame.calculateState(GitAttributesLineEndings.java:92)
at com.diffplug.spotless.extra.GitAttributesLineEndings$LazyAllTheSame.calculateState(GitAttributesLineEndings.java:80)
at com.diffplug.spotless.LazyForwardingEquality.state(LazyForwardingEquality.java:57)
at com.diffplug.spotless.LazyForwardingEquality.writeObject(LazyForwardingEquality.java:69)
...
org.gradle.internal.serialize.codecs.core.jos.JavaObjectSerializationCodec$WriteObjectEncoding.recordWritingOf(JavaObjectSerializationCodec.kt:148)
at org.gradle.internal.serialize.codecs.core.jos.JavaObjectSerializationCodec$WriteObjectEncoding.recordWritingOf(_Collections.kt:1869)
at org.gradle.internal.serialize.codecs.core.jos.JavaObjectSerializationCodec$WriteObjectEncoding.recordWritingOf(JavaObjectSerializationCodec.kt:147)
at org.gradle.internal.serialize.codecs.core.jos.JavaObjectSerializationCodec$WriteObjectEncoding.recordWritingOf(JavaObjectSerializationCodec.kt:146)
at org.gradle.internal.serialize.codecs.core.jos.JavaObjectSerializationCodec$WriteObjectEncoding.encode(JavaObjectSerializationCodec.kt:137)
at org.gradle.internal.serialize.codecs.core.jos.JavaObjectSerializationCodec$WriteObjectEncoding.encode(Codec.kt:310)
at org.gradle.internal.serialize.codecs.core.jos.JavaObjectSerializationCodec$WriteObjectEncoding.encode(Codec.kt:293)
at org.gradle.internal.serialize.codecs.core.jos.JavaObjectSerializationCodec$WriteObjectEncoding.encode(JavaObjectSerializationCodec.kt:135)

```

**Comment by yogurtearl** [comment]
A stack trace would be **_very_** helpful compared to the current messages. :)

**Comment by jjohannes** [comment]
I think the most interesting bit of information here for my as **user** is **which plugin** is responsible for doing something "unexpected".

IIUC, what Spotless does is not something you "should do". (At least to me it looks like something you definitely should not do in a Gradle plugin.) And that's why the information you would usually see as reason is missing. Then, for me as user, it indicates that there is a bug/issue in the plugin.

If I know the responsible plugin and have a stack trace, I can then share that with the plugin maintainer.
