### ISSUE TITLE
Configuration cache state could not be cached: field `value` of `kotlinx.datetime.LocalDateTime` bean found in field `currentTime` of task `:printTimeTask` of type `Build_gradle$PrintTimeTask`: error writing value of type 'java.time.LocalDateTime' > Unable to make private java.lang.Object java.time.LocalDateTime.writeReplace() accessible: module java.base does not "opens java.time" to unnamed module @571be0ad

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#25680]
### Expected Behavior

Configuration Cache can be cached

### Current Behavior

Configuration Cache cannot be cached

### Steps to Reproduce

```
import kotlinx.datetime.TimeZone
import kotlinx.datetime.toLocalDateTime

buildscript {
  dependencies {
    classpath("org.jetbrains.kotlinx:kotlinx-datetime:0.4.0")
  }
}

plugins {
  base
}


abstract class PrintTimeTask : DefaultTask() {
  private val currentTime = kotlinx.datetime.Clock.System.now().toLocalDateTime(TimeZone.UTC)
  @TaskAction
  fun action() {
    println(currentTime)
  }
}

val printTimeTask by tasks.registering(PrintTimeTask::class) {

}
```

`./gradlew PrintTimeTask`

```
15:50:08: Executing 'printTimeTask'...

Calculating task graph as no configuration cache is available for tasks: printTimeTask

FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache state could not be cached: field `value` of `kotlinx.datetime.LocalDateTime` bean found in field `currentTime` of task `:printTimeTask` of type `Build_gradle$PrintTimeTask`: error writing value of type 'java.time.LocalDateTime'
> Unable to make private java.lang.Object java.time.LocalDateTime.writeReplace() accessible: module java.base does not "opens java.time" to unnamed module @571be0ad

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 2s
```

### Gradle version

8.2

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by mlopatkin** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

***

This issue can be worked around by storing e.g. a String representation, but this is, of course, quite ugly.

We did few rounds of whack-a-mole with `add-opens`, but this doesn't scale well. A general solution is tracked at #16429.

**Comment by aSemy** [comment]
> This issue can be worked around by storing e.g. a String representation, but this is, of course, quite ugly.

Thanks for the suggestion. I have a though, and I wonder what you think: [Kotlinx LocalDateTime is serializable with Kotlinx Serialization](https://github.com/Kotlin/kotlinx-datetime/blob/c84554c50b4d752926931a8a07e8eee14e7e4c7e/core/common/src/LocalDateTime.kt#L27-L28). Would it be possible for Gradle to automatically use Kotlinx Serialization?

**Comment by tnielens-centrica** [comment]
Facing similar issues with java.time classes.
```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make private java.lang.Object java.time.ZonedDateTime.writeReplace() accessible: module java.base does not "opens java.time" to unnamed module @3959a4bc
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:200)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:194)
        at org.gradle.internal.serialize.codecs.core.jos.MethodCacheKt.firstAccessibleMatchingMethodOrNull(MethodCache.kt:50)
        at org.gradle.internal.serialize.codecs.core.jos.JavaSerializationEncodingLookup.writeReplaceMethodFrom(JavaSerializationEncodingLookup.kt:78)
        at org.gradle.internal.serialize.codecs.core.jos.JavaSerializationEncodingLookup.writeReplaceEncodingFor(JavaSerializationEncodingLookup.kt:56)
        at org.gradle.internal.serialize.codecs.core.jos.JavaSerializationEncodingLookup.calculateEncoding(JavaSerializationEncodingLookup.kt:47)
        at org.gradle.internal.serialize.codecs.core.jos.JavaSerializationEncodingLookup.access$calculateEncoding(JavaSerializationEncodingLookup.kt:32)
        at org.gradle.internal.serialize.codecs.core.jos.JavaSerializationEncodingLookup$encodingFor$1.apply(JavaSerializationEncodingLookup.kt:41)
        at org.gradle.internal.serialize.codecs.core.jos.JavaSerializationEncodingLookup$encodingFor$1.apply(JavaSerializationEncodingLookup.kt:41)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
        at org.gradle.internal.serialize.codecs.core.jos.JavaSerializationEncodingLookup.encodingFor(JavaSerializationEncodingLookup.kt:41)
        at org.gradle.internal.serialize.codecs.core.jos.JavaObjectSerializationCodec.encodingForType(JavaObjectSerializationCodec.kt:79)
        at org.gradle.internal.serialize.graph.codecs.Binding.encodingForType(BindingsBackedCodec.kt:101)
        at org.gradle.internal.serialize.graph.codecs.BindingsBackedCodec.computeEncoding(BindingsBackedCodec.kt:80)
        at org.gradle.internal.serialize.graph.codecs.BindingsBackedCodec.access$computeEncoding(BindingsBackedCodec.kt:43)
        at org.gradle.internal.serialize.graph.codecs.BindingsBackedCodec$taggedEncodingFor$1.apply(BindingsBackedCodec.kt:75)
        at org.gradle.internal.serialize.graph.codecs.BindingsBackedCodec$taggedEncodingFor$1.apply(BindingsBackedCodec.kt:75)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at org.gradle.internal.serialize.graph.codecs.BindingsBackedCodec.taggedEncodingFor(BindingsBackedCodec.kt:75)
        at org.gradle.internal.serialize.graph.codecs.BindingsBackedCodec.encode(BindingsBackedCodec.kt:56)
        at org.gradle.internal.serialize.graph.DefaultWriteContext.write(Contexts.kt:109)
        at org.gradle.internal.serialize.codecs.stdlib.NonPrimitiveArrayCodec.encode(ArrayCodecs.kt:45)
        at org.gradle.internal.serialize.codecs.stdlib.NonPrimitiveArrayCodec.encode(ArrayCodecs.kt:42)
        at org.gradle.internal.serialize.graph.codecs.BindingsBackedCodec.encode(BindingsBackedCodec.kt:63)
        at org.gradle.internal.serialize.graph.DefaultWriteContext.write(Contexts.kt:109)
        at org.gradle.internal.serialize.graph.BeanPropertyExtensionsKt.writePropertyValue(BeanPropertyExtensions.kt:34)
        ... 110 more
```
