### ISSUE TITLE
DirectoryProperty doesn't work with `=` when assigning `Provider<Directory>` with Groovy

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#25706]
When changing [this line in docs/build.gradle](https://github.com/gradle/gradle/blob/2ed794211440d14192b853519b09e9fb815de49a/subprojects/docs/build.gradle#L591C5-L591C105):
```
installationEnvProvider.samplesdir.set(project.layout.buildDirectory.dir("working/samples/testing"))
```

to:
```
installationEnvProvider.samplesdir = project.layout.buildDirectory.dir("working/samples/testing")
``` 

Gradle throws:
```
Caused by: groovy.lang.ReadOnlyPropertyException: Cannot set readonly property: samplesdir for class: GradleInstallationForTestEnvironmentProvider
        at build_eg0kubr2vitheakeptlnomh4o$_run_closure14.doCall(/Users/asodja/workspace/gradle/subprojects/docs/build.gradle:591)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.util.internal.ClosureBackedAction.execute(ClosureBackedAction.java:73)
        at org.gradle.util.internal.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
        at org.gradle.util.internal.ConfigureUtil.configureSelf(ConfigureUtil.java:131)
        at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:702)
        at org.gradle.api.DefaultTask.configure(DefaultTask.java:319)
        at org.gradle.api.DefaultTask.configure(DefaultTask.java:45)
        at org.gradle.util.internal.ConfigureUtil.configure(ConfigureUtil.java:104)
        at org.gradle.util.internal.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:167)
        at org.gradle.api.internal.DefaultMutationGuard$1.execute(DefaultMutationGuard.java:45)
        at org.gradle.api.internal.DefaultMutationGuard$1.execute(DefaultMutationGuard.java:45)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:123)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:110)
```

SamplesDir is defined as https://github.com/gradle/gradle/blob/2ed794211440d14192b853519b09e9fb815de49a/subprojects/docs/build.gradle#L819-L821

Lets figure out why.

How to reproduce: update the problematic line and run:
```
 ./gradlew :docs:docsTest --dry-run --stacktrace
 ```

**Comment by asodja** [comment]
Actually the issue is, that the type `GradleInstallationForTestEnvironmentProvider` was not created with `ObjectFactory`.
