### ISSUE TITLE
Improve error messaging of built-in providers

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#25716]
### Expected Behavior

An exception message that contains the environment variable name that could not be found rather than "this provider".

Doing a short debug in `AbstractMinimalProvider`, it seems that `cannotQueryValueOf` is totally ready for a nice message via `getDisplayName()`, and even a causal chain.

It seems that adding the following method to `DefaultValueSourceProviderFactory.ValueSourceProvider` would solve this problem:
```java
@Override protected String getDeclaredDisplayName() {
  ValueSource source = value.source();
  return source instanceof Describable ? source.getDisplayName() : super.getDeclaredDisplayName();
}
```
`LazilyObtainedValue` might need some adjustments to cache the `source` along with the value too if it has been obtained.

### Current Behavior (optional)

```gradle
providers.environmentVariable("NON_EXISTENT_ENV_VAR").get()
```

```
org.gradle.api.internal.provider.MissingValueException: Cannot query the value of this provider because it has no value available.
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:75)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:93)
        at Build_gradle....(build.gradle.kts:78)
```

If possible, taking it a step further:
```gradle
providers.environmentVariable("NON_EXISTENT_ENV_VAR").map(::File).get()
```
should still contain the root cause in some form.

### Context

To improve developer experience, and bring down diagnostic time.

**Comment by mlopatkin** [comment]
This feature request is in the backlog of the relevant team and is prioritized by them.
***

If you are interested in contributing to Gradle, this issue is actionable and ready for contribution but might be challenging for first-time contributors.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

**Comment by cmacfarl** [comment]
I recently spent a couple of days trying to figure out why Gradle was throwing this error when attempting to publish a library module to maven.

```
* What went wrong:
Could not determine the dependencies of task ':RobotCore:publishReleasePublicationTo<elided>'.
> Cannot query the value of this property because it has no value available.
```

Wherein the publications block of the maven plugin defines version as

```
version System.getenv("PUBLISH_VERSION")
```

And because I was doing work to implement product flavors in the application that has a dependency on this module I ran down the wrong path thinking I had broken something in the library's maven publishing because of the unrelated work for product flavors in the application.  When in reality, because this was a testing workspace and not a real release environment, I had simply forgotten to set the PUBLISH_VERSION environment variable.

This is a classic example of Gradle's penchant for error messaging that is extremely obtuse.  At the very least referencing the name of the property that has no value would be useful and help the user much more quickly realize what went wrong.   Optimally, being able to reference the line of Gradle DSL causing the problem would have resulted in a solution immediately.
