### ISSUE TITLE
Support a Windows filesystem GRADLE_USER_HOME from WSL

### ISSUE THREAD

**Issue by ianbrandt** [gradle/gradle#25723]
### Expected Behavior

Running `gradlew` from WSL with `GRADLE_USER_HOME` set to a Windows filesystem location works.

### Current Behavior (optional)

I get the following error:

```text
$ ./gradlew help --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Could not write cache value to '/mnt/c/Dev/.gradle/daemon/8.2.1/registry.bin'.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.GradleException: Could not write cache value to '/mnt/c/Dev/.gradle/daemon/8.2.1/registry.bin'.
        at org.gradle.cache.internal.FileBackedObjectHolder.serialize(FileBackedObjectHolder.java:133)
        at org.gradle.cache.internal.FileBackedObjectHolder.access$100(FileBackedObjectHolder.java:34)
        at org.gradle.cache.internal.FileBackedObjectHolder$2.run(FileBackedObjectHolder.java:62)
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.doWriteAction(DefaultFileLockManager.java:216)
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.writeFile(DefaultFileLockManager.java:206)
        at org.gradle.cache.internal.OnDemandFileAccess.writeFile(OnDemandFileAccess.java:63)
        at org.gradle.cache.internal.FileBackedObjectHolder.set(FileBackedObjectHolder.java:59)
        at org.gradle.cache.internal.FileIntegrityViolationSuppressingObjectHolderDecorator.set(FileIntegrityViolationSuppressingObjectHolderDecorator.java:42)
        at org.gradle.cache.internal.FileIntegrityViolationSuppressingObjectHolderDecorator.doUpdate(FileIntegrityViolationSuppressingObjectHolderDecorator.java:70)
        at org.gradle.cache.internal.FileIntegrityViolationSuppressingObjectHolderDecorator.update(FileIntegrityViolationSuppressingObjectHolderDecorator.java:47)
        at org.gradle.launcher.daemon.registry.PersistentDaemonRegistry.removeStopEvents(PersistentDaemonRegistry.java:208)
        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.handleStopEvents(DefaultDaemonConnector.java:145)
        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connect(DefaultDaemonConnector.java:137)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:144)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:98)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:57)
[...]
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:103)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:66)
Caused by: org.gradle.internal.file.FileException: Could not set file mode 700 on '/mnt/c/Dev/.gradle/daemon/8.2.1'.
        at org.gradle.internal.nativeintegration.filesystem.services.GenericFileSystem.chmod(GenericFileSystem.java:115)
        at org.gradle.cache.internal.FileBackedObjectHolder.serialize(FileBackedObjectHolder.java:124)
        ... 47 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not set UNIX mode on /mnt/c/Dev/.gradle/daemon/8.2.1: could not chmod file (errno 1: Operation not permitted)
        at net.rubygrapefruit.platform.internal.DefaultPosixFiles.setMode(DefaultPosixFiles.java:65)
        at org.gradle.internal.nativeintegration.filesystem.services.NativePlatformBackedChmod.chmod(NativePlatformBackedChmod.java:33)
        at org.gradle.internal.nativeintegration.filesystem.services.GenericFileSystem.chmod(GenericFileSystem.java:113)
        ... 48 more
```

I tried deleting the existing `/mnt/c/Dev/.gradle/daemon` directory and rerunning, but received the same error.

I haven't changed any permissions, so I have what I believe to be the defaults for WSL:

```text
$ ls -al /mnt/c/Dev/.gradle/daemon/8.2.1
total 0
drwxrwxrwx 1 root root 512 Jul 11 13:28 .
drwxrwxrwx 1 root root 512 Jul 11 13:28 ..
-rwxrwxrwx 1 root root   0 Jul 11 13:28 registry.bin
-rwxrwxrwx 1 root root  17 Jul 11 13:28 registry.bin.lock
```

WSL file permissions reference: https://learn.microsoft.com/en-us/windows/wsl/file-permissions.

### Context

Per #25721, I'd like to use Bash/Zsh over Powershell for development on Windows via Windows Subsystem for Linux.

WSL supports [sharing environment variables from Windows to Linux](https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/#wsl-and-environment-variables-after-insider-17063). As such, I can set the `GRADLE_USER_HOME` for my WSL shell to be the same as for my Windows environment by setting `WSLENV` to `GRADLE_USER_HOME/up` in the environment variables for my user account in Windows. My WSL distribution is the current default Ubuntu install, and I've installed 'openjdk-11-jdk' via `apt`.

The goal is to share the same caches when running from Windows or WSL, so as not to have to download all my upstream dependencies twice.

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

We are not 100% that it is a Gradle-only problem, and nothing from the environment is involved. Could you please add a detailed list of steps required to reproduce this issue?

**Comment by ianbrandt** [comment]
Certainly,

I'm on Windows 10, Version 21H2, Build 19044.3086.

I installed WSL via [Software Center](https://learn.microsoft.com/en-us/mem/configmgr/core/understand/software-center) (my company blocks direct access to the Microsoft Store). This took the place of an [initial run of `wsl --install`](https://learn.microsoft.com/en-us/windows/wsl/install#install-wsl-command).

I opened an unprivileged PowerShell window, and ran `wsl --install -d Ubuntu`. We're not given Administrator permissions on our machines, so I couldn't install the distribution via PowerShell run as Administrator. My assumption is that Administrator is only required for the initial `wsl --install`, or a Windows permissions policy is in place at my company to allow Linux distribution installation as a regular user. I'm far from a Windows or WSL expert, so I can't offer much more here other than the installation succeeded without error.

I opened "Edit environment variables for your account" in Control Panel. I already had `GRADLE_USER_HOME` set to 'C:\Dev\.gradle' for my Windows development. I added a `WSLENV` entry with the value 'GRADLE_USER_HOME/up'.

I opened a new Ubuntu terminal window, and tested that setting `WSLENV` resulted in the `GRADLE_USER_HOME` value being propagated into the Linux environment. It did:

```text
$ echo $GRADLE_USER_HOME
/mnt/c/Dev/.gradle
```

I changed directory to my project, ran `./gradlew help`, and received the reported error.

**Comment by ianbrandt** [comment]
Looking into this more, I realized that despite having installed WSL 2, the default version for new Linux distributions was still 1.

I've upgraded my distribution from an unprivileged PowerShell window with `wsl --set-version Ubuntu 2`.

I confirmed the upgrade from PowerShell:

```text
> wsl --list --verbose
  NAME      STATE           VERSION
* Ubuntu    Running         2
```

Now I get:

```text
$ ./gradlew help --stacktrace
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Gradle could not start your build.
> Cannot create service of type BuildSessionActionExecutor using method LauncherServices$ToolingBuildSessionScopeServices.createActionExecutor() as there is a problem with parameter #21 of type FileSystemWatchingInformation.
   > Cannot create service of type BuildLifecycleAwareVirtualFileSystem using method VirtualFileSystemServices$GradleUserHomeServices.createVirtualFileSystem() as there is a problem with parameter #7 of type GlobalCacheLocations.
      > Cannot create service of type GlobalCacheLocations using method GradleUserHomeScopeServices.createGlobalCacheLocations() as there is a problem with parameter #1 of type List<GlobalCache>.
         > Could not create service of type FileAccessTimeJournal using GradleUserHomeScopeServices.createFileAccessTimeJournal().
            > java.io.IOException: Input/output error

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.initialization.exception.InitializationException: Gradle could not start your build.
        at org.gradle.initialization.exception.DefaultExceptionAnalyser.collectFailures(DefaultExceptionAnalyser.java:58)
        at org.gradle.initialization.exception.MultipleBuildFailuresExceptionAnalyser.transform(MultipleBuildFailuresExceptionAnalyser.java:55)
        at org.gradle.initialization.exception.MultipleBuildFailuresExceptionAnalyser.transform(MultipleBuildFailuresExceptionAnalyser.java:38)
        at org.gradle.initialization.exception.StackTraceSanitizingExceptionAnalyser.transform(StackTraceSanitizingExceptionAnalyser.java:33)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:38)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
        at org.gradle.util.internal.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:64)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: org.gradle.internal.service.ServiceCreationException: Cannot create service of type BuildSessionActionExecutor using method LauncherServices$ToolingBuildSessionScopeServices.createActionExecutor() as there is a problem with parameter #21 of type FileSystemWatchingInformation.
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.bind(DefaultServiceRegistry.java:815)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.prepare(DefaultServiceRegistry.java:700)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.getService(DefaultServiceRegistry.java:723)
        at org.gradle.internal.service.DefaultServiceRegistry$OwnServices.getService(DefaultServiceRegistry.java:450)
        at org.gradle.internal.service.DefaultServiceRegistry$CompositeServiceProvider.getService(DefaultServiceRegistry.java:1008)
        at org.gradle.internal.service.DefaultServiceRegistry.find(DefaultServiceRegistry.java:1094)
        at org.gradle.internal.service.DefaultServiceRegistry.getService(DefaultServiceRegistry.java:329)
        at org.gradle.internal.service.DefaultServiceRegistry.find(DefaultServiceRegistry.java:323)
        at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:308)
        at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:303)
        at org.gradle.internal.session.DefaultBuildSessionContext.execute(DefaultBuildSessionContext.java:46)
        at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter$ActionImpl.apply(BuildSessionLifecycleBuildActionExecuter.java:100)
        at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter$ActionImpl.apply(BuildSessionLifecycleBuildActionExecuter.java:88)
        at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:69)
        at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildActionExecuter.java:62)
        at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildActionExecuter.java:41)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:64)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:32)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:50)
        ... 29 more
Caused by: org.gradle.internal.service.ServiceCreationException: Cannot create service of type BuildLifecycleAwareVirtualFileSystem using method VirtualFileSystemServices$GradleUserHomeServices.createVirtualFileSystem() as there is a problem with parameter #7 of type GlobalCacheLocations.
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.bind(DefaultServiceRegistry.java:815)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.prepare(DefaultServiceRegistry.java:700)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.getService(DefaultServiceRegistry.java:723)
        at org.gradle.internal.service.DefaultServiceRegistry$OwnServices.getService(DefaultServiceRegistry.java:450)
        at org.gradle.internal.service.DefaultServiceRegistry$CompositeServiceProvider.getService(DefaultServiceRegistry.java:1008)
        at org.gradle.internal.service.DefaultServiceRegistry$ParentServices.getService(DefaultServiceRegistry.java:1062)
        at org.gradle.internal.service.DefaultServiceRegistry$CompositeServiceProvider.getService(DefaultServiceRegistry.java:1008)
        at org.gradle.internal.service.DefaultServiceRegistry$CompositeServiceProvider.getService(DefaultServiceRegistry.java:1008)
        at org.gradle.internal.service.DefaultServiceRegistry.find(DefaultServiceRegistry.java:1094)
        at org.gradle.internal.service.DefaultServiceRegistry.access$1600(DefaultServiceRegistry.java:83)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.bind(DefaultServiceRegistry.java:813)
        ... 47 more
Caused by: org.gradle.internal.service.ServiceCreationException: Cannot create service of type GlobalCacheLocations using method GradleUserHomeScopeServices.createGlobalCacheLocations() as there is a problem with parameter #1 of type List<GlobalCache>.
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.bind(DefaultServiceRegistry.java:815)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.prepare(DefaultServiceRegistry.java:700)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.getService(DefaultServiceRegistry.java:723)
        at org.gradle.internal.service.DefaultServiceRegistry$OwnServices.getService(DefaultServiceRegistry.java:450)
        at org.gradle.internal.service.DefaultServiceRegistry$CompositeServiceProvider.getService(DefaultServiceRegistry.java:1008)
        at org.gradle.internal.service.DefaultServiceRegistry.find(DefaultServiceRegistry.java:1094)
        at org.gradle.internal.service.DefaultServiceRegistry.access$1600(DefaultServiceRegistry.java:83)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.bind(DefaultServiceRegistry.java:813)
        ... 57 more
Caused by: org.gradle.internal.service.ServiceCreationException: Could not create service of type FileAccessTimeJournal using GradleUserHomeScopeServices.createFileAccessTimeJournal().
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:913)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.createServiceInstance(DefaultServiceRegistry.java:838)
        at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:623)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:686)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:851)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.createServiceInstance(DefaultServiceRegistry.java:837)
        at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:623)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:686)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:851)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.createServiceInstance(DefaultServiceRegistry.java:837)
        at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:623)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:686)
        at org.gradle.internal.service.DefaultServiceRegistry.getCollectionService(DefaultServiceRegistry.java:1141)
        at org.gradle.internal.service.DefaultServiceRegistry.getCollectionService(DefaultServiceRegistry.java:1123)
        at org.gradle.internal.service.DefaultServiceRegistry.find(DefaultServiceRegistry.java:1086)
        at org.gradle.internal.service.DefaultServiceRegistry.access$1600(DefaultServiceRegistry.java:83)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.bind(DefaultServiceRegistry.java:813)
        ... 64 more
Caused by: org.gradle.api.UncheckedIOException: java.io.IOException: Input/output error
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:62)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
        at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:113)
        at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.incrementLockCount(LockOnDemandCrossProcessCacheAccess.java:106)
        at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.acquireFileLock(LockOnDemandCrossProcessCacheAccess.java:168)
        at org.gradle.cache.internal.DefaultCacheCoordinator.onStartWork(DefaultCacheCoordinator.java:398)
        at org.gradle.cache.internal.DefaultCacheCoordinator.useCache(DefaultCacheCoordinator.java:239)
        at org.gradle.cache.internal.DefaultCacheCoordinator.useCache(DefaultCacheCoordinator.java:229)
        at org.gradle.cache.internal.DefaultCacheCoordinator.newCache(DefaultCacheCoordinator.java:320)
        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.createIndexedCache(DefaultPersistentDirectoryStore.java:173)
        at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.createIndexedCache(DefaultCacheFactory.java:199)
        at org.gradle.api.internal.changedetection.state.DefaultFileAccessTimeJournal.<init>(DefaultFileAccessTimeJournal.java:55)
        at org.gradle.internal.service.scopes.GradleUserHomeScopeServices.createFileAccessTimeJournal(GradleUserHomeScopeServices.java:227)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
        at org.gradle.internal.service.ReflectionBasedServiceMethod.invoke(ReflectionBasedServiceMethod.java:34)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:911)
        ... 80 more
Caused by: java.io.IOException: Input/output error
        at org.gradle.cache.internal.filelock.LockStateAccess.readState(LockStateAccess.java:69)
        at org.gradle.cache.internal.filelock.LockStateAccess.ensureLockState(LockStateAccess.java:46)
        at org.gradle.cache.internal.filelock.LockFileAccess.ensureLockState(LockFileAccess.java:57)
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.lock(DefaultFileLockManager.java:306)
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.<init>(DefaultFileLockManager.java:164)
        at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:110)
        ... 96 more


BUILD FAILED in 15s
```

A notable change is that with WSL 2, my Windows filesystem files are now reported as owned by my regular Linux user and and group, rather than root:

```text
$ ls -al /mnt/c/Dev/.gradle/daemon/8.2.1
total 316
drwxrwxrwx 1 ibrandt ibrandt    512 Jul 17 12:24 .
drwxrwxrwx 1 ibrandt ibrandt    512 Jul 11 14:55 ..
-rwxrwxrwx 1 ibrandt ibrandt  57967 Jul 17 08:54 daemon-147.out.log
-rwxrwxrwx 1 ibrandt ibrandt 190276 Jul 17 08:53 daemon-21800.out.log
-rwxrwxrwx 1 ibrandt ibrandt  42054 Jul 17 12:26 daemon-479.out.log
-rwxrwxrwx 1 ibrandt ibrandt   1267 Jul 17 12:24 registry.bin
-rwxrwxrwx 1 ibrandt ibrandt     17 Jul 17 12:24 registry.bin.lock
```

**Comment by ov7a** [comment]
Sounds like a WSL problem to me. 

I suppose the first error was related to permissions, and I don't think Gradle caused it.

For the second problem, there are multiple reports for other products with the same `java.io.IOException: Input/output error` issue related to WSL. Some recommendations for solving these issues:
* [Restart](https://github.com/microsoft/WSL/issues/4377) `wslhost.exe`
* [Upgrade JVM versions](https://discuss.elastic.co/t/profiling-inferred-spans-enabled-causes-ioexception-input-output-error-when-closing-a-filestream-on-a-nas-server-that-uses-windows/254911)
* Make sure the Gradle process has required permissions to write to target directories and it is not prevented by any sort of antimalware protection.

In both cases, the error message can be improved though.
