### ISSUE TITLE
JUnitJupiterCategoriesOrTagsCoverageIntegrationTest#"can combine tags with custom extension" fails on German OS

### ISSUE THREAD

**Issue by zeners** [gradle/gradle#25947]
### Expected Behavior

`./gradlew gradle testing-jvm:quickTest `
shouldn't fail, if running under other than english language operating system

### Current Behavior

`./gradlew testing-jvm:quickTest` 
fails under german Language-settings on current master (72387fd3cd969661629a90398cca346f663275fa) with

```
JUnitJupiterCategoriesOrTagsCoverageIntegrationTest
can combine tags with custom extension 5.9.2

Condition failed with Exception:

result.testClass("SomeLocaleTests").assertTestsExecuted( result.testCase('ok1(Locale)[1]', 'French'), result.testCase('ok1(Locale)[2]', 'German'), result.testCase('ok1(Locale)[3]', 'English') )
|      |                            |                    |      |                                     |      |                                     |      |
|      |                            |                    |      |                                     |      |                                     |      org.gradle.integtests.fixtures.DefaultTestExecutionResult$DefaultTestCase(ok1(Locale)[3], English, [])
|      |                            |                    |      |                                     |      |                                     <org.gradle.integtests.fixtures.DefaultTestExecutionResult@5474ae5 results=[org.gradle.integtests.fixtures.HtmlTestExecutionResult@7be083f7, org.gradle.integtests.fixtures.JUnitXmlTestExecutionResult@558cd652] htmlResult=org.gradle.integtests.fixtures.HtmlTestExecutionResult@7be083f7 xmlResult=org.gradle.integtests.fixtures.JUnitXmlTestExecutionResult@558cd652>
|      |                            |                    |      |                                     |      org.gradle.integtests.fixtures.DefaultTestExecutionResult$DefaultTestCase(ok1(Locale)[2], German, [])
|      |                            |                    |      |                                     <org.gradle.integtests.fixtures.DefaultTestExecutionResult@5474ae5 results=[org.gradle.integtests.fixtures.HtmlTestExecutionResult@7be083f7, org.gradle.integtests.fixtures.JUnitXmlTestExecutionResult@558cd652] htmlResult=org.gradle.integtests.fixtures.HtmlTestExecutionResult@7be083f7 xmlResult=org.gradle.integtests.fixtures.JUnitXmlTestExecutionResult@558cd652>
|      |                            |                    |      org.gradle.integtests.fixtures.DefaultTestExecutionResult$DefaultTestCase(ok1(Locale)[1], French, [])
|      |                            |                    <org.gradle.integtests.fixtures.DefaultTestExecutionResult@5474ae5 results=[org.gradle.integtests.fixtures.HtmlTestExecutionResult@7be083f7, org.gradle.integtests.fixtures.JUnitXmlTestExecutionResult@558cd652] htmlResult=org.gradle.integtests.fixtures.HtmlTestExecutionResult@7be083f7 xmlResult=org.gradle.integtests.fixtures.JUnitXmlTestExecutionResult@558cd652>
|      |                            Assertion failed: 
|      |                             
|      |                            assert executedAndNotSkipped.containsAll(testCases)
|      |                                   |                     |           |
|      |                                   |                     false       [org.gradle.integtests.fixtures.DefaultTestExecutionResult$DefaultTestCase(ok1(Locale)[1], French, []), org.gradle.integtests.fixtures.DefaultTestExecutionResult$DefaultTestCase(ok1(Locale)[2], German, []), org.gradle.integtests.fixtures.DefaultTestExecutionResult$DefaultTestCase(ok1(Locale)[3], English, [])]
|      |                                   [org.gradle.integtests.fixtures.DefaultTestExecutionResult$DefaultTestCase(ok1(Locale)[1], Französisch, []), org.gradle.integtests.fixtures.DefaultTestExecutionResult$DefaultTestCase(ok1(Locale)[2], Deutsch, []), org.gradle.integtests.fixtures.DefaultTestExecutionResult$DefaultTestCase(ok1(Locale)[3], Englisch, [])]
|      |                             
|      |                            	at org.gradle.integtests.fixtures.HtmlTestExecutionResult$HtmlTestClassExecutionResult.assertTestsExecuted(HtmlTestExecutionResult.groovy:141)
|      |                            	at org.gradle.integtests.fixtures.DefaultTestExecutionResult$DefaultTestClassExecutionResult.assertTestsExecuted(DefaultTestExecutionResult.groovy:172)
|      |                            	at org.gradle.testing.junit.jupiter.JUnitJupiterCategoriesOrTagsCoverageIntegrationTest.can combine tags with custom extension(JUnitJupiterCategoriesOrTagsCoverageIntegrationTest.groovy:261)
|      <org.gradle.integtests.fixtures.DefaultTestExecutionResult$DefaultTestClassExecutionResult@6aa3be64 testClassResults=[org.gradle.integtests.fixtures.HtmlTestExecutionResult$HtmlTestClassExecutionResult@1688a544, org.gradle.integtests.fixtures.JUnitTestClassExecutionResult@69887359] this$0=org.gradle.integtests.fixtures.DefaultTestExecutionResult@5474ae5>
<org.gradle.integtests.fixtures.DefaultTestExecutionResult@5474ae5 results=[org.gradle.integtests.fixtures.HtmlTestExecutionResult@7be083f7, org.gradle.integtests.fixtures.JUnitXmlTestExecutionResult@558cd652] htmlResult=org.gradle.integtests.fixtures.HtmlTestExecutionResult@7be083f7 xmlResult=org.gradle.integtests.fixtures.JUnitXmlTestExecutionResult@558cd652>

	at org.gradle.testing.junit.jupiter.JUnitJupiterCategoriesOrTagsCoverageIntegrationTest.can combine tags with custom extension(JUnitJupiterCategoriesOrTagsCoverageIntegrationTest.groovy:261)
Caused by: Assertion failed: 

assert executedAndNotSkipped.containsAll(testCases)
       |                     |           |
       |                     false       [org.gradle.integtests.fixtures.DefaultTestExecutionResult$DefaultTestCase(ok1(Locale)[1], French, []), org.gradle.integtests.fixtures.DefaultTestExecutionResult$DefaultTestCase(ok1(Locale)[2], German, []), org.gradle.integtests.fixtures.DefaultTestExecutionResult$DefaultTestCase(ok1(Locale)[3], English, [])]
       [org.gradle.integtests.fixtures.DefaultTestExecutionResult$DefaultTestCase(ok1(Locale)[1], Französisch, []), org.gradle.integtests.fixtures.DefaultTestExecutionResult$DefaultTestCase(ok1(Locale)[2], Deutsch, []), org.gradle.integtests.fixtures.DefaultTestExecutionResult$DefaultTestCase(ok1(Locale)[3], Englisch, [])]

	at org.gradle.integtests.fixtures.HtmlTestExecutionResult$HtmlTestClassExecutionResult.assertTestsExecuted(HtmlTestExecutionResult.groovy:141)
	at org.gradle.integtests.fixtures.DefaultTestExecutionResult$DefaultTestClassExecutionResult.assertTestsExecuted(DefaultTestExecutionResult.groovy:172)
	... 1 more
```

### Context (optional)

on verifying pull request meet requirement: 

> Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Steps to Reproduce

1. checkout current master
2.  run `./gradlew :testing-jvm:embeddedIntegTest --tests "org.gradle.testing.junit.jupiter.JUnitJupiterCategoriesOrTagsCoverageIntegrationTest"` under German language settings

### Gradle version

8.3 (commit 72387fd3cd969661629a90398cca346f663275fa)

**Comment by ov7a** [comment]
Thank you for providing a valid reproducer.

Thank you for providing a PR with the fix, we'll push it through CI.
