### ISSUE TITLE
Gradle 8.0.2 -> 8.1.0 broke my app

### ISSUE THREAD

**Issue by ashishb** [gradle/gradle#25957]
### Expected Behavior

Android app should not crash

### Current Behavior

Android app built with 8.1.0 crashes.
Stack trace is attached.

### Context (optional)

```
Caused by java.lang.InstantiationException: java.lang.Class<r9.a> has no zero argument constructor
       at java.lang.Class.newInstance(Class.java)
       at com.google.api.client.util.Types.newInstance(Types.java:113)
       at com.google.api.client.util.Data.newMapInstance(Data.java:550)
       at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:766)
       at com.google.api.client.json.JsonParser.parse(JsonParser.java:360)
       at com.google.api.client.json.JsonParser.parse(JsonParser.java:335)
       at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:79)
       at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:73)
       at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:162)
       at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:139)
       at net.ashishb.androidmusicplayer.util.GoogleAccountHelper.getServiceAccountCredentials(GoogleAccountHelper.java:79)
       at net.ashishb.androidmusicplayer.network.GoogleDriveHelper.<init>(GoogleDriveHelper.java:167)
       at net.ashishb.androidmusicplayer.GoogleDriveManager.initGoogleDriveHelper(GoogleDriveManager.java:81)
       at net.ashishb.androidmusicplayer.MusicApplication.initGoogleDriveHelper(MusicApplication.java:212)
       at net.ashishb.androidmusicplayer.MusicApplication.lambda$onCreate$0(MusicApplication.java:120)
```

### Steps to Reproduce

The stack trace should suffice as the crash is Google's library.
I don't believe that the crash is specific to my app.

### Gradle version

8.1.0

### Gradle version that used to work

8.0.2

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

This is an issue with the Android Gradle Plugin, which is developed by Google and cannot be addressed in the Gradle Build Tool project.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/docs/setup/contribute/report-bugs#filing-a-bug
