### ISSUE TITLE
On timeout, offer more helpful stacktrace for worker API tasks

### ISSUE THREAD

**Issue by mathjeff** [gradle/gradle#26090]
### Current Behavior

I'm observing that when a task using the worker API times out, neither the task nor its workers appear to be listed under "Current stacktrace of timed out but not yet stopped task"

### Expected Behavior

It could be helpful if Gradle could include a stacktrace for the threads that are still working: at least the threads spawned by Gradle

### Context (optional)

In AndroidX we've started observing the Kotlin compiler timing out ( https://issuetracker.google.com/issues/295212080 ) but the stack trace listed from Gradle doesn't mention what the Gradle worker is doing.

It could be easier for us to diagnose it if Gradle can give more details about what is happening when the task times out.

In the specific case of the Kotlin compiler, it wouldn't surprise me if Gradle just points to a line of code where the Kotlin compiler is forking and waiting for a process, although it could still help in this case to be sure that that's what's going on.

### Steps to Reproduce

See https://github.com/mathjeff/gradle-samples-2/tree/main/timeout-stacktrace

### Gradle version

8.3-rc-1

**Comment by jbartok** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

**Comment by ericoporto** [comment]
This would be pretty useful, on timeout there is no useful information.

**Comment by mathjeff** [comment]
We ended up figuring out the cause of our task timeouts so we don't need this in androidx at the moment.

Interestingly enough, though, in our case it did end up being helpful to get the stacktrace of the Gradle Daemon (manually via `jstack`), because there had been a thread in the Gradle Daemon (running code from the kotlin plugin) that seemed to be doing something that we hadn't expected:

```
jdk.proxy6.$Proxy165.getDaemonJVMOptions(jdk.proxy6/Unknown Source)
```

(https://youtrack.jetbrains.com/issue/KT-61306/Unresponsive-compiler-daemon-blocking-subsequent-builds)

**Comment by mathjeff** [comment]
We encountered this again with a different task: https://issuetracker.google.com/issues/309773103#comment12 .

For now, we're spawning a separate monitoring process that after 1 hour gets a stacktrace from each jvm process, see https://r.android.com/2815713

**Comment by ganadist** [comment]
I have similar case : https://issuetracker.google.com/issues/398904335
And in my case, I added following logic on build script.
```
    tasks.withType<ManagedDeviceInstrumentationTestTask>().configureEach {
        timeout.set(
            Duration.ofMinutes(androidTestTimeout)
        )
    }
```

This can prevent excessive build time from being consumed, but it can be difficult to pinpoint the cause.
Because gradle don't show enough information why timeout was exceeded.
Gradle just shows

* console log:
```
:module1:gmdDebugAndroidTest FAILED

FAILURE: Build failed with an exception.        

* What went wrong:      
Execution failed for task ':module1:gmdDebugAndroidTest'.       
> Timeout has been exceeded   
```
* stacktrace:
```
Exception
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':module1:gmdDebugAndroidTest'.  
at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)       
•••
  Caused by: org.gradle.api.GradleException: Timeout has been exceeded  
  at org.gradle.internal.execution.steps.TimeoutStep.executeWithTimeout(TimeoutStep.java:69)   
```

If gradle shows full stacktraces of all threads when task has timeout, this will be very helpful in determining the cause of the problem (especially tasks provided by 3rd party plugins).
