### ISSUE TITLE
./gradlew on new project results in timeout downloading gradle-8.2-bin.zip

### ISSUE THREAD

**Issue by AirborneDetergent** [gradle/gradle#26094]
### Current Behavior

When you make a new project in IntelliJ, you get an error after it tries to download gradle:
![image](https://github.com/gradle/gradle/assets/78456403/8cb21a8a-4b63-4d9a-89ea-c7d92ee400b0)
It usually stops at either 1.06MB or 2.11MB before it switches to a cycling progress bar and then errors out.
Upon executing ./gradlew in the terminal, you get this error after waiting a few seconds:
```
Exception in thread "main" java.io.IOException: Downloading from https://services.gradle.org/distributions/gradle-8.2-bin.zip failed: timeout
        at org.gradle.wrapper.Download.downloadInternal(Download.java:122)
        at org.gradle.wrapper.Download.download(Download.java:80)
        at org.gradle.wrapper.Install$1.call(Install.java:83)
        at org.gradle.wrapper.Install$1.call(Install.java:63)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:63)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
        at sun.security.ssl.SSLSocketInputRecord.readFully(Unknown Source)
        at sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(Unknown Source)
        at sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
        at sun.security.ssl.SSLTransport.decode(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.access$300(Unknown Source)
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source)
        at java.io.BufferedInputStream.read1(Unknown Source)
        at java.io.BufferedInputStream.read(Unknown Source)
        at sun.net.www.MeteredStream.read(Unknown Source)
        at java.io.FilterInputStream.read(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:106)
        ... 7 more
```

### Expected Behavior

It should download gradle and set the project up properly.

### Context (optional)

It first started when I tried to make a LibGDX project. It's worth noting that while this issue occurs in IntelliJ, it's not isolated to IntelliJ. The LibGDX setup utility gave the same error (with a slightly different version of gradle.zip listed). Now, I can't create ANY new Java gradle projects. My installations were nuked and replaced AFTER trying to use LibGDX.

This issue is a continuation from https://github.com/libgdx/libgdx/issues/7208 because I felt it made more sense to put it here.

### Steps to Reproduce

1. Install IntelliJ
2. Install Java
3. Attempt to create a gradle Java project
4. Wait about a minute to see the first (IntelliJ) error
5. Run `./gradlew` in the terminal to see the other error, which has a nice stack trace

### Gradle version

8.2

### Your Environment (optional)

Windows 10, issue persisted across a fresh re-installation of both Java and IntelliJ.

**Comment by tommyettinger** [comment]
I'm also continuing from the issue on libgdx/libgdx ; this is an exceptionally strange bug and I have never seen it before myself. This happened with Gradle 7.5.1 as well as what I believe was 8.2.1 (may have been 8.2). One of the possible clues is that `curl` fails to download Gradle from the URL printed in the output, though it does this for me also and my installation works fine. There's a 301 code from `curl` that redirects from https://services.gradle.org/distributions/gradle-7.5.1-bin.zip to https://downloads.gradle.org/distributions/gradle-7.5.1-bin.zip . Among the things tried were moving/renaming `~/.gradle/`, which apparently didn't help at all. It seems like there's some network error, I just have no idea how this might happen only for Gradle wrapper dists.

**Comment by AirborneDetergent** [comment]
Some additional info, tracert to services.gradle.org:
```
Tracing route to services.gradle.org [2606:4700::6811:a42]
over a maximum of 30 hops:

  1     6 ms     4 ms     4 ms  [CENSORED]
  2    15 ms    14 ms    14 ms  [CENSORED]
  3    13 ms    18 ms    12 ms  [CENSORED]
  4    11 ms    12 ms    12 ms  [CENSORED]
  5     *        *        *     Request timed out.
  6    27 ms    13 ms    13 ms  be-36111-cs01.seattle.wa.ibone.comcast.net [2001:558:3:940::1]
  7    13 ms    14 ms    22 ms  be-2112-pe12.seattle.wa.ibone.comcast.net [2001:558:3:a0::2]
  8    12 ms    13 ms    14 ms  as15169-4-c.56marietta.ga.ibone.comcast.net [2001:559::312]
  9    18 ms    20 ms    18 ms  2400:cb00:542:3::
 10    12 ms    11 ms    14 ms  2606:4700::6811:a42
```
I don't know enough about networking to be able to understand exactly what this means, but it definitely looks like there's something breaking along the way. It's worth noting that I still have zero issue downloading gradle from my browser, despite one of the hops timing out.

**Comment by AirborneDetergent** [comment]
The issue actually turned out not to be with gradle either. I still don't know why I was able to download gradle from my browser and not through gradlew, but rebooting my router again seems to have solved the issue. Thanks for putting me through hell, Comcast!
