### ISSUE TITLE
Improve error message when build uses unsupported JDK

### ISSUE THREAD

**Issue by donat** [gradle/gradle#26124]
I want to highlight the problem of running Gradle on newer unsupported JDK releases. Produced error is quite generic and does not help user to understand the cause. 

If user will try to rerun with --stacktrace he/she will see:
```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 64
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.lambda$visitEntries$1(InstrumentingClasspathFileTransformer.java:151)
        ... 15 more
```

It would be nice if Gradle could provide more user friendly error here - something like "Current version of Gradle does not yet support running on Java version <version>. Please check newer Gradle releases."

**Comment by ljacomet** [comment]
This issue will be closed as a duplicate of

* #13294

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.
