### ISSUE TITLE
Tooling API client running in Java 21 gets java.io.StreamCorruptedException: invalid type code: 01

### ISSUE THREAD

**Issue by nskvortsov** [gradle/gradle#26161]
### Current Behavior

When a tooling client runs on a Java 21 virtual machine and executes a `connection.action()` the return value fails to deserialize:

```
Caused by: org.gradle.api.UncheckedIOException: java.io.StreamCorruptedException: invalid type code: 01
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:62)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
	at org.gradle.tooling.internal.provider.serialization.PayloadSerializer.deserialize(PayloadSerializer.java:78)
	at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:226)
        ...
```

### Expected Behavior

The return value deserializes successfully.

### Context (optional)

IntelliJ IDEA plans to migrate to Java 21 in the future. We started running tests with pre-release versions of Java Runtime 21

### Steps to Reproduce

Please find attached [gradle-tapi-sample.zip](https://github.com/gradle/gradle/files/12407677/gradle-tapi-sample.zip) with TAPI client and simple project.
Navigate to `gradle-tapi-client` and invoke `gradlew run` to observe the exception.

This sample is setup using Gradle Toolchains.
You can change the runtime level to 20 in the marked line in `build.gradle` file to get things working.

### Gradle version

8.0

### Your Environment (optional)

Windows 11, JDK11 + JDK21

**Comment by hegyibalint** [comment]
I have a trouble reproducing this on Windows 10, using the following JDKs:
```
 + Eclipse Temurin JDK 11.0.18+10
     | Location:           C:\Program Files\Java\open-jdk-11
     | Language Version:   11
     | Vendor:             Eclipse Temurin
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Current JVM

 + OpenJDK 21-ea+30-2426
     | Location:           C:\Program Files\Java\open-jdk-21-ea
     | Language Version:   21
     | Vendor:             Oracle
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        system property 'org.gradle.java.installations.paths'
```

@nskvortsov could you give me the same `./gradlew -q javaToolchains` output?

**Comment by nskvortsov** [comment]
Here is the output. I will try with the Oracle JDK [report.txt](https://github.com/gradle/gradle/files/12523590/report.txt)

**Comment by hegyibalint** [comment]
Can you give me also a precise JDK11 version, as I think it's also crucial to reproduce this.

**Comment by nskvortsov** [comment]
Seems  like it was something related to earlier JBR21 build (https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jbr-release-21b126.4)
I can not reproduce it with 21b212 posted earlier either.
Lets close the issue for now, I will request a re-open if I have new information.

**Comment by donat** [comment]
Closing as not not reproducible.

**Comment by nskvortsov** [comment]
Just for the record. We did a deeper investigation and found it is caused by a JDK bug: https://bugs.openjdk.org/browse/JDK-8309885

**Comment by nskvortsov** [comment]
It was fixed here: https://github.com/openjdk/jdk21/pull/15
