### ISSUE TITLE
VFS file watching doesn't work on ReFS disks on Windows (fatally on gradle 7.6, non-fatal on 8.3)

### ISSUE THREAD

**Issue by doctorpangloss** [gradle/gradle#26225]
### Current Behavior

VFS file watching breaks fatally on 7.6 and non-fatally on 8.3 when run on an ReFS volume.

### Expected Behavior

ReFS should work. Eventually everything will migrate to it.

### Context (optional)

This is going to affect people who use gradle to build on Windows in the cloud, which is all Windows server and may nowadays allocate ReFS on e.g. Kubernetes.

https://learn.microsoft.com/en-us/windows-server/storage/refs/refs-overview

### Steps to Reproduce

I'm not sure if these scripts can work in vanilla Windows 11, because I'm not sure you can install the Hyper-V-Powershell windows feature for it, but it's worth a try. Otherwise, you can fiddle around with disk manager to create a VHDX with ReFS.
 1. Execute the following script as an administrator to create a ReFS disk:
```pwsh
# not sure if you need these
# Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
# Install-WindowsFeature -Name Hyper-V-Tools

# as administrator
Install-WindowsFeature -Name Hyper-V-PowerShell
Import-Module Hyper-V

$vhdxPath = "C:/test.vhdx"
$vhdxSize = 1GB
$driveLetter = "X"
New-VHD -Path $vhdxPath -SizeBytes $vhdxSize -Dynamic
Mount-VHD -Path $vhdxPath

$disk = Get-Disk | Where-Object { $_.PartitionStyle -eq 'RAW' -and $_.Size -eq $vhdxSize }

if (-not $disk) {
    throw "Unable to find the recently mounted VHDX."
}

$disk | Initialize-Disk -PartitionStyle GPT
$partition = $disk | New-Partition -AssignDriveLetter -UseMaximumSize
$partition | Format-Volume -FileSystem ReFS -Confirm:$false
$partition | Set-Partition -NewDriveLetter $driveLetter
```

2. Execute this script to create a gradle project with VFS file watching

```pwsh

$directory = "X:/test"  # Path where you want the new project to be initialized

if (-not (Test-Path $directory)) {
    New-Item -Path $directory -ItemType Directory
}

Set-Location -Path $directory
gradle init --type java-application --dsl groovy --test-framework junit --project-name test --package com.test
Add-Content -Path "./gradle.properties" -Value "`norg.gradle.vfs.watch=true"
gradle test
```
3. Observe the following error:
```pwsh
PS X:\test> gradle test
Error while receiving file changes
net.rubygrapefruit.platform.NativeException: Error received when handling events, error = 1: X:\test
        at net.rubygrapefruit.platform.internal.jni.AbstractNativeFileEventFunctions$NativeFileWatcher.executeRunLoop0(Native Method)
        at net.rubygrapefruit.platform.internal.jni.AbstractNativeFileEventFunctions$NativeFileWatcher.executeRunLoop(AbstractNativeFileEventFunctions.java:42)
        at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$AbstractFileWatcher$1.run(AbstractFileEventFunctions.java:154)
Stopping file watching and invalidating VFS after an error happened
```

 4. Rerun on NTFS. Observe everything works as expected.

```
Import-Module Hyper-V

$vhdxPath = "C:/test2.vhdx"  # Path to save the VHDX file
$vhdxSize = 1GB                    # Size of the VHDX
$driveLetter = "Y"                  # Drive letter to mount the VHDX
New-VHD -Path $vhdxPath -SizeBytes $vhdxSize -Dynamic
Mount-VHD -Path $vhdxPath

$disk = Get-Disk | Where-Object { $_.PartitionStyle -eq 'RAW' -and $_.Size -eq $vhdxSize }

if (-not $disk) {
    throw "Unable to find the recently mounted VHDX."
}

$disk | Initialize-Disk -PartitionStyle GPT
$partition = $disk | New-Partition -AssignDriveLetter -UseMaximumSize
$partition | Format-Volume -FileSystem NTFS -Confirm:$false
$partition | Set-Partition -NewDriveLetter $driveLetter

$directory = "Y:/test"  # Path where you want the new project to be initialized

if (-not (Test-Path $directory)) {
    New-Item -Path $directory -ItemType Directory
}

Set-Location -Path $directory
gradle init --type java-application --dsl groovy --test-framework junit --project-name test --package com.test
Add-Content -Path "./gradle.properties" -Value "`norg.gradle.vfs.watch=true"
gradle test
```

On Gradle 7.6, this error is critical. On 8.3, execution still succeeds but VFS fails.

### Gradle version

8.3

### Build scan URL (optional)

https://gradle.com/s/lnrgneqjleux2

### Your Environment (optional)

Windows 2022 LTSC (20348.1906)
```
java -version
openjdk version "20.0.2" 2023-07-18
OpenJDK Runtime Environment (build 20.0.2+9-78)
OpenJDK 64-Bit Server VM (build 20.0.2+9-78, mixed mode, sharing)
```

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by lptr** [comment]
I took a look today, but this is somewhat complicated as I need to get hold of an admin user on a Windows Pro or Enterprise edition, and that proves to be more complicated than I expected.

**Comment by lptr** [comment]
We ended up not being able to reproduce the issue on our infra internally, as creating a ReFS partition proved to be challenging. Before deciding whether it's worth investing more into this, I'd like to see more clearly.

FTR, Gradle's file-system watching (FSW) functionality officially does not support ReFS: https://docs.gradle.org/current/userguide/file_system_watching.html#supported_file_systems

You are forcing FSW to be enabled by setting `org.gradle.vfs.watch=true`. Do I understand correctly that without this Gradle correctly detects that it can't watch the ReFS volume, and continues without FSW? If that's the case then it works as designed.

Also note that file-system watching has little use in a cloud build environment. It is designed to help speed up consecutive builds in the same daemon. So you are not missing anything in the use case you listed, assuming Gradle decides automatically to disable FSW.

Please report back if not forcing FSW leads to a successful build. If not, then we probably need to fix this, but if it works, then I don't see us doing anything at this point. If ReFS becomes a popular choice for developers to use in their work environments, then we can reconsider.

**Comment by lptr** [comment]
Let me close this for now, please comment if you think the issue should be reopened.

**Comment by manodasanW** [comment]
> If ReFS becomes a popular choice for developers to use in their local work environments, then we can reconsider.

@lptr As an additional input, the latest Windows 11 update released recently added support for [Dev Drive](https://learn.microsoft.com/windows/dev-drive/) which is based on the `ReFs` file system and is targeted at developers for use in their dev environments.  The link has more details on Dev Drive, but it brings performance improvements targeted at developer workloads.  As a result, you may see more users running into this.

**Comment by doctorpangloss** [comment]
The underlying issue doesn't seem to be ReFS support. Ultimately the gradle team could not use my reproduction steps for powershell to create and test a ReFS disk easily. They had addressed ReFS disks before. There is an exception being thrown, I don't know how to drill down into that exception easily. It will probably be a 1 line change.

>  as creating a ReFS partition proved to be challenging. Before deciding whether it's worth investing more into this, I'd like to see more clearly.

I guess did you try my powershell scripts or not?

**Comment by sschuberth** [comment]
> as creating a ReFS partition proved to be challenging.

Actually, it's super easy now with the [instructions](https://learn.microsoft.com/windows/dev-drive/) already linked by @manodasanW.

**Comment by chrispoulsen** [comment]
I was just hit by this as well. I'm using a local "dev drive" (Windows 11, Java 20, Gradle 8.4). My gradle build is not using any special settings (no forcing `org.gradle.vfs.watch=true` or other properties set).

I ran out of disk space on my laptop and added a new drive. During setup Windows suggested creating a "dev drive" for better developer experience, so I did. 

Getting access to a ReFS filesystem should not be an issue anymore, it is almost forced upon you during setup.

My `C:` drive is NTFS, the "dev drive (ReFS)" `D:` 

Since I have a lot of existing projects, I chose to mount my "dev drive" into the old source folder on `C:` and copied the old data into the new drive - So I just got more space without changing the path.

Maybe this setup messes up the Gradle detection of supported filesystems? (`C:` is NTFS, while `C:\code` is ReFS).

I just tried executing `.\gradle build` on my `D:` drive, it also gives the error, so it is probably not the "mount/symlink" that is the issue.

**Comment by kslesinski-godaddy** [comment]
Same issue. It would be nice to add ReFS support.

**Comment by lptr** [comment]
I think the comments make a good argument for reopening this. Can't promise a timeline to adding support at this time, though.

**Comment by tcfurrer** [comment]
I dunno if this will helpful to anyone, but just in case...
Here is the exception stack trace I got when trying to run Gradle with both the git clone and GRADLE_USER_HOME located on a Dev Drive.

`Gradle was unable to watch the file system for changes
net.rubygrapefruit.platform.NativeException: Couldn't add watch, error = 1: D:\repos\repo
	at net.rubygrapefruit.platform.internal.jni.AbstractNativeFileEventFunctions$NativeFileWatcher.startWatching0(Native Method)
	at net.rubygrapefruit.platform.internal.jni.AbstractNativeFileEventFunctions$NativeFileWatcher.doStartWatching(AbstractNativeFileEventFunctions.java:49)
	at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$AbstractFileWatcher.startWatching(AbstractFileEventFunctions.java:181)
	at net.rubygrapefruit.platform.internal.jni.WindowsFileEventFunctions$WindowsFileWatcher.startWatching(WindowsFileEventFunctions.java:59)
	at org.gradle.internal.watch.registry.impl.HierarchicalFileWatcherUpdater.updateWatchesOnChangedWatchedFiles(HierarchicalFileWatcherUpdater.java:121)
	at org.gradle.internal.watch.registry.impl.AbstractFileWatcherUpdater.update(AbstractFileWatcherUpdater.java:141)
	at org.gradle.internal.watch.registry.impl.AbstractFileWatcherUpdater.virtualFileSystemContentsChanged(AbstractFileWatcherUpdater.java:90)
	at org.gradle.internal.watch.registry.impl.DefaultFileWatcherRegistry.virtualFileSystemContentsChanged(DefaultFileWatcherRegistry.java:153)
	at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem.lambda$updateNotifyingListeners$0(WatchingVirtualFileSystem.java:104)
	at org.gradle.internal.watch.registry.impl.SnapshotCollectingDiffListener.publishSnapshotDiff(SnapshotCollectingDiffListener.java:32)
	at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem.lambda$updateNotifyingListeners$1(WatchingVirtualFileSystem.java:103)
	at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem.lambda$withWatcherChangeErrorHandling$9(WatchingVirtualFileSystem.java:450)
	at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem.withWatcherChangeErrorHandling(WatchingVirtualFileSystem.java:457)
	at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem.withWatcherChangeErrorHandling(WatchingVirtualFileSystem.java:449)
	at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem.updateNotifyingListeners(WatchingVirtualFileSystem.java:103)
	at org.gradle.internal.vfs.impl.AbstractVirtualFileSystem.lambda$storeIfUnchanged$3(AbstractVirtualFileSystem.java:101)
	at org.gradle.internal.vfs.impl.AbstractVirtualFileSystem.lambda$updateRootUnderLock$0(AbstractVirtualFileSystem.java:60)
	at org.gradle.internal.vfs.impl.AbstractVirtualFileSystem.underLock(AbstractVirtualFileSystem.java:51)
	at org.gradle.internal.vfs.impl.AbstractVirtualFileSystem.updateRootUnderLock(AbstractVirtualFileSystem.java:58)
	at org.gradle.internal.vfs.impl.AbstractVirtualFileSystem.storeIfUnchanged(AbstractVirtualFileSystem.java:101)
	at org.gradle.internal.vfs.impl.AbstractVirtualFileSystem.lambda$store$1(AbstractVirtualFileSystem.java:91)
	at org.gradle.internal.vfs.impl.DefaultFileSystemAccess.lambda$snapshot$8(DefaultFileSystemAccess.java:172)
	at org.gradle.internal.vfs.impl.AbstractVirtualFileSystem.store(AbstractVirtualFileSystem.java:90)
	at org.gradle.internal.vfs.impl.DefaultFileSystemAccess.snapshot(DefaultFileSystemAccess.java:166)
	at org.gradle.internal.vfs.impl.DefaultFileSystemAccess.lambda$read$0(DefaultFileSystemAccess.java:92)`

**Comment by translatenix** [comment]
I've noticed that Gradle glob patterns are prohibitively slow on Windows.
I recently came across a task that used wide glob patterns and took 2s on macOS vs. 122s on Windows.
After optimizing the glob pattern, Windows improved to 3s.
I suspect this is caused by missing ReFS support.

In any case, it's very problematic that Gradle doesn't have good support for the *recommended* Windows dev setup.

**Comment by lptr** [comment]
> I've noticed that Gradle glob patterns are prohibitively slow on Windows. I recently came across a task that used "wide" glob patterns and took 2s on macOS vs. 122s on Windows. After optimizing the glob patterns, Windows improved to 3s. I suspect this is caused by missing ReFS support.

This seems like a separate issue. Can you please open one and describe your use case better? It would be ideal if you had a simple reproducer for the issue -- see https://github.com/gradle/gradle-issue-reproducer. Thanks!

> In any case, it's very problematic that Gradle doesn't have good support for the _recommended_ Windows dev setup.

I might have missed something here. Are you saying ReFS has been recommended as part of development environment setup by Microsoft? Can you please link to your source?

**Comment by lptr** [comment]
> I might have missed something here. Are you saying ReFS has been recommended as part of development environment setup by Microsoft? Can you please link to your source?

I think I found it: https://learn.microsoft.com/en-us/windows/dev-drive/

This is an article from August. There is also a blog post that is over a year old: https://devblogs.microsoft.com/visualstudio/devdrive/

**Comment by translatenix** [comment]
> Are you saying ReFS has been recommended as part of development environment setup by Microsoft? Can you please link to your source?

Windows 11, Settings->System->for developers

![Image](https://github.com/user-attachments/assets/8e99004b-8c97-4ef1-a58a-2e746aa15997)

"Learn more" links to your first article.

**Comment by lptr** [comment]
> I moved my projects and Gradle user home to a Dev Drive in the hope that this would speed up my Gradle builds. :-)

I see Microsoft has some specific instructions about running Gradle with dev drive. :o Might have been a good idea to reach out to make sure it works well. :) Anyway, we'll see what we can do, especially since ReFS has been such a neglected project for so long.

Anyway, Microsoft picking up ReFS and recommending it for developers is great. We've been thinking about sandboxed execution in Gradle for a long while, but file-systems with copy-on-write functionality haven't been widely available for all platforms. With APFS, btrfs and now ReFS we have all major platforms covered, though. I'm excited about this!

The biggest obstacle right now is our testing infrastructure: we are testing on Windows 10 to ensure backwards compatibility, and I don't think ReFS is available for our instances. We'll need to add some Windows 11 executors to test this, which might take some time. But we'll get there.
