### ISSUE TITLE
Cannot run Gradle Plugin Publish `PublishTask` - Extension of type 'GradlePluginDevelopmentExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension]

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#26238]
### Current Behavior

To try and workaround the issues with the Gradle Publish Plugin I manually register the PublishTask

```kotlin
tasks.register<PublishTask>(PUBLISH_TASK_NAME) {
  description = PUBLISH_TASK_DESCRIPTION
  group = PORTAL_BUILD_GROUP_NAME
  setBundleConfig(null)
  notCompatibleWithConfigurationCache("Plugin Publish plugin not yet compatible with Configuration Cache")
  dependOnPublishTasks();
}
```

When I run this task, I get a bizarre error:

```
Caused by: org.gradle.api.UnknownDomainObjectException: Extension of type 'GradlePluginDevelopmentExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension]
	at org.gradle.internal.extensibility.ExtensionsStorage.getHolderByType(ExtensionsStorage.java:88)
	at org.gradle.internal.extensibility.ExtensionsStorage.getByType(ExtensionsStorage.java:74)
	at org.gradle.internal.extensibility.DefaultConvention.getByType(DefaultConvention.java:175)
	at org.gradle.internal.extensibility.DefaultConvention.getByType(DefaultConvention.java:170)
	at com.gradle.publish.PublishTask.executeTask(PublishTask.java:76)
```

`java-gradle-plugin` is applied, so it doesn't make sense that the extension isn't present.

### Expected Behavior

Extensions added by plugins should be present.

Error messages contain useful information.

### Steps to Reproduce

[dokkatoo.zip](https://github.com/gradle/gradle/files/12487060/dokkatoo.zip)

### Gradle version

8.3

**Comment by jbartok** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

**Comment by big-guy** [comment]
@gradle/bt-extensibility-maintainers where should this issue be moved to?

**Comment by JavierSegoviaCordoba** [comment]
Getting this, the problem is that the plugin is not compatible with configuration cache.

**Comment by ov7a** [comment]
Given that the publishing plugin is now [CC-compatible](https://docs.gradle.org/9.1.0/release-notes.html#publishing-plugin-improvements), is there anything left to be done here? If there is still an issue, please provide a reproducer.
