### ISSUE TITLE
Could not add entry […] to cache sha1-checksums.bin

### ISSUE THREAD

**Issue by CLOVIS-AI** [gradle/gradle#26265]
Adding the Foojay plugin to a build creates thousands of checksum errors of the shape:

```
Failed to execute org.gradle.cache.internal.AsyncCacheAccessDecoratedCache$$Lambda$752/0x0000000100c18510@df5a3f3.
org.gradle.api.UncheckedIOException: Could not add entry '/home/[REDACTED]/.gradle/.tmp/gradle_download17513170584614972349bin' to cache sha1-checksums.bin (/home/[REDACTED]/playground/.gradle/8.2/checksums/sha1-checksums.bin).
```

From the number of messages, it seems virtually all files touched by Gradle generate this error.

<details>
<summary>Full stack trace</summary>

This is the trace for one specific example, but it appears thousands of times during the build with different files. The stack trace seems to always be exactly the same, so I'm only adding one.
```
Failed to execute org.gradle.cache.internal.AsyncCacheAccessDecoratedCache$$Lambda$752/0x0000000100c18510@df5a3f3.
org.gradle.api.UncheckedIOException: Could not add entry '/home/[REDACTED]/.gradle/.tmp/gradle_download17513170584614972349bin' to cache sha1-checksums.bin (/home/[REDACTED]/playground/.gradle/8.2/checksums/sha1-checksums.bin).
        at org.gradle.cache.internal.btree.BTreePersistentIndexedCache.put(BTreePersistentIndexedCache.java:162)
        at org.gradle.cache.internal.DefaultMultiProcessSafeIndexedCache.lambda$put$1(DefaultMultiProcessSafeIndexedCache.java:67)
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.doWriteAction(DefaultFileLockManager.java:216)
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.writeFile(DefaultFileLockManager.java:206)
        at org.gradle.cache.internal.DefaultCacheCoordinator$UnitOfWorkFileAccess.writeFile(DefaultCacheCoordinator.java:472)
        at org.gradle.cache.internal.DefaultMultiProcessSafeIndexedCache.put(DefaultMultiProcessSafeIndexedCache.java:67)
        at org.gradle.cache.internal.AsyncCacheAccessDecoratedCache.lambda$putLater$1(AsyncCacheAccessDecoratedCache.java:56)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.cache.internal.ExclusiveCacheAccessingWorker$2.run(ExclusiveCacheAccessingWorker.java:185)
        at org.gradle.internal.Factories$1.create(Factories.java:31)
        at org.gradle.cache.internal.DefaultCacheCoordinator.useCache(DefaultCacheCoordinator.java:248)
        at org.gradle.cache.internal.DefaultCacheCoordinator.useCache(DefaultCacheCoordinator.java:229)
        at org.gradle.cache.internal.ExclusiveCacheAccessingWorker.flushOperations(ExclusiveCacheAccessingWorker.java:175)
        at org.gradle.cache.internal.ExclusiveCacheAccessingWorker.run(ExclusiveCacheAccessingWorker.java:145)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.gradle.api.UncheckedIOException: java.io.IOException: Bad file descriptor
        at org.gradle.cache.internal.btree.FileBackedBlockStore.write(FileBackedBlockStore.java:140)
        at org.gradle.cache.internal.btree.CachingBlockStore.flush(CachingBlockStore.java:64)
        at org.gradle.cache.internal.btree.FreeListBlockStore.flush(FreeListBlockStore.java:103)
        at org.gradle.cache.internal.btree.StateCheckBlockStore.flush(StateCheckBlockStore.java:85)
        at org.gradle.cache.internal.btree.BTreePersistentIndexedCache.put(BTreePersistentIndexedCache.java:160)
        ... 18 more
Caused by: java.io.IOException: Bad file descriptor
        at java.base/java.io.RandomAccessFile.writeBytes(Native Method)
        at java.base/java.io.RandomAccessFile.write(RandomAccessFile.java:558)
        at org.gradle.internal.io.RandomAccessFileOutputStream.write(RandomAccessFileOutputStream.java:46)
        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
        at java.base/java.io.FilterOutputStream.flush(FilterOutputStream.java:153)
        at org.gradle.cache.internal.btree.ByteOutput.done(ByteOutput.java:62)
        at org.gradle.cache.internal.btree.FileBackedBlockStore$BlockImpl.write(FileBackedBlockStore.java:223)
        at org.gradle.cache.internal.btree.FileBackedBlockStore.write(FileBackedBlockStore.java:136)
        ... 22 more

```

</details>

After the first execution, which creates the traces mentioned above, subsequent executions fail with the following error:
```
> Could not create service of type BuildLifecycleController using ServicesProvider.createBuildLifecycleController().
   > Could not create service of type ChecksumService using BuildSessionScopeServices.createChecksumService().
      > Cannot lock checksums cache (/home/[REDACTED]/playground/.gradle/8.2/checksums) as it has already been locked by this process.
```

### Reproduction

Gradle version:
```
------------------------------------------------------------
Gradle 8.2
------------------------------------------------------------

Build time:   2023-06-30 18:02:30 UTC
Revision:     5f4a070a62a31a17438ac998c2b849f4f6892877

Kotlin:       1.8.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.8.1 (Oracle Corporation 17.0.8.1+1)
OS:           Linux 6.4.12-arch1-1 amd64
```

Steps:
- `git clone https://gitlab.com/opensavvy/playgrounds/gradle.git`
- `git switch --detach a2502fb619ed5a1dae4947c1c2032c54c85fc784`
- Add the plugin to the `settings.gradle.kts` file (version 0.7.0). [See my changes](https://gitlab.com/opensavvy/playgrounds/gradle/-/merge_requests/16/diffs)
- Entirely clean Gradle:

```
$ ./gradlew clean
$ ./gradlew --stop
$ cd ~/.gradle
$ rm -rf android android.lock build-scan-data caches daemon jdks kotlin-profile native nodejs notifications undefined-build workers wrapper yarn .tmp
```

- Go back to the Playground repository and execute any Gradle command, for example `./gradlew projects`.

On my machine, it reliably fails in exactly the same way on each execution, but it seems to be somewhat environment-dependent. For example, no messages are generated on [our CI server](https://gitlab.com/opensavvy/playgrounds/gradle/-/jobs/5000998901).

**Comment by jbartok** [comment]
I can't reproduce this.
I admit I didn't clean my original `.gradle` home folder, but used a different one via the `-g <FOLDER>` option.

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***

Sorry, we can't fix something we can't reproduce. If you can provide further help with reproducing, then please leave a comment, and we can reopen it.

**Comment by CLOVIS-AI** [comment]
After trying it again, I cannot reproduce it either, even with the original repository and no known changes to configuration.

I'll let you decide if it's better to keep this issue open for someone else, or close it, depending on your workflow.
