### ISSUE TITLE
Configuration cache fails when using filtered FileCollection

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#26352]
### Current Behavior

The build fails.

### Expected Behavior

The build shouldn't fail.

### Steps to Reproduce

1. Open the attached project: [FilteredFileCollection.zip](https://github.com/gradle/gradle/files/12589063/FilteredFileCollection.zip)

It has the following build script (note that it uses the `FileCollection#filter` API):
```
abstract class CustomTask : DefaultTask() {

    @get:InputFiles
    abstract val inputFiles: ConfigurableFileCollection

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun run() {
        println("Running task $this with inputFiles ${inputFiles.files} and outputFile ${outputFile.get().asFile}")
        outputFile.get().asFile.writeText("Hello")
    }
}

val fooTask by tasks.registering(CustomTask::class) {
    inputFiles.from(project.file("fooInputFile.txt"))
    outputFile.set(project.layout.buildDirectory.file("fooOutputFile.txt"))
}

val barTask by tasks.registering(CustomTask::class) {
    // Set fooTask's outputFile as barTask's inputFiles
    val regularFile: Provider<RegularFile> = fooTask.flatMap { it.outputFile }
    val regularFiles: Provider<List<RegularFile>> = regularFile.map { listOf(it) }
    val fileCollection: FileCollection = project.files(regularFiles)

    inputFiles.from(
        fileCollection
            .filter { it.isFile } // Comment out this line to make the build pass (`./gradlew clean barTask --configuration-cache`)
    )

    outputFile.set(project.layout.buildDirectory.file("barOutputFile.txt"))
}
```
2. Run `./gradlew clean barTask --configuration-cache -s`. The build will fail with:
```
Configuration cache state could not be cached: field `__inputFiles__` of task `:barTask` of type `Build_gradle$CustomTask`: error writing value of type 'org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection'
> Querying the mapped value of flatmap(provider(task 'fooTask', class Build_gradle$CustomTask)) before task ':fooTask' has completed is not supported
Caused by: org.gradle.api.InvalidUserCodeException: Querying the mapped value of flatmap(provider(task 'fooTask', class Build_gradle$CustomTask)) before task ':fooTask' has completed is not supported
        at org.gradle.api.internal.provider.TransformBackedProvider.lambda$beforeRead$0(TransformBackedProvider.java:98)
        at org.gradle.api.internal.provider.ValueSupplier$TaskProducer.visitContentProducerTasks(ValueSupplier.java:140)
        at org.gradle.api.internal.provider.TransformBackedProvider.beforeRead(TransformBackedProvider.java:95)
        at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:81)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:73)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:93)
        at org.gradle.api.internal.provider.ProviderResolutionStrategy$2.resolve(ProviderResolutionStrategy.java:33)
        at org.gradle.api.internal.file.collections.ProviderBackedFileCollection.visitChildren(ProviderBackedFileCollection.java:64)
        at org.gradle.api.internal.file.CompositeFileCollection$1.visitChildren(CompositeFileCollection.java:103)
        ...
```

### Gradle version

8.3

**Comment by jdochez** [comment]
have you tried doing : 
```
fileCollection.elements.map {
        it.filter { file -> file.asFile.isFile }
}
```

**Comment by bamboo** [comment]
Thanks for the report, @hungvietnguyen. I can confirm it's a bug. In the meantime, @jdochez's suggestion above be a suitable workaround.

**Comment by hungvietnguyen** [comment]
Thanks Jerome, that one works!

I think this should still be fixed in Gradle because:
  - It doesn't fail without configuration cache.
  - `FileCollection.filter` returns a `FileCollection`, so using `filter` should not change the nature of the `FileCollection` and make the build fail.
  - Reproducing this error requires a very specific setup in addition to the use of `FileCollection.filter` (only 1 of our many AGP tests can detect this bug). If the test didn't fail, we wouldn't have detected it.
  - It would be nice if the workaround was shown in the error message.
