### ISSUE TITLE
IllegalArgumentException: pos must be >= -1 at o.g.cache.internal.btree.BlockPointer.pos(BlockPointer.java:30)

### ISSUE THREAD

**Issue by ducrohet** [gradle/gradle#2652]
One of our users (Android developer) is reporting a weird error that seems to be in Gradle itself.
Issue on our tracker is here: https://issuetracker.google.com/issues/63877058

The relevant part of the stacktrace is (full one on the bug above): 

Cause 3: org.gradle.api.artifacts.transform.ArtifactTransformException: Failed to transform file 'a5ce2e93b1a5e5b529bade645d87c74b' to match attributes {artifactType=android-manifest} using transform AarTransform
        at org.gradle.api.internal.artifacts.transform.DefaultVariantTransformRegistration.transform(DefaultVariantTransformRegistration.java:97)
        at org.gradle.api.internal.artifacts.transform.DefaultVariantTransformRegistration.transform(DefaultVariantTransformRegistration.java:41)
        at org.gradle.api.internal.artifacts.transform.VariantAttributeMatchingCache$1.transform(VariantAttributeMatchingCache.java:86)
        at org.gradle.api.internal.artifacts.transform.VariantAttributeMatchingCache$1.transform(VariantAttributeMatchingCache.java:81)
        at org.gradle.api.internal.artifacts.transform.DefaultArtifactTransforms$TransformArtifactOperation.run(DefaultArtifactTransforms.java:226)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.access$900(DefaultBuildOperationExecutor.java:61)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$ParentPreservingQueueWorker.execute(DefaultBuildOperationExecutor.java:378)
        at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runOperation(DefaultBuildOperationQueue.java:183)
        at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.access$600(DefaultBuildOperationQueue.java:132)
        at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable$1.run(DefaultBuildOperationQueue.java:164)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runBatch(DefaultBuildOperationQueue.java:159)
        at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.run(DefaultBuildOperationQueue.java:137)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.gradle.api.UncheckedIOException: Could not read entry '70a1c112c8813b993da165efce9b761a' from cache results.bin (C:\Users\gamer\.gradle\caches\transforms-1\metadata-1.1\results.bin).
        at org.gradle.cache.internal.btree.BTreePersistentIndexedCache.get(BTreePersistentIndexedCache.java:132)
        at org.gradle.cache.internal.DefaultMultiProcessSafePersistentIndexedCache$1.create(DefaultMultiProcessSafePersistentIndexedCache.java:43)
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.readFile(DefaultFileLockManager.java:170)
        at org.gradle.cache.internal.DefaultCacheAccess$UnitOfWorkFileAccess.readFile(DefaultCacheAccess.java:390)
        at org.gradle.cache.internal.DefaultMultiProcessSafePersistentIndexedCache.get(DefaultMultiProcessSafePersistentIndexedCache.java:41)
        at org.gradle.cache.internal.AsyncCacheAccessDecoratedCache$1.create(AsyncCacheAccessDecoratedCache.java:43)
        at org.gradle.cache.internal.CacheAccessWorker$1.call(CacheAccessWorker.java:80)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.cache.internal.CacheAccessWorker$2.run(CacheAccessWorker.java:179)
        at org.gradle.internal.Factories$1.create(Factories.java:25)
        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:209)
        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:190)
        at org.gradle.cache.internal.CacheAccessWorker.flushOperations(CacheAccessWorker.java:174)
        at org.gradle.cache.internal.CacheAccessWorker.run(CacheAccessWorker.java:144)
        ... 6 more
Caused by: org.gradle.api.UncheckedIOException: java.lang.IllegalArgumentException: pos must be >= -1
        at org.gradle.cache.internal.btree.FileBackedBlockStore.read(FileBackedBlockStore.java:107)
        at org.gradle.cache.internal.btree.CachingBlockStore.read(CachingBlockStore.java:92)
        at org.gradle.cache.internal.btree.FreeListBlockStore.read(FreeListBlockStore.java:78)
        at org.gradle.cache.internal.btree.StateCheckBlockStore.read(StateCheckBlockStore.java:61)
        at org.gradle.cache.internal.btree.BTreePersistentIndexedCache.load(BTreePersistentIndexedCache.java:177)
        at org.gradle.cache.internal.btree.BTreePersistentIndexedCache.access$1200(BTreePersistentIndexedCache.java:47)
        at org.gradle.cache.internal.btree.BTreePersistentIndexedCache$IndexBlock.find(BTreePersistentIndexedCache.java:475)
        at org.gradle.cache.internal.btree.BTreePersistentIndexedCache$IndexBlock.find(BTreePersistentIndexedCache.java:455)
        at org.gradle.cache.internal.btree.BTreePersistentIndexedCache$IndexBlock.get(BTreePersistentIndexedCache.java:445)
        at org.gradle.cache.internal.btree.BTreePersistentIndexedCache.get(BTreePersistentIndexedCache.java:122)
        ... 20 more
Caused by: java.lang.IllegalArgumentException: pos must be >= -1
        at org.gradle.cache.internal.btree.BlockPointer.pos(BlockPointer.java:30)
        at org.gradle.cache.internal.btree.BTreePersistentIndexedCache$IndexBlock.read(BTreePersistentIndexedCache.java:372)
        at org.gradle.cache.internal.btree.FileBackedBlockStore$BlockImpl.read(FileBackedBlockStore.java:231)
        at org.gradle.cache.internal.btree.FileBackedBlockStore.read(FileBackedBlockStore.java:102)
        ... 29 more

**Comment by oehme** [comment]
Of course the exception doesn't contain the actual value. And of course it was me who made that mistake ;)

The block pointers are only ever increased, so my best guess is that we have an overflow here.

**Comment by eriwen** [comment]
@oehme is this a blocker for 4.1?

**Comment by oehme** [comment]
No, but I'll improve the message for 4.2. I suspect we just silently corrupted the cache previously when this assertion wasn't there.

**Comment by oehme** [comment]
The problem was that we threw an IllegalArgumentException here instead of a CacheCorruptedException. The latter tells Gradle to discard the cache and reconstruct it instead of failing.
