### ISSUE TITLE
ValueSource cannot have access to a logger

### ISSUE THREAD

**Issue by jdochez** [gradle/gradle#26785]
### Current Behavior

I would like to use a logger in my ValueSource.obtain() method. 

I declared the ValueSource.Parameters as : 
```
    interface Params: ValueSourceParameters {
        .... some other parameters...
        val logger: Property<Logger>
    }
```

At execution, I am getting : 
```
Caused by: org.gradle.internal.snapshot.ValueSnapshottingException: Could not serialize value of type OutputEventListenerBackedLogger
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.newValueSerializationException(AbstractValueProcessor.java:187)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.javaSerialization(AbstractValueProcessor.java:178)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.processValue(AbstractValueProcessor.java:157)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.processValue(AbstractValueProcessor.java:134)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.processValue(AbstractValueProcessor.java:134)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.processValue(AbstractValueProcessor.java:121)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.processValue(AbstractValueProcessor.java:134)
```

I also tried to inject through the constructor of the ValueSource class but there is not an available service that will provide me access to the Logger. Maybe that's an easier fix and would be enough for my case.

list of services I found : 
https://docs.gradle.org/current/userguide/custom_gradle_types.html#services_for_injection

### Expected Behavior

getting a logger instance either by service injection or ValueSource parameters

### Steps to Reproduce

try to obtain a Logger in ValueSource.obtain() implementation

### Gradle version

8.3

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team and is prioritized by them.

**Comment by amal** [comment]
Same for build services and `BuildServiceParameters`.  That's strange.

**Comment by mlopatkin** [comment]
Why do you need to pass the logger through the parameters, though? Also, it should already be possible to use SLF4J to obtain a logger.
