### ISSUE TITLE
Generating plugin dependency verification checksums 

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#26803]
### Current Behavior

Generating the checksums for the plugin `com.jaredsburrows:gradle-license-plugin:0.9.4-SNAPSHOT` creates a misleading error message. I would expect a different error message given that SNAPSHOT dependencies are not supported. Looking at the error message it seems more like an internal bug though.

```
* What went wrong:
Multiple entries with same key: com.jaredsburrows:gradle-license-plugin:0.9.4-SNAPSHOT=org.gradle.api.internal.artifacts.verification.model.ImmutableComponentVerificationMetadata@3ac842da and com.jaredsburrows:gradle-license-plugin:0.9.4-SNAPSHOT=org.gradle.api.internal.artifacts.verification.model.ImmutableComponentVerificationMetadata@772201ae
```

Stack trace:

```
* Exception is:
java.lang.IllegalArgumentException: Multiple entries with same key: com.jaredsburrows:gradle-license-plugin:0.9.4-SNAPSHOT=org.gradle.api.internal.artifacts.verification.model.ImmutableComponentVerificationMetadata@c442087 and com.jaredsburrows:gradle-license-plugin:0.9.4-SNAPSHOT=org.gradle.api.internal.artifacts.verification.model.ImmutableComponentVerificationMetadata@7a9d6244
        at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:378)
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:372)
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:246)
        at com.google.common.collect.RegularImmutableMap.fromEntryArrayCheckingBucketOverflow(RegularImmutableMap.java:133)
        at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:95)
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:572)
        at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:600)
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:587)
        at org.gradle.api.internal.artifacts.verification.verifier.DependencyVerifier.<init>(DependencyVerifier.java:57)
        at org.gradle.api.internal.artifacts.verification.verifier.DependencyVerifierBuilder.build(DependencyVerifierBuilder.java:144)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.verification.writer.WriteDependencyVerificationFile.serializeResult(WriteDependencyVerificationFile.java:221)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.verification.writer.WriteDependencyVerificationFile.buildFinished(WriteDependencyVerificationFile.java:202)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.StartParameterResolutionOverride$DisablingVerificationOverride.buildFinished(StartParameterResolutionOverride.java:273)
        at org.gradle.api.internal.artifacts.DependencyManagementBuildScopeServices$3.beforeModelDiscarded(DependencyManagementBuildScopeServices.java:457)
```

### Expected Behavior

The error message clearly expresses that SNAPSHOT dependencies are not supported for dependency verification or SNAPSHOT dependencies are ignored from generating the checksums.

### Steps to Reproduce

**build.gradle:**

```
buildscript {
    repositories {
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
        mavenCentral()
    }

    dependencies {
        classpath 'com.jaredsburrows:gradle-license-plugin:0.9.4-SNAPSHOT'
    }
}
```

Run the command `./gradlew --write-verification-metadata sha256 help`.

### Gradle version

8.4

**Comment by ov7a** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.
