### ISSUE TITLE
Configuration cache error with Java11 collections

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#26942]
### Current Behavior

When using Java11 collections Gradle fails with configuration cache with error:
```
org.gradle.api.GradleException: Could not load the value of field `$myList` of `Build_gradle$$$result$1$1` bean found in field `action` of `org.gradle.api.internal.AbstractTask$TaskActionWrapper` bean found in field `actions` of task `:testJava11Collections` of type `org.gradle.api.DefaultTask`.
        at org.gradle.configurationcache.serialization.beans.BeanPropertyReaderKt.readPropertyValue(BeanPropertyReader.kt:112)
        at org.gradle.configurationcache.serialization.beans.BeanPropertyReader.readStateOf(BeanPropertyReader.kt:68)
        at org.gradle.configurationcache.serialization.codecs.BeanCodec.readBeanOf(BeanCodec.kt:72)
        at org.gradle.configurationcache.serialization.codecs.BeanCodec.decode(BeanCodec.kt:47)
        at org.gradle.configurationcache.serialization.CombinatorsKt$reentrant$1$decodeLoop$1.invokeSuspend(Combinators.kt:166)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.configurationcache.serialization.codecs.jos.JavaObjectSerializationCodec.readResolve(JavaObjectSerializationCodec.kt:194)
        at org.gradle.configurationcache.serialization.codecs.jos.JavaObjectSerializationCodec.decode(JavaObjectSerializationCodec.kt:109)
        at org.gradle.configurationcache.serialization.codecs.BindingsBackedCodec.decode(BindingsBackedCodec.kt:59)
        at org.gradle.configurationcache.serialization.DefaultReadContext.read(Contexts.kt:269)
        at org.gradle.configurationcache.serialization.beans.BeanPropertyReaderKt.readPropertyValue(BeanPropertyReader.kt:106)
        ... 169 more
Caused by: java.io.InvalidObjectException: null array
        ... 177 more
        ````

### Expected Behavior

There is no error, Gradle works with Java11 collections.

### Context (optional)

Cannot use a plugin that uses Java11 collections.

### Steps to Reproduce

1. git clone git@github.com:asodja/gradle-cc-with-java11-collections.git
2. Use Java11 to run a project
2. Run `./gradlew :testPreJava11Collections --configuration-cache --stacktrace` -> everything works
3. Run `./gradlew :testJava11Collections --configuration-cache --stacktrace` -> exception is thrown

### Gradle version

Any version, reproducer uses `8.6-20231104002619+0000` nightly

**Comment by ljacomet** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by mlopatkin** [comment]
This is yet another issue of us trying to serialize the thing returned by `writeReplace` with bean serialization without checking if Java serialization is used. The serialized form uses `readObject`/`writeObject` to implement custom protocol, and then uses `readResolve` to replace itself with the original collection implementation.

**Comment by Technici4n** [comment]
Hi, we also ran into this issue multiple times in different plugins. Is a fix being looked at? Thanks!
