### ISSUE TITLE
Add `@ClosureParams` to `Closure` method parameters that already have a `@DelegatesTo`

### ISSUE THREAD

**Issue by PaintNinja** [gradle/gradle#27077]
### Expected Behavior

Various methods that take `Closure`s exist with an appropriate `@DelegatesTo` annotation attached to them, which is great for improving IDE support and aiding less verbose `@TypeChecked` or even `@CompileStatic` Groovy plugin code.

However, I noticed it is seldom combined with `@ClosureParams`, which if added, would show the param type in the IDE, like this:
<img width="201" alt="image" src="https://github.com/gradle/gradle/assets/3158390/945705f3-eae6-4730-adb1-c61f335de724">

### Current Behavior (optional)

Currently in Gradle 8.4, the lack of that annotation means the implicit `it` type isn't automatically known by the IDE and typing a quick `it.` to get suggestions doesn't show anything specific:
<img width="454" alt="image" src="https://github.com/gradle/gradle/assets/3158390/bfd2a29f-1ae7-4c0d-8ac2-e7b1d073fb2e">

But you can manually verify the type with a simple `instanceof` check on the param first...
```groovy
subprojects {
    println it instanceof Project // prints true
}
```
...and then manually looking at `Project`'s methods.

Alternatively, hovering over the `subprojects` part and looking at the type of the `@DelegatesTo` annotation also works:
<img width="481" alt="image" src="https://github.com/gradle/gradle/assets/3158390/39dc4422-15d4-42be-bc6a-7844649ba39f">

### Context

I did a fair bit of investigating before filing this feature request...

My first thought was it might be a bug in IntelliJ and that the closure param type hint shown should use the `@DelegatesTo` type if the `@ClosureParams` annotation is missing, however after playing around with some code I discovered this isn't always the case (a `@DelegatesTo`-only annotated `Closure` isn't guaranteed to have its type available in the implicit `it`).

I then started looking at Gradle code to verify that the methods set both the param and delegate and it looks like it does in various cases, as internally it seems to end up [here](https://github.com/gradle/gradle/blob/77d562cbe73c36eb5d25c5c18931b6d5e67aad00/platforms/core-configuration/model-core/src/main/java/org/gradle/util/ClosureBackedAction.java#L71) which sets the delegate and also calls the closure with it as the param if possible.

With all that confirmed and out of the way, it seems trivial to improve IDE support for the Groovy DSL in this specific scenario (and likely for various other methods that have a `@DelegatesTo`-only annotated `Closure`):
```groovy
void subprojects(@DelegatesTo(Project.class) @ClosureParams(value = SimpleType.class, options = "org.gradle.api.Project") Closure configureClosure);
```

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team, but this area of Gradle is currently not in focus. It might take a while before it gets implemented.

**Comment by hegyibalint** [comment]
Thanks @PaintNinja for the comprehensive write-up!

> My first thought was it might be a bug in IntelliJ and that the closure param type hint shown should use the `@DelegatesTo` type if the `@ClosureParams` annotation is missing, however after playing around with some code I discovered this isn't always the case (a `@DelegatesTo`-only annotated `Closure` isn't guaranteed to have its type available in the implicit it).

Hmm, I could argue against this statement, but I'm not a Groovy expert: reading the JavaDocs, it sounds to me that when you use `@DelegatesTo`, you inform the IDE that the Closure is going to be backed by a certain delegate object. 

IIUC by providing a delegate (`@DelegatesTo` should be a way to inform the IDE about this fact) a `Closure` "inherits" all the method and field signatures from its delegate. What you could choose is the [strategy](https://docs.groovy-lang.org/latest/html/api/groovy/lang/Closure.html#DELEGATE_FIRST) how to do things.

Based on this, I believe that IDEA should provide code completion solely based on the `@DelegatesTo`.

Did you try to bring this up to the JetBrains team? I would be interested if they could bring up any good point as to why this is not the situation right now.

**Comment by PaintNinja** [comment]
No problem!

I understand this behaviour is surprising, however I've confirmed this is indeed intended behaviour and not a bug in IntelliJ. Allow me to provide my test code, example output and screenshots to demonstrate this...

## Explainer
First, let's make `DelegateClass` for testing purposes:
```groovy
package org.example

class DelegateClass {
    public String myField = 'field'
    String myProperty = 'property'

    static void staticMethod() {
        println 'staticMethod'
    }

    void instanceMethod() {
        println 'instanceMethod'
    }
}
```

The `@DelegatesTo` and `@ClosureParams` annotations act as IDE and compiler hints (for Groovy's `@TypeChecked` and `@CompileStatic` modes), which correspond to `Closure#setDelegate()` and `Closure#call(param)`, respectively.

If you call a closure and only set the delegate without calling it with the param, the implicit `it` won't be set:
```groovy
class ClosureExample1 {
    static void main(String[] args) {
        closureWithOnlyDelegate {
            println 'delegate'
            println '--------'
            println myField
            println getMyProperty()
            staticMethod()
            instanceMethod()

            println '\nimplicit it'
            println '-----------'
            // these will fail at runtime in @CompileDynamic mode (default) and at compile time in @TypeChecked and @CompileStatic modes
            println it.myField
            println it.getMyProperty()
            it.staticMethod()
            it.instanceMethod()
        }
    }

    static void closureWithOnlyDelegate(@DelegatesTo(DelegateClass) Closure closure) {
        var delegateClass = new DelegateClass()
        closure.delegate = delegateClass
        closure.call() // notable: delegateClass is not passed as a parameter to the call method
    }
}
```

`@CompileDynamic` (default) runtime output:
```
delegate
--------
field
property
staticMethod
instanceMethod

implicit it
-----------
Exception in thread "main" java.lang.NullPointerException: Cannot get property 'myField' on null object
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:94)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:336)
	at org.example.ClosureExample1$_main_closure1.doCall(ClosureExample1.groovy:19)
	at org.example.ClosureExample1$_main_closure1.doCall(ClosureExample1.groovy)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:338)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:272)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:266)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:336)
	at org.example.ClosureExample1.closureWithOnlyDelegate(ClosureExample1.groovy:29)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:336)
	at org.example.ClosureExample1.main(ClosureExample1.groovy:8)
```

`@TypeChecked`/`@CompileStatic` compile error:
```
startup failed:
D:\Projects\groovytest\groovytest\src\main\groovy\org\example\ClosureExample1.groovy: 19: [Static type checking] - No such property: myField for class: java.lang.Object
 @ line 19, column 21.
               println it.myField
                       ^

D:\Projects\groovytest\groovytest\src\main\groovy\org\example\ClosureExample1.groovy: 20: [Static type checking] - Cannot find matching method java.lang.Object#getMyProperty(). Please check if the declared type is correct and if the method exists.
 @ line 20, column 21.
               println it.getMyProperty()
                       ^

D:\Projects\groovytest\groovytest\src\main\groovy\org\example\ClosureExample1.groovy: 21: [Static type checking] - Cannot find matching method java.lang.Object#staticMethod(). Please check if the declared type is correct and if the method exists.
 @ line 21, column 13.
               it.staticMethod()
               ^

D:\Projects\groovytest\groovytest\src\main\groovy\org\example\ClosureExample1.groovy: 22: [Static type checking] - Cannot find matching method java.lang.Object#instanceMethod(). Please check if the declared type is correct and if the method exists.
 @ line 22, column 13.
               it.instanceMethod()
               ^

4 errors


FAILURE: Build failed with an exception.
```

A similar error will occur if the delegate isn't set but is passed in as a parameter with the `@ClosureParams` hint, except it'll fail on the usages without the `it.` prefix.

This is why IntelliJ treats `@DelegatesTo` and `@ClosureParams` separately - to align with Groovy runtime and compiler behaviour.

**Gradle specifically always sets the closure delegate and calls the closure with the param, so it should have both the `@DelegatesTo` and `@ClosureParams` annotations for proper IDE support and to better support statically compiled or type-checked Gradle plugins written in Groovy.**

### Here's a table that summarises the behaviour:
| Closure type                       | Has `@DelegatesTo`? | Has `@ClosureParams`? | Works in dynamic?         | Works in static?          |
|------------------------------------|---------------------|-----------------------|---------------------------|---------------------------|
| Only delegate set                  | No                  | No                    | Only without `it.` prefix | No                        |
| Closure only called with param     | No                  | No                    | Only *with* `it.` prefix  | No                        |
| Only delegate set                  | Yes                 | No                    | Only without `it.` prefix | Only without `it.` prefix |
| Closure only called with param     | No                  | Yes                   | Only *with* `it.` prefix  | Only *with* `it.` prefix  |
| Delegate set and called with param | No                  | No                    | Yes                       | No                        |
| Delegate set and called with param | Yes                 | No                    | Yes                       | Only without `it.` prefix |
| Delegate set and called with param | No                  | Yes                   | Yes                       | Only *with* `it.` prefix  |
| Delegate set and called with param | Yes                 | Yes                   | Yes                       | Yes                       |

Note that the "works in static?" column also reflects IDE support/code completion hints/type hints/etc...

Here's the code used for gathering the data for that table: https://gist.github.com/PaintNinja/4fc2e144e70fb25d4a22149a5eb1262f
The `callClosure()` method was adjusted along with relevant code for each scenario.

### Screenshots of IDE support for each combination of hints
<img width="242" alt="image" src="https://github.com/gradle/gradle/assets/3158390/38a7ee7a-45e7-4fd9-93e9-529bf0cf1cf4">
<img width="503" alt="image" src="https://github.com/gradle/gradle/assets/3158390/ec84dbf9-f084-43f0-9c02-f87a58b0cd28">

## Reasoning
As for why this behaviour exists, presumably it's to allow for scenarios such as `@DelegatesTo(value = DelegateClass, strategy = Closure.OWNER_ONLY)` with custom, explicitly typed data fed into the param. This scenario would prevent accessing any variables or methods outside of the closure delegate but still allow accessing specific extra data from the closure parameters.

I've considered contacting the Groovy team about changing the default behaviour in Groovy 5 so that setting only a delegate or parameter also sets the other by default rather than being null, effectively implementing what you expected however I haven't had time to get around to that yet and unsure if it would be a good idea (could cause ambiguity for IDEs unless they detect the Groovy version that would be used to run the file).

Somewhat related - I have reported various things to IntelliJ related to Groovy and Gradle's Groovy DSL, which you can find here if interested: https://youtrack.jetbrains.com/issues?q=by:%20PaintNinja%20 .

---

Hope this helps! :)

**Comment by hegyibalint** [comment]
I am not finding the time to handle this since a while, I'm going to throw this back into a pool.

If anybody wants to take a stab at this, look at the https://github.com/gradle/gradle/tree/bhegyi-ljacomet/asm-based-closure-annotations branch. It is quite outdated at this point, but:
 - has the essential idea of the implementation 
 - with an unsolved bug: for some reason the class generated will be invalid: we didn't figure out why
