### ISSUE TITLE
Gradle build fails on new clean java default project on Windows

### ISSUE THREAD

**Issue by dzhelek** [gradle/gradle#27188]
### Current Behavior
Build fails with the following error:
```bash
Could not write standard input to Gradle Test Executor 2.
java.io.IOException: The pipe is being closed
        at java.base/java.io.FileOutputStream.writeBytes(Native Method)
        at java.base/java.io.FileOutputStream.write(FileOutputStream.java:373)
        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:125)
        at java.base/java.io.BufferedOutputStream.implFlush(BufferedOutputStream.java:252)
        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:240)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.writeBuffer(ExecOutputHandleRunner.java:98)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:85)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:64)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1623)

> Task :app:test FAILED
Error: Could not find or load main class worker.org.gradle.process.internal.worker.GradleWorkerMain
Caused by: java.lang.ClassNotFoundException: worker.org.gradle.process.internal.worker.GradleWorkerMain

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:test'.
> Process 'Gradle Test Executor 2' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1s
7 actionable tasks: 7 executed
```
It's the same result using the command `.\gradlew.bat build`.

### Expected Behavior

I expect the build of the default generated java application to be successful.

### Steps to Reproduce

```bash
mkdir project
cd project
gradle init
gradle build
```
in the `gradle init` step a java application is chosen, all other options are left default values.

### Gradle version

v8.4 binary-only

### Build scan URL (optional)

https://gradle.com/s/g76ijug6wpa2o

### Your Environment (optional)

I tried reinstalling gradle with the steps in the article: https://docs.gradle.org/current/userguide/installation.html.

**Comment by cobexer** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.
***
Please verify the integrity of your Gradle installation.

Please also share the output of `gradle -v`.

Given the error, this looks like an environment problem, not a Gradle problem.
