### ISSUE TITLE
8.5: building the project twice with tr_TR locale yields NullPointerException: javaClass.getResourceAsStream(resourcePath)

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#27261]
### Current Behavior

```
        java.lang.NullPointerException: javaClass.getResourceAsStream(resourcePath) must not be null
            at org.gradle.kotlin.dsl.execution.ExecutableProgram$StagedProgram.loadScriptResource(ExecutableProgram.kt:102)
            at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost$compileSecondStageOf$cacheDir$1.invoke(Interpreter.kt:478)
            at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost$compileSecondStageOf$cacheDir$1.invoke(Interpreter.kt:467)
            at org.gradle.kotlin.dsl.provider.CompileKotlinScript.execute(KotlinScriptEvaluator.kt:411)
            at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:105)
            at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44)
            at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:59)
            at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:56)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
            at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
            at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
            at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
            at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:56)
            at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:44)
            at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:67)
            at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:37)
            at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
            at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
            at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
            at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:50)
            at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:28)
            at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.executeDelegateBroadcastingChanges(CaptureStateAfterExecutionStep.java:100)
            at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:72)
            at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:50)
            at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:40)
            at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:29)
            at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:179)
            at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:70)
            at org.gradle.internal.Either$Right.fold(Either.java:175)
```

### Expected Behavior

Gradle build should succeed

### Context (optional)

This seems to reproduce only with 17.0.9 Semeru JDK with tr_TR locale
At this point, I am not sure if the root cause is with Gradle or with Semeru, however, I create an issue so others could find it and relate it to their problems.

### Steps to Reproduce

1. Checkout https://github.com/apache/jmeter/pull/6166
2. Stop all daemons `./gradlew --stop`
3. Remove `$home/.gradle/caches/8.5`
4. Build: `TZ="Pacific/Chatham" _JAVA_OPTIONS="-Duser.country=TR -Duser.language=tr" ./gradlew compileKotlin --rerun-tasks --no-build-cache -Duser.country=TR -Duser.language=tr`. It will succeed
5. Build the second time with same options: `TZ="Pacific/Chatham" _JAVA_OPTIONS="-Duser.country=TR -Duser.language=tr" ./gradlew compileKotlin --rerun-tasks --no-build-cache -Duser.country=TR -Duser.language=tr`. It will fail

### Gradle version

8.5

### Build scan URL (optional)

https://ge.apache.org/s/i6ryc67d76hh4/failure#1

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Can you reproduce it with another JDK?

**Comment by vlsi** [comment]
It reproduces with Semeru only

**Comment by ov7a** [comment]
@vlsi Thanks! I think it should be closed because it's a bug in Semeru, not in Gradle.
