### ISSUE TITLE
Caused by: org.gradle.api.UncheckedIOException: Unable to store input properties for task ':Main:checkDebugClasspath'. Property 'runtimeVersionMap' with value   cannot be serialized

### ISSUE THREAD

**Issue by killnono** [gradle/gradle#27701]
### Current Behavior

After upgrading the Android Gradle Plugin and Gradle version, an error occurs during the checkClasspath step of the build task execution.

### Expected Behavior

Caused by: org.gradle.api.UncheckedIOException: Unable to store input properties for task ':Main:checkXuexiDebugClasspath'. Property 'runtimeVersionMap' with value   cannot be serialized
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.lambda$fingerprintInputProperties$2(CaptureStateBeforeExecutionStep.java:140)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.visitInputProperties(ExecuteActionsTaskExecuter.java:266)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.fingerprintInputProperties(CaptureStateBeforeExecutionStep.java:131)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.createExecutionState(CaptureStateBeforeExecutionStep.java:113)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:67)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        ... 24 more
Caused by: org.gradle.internal.snapshot.ValueSnapshottingException: Could not serialize value of type 'com.android.build.gradle.internal.tasks.Info'
        at org.gradle.internal.snapshot.impl.DefaultValueSnapshotter.serialize(DefaultValueSnapshotter.java:174)
        at org.gradle.internal.snapshot.impl.DefaultValueSnapshotter.processValue(DefaultValueSnapshotter.java:163)
        at org.gradle.internal.snapshot.impl.DefaultValueSnapshotter.processValue(DefaultValueSnapshotter.java:125)
        at org.gradle.internal.snapshot.impl.DefaultValueSnapshotter.snapshot(DefaultValueSnapshotter.java:53)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.lambda$fingerprintInputProperties$2(CaptureStateBeforeExecutionStep.java:135)
        ... 41 more
Caused by: java.io.NotSerializableException: com.android.build.gradle.internal.tasks.Info
        at org.gradle.internal.snapshot.impl.DefaultValueSnapshotter.serialize(DefaultValueSnapshotter.java:171)
        ... 45 more

### Context (optional)

Android gradle 3.6.4 & gradle 5.6.4

### Steps to Reproduce

./gradlew clean assembledebug --stacktrace

### Gradle version

 5.6.4

**Comment by killnono** [comment]
It seems to be related to the setting of ”android.dependency.useConstraints=false“，The option setting 'android.dependency.useConstraints=false' is experimental and unsupported.

**Comment by cobexer** [comment]
Sorry that you're having trouble with Gradle!

This is an issue with the Android Gradle Plugin, which is developed by Google and cannot be addressed in the Gradle Build Tool project.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/docs/setup/contribute/report-bugs#filing-a-bug

***
Also Gradle 5.6.4 is EOL see https://docs.gradle.org/current/userguide/feature_lifecycle.html#eol_support

**Comment by mwshubham** [comment]
@killnono Did you find any solution for this. I am also facing similar issue but with different input property.

Link: https://discuss.gradle.org/t/cannot-fingerprint-input-property-compileversionmap/48740
