### ISSUE TITLE
Push to remote task cache fails with IOException on local build

### ISSUE THREAD

**Issue by tjoneslo** [gradle/gradle#2771]
This is on my CI build machine, but does not happen locally. I've tried this several times and it fails at a different project and class location for each attempt, with a different number of bytes written in every case.

```
10:30:41 -         Could not pack property 'destinationDir': java.io.IOException: entry 'property-destinationDir/path/Foo.class' closed at '58368' before the '71838' bytes specified in the header were written
```

I've reviewed the logs on the remote task cache instance, and there are no errors in any of the logs. All the remote access (GET/PUT) looks completely normal. The build process has accessed the remote build cache to both get several artifact and push a number of other ones. 

We're using Gradle 3.5

```
10:30:41 -         * Exception is:
10:30:41 -         org.gradle.api.GradleException: Could not pack property 'destinationDir': java.io.IOException: entry 'property-destinationDir/path/Foo.class' closed at '58368' before the '71838' bytes specified in the header were written
10:30:41 -         	at org.gradle.caching.internal.tasks.TarTaskOutputPacker.pack(TarTaskOutputPacker.java:115)
10:30:41 -         	at org.gradle.caching.internal.tasks.TarTaskOutputPacker.access$100(TarTaskOutputPacker.java:65)
10:30:41 -         	at org.gradle.caching.internal.tasks.TarTaskOutputPacker$1.execute(TarTaskOutputPacker.java:88)
10:30:41 -         	at org.gradle.caching.internal.tasks.TarTaskOutputPacker$1.execute(TarTaskOutputPacker.java:80)
10:30:41 -         	at org.gradle.internal.IoActions.withResource(IoActions.java:79)
10:30:41 -         	at org.gradle.caching.internal.tasks.TarTaskOutputPacker.pack(TarTaskOutputPacker.java:80)
10:30:41 -         	at org.gradle.caching.internal.tasks.GZipTaskOutputPacker.pack(GZipTaskOutputPacker.java:45)
10:30:41 -         	at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter$2.writeTo(SkipCachedTaskExecuter.java:103)
10:30:41 -         	at org.gradle.caching.internal.BuildOperationFiringBuildCacheServiceDecorator$BuildOperationFiringBuildCacheEntryWriter$1.execute(BuildOperationFiringBuildCacheServiceDecorator.java:89)
10:30:41 -         	at org.gradle.caching.internal.BuildOperationFiringBuildCacheServiceDecorator$BuildOperationFiringBuildCacheEntryWriter$1.execute(BuildOperationFiringBuildCacheServiceDecorator.java:85)
10:30:41 -         	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
10:30:41 -         	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
10:30:41 -         	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
10:30:41 -         	at org.gradle.caching.internal.BuildOperationFiringBuildCacheServiceDecorator$BuildOperationFiringBuildCacheEntryWriter.writeTo(BuildOperationFiringBuildCacheServiceDecorator.java:85)
10:30:41 -         	at org.gradle.caching.http.internal.HttpBuildCacheService$1.writeTo(HttpBuildCacheService.java:145)
10:30:41 -         	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:158)
10:30:41 -         	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:162)
10:30:41 -         	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:237)
10:30:41 -         	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:122)
10:30:41 -         	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
10:30:41 -         	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
10:30:41 -         	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
10:30:41 -         	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
10:30:41 -         	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
10:30:41 -         	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
10:30:41 -         	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:113)
10:30:41 -         	at org.gradle.caching.http.internal.HttpBuildCacheService.store(HttpBuildCacheService.java:155)
10:30:41 -         	at org.gradle.caching.internal.ForwardingBuildCacheService.store(ForwardingBuildCacheService.java:40)
10:30:41 -         	at org.gradle.caching.internal.ForwardingBuildCacheService.store(ForwardingBuildCacheService.java:40)
10:30:41 -         	at org.gradle.caching.internal.BuildOperationFiringBuildCacheServiceDecorator.store(BuildOperationFiringBuildCacheServiceDecorator.java:47)
10:30:41 -         	at org.gradle.caching.internal.ForwardingBuildCacheService.store(ForwardingBuildCacheService.java:40)
10:30:41 -         	at org.gradle.caching.internal.LoggingBuildCacheServiceDecorator.store(LoggingBuildCacheServiceDecorator.java:53)
10:30:41 -         	at org.gradle.caching.internal.ForwardingBuildCacheService.store(ForwardingBuildCacheService.java:40)
10:30:41 -         	at org.gradle.caching.internal.ShortCircuitingErrorHandlerBuildCacheServiceDecorator.store(ShortCircuitingErrorHandlerBuildCacheServiceDecorator.java:67)
10:30:41 -         	at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:99)
10:30:41 -         	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
10:30:41 -         	at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:51)
10:30:41 -         	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
10:30:41 -         	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
10:30:41 -         	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
10:30:41 -         	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
10:30:41 -         	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
10:30:41 -         	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:47)
10:30:41 -         	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
10:30:41 -         	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
10:30:41 -         	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
10:30:41 -         	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
10:30:41 -         	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
10:30:41 -         	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
10:30:41 -         	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
10:30:41 -         	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
10:30:41 -         	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
10:30:41 -         	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
10:30:41 -         	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
10:30:41 -         	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
10:30:41 -         	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
10:30:41 -         Caused by: org.gradle.api.UncheckedIOException: java.io.IOException: entry 'property-destinationDir/path/Foo.class' closed at '58368' before the '71838' bytes specified in the header were written
10:30:41 -         	at org.gradle.caching.internal.tasks.TarTaskOutputPacker$2.visitFile(TarTaskOutputPacker.java:166)
10:30:41 -         	at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalker$1.visitFile(Jdk7DirectoryWalker.java:85)
10:30:41 -         	at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalker$1.visitFile(Jdk7DirectoryWalker.java:58)
10:30:41 -         	at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalker.walkDir(Jdk7DirectoryWalker.java:58)
10:30:41 -         	at org.gradle.caching.internal.tasks.TarTaskOutputPacker.storeDirectoryProperty(TarTaskOutputPacker.java:170)
10:30:41 -         	at org.gradle.caching.internal.tasks.TarTaskOutputPacker.packProperty(TarTaskOutputPacker.java:133)
10:30:41 -         	at org.gradle.caching.internal.tasks.TarTaskOutputPacker.pack(TarTaskOutputPacker.java:113)
10:30:41 -         	... 55 more
10:30:41 -         Caused by: java.io.IOException: entry 'property-destinationDir/path/Foo.class' closed at '58368' before the '71838' bytes specified in the header were written
10:30:41 -         	at org.apache.tools.tar.TarOutputStream.closeEntry(TarOutputStream.java:350)
10:30:41 -         	at org.gradle.caching.internal.tasks.TarTaskOutputPacker.storeFileEntry(TarTaskOutputPacker.java:197)
10:30:41 -         	at org.gradle.caching.internal.tasks.TarTaskOutputPacker.access$300(TarTaskOutputPacker.java:65)
10:30:41 -         	at org.gradle.caching.internal.tasks.TarTaskOutputPacker$2.visitFile(TarTaskOutputPacker.java:164)
10:30:41 -         	... 61 more
```

**Comment by wolfs** [comment]
@tjoneslo Thank you for the report. Gradle 3.5 may shade the real cause of the exception. This is much better handled in Gradle 4.0. The build cache also may have some other problems for Gradle 3.5. Could you possible upgrade to Gradle 4.1 - we improved error handling quite a bit for that release.
A cause I could think of is that you lost the connection while packing or that the file which was just packed was modified.

**Comment by wolfs** [comment]
I will close this issue for now. Please re-open if you still have problems when using Gradle 4.1.

**Comment by tjoneslo** [comment]
To close the loop here. We upgraded to Gradle 4.1 and the problem has not re-occured.
