### ISSUE TITLE
8.6: Running debuggable integration tests with configuration cache enabled fails on lambda serialization

### ISSUE THREAD

**Issue by martinbonnin** [gradle/gradle#27956]
### Current Behavior

When running Gradle integration tests using `withDebug(true)` fails with an error like this:

```
    FAILURE: Build failed with an exception.

    * What went wrong:
    Could not load the value of field `specs` of `org.gradle.api.specs.AndSpec` bean found in task `:exampleTask` of type `example.ExampleTask`.
    > example.ExampleTask$$Lambda$1370/0x0000000300b1bd38

    * Try:
    > Run with --info or --debug option to get more log output.
    > Run with --scan to get full insights.
    > Get more help at https://help.gradle.org.

    * Exception is:
    org.gradle.api.GradleException: Could not load the value of field `specs` of `org.gradle.api.specs.AndSpec` bean found in task `:exampleTask` of type `example.ExampleTask`.
        at org.gradle.configurationcache.serialization.beans.BeanPropertyReaderKt.readPropertyValue(BeanPropertyReader.kt:112)
        at org.gradle.configurationcache.serialization.beans.BeanPropertyReaderKt$readPropertyValue$1.invokeSuspend(BeanPropertyReader.kt)

[...]

    Caused by: java.lang.ClassNotFoundException: example.ExampleTask$$Lambda$1370/0x0000000300b1bd38
        at org.gradle.configurationcache.serialization.DefaultReadContext.readClass(Contexts.kt:295)
        at org.gradle.configurationcache.serialization.codecs.BeanCodec.decode(BeanCodec.kt:44)
        at org.gradle.configurationcache.serialization.CombinatorsKt$reentrant$1$decodeLoop$1.invokeSuspend(Combinators.kt:166)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        ... 159 more
```

### Expected Behavior

The integration test does not fail

### Context (optional)

Follow up from this Gradle slack thread: https://www.linen.dev/s/gradle-community/t/16368161/i-have-the-weirdest-issue-when-upgrading-with-8-6-in-integra#1b263523-b9e7-4177-8dde-640aa14d5946

The change introducing the problem seems to be https://github.com/gradle/gradle/pull/26045/

My current hunch is that the instrumentation agent isn't installed during integration tests which means the lambdas are not rewritten to be made serializable.

### Steps to Reproduce

See https://github.com/martinbonnin/test-gradle-8-6

```
git clone https://github.com/martinbonnin/test-gradle-8-6
cd test-gradle-8-6
./gradlew test --configuration-cache -i
```

Output:

```
> Task :test FAILED

MainTest > testPlugin FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in /Users/mbonnin/git/test-gradle-8-6/./build/testProject with arguments [exampleTask, --configuration-cache]

    Output:
    Calculating task graph as no cached configuration is available for tasks: exampleTask

    FAILURE: Build failed with an exception.

    * What went wrong:
    Could not load the value of field `specs` of `org.gradle.api.specs.AndSpec` bean found in task `:exampleTask` of type `example.ExampleTask`.
    > example.ExampleTask$$Lambda$1306/0x0000000300b226b0

    * Try:
    > Run with --stacktrace option to get the stack trace.
    > Run with --info or --debug option to get more log output.
    > Run with --scan to get full insights.
    > Get more help at https://help.gradle.org.

    BUILD FAILED in 2s
    Configuration cache entry stored.
        at app//org.gradle.testkit.runner.internal.DefaultGradleRunner.lambda$build$2(DefaultGradleRunner.java:269)
        at app//org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:362)
        at app//org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:267)
        at app//MainTest.testPlugin(MainTest.kt:18)
```

### Gradle version

8.6

### Gradle version that used to work

8.5

**Comment by ov7a** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by asodja** [comment]
Could you verify that https://services.gradle.org/distributions-snapshots/gradle-8.7-branch-asodja_testkit_debug_fix-20240206192522+0000-bin.zip fixes your issue?

**Comment by martinbonnin** [comment]
@asodja I can confirm that works 🎉
