### ISSUE TITLE
IllegalStateException No operation is currently running when testing a gradle task

### ISSUE THREAD

**Issue by alinbutura** [gradle/gradle#2808]
Hi,

I am currently experimenting with the Gradle upgrade from version 3.5 to 4.1 and I stumbled upon the following error:
Imagine the following Gradle task:

```groovy
class MyTask extends DefaultTask implements VersionedTask {
    final WorkerExecutor workerExecutor

    @Input
    String version

    @InputDirectory
    File inputDirectory = project.file("$project.buildDir/my-content")

    @OutputDirectory
    File outputDirectory = project.file("$project.buildDir/my-generated-content")

    @Inject
    MyTask(WorkerExecutor workerExecutor) {
        this.workerExecutor = workerExecutor
        onlyIf {
            inputDirectory != null && inputDirectory.isDirectory()
        }
    }

    @TaskAction
    void execute(IncrementalTaskInputs inputs) {
        inputs.removed { InputFileDetails details ->
            File inputFile = details.file
            workerExecutor.submit(FileCleaner.class) { WorkerConfiguration config ->
                config.isolationMode = IsolationMode.NONE
                config.params inputFile
            }
        }
    }
    private static class FileCleaner implements Runnable {
        File file

        @Inject
        FileUnmarshaller(File file) {
            this.file = file
        }

        @Override
        void run() {
            File outputFile = getOutputFile(this.file)

            if (outputFile.isFile()) {
                outputFile.delete()
            } else {
                logger.warn('Output file {} does not exist', outputFile)
            }
        }
    }
}
```

And the test case:

```groovy
class MyTaskTest {
    File inputFile

    File outputFile

    MyTask task

    Class clazz

    @Before
    void setUp() {
        File projectDirectory = File.createTempDir()
        Project project = ProjectBuilder.builder()
                .withProjectDir(projectDirectory)
                .build()
        task = project.task([type: MyTask], 'execute')
        inputFile = new File(task.inputDirectory, 'pack/Test.ssm')
        outputFile = new File(task.outputDirectory, 'pack/Test.ser')
    }

    void remove() {
        task.execute(new DefaultTaskInputs() {

            @Override
            void removed(Action<? super InputFileDetails> removedAction) {
                removedAction.execute(new RemovedFileDetails(inputFile))
            }
        })
    }

    @Test
    void 'Removing an existing file results in the corresponding output file being removed'() {
        outputFile.getParentFile().mkdirs()
        outputFile.createNewFile()
        remove()

        assert !outputFile.exists()
    }

    @Test
    void 'Removing an existing file does not fail if the corresponding output file does not exist'() {
        remove()

        assert !outputFile.exists()
    }
}
```

This will fail with the exception:

java.lang.IllegalStateException: No operation is currently running.

	at org.gradle.internal.progress.DefaultBuildOperationExecutor.getCurrentOperation(DefaultBuildOperationExecutor.java:99)
	at org.gradle.workers.internal.DefaultWorkerExecutor.submit(DefaultWorkerExecutor.java:98)
	at org.gradle.workers.internal.DefaultWorkerExecutor.submit(DefaultWorkerExecutor.java:93)
	at org.gradle.workers.internal.DefaultWorkerExecutor_Decorated.submit(Unknown Source)
	at org.gradle.workers.internal.DefaultWorkerExecutor_Decorated$submit.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at eurocontrol.nconect.ssm.gradle.MyTask$_execute_closure2.doCall(MyTask.groovy:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:54)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
	at com.sun.proxy.$Proxy26.execute(Unknown Source)

I am running the test from Intellij IDEA Ultimate 2017.2 on a RHEL 7.3 64 bits machine.

Can you help? Thanks a lot!

Cheers,
Alin

**Comment by bmuschko** [comment]
@ghale Would you mind having a look? Seems to be related to the worker API.

**Comment by oehme** [comment]
The ProjectBuilder API cannot be used to run tasks. Please use [TestKit](https://docs.gradle.org/4.1/userguide/test_kit.html) tests instead.

**Comment by oehme** [comment]
We should prevent `Task.execute` from being called by anything but Gradle, so we can provide a better error messages to users trying this.
