### ISSUE TITLE
Project Isolation: PropertyDelegate: Expected unreportedProblemInCurrentCall to be called after enterDynamicCall

### ISSUE THREAD

**Issue by hfhbd** [gradle/gradle#28204]
### Current Behavior

```stacktrace
Caused by: java.lang.IllegalStateException: Expected unreportedProblemInCurrentCall to be called after enterDynamicCall
        at org.gradle.configurationcache.DefaultDynamicCallProblemReporting.unreportedProblemInCurrentCall(DynamicCallProblemReporting.kt:75)
        at org.gradle.configurationcache.CrossProjectModelAccessTrackingParentDynamicObject.maybeReportProjectIsolationViolation(CrossProjectModelAccessTrackingParentDynamicObject.kt:114)
        at org.gradle.configurationcache.CrossProjectModelAccessTrackingParentDynamicObject.onAccess(CrossProjectModelAccessTrackingParentDynamicObject.kt:109)
        at org.gradle.configurationcache.CrossProjectModelAccessTrackingParentDynamicObject.tryGetProperty(CrossProjectModelAccessTrackingParentDynamicObject.kt:57)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryGetProperty(CompositeDynamicObject.java:56)
        at org.gradle.kotlin.dsl.NullableDynamicPropertyDelegate.getValue(PropertyDelegate.kt:65)
```

### Expected Behavior

No error

### Context (optional)

Workaround:
```kotlin
val s: Provider<String> = project.providers.gradleProperty("s")
```

### Steps to Reproduce

```kotlin
val s: String? by project
println(s)
```

[gradle28204.zip](https://github.com/gradle/gradle/files/14383932/gradle28204.zip)
`./gradlew help`

### Gradle version

8.7-RC1

**Comment by ov7a** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by alllex** [comment]
The issue is reproducible with 8.6 and 8.5. Here is a simpler reproducer as an integration test:
```groovy
    def "reproducer"() {
        file("a/build.gradle.kts") << """
            val s: String? by project
            println(s)
        """

        settingsFile """
            include("a")
        """

        expect:
        isolatedProjectsRun("help")
    }
    ```
    
It does not fail the build logic is in the root project.

**Comment by alllex** [comment]
Another instance of the same problem (this reproduced with Groovy DSL)

The error occurs in a custom plugin that retrieves a property on an extension on Project in the callback:
```
project.pluginManager.withPlugin('plugin-name', {
	dependencies {
		runtimeOnly(projectProperty.foo)
	}
}
```
The projectProperty is declared as:
```
ext {
	projectProperty = [
		foo: 'value'
	]
}
```
