### ISSUE TITLE
Allow inspecting the sizes of configuration cache entries

### ISSUE THREAD

**Issue by mgroth0** [gradle/gradle#28327]
### Expected Behavior

The title says it all. 

### Current Behavior (optional)

There is no way to inspect the size of configuration cache interies.

The configuration cache is stored in `.bin` files (binary, with a custom, internal encoding?) inside `.gradle/confgiuration-cache`. I'm sure that the encoding is designed and optimized for performance, but currently there is no direct way for a developer to answer the question "what entries in my configuration cache is making it so large"?

The workarounds I can think of are:

- None

### Context

This is the third in my series of issues requesting features to allow developers to debug and better understand their own configuration cache. The previous issues (which as of now are still open):

1. https://github.com/gradle/gradle/issues/24757
2. https://github.com/gradle/gradle/issues/26440

I have a very large build, and the time it takes to read and write the configuration cache is enormous (in the minutes sometimes) and growing. Now, for the first time, I got an OOM error while gradle was doing some work related to the configuration cache:

<details><summary>OutOfMemoryError Stack Trace</summary>
<p>

```
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.gradle.configurationcache.serialization.codecs.BeanCodec.decode(BeanCodec.kt)
	at org.gradle.configurationcache.serialization.CombinatorsKt$reentrant$1$decodeLoop$1.invokeSuspend(Combinators.kt:166)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at org.gradle.configurationcache.serialization.CombinatorsKt$reentrant$1.decodeLoop(Combinators.kt:167)
	at org.gradle.configurationcache.serialization.CombinatorsKt$reentrant$1.decode(Combinators.kt:131)
	at org.gradle.configurationcache.serialization.codecs.BindingsBackedCodec.decode(BindingsBackedCodec.kt:59)
	at org.gradle.configurationcache.serialization.DefaultReadContext.read(Contexts.kt:269)
	at org.gradle.configurationcache.serialization.beans.BeanPropertyReaderKt.readPropertyValue(BeanPropertyReader.kt:106)
	at org.gradle.configurationcache.serialization.beans.BeanPropertyReader.readStateOf(BeanPropertyReader.kt:68)
	at org.gradle.configurationcache.serialization.codecs.TaskNodeCodec$readTask$2.invokeSuspend(TaskNodeCodec.kt:135)
	at org.gradle.configurationcache.serialization.codecs.TaskNodeCodec$readTask$2.invoke(TaskNodeCodec.kt)
	at org.gradle.configurationcache.serialization.codecs.TaskNodeCodec$readTask$2.invoke(TaskNodeCodec.kt)
	at org.gradle.configurationcache.serialization.codecs.TaskNodeCodecKt.withTaskOf(TaskNodeCodec.kt:237)
	at org.gradle.configurationcache.serialization.codecs.TaskNodeCodecKt.access$withTaskOf(TaskNodeCodec.kt:1)
	at org.gradle.configurationcache.serialization.codecs.TaskNodeCodec.readTask(TaskNodeCodec.kt:129)
	at org.gradle.configurationcache.serialization.codecs.TaskNodeCodec.decode(TaskNodeCodec.kt:78)
	at org.gradle.configurationcache.serialization.codecs.BindingsBackedCodec.decode(BindingsBackedCodec.kt:59)
	at org.gradle.configurationcache.serialization.DefaultReadContext.read(Contexts.kt:269)
	at org.gradle.configurationcache.serialization.CodecKt.readNonNull(Codec.kt:96)
	at org.gradle.configurationcache.serialization.codecs.WorkNodeCodec.readNode(WorkNodeCodec.kt:126)
	at org.gradle.configurationcache.serialization.codecs.WorkNodeCodec.doRead(WorkNodeCodec.kt:104)
	at org.gradle.configurationcache.serialization.codecs.WorkNodeCodec.readWork(WorkNodeCodec.kt:62)
	at org.gradle.configurationcache.ConfigurationCacheState.readWorkGraph(ConfigurationCacheState.kt:493)
	at org.gradle.configurationcache.ConfigurationCacheState.readBuildContent$configuration_cache(ConfigurationCacheState.kt:474)
	at org.gradle.configurationcache.ConfigurationCacheState.readBuildState(ConfigurationCacheState.kt:326)
	at org.gradle.configurationcache.ConfigurationCacheState.readBuildsInTree(ConfigurationCacheState.kt:288)
	at org.gradle.configurationcache.ConfigurationCacheState.readRootBuild(ConfigurationCacheState.kt:259)
	at org.gradle.configurationcache.ConfigurationCacheState.readRootBuildState(ConfigurationCacheState.kt:160)
	at org.gradle.configurationcache.ConfigurationCacheIO$readRootBuildStateFrom$1.invokeSuspend(ConfigurationCacheIO.kt:160)
	at org.gradle.configurationcache.ConfigurationCacheIO$readRootBuildStateFrom$1.invoke(ConfigurationCacheIO.kt)
	at org.gradle.configurationcache.ConfigurationCacheIO$readRootBuildStateFrom$1.invoke(ConfigurationCacheIO.kt)


```

</p>
</details> 

Currently, there is no reasonable way for me to fix my error. My only options are to basically to delete the cache and try again. My build is large and complex and I have no idea what subprojects/tasks/plugins are making the cache so large. My machine has more than enough memory, and this should not be an issue. Even if I didn't get an OOM error, there is still the issue of configuration-cache work taking minutes at a time.

The whole Gradle community would benefit greatly if developers had the tools to start inspecting their own configuration cache. 
- It would help developers optimize their builds
- It would help plugin authors optimize their plugins to provide a minimal footprint
- It would allow new configuration cache issues to reported with greater detail 

One way that could possibly be the easiest way to resolve this issue would be a simple command line tool or gradle task that reads a configuration cache folder (with the .bin files) and writes the entries to a json file. Each entry would just need a human-readable name and a byte size. This likely requires a solution to https://github.com/gradle/gradle/issues/24757 as well; we need a way to identify which build is associated with which configuration cache folder.

Here is a proposed json format:

```json
[
	{
		"build": "<a build identifier>",
		"configuration-cache": {
		    "entries": [
		        {
		            "name": "FileContents[/some/jar]",
		            "size": 293555
		        },
                {
					"name": "Property[somePropertyName]",
		            "size": 53
		        }
		    ]
		}
	}
]
```

**Comment by ov7a** [comment]
This feature request is in the backlog of the relevant team and is prioritized by them.

**Comment by bamboo** [comment]
> Why is `work.bin` over a gigabyte? I would like to inspect it.

This tool might help in the meantime: https://github.com/gradle/gcc2speedscope
