### ISSUE TITLE
Configuration cache should support Kotlin collection builders

### ISSUE THREAD

**Issue by alllex** [gradle/gradle#28325]
### Current Behavior

When creating a collection with `buildList` from Kotlin stdlib, CC deserialization fails

### Expected Behavior

CC serialization should work with Kotlin collection builders

### Context (optional)

This is not a recent regression but an unsupported feature. However, I'd consider it a bug in the CC adoption track.

The most likely reason for the error is the fact that the resulting instance of the list that is being serialized uses `writeReplace` mechanism, that is not currently/entirely supported by CC:
https://github.com/JetBrains/kotlin/blob/f844b87f75b0b02919dd35f26afb87bb47059136/libraries/stdlib/jvm/src/kotlin/collections/builders/ListBuilder.kt#L27-L29

A similar problem may exist for other collection builders such as `buildMap`. However, I did not verify this.

### Steps to Reproduce

```
// build.gradle.kts

tasks.register("something") {
    val myList = buildList { add(1); add(2); add(3) }
    doLast {
        println("My list: $myList")
    }
}
```

Running `./gradlew --configuration-cache something` results in the following error:
```
org.gradle.api.GradleException: Could not load the value of field `collection` of `kotlin.collections.builders.SerializedCollection` bean found in field `$myList` of `Build_gradle$$$result$1$1` bean found in field `action` of `org.gradle.api.internal.AbstractTask$TaskActionWrapper` bean found in field `actions` of task `:something` of type `org.gradle.api.DefaultTask`.
```

### Gradle version

8.7-rc-2

### Build scan URL (optional)

https://ge.gradle.org/s/xwvlrc2zi2aju

**Comment by mlopatkin** [comment]
What we've found so far:
* the builder uses Externalizable internally: it has writeReplace that returns an Externalizable SerializedCollection with a custom serialization protocol. The SerializedCollection has readResolve that reconstructs the builder.
* Despite the above, CC serialization doesn't produce "unsupported Externalizable" here, because when serializing Serializable with `writeReplace`, it unconditionally writes result with bean serialization.
* The `SerializedCollection` contains a (circular) reference to the builder, which seems to be incorrectly deserialized.

At least one issue is that we don't check if the type returned by `writeReplace` is supported by CC serialization. Another issue is handling of circular references there.

**Comment by abstratt** [comment]
It seems this has been addressed in 9.0, possibly by the fix to: https://github.com/gradle/gradle/issues/26942

**Comment by alllex** [comment]
@abstratt, let's not close the issue before we have a test proving it's supported

**Comment by abstratt** [comment]
The original test case is no longer reproducible with Gradle 9. It could be due to a change in the Kotlin library implementation though.

At first, the work on https://github.com/gradle/gradle/issues/26942 to improve support for `writeReplace` looked like could have addressed the underlying issue. However, a similar outcome is obtainable with the following test case:

```
import java.util.stream.*

// Base class: not serializable
abstract class Node {
    public String name;
    public List<Node> edges;
    List<String> collectNames() {
        return collect(new LinkedHashSet()).stream().map { it.name }.collect(Collectors.toCollection(ArrayList::new));
    }
    Set<Node> collect(Set<Node> visited) {
        if (!visited.contains(this)) {
            visited.add(this);
            if (edges != null) {
                edges.stream().forEach { it ->
                    it.collect(visited);
                }
            }
        }
        return visited;
    }
    @Override
    public String toString() {
        return name;
    }
}

// Serializable implementation
class SerializableNode extends Node implements Serializable {}

// Replaceable-as-serializable implementation
class ReplaceableAsSerializableNode extends Node implements Serializable {
    private Object writeReplace() throws ObjectStreamException {
        SerializableNode proxy = new SerializableNode();
        proxy.name = this.name;
        proxy.edges = this.edges;
        return proxy;
    }
}

tasks.register("something") {
    def a = new SerializableNode(name: "a")
    def c = new ReplaceableAsSerializableNode(name: "c")
    def e = new SerializableNode(name: "e")
    
    a.edges = [c]
    c.edges = [e]
    e.edges = [c]

    doLast {
        def names = a.collectNames()
        println(names)
        assert names == ["a", "c", "e"]
    }
}
```
 
which fails in Gradle 9.1 for:

```
gradle something --configuration-cache 
```

**Comment by abstratt** [comment]
```
Calculating task graph as configuration cache cannot be reused because the set of Gradle properties has changed: the value of 'a' was changed.

FAILURE: Build failed with an exception.

* What went wrong:
Could not load the value of field `edges` of `SerializableNode` bean found in field `edges` of `SerializableNode` bean found in field `edges` of `SerializableNode` bean found in field `value` of `groovy.lang.Reference` bean found in field `a` of `build_7byk8gy8qcp1qqipvkkbw8fz1$_run_closure1$_closure2` bean found in field `closure` of `org.gradle.api.internal.AbstractTask$ClosureTaskAction` bean found in field `actions` of task `:something` of type `org.gradle.api.DefaultTask`.
> Index 51 out of bounds for length 4

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.GradleException: Could not load the value of field `edges` of `SerializableNode` bean found in field `edges` of `SerializableNode` bean found in field `edges` of `SerializableNode` bean found in field `value` of `groovy.lang.Reference` bean found in field `a` of `build_7byk8gy8qcp1qqipvkkbw8fz1$_run_closure1$_closure2` bean found in field `closure` of `org.gradle.api.internal.AbstractTask$ClosureTaskAction` bean found in field `actions` of task `:something` of type `org.gradle.api.DefaultTask`.
        at org.gradle.internal.serialize.graph.BeanPropertyExtensionsKt.readPropertyValue(BeanPropertyExtensions.kt:70)
        at org.gradle.internal.serialize.beans.services.BeanPropertyReader.readFieldOf(BeanPropertyReader.kt:93)
        at org.gradle.internal.serialize.beans.services.BeanPropertyReader.readFieldsOf(BeanPropertyReader.kt:73)
        at org.gradle.internal.serialize.beans.services.BeanPropertyReader.readStateOf(BeanPropertyReader.kt:66)
        at org.gradle.internal.serialize.graph.codecs.BeanCodec.readBeanOf(BeanCodec.kt:61)
        at org.gradle.internal.serialize.graph.codecs.BeanCodec.decode(BeanCodec.kt:43)
        at org.gradle.internal.serialize.graph.CombinatorsKt$reentrant$1$decodeLoop$1.invokeSuspend(Combinators.kt:122)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
        at org.gradle.internal.serialize.graph.CombinatorsKt$reentrant$1.decodeLoop(Combinators.kt:123)
        at org.gradle.internal.serialize.graph.CombinatorsKt$reentrant$1.decode(Combinators.kt:85)
        at org.gradle.internal.serialize.graph.codecs.BindingsBackedCodec.decode(BindingsBackedCodec.kt:92)
        at org.gradle.internal.serialize.graph.DefaultReadContext.read(Contexts.kt:283)
        at org.gradle.internal.serialize.graph.CombinatorsKt.readCollectionInto(Combinators.kt:189)
        at org.gradle.internal.serialize.codecs.stdlib.CollectionCodecsKt$collectionCodec$2.invokeSuspend(CollectionCodecs.kt:81)
        at org.gradle.internal.serialize.codecs.stdlib.CollectionCodecsKt$collectionCodec$2.invoke(CollectionCodecs.kt)
        at org.gradle.internal.serialize.codecs.stdlib.CollectionCodecsKt$collectionCodec$2.invoke(CollectionCodecs.kt)
        at org.gradle.internal.serialize.graph.CombinatorsKt$codec$1.decode(Combinators.kt:44)
        at org.gradle.internal.serialize.graph.codecs.BindingsBackedCodec.decode(BindingsBackedCodec.kt:92)
        at org.gradle.internal.serialize.graph.DefaultReadContext.read(Contexts.kt:283)
        at org.gradle.internal.serialize.graph.BeanPropertyExtensionsKt.readPropertyValue(BeanPropertyExtensions.kt:61)
        at org.gradle.internal.serialize.beans.services.BeanPropertyReader.readFieldOf(BeanPropertyReader.kt:93)
        at org.gradle.internal.serialize.beans.services.BeanPropertyReader.readFieldsOf(BeanPropertyReader.kt:73)
        at org.gradle.internal.serialize.beans.services.BeanPropertyReader.readStateOf(BeanPropertyReader.kt:66)
        at org.gradle.internal.serialize.codecs.core.TaskNodeCodec$readTask$2.invokeSuspend(TaskNodeCodec.kt:134)
        at org.gradle.internal.serialize.codecs.core.TaskNodeCodec$readTask$2.invoke(TaskNodeCodec.kt)
        at org.gradle.internal.serialize.codecs.core.TaskNodeCodec$readTask$2.invoke(TaskNodeCodec.kt)
        at org.gradle.internal.serialize.codecs.core.TaskNodeCodecKt.withTaskOf(TaskNodeCodec.kt:236)
        at org.gradle.internal.serialize.codecs.core.TaskNodeCodecKt.access$withTaskOf(TaskNodeCodec.kt:1)
        at org.gradle.internal.serialize.codecs.core.TaskNodeCodec.readTask(TaskNodeCodec.kt:128)
        at org.gradle.internal.serialize.codecs.core.TaskNodeCodec.decode(TaskNodeCodec.kt:79)
        ...
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 51 out of bounds for length 4
        at org.gradle.internal.serialize.codecs.core.jos.JavaObjectSerializationCodec.decode(JavaObjectSerializationCodec.kt:299)
        at org.gradle.internal.serialize.graph.codecs.BindingsBackedCodec.decode(BindingsBackedCodec.kt:92)
        at org.gradle.internal.serialize.graph.DefaultReadContext.read(Contexts.kt:283)
        at org.gradle.internal.serialize.graph.CombinatorsKt.readCollectionInto(Combinators.kt:189)
        at org.gradle.internal.serialize.codecs.stdlib.CollectionCodecsKt$collectionCodec$2.invokeSuspend(CollectionCodecs.kt:81)
        at org.gradle.internal.serialize.codecs.stdlib.CollectionCodecsKt$collectionCodec$2.invoke(CollectionCodecs.kt)
        at org.gradle.internal.serialize.codecs.stdlib.CollectionCodecsKt$collectionCodec$2.invoke(CollectionCodecs.kt)
        at org.gradle.internal.serialize.graph.CombinatorsKt$codec$1.decode(Combinators.kt:44)
        at org.gradle.internal.serialize.graph.codecs.BindingsBackedCodec.decode(BindingsBackedCodec.kt:92)
        at org.gradle.internal.serialize.graph.DefaultReadContext.read(Contexts.kt:283)
        at org.gradle.internal.serialize.graph.BeanPropertyExtensionsKt.readPropertyValue(BeanPropertyExtensions.kt:61)
        ... 220 more


BUILD FAILED in 344ms
Configuration cache entry stored.
```
