### ISSUE TITLE
Composite build exception when adding a library module dependency from the second build

### ISSUE THREAD

**Issue by dimitar71** [gradle/gradle#28357]
### Current Behavior

1. I am having 2 Android projects in two folders next to each other as follow:

`MyApplication`
.. `app` Android application module
...... `build.gradle`
.. `api` - Android library module
...... `build.gradle`
.. `settings.gradle`

`SharedLibraries`
.. `app` Android application module
...... `build.gradle`
.. `shared-library` - Android library module
...... `build.gradle`
.. `settings.gradle`

2. `MyApplication/settings.gradle` has `includeBuild("../SharedLibraries")`.

3. I want to have a `SharedLibraries/shared-library` dependency in `MyApplication/api/build.gradle`

---

When I add in `MyApplication/api/build.gradle` this line:
`implementation(project(":SharedLibraries:shared-library"))`

I get this exception
```
Build file '/Users/dimitar/AndroidStudioProjects/MyApplication/api/build.gradle.kts' line: 33
org.gradle.api.UnknownProjectException: Project with path ':SharedLibraries:shared-library' could not be found in project ':api'.
	at org.gradle.api.internal.project.DefaultProject.project(DefaultProject.java:692)
	at org.gradle.api.internal.project.DefaultProject.project(DefaultProject.java:685)
	at org.gradle.internal.service.scopes.DefaultProjectFinder.getProject(DefaultProjectFinder.java:33)
```
---

Attached is a screenshot of the project structure.

<img width="461" alt="composite_build_project" src="https://github.com/gradle/gradle/assets/1563337/2902ad65-48a1-436d-b438-4b93661ef846">

### Expected Behavior

Library module dependency from a `includeBuild()` project should be valid and used as expected.

### Steps to Reproduce

Please open `MyApplication` project from Android Studio and try to `File > Sync Project with Gradle Files`.

Exception will be shown in `Build` window.

Here is the project zip - [composite_build_exception.zip](https://github.com/gradle/gradle/files/14489329/composite_build_exception.zip)

### Gradle version

8.6

### Your Environment (optional)

Android Studio Iguana
Mac OS Sonoma 14.3.1

**Comment by ov7a** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

You are supposed to use `implementation("com.example.shared_library:1.0")` instead of `implementation(project(":SharedLibraries:shared-library"))`. See the [documentation](https://docs.gradle.org/current/userguide/composite_builds.html).

**Comment by dimitar71** [comment]
I still think the issue lies in composite builds.

The documentation provides sample ofusing binary librarires (JAR, AAR):

`The my-utils multi-project build produces two Java libraries, number-utils and string-utils. The my-app build produces an executable using functions from those libraries.`

The problem I am having is using the Android library module as code, not as JAR/AAR.

**Comment by ov7a** [comment]
> The problem I am having is using the Android library module as code, not as JAR/AAR.

Then try to include those projects in your build without composite builds, using [regular `include`](https://docs.gradle.org/current/userguide/declaring_dependencies_between_subprojects.html)

**Comment by dimitar71** [comment]
`include()` works **only** when modules are part of same project.

These modules are in two separate projects.

Composite builds include a separate build via `includeBuild()`

I would not post here unless I am really stuck.

I think this in issue with Gradle (or Android Gradle plugin).
Still nothing from Android team - https://issuetracker.google.com/issues/328115462, and silence in Gradle Cummnity Slack channel - https://gradle-community.slack.com/archives/CJYS1DAP5/p1709728902331599.

No fun :(

**Comment by dimitar71** [comment]
I stand corrected.
The issue **is** on my side, not a Gradle problem.

Adding `group` and `version` and using Maven coordinates solved it.

Thanks to the responds which nudged me to the right direction - https://gradle-community.slack.com/archives/CAHSN3LDN/p1709760926133779

**Comment by ov7a** [comment]
@dimitar71 Sorry for misleading you. Glad you resolved the issue.

The comment in [the thread](https://www.linen.dev/s/gradle-community/t/16646261/hello-i-am-trying-to-deal-with-a-specific-issue-which-is-hap#5d6a1723-587b-4717-af35-56ab5ae2e231) is right: the documentation on the composite builds should be improved. Thus, I'm reopening this as a documentation issue.
