### ISSUE TITLE
Valid class fails with "java.lang.ClassFormatError" during plugin application

### ISSUE THREAD

**Issue by Berstanio** [gradle/gradle#28389]
### Current Behavior

I'm maintaining a gradle plugin that contains the following class:
```java
public abstract class RuleClosure extends Closure<Task> {

    protected RuleClosure(Object owner) {
        super(Require.nonNull(owner));
    }

    public abstract Task doCall(String taskName);
}
```

the compiled bytecode with `javap -v` looks like this:
```
{
  protected org.moe.gradle.groovy.closures.RuleClosure(java.lang.Object);
    descriptor: (Ljava/lang/Object;)V
    flags: (0x0004) ACC_PROTECTED
    Code:
      stack=2, locals=2, args_size=2
         0: aload_0
         1: aload_1
         2: invokestatic  #1                  // Method org/moe/gradle/utils/Require.nonNull:(Ljava/lang/Object;)Ljava/lang/Object;
         5: invokespecial #7                  // Method groovy/lang/Closure."<init>":(Ljava/lang/Object;)V
         8: return
      LineNumberTable:
        line 29: 0
        line 30: 8
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       9     0  this   Lorg/moe/gradle/groovy/closures/RuleClosure;
            0       9     1 owner   Ljava/lang/Object;

  public abstract org.gradle.api.Task doCall(java.lang.String);
    descriptor: (Ljava/lang/String;)Lorg/gradle/api/Task;
    flags: (0x0401) ACC_PUBLIC, ACC_ABSTRACT
}
```
`doCall` contains no "Code" section, since it is abstract.
However, when trying to import a plugin with this class I get the following exception:
```java
Caused by: java.lang.ClassFormatError: Code attribute in native or abstract methods in class file org/moe/gradle/groovy/closures/RuleClosure
	at org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader.findClass(VisitableURLClassLoader.java:186)
	at org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader.findClass(VisitableURLClassLoader.java:186)
```

### Expected Behavior

The class is seemingly valid and should therefor not throw an exception.

### Steps to Reproduce

1. `git clone https://github.com/Berstanio/TestMOE`
2. `./gradlew build` (or related)

### Gradle version

8.4+

### Gradle version that used to work

8.3

### Your Environment (optional)

I tested it on multiple JDK's with java 11 and 17.

**Comment by ov7a** [comment]
The reproducer can be simplified to
```
buildscript {
  repositories {
	mavenCentral()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
  }
  dependencies {
    classpath "org.multi-os-engine:moe-gradle:1.10.0-SNAPSHOT"

  }
}

apply plugin: 'moe'
```

This can be related to these issues:
* https://github.com/gradle/gradle/issues/26271
* https://github.com/gradle/gradle/issues/24716
