### ISSUE TITLE
ClassCastException during signature verifaction

### ISSUE THREAD

**Issue by Zuplyx** [gradle/gradle#28400]
### Current Behavior

When trying to use the signature verification, the build fails with `ClassCastException: class org.bouncycastle.openpgp.PGPCompressedData cannot be cast to class org.bouncycastle.openpgp.PGPSignatureList`.

Stacktrace (Gradle 8.5):
```
 java.lang.ClassCastException: class org.bouncycastle.openpgp.PGPCompressedData cannot be cast to class org.bouncycastle.openpgp.PGPSignatureList (org.bouncycastle.openpgp.PGPCompressedData and org.bouncycastle.openpgp.PGPSignatureList are in unnamed module of loader org.gradle.initialization.MixInLegacyTypesClassLoader @2fba3fc4)
        at org.gradle.security.internal.SecuritySupport.readSignatures(SecuritySupport.java:93)
        at org.gradle.security.internal.SecuritySupport.readSignatures(SecuritySupport.java:82)
        at org.gradle.api.internal.artifacts.verification.signatures.DefaultSignatureVerificationServiceFactory$DefaultSignatureVerificationService.verify(DefaultSignatureVerificationServiceFactory.java:136)
        at org.gradle.api.internal.artifacts.verification.signatures.CrossBuildSignatureVerificationService.performActualVerification(CrossBuildSignatureVerificationService.java:111)
        at org.gradle.api.internal.artifacts.verification.signatures.CrossBuildSignatureVerificationService.verify(CrossBuildSignatureVerificationService.java:89)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.verification.writer.WriteDependencyVerificationFile$2.run(WriteDependencyVerificationFile.java:419)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$QueueWorker.execute(DefaultBuildOperationExecutor.java:238)
        at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runOperation(DefaultBuildOperationQueue.java:272)
        at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.doRunBatch(DefaultBuildOperationQueue.java:253)
        at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.lambda$runBatch$0(DefaultBuildOperationQueue.java:238)
        at org.gradle.internal.resources.AbstractResourceLockRegistry.whileDisallowingLockChanges(AbstractResourceLockRegistry.java:50)
        at org.gradle.internal.work.DefaultWorkerLeaseService.whileDisallowingProjectLockChanges(DefaultWorkerLeaseService.java:236)
        at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.lambda$runBatch$1(DefaultBuildOperationQueue.java:238)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:264)
        at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:128)
        at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runBatch(DefaultBuildOperationQueue.java:224)
        at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.run(DefaultBuildOperationQueue.java:192)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
```

### Expected Behavior

A `ClassCastException` should never occur during the signature verification. 
If the signature is valid, the key should be added to the `verification-metadata.xml` file.
If the signature is faulty, the user should be presented with a clear error message stating which signature file was invalid.

### Steps to Reproduce

Create a Gradle build and add a dependency on `fr.inria.gforge.spoon:spoon-core:10.4.0`. Then try to create the signature verification data by using `./gradlew --write-verification-metadata pgp,sha256`.

I also created a reproducer here: https://github.com/Zuplyx/gradle-issue-cce

### Gradle version

8.5 locally; 8.6 for the reproducer

**Comment by ov7a** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.
