### ISSUE TITLE
Deprecated properties warning breaks Gradle 8.5 Tooling API when `ProgressListener` is registered

### ISSUE THREAD

**Issue by brigaccess** [gradle/gradle#28464]
### Current Behavior

With Gradle 8.5 and Tooling API `ProgressListener` registered, having deprecated properties in bulid configuration results in the following exception:
```
org.gradle.internal.exceptions.LocationAwareException: Build file '<...>' line: NN
Attempted to serialize java.lang.Class: org.gradle.api.plugins.BasePluginExtension. Forgot to register a type adapter?
<...>
Caused by: java.lang.UnsupportedOperationException: Attempted to serialize java.lang.Class: org.gradle.api.plugins.BasePluginExtension. Forgot to register a type adapter?
	at com.google.gson.internal.bind.TypeAdapters$1.write(TypeAdapters.java:74)
	<...>
        at com.google.gson.Gson.toJson(Gson.java:649)
        at org.gradle.tooling.internal.provider.runner.ProblemsProgressEventConsumer.progress(ProblemsProgressEventConsumer.java:55)
	at org.gradle.tooling.internal.provider.runner.ClientBuildEventGenerator.progress(ClientBuildEventGenerator.java:100)
	at org.gradle.internal.operations.DefaultBuildOperationListenerManager$ProgressShieldingBuildOperationListener.progress(DefaultBuildOperationListenerManager.java:120)
	at org.gradle.internal.operations.DefaultBuildOperationListenerManager$1.progress(DefaultBuildOperationListenerManager.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationProgressEventEmitter.doEmit(DefaultBuildOperationProgressEventEmitter.java:72)
	at org.gradle.internal.operations.DefaultBuildOperationProgressEventEmitter.emitIfCurrent(DefaultBuildOperationProgressEventEmitter.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationProgressEventEmitter.emitNowIfCurrent(DefaultBuildOperationProgressEventEmitter.java:46)
	at org.gradle.api.problems.internal.DefaultProblems.reportAsProgressEvent(DefaultProblems.java:98)
	at org.gradle.api.problems.internal.DefaultReportableProblem.report(DefaultReportableProblem.java:66)
	at org.gradle.internal.featurelifecycle.LoggingDeprecatedFeatureHandler.featureUsed(LoggingDeprecatedFeatureHandler.java:103)
	at org.gradle.internal.deprecation.DeprecationLogger.nagUserWith(DeprecationLogger.java:348)
	at org.gradle.internal.deprecation.DeprecationLogger.nagUserWith(DeprecationLogger.java:247)
	at org.gradle.internal.deprecation.DeprecationMessageBuilder$WithDocumentation.nagUser(DeprecationMessageBuilder.java:140)
	at org.gradle.api.plugins.internal.DefaultBasePluginExtension.logPropertyDeprecation(DefaultBasePluginExtension.java:108)
<...>
```

### Expected Behavior

No exceptions being raised

### Context (optional)

Upgrading to 8.6 and downgrading to 8.4 seem to fix the issue, as does omitting the `ProgressListener` registration.

### Steps to Reproduce

[gradle-problem-serialization-reproducer.tar.gz](https://github.com/gradle/gradle/files/14605434/gradle-problem-serialization-reproducer.tar.gz)

### Gradle version

8.5

**Comment by ov7a** [comment]
Thanks for the report!

Since this works in 8.6 and there will be no 8.5.1, I'm closing this.
