### ISSUE TITLE
Blocker: FileNotFoundException(No such file or directory) while running Junit Test 

### ISSUE THREAD

**Issue by nkumarom** [gradle/gradle#2854]
Gradle 3.5
We run gradle build in an ubuntu docker VM. We have few junit test placed in buildSrc. While running gradle build  we are getting this issue sporadically. Every 2 out of 10 build has this issue. I am assuming that this is  race-condition occurring in gradle. The docker container is very isolated so I do not think it is related to docker. Any small help is appreciated.. 
Why it is trying to find a file even before creating it?

```
:buildSrc:compileTestGroovy
:buildSrc:processTestResources NO-SOURCE
:buildSrc:testClasses
:buildSrc:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:test'.
> Could not generate test report to '/opt/prpc-platform/buildSrc/build/reports/tests/test'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':buildSrc:test'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:98)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:68)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
Caused by: org.gradle.api.GradleException: Could not generate test report to '/opt/prpc-platform/buildSrc/build/reports/tests/test'.
	at org.gradle.api.internal.tasks.testing.junit.report.DefaultTestReport.generateFiles(DefaultTestReport.java:102)
	at org.gradle.api.internal.tasks.testing.junit.report.DefaultTestReport.generateReport(DefaultTestReport.java:55)
	at org.gradle.api.tasks.testing.Test.executeTests(Test.java:662)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:692)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:675)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:115)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:109)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:109)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:90)
	... 20 more
Caused by: org.gradle.internal.operations.MultipleBuildOperationFailures: A build operation failed.
    Could not write to file '/opt/prpc-platform/buildSrc/build/reports/tests/test/classes/com.pega.gradle.base.PegaDepModuleTest.html'.
	at org.gradle.internal.operations.DefaultBuildOperationQueue.waitForCompletion(DefaultBuildOperationQueue.java:100)
	at org.gradle.internal.operations.DefaultBuildOperationProcessor.run(DefaultBuildOperationProcessor.java:60)
	at org.gradle.internal.operations.DefaultBuildOperationProcessor.run(DefaultBuildOperationProcessor.java:85)
	at org.gradle.api.internal.tasks.testing.junit.report.DefaultTestReport$2.render(DefaultTestReport.java:87)
	at org.gradle.api.internal.tasks.testing.junit.report.DefaultTestReport$2.render(DefaultTestReport.java:84)
	at org.gradle.reporting.HtmlReportRenderer.render(HtmlReportRenderer.java:42)
	at org.gradle.api.internal.tasks.testing.junit.report.DefaultTestReport.generateFiles(DefaultTestReport.java:84)
	... 35 more
Caused by: org.gradle.api.UncheckedIOException: Could not write to file '/opt/prpc-platform/buildSrc/build/reports/tests/test/classes/com.pega.gradle.base.PegaDepModuleTest.html'.
	at org.gradle.internal.IoActions$TextFileWriterIoAction.execute(IoActions.java:141)
	at org.gradle.internal.IoActions$TextFileWriterIoAction.execute(IoActions.java:117)
	at org.gradle.internal.IoActions.writeTextFile(IoActions.java:43)
	at org.gradle.reporting.HtmlReportRenderer$DefaultHtmlReportContext.renderHtmlPage(HtmlReportRenderer.java:118)
	at org.gradle.api.internal.tasks.testing.junit.report.DefaultTestReport$HtmlReportFileGenerator.run(DefaultTestReport.java:130)
	at org.gradle.internal.operations.DefaultBuildOperationProcessor$1.execute(DefaultBuildOperationProcessor.java:82)
	at org.gradle.internal.operations.DefaultBuildOperationProcessor$1.execute(DefaultBuildOperationProcessor.java:74)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$OperationHolder.runBuildOperation(DefaultBuildOperationQueue.java:169)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$OperationHolder.run(DefaultBuildOperationQueue.java:162)
	... 2 more
Caused by: java.io.FileNotFoundException: /opt/prpc-platform/buildSrc/build/reports/tests/test/classes/com.pega.gradle.base.PegaDepModuleTest.html (No such file or directory)
	at org.gradle.internal.IoActions$TextFileWriterIoAction.execute(IoActions.java:134)
	... 10 more


BUILD FAILED
```

**Comment by blindpirate** [comment]
I slightly format your issue description.

The error is not saying it's trying find it. I think the reason is that `/opt/prpc-platform/buildSrc/build/reports/tests/test/classes/` directory doesn't exist when Gradle tries to write to `/opt/prpc-platform/buildSrc/build/reports/tests/test/classes/com.pega.gradle.base.PegaDepModuleTest.html`.

So here's the question: why its parent directory doesn't exist? I guess you have concurrent access on the project directory, e.g. multiple docker containers mounting the same directory. Just before container A wants to write to the directory, container B deletes it. Am I right?

**Comment by nkumarom** [comment]
No, the directory is not shared between containers.

**Comment by blindpirate** [comment]
That's weird. Have you tried newer Gradle versions like 4.0 or 4.1? It would be great if you can provide us a sample to reproduce it (fail 2 out of 10 executions) to help us dig into it.

**Comment by nkumarom** [comment]
OS: ubuntu:14.04.3
Docker Version: 1.13.1
JDK: java-1.7.0_79

We just upgraded it to 3.5 from 2.14. If I am able to reproduce it then it would be very easy to find the root cause. Unluckily it is very sporadic.
We have a docker image which contains the monolithic gradle project at /opt/prpc-platform which has 20 + gradle modules. This docker image also contains  gradle cache at /root/.gradle location. We use jenkins pipeline to open this image as node{} and perform a gradle build inside it. There are several node like this running in parallel. When the load is little high, this issue occurs that too very very sporadic.

It is really weird.... Can you please tell me, exactly why this issue occurs? 
There must be a reason as to why this exact stacktrace comes. I have googled a lot but did not find any forum with these stacktrace.... 
I assume that gradle is running test in buildSrc one by one. Once all test has be executed it creates all the respective folder and creates the html file in it. If there is no read operation then how come filenotfoundexception is coming? 

Can this happen. Correct me if I am wrong... Gradle 3.5 has ability to run tasks in parallel... Is it causing this? 


Any help is appreciated...

**Comment by blindpirate** [comment]
I don't think `parallel` caused this because in 3.5 `parallel` is disabled by default.

I've checked the code and didn't find any potential causes. JDK allows to write to an inexistent file directly, which will be created automatically, but this is only possible when its parent directory does exist. If its parent directory doesn't exist, a `FileNotFoundException` will be thrown. That's why I asked if you have concurrent access on the project directory.

As you said, your build is totally isolated in docker images without any directories mounting, could you reproduce this issue in your local machine? I mean, does this issue only occur in Jenkins?

Since you're using `node{}` to run the docker image, AFAIK, with `node {}`, the actual build will be executed on different Jenkins slaves, so which kind of Jenkins slave  node is more easy to have this issue? Is it a fixed node?

**Comment by nkumarom** [comment]
yes, it is a fixed node...

**Comment by blindpirate** [comment]
Looks like some thing wrong with that node. What difference does that node have? Is it same with the environment?

> OS: ubuntu:14.04.3
> Docker Version: 1.13.1
> JDK: java-1.7.0_79

**Comment by petehayes** [comment]
Hi - I work with nkumarom and we continue to see this error popping on Gradle 3.5 - always when generating the test html report.  We are running gradle in parallel mode.  

One question I have is if there is any parallelism in the test report generation?  I looked through the code a bit and I see some queuing of tasks during the report generation and was wondering if there is some multi-threaded code in place there too?

**Comment by kotsi** [comment]
Hi,

I also work with nkumaron and we are seeing a very similar problem in another Windows-based environment, running a standalone Hudson - so no pipelines et al - and in both cases, the two environments are doing virtually the same thing: attempting to build a branch, and run unit tests, though they pop in different places. However, it appears that both problems appear during test execution:

     [exec] * What went wrong:
     [exec] Execution failed for task ':buildSrc:test'.
     [exec] > Failed to create directory 'C:\usr\app\AutomatedInstaller\work\projects\buildSrc\build\test-results\test\binary'

I strongly suspect this is another concurrency problem with gradle, and that in this case, the parent 'test' directory has been deleted underneath us somehow.

**Comment by blindpirate** [comment]
@kotsi @petehayes please try the latest `4.2-rc-1` to see if the situation is improved. I'll raise a discussion internally about it.

**Comment by big-guy** [comment]
@kotsi @nkumarom when the build fails, could you check if the particular directory (and its parents) in the error exists and what the permissions are for it?

Could you also check if the docker container has enough disk space and inodes? (`df -i`)  This sort of looks like a file permission or filesystem wonkiness. The parent directories should be all created well before we execute anything inside the task and we try to create the parent directories before we write the individual HTML pages.  So my suspicions would be:

- The filesystem is doing something funky (because it's low on space or inodes), or
- A separate process is deleting `buildSrc/build` concurrently (either another Gradle build or something else)

Do you have any plugins applied to the `buildSrc` project or any extra configuration for the `test` task?

You might try something low-tech like this in your `buildSrc/settings.gradle`:
```
gradle.projectsLoaded {
  file("build.log") << new Date().toString() + " " + gradle.startParameter
}
```

When the failure occurs, look at `buildSrc/build.log` and try to figure out if there were two builds running at once.

**Comment by petehayes** [comment]
Thanks.  I will add those checks in on failure of this process to see if we
get some more diagnostics.

**Comment by nkumarom** [comment]
We can rule out the inode cause and disk space cause. I ran a build with only 100 free inode but ample of disk space left. The build failed with some different stacktrace.

**Caused by: org.gradle.api.UncheckedIOException: java.io.FileNotFoundException: /opt/prpc-platform/buildSrc/build/test-results/test/binary/results.bin (No space left on device)**
        at org.gradle.api.internal.tasks.testing.junit.result.TestResultSerializer.write(TestResultSerializer.java:55)
        at org.gradle.api.tasks.testing.Test.executeTests(Test.java:640)

**Caused by: java.io.FileNotFoundException: /opt/prpc-platform/buildSrc/build/test-results/test/binary/results.bin (No space left on device)**
        at java.io.FileOutputStream.open(Native Method)

**Comment by amarruedo** [comment]
Hi there!

We are experiencing the same issue. Our scenario is the same, gradle builds inside an ubuntu container that are run by Jenkins pipelines. 

The tests fail randomly, and we have to re-run the build several times till we get no errors. Here is the build log we get when tests fail:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':com.xxxxxxxxxxxx.xxxxxxxxxxxx.sdk:testDebugUnitTest'.
> Could not generate test report to '/Users/cicd-bot/workspace/KAS-33-yyyyyyyyyyyyyyyyyyyy-MIGRX3WCMXHSNLD7E77TAWVA3FRQXIR7R76XWYGLRCC6K4HNIHMA/com.xxxxxxxxxxxx.xxxxxxxxxxxx.sdk/build/reports/tests/testDebugUnitTest'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':com.xxxxxxxxxxxx.xxxxxxxxxxxx.sdk:testDebugUnitTest'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:196)
        at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:193)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:193)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.GradleException: Could not generate test report to '/Users/cicd-bot/workspace/KAS-33-yyyyyyyyyyyyyyyyyyyy-MIGRX3WCMXHSNLD7E77TAWVA3FRQXIR7R76XWYGLRCC6K4HNIHMA/com.xxxxxxxxxxxx.xxxxxxxxxxxx.sdk/build/reports/tests/testDebugUnitTest'.
        at org.gradle.api.internal.tasks.testing.junit.report.DefaultTestReport.generateFiles(DefaultTestReport.java:102)
        at org.gradle.api.internal.tasks.testing.junit.report.DefaultTestReport.generateReport(DefaultTestReport.java:55)
        at org.gradle.api.tasks.testing.Test.executeTests(Test.java:653)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 70 more
Caused by: org.gradle.internal.operations.MultipleBuildOperationFailures: Multiple build operations failed.
    Could not write to file '/Users/cicd-bot/workspace/KAS-33-yyyyyyyyyyyyyyyyyyyy-MIGRX3WCMXHSNLD7E77TAWVA3FRQXIR7R76XWYGLRCC6K4HNIHMA/com.xxxxxxxxxxxx.xxxxxxxxxxxx.sdk/build/reports/tests/testDebugUnitTest/classes/com.xxxxxxxxxxxx.xxxxxxxxxxxx.sdk.common.OpResultTest.html'.
    Could not write to file '/Users/cicd-bot/workspace/KAS-33-yyyyyyyyyyyyyyyyyyyy-MIGRX3WCMXHSNLD7E77TAWVA3FRQXIR7R76XWYGLRCC6K4HNIHMA/com.xxxxxxxxxxxx.xxxxxxxxxxxx.sdk/build/reports/tests/testDebugUnitTest/classes/com.xxxxxxxxxxxx.xxxxxxxxxxxx.sdk.xxx.xxxxxxServiceTest.html'.
        at org.gradle.internal.operations.DefaultBuildOperationQueue.waitForCompletion(DefaultBuildOperationQueue.java:100)
        at org.gradle.internal.operations.DefaultBuildOperationProcessor.run(DefaultBuildOperationProcessor.java:60)
        at org.gradle.internal.operations.DefaultBuildOperationProcessor.run(DefaultBuildOperationProcessor.java:85)
        at org.gradle.api.internal.tasks.testing.junit.report.DefaultTestReport$2.render(DefaultTestReport.java:87)
        at org.gradle.api.internal.tasks.testing.junit.report.DefaultTestReport$2.render(DefaultTestReport.java:84)
        at org.gradle.reporting.HtmlReportRenderer.render(HtmlReportRenderer.java:42)
        at org.gradle.api.internal.tasks.testing.junit.report.DefaultTestReport.generateFiles(DefaultTestReport.java:84)
        ... 80 more
Caused by: org.gradle.api.UncheckedIOException: Could not write to file '/Users/cicd-bot/workspace/KAS-33-yyyyyyyyyyyyyyyyyyyy-MIGRX3WCMXHSNLD7E77TAWVA3FRQXIR7R76XWYGLRCC6K4HNIHMA/com.xxxxxxxxxxxx.xxxxxxxxxxxx.sdk/build/reports/tests/testDebugUnitTest/classes/com.xxxxxxxxxxxx.xxxxxxxxxxxx.sdk.common.OpResultTest.html'.
        at org.gradle.internal.IoActions$TextFileWriterIoAction.execute(IoActions.java:132)
        at org.gradle.internal.IoActions$TextFileWriterIoAction.execute(IoActions.java:108)
        at org.gradle.internal.IoActions.writeTextFile(IoActions.java:38)
        at org.gradle.reporting.HtmlReportRenderer$DefaultHtmlReportContext.renderHtmlPage(HtmlReportRenderer.java:118)
        at org.gradle.api.internal.tasks.testing.junit.report.DefaultTestReport$HtmlReportFileGenerator.run(DefaultTestReport.java:130)
        at org.gradle.internal.operations.DefaultBuildOperationProcessor$1.execute(DefaultBuildOperationProcessor.java:82)
        at org.gradle.internal.operations.DefaultBuildOperationProcessor$1.execute(DefaultBuildOperationProcessor.java:74)
        at org.gradle.internal.operations.DefaultBuildOperationQueue$OperationHolder.runBuildOperation(DefaultBuildOperationQueue.java:169)
        at org.gradle.internal.operations.DefaultBuildOperationQueue$OperationHolder.run(DefaultBuildOperationQueue.java:162)
        ... 2 more
Caused by: java.lang.IllegalStateException: Test outputs data file '/Users/cicd-bot/workspace/KAS-33-yyyyyyyyyyyyyyyyyyyy-MIGRX3WCMXHSNLD7E77TAWVA3FRQXIR7R76XWYGLRCC6K4HNIHMA/com.xxxxxxxxxxxx.xxxxxxxxxxxx.sdk/build/test-results/testDebugUnitTest/binary/output.bin' does not exist but the index file '/Users/cicd-bot/workspace/KAS-33-yyyyyyyyyyyyyyyyyyyy-MIGRX3WCMXHSNLD7E77TAWVA3FRQXIR7R76XWYGLRCC6K4HNIHMA/com.xxxxxxxxxxxx.xxxxxxxxxxxx.sdk/build/test-results/testDebugUnitTest/binary/output.bin.idx' does
        at org.gradle.api.internal.tasks.testing.junit.result.TestOutputStore$Reader.<init>(TestOutputStore.java:272)
        at org.gradle.api.internal.tasks.testing.junit.result.TestOutputStore.reader(TestOutputStore.java:388)
        at org.gradle.api.internal.tasks.testing.junit.result.TestOutputStoreBackedResultsProvider.withReader(TestOutputStoreBackedResultsProvider.java:33)
        at org.gradle.api.internal.tasks.testing.junit.result.InMemoryTestResultsProvider.hasOutput(InMemoryTestResultsProvider.java:36)
        at org.gradle.api.internal.tasks.testing.junit.report.ClassPageRenderer.registerTabs(ClassPageRenderer.java:108)
        at org.gradle.api.internal.tasks.testing.junit.report.PageRenderer$5.render(PageRenderer.java:180)
        at org.gradle.api.internal.tasks.testing.junit.report.PageRenderer$5.render(PageRenderer.java:175)
        at org.gradle.reporting.TabbedPageRenderer.render(TabbedPageRenderer.java:71)
        at org.gradle.reporting.TabbedPageRenderer.render(TabbedPageRenderer.java:25)
        at org.gradle.reporting.HtmlReportRenderer$DefaultHtmlReportContext$1.doExecute(HtmlReportRenderer.java:123)
        at org.gradle.reporting.HtmlReportRenderer$DefaultHtmlReportContext$1.doExecute(HtmlReportRenderer.java:118)
        at org.gradle.internal.ErroringAction.execute(ErroringAction.java:35)
        at org.gradle.internal.IoActions$TextFileWriterIoAction.execute(IoActions.java:127)
        ... 10 more


BUILD FAILED
```

**Comment by amarruedo** [comment]
More info on our environment:

- Ubuntu 16.04 based docker container
- gradle 3.3
- OpenJDK Runtime Environment (build 1.8.0_121-b13-0ubuntu1.16.04.2-b13)
- OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by atorstling** [comment]
We're still getting this on 4.10, as soon as parallel builds are enabled.

**Comment by pskrivanek** [comment]
I'm using Gradle 5.2 and for parallel testing have the same problem.
