### ISSUE TITLE
JVM Test Suit does not allow adding dependencies if there's build logic iterating over declared dependencies

### ISSUE THREAD

**Issue by ALikhachev** [gradle/gradle#28867]
### Current Behavior

Such build logic makes adding dependencies to a test suit impossible:
```
configurations.configureEach {
    if (isCanBeResolved && !isCanBeConsumed) {
        allDependencies.configureEach { // <-- removing this logic solves the problem

        }
    }
}
```

Project configuration fails with
```
FAILURE: Build failed with an exception.

* Where:
Build file '[redacted]/test-suites-dependencies/build.gradle.kts' line: 26

* What went wrong:
Could not create domain object 'myAwesomeTests' (JvmTestSuite)
> The value for property 'dependencies.implementation' property 'dependencies' is final and cannot be changed any further.
```

### Expected Behavior

It's possible to iterate over declared dependencies and add dependencies to test suites

### Context (optional)

We use such build logic in the [Kotlin repo](https://github.com/JetBrains/kotlin/blob/2b9b66b2b24124172741f4b3e4ef4b944c28e46f/repo/gradle-build-conventions/buildsrc-compat/src/main/kotlin/common-configuration.gradle.kts#L19) to add dependency constrains dynamically via a convention plugin

This used to work on Gradle versions below 8.6

### Steps to Reproduce

https://github.com/ALikhachev/gradle-reproducers/tree/main/test-suites-dependencies

### Gradle version

8.6, 8.7

### Gradle version that used to work

8.5

**Comment by big-guy** [comment]
This is working as designed. Once the dependencies have been observed, we can't allow mutations that could change the set of dependencies. 

I think it's unnecessary to look at the dependencies to see if `gson` is declared and only add the constraint then. You can add the constraint all of the time and if it's not used, the constraint won't matter. 

I think something like this would work:
```
val gsonVersion = rootProject.extra["versions.gson"] as String
dependencies {
    constraints {
        configurations.all {
            if (isCanBeResolved && !isCanBeConsumed && isCanBeDeclared) {
                this@constraints.add(name, "com.google.code.gson:gson") {
                    version {
                        require(gsonVersion)
                    }
                    because("Force using same gson version because of https://github.com/google/gson/pull/1991")
                }
            }
        }
    }
}
```

The previous code had a couple of subtle problems:
- It didn't add the constraint if the dependency on gson was added after this check. 
- It didn't add the constraint if the dependency on gson was transitive.

Alternatively, if you only wanted to enforce a particular version of gson when you've directly declared that you use gson, you could instead use a strict version at the declaration site.

**Comment by bric3** [comment]
@big-guy I got a similar error while applying a dependency as described in the doc, I think. This was working in JUnit 8.5

I'm not quite sure what's going on as the code below just declares / register a new test suite, with a suite implementation dep. That said maybe there are other things at play here (unsure what at this moment) as I wasn't able to reproduce in a minimal reproducer.

https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html#:~:text=integrationTest%22)%20%7B-,dependencies%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20implementation(project())%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D,-targets%20%7B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20all

Doc snippet

```gradle
testing {
    suites { 
        test { 
            useJUnitJupiter() 
        }

        integrationTest(JvmTestSuite) { 
            dependencies {
                implementation project() 
            }

            targets { 
                all {
                    testTask.configure {
                        shouldRunAfter(test)
                    }
                }
            }
        }
    }
}
```

Our extension function 

```gradle
ext.addTestSuiteExtendingForDir = { testSuiteName, parentSuiteName, dirName ->
  testing {
    suites {
      register(testSuiteName, JvmTestSuite, {
        dependencies {
          implementation project()
        }
        sources {
          java {
            srcDirs = ["src/$dirName/java"]
          }
          resources {
            srcDirs = ["src/$dirName/resources"]
          }
          if (project.plugins.hasPlugin('groovy')) {
            groovy {
              srcDirs = ["src/$dirName/groovy"]
            }
          }
          if (project.plugins.hasPlugin('kotlin')) {
            kotlin {
              srcDirs = ["src/$dirName/kotlin"]
            }
          }
          if (project.plugins.hasPlugin('scala')) {
            scala {
              srcDirs = ["src/$dirName/scala"]
            }
          }
        }
      })
    }
  }
```


<details><summary>stacktrace</summary

```
Caused by: java.lang.IllegalStateException: Could not create domain object 'latestDepTest' (JvmTestSuite)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.domainObjectCreationException(DefaultNamedDomainObjectCollection.java:1042)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.tryCreate(DefaultNamedDomainObjectCollection.java:1014)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.calculateOwnValue(DefaultNamedDomainObjectCollection.java:988)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:117)
        at org.gradle.api.internal.provider.Collectors$ElementFromProvider.collectEntries(Collectors.java:105)
        at org.gradle.api.internal.provider.Collectors$TypedCollector.collectEntries(Collectors.java:371)
        at org.gradle.api.internal.provider.Collectors$TypedCollector.collectInto(Collectors.java:366)
        at org.gradle.api.internal.collections.SortedSetElementSource.realize(SortedSetElementSource.java:144)
        at org.gradle.api.internal.collections.SortedSetElementSource.addPending(SortedSetElementSource.java:173)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAddLater(DefaultDomainObjectCollection.java:295)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.doAddLater(DefaultNamedDomainObjectCollection.java:163)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.addLater(DefaultNamedDomainObjectCollection.java:158)
        at org.gradle.api.internal.AbstractPolymorphicDomainObjectContainer.createDomainObjectProvider(AbstractPolymorphicDomainObjectContainer.java:91)
        at org.gradle.api.internal.AbstractPolymorphicDomainObjectContainer.register(AbstractPolymorphicDomainObjectContainer.java:83)
        at org.gradle.api.internal.DefaultPolymorphicDomainObjectContainer_Decorated.register(Unknown Source)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:547)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:218)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:99)
        at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:38)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:65)
        at test_suites_r9auhkrqce1grvi3u2lgfp6l$_run_closure1$_closure4$_closure6.doCall$original(/Users/brice.dutheil/go/src/github.com/DataDog/dd-trace-java/gradle/test-suites.gradle:6)
        at test_suites_r9auhkrqce1grvi3u2lgfp6l$_run_closure1$_closure4$_closure6.doCall(/Users/brice.dutheil/go/src/github.com/DataDog/dd-trace-java/gradle/test-suites.gradle)
        at org.gradle.util.internal.ClosureBackedAction.execute(ClosureBackedAction.java:73)
        at org.gradle.util.internal.ConfigureUtil.configureTarget(ConfigureUtil.java:166)
        at org.gradle.util.internal.ConfigureUtil.configureSelf(ConfigureUtil.java:154)
        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:97)
        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:37)
        at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:57)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:65)
        at test_suites_r9auhkrqce1grvi3u2lgfp6l$_run_closure1$_closure4.doCall$original(/Users/brice.dutheil/go/src/github.com/DataDog/dd-trace-java/gradle/test-suites.gradle:5)
        at test_suites_r9auhkrqce1grvi3u2lgfp6l$_run_closure1$_closure4.doCall(/Users/brice.dutheil/go/src/github.com/DataDog/dd-trace-java/gradle/test-suites.gradle)
        at org.gradle.util.internal.ClosureBackedAction.execute(ClosureBackedAction.java:73)
        at org.gradle.util.internal.ConfigureUtil.configureTarget(ConfigureUtil.java:166)
        at org.gradle.util.internal.ConfigureUtil.configure(ConfigureUtil.java:107)
        at org.gradle.util.internal.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:178)
        at org.gradle.internal.extensibility.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:177)
        at org.gradle.internal.extensibility.ExtensionsStorage.configureExtension(ExtensionsStorage.java:64)
        at org.gradle.internal.extensibility.DefaultConvention.configureExtension(DefaultConvention.java:388)
        at org.gradle.internal.extensibility.DefaultConvention.access$500(DefaultConvention.java:49)
        at org.gradle.internal.extensibility.DefaultConvention$ExtensionsDynamicObject.tryInvokeMethod(DefaultConvention.java:317)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:99)
        at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:38)
        at org.gradle.groovy.scripts.BasicScript$ScriptDynamicObject.tryInvokeMethod(BasicScript.java:138)
        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
        at org.gradle.api.internal.project.DefaultDynamicLookupRoutine.invokeMethod(DefaultDynamicLookupRoutine.java:58)
        at org.gradle.groovy.scripts.BasicScript.invokeMethod(BasicScript.java:87)
        at test_suites_r9auhkrqce1grvi3u2lgfp6l$_run_closure1.doCall$original(/Users/brice.dutheil/go/src/github.com/DataDog/dd-trace-java/gradle/test-suites.gradle:4)
        at test_suites_r9auhkrqce1grvi3u2lgfp6l$_run_closure1.doCall(/Users/brice.dutheil/go/src/github.com/DataDog/dd-trace-java/gradle/test-suites.gradle)
        at org.gradle.internal.extensibility.DefaultExtraPropertiesExtension.methodMissing(DefaultExtraPropertiesExtension.java:134)
        at test_suites_r9auhkrqce1grvi3u2lgfp6l$_run_closure2.doCall$original(/Users/brice.dutheil/go/src/github.com/DataDog/dd-trace-java/gradle/test-suites.gradle:74)
        at test_suites_r9auhkrqce1grvi3u2lgfp6l$_run_closure2.doCall(/Users/brice.dutheil/go/src/github.com/DataDog/dd-trace-java/gradle/test-suites.gradle)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:547)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:218)
        at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:50)
        at org.gradle.groovy.scripts.BasicScript$ScriptDynamicObject.tryInvokeMethod(BasicScript.java:138)
        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
        at org.gradle.api.internal.project.DefaultDynamicLookupRoutine.invokeMethod(DefaultDynamicLookupRoutine.java:58)
        at org.gradle.groovy.scripts.BasicScript.invokeMethod(BasicScript.java:87)
        at build_6jn149m1x4xch7j4npgg6jovz.run(/Users/brice.dutheil/go/src/github.com/DataDog/dd-trace-java/dd-java-agent/instrumentation/junit-4.10/build.gradle:13)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
        ... 158 more
Caused by: java.lang.IllegalStateException: The value for property 'dependencies.implementation' property 'dependencies' is final and cannot be changed any further.
        at org.gradle.api.internal.provider.ValueState$FinalizedValue.beforeMutate(ValueState.java:394)
        at org.gradle.api.internal.provider.AbstractProperty.assertCanMutate(AbstractProperty.java:398)
        at org.gradle.api.internal.provider.AbstractCollectionProperty.addExplicitCollector(AbstractCollectionProperty.java:207)
        at org.gradle.api.internal.provider.AbstractCollectionProperty.add(AbstractCollectionProperty.java:144)
        at org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyCollector.doAddEager(DefaultDependencyCollector.java:89)
        at org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyCollector.add(DefaultDependencyCollector.java:149)
        at org.gradle.api.internal.artifacts.dsl.dependencies.DependenciesExtensionModule.call(DependenciesExtensionModule.java:229)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:547)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:218)
        at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:62)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:65)
        at test_suites_r9auhkrqce1grvi3u2lgfp6l$_run_closure1$_closure4$_closure6$_closure7$_closure8.doCall$original(/Users/brice.dutheil/go/src/github.com/DataDog/dd-trace-java/gradle/test-suites.gradle:8)
        at test_suites_r9auhkrqce1grvi3u2lgfp6l$_run_closure1$_closure4$_closure6$_closure7$_closure8.doCall(/Users/brice.dutheil/go/src/github.com/DataDog/dd-trace-java/gradle/test-suites.gradle)
        at org.gradle.util.internal.ClosureBackedAction.execute(ClosureBackedAction.java:73)
        at org.gradle.util.internal.ConfigureUtil.configureTarget(ConfigureUtil.java:166)
        at org.gradle.util.internal.ConfigureUtil.configure(ConfigureUtil.java:107)
        at org.gradle.util.internal.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:178)
        at org.gradle.api.plugins.jvm.internal.DefaultJvmTestSuite.dependencies(DefaultJvmTestSuite.java:297)
        at org.gradle.api.plugins.jvm.internal.DefaultJvmTestSuite_Decorated.dependencies(Unknown Source)
        at org.gradle.api.plugins.jvm.internal.DefaultJvmTestSuite_Decorated$dependencies.call(Unknown Source)
        at test_suites_r9auhkrqce1grvi3u2lgfp6l$_run_closure1$_closure4$_closure6$_closure7.doCall$original(/Users/brice.dutheil/go/src/github.com/DataDog/dd-trace-java/gradle/test-suites.gradle:7)
        at test_suites_r9auhkrqce1grvi3u2lgfp6l$_run_closure1$_closure4$_closure6$_closure7.doCall(/Users/brice.dutheil/go/src/github.com/DataDog/dd-trace-java/gradle/test-suites.gradle)
        at org.gradle.util.internal.ClosureBackedAction.execute(ClosureBackedAction.java:73)
        at org.gradle.util.internal.ConfigureUtil.configureTarget(ConfigureUtil.java:166)
        at org.gradle.util.internal.ConfigureUtil.configure(ConfigureUtil.java:107)
        at org.gradle.util.internal.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:178)
        at org.gradle.api.internal.DefaultMutationGuard$1.execute(DefaultMutationGuard.java:66)
        at org.gradle.internal.code.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:124)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:110)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:30)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:27)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:67)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:60)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:167)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:60)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:48)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:107)
        at org.gradle.internal.ImmutableActionSet$SetWithFewActions.execute(ImmutableActionSet.java:285)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:280)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.doAdd(DefaultNamedDomainObjectCollection.java:125)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.tryCreate(DefaultNamedDomainObjectCollection.java:1008)
        ... 216 more
```


</details>
