### ISSUE TITLE
newer version testImplementation dependency can't not overlay older implementation dependency properly

### ISSUE THREAD

**Issue by douo** [gradle/gradle#2914]
### Steps to Reproduce (for bugs)

1. add dependencies

```
dependencies {
      ...
      implementation 'com.google.auto.service:auto-service:1.0-rc3'
      testImplementation "com.google.truth:truth:0.35"
}
```
2.  write some test code

```
final Object object = new Object();
Truth.assertThat(object).isEqualTo(object);
```
3. run the test and will throw a  exception:

```
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
    
    	at com.google.common.truth.FailureContext.<init>(FailureContext.java:45)
    	at com.google.common.truth.AbstractVerb.<init>(AbstractVerb.java:42)
    	at com.google.common.truth.TestVerb.<init>(TestVerb.java:55)
    	at com.google.common.truth.TestVerb.<init>(TestVerb.java:47)
    	at com.google.common.truth.TestVerb.<init>(TestVerb.java:43)
    	at com.google.common.truth.StandardSubjectBuilder.<init>(StandardSubjectBuilder.java:69)
    	at com.google.common.truth.StandardSubjectBuilder.forCustomFailureStrategy(StandardSubjectBuilder.java:63)
    	at com.google.common.truth.Truth.<clinit>(Truth.java:109)
```

### Why

google/auto-service has depend on google/guava:19.0 and google/truth has depend on google/guava:22.0-android

Run `gradle dependencies`  we can see gradle resolve these conflict properly.

```
runtimeClasspath - Runtime classpath of source set 'main'.
+--- com.google.auto.service:auto-service:1.0-rc3
|    +--- com.google.auto:auto-common:0.3
|    |    \--- com.google.guava:guava:18.0 -> 19.0
|    \--- com.google.guava:guava:19.0
```

```
testRuntimeClasspath - Runtime classpath of source set 'test'.
+--- com.google.auto.service:auto-service:1.0-rc3
|    +--- com.google.auto:auto-common:0.3
|    |    \--- com.google.guava:guava:18.0 -> 22.0-android
|    |         +--- com.google.code.findbugs:jsr305:1.3.9
|    |         +--- com.google.errorprone:error_prone_annotations:2.0.18 -> 2.0.19
|    |         +--- com.google.j2objc:j2objc-annotations:1.1
|    |         \--- org.codehaus.mojo:animal-sniffer-annotations:1.14
|    \--- com.google.guava:guava:19.0 -> 22.0-android (*)
\--- com.google.truth:truth:0.35
     +--- com.google.guava:guava:22.0-android (*)
     +--- junit:junit:4.12
     |    \--- org.hamcrest:hamcrest-core:1.3
     \--- com.google.errorprone:error_prone_annotations:2.0.19
```

But Android Studio is not, after run the test we can see two guava in classpath:

```
... -classpath "...:/Users/xxx/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/19.0/6ce200f6b23222af3d8abb6b6459e6c44f4bb0e9/guava-19.0.jar:...:/Users/xxx/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/22.0-android/7b2fc7ef242f35bc2c9a3b816ed846c9345e3f95/guava-22.0-android.jar:..." com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 info.dourok.compiler.SomeTest
```

the solution is simple, just declare a implementation dependency to guava

     implementation 'com.google.guava:guava:23.0-android'

But I support this behavior is a bug.

### Your Environment
- gradle-4.1-all.zip
- Android Studio 3.0 beta5
- java-library plugin

**Comment by oehme** [comment]
We can make this a bit better (see #994), but generally this can always happen, because we can't stop IDEA from computing `test classpath = RUNTIME + TEST`. So you can always end up with this situation if you have different versions on your runtime and test classpath.

You can [force](https://docs.gradle.org/current/userguide/dependency_management.html#sec:finetuning_the_dependency_resolution_process) the same version across all `Configurations` in your project to avoid problems like these.
