### ISSUE TITLE
Allow configurations to be safely resolved from outside of owning scope

### ISSUE THREAD

**Issue by aalmiray** [gradle/gradle#29503]
### Expected Behavior

As explained at https://docs.gradle.org/8.8/userguide/viewing_debugging_dependencies.html#sub:resolving-unsafe-configuration-resolution-errors there are ways for two projects to exchange information safely. However, the suggested fix does not apply to plugins that are registered with the `Settings` instance as it happens with the Gradle enforcer plugin (see https://github.com/kordamp/enforcer-gradle-plugin/issues/17)

There are some rules provided by the enforcer plugin that require resolving one ore more configurations, whether those are the original configuration or a detached copy is a matter of impl details. The point is that those configurations will be considered outside of the owning scope (the project) as the plugin is the actor/accessor.

If the suggested fix were to be followed it would mean creating additional configurations in a project such that they could be consumed by the plugin. That seems kind of odd, error prone, tiresome, specially given some rules would need to scan all "reachable" configurations (i.e visible and resolvable) in order to perform their duties.

### Current Behavior (optional)

Warnings appear on the console. Current behavior will be flagged as error in Gradle 9.0

```
Resolution of the configuration :jreleaser-gitter-java-sdk:testRuntimeClasspathCopy3 was attempted from a context different than the project context. Have a look at the documentation to understand why this is a problem and how it can be resolved. This behavior has been deprecated. This will fail with an error in Gradle 9.0. For more information, please refer to https://docs.gradle.org/8.8/userguide/viewing_debugging_dependencies.html#sub:resolving-unsafe-configuration-resolution-errors in the Gradle documentation.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:725)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$500(DefaultConfiguration.java:156)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ResolverResultsResolutionResultProvider.getValue(DefaultConfiguration.java:703)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ResolverResultsResolutionResultProvider.getValue(DefaultConfiguration.java:664)
	at org.gradle.api.internal.artifacts.configurations.ResolutionResultProvider$1.getValue(ResolutionResultProvider.java:53)
	at org.gradle.api.internal.artifacts.configurations.ResolutionBackedFileCollection.getSelectedArtifacts(ResolutionBackedFileCollection.java:95)
	at org.gradle.api.internal.artifacts.configurations.ResolutionBackedFileCollection.visitContents(ResolutionBackedFileCollection.java:73)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:361)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.visitContents(DefaultConfiguration.java:526)
	at org.gradle.api.internal.file.AbstractFileCollection.getFiles(AbstractFileCollection.java:124)
	at org.gradle.api.internal.artifacts.configurations.DefaultUnlockedConfiguration_Decorated.getFiles(Unknown Source)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolve(DefaultConfiguration.java:516)
	at enforcer.rules.BanDuplicateClasses.handleConfiguration(BanDuplicateClasses.groovy:154)
	at enforcer.rules.BanDuplicateClasses.access$0(BanDuplicateClasses.groovy)
	at enforcer.rules.BanDuplicateClasses$_enforceBanDuplicates_closure2.doCall$original(BanDuplicateClasses.groovy:102)
	at enforcer.rules.BanDuplicateClasses$_enforceBanDuplicates_closure2.doCall(BanDuplicateClasses.groovy)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
	at groovy.lang.Closure.call(Closure.java:427)
	at groovy.lang.Closure.call(Closure.java:416)
	at enforcer.rules.BanDuplicateClasses.enforceBanDuplicates(BanDuplicateClasses.groovy:99)
	at enforcer.rules.BanDuplicateClasses.doExecute(BanDuplicateClasses.groovy:84)
	at enforcer.rules.AbstractFilteringEnforcerRule.execute(AbstractFilteringEnforcerRule.groovy:76)
	at org.kordamp.gradle.plugin.enforcer.internal.AbstractEnforcerRuleInvoker.invokeRule(AbstractEnforcerRuleInvoker.groovy:167)
	at org.kordamp.gradle.plugin.enforcer.internal.AbstractEnforcerRuleInvoker.maybeCreateAndInvokeRules(AbstractEnforcerRuleInvoker.groovy:58)
	at org.kordamp.gradle.plugin.enforcer.internal.BuildEnforcerRuleInvoker.doProjectsEvaluated(BuildEnforcerRuleInvoker.groovy:116)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.kordamp.gradle.plugin.enforcer.internal.BuildEnforcerRuleInvoker$_registerAllProjectsEvaluatedListener_closure3.doCall$original(BuildEnforcerRuleInvoker.groovy:215)
	at org.kordamp.gradle.plugin.enforcer.internal.BuildEnforcerRuleInvoker$_registerAllProjectsEvaluatedListener_closure3.doCall(BuildEnforcerRuleInvoker.groovy)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
	at groovy.lang.Closure.call(Closure.java:427)
	at groovy.lang.Closure.call(Closure.java:406)
	at groovy.lang.Closure.run(Closure.java:498)
	at org.kordamp.gradle.plugin.enforcer.internal.BuildEnforcerAllProjectsEvaluatedListener.allProjectsEvaluated(BuildEnforcerAllProjectsEvaluatedListener.groovy:39)
	at org.kordamp.gradle.listener.ProjectEvaluationListenerManager$Listener.projectsEvaluated(ProjectEvaluationListenerManager.groovy:119)
```

### Context

Any projects consuming the enforcer plugin will fail once they migrate to Gradle 9.x

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

@aalmiray Can you be more explicit about how the plugin implements "dependency resolution aware" rules?
This might help the team confirm or provide workarounds for the following statement:

> The point is that those configurations will be considered outside of the owning scope (the project) as the plugin is the actor/accessor.

Might be related to:
* #1629

**Comment by aalmiray** [comment]
Understood. The current design of the enforcer plugin ensures that rules are evaluated every single time a build is run, ensuring they are followed, instead of giving the choice to developers to ignore or forget about them rules.

AFAICT there's no base task that's always invoked regardless of the task(s) supplied to the command line, right? I mean, if `classes` (as an example, not a good one, I know) was to be invoked regardless of what you type in, then an enforcer task could latch on to it transparently and thus be invoked every single time (unless disabled by other means).
