### ISSUE TITLE
8.5 thru 8.8 busted on jdk-22. 

### ISSUE THREAD

**Issue by crowlogic** [gradle/gradle#29660]
### Current Behavior

```java
Press <enter> to keep the current choice[*], or type selection number: 6
update-alternatives: using /usr/lib/jvm/jdk-22-oracle-x64/bin/java to provide /usr/bin/java (java) in manual mode
[crow@c15 20240622-01:03:55PM]~$ cd a
[crow@c15 20240622-01:03:55PM]~/a$ gradle in^C
[crow@c15 20240622-01:03:58PM]~/a$ make jar
make: Nothing to be done for 'jar'.
[crow@c15 20240622-01:03:59PM]~/a$ gradle install
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.gradle.internal.concurrent.CompositeStoppable.<clinit>(CompositeStoppable.java:37)
	at org.gradle.internal.classloader.ClassLoaderUtils.tryClose(ClassLoaderUtils.java:51)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:64)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:34)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 7 more
```

### Expected Behavior

jdk 21 works fine

```java
Press <enter> to keep the current choice[*], or type selection number: 5
update-alternatives: using /usr/lib/jvm/jdk-21-oracle-x64/bin/java to provide /usr/bin/java (java) in manual mode
[crow@c15 20240622-01:04:25PM]~/a$ gradle install

> Configure project :
Project : => 'arb4j' Java module

FAILURE: Build failed with an exception.

* What went wrong:
Task 'install' not found in root project 'arb4j'.

```

### Steps to Reproduce

```java
Press <enter> to keep the current choice[*], or type selection number: 6
update-alternatives: using /usr/lib/jvm/jdk-22-oracle-x64/bin/java to provide /usr/bin/java (java) in manual mode
[crow@c15 20240622-01:03:55PM]~$ cd a
[crow@c15 20240622-01:03:55PM]~/a$ gradle in^C
[crow@c15 20240622-01:03:58PM]~/a$ make jar
make: Nothing to be done for 'jar'.
[crow@c15 20240622-01:03:59PM]~/a$ gradle install
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.gradle.internal.concurrent.CompositeStoppable.<clinit>(CompositeStoppable.java:37)
	at org.gradle.internal.classloader.ClassLoaderUtils.tryClose(ClassLoaderUtils.java:51)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:64)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:34)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 7 more
```

### Gradle version

8.5

**Comment by ov7a** [comment]
Please take a look at the [Compatibility Matrix](https://docs.gradle.org/current/userguide/compatibility.html#java)

Java 22 can be used to _run_ Gradle since 8.8.
