### ISSUE TITLE
 Gradle build failed with build.gradle not found

### ISSUE THREAD

**Issue by shashidhar502** [gradle/gradle#2967]
As we have a limitation of 240 characters
we are creating substitution drive for the project and then invoking gradle commands on it
when we invoke gradlew command
we are getting following error
Build file 'A:\ProjectLocation\build.gradle' does not exist.

But when we check the physical location the file exists
And the issue is reproduced 1 out of 50 machines

when we run gradlew --stop before the the build then build works smoothly

As per stackoverflow suggestion the file check should be like this
In few machines
file.exists() == false
file.getAbsoluteFile().exists() == true

### Your Environment

 * Build scan URL:

**Comment by oehme** [comment]
Without a reproducible example I don't think we'll be able to help here. Given the fact that it fails on "1 out of 50" machines makes it seem like a problem in the setup of those machines.

You could debug Gradle using `-Dorg.gradle.debug=true` and see why this happens on some of the machines. Maybe this way you will find some more details that will help us fix the issue.

**Comment by shashidhar502** [comment]
please find the stacktrace


A:\Sample2>gradlew clean -b build.gradle --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Build file 'A:\Sample2\build.gradle' does not exist.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.InvalidUserDataException: Build file 'A:\Sample2\build.gradle' does not exist.
        at org.gradle.initialization.BuildFileProjectSpec.checkPreconditions(BuildFileProjectSpec.java:52)
        at org.gradle.initialization.AbstractProjectSpec.containsProject(AbstractProjectSpec.java:27)
        at org.gradle.initialization.DefaultSettingsLoader.findAndLoadSettings(DefaultSettingsLoader.java:51)
        at org.gradle.internal.composite.CompositeBuildSettingsLoader.findAndLoadSettings(CompositeBuildSettingsLoader.java:48)
        at org.gradle.initialization.NotifyingSettingsLoader.findAndLoadSettings(NotifyingSettingsLoader.java:33)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:147)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)


BUILD FAILED

Total time: 1.423 secs

**Comment by shashidhar502** [comment]
As per stackoverflow suggestion
its better to use
file.getAbsoluteFile().exists() for file check
https://stackoverflow.com/questions/919918/file-exists-returns-false-when-file-exists

check attached image of your code

![image](https://user-images.githubusercontent.com/4785725/30587276-33307ba4-9d50-11e7-8702-abfa6f091322.png)

**Comment by oehme** [comment]
The path that Gradle prints points to the correct file, so I assume there is something else going on, like missing permissions.

**Comment by shashidhar502** [comment]
I have checked the path the file exist in that place and permissions are available
and i check the file availability using ant task

**Comment by oehme** [comment]
Since you have a machine where you can reproduce it, it would be best if you ran Gradle with a debugger attached and investigated why `file.exists()` returns false at this point.
