### ISSUE TITLE
TestKit is broken when tests execute Java compilation and debugging is turned on

### ISSUE THREAD

**Issue by hegyibalint** [gradle/gradle#29696]
### Current behavior

When:
 - TestKit is used to execute a build
 - The build does something related to a Java compilation
 - And the executor is used with **debugging on**

The test will fail with an `IllegalAccessError`:
```
Caused by: java.lang.IllegalAccessError: class org.gradle.api.internal.tasks.compile.JdkJavaCompiler (in unnamed module @0x25377fa1) cannot access class com.sun.tools.javac.util.Context (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.util to unnamed module @0x25377fa1	
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.<init>(JdkJavaCompiler.java:59)	
	at org.gradle.api.internal.tasks.compile.DefaultJavaCompilerFactory.createTargetCompiler(DefaultJavaCompilerFactory.java:93)
```

### Expected Behavior

TestKit-driven tests should not fail when debugging is on.

### Context

The modifications done in order to extract more structured compiler information (https://github.com/gradle/gradle/pull/28281) made it necessary to have new `--add-exports` flags:

https://github.com/gradle/gradle/blob/b47610e5c225c52140ac7a55893ecc8f2eac6780/platforms/core-runtime/base-services/src/main/java/org/gradle/internal/jvm/JpmsConfiguration.java#L40-L41

The modification above made sure that normally executed builds were executed with the correct flags.
We've made a mistake and not expanded the list of JVM flags passed to the test executor set by `java-gradle-plugin`.

This made the behavior differ:
 - When debugging is off, the Gradle runner is forked, and our standard mechanism adds the flags to the forked `java` process.
 - When debugging is on, the Gradle runner is embedded inside the test JVM (i.e. no forking happens), and this necessitates that you already have a JVM with the correct flags applied; otherwise, the `IllegalAccessError` presented above will happen.

**Comment by ljacomet** [comment]
Fixed with #29684
