### ISSUE TITLE
Document that CompileOptions.compilerArgs doesn't accept non-string argument when migration to a lazy type

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#29716]
[CompileOptions.compilerArgs](https://github.com/gradle/gradle/blob/14f9e307641c2f3ce738338a54e71ac2f1c9bf41/platforms/jvm/language-jvm/src/main/java/org/gradle/api/tasks/compile/CompileOptions.java#L341-L343) currently accept any type, even [integer](https://github.com/gradle/gradle/blob/14f9e307641c2f3ce738338a54e71ac2f1c9bf41/platforms/jvm/plugins-java/src/integTest/groovy/org/gradle/java/compile/AbstractJavaCompilerIntegrationSpec.groovy#L263) or a file.

When moving `CompileOptions.compilerArgs` to `ListProperty<String>` the type gets checked during property evaluation and you get an exception if element of a `ListProperty` is not a String or GString like:
```
Caused by: java.lang.IllegalArgumentException: Cannot get the value of a property of type java.util.List with element type java.lang.String as the source value contains an element of type java.lang.Integer.
	at org.gradle.api.internal.provider.ValidatingValueCollector.add(ValidatingValueCollector.java:44)
	at org.gradle.api.internal.provider.ValidatingValueCollector.addAll(ValidatingValueCollector.java:54)
	at org.gradle.api.internal.provider.Collectors$ElementsFromCollection.collectEntries(Collectors.java:204)
	at org.gradle.api.internal.provider.AbstractCollectionProperty$PlusCollector.collectEntries(AbstractCollectionProperty.java:674)
	at org.gradle.api.internal.provider.AbstractCollectionProperty$CollectingSupplier.calculateValue(AbstractCollectionProperty.java:500)
	at org.gradle.api.internal.provider.AbstractCollectionProperty.calculateValueFrom(AbstractCollectionProperty.java:306)
	at org.gradle.api.internal.provider.AbstractCollectionProperty.calculateValueFrom(AbstractCollectionProperty.java:79)
	at org.gradle.api.internal.provider.AbstractProperty.doCalculateValue(AbstractProperty.java:170)
	... 160 more
```

We should document that in the migration guide once we do migration.

**Comment by asodja** [comment]
This was actually fixed with https://github.com/gradle/gradle/pull/37658, so no documentation is needed
