### ISSUE TITLE
Gradle 8.8: enabled build cache + use of `--build-file` on the command line is broken

### ISSUE THREAD

**Issue by mcumings** [gradle/gradle#29747]
### Current Behavior

Enabling build cache and attempting to use an alternate `--build-file` causes the build to break with an `IllegalStateException` indicating that the `Build cache controller already set`.

### Expected Behavior

Build cache plus the use of alternate build files should work fine.

### Steps to Reproduce

Repro steps:
- Initialize a new project with gradle wrapper
- Create an empty `settings.gradle.kts` file
- Create an empty `alternate.gradle.kts` file
- Run `./gradlew --build-cache  --stacktrace --build-file alternate.gradle.kts`

The build will fail with:
```
* Exception is:
java.lang.IllegalStateException: Build cache controller already set
        at org.gradle.caching.internal.controller.impl.LifecycleAwareBuildCacheControllerFactory$DelegatingBuildCacheController.createDelegate(LifecycleAwareBuildCacheControllerFactory.java:98)
        at org.gradle.caching.internal.controller.impl.LifecycleAwareBuildCacheControllerFactory$RootBuildCacheController.configurationAvailable(LifecycleAwareBuildCacheControllerFactory.java:137)
        at org.gradle.initialization.RootBuildCacheControllerSettingsProcessor.process(RootBuildCacheControllerSettingsProcessor.java:36)
...
```

### Gradle version

8.8

### Build scan URL (optional)

https://scans.gradle.com/s/2xddo2selsafc

### Your Environment (optional)

------------------------------------------------------------
Gradle 8.8
------------------------------------------------------------

Build time:   2024-05-31 21:46:56 UTC
Revision:     4bd1b3d3fc3f31db5a26eecb416a165b8cc36082

Kotlin:       1.9.22
Groovy:       3.0.21
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.6 (Azul Systems, Inc. 17.0.6+10-LTS)
OS:           Mac OS X 14.5 aarch64

**Comment by stiost** [comment]
I'm also getting this, it broke IntelliJ.

**Comment by alllex** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

***

This might be related to 
* https://github.com/gradle/gradle/pull/28879

**Comment by asodja** [comment]
Thanks for the report, but note that `--build-file` is deprecated from Gradle 7.1, see https://github.com/gradle/gradle/issues/16402 and it will be an error in Gradle 9, see https://github.com/gradle/gradle/issues/22910. So we will investigate how expensive it is to fix and then decide.

Also see documentation where it's marked as deprecated https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:environment_options.

**Comment by rcgonzalezf** [comment]
For other devs impacted a potential workaround is to not use the `build cache`, e.g:
```
./gradlew --no-build-cache  --stacktrace --build-file alternate.gradle.kts
```
Otherwise, it fails consistently; seems like a regression even if it's deprecated.

**Comment by yury-vashchyla** [comment]
Is there a solution to this problem? Other than disabling the cache

**Comment by asodja** [comment]
Closing this issue, since `--build-file` was removed with Gradle 9.0.0
