### ISSUE TITLE
Support Java Toolchains as optional task inputs

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#29758]
### Expected Behavior

Java Toolchains can be used as optional task inputs.

### Current Behavior (optional)

Java Toolchains cannot be used as optional task inputs.

### Context

> How has this issue affected you?

This issue has affected me because I can't define a Java Toolchain as an optional task input.

> What are you trying to accomplish?

I am trying to use a Java Toolchain as an optional task input

> What other alternatives have you considered?

There are no reasonable alternatives.

### Reproducer

```kts
// build.gradle.kts

val foo by tasks.registering {
    val javaToolchains = serviceOf<JavaToolchainService>()

    val java99 = javaToolchains.compilerFor {
        languageVersion.convention(JavaLanguageVersion.of(99))
    }

    inputs.property("java99", java99).optional(true)

    doLast {
        println("java99 ${java99.orNull}")
    }
}
```

#### Error

```
$ ./gradlew foo

> Task :foo FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
11 actionable tasks: 2 executed, 9 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':foo'.
> Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=99, vendor=any, implementation=vendor-specific} for MAC_OS on aarch64.
   > No locally installed toolchains match and toolchain download repositories have not been configured.

* Try:
> Learn more about toolchain auto-detection at https://docs.gradle.org/8.8/userguide/toolchains.html#sec:auto_detection.
> Learn more about toolchain repositories at https://docs.gradle.org/8.8/userguide/toolchains.html#sub:download_repositories.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':foo'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: org.gradle.jvm.toolchain.internal.NoToolchainAvailableException: Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=99, vendor=any, implementation=vendor-specific} for MAC_OS on aarch64.
	at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.downloadToolchain(JavaToolchainQueryService.java:180)
	at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.lambda$query$2(JavaToolchainQueryService.java:146)
	at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.query(JavaToolchainQueryService.java:146)
	at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.lambda$resolveToolchain$1(JavaToolchainQueryService.java:124)
	at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.resolveToolchain(JavaToolchainQueryService.java:122)
	at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.lambda$findMatchingToolchain$0(JavaToolchainQueryService.java:103)
	at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:72)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:115)
	at org.gradle.api.internal.provider.WithSideEffectProvider.calculateOwnValue(WithSideEffectProvider.java:54)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:115)
	at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:81)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculatePresence(AbstractMinimalProvider.java:95)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.isPresent(AbstractMinimalProvider.java:90)
	at org.gradle.api.internal.tasks.properties.AbstractValidatingProperty.isPresent(AbstractValidatingProperty.java:85)
	at org.gradle.api.internal.tasks.properties.AbstractValidatingProperty.validate(AbstractValidatingProperty.java:71)
	at org.gradle.api.internal.tasks.properties.DefaultTaskProperties.validate(DefaultTaskProperties.java:151)
	at org.gradle.api.internal.tasks.execution.TaskExecution.validate(TaskExecution.java:466)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:75)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:55)
	at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:64)
	at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:43)
	at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.executeWithNonEmptySources(AbstractSkipEmptyWorkStep.java:125)
	at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:56)
	at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23)
	at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:75)
	at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:41)
	at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.lambda$execute$0(AssignMutableWorkspaceStep.java:35)
	at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:289)
	at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:31)
	at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:22)
	at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:40)
	at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:23)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.lambda$execute$2(ExecuteWorkBuildOperationFiringStep.java:67)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:67)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:39)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:46)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:34)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:48)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:35)
	at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:61)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:127)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:116)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: org.gradle.jvm.toolchain.internal.ToolchainDownloadFailedException: No locally installed toolchains match and toolchain download repositories have not been configured.
	at org.gradle.jvm.toolchain.internal.install.DefaultJavaToolchainProvisioningService.tryInstall(DefaultJavaToolchainProvisioningService.java:118)
	at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.downloadToolchain(JavaToolchainQueryService.java:178)
	... 71 more

BUILD FAILED in 186ms
```

Gradle version 8.8

**Comment by alllex** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

The [optional input javadoc](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/Optional.html) states that whenever the input is provided, it must be valid:
> Marks a task property as optional. This means that a value does not have to be specified for the property, but any value specified must meet the validation constraints for the property.

**Comment by aSemy** [comment]
Thank you for your response. I appreciate the reference to the optional input javadoc which states:

> Marks a task property as optional. This means that a value does not have to be specified for the property, but any value specified must meet the validation constraints for the property.

I understand this definition and the importance of ensuring that any provided value must be valid. However, I'd like to clarify why this does not negate the need for the requested feature and why this should be considered a feature request rather than a usage question.

### Detailed Explanation

**Current Limitation:**
Java Toolchains in Gradle cannot be marked as optional task inputs. This restriction limits the flexibility of task configurations, especially in scenarios where the presence of a specific Java Toolchain might not be guaranteed or required for all builds.

**Why This Is a Feature Request:**
The ability to mark task inputs as optional is a significant feature in Gradle that allows tasks to adapt based on the availability of certain inputs. While this works well for many types of inputs (e.g., files, properties), it does not currently extend to Java Toolchains. This inconsistency poses a challenge when trying to conditionally use different toolchains, leading to more complex build scripts and workarounds that reduce maintainability.

### Use Case Example

Consider a project that supports multiple Java versions, including future versions for which the toolchain might not always be present. The project may want to define tasks that only use the Java 99 toolchain if it is available, without failing the build if it isn't.

#### Example Scenario:

```kts
// build.gradle.kts

val foo by tasks.registering {
    val javaToolchains = serviceOf<JavaToolchainService>()

    val java99 = javaToolchains.compilerFor {
        languageVersion.convention(JavaLanguageVersion.of(99))
    }

    inputs.property("java99", java99).optional(true)

    doLast {
        println("java99 ${java99.orNull}")
    }
}
```

In the above script:
1. We attempt to use a Java 99 toolchain.
2. We mark it as an optional input, expecting the task to handle the absence of this toolchain gracefully.
3. Without this feature, we are forced to add extra logic to manually check for the toolchain's availability and conditionally register the task or configure it, leading to more verbose and error-prone build scripts.

### Broader Context

This feature would benefit any project that:
- Supports multiple JDK versions, including experimental or future versions.
- Wants to provide more robust and flexible build scripts that adapt to the environment.
- Needs to simplify task configurations by leveraging the existing optional input mechanism.

### Response to Optional Input Javadoc

The current javadoc explanation for optional inputs states that any value specified must be valid. This terminology implies that if a value is provided, it should conform to the expected constraints, which is perfectly reasonable. However, this does not address the specific need for Java Toolchains to be treated as optional inputs, particularly because:
- The concept of "validity" for a toolchain should include the scenario where a specific toolchain might not be available or needed for certain builds.
- The current inability to mark Java Toolchains as optional inputs forces developers to write additional conditional logic, complicating the build scripts unnecessarily.

### Conclusion

By supporting Java Toolchains as optional task inputs, Gradle would enhance its flexibility and maintainability for complex builds. This feature aligns with the goals of providing a powerful and adaptable build tool, reducing the need for boilerplate code and custom conditional logic in build scripts.

I hope this clarifies the need for this feature request and distinguishes it from a general usage question. Thank you for considering this enhancement.

**Comment by alllex** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

Thank you for sharing a specific use case.

> Current Limitation:
Java Toolchains in Gradle cannot be marked as optional task inputs. This restriction limits the flexibility of task configurations, especially in scenarios where the presence of a specific Java Toolchain might not be guaranteed or required for all builds.

The limitation that you point out is present on the level of the Toolchains API, and is not tied to the optionality of the task inputs.

What you seem to be asking for is additional methods in the Toolchains-related API to request a toolchain without failing if it was not found, and allowing the caller to explicitly handle the absent case.

If that API was added, it can then be combined with the existing contract for optional task inputs by plugging the provider of the "optional" toolchain into the optional task input.

**Comment by aSemy** [comment]
I've looked into this and I think there are three options for supporting optional tools.


### Add `Property<>` to `JavaToolchainSpec` to control failure handling

Add `JavaToolchainSpec#getMissingToolchainMode`.

I think this option is the most succinct, idiomatic, and flexible. It requires the fewest changes to the public API. Adding a single option in `JavaToolchainSpec` simultaneously adds support for all the current tools (launchers, compilers, and javadoc), as well as any future tools.

Using an enum instead of a boolean can be discussed. I've used an enum here in case other modes are required in the future (for example, only ignoring specific failures like `ToolchainProvisioningException`).

```java
public interface JavaToolchainSpec extends Describable {
    // [...]
    /** Controls how to handle the outcome when the requested toolchain cannot be found. */
    @Incubating
    Property<JavaToolchainNotFoundMode> getOnNoMatchFound();
}

public enum JavaToolchainNotFoundMode {
    /**
     * If no toolchain matching a given {@link JavaToolchainSpec} is found, failures will be ignored.
     */
    IGNORE,

    /**
     * If no toolchain matching a given {@link JavaToolchainSpec} can be found, a failure will be thrown.
     */
    THROW_EXCEPTION,
}
```

### Optional toolchain functions

Add new functions to `JavaToolchainService`.

```java
public interface JavaToolchainService {

    /**
     * Obtain a {@link JavaCompiler} matching the {@link JavaToolchainSpec}
     * if a matching toolchain, configured by the provided action, is available.
     *
     * If no matching toolchain is available the returned {@link Provider} will throw an exception when it is evaluated.
     *
     * @param config The configuration of the {@code JavaToolchainSpec}
     * @return A {@code Provider<JavaCompiler>}
     * @since 9.4.0
     */
    @Incubating
    Provider<JavaCompiler> optionalCompilerFor(Action<? super JavaToolchainSpec> config);
}
```

Internally, if the requested JavaToolchain cannot be accessed then the returned Provider would be null.

Downsides:
- It's not possible to configure the optionality at runtime, as it would be for a `Property<>`.
- This would double the number of functions in `JavaToolchainService`. It makes the API harder to navigate, and testing is harder. If more options are added in the future, the number of functions could double again.

#### Add new 'optional' parameter to functions in `JavaToolchainService`

```java
public interface JavaToolchainService {

    @Incubating
    Provider<JavaCompiler> compilerFor(Action<? super JavaToolchainSpec> config, boolean optional);
}
```

Suffers from similar problems as with adding 'Optional toolchain functions'.

### Expose failures as public API

I also think there's something else that would help support optional toolchains.

Currently, when a function like `JavaToolchainService#compilerFor` fails, it returns an internal exception: `org.gradle.jvm.toolchain.internal.install.exceptions.ToolchainProvisioningException`.

If these exceptions were part of the public API, and documented in the `JavaToolchainService` functions, then handling missing toolchains could be implemented by users, even if it was inelegant.

**Comment by big-guy** [comment]
This is a valid request, but we think we should solve this without a special flag on the toolchain spec.

Ideally, `getOrElse` should work like any other Provider and the JavaToolchainService would return a Provider without a value.  Calling `.get()` should give you the context of the failure, but this isn't the way we validate task properties today. This is relying on isPresent throwing, which isn't the way this should work.

A proper solution requires some changes on both the toolchain service and the Provider sides.
