### ISSUE TITLE
Extensions added to task don't carry task dependency for output properties on extension

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#29826]
If you create an extension on a task as we do for Jacoco, see https://github.com/gradle/gradle/blob/7f9d7655d8e6b95abe88a34b584cb06915b37b70/platforms/jvm/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPluginExtension.java#L116-L117 then properties on that extension annotated as outputs (e.g. `@OutputFile`) don't carry task dependencies. 

Result of that is you cannot have such properties lazy (either `RegularFileProperty` or `DirectoryProperty`), since that would causes a failure like:
```
Caused by: java.lang.IllegalStateException: Extension 'jacoco' property 'destinationFile' is declared as an output property of extension 'jacoco' (type JacocoTaskExtension) but does not have a task associated with it.
	at org.gradle.api.internal.provider.AbstractProperty.getProducerTask(AbstractProperty.java:386)
	at org.gradle.api.internal.provider.AbstractProperty.getProducer(AbstractProperty.java:213)
	at org.gradle.api.internal.file.collections.ProviderBackedFileCollection.visitDependencies(ProviderBackedFileCollection.java:51)
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:108)
	at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmptyEdges.getNodeValues(CachingDirectedGraphWalker.java:213)
	at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:121)
	at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:73)
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:67)
	... 182 more
```

Let's investigate that and find a solution.

**Comment by asodja** [comment]
This is probably an issue with `@Nested` beans, see [Task dependency inference should work for output file properties attached to nested beans · Issue #6619 · gradle/gradle · GitHub](https://github.com/gradle/gradle/issues/6619)

**Comment by asodja** [comment]
This is really an issue with https://github.com/gradle/gradle/issues/6619, so I am closing this as a duplicate.
