### ISSUE TITLE
ServiceRegistry for SourceSet instance does not contain expected services

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#29846]
This is similar to #18213 and https://github.com/gradle/gradle/issues/16936.

For example when you have:
```
def "source extension can have abstract lazy typed property methods"() {
    given:
    buildFile """
        plugins {
            id 'java'
        }

        abstract class MyExtensible {
            MyExtensible() {
                // Invoke getThing() method to ensure Property is instantiated
                getThing().convention("foo")
            }
            abstract Property<String> getThing()
        }

        sourceSets {
            main {
                extensions.create("myExtensible", MyExtensible)
            }
        }
    """

    expect:
    succeeds "help"
}
```

Then the build will fail with:
```
Caused by: org.gradle.internal.service.UnknownServiceException: No service of type ObjectFactory available in default services.
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:343)
	at org.gradle.internal.instantiation.generator.ManagedObjectFactory.getObjectFactory(ManagedObjectFactory.java:140)
	at org.gradle.internal.instantiation.generator.ManagedObjectFactory.newInstance(ManagedObjectFactory.java:92)
	at MyExtensible.<init>(/Users/asodja/workspace/gradle/subprojects/core/build/tmp/teŝt files/ObjectFacto.Test/4ef6g/build.gradle:9)
	at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:2107)
	at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:543)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:65)
	... 180 more
```

**Comment by mlopatkin** [comment]
This feature request is in the backlog of the relevant team and is prioritized by them.
***
We should address it for the rest of ExtensionsAware stuff, likely alongside the #18213.
