### ISSUE TITLE
When finalizing a property whose value is an adhoc provider orElse-ed and mapped resolve twice

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#29852]
### Current Behavior

The ad-hoc provider will resolve twice (once for `beforeEach` and another time during `calculateOwnValue`).

### Expected Behavior

When finalizing a property, all providers constituting its value should always evaluate once regardless of how they were realized (`beforeEach` vs `calculateOwnValue`). A provider should maintain atomicity as a provider may be changing which breaks the `finalizeValue` contract.

### Context (optional)

See [Nokee for expert Gradle consulting](https://nokee.dev/services/consulting.html).

### Steps to Reproduce

Look at the two stack trace generated by the following build script code:

```
def provider = project.provider {
	new Throwable('realize').printStackTrace()
	return 'foo'
}
def prop = objects.property(Object)
prop.value(provider.orElse([]).map { it })

prop.finalizeValue()
```

The top of both stacktrace are as followed:

First realize:
```
java.lang.Throwable: realize
        at java.base/jdk.internal.reflect.GeneratedConstructorAccessor212.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
        at build_1sv88fhrxtcne6n86m0wa9yuy$_run_closure1.doCall$original(/Users/daniel/gradle/tmp/multiple-evaluation/build.gradle:9)
        at build_1sv88fhrxtcne6n86m0wa9yuy$_run_closure1.doCall(/Users/daniel/gradle/tmp/multiple-evaluation/build.gradle)
        at build_1sv88fhrxtcne6n86m0wa9yuy$_run_closure1.doCall$original(/Users/daniel/gradle/tmp/multiple-evaluation/build.gradle)
        at build_1sv88fhrxtcne6n86m0wa9yuy$_run_closure1.doCall(/Users/daniel/gradle/tmp/multiple-evaluation/build.gradle)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
        at groovy.lang.Closure.call(Closure.java:427)
        at groovy.lang.Closure.call(Closure.java:406)
        at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:72)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:115)
        at org.gradle.api.internal.provider.OrElseFixedValueProvider.calculateOwnValue(OrElseFixedValueProvider.java:70)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:115)
        at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:81)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:115)
        at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:81)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:115)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.withFinalValue(AbstractMinimalProvider.java:168)
        at org.gradle.api.internal.provider.DefaultProperty.finalValue(DefaultProperty.java:162)
        at org.gradle.api.internal.provider.DefaultProperty.finalValue(DefaultProperty.java:33)
        at org.gradle.api.internal.provider.AbstractProperty.finalizeNow(AbstractProperty.java:281)
        at org.gradle.api.internal.provider.AbstractProperty.finalizeValue(AbstractProperty.java:227)
        at org.gradle.api.provider.Property$finalizeValue$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
        at build_1sv88fhrxtcne6n86m0wa9yuy.run(/Users/daniel/gradle/tmp/multiple-evaluation/build.gradle:27)
```

Second realize:
```
java.lang.Throwable: realize
        at java.base/jdk.internal.reflect.GeneratedConstructorAccessor212.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
        at org.gradle.internal.classpath.intercept.DefaultCallSiteDecorator$DecoratingCallSite.access$401(DefaultCallSiteDecorator.java:145)
        at org.gradle.internal.classpath.intercept.DefaultCallSiteDecorator$DecoratingCallSite$4.callOriginal(DefaultCallSiteDecorator.java:199)
        at org.gradle.internal.classpath.intercept.DefaultCallSiteDecorator$1.intercept(DefaultCallSiteDecorator.java:63)
        at org.gradle.internal.classpath.intercept.DefaultCallSiteDecorator$DecoratingCallSite.callConstructor(DefaultCallSiteDecorator.java:196)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
        at build_1sv88fhrxtcne6n86m0wa9yuy$_run_closure1.doCall$original(/Users/daniel/gradle/tmp/multiple-evaluation/build.gradle:9)
        at build_1sv88fhrxtcne6n86m0wa9yuy$_run_closure1.doCall(/Users/daniel/gradle/tmp/multiple-evaluation/build.gradle)
        at build_1sv88fhrxtcne6n86m0wa9yuy$_run_closure1.doCall$original(/Users/daniel/gradle/tmp/multiple-evaluation/build.gradle)
        at build_1sv88fhrxtcne6n86m0wa9yuy$_run_closure1.doCall(/Users/daniel/gradle/tmp/multiple-evaluation/build.gradle)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
        at groovy.lang.Closure.call(Closure.java:427)
        at groovy.lang.Closure.call(Closure.java:406)
        at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:72)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateExecutionTimeValue(AbstractMinimalProvider.java:152)
        at org.gradle.api.internal.provider.OrElseValueProducer.mayHaveValue(OrElseValueProducer.java:71)
        at org.gradle.api.internal.provider.OrElseValueProducer.visitProducerTasks(OrElseValueProducer.java:58)
        at org.gradle.api.internal.provider.ValueSupplier$ValueProducer.visitContentProducerTasks(ValueSupplier.java:72)
        at org.gradle.api.internal.provider.TransformBackedProvider.beforeRead(TransformBackedProvider.java:95)
        at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:80)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:115)
        at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:81)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:115)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.withFinalValue(AbstractMinimalProvider.java:168)
        at org.gradle.api.internal.provider.DefaultProperty.finalValue(DefaultProperty.java:162)
        at org.gradle.api.internal.provider.DefaultProperty.finalValue(DefaultProperty.java:33)
        at org.gradle.api.internal.provider.AbstractProperty.finalizeNow(AbstractProperty.java:281)
        at org.gradle.api.internal.provider.AbstractProperty.finalizeValue(AbstractProperty.java:227)
        at org.gradle.api.provider.Property$finalizeValue$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
        at build_1sv88fhrxtcne6n86m0wa9yuy.run(/Users/daniel/gradle/tmp/multiple-evaluation/build.gradle:27)
```

### Gradle version

at least Gradle 7.5, 6.2.1, 8.8 and 8.9 RC 2

**Comment by alllex** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.
