### ISSUE TITLE
Problem accessing the web via a proxy Gradle 4.2

### ISSUE THREAD

**Issue by thiaguten** [gradle/gradle#2987]
After upgrading to gradle 4.2 I am not able to access the web via proxy to download dependencies. 
My proxy settings are described in the gradle.properties in my gradle user home.
When I go back to Gradle 4.1 everything works fine again.

Error:

```
Downloading https://services.gradle.org/distributions/gradle-4.2-bin.zip

Exception in thread "main" java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
	at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2124)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
	at org.gradle.wrapper.Download.download(Download.java:51)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

```

**Comment by oehme** [comment]
The message above is not about downloading dependencies. It's about downloading Gradle itself. 

Can please you check if you get the same problem with 4.1 if you tell Gradle to use a fresh user home? `gradlew --gradle-user-home test-home help`.

**Comment by thiaguten** [comment]
@oehme 

After resetting my Gradle home and executing the command you requested everything worked correctly in versions 4.1 and 4.2 of Gradle. It was probably some instability in the company network. I believe you can close this issue. Thank you for your help.

```
thiago@thiago-linux:~$ rm -rf ~/.gradle/
thiago@thiago-linux:~$ mkdir ~/.gradle/
thiago@thiago-linux:~$ cd ~/Development/Projects/horus/
thiago@thiago-linux:~/Development/Projects/horus$ ./gradlew --gradle-user-home ~/.gradle help
Downloading https://services.gradle.org/distributions/gradle-4.2-bin.zip
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /home/thiago/.gradle/wrapper/dists/gradle-4.2-bin/cl9xe1l8k8ophj72k8rv6xbu7/gradle-4.2-bin.zip to /home/thiago/.gradle/wrapper/dists/gradle-4.2-bin/cl9xe1l8k8ophj72k8rv6xbu7
Set executable permissions for: /home/thiago/.gradle/wrapper/dists/gradle-4.2-bin/cl9xe1l8k8ophj72k8rv6xbu7/gradle-4.2/bin/gradle
Starting a Gradle Daemon (subsequent builds will be faster)
Parallel execution is an incubating feature.
Download https://plugins.gradle.org/m2/org/ajoberstar/grgit/2.0.0/grgit-2.0.0.pom
Download https://plugins.gradle.org/m2/org/eclipse/jgit/org.eclipse.jgit.ui/4.8.0.201706111038-r/org.eclipse.jgit.ui-4.8.0.201706111038-r.pom
Download https://plugins.gradle.org/m2/org/eclipse/jgit/org.eclipse.jgit/4.8.0.201706111038-r/org.eclipse.jgit-4.8.0.201706111038-r.pom
Download https://plugins.gradle.org/m2/org/eclipse/jgit/org.eclipse.jgit-parent/4.8.0.201706111038-r/org.eclipse.jgit-parent-4.8.0.201706111038-r.pom
Download https://plugins.gradle.org/m2/com/googlecode/javaewah/JavaEWAH/1.1.6/JavaEWAH-1.1.6.pom
Download https://plugins.gradle.org/m2/org/sonatype/oss/oss-parent/5/oss-parent-5.pom
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpclient/4.3.6/httpclient-4.3.6.pom
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpcomponents-client/4.3.6/httpcomponents-client-4.3.6.pom
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpcore/4.3.3/httpcore-4.3.3.pom
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpcomponents-core/4.3.3/httpcomponents-core-4.3.3.pom
Download https://plugins.gradle.org/m2/org/ajoberstar/grgit/2.0.0/grgit-2.0.0.jar
Download https://plugins.gradle.org/m2/org/eclipse/jgit/org.eclipse.jgit.ui/4.8.0.201706111038-r/org.eclipse.jgit.ui-4.8.0.201706111038-r.jar
Download https://plugins.gradle.org/m2/com/googlecode/javaewah/JavaEWAH/1.1.6/JavaEWAH-1.1.6.jar
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpclient/4.3.6/httpclient-4.3.6.jar
Download https://plugins.gradle.org/m2/org/eclipse/jgit/org.eclipse.jgit/4.8.0.201706111038-r/org.eclipse.jgit-4.8.0.201706111038-r.jar
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpcore/4.3.3/httpcore-4.3.3.jar

> Task :help

Welcome to Gradle 4.2.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see a list of command-line options, run gradlew --help

To see more detail about a task, run gradlew help --task <task>


BUILD SUCCESSFUL in 50s
1 actionable task: 1 executed
thiago@thiago-linux:~/Development/Projects/horus$
```

**Comment by oehme** [comment]
Thank you for verifying!
