### ISSUE TITLE
Gradle 4.2 fails with Zulu JDK 9

### ISSUE THREAD

**Issue by Shorttail** [gradle/gradle#2992]
### Expected Behavior
Gradle runs under the Zulu JDK ~~and under Oracle JDK~~.

### Current Behavior
Gradle crashes with the following error:

```
java.lang.IllegalArgumentException: Could not determine java version from '9.0.0.15'.
        at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:72)
        at org.gradle.api.JavaVersion.current(JavaVersion.java:82)
        at org.gradle.internal.jvm.UnsupportedJavaRuntimeException.assertUsingVersion(UnsupportedJavaRuntimeException.java:42)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:32)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:246)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:182)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

### Context
I just installed Zulu ~~and Oracle JDK~~ and tried to run Gradle.

### Steps to Reproduce (for bugs)
Install Zulu from https://www.azul.com/downloads/zulu/ ~~or Oracle JDK from http://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html~~
Run any Gradle command.

### Your Environment
Windows 10, Zulu 9.0.0, Gradle 4.2:

```
openjdk version "9.0.0.15"
OpenJDK Runtime Environment (Zulu build 9.0.0.15+181)
OpenJDK 64-Bit Server VM (Zulu build 9.0.0.15+181, mixed mode)
```

**Comment by blindpirate** [comment]
Thanks for reporting. Looks like the version number format has been changed and Gradle can't foresee it.

**Comment by blindpirate** [comment]
@Shorttail Could you please double-check it? In my investigation, this issue does occur with zulu 9, but not with Oracle JDK 9.

```
# zhb @ bs-MacBook-Pro in ~/Projects/tmp/jdk9 [8:50:18]
$ /Library/Java/JavaVirtualMachines/zulu8.23.0.3-jdk8.0.144-macosx_x64/bin/java Version
1.8.0_144

# zhb @ bs-MacBook-Pro in ~/Projects/tmp/jdk9 [8:50:42]
$ /Library/Java/JavaVirtualMachines/zulu9.0.0.15-jdk9.0.0-macosx_x64/bin/java Version
9.0.0.15

# zhb @ bs-MacBook-Pro in ~/Projects/tmp/jdk9 [8:50:54]
$ /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java Version
1.8.0_121

# zhb @ bs-MacBook-Pro in ~/Projects/tmp/jdk9 [8:51:23]
$ /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/bin/java Version
9
```
Only zulu9 has changed version format to `9.0.0.15`, Oracle JDK's version format `9` is still supported by Gradle.

And I've run Gradle with Oracle JDK9, looks like it's OK.

**Comment by Shorttail** [comment]
You are correct, I am mistaken. Gradle 4.2 does start on Oracle JDK 9.

**Comment by blindpirate** [comment]
Thanks, we'll support zulu 9 soon.

**Comment by oehme** [comment]
We need to cherry-pick this to `release`

**Comment by jjohannes** [comment]
Picked to release for `4.2.1`: https://github.com/gradle/gradle/commit/d9c35cf9d74c102641fcfe0bb7bf622791a96caf

**Comment by blindpirate** [comment]
Thanks @jjohannes !
