### ISSUE TITLE
[8.9] Gradle build daemon crashes immediately (in low-memory environment?)

### ISSUE THREAD

**Issue by mateuszkwiecinski** [gradle/gradle#29958]
### Current Behavior

An automated PR that upgrades gradle to latest stable version fails the build with

<details>
<summary>Full message</summary>

```
Downloading https://services.gradle.org/distributions/gradle-8.9-bin.zip
............10%.............20%.............30%.............40%.............50%.............60%.............70%.............80%.............90%.............100%

Welcome to Gradle 8.9!

Here are the highlights of this release:
 - Enhanced Error and Warning Messages
 - IDE Integration Improvements
 - Daemon JVM Information

For more details see https://docs.gradle.org/8.9/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
Will push to remote build cache
> Task :plugins:lintKotlinMain
> Task :plugins:lintKotlinTest NO-SOURCE
> Task :plugins:validateEditorConfigForKtlint FROM-CACHE
> Task :plugins:lintKotlin
> Task :plugins:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :plugins:pluginDescriptors
> Task :plugins:processResources
> Task :plugins:processTestResources NO-SOURCE
> Task :plugins:compileKotlin

The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=7c0c0075-8025-4128-b766-512b5ee3e257, currentDir=/home/runner/_work/<REDACTED>}
Attempting to read last messages from the daemon log...
Daemon pid: 365
  log file: /home/runner/.gradle/daemon/8.9/daemon-365.out.log
----- Last  20 lines from daemon log file - daemon-365.out.log -----
2024-07-18T07:52:15.988+0000 [DEBUG] [org.gradle.launcher.daemon.server.DefaultDaemonConnection] thread 30: Received non-IO message from client: Build{id=7c0c0075-8025-4128-b766-512b5ee3e257, currentDir=/home/runner/_work/<REDACTED>}
2024-07-18T07:52:15.988+0000 [INFO] [org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler] Received command: Build{id=7c0c0075-8025-4128-b766-512b5ee3e257, currentDir=/home/runner/_work/<REDACTED>}.
2024-07-18T07:52:15.989+0000 [DEBUG] [org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler] Starting executing command: Build{id=7c0c0075-8025-4128-b766-512b5ee3e257, currentDir=/home/runner/_work/<REDACTED>} with connection: socket connection from /127.0.0.1:39117 to /127.0.0.1:50946.
2024-07-18T07:52:15.992+0000 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] Command execution: started DaemonCommandExecution[command = Build{id=7c0c0075-8025-4128-b766-512b5ee3e257, currentDir=/home/runner/_work/<REDACTED>}, connection = DefaultDaemonConnection: socket connection from /127.0.0.1:39117 to /127.0.0.1:50946] after 0.0034166666666666664 minutes of idle
2024-07-18T07:52:15.992+0000 [INFO] [org.gradle.launcher.daemon.server.DaemonRegistryUpdater] Marking the daemon as busy, address: [42650d56-1b7e-4677-ae19-3f5ffc61d89f port:39117, addresses:[localhost/127.0.0.1]]
2024-07-18T07:52:15.992+0000 [DEBUG] [org.gradle.launcher.daemon.registry.PersistentDaemonRegistry] Marking busy by address: [42650d56-1b7e-4677-ae19-3f5ffc61d89f port:39117, addresses:[localhost/127.0.0.1]]
2024-07-18T07:52:15.993+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on daemon addresses registry.
2024-07-18T07:52:15.993+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2024-07-18T07:52:15.995+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2024-07-18T07:52:15.995+0000 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] resetting idle timer
2024-07-18T07:52:15.995+0000 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] daemon is running. Sleeping until state changes.
2024-07-18T07:52:15.996+0000 [INFO] [org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy] Daemon is about to start building Build{id=7c0c0075-8025-4128-b766-512b5ee3e257, currentDir=/home/runner/_work/<REDACTED>}. Dispatching build started information...
2024-07-18T07:52:15.997+0000 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 32: dispatching org.gradle.launcher.daemon.protocol.BuildStarted@336744c2
2024-07-18T07:52:15.999+0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment] Configuring env variables: [PATH, <REDACTED>]
2024-07-18T07:52:16.006+0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.LogToClient] About to start relaying all logs to the client via the connection.
2024-07-18T07:52:16.006+0000 [INFO] [org.gradle.launcher.daemon.server.exec.LogToClient] The client will now receive all logging from the daemon (pid: 365). The daemon log file: /home/runner/.gradle/daemon/8.9/daemon-365.out.log
2024-07-18T07:52:16.009+0000 [INFO] [org.gradle.launcher.daemon.server.exec.LogAndCheckHealth] Starting build in new daemon [memory: 494.9 MiB]
2024-07-18T07:52:16.012+0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has started executing the build.
2024-07-18T07:52:16.012+0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] Executing build with daemon context: DefaultDaemonContext[uid=5e5f4e20-65ec-47b9-8ed6-f8ba456ec6b2,javaHome=/home/runner/_work/_tool/Java_Temurin-Hotspot_jdk/21.0.4-7.0.LTS/x64,javaVersion=21,daemonRegistryDir=/home/runner/.gradle/daemon,pid=365,idleTimeout=10800000,priority=NORMAL,applyInstrumentationAgent=true,nativeServicesMode=ENABLED,daemonOpts=--add-opens=java.base/java.util=ALL-UNNAMED,--add-opens=java.base/java.lang=ALL-UNNAMED,--add-opens=java.base/java.lang.invoke=ALL-UNNAMED,--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED,--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED,--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED,--add-opens=java.base/java.nio.charset=ALL-UNNAMED,--add-opens=java.base/java.net=ALL-UNNAMED,--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED,-XX:MaxMetaspaceSize=384m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country,-Duser.language=en,-Duser.variant]
Will push to remote build cache----- End of the daemon log -----


FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```
</details>

Running with info reveals more info

<details>
<summary>--info output</summary>

```
Resolve mutations for :plugins:processTestResources (Thread[#138,Execution worker Thread 8,5,main]) started.
:plugins:processTestResources (Thread[#138,Execution worker Thread 8,5,main]) started.
Skipping task ':plugins:processTestResources' as it has no source files and no previous output files.
i: starting the daemon as: /home/runner/_work/_tool/Java_Temurin-Hotspot_jdk/21.0.4-7.0.LTS/x64/bin/java -cp /home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/2.0.0/1de310de3446414381282ffc46c3ed3919a4d1da/kotlin-compiler-embeddable-2.0.0.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/2.0.0/b48df2c4aede9586cc931ead433bc02d6fd7879e/kotlin-stdlib-2.0.0.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-script-runtime/2.0.0/fdc27dd047d592fa41d2dfa21e7621287a361612/kotlin-script-runtime-2.0.0.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.6.10/1cbe9c92c12a94eea200d23c2bbaedaf3daf5132/kotlin-reflect-1.6.10.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-daemon-embeddable/2.0.0/b39c612768614c4428c96ee9c65477181fffe9d/kotlin-daemon-embeddable-2.0.0.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.intellij.deps/trove4j/1.0.20200330/3afb14d5f9ceb459d724e907a21145e8ff394f02/trove4j-1.0.20200330.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar -Djava.awt.headless=true -Djava.rmi.server.hostname=127.0.0.1 -Xmx512m -XX:MaxMetaspaceSize=384m -XX:ReservedCodeCacheSize=320m -Dkotlin.environment.keepalive -ea -XX:+UseCodeCacheFlushing -XX:+UseParallelGC --add-exports java.base/sun.nio.ch=ALL-UNNAMED org.jetbrains.kotlin.daemon.KotlinCompileDaemon --daemon-runFilesPath /home/runner/.kotlin/daemon --daemon-autoshutdownIdleSeconds=7200 --daemon-compilerClasspath /home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/2.0.0/1de310de3446414381282ffc46c3ed3919a4d1da/kotlin-compiler-embeddable-2.0.0.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/2.0.0/b48df2c4aede9586cc931ead433bc02d6fd7879e/kotlin-stdlib-2.0.0.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-script-runtime/2.0.0/fdc27dd047d592fa41d2dfa21e7621287a361612/kotlin-script-runtime-2.0.0.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.6.10/1cbe9c92c12a94eea200d23c2bbaedaf3daf5132/kotlin-reflect-1.6.10.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-daemon-embeddable/2.0.0/b39c612768614c4428c96ee9c65477181fffe9d/kotlin-daemon-embeddable-2.0.0.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.intellij.deps/trove4j/1.0.20200330/3afb14d5f9ceb459d724e907a21145e8ff394f02/trove4j-1.0.20200330.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar
i: #1 retrying connecting to the daemon 
Options for KOTLIN DAEMON: IncrementalCompilationOptions(super=CompilationOptions(compilerMode=INCREMENTAL_COMPILER, targetPlatform=JVM, reportCategories=[0, 3], reportSeverity=2, requestedCompilationResults=[0], kotlinScriptExtensions=[]), areFileChangesKnown=false, modifiedFiles=null, deletedFiles=null, classpathChanges=NotAvailableForNonIncrementalRun, workingDir=/home/runner/_work/<REDACTED>/plugins/build/kotlin/compileKotlin/cacheable, multiModuleICSettings=MultiModuleICSettings(buildHistoryFile=/home/runner/_work/<REDACTED>/plugins/build/kotlin/compileKotlin/local-state/build-history.bin, useModuleDetection=false), usePreciseJavaTracking=true, icFeatures=IncrementalCompilationFeatures(withAbiSnapshot=false, preciseCompilationResultsBackup=true, keepIncrementalCompilationCachesInMemory=true, enableUnsafeIncrementalCompilationForMultiplatform=false), outputFiles=[/home/runner/_work/<REDACTED>/plugins/build/classes/kotlin/main, /home/runner/_work/<REDACTED>/plugins/build/kotlin/compileKotlin/cacheable, /home/runner/_work/<REDACTED>/plugins/build/kotlin/compileKotlin/local-state])----- End of the daemon log -----


FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

* Try:
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```
</details>

the build failure exception is:
```stacktrace
* Exception is:
org.gradle.launcher.daemon.client.DaemonDisappearedException: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
	at org.gradle.launcher.daemon.client.DaemonClient.handleDaemonDisappearance(DaemonClient.java:282)
	at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:255)
	at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:208)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:172)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:97)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:56)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:167)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:333)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:297)
	at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:74)
	at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:30)
	at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:96)
	at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:40)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:50)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:27)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:445)
	at org.gradle.launcher.Main.doAction(Main.java:35)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:52)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.gradle.wrapper.GradleWrapperMain.main(SourceFile:70)
```

### Expected Behavior

The daemon doesn't crash

### Context (optional)

- I'm not able to reproduce the issue locally
- The issue happens only on self-hosted github runners
- Our infra provides multiple sizes of runners, and from my testing the issue seems to happen only on the following setup:
	- 750MB of memory (I see the config has "187" of "cpu", but I'm not sure what it means)
	- 1.5GB of memory (I see the config has "375m" of "cpu")
- The smallest runner that doesn't reproduce the issue has 3GB of RAM (and has "750m" of "cpu")
- I scanned through [8.9's release notes](https://docs.gradle.org/current/release-notes.html), but I can't see anything related to increased RAM requirements or expected changed to the daemon 👀 
- The project I'm testing on is tiny (just a small set of private gradle plugins), that's why it was assigned to such a small runner (with just 750MB of ram)
- Everything works fine in 8.8 and did in all other 8.x and probably 7.x too
- Running with `--no-daemon` makes the build pass

### Steps to Reproduce

I can't provide repro project :/ It doesn't seem to be a project specific issue, but rather an _environment_ one

### Gradle version

8.9

### Gradle version that used to work

8.8

### Build scan URL (optional)

The build scan is not available :/

**Comment by alllex** [comment]
Thank you for reporting the issue

We will try to investigate the issue with the provided information. However, it would be helpful if you could provide the project causing the issue (or an equivalent project). The memory dumps for the corresponding Gradle versions could be also helpful.

Can you confirm that running with `--no-daemon` actually runs without a daemon as opposed to spawning a single-use daemon?

Related documentation: https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:disabling_the_daemon

**Comment by ljacomet** [comment]
Any chance you can try with [an 8.10 nightly](https://gradle.org/nightly/)?

There have been some attempts at improving memory recently. And maybe the line crossing you seem to experience is already resolved.

**Comment by mateuszkwiecinski** [comment]
when running with `--no-daemon` I see the follwing message the logs:

>To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.9/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build 

so I guess the build uses single-use daemon

> The memory dumps for the corresponding Gradle versions could be also helpful.

Can you point me at should I do that? I know how to pass jvmArgs to tasks to automatically dump the memory on OOM exception, but I'm not sure how to do a memory dump before(?) the daemon crashes 👀 

>Any chance you can try with an 8.10 nightly?

I tested `8.10-20240718001640+0000` and I observe the same behavior

<details>
<summary>--info output</summary>

```
Resolve mutations for :plugins:processResources (Thread[#140,Execution worker Thread 11,5,main]) started.
:plugins:processResources (Thread[#140,Execution worker Thread 11,5,main]) started.
Caching disabled for task ':plugins:processResources' because:
  Not worth caching
Task ':plugins:processResources' is not up-to-date because:
  No history is available.
file or directory '/home/runner/_work/<REDACTED>/plugins/src/main/resources', not found
Resolve mutations for :plugins:processTestResources (Thread[#140,Execution worker Thread 11,5,main]) started.
:plugins:processTestResources (Thread[#140,Execution worker Thread 11,5,main]) started.
Skipping task ':plugins:processTestResources' as it has no source files and no previous output files.
i: starting the daemon as: /home/runner/_work/_tool/Java_Temurin-Hotspot_jdk/21.0.4-7.0.LTS/x64/bin/java -cp /home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/2.0.0/1de310de3446414381282ffc46c3ed3919a4d1da/kotlin-compiler-embeddable-2.0.0.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/2.0.0/b48df2c4aede9586cc931ead433bc02d6fd7879e/kotlin-stdlib-2.0.0.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-script-runtime/2.0.0/fdc27dd047d592fa41d2dfa21e7621287a361612/kotlin-script-runtime-2.0.0.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.6.10/1cbe9c92c12a94eea200d23c2bbaedaf3daf5132/kotlin-reflect-1.6.10.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-daemon-embeddable/2.0.0/b39c612768614c4428c96ee9c65477181fffe9d/kotlin-daemon-embeddable-2.0.0.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.intellij.deps/tr
i: #1 retrying connecting to the daemon 
Options for KOTLIN DAEMON: IncrementalCompilationOptions(super=CompilationOptions(compilerMode=INCREMENTAL_COMPILER, targetPlatform=JVM, reportCategories=[0, 3], reportSeverity=2, requestedCompilationResults=[0], kotlinScriptExtensions=[]), areFileChangesKnown=false, modifiedFiles=null, deletedFiles=null, classpathChanges=NotAvailableForNonIncrementalRun, workingDir=/home/runner/_work/<REDACTED>/plugins/build/kotlin/compileKotlin/cacheable, multiModuleICSettings=MultiModuleICSettings(buildHistoryFile=/home/runner/_work/<REDACTED>/plugins/build/kotlin/compileKotlin/local-state/build-history.bin, useModuleDetection=false), usePreciseJavaTracking=true, icFeatures=IncrementalCompilationFeatures(withAbiSnapshot=false, preciseCompilationResultsBackup=true, keepIncrementalCompilationCachesInMemory=true, enableUnsafeIncrementalCompilationForMultiplatform=false), outputFiles=[/home/runner/_work/<REDACTED>/plugins/b
FAILURE: Build failed with an exception.
* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
* Try:
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
* Exception is:
org.gradle.launcher.daemon.client.DaemonDisappearedException: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
(...)
```

</details>

**Comment by asodja** [comment]
To get a heap dump you could try adding. 
```
org.gradle.jvmargs=-Xmx<YourMemorySettings>m -XX:+HeapDumpOnOutOfMemoryError
```
On crash you might then find `java_pid.hprof` file in working dir.

**Comment by mateuszkwiecinski** [comment]
When trying to come up with a reproducer, I initially assumed it's enough to have an environment with low amount of available RAM, but I couldn't reproduce the issue with only that 👀 
The more code I remove the later the daemon dies (Initially it started during `compileKotlin` now I'm at `validatePlugins` which is the last task to run, I think. 
The current exception is:
```
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :plugins:lintKotlinMain
> Task :plugins:lintKotlinTest NO-SOURCE
> Task :plugins:validateEditorConfigForKtlint
> Task :plugins:lintKotlin
> Task :plugins:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :plugins:pluginDescriptors
> Task :plugins:processResources
> Task :plugins:processTestResources NO-SOURCE
> Task :plugins:compileKotlin
> Task :plugins:compileJava NO-SOURCE
> Task :plugins:classes
> Task :plugins:compileTestKotlin NO-SOURCE
> Task :plugins:compileTestJava NO-SOURCE
> Task :plugins:pluginUnderTestMetadata
> Task :plugins:testClasses UP-TO-DATE
> Task :plugins:test NO-SOURCE
> Task :plugins:validatePlugins
> Task :plugins:validatePlugins FAILED

7 actionable tasks: 7 executed
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':plugins:validatePlugins'.
> There was a failure while executing work items
   > A failure occurred while executing org.gradle.plugin.devel.tasks.internal.ValidateAction
      > Failed to run Gradle Worker Daemon
         > Unable to connect to the child process 'Gradle Worker Daemon 2'.
           It is likely that the child process have crashed - please find the stack trace in the build log.
           This exception might occur when the build machine is extremely loaded.
           The connection attempt hit a timeout after 1[20](https://github.com/<REDACTED>/actions/runs/9994153725/job/27623257177#step:5:21).0 seconds (last known process state: STARTED, running: true).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 3m 44s
```

I tried adding a `org.gradle.jvmargs=-XX:+HeapDumpOnOutOfMemoryError`, but the memory has not been dumped (from my observation the daemon doesn't crash because of OOM) 🤷 

Here's a repro I'm able to reproduce the issue on: https://github.com/mateuszkwiecinski/gradle_daemon_doesnt_work (smallest I can publicly share, not smallest that reproduces the issue, sorry :/. It can probably be stripped even further). 
I'll also mention how I ended up with such repro:
- After I removed ~all of the code - the build passed
- I restored some of the code - the build failed
- I removed all dependencies (because they weren't used) - the build passed
- I restored some of the dependencies - the build started to fail again
- I removed buildscript dependency on `ktlint` wrapper - the build started passing
- I kept the buildscript dependency removed and restored dependencies and all the code (suspecting that's the root cause) the build started to fail (with the same exception) again.

The failure is fully reproducible, and goes away when using larger runners (so it will pass on github hosted `ubuntu-latest`)

And at the end I'll confirm, the same repro, works perfectly fine with Gradle 8.8

**Comment by asodja** [comment]
On what machine does it fail? Also what happens if you somewhat limit the memory, e.g. you set `org.gradle.jvmargs=-Xmx512m`?

**Comment by mateuszkwiecinski** [comment]
>On what machine does it fail exactly? 

Unfortunately I don't know the details, I only see some of its user-facing configuration. I know we use [runner sets](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller) and that docker image with `ubuntu2204-x64` is involved. The following nodes are made available to us (I can switch between them by updating `runs-on` label on GA):
- memory=750Mi, cpu=187m - the daemon crashes here
- memory=1.5Gi, cpu 375m - the daemon crashes here
- memory=3Gi, cpu=750m - the build passes

I don't know what these `memory`/`cpu` settings are translated into specifically :/ 
I haven't tried larger self-hosted machines. I know it passes on github-hosted `ubuntu-latest` and it also works fine on self-hosted ARM-based mac runner

>Also what happens if you somewhat limit the memory, e.g. you set org.gradle.jvmargs=-Xmx512m?

The daemon still crashes (only on gradle 8.9). And I see the setting reflected in daemon crash log:

Before:
```
2024-07-18T16:17:28.617+0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] Executing build with daemon context: DefaultDaemonContext[uid=7ccbc409-7fed-4cfc-bd38-f874f258c61a,javaHome=/home/runner/_work/_tool/Java_Temurin-Hotspot_jdk/21.0.4-7.0.LTS/x64,javaVersion=21,daemonRegistryDir=/home/runner/.gradle/daemon,pid=292,idleTimeout=10800000,priority=NORMAL,applyInstrumentationAgent=true,nativeServicesMode=ENABLED,daemonOpts=-XX:+HeapDumpOnOutOfMemoryError,--add-opens=java.base/java.util=ALL-UNNAMED,--add-opens=java.base/java.lang=ALL-UNNAMED,--add-opens=java.base/java.lang.invoke=ALL-UNNAMED,--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED,--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED,--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED,--add-opens=java.base/java.nio.charset=ALL-UNNAMED,--add-opens=java.base/java.net=ALL-UNNAMED,--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED,-Dfile.encoding=UTF-8,-Duser.country,-Duser.language=en,-Duser.variant]
```
After:
```
2024-07-19T09:36:48.392+0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] Executing build with daemon context: DefaultDaemonContext[uid=6c28bab5-75dc-409a-9200-40a59a92491a,javaHome=/home/runner/_work/_tool/Java_Temurin-Hotspot_jdk/21.0.4-7.0.LTS/x64,javaVersion=21,daemonRegistryDir=/home/runner/.gradle/daemon,pid=298,idleTimeout=10800000,priority=NORMAL,applyInstrumentationAgent=true,nativeServicesMode=ENABLED,daemonOpts=-XX:+HeapDumpOnOutOfMemoryError,--add-opens=java.base/java.util=ALL-UNNAMED,--add-opens=java.base/java.lang=ALL-UNNAMED,--add-opens=java.base/java.lang.invoke=ALL-UNNAMED,--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED,--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED,--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED,--add-opens=java.base/java.nio.charset=ALL-UNNAMED,--add-opens=java.base/java.net=ALL-UNNAMED,--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country,-Duser.language=en,-Duser.variant]
```

**Comment by asodja** [comment]
We got some reports from users that they see more memory consumption for newer Gradle versions (8.9+), it could be 10% compared to 8.5.

We are investigating if that is expected or something needs improvement.

---
FYI: I spent a small amount of time investigating the issue, and with low heap, e.g. -Xmx256m (or less) it is reproducible for me, but only on first run, i.e. with clean cache. After cache was populated there was no more problem.

**Comment by laosiji66666** [comment]
I've recently run into this same issue, and no amount of adjusting the Gradle version or memory settings would fix it.

Strangely, this problem only occurred on one specific computer with one specific project, and it was intermittent.

I finally found the answer in the Windows Event Viewer: a DLL file from an internal company encryption software was causing the termination. After I renamed that DLL, the problem was solved, and the project now builds successfully.

If you're experiencing a similar issue, you might want to check for conflicts with other software.

**Comment by abstratt** [comment]
@mateuszkwiecinski We believe 8.14.4 or 8.15 should have this issue fixed (via https://github.com/gradle/gradle/issues/36396). Or, if you can use a 9.x release, 9.3 or later would work as well.

Could you please try with one of those versions and see if this issue still occurs?
