### ISSUE TITLE
Circular evaluation detected error message is unhelpful and inactionable

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#29979]
### Current Behavior

Currently, if a circular evaluation between two properties are detected, only a simple message with no context (what tasks are they in? what's the context?) is printed and it's more or less inactionable to users.

```
Caused by: org.gradle.api.internal.provider.EvaluationContext$CircularEvaluationException: Circular evaluation detected: property 'jvmTarget'
 -> property 'jvmTarget'
        at org.gradle.api.internal.provider.EvaluationContext$PerThreadContext.prepareException(EvaluationContext.java:256)
        at org.gradle.api.internal.provider.EvaluationContext$PerThreadContext.push(EvaluationContext.java:206)
        at org.gradle.api.internal.provider.EvaluationContext$PerThreadContext.open(EvaluationContext.java:216)
        at org.gradle.api.internal.provider.EvaluationContext.open(EvaluationContext.java:117)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.openScope(AbstractMinimalProvider.java:217)
        at org.gradle.api.internal.provider.AbstractProperty.getProducer(AbstractProperty.java:217)
        at org.gradle.api.internal.provider.AbstractProperty.getProducer(AbstractProperty.java:218)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.visitDependencies(AbstractMinimalProvider.java:142)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:108)
        at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmptyEdges.getNodeValues(CachingDirectedGraphWalker.java:213)
        at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:121)
        at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:73)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:67)
        ... 146 more

```

### Expected Behavior

I would expect this message to be actionable. For example: 

```
Circular evaluation detected: property 'jvmTarget' in KotlinCompile task 'compileKotlin'
 -> property 'jvmTarget' in SlackExtension extension 'slack'
```

### Steps to Reproduce

Example: https://github.com/ZacSweers/CatchUp/pull/1521

### Gradle version

8.9

**Comment by ov7a** [comment]
This feature request is in the backlog of the relevant team and is prioritized by them.
