### ISSUE TITLE
Build Failures due to file locking

### ISSUE THREAD

**Issue by inktomi** [gradle/gradle#29999]
### Current Behavior

Running a build with `--no-configuration-cache --no-configure-on-demand --no-daemon` sometimes seems to result in the following failure in CI: 

```
java.lang.IllegalStateException: Cannot start managing file contention because this handler has been closed.
	at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler.assertNotStopped(DefaultFileLockContentionHandler.java:217)
	at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler.getCommunicator(DefaultFileLockContentionHandler.java:260)
	at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler.reservePort(DefaultFileLockContentionHandler.java:254)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:124)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:106)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:101)
	at org.gradle.cache.internal.OnDemandFileAccess.updateFile(OnDemandFileAccess.java:51)
	at org.gradle.cache.internal.FileBackedObjectHolder.update(FileBackedObjectHolder.java:77)
	at org.gradle.cache.internal.FileIntegrityViolationSuppressingObjectHolderDecorator.lambda$update$0(FileIntegrityViolationSuppressingObjectHolderDecorator.java:48)
	at org.gradle.cache.internal.FileIntegrityViolationSuppressingObjectHolderDecorator.doUpdate(FileIntegrityViolationSuppressingObjectHolderDecorator.java:58)
	at org.gradle.cache.internal.FileIntegrityViolationSuppressingObjectHolderDecorator.update(FileIntegrityViolationSuppressingObjectHolderDecorator.java:48)
	at org.gradle.launcher.daemon.registry.PersistentDaemonRegistry.remove(PersistentDaemonRegistry.java:133)
	at org.gradle.launcher.daemon.server.Daemon$1.run(Daemon.java:133)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Expected Behavior

Builds should not fail a small percentage of the time. 

### Context (optional)

We see this failure at the end of some of our builds running in CI. This fails a few times out of 22 builds that we do using Gradle 8.9. 

### Steps to Reproduce

Run a build with the mentioned flags. Infrequently, you'll see a failure. 

### Gradle version

8.9

**Comment by alllex** [comment]
We appreciate the effort, but we must ask for more information so that we can triage it. 

We do not see an immediate root cause, and we need a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) for the triage. If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***
