### ISSUE TITLE
Build failed, Failed to load native-platform.dll

### ISSUE THREAD

**Issue by Suollo** [gradle/gradle#30451]
### Current Behavior

I am trying to manually install gradle for the first time. when gradle -v is run, error comes up

following error:

**C:\Users\oofoo>gradle --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Gradle could not start your build.
> Could not initialize native services.
   > Failed to load native library 'native-platform.dll' for Windows 11 amd64.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.initialization.exception.InitializationException: Gradle could not start your build.
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:49)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:444)
        at org.gradle.launcher.Main.doAction(Main.java:35)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:52)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:72)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:39)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
Caused by: org.gradle.internal.service.ServiceCreationException: Could not initialize native services.
        at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:217)
        at org.gradle.internal.nativeintegration.services.NativeServices.initializeOnClient(NativeServices.java:184)
        at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:48)
        at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:27)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
        ... 9 more
Caused by: net.rubygrapefruit.platform.NativeException: Failed to load native library 'native-platform.dll' for Windows 11 amd64.
        at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:67)
        at net.rubygrapefruit.platform.Native.init(Native.java:56)
        at org.gradle.internal.nativeintegration.services.NativeServices.initializeNativeIntegrations(NativeServices.java:234)
        at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:213)
        ... 13 more
Caused by: java.io.IOException: The system cannot find the path specified
        at java.base/java.io.WinNTFileSystem.createFileExclusively0(Native Method)
        at java.base/java.io.WinNTFileSystem.createFileExclusively(WinNTFileSystem.java:536)
        at java.base/java.io.File.createNewFile(File.java:1045)
        at net.rubygrapefruit.platform.internal.NativeLibraryLocator.find(NativeLibraryLocator.java:45)
        at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:45)
        ... 16 more**

### Expected Behavior

I guess I expected the gradle version to come up

### Context (optional)

I am running AtlasOs instead of stock windows 11, which is where I assume the issue lies.

### Steps to Reproduce

Install AtlasOS

follow all gradle install instructions, and run gradle -v

thats how I get my error message

### Gradle version

8.10

**Comment by asodja** [comment]
Could you maybe try with the latest 8.x Gradle version?

Unfortunatly we currently don't have a bandwidth to investigate and support AtlasOS. 

We could improve the error message and add a link to https://docs.gradle.org/current/userguide/compatibility.html#target_platforms
