### ISSUE TITLE
Mangled stacktraces in configuration cache reports

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#30639]
### Current Behavior

It feels like there is a race condition somewhere.

[configuration-cache-report.zip](https://github.com/user-attachments/files/17069728/configuration-cache-report.zip)

I get stacktraces like this

```
	at org.gradle.internal.configuration.problems.DefaultProblemFactory$problem$1.build(DefaultProblemFactory.kt:89)oorg.gradle.internal.configuration.problems.DefaultProblemFactory$problem$1$build$diagnostics$1.get(DefaultProblemFactory.kt:89)com.	at gradle.internal.cc.impl.ProblemReportingCrossProjectModelAccess$ProblemReportingP
	at		at org.gradle.internal.cc.impl.ProblemReportingCrossProjectModelAccess$ProblemReportingProject.reportCrossProjectAccessProblem(ProblemReportingCrossProjectModelAccess.kt:584)
	at org.gradle.api.InvalidUserCodeException: Project ':activity:activity-compose' cannot dynamically look up a method in the parent project ':activity'


at 
	at 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at androidx.build.testConfiguration.TestSuiteConfigurationKt.access$createTestConfigurationGenerationTa	at org.gradle.internal.cc.impl.ProblemReportingCrossProjectModelAccess$ProblemReportingProject.onMutableStateAccess(ProblemReportingCrossProjectModelAccess.kt:162)
	at org.jetbrains.kotlin.compilerRunner.KotlinNativeToolRunner$Settings$Companion.of(nativeToolRunners.kt:103)
	at org.gradle.internal.metaobject.CompositeDynamicObject.hasMethod(CompositeDynamicObject.java:89)
org.org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunne
	at a:59)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAct
on.execu
e(Defaul
	at 
gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.
	at 	at gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.lambda$run$0(LifecycleProjectEvaluator.java:114)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:65)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)org.gradle.api.internal.DefaultMutationGuard$1.execute(DefaultMu	at onGuard.java:	at 	at le.internal.event.AbstractBroadcastDisp	at .dispatch(AbstractBroadcastDispatch.java:70)Downloader$c
rg.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)			at 		at groovy.lang.Closure.call(Closure.java:427)o	at radle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.lambda$fromMutableState$2(DefaultProjectStateRegistry.java:434)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:348)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.api.internal.project.MutableStateAccessAwareProject.getTasks(MutableStateAccessAwarePro
org.gradle.internal.ImmutableActionSet$SetWithFewActions.execute(ImmutableActionSet.java:285)
	at org.gradle.internal.problems.DefaultProblemDiagnosticsFactory$DefaultProblemStream.getImplicitThrowable(DefaultProblemDiagnosticsFactory.java:165)
org.org.gradle.internal.operations.DefaultBuildOperationRunner$1.executultBuildOperationRunner.java:47
		at  gradle.internal.event.BroadcastDispatch$
ompositeDispatch.dispatch(BroadcastDispatch.java:272)
	at C	at 
rg.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:280)
	at oidx.build.testConfiguration.TestSuiteConfigurationKt.registerGenera	at stConfigurationTask(TestSuiteConfiguration.kt:190)
	at 	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.fromMutableState(DefaultProjectStateRegistry.java:434)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:170)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.api.internal.plugins.DefaultPluginManager.lambda$doApply$0(DefaultPluginManager.java:170)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at androidx.build.testConfiguration.TestSuiteConfigurationKt.createTestConfigurationGenerationTask(TestSuiteConfiguration.kt:109)o		at gradle.api.internal.provider.DefaultProviderFactory.of(DefaultProviderFactory.java:212)
	at 	at java	at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.run(LifecycleProjectEvaluator.java:100)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)

	at 	at  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at androidx.build.testConfiguration.TestSuiteConfigurationKt.access$createTestConfigurationGenerationTa	at org.gradle.internal.cc.impl.ProblemReportingCrossProjectModelAccess$ProblemReportingProject.onMutableStateAccess(ProblemReportingCrossProjectModelAccess.kt:162)
	at org.jetbrains.kotlin.compilerRunner.KotlinNativeToolRunner$Settings$Companion.of(nativeToolRunners.kt:103)
	at org.gradle.internal.metaobject.CompositeDynamicObject.hasMethod(CompositeDynamicObject.java:89)
org.org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunne
	at a:59)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAct
on.execu
e(Defaul
	at 
gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.
	at 	at gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.lambda$run$0(LifecycleProjectEvaluator.java:114)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:65)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)org.gradle.api.internal.DefaultMutationGuard$1.execute(DefaultMu	at onGuard.java:	at 	at le.internal.event.AbstractBroadcastDisp	at .dispatch(AbstractBroadcastDispatch.java:70)Downloader$c
rg.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)			at 		at groovy.lang.Closure.call(Closure.java:427)o	at radle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.lambda$fromMutableState$2(DefaultProjectStateRegistry.java:434)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:348)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.api.internal.project.MutableStateAccessAwareProject.getTasks(MutableStateAccessAwarePro
org.gradle.internal.ImmutableActionSet$SetWithFewActions.execute(ImmutableActionSet.java:285)
	at org.gradle.internal.problems.DefaultProblemDiagnosticsFactory$DefaultProblemStream.getImplicitThrowable(DefaultProblemDiagnosticsFactory.java:165)
org.org.gradle.internal.operations.DefaultBuildOperationRunner$1.executultBuildOperationRunner.java:47
		at  gradle.internal.event.BroadcastDispatch$
ompositeDispatch.dispatch(BroadcastDispatch.java:272)
	at C	at 
rg.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:280)
	at oidx.build.testConfiguration.TestSuiteConfigurationKt.registerGenera	at stConfigurationTask(TestSuiteConfiguration.kt:190)
	at 	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.fromMutableState(DefaultProjectStateRegistry.java:434)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:170)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.api.internal.plugins.DefaultPluginManager.lambda$doApply$0(DefaultPluginManager.java:170)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at androidx.build.testConfiguration.TestSuiteConfigurationKt.createTestConfigurationGenerationTask(TestSuiteConfiguration.kt:109)o		at gradle.api.internal.provider.DefaultProviderFactory.of(DefaultProviderFactory.java:212)
	at 	at java	at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.run(LifecycleProjectEvaluator.java:100)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
org.gradle.util.internal.ConfigureUtil.configureTarget(ConfigureUtil.java:166)org.gradle.internal.cc.impl.ProblemReportingCrossProjectModelAccess$ProblemReportingProject.reportCrossProjectAccessProblem(ProblemReportingCrossProjectModelAccess.kt:584)
	at gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunne
.java:69)
at iteConfiguration.kt:1		at	at .gradle.internal.operations.DefaultBuildOperationRunner.run(Def	at Build	at ationRunner.java:47)mpl.ProblemReportingCrossProjectModelAccess$ProblemReportingProject.reportCrossProjectAccessProblem$default(ProblemReportingCrossProjectModelAccess.kt:569)
	at o	at 	at com.android.build.api.extension.impl.AndroidComponentsExtensionImpl$onVariants$1.execute(AndroidComponentsExtension
	at 
	at org.gradle.api.internal.plugins.DefaultPluginManager.addImperativePlugin(DefaultPluginManager.java:98)
	at jdk.proxy1/jdk.proxy1.$Proxy102.afterEvaluate(Unknown Source)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:170)a	at id	at 	at Release.addToAnchorTask(Release.kt:470)org.gradle.internal.cc.impl.ProblemReportingCrossProjectModelAccess$ProblemReportingProject.reportCrossProjectAccessProblem(ProblemReportingCrossProjectModelAccess.kt:584)
	at com.android.build.gradle.internal.plugins.BasePlugin$createTasks$2.accept(BasePlugin.kt:594)
	at  gradle	at org.gradle.internal.cc.impl.ProblemReportingCrossProjectModelAccess$ProblemReportingProject.onMutableStateAccess(ProblemReportingCrossProjectModelAccess.kt:162)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)o
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:348)
org.gradle.api.internal.project.DefaultProject.evaluateUnchecked(DefaultProject.java:824)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:110)
uild_e0u21j5nyv8aavr08nk5y2t00.run(/usr/local/google/home/aurimas/Code/androidx-main/frameworks/support/activity/activity-compose/build.gradle:72)o
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

### Expected Behavior

Normal readeable stacktraces

### Self-contained Reproducer Project

It seems to work best on large projects like https://github.com/androidx/androidx

### Gradle version

gradle-8.11-20240919190722+0000

### Build scan URL (optional)

https://ge.androidx.dev/s/wb6w45ftnfiwq

**Comment by eskatos** [comment]
Thank you for the report Aurimas.
The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by mlopatkin** [comment]
This has likely been fixed with #31286.

@liutikas have you seen this issue again recently (since 8.11.1)?
