### ISSUE TITLE
Random exception  at org.jetbrains.kotlin.psi.psiUtil.PsiUtilsKt$siblings$1$iterator$1.next(psiUtils.kt:57)

### ISSUE THREAD

**Issue by jakub-bochenski** [gradle/gradle#30679]
### Current Behavior

My build started to randomly fail with below stacktrace.
Running `./gradlew clean` does nothing. I have to run `git clean -fdx` to make it build again.
```
$ ./gradlew clean check --rerun-tasks
> Task :buildSrc:compilePluginsBlocks FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':buildSrc:compilePluginsBlocks'.
> 'org.jetbrains.kotlin.com.intellij.psi.PsiElement org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.SharedImplUtil.lass(org.jetbrains.kotlin.com.intellij.lang.ASTNode)'
```

```
[ ... al lot of bytecode or something?]
(Lorg/jetbrains/kotlin/psi/stubs/KotlinClassOrObjectStub<+Lorg/jetbrains/kotlin/psi/KtClassOrObject;>;Lorg/jetbrains/kotlin/com/intellij/psi/stubs/IStubElementType<**>;)Veæÿeæÿeæÿeæÿeæÿeæÿeæÿ?eæÿeæÿeæÿeæÿeæÿe50C}¤{?WA()
0Ev[}¤{q]Method org/jetbrains/kotlin/com/intellij/psi/StubBasedPsiElement.getContainingFile()Lorg/jetbrains/kotlin/com/intellij/psi/PsiFile; is abstractUãԗMethod org/jetbrains/kotlin/com/intellij/psi/StubBasedPsiElement.acceptChildren(Lorg/jetbrains/kotlin/com/intellij/psi/PsiElementVisitor;)V is abstractuàVß}¤{¥¨Method org/jetbrains/kotlin/com/intellij/psi/StubBasedPsiElement.getCopyableUserData(Lorg/jetbrains/kotlin/com/intellij/openapi/util/Key;)Ljava/lang/Object; is abstractu¬ß}¤{%`©Method org/jetbrains/kotlin/com/intellij/psi/StubBasedPsiElement.putCopyableUserData(Lorg/jetbrains/kotlin/com/intellij/openapi/util/Key;Ljava/lang/Object;)V is abstractåÓ@]Method org/jetbrains/kotlin/com/intellij/psi/StubBasedPsiElement.textContains(C)Z is abstractõ▒¥{ôäfMethod org/jetbrains/kotlin/com/intellij/psi/StubBasedPsiElement.getStartOffsetInParent()I is abstractU04ß}¤{{Method org/jetbrains/kotlin/com/intellij/psi/StubBasedPsiElement.getTextRange()Lorg/jetbrains/kotlin/com/intellij/openapi/util/TextRange; is abstractå°Ú}¤{(]Method org/jetbrains/kotlin/com/intellij/psi/StubBasedPsiElement.getTextOffset()I is abstractE ©Ù}¤{kMethod org/jetbrains/kotlin/com/intellij/psi/StubBasedPsiElement.findElementAt(I)Lorg/jetbrains/kotlin/com/intellij/psi/PsiElement; is abstractU?7~¤{Ò͓Method org/jetbrains/kotlin/com/intellij/psi/StubBasedPsiElement.findReferenceAt(I)Lorg/jetbrains/kotlin/com/intellij/psi/PsiReference; is abstractå@mÁ|¤{+`Method org/jetbrains/kotlin/com/intellij/psi/StubBasedPsiElement.textToCharArray()[C is abstractU0~¤{1ãMethod org/jetbrains/kotlin/com/intellij/psi/StubBasedPsiElement.getNavigationElement()Lorg/jetbrains/kotlin/com/intellij/psi/PsiElement; is abstractUîÎ}¤{§֓Method org/jetbrains/kotlin/com/intellij/psi/StubBasedPsiElement.getOriginalElement()Lorg/jetbrains/kotlin/com/intellij/psi/PsiElement; is abstract°uX~¤{õsMethod org/jetbrains/kotlin/com/intellij/psi/StubBasedPsiElement.textMatches(Ljava/lang/CharSequence;)Z is abstractEp&ü}¤{9#Method org/jetbrains/kotlin/com/intellij/psi/StubBasedPsiElement.textMatches(Lorg/jetbrains/kotlin/com/intellij/psi/PsiElement;)Z is abstractÕ 6Ò}¤{¼ØMethod org/jetbrains/kotlin/psi/KtAnnotated.addAfter(Lorg/jetbrains/kotlin/com/intellij/psi/PsiElement;Lorg/jetbrains/kotlin/com/intellij/psi/PsiElement;)Lorg/jetbrains/kotlin/com/intellij/psi/PsiElement; is abstractbstract(ASTDelegatePsiElement.java:114)
        at org.jetbrains.kotlin.psi.psiUtil.PsiUtilsKt$siblings$1$iterator$1.next(psiUtils.kt:57)
        at org.jetbrains.kotlin.psi.psiUtil.PsiUtilsKt$siblings$1$iterator$1.next(psiUtils.kt:49)
        at org.jetbrains.kotlin.psi.KtQualifiedExpression.getExpression(KtQualifiedExpression.kt:47)
        at org.jetbrains.kotlin.psi.KtQualifiedExpression.getReceiverExpression(KtQualifiedExpression.kt:29)
        at org.jetbrains.kotlin.psi.KtDotQualifiedExpression.getReceiverExpression(KtDotQualifiedExpression.kt:45)
        at org.jetbrains.kotlin.psi.KtPackageDirective.getPackageNames(KtPackageDirective.java:67)
        at org.jetbrains.kotlin.psi.KtPackageDirective.getQualifiedNameOf(KtPackageDirective.java:160)
        at org.jetbrains.kotlin.psi.KtPackageDirective.getQualifiedName(KtPackageDirective.java:151)
        at org.jetbrains.kotlin.psi.KtPackageDirective.getFqName(KtPackageDirective.java:112)
        at org.jetbrains.kotlin.psi.KtFile.getPackageFqNameByTree(KtFile.kt:102)
        at org.jetbrains.kotlin.psi.KtFile.getPackageFqName(KtFile.kt:90)
        at org.jetbrains.kotlin.cli.common.UtilsKt$checkKotlinPackageUsageForPsi$1.invoke(utils.kt:77)
        at org.jetbrains.kotlin.cli.common.UtilsKt$checkKotlinPackageUsageForPsi$1.invoke(utils.kt:75)
        at org.jetbrains.kotlin.cli.common.UtilsKt.checkKotlinPackageUsage(utils.kt:55)
        at org.jetbrains.kotlin.cli.common.UtilsKt.checkKotlinPackageUsageForPsi(utils.kt:75)
        at org.jetbrains.kotlin.cli.common.UtilsKt.checkKotlinPackageUsageForPsi$default(utils.kt:70)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileBunchOfSources(KotlinToJVMBytecodeCompiler.kt:136)
        at org.gradle.kotlin.dsl.support.KotlinCompilerKt.compileKotlinScriptModuleTo(KotlinCompiler.kt:189)
        at org.gradle.kotlin.dsl.support.KotlinCompilerKt.compileKotlinScriptModuleTo(KotlinCompiler.kt:101)
        at org.gradle.kotlin.dsl.provider.plugins.precompiled.tasks.CompilePrecompiledScriptPluginPlugins.compile(CompilePrecompiledScriptPluginPlugins.kt:107)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:244)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:229)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:212)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:195)
        at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:162)
        at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:105)
        at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:59)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:56)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:56)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:44)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:42)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:75)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
        at org.gradle.internal.execution.steps.PreCreateOutputParentsStep.execute(PreCreateOutputParentsStep.java:50)
        at org.gradle.internal.execution.steps.PreCreateOutputParentsStep.execute(PreCreateOutputParentsStep.java:28)
        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:67)
        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:37)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:61)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:26)
        at org.gradle.internal.execution.steps.CaptureOutputsAfterExecutionStep.execute(CaptureOutputsAfterExecutionStep.java:69)
        at org.gradle.internal.execution.steps.CaptureOutputsAfterExecutionStep.execute(CaptureOutputsAfterExecutionStep.java:46)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:40)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:29)
        at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:189)
        at org.gradle.internal.execution.steps.BuildCacheStep.executeAndStoreInCache(BuildCacheStep.java:145)
        at org.gradle.internal.execution.steps.BuildCacheStep.lambda$executeWithCache$4(BuildCacheStep.java:101)
        at org.gradle.internal.execution.steps.BuildCacheStep.lambda$executeWithCache$5(BuildCacheStep.java:101)
        at org.gradle.internal.Try$Success.map(Try.java:175)
        at org.gradle.internal.execution.steps.BuildCacheStep.executeWithCache(BuildCacheStep.java:85)
        at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$0(BuildCacheStep.java:74)
        at org.gradle.internal.Either$Left.fold(Either.java:115)
        at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:62)
        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:73)
        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:48)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:46)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:35)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:75)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:53)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:53)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:35)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
        at org.gradle.internal.execution.steps.ResolveIncrementalCachingStateStep.executeDelegate(ResolveIncrementalCachingStateStep.java:49)
        at org.gradle.internal.execution.steps.ResolveIncrementalCachingStateStep.executeDelegate(ResolveIncrementalCachingStateStep.java:27)
        at org.gradle.internal.execution.steps.AbstractResolveCachingStateStep.execute(AbstractResolveCachingStateStep.java:71)
        at org.gradle.internal.execution.steps.AbstractResolveCachingStateStep.execute(AbstractResolveCachingStateStep.java:39)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:65)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:36)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:105)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:54)
        at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:64)
        at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:43)
        at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.executeWithNonEmptySources(AbstractSkipEmptyWorkStep.java:125)
        at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:56)
        at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36)
        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23)
        at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:75)
        at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:41)
        at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.lambda$execute$0(AssignMutableWorkspaceStep.java:35)
        at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:289)
        at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:31)
        at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:22)
        at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:40)
        at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:23)
        at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.lambda$execute$2(ExecuteWorkBuildOperationFiringStep.java:67)
        at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:67)
        at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:39)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:46)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:34)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:48)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:35)
        at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:61)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:127)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:116)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
        at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:85)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:459)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:376)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)
```

### Expected Behavior

Build should not randomly fail.

Clean task should fix this.

### Context (optional)

https://stackoverflow.com/q/79007564/1237617

### Self-contained Reproducer Project

The build just fails randomly it's obviously some internal bug :(

### Gradle version

Gradle 8.9

**Comment by eskatos** [comment]
We appreciate the effort, but we must ask for more information so that we can triage it. 

We do not see an immediate root cause, and we need a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) for the triage. If we have a reproducer project, we may be also able to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer project is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***

The garbled characters in the stacktrace suggest that there could be a corruption of your filesystem or memory.
We are not sure how to investigate, especially if this is an issue with the execution environment.

**Comment by jakub-bochenski** [comment]
The problem is this issue happens randomly it's not deterministic.
I mean once it's there it will happen until I run `git clean -fdx`, but once it's gone I have no reliable way of causing it.

I think that rules out memory corruption.
As for disk corruption I think it's rather unlikely that I'd get silent corruption on an encrypted ext4 LVM filesystem. 
Bugs happen, but the last one I'm aware was on 6.1 kernel and I'm on 6.8.
I might double check the syslog for that though...

I'm not going to try and make a minimal project for this.

I can show you the full stacktrace if it helps:
[stacktrace.txt](https://github.com/user-attachments/files/17149770/stacktrace.txt)

**Comment by ov7a** [comment]
Other potential reasons:
1. Something is printing binary contents in the output (kotlin daemon?)
2. Something happened to daemon <-> launcher connection, but I guess this can be eliminated by the fact that git clean fixes the issue. Can you also check if killing Gradle daemon does not help in your case?
3. Corrupted caches

Can you please provide a reproducer project, so we can narrow it down and eliminate the environment hypothesis? The ideal way to provide a reproducer project is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. It would be useful to use [custom gradle home](https://docs.gradle.org/current/userguide/gradle_directories.html#gradle_user_home) to be part of the repo, so the potentially corrupted stuff is preserved.

**Comment by jakub-bochenski** [comment]
As I said the issue happens randomly, I don't understand how would I even attempt to make a reproducer project

**Comment by ov7a** [comment]
Sorry, but I'm unsure how to investigate this deeper using only the provided stack trace. Currently, there is not enough data to narrow down the root cause for the bug.
