### ISSUE TITLE
'BuildDependents' task isn't compatible with project isolation 

### ISSUE THREAD

**Issue by ksiarhey** [gradle/gradle#30799]
### Current Behavior

When executing the 'buildDependents' task with Project Isolation enabled (org.gradle.unsafe.isolated-projects=true), it encounters the following errors:

`org.gradle.api.InvalidUserCodeException: Project ':' cannot access 'Project.tasks' functionality on subprojects via 'allprojects'
	at org.gradle.internal.configuration.problems.DefaultProblemFactory$problem$1$build$diagnostics$1.get(DefaultProblemFactory.kt:89)
	at org.gradle.internal.configuration.problems.DefaultProblemFactory$problem$1$build$diagnostics$1.get(DefaultProblemFactory.kt:89)
	at org.gradle.internal.problems.DefaultProblemDiagnosticsFactory$DefaultProblemStream.getImplicitThrowable(DefaultProblemDiagnosticsFactory.java:165)
	at org.gradle.internal.problems.DefaultProblemDiagnosticsFactory$DefaultProblemStream.forCurrentCaller(DefaultProblemDiagnosticsFactory.java:154)
	at org.gradle.internal.configuration.problems.DefaultProblemFactory$problem$1.build(DefaultProblemFactory.kt:89)
	at org.gradle.internal.cc.impl.ProblemReportingCrossProjectModelAccess$ProblemReportingProject.reportCrossProjectAccessProblem(ProblemReportingCrossProjectModelAccess.kt:584)
	at `

and 

`org.gradle.api.InvalidUserCodeException: Project ':app' cannot access 'Project.tasksByName' functionality on another project ':'
	at org.gradle.internal.configuration.problems.DefaultProblemFactory$problem$1$build$diagnostics$1.get(DefaultProblemFactory.kt:89)
	at org.gradle.internal.configuration.problems.DefaultProblemFactory$problem$1$build$diagnostics$1.get(DefaultProblemFactory.kt:89)
	at org.gradle.internal.problems.DefaultProblemDiagnosticsFactory$DefaultProblemStream.getImplicitThrowable(DefaultProblemDiagnosticsFactory.java:165)
	at org.gradle.internal.problems.DefaultProblemDiagnosticsFactory$DefaultProblemStream.forCurrentCaller(DefaultProblemDiagnosticsFactory.java:154)
	at org.gradle.internal.configuration.problems.DefaultProblemFactory$problem$1.build(DefaultProblemFactory.kt:89)
	at org.gradle.internal.cc.impl.ProblemReportingCrossProjectModelAccess$ProblemReportingProject.reportCrossProjectAccessProblem(ProblemReportingCrossProjectModelAccess.kt:584)
	at org.gradle.internal.cc.impl.ProblemReportingCrossProjectModelAccess$ProblemReportingProject.reportCrossProjectAccessProblem$default(ProblemReportingCrossProjectModelAccess.kt:569)
	at org.gradle.internal.cc.impl.ProblemReportingCrossProjectModelAccess$ProblemReportingProject.onIsolationViolation(ProblemReportingCrossProjectModelAccess.kt:499)
	at `

The project setup is very simple, there are 2 modules, one depends on another one via dependencies : 'implementation(project(":projectName"))'
	

### Expected Behavior

'BuildDependents' task is compatible with the Project isolation feature 

### Self-contained Reproducer Project

[test-wizard-multi-modules.zip](https://github.com/user-attachments/files/17259039/test-wizard-multi-modules.zip)

### Gradle version

8.10.1

**Comment by ov7a** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.
