### ISSUE TITLE
ClassCastException for com.android.build.gradle.LibraryExtension 

### ISSUE THREAD

**Issue by drysovanyi** [gradle/gradle#30801]
### Current Behavior

I have Jacoco scripts in buildSrc for Kotlin DSL including Kotlin-dsl-precompiled-script-plugins that calculate for me code coverage. I need to get info about current project variants, I'm using this code 

```
val androidExtension = project.extensions.getByName("android")
    val variants = if (project.hasProperty("applicationVariants")) {
        (androidExtension as AppExtension).applicationVariants
    } else {
        (androidExtension as LibraryExtension).libraryVariants
    }
```
    
and I have these two imports in my build 

import com.android.build.gradle.AppExtension
import com.android.build.gradle.LibraryExtension
    
But when I'm trying to sync my project I'm getting this error

Here is a stacktrace

```
Caused by: java.lang.ClassCastException: class com.android.build.gradle.internal.dsl.BaseAppModuleExtension_Decorated cannot be cast to class com.android.build.gradle.LibraryExtension (com.android.build.gradle.internal.dsl.BaseAppModuleExtension_Decorated and com.android.build.gradle.LibraryExtension are in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader @139b2ee4)
        at Jacoco_reports_gradle.setupAndroidReporting(jacoco-reports.gradle.kts:46)
        at Jacoco_reports_gradle$2.execute(jacoco-reports.gradle.kts:27)
        at Jacoco_reports_gradle$2.execute(jacoco-reports.gradle.kts:24)
        at org.gradle.internal.code.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:122)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.run(DefaultListenerBuildOperationDecorator.java:173)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction.execute(DefaultListenerBuildOperationDecorator.java:170)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:99)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:87)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:43)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:268)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:170)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:83)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:69)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:381)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:272)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:148)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at jdk.proxy1/jdk.proxy1.$Proxy69.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:247)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:244)
        at org.gradle.api.internal.project.DefaultProject.stepEvaluationListener(DefaultProject.java:1492)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate.run(LifecycleProjectEvaluator.java:253)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
```
        
        
        And this error in Gradle
        
```
class com.android.build.gradle.internal.dsl.BaseAppModuleExtension_Decorated cannot be cast to class com.android.build.gradle.LibraryExtension (com.android.build.gradle.internal.dsl.BaseAppModuleExtension_Decorated and com.android.build.gradle.LibraryExtension are in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader @67c0cf12)
class com.android.build.gradle.internal.dsl.BaseAppModuleExtension_Decorated cannot be cast to class com.android.build.gradle.LibraryExtension (com.android.build.gradle.internal.dsl.BaseAppModuleExtension_Decorated and com.android.build.gradle.LibraryExtension are in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader @67c0cf12)
```

Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

Re-download dependencies and sync project (requires network)
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.

Stop Gradle build processes (requires restart)
Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

        
I did try to clean my cache including deleting cache directory but it didn't help
```
AGP version = 8.5.2
Wrapper = 8.7
Kotlin 2.0.10
```

### Expected Behavior

The app should synchronise

### Self-contained Reproducer Project

```
import com.android.build.gradle.AppExtension
import com.android.build.gradle.LibraryExtension
import org.gradle.api.Project

apply(from = "../coverage-exclusionskts.gradle.kts")
apply(plugin = "jacoco")


configure<JacocoPluginExtension> {
    toolVersion = "0.8.7" // Replace with the correct version
}

fun isAndroidModule(project: Project): Boolean {
    val isAndroidLibrary = project.plugins.hasPlugin("com.android.library")
    val isAndroidApp = project.plugins.hasPlugin("com.android.application")
    return isAndroidLibrary || isAndroidApp
}

afterEvaluate {
    if (isAndroidModule(project)) {
        println("Setting up Android reporting...")
        setupAndroidReporting()
    } else {
        println("Setting up Kotlin reporting...")
        setupKotlinReporting()
    }
}

fun setupAndroidReporting() {
    val androidExtension = project.extensions.getByName("android")
    val variants = if (project.hasProperty("applicationVariants")) {
        (androidExtension as AppExtension).applicationVariants
    } else {
        (androidExtension as LibraryExtension).libraryVariants
    }
}
```

### Gradle version

8.5.2

### Build scan URL (optional)

https://scans.gradle.com/s/oliuwg42r3uzw

**Comment by ov7a** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

As the error indicates, you're trying to cast `BaseAppModuleExtension` to `LibraryExtension`, which fails. The sync fails because the build script contains errors.
