### ISSUE TITLE
Groovy interception with Groovy 4.x causes stackoverflow for implicit receivers

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#30805]
This happens only on [EAP branch](https://github.com/gradle/gradle/pull/25963) for signing tests. 

This was workarounded by using explicit receivers, see https://github.com/gradle/gradle/pull/30781. Reverting that PR and running these tests should cause errors like:
```
  java.lang.StackOverflowError
    at org.gradle.internal.classpath.CallInterceptingMetaClass.lambda$invokeMethod$5(CallInterceptingMetaClass.java:183)
    at org.gradle.internal.classpath.CallInterceptingMetaClass.invokeIntercepted(CallInterceptingMetaClass.java:242)
    at org.gradle.internal.classpath.CallInterceptingMetaClass.invokeMethod(CallInterceptingMetaClass.java:183)
    at org.gradle.plugins.signing.SigningProjectSpec.methodMissing(SigningProjectSpec.groovy:31)
 ```
for `org.gradle.plugins.signing.SigningConfigurationsSpec.sign task has description`.

See build scan: https://ge.gradle.org/s/5al2ktbtbtxjy

**Comment by octylFractal** [comment]
This may be Groovy 4.x related.

**Comment by octylFractal** [comment]
I tested reverting this PR locally and this no longer occurs.
