### ISSUE TITLE
Kotlin script works but Groovy fails with `Could not serialize value of type $Proxy96`

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [gradle/gradle#30830]
### Current Behavior

Running `./gradlew printSemver` crashes with:

```
Could not determine the dependencies of task ':prepareKotlinIdeaImport'.
> Could not create task ':printSemver'.
   > Could not isolate value com.javiersc.semver.project.gradle.plugin.valuesources.VersionValueSource$Params_Decorated@29b7b7f of type VersionValueSource.Params
      > Could not serialize value of type $Proxy96
```

If you rename the Reproducer `build.gradle` file to `build.gradle.kts` it compiles without no issues and it prints:

```
> Task :printSemver
semver for semver-repro-175: 1.0.0
```

I have tried to change the implementation of the value source `versionMapper` property to use the Gradle API `Transformer` with no luck.

- [Plugin value source](https://github.com/JavierSegoviaCordoba/semver-gradle-plugin/blob/c402c81e05b77cb34315c23c89e2ee312a218b8d/semver-project-gradle-plugin/main/kotlin/com/javiersc/semver/project/gradle/plugin/valuesources/VersionValueSource.kt#L84-L94)
- [Reproducer](https://github.com/Reproducers/semver-repro-175)

### Expected Behavior

As the project is working with a Kotlin script, I would expect it to work with a Groovy script.

### Self-contained Reproducer Project

- [Reproducer](https://github.com/Reproducers/semver-repro-175)

### Gradle version

8.10.2

**Comment by JavierSegoviaCordoba** [comment]
Original issue: https://github.com/JavierSegoviaCordoba/semver-gradle-plugin/issues/175

**Comment by Vampire** [comment]
Ugly, but working work-around:
```groovy
class Map {
	static per = new SemverExtension.VersionMapper() {
		@Override
		String map(GradleVersion gradleVersion) {
			"1.0.0"
		}
	}
}
semver {
	mapVersion Map.per
}
```

**Comment by tkrah** [comment]
> Ugly, but working work-around:
> 
> ```groovy
> class Map {
>     static per = new SemverExtension.VersionMapper() {
>         @Override
>         String map(GradleVersion gradleVersion) {
>             "1.0.0"
>         }
>     }
> }
> semver {
>     mapVersion Map.per
> }
> ```

Did you tried that work-around? Gradle complains with that to me:

```

* Where:
Build file '/path/semver-gradle-plugin-playground/build.gradle' line: 18

* What went wrong:
Could not compile build file '/path/semver-gradle-plugin-playground/build.gradle'.
> startup failed:
  build file '/path/semver-gradle-plugin-playground/build.gradle': 18: Can't have an abstract method in a non-abstract class. The class 'Map$1' must be declared abstract or the method 'java.lang.String map(com.javiersc.gradle.version.GradleVersion)' must be implemented.
   @ line 18, column 51.
     mverExtension.VersionMapper() {
                                   ^
  
  build file '/path/semver-gradle-plugin-playground/build.gradle': 19: Method 'map' from class 'Map$1' does not override method from its superclass or interfaces but is annotated with @Override.
   @ line 19, column 3.
                @Override
       ^
  
  2 errors

```

**Comment by Vampire** [comment]
Yes I did, but I omitted the imports, maybe you miss them?

**Comment by tkrah** [comment]
> Yes I did, but I omitted the imports, maybe you miss them?

No I got them too. I'll push a branch to my playground, may you can spot my error if you can have a look ([here](https://github.com/tkrah/semver-gradle-plugin-playground/tree/ISSUE-175-WORKAROUND))

**Comment by ov7a** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

We need to investigate where does this `Proxy` comes from

**Comment by Vampire** [comment]
@ov7a the proxy is the Groovy closure and it actually fails to serialized the extension which seems to be referred to by the closure. Also see the discussion that led to this ticket: https://www.linen.dev/s/gradle-community/t/23142024/related-to-the-above-i-am-getting-this-error-gt-could-not-cr#3532209a-769e-469d-9fa4-66e27900b423

**Comment by ov7a** [comment]
Thanks, @Vampire!

**Comment by mlopatkin** [comment]
The relevant stack trace:
```
Caused by: org.gradle.internal.snapshot.impl.IsolationException: Could not isolate value com.javiersc.semver.project.gradle.plugin.valuesources.VersionValueSource$Params_Decorated@3bcdc308 of type VersionValueSource.Params
        at org.gradle.internal.snapshot.impl.DefaultIsolatableFactory.isolate(DefaultIsolatableFactory.java:51)
        at org.gradle.api.internal.provider.DefaultValueSourceProviderFactory.isolateParameters(DefaultValueSourceProviderFactory.java:174)
        at org.gradle.api.internal.provider.DefaultValueSourceProviderFactory.access$400(DefaultValueSourceProviderFactory.java:49)
        at org.gradle.api.internal.provider.DefaultValueSourceProviderFactory$LazilyObtainedValue.source(DefaultValueSourceProviderFactory.java:334)
        at org.gradle.api.internal.provider.DefaultValueSourceProviderFactory$LazilyObtainedValue.lambda$new$0(DefaultValueSourceProviderFactory.java:298)
        at org.gradle.internal.model.CalculatedValueContainerFactory$SupplierBackedCalculator.calculateValue(CalculatedValueContainerFactory.java:78)
        at org.gradle.internal.model.CalculatedValueContainer$CalculationState.lambda$attachValue$0(CalculatedValueContainer.java:228)
        at org.gradle.internal.Try.ofFailable(Try.java:50)
        at org.gradle.internal.model.CalculatedValueContainer$CalculationState.attachValue(CalculatedValueContainer.java:223)
        at org.gradle.internal.model.CalculatedValueContainer.finalizeIfNotAlready(CalculatedValueContainer.java:194)
        at org.gradle.internal.model.CalculatedValueContainer.finalizeIfNotAlready(CalculatedValueContainer.java:185)
        at org.gradle.api.internal.provider.DefaultValueSourceProviderFactory$LazilyObtainedValue.obtain(DefaultValueSourceProviderFactory.java:315)
        at org.gradle.api.internal.provider.DefaultValueSourceProviderFactory$ValueSourceProvider.calculateOwnValue(DefaultValueSourceProviderFactory.java:267)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.getOrNull(AbstractMinimalProvider.java:105)
        at com.javiersc.semver.project.gradle.plugin.VersionProperty.toString(VersionProperty.kt:7)
        at com.javiersc.semver.project.gradle.plugin.tasks.PrintSemverTask$Companion.register$lambda$2(PrintSemverTask.kt:179)
        at com.javiersc.semver.project.gradle.plugin.tasks.PrintSemverTask$Companion.register$lambda$3(PrintSemverTask.kt:169)
        at org.gradle.api.internal.DefaultMutationGuard$1.execute(DefaultMutationGuard.java:45)
        at org.gradle.api.internal.DefaultMutationGuard$1.execute(DefaultMutationGuard.java:45)
        at org.gradle.internal.code.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:124)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:110)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:107)
        at org.gradle.internal.ImmutableActionSet$SetWithManyActions.execute(ImmutableActionSet.java:329)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:262)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.doAdd(DefaultNamedDomainObjectCollection.java:125)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:256)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.tryCreate(DefaultNamedDomainObjectCollection.java:1011)
        ... 160 more
Caused by: org.gradle.internal.snapshot.ValueSnapshottingException: Could not serialize value of type $Proxy108
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.newValueSerializationException(AbstractValueProcessor.java:223)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.javaSerialized(AbstractValueProcessor.java:214)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.javaSerialization(AbstractValueProcessor.java:205)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.processValue(AbstractValueProcessor.java:119)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.processManaged(AbstractValueProcessor.java:127)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.processValue(AbstractValueProcessor.java:98)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.processManaged(AbstractValueProcessor.java:127)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.processValue(AbstractValueProcessor.java:98)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.processManaged(AbstractValueProcessor.java:127)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.processValue(AbstractValueProcessor.java:98)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.processArrayElements(AbstractValueProcessor.java:183)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.processArray(AbstractValueProcessor.java:176)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.processValue(AbstractValueProcessor.java:92)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.processManaged(AbstractValueProcessor.java:127)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.processValue(AbstractValueProcessor.java:98)
        at org.gradle.internal.snapshot.impl.DefaultIsolatableFactory.isolate(DefaultIsolatableFactory.java:49)
        ... 193 more
Caused by: java.io.NotSerializableException: com.javiersc.semver.project.gradle.plugin.SemverExtension_Decorated
        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1175)
        at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1543)
        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1500)
        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1423)
        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1169)
        at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1543)
        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1500)
        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1423)
        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1169)
        at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1543)
        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1500)
        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1423)
        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1169)
        at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1543)
        at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1500)
        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1423)
        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1169)
        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:345)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.javaSerialized(AbstractValueProcessor.java:211)
        ... 207 more

```
