### ISSUE TITLE
CC-compatible code seems to be not compatible when running with STABLE_CONFIGURATION_CACHE

### ISSUE THREAD

**Issue by abstratt** [gradle/gradle#30903]
### Current Behavior

When [STABLE_CONFIGURATION_CACHE](https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:stable) is enabled, `gradle tasks` produces a deprecation warning:

```
gradle  tasks --warning-mode all --no-configuration-cache
```

```
Invocation of Task.project at execution time has been deprecated. This will fail with an error in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.10.2/userguide/upgrading_version_7.html#task_project
```

### Expected Behavior

Gradle own tasks, such a `tasks`, should be compatible with the configuration cache and not produce warnings when running in vintage mode.

### Context (optional)

In this case, the task is CC-compatible, but the approach it uses is based on a pattern that triggers false positives when used in vintage mode. 

We are going to deprecate `Task.getProject()` when CC is *not* enabled (#30860). Up to 8.11, we only did that for builds where `STABLE_CONFIGURATION_CACHE` is enabled. We need to allow CC-compatible code to run in vintage mode without producing warnings.

### Self-contained Reproducer Project

Any project will do.

### Gradle version

At least since 8.10

**Comment by abstratt** [comment]
```
	at org.gradle.internal.cc.impl.DeprecatedFeaturesListener.nagUserAbout(DeprecatedFeaturesListener.kt:98)
	at org.gradle.internal.cc.impl.DeprecatedFeaturesListener.onProjectAccess(DeprecatedFeaturesListener.kt:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:570)
	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:540)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:84)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:70)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:397)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:382)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:67)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:397)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:382)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:92)
	at com.sun.proxy.$Proxy110.onProjectAccess(Unknown Source)
	at org.gradle.internal.cc.impl.AbstractTaskProjectAccessChecker.notifyProjectAccess(TaskExecutionAccessCheckers.kt:47)
	at org.gradle.api.internal.AbstractTask.getProject(AbstractTask.java:238)
	at org.gradle.api.DefaultTask.getProject(DefaultTask.java:59)
	at org.gradle.api.tasks.diagnostics.internal.TaskDetailsFactory.create(TaskDetailsFactory.java:34)
	at org.gradle.api.tasks.diagnostics.internal.SingleProjectTaskReportModel.forTasks(SingleProjectTaskReportModel.java:33)
	at org.gradle.api.tasks.diagnostics.TaskReportTask.lambda$buildTaskReportModelFor$4(TaskReportTask.java:267)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.fromMutableState(DefaultProjectStateRegistry.java:429)
	at org.gradle.api.tasks.diagnostics.TaskReportTask.buildTaskReportModelFor(TaskReportTask.java:266)
	at org.gradle.api.tasks.diagnostics.TaskReportTask.taskReportModelFor(TaskReportTask.java:250)
	at org.gradle.api.tasks.diagnostics.TaskReportTask.projectReportModelFor(TaskReportTask.java:218)
	at org.gradle.api.tasks.diagnostics.TaskReportTask.lambda$computeProjectModels$2(TaskReportTask.java:182)
	at org.gradle.internal.Try.ofFailable(Try.java:50)
	at org.gradle.api.tasks.diagnostics.TaskReportTask.computeProjectModels(TaskReportTask.java:182)
	at org.gradle.api.tasks.diagnostics.TaskReportTask.computeTaskReportModel(TaskReportTask.java:176)
	at org.gradle.internal.Try.ofFailable(Try.java:50)
	at org.gradle.internal.serialization.Cached$Deferred.result(Cached.java:53)
	at org.gradle.internal.serialization.Cached$Deferred.get(Cached.java:48)
	at org.gradle.api.tasks.diagnostics.TaskReportTask.generate(TaskReportTask.java:166)
```

**Comment by mlopatkin** [comment]
We use `Cached` for some tasks and rely on its serialization behavior to compute `getProject`-calling methods at store time. Obviously, this doesn't work when CC isn't enabled because there is no store, which leads to calling `getProject` at execution time.

This was one of the scenarios of #22481, but I over-focused on KGP scenarios where `provider {}` is involved and forgot to actually fix `Cached`.

I'd argue that we don't really need private API of `Cached` and can use `provider {}` instead which gives the same semantics while suppressing the deprecation when store isn't there (==without CC).
