### ISSUE TITLE
Deadlock with configuration cache in Gradle 8.10

### ISSUE THREAD

**Issue by Tapchicoma** [gradle/gradle#30905]
### Current Behavior

This is a cross-link issue for [this Kotlin issue](https://youtrack.jetbrains.com/issue/KT-72001).

> On Mac computers, in AndroidX repo Gradle hangs on resolving dependencies for some tasks, e.g ./gradlew :compose:integration-tests:demos:installDebug.

From captured jstack it looks like Gradle is waiting for a lock to capture environment variable:
```
"Daemon worker" #29 [42243] prio=5 os_prio=31 cpu=40318.06ms elapsed=210.81s tid=0x0000000154d3de00 nid=42243 waiting on condition  [0x0000000172b06000]
   java.lang.Thread.State: WAITING (parking)
    at jdk.internal.misc.Unsafe.park(java.base@21.0.4/Native Method)
    - parking to wait for  <0x0000000601431a20> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
    at java.util.concurrent.locks.LockSupport.park(java.base@21.0.4/LockSupport.java:221)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@21.0.4/AbstractQueuedSynchronizer.java:754)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@21.0.4/AbstractQueuedSynchronizer.java:990)
    at java.util.concurrent.locks.ReentrantLock$Sync.lock(java.base@21.0.4/ReentrantLock.java:153)
    at java.util.concurrent.locks.ReentrantLock.lock(java.base@21.0.4/ReentrantLock.java:322)
    at org.gradle.internal.event.DefaultListenerManager$ExclusiveEventBroadcast.startDispatch(DefaultListenerManager.java:473)
    at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:395)
    at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:382)
    at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:92)
    at jdk.proxy3.$Proxy34.envVariableRead(jdk.proxy3/Unknown Source)
    at org.gradle.internal.cc.impl.InstrumentedInputAccessListener.envVariableQueried(InstrumentedInputAccessListener.kt:103)
    at org.gradle.internal.classpath.Instrumented.envVariableQueried(Instrumented.java:446)
    at org.gradle.internal.classpath.Instrumented.getenv(Instrumented.java:235)
    at org.jetbrains.kotlin.konan.util.DependencyDirectories.getLocalKonanDir(DependencyDirectories.kt:26)
```

### Expected Behavior

No deadlock with configuration cache enabled.

### Self-contained Reproducer Project

Check public AndroidX repo.

### Gradle version

8.10.2

### Gradle version that used to work

8.9

**Comment by mlopatkin** [comment]
Fixed in #30953
