### ISSUE TITLE
Gradle fails to incrementally compile when the classpath contains a multi-release jar with a higher Java version

### ISSUE THREAD

**Issue by brettkail-wk** [gradle/gradle#30949]
### Current Behavior

This is a restatement of #27856 for the general problem: if your project is stuck on an older version of Gradle or Java for whatever reason, but your project must update to a newer version of a library dependency for whatever reason, Gradle fails to incrementally compile even though those class files will not be used for compilation.  Gradle should either ignore those classes or give some option to ignore them.

### Expected Behavior

See #27856.  Incremental compilation continues to work when multi-release jars contain classes that are too high for Gradle to understand.

### Self-contained Reproducer Project

See #27856.  It's not really possible to create an project that won't get outdated since any example will require finding a released dependency with an MR class that has a higher version than the latest supported by Gradle.  We're currently on 8.5 attempting to depending on Jackson 2.18.0.  The specific problem is resolved by moving to Gradle 8.10.2, but it's not clear that the general problem has been resolved.

### Gradle version

8.5

**Comment by jacinpoz** [comment]
Are there any news regarding prioritization of this issue? It is kind of a big deal for us, as we provide software for organisations that can't upgrade Gradle quickly due to their internal vetting process. 

Jackson is a very common library in the JVM ecosystem, so many third party dependencies upgrade to newer versions regularly, causing clashes in our build that are hard to manage and potentially preventing us from upgrading certain libs which then leads to CVE vulnerabilities not being addressed.

In our particular case, we are using Gradle 8.4 and this issue causes the build to fail immediately rather than prevent incremental compilation from happening. It doesn't even allow us to upgrade the gradle wrapper (it fails with the same error) unless we do so using a separate gradle installation. Sample stacktrace below:

```
Caused by: java.io.IOException: Failed to process the entry 'META-INF/versions/22/com/fasterxml/jackson/core/internal/shaded/fdp/v2_18_3/FastDoubleSwar.class' from '/home/user_home/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.18.3/78f80c259268200e588aa204dd97ecf09b76916e/jackson-core-2.18.3.jar'
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.lambda$visitEntries$1(InstrumentingClasspathFileTransformer.java:222)
	at org.gradle.internal.classpath.ClasspathWalker.visitJarContents(ClasspathWalker.java:91)
	at org.gradle.internal.classpath.ClasspathWalker.visit(ClasspathWalker.java:55)
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.visitEntries(InstrumentingClasspathFileTransformer.java:201)
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.lambda$instrument$0(InstrumentingClasspathFileTransformer.java:192)
	at org.gradle.internal.classpath.ClasspathBuilder.buildJar(ClasspathBuilder.java:68)
	at org.gradle.internal.classpath.ClasspathBuilder.jar(ClasspathBuilder.java:55)
```

Thanks!

**Comment by Vampire** [comment]
@jacinpoz this issue is about analysis for incremental compilation, your stacktrace shows that your issues is with instrumentation, which @ljacomet stated in the comment before yours should be fixed in 8.4 already.
If you really get this with 8.4, you should open a bug report, but I just tried.
If I have that Jackson version in 8.3 build script classpath exactly that error with exactly that line information is thrown.,
if I try with 8.4 there is no error, so I assume that you are not using 8.4, but something older.

 >  It doesn't even allow us to upgrade the gradle wrapper

Just update the version in the `gradle-wrapper.properties`. :-)

**Comment by jacinpoz** [comment]
@Vampire We were 100% using Gradle 8.4 and I can reproduce the issue on demand in our project. However, we managed to get approval to upgrade to a newer Gradle version since then internally and therefore this is not a problem for us anymore.

Thanks for replying though, I appreciate the help :-).

**Comment by dhensche** [comment]
We are using a Gradle 8.12 wrapper and can reproduce this issue as well. In a similar boat, our bloated app is stuck on java 8 for now but a lot of our dependencies use the multi-release jar and it prevents incremental compilation. Our app has 13k+ source files so it is a pretty decent devex pain. I can pinpoint which classes are causing the issue, but don't have a great work around for the developers I support
