### ISSUE TITLE
Toolchain download on alpine fails in indecipherable way

### ISSUE THREAD

**Issue by Mahoney** [gradle/gradle#30970]
### Current Behavior

Attempting to use a Java 21 toolchain on alpine without Java 21 installs fails, but in an indecipherable way.

If you use an alpine based Docker image to run a gradle build that requires a toolchain download it fails - which is fine, except that the failure is totally obscured by a further exception thrown when trying to instantiate the actual exception.

Stacktrace:
```
org.gradle.internal.nativeintegration.NativeIntegrationUnavailableException: Service 'SystemInfo' is not available (os=Linux 6.10.4-linuxkit aarch64, enabled=false).
   at org.gradle.internal.nativeintegration.services.NativeServices$BrokenService.invoke(NativeServices.java:573)
   at jdk.proxy1/jdk.proxy1.$Proxy86.getArchitecture(Unknown Source)
   at org.gradle.platform.internal.DefaultBuildPlatform.getArchitecture(DefaultBuildPlatform.java:52)
   at org.gradle.platform.internal.DefaultBuildPlatform.lambda$new$0(DefaultBuildPlatform.java:37)
   at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181)
   at org.gradle.platform.internal.DefaultBuildPlatform.getArchitecture(DefaultBuildPlatform.java:43)
   at org.gradle.platform.internal.DefaultBuildPlatform_Decorated.getArchitecture(Unknown Source)
   at org.gradle.jvm.toolchain.internal.NoToolchainAvailableException.<init>(NoToolchainAvailableException.java:37)
   at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.downloadToolchain(JavaToolchainQueryService.java:227)
```

As you can see, gradle is trying to instantiate a `NoToolchainAvailableException`, which is expected, but in the process it calls `getArchitecture()` on a proxy implementing `net.rubygrapefruit.platform.SystemInfo`, which itself throws an exception.

This causes the original `ToolchainDownloadFailedException` that would have been included as the cause of the `NoToolchainAvailableException` to be lost.

### Expected Behavior

The `NoToolchainAvailableException` is successfully instantiated with the `ToolchainDownloadFailedException` as its cause and printed out by gradle as the actual problem, despite Service 'SystemInfo' not being available.

### Self-contained Reproducer Project

https://github.com/Mahoney-bug-examples/gradle-alpine-arm-toolchain-bug

### Gradle version

8.10.2

### Your Environment (optional)

Docker image `eclipse-temurin:23_37-jdk-alpine` on both ARM & AMD64

**Comment by ljacomet** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

***

This is caused by lack of support of some native integration on Alpine/musl.

But indeed, the failure to query the architecture should not hide the toolchain exception. Gradle should report an unknown architecture - which is probably also the root cause of being unable to download a toolchain.

Relates to:
* #30885
