### ISSUE TITLE
BuildCache should support lazy Property API

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#30985]
### Expected Behavior

There should be a way to configure `BuildCache` with lazy APIs like `Property<String>`.
Both `BuildCache` and `BuildCacheServiceFactory` should be able to use `ProviderFactory` so they can use something like `providers.environmentVariable`

### Current Behavior (optional)

There's no way to use `Property<T>` for `BuildCache` properties.
It is unclear how system environment variables should be passes to `BuildService`.

Adding a property causes the following failure:

```kotlin
abstract class AwsS3BuildCache : AbstractBuildCache() {
    abstract val sessionTokenProperty: Property<String>
}
```

```
Caused by: org.gradle.internal.service.UnknownServiceException: No service of type ObjectFactory available in default services.
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:304)
	at org.gradle.internal.instantiation.generator.ManagedObjectFactory.getObjectFactory(ManagedObjectFactory.java:132)
	at org.gradle.internal.instantiation.generator.ManagedObjectFactory.newInstance(ManagedObjectFactory.java:87)
	at com.github.burrunan.s3cache.AwsS3BuildCache_Decorated.getSessionTokenProperty(Unknown Source)
	at com.github.burrunan.s3cache.AwsS3BuildCache.setProp(AwsS3BuildCache.kt:43
```

My current `BuildCache` implementation uses `System.getenv(String)`, so it invalidates the configuration cache:

```kotlin
abstract class AwsS3BuildCache : AbstractBuildCache() {
    var awsAccessKeyId: String? = System.getenv("S3_BUILD_CACHE_ACCESS_KEY_ID")
    var awsSecretKey: String? = System.getenv("S3_BUILD_CACHE_SECRET_KEY")
    var sessionToken: String? = System.getenv("S3_BUILD_CACHE_SESSION_TOKEN")
    var awsProfile: String? = System.getenv("S3_BUILD_CACHE_PROFILE")
```

It looks like I should migrate to `providers.environmentVariable`, however, it is unclear how should I do so.

### Context

* https://github.com/burrunan/gradle-s3-build-cache/pull/74

**Comment by vlsi** [comment]
Closing, as the issue is present in 7.5, and it does not reproduce in 7.6.4+

**Comment by vlsi** [comment]
Closing as not planned
