### ISSUE TITLE
Eliminate potential deadlocks when writing CC fingerprint

### ISSUE THREAD

**Issue by mlopatkin** [gradle/gradle#30990]
Writing some CC fingerprint data may trigger another fingerprint event. This includes:
- processing a ValueSource (we store input parameters that can be providers)
- fingerprinting a FileCollection (may contain other file collections or providers), as part of task inputs or when observed by the user code

ValueSources are mostly mitigated now after we've made the fingerprint listener parallel. FileCollection deadlocks are hard to reproduce, but remain theoretically possible and may become an issue when we fingerprint more of them.

**Comment by mlopatkin** [comment]
It is still possible to have a deadlock because of the fingerprint writer lock:
```
Thread A: ValueSource obtained -> acquires writer lock -> starts writing -> triggers env var read -> tries to acquire broadcast lock
Thread B: reads env var -> acquires broadcast lock -> tries to acquire the writer lock
```

**Comment by bamboo** [comment]
> It is still possible to have a deadlock because of the fingerprint writer lock:
Can't we get rid of the writer lock completely via a queue?

**Comment by mlopatkin** [comment]
>Can't we get rid of the writer lock completely via a queue?

We may have to run user code when serializing (providers and serializables), so it isn't easy to offload (I suppose you're suggesting using a writer thread to handle the queue).

**Comment by abstratt** [comment]
I tried to imagine a test case with carefully placed sync points but my imagination is failing me. I was assuming project-specific serialization build operations (with parallel CC), with some sort of mutual dependency, but I guess that is not it. 

@mlopatkin  What are the threads mentioned here? https://github.com/gradle/gradle/issues/30990#issuecomment-2492159107

  ```
  Thread A: ValueSource obtained -> acquires writer lock -> starts writing -> triggers env var read -> tries to acquire broadcast lock
  Thread B: reads env var -> acquires broadcast lock -> tries to acquire the writer lock
  ```

EDIT: Ah, it is the fingerprinter listener that is parallel, and this may have nothing to do with parallel CC:

> ValueSources are mostly mitigated now after we've made the fingerprint listener parallel. FileCollection deadlocks are hard to reproduce, but remain theoretically possible and may become an issue when we fingerprint more of them.

**Comment by mlopatkin** [comment]
> I tried to imagine a test case with carefully placed sync points

This is annoying to test, as there is no control in interesting points. The thread B in the example must wait with the broadcast lock held before acquiring the writer lock, and there is no place to put user-supplied waiting code.

>What are the threads mentioned here?

Anything running at configuration phase, actually. Today it is either IP workers running project configuration or CC store workers serializing project tasks with Parallel CC.

**Comment by mlopatkin** [comment]
We did some investigations with @jvandort. Here are the findings:
- We might be able to get rid of the broadcast lock inside the ListenerManager. It mostly ensures that the event broadcasts are serialized, and all listeners receive events in the same order, when multiple threads do the broadcast. It isn't clear, how important this guarantee is, we managed to pass all the smoke tests without it. Note that even without it, no listener receives events concurrently unless annotated with `@ParallelListener`.
- If we think that the guarantee is important to keep in general, we may relax it for the listeners CC uses by converting them to `@StatefulListener`. They have weaker guarantees, though I'm not sure we document this properly.

CC also need re-enterable listeners, e.g. writing a ValueSource may trigger another ValueSource to be obtained. System property reads may also cause some non-trivial serialization, though both examples require rather convoluted set ups.

**Comment by mlopatkin** [comment]
An example deadlock with KMP (IP enabled):

<details>
<summary>Thread 1 (ValueSource.obtained -> [Writer lock] -> getenv -> blocked on InstrumentedListener lock) </summary>

```
	- parking to wait for  <0x0000000626682f18> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@21.0.4/LockSupport.java:221)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@21.0.4/AbstractQueuedSynchronizer.java:754)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@21.0.4/AbstractQueuedSynchronizer.java:990)
	at java.util.concurrent.locks.ReentrantLock$Sync.lock(java.base@21.0.4/ReentrantLock.java:153)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@21.0.4/ReentrantLock.java:322)
	at org.gradle.internal.event.DefaultListenerManager$ExclusiveEventBroadcast.startDispatch(DefaultListenerManager.java:473)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:395)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:382)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:92)
	at jdk.proxy3.$Proxy34.envVariableRead(jdk.proxy3/Unknown Source)
	at org.gradle.internal.cc.impl.InstrumentedInputAccessListener.envVariableQueried(InstrumentedInputAccessListener.kt:103)
	at org.gradle.internal.classpath.Instrumented.envVariableQueried(Instrumented.java:440)
	at org.gradle.internal.classpath.Instrumented.getenv(Instrumented.java:229)
	at org.jetbrains.kotlin.konan.util.DependencyDirectories.getLocalKonanDir(DependencyDirectories.kt:26)
	at org.jetbrains.kotlin.gradle.utils.NativeCompilerDownloader$Companion.getDefaultCompilerDirectory$kotlin_gradle_plugin_common(NativeCompilerDownloader.kt:69)
	at org.jetbrains.kotlin.gradle.internal.properties.NativePropertiesLoader$actualNativeHomeDirectory$3.call(NativeProperties.kt:115)
	at org.jetbrains.kotlin.gradle.internal.properties.NativePropertiesLoader$actualNativeHomeDirectory$3.call(NativeProperties.kt:114)
	at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:72)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateExecutionTimeValue(AbstractMinimalProvider.java:152)
	at org.gradle.api.internal.provider.OrElseProvider.calculateExecutionTimeValue(OrElseProvider.java:63)
	at org.gradle.api.internal.provider.OrElseProvider.calculateExecutionTimeValue(OrElseProvider.java:63)
	at org.gradle.api.internal.provider.BiProvider.isChangingValue(BiProvider.java:64)
	at org.gradle.api.internal.provider.BiProvider.calculateExecutionTimeValue(BiProvider.java:56)
	at org.gradle.internal.serialize.codecs.core.FixedValueReplacingProviderCodec.encodeProvider(ProviderCodecs.kt:94)
	at org.gradle.internal.serialize.codecs.core.ProviderCodec.encode(ProviderCodecs.kt:219)
	at org.gradle.internal.serialize.codecs.core.ProviderCodec.encode(ProviderCodecs.kt:213)
	at org.gradle.internal.serialize.graph.codecs.BindingsBackedCodec.encode(BindingsBackedCodec.kt:63)
	at org.gradle.internal.serialize.graph.DefaultWriteContext.write(Contexts.kt:95)
	at org.gradle.internal.serialize.graph.BeanPropertyExtensionsKt.writeNextProperty(BeanPropertyExtensions.kt:34)
	at org.gradle.internal.serialize.beans.services.BeanPropertyWriter.writeStateOf(BeanPropertyWriter.kt:54)
	at org.gradle.internal.serialize.graph.codecs.BeanCodec.writeBeanOf(BeanCodec.kt:57)
	at org.gradle.internal.serialize.graph.codecs.BeanCodec.encode(BeanCodec.kt:35)
	at org.gradle.internal.serialize.graph.CombinatorsKt$reentrant$1$encodeLoop$1.invokeSuspend(Combinators.kt:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at org.gradle.internal.serialize.graph.CombinatorsKt$reentrant$1.encodeLoop(Combinators.kt:101)
	at org.gradle.internal.serialize.graph.CombinatorsKt$reentrant$1.encode(Combinators.kt:68)
	at org.gradle.internal.serialize.graph.codecs.BindingsBackedCodec.encode(BindingsBackedCodec.kt:63)
	at org.gradle.internal.serialize.graph.DefaultWriteContext.write(Contexts.kt:95)
	at org.gradle.internal.cc.impl.fingerprint.ScopedFingerprintWriter$unsafeWrite$1.invokeSuspend(ScopedFingerprintWriter.kt:50)
	at org.gradle.internal.cc.impl.fingerprint.ScopedFingerprintWriter$unsafeWrite$1.invoke(ScopedFingerprintWriter.kt)
	at org.gradle.internal.cc.impl.fingerprint.ScopedFingerprintWriter$unsafeWrite$1.invoke(ScopedFingerprintWriter.kt)
	at org.gradle.internal.serialize.graph.RunningKt$runWriteOperation$1.invokeSuspend(Running.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at org.gradle.internal.serialize.graph.RunningKt.runToCompletion(Running.kt:54)
	at org.gradle.internal.serialize.graph.RunningKt.runWriteOperation(Running.kt:42)
	at org.gradle.internal.cc.impl.fingerprint.ScopedFingerprintWriter.unsafeWrite(ScopedFingerprintWriter.kt:49)
	at org.gradle.internal.cc.impl.fingerprint.ScopedFingerprintWriter.write(ScopedFingerprintWriter.kt:42)
	- locked <0x00000006266cc3c0> (a org.gradle.internal.serialize.graph.DefaultWriteContext)
	at org.gradle.internal.cc.impl.fingerprint.ConfigurationCacheFingerprintWriter$BuildScopedSink.write(ConfigurationCacheFingerprintWriter.kt:859)
	at org.gradle.internal.cc.impl.fingerprint.ConfigurationCacheFingerprintWriter.valueObtained(ConfigurationCacheFingerprintWriter.kt:454)
...
```
</details>

<details>
<summary>Thread 2 (fileSystemEntryObserved -> [InstrumentedListener lock] -> blocked on Writer lock)</summary>

```
"Build operations Thread 25" #1537 [1978939] prio=5 os_prio=0 cpu=75.77ms elapsed=328.84s tid=0x00007f94ec1aded0 nid=1978939 waiting for monitor entry  [0x00007fa437ffa000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.gradle.internal.cc.impl.fingerprint.ScopedFingerprintWriter.write(ScopedFingerprintWriter.kt:40)
	- waiting to lock <0x00000006266cc3c0> (a org.gradle.internal.serialize.graph.DefaultWriteContext)
	at org.gradle.internal.cc.impl.fingerprint.ConfigurationCacheFingerprintWriter$BuildScopedSink.write(ConfigurationCacheFingerprintWriter.kt:859)
	at org.gradle.internal.cc.impl.fingerprint.ConfigurationCacheFingerprintWriter$Sink.write$default(ConfigurationCacheFingerprintWriter.kt:841)
	at org.gradle.internal.cc.impl.fingerprint.ConfigurationCacheFingerprintWriter$Sink.captureFileSystemEntry(ConfigurationCacheFingerprintWriter.kt:826)
	at org.gradle.internal.cc.impl.fingerprint.ConfigurationCacheFingerprintWriter.fileSystemEntryObserved(ConfigurationCacheFingerprintWriter.kt:284)
	at java.lang.invoke.LambdaForm$DMH/0x00007fa46b4f8000.invokeInterface(java.base@21.0.4/LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/0x00007fa46b9f9c00.invoke(java.base@21.0.4/LambdaForm$MH)
	at java.lang.invoke.LambdaForm$MH/0x00007fa46b002800.invokeExact_MT(java.base@21.0.4/LambdaForm$MH)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.base@21.0.4/DirectMethodHandleAccessor.java:155)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(java.base@21.0.4/DirectMethodHandleAccessor.java:103)
	at java.lang.reflect.Method.invoke(java.base@21.0.4/Method.java:580)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:564)
	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:540)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:84)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:70)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:397)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:382)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:92)
	at jdk.proxy3.$Proxy34.fileSystemEntryObserved(jdk.proxy3/Unknown Source)
	at org.gradle.internal.cc.impl.InstrumentedInputAccessListener.fileSystemEntryObserved(InstrumentedInputAccessListener.kt:131)
	at org.gradle.internal.classpath.Instrumented.fileSystemEntryObserved(Instrumented.java:319)
	at org.gradle.internal.classpath.Instrumented.fileExists(Instrumented.java:323)
	at org.gradle.internal.classpath.declarations.FileInterceptorsDeclaration.intercept_exists(FileInterceptorsDeclaration.java:71)
	at org.jetbrains.kotlin.gradle.plugin.sources.android.checker.MultiplatformLayoutV2AndroidStyleSourceDirUsageChecker.checkCreatedSourceSet(MultiplatformLayoutV2AndroidStyleSourceDirUsageChecker.kt:31)
	at org.jetbrains.kotlin.gradle.plugin.sources.android.checker.CompositeKotlinAndroidSourceSetLayoutChecker.checkCreatedSourceSet(KotlinAndroidSourceSetLayoutChecker.kt:58)
	at org.jetbrains.kotlin.gradle.plugin.sources.android.KotlinAndroidSourceSetFactory.getOrCreateConfiguredKotlinSourceSet(KotlinAndroidSourceSetFactory.kt:33)
	at org.jetbrains.kotlin.gradle.plugin.sources.android.KotlinAndroidSourceSets$applyKotlinAndroidSourceSetLayout$2.execute(KotlinAndroidSourceSets.kt:46)
	at org.jetbrains.kotlin.gradle.plugin.sources.android.KotlinAndroidSourceSets$applyKotlinAndroidSourceSetLayout$2.execute(KotlinAndroidSourceSets.kt:40)
	at org.gradle.internal.code.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:124)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:110)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:107)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:185)
	at org.jetbrains.kotlin.gradle.plugin.sources.android.KotlinAndroidSourceSets.applyKotlinAndroidSourceSetLayout(KotlinAndroidSourceSets.kt:40)
	at org.jetbrains.kotlin.gradle.plugin.sources.android.KotlinAndroidSourceSets.applyKotlinAndroidSourceSetLayout$default(KotlinAndroidSourceSets.kt:20)
	at org.jetbrains.kotlin.gradle.plugin.AndroidProjectHandler.configureTarget(AndroidProjectHandler.kt:61)
	at org.jetbrains.kotlin.gradle.plugin.KotlinAndroidPlugin$Companion$dynamicallyApplyWhenAndroidPluginIsApplied$2$1.execute(KotlinAndroidPlugin.kt:64)
	at org.jetbrains.kotlin.gradle.plugin.KotlinAndroidPlugin$Companion$dynamicallyApplyWhenAndroidPluginIsApplied$2$1.execute(KotlinAndroidPlugin.kt:61)
	at org.gradle.internal.code.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:124)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:110)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:107)
	at org.gradle.api.internal.collections.CollectionFilter$1.execute(CollectionFilter.java:62)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:185)
	at org.gradle.api.internal.plugins.DefaultPluginContainer$2.execute(DefaultPluginContainer.java:163)
	at org.gradle.api.internal.plugins.DefaultPluginContainer$2.execute(DefaultPluginContainer.java:154)
	at org.gradle.internal.code.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:124)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:110)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:107)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:185)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.withId(DefaultPluginContainer.java:167)
	at org.jetbrains.kotlin.gradle.plugin.KotlinAndroidPlugin$Companion.dynamicallyApplyWhenAndroidPluginIsApplied$kotlin_gradle_plugin_common(KotlinAndroidPlugin.kt:61)
	at org.jetbrains.kotlin.gradle.plugin.KotlinAndroidPlugin$Companion.dynamicallyApplyWhenAndroidPluginIsApplied$kotlin_gradle_plugin_common$default(KotlinAndroidPlugin.kt:54)
	at org.jetbrains.kotlin.gradle.plugin.mpp.KotlinAndroidTargetPreset.createTargetInternal(KotlinAndroidTargetPreset.kt:40)
	at org.jetbrains.kotlin.gradle.plugin.mpp.KotlinAndroidTargetPreset.createTargetInternal(KotlinAndroidTargetPreset.kt:19)
	at org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtensionKt.configureOrCreate(KotlinMultiplatformExtension.kt:336)
	at org.jetbrains.kotlin.gradle.dsl.KotlinTargetContainerWithPresetFunctions$DefaultImpls.androidTarget(KotlinTargetContainerWithPresetFunctions.kt:44)
	at org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension.androidTarget(KotlinMultiplatformExtension.kt:30)
	at org.jetbrains.kotlin.gradle.dsl.KotlinTargetContainerWithPresetFunctions$DefaultImpls.androidTarget$default(KotlinTargetContainerWithPresetFunctions.kt:40)
...
```

</details>
