### ISSUE TITLE
A `Cached` instance created via `Cached.of()` is not safe to be used from multiple threads

### ISSUE THREAD

**Issue by abstratt** [gradle/gradle#31239]
### Issue type

Other

### Problem description

We use `Cached.of()` internally in the Gradle implementation to wrap computations performed by model objects that are safe for the configuration cache. When CC is not used, `Cached` work a lot like `Lazy.unsafe(...)`, however that is not documented as such. The symnptoms are that it does not honor its advertised at-most-once guarantees, and can fail with exceptiions due to race conditions. We should provide a version of `Cached` that is safe for multithreaded usage (even if at the expense of at-most-once semantics). 

### Context (optional)

Case in point:

```
 Caused by: java.lang.NullPointerException: Cannot invoke "java.util.concurrent.Callable.call()" because "failable" is null	
at org.gradle.internal.Try.ofFailable(Try.java:50)	
at org.gradle.internal.serialization.Cached$Deferred.lambda$tryComputation$0(Cached.java:65)	
at org.gradle.internal.evaluation.EvaluationContext.evaluate(EvaluationContext.java:91)	
at org.gradle.internal.serialization.Cached$Deferred.tryComputation(Cached.java:65)	
at org.gradle.internal.serialization.Cached$Deferred.result(Cached.java:56)	
at org.gradle.internal.serialization.Cached$Deferred.get(Cached.java:51)	
at org.gradle.internal.jvm.inspection.JvmInstallationMetadata$DefaultJvmInstallationMetadata.getCapabilities(JvmInstallationMetadata.java:245)	
at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.asToolchainOrThrow(JavaToolchainQueryService.java:242)	
at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.query(JavaToolchainQueryService.java:185)	
at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.lambda$resolveToolchain$1(JavaToolchainQueryService.java:170)	
at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.resolveToolchain(JavaToolchainQueryService.java:168)	
```

**Comment by abstratt** [comment]
Instead of making `Cached` thread-safe, we should change usages in the context of infrastructure to use `CalculatedValue` instead. Only model types should use `Cached`, and those AFAICT do not need to support multi-threaded scenarios.

Context: 

https://gradle.slack.com/archives/CH43P3A10/p1731354222903929?thread_ts=1731338178.627009&cid=CH43P3A10
