### ISSUE TITLE
Usage of `Cached` in `DefaultJvmInstallationMetadata.capabilities` is  not thread-safe

### ISSUE THREAD

**Issue by abstratt** [gradle/gradle#31242]
### Issue type

Polishing

### Problem description

`org.gradle.internal.serialization.Cached` is not meant for multi-threaded usage. It can only honor the at-most-once semantics if used from a single thread. Also, multi-threaded usage may lead to unexpected runtime exceptions (we have seen NPEs, though those have been addressed [here](https://github.com/gradle/gradle/pull/31240)).

For infrastructure data, `CalculatedValue` is preferred. `Cached` should be used for model types only. 

Related issue: https://github.com/gradle/gradle/issues/31239

### Context (optional)

Via @adammurdoch :

> If we're seeing a problem with the toolchains stuff not being thread-safe, then we should fix it rather than add work arounds to `Cached`.
Specifically, if we're seeing problems with DefaultJvmInstallationMetadata I would make the capabilities field eager, so that the object becomes data only. I don't see any real benefit in making that field lazy.

https://gradle.slack.com/archives/CH43P3A10/p1731353828772589?thread_ts=1731338178.627009&cid=CH43P3A10

**Comment by abstratt** [comment]
Example of an "unpredictable failure" (beware that [a workaround](https://github.com/gradle/gradle/pull/31240) was submitted for this, so it may no longer be reproducible by the time you try to reproduce it), triggered by this [line in this test case](https://github.com/gradle/gradle/blob/b0d78113593c1f12b7bb602baaf4bc202c984bde/platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r68/ParallelActionExecutionCrossVersionSpec.groovy#L60):

```
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.concurrent.Callable.call()" because "failable" is null	
at org.gradle.internal.Try.ofFailable(Try.java:50)	
at org.gradle.internal.serialization.Cached$Deferred.lambda$tryComputation$0(Cached.java:65)	
at org.gradle.internal.evaluation.EvaluationContext.evaluate(EvaluationContext.java:91)	
at org.gradle.internal.serialization.Cached$Deferred.tryComputation(Cached.java:65)	
at org.gradle.internal.serialization.Cached$Deferred.result(Cached.java:56)	
at org.gradle.internal.serialization.Cached$Deferred.get(Cached.java:51)	
at org.gradle.internal.jvm.inspection.JvmInstallationMetadata$DefaultJvmInstallationMetadata.getCapabilities(JvmInstallationMetadata.java:245)	
at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.asToolchainOrThrow(JavaToolchainQueryService.java:242)	
at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.query(JavaToolchainQueryService.java:185)	
at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.lambda$resolveToolchain$1(JavaToolchainQueryService.java:170)	
at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.resolveToolchain(JavaToolchainQueryService.java:168)	
at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.lambda$findMatchingToolchain$0(JavaToolchainQueryService.java:146)	
at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:73)	
at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:117)	
at org.gradle.api.internal.provider.WithSideEffectProvider.calculateOwnValue(WithSideEffectProvider.java:54)	
at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:117)	
at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:82)	
at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:117)	
at org.gradle.api.internal.provider.FlatMapProvider.calculateOwnValue(FlatMapProvider.java:54)	
at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:117)	
at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:82)	
at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:117)	
at org.gradle.api.internal.provider.AbstractMinimalProvider.withFinalValue(AbstractMinimalProvider.java:170)	
at org.gradle.api.internal.provider.DefaultProperty.finalValue(DefaultProperty.java:163)	
at org.gradle.api.internal.provider.DefaultProperty.finalValue(DefaultProperty.java:34)	
at org.gradle.api.internal.provider.AbstractProperty.finalizeNow(AbstractProperty.java:293)	
at org.gradle.api.internal.provider.AbstractProperty.lambda$beforeRead$0(AbstractProperty.java:288)	
at org.gradle.api.internal.provider.ValueState.finalizeOnReadIfNeeded(ValueState.java:140)	
at org.gradle.api.internal.provider.AbstractProperty.beforeRead(AbstractProperty.java:288)	
at org.gradle.api.internal.provider.AbstractProperty.beforeRead(AbstractProperty.java:280)	
at org.gradle.api.internal.provider.AbstractProperty.calculateOwnValue(AbstractProperty.java:163)	
at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:82)	
at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:102)	
at org.gradle.api.plugins.JavaBasePlugin.lambda$configureCompileDefaults$11(JavaBasePlugin.java:336)	
at org.gradle.api.plugins.internal.JvmPluginsHelper.computeSourceCompatibilityConvention(JvmPluginsHelper.java:188)	
at org.gradle.api.plugins.internal.JvmPluginsHelper.lambda$configureCompileDefaults$6(JvmPluginsHelper.java:183)	
at org.gradle.internal.UncheckedException.uncheckedCall(UncheckedException.java:103)	
at org.gradle.internal.extensibility.ConventionAwareHelper$2.doGetValue(ConventionAwareHelper.java:148)	
at org.gradle.internal.extensibility.ConventionAwareHelper$MappedPropertyImpl.getValue(ConventionAwareHelper.java:205)	
at org.gradle.internal.extensibility.ConventionAwareHelper.getConventionValue(ConventionAwareHelper.java:181)	
at org.gradle.api.plugins.internal.JvmPluginsHelper.computeTargetCompatibilityConvention(JvmPluginsHelper.java:194)	
at org.gradle.api.plugins.internal.JvmPluginsHelper.lambda$configureCompileDefaults$7(JvmPluginsHelper.java:184)	
at org.gradle.internal.UncheckedException.uncheckedCall(UncheckedException.java:103)	
at org.gradle.internal.extensibility.ConventionAwareHelper$2.doGetValue(ConventionAwareHelper.java:148)	
at org.gradle.internal.extensibility.ConventionAwareHelper$MappedPropertyImpl.getValue(ConventionAwareHelper.java:205)	
at org.gradle.internal.extensibility.ConventionAwareHelper.getConventionValue(ConventionAwareHelper.java:181)	
at org.gradle.api.plugins.jvm.internal.DefaultJvmLanguageUtilities.lambda$getDefaultTargetPlatform$2(DefaultJvmLanguageUtilities.java:101)	
at org.gradle.api.plugins.jvm.internal.DefaultJvmLanguageUtilities.getDefaultTargetPlatform(DefaultJvmLanguageUtilities.java:103)	
at org.gradle.api.plugins.jvm.internal.DefaultJvmLanguageUtilities.lambda$useDefaultTargetPlatformInference$1(DefaultJvmLanguageUtilities.java:68)	
at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:73)	
at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:82)	
at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:102)	
at org.gradle.api.internal.attributes.DefaultMutableAttributeContainer.lambda$realizeAllLazyAttributes$2(DefaultMutableAttributeContainer.java:210)	
at org.gradle.api.internal.attributes.DefaultMutableAttributeContainer.realizeAllLazyAttributes(DefaultMutableAttributeContainer.java:202)	
at org.gradle.api.internal.attributes.DefaultMutableAttributeContainer.asImmutable(DefaultMutableAttributeContainer.java:151)	
at org.gradle.api.internal.attributes.FreezableAttributeContainer.freeze(FreezableAttributeContainer.java:45)	
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.lambda$markAsObserved$8(DefaultConfiguration.java:1167)	
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.runActionInHierarchy(DefaultConfiguration.java:1188)	
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.markAsObserved(DefaultConfiguration.java:1165)	
at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveGraph(ShortCircuitEmptyConfigurationResolver.java:103)	
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$1.call(DefaultConfiguration.java:797)	
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$1.call(DefaultConfiguration.java:789)	
at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)	
at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)	
at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)	
at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)	
at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)	
at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)	
at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)	
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphInBuildOperation(DefaultConfiguration.java:789)	
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.lambda$resolveExclusivelyIfRequired$5(DefaultConfiguration.java:781)	
at org.gradle.api.internal.project.DefaultProjectStateRegistry$CalculatedModelValueImpl.update(DefaultProjectStateRegistry.java:509)	
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveExclusivelyIfRequired(DefaultConfiguration.java:776)	
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:769)	
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1100(DefaultConfiguration.java:158)	
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ResolverResultsResolutionResultProvider.getValue(DefaultConfiguration.java:743)	
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ResolverResultsResolutionResultProvider.getValue(DefaultConfiguration.java:704)	
at org.gradle.api.internal.artifacts.configurations.ResolutionResultProvider$1.getValue(ResolutionResultProvider.java:54)	
at org.gradle.api.internal.artifacts.configurations.ResolutionBackedFileCollection.getSelectedArtifacts(ResolutionBackedFileCollection.java:98)	
at org.gradle.api.internal.artifacts.configurations.ResolutionBackedFileCollection.visitContents(ResolutionBackedFileCollection.java:76)	
at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:360)	
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.visitContents(DefaultConfiguration.java:548)	
at org.gradle.api.internal.file.AbstractFileCollection.getFiles(AbstractFileCollection.java:123)	
at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:257)	
at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:198)	
at org.gradle.internal.metaobject.CompositeDynamicObject.tryGetProperty(CompositeDynamicObject.java:56)	
at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:60)	
at CustomBuilder.buildAll(/tmp/test-distribution6297373022231753500/rootDir/platforms/ide/tooling-api/build/tmp/teŝt files/ParallelAct.Spec/nested_acti.rent/g2frc/build.gradle:30)	
```
