### ISSUE TITLE
`FileLockCommunicator` is not compatible with macOS 15.1 firewall

### ISSUE THREAD

**Issue by joshfriend** [gradle/gradle#31245]
### Current Behavior

When running on macOS 15, gradle daemons are unable to send pings to each other inside `FileLockCommunicator`. The socket connections appear to be dropped by the `socketfilterfw`. Disabling firewall with `/usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off` makes things better. Adding the java executable used to run gradle to the firewall exceptions does not help.

### Expected Behavior

Gradle should function with macos firewall enabled.

### Context (optional)

Typically, having multiple daemons running is not an issue besides making things run slower overall. After updating to macOS 15 builds just break instead and developers are manually `kill -9`-ing daemons to unlock the caches.

### Self-contained Reproducer Project

Take any two gradle projects and open both at the same time to force lock contention in the daemons. One daemon will spit out:

```
Problems handling incoming cache access requests.
java.lang.RuntimeException: java.net.SocketException: Broken pipe
	at org.gradle.cache.internal.locklistener.FileLockCommunicator.confirmUnlockRequest(FileLockCommunicator.java:115)
	at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler$1.doRun(DefaultFileLockContentionHandler.java:135)
	at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler$1.run(DefaultFileLockContentionHandler.java:105)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.SocketException: Broken pipe
	at java.base/sun.nio.ch.DatagramChannelImpl.send0(Native Method)
	at java.base/sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:901)
	at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:863)
	at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:821)
	at java.base/sun.nio.ch.DatagramChannelImpl.blockingSend(DatagramChannelImpl.java:853)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.send(DatagramSocketAdaptor.java:218)
	at java.base/java.net.DatagramSocket.send(DatagramSocket.java:669)
	at org.gradle.cache.internal.locklistener.FileLockCommunicator.confirmUnlockRequest(FileLockCommunicator.java:112)
	... 7 more
```

but complete a sync in the IDE successfully. The other will eventually time out waiting for file locks because it cannot communicate with the other daemon:

```
> java.util.concurrent.ExecutionException: org.gradle.cache.LockTimeoutException: Timeout waiting to lock journal cache (/Users/jfriend/.gradle/caches/journal-1). It is currently in use by another Gradle instance.
  Owner PID: 3778
  Our PID: 3310
  Owner Operation: 
  Our operation: 
  Lock file: /Users/jfriend/.gradle/caches/journal-1/journal-1.lock
```

### Gradle version

8.6

### Your Environment (optional)

macOS 15.1
jdk 17
Gradle 8.6, have also seen the error in 8.8 and 8.10.2. Seems unspecific to gradle version

**Comment by joshfriend** [comment]
Of course immediately after I write this down, we discover that VPN software could also be the culprit

**Comment by ov7a** [comment]
Can someone confirm that macOs is indeed the culprit here?

Otherwise, since there is no clear indication that this is macOS-related, this issue will be closed in a week.

**Comment by kyeotic** [comment]
I can't confirm macOS is the culrpit, but on my team only the mac machines are running into this issue.

**Comment by joshfriend** [comment]
Going to close because at this point we are pretty sure it is a combination of Crowdstrike, Cloudflare WARP and macOS 15 fighting against each other. Will update later with any solutions we come up with

**Comment by ov7a** [comment]
> Going to close because at this point we are pretty sure it is a combination of Crowdstrike, Cloudflare WARP and macOS 15 fighting against each other. Will update later with any solutions we come up with

Thanks!

**Comment by ljacomet** [comment]
Re-opening as we discussed this recently. And there might be information for other users facing a similar issue.

@joshfriend Could you add more information that would help us reproduce and possibly improve the resilience of Gradle?

**Comment by joshfriend** [comment]
We discovered that Cloudflare WARP adds two loopback devices:
```
$ ifconfig lo0
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000
	inet6 ::1 prefixlen 128
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
	inet 127.0.2.2 netmask 0xff000000. # This one!
	inet 127.0.2.3 netmask 0xff000000. # and this one
	nd6 options=201<PERFORMNUD,DAD>
```

Gradle adds all of those as loopback interfaces:
https://github.com/gradle/gradle/blob/b2ef976169a05b3c76d04f0fa76a940859f96fa4/platforms/core-runtime/messaging/src/main/java/org/gradle/internal/remote/internal/inet/InetAddresses.java#L61-L63
```
2024-11-13T15:41:47.333-0500 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding IP addresses for network interface lo0
2024-11-13T15:41:47.333-0500 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Is this a loopback interface? true
2024-11-13T15:41:47.334-0500 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Ignoring remote address on loopback interface /fe80:0:0:0:0:0:0:1%lo0
2024-11-13T15:41:47.334-0500 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding loopback address /0:0:0:0:0:0:0:1%lo0
2024-11-13T15:41:47.334-0500 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding loopback address /127.0.2.3
2024-11-13T15:41:47.334-0500 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding loopback address /127.0.2.2
2024-11-13T15:41:47.334-0500 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding loopback address /127.0.0.1
```

When a gradle daemon pings another daemon who owns a lock, the lock-holder does receive the ping, releases the lock, and attempts to reply back to the requesting daemon, but that fails with the `SocketException: broken pipe` error. The requesting daemon never hears a reply and eventually times out waiting for the lock to be released. In pcaps we can see that the reply packet is missing.

The issue should be replicable without having to install crowdstrike/warp by adding dummy loopbacks:

```
sudo ifconfig lo0 alias 127.0.2.2/8 up
sudo ifconfig lo0 alias 127.0.2.3/8 up
# or to remove:
# sudo ifconfig lo0 -alias 127.0.2.2
# sudo ifconfig lo0 -alias 127.0.2.3
```

We have tested the following scenarios with the macOS firewall enabled:
Crowdstrike on / Warp on = 🔴 
SentinelOne on / Warp on = 🔴 
SentinelOne on / Warp off = 🟢 
Crowdstrike on / Warp off = 🟢 
MalwareBytes on / Warp on = 🟢 

The most recent macOS update (15.1.1) and the latest agent updates for crowdstrike/sentinelone also do not fix the issue.

While this problem is not caused by Gradle, it seems that there is more resiliency that could be added. Gradle is currently adding the loopback addresses in the reverse order which they appear in `ifconfig`. `127.0.0.1` is the correct/working address, but gradle tries using `127.0.2.3` first, which does not work, and then gives up because the broken pipe error is not a known recoverable error to `FileLockCommunicator`:

https://github.com/gradle/gradle/blob/master/platforms/core-execution/persistent-cache/src/main/java/org/gradle/cache/internal/locklistener/FileLockCommunicator.java#L64-L68

**Comment by reinsch82** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by joshfriend** [comment]
We have found that disabling crowdstrike network filtering helps: `sudo /Applications/Falcon.app/Contents/Resources/falconctl disable-filter`. This is different from the "Falcon Firewall" product that crowdstrike also sells. 

Also sentinelone users can disable network extensions in macOS to alleviate the issue.

I added some additional logging to gradle to try to get more visibility into what is going on and while I don't have a solution that i could fix in gradle itself yet, here's what I've observed:

In daemon1 (whose build failed), the lock holder receives a ping from another daemon(2) and attempts to release the lock and inform daemon2 that the lock is released:
```
Starting Gradle Daemon...
Gradle Daemon started in 715 ms
Confirming unlock request at address /[0:0:0:0:0:0:0:1]:58217 for lock with id 1187920257040917023.
Confirming unlock request at address /127.0.0.1:58217 for lock with id 1187920257040917023.
Confirming lock release to Gradle process at address /[0:0:0:0:0:0:0:1]:58217 for lock with id 1187920257040917023.
Confirming lock release to Gradle process at address /127.0.0.1:58217 for lock with id 1187920257040917023.
Confirming unlock request at address /[0:0:0:0:0:0:0:1]:58217 for lock with id 4839816992345571465.
Confirming unlock request at address /127.0.2.4:58217 for lock with id 4839816992345571465.
Confirming lock release to Gradle process at address /[0:0:0:0:0:0:0:1]:58217 for lock with id 4839816992345571465.
Confirming lock release to Gradle process at address /127.0.2.4:58217 for lock with id 4839816992345571465.
Failed to confirm lock release to Gradle process at address /127.0.2.4:58217 for lock with id 4839816992345571465.
Problems handling incoming cache access requests.
java.lang.RuntimeException: java.net.SocketException: Broken pipe
```

It looks odd that gradle tries to reply back on both the ipv6 and ipv4 address, and that sometimes it uses one of the other loopback addresses.

In daemon2 (whose build passed) i just see a lot of logs like the following:
```
Starting Gradle Daemon...
Gradle Daemon started in 711 ms
Confirming unlock request at address /[0:0:0:0:0:0:0:1]:64283 for lock with id -6736320527874091085.
Confirming lock release to Gradle process at address /[0:0:0:0:0:0:0:1]:64283 for lock with id -6736320527874091085.
Confirming unlock request at address /[0:0:0:0:0:0:0:1]:64283 for lock with id -8279814339630415312.
Confirming lock release to Gradle process at address /[0:0:0:0:0:0:0:1]:64283 for lock with id -8279814339630415312.
Confirming unlock request at address /[0:0:0:0:0:0:0:1]:64283 for lock with id 1324168725312544943.
Confirming unlock request at address /[0:0:0:0:0:0:0:1]:58217 for lock with id 1324168725312544943.
Confirming lock release to Gradle process at address /[0:0:0:0:0:0:0:1]:64283 for lock with id 1324168725312544943.
Confirming lock release to Gradle process at address /[0:0:0:0:0:0:0:1]:58217 for lock with id 1324168725312544943.
Confirming unlock request at address /[0:0:0:0:0:0:0:1]:58217 for lock with id -4356291681721494765.
Confirming lock release to Gradle process at address /[0:0:0:0:0:0:0:1]:58217 for lock with id -4356291681721494765.
```

I also started daemon3 (whose build passed), whose logs are similar to daemon2 but there are mixed ipv4 and ipv6 addresses in the mix:
```
Starting Gradle Daemon...
Gradle Daemon started in 762 ms
Confirming unlock request at address /[0:0:0:0:0:0:0:1]:49915 for lock with id 671124401958403567.
Confirming lock release to Gradle process at address /[0:0:0:0:0:0:0:1]:49915 for lock with id 671124401958403567.
Confirming unlock request at address /[0:0:0:0:0:0:0:1]:49915 for lock with id 5921326000204650665.
Confirming lock release to Gradle process at address /[0:0:0:0:0:0:0:1]:49915 for lock with id 5921326000204650665.
Confirming unlock request at address /[0:0:0:0:0:0:0:1]:64283 for lock with id -1631868104486139816.
Confirming lock release to Gradle process at address /[0:0:0:0:0:0:0:1]:64283 for lock with id -1631868104486139816.
Confirming unlock request at address /[0:0:0:0:0:0:0:1]:49915 for lock with id 3060333317883234944.
Confirming unlock request at address /127.0.0.1:49915 for lock with id 3060333317883234944.
Confirming lock release to Gradle process at address /[0:0:0:0:0:0:0:1]:49915 for lock with id 3060333317883234944.
Confirming lock release to Gradle process at address /127.0.0.1:49915 for lock with id 3060333317883234944.
Confirming unlock request at address /[0:0:0:0:0:0:0:1]:49915 for lock with id 8410635804195944506.
Confirming unlock request at address /127.0.0.1:49915 for lock with id 8410635804195944506.
Confirming lock release to Gradle process at address /[0:0:0:0:0:0:0:1]:49915 for lock with id 8410635804195944506.
Confirming lock release to Gradle process at address /127.0.0.1:49915 for lock with id 8410635804195944506.
```

**Comment by joshfriend** [comment]
@big-guy created a simple java app that emulates and reproduces the lock communication issues. 

```java
package org.gradle.sample;

import java.io.IOException;
import java.net.*;
import java.util.ArrayList;
import java.util.List;

public class CommunicationTest {
    public static void main(String... args) throws IOException {
        final DatagramSocket serverSocket = new DatagramSocket(0);
        // Listening thread, represents the daemon with the lock
        new Thread(() -> {
            // create a datagram socket that's listening on the wildcard address
            // and a random port
            try (serverSocket) {
                // create a datagram packet to receive the incoming data
                while (true) {
                    byte[] buffer = new byte["echo".getBytes().length];
                    DatagramPacket packet = new DatagramPacket(buffer, buffer.length);

                    try {
                        // receive the incoming data
                        serverSocket.receive(packet);
                        // print the received data
                        System.out.println("receive " + new String(packet.getData(), 0, packet.getLength()) + " <- " + packet.getAddress());
                    } catch (IOException e) {
                        System.out.println("could not receive? " + e.getMessage());
                        continue;
                    }

                    // echo it back
                    try {
//                        byte[] address = packet.getAddress().getAddress();
//                        if (address.length == 4 && address[3] == 3) {
//                            // don't reply
//                            continue;
//                        }
                        serverSocket.send(new DatagramPacket(packet.getData(), packet.getLength(), packet.getAddress(), packet.getPort()));
                    } catch (IOException e) {
                        System.out.println("could not send to " + packet.getAddress() + " " + e.getMessage());
                        e.printStackTrace();
                    }
                }
            }
        }).start();

        List<InetAddress> addresses = findAddresses();

        try {
            try (DatagramSocket socket = new DatagramSocket(0)) {
                socket.setSoTimeout(5000);

                for (int i = 0; i < 5; i++) {
                    System.out.println("iteration " + i);
                    byte[] buffer = "echo".getBytes();
                    for (InetAddress address : addresses) {
                        DatagramPacket packet = new DatagramPacket(buffer, buffer.length);
                        packet.setAddress(address);
                        packet.setPort(serverSocket.getLocalPort());
                        System.out.println("send echo -> " + address);
                        socket.send(packet);

                        byte[] responseBuffer = new byte[buffer.length];
                        DatagramPacket responsePacket = new DatagramPacket(responseBuffer, responseBuffer.length);
                        socket.receive(responsePacket);
                        System.out.println("confirm " + new String(responsePacket.getData(), 0, responsePacket.getLength()) + " <- " + responsePacket.getAddress());
                    }
                }
            }
        } finally {
            System.exit(0);
        }
    }

    static List<InetAddress> findAddresses() throws SocketException {
        List<InetAddress> interfaces = new ArrayList<>();
        NetworkInterface.getNetworkInterfaces().asIterator().forEachRemaining(networkInterface -> {
            System.out.println("Adding IP addresses for network interface " + networkInterface.getDisplayName());
            try {
                boolean isLoopbackInterface = networkInterface.isLoopback();
                System.out.println("Is this a loopback interface? " + isLoopbackInterface);

                networkInterface.getInetAddresses().asIterator().forEachRemaining(candidate -> {
                    if (isLoopbackInterface) {
                        if (candidate.isLoopbackAddress()) {
                            System.out.println("Adding loopback address " + candidate);
                            interfaces.add(candidate);
                        }
                    }
                });
            } catch (SocketException e) {
                System.out.println("Failed to analyze network interface " + networkInterface.getDisplayName());
            }
        });
        return interfaces;
    }
}
```

**Comment by GabeK0** [comment]
+1, this recently started happening to us on the Android team at Ramp, specifically after we updated to macOS 15. Disabling Cloudflare WARP indeed fixes the issue as a temporary workaround!

**Comment by monosoul** [comment]
This affects me and my colleagues as well. MacOS 15.2, Gradle 8.12 and we use WARP too.

**Comment by xtr0nx** [comment]
We've tried the following gradle settings:

```
# ~/.gradle/gradle.properties
systemProp.java.net.preferIPv4Stack=true
org.gradle.daemon.host=127.0.0.1
```

As well as excluding the following CIDRs in the Split Tunnels configuration:

* `127.0.0.0/8`
* `::1/128`

But that didn't appear to work either. I'm about to file a support ticket with Cloudflare.

**Comment by ajaiswal595** [comment]
I'm using macbook 
2.3 GHz 8-Core Intel Core i9
Sonoma 14.7 (23H124)

Disabling the firewall doesn't help.

**Comment by pts-danielmanley** [comment]
I've got MacOS 15.2 and our company uses FortiClient VPN and we're also experiencing problems when the VPN is engaged. This is the error we're getting:
```
FAILURE: Build failed with an exception.

* What went wrong:
Gradle could not start your build.
> Cannot create service of type BuildSessionActionExecutor using method LauncherServices$ToolingBuildSessionScopeServices.createActionExecutor() as there is a problem with parameter #21 of type BuildLifecycleAwareVirtualFileSystem.
   > Cannot create service of type BuildLifecycleAwareVirtualFileSystem using method VirtualFileSystemServices$GradleUserHomeServices.createVirtualFileSystem() as there is a problem with parameter #1 of type FileWatchingFilter.
      > Cannot create service of type FileWatchingFilter using method VirtualFileSystemServices$GradleUserHomeServices.createFileWatchingFilter() as there is a problem with parameter #1 of type GlobalCacheLocations.
         > Cannot create service of type GlobalCacheLocations using method GradleUserHomeScopeServices.createGlobalCacheLocations() as there is a problem with parameter #1 of type List<GlobalCache>.
            > Could not create service of type FileAccessTimeJournal using GradleUserHomeScopeServices.createFileAccessTimeJournal().
               > newPosition > limit: (312 > 10)
```

**Comment by joshfriend** [comment]
@pts-danielmanley your problem looks unrelated to this, try filing a separate issue

**Comment by ljacomet** [comment]
Anyone experiencing this issue, could you try with version `8.12.1-milestone-1` and report?

**Comment by monosoul** [comment]
Tried it out with a build where I was consistently getting `java.net.SocketException: Broken pipe` before, works fine now with `8.12.1-milestone-1`

**Comment by joshfriend** [comment]
The 8.12.1-milestone-1 build seems to resolve the issue for me (I'm testing with SentinelOne). I also kept one project at 8.12 and the different lock communicator versions seem to play nicely with each other. I was still unable to duplicate the issue even with older daemons in the mix. To test, I clicked sync on multiple projects rapidly and it didn't seem to matter what order i clicked sync on the 8.12 build, it worked whether it was first or last.

**Comment by big-guy** [comment]
@joshfriend yep, I would expect that new->new, old->new or new->old would be OK.  We made changes that prevent Gradle from using the "bad" loopback addresses, so new daemons do not try to communicate with old daemons on the bad addresses. We also made changes so that if the old daemons communicate over the bad loopback addresses and the new daemons run into problems, Gradle ignores the failures and keeps going. As long as one of the communication addresses works between old and new, lock sharing will keep working.

What isn't fixed is if you have 3 daemons, 2 old and 1 new.  If a lock is held by the old daemon and the other old daemon requests it, the first old daemon can be put into a bad state where it will not release locks or respond to requests.  Even if the new daemon comes along, it will timeout waiting for the original old daemon. 

This is a pick your poison problem:
- Ask for a lock and timeout if the owner fails to respond
- Ask for a lock and assume its released if the owner fails to respond

The danger is that the other daemon can still be doing work and using the lock, but we just can't tell. 

I would expect that if you reproduce the problem with an old version and then switch to the new version, you'll still see a timeout as long as the old daemon is running.

**Comment by joshfriend** [comment]
[macOS 15.3 release notes for enterprise](https://support.apple.com/en-us/121011) includes (as 15.2 also did) this point:

> Improves stability for apps over VPN connections when using the built-in firewall and a content filter extension.

I tested the `CommunicationTest` class above and my usual reproducer of opening and syncing multiple projects at once, and both were unable to reproduce the issue.
