### ISSUE TITLE
ArrayIndexOutOfBoundsException after upgrading to gradle 8.11 when generating problems report

### ISSUE THREAD

**Issue by staktrace** [gradle/gradle#31284]
### Current Behavior

We have a build that does a bunch of publishing to an internal Artifactory instance. The build mostly runs fine but then fails with an ArrayIndexOfOutOfBoundsException internally in gradle. Stack below (in screenshot form because build scans are impossble to copy out of)

![Image](https://github.com/user-attachments/assets/32af3c65-f9bc-4427-b1ab-d9ee88fdcf02)
![Image](https://github.com/user-attachments/assets/318b478c-a41c-4d31-b263-aeceda1e6b57)

### Expected Behavior

No exception should be thrown, and it shouldn't fail the build

### Self-contained Reproducer Project

Don't really have one but hopefully the stack is enough

### Gradle version

8.11

**Comment by staktrace** [comment]
Ah I figured out how to paste it without HTML tags:

```
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 39 out of bounds for byte[34]
at org.gradle.internal.problems.failure.FailurePrinter$Job.printRecursively(FailurePrinter.java:69)	
at org.gradle.internal.problems.failure.FailurePrinter$Job.print(FailurePrinter.java:59)	
at org.gradle.internal.problems.failure.FailurePrinter.print(FailurePrinter.java:42)	
at org.gradle.internal.configuration.problems.FailureDecorator.partitionedTraceFor(DecoratedReportProblem.kt:182)	
at org.gradle.internal.configuration.problems.FailureDecorator.decorate(DecoratedReportProblem.kt:174)	
at org.gradle.internal.configuration.problems.CommonReport.decoratedFailureFor(CommonReport.kt:309)	
at org.gradle.internal.configuration.problems.CommonReport.decorateProblem(CommonReport.kt:299)	
at org.gradle.internal.configuration.problems.CommonReport.onPropertyProblem(CommonReport.kt:351)	
at org.gradle.internal.configuration.problems.CommonReport.onIncompatibleTask(CommonReport.kt:340)	
at org.gradle.internal.cc.impl.problems.ConfigurationCacheProblems.onIncompatibleTask(ConfigurationCacheProblems.kt:243)	
at org.gradle.internal.cc.impl.problems.ConfigurationCacheProblems.reportIncompatibleTask(ConfigurationCacheProblems.kt:180)	
at org.gradle.internal.cc.impl.problems.ConfigurationCacheProblems.forIncompatibleTask(ConfigurationCacheProblems.kt:154)	
at org.gradle.internal.serialize.graph.AbstractIsolateContext.forIncompatibleTask$suspendImpl(Contexts.kt:370)	
at org.gradle.internal.serialize.graph.AbstractIsolateContext.forIncompatibleTask(Contexts.kt)	
at org.gradle.internal.serialize.codecs.core.TaskNodeCodecKt.withTaskOf(TaskNodeCodec.kt:238)	
at org.gradle.internal.serialize.codecs.core.TaskNodeCodecKt.access$withTaskOf(TaskNodeCodec.kt:1)	
at org.gradle.internal.serialize.codecs.core.TaskNodeCodec.writeTask(TaskNodeCodec.kt:97)	
at org.gradle.internal.serialize.codecs.core.TaskNodeCodec.encode(TaskNodeCodec.kt:75)	
at org.gradle.internal.serialize.codecs.core.TaskNodeCodec.encode(TaskNodeCodec.kt:68)	
at org.gradle.internal.serialize.graph.codecs.BindingsBackedCodec.encode(BindingsBackedCodec.kt:63)	
at org.gradle.internal.serialize.graph.DefaultWriteContext.write(Contexts.kt:95)	
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$writeGroupedNodes$1$1$1.invokeSuspend(WorkNodeCodec.kt:327)	
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$writeGroupedNodes$1$1$1.invoke(WorkNodeCodec.kt)	
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$writeGroupedNodes$1$1$1.invoke(WorkNodeCodec.kt)	
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$safeRunnerFor$2$1$1.invokeSuspend(WorkNodeCodec.kt:395)	
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$safeRunnerFor$2$1$1.invoke(WorkNodeCodec.kt)	
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$safeRunnerFor$2$1$1.invoke(WorkNodeCodec.kt)	
at org.gradle.internal.serialize.graph.RunningKt$runWriteOperation$1.invokeSuspend(Running.kt:43)	
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)	
at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)	
at org.gradle.internal.serialize.graph.RunningKt.runToCompletion(Running.kt:54)	
at org.gradle.internal.serialize.graph.RunningKt.runWriteOperation(Running.kt:42)	
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$safeRunnerFor$2$1.accept(WorkNodeCodec.kt:394)	
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$safeRunnerFor$2$1.accept(WorkNodeCodec.kt:393)	
at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.lambda$applyToMutableState$1(DefaultProjectStateRegistry.java:411)	
at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.lambda$fromMutableState$2(DefaultProjectStateRegistry.java:434)	
at org.gradle.internal.work.DefaultWorkerLeaseService.withReplacedLocks(DefaultWorkerLeaseService.java:359)	
at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.fromMutableState(DefaultProjectStateRegistry.java:434)	
at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.applyToMutableState(DefaultProjectStateRegistry.java:410)	
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$safeRunnerFor$2.invokeSuspend(WorkNodeCodec.kt:393)	
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$safeRunnerFor$2.invoke(WorkNodeCodec.kt)	
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$safeRunnerFor$2.invoke(WorkNodeCodec.kt)	
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$writeGroupedNodes$1.invokeSuspend(WorkNodeCodec.kt:326)	
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$writeGroupedNodes$1.invoke(WorkNodeCodec.kt)	
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$writeGroupedNodes$1.invoke(WorkNodeCodec.kt)	
at org.gradle.internal.serialize.graph.RunningKt$runWriteOperation$1.invokeSuspend(Running.kt:43)	
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)	
at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)	
at org.gradle.internal.serialize.graph.RunningKt.runToCompletion(Running.kt:54)	
at org.gradle.internal.serialize.graph.RunningKt.runWriteOperation(Running.kt:42)	
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec.writeGroupedNodes(WorkNodeCodec.kt:322)	
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec.access$writeGroupedNodes(WorkNodeCodec.kt:81)	
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$writeNodes$2$1$1.invoke(WorkNodeCodec.kt:220)	
at org.gradle.internal.serialize.codecs.core.WorkNodeCodec$writeNodes$2$1$1.invoke(WorkNodeCodec.kt:218)	
at org.gradle.internal.serialize.codecs.core.WorkNodeCodecKt$asBuildOperation$1.run(WorkNodeCodec.kt:634)	
at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)	
at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)	
at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)	
at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)	
at org.gradle.internal.operations.DefaultBuildOperationExecutor$QueueWorker.execute(DefaultBuildOperationExecutor.java:161)	
at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runOperation(DefaultBuildOperationQueue.java:272)	
at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.doRunBatch(DefaultBuildOperationQueue.java:253)	
at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.lambda$runBatch$1(DefaultBuildOperationQueue.java:226)	
at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:263)	
at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:127)	
at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runBatch(DefaultBuildOperationQueue.java:224)	
at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.run(DefaultBuildOperationQueue.java:192)	
at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)	
at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)	
```

**Comment by staktrace** [comment]
This might actually be related to the 
```
org.gradle.configuration-cache.parallel=true
```
flag we just turned on. Will try turning it off and see what happens.

Also for context this happening at the tail end of our main branch CI pipeline and it's a bit hard to reproduce the exact scenario on a local machine or anywhere else really.

**Comment by staktrace** [comment]
There are also other failures. Similar-sounding errors, slightly different failures:

 ![Image](https://github.com/user-attachments/assets/83037d68-396e-4ace-8a77-7af3bad0eebc)

**Comment by alllex** [comment]
This is a bug that is caused by having parallel CC enabled and also having CC-related "problems" in the build that are reported concurrently. 

In this case, it appears that you have a number of CC-incompatible tasks. Those are reported as "problems" so they are included in the CC report. With Parallel CC enabled, the processing of tasks in different subprojects happens concurrently and they race for being reported.

We will address this in a patch release. Turning off parallel CC should avoid the problem.

**Comment by alllex** [comment]
Fixed by https://github.com/gradle/gradle/pull/31286

**Comment by abigalegeathers** [comment]
功aeき![image](https://github.com/user-attachments/assets/c83aee0e-22d4-4452-97a9-4b19ed4e8558)
