### ISSUE TITLE
Improve stacktrace/messaging for Property::disallowUnsafeRead

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#31381]
### Expected Behavior

Given a violation of `Property::disallowUnsafeRead` the class and property name should be printed, maybe something like

```
java.lang.IllegalStateException: Cannot query the value of 'FooExtension.bar' property because configuration of root project 'test' has not completed yet.
```

### Current Behavior (optional)

```
java.lang.IllegalStateException: Cannot query the value of this property because configuration of root project 'test' has not completed yet.
	at org.gradle.api.internal.provider.ValueState$NonFinalizedValue.maybeFinalizeOnRead(ValueState.java:203)
	at org.gradle.api.internal.provider.ValueState.finalizeOnReadIfNeeded(ValueState.java:138)
	at org.gradle.api.internal.provider.AbstractProperty.beforeRead(AbstractProperty.java:276)
	at org.gradle.api.internal.provider.AbstractProperty.beforeRead(AbstractProperty.java:268)
	at org.gradle.api.internal.provider.AbstractProperty.calculateOwnValue(AbstractProperty.java:162)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:80)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:100)
	at com.xenoterracide.gradle.semver.SemverPluginTest.apply(SemverPluginTest.java:42)
```

### Context

this message was only useful because I just decided to finalize on read instead since it's partially caused by me not knowing how to finish configuring `Project` built by `ProjectBuilder`. It's possible that I couldn't use this settings anyways. Of the dozen properties that I set this on, which one was it?

**Comment by ov7a** [comment]
This feature request is in the backlog of the relevant team and is prioritized by them.
