### ISSUE TITLE
AccessDeniedException when using Kotlin JVM plugin on Windows: Could not move temporary workspace to immutable location

### ISSUE THREAD

**Issue by mrozanc** [gradle/gradle#31392]
### Current Behavior

All tasks execution fail on any project, two different computers, on projects that where working before without any change.

The `./gradlew clean --debug --stacktrace` command generates this output:
[output-log.txt](https://github.com/user-attachments/files/17882644/output-log.txt)

The main message is:
```
Calculating task graph as no cached configuration is available for tasks: clean

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':lib'.
> Multiple build operations failed.
      Could not move temporary workspace (C:\Users\marc\.gradle\caches\8.11.1\transforms\578ca4cb36bb26d07c14919c1eb98721-ba8b6336-04b0-4f55-9099-6addaf0bb6f7) to immutable location (C:\Users\marc\.gradle\caches\8.11.1\transforms\578ca4cb36bb26d07c14919c1eb98721)
      Could not move temporary workspace (C:\Users\marc\.gradle\caches\8.11.1\transforms\cbd3de25a72ce9fcaf8b72e99052c79e-a073bcef-7f0a-4d37-a093-4dd68a667509) to immutable location (C:\Users\marc\.gradle\caches\8.11.1\transforms\cbd3de25a72ce9fcaf8b72e99052c79e)
   > Could not move temporary workspace (C:\Users\marc\.gradle\caches\8.11.1\transforms\578ca4cb36bb26d07c14919c1eb98721-ba8b6336-04b0-4f55-9099-6addaf0bb6f7) to immutable location (C:\Users\marc\.gradle\caches\8.11.1\transforms\578ca4cb36bb26d07c14919c1eb98721)
   > Could not move temporary workspace (C:\Users\marc\.gradle\caches\8.11.1\transforms\cbd3de25a72ce9fcaf8b72e99052c79e-a073bcef-7f0a-4d37-a093-4dd68a667509) to immutable location (C:\Users\marc\.gradle\caches\8.11.1\transforms\cbd3de25a72ce9fcaf8b72e99052c79e)
```

The stacktrace points to an `AccessDeniedException` when moving files:
```
Caused by: java.nio.file.AccessDeniedException: C:\Users\marc\.gradle\caches\8.11.1\transforms\861004acddba2701e93ae76fc6f706a8-770f8cf9-a2e1-495f-98f1-b5b0a064985f -> C:\Users\marc\.gradle\caches\8.11.1\transforms\861004acddba2701e93ae76fc6f706a8
        at org.gradle.internal.vfs.impl.DefaultFileSystemAccess.lambda$moveAtomically$13(DefaultFileSystemAccess.java:229)
        at org.gradle.internal.vfs.impl.DefaultFileSystemAccess.write(DefaultFileSystemAccess.java:217)
        at org.gradle.internal.vfs.impl.DefaultFileSystemAccess.moveAtomically(DefaultFileSystemAccess.java:228)
        at org.gradle.internal.execution.steps.AssignImmutableWorkspaceStep$WorkspaceMoveHandler.executeMoveOr(AssignImmutableWorkspaceStep.java:273)
        ... 61 more
```

The bug happened on different Gradle versions I tested: `8.10.2`, `8.11`, `8.11.1`.

It happens only:
- On Windows (tested on Windows 11), but not when using WSL on the exact same project.
- When the `[org.jetbrains.kotlin.jvm](https://plugins.gradle.org/plugin/org.jetbrains.kotlin.jvm)` plugin is applied (tested with versions 1.9.25, 2.0.20, 2.0.21)

It may be related to: https://github.com/gradle/gradle/issues/28475 and I don't think I'm the only person having this problem: https://github.com/facebook/react-native/issues/47692

### Expected Behavior

I can execute any task without facing those "Could not move temporary workspace to immutable location" errors.

### Self-contained Reproducer Project

Just generate a new project with gradle init:
```
❯ gradle --version

------------------------------------------------------------
Gradle 8.11.1
------------------------------------------------------------

Build time:    2024-11-20 16:56:46 UTC
Revision:      481cb05a490e0ef9f8620f7873b83bd8a72e7c39

Kotlin:        2.0.20
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.14 compiled on August 16 2023
Launcher JVM:  21.0.5 (Eclipse Adoptium 21.0.5+11-LTS)
Daemon JVM:    C:\Users\marc\scoop\apps\temurin21-jdk\current (no JDK specified, using current Java home)
OS:            Windows 11 10.0 amd64

❯ gradle init --type kotlin-library --dsl kotlin --project-name test-project --java-version 21

Select test framework:
  1: kotlin.test
  2: JUnit Jupiter
Enter selection (default: kotlin.test) [1..2] 1

Generate build using new APIs and behavior (some features may change in the next minor release)? (default: no) [yes, no] no


> Task :init
Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.11.1/samples/sample_building_kotlin_libraries.html

BUILD SUCCESSFUL in 7s
1 actionable task: 1 executed
```

The one I generated:
[test-project.zip](https://github.com/user-attachments/files/17882727/test-project.zip)

### Gradle version

8.11.1

### Build scan URL (optional)

https://scans.gradle.com/s/n2x27z75sirtw

### Your Environment (optional)

```
❯ gradle --version

------------------------------------------------------------
Gradle 8.11.1
------------------------------------------------------------

Build time:    2024-11-20 16:56:46 UTC
Revision:      481cb05a490e0ef9f8620f7873b83bd8a72e7c39

Kotlin:        2.0.20
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.14 compiled on August 16 2023
Launcher JVM:  21.0.5 (Eclipse Adoptium 21.0.5+11-LTS)
Daemon JVM:    C:\Users\marc\scoop\apps\temurin21-jdk\current (no JDK specified, using current Java home)
OS:            Windows 11 10.0 amd64         Windows 11 10.0 amd64
```

Noticed this issue on all my Kotlin projects since 2024-11-22, on 2 different computers on Windows 11, so it may be something that changed on Windows. I keep my OS up-to-date:

```
Edition: Windows 11 Professionnel
Version: 23H2
Build: 22631.4317
Experience: Windows Feature Experience Pack 1000.22700.1041.0
```

I also had the exact same error running Gradle with the last Temurin JDK 11.

**Comment by mrozanc** [comment]
I noticed that the `$HOME/.gradle\caches\8.11.1\transforms\<id1>-<id2>` folders are moved to `$HOME/.gradle\caches\8.11.1\transforms\<id1>`.

After I have the error, if I look into the transforms folder, I find many `<id1>-<id2>` folders having the same `<id1>` I got in the exception.

If I rename myself one `<id1>-<id2>` folder to `<id1>` and relaunch the build, it continues until it fails on another different `<id1>`. I repeat the operation again for different ids and finally the build no longer blocked.

I guess the problem is that there are many `<id1>-<id2>` folders that concur to be moved to `<id1>` and they conflict with each others.

What confuses me the most is that it happens with different versions of Gradle that were working fine before.

**Comment by DuncanCasteleyn** [comment]
I  have the same problem had to revert to version 8.10.2 on all my Kotlin projects.

**Comment by torbenziegler** [comment]
Same issue here creating new project with Kotlin Multiplatform Wizard which sets Gradle to 8.9. Tried upgrading until 8.5 and upgrading to 8.11, nothing helped yet.

**Comment by mrozanc** [comment]
Any idea of a workaround except moving the files manually each time there are new transforms?

I don't understand why I have this problem now after spending months with the same Gradle versions (8.6 to 8.11.1) without any issue on the same computers.

Reading the bug reports I see that may be related to me installing gradle using Scoop. It defined the `GRADLE_USER_HOME` env var, which I didn't want, so I unset it, but before that I encountered the problem (and that's how I saw that it modified the Gradle home location.

The thing is even after removing the content of `$HOME/.gradle`, reseting the env var, the problem stays on all Gradle 8.6 to 8.11.1 versions, so I guess something changed on my system that cause the problem, but what?

**Comment by stan-at-work** [comment]
Any updates ?
