### ISSUE TITLE
Invalid JDK environment variable causes cryptic error when using Daemon JVM discovery

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#31409]
### Current Behavior

In the JUnit repository we have `org.gradle.java.installations.fromEnv` configured to include `JDK24` in the project's `gradle.properties`:
https://github.com/junit-team/junit5/blob/ddeac0da590c19704fef9e555f1eea8a5c5ebe25/gradle.properties#L23

Moreover, we're using the incubating "Daemon JVM discovery" feature:
https://github.com/junit-team/junit5/blob/de40dbe56ab3fee1f77727055bda18bbf9bd8db3/gradle/gradle-daemon-jvm.properties#L1-L2

I've recently updated my local JDK 24-ea version and forgot that I has set a `JDK24` in my shell configuration:
```zsh
export JDK24=$(asdf where java 'openjdk-24-ea+14')
```

Removing the referenced JDK caused the following value to be set:
```terminal
$ echo $JDK24
Version not installed
```

I didn't notice at first, because I already had a Gradle daemon running. However, after restarting the machine and running a Gradle build I got the following error:

```terminal
$ ./gradlew :help                       
Daemon JVM discovery is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Cannot convert relative path Version not installed to an absolute file.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```

Full stacktrace:
```
java.lang.UnsupportedOperationException: java.lang.UnsupportedOperationException: Cannot convert relative path Version not installed to an absolute file.
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:540)
        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:670)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.gradle.internal.jvm.inspection.DefaultJavaInstallationRegistry.collectInstallations(DefaultJavaInstallationRegistry.java:172)
        at org.gradle.internal.jvm.inspection.DefaultJavaInstallationRegistry.maybeCollectInBuildOperation(DefaultJavaInstallationRegistry.java:130)
        at org.gradle.internal.jvm.inspection.DefaultJavaInstallationRegistry.lambda$new$0(DefaultJavaInstallationRegistry.java:113)
        at org.gradle.internal.jvm.inspection.DefaultJavaInstallationRegistry$Installations.initIfNeeded(DefaultJavaInstallationRegistry.java:281)
        at org.gradle.internal.jvm.inspection.DefaultJavaInstallationRegistry$Installations.get(DefaultJavaInstallationRegistry.java:270)
        at org.gradle.internal.jvm.inspection.DefaultJavaInstallationRegistry.listInstallations(DefaultJavaInstallationRegistry.java:137)
        at org.gradle.internal.jvm.inspection.DefaultJavaInstallationRegistry.toolchains(DefaultJavaInstallationRegistry.java:143)
        at org.gradle.launcher.daemon.toolchain.DaemonJavaToolchainQueryService.locateToolchain(DaemonJavaToolchainQueryService.java:67)
        at org.gradle.launcher.daemon.toolchain.DaemonJavaToolchainQueryService.findMatchingToolchain(DaemonJavaToolchainQueryService.java:51)
        at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startDaemon(DefaultDaemonStarter.java:100)
        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.doStartDaemon(DefaultDaemonConnector.java:216)
        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.startDaemon(DefaultDaemonConnector.java:210)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:169)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:97)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:56)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:167)
        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:370)
        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:334)
        at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:74)
        at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:30)
        at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:97)
        at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:40)
        at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:50)
        at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:27)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:482)
        at org.gradle.launcher.Main.doAction(Main.java:35)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:52)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:72)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:39)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.gradle.wrapper.GradleWrapperMain.main(SourceFile:70)
Caused by: java.lang.UnsupportedOperationException: Cannot convert relative path Version not installed to an absolute file.
        at org.gradle.api.internal.file.IdentityFileResolver.doResolve(IdentityFileResolver.java:37)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:74)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:48)
        at org.gradle.jvm.toolchain.internal.EnvironmentVariableListInstallationSupplier.resolveEnvironmentVariable(EnvironmentVariableListInstallationSupplier.java:63)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.gradle.jvm.toolchain.internal.EnvironmentVariableListInstallationSupplier.get(EnvironmentVariableListInstallationSupplier.java:55)
        at org.gradle.jvm.toolchain.internal.EnvironmentVariableListInstallationSupplier.get(EnvironmentVariableListInstallationSupplier.java:29)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
        at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
        at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

After I removed `gradle/gradle-daemon-jvm.properties`, the daemon started and invoking `:javaToolchains` did not yield any errors.

### Expected Behavior

After staring at the stacktrace for a while, I could derive that it must be some kind of problem with environment variables (it contains `EnvironmentVariableListInstallationSupplier.resolveEnvironmentVariable`).

However, it should at least state which environment variable is at fault so it's easier to fix.

### Self-contained Reproducer Project

- Clone the [junit5 repo](https://github.com/junit-team/junit5/)
- Set `JDK24` environment variable to an invalid path
- Run `./gradlew :help`

### Gradle version

8.11.1

**Comment by ov7a** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by big-guy** [comment]
We shouldn't fail the build if we can't figure out which paths to inspect.

cc @ljacomet this is an interesting error to fix.  I think the DV ran into something like this too.
