### ISSUE TITLE
[Project isolation] Starting with Gradle 8.11, with project isolation enabled, dependencies are resolved during configuration time

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#31483]
### Current Behavior

In our project (Android Gradle plugin), we enable **project isolation** by default in our tests and have a custom check to fail if dependencies are resolved at configuration time. When updating from Gradle 8.10.2 to **8.11.1**, many of our tests start to fail because dependencies are resolved at configuration time.

### Expected Behavior

The tests shouldn't fail. (Dependencies shouldn't be resolved at configuration time.)

### Self-contained Reproducer Project

To reproduce the issue, use this project [MyApplication.zip](https://github.com/user-attachments/files/17980237/MyApplication.zip) (a simple project with 4 subprojects).

Go to the project directory, set `ANDROID_HOME` in the command below, then run:
```
rm -rf .gradle/configuration-cache && ANDROID_HOME=/path/to/Android/Sdk ./gradlew :app:assembleDebug -Dorg.gradle.unsafe.isolated-projects=true -Pandroid.dependencyResolutionAtConfigurationTime.disallow=true -s
```

The build will fail (most of the time) with:
```
Configuration cache state could not be cached: field `__platformAttrRTxt__` of task `:lib:parseDebugLocalResources` of type `com.android.build.gradle.internal.res.ParseLibraryResourcesTask`: error writing value of type 'org.gradle.api.internal.provider.DefaultProperty'
...
Caused by: java.lang.RuntimeException: Configuration 'androidApis' was resolved during configuration time.
This is a build performance and scalability issue.
See https://github.com/gradle/gradle/issues/2298
        at com.android.build.gradle.internal.DependencyResolutionChecks$registerDependencyCheck$4$1.execute(DependencyResolutionChecks.kt:65)
        at com.android.build.gradle.internal.DependencyResolutionChecks$registerDependencyCheck$4$1.execute(DependencyResolutionChecks.kt:55)
```

### Gradle version

8.11.1 (didn't happen in 8.10.2 and earlier)

### Your Environment (optional)

Android Gradle plugin 8.9.0-alpha03 and earlier

(Note that with Android Gradle plugin 8.9.0-alpha04+, we have disabled this check when project isolation is enabled so that we can upgrade to Gradle 8.11.1.)

**Comment by jbartok** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by alllex** [comment]
Fixed by https://github.com/gradle/gradle/pull/31692
