### ISSUE TITLE
Improves message `Querying the mapped value of task '<task>' property '<some property>' before task '<task>' has completed is not supported`

### ISSUE THREAD

**Issue by bric3** [gradle/gradle#31627]
### Expected Behavior

The following message is really odd

> Querying the mapped value of task ':module:generateClass' property 'generatedClassDir' before task ':module:generateClass' has completed is not supported

In the trend of 

* https://github.com/gradle/build-tool-roadmap/issues/49

What do you think about indicating the underlying reason : e.g.

```
Execution failed for task ':module:generatedClass'.
> Calling 'project.file' during a task execution is not supported
  > Querying the mapped value of task ':module:generateClass' property 'generatedClassDir' before task ':module:generateClass' has completed is not supported calling `map` during task execution
```

### Current Behavior (optional)

I was rewriting some tasks written using the Kotlin DSK ta a task class, The DSL code made use of 

```kotlin
project.file(generatedClassDir.map { it.file("some/path/to/A.java") })
```

Let's ignore that this line could be improved for a moment.

Using this line in this code

```kotlin
val generateClass by tasks.registering(GenerateClass::class)
abstract class GenerateClass : DefaultTask() {
    @OutputDirectory
    val generatedClassDir: DirectoryProperty = project.objects.directoryProperty()
        .convention(project.layout.buildDirectory.dir("generated/sources/version/java"))

    @TaskAction
    fun generate() {
        project.file(generatedClassDir.map { it.file("some/path/to/A.java") })
        // not useful to reproduce
    }
}
```

And executing `generateClass` results in the following message

```
Execution failed for task ':module:generatedClass'.
> Querying the mapped value of task ':module:generateClass' property 'generatedClassDir' before task ':module:generateClass' has completed is not supported
```

It took more time than necessary that I shouldn't call `project.file(<file property>)` during the execution

### Context

Converting a kotlin DSL task to a task class

----

Related but different than #16777

**Comment by lkasso** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

This looks like a deeper issue where a task is accessing its own output property through the provider API and poses a problem, but it should not. The informed team will decide on the best course of action (either a deeper investigation or improving the error message).

**Comment by bric3** [comment]
For reference I also triggered this behavior, still using whatever `Provider`. E.g.

```kotlin
abstract class CustomTask @Inject constructor(
    private val project: Project,
) : DefaultTask() {
    @get:OutputDirectory
    abstract val dest: DirectoryProperty

    @TaskAction
    fun proceed() {
        val fileDest = = dest.map { "foo" }.get()
    }
}
```


```
...
Caused by: org.gradle.api.InvalidUserCodeException: Querying the mapped value of task ':jufmt-lib:scrapeAolFonts' property 'dest' before task ':jufmt-lib:scrapeAolFonts' has completed is not supported
        at org.gradle.api.internal.provider.TransformBackedProvider.lambda$beforeRead$0(TransformBackedProvider.java:99)
        at org.gradle.api.internal.provider.ValueSupplier$TaskProducer.visitContentProducerTasks(ValueSupplier.java:134)
        at org.gradle.api.internal.provider.TransformBackedProvider.beforeRead(TransformBackedProvider.java:96)
        at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:81)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:82)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:102)
        at Build_gradle$AolFontScrapper.scrape(build.gradle.kts:213)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
...
```

----

I have found a workaround using a local provider for a temporary location, then copy from my temporary location to the output destination 

```kotlin
        project.layout.buildDirectory
            .dir("tmp/$name/downloaded")
            .map { it.file("../$month-aol-fonts.zip") }
        project.copy {
            from(listFile, aolFontsArchive)
            into(dest)
        }
```

**Comment by asodja** [comment]
This issue will be closed as a duplicate of

* #26340

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***
