### ISSUE TITLE
GradleDaemonStopped exception when canceling a build and immediately executing new build which leads to new daemon being spawned

### ISSUE THREAD

**Issue by ss-block** [gradle/gradle#31679]
### Current Behavior

I have a use case where I already have a build running and when a new build is started, I want the first build to cancel and the new build to be executed on the same daemon.

I have been testing with Tooling Api but also replicable without Tooling api by executing the first build in cli, cancelling it with ctrl-c and immediately executing a new build.

I have noticed a delay in the time it takes to stop a build, both w/ Tooling api cancellation token and with ctrl-c. So when the second build starts, the first is still being cancelled so the daemon is in a CANCELLED state. This causes a new daemon to spawn to run the second build instead of reusing the original daemon.

I have been running just the configuration phase of the build with `--dry-run` and have found something interesting -
I am noticing that the above scenario of build cancellation taking too long with daemon being in CANCELLED state causing a new daemon being to spawn for 2nd build happens in the late stages when the build has already made a lot of progress and is near/in the configuration cache store phase.
If the the build is in the early/mid configuration phase, cancellation happens almost instantly and the 2nd build is able to reuse the same daemon.

```
org.gradle.tooling.BuildCancelledException: Could not execute build using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-8.11-bin.zip'.
	at org.gradle.tooling.internal.consumer.ConnectionExceptionTransformer.transform(ConnectionExceptionTransformer.java:49)
	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:42)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:68)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
	at org.gradle.tooling.internal.consumer.DefaultBuildLauncher.run(DefaultBuildLauncher.java:82)
	at com.squareup.mdx.daemon.util.GradleExecutor.executeTask(GradleExecutor.kt:30)
	at com.squareup.mdx.daemon.configuration.JobExecutionConfiguration$applyFor$2.invokeSuspend(JobExecutionConfiguration.kt:54)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
Caused by: org.gradle.api.BuildCancelledException: Daemon was stopped to handle build cancel request.
	at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:226)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:158)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:97)
	at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:30)
	at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:56)
	at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:37)
	at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:262)
	at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:167)
	at org.gradle.tooling.internal.provider.DefaultConnection.getModel(DefaultConnection.java:154)
	at org.gradle.tooling.internal.consumer.connection.CancellableModelBuilderBackedModelProducer.produceModel(CancellableModelBuilderBackedModelProducer.java:53)
	at org.gradle.tooling.internal.consumer.connection.PluginClasspathInjectionSupportedCheckModelProducer.produceModel(PluginClasspathInjectionSupportedCheckModelProducer.java:38)
	at org.gradle.tooling.internal.consumer.connection.AbstractConsumerConnection.run(AbstractConsumerConnection.java:64)
	at org.gradle.tooling.internal.consumer.connection.ParameterValidatingConsumerConnection.run(ParameterValidatingConsumerConnection.java:49)
	at org.gradle.tooling.internal.consumer.DefaultBuildLauncher$1.run(DefaultBuildLauncher.java:96)
	at org.gradle.tooling.internal.consumer.DefaultBuildLauncher$1.run(DefaultBuildLauncher.java:88)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:143)
	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:61)
	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:66)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.gradle.launcher.daemon.server.api.DaemonStoppedException: Gradle build daemon has been stopped: cancel requested but timed out
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator.waitForCommandCompletion(DaemonStateCoordinator.java:353)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator.runCommand(DaemonStateCoordinator.java:327)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy.doBuild(StartBuildOrRespondWithBusy.java:56)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ReturnResult.execute(ReturnResult.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.CleanUpVirtualFileSystemAfterBuild.doBuild(CleanUpVirtualFileSystemAfterBuild.java:58)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.api.HandleReportStatus.execute(HandleReportStatus.java:35)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.HandleCancel.execute(HandleCancel.java:39)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.api.HandleInvalidateVirtualFileSystem.execute(HandleInvalidateVirtualFileSystem.java:46)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.api.HandleStop.execute(HandleStop.java:46)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecuter.executeCommand(DaemonCommandExecuter.java:55)
	at org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler$ConnectionWorker.handleCommand(DefaultIncomingConnectionHandler.java:161)
	at org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler$ConnectionWorker.receiveAndHandleCommand(DefaultIncomingConnectionHandler.java:134)
	at org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler$ConnectionWorker.run(DefaultIncomingConnectionHandler.java:122)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)
	... 3 more
```

### Expected Behavior

Able to cancel current build and execute new build immediately on the same daemon instead of spawning a new daemon.

### Context (optional)

This specific use case, we only care about executing the configuration phase and creating a cc entry so only runs the builds with `--dry-run`.

### Self-contained Reproducer Project

Currently do not have a reproducer project.

### Gradle version

8.11

### Your Environment (optional)

```
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.daemon=true
```

**Comment by ov7a** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

***

@ss-block can you provide a reproducer project/steps to reproduce it easily, please?

**Comment by ss-block** [comment]
I currently do not have a reproducer project w/ Tooling Api but can also be replicated through CLI build.

Steps to reproduce
- enable configuration cache
- use gradle daemon
- gradle 8.11

```
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.daemon=true
```

- execute Build #1 w/ `--dry-run` flag `./gradlew :app:assembleDebug --dry-run` in CLI
- when Build 1 has ran for some time and is close to finishing or in configuration cache store phase, do Ctrl-C to terminate the build
- after Ctrl-C, immediately execute Build #2 `./gradlew :app:assembleDebug --dry-run`
- The behavior is flakey but many times when the second build is executed, it will show "available daemon is already in use, starting new daemon" message.

- This happens because build #1 hasn't completely finished cancellation so daemon is in `CANCELLED` state instead of `IDLE`, causing a new daemon to spawn for build #2.

**Comment by ss-block** [comment]
As per @alllex's request, attaching thread dumps of 3 separate instances of this issue occurring 

[threaddump1.txt](https://github.com/user-attachments/files/18494314/threaddump1.txt)
[threaddump2.txt](https://github.com/user-attachments/files/18494315/threaddump2.txt)
[threaddump3.txt](https://github.com/user-attachments/files/18494316/threaddump3.txt)

**Comment by abstratt** [comment]
Thanks. The first thread dump suggests an instance of https://github.com/gradle/gradle/issues/8750 (sample thread below, similar to other 17 threads). The other two dumps do not seem to be stalled/stuck AFAICT.

```
java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.6/Native Method)
        - parking to wait for  <0x000000040ec0d390> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@17.0.6/LockSupport.java:252)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@17.0.6/AbstractQueuedSynchronizer.java:1757)
        at org.gradle.cache.internal.DefaultFileLockManager$AwaitableFileLockReleasedSignal.await(DefaultFileLockManager.java:469)
        at org.gradle.internal.time.ExponentialBackoff.retryUntil(ExponentialBackoff.java:73)
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.lockStateRegion(DefaultFileLockManager.java:409)
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.lock(DefaultFileLockManager.java:332)
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.<init>(DefaultFileLockManager.java:179)
        at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:125)
        at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.incrementLockCount(LockOnDemandCrossProcessCacheAccess.java:106)
        at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.acquireFileLock(LockOnDemandCrossProcessCacheAccess.java:163)
        at org.gradle.cache.internal.CrossProcessSynchronizingIndexedCache.put(CrossProcessSynchronizingIndexedCache.java:57)
        at org.gradle.api.internal.changedetection.state.DefaultFileAccessTimeJournal.setLastAccessTime(DefaultFileAccessTimeJournal.java:82)
        at org.gradle.internal.file.impl.SingleDepthFileAccessTracker.markAccessed(SingleDepthFileAccessTracker.java:51)
        at org.gradle.internal.resource.cached.AbstractCachedIndex.lookup(AbstractCachedIndex.java:71)
        at org.gradle.api.internal.artifacts.ivyservice.modulecache.artifacts.DefaultModuleArtifactCache.lookup(DefaultModuleArtifactCache.java:81)
        at org.gradle.api.internal.artifacts.ivyservice.modulecache.artifacts.InMemoryModuleArtifactCache.lookup(InMemoryModuleArtifactCache.java:63)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$LocateInCacheRepositoryAccess.resolveArtifactFromCache(CachingModuleComponentRepository.java:324)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$LocateInCacheRepositoryAccess.resolveArtifact(CachingModuleComponentRepository.java:291)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.lambda$resolveArtifact$12(ErrorHandlingModuleComponentRepository.java:169)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess$$Lambda$1955/0x0000007001c671d0.call(Unknown Source)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.tryResolveAndMaybeDisable(ErrorHandlingModuleComponentRepository.java:236)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.performOperationWithRetries(ErrorHandlingModuleComponentRepository.java:193)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.resolveArtifact(ErrorHandlingModuleComponentRepository.java:167)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainArtifactResolver.resolveArtifactLater(RepositoryChainArtifactResolver.java:73)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainArtifactResolver.lambda$resolveArtifact$0(RepositoryChainArtifactResolver.java:63)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainArtifactResolver$$Lambda$1953/0x0000007001c669e0.get(Unknown Source)
        at org.gradle.internal.model.CalculatedValueContainerFactory$SupplierBackedCalculator.calculateValue(CalculatedValueContainerFactory.java:78)
        at org.gradle.internal.model.CalculatedValueContainer$CalculationState.lambda$attachValue$0(CalculatedValueContainer.java:229)
        at org.gradle.internal.model.CalculatedValueContainer$CalculationState$$Lambda$1088/0x000000700180e9d0.call(Unknown Source)
        at org.gradle.internal.Try.ofFailable(Try.java:50)
        at org.gradle.internal.model.CalculatedValueContainer$CalculationState.attachValue(CalculatedValueContainer.java:224)
        at org.gradle.internal.model.CalculatedValueContainer.finalizeIfNotAlready(CalculatedValueContainer.java:195)
        at org.gradle.internal.model.CalculatedValueContainer.finalizeIfNotAlready(CalculatedValueContainer.java:186)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.ArtifactBackedResolvedVariant$DownloadArtifactFile.run(ArtifactBackedResolvedVariant.java:189)
...
```

**Comment by ss-block** [comment]
@abstratt In the other 2 instances, the first build was canceled and right away a second was started. However, the second builds still caused a new daemon to spawn instead of running on the same daemon as first daemon was still in CANCELLED state, so the root issue was still there.

Is there a workaround? Is it possible to set a timeout or delay the execution of the second build until the daemon is back in IDLE state from CANCELLED? For our use case, a slight delay to start the new build is acceptable (while the original build is finishing being cancelled) to be able to reuse the existing warm daemon instead of spawning a new one (cold).
