### ISSUE TITLE
ConfigurationCacheException: Error while saving task graph

### ISSUE THREAD

**Issue by cusxy** [gradle/gradle#31673]
### Current Behavior

Hi!

I’m encountering errors when trying to publish a project on CI. The issue is flaky, occurring in about half of the builds. Unfortunately, I’m unable to provide a sample project, but I’m happy to share relevant code snippets and stack traces to help investigate.

### Expected Behavior

Here is a stacktrace

[stacktrace.txt](https://github.com/user-attachments/files/18096936/stacktrace.txt)

### Self-contained Reproducer Project

Not applicable 

### Gradle version

8.11.1

### Your Environment (optional)

A project with several Kotlin Multiplatform modules with java, android, and iOS support.

Kotlin Gradle Plugin — 2.0.21
Android Gradle Plugin — 8.7.2

**Comment by ov7a** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

****

This part of the stacktrace is suspicious. 
```
Caused by: java.util.ConcurrentModificationException
	at org.gradle.api.internal.collections.SortedSetElementSource.removeByProvider(SortedSetElementSource.java:202)
	at org.gradle.api.internal.collections.SortedSetElementSource.removePending(SortedSetElementSource.java:196)
	at org.gradle.api.internal.collections.SortedSetElementSource.realizeExternal(SortedSetElementSource.java:260)
	at org.gradle.api.internal.DefaultDomainObjectCollection.realized(DefaultDomainObjectCollection.java:82)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.realized(DefaultNamedDomainObjectCollection.java:138)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.tryCreate(DefaultNamedDomainObjectCollection.java:1009)
	... 89 more
```
@gradle/bt-configuration Do you have enough information to investigate this report, or is something else needed?

**Comment by mlopatkin** [comment]
It would be great to have a reproducer project, but given how the failure is intermittent, we can start with the stacktrace.

**Comment by mlopatkin** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.
