### ISSUE TITLE
[Gradle 8.12] "Problems service is not initialized error" in plugin unit tests

### ISSUE THREAD

**Issue by ssthom** [gradle/gradle#31862]
### Current Behavior

Upgrading Gradle wrapper from 8.11.1 to 8.12 in our plugins repo we are seeing an issue in our internal Gradle plugin unit tests where there is a `java.lang.IllegalStateException: Problems service is not initialized.` exception. I did't see anything in the https://docs.gradle.org/8.12/release-notes.html release notes about anything required to implement or https://docs.gradle.org/8.12/userguide/reporting_problems.html. 

>Plugins **<ins>can</ins>** report problems through Gradle’s problems-reporting APIs. The APIs report rich, structured information about problems happening during the build.

Exception in tests
```
org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin 'cicd-common-plugin'.
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:176)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:148)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:162)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:44)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:99)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:185)
	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:49)
	at org.gradle.api.internal.project.DefaultProject.apply(DefaultProject.java:1556)
	at com.ibm.sterling.gradle.CommonConfigurationPluginTests.plugin_Adds_The_compileJava_task(CommonConfigurationPluginTests.groovy:73)
Caused by: java.lang.IllegalStateException: Problems service is not initialized.
	at org.gradle.api.problems.internal.ProblemsProgressEventEmitterHolder.get(ProblemsProgressEventEmitterHolder.java:28)
	at org.gradle.internal.execution.impl.DefaultWorkValidationContext.getProblemsService(DefaultWorkValidationContext.java:48)
	at org.gradle.internal.execution.impl.DefaultWorkValidationContext.forType(DefaultWorkValidationContext.java:55)
	at org.gradle.internal.execution.steps.ValidateStep.validateImplementations(ValidateStep.java:124)
	at org.gradle.internal.execution.steps.ValidateStep.lambda$execute$0(ValidateStep.java:78)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:78)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:56)
	at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:64)
	at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:43)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
	at org.gradle.internal.execution.steps.AssignImmutableWorkspaceStep.lambda$executeInTemporaryWorkspace$3(AssignImmutableWorkspaceStep.java:209)
	at org.gradle.internal.execution.workspace.impl.CacheBasedImmutableWorkspaceProvider$1.withTemporaryWorkspace(CacheBasedImmutableWorkspaceProvider.java:116)
	at org.gradle.internal.execution.steps.AssignImmutableWorkspaceStep.executeInTemporaryWorkspace(AssignImmutableWorkspaceStep.java:199)
	at org.gradle.internal.execution.steps.AssignImmutableWorkspaceStep.lambda$execute$0(AssignImmutableWorkspaceStep.java:121)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.gradle.internal.execution.steps.AssignImmutableWorkspaceStep.execute(AssignImmutableWorkspaceStep.java:121)
	at org.gradle.internal.execution.steps.AssignImmutableWorkspaceStep.execute(AssignImmutableWorkspaceStep.java:90)
	at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:38)
	at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:23)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.lambda$execute$2(ExecuteWorkBuildOperationFiringStep.java:67)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:67)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:39)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:46)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:34)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:48)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:35)
	at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:61)
	at org.gradle.groovy.scripts.internal.GroovyScriptClassCompiler.doCompile(GroovyScriptClassCompiler.java:167)
	at org.gradle.groovy.scripts.internal.GroovyScriptClassCompiler.compile(GroovyScriptClassCompiler.java:129)
	at org.gradle.groovy.scripts.internal.CrossBuildInMemoryCachingScriptClassCache.getOrCompile(CrossBuildInMemoryCachingScriptClassCache.java:53)
	at org.gradle.groovy.scripts.internal.BuildScopeInMemoryCachingScriptClassCompiler.compile(BuildScopeInMemoryCachingScriptClassCompiler.java:50)
	at org.gradle.groovy.scripts.DefaultScriptCompilerFactory$ScriptCompilerImpl.compile(DefaultScriptCompilerFactory.java:49)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:117)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.configuration.BuildOperationScriptPlugin.lambda$apply$0(BuildOperationScriptPlugin.java:65)
	at org.gradle.internal.code.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:44)
	at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:65)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyScript(DefaultObjectConfigurationAction.java:151)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$000(DefaultObjectConfigurationAction.java:44)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$1.run(DefaultObjectConfigurationAction.java:77)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:185)
	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:49)
	at org.gradle.api.internal.project.DefaultProject.apply(DefaultProject.java:1556)
	at com.ibm.sterling.gradle.CommonConfigurationPlugin.apply(CommonConfigurationPlugin.groovy:18)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:54)
	at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:190)
	at org.gradle.api.internal.plugins.DefaultPluginManager.access$100(DefaultPluginManager.java:54)
	at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:285)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.api.internal.plugins.DefaultPluginManager.lambda$doApply$0(DefaultPluginManager.java:170)
	at org.gradle.internal.code.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:44)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:169)
	... 8 more
```

### Expected Behavior

Upgrading from 8.11.1 to 8.12 happens without issues or has appropriate instructions on how to fix issues when upgrading either in CLI or in release notes as breaking changes

### Self-contained Reproducer Project

I cannot submit our internal code but I gave complete stacktrace above and can provide more information as wanted

### Gradle version

8.12

### Your Environment (optional)

Java 17.0.13
Gradle 8.11.1 -> 8.12
Both Linux x86_64 CI environment and my local Arm Mac M1 machine

**Comment by ov7a** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by donat** [comment]
@hegyibalint The stacktrace indicate that somewhere early on in Gradle there's a broken groovy script that triggers a problem report. Can you please try to replicate that usecase in a reproducer?

**Comment by hegyibalint** [comment]
I've attempted to reproduce the issue but failed.

@ssthom, could you take a look at https://github.com/hegyibalint/31862-emitter-not-initialized, compare it with your issue, and if you have a more refined idea based on your source code, create a PR or fork the repository to reproduce? Otherwise, we have no reasonable idea why this might happen, as nobody else has reported this.

If anybody else has the same issue and has a good idea of what might cause this, please don't hesitate to contribute here or on the reproducer repository. Thanks!

**Comment by dreis2211** [comment]
@hegyibalint Not sure if this is the same problem as the reporter has, but I can reproduce this with this minimal project: 

https://github.com/dreis2211/gradle-8-12-problem-reporter-bug

Just run `./gradlew test` and you should see a failing test with the message described above.

Hope this helps.
Cheers,
Christoph

**Comment by ssthom** [comment]
I do get the exact same error in https://github.com/dreis2211/gradle-8-12-problem-reporter-bug as I do locally when running `./gradlew test`

**Comment by mricciuti** [comment]
Hi.
I have exactly the same stack trace when trying to upgrade my plugins project from Gradle 8.11.1 to 8.12.1.
My plugins project is using JDK 1.8  and Kotlin DSL 

Error occurs on some (but not all) JUnit test cases; I cannot easily create a simple reproduser project right now, but my failing test cases look like:

```
    @Test
    fun `Valid configuration should configure rpm plugin successfully`() {

        val project = createProjectFromTestResources("$RPM_RES_BASE/rpm-valid")
        project.pluginManager.apply("mycompany.rpm")
        (project as DefaultProject).evaluate()   //  <--- failure here
		
	 // ...
	}	
```

I get following stacktrace (truncated , as it's almost identical to the one abobe)

```

org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'test'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:84)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:77)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$500(LifecycleProjectEvaluator.java:55)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.lambda$run$0(LifecycleProjectEvaluator.java:111)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.lambda$applyToMutableState$1(DefaultProjectStateRegistry.java:411)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.fromMutableState(DefaultProjectStateRegistry.java:429)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.applyToMutableState(DefaultProjectStateRegistry.java:410)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.run(LifecycleProjectEvaluator.java:100)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:72)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:822)
	at RpmPluginTest.Valid configuration should configure rpm plugin successfully(RpmPluginTest.kt:19)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
Caused by: java.lang.IllegalStateException: Problems service is not initialized.
	at org.gradle.api.problems.internal.ProblemsProgressEventEmitterHolder.get(ProblemsProgressEventEmitterHolder.java:28)
	at org.gradle.internal.execution.impl.DefaultWorkValidationContext.getProblemsService(DefaultWorkValidationContext.java:48)
	at org.gradle.internal.execution.impl.DefaultWorkValidationContext.forType(DefaultWorkValidationContext.java:55)
	at org.gradle.internal.execution.steps.ValidateStep.validateImplementations(ValidateStep.java:124)
	at org.gradle.internal.execution.steps.ValidateStep.lambda$execute$0(ValidateStep.java:78)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:78)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:56)
	at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:64)
	at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:43)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
	at org.gradle.internal.execution.steps.AssignImmutableWorkspaceStep.lambda$executeInTemporaryWorkspace$3(AssignImmutableWorkspaceStep.java:209)
	at org.gradle.internal.execution.workspace.impl.CacheBasedImmutableWorkspaceProvider$1.withTemporaryWorkspace(CacheBasedImmutableWorkspaceProvider.java:116)
	at org.gradle.internal.execution.steps.AssignImmutableWorkspaceStep.executeInTemporaryWorkspace(AssignImmutableWorkspaceStep.java:199)
	at org.gradle.internal.execution.steps.AssignImmutableWorkspaceStep.lambda$execute$0(AssignImmutableWorkspaceStep.java:121)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.gradle.internal.execution.steps.AssignImmutableWorkspaceStep.execute(AssignImmutableWorkspaceStep.java:121)
	....
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:72)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:822)
	at RpmPluginTest.Valid configuration should configure rpm plugin successfully(RpmPluginTest.kt:19)
```

**Comment by dreis2211** [comment]
This is still an issue with Gradle 8.13

**Comment by dreis2211** [comment]
I can workaround this problem by calling `ProblemsProgressEventEmitterHolder.init()` in the test setup (prior to project evaluation), like the following:
 
```
ProblemsProgressEventEmitterHolder.init(Mockito.mock(InternalProblems.class));
project = projectBuilder().withProjectDir(projectDir).build();
(project as DefaultProject).evaluate();
```

Maybe this helps others here to progress.

**Comment by ssthom** [comment]
Thank you @dreis2211! That workaround worked for me as well. I was able to upgrade to 8.13

**Comment by micahjo7** [comment]
This is still an issue in the Android Gradle Plugin tests, when attempting to upgrade to Gradle 8.12. That issue is tracked in:

https://issuetracker.google.com/issues/400789167

Is there an update on the fix for this error?

**Comment by reinsch82** [comment]
Hi all,

I was able to reproduce this issue with @dreis2211 's [example](https://github.com/dreis2211/gradle-8-12-problem-reporter-bug) and was able to fix this for 8.14.

You may use a [nightly](https://services.gradle.org/distributions-snapshots/) to try it out, I'd recommend tomorrows 8.14 snapshot.
