### ISSUE TITLE
dependency locking sometimes fails

### ISSUE THREAD

**Issue by NikolayMetchev** [gradle/gradle#31875]
### Current Behavior

After upgrading to 8.12 resolveAndLockAll (as described here: https://docs.gradle.org/current/userguide/dependency_locking.html) has become flaky. There appears to possibly be a race condition. In CI using GithubActions a build running this
```
./gradlew resolveAndLockAll --write-locks --no-configuration-cache
```
will usually fail on the first build and re-run will succeed.
The failure is as follows:
```
Something has been appended to this collector already
```

Attached is a develocity build scan showing the failure.
[rahhqf3ktyqgu.scandump.zip](https://github.com/user-attachments/files/18229743/rahhqf3ktyqgu.scandump.zip)

### Expected Behavior

resolveAndLockAll to not fail

### Self-contained Reproducer Project

N/A

### Gradle version

8.12

### Your Environment (optional)

Github Actions
linux
x86

**Comment by NikolayMetchev** [comment]
adding `--no-parallel` appears to be a good workaround.

**Comment by abstratt** [comment]
We appreciate the effort, but we must ask for more information so that we can triage it. 

We do not see an immediate root cause, and we need a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) for the triage. If we have a reproducer project, we may be also able to suggest other workarounds or ways to avoid the problem.

The ideal way to provide a reproducer project is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project.

Also, thanks for sharing the build scan dump, but since it is not accessible to most users, could you instead either share the build scan URL, or the stack trace for the failure?

**Comment by NikolayMetchev** [comment]
I have reproduced it.. but it isn't easy. Doesn't happen every time: https://github.com/NikolayMetchev/gradle-issue-31875-reproducer/actions/runs/12583729406/job/35071901205

**Comment by ljacomet** [comment]
This is an issue with the Kotlin Gradle Plugin, which is developed by JetBrains, and cannot be addressed in the Gradle Build Tool project. We cannot just move the issue.

Please open such Kotlin-related issues on the JetBrains YouTrack at https://kotl.in/issue.

If you believe this is not a Kotlin plugin issue, please update with a reproducer that does not involve the Kotlin plugin.

***

Given the stacktrace in the scan produced on GH actions, this issue seems to come from the Kotlin plugin:

```
at org.gradle.api.internal.provider.AbstractCollectionProperty.add(AbstractCollectionProperty.java:161)	
at org.jetbrains.kotlin.gradle.utils.ReportUtilsKt.addConfigurationMetrics(reportUtils.kt:23)	
at org.jetbrains.kotlin.gradle.plugin.statistics.KotlinStdlibConfigurationMetrics.collectMetrics$kotlin_gradle_plugin_common(FusMetrics.kt:332)	
at org.jetbrains.kotlin.gradle.internal.StdlibDependencyManagementKt$addStdlibDependency$1$1$1.execute(stdlibDependencyManagement.kt:139)	
at org.jetbrains.kotlin.gradle.internal.StdlibDependencyManagementKt$addStdlibDependency$1$1$1.execute(stdlibDependencyManagement.kt:116)	
at org.gradle.internal.ImmutableActionSet$SetWithFewActions.execute(ImmutableActionSet.java:285)	
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.lambda$runDependencyActions$2(DefaultConfiguration.java:509)
```

Looks like something is going wrong with a dependency action registered against a configuration, causing an invalid use of a Gradle collection type.

**Comment by NikolayMetchev** [comment]
https://youtrack.jetbrains.com/issue/KT-74241/Dependency-locking-sometimes-fails-with-gradle-kotlin-plugin
