### ISSUE TITLE
Calling SourceSetContainer#create with an empty string throws confusing exception

### ISSUE THREAD

**Issue by felipecsl** [gradle/gradle#3221]
When creating new `SourceSet`s with `SourceSetContainer#create`, calling that method with an empty string throws the exception below:

```
Caused by: org.gradle.api.InvalidUserDataException: Cannot add task ':processResources' as a task with that name already exists.
        at org.gradle.api.internal.tasks.DefaultTaskContainer.addTask(DefaultTaskContainer.java:93)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:117)
        at org.gradle.api.plugins.JavaBasePlugin.createProcessResourcesTaskForBinary(JavaBasePlugin.java:203)
        at org.gradle.api.plugins.JavaBasePlugin.access$300(JavaBasePlugin.java:90)
        at org.gradle.api.plugins.JavaBasePlugin$2.execute(JavaBasePlugin.java:167)
        at org.gradle.api.plugins.JavaBasePlugin$2.execute(JavaBasePlugin.java:158)
        at org.gradle.internal.ImmutableActionSet$CompositeSet.execute(ImmutableActionSet.java:196)
        at org.gradle.internal.MutableActionSet.execute(MutableActionSet.java:35)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:204)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:198)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.add(DefaultNamedDomainObjectCollection.java:93)
        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.create(AbstractNamedDomainObjectContainer.java:68)
        at org.gradle.api.internal.AbstractValidatingNamedDomainObjectContainer.create(AbstractValidatingNamedDomainObjectContainer.java:42)
        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.create(AbstractNamedDomainObjectContainer.java:50)
```

### Expected Behavior
Ideally, sourceSets with an empty name shouldn't be allowed.
If that's a valid name, then an exception should not be thrown.
The exception above is raised by the Java plugin. Other errors might happen with different plugins applied.

### Current Behavior
Calling `SourceSetContainer#create` with an empty String throws a confusing exception.

### Context
I came across this issue while writing a plugin that creates sourceSets dynamically and accidentally called that method with an empty String.

### Steps to Reproduce (for bugs)
```
apply plugin: 'java'
sourceSets.create('')
```

### Your Environment
Gradle v4.2.1

**Comment by oehme** [comment]
This will be forbidden in 5.0, bad names currently lead to a deprecation warning.

**Comment by bigdaz** [comment]
#6955 Added a test for this use case, and improved the error reporting.
