### ISSUE TITLE
taskReport task sometimes throws exception when using parallel build

### ISSUE THREAD

**Issue by leomekenkamp** [gradle/gradle#3286]
### Expected Behavior
We have got our build running in Jenkins, and most of the time the build completes like expected. We have parallel running enabled and call gradlew with params "--no-daemon -Pversion=develop-SNAPSHOT --init-script [redacted] build projectReport buildDashboard artifactoryPublish"

We expect the build to always run without exceptions.

### Current Behavior
Sometimes (about 1 in 10 runs?) we see the following exception:
_____________________________________________________________________
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':database:taskReport'.
> Exception thrown while executing model rule: tasks.addPlaceholderAction(buildEnvironment)
   > Cannot set value for model element 'tasks.buildEnvironment' as this element is not mutable.
https://gradle.com/scans/get-started
_____________________________________________________________________

### Context
We would like the build to run as fast as possible, so we have set parallel to true in the project properties. We also generate a build dashboard and a project report for reference sake. It seems these two things do not go well together at this point.

### Steps to Reproduce (for bugs)
I am sorry, but I have not been able to get this issue to reproduce in a reliable way. And since the build runs (and fails) on a Jenkins server on which I have no further rights, I am afraid I cannot do something more useful than add the output of both a failing as well as the output of a non-failing build. I have a sneaking suspicion that the order in which the tasks run is responsible for this bug, so this may just be enough information. Output below last question.

### Your Environment
Gradle 4.2.1, with wrapper, on Jenkins on a linux machine, with the Jenkins/Gradle/Artifactory plugin enabled. Java 1.8.0_141-b15

Output of a NON_FAILING build:
_____________________________________________________________________
:assemble
:common:compileJava
:assemble UP-TO-DATE
:database:bbbSqlZip
:docker:compileJava
:nolio:apacheZip
:check
:testautomation:processResources
:war:processResources
:check UP-TO-DATE
:build UP-TO-DATE
:dependencyReport
:testautomation:processResources NO-SOURCE
:testautomation:processTestResources
:docker:compileJava NO-SOURCE
:docker:processResources NO-SOURCE
:docker:classes UP-TO-DATE
:docker:jar
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/build/reports/project/dependencies.txt
:htmlDependencyReport
:nolio:manifestZip
:docker:assemble
:docker:compileTestJava
:war:processTestResources
:database:assemble
:database:check UP-TO-DATE
:database:build
:database:dependencyReport
:docker:compileTestJava NO-SOURCE
:docker:processTestResources NO-SOURCE
:docker:testClasses UP-TO-DATE
:docker:test
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/database/build/reports/project/dependencies.txt
:testautomation:htmlDependencyReport
:war:htmlDependencyReport
:database:htmlDependencyReport
:nolio:sybaseZip
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/build/reports/project/dependencies/index.html
:docker:test NO-SOURCE
:docker:htmlDependencyReport
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/database/build/reports/project/dependencies/index.html
:nolio:tomcatZip
:propertyReport
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/build/reports/project/properties.txt
:taskReport
:database:buildDashboard
:nolio:assemble
:nolio:check UP-TO-DATE
:nolio:build
:nolio:dependencyReport
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/nolio/build/reports/project/dependencies.txt
:database:propertyReport
:nolio:htmlDependencyReport
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/database/build/reports/project/properties.txt
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/nolio/build/reports/project/dependencies/index.html
:database:taskReport
:nolio:buildDashboard
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/database/build/reports/project/tasks.txt
:database:projectReport
:database:artifactoryPublish
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/build/reports/project/tasks.txt
:projectReport
:nolio:propertyReport
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/nolio/build/reports/project/properties.txt
:nolio:taskReport
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/nolio/build/reports/project/tasks.txt
:nolio:projectReport
:nolio:artifactoryPublish
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/war/build/reports/project/dependencies/index.html
:war:dependencyReport
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/war/build/reports/project/dependencies.txt
:war:propertyReport
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/war/build/reports/project/properties.txt
:war:taskReport
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/war/build/reports/project/tasks.txt
:war:projectReport
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/testautomation/build/reports/project/dependencies/index.html
:testautomation:dependencyReport
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/testautomation/build/reports/project/dependencies.txt
:testautomation:propertyReport
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/testautomation/build/reports/project/properties.txt
:testautomation:taskReport
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/testautomation/build/reports/project/tasks.txt
:testautomation:projectReport
Note: Hibernate JPA 2 Static-Metamodel Generator 5.2.7.Final
:common:processResources
:common:classes
:common:jar
:common:assemble
:testautomation:compileJava
:war:compileJava
:common:compileTestJavaNote: Hibernate JPA 2 Static-Metamodel Generator 5.2.7.Final

:common:processTestResources
:common:testClasses
:common:test
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/docker/build/reports/project/dependencies/index.html
:docker:buildDashboard
:docker:check UP-TO-DATE
:docker:build
:docker:dependencyReport
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/docker/build/reports/project/dependencies.txt
:docker:propertyReport
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/docker/build/reports/project/properties.txt
:docker:taskReport
See the report at: file:///opt/app/slhudson/workspace/Netting-develop__release/docker/build/reports/project/tasks.txt
:docker:projectReport
:docker:installNote: Hibernate JPA 2 Static-Metamodel Generator 5.2.7.Final

:docker:artifactoryPublish
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /opt/app/slhudson/workspace/Netting-develop__release/war/src/main/java/nl/mendesgans/netting/web/InitializeServlet.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:war:classes
:war:war
:war:assemble
:war:compileTestJava NO-SOURCE
:war:testClasses
:war:test NO-SOURCE
:war:buildDashboard
:war:check UP-TO-DATE
:war:build
:war:install
:war:artifactoryPublish
Note: Hibernate JPA 2 Static-Metamodel Generator 5.2.7.Final
:testautomation:classes
:testautomation:jar
:testautomation:assemble
:testautomation:compileTestJava
:common:htmlDependencyReport
See the report at: [redacted]/common/build/reports/project/dependencies/index.html
:common:buildDashboard
:common:check
:common:build
:common:dependencyReport
See the report at: [redacted]/common/build/reports/project/dependencies.txt
:common:propertyReport
See the report at: [redacted]/common/build/reports/project/properties.txt
:common:taskReport
See the report at: [redacted]/common/build/reports/project/tasks.txt
:common:projectReport
:common:install
:common:artifactoryPublish
Note: Hibernate JPA 2 Static-Metamodel Generator 5.2.7.Final
:testautomation:testClasses
:testautomation:test NO-SOURCE
:testautomation:buildDashboard
:testautomation:check UP-TO-DATE
:buildDashboard
:testautomation:build
:testautomation:install
:testautomation:artifactoryPublish
:artifactoryPublish
[redacted]
BUILD SUCCESSFUL in 2m 26s
66 actionable tasks: 66 executed
_____________________________________________________________________

Output of a FAILING build:
_____________________________________________________________________
:assemble
:nolio:apacheZip
:common:compileJava
:database:bbbSqlZip
:docker:compileJava
:testautomation:processResources
:assemble UP-TO-DATE
:check UP-TO-DATE
:build UP-TO-DATE
:dependencyReport
:war:processResources
:testautomation:processResources NO-SOURCE
:testautomation:processTestResources
:docker:compileJava NO-SOURCE
:docker:processResources NO-SOURCE
:docker:classes UP-TO-DATE
:docker:jar
See the report at: [redacted]/build/reports/project/dependencies.txt
:htmlDependencyReport
:docker:assemble
:docker:compileTestJava
:nolio:manifestZip
:war:processTestResources
:docker:compileTestJava NO-SOURCE
:docker:processTestResources NO-SOURCE
:docker:testClasses UP-TO-DATE
:docker:test
:testautomation:htmlDependencyReport
:war:htmlDependencyReport
:docker:test NO-SOURCE
:docker:htmlDependencyReport
:database:assemble
:database:check UP-TO-DATE
:database:build
:database:dependencyReport
See the report at: [redacted]/database/build/reports/project/dependencies.txt
:nolio:sybaseZip
See the report at: [redacted]/build/reports/project/dependencies/index.html
:database:htmlDependencyReport
:nolio:tomcatZip
See the report at: [redacted]/database/build/reports/project/dependencies/index.html
:propertyReport
See the report at: [redacted]/build/reports/project/properties.txt
:taskReport
:database:buildDashboard
:nolio:assemble
:nolio:check UP-TO-DATE
:nolio:build
:nolio:dependencyReport
:database:propertyReport
See the report at: [redacted]/nolio/build/reports/project/dependencies.txt
:nolio:htmlDependencyReport
See the report at: [redacted]/database/build/reports/project/properties.txt
:database:taskReport
See the report at: [redacted]/nolio/build/reports/project/dependencies/index.html
:database:taskReport FAILED
See the report at: [redacted]/build/reports/project/tasks.txt
Download [redacted, 9 lines]
See the report at: [redacted]/war/build/reports/project/dependencies/index.html
See the report at: [redacted]/testautomation/build/reports/project/dependencies/index.html
Note: Hibernate JPA 2 Static-Metamodel Generator 5.2.7.Final
See the report at: [redacted]/docker/build/reports/project/dependencies/index.html
:docker:buildDashboard
:buildDashboard

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':database:taskReport'.
> Exception thrown while executing model rule: tasks.addPlaceholderAction(buildEnvironment)
   > Cannot set value for model element 'tasks.buildEnvironment' as this element is not mutable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
26 actionable tasks: 26 executed
_____________________________________________________________________

**Comment by blindpirate** [comment]
Thanks for reporting. It would be great if you could add `--stacktrace` so that it will make it much easier for us to find out the reason.

**Comment by blindpirate** [comment]
Closed due to unresponsiveness.

**Comment by leomekenkamp** [comment]
Sorry for the late response: long holiday combined with some missed email. And there is the fact that this does not happen very often. Here is the stacktrace, hope you will reopen the bug and take a look at it.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':bmgstyle-selenium:taskReport'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.model.internal.core.ModelRuleExecutionException: Exception thrown while executing model rule: tasks.addPlaceholderAction(components)
	at org.gradle.model.internal.registry.DefaultModelRegistry.fireAction(DefaultModelRegistry.java:490)
	at org.gradle.model.internal.registry.DefaultModelRegistry.access$700(DefaultModelRegistry.java:71)
	at org.gradle.model.internal.registry.DefaultModelRegistry$RunModelAction.apply(DefaultModelRegistry.java:1184)
	at org.gradle.model.internal.registry.DefaultModelRegistry.transitionTo(DefaultModelRegistry.java:390)
	at org.gradle.model.internal.registry.DefaultModelRegistry.get(DefaultModelRegistry.java:360)
	at org.gradle.model.internal.registry.DefaultModelRegistry.require(DefaultModelRegistry.java:340)
	at org.gradle.model.internal.registry.DefaultModelRegistry.realizeNode(DefaultModelRegistry.java:262)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.realize(DefaultTaskContainer.java:220)
	at org.gradle.api.internal.project.DefaultProjectTaskLister.listProjectTasks(DefaultProjectTaskLister.java:29)
	at org.gradle.api.tasks.diagnostics.TaskReportTask.generate(TaskReportTask.java:75)
	at org.gradle.api.tasks.diagnostics.AbstractReportTask$2.generateReport(AbstractReportTask.java:74)
	at org.gradle.api.tasks.diagnostics.internal.ReportGenerator.generateReport(ReportGenerator.java:58)
	at org.gradle.api.tasks.diagnostics.AbstractReportTask.generate(AbstractReportTask.java:84)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:784)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:751)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 29 more
Caused by: java.lang.IllegalStateException: Cannot set value for model element 'tasks.components' as this element is not mutable.
	at org.gradle.model.internal.registry.ModelElementNode.setPrivateData(ModelElementNode.java:117)
	at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreator.execute(DefaultTaskContainer.java:324)
	at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreator.execute(DefaultTaskContainer.java:305)
	at org.gradle.model.internal.core.ModelRegistrations$Builder$NoInputsBuilderAction.execute(ModelRegistrations.java:190)
	at org.gradle.model.internal.registry.DefaultModelRegistry$4.run(DefaultModelRegistry.java:485)
	at org.gradle.model.internal.registry.RuleContext.run(RuleContext.java:42)
	at org.gradle.model.internal.registry.DefaultModelRegistry.fireAction(DefaultModelRegistry.java:482)
	... 54 more

**Comment by leomekenkamp** [comment]
And we've just seen another one, slightly different:

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':taskReport'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.model.internal.core.ModelRuleExecutionException: Exception thrown while executing model rule: MavenPublishPlugin.Rules#realizePublishingTasks(ModelMap<Task>, PublishingExtension, File) > create(publishMavenJavaPublicationToMavenLocal)
	at org.gradle.model.internal.registry.DefaultModelRegistry.fireAction(DefaultModelRegistry.java:490)
	at org.gradle.model.internal.registry.DefaultModelRegistry.access$700(DefaultModelRegistry.java:71)
	at org.gradle.model.internal.registry.DefaultModelRegistry$RunModelAction.apply(DefaultModelRegistry.java:1184)
	at org.gradle.model.internal.registry.DefaultModelRegistry.transitionTo(DefaultModelRegistry.java:390)
	at org.gradle.model.internal.registry.DefaultModelRegistry.get(DefaultModelRegistry.java:360)
	at org.gradle.model.internal.registry.DefaultModelRegistry.require(DefaultModelRegistry.java:340)
	at org.gradle.model.internal.registry.DefaultModelRegistry.realizeNode(DefaultModelRegistry.java:262)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.realize(DefaultTaskContainer.java:220)
	at org.gradle.api.internal.project.DefaultProjectTaskLister.listProjectTasks(DefaultProjectTaskLister.java:29)
	at org.gradle.api.tasks.diagnostics.TaskReportTask.generate(TaskReportTask.java:80)
	at org.gradle.api.tasks.diagnostics.AbstractReportTask$2.generateReport(AbstractReportTask.java:74)
	at org.gradle.api.tasks.diagnostics.internal.ReportGenerator.generateReport(ReportGenerator.java:58)
	at org.gradle.api.tasks.diagnostics.AbstractReportTask.generate(AbstractReportTask.java:84)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:780)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:747)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 29 more
Caused by: java.lang.IllegalStateException: Cannot set value for model element 'tasks.publishMavenJavaPublicationToMavenLocal' as this element is not mutable.
	at org.gradle.model.internal.registry.ModelElementNode.setPrivateData(ModelElementNode.java:117)
	at org.gradle.model.internal.core.NodeBackedModelMap$4$1$1.execute(NodeBackedModelMap.java:134)
	at org.gradle.model.internal.core.NodeBackedModelMap$4$1$1.execute(NodeBackedModelMap.java:129)
	at org.gradle.model.internal.core.DirectNodeNoInputsModelAction$1.execute(DirectNodeNoInputsModelAction.java:39)
	at org.gradle.model.internal.registry.DefaultModelRegistry$4.run(DefaultModelRegistry.java:485)
	at org.gradle.model.internal.registry.RuleContext.run(RuleContext.java:42)
	at org.gradle.model.internal.registry.DefaultModelRegistry.fireAction(DefaultModelRegistry.java:482)
