### ISSUE TITLE
Re-ran task fails to be stored in local cache

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#3358]
When the first cacheable task in a build is re-ran (because of `--rerun-tasks` or because of `upToDateWhen()` returning `false`) an exception is thrown:

```text
> Task :junit-platform-engine-test-support:compileKotlin
Using Kotlin incremental compilation
Failed to store cache entry a17159cb3ed2b1d24c0a6013c957335b for task ':junit-platform-engine-test-support:compileKotlin'
org.gradle.internal.resource.local.FileStoreException: Cannot move '/Users/lptr/.gradle/caches/build-cache-1/a17159cb3ed2b1d24c0a6013c957335b8520798112014501714.part' into filestore @ '/Users/lptr/.gradle/caches/build-cache-1/a17159cb3ed2b1d24c0a6013c957335b' as it does not exist
        at org.gradle.internal.resource.local.DefaultPathKeyFileStore.saveIntoFileStore(DefaultPathKeyFileStore.java:128)
        at org.gradle.internal.resource.local.DefaultPathKeyFileStore.move(DefaultPathKeyFileStore.java:74)
        at org.gradle.internal.resource.local.DefaultPathKeyFileStore.move(DefaultPathKeyFileStore.java:50)
        at org.gradle.caching.local.internal.DirectoryBuildCacheService$3.run(DirectoryBuildCacheService.java:145)
        at org.gradle.internal.Factories$1.create(Factories.java:25)
        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:217)
        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:198)
        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:152)
        at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.useCache(DefaultCacheFactory.java:190)
        at org.gradle.caching.local.internal.DirectoryBuildCacheService.store(DirectoryBuildCacheService.java:142)
        at org.gradle.caching.internal.controller.service.DefaultLocalBuildCacheServiceHandle.store(DefaultLocalBuildCacheServiceHandle.java:59)
        at org.gradle.caching.internal.controller.DefaultBuildCacheController$2.execute(DefaultBuildCacheController.java:222)
        at org.gradle.caching.internal.controller.DefaultBuildCacheController$2.execute(DefaultBuildCacheController.java:208)
        at org.gradle.caching.local.internal.DefaultBuildCacheTempFileStore.allocateTempFile(DefaultBuildCacheTempFileStore.java:49)
        at org.gradle.caching.local.internal.DirectoryBuildCacheService.allocateTempFile(DirectoryBuildCacheService.java:152)
        at org.gradle.caching.internal.controller.DefaultBuildCacheController.store(DefaultBuildCacheController.java:208)
        at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:116)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:61)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
```

https://e.grdev.net/s/biclneqynhblc

**Comment by lptr** [comment]
PR: #3329
