### ISSUE TITLE
ProgressLogEventGenerator gives NoSuchElementException

### ISSUE THREAD

**Issue by remmeier** [gradle/gradle#3465]
### Expected Behavior

no exceptions

### Current Behavior

NoSuchElementException being thrown.

```
java.util.NoSuchElementException
	at org.gradle.internal.logging.sink.ProgressLogEventGenerator.onComplete(ProgressLogEventGenerator.java:82)
	at org.gradle.internal.logging.sink.ProgressLogEventGenerator.onOutput(ProgressLogEventGenerator.java:59)
	at org.gradle.internal.logging.console.BuildLogLevelFilterRenderer.onOutput(BuildLogLevelFilterRenderer.java:41)
	at org.gradle.internal.logging.console.AbstractUserInputRenderer.onOutput(AbstractUserInputRenderer.java:54)
	at org.gradle.internal.logging.sink.OutputEventRenderer$4.onOutput(OutputEventRenderer.java:265)
	at org.gradle.internal.logging.sink.OutputEventRenderer$LazyListener.onOutput(OutputEventRenderer.java:354)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy0.onOutput(Unknown Source)
	at org.gradle.internal.logging.sink.OutputEventRenderer.onOutput(OutputEventRenderer.java:322)
	at org.gradle.internal.logging.services.ProgressLoggingBridge.completed(ProgressLoggingBridge.java:33)
	at org.gradle.internal.logging.progress.DefaultProgressLoggerFactory$ProgressLoggerImpl.completed(DefaultProgressLoggerFactory.java:176)
	at org.gradle.internal.progress.BuildProgressLogger.beforeComplete(BuildProgressLogger.java:93)
	at org.gradle.internal.progress.BuildProgressFilter.beforeComplete(BuildProgressFilter.java:111)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:371)
	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:353)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:341)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:328)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:341)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:328)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:341)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:152)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:126)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy20.beforeComplete(Unknown Source)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:50)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:57)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:32)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:64)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:45)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)


* Get more help at https://help.gradle.org

BUILD FAILED in 2m 9s
```

### Context

breaks the build

### Steps to Reproduce (for bugs)

what seems rather hard. We see it randomly in a fairly large internal project. The issue started to pop up recently after we added a further subproject that makes use of the GradleRunner. But no idea how that could be related.

### Your Environment

happens both on Windows 10 and redhat 7. Gradle is 4.3. Java 8 and 9.

build scan crashes with:

`
Caused by: java.lang.NullPointerException
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.SelectorState.getFailure(SelectorState.java:68)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.EdgeState.getFailure(EdgeState.java:182)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.oldresult.ResolutionFailureCollector.visitNode(ResolutionFailureCollector.java:54)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.CompositeDependencyGraphVisitor.visitNode(CompositeDependencyGraphVisitor.java:39)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.CompositeDependencyGraphVisitor.visitNode(CompositeDependencyGraphVisitor.java:39)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.assembleResult(DependencyGraphBuilder.java:302)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:104)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:84)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolveGraph(DefaultConfigurationResolver.java:138)
        at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveGraph(ShortCircuitEmptyConfigurationResolver.java:73)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:66)
        ... 108 more
`

**Comment by bmuschko** [comment]
Is there any chance you could provide us with the build options you use e.g. `--parallel` etc.? The easiest way to provide the information would be with a build scan.

**Comment by remmeier** [comment]
got the scan working, here it is:

https://scans.gradle.com/s/xhoayv4h7i7q6

that is from my local machine. I did not get a scan for the failed build. This build is executed after the failed one. Since most to everything was up-to-date, Gradle did not have much to do anymore and this build passes.

**Comment by remmeier** [comment]
the issue does not happen when parallel build is disabled, but then the build takes quite long.

the build is also marked as "BUILD SUCCESSFUL in..." and only then crashes.

**Comment by eriwen** [comment]
@bmuschko Couple thoughts to help debug this:

 * The only recent change I'm aware of in logging is conversion to use BuildOperations in more cases, but I'm not sure if this is in 4.3
 * Based on the code, this looks like a race condition that has existed for quite awhile, so `--parallel` definitely factors in here.

**Comment by eriwen** [comment]
BTW @remmeier thanks for the build scan and the additional info. Very helpful 👍

**Comment by bmuschko** [comment]
@remmeier From the build scan I see that you apply the build scan plugin to root project of your build. Do you see the same issue if you do not apply the build scan plugin?

**Comment by bmuschko** [comment]
@eriwen Wild guess when looking at `OutputEventRenderer`. For the [rich console listener chain](https://github.com/gradle/gradle/blob/master/subprojects/logging/src/main/java/org/gradle/internal/logging/sink/OutputEventRenderer.java#L223) we [synchronize the incoming events](https://github.com/gradle/gradle/blob/master/subprojects/logging/src/main/java/org/gradle/internal/logging/console/ThrottlingOutputEventListener.java#L68) in `ThrottlingOutputEventListener`. For the [plain console listener chain](https://github.com/gradle/gradle/blob/master/subprojects/logging/src/main/java/org/gradle/internal/logging/sink/OutputEventRenderer.java#L82) we do not do such a thing. Does that sounds reasonable?

**Comment by eriwen** [comment]
@bmuschko that sounds very interesting. We should run a targeted performance test before merging that to see how much that slows logging down.

**Comment by remmeier** [comment]
yes, the issue is there even without the build scan plugin

the issue is also there in 4.2.1 and in 4.0.0. For 4.2.1 it is:

```
* Exception is:
java.util.NoSuchElementException
        at org.gradle.internal.logging.sink.ProgressLogEventGenerator.onComplete(ProgressLogEventGenerator.java:82)
        at org.gradle.internal.logging.sink.ProgressLogEventGenerator.onOutput(ProgressLogEventGenerator.java:59)
        at org.gradle.internal.logging.console.BuildLogLevelFilterRenderer.onOutput(BuildLogLevelFilterRenderer.java:41)
        at org.gradle.internal.logging.sink.OutputEventRenderer$4.onOutput(OutputEventRenderer.java:252)
        at org.gradle.internal.logging.sink.OutputEventRenderer$LazyListener.onOutput(OutputEventRenderer.java:341)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy0.onOutput(Unknown Source)
        at org.gradle.internal.logging.sink.OutputEventRenderer.onOutput(OutputEventRenderer.java:309)
        at org.gradle.internal.logging.services.ProgressLoggingBridge.completed(ProgressLoggingBridge.java:33)
        at org.gradle.internal.logging.progress.DefaultProgressLoggerFactory$ProgressLoggerImpl.completed(DefaultProgressLoggerFactory.java:176)
        at org.gradle.internal.progress.BuildProgressLogger.beforeComplete(BuildProgressLogger.java:92)
        at org.gradle.internal.progress.BuildProgressFilter.beforeComplete(BuildProgressFilter.java:111)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:371)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:353)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:341)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:328)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:341)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:328)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:341)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:152)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:126)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy20.beforeComplete(Unknown Source)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:50)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:57)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:32)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:64)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:45)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:50)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)

* Get more help at https://help.gradle.org
BUILD FAILED in 3m 22s
```

I investigated it a bit further. The issue only happens when the moap-blueprint subproject is included in the build. There is nothing special in that subproject except that it contains a lot of copy tasks that copy paste & package the sources of the other subprojects (those copies artifact will be used as templates). I suspect that this pattern facilitates running into the threading issue by having those copy tasks have as input most of the other subprojects sources, causing some kind of "synchronization point" in the task graph or however that should be called. 

The copies look as simple as:

`
def templatesSourceDir = rootDir
def templatesBuildDir = new File(buildDir, '/templates')
def templatesPackageDir = new File(templatesBuildDir, '/ch/xy/moap/blueprints/')

task copyCommonServiceTemplates(type: Copy) {
	from new File(templatesSourceDir, 'moap-movie-common-service/src/main/java/ch/adnovum/moap/movie/common/service')
	into new File(templatesPackageDir, 'common')
}
`

removing the copy compands make the build pass.

**Comment by bmuschko** [comment]
@remmeier Thanks for your analysis. Do you think you could try to condense your large project to a smaller one that reproduces the issue? I might have an idea where the issue lies but so far I couldn't reproduce the issue yet.

**Comment by bmuschko** [comment]
@remmeier [Here's what I tried so far.](https://github.com/bmuschko/gradle-issue-3465) Let me know if that somewhat resembles your project structure and the work you are trying to achieve with your build.

If you try out my sample project you'll first have to generate some subprojects with the following command:

```
./gradlew createSubprojects

After that I tried to run the `build` task in combination with the parallel command line option:

```
./gradlew build --parallel
```

The copy tasks live in the `dist` subproject and are task dependencies for the `build` task.

Can you maybe use that to reproduce the issue by changing things in a way to potentially reproduces the issue?

**Comment by remmeier** [comment]
it happens to both, the plain and the rich console.

I tried to modify your setup. Unforunately I did not mange to reproduce it either. I added further classes and copy commands. But that did not help. Downstripping my application is rather difficult, we make use of a few of private plugins and libraries the entire project depends upon. By removing that we end up with the application you already setup.

sorry, probably not the things you wanted to hear :-(

**Comment by bmuschko** [comment]
@remmeier Interesting find though that it fails in rich and plain console. I am wondering if the issue is an external plugin (that maybe does its own progress logging). Maybe you can try to chop away some of the plugins you don't necessarily need to see if that gives us a clue.

**Comment by bmuschko** [comment]
@remmeier Were you able to make anymore progress?

**Comment by remmeier** [comment]
not really :-( I noticed some other people a while back with similar/same issues (https://discuss.gradle.org/t/java-lang-illegalstateexception-received-progress-event-for-an-unknown-operation-id-125/1776).

It is quite difficult. I was able to remove the major external plugins (docker, npm, rpm), but the issue persists. I can remove some more things and the issue dissappears. But it seems more related to removing stuff than the actual stuff being removed. 

The exception happens at the very end. The build is marked as successfull and only Gradle related code is in the stacktrace. What makes you thinkg a third-party plugin is involved? The issue only arose after we added that blueprint project lately.

I also tried to find out more with debug. But then it does not seem to crash either.

**Comment by bmuschko** [comment]
> What makes you thinkg a third-party plugin is involved?

It was somewhat a guess because I couldn't reproduce the issue on my machine with the sample project. Also, there might be something funny a plugin is doing that messes with the progress logging. It really looks like the issue has been around forever as indicated by the link to the forum post you provided.

**Comment by bmuschko** [comment]
So far I wasn't able to reproduce the issue. @remmeier It would be great if you could have another look at your project to see if we can find some sort of root cause or correlation (apart from running with `--parallel`).

**Comment by remmeier** [comment]
ok thx, i will try to track it down in early january

**Comment by RemonSinnema** [comment]
We also suffer from this a lot :( We're using Gradle 4.5.1. All classes in the stack trace are in `org.gradle` or `com.sun.proxy`. We see it even if we only run `gradlew clean`. We see it often with `--console=plain`, but occasionally we see it without that as well.

**Comment by bmuschko** [comment]
@RemonSinnema Any chance you can provide a reproducible example project? So far I haven't been able to reproduce the issue on my machine. Can you also provide information on OS and console in use?

**Comment by RemonSinnema** [comment]
We've definitely seen it on Linux, not sure about other OSes.
Not sure I understand your question about "console in use". I already mentioned that

> We see it often with --console=plain, but occasionally we see it without that as well.

**Comment by bmuschko** [comment]
> Not sure I understand your question about "console in use". I already mentioned that

@RemonSinnema I was asking about the type of shell. Maybe you are using something specific here.

**Comment by RemonSinnema** [comment]
I'm using `bash`. I also see it on TeamCity, not sure what they use there. And I've seen it on TeamCity Windows agents as well.

**Comment by bmuschko** [comment]
@RemonSinnema Thanks, we'd need a reproducible example for fix the underlying issue. Any chance you could put something together?

**Comment by remmeier** [comment]
The popped up again in two of our builds and I investigated it a bit further (Gradle 4.7 and 4.10 for two different projects). What I can say is that the notified completion event never triggered the matching onStart event in ProgressLogEventGenerator. As such the map is empty and the build crashes. There are not concurrent completion events with the same ID or something, it rather is and never was there in the first place.

I started storing all the events within static maps to trace back where it is coming from. Mostly it seems to be crashing from testing related events. TestWorkerProgressListener is one area where does are coming from. Not sure about the code in there, the usage of "description" as map key seems a bit odd and the `testWorkerProgressLoggers.containsKey(description)` look a bit fragile. But I think that part seems to work and is not the cause. 

There are also many usages of HashMap, LinkedHashMap, etc. not sure whether thread safety has to be considered given that it is most likely a multi-threading issue.

Not sure what kind of filters are in place that may lead to a completion without a start event. If anybody has some pointers to investigate, just let me know. I have the Gradle sources checked out and started doing some changes. Currently the build crashes quite often, which makes it easy to investigate things. But I still cannot share the sources unfortunately.

In general It may also not be necessary to crash the build at that location since it is only logging related. But if the events are not properly dispatched, I guess more issues could pop up.

**Comment by remmeier** [comment]
created a PR that adds a NPE check

**Comment by mikand13** [comment]
If you need a reproducer you can clone

https://github.com/NoriginMedia/nannoq-tools

checkout develop and run

./gradlew build

If first pass completes for some reason run

./gradlew clean build --rerun-tasks --stacktrace

**Comment by mikand13** [comment]
For me, it's consistenly always :test. Specfically all tests pass, but the task fails. If any tests fail, :test fails "ordinarily".

All of this is only in parallel mode. Perfectly fine sequentially. But very slow, ofc.

**Comment by mikand13** [comment]
See now that its slightly different. For me the operation is null, so i get an NPE.

**Comment by big-guy** [comment]
@remmeier @mikand13 could you give Gradle 5.6.2 a try?
