### ISSUE TITLE
The error message of a failed build should render a hint to use the `--scan` command line option

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#3516]
### Expected Behavior

The error message of a failed build should render a hint to use the `--scan` command line option. The message is rendered independent of logging options (`-i`, `-d`, `-w`, `-q` or default) or if a stack trace (`-s`, `-S`) was requested.

For example:

```
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```
The message is rendered even if `--scan` or `buildScan.alwaysPublish()` were configured.

### Current Behavior

Users might not be aware of the usefulness of the built-in build scan command line option to diagnose the root cause of a build failure.

### Context

Built-in build scans were introduced and documented with Gradle 4.3. Make users more aware of the build scans by proposing the build scan option.

**Comment by mohsinbaig27** [comment]
019-12-04 03:59:19.964 9679-9711/com.mohsin.collectingshope E/eglCodecCommon: GoldfishAddressSpaceHostMemoryAllocator: ioctl_ping failed for device_type=5, ret=-1
2019-12-04 03:59:38.227 9679-9679/com.mohsin.collectingshope E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mohsin.collectingshope, PID: 9679
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.mohsin.collectingshope.LoginActivity$4.onDataChange(LoginActivity.java:117)
        at com.google.firebase.database.zzp.onDataChange(Unknown Source:7)
        at com.google.android.gms.internal.zzegf.zza(Unknown Source:13)
        at com.google.android.gms.internal.zzeia.zzbyc(Unknown Source:2)
        at com.google.android.gms.internal.zzeig.run(Unknown Source:71)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
i cant solve this problem anyone here solve this
