### ISSUE TITLE
ImmutableModuleExclusionSet.excludesArtifact() should never throw NPE

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#3679]
This seems to be a concurrency issue which we hit very rarely. It was presumably introduced with https://github.com/gradle/gradle/commit/3d8eef59620dd023e4a54b5d6e4be7f18dbd0787.

[Build Scan](https://e.grdev.net/s/ej2yxlduxee3s/failure?openFailures=WzBd&openStackTraces=WzIse31d#top=0)

 ```
 java.lang.NullPointerException:
at org.gradle.api.internal.artifacts.ivyservice.resolveengine.excludes.ImmutableModuleExclusionSet.excludesArtifact(ImmutableModuleExclusionSet.java:110)
at org.gradle.api.internal.artifacts.ivyservice.resolveengine.excludes.IntersectionExclusion.excludeArtifact(IntersectionExclusion.java:77)
at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.DefaultArtifactSet.toResolvedVariant(DefaultArtifactSet.java:91)
at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.DefaultArtifactSet.singleVariant(DefaultArtifactSet.java:78)
at org.gradle.internal.component.external.model.FixedComponentArtifacts.getArtifactsFor(FixedComponentArtifacts.java:51)
...
````

@bigdaz wrote:
That NPE looks like a thread-safety issue in the exclude rule merging. One way this could happen would be when one thread is inside `precomputeCaches()` a second thread will get short-circuited too early, before `artifactExcludes` has been populated by the first thread. https://github.com/gradle/gradle/blob/2df0fb42698fa61a4754ae7c2d64dc23e27757da/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/excludes/ImmutableModuleExclusionSet.java#L46-L66

I suspect we are caching `ImmutableModuleExclusionSet` and sharing between threads.

(A strong fix would be to use synchronization, but we might get away with checking existence of all caches before short-circuiting)

 ```    
private void precomputeCaches() {
    if (excludedModules != null && otherExcludes != null && artifactExcludes != null) {
        return;
    }
}
```

**Comment by jjohannes** [comment]
After a [discussion](https://gradle.slack.com/archives/C7H5CP62W/p1512091091000278) with @melix, we decided to make the method synchronized.
