### ISSUE TITLE
[Ionic + Cordova + Gradle + Android + Jenkins on Windows] Build failed with the pipe is being closed

### ISSUE THREAD

**Issue by anatoly-spb** [gradle/gradle#3729]
I created the jenkins item with free configuration and run the following windows batch several times (suppose that nodejs/npm/cordova/ionic installed according to https://ionicframework.com/docs/intro/installation/ ):
```
set ANDROID_HOME=C:\android\sdk
set NODEJS_HOME=C:\nodejs
set NPM_HOME=%NODEJS_HOME%\npmroot
set CI=true
set PATH=%SystemRoot%\system32;%SystemRoot%
set PATH=%JAVA_HOME%\bin;%PATH%
set PATH=%NODEJS_HOME%;%PATH%
set PATH=%NPM_HOME%;%PATH%
set PATH=%ANDROID_HOME%\platform-tools;%ANDROID_HOME%\tools;%ANDROID_HOME%\tools\bin;%PATH%
set BUILD_DIR=%WORKSPACE%\..\builds\%BUILD_ID%\build
mkdir %BUILD_DIR%
cd %BUILD_DIR%
call ionic start latest sidemenu
cd latest
call npm install
call ionic cordova plugin add cordova-plugin-file-transfer
call ionic cordova plugin add cordova-sqlite-storage
call ionic cordova plugin add cordova-plugin-advanced-http
call ionic cordova plugin add ionic-plugin-deeplinks --variable URL_SCHEME=myapp --variable DEEPLINK_SCHEME=https --variable DEEPLINK_HOST=example.com --variable ANDROID_PATH_PREFIX=/
call ionic cordova plugin add cordova-plugin-pin-dialog
call ionic cordova plugin add cordova-plugin-crosswalk-webview
call ionic cordova platform add android
rem also I tried to set android.aaptOptions.useNewCruncher=true in build-extras.gradle but it does not help
rem echo android.aaptOptions.useNewCruncher=true >platforms\android\build-extras.gradle
rem also I tried to set cdvBuildToolsVersion with different build-tools, it does not help
rem echo cdvBuildToolsVersion=25 >platforms\android\gradle.properties 
call ionic cordova build android --prod --release -- --gradleArg=--info
```

### Expected Behavior

success build

### Current Behavior

from time to time my build failed with:

```
* What went wrong:
Execution failed for task ':mergeArmv7ReleaseResources'.
> Error: java.util.concurrent.ExecutionException: java.io.IOException: The pipe is being closed

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.
```
Here is full log: https://pastebin.com/WBkZCipg

### Steps to Reproduce (for bugs)

I have desribed above.

### Your Environment

 * Build scan URL: 
```
PATH=C:\android\sdk\platform-tools;C:\android\sdk\tools;C:\android\sdk\tools\bin;C:\nodejs\npmroot;C:\nodejs;C:\Program Files\Java\jdk1.8.0_151\bin;C:\Windows\system32;C:\Windows
windows 8.1 
jenkins: 2.73.3
java version "1.8.0_151"
node v8.9.1
npm 5.5.1
cordova 7.1.0
cli packages: (C:\nodejs\npmroot\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0
 

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.1
    npm               : 5.5.1 
    OS                : Windows 8.1

Environment Variables:

    ANDROID_HOME : C:\android\sdk
```

**Comment by blindpirate** [comment]
Looks like issues are on Android side because Gradle isn't involved in the stacktraces:

```
Thread(png-cruncher_5): The pipe is being closed
java.io.IOException: The pipe is being closed
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
	at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
	at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
	at java.lang.Thread.run(Thread.java:748)
```

Notice the thread name `png-cruncher_5`, I think this may be a clue.

**Comment by anatoly-spb** [comment]
I have solved the problem with disable gradle daemon:
```
ionic cordova build android --prod --release -- -- --gradleArg=--no-daemon

**Comment by blindpirate** [comment]
Glad you solved it.
