### ISSUE TITLE
Timeout waiting to lock Zinc 0.3.15 compiler cache

### ISSUE THREAD

**Issue by dsilvasc** [gradle/gradle#3777]
Following up on the behavior that continues after https://github.com/gradle/gradle/issues/2605

I just ran into this with Gradle 4.3-20170911235713 and zinc 0.3.15:

```
Execution failed for task ':some:module:compileScala'.
> Could not open Zinc 0.3.15 compiler cache (/home/ubuntu/.gradle/caches/4.3-20170911235713+0000/zinc-0.3.15).
   > Timeout waiting to lock Zinc 0.3.15 compiler cache (/home/ubuntu/.gradle/caches/4.3-20170911235713+0000/zinc-0.3.15). It is currently in use by another Gradle instance.
     Owner PID: 17847
     Our PID: 17845
     Owner Operation: 
     Our operation: 
     Lock file: /home/ubuntu/.gradle/caches/4.3-20170911235713+0000/zinc-0.3.15/zinc-0.3.15.lock
```

### Current Behavior

```
* What went wrong:
Execution failed for task ':some:project:compileScala'.
> Could not open Zinc 0.3.15 compiler cache (/home/ubuntu/.gradle/caches/4.3-20170911235713+0000/zinc-0.3.15).
   > Timeout waiting to lock Zinc 0.3.15 compiler cache (/home/ubuntu/.gradle/caches/4.3-20170911235713+0000/zinc-0.3.15). It is currently in use by another Gradle instance.
     Owner PID: 16501
     Our PID: 16540
     Owner Operation: 
     Our operation: 
     Lock file: /home/ubuntu/.gradle/caches/4.3-20170911235713+0000/zinc-0.3.15/zinc-0.3.15.lock

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':some:project:compileScala'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.cache.CacheOpenException: Could not open Zinc 0.3.15 compiler cache (/home/ubuntu/.gradle/caches/4.3-20170911235713+0000/zinc-0.3.15).
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:61)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:32)
	at org.gradle.cache.internal.DefaultCacheFactory.doOpen(DefaultCacheFactory.java:90)
	at org.gradle.cache.internal.DefaultCacheFactory.open(DefaultCacheFactory.java:64)
	at org.gradle.cache.internal.DefaultCacheRepository$PersistentCacheBuilder.open(DefaultCacheRepository.java:123)
	at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory.createParallelSafeCompiler(ZincScalaCompilerFactory.java:58)
	at org.gradle.api.internal.tasks.scala.ZincScalaCompiler$Compiler.execute(ZincScalaCompiler.java:64)
	at org.gradle.api.internal.tasks.scala.ZincScalaCompiler.execute(ZincScalaCompiler.java:52)
	at org.gradle.api.internal.tasks.scala.ZincScalaCompiler.execute(ZincScalaCompiler.java:38)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerRunnable.run(AbstractDaemonCompiler.java:87)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:36)
	at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:46)
	at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	... 6 more
Caused by: org.gradle.cache.LockTimeoutException: Timeout waiting to lock Zinc 0.3.15 compiler cache (/home/ubuntu/.gradle/caches/4.3-20170911235713+0000/zinc-0.3.15). It is currently in use by another Gradle instance.
Owner PID: 16501
Our PID: 16540
Owner Operation: 
Our operation: 
Lock file: /home/ubuntu/.gradle/caches/4.3-20170911235713+0000/zinc-0.3.15/zinc-0.3.15.lock
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.lock(DefaultFileLockManager.java:280)
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.<init>(DefaultFileLockManager.java:150)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:100)
	at org.gradle.cache.internal.FixedExclusiveModeCrossProcessCacheAccess.open(FixedExclusiveModeCrossProcessCacheAccess.java:67)
	at org.gradle.cache.internal.DefaultCacheAccess.open(DefaultCacheAccess.java:141)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:59)
	... 32 more
```

### Steps to Reproduce (for bugs)

This was on CircleCI with 1 container, with gradle config `javaCompile { options.fork=true }` and `test { forkEvery=25 }`

Disabling [incremental compilation](https://docs.gradle.org/4.3/userguide/scala_plugin.html#sec:scala_incremental_compilation) with this config did not help:

```
tasks.withType(ScalaCompile) {
    scalaCompileOptions.with {
        force = true
    }
}
```

### Your Environment

 * Build scan URL:

**Comment by jjohannes** [comment]
It seems like the general problems with lock timeout issues have been fixed with https://github.com/gradle/gradle/issues/2605 in 4.2.

I assume that this issue is due to the fact that the Zinc compiler just needs more time when it initializes the cache.

I would propose to increase the timeout **only** for the Zinc compiler (not in general) by making the timeout configurable and providing a larger value here:
https://github.com/gradle/gradle/blob/2f94bfed05d248447439febefb45e841b7d73793/subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompilerFactory.java#L58-L61

**Comment by mockitoguy** [comment]
At LinkedIn we also observe this behavior, we started seeing it in Gradle 4.10. Has something changed wrt to this in the recent release?

**Comment by big-guy** [comment]
@oehme @marcphilipp could this be affected by the lock changes made for cleaning caches?

**Comment by oehme** [comment]
It could be, but without a thread dump from the "owner" process it's hard to tell what it was doing.

**Comment by emmanuelguerin** [comment]
We do reproduce this on our build. We get a couple errors on a build with roughly 2000+ tasks.
It seems more frequent in gradle 5 than in gradle 4.6 (the two versions we are testing now)

```
2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':bidding-strategies:clearing-price:fullbaf:langoustine:compileScala'.
> Could not open Zinc 0.3.15 compiler cache (/home/jenkins/.gradle/caches/5.0/zinc-0.3.15).
   > Timeout waiting to lock Zinc 0.3.15 compiler cache (/home/jenkins/.gradle/caches/5.0/zinc-0.3.15). It is currently in use by another Gradle instance.
     Owner PID: 25784
     Our PID: 22630
     Owner Operation: 
     Our operation: 
     Lock file: /home/jenkins/.gradle/caches/5.0/zinc-0.3.15/zinc-0.3.15.lock

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':bidding-strategies:clearing-price:fullbaf:langoustine:compileScala'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:96)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:65)
	at org.gradle.api.internal.tasks.execution.ActionEventFiringTaskExecuter.execute(ActionEventFiringTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.TimeoutTaskExecuter.execute(TimeoutTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.SnapshotAfterExecutionTaskExecuter.execute(SnapshotAfterExecutionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:49)
	at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:78)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:61)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:49)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:44)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:337)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:325)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:318)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:304)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.gradle.cache.CacheOpenException: Could not open Zinc 0.3.15 compiler cache (/home/jenkins/.gradle/caches/5.0/zinc-0.3.15).
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:80)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:42)
	at org.gradle.cache.internal.DefaultCacheFactory.doOpen(DefaultCacheFactory.java:94)
	at org.gradle.cache.internal.DefaultCacheFactory.open(DefaultCacheFactory.java:68)
	at org.gradle.cache.internal.DefaultCacheRepository$PersistentCacheBuilder.open(DefaultCacheRepository.java:117)
	at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory.createParallelSafeCompiler(ZincScalaCompilerFactory.java:62)
	at org.gradle.api.internal.tasks.scala.ZincScalaCompiler$Compiler.execute(ZincScalaCompiler.java:64)
	at org.gradle.api.internal.tasks.scala.ZincScalaCompiler.execute(ZincScalaCompiler.java:52)
	at org.gradle.api.internal.tasks.scala.ZincScalaCompiler.execute(ZincScalaCompiler.java:38)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:86)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:74)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:42)
	at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	... 6 more
Caused by: org.gradle.cache.LockTimeoutException: Timeout waiting to lock Zinc 0.3.15 compiler cache (/home/jenkins/.gradle/caches/5.0/zinc-0.3.15). It is currently in use by another Gradle instance.
Owner PID: 25784
Our PID: 22630
Owner Operation: 
Our operation: 
Lock file: /home/jenkins/.gradle/caches/5.0/zinc-0.3.15/zinc-0.3.15.lock
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.lock(DefaultFileLockManager.java:291)
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.<init>(DefaultFileLockManager.java:161)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:107)
	at org.gradle.cache.internal.FixedExclusiveModeCrossProcessCacheAccess.open(FixedExclusiveModeCrossProcessCacheAccess.java:66)
	at org.gradle.cache.internal.DefaultCacheAccess.open(DefaultCacheAccess.java:141)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:78)
	... 32 more

==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1h 4m 16s
2338 actionable tasks: 2179 executed, 159 from cache
```

**Comment by big-guy** [comment]
@emmanuelguerin You may be experiencing more timeouts with Gradle 5.0 because Gradle 4.9 has already generated the Zinc compiler interface jar.  This is regenerated on every Gradle update, so the problem will settle out once the jar has been generated on an agent.

What we believe is happening is that the Zinc compiler jar usually takes ~30 seconds to build, but under load, this can increase to ~minutes.  At that point, we have timeouts that fail the build.

Can you tell if how many concurrent tasks or other activity were happening on the build agent when the timeout happened?  A [build scan](https://scans.gradle.com/) would show concurrent task execution, if you're able to share that.

**Comment by emmanuelguerin** [comment]
Thanks for the feedback. This happened on our CI server with parallel mode, so it is quite possible that there was important load. But since the issue seems to disappear, your hypothesis is probably correct.
We don't have scans activated on these builds, so no scan for the moment.

**Comment by Sovietaced** [comment]
Does anyone have any advice for this? We are seeing this happen pretty often with our parallel builds. 

```
* What went wrong:
Execution failed for task ':compileGatlingScala'.
> Could not open Zinc 0.3.15 compiler cache (/home/ubuntu/.gradle/caches/5.1.1/zinc-0.3.15).
   > Timeout waiting to lock Zinc 0.3.15 compiler cache (/home/ubuntu/.gradle/caches/5.1.1/zinc-0.3.15). It is currently in use by another Gradle instance.
     Owner PID: 20871
     Our PID: 21311
     Owner Operation: 
     Our operation: 
     Lock file: /home/ubuntu/.gradle/caches/5.1.1/zinc-0.3.15/zinc-0.3.15.lock
```

**Comment by sacchettom** [comment]
First seen this now on a build we just moved to a Jenkins CI system.
The build is running on Gradle 6.5. Seems to happen consistently when at least two of the same build are running on the same agent. This is a pretty intense build, with parallel building enabled doing cross-compiling with multiple scala versions. Still takes 30+ minutes. One build at once seems just fine though. Builds are executed in docker containers, and the workspace is wiped out at the end of every build
```
Timeout waiting to lock zinc-1.3.5_2.12.1_8 compiler cache (/home/********/jenkins/workspace/**********/GRADLE_HOME/caches/6.5/zinc-1.3.5_2.12.1_8). It is currently in use by another Gradle instance.
Owner PID: 1445
Our PID: 1426
Owner Operation: 
Our operation: 
Lock file: /home/***********/jenkins/workspace/**********/GRADLE_HOME/caches/6.5/zinc-1.3.5_2.12.1_8/zinc-1.3.5_2.12.1_8.lock
```
I had to clean the output, but we do generate a gradle home folder in a subfolder of the working space (the code is in a different subfolder).
The broken task is the last scala compilation task at the bottom, so I assume that indeed the zinc jar creation timeout is a possible reason for this. Is there a manual option for increasing the timeout?
![Screenshot 2020-07-14 at 16 15 33](https://user-images.githubusercontent.com/14197893/87443719-c0282980-c5ed-11ea-8b12-52b611b9ea02.png)

**Comment by edoardocomar** [comment]
Seeing this on a Jenkins build running Gradle 7.2 
```
15:30:58 Execution failed for task ':streams:streams-scala:compileScala'.
15:30:58 > Timeout waiting to lock zinc-1.3.5_2.13.9_11 compiler cache (/home/jenkins/.gradle/caches/7.2/zinc-1.3.5_2.13.9_11). It is currently in use by another Gradle instance.
```

**Comment by praetp** [comment]
Seen again on Gradle 7.6.1
