### ISSUE TITLE
Transitive dependency for list of version ranges break build.

### ISSUE THREAD

**Issue by gavenkoa** [gradle/gradle#3869]
I  have uncontrolled transitive dependency which declare list of version ranges.

https://stackoverflow.com/questions/47925540/does-gradle-support-comma-in-version-to-specify-several-ranges/

    apply plugin: 'java'

    repositories {
        maven { url 'http://ilcvs02/artifactory/libs-release' }
        mavenCentral()
        jcenter()
    }

    dependencies {
        compile(group: 'org.webjars.npm', name: 'glob', version: '5.0.15') {
            exclude module: 'minimatch'
        }
        compile 'org.webjars.npm:minimatch:3.0.4'
    }

    // compile 'org.webjars.npm:minimatch:2.+,3.+'
    // compile 'org.webjars.npm:minimatch:[2,3),[3,4)'

    task dump {
        doLast { configurations.runtime.each { println it } }
    }

`gradle dump  --stacktrace`:

    * What went wrong:
    Execution failed for task ':dump'.
    > Could not resolve all files for configuration ':runtime'.
       > Could not find org.webjars.npm:minimatch:[2,3),[3,4).
         Searched in the following locations:
             https://repo1.maven.org/maven2/org/webjars/npm/minimatch/[2,3),[3,4)/minimatch-[2,3),[3,4).pom
             https://repo1.maven.org/maven2/org/webjars/npm/minimatch/[2,3),[3,4)/minimatch-[2,3),[3,4).jar
             https://jcenter.bintray.com/org/webjars/npm/minimatch/[2,3),[3,4)/minimatch-[2,3),[3,4).pom
             https://jcenter.bintray.com/org/webjars/npm/minimatch/[2,3),[3,4)/minimatch-[2,3),[3,4).jar
         Required by:
             project : > org.webjars.npm:glob:5.0.15
    * Exception is:
    org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dump'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
    Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':runtime'.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:892)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1500(DefaultConfiguration.java:114)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:866)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(DefaultConfiguration.java:384)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
        at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:68)
        at build_6wa2dqsclsuh6xn8zcwbxj3sn$_run_closure3$_closure6.doCall(C:\home\devel\1\build.gradle:23)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:700)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:673)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 28 more
    Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find org.webjars.npm:minimatch:[2,3),[3,4).
    Searched in the following locations:
        https://repo1.maven.org/maven2/org/webjars/npm/minimatch/[2,3),[3,4)/minimatch-[2,3),[3,4).pom
        https://repo1.maven.org/maven2/org/webjars/npm/minimatch/[2,3),[3,4)/minimatch-[2,3),[3,4).jar
        https://jcenter.bintray.com/org/webjars/npm/minimatch/[2,3),[3,4)/minimatch-[2,3),[3,4).pom
        https://jcenter.bintray.com/org/webjars/npm/minimatch/[2,3),[3,4)/minimatch-[2,3),[3,4).jar
    Required by:
        project : > org.webjars.npm:glob:5.0.15
        at org.gradle.internal.resolve.result.DefaultBuildableComponentResolveResult.notFound(DefaultBuildableComponentResolveResult.java:38)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolveModule(RepositoryChainComponentMetaDataResolver.java:105)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolve(RepositoryChainComponentMetaDataResolver.java:60)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.ComponentResolversChain$ComponentMetaDataResolverChain.resolve(ComponentResolversChain.java:93)
        at org.gradle.api.internal.artifacts.ivyservice.clientmodule.ClientModuleResolver.resolve(ClientModuleResolver.java:45)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$ComponentState.resolve(DependencyGraphBuilder.java:854)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$ComponentState.getMetaData(DependencyGraphBuilder.java:865)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$EdgeState.calculateTargetConfigurations(DependencyGraphBuilder.java:446)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$EdgeState.attachToTargetConfigurations(DependencyGraphBuilder.java:417)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.attachToTargetRevisionsSerially(DependencyGraphBuilder.java:223)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.resolveEdges(DependencyGraphBuilder.java:213)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.traverseGraph(DependencyGraphBuilder.java:148)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:121)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:86)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolveGraph(DefaultConfigurationResolver.java:138)
        at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveGraph(ShortCircuitEmptyConfigurationResolver.java:73)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:66)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$4.run(DefaultConfiguration.java:463)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:455)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:439)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1600(DefaultConfiguration.java:114)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getSelectedArtifacts(DefaultConfiguration.java:875)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:863)
        ... 41 more

Temporary workaround:

    dependencies {
        compile(group: 'org.webjars.npm', name: 'glob', version: '5.0.15') {
            exclude module: 'minimatch'
        }
        compile 'org.webjars.npm:minimatch:3.0.4'
    }

**Comment by bmuschko** [comment]
@jjohannes @bigdaz @melix Could you guys provide some insight here?

**Comment by melix** [comment]
A list of version ranges is not a valid selector, so no wonder the dependency resolution engine fails. One option is to use the new `withDependencies` block to fix bad metadata. See https://github.com/gradle/gradle/blob/master/gradle/dependencies.gradle#L177-L179 for examples.

Note that this is a non documented API (documentation is planned for 4.6).

**Comment by napstr** [comment]
>A list of version ranges is not a valid selector

It is in Maven. Sadly you can't consume Maven projects that use a set of version ranges inside of a gradle build, making a smooth migration of a whole build pipeline to Gradle's take on dependency resolution rather painful / actually impossible, because the other way round the same is true: Maven can't consume the version ranges Gradle puts into the published poms (like '+').

**Comment by dagguh** [comment]
If Gradle could support version ranges list, it would tremendously help with SemVer dependencies.
E.g. supporting multiple major versions is currently unfeasible only because of Gradle limitations.

Say a `report` module depends on `data`. The `data` module uses SemVer, so `report` can safely depend on `data:[1.0.0,2.0.0)`. New `data:1.x.y` releases can be consumed automatically. Or if we want stable build, we can use dependency locks, but the range declaration is still useful, for `report` consumers to calculate the final overlap of all version ranges.

So `data` is used in many places, but had to break source compatibility since `1.0.0` and had to be bumped to `2.0.0`, admitting to the incompatibility. Some of `data` consumers switched to `[2.0.0,3.0.0)` and some stayed behind on `[1.0.0,2.0.0)`.
However, `report` was robust enough to be able to support BOTH major versions: `[1.0.0,3.0.0)`. Good job `report` 👍 

Time passes, and `data` gets a new awesome feature in `2.1.0` 🎉 . They even backported it to `1.1.0`. And `report` wants to use it, but if it simply bumps to `[2.1.0,3.0.0)`, it means it effectively drops support of `data:1` and throws a wrench into its consumers, who might have counted on that support, especially with the transitive trees of other participants.
It would be perfect, if `report` could depend on `data:[1.1.0,2.0.0),[2.1.0,3.0.0)`. It can do so in Maven, but if it uses Gradle, then bad luck. It is currently counter-productive to support multiple major versions of a dependency. Not because compatibility is difficult (we can manage that), but merely because Gradle doesn't support a notation.

**Comment by dagguh** [comment]
It would still be nice to depend on multiple ranges.

**Comment by jmini** [comment]
I found an other case where a POM on maven central contains multiple version ranges:
[`plugin-node-resolve-15.2.3.pom`](https://repo1.maven.org/maven2/org/mvnpm/at/rollup/plugin-node-resolve/15.2.3/plugin-node-resolve-15.2.3.pom)

```xml
<dependency>
	<groupId>org.mvnpm</groupId>
	<artifactId>rollup</artifactId>
	<version>[2.78.0,3),[3.0.0,4),[4.0.0,5)</version>
</dependency>
```
(using the `${org.mvnpm-rollup.version}` variable that I have resolved here)

The [maven central UI](https://central.sonatype.com/artifact/org.mvnpm.at.rollup/plugin-node-resolve/dependencies) does not complain and displays in the "Dependencies" tab:

<img width="1217" alt="maven central UI displaying 'Version: [2.78.0,3),[3.0.0,4),[4.0.0,5)' " src="https://github.com/user-attachments/assets/5d1e8060-897c-4f95-a1db-8067ad30eacf">

---

**Reproducer with gradle:**

<details><summary>build.gradle file</summary>
<p>

```
plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'org.mvnpm:flowbite:2.5.1' 
}
```

</p>
</details> 

Gradle is not able to resolve it. Output of the `gradle dependencies --configuration=compileClasspath` command:

```
compileClasspath - Compile classpath for source set 'main'.
\--- org.mvnpm:flowbite:2.5.1
     +--- org.mvnpm.at.popperjs:core:[2.9.3,3) -> 2.11.8
     +--- org.mvnpm:mini-svg-data-uri:[1.4.3,2) -> 1.4.4
     \--- org.mvnpm:flowbite-datepicker:[1.3.0,2) -> 1.3.0
          +--- org.mvnpm.at.rollup:plugin-node-resolve:[15.2.3,16) -> 15.2.3
          |    +--- org.mvnpm.at.rollup:pluginutils:[5.0.1,6) -> 5.1.0
          |    |    +--- org.mvnpm.at.types:estree:[1.0.0,2) -> 1.0.5
          |    |    +--- org.mvnpm:estree-walker:[2.0.2,3) -> 2.0.2
          |    |    \--- org.mvnpm:picomatch:[2.3.1,3) -> 2.3.1
          |    +--- org.mvnpm.at.types:resolve:1.20.2
          |    +--- org.mvnpm:deepmerge:[4.2.2,5) -> 4.3.1
          |    +--- org.mvnpm:is-builtin-module:[3.2.1,4) -> 3.2.1
          |    |    \--- org.mvnpm:builtin-modules:[3.3.0,4) -> 3.3.0
          |    +--- org.mvnpm:is-module:[1.0.0,2) -> 1.0.0
          |    +--- org.mvnpm:resolve:[1.22.1,2) -> 1.22.8
          |    |    +--- org.mvnpm:is-core-module:[2.13.0,3) -> 2.15.1
          |    |    |    \--- org.mvnpm:hasown:[2.0.2,3) -> 2.0.2
          |    |    |         \--- org.mvnpm:function-bind:[1.1.2,2) -> 1.1.2
          |    |    +--- org.mvnpm:path-parse:[1.0.7,2) -> 1.0.7
          |    |    \--- org.mvnpm:supports-preserve-symlinks-flag:[1.0.0,2) -> 1.0.0
          |    \--- org.mvnpm:rollup:[2.78.0,3),[3.0.0,4),[4.0.0,5) FAILED
          \--- org.mvnpm:flowbite:[2.0.0,3) -> 2.5.1 (*)

(*) - Indicates repeated occurrences of a transitive dependency subtree. Gradle expands transitive dependency subtrees only once per project; repeat occurrences only display the root of the subtree, followed by this annotation.
```

A more realistic usage (quarkus project) produces this error:

```
* What went wrong:
Execution failed for task ':quarkusGenerateCodeDev'.
> Could not resolve all files for configuration ':quarkusDevBaseRuntimeClasspathConfiguration'.
   > Could not find org.mvnpm:rollup:[2.78.0,3),[3.0.0,4),[4.0.0,5).
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/mvnpm/rollup/%5B2.78.0,3),%5B3.0.0,4),%5B4.0.0,5)/rollup-%5B2.78.0,3),%5B3.0.0,4),%5B4.0.0,5).pom
     Required by:
         project : > org.mvnpm:flowbite:2.5.1 > org.mvnpm:flowbite-datepicker:1.3.0 > org.mvnpm.at.rollup:plugin-node-resolve:15.2.3
```

The work-around is to add a constraint to help gradle with the resolution of `[2.78.0,3),[3.0.0,4),[4.0.0,5)`:

```
dependencies {
    compileOnly 'org.mvnpm:flowbite:2.5.1' 
    constraints {
        compileOnly('org.mvnpm:rollup:4.21.0') {
            because 'Latest available at time of writing, needed because the pom of "org.mvnpm.at.rollup:plugin-node-resolve" can not be interpreted by gradle'
        }
    }
}
```

---

By comparison this is something that is well supported by maven:

Output of `mvn dependency:tree` in a similar project:
```
[INFO] +- org.mvnpm:flowbite:jar:2.5.1:provided
[INFO] |  +- org.mvnpm.at.popperjs:core:jar:2.11.8:provided (version selected from constraint [2.9.3,3))
[INFO] |  +- org.mvnpm:mini-svg-data-uri:jar:1.4.4:provided (version selected from constraint [1.4.3,2))
[INFO] |  \- org.mvnpm:flowbite-datepicker:jar:1.3.0:provided (version selected from constraint [1.3.0,2))
[INFO] |     \- org.mvnpm.at.rollup:plugin-node-resolve:jar:15.2.3:provided (version selected from constraint [15.2.3,16))
[INFO] |        +- org.mvnpm.at.rollup:pluginutils:jar:5.1.0:provided (version selected from constraint [5.0.1,6))
[INFO] |        |  +- org.mvnpm.at.types:estree:jar:1.0.5:provided (version selected from constraint [1.0.0,2))
[INFO] |        |  +- org.mvnpm:estree-walker:jar:2.0.2:provided (version selected from constraint [2.0.2,3))
[INFO] |        |  \- org.mvnpm:picomatch:jar:2.3.1:provided (version selected from constraint [2.3.1,3))
[INFO] |        +- org.mvnpm.at.types:resolve:jar:1.20.2:provided
[INFO] |        +- org.mvnpm:deepmerge:jar:4.3.1:provided (version selected from constraint [4.2.2,5))
[INFO] |        +- org.mvnpm:is-builtin-module:jar:3.2.1:provided (version selected from constraint [3.2.1,4))
[INFO] |        |  \- org.mvnpm:builtin-modules:jar:3.3.0:provided (version selected from constraint [3.3.0,4))
[INFO] |        +- org.mvnpm:is-module:jar:1.0.0:provided (version selected from constraint [1.0.0,2))
[INFO] |        +- org.mvnpm:resolve:jar:1.22.8:provided (version selected from constraint [1.22.1,2))
[INFO] |        |  +- org.mvnpm:is-core-module:jar:2.15.1:provided (version selected from constraint [2.13.0,3))
[INFO] |        |  |  \- org.mvnpm:hasown:jar:2.0.2:provided (version selected from constraint [2.0.2,3))
[INFO] |        |  |     \- org.mvnpm:function-bind:jar:1.1.2:provided (version selected from constraint [1.1.2,2))
[INFO] |        |  +- org.mvnpm:path-parse:jar:1.0.7:provided (version selected from constraint [1.0.7,2))
[INFO] |        |  \- org.mvnpm:supports-preserve-symlinks-flag:jar:1.0.0:provided (version selected from constraint [1.0.0,2))
[INFO] |        \- org.mvnpm:rollup:jar:4.21.0:provided (version selected from constraint [3.0.0,4), [4.0.0,5), [2.78.0,3))
```

See the last line: `version selected from constraint [3.0.0,4), [4.0.0,5), [2.78.0,3)`

**Comment by jmini** [comment]
From the maven docs:

> Multiple requirements are separated by commas.

sources: https://maven.apache.org/pom.html#Dependency_Version_Requirement_Specification
