### ISSUE TITLE
Task input validation calls get on Provider

### ISSUE THREAD

**Issue by mduesterhoeft** [gradle/gradle#3879]
### Expected Behavior

Task properties of type `org.gradle.api.provider.Property` can be optional and task input validation should not call `get()` on these properties, because it throws an `java.lang.IllegalStateException` if the value is not present

### Current Behavior

The `get()` method on task input properties of type `org.gradle.api.provider.Property` is called during validation. This causes this exception for properties that do not contain a value.

```
java.lang.IllegalStateException: No value has been specified for this provider.
        at org.gradle.api.internal.provider.Providers$1.get(Providers.java:32)
        at org.gradle.api.internal.provider.DefaultPropertyState.get(DefaultPropertyState.java:89)
        at org.gradle.util.DeferredUtil.unpack(DeferredUtil.java:39)
        at org.gradle.api.internal.project.taskfactory.TaskPropertyInfo$3.validate(TaskPropertyInfo.java:105)
        at org.gradle.api.internal.tasks.TaskPropertyValue.validate(TaskPropertyValue.java:38)
        at org.gradle.api.internal.tasks.DefaultTaskInputPropertySpec.validate(DefaultTaskInputPropertySpec.java:53)
        at org.gradle.api.internal.tasks.DefaultTaskInputs.validate(DefaultTaskInputs.java:168)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:47)
```

As far as I could see `DeferredUtil.unpack` is to blame:

```
else if (current instanceof Provider) {
     return ((Provider<?>) current).get();
 }
```

I think it should rather be `((Provider<?>) current).getOrNull()`

### Context

I am using gradle 4.3.

I have a task property defined like this:

```
    @Input
    @Optional
    Property<String> apiBaseUri = project.objects.property(String)
```

When accessing this optional property I am taking care to check if a value exists before getting it:
```
if (apiBaseUri.isPresent()) {
  writer.write("baseUri: ${apiBaseUri.get()}\n")
}
```

If I run the task with an empty value I get the exception stated above.

### Steps to Reproduce (for bugs)

This sample project can be used to reproduce:
https://github.com/ePages-de/restdocs-raml/tree/master/restdocs-raml-sample

- in the build.gradle remove the contents of the `ramldoc` extension block
- run `./gradlew ramldoc`

### Your Environment

 * Build scan URL: 
https://gradle.com/s/axrevjt2zhld4

**Comment by mduesterhoeft** [comment]
sorry - seems to work with 4.4
