### ISSUE TITLE
Build operation trace doesn't work with GradleBuild

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#3983]
### Expected Behavior

Running this build with `-Dorg.gradle.internal.operations.trace=build.log` should succeed:

```gradle
task otherBuild(type: GradleBuild) {
    dir = 'other'
    startParameter.searchUpwards = false
}
```

### Current Behavior

Executing the above build fails with an exception while the `otherBuild` task is finishing:

```text
java.lang.AssertionError: parentChildren != null '    {"id":16,"endTime":1515166868990}' from /Users/lptr/Workspace/gradle/gradle/build/tmp/test files/GradleBuildBuildOperationsIntegrationTest/can_run_a_build_wit...ion_trace/80xp7/build.log-log.txt
	at org.gradle.internal.operations.trace.BuildOperationTrace$2.processLine(BuildOperationTrace.java:282)
	at com.google.common.io.CharStreams.readLines(CharStreams.java:317)
	at com.google.common.io.CharSource.readLines(CharSource.java:240)
	at org.gradle.internal.operations.trace.BuildOperationTrace.readLogToTreeRoots(BuildOperationTrace.java:226)
	at org.gradle.internal.operations.trace.BuildOperationTrace.stop(BuildOperationTrace.java:129)
	at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:103)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.stop(DefaultServiceRegistry.java:638)
	at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:103)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.stop(DefaultServiceRegistry.java:638)
	at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:103)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.stop(DefaultServiceRegistry.java:638)
	at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:103)
	at org.gradle.internal.service.DefaultServiceRegistry$OwnServices.stop(DefaultServiceRegistry.java:530)
	at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:103)
	at org.gradle.internal.service.DefaultServiceRegistry$CompositeServiceProvider.stop(DefaultServiceRegistry.java:1043)
	at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:103)
	at org.gradle.internal.service.DefaultServiceRegistry.close(DefaultServiceRegistry.java:268)
	at org.gradle.internal.concurrent.CompositeStoppable$2.stop(CompositeStoppable.java:88)
	at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:103)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:62)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:32)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:69)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:30)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:45)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
```

**Comment by lptr** [comment]
@ldaley can you please take a look?

**Comment by lptr** [comment]
I've added an integration test to reproduce the issue on `master`, see `GradleBuildBuildOperationsIntegrationTest`.

**Comment by ldaley** [comment]
Fixed by https://github.com/gradle/gradle/pull/4560.
