### ISSUE TITLE
Wrong classpath withDebug(true) VS Checkstyle (ant) task

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#3995]
### Expected Behavior
```log
:compileJava
:processResources NO-SOURCE
:classes
:checkstyleMain

BUILD SUCCESSFUL in 4s
2 actionable tasks: 2 executed
```
### Current Behavior
```log
:compileJava
:processResources NO-SOURCE
:classes
:checkstyleMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkstyleMain'.
> groovy/util/AntBuilder

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':checkstyleMain'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.NoClassDefFoundError: groovy/util/AntBuilder
	at org.gradle.internal.classloader.MultiParentClassLoader.loadClass(MultiParentClassLoader.java:82)
	at org.gradle.internal.classloader.CachingClassLoader.loadClass(CachingClassLoader.java:54)
	at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder.newInstanceOf(DefaultIsolatedAntBuilder.java:165)
	at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder.access$200(DefaultIsolatedAntBuilder.java:48)
	at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder$2.execute(DefaultIsolatedAntBuilder.java:138)
	at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder$2.execute(DefaultIsolatedAntBuilder.java:134)
	at org.gradle.api.internal.project.antbuilder.ClassPathToClassLoaderCache.withCachedClassLoader(ClassPathToClassLoaderCache.java:134)
	at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder.execute(DefaultIsolatedAntBuilder.java:128)
	at org.gradle.api.internal.project.IsolatedAntBuilder$execute$0.call(Unknown Source)
	at org.gradle.api.plugins.quality.internal.CheckstyleInvoker.invoke(CheckstyleInvoker.groovy:51)
	at org.gradle.api.plugins.quality.Checkstyle.run(Checkstyle.java:153)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:780)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:747)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 29 more
Caused by: java.lang.ClassNotFoundException: groovy.util.AntBuilder
	... 53 more


* Get more help at https://help.gradle.org

BUILD FAILED in 4s
2 actionable tasks: 2 executed
```
### Context
I'm trying to write a plugin to apply quality plugins to Android projects: https://github.com/TWiStErRob/net.twisterrob.gradle.quality

I'm doing so with coverage through integration tests. I have all the tasks running successfully, even [a full very complex Android build](https://github.com/TWiStErRob/net.twisterrob.gradle.quality/blob/e4767ec62bb6ccc7e9c770c023d344a67e0ca7af/checkstyle/src/test/groovy/net/twisterrob/gradle/checkstyle/CheckStylePluginTest.groovy#L67-L94), and a [double-nested Gradle Test Kit run](https://github.com/TWiStErRob/net.twisterrob.gradle.quality/blob/e4767ec62bb6ccc7e9c770c023d344a67e0ca7af/test/src/test/groovy/net/twisterrob/gradle/test/TestPluginTest.groovy). But when I add `withDebug(true)` all hell breaks loose and I can't debug my code because of this issue. This really slows down development as I can't see the context and have to fall back to `println` debugging.

### Investigation
I've spent a few hours debugging classloading and looked around here:
```java
class DefaultIsolatedAntBuilder {
	DefaultIsolatedAntBuilder() {
		this.antAdapterLoader = new VisitableURLClassLoader(baseAntLoader, gradleCoreUrls);
	}
	private Object newInstanceOf(String className) {
		try {
			return antAdapterLoader.loadClass(className).newInstance();
		} catch (Exception e) {
			// should never happen
			throw UncheckedException.throwAsUncheckedException(e);
		}
	}
}
class URLClassLoader {
	protected Class<?> findClass(final String name) {
		try {
			result = AccessController.doPrivileged(
				new PrivilegedExceptionAction() {
					public Class<?> run() {
						Resource res = ucp.getResource(path, false);
						if (res != null) {
}
```
What I've seen by debugging the test run with `withDebug` and a real external run with `-Dorg.gradle.debug=true` is that the classloaders are a bit different. The strange thing is that the difference may not necessarily affect this issue. So, it may a big red herring, or the key, not sure. Anyway here are the dumps and the dumper code: [ClassLoader dumps.zip](https://github.com/gradle/gradle/files/1610318/ClassLoader.dumps.zip) (take a look at "step 1", "step 2", etc. "miss" is CNFE and "hit" is successful load)

### Steps to Reproduce (for bugs)
Set up project: [gradle-kit-embed-debug-ant.zip](https://github.com/gradle/gradle/files/1610304/gradle-kit-embed-debug-ant.zip) and `gradle test`
Files inside (for easy web view):
[`build.gradle`](https://github.com/gradle/gradle/files/1610307/build.gradle.txt)
[`src/test/groovy/MyTest.groovy`](https://github.com/gradle/gradle/files/1610302/MyTest.groovy.txt)

```gradle
// automatically adds gradleTestKit() and stuff
apply plugin: 'java-gradle-plugin'
```
```groovy
// something like this, the important part is withDebug in my experience
GradleRunner.create().withArguments(args).withDebug(true).build();
// it's also important that :checkstyleMain is not NO-SOURCE, so you need at least 1 Java file, may it be empty
```

### Your Environment
Reproduced on both Gradle 4.2.1, 4.4 and 4.4.1
```
P:\projects\bugs\gradle-kit-embed-debug-ant>gradle --version

------------------------------------------------------------
Gradle 4.4
------------------------------------------------------------

Build time:   2017-12-06 09:05:06 UTC
Revision:	 cf7821a6f79f8e2a598df21780e3ff7ce8db2b82

Groovy:	   2.4.12
Ant:		  Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:		  1.8.0_121 (Oracle Corporation 25.121-b13)
OS:		   Windows 10 10.0 amd64
```

**Comment by tgeens** [comment]
Found this GH issue after bumping into this too, using Gradle 5.5

I can confirm using `.withDebug(false)` makes the `NoClassDefFoundError` go away.

**Comment by ov7a** [comment]
Sorry for the late reply.

Since [7.5](https://docs.gradle.org/current/userguide/upgrading_version_7.html#checkstyle_worker_api), the Checkstyle plugin uses the Gradle worker API to run Checkstyle as an external worker process. 

So, this issue can be considered fixed. If you experience a similar problem, please open a new issue.
