### ISSUE TITLE
Gradle crashes with NPE after task completion

### ISSUE THREAD

**Issue by kurguzov** [gradle/gradle#4024]
When I run `./gradlew libs:apiclient:unittest libs:wsnext:unittest` Gradle falls with exception:
```
FAILURE: Build failed with an exception.

* What went wrong:
java.lang.NullPointerException (no error message)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.NullPointerException
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.recordTaskStarted(DefaultTaskExecutionPlan.java:819)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.access$2700(DefaultTaskExecutionPlan.java:92)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan$9.transform(DefaultTaskExecutionPlan.java:602)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan$9.transform(DefaultTaskExecutionPlan.java:591)
        at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.selectNextTask(DefaultTaskExecutionPlan.java:591)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.access$2300(DefaultTaskExecutionPlan.java:92)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan$8.transform(DefaultTaskExecutionPlan.java:565)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan$8.transform(DefaultTaskExecutionPlan.java:546)
        at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:546)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)


* Get more help at https://help.gradle.org

BUILD FAILED in 1m 40s
17 actionable tasks: 6 executed, 11 up-to-date
```

### Expected Behavior
No exception is thrown, task completes successfully.

### Current Behavior
Build seems to be finished without errors, but gradle itself falls with exception above, I cannot continue to next steps (due to non-zero gradle exit code)

### Context

I perform per-commit unit testing via gradle task for specific gradle modules instead of the whole project. Module libs:apiclient:unittest does not contain any tests at all, and it depends on libs:wsnext:unittest. Module libs:wsnext:unittest contains some tests.

### Steps to Reproduce (for bugs)
Unfortunately, I couldn't reproduce this issue on pure project, even on our project is started reproducing unexpectedly. Our project cannot be shared due to NDA.
My findings are:
1. if I run `./gradlew libs:apiclient:unittest libs:wsnext:unittest`, gradle crashes after task completion, but if  I run `./gradlew libs:wsnext:unittest libs:apiclient:unittest` - it completes successfully
2. if I run `./gradlew libs:apiclient:unittest libs:wsnext:unittest -x libs:apiclient:unittest` no failure occures
3. when I change project state to older revisions (even half year ago) - the problem still exists
4. when I change gradle version to any of 4.*, the problem is reproduced, when I rollback gradle to 3.5, the problem goes away on the same project state.

### Your Environment
 * Build scan URL: 
Unfortunately, I cannot publish scan, since I cannot preview it for privacy information before publishing.

**Comment by bmuschko** [comment]
Could you please provide more information about your environment (OS, console etc.) and the runtime flags (`--parallel`, `--configure-on-demand` etc.) you are using? Can you confirm that the issue already occurs with Gradle 4.0?

**Comment by kurguzov** [comment]
MacOs High Sierra, 10.13.2 (17C88) on my mac, as well as on teamcity build agents in docker (Linux)
I've run both with --parallel and not (maxParallelForks = 1): it does not affect the result.

However, If I add --configure-on-demand option, the problem disappears.

**Comment by bmuschko** [comment]
Thanks for the additional information. What version Gradle produces the stack trace you posted above? Could you maybe try to simulate the issue with a sample project? I see that you already tried but it would be super helpful to have a reproducible example.

**Comment by kurguzov** [comment]
Yes, I do understand, however without understanding the reason it is very expensive to build a sample project. Meanwhile, I can still reproduce it on my project, and if some other experiment can be helpful, I can perform it and provide you with results.

**Comment by remmeier** [comment]
the issue is back for me in two unrelated gradle builds. Still not able to share those builds unfortunately. But at least I can now reproduce it. Clean build crashes about 75% of the time having 8 cores + SMT. A new stacktrace based on Gradle 10.1 (I started putting more output too ProgressLogEventGenerator, so its line numbers may not exactly match):

`
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':management:management-service:integrationTest'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:105)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:79)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.IllegalStateException: ProgressComplete (9326)  op=null prevStarted=null
        at org.gradle.internal.logging.sink.ProgressLogEventGenerator.onComplete(ProgressLogEventGenerator.java:80)
        at org.gradle.internal.logging.sink.ProgressLogEventGenerator.onOutput(ProgressLogEventGenerator.java:56)
        at org.gradle.internal.logging.console.BuildLogLevelFilterRenderer.onOutput(BuildLogLevelFilterRenderer.java:41)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy0.onOutput(Unknown Source)
        at org.gradle.internal.logging.sink.OutputEventTransformer.onOutput(OutputEventTransformer.java:88)
        at org.gradle.internal.logging.sink.OutputEventRenderer.onOutput(OutputEventRenderer.java:436)
        at org.gradle.internal.logging.sink.OutputEventListenerManager$1.onOutput(OutputEventListenerManager.java:36)
        at org.gradle.internal.logging.services.ProgressLoggingBridge.completed(ProgressLoggingBridge.java:33)
        at org.gradle.internal.logging.progress.DefaultProgressLoggerFactory$ProgressLoggerImpl.completed(DefaultProgressLoggerFactory.java:262)
        at org.gradle.internal.logging.progress.DefaultProgressLoggerFactory$ProgressLoggerImpl.completed(DefaultProgressLoggerFactory.java:255)
        at org.gradle.api.internal.tasks.testing.logging.TestWorkerProgressListener.completed(TestWorkerProgressListener.java:70)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy82.completed(Unknown Source)
        at org.gradle.api.internal.tasks.testing.results.StateTrackingTestResultProcessor.completed(StateTrackingTestResultProcessor.java:96)
        at org.gradle.api.internal.tasks.testing.results.AttachParentTestResultProcessor.completed(AttachParentTestResultProcessor.java:56)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:29)
        at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:133)
        at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:34)
        at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:73)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        ... 3 more
`

What I can say is that that given event to be completed never reached the matching onStart in ProgressLogEventGenerator. As such it is not in the map and triggers a NPE. On the other side, a matching ProgressStartEvent is created somewhere (I started storing static maps of all the events to later track down what is missing). 

`
In the one above it was related to a testing event (ProgressStart (p:22006 parent p:21983 b:21999) Test Execution).  One of the suspects is TestWorkerProgressListener where I'm not sure how robust it really is (like that "description" usage as key seems odd). But there are also other stacktraces also look differently, like:

Caused by: java.lang.IllegalStateException: ProgressComplete (59446)  op=null generatorOnStart=null eventConstructor=ProgressStart (p:59446 parent p:59294 b:59446) Unpack build cache entry ab3897072d9ef0c162a2624cf21a8efc
        at org.gradle.internal.logging.sink.ProgressLogEventGenerator.onComplete(ProgressLogEventGenerator.java:82)
        at org.gradle.internal.logging.sink.ProgressLogEventGenerator.onOutput(ProgressLogEventGenerator.java:56)
        at org.gradle.internal.logging.console.BuildLogLevelFilterRenderer.onOutput(BuildLogLevelFilterRenderer.java:41)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
`
In this case it was related to the build cache. So it could also be a second problem caused by the first by corrupting more things due to the crash.

Pointers where to look would be appreciated. I don't really have an understanding of all the things involved. Maybe it would also be worthwhile for today to just catch that NPE and log it as error or make it a bit more resilient in the area. It seems not necessray to crash the entire build due to some logging issue (the build itself seems fine). Also I see usages of HashMap, LinkedHashMap, not sure whether somewhere some multi-threadin precaution should have to be taken.

**Comment by krmahadevan** [comment]
@kurguzov - This is now happening for the TestNG builds as well.

Here's the complete logs 

Travis Job : https://travis-ci.org/cbeust/testng/jobs/572598436

Build scan report : https://gradle.com/s/jdtmjd5exop2u

Gradle version being used `gradle 5.0`

Github repository : https://github.com/cbeust/testng
