### ISSUE TITLE
Interop between Kotlin DSL and Groovy for set of enums

### ISSUE THREAD

**Issue by Tapchicoma** [gradle/gradle#4030]
### Current Behaviour
I am working on a gradle plugin written in Kotlin DSL. Here is example of plugin extension setup:
```
enum ExtentionEnum {
    SOMENAME1, SOMENAME2, SOMENAME3;
}

open class MyPluginExtention {
    val someField: ExtentionEnum = ExtentionEnum.SOMENAME1

    val someFields: Set<ExtentionEnum> = setOf(ExtentionEnum.SOMENAME3)
}
```
And this is from `build.gradle` of a sample project that applies that plugin:
```
myPluginExtention {
    someField = "somename1"
    someFields = ["somename1"]
}
```
While using string in first case works ok, using string for the second extention property produces following error: `java.lang.String cannot be cast to ExtentionEnum`

Changing `Set<ExtentionEnum>` to `Array<ExtentionEnum>` changes error to `No enum constant`

Changing to `someFields = ["SOMENAME1"]` solves the problem, but it not look nice as usual approach for build setup will be writing `["somename1"]`.

### Expected Behavior

Gradle should cast to set of enums from groovy collection of Strings in the second case.

### Context
Developing plugin in Kotlin DSL that works both with Kotlin project setups and Groovy project setups.

### Your Environment
Gradle wrapper version `4.4.1`.
Plugin url repo: https://github.com/JLLeitschuh/ktlint-gradle

**Comment by JLLeitschuh** [comment]
I was under the impression you could specify some `valueOf` method in groovy and it would reflexively call that for you. Is that not the case?

**Comment by bmuschko** [comment]
Looks like a bug to me. From my perspective the handling of a single enum value vs. `Collection` of enum values should behave consistently.

**Comment by Tapchicoma** [comment]
Another finding.

If I change:
```kotlin
    val someFields: Array<ExtentionEnum> = arrayOf(ExtentionEnum.SOMENAME3)
```
to
```kotlin
    val someFields: List<ExtentionEnum> = listOf(ExtentionEnum.SOMENAME3)
```
and in `build.gradle` will define following:
```gradle
myPluginExtention {
    someFields = ["SOMENAME1"]
}
```
Gradle will show following error:
```kotlin
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to org.jlleitschuh.gradle.ktlint.reporter.ReporterType
        at org.jlleitschuh.gradle.ktlint.reporter.ReporterKt.setMultipleReporters(Reporter.kt:119)
        at org.jlleitschuh.gradle.ktlint.reporter.ReporterKt.applyReporters(Reporter.kt:20)
        at org.jlleitschuh.gradle.ktlint.KtlintPlugin.createCheckTask(KtlintPlugin.kt:164)
        at org.jlleitschuh.gradle.ktlint.KtlintPlugin.access$createCheckTask(KtlintPlugin.kt:32)
        at org.jlleitschuh.gradle.ktlint.KtlintPlugin$addKtLintTasksToKotlinPlugin$1$1.execute(KtlintPlugin.kt:60)
        at org.jlleitschuh.gradle.ktlint.KtlintPlugin$addKtLintTasksToKotlinPlugin$1$1.execute(KtlintPlugin.kt:32)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy26.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:76)
        ... 81 more
```

With `Array` it works fine.

**Comment by JLLeitschuh** [comment]
Is this a Groovy issue, or a Gradle issue?
