### ISSUE TITLE
Gradle 4.5 `ant` call fails with: you can only specify one of the dir and file attributes

### ISSUE THREAD

**Issue by cdancy** [gradle/gradle#4212]
### Summary

When upgrading from gradle `4.3.1` to `4.5` our build fails, when calling out to an `ant` task, with: 

```
* What went wrong:
Execution failed for task ':projects:My-Project:antInstaller'.
> you can only specify one of the dir and file attributes

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':projects:My-Project:antInstaller'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:623)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:578)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: : you can only specify one of the dir and file attributes
        at org.apache.tools.ant.types.AbstractFileSet.dirAndFileAreMutuallyExclusive(AbstractFileSet.java:932)
        at org.apache.tools.ant.types.AbstractFileSet.setFile(AbstractFileSet.java:236)
        at org.tp23.antinstaller.taskdefs.Installer.setAntLib(Installer.java:226)
        at org.apache.tools.ant.IntrospectionHelper$7.set(IntrospectionHelper.java:1117)
        at org.apache.tools.ant.IntrospectionHelper$AttributeSetter.setObject(IntrospectionHelper.java:1512)
        at org.apache.tools.ant.IntrospectionHelper.setAttribute(IntrospectionHelper.java:412)
        at org.apache.tools.ant.RuntimeConfigurable.maybeConfigure(RuntimeConfigurable.java:528)
        at org.apache.tools.ant.RuntimeConfigurable.maybeConfigure(RuntimeConfigurable.java:464)
        at org.apache.tools.ant.Task.maybeConfigure(Task.java:202)
        at org.apache.tools.ant.UnknownElement.configure(UnknownElement.java:200)
        at org.apache.tools.ant.UnknownElement.maybeConfigure(UnknownElement.java:164)
        at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:78)
        at org.gradle.api.internal.project.ant.BasicAntBuilder.doInvokeMethod(BasicAntBuilder.java:103)
        at build_dal73bify9xdce95oszfkuztb$_run_closure16.doCall(/home/dancc/prpc-platform/etc/GUI-Installer/build.gradle:323)
        at build_dal73bify9xdce95oszfkuztb$_run_closure19$_closure93.doCall(/home/dancc/prpc-platform/etc/GUI-Installer/build.gradle:375)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:726)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:699)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 30 more


```

### Expected Behavior
Things to "just work" and not fall over. Nothing changed code wise we're just testing with bumping gradle to `4.5`.

### Current Behavior
The build fails with the aforementioned `you can only specify one of the dir and file attributes` exception message.

### Context
Just trying to run our build with an upgraded version of gradle.

### Steps to Reproduce (for bugs)
Setup a project using the [ant-installer](http://antinstaller.sourceforge.net/installertask.html) with gradle `4.5` and watch things fall over. I've included the stacktrace above as hopefully one can gleam from the code path what is the problem and why it's breaking now.

It should be noted that we are not calling a gradle task but instead wrapping the below in a `doLast` and just "running code" so to speak. The code below was taken from an example from the `ant-installer` link above. 

```
    ant.path(id: "taskdef.cp") { fileset(dir: "$buildDir/compileConfig") }

    file("$buildDir/libs").mkdirs()

    ant.taskdef(name: "installer", classpathref: "taskdef.cp",
            classname: "org.tp23.antinstaller.taskdefs.Installer")

    ant.installer(file: "${buildDir}/libs/${jarName}.jar",
            compress: "true",
            extractType: "SelfExtractor",
            installConfig: configFile,
            buildFile: xmlBuildFile,
            antInstallLib: "$buildDir/licenselib",
            antLib: "$buildDir/compileConfig",
            validateConfig: "true",
            failOnError: "true",
            resProperties: "lib/res/$resFile") {
        fileset(dir: "$buildDir/contents",
                includes: "resources/**, ant_async/**, *.zip, *.jar, *.exe, *.txt, *.xml")
    }
```

### Your Environment
Happens across the board no matter where it's run.

**Comment by bmuschko** [comment]
We upgraded the [bundled Ant version to 1.9.9](https://docs.gradle.org/4.4/release-notes.html#ant-version-upgraded-to-ant-1.9.9) with Gradle 4.4. The new version might treat a fileset differently or Ant Installer is not compatible anymore with the version you got. I can't spot the issue directly. Try changing how you define the installer task. Sounds like you can either use `file` or `dir`.

**Comment by cdancy** [comment]
@bmuschko yeah I did notice you guys bumped to 1.9 from 1.6. The odd part about the above snippet is that, so far as I can tell, we are ONLY defining the `file` attribute and not the `dir` as the exception message states. I tracked things down to [THIS LINE](https://github.com/apache/ant/blob/master/src/main/org/apache/tools/ant/types/AbstractFileSet.java#L242). After following the logic it would seem that the nested `fileset` can't have the `dir` attribute set which feels weird.

**Comment by big-guy** [comment]
Depending on how you look at it, this looks is an Ant regression or a misuse of the Ant FileSet API by the Installer task.

This looks related (from Ant 1.9.8):
```
<fileset>/<zipfileset>/<tarfileset> exhibited undefined
   behavior when both the dir and file attribute have been used on the
   same instance. This will now cause the build to fail.
   Bugzilla Report 59402
```
https://archive.apache.org/dist/ant/RELEASE-NOTES-1.9.8.html

In the Installer task:
https://github.com/tikalk/tikal-ant-installer/blob/master/src_ext/org/tp23/antinstaller/taskdefs/Installer.java#L195-L196

Calling `setFile` twice like this would blow up because the first call would set `dir` and the second would fail the check that only file or dir are used.

I'm not sure if there's a workaround from the Gradle side... does the task still work if you don't pass `antLib`?

**Comment by cdancy** [comment]
@big-guy that does indeed work though now my resulting jar is now missing all of the classes from the now missing ant jars. I'll play around with this a bit and see if I can come up with something before I deem this a success.

**Comment by cdancy** [comment]
Closing issue as removing the `antLib` parameter works combined with updating the produced jar with the missing libs that came from the `antLib` parameter.

**Comment by big-guy** [comment]
Thanks @cdancy -- I raised https://bz.apache.org/bugzilla/show_bug.cgi?id=62071 and it looks like they're going to improve the error message for Ant 1.9.10.  The Installer task would still not work when setting `antLib` because they Ant will still prohibit you from calling `setFile` twice with different arguments.
