### ISSUE TITLE
:buildSrc:codenarcMain SAXParseException while building Gradle under Windows

### ISSUE THREAD

**Issue by grv87** [gradle/gradle#4470]
### Expected Behavior
Gradle can be built under any supported OS.

### Current Behavior
Error building under Windows:
```
Parallel execution is an incubating feature.
:buildSrc:clean
:buildSrc:compileJava
:buildSrc:compileGroovy
:buildSrc:processResources
:buildSrc:classes
:buildSrc:jar
:buildSrc:assemble
:buildSrc:checkstyleMain
:buildSrc:compileTestJava NO-SOURCE
:buildSrc:compileTestGroovy
:buildSrc:processTestResources
:buildSrc:testClasses
:buildSrc:checkstyleTest NO-SOURCE
:buildSrc:codenarcMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:codenarcMain'.
> org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':buildSrc:codenarcMain'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: : org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:116)
	at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:78)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:479)
	at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
	at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:160)
	at org.gradle.api.internal.project.antbuilder.AntBuilderDelegate.nodeCompleted(AntBuilderDelegate.java:118)
	at org.gradle.api.plugins.quality.internal.CodeNarcInvoker$_invoke_closure1.doCall(CodeNarcInvoker.groovy:50)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:53)
	at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder$2.execute(DefaultIsolatedAntBuilder.java:152)
	at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder$2.execute(DefaultIsolatedAntBuilder.java:134)
	at org.gradle.api.internal.project.antbuilder.ClassPathToClassLoaderCache.withCachedClassLoader(ClassPathToClassLoaderCache.java:134)
	at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder.execute(DefaultIsolatedAntBuilder.java:128)
	at org.gradle.api.internal.project.IsolatedAntBuilder$execute$0.call(Unknown Source)
	at org.gradle.api.plugins.quality.internal.CodeNarcInvoker.invoke(CodeNarcInvoker.groovy:47)
	at org.gradle.api.plugins.quality.CodeNarc.run(CodeNarc.java:113)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:784)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:751)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 29 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:994)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.jaxp.validation.StreamValidatorHelper.validate(StreamValidatorHelper.java:155)
	at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(ValidatorImpl.java:116)
	at org.codenarc.ruleset.XmlReaderRuleSet.validateXml(XmlReaderRuleSet.groovy:130)
	at org.codenarc.ruleset.XmlReaderRuleSet.this$2$validateXml(XmlReaderRuleSet.groovy)
	at org.codenarc.ruleset.XmlReaderRuleSet.<init>(XmlReaderRuleSet.groovy:49)
	at org.codenarc.ruleset.XmlFileRuleSet$_closure1.doCall(XmlFileRuleSet.groovy:50)
	at org.codenarc.ruleset.XmlFileRuleSet.<init>(XmlFileRuleSet.groovy:49)
	at org.codenarc.ruleset.RuleSetUtil.loadRuleSetFile(RuleSetUtil.groovy:40)
	at org.codenarc.ruleset.RuleSetUtil$loadRuleSetFile.call(Unknown Source)
	at org.codenarc.CodeNarcRunner$_createRuleSet_closure2.doCall(CodeNarcRunner.groovy:99)
	at org.codenarc.CodeNarcRunner.createRuleSet(CodeNarcRunner.groovy:98)
	at org.codenarc.CodeNarcRunner.execute(CodeNarcRunner.groovy:69)
	at org.codenarc.CodeNarcRunner$execute.call(Unknown Source)
	at org.codenarc.ant.CodeNarcTask.execute(CodeNarcTask.groovy:104)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	... 57 more


* Get more help at https://help.gradle.org

BUILD FAILED in 17s
```

### Steps to Reproduce (for bugs)
* Clone Gradle repository on Windows machine
* Run `gradlew installAll -Pgradle_installPath=U:\gradle-source-build`

### Context
* Tried also tagged version 4.3.1, the same error
* No error under Debian

### My Environment
* OS Windows 7 SP1
* Oracle JDK 1.8.0u152
* Build scan URL (for buildSrc): https://scans.gradle.com/s/iegcbas32xc64

**Comment by grv87** [comment]
I see that `config/codenarc.xml` contains no XML header. I tried to add it, but that didn't help.

**Comment by grv87** [comment]
Tried also:
* update JDK to 8u162
* use CodeNarc 0.27.0 and 1.1

Didn't help.

**Comment by blindpirate** [comment]
Well, thanks for reporting, but it works on my Windows 7 machine. After looking into your stacktrace, I tend to think it as a locale or encoding issue. See here: https://stackoverflow.com/questions/5138696/org-xml-sax-saxparseexception-content-is-not-allowed-in-prolog

I think the reason why you're the only person encountering this issue is the missing XML encoding header in `config/codenarc.xml`, an extra XML encoding header will make this issue disappear.

**Comment by grv87** [comment]
Adding encoding header to `config.xml` didn't help. Also, CodeNarc built-in rulesets don't have XML headers either. I tried to add there too, no change.
I use CodeNarc in my own project, so this by its own can't be a reason.

I'll try another machine.

Could it be an issue with `xerces`? I know there are some incompatibilities between versions.

**Comment by big-guy** [comment]
Are you still seeing this on master/5.x?  Please reopen if you are, thanks!

**Comment by grv87** [comment]
Unfortunately, the problem is still here, with Gradle 5.2.1 and JDK 11.
But if nobody could reproduce it then this should be a problem with my machine or user.
I'll reopen if I find otherwise.

**Comment by grv87** [comment]
The problem is how CodeNarc handles file paths. In my case, I was running build from `#all\...` directory, and CodeNarc doesn't accept `#`.
I've opened CodeNarc/CodeNarc#400, let's see what they say.

Anyway, there is another problem, with comma. And this should be addressed in Gradle some way.

**Comment by big-guy** [comment]
@grv87 what's the issue with comma?

**Comment by grv87** [comment]
@big-guy, see my P.S. in mentioned CodeNarc issue.
CodeNarc uses comma to separate ruleset files. If filename contains the comma then it is interpreted as two files.

In current CodeNarc implementation this could be overcome using percent encoding.
Here:
https://github.com/gradle/gradle/blob/9eb4f1337a8befe0ffc0d77b55de5b0096416dbc/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/CodeNarcInvoker.groovy#L50
commas in `configFile` should be replaced with `%2C`.
But I'm not sure that CodeNarc team considers this as a correct workaround, not a bug.

**Comment by grv87** [comment]
Another question is why CodeNarc task/plugin accepts single `configFile` whenever CodeNarc itself accepts multiple.

**Comment by wolfs** [comment]
@grv87 Did you manage to fix your issue? I'll close the current issue. Please report back if that is still a problem for you.

**Comment by grv87** [comment]
No, I did not (except obvious workarounds).
The problem is on CodeNarc side, it's OK to close this issue
