### ISSUE TITLE
Build fails sometimes due to ` java.lang.IllegalStateException: initialize must be called for meta class of class`

### ISSUE THREAD

**Issue by daniellansun** [gradle/gradle#4505]
### Expected Behavior
I hope `install` task runs successfully.

### Current Behavior
Error occurred:
```
Execution failed for task ':groovy-jmx:install'. java.lang.IllegalStateException: initialize must be called for meta class of class upload_bk1wuzgd06t1lgmqujau96ips$_run_closure5(class org.codehaus.groovy.runtime.metaclass.ClosureMetaClass) to complete initialisation process before any invocation or field/property access can be done

[11:39:11][Gradle failure report] 	at org.gradle.internal.metaobject.BeanDynamicObject$GroovyObjectAdapter.invokeOpaqueMethod(BeanDynamicObject.java:579)
[11:39:11][Gradle failure report] 	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:506)
[11:39:11][Gradle failure report] 	at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
[11:39:11][Gradle failure report] 	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:78)
[11:39:11][Gradle failure report] 	at upload_bk1wuzgd06t1lgmqujau96ips$_run_closure5$_closure18$_closure29.doCall(/var/teamcity/buildagent-jdk8/work/cba52975ead8186f/gradle/upload.gradle:127)
[11:39:11][Gradle failure report] 	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:726)
[11:39:11][Gradle failure report] 	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:699)
[11:39:11][Gradle failure report] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
[11:39:11][Gradle failure report] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
[11:39:11][Gradle failure report] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
[11:39:11][Gradle failure report] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
[11:39:11][Gradle failure report] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
[11:39:11][Gradle failure report] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
[11:39:11][Gradle failure report] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
[11:39:11][Gradle failure report] 	... 106 more
[11:39:11][Gradle failure report] 
[11:39:11][Gradle failure report] 
[11:39:11][Gradle failure report] * Get more help at https://help.gradle.org
[11:39:11][Gradle failure report] 
[11:39:11][Gradle failure report] BUILD FAILED in 3m 31s
```

### Context
Try to run again...

### Steps to Reproduce (for bugs)
It's hard to reproduce because the issue appears sometimes.
You can search keyword `gradle exception` in the following page to find the failed builds:
http://ci.groovy-lang.org/viewType.html?guest=1&buildTypeId=Groovy_Jdk8Build_PlusSnapshotDeploy&tab=buildTypeHistoryList&branch_Groovy=<default>

### Your Environment
Gradle 4.5.1, Java 8, Ubuntu

 * Build scan URL: 
https://scans.gradle.com/s/fjsj2g7jxf2qc

**Comment by danielsun1106** [comment]
4.6.0-rc-2 has the same issue:
http://ci.groovy-lang.org/viewLog.html?guest=1&buildId=47418&tab=buildResultsDiv&buildTypeId=Groovy_Jdk8Build_PlusSnapshotDeploy

**Comment by autonomousapps** [comment]
I'm seeing this as well, with Gradle 5.2.1.

**Comment by ldaley** [comment]
@adammurdoch @ghale If you look at the errors, they are happening in a `doFirst {}` defined in a script. Our project locking should prevent any kind of race here, and perhaps already does for recent versions.

**Comment by ataverasp** [comment]
I'm seeing this error when building with the daemons in our CI when there is a publishing job and other daemons on the same CI server are using the same daemons and doing another build. 

When I turned the daemons off on the job that it is actually publishing it went away.

**Comment by shevek** [comment]
We have this issue, perhaps 1% of the time. It's related to running with `--parallel` and some after*{} hook, but we can't figure out which one. It's an absolute pain.

**Comment by mattjquinn** [comment]
Like Shevek, I also have this issue periodically, perhaps 2% of the time, in gradle 5.6.

**Comment by SamDeBlock** [comment]
Anyone any idea here? Having the same issue with CI, daemon, --parallel and a task with a doLast block.

**Comment by jeffalder** [comment]
bump - happening on Gradle 6.5 on Fedora. We're also running `--parallel`.

**Comment by shevek** [comment]
It's because Closure's initializer/internal state isn't threadsafe, and Gradle isn't adequately able to protect nested closure structures using the project locks. If you flatten your build structure so that all Closures get statically initialized at build-script execution time, you can work around this. The upshot is that there are a bunch of things that look as if they should work, but don't, because Closure isn't immutable.

I read through the code and there's some use of volatile, etc, in there, but it doesn't prevent an ABA race. I didn't come up with a canonical solution because it's not my dayjob, but I did find ways to flatten our build logic somewhat to avoid triggering the bug.

**Comment by greenrd** [comment]
@shevek I'm not following. For those who aren't Groovy/Gradle experts, can you show what you mean with example(s)?

**Comment by SheetalAgrawal28** [comment]
Hi @shevek , can you please provide one sample example for above workaround ?

**Comment by simschla** [comment]
In my project I encountered the same issue for some tasks that uses `project.copy` using the closure syntax:
(BTW: our actual copy is a bit more complex and we are not using a `CopyTask` because that seems to eat up a lot of config-time in our project, for some reason (probably because we are copying into `projectDir` and that has a lot of files in it depending on the subproject)
```groovy
task myTask {
    // some configuration here
    // [...]
    doLast {
        project.copy {
            from file("${rootProject.projectDir}/../myfile.json")
            into projectDir
        }
    }
}
```

changed that to:
```groovy
task myTask {
    // some configuration here
    // [...]
    doLast {
        project.copy (new Action<CopySpec>() {
            @Override
            void execute(CopySpec spec) {
                spec.from file("${rootProject.projectDir}/../myfile.json")
                spec.into projectDir
            }
        })
    }
}
```

And the issue disappeared on our end.

**Comment by broecirr** [comment]
We're seeing this too in 6.8.1.

**Comment by broecirr** [comment]
After some experimentation, I can reproduce the underlying Groovy issue with a simple script:
`import java.util.concurrent.Executors
def executor = Executors.newCachedThreadPool()
final Closure action = { -> }
while (true) {
  executor.execute(action)
  executor.execute(() -> action.respondsTo('test'))
}
`
The problem is in the way ClosureMetaClass.loadMetaInfo() resets the initialized state without a lock I believe.

**Comment by broecirr** [comment]
Hopefully https://github.com/apache/groovy/pull/1516 will fix this in Groovy and this can be closed in a future Gradle release.

**Comment by danielsun1106** [comment]
@broecirr The bugfix you contributed will be included in Groovy 3.0.8. Thanks! 

https://github.com/apache/groovy/commit/f3d400574e43df7bbdc0e9136f13e756a3596266

/cc @paulk-asert

**Comment by mlopatkin** [comment]
> I guess this is fixed with Gradle 7.2 as that updated to 3.0.8? [c541589#diff-975eb0b10a3bb71fec0c5aa5a08262069c4cbde632deea84e09b48e6f3e8fbb1](https://github.com/gradle/gradle/commit/c5415897c5a89f1872e23e557b235270db559ccc#diff-975eb0b10a3bb71fec0c5aa5a08262069c4cbde632deea84e09b48e6f3e8fbb1)

As we don't see any new reports of the issue, we can conclude that the issue indeed has been fixed. Please file a new report if you see a similar issue again with a recent version of Gradle.
