### ISSUE TITLE
Gradle Test Kit functional tests fail in an unrecoverable way

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#4506]
Sporadically, Gradle plugin functional tests using TestKit fail and require manual intervention to make them work again.

### Expected Behavior
Gradle tests will not fail or if they do fail, they fail in a recoverable fashion.

### Current Behavior
Build sometimes fails with:
```
What went wrong:
Failed to deserialize script metadata extracted for initialization script '/Users/user/.gradle/wrapper/dists/gradle-4.3.1-custom.0.5.7/1uypxo3zdds5egxdw05gd67b4/gradle-4.3.1/init.d/init.gradle'
> /private/var/folders/0m/jk0xbhlx50xd6820m9ks9tp02k683n/T/.gradle-test-kit-user/caches/4.3.1/scripts-remapped/init_69n7a7w49hlv93xxbacu2fv7w/doy4q7dnf06e2cvbl78kx9got/cp_init83b741245ea72a40d718756d5d973aaa/metadata/metadata.bin (No such file or directory)
```
Once this is encountered, the `.gradle-test-kit` directory needs to be deleted.

This is with Gradle 4.3.1 and with a custom distribution that embeds a init script in the Gradle distribution.

**Comment by big-guy** [comment]
@melix @oehme Does this look familiar? It seems like it might be a concurrency bug with build script compilation caching?

**Comment by oehme** [comment]
It doesn't ring a bell. Not sure under what conditions a concurrency issue would occur here, since initialization is serial and a daemon won't run two builds at the same time. A full stacktrace or reproducible example would be great.

**Comment by conorgriffin** [comment]
This also happened to me, here's the stacktrace/error logs

```
com.mycompany.gradle.esb.stf.DeployRpmsTaskSpec > should deploy RPM FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in /var/folders/vz/xc5tzq2s5v55kr1g1z77qj09gznhqb/T/junit4094341627042014764/testBuild with arguments [deployRpmsToFoo, -is]

    Output:
    Using 8 worker leases.
    Creating new cache for fileHashes, path /private/var/folders/vz/xc5tzq2s5v55kr1g1z77qj09gznhqb/T/junit4094341627042014764/testBuild/.gradle/4.4/fileHashes/fileHashes.bin, access org.gradle.cache.internal.DefaultCacheAccess@2953ca66
    Starting Build
    Invalidating in-memory cache of /private/var/folders/vz/xc5tzq2s5v55kr1g1z77qj09gznhqb/T/.gradle-test-kit-conor.griffin/caches/4.4/fileHashes/fileHashes.bin
    Invalidating in-memory cache of /private/var/folders/vz/xc5tzq2s5v55kr1g1z77qj09gznhqb/T/.gradle-test-kit-conor.griffin/caches/4.4/fileHashes/resourceHashesCache.bin
    Creating new cache for metadata-1.1/results, path /private/var/folders/vz/xc5tzq2s5v55kr1g1z77qj09gznhqb/T/.gradle-test-kit-conor.griffin/caches/transforms-1/metadata-1.1/results.bin, access org.gradle.cache.internal.DefaultCacheAccess@3c2c18ef
    Added library 'GRADLE_DIR/lib/mycompany-extensions.jar' to the init script's classpath

    FAILURE: Build failed with an exception.

    * What went wrong:
    Failed to deserialize script metadata extracted for initialization script '/Users/conor.griffin/.gradle/wrapper/dists/gradle-4.4-mycompany-1/9kk9wxbbc4aqnhe9ecp1lqkv9/gradle-4.4/init.d/artifactory.gradle'
    > /private/var/folders/vz/xc5tzq2s5v55kr1g1z77qj09gznhqb/T/.gradle-test-kit-conor.griffin/caches/4.4/scripts-remapped/artifactory_5xsvnjvgabekjj3s73cwywlwm/76whxl5s36md2bwkevqdvog1c/init747428a193288c3c5496d65e64455fb0/metadata/metadata.bin (No such file or directory)

    * Try:
    Run with --debug option to get more log output. Run with --scan to get full insights.

    * Exception is:
    java.lang.IllegalStateException: Failed to deserialize script metadata extracted for initialization script '/Users/conor.griffin/.gradle/wrapper/dists/gradle-4.4-mycompany-1/9kk9wxbbc4aqnhe9ecp1lqkv9/gradle-4.4/init.d/artifactory.gradle'
        at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler.loadFromDir(DefaultScriptCompilationHandler.java:228)
        at org.gradle.groovy.scripts.internal.FileCacheBackedScriptClassCompiler.compile(FileCacheBackedScriptClassCompiler.java:115)
        at org.gradle.groovy.scripts.internal.CrossBuildInMemoryCachingScriptClassCache.getOrCompile(CrossBuildInMemoryCachingScriptClassCache.java:51)
        at org.gradle.groovy.scripts.internal.BuildScopeInMemoryCachingScriptClassCompiler.compile(BuildScopeInMemoryCachingScriptClassCompiler.java:48)
        at org.gradle.groovy.scripts.DefaultScriptCompilerFactory$ScriptCompilerImpl.compile(DefaultScriptCompilerFactory.java:50)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:189)
        at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:61)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:58)
        at org.gradle.configuration.DefaultInitScriptProcessor.process(DefaultInitScriptProcessor.java:49)
        at org.gradle.initialization.InitScriptHandler$1.run(InitScriptHandler.java:55)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.initialization.InitScriptHandler.executeScripts(InitScriptHandler.java:49)
        at org.gradle.initialization.DefaultGradleLauncher$LoadBuild.run(DefaultGradleLauncher.java:232)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.initialization.DefaultGradleLauncher.loadSettings(DefaultGradleLauncher.java:159)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122)
        at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:109)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:78)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:75)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
        at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:100)
        at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:75)
        at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:53)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$1.run(RunAsBuildOperationBuildActionRunner.java:43)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:57)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:32)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:69)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:30)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:45)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
        at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:60)
        at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:41)
        at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:60)
        at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:34)
        at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:156)
        at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:122)
        at org.gradle.tooling.internal.provider.DefaultConnection.getModel(DefaultConnection.java:204)
        at org.gradle.tooling.internal.consumer.connection.CancellableModelBuilderBackedModelProducer.produceModel(CancellableModelBuilderBackedModelProducer.java:53)
        at org.gradle.tooling.internal.consumer.connection.PluginClasspathInjectionSupportedCheckModelProducer.produceModel(PluginClasspathInjectionSupportedCheckModelProducer.java:41)
        at org.gradle.tooling.internal.consumer.connection.AbstractConsumerConnection.run(AbstractConsumerConnection.java:58)
        at org.gradle.tooling.internal.consumer.connection.ParameterValidatingConsumerConnection.run(ParameterValidatingConsumerConnection.java:46)
        at org.gradle.tooling.internal.consumer.DefaultBuildLauncher$1.run(DefaultBuildLauncher.java:89)
        at org.gradle.tooling.internal.consumer.DefaultBuildLauncher$1.run(DefaultBuildLauncher.java:83)
        at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:84)
        at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
        at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
        at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
        at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
    Caused by: java.io.FileNotFoundException: /private/var/folders/vz/xc5tzq2s5v55kr1g1z77qj09gznhqb/T/.gradle-test-kit-conor.griffin/caches/4.4/scripts-remapped/artifactory_5xsvnjvgabekjj3s73cwywlwm/76whxl5s36md2bwkevqdvog1c/init747428a193288c3c5496d65e64455fb0/metadata/metadata.bin (No such file or directory)
        at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler.loadFromDir(DefaultScriptCompilationHandler.java:209)
        ... 81 more


    * Get more help at https://help.gradle.org

    BUILD FAILED in 0s
        at org.gradle.testkit.runner.internal.DefaultGradleRunner$1.execute(DefaultGradleRunner.java:237)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner$1.execute(DefaultGradleRunner.java:234)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:298)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:234)
        at com.mycompany.gradle.esb.stf.DeployRpmsTaskSpec.should deploy RPM(DeployRpmsTaskSpec.groovy:189)
```

I tried removing the project `.gradle` directory and also everything in `~/.gradle` but still got the same error.  I came across this issue and tried `rm -rf /private/var/folders/vz/xc5tzq2s5v55kr1g1z77qj09gznhqb/T/.gradle-test-kit-conor.griffin` and this resolved the issue.

Prior to doing this I performed a `tree` command in `/private/var/folders/vz/xc5tzq2s5v55kr1g1z77qj09gznhqb/T/.gradle-test-kit-conor.griffin/caches/4.4/scripts-remapped/artifactory_5xsvnjvgabekjj3s73cwywlwm/76whxl5s36md2bwkevqdvog1c/init747428a193288c3c5496d65e64455fb0` and got the following output

```
.
├── cache.properties
├── classes
├── init747428a193288c3c5496d65e64455fb0.lock
└── metadata
```

So the `metadata.bin` file that was expected to be under the `metadata/` directory was indeed missing.  I'm not sure what caused it but deleting the `/private/var/folders/vz/xc5tzq2s5v55kr1g1z77qj09gznhqb/T/.gradle-test-kit-conor.griffin` directory resolved it.

**Comment by big-guy** [comment]
I think this is fixed in 4.9 with #5715 -- this doesn't fix earlier versions of Gradle unfortunately. I think this may only occur or is more likely to occur when the Gradle distribution being tested has an embedded init script.

A couple of workarounds:
- Don't test Gradle distributions with init scripts. If your tests require the init scripts to function, include that as part of the test (e.g., `-I path/to/initscript.gradle`)
- Before running the test task, delete the TestKit directories (maybe just the problematic remapped scripts cache for builds older than Gradle 4.9)
- Restrict tests that need to use the Gradle distribution with an init script to serial execution for <Gradle 4.9

The fix doesn't prevent or try to recover from intentional tampering with the cache directory, but it fixes a concurrency problem that could occur with multiple TestKit tests initializing the scripts-remapped cache at the same time without holding proper locks.

**Comment by oehme** [comment]
@big-guy it would be great if you could add a regression test demonstrating that it works now.

**Comment by fcurts** [comment]
Just hit this with Gradle 5.1.1. Again, only way to fix was to delete the `.gradle-test-kit` directory.

**Comment by big-guy** [comment]
@fcurts do you have an example build you can share? or a build scan or test report with the failure?

Are you testing with an embedded init script (in the version of Gradle you're testing)? Are you using Kotlin DSL or Groovy?

**Comment by atorok** [comment]
We are also running into this in CI on  Mac OS with  Gradle `5.2.1`, here's the scan: https://scans.gradle.com/s/j7vcm673fprki/tests/orjfcz7hu5lqq-nintycfxgckka

**Comment by bendb-instacart** [comment]
Just lost an hour to this bug on Gradle 5.6.1.  No repro, unfortunately, just adding my voice.  The fix posted by @conorgriffin worked - that is, finding the `.gradle-test-kit` temp dir and deleting it.

I missed it the other times because I didn't notice that the pathname in the innermost exception is different from the path in the outermost (i.e. first visible) error.  It's that inner path that has the test-kit cache to be cleared.

**Comment by nedtwigg** [comment]
Just bumped into this in gradle 6.0.1  Easy to fix, but can't get it to happen again.  Next time instead of `rm -rf` I'll `cp` first, in case that helps debug.

**Comment by autonomousapps** [comment]
This just happened to me on [this](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin) project, where I use TestKit to test against 5.6.4, 6.0.1, and 6.1-rc-1. Actual build uses 5.6.4.

Once I hit it (running `./gradlew check`), it keeps happening. I haven't tried the workaround of deleting `.gradle-test-kit` yet.

**Comment by CristianGM** [comment]
Just been hit by this issue:
Gradle 6.3

(Scan available at our Gradle Enterprise)

**Comment by martinda** [comment]
I encountered the same with Gradle 6.6.1 and 6.7. Perhaps the problem was that I was switching between the two on the same build and that corrupted the cache content. After I rm -rf /tmp/.gradle-test-kit-martinda things went fine.

Would you recommend using [GradleRunner.withTestKitDir(File testKitDir)](https://docs.gradle.org/current/javadoc/org/gradle/testkit/runner/GradleRunner.html#withTestKitDir-java.io.File-) set to something that gets cleaned often like `build/` to alleviate the problem? I guess yes since that what the javadoc says.
