### ISSUE TITLE
4.6 - JUnit Platform Support - "NoClassDefFoundError" from Gradle Test Executor propagated to build 

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#4544]
### Expected Behavior

Should not receive an error from the test executor and the test should execute normally.
Maybe this comes from multi level nesting of tests (tests are also in Kotlin)?

### Current Behavior

Tests succeeded using the JUnit Gradle Platform plugin that was build by the JUnit team.
Tests also succeed when running in intelliJ.
Tests fail when running with Gradle's `useJUnitPlatform()` support.

```
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not execute test class 'com.mkobit.gradle.test.kotlin.io.FileContextTest$DirectoryContextTest$FileActionMaybeCreate$when string invocation is used and file exists at path then FileAlreadyExistsException is thrown$1$1$1$1'.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:53)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy6.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: com/mkobit/gradle/test/kotlin/io/FileContextTest$DirectoryContextTest$FileActionMaybeCreate$when string invocation is used and file exists at path then FileAlreadyExistsException is thrown$1$1$1
	at java.lang.Class.getEnclosingMethod0(Native Method)
	at java.lang.Class.getEnclosingMethodInfo(Class.java:1072)
	at java.lang.Class.getEnclosingClass(Class.java:1272)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.isTopClass(JUnitPlatformTestClassProcessor.java:100)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.access$300(JUnitPlatformTestClassProcessor.java:52)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.execute(JUnitPlatformTestClassProcessor.java:86)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.execute(JUnitPlatformTestClassProcessor.java:80)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	... 23 more
Caused by: java.lang.ClassNotFoundException: com.mkobit.gradle.test.kotlin.io.FileContextTest$DirectoryContextTest$FileActionMaybeCreate$when string invocation is used and file exists at path then FileAlreadyExistsException is thrown$1$1$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 more
```

![Picture from test report](https://user-images.githubusercontent.com/1447148/36811160-723e890a-1c92-11e8-8343-35e24c3c0d73.png)

### Context

Trying to migrate from the JUnit Platform Gradle plugin to Gradle's built-in support.

### Steps to Reproduce (for bugs)

* `git clone -b mk/gradle-4.6 https://github.com/mkobit/gradle-test-kotlin-extensions.git`
* `./gradlew build` on Java 8

### Your Environment

 * Build scan URL: https://gradle.com/s/mcrexd2wyitww

The test failure indicated is not recorded in the build scan test report, but the picture above and hopefully the reproduction case shows what happened

**Comment by blindpirate** [comment]
Thanks for reporting. Looks like your test module generates a class `FileContextTest$DirectoryContextTest$FileActionMaybeCreate$when string invocation is used and file exists at path then FileAlreadyExistsException is thrown$1$1$1$1.class`, and this class says, "hey my enclosing class is `FileContextTest$DirectoryContextTest$FileActionMaybeCreate$when string invocation is used and file exists at path then FileAlreadyExistsException is thrown$1$1$1`":

```
EnclosingMethod: #54.#56                // com.mkobit.gradle.test.kotlin.io.FileContextTest$DirectoryContextTest$FileActionMaybeCreate$when string invocation is used and file exists at path then FileAlreadyExistsException is thrown$1$1$1.call
```

But this class file doesn't exist - that's weird. We need to investigate this, maybe because of some kotlin compiler configuration.

**Comment by blindpirate** [comment]
Seems like Kotlin issue:

https://youtrack.jetbrains.com/issue/KT-22663

https://github.com/blindpirate/gradle-test-kotlin-extensions

**Comment by oehme** [comment]
If we decide to add a workaround for #4618 (filtering anonymous classes without loading them), this issue would also be fixed as a result. Might be worth considering.
