### ISSUE TITLE
Allow HTTP basic authentication for "apply from:"

### ISSUE THREAD

**Issue by pnidl** [gradle/gradle#4586]
### Expected Behavior
Given following setup:

_gradle.properties_:
``scripts_url=http://username:password@host:port/path``

_build.gradle_:
``apply from: "$scripts_url/common-build-script.gradle"``

I would expect that Gradle will correctly apply the HTTP basic authentication to the request and will download the resource from _http://username:password@host:port/path/common-build-script.gradle_

### Current Behavior
The problem is it completely ignores the authentication parts of the URL. _org.gradle.internal.resource.ExternalResourceName#encodeRoot_, that provides the URL to the HTTP, client only concerns scheme, host and port.

### Context
I have a set up as described in Expected behavior and a set of common build scripts deployed in artifactory. I can not allow anonymous access to the artifactory and I want these to be applied for each of my projects but I'm getting following exception (the URL is intentionally changed):
```
Caused by: org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not HEAD 'http://host:port/path/common-build-script.gradle'. Received status code 401 from server: Unauthorized
        at org.gradle.internal.resource.transport.http.HttpClientHelper.processResponse(HttpClientHelper.java:158)
        at org.gradle.internal.resource.transport.http.HttpClientHelper.performHead(HttpClientHelper.java:76)
        at org.gradle.internal.resource.transport.http.HttpResourceAccessor.getMetaData(HttpResourceAccessor.java:65)
        at org.gradle.internal.resource.transfer.DefaultExternalResourceConnector.getMetaData(DefaultExternalResourceConnector.java:63)
        at org.gradle.internal.resource.transfer.AccessorBackedExternalResource.getMetaData(AccessorBackedExternalResource.java:201)
        at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$1.call(BuildOperationFiringExternalResourceDecorator.java:61)
        at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$1.call(BuildOperationFiringExternalResourceDecorator.java:58)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:350)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:340)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:120)
        at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator.getMetaData(BuildOperationFiringExternalResourceDecorator.java:58)
        at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor$1.create(DefaultCacheAwareExternalResourceAccessor.java:102)
        at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor$1.create(DefaultCacheAwareExternalResourceAccessor.java:82)
        at org.gradle.cache.internal.ProducerGuard$AdaptiveProducerGuard.guardByKey(ProducerGuard.java:97)
        at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.getResource(DefaultCacheAwareExternalResourceAccessor.java:82)
        at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceAccessor.resolve(DefaultExternalResourceAccessor.java:60)
        ... 104 more
```
### Steps to Reproduce

1. Deploy any gradle build script into an endpoint secured with basic authentication
1. Add following line to any (even empty one) _build.gradle_ file:
``apply from: "http://username:password@url:port/path/common-build-script.gradle"``

### Environment

Artifactory with anonymous access disabled
Gradle 4.5.1

**Comment by rickbradshaw** [comment]
I am also hitting this exact same issue. Is there a work-a-round?

**Comment by FedorRomanov** [comment]
we also suffering from this issue: no option to use authentication when fetching external file by HTTPS. Any plans to fix it?

**Comment by aram535** [comment]
There is an absolutely horrible workaround 
```
try{
    def curl = "curl -o generic.gradle https://${artifactory_user}:${artifactory_password}@${artifactory_url}/${gradle_repository}/company.gradle"
    curl.execute().waitFor()
} catch (Exception e) {
    println 'Failed to get remote gradle script'
}

apply from : "company.gradle"
```
You can then either Project.delete('...') or add it to your .gitignore file to ignore it.

**Comment by niclarcipretti** [comment]
Same here. Any updates?

**Comment by miguelsosa** [comment]
Is there an alternate way to do this?

**Comment by niclarcipretti** [comment]
@miguelsosa natively, nope...

I guess they should add a "credentials" param to the "apply from".

**Comment by big-guy** [comment]
The better alternative here is to use a binary plugin vs a script and apply it like you do any other plugin.  Plugin repositories can be authenticated.

We're not likely to add authentication for scripts beyond what we can already do.  We're moving towards making script plugins behave more like binary plugins (see https://docs.gradle.org/current/userguide/kotlin_dsl.html#kotdsl:precompiled_plugins), so you can apply them in the same way but keep the "script" feeling.

**Comment by apxcoder** [comment]
Can we reopen this issue? I'm seeing the same issue.
