### ISSUE TITLE
[4.6] - Caused by: java.lang.ClassCastException: org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by jaredsburrows** [gradle/gradle#4730]
## Description:
When upgrading from 4.5 to 4.6, I cannot run tests: `Caused by: java.lang.ClassCastException: org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String`

## Error:
Bug PR: https://github.com/jaredsburrows/gradle-checker-framework-plugin/pull/6
```
13 tests completed, 6 failed
:test FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/travis/build/[secure]/gradle-checker-framework-plugin/build/reports/tests/test/index.html
* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:66)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: There were failing tests. See the report at: file:///home/travis/build/[secure]/gradle-checker-framework-plugin/build/reports/tests/test/index.html
	at org.gradle.api.tasks.testing.AbstractTestTask.handleTestFailures(AbstractTestTask.java:611)
	at org.gradle.api.tasks.testing.AbstractTestTask.executeTests(AbstractTestTask.java:483)
	at org.gradle.api.tasks.testing.Test.executeTests(Test.java:561)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
	... 31 more
* Get more help at https://help.gradle.org
BUILD FAILED in 1m 46s
13 actionable tasks: 12 executed, 1 up-to-date
Publishing build scan...
https://gradle.com/s/elzds3h4ulfvs
The command "./gradlew clean build -s --scan" exited with 1.
cache.2
store build cache
0.01s
60.67schange detected (content changed, file is created, or file is deleted):
/home/travis/.gradle/caches/4.6/file-changes/last-build.bin
/home/travis/.gradle/caches/4.6/fileHashes/fileHashes.bin
/home/travis/.gradle/caches/4.6/fileHashes/fileHashes.lock
/home/travis/.gradle/caches/4.6/fileHashes/resourceHashesCache.bin
/home/travis/.gradle/caches/4.6/generated-gradle-jars/generated-gradle-jars.lock
/home/travis/.gradle/caches/4.6/generated-gradle-jars/gradle-api-4.6.jar
/home/travis/.gradle/caches/4.6/generated-gradle-jars/gradle-test-kit-4.6.jar
/home/travis/.gradle/caches/4.6/scripts/5oubvvq1xz4i5gjqlqqo9jfhp/cp_dsl/cp_dsldf5583fde4f7f1f2f3f5ea117e2cdff1/cache.properties
/home/travis/.gradle/caches/4.6/scripts/5oubvvq1xz4i5gjqlqqo9jfhp/cp_dsl/cp_dsldf5583fde4f7f1f2f3f5ea117e2cdff1/cp_dsldf5583fde4f7f1f2f3f5ea117e2cdff1.lock
/home/travis/.gradle/caches/4.6/scripts/5oubvvq1xz4i5gjqlqqo9jfhp/cp_dsl/cp_dsldf5583fde4f7f1f2f3f5ea117e2cdff1/metadata/metadata.bin
/home/travis/.gradle/caches/4.6/scripts/5oubvvq1xz4i5gjqlqqo9jfhp/dsl/dsldf5583fde4f7f1f2f3f5ea117e2cdff1/
...
changes detected, packing new archive
.
.
.
.
.
.
.
.
uploading archive
Done. Your build exited with 1.
```

## Repro:
```
git clone https://github.com/jaredsburrows/gradle-checker-framework-plugin
cd gradle-checker-framework-plugin
gradlew test
```

**Comment by blindpirate** [comment]
Thanks for reporting. This is due to some changes of annotation processors in `4.6`. A workaround would be change the line https://github.com/jaredsburrows/gradle-checker-framework-plugin/blob/master/src/main/groovy/com/jaredsburrows/checkerframework/CheckerPlugin.groovy#L86

from 

```
"-processorpath", "${project.configurations.checkerFramework.asPath}",
```

to 

```
"-processorpath", "${project.configurations.checkerFramework.asPath}".toString(),
```

**Comment by blindpirate** [comment]
@oehme This line throws `ClassCastException`: https://github.com/gradle/gradle/blob/01e15334c53f207384264b7516f04bd4e2dd101d/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/AnnotationProcessorPathFactory.java#L84

I'm sure you're more familiar than me.

**Comment by jaredsburrows** [comment]
@blindpirate Thank you. On my side, I will use `toString()`.

**Comment by oehme** [comment]
Oh Groovy...
