### ISSUE TITLE
JUnit 5 integration relies on Jupiter specifics

### ISSUE THREAD

**Issue by codecholeric** [gradle/gradle#4912]
Recently I tried to implement a custom `TestEngine` (see https://github.com/TNG/ArchUnit/issues/34) and was wondering, that JUnit 5 tests were executed in IntelliJ and Maven, but not Gradle.

The reason seems, that Gradle makes some (in my opinion) unjustified assumptions in 

```
org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestExecutionListener#getDescriptor
```

Namely that the chosen type of descriptor is based on

```
private boolean isClass(TestIdentifier test) {
    return test.getSource().isPresent() && test.getSource().get() instanceof ClassSource;
}
```

While on the other hand, the Javadoc of `Optional<TestSource> getSource()` seems to suggest, that it is valid to not provide any source. In my concrete case, I did not provide a `ClassSource`, which caused Gradle to use a `DefaultTestDescriptor`, that in turn always claims `isComposite() -> false`. On the other hand, within 

```
org.gradle.api.internal.tasks.testing.results.AttachParentTestResultProcessor#started
```

Gradle expects `isComposite() -> true`, if the `rootId` is not yet set. This lead to a somewhat silent exception and Gradle reporting `SUCCESS` without any test being run (I don't know if I like this behavior, but maybe there is a reason for that, that I don't know about :wink:)

I don't know much about JUnit 5 / Gradle interna, but shouldn't `isComposite()` rather refer to

```
org.junit.platform.launcher.TestIdentifier#getType
```

? I.e. if the type of the descriptor is a `CONTAINER` or `TEST`.

I've "fixed" the issue in my case by providing the source (which I probably would have done eventually, anyway), but the behavior and assumptions still seem a little shady. 

Might also be related to #4773, since I think this would affect the same places?

**Comment by blindpirate** [comment]
Thanks for reporting, that's definitely what we want to improve. We did make some assumption when integrating JUnit 5 with Gradle, because traditional Gradle test infrastructure is class-based (e.g. report is class-based). Your project is a perfect case for us to look into. I'll take a look at it.

**Comment by codecholeric** [comment]
Just to clarify, my `TestEngine` is class-based, too :wink: 
So it's unfortunately not a good example for a file-based `TestEngine`. However, if you want to analyse the problem, I've pushed a branch with my original code:

https://github.com/TNG/ArchUnit/tree/junit5-support-gradle-problem

You can run `./gradlew install` and then add the dependency to another Gradle project:

```
testCompile("com.tngtech.archunit:archunit-junit5:1.0.0-junit5-SNAPSHOT")
```

Then add a simple test

```
@AnalyzeClasses(packagesOf = MyArchTest.class)
public class MyArchTest {
    @ArchTest
    public static final ArchRule some_failing_rule = classes().should().bePrivate();
}
```

This test should run fine in IntelliJ Idea (violation at least by the test class itself), but if you run it from the command line with Gradle, it silently gets skipped (note that you need Gradle >= 4.6 with the new JUnit 5 support).

The version with the test source (https://github.com/TNG/ArchUnit/tree/junit5-support) works as expected.

**Comment by blindpirate** [comment]
Thanks @codecholeric , it's very kind of you. However I did as you said, seems your test engine didn't discover the test:

![image](https://user-images.githubusercontent.com/12689835/38251765-f0cb1e70-3784-11e8-9a53-2ac2d5d87d91.png)

Am I wrong somewhere?

Here's my repository: https://github.com/blindpirate/MyArchTest

**Comment by codecholeric** [comment]
Hey, I think you forgot the `@AnalyzeClasses(packagesOf = MyArchTest.class)` :wink: 
Classes not annotated that way get filtered out, since the engine wouldn't know what classes to test the rules against.

**Comment by codecholeric** [comment]
My old JUnit 4 infrastructure would fail in that case, but I think with JUnit 5 all `TestEngines` are queried with the `ClassSelector`, so I didn't wanna throw an Exception... (Don't know what the best JUnit 5 style would be in that case, because from the `ArchUnitTestEngine`'s point of view, this actually is a misconfiguration)

**Comment by marcphilipp** [comment]
@codecholeric If the class does not look like a ArchUnit test class at all, the engine should simply ignore it. If the test class looks like it was meant to be for ArchUnit but is missing a crucial annotation, the engine should report an error when the test class is executed. But the latter is more of a nice-to-have feature.

**Comment by blindpirate** [comment]
Thanks @codecholeric , now I can reproduce it. A simple solution might be putting the tests which don't have a "Class Source" into a special "UnknownClass", WDYT? And curious about how IDEA and Maven make it?

**Comment by codecholeric** [comment]
Thanks @marcphilipp for clarifying this! So if I understand correctly, I should
* search for members with `@ArchTest`
* if the class has any, but is not annotated with `@AnalyzeClasses` it's a misconfiguration and I should report it
* otherwise I'll just ignore the class

**Comment by codecholeric** [comment]
Depends on your goal @blindpirate :wink: 
If you want to support a file-based `TestEngine`, the whole concept of a "test class" will probably need to be replaced by something more generic anyway.
As a quick-fix, an "UnknownClass" could work, but I don't know what consequences this has. You wouldn't want this to appear in any report... I don't have enough insights into Gradle to know, where this "UnknownClass" would be used, or why you need the concept of a class for this anyway (if there only was the concept of a composite / container, you wouldn't have any problem in the first place).
Unfortunately I don't know how Maven / IntelliJ do this...

**Comment by blindpirate** [comment]
@marcphilipp Of course I don't mind, ping me if you need any help.

**Comment by sksamuel** [comment]
Hi, I'd like to add some comments to this. As one of the authors of [KotlinTest](https://github.com/kotlintest/kotlintest) which relieves very heavily on Junit5 and it's ability to arbitarily nest tests. You can use our repo as a good example of tests that have [no limit on their structure](https://github.com/kotlintest/kotlintest/blob/newconfig/kotlintest-tests/src/test/kotlin/com/sksamuel/kotlintest/tests/specs/FreeSpecLambdaTest.kt).

I've ran into two problems. The first (as already reported by @codecholeric) is that we shouldn't have to provide a `ClassSource` or any source at all. In fact we should be able to use `ClassSource` in multiple places (nested tests) which you currently cannot. I don't think the implementation should assume that a test that has a `ClassSource`*is* a class. 

Secondly, in gradle 4.7, and something more urgent, is that if a nested test fails, and the test is a container, gradle assumes a start event will not have been fired and thus fires one. This means we get:

```   java.lang.AssertionError: Unexpected start event for [engine:kotlintest]/[spec:StringSpecTest]/[test:hi wrld]
        at org.gradle.api.internal.tasks.testing.junit.GenericJUnitTestEventAdapter.testStarted(GenericJUnitTestEventAdapter.java:52)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestExecutionListener.executionFinishedAfterTestClassStart(JUnitPlatformTestExecutionListener.java:107)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestExecutionListener.executionFinished(JUnitPlatformTestExecutionListener.java:91)
        at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.lambda$executionFinished$3(TestExecutionListenerRegistry.java:77)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.junit.platform.launcher.core.TestExecutionListenerRegistry.notifyTestExecutionListeners(TestExecutionListenerRegistry.java:51)
        at org.junit.platform.launcher.core.TestExecutionListenerRegistry.access$100(TestExecutionListenerRegistry.java:27)
        at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.executionFinished(TestExecutionListenerRegistry.java:77)
        at org.junit.platform.launcher.core.ExecutionListenerAdapter.executionFinished(ExecutionListenerAdapter.java:56)
        at io.kotlintest.runner.junit5.SynchronizedEngineExecutionListener.executionFinished(SynchronizedEngineExecutionListener.kt:12)
        at io.kotlintest.runner.junit5.JUnitTestRunnerListener.completeSpec(JUnitTestRunnerListener.kt:127)
        at io.kotlintest.runner.jvm.TestEngine.executeSpec(TestEngine.kt:112)
```

As far as I can tell, gradle is not supporting `CONTAINER_AND_TEST` which is a valid type of `TestDescriptor`. It assumes that it's either a `CONTAINER` (and fires a start event) or a `TEST`.  The `CONTAINER_AND_TEST` in JUnit platform allows nested test contexts to act as both a test case itself and a container of more tests. 

In other words, this method makes incorrect assumptions.

```
    private void executionFinishedAfterTestClassStart(TestIdentifier testIdentifier, TestExecutionResult testExecutionResult) {
        // Generally, there're 2 kinds of identifier:
        // 1. A container (test engine/class/repeated tests). It is not tracked unless it fails/aborts.
        // 2. A test "leaf" method. It's always tracked.
        if (isFailedContainer(testIdentifier, testExecutionResult)) {
            // only leaf methods triggered start events previously
            // so here we need to add the missing start events
            adapter.testStarted(testIdentifier.getUniqueId(), getDescriptor(testIdentifier));
            testFinished(testIdentifier, testExecutionResult);
        } else if (isLeafTest(testIdentifier)) {
            testFinished(testIdentifier, testExecutionResult);
        }

        if (isClass(testIdentifier)) {
            reportTestClassFinished(testIdentifier);
        }
    }
```

I hope this helps.

**Comment by marcphilipp** [comment]
@sksamuel Thanks for your feedback! I'm already working on this issue and #4252 and intend to remove these assumptions and report events for all nodes of the test tree to support arbitrarily nested structures. I'll make sure to add an integration test that uses KotlinTest.

**Comment by sksamuel** [comment]
No problem. If you need any early feedback I'm happy to help test your work.

**Comment by oehme** [comment]
See also #5678 for how our test filtering has similar problems.

**Comment by sormuras** [comment]
Any news here?

**Comment by marcphilipp** [comment]
We're a bit closer but there's still work to be done.

**Comment by Kerooker** [comment]
Hey, @marcphilipp !
Any news here? Perhaps we can help with it?

**Comment by marcphilipp** [comment]
@Kerooker Gradle's test execution infrastructure still relies on the concept of test classes and methods. There's now only a single place that checks for `ClassSource`:

https://github.com/gradle/gradle/blob/6478a82c63c8fb37b005964be08a241ff09fca9a/subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestExecutionListener.java#L206-L208

I an engine does not use `ClassSource`, Gradle has no way of knowing which identifiers represent test classes. We could probably find a heuristic, e.g. assume direct children of an engine's identifier are classes if no `ClassSource` can be found but I'm not convinced that would do much good. It might be better to close this issue in favor of #4773 but that would require a general overhaul of Gradle's test reporting infrastructure.

**Comment by sksamuel** [comment]
Does it matter if something is a class or not? In the `TestExecutionListener` can you not just take the test name, and then report from that? That's the idea behind the hierarchy in junit 5 I thought, that tests can be arbitrary nested.

**Comment by marcphilipp** [comment]
Yes, that's the idea in JUnit. In Gradle, however, test reports are (currently) per-class.

**Comment by jbduncan** [comment]
I think this issue is still valuable and worth tackling. :)

**Comment by sksamuel** [comment]
Any plans to support CONTAINER_AND_TEST ?

**Comment by octylFractal** [comment]
I believe this should be fixed now that #35428 has been partially integrated (though non-class-based testing is still not currently possible until a future release, the `ClassSource` assumption is now gone), along with a bug fix for `CONTAINER_AND_TEST` in #35773. Please file a new issue if you run into more problems related to a class-based `TestEngine`.
