### ISSUE TITLE
UndeclaredThrowableException with JDK 9 or JDK 10

### ISSUE THREAD

**Issue by FilipJirsak** [gradle/gradle#4931]
When `javac` within `:compileJava` task throws `NullPointerException`, Gradle hides this exception and instead it throws `java.lang.reflect.UndeclaredThrowableException`.

The NPE exception occurs with JDK 9 or JDK 10. JDK 8 is OK.

I know this is primarly problem of `javac` but I think Gradle should not hide the original exception from `javac`. It is not even in `--debug` output.

```
C:\work\test>echo %JAVA_HOME%
C:\jdk-9

C:\work\test>gradlew compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> java.lang.reflect.UndeclaredThrowableException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
1 actionable task: 1 executed
```

I get the same result with JDK 10. But with JDK 8 it works:

```
C:\work\test>set JAVA_HOME=C:\jdk1.8

C:\work\test>echo %JAVA_HOME%
C:\jdk1.8

C:\work\test>gradlew compileJava

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
```
But when I remove dependency on jodd-core, it works with both JDK 9 and JDK 10:
```
C:\work\test>set JAVA_HOME=C:\jdk-9

C:\work\test>gradlew compileJava

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
```

Sample `build.gradle` file:
```gradle
apply plugin: 'java'

sourceCompatibility = 1.8

repositories {
  mavenCentral()
}

dependencies {
  compile(
	"org.jodd:jodd-core:4.3.0",
  )
}

task wrapper(type: Wrapper) {
  gradleVersion = '4.6'
}
```
There is only one empty class in my project, without them compileJava will be skipped:

File `src/main/java/test/Consts.java`
```java
package test;

public final class Consts {
}
```

```
C:\work\test>gradlew --version
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/C:/Users/jirsakf/.gradle/wrapper/dists/gradle-4.6-all/bcst21l2brirad8k2ben1letg/gradle-4.6/lib/groovy-all-2.4.12.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          10 ("Oracle Corporation" 10+46)
OS:           Windows 10 10.0 amd64
```

Underlying exception from `javac` is NullPointerException:

```
C:\work\test\src\main\java>C:\jdk-9\bin\javac.exe -cp C:\Users\jirsakf\.gradle\caches\modules-2\files-2.1\org.jodd\jodd-core\4.3.0\9ca4c4460010604219f554b5c94ceb13144aab7e\jodd-core-4.3.0.jar test/Consts.java
An exception has occurred in the compiler (9.0.1). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.NullPointerException
        at jdk.zipfs/jdk.nio.zipfs.JarFileSystem.getVersionMap(JarFileSystem.java:137)
        at jdk.zipfs/jdk.nio.zipfs.JarFileSystem.createVersionedLinks(JarFileSystem.java:112)
        at jdk.zipfs/jdk.nio.zipfs.JarFileSystem.<init>(JarFileSystem.java:85)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:134)
        at jdk.compiler/com.sun.tools.javac.file.JavacFileManager$ArchiveContainer.<init>(JavacFileManager.java:517)
        at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getContainer(JavacFileManager.java:319)
        at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.list(JavacFileManager.java:715)
        at jdk.compiler/com.sun.tools.javac.code.ClassFinder.list(ClassFinder.java:722)
        at jdk.compiler/com.sun.tools.javac.code.ClassFinder.scanUserPaths(ClassFinder.java:648)
        at jdk.compiler/com.sun.tools.javac.code.ClassFinder.fillIn(ClassFinder.java:529)
        at jdk.compiler/com.sun.tools.javac.code.ClassFinder.complete(ClassFinder.java:293)
        at jdk.compiler/com.sun.tools.javac.code.Symbol.complete(Symbol.java:633)
        at jdk.compiler/com.sun.tools.javac.code.Symbol$PackageSymbol.members(Symbol.java:1120)
        at jdk.compiler/com.sun.tools.javac.code.Symtab.listPackageModules(Symtab.java:810)
        at jdk.compiler/com.sun.tools.javac.comp.Enter.visitTopLevel(Enter.java:344)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:529)
        at jdk.compiler/com.sun.tools.javac.comp.Enter.classEnter(Enter.java:285)
        at jdk.compiler/com.sun.tools.javac.comp.Enter.classEnter(Enter.java:300)
        at jdk.compiler/com.sun.tools.javac.comp.Enter.complete(Enter.java:570)
        at jdk.compiler/com.sun.tools.javac.comp.Enter.main(Enter.java:554)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:1052)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:923)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:302)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:162)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
```

**Comment by FilipJirsak** [comment]
Original bug in Java compiler Bug Database: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8193802

**Comment by oehme** [comment]
Thanks for the heads-up! This should be fixed by https://github.com/gradle/gradle/pull/4954
