### ISSUE TITLE
NPE starting daemon with 4.7-rc-1, Java 10, and Docker

### ISSUE THREAD

**Issue by ajoberstar** [gradle/gradle#4973]
I'm trying to run my Gradle plugin test suites against multiple Java versions now, and have run into issues when using the combination of Java 10 and 4.7-rc-1 on Docker (specifically Circle CI). This same issue does not occur with Java 10 on my Windows desktop.

So I'm not clear if this is a Linux/Debian issue with 4.7-rc-1 or if it has anything to do with the Circle CI docker environment.

### Expected Behavior

Gradle should be able to run on Java 10 with 4.7-rc-1.

### Current Behavior

```
./gradlew clean check --continue --stacktrace

Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/4.7-rc-1/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------

Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "main"


* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleException: Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/4.7-rc-1/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------

Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "main"

	at org.gradle.launcher.daemon.client.DaemonGreeter.parseDaemonOutput(DaemonGreeter.java:35)
	at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startProcess(DefaultDaemonStarter.java:160)
	at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startDaemon(DefaultDaemonStarter.java:136)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.doStartDaemon(DefaultDaemonConnector.java:212)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.startDaemon(DefaultDaemonConnector.java:206)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connect(DefaultDaemonConnector.java:130)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:139)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:93)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:52)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:379)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:352)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:37)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:23)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:345)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:275)
	at org.gradle.launcher.Main.doAction(Main.java:36)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)


* Get more help at https://help.gradle.org
Exited with code 1
```

### Context

This is preventing support of 4.7-rc-1 for my plugins. See an [example](https://circleci.com/gh/ajoberstar/reckon/22) (there's more minimal one below) of this failing on an actual test suite.

In the Circle CI environment this suite passes on:

- Java 8: 3.0 through 4.7-rc-1
- Java 9: 4.2.1 through 4.7-rc-1
- Java 10: 4.1 through 4.6

4.7-rc-1 on Java 10 is the only failing case.

### Steps to Reproduce (for bugs)

[Circle CI job](https://circleci.com/gh/ajoberstar/pipeline-test/261) with the failure.

[Commit](https://github.com/ajoberstar/pipeline-test/tree/00af5598457a38c00b3d7da39aeb2a0890421c84) in test project that reproduces.

Run in the affected environments:

```
./gradlew check
```

### Your Environment

Failing environment:

```
------------------------------------------------------------
Gradle 4.7-rc-1
------------------------------------------------------------

Build time:   2018-04-03 11:36:02 UTC
Revision:     2f0b7b15068980c05470af1882d79e9c8ef5c71b

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          10 (Oracle Corporation 10+46-Debian-4)
OS:           Linux 4.4.0-116-generic amd64
```

Working environment:

```
------------------------------------------------------------
Gradle 4.7-rc-1
------------------------------------------------------------

Build time:   2018-04-03 11:36:02 UTC
Revision:     2f0b7b15068980c05470af1882d79e9c8ef5c71b

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          10 (Azul Systems, Inc. 10+46)
OS:           Windows 10 10.0 amd64
```

**Comment by jamespedwards42** [comment]
+1 Same issue here. No issue locally on mac. Fails with the following error on Gitlab build pipeline server.

```
Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "main"
```

**Comment by ghale** [comment]
Thans for reporting this @ajoberstar, @jamespedwards42.  I'm pretty sure I know what's going on here and there's a combination of factors including your environment, differences in JDK10 and changes in Gradle 4.7 that are coming together to create this problem.

What it looks like is that the default locale in that CircleCI container is getting set to a language without a region.  When this happens, JDK10 ends up logging an INFO level logging message at just the right moment and this triggers a bug in the Gradle logging framework.

We'll fix this in Gradle, but in the short term, if you want to work around the problem, you should be able to just set `user.country` to force the locale to have a region (e.g. `./gradlew -Duser.country=US check`).  That should prevent the bug from being triggered.

**Comment by henrik242** [comment]
Sounds reasonable, it works for us with
```
------------------------------------------------------------
Gradle 4.7-rc-1
------------------------------------------------------------
Build time:   2018-04-03 11:36:02 UTC
Revision:     2f0b7b15068980c05470af1882d79e9c8ef5c71b
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          10 ("Oracle Corporation" 10+46)
OS:           Linux 4.9.0-0.bpo.5-amd64 amd64
```
and
```
-Djava.security.egd=file:/dev/./urandom -Duser.region=NO -Duser.timezone=Europe/Oslo --add-modules=java.xml.bind,java.activation,java.xml.ws.annotation -Dfile.encoding=UTF-8 -Duser.country=NO -Duser.language=nb -Duser.variant
```
