### ISSUE TITLE
Gradle wrapper does not respect proxy user and pass for distribution downloading

### ISSUE THREAD

**Issue by nevenr** [gradle/gradle#5052]
### Expected Behavior
When http.proxyHost, http.proxyPort, http.proxyUser and http.proxyPassword are specified in GRADLE_OPTS environment variable they should be respected during distribution downloading.

### Current Behavior
Seems like only http.proxyHost and http.proxyPort are taken into account.
While invoking "gradlew installDist" this exception is thrown:
Exception in thread "main" java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"

### Context
Build container is behind web proxy and all gradle operations (distribution downloading and build dependency downloading) should respect all web proxy properties (http.proxyHost, http.proxyPort, http.proxyUser and http.proxyPassword + https.proxyHost, https.proxyPort, https.proxyUser and https.proxyPassword). 

### Steps to Reproduce (for bugs)
Gradle 4.4 is used and gradle-wrapper.properties look like this:
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-bin.zip
```

Steps:
```
bash-4.2$ echo "env GRADLE_OPTS: ${GRADLE_OPTS}"
env GRADLE_OPTS: -Dhttp.proxyHost=proxy.host -Dhttp.proxyPort=8080 -Dhttp.proxyUser=proxy-user -Dhttp.proxyPassword=proxy-pass -Dhttps.proxyHost=proxy.host -Dhttps.proxyPort=8080 -Dhttps.proxyUser=proxy-user -Dhttps.proxyPassword=proxy-pass

bash-4.2$ echo "env JAVA_OPTS: ${JAVA_OPTS}"
env JAVA_OPTS: -XshowSettings:properties -Djava.util.logging.config.file=/tmp/logging.properties

bash-4.2$ ./gradlew installDist
Property settings:
    awt.toolkit = sun.awt.X11.XToolkit
    file.encoding = ANSI_X3.4-1968
    file.encoding.pkg = sun.io
    file.separator = /
    http.proxyHost = proxy.host
    http.proxyPassword = proxy-pass
    http.proxyPort = 8080
    http.proxyUser = proxy-user
    https.proxyHost = proxy.host
    https.proxyPassword = proxy-pass
    https.proxyPort = 8080
    https.proxyUser = proxy-user
    java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
    java.awt.printerjob = sun.print.PSPrinterJob
    java.class.path = /tmp/src/gradle/wrapper/gradle-wrapper.jar
    java.class.version = 52.0
    java.endorsed.dirs = /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/lib/endorsed
    java.ext.dirs = /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/lib/ext
        /usr/java/packages/lib/ext
    java.home = /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre
    java.io.tmpdir = /tmp
    java.library.path = /usr/java/packages/lib/amd64
        /usr/lib64
        /lib64
        /lib
        /usr/lib
    java.runtime.name = OpenJDK Runtime Environment
    java.runtime.version = 1.8.0_161-b14
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 1.8
    java.util.logging.config.file = /tmp/logging.properties
    java.vendor = Oracle Corporation
    java.vendor.url = http://java.oracle.com/
    java.vendor.url.bug = http://bugreport.sun.com/bugreport/
    java.version = 1.8.0_161
    java.vm.info = mixed mode
    java.vm.name = OpenJDK 64-Bit Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 1.8
    java.vm.vendor = Oracle Corporation
    java.vm.version = 25.161-b14
    line.separator = \n
    org.gradle.appname = gradlew
    os.arch = amd64
    os.name = Linux
    os.version = 3.10.0-693.17.1.el7.x86_64
    path.separator = :
    sun.arch.data.model = 64
    sun.boot.class.path = /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/lib/resources.jar
        /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/lib/rt.jar
        /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/lib/sunrsasign.jar
        /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/lib/jsse.jar
        /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/lib/jce.jar
        /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/lib/charsets.jar
        /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/lib/jfr.jar
        /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/classes
    sun.boot.library.path = /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre/lib/amd64
    sun.cpu.endian = little
    sun.cpu.isalist =
    sun.io.unicode.encoding = UnicodeLittle
    sun.java.command = org.gradle.wrapper.GradleWrapperMain installDist
    sun.java.launcher = SUN_STANDARD
    sun.jnu.encoding = ANSI_X3.4-1968
    sun.management.compiler = HotSpot 64-Bit Tiered Compilers
    sun.os.patch.level = unknown
    user.country = US
    user.dir = /tmp/src
    user.home = /opt/app-root/src
    user.language = en
    user.name = default
    user.timezone =

Downloading https://services.gradle.org/distributions/gradle-4.4-bin.zip
Apr 14, 2018 10:25:19 PM sun.net.www.protocol.http.HttpURLConnection plainConnect0
FINEST: ProxySelector Request for https://services.gradle.org/distributions/gradle-4.4-bin.zip
Apr 14, 2018 10:25:19 PM sun.net.www.protocol.https.HttpsClient New
FINEST: Looking for HttpClient for URL https://services.gradle.org/distributions/gradle-4.4-bin.zip and proxy value of HTTP @ proxy.host:8080
Apr 14, 2018 10:25:19 PM sun.net.www.protocol.https.HttpsClient <init>
FINEST: Creating new HttpsClient with url:https://services.gradle.org/distributions/gradle-4.4-bin.zip and proxy:HTTP @ proxy.host:8080 with connect timeout:-1
Apr 14, 2018 10:25:19 PM sun.net.www.protocol.http.HttpURLConnection plainConnect0
FINEST: Proxy used: HTTP @ proxy.host:8080
Apr 14, 2018 10:25:19 PM sun.net.www.protocol.http.HttpURLConnection sendCONNECTRequest
FINE: sun.net.www.MessageHeader@108c4c355 pairs: {CONNECT services.gradle.org:443 HTTP/1.1: null}{User-Agent: Java/1.8.0_161}{Host: services.gradle.org}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Proxy-Connection: keep-alive}
Apr 14, 2018 10:25:19 PM sun.net.www.http.HttpClient logFinest
FINEST: KeepAlive stream used: https://services.gradle.org/distributions/gradle-4.4-bin.zip
Apr 14, 2018 10:25:19 PM sun.net.www.protocol.http.HttpURLConnection doTunneling
FINE: sun.net.www.MessageHeader@4ccabbaa14 pairs: {null: HTTP/1.1 407 Proxy Authentication Required}{Server: squid/3.5.20}{Mime-Version: 1.0}{Date: Sat, 14 Apr 2018 22:25:19 GMT}{Content-Type: text/html;charset=utf-8}{Content-Length: 3744}{X-Squid-Error: ERR_CACHE_ACCESS_DENIED 0}{Vary: Accept-Language}{Content-Language: en}{Proxy-Authenticate: Basic realm="proxy"}{X-Cache: MISS from node187}{X-Cache-Lookup: NONE from node187:8080}{Via: 1.1 node187 (squid/3.5.20)}{Connection: keep-alive}
Apr 14, 2018 10:25:19 PM sun.net.www.protocol.http.HttpURLConnection getHttpProxyAuthentication
FINER: Proxy Authentication for AuthenticationHeader: prefer null returned null

Exception in thread "main" java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
        at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2142)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
        at org.gradle.wrapper.Download.download(Download.java:51)
        at org.gradle.wrapper.Install$1.call(Install.java:62)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

bash-4.2$
```

Regards,
N.

**Comment by nevenr** [comment]
Hi,

in the same time with similar setting with curl we are able to download distribution 
```
bash-4.2$ export http_proxy=http://proxy-user:proxy-pass@proxy.host:8080
bash-4.2$ export https_proxy=http://proxy-user:proxy-pass@proxy.host:8080

bash-4.2$ curl -L -vvv -O https://services.gradle.org/distributions/gradle-4.4-bin.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* About to connect() to proxy proxy.host port 8080 (#0)
*   Trying 10.135.245.120...
* Connected to proxy.host (10.135.245.120) port 8080 (#0)
* Establish HTTP proxy tunnel to services.gradle.org:443
* Proxy auth using Basic with user 'proxy-user'
> CONNECT services.gradle.org:443 HTTP/1.1
> Host: services.gradle.org:443
> Proxy-Authorization: Basic cHJveHktdXNlcjpwcm94eS1wYXNz
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied OK to CONNECT request
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=ssl473435.cloudflaressl.com,OU=PositiveSSL Multi-Domain,OU=Domain Control Validated
*       start date: Mar 06 00:00:00 2018 GMT
*       expire date: Sep 12 23:59:59 2018 GMT
*       common name: ssl473435.cloudflaressl.com
*       issuer: CN=COMODO ECC Domain Validation Secure Server CA 2,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB
> GET /distributions/gradle-4.4-bin.zip HTTP/1.1
> User-Agent: curl/7.29.0
> Host: services.gradle.org
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Sat, 14 Apr 2018 23:15:05 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Cache-Control: max-age=3600
< Expires: Sun, 15 Apr 2018 00:15:05 GMT
< Location: https://downloads.gradle.org/distributions/gradle-4.4-bin.zip
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
< CF-RAY: 40b9df595c60972c-FRA
<
* Ignoring the response-body
{ [data not shown]
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host proxy.host left intact
* Issue another request to this URL: 'https://downloads.gradle.org/distributions/gradle-4.4-bin.zip'
* About to connect() to proxy proxy.host port 8080 (#1)
*   Trying 10.135.245.120...
* Connected to proxy.host (10.135.245.120) port 8080 (#1)
* Establish HTTP proxy tunnel to downloads.gradle.org:443
* Proxy auth using Basic with user 'proxy-user'
> CONNECT downloads.gradle.org:443 HTTP/1.1
> Host: downloads.gradle.org:443
> Proxy-Authorization: Basic cHJveHktdXNlcjpwcm94eS1wYXNz
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied OK to CONNECT request
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=ssl473435.cloudflaressl.com,OU=PositiveSSL Multi-Domain,OU=Domain Control Validated
*       start date: Mar 06 00:00:00 2018 GMT
*       expire date: Sep 12 23:59:59 2018 GMT
*       common name: ssl473435.cloudflaressl.com
*       issuer: CN=COMODO ECC Domain Validation Secure Server CA 2,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB
> GET /distributions/gradle-4.4-bin.zip HTTP/1.1
> User-Agent: curl/7.29.0
> Host: downloads.gradle.org
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Sat, 14 Apr 2018 23:15:05 GMT
< Content-Type: application/zip
< Content-Length: 75520391
< Connection: keep-alive
< Set-Cookie: __cfduid=dd15ca49f0e8db8c09082d908977440b01523747705; expires=Sun, 14-Apr-19 23:15:05 GMT; path=/; domain=.gradle.org; HttpOnly
< Last-Modified: Wed, 06 Dec 2017 09:13:42 GMT
< ETag: "7853dfc6e46ed2dc5050223275952a84"
< x-amz-meta-gradle-release-date: 20171206090506+0000
< x-amz-meta-md5-hash: 7853dfc6e46ed2dc5050223275952a84
< X-Cache: RefreshHit from cloudfront
< Via: 1.1 487cdcdf7a19623b97a27be170bb81f4.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: PGKqZCpVOFjwmi2qOfUWFPfcTZiJwZ3P4-ZwqYeFLtsZB_3eTF2-vg==
< CF-Cache-Status: HIT
< Expires: Sun, 14 Apr 2019 23:15:05 GMT
< Cache-Control: public, max-age=31536000
< Accept-Ranges: bytes
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
< CF-RAY: 40b9df59fd5f972c-FRA
<
{ [data not shown]
100 72.0M  100 72.0M    0     0  21.6M      0  0:00:03  0:00:03 --:--:-- 24.3M
* Connection #1 to host proxy.host left intact
bash-4.2$ ls -la gradle-4.4-bin.zip
-rw-r--r--. 1 user user 75520391 Apr 14 23:15 gradle-4.4-bin.zip
bash-4.2$
```

Regards,
N.

**Comment by tiliarou** [comment]
This happens on 4.0 rc2 as well...

**Comment by kapfab** [comment]
Same issue on our side.

We tried to set proxy credentials through the `GRADLE_OPTS` and `DEFAULT_JVM_ARGS` environment variables, via the `grade.properties` file, and some other sorcery tricks, but none worked.

We once thought it was working but it was in fact some other background process on the machine opening an IP-based session on our proxy a few minutes before !

So, for now, we do a dummy `curl` before every build to make sure subsequent Gradle builds can benefit from this pre-opened a proxy session.
This is quite awful but at least this is working in a predictable way.

From a more general standpoint, I don't understand why using authenticated proxies with Java command-line tools is so complicated…

**Comment by sschuberth** [comment]
It just occurred to me that for the *wrapper* to authenticate it seems you need to use the `systemProp.gradle.wrapperUser` and `systemProp.gradle.wrapperPassword` properties, as the docs on [Authenticated Gradle distribution download](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:authenticated_download) say "This can be used in conjunction with a proxy, authenticated or not".

**Comment by zmeeagain** [comment]
Could this be because after java 8u111 `Basic` authentication for https tunneling is not allowed? Had the same issue, and just allowed the scheme by adding `systemProp.jdk.http.auth.tunneling.disabledSchemes=""` to `gradle.properties`. Maybe not ideal security-wise, but does the job for the time being.

**Comment by pandel** [comment]
> 
> 
> Could this be because after java 8u111 `Basic` authentication for https tunneling is not allowed? Had the same issue, and just allowed the scheme by adding `systemProp.jdk.http.auth.tunneling.disabledSchemes=""` to `gradle.properties`. Maybe not ideal security-wise, but does the job for the time being.

You saved my day! That works perfectly well!

**Comment by sschuberth** [comment]
> When http.proxyHost, http.proxyPort, http.proxyUser and http.proxyPassword are specified in GRADLE_OPTS environment variable they should be respected during distribution downloading.

@nevenr, please note that as the distribution is downloaded via `https`, you should also use the `https.*` properties for the proxy. This is just to clarify, as I see in the log that you actually have both `http.*` and `https.*` properties set.

That said, my PR https://github.com/gradle/gradle/pull/12598 should fix the issue, and setting `https.*` should now work to download the distribution behind a proxy that requires authentication. It would be great if you could give it a try.

As a bonus, my branch will also respect the `http_proxy` / `https_proxy` environment variables when downloading the distribution.
