### ISSUE TITLE
Gnupg signatory does not support 'required' option

### ISSUE THREAD

**Issue by maxanier** [gradle/gradle#5064]
I having trouble setting up my project to sign my artifacts using my (smartcard) gnupg key only if the key is available (so other developers can still build test builds).

Setup:
```
signing {
    useGpgCmd()
    required = false
    sign jar
}
```

In my gradle.properties:
signing.keyId=xyzxyzxyz

The signing itself works fine if the key id is set and the smartcard/key is available.

However if I remove the key id from my properties the sign task fails even though I have set required to false:
```
Caused by: org.gradle.process.internal.ExecException: Process 'command 'gpg2'' finished with non-zero exit value 2
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:389)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:36)
        at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:189)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1087)
        at org.gradle.plugins.signing.signatory.internal.gnupg.GnupgSignatory.sign(GnupgSignatory.java:71)
        at org.gradle.plugins.signing.type.AbstractSignatureType.sign(AbstractSignatureType.java:65)
        at org.gradle.plugins.signing.type.pgp.ArmoredSignatureType.sign(ArmoredSignatureType.java:41)
        at org.gradle.plugins.signing.type.AbstractSignatureType$1$1.execute(AbstractSignatureType.java:49)
        at org.gradle.plugins.signing.type.AbstractSignatureType$1$1.execute(AbstractSignatureType.java:46)
        at org.gradle.internal.IoActions.withResource(IoActions.java:76)
        at org.gradle.plugins.signing.type.AbstractSignatureType$1.execute(AbstractSignatureType.java:46)
```

I have checked the signing extension code and it does not seem like the required option is supported by the gnupg part https://github.com/gradle/gradle/tree/master/subprojects/signing/src/main/java/org/gradle/plugins/signing/signatory/internal/gnupg.
Only the PGP signatory seems to (partly) support this. It returns a null signatory if the properties are not set and required is false as far as I can tell: https://github.com/gradle/gradle/blob/c6857d1d12eff2828a62e705fa03fa4e9d0d00da/subprojects/signing/src/main/java/org/gradle/plugins/signing/signatory/pgp/PgpSignatoryFactory.java#L87-L112

Is it possible to implement something similar for the gnupg part?
Thank you

```
./gradlew --version

------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_161 (Oracle Corporation 25.161-b12)
OS:           Linux 4.13.0-38-generic amd64
```

**Comment by marcphilipp** [comment]
@maxanier Looks like a bug to me, too!

As a workaround, you should be able to use

```gradle
tasks.withType(Sign) {
    onlyIf {
        project.hasProperty('signing.keyId')
    }
}
```

**Comment by maxanier** [comment]
Thank you!
That works perfectly for now :)

**Comment by rleigh-codelibre** [comment]
This doesn't work for me at all with 4.10.2.  If `useGpgCmd()` is present, then `onlyIf` has no effect: the GPG agent **always** prompts me.  I resorted to:

```
    signing {
        required { isReleaseVersion && gradle.taskGraph.hasTask("uploadArchives") }
        if (isReleaseVersion && project.hasProperty('signing.keyId')) {
            useGpgCmd()
        }
        sign configurations.archives
    }

    tasks.withType(Sign) {
        onlyIf { isReleaseVersion && project.hasProperty('signing.keyId') }
    }
```

which is massive overkill, but making the `useGpgCmd` itself conditional does prevent the unwanted prompts.  (there's no signing of CI builds or non-release builds, or builds where there's no signing key)

**Comment by Vampire** [comment]
I don't think **this**  should be changed, it behaves consistent and correct, but with 5.1 the situation got worse and **that** should be fixed.

Let me elaborate a bit what I mean.

The tasks standard `onlyIf` checks for `required || signatoryPresent`, so it is always done if it is required, if it is not required but a signatory is set, it is done too though, because "why not if it can".

For the standard PGP signatory it can only work if the `signing....` properties are set, so the signatory factory has this code that produces a `null` signatory if the properties are not set if the signing is not required.

For the GPG signatory this is different, you usually don't need any properties at all. There are some supported to change behavior, but none is required, so skipping the task if one of the properties is missing is a bad idea.

Now **if** a signatory is set (either PGP using the properites or GPG explicitly), the task is always run. If there is an error during signing, e. g. because of wrong configuration or file access problems or whatever, the signing fails with both signatories. So this is imho like expected and consistent and shouldn't change.

I actually wonder how setting `signing.keyId` changes anything when the GPG signatory is used, because this property should not have any effect actually. It is only used by the PGP singatory. To configure the key to be used by the GPG signatory you need to set the `signing.gnupg.keyName` property and if it is not set, the default key of the agent is used. So if the work-around provided here does not work for someone, he might try to use the correct property name instead. At least I tested with 4.10.2 and there only the documented key name property had any effect on the chosen key, not the key id property.

---

Now the problem I have is, that the situation got worse with 5.1 which introduced a (hopefully unintentional) breaking change with commit c216cc725d5217b813ea3515ea50c64aa08bed65.

Before this commit the keyId property was optional (The GPG signatory delivers the configured key name when the key id is requested):
```diff
     public Sign() {
         // If we aren't required and don't have a signatory then we just don't run
         onlyIf(task -> isRequired() || getSignatory() != null);
-
-        getInputs().property("signatory", new Callable<Object>() {
-            @Override
-            public Object call() throws Exception {
-                Signatory signatory = getSignatory();
-                return signatory == null ? null : signatory.getKeyId();
-            }
-        }).optional(true);
     }
```

After it, it suddenly is required now:
```diff
@@ -55,5 +58,6 @@ public interface Signatory {
      *
      * @return The key id
      */
+    @Input
     String getKeyId();
 }
```
```diff
@@ -374,6 +348,8 @@ public class Sign extends DefaultTask implements SignatureSpec {
      * Returns the signatory for this signing task.
      * @return the signatory
      */
+    @Nested
+    @Optional
     public Signatory getSignatory() {
         return signatory;
     }
```

So now the whole signatory stays optional, but if a signatory is set, the key id is mandatory.
Which is pretty bad, as not setting the key id means it uses the default key.

---

@maxanier I think you should instead investigate _why_ the gpg call is failing for you. If it is because you have no default key and you don't want to have a default key, then checking for the properties in your build script might be the correct way for you.
I usually make the call to `useGpgCmd()` dependent on a property I defined to be set to `true` as it is an environment question whether someone wants either or the other, so if no property is set, no signatory is set and if the GPG property is set, the GPG signatory gets configured.

**Comment by Vampire** [comment]
The code still seems to be the same in current master.
@marcphilipp can you maybe elaborate on whether the change was intentional?
