### ISSUE TITLE
Exception: cache.properties does not exist

### ISSUE THREAD

**Issue by wisechengyi** [gradle/gradle#5077]
Seeing gradle build cache throwing error on `cache.properties`

### Expected Behavior
No error on build cache operations. This issue does not affect the end build result. However, it does produce a lot of exceptions which makes the log confusing.

### Current Behavior
Seeing gradle throwing
```
16:16:03 org.gradle.api.GradleException: Build cache entry ece8e0a901dbcc0047c3a9c4e3433f81 from local build cache is invalid
16:16:03 	at org.gradle.caching.internal.controller.DefaultBuildCacheController.load(DefaultBuildCacheController.java:106)
16:16:03 	at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:79)
16:16:03 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
16:16:03 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
16:16:03 	at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:66)
16:16:03 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
16:16:03 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
16:16:03 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
16:16:03 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
16:16:03 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
16:16:03 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
16:16:03 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
16:16:03 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
16:16:03 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
16:16:03 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
16:16:03 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
16:16:03 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
16:16:03 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
16:16:03 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
16:16:03 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
16:16:03 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
16:16:03 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
16:16:03 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
16:16:03 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
16:16:03 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
16:16:03 	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
16:16:03 	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
16:16:03 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
16:16:03 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
16:16:03 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
16:16:03 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:16:03 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:16:03 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
16:16:03 	at java.lang.Thread.run(Thread.java:748)
16:16:03 Caused by: org.gradle.api.UncheckedIOException: java.io.FileNotFoundException: /dev/shm/android-build-cache/cache.properties (No such file or directory)
16:16:03 	at org.gradle.util.GUtil.loadProperties(GUtil.java:211)
16:16:03 	at org.gradle.cache.internal.DefaultPersistentDirectoryCache$Initializer.requiresInitialization(DefaultPersistentDirectoryCache.java:87)
16:16:03 	at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.incrementLockCount(LockOnDemandCrossProcessCacheAccess.java:107)
16:16:03 	at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.withFileLock(LockOnDemandCrossProcessCacheAccess.java:87)
16:16:03 	at org.gradle.cache.internal.DefaultCacheAccess.withFileLock(DefaultCacheAccess.java:198)
16:16:03 	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.withFileLock(DefaultPersistentDirectoryStore.java:163)
16:16:03 	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.withFileLock(DefaultCacheFactory.java:192)
16:16:03 	at org.gradle.caching.local.internal.DirectoryBuildCacheService.loadLocally(DirectoryBuildCacheService.java:96)
16:16:03 	at org.gradle.caching.internal.controller.service.DefaultLocalBuildCacheServiceHandle.load(DefaultLocalBuildCacheServiceHandle.java:49)
16:16:03 	at org.gradle.caching.internal.controller.DefaultBuildCacheController.load(DefaultBuildCacheController.java:104)
16:16:03 	... 33 more
16:16:03 Caused by: java.io.FileNotFoundException: /dev/shm/android-build-cache/cache.properties (No such file or directory)
16:16:03 	at java.io.FileInputStream.open0(Native Method)
16:16:03 	at java.io.FileInputStream.open(FileInputStream.java:195)
16:16:03 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
16:16:03 	at org.gradle.util.GUtil.loadProperties(GUtil.java:204)
16:16:03 	... 42 more
```
### Context
The error only seems to happen on CI machines where /dev/shm/android-build-cache is shared among multiple executors.
For example:
`/home/jenkins/workspace_0` and `/home/jenkins/workspace_1` are separate repos both running gradle, but they use `/dev/shm/android-build-cache` as their shared local cache location. 

### Steps to Reproduce (for bugs)

This only happens from time to time, so no consistent way to repro. I was wondering if the right assumption were made on reading/writing `cache.properties` in a concurrent context.

### Your Environment
Centos7

**Comment by wisechengyi** [comment]
A bit more context: potentially related to our periodically manual cleanup because we are not consuming #4950 yet, that a gradle build could be in flight while the local build cache directory is removed.

Not urgent issue, but I think the error handling can be more graceful and should not block further cache operations.

**Comment by lptr** [comment]
As you say, #4950 will solve the problems with periodical cleanup you might have currently. Once it ships with Gradle 4.8 there won't be need for external cleanup. Meanwhile, you could make sure that your cleanup script does not delete the `cache.properties` file.
