### ISSUE TITLE
NullPointerException in Gradle api. Could not resolve all files for configuration ':gems'.

### ISSUE THREAD

**Issue by ARnikev** [gradle/gradle#5121]
Hi!
I'm developing service using spring boot (with spring-boot-gradle-plugin) and use asciidoctor-gradle-plugin + jruby-gradle-plugin for my project docs generation. After migration of my project from spring boot 1.5.6.RELEASE to 2.0.0.RELEASE version i've run into a problem that 'asciidoctor' task, that assemble docs for my project, started to fail executing dependent 'jrubyPrepare' task with NullPointerException.

I've also reported this issue to 'jruby-gradle-plugin' repository ([issue](https://github.com/jruby-gradle/jruby-gradle-plugin/issues/326)) and to 'spring-boot' repository ([issue](https://github.com/spring-projects/spring-boot/issues/12897#issuecomment-382783051)).
Guys from spring-boot advised me to report this issue here as well, because actually NullPointerException occurs in Gradle api.

It would be great if you gave me some idea about what could be the problem. Thank you.

### Expected Behavior
When i run `./gradlew clean asciidoctor` tasks - documentation for my project should be built and put in `/build/asciidoc/` project folder.

### Current Behavior
Execution of task `asciidoctor` fails with following error:

```
Execution failed for task ":jrubyPrepare".
 Could not resolve all files for configuration ":gems".
    java.lang.NullPointerException (no error message)
```

Considering the log message, it fails while trying to resolve gems dependencies:

```
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':gems'.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:915)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1600(DefaultConfiguration.java:116)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:889)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(DefaultConfiguration.java:401)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
        at org.gradle.api.internal.file.CompositeFileCollection.getFiles(CompositeFileCollection.java:56)
        at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:68)
        at com.github.jrubygradle.GemUtils.getGems(GemUtils.groovy:33)
        at com.github.jrubygradle.GemUtils$getGems.call(Unknown Source)
        at com.github.jrubygradle.JRubyPrepare.gemsAsFileCollection(JRubyPrepare.groovy:36)
        at com.github.jrubygradle.JRubyPrepare.copy(JRubyPrepare.groovy:69)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 104 more
```

### Steps to Reproduce (for bugs)
I've made example project so you can reproduce this exception - [example](https://github.com/ARnikev/spring-boot-2-asciidoctor). You can reproduce the issue running such task:
`./gradlew clean asciidoctor`
If you change spring boot version to 1.5.6.RELEASE or comment out applying of 'org.springframework.boot' plugin - everything works fine.

### Your Environment
It's only possible to get build scan when applying of 'org.springframework.boot' plugin is commented out, because in the other case it fails. So here it is.
 * Build scan URL: https://scans.gradle.com/s/4hwkph7lxznbw

**Comment by lavcraft** [comment]
I`m using asciidoctor(jruby plugin) with asciidoctor-diagram and spring-boot. Reproduce this problem with Spring Boot 2.0.1.RELEASE

**Comment by psathesh** [comment]
Have the same issue. Stuck at this point now.

**Comment by fdw** [comment]
I also have this problem. Is there any way to help? Do you need more information?

**Comment by wilkinsona** [comment]
Spring Boot's plugin doesn't appear in the stacktrace of the failure, but it appears that there was some code in Spring Boot's plugin that was causing Gradle to get into a state where the NPE would occur.

The bad news is that I still think there's a bug in Gradle that causes it to corrupt its internal state. The good news is that the code in Spring Boot's plugin that was triggering this bug was [changed](https://github.com/spring-projects/spring-boot/pull/12784) in Spring Boot 2.0.2. The [original sample](https://github.com/ARnikev/spring-boot-2-asciidoctor) that was provided [above](https://github.com/ARnikev/spring-boot-2-asciidoctor) by @ARnikev works when upgraded to Spring Boot 2.0.2.

**Comment by lavcraft** [comment]
@wilkinsona thanks a lot!

**Comment by ghale** [comment]
Given that the original issue was resolved in the plugin, and that there have been a fair number of changes to the affected Gradle code over the last 6 months, I'm closing this issue for now.  If anyone can reproduce the problem with the latest Gradle, we can reopen and look into it.
