### ISSUE TITLE
Breaking change after lazy task creation

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#5148]
### Context

Recently I found a weird inconsistent behavior when investigating an issue. The following script:

```
apply plugin: 'java'

project.tasks.withType(JavaCompile).getByName("compileJava")
```

works well with `4.7`, but fail with latest nighty:

```
Caused by: org.gradle.api.UnknownTaskException: Task with name 'compileJava' not found in root project 'provider-issue'.
        at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:80)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:299)
        at org.gradle.api.internal.tasks.DefaultTaskCollection.getByName(DefaultTaskCollection.java:31)
        at org.gradle.api.internal.tasks.RealizableTaskCollection.getByName(RealizableTaskCollection.java:93)
        at org.gradle.api.tasks.TaskCollection$getByName$0.call(Unknown Source)
        at build_6gpl6y704b2h7ifa5j3mcj64i.run(/Users/zhb/Projects/tmp/provider-issue/build.gradle:10)
```

I don't think it's expected behavior. It seems to be related to this change: https://github.com/gradle/gradle/pull/4908 . 

The `compileJava` task is now created lazily, which results in a retrieve failure.

**Comment by big-guy** [comment]
Thanks @blindpirate -- we'll get this fixed.
