### ISSUE TITLE
Included builds should be run with their respective Gradle version, not with the one of the including build

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#5162]
Is it intended / expected that an included build is run with the Gradle version of the including build?
This seems to contradict the pattern that the build author defines the version of the build tool the build is designed for and should be used to build it.
If this does not hold for composite builds, that means to include a build I first have to make the other build compatible with the Gradle version I use or change my Gradle version to the one of the inculded build.
And if you include more than one build this sums up of course.

I just stumbled upon this, because I updated a build to a 4.8 snapshot to be able to use the new publication signing functionality and when I then tried to run the including build which still was on 4.6, it failed because it didn't find the `sign` method that is added in 4.8.

I'd expect that included builds are run with the version their wrapper configuration dictates instead of the Gradle version of the including build.

**Comment by oehme** [comment]
Yes, this is expected behavior. Making included builds work without them running in the same daemon would be a lot harder (and require more system resources) than integrating them into one build tree. We don't plan to add such a more isolated option any time soon, though it is not completely out of question either, for the reasons you mentioned.

**Comment by Vampire** [comment]
Ok, I see.
This somewhat lowers the usefulness of this feature that I heavily advertised before much.
I'll wait then and hope this gets implemented. :-)

**Comment by Vampire** [comment]
@oehme can you maybe help me with a little problem somehow maybe related to this?
I before had including build Gradle 4.6 and included build Gradle 4.6.
As the included build is not on `gradle-4.8-20180421000019+0000-bin.zip`, I also changed the including build to `gradle-4.8-20180421000019+0000-bin.zip`, but if I now try to synchronize the including build in InteliJ IDEA 2016.1.4, I get

```
Caused by: java.lang.IllegalStateException: The root project is not yet available for build.
        at org.gradle.invocation.DefaultGradle.getRootProject(DefaultGradle.java:216)
        at org.gradle.invocation.DefaultGradle_Decorated.getRootProject(Unknown Source)
        at org.gradle.tooling.internal.provider.runner.ClientProvidedBuildActionRunner.forceFullConfiguration(ClientProvidedBuildActionRunner.java:97)
        ... 86 more
```

Did I do something wrong, or is this a regression bug I should report?

**Comment by oehme** [comment]
That looks like a bug. Do you also see this with 4.7?

**Comment by Vampire** [comment]
wth, now it doesn't even work with 4.6 with commented out signing anymore, with a different error though

```java
2018-04-25 11:14:56,587 [57122082]   WARN - nal.AbstractExternalSystemTask - Can't parse gradle module dependency 'DefaultIdeaModuleDependency{scope='IdeaDependencyScope{scope='COMPILE'}', targetModuleName='javacord-api', exported=false}'. Reason: referenced module is null
com.intellij.openapi.externalSystem.model.ExternalSystemException: Can't parse gradle module dependency 'DefaultIdeaModuleDependency{scope='IdeaDependencyScope{scope='COMPILE'}', targetModuleName='javacord-api', exported=false}'. Reason: referenced module is null
        at org.jetbrains.plugins.gradle.service.project.AbstractProjectImportErrorHandler.createUserFriendlyError(AbstractProjectImportErrorHandler.java:106)
        at org.jetbrains.plugins.gradle.service.project.BaseProjectImportErrorHandler.getUserFriendlyError(BaseProjectImportErrorHandler.java:158)
        at org.jetbrains.plugins.gradle.service.project.BaseGradleProjectResolverExtension.getUserFriendlyError(BaseGradleProjectResolverExtension.java:580)
        at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:158)
        at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:158)
        at com.android.tools.idea.gradle.project.AndroidGradleProjectResolver.getUserFriendlyError(AndroidGradleProjectResolver.java:351)
        at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:158)
        at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:158)
        at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:772)
        at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:752)
        at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.execute(GradleExecutionHelper.java:228)
        at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:112)
        at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:73)
        at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl$1.produce(RemoteExternalSystemProjectResolverImpl.java:41)
        at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl$1.produce(RemoteExternalSystemProjectResolverImpl.java:37)
        at com.intellij.openapi.externalSystem.service.remote.AbstractRemoteExternalSystemService.execute(AbstractRemoteExternalSystemService.java:59)
        at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.resolveProjectInfo(RemoteExternalSystemProjectResolverImpl.java:37)
        at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemProjectResolverWrapper.resolveProjectInfo(ExternalSystemProjectResolverWrapper.java:49)
        at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:51)
        at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:138)
        at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:124)
        at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:419)
        at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$4$2.run(ExternalSystemUtil.java:500)
        at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
        at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
        at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
        at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by Vampire** [comment]
Ok, now to the semi-orginal problem, it is a regression in 4.8, with 4.7 it works

**Comment by Vampire** [comment]
Same in latest nightly, so this seems to be a bug indeed, I delete my comments here and open a new ticket

**Comment by Vampire** [comment]
Still relevant
