### ISSUE TITLE
Gradle Test Executor is crashed with jacoco with-options `includeNoLocationClasses` on JDK 9

### ISSUE THREAD

**Issue by wreulicke** [gradle/gradle#5184]
### Expected Behavior

Gradle Test Executor executes successfully when enabled `includeNoLocationClasses` in jacoco plugin on JDK9.

### Current Behavior

Gradle Test Executor crashed when enabled `includeNoLocationClasses` in jacoco plugin on JDK9.

I attached stacktrace when crashed below.

```
$  ./gradlew clean test
> Task :test
java.lang.NoClassDefFoundError: jdk/internal/reflect/GeneratedSerializationConstructorAccessor1
        at jdk.internal.reflect.GeneratedSerializationConstructorAccessor1.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
        at java.base/java.io.ObjectStreamClass.newInstance(ObjectStreamClass.java:1081)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2062)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1585)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:107)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:64)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:62)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:67)
Caused by: java.lang.ClassNotFoundException: jdk.internal.reflect.GeneratedSerializationConstructorAccessor1
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 10 more
java.lang.NoClassDefFoundError: jdk/internal/reflect/GeneratedSerializationConstructorAccessor1
        at jdk.internal.reflect.GeneratedSerializationConstructorAccessor1.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
        at java.base/java.io.ObjectStreamClass.newInstance(ObjectStreamClass.java:1081)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2062)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1585)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:107)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:64)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:62)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:67)
Caused by: java.lang.ClassNotFoundException: jdk.internal.reflect.GeneratedSerializationConstructorAccessor1
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 10 more
Process 'Gradle Test Executor 2' finished with non-zero exit value 1
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 2' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:389)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.onProcessStop(DefaultWorkerProcess.java:118)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.access$000(DefaultWorkerProcess.java:41)
        at org.gradle.process.internal.worker.DefaultWorkerProcess$1.executionFinished(DefaultWorkerProcess.java:74)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy77.executionFinished(Unknown Source)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:207)
        at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHandle.java:334)
        at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:102)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:82)
        at org.gradle.internal.operations.BuildOperationIdentifierPreservingRunnable.run(BuildOperationIdentifierPreservingRunnable.java:39)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.NoClassDefFoundError: jdk/internal/reflect/GeneratedSerializationConstructorAccessor1
        at jdk.internal.reflect.GeneratedSerializationConstructorAccessor1.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
        at java.base/java.io.ObjectStreamClass.newInstance(ObjectStreamClass.java:1081)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2062)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1585)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:107)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:64)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:62)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:67)
Caused by: java.lang.ClassNotFoundException: jdk.internal.reflect.GeneratedSerializationConstructorAccessor1
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 10 more
Process 'Gradle Test Executor 3' finished with non-zero exit value 1
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 3' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:389)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.onProcessStop(DefaultWorkerProcess.java:118)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.access$000(DefaultWorkerProcess.java:41)
        at org.gradle.process.internal.worker.DefaultWorkerProcess$1.executionFinished(DefaultWorkerProcess.java:74)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy77.executionFinished(Unknown Source)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:207)
        at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHandle.java:334)
        at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:102)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:82)
        at org.gradle.internal.operations.BuildOperationIdentifierPreservingRunnable.run(BuildOperationIdentifierPreservingRunnable.java:39)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.NoClassDefFoundError: jdk/internal/reflect/GeneratedSerializationConstructorAccessor1
        at jdk.internal.reflect.GeneratedSerializationConstructorAccessor1.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
        at java.base/java.io.ObjectStreamClass.newInstance(ObjectStreamClass.java:1081)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2062)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1585)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:107)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:64)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:62)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:67)
Caused by: java.lang.ClassNotFoundException: jdk.internal.reflect.GeneratedSerializationConstructorAccessor1
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 10 more
Process 'Gradle Test Executor 4' finished with non-zero exit value 1
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 4' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:389)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.onProcessStop(DefaultWorkerProcess.java:118)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.access$000(DefaultWorkerProcess.java:41)
        at org.gradle.process.internal.worker.DefaultWorkerProcess$1.executionFinished(DefaultWorkerProcess.java:74)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy77.executionFinished(Unknown Source)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:207)
        at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHandle.java:334)
        at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:102)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:82)
        at org.gradle.internal.operations.BuildOperationIdentifierPreservingRunnable.run(BuildOperationIdentifierPreservingRunnable.java:39)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:844)
``` 

### Context

project and jacoco settings here.
I try to remove `enabled = System.getProperty("java.specification.version") != "9"`
https://github.com/spotbugs/spotbugs-gradle-plugin/blob/1.6.1/gradle/jacoco.gradle#L15-L17

### Steps to Reproduce (for bugs)

* clone and checkout code.
https://github.com/spotbugs/spotbugs-gradle-plugin/blob/1.6.1/gradle/jacoco.gradle#L15-L17

* remove `enabled = System.getProperty("java.specification.version") != "9"` in `gradle/jacoco.gradle`

* execute tests.

```
./gradlew clean test
```

### Your Environment

```bash
$  ./gradlew -version

------------------------------------------------------------
Gradle 4.5.1
------------------------------------------------------------

Build time:   2018-02-05 13:22:49 UTC
Revision:     37007e1c012001ff09973e0bd095139239ecd3b3

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          9.0.4 (Oracle Corporation 9.0.4+11)
OS:           Mac OS X 10.13.4 x86_64
```

**Comment by marcphilipp** [comment]
Have you tried the latest JaCoCo version? IIRC it only supports Java 9 since 0.8.0. Your environment output above says JDK 8 but you were using JDK 9, right?

**Comment by wreulicke** [comment]
sorry, `gradle -version` output's is wrong due to mistake.
I rewrote.

The project use jacoco 0.7.9, but I updated to 0.8.1.

**Comment by wreulicke** [comment]
@marcphilipp ping

**Comment by marcphilipp** [comment]
Adding `excludes = ['jdk.internal.*']` to the `jacoco` config resolves this error.

@wreulicke Does that work for you?

**Comment by idrisadetunmbi** [comment]
I am having this same exact issue

**Comment by marcphilipp** [comment]
@oehme I'm inclined to close this issue since most users will not use `includeNoLocationClasses` and generating coverage for JDK internal classes is not really a use case. I thought about adding default excludes, but those are likely to differ on different JDKs. What do you think?

**Comment by oehme** [comment]
I agree, especially since the workaround is simple.

**Comment by marcphilipp** [comment]
Alright, closing this issue for now.

**Comment by tmehta813** [comment]
> This is an old issue, but for future google searchers and perhaps interested parties that could work around this, it is worth mentioning that if you are using one of the more popular walk-throughs to set up JaCoCo + Robolectric + Espresso - https://medium.com/@rafael_toledo/setting-up-an-unified-coverage-report-in-android-with-jacoco-robolectric-and-espresso-ffe239aaf3fa - you will indeed be using "includeNoLocationClasses", so you will see this error with Java9+ and probably end up here. The workaround does work though, and the required modification (per [the followup article](https://proandroiddev.com/unified-code-coverage-for-android-revisited-44789c9b722f) on the setup guide I linked above) is:
> 
> ```
> tasks.withType(Test) {
>     jacoco.includeNoLocationClasses = true
>     jacoco.excludes = ['jdk.internal.*']
> }
> ```

Thank you, you saved me

**Comment by alan-czajkowski** [comment]
does anybody have a configuration that is valid for 2021?
JaCoCo coverage report configuration that works with Gradle 6.8 or 7.0 with JaCoCo 0.8.6 ... all examples online are for prior versions and are not valid anymore

**Comment by mikehardy** [comment]
I'm using Gradle 7 as of a few days ago. I'm using JaCoCo 0.8.6. It's all working fine.
We've got all our stuff in AnkiDroid in one file, so it's easy to see how it all fits together

https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/jacoco.gradle

Cheers @alan-czajkowski

**Comment by alan-czajkowski** [comment]
@mikehardy that is one of the best comprehensive examples I've seen anywhere online, thanks! this will help a lot in getting the reports into SonarQube

**Comment by tmehta813** [comment]
@alan-czajkowski 
you can use below configuration which I've setup few days back, working fine for me


1. if you've variant in your app module eg. "mock" use below code 
if you don't have any variant then remove mock from below code wherever it is mentioned. 

apply plugin: 'jacoco'

jacoco {
    toolVersion = '0.8.5' //Use latest version
    reportsDir = file("$buildDir/reports/jacoco")
}
tasks.withType(Test) {
    jacoco.includeNoLocationClasses = true
    jacoco.excludes = ['jdk.internal.*']
}

task jacocoTestReport(type: JacocoReport, dependsOn: ['testMockDebugUnitTest', 'createMockDebugCoverageReport']) {
    reports {
        xml {
            enabled = true
        }
        csv.enabled false
        html {
            enabled true
        }
    }

    def fileFilter = ['**/R.class',
                      '**/R$*.class',
                      '**/BuildConfig.*',
                      '**/Manifest*.*',
                      '**/*Test*.*',
                      'android/**/*.*',
                      '**/*$[0-9].*',
                      '**/*Dao**',
                      '**/*Receiver**',
                      '**/*Activity**',
                      '**/*Service**',
                      '**/*Application**'
    ]
    def debugTree = fileTree(dir: "$project.buildDir/tmp/kotlin-classes/mockDebug", excludes: fileFilter)
    def mainSrc = "$project.projectDir/src/main/java"

    getSourceDirectories().setFrom(files([mainSrc]))
    getClassDirectories().setFrom(files([debugTree]))
    getExecutionData().setFrom(fileTree(dir: project.buildDir, includes: ['jacoco/tesMockDebugUnitTest.exec',
                                                                          'outputs/code_coverage/MockDebugAndroidTest/connected/**/*.ec']))
}

**Comment by rugged-bl** [comment]
Also updating to [JaCoCo 0.8.7](https://www.jacoco.org/jacoco/trunk/doc/changes.html) might help if you got in trouble after updating to **Kotlin 1.5**+

**Comment by Bradleycorn** [comment]
has anyone tried this with Kotlin? The above mentioned solutions/workaround from @mikehardy and @tmehta813  don't seem to work fully. They do seem to fix the original issue. However there is new issue where jacoco execution data doesn't match, and so all coverage reports show as 0% coverage.

**Comment by silin** [comment]
> has anyone tried this with Kotlin? The above mentioned solutions/workaround from @mikehardy and @tmehta813 don't seem to work fully for me. They do seem to fix the original issue. However there is new issue where jacoco execution data doesn't match, and so all coverage reports show as 0% coverage. Has anyone else run into this issue?

Tried, everything works fine. In Kotlin it looks like this (assuming Jacoco plugin applied):
```
tasks.withType<Test> {
    extensions.configure(JacocoTaskExtension::class) {
        isIncludeNoLocationClasses = true
        excludes = listOf("jdk.internal.*")
    }
}
```

**Comment by aljohnston112** [comment]
@[tmehta813](https://github.com/tmehta813)'s solution does not work with ActivityScenario.
See https://github.com/android/android-test/issues/1377
