### ISSUE TITLE
ConnectionScopeServices does not honor GradleConnection home setting

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#5188]
We're unable to use Gradle embedded in a service with a service user that does not have permission to it's home directory:

```
org.gradle.api.UncheckedIOException: Failed to create parent directory '/var/www/.gradle' when creating directory '/var/www/.gradle/daemon/4.7'
	at org.gradle.util.GFileUtils.mkdirs(GFileUtils.java:310) ~[?:?]
	at org.gradle.launcher.daemon.registry.DaemonDir.<init>(DaemonDir.java:33) ~[?:?]
	at org.gradle.launcher.daemon.registry.DaemonRegistryServices.createDaemonDir(DaemonRegistryServices.java:52) ~[?:?]
	...
```

It appears there's a default `DaemonParameters`/`BuildLayoutParameters` initialized in `ConnectionScopeServices` when initialing the `DaemonStopClient` service, which causes the failure:
```
    ShutdownCoordinator createShutdownCoordinator(ListenerManager listenerManager, DaemonClientFactory daemonClientFactory, OutputEventListener outputEventListener) {
        ServiceRegistry clientServices = daemonClientFactory.createStopDaemonServices(outputEventListener, new DaemonParameters(new BuildLayoutParameters()));
        DaemonStopClient client = clientServices.get(DaemonStopClient.class);
        ShutdownCoordinator shutdownCoordinator = new ShutdownCoordinator(client);
        listenerManager.addListener(shutdownCoordinator);
        return shutdownCoordinator;
    }
```

### Expected Behavior
The connection should succeed.

### Current Behavior
The connection fails, due to a permission error.

### Steps to Reproduce (for bugs)
Attempt to create a tooling API connection for user that does not have permission to login/have permission to their home directory.

### Your Environment
Gradle 4.7

### Full Stack Trace

```
Caused by: org.gradle.internal.service.ServiceCreationException: Could not create service of type ShutdownCoordinator using ConnectionScopeServices.createShutdownCoordinator().
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:816) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:767) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:571) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:628) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:780) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:766) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:571) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:628) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry.find(DefaultServiceRegistry.java:295) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:284) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:279) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.provider.DefaultConnection.initializeServices(DefaultConnection.java:125) ~[?:?]
	at org.gradle.tooling.internal.provider.DefaultConnection.configure(DefaultConnection.java:102) ~[?:?]
	at org.gradle.tooling.internal.consumer.connection.AbstractPost12ConsumerConnection.configure(AbstractPost12ConsumerConnection.java:37) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.loader.DefaultToolingImplementationLoader.createConnection(DefaultToolingImplementationLoader.java:115) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.loader.DefaultToolingImplementationLoader.create(DefaultToolingImplementationLoader.java:91) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:44) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(SynchronizedToolingImplementationLoader.java:53) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(LazyConsumerActionExecutor.java:101) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:83) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46) ~[gradle-tooling-api-4.7.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_152]
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55) ~[gradle-tooling-api-4.7.jar:?]
	... 1 more
Caused by: org.gradle.internal.service.ServiceCreationException: Could not create service of type DaemonDir using DaemonRegistryServices.createDaemonDir().
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:816) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:767) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:571) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:628) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:780) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:766) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:571) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:628) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:780) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:766) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:571) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:628) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:780) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:766) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:571) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:628) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry.find(DefaultServiceRegistry.java:295) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:284) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:279) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.provider.ConnectionScopeServices.createShutdownCoordinator(ConnectionScopeServices.java:61) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.ReflectionBasedServiceMethod.invoke(ReflectionBasedServiceMethod.java:35) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:814) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:767) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:571) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:628) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:780) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:766) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:571) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:628) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry.find(DefaultServiceRegistry.java:295) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:284) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:279) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.provider.DefaultConnection.initializeServices(DefaultConnection.java:125) ~[?:?]
	at org.gradle.tooling.internal.provider.DefaultConnection.configure(DefaultConnection.java:102) ~[?:?]
	at org.gradle.tooling.internal.consumer.connection.AbstractPost12ConsumerConnection.configure(AbstractPost12ConsumerConnection.java:37) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.loader.DefaultToolingImplementationLoader.createConnection(DefaultToolingImplementationLoader.java:115) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.loader.DefaultToolingImplementationLoader.create(DefaultToolingImplementationLoader.java:91) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:44) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(SynchronizedToolingImplementationLoader.java:53) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(LazyConsumerActionExecutor.java:101) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:83) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46) ~[gradle-tooling-api-4.7.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_152]
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55) ~[gradle-tooling-api-4.7.jar:?]
	... 1 more
Caused by: org.gradle.api.UncheckedIOException: Failed to create parent directory '/var/www/.gradle' when creating directory '/var/www/.gradle/daemon/4.7'
	at org.gradle.util.GFileUtils.mkdirs(GFileUtils.java:310) ~[?:?]
	at org.gradle.launcher.daemon.registry.DaemonDir.<init>(DaemonDir.java:33) ~[?:?]
	at org.gradle.launcher.daemon.registry.DaemonRegistryServices.createDaemonDir(DaemonRegistryServices.java:52) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.ReflectionBasedServiceMethod.invoke(ReflectionBasedServiceMethod.java:35) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:814) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:767) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:571) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:628) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:780) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:766) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:571) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:628) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:780) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:766) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:571) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:628) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:780) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:766) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:571) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:628) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry.find(DefaultServiceRegistry.java:295) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:284) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:279) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.provider.ConnectionScopeServices.createShutdownCoordinator(ConnectionScopeServices.java:61) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.ReflectionBasedServiceMethod.invoke(ReflectionBasedServiceMethod.java:35) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:814) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:767) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:571) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:628) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:780) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:766) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:571) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:628) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry.find(DefaultServiceRegistry.java:295) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:284) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:279) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.provider.DefaultConnection.initializeServices(DefaultConnection.java:125) ~[?:?]
	at org.gradle.tooling.internal.provider.DefaultConnection.configure(DefaultConnection.java:102) ~[?:?]
	at org.gradle.tooling.internal.consumer.connection.AbstractPost12ConsumerConnection.configure(AbstractPost12ConsumerConnection.java:37) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.loader.DefaultToolingImplementationLoader.createConnection(DefaultToolingImplementationLoader.java:115) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.loader.DefaultToolingImplementationLoader.create(DefaultToolingImplementationLoader.java:91) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:44) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(SynchronizedToolingImplementationLoader.java:53) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(LazyConsumerActionExecutor.java:101) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:83) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63) ~[gradle-tooling-api-4.7.jar:?]
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46) ~[gradle-tooling-api-4.7.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_152]
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55) ~[gradle-tooling-api-4.7.jar:?]
	... 1 more
```

**Comment by DanielThomas** [comment]
Looking at `org.gradle.initialization.BuildLayoutParameters#BuildLayoutParameters`, I should be able to workaround this by setting `org.gradle.initialization.BuildLayoutParameters#GRADLE_USER_HOME_PROPERTY_KEY`.

**Comment by scott-pollom** [comment]
I'm hitting this bug when using `GradleConnector` in a test that is run via Bazel on Linux.

I can work around the issue by calling `System.setProperty("gradle.user.home", "")`
