### ISSUE TITLE
Tar task: 'java.lang.UnsupportedOperationException' for content filtering from tar archive to tar archive

### ISSUE THREAD

**Issue by wszeboreq** [gradle/gradle#5230]
### Expected Behavior

I wanted to create a tar archive ('test_archive.tar') containg the filtered contents of the other archive ('test_file.tar.gz'). The source archive contains a 'test_file.txt' file with a 'Test file content.' line, I expected filtering to change this line in target archive into 'My test file content.'.

```
task testTar(type: Tar) {
    baseName "test_archive"
    
    from tarTree("test_file.tar.gz")
    filter { line -> return line.replaceFirst("Test", "My test") }
}
```

### Current Behavior

I'm getting the foollowing exception ('java.lang.UnsupportedOperationException: The contents of tar entry D:\home\wszebor\dv\builds\cpptest.build\test_file.tar.gz!test_file.txt has already been read.'):

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':testTar'.
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
  at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
  at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
  at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
  at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
  at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
  at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
  at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
  at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
  at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
  at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
  at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
  at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
  at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
  at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
  at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
  at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
  at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
  at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
  at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
  at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
  at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
  at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
  at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
  at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:596)
  at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
  at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
  at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
  at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: Unable to expand TAR 'D:\home\wszebor\dv\builds\cpptest.build\test_file.tar.gz'
  The tar might be corrupted or it is compressed in an unexpected way.
  By default the tar tree tries to guess the compression based on the file extension.
  If you need to specify the compression explicitly please refer to the DSL reference.
  at org.gradle.api.internal.file.archive.TarFileTree.visit(TarFileTree.java:94)
  at org.gradle.api.internal.file.collections.FileTreeAdapter.visit(FileTreeAdapter.java:116)
  at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTreeImpl.visit(AbstractFileTree.java:189)
  at org.gradle.api.internal.file.CompositeFileTree.visit(CompositeFileTree.java:87)
  at org.gradle.api.internal.file.copy.CopySpecActionImpl.execute(CopySpecActionImpl.java:39)
  at org.gradle.api.internal.file.copy.CopySpecActionImpl.execute(CopySpecActionImpl.java:24)
  at org.gradle.api.internal.file.copy.DefaultCopySpec$DefaultCopySpecResolver.walk(DefaultCopySpec.java:707)
  at org.gradle.api.internal.file.copy.DefaultCopySpec$DefaultCopySpecResolver.walk(DefaultCopySpec.java:709)
  at org.gradle.api.internal.file.copy.DefaultCopySpec.walk(DefaultCopySpec.java:513)
  at org.gradle.api.internal.file.copy.CopySpecBackedCopyActionProcessingStream.process(CopySpecBackedCopyActionProcessingStream.java:38)
  at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator$1.process(DuplicateHandlingCopyActionDecorator.java:44)
  at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator$1.process(NormalizingCopyActionDecorator.java:57)
  at org.gradle.api.internal.file.archive.TarCopyAction$1.doExecute(TarCopyAction.java:68)
  at org.gradle.api.internal.file.archive.TarCopyAction$1.doExecute(TarCopyAction.java:58)
  at org.gradle.internal.ErroringAction.execute(ErroringAction.java:35)
  at org.gradle.internal.IoActions.withResource(IoActions.java:76)
  at org.gradle.api.internal.file.archive.TarCopyAction.execute(TarCopyAction.java:58)
  at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator.execute(NormalizingCopyActionDecorator.java:53)
  at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator.execute(DuplicateHandlingCopyActionDecorator.java:42)
  at org.gradle.api.internal.file.copy.CopyActionExecuter.execute(CopyActionExecuter.java:40)
  at org.gradle.api.tasks.AbstractCopyTask.copy(AbstractCopyTask.java:179)
  at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
  at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
  at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
  at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
  at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:794)
  at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:761)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
  at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
  at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
  at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
  at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
  at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
  ... 29 more
Caused by: org.gradle.api.GradleException: Could not add tar entry D:\home\wszebor\dv\builds\cpptest.build\test_file.tar.gz!test_file.txt to TAR 'test_archive.tar'.
  at org.gradle.api.internal.file.archive.TarCopyAction$StreamAction.visitFile(TarCopyAction.java:101)
  at org.gradle.api.internal.file.archive.TarCopyAction$StreamAction.processFile(TarCopyAction.java:87)
  at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator$1$1.processFile(NormalizingCopyActionDecorator.java:66)
  at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator$1$1.processFile(DuplicateHandlingCopyActionDecorator.java:60)
  at org.gradle.api.internal.file.copy.CopyFileVisitorImpl.processFile(CopyFileVisitorImpl.java:62)
  at org.gradle.api.internal.file.copy.CopyFileVisitorImpl.visitFile(CopyFileVisitorImpl.java:46)
  at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTreeImpl$1.visitFile(AbstractFileTree.java:198)
  at org.gradle.api.internal.file.archive.TarFileTree.visitImpl(TarFileTree.java:107)
  at org.gradle.api.internal.file.archive.TarFileTree.visit(TarFileTree.java:85)
  ... 63 more
Caused by: java.lang.UnsupportedOperationException: The contents of tar entry D:\home\wszebor\dv\builds\cpptest.build\test_file.tar.gz!test_file.txt has already been read.
  at org.gradle.api.internal.file.archive.TarFileTree$DetailsImpl.open(TarFileTree.java:221)
  at org.gradle.api.internal.file.copy.DefaultFileCopyDetails.open(DefaultFileCopyDetails.java:93)
  at org.gradle.api.internal.file.AbstractFileTreeElement.copyTo(AbstractFileTreeElement.java:56)
  at org.gradle.api.internal.file.copy.DefaultFileCopyDetails.copyTo(DefaultFileCopyDetails.java:101)
  at org.gradle.api.internal.file.archive.TarCopyAction$StreamAction.visitFile(TarCopyAction.java:98)
  ... 71 more

```

Commenting out the 'filter' line in 'testTar' task makes the target tar archive successfully created.

### Your Environment

> ------------------------------------------------------------
> Gradle 4.7
> ------------------------------------------------------------
> 
> Build time:   2018-04-18 09:09:12 UTC
> Revision:     b9a962bf70638332300e7f810689cb2febbd4a6c
> 
> Groovy:       2.4.12
> Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
> JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
> OS:           Windows 10 10.0 amd64

**Comment by marcphilipp** [comment]
I can reproduce the bug. As a workaround extract the TAR archive first:

```gradle
def tmpDir = file("$buildDir/tmp")

task extractAndFilter(type: Copy) {
    from tarTree('test_file.tar.gz')
    into tmpDir
    filter { line -> line.replaceFirst("Test", "My test") }
}

task testTar(type: Tar) {
    dependsOn extractAndFilter
    baseName "test_archive"
    from tmpDir
}
```

**Comment by wszeboreq** [comment]
Thank you for confirmation and for accepting the bug. We are already using the proposed workaround, unfortunately it decreases the performance. I forgot to mention that with Zip task the problem does not occur.

Basing on your experience, how do you think - when this problem will be fixed?

**Comment by marcphilipp** [comment]
I haven't looked into the code and thus don't know how easy or hard it will be to fix. Would you be interested in submitting a pull request?

**Comment by wszeboreq** [comment]
Unfortunately, honesty speaking, I think I don't have the necessary abilities. Our gradle adventure has just started.

**Comment by wszeboreq** [comment]
Any chances to have it assigned to some milestone?
