### ISSUE TITLE
gradle build --scan fails

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle#5709]
Build scan fails on a composite build using Gradle 4.8 with Java 10.0.1+10 on macOS 10.13.5.

The URL for bug reporting doesn't work, either:

https://gradle.com/scans/help/plugin

Here's the error info:

```
Gradle version: 4.8
Plugin version: 1.13.4

java.lang.IllegalStateException: Root project has not been attached.
        at org.gradle.invocation.DefaultGradle.getIdentityPath(DefaultGradle.java:112)
        at org.gradle.invocation.DefaultGradle_Decorated.getIdentityPath(Unknown Source)
        at org.gradle.initialization.DefaultGradleLauncher$LoadBuild$1.getBuildPath(DefaultGradleLauncher.java:252)
        at com.gradle.scan.plugin.internal.a.i.c$1.a(SourceFile:48)
        at com.gradle.scan.plugin.internal.a.i.c$1.a(SourceFile:45)
        at com.gradle.scan.plugin.internal.a.i.c$d.a(SourceFile:136)
        at com.gradle.scan.plugin.internal.i.d.a(SourceFile:23)
        at com.gradle.scan.plugin.internal.i.k.a(SourceFile:45)
        at com.gradle.scan.plugin.internal.i.k.a(SourceFile:39)
        at com.gradle.scan.plugin.internal.i.k.a(SourceFile:17)
        at com.gradle.scan.plugin.internal.i.p.a(SourceFile:33)
        at com.gradle.scan.plugin.internal.i.o.a(SourceFile:20)
        at com.gradle.scan.plugin.internal.i.h.a(SourceFile:56)
        at com.gradle.scan.plugin.internal.i.i$c$1.started(SourceFile:33)
        at org.gradle.internal.operations.notify.BuildOperationNotificationBridge$ReplayAndAttachListener.started(BuildOperationNotificationBridge.java:329)
        at org.gradle.internal.operations.notify.BuildOperationNotificationBridge$Adapter.started(BuildOperationNotificationBridge.java:212)
        at org.gradle.internal.operations.DefaultBuildOperationListenerManager$ProgressShieldingBuildOperationListener.started(DefaultBuildOperationListenerManager.java:115)
        at org.gradle.internal.operations.DefaultBuildOperationListenerManager$1.started(DefaultBuildOperationListenerManager.java:44)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:177)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.initialization.DefaultGradleLauncher.loadSettings(DefaultGradleLauncher.java:167)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:128)
        at org.gradle.initialization.DefaultGradleLauncher.getConfiguredBuild(DefaultGradleLauncher.java:110)
        at org.gradle.initialization.DefaultGradleLauncher.scheduleTasks(DefaultGradleLauncher.java:191)
        at org.gradle.composite.internal.DefaultIncludedBuild.execute(DefaultIncludedBuild.java:205)
        at org.gradle.composite.internal.DefaultIncludedBuildController.doBuild(DefaultIncludedBuildController.java:164)
        at org.gradle.composite.internal.DefaultIncludedBuildController.run(DefaultIncludedBuildController.java:94)
        at org.gradle.composite.internal.DefaultIncludedBuildControllers$BuildOpRunnable.run(DefaultIncludedBuildControllers.java:112)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
```

**Comment by ldaley** [comment]
@rgoldberg thanks for reporting.

It seems to be something particular about your composite build, that I am unable to reproduce. Are you able to create a small sample reproducing the problem that you can share?

**Comment by breskeby** [comment]
@rgoldberg I can reproduce the problem you describe. In general build scan do currently not support plugin composites, but should provide you a meaningful warning instead of the error you're experiencing. your `passThroughTaskToIncludedBuilds` logic seems to cause the plugin composite detection to fail. when commenting this out the `--scan` provides you with the warning I mentioned above. thanks again for reporting this issue. We're working on a fix

**Comment by rgoldberg** [comment]
Thanks for investigating.

If you have a moment, I've replaced `passThroughTaskToIncludedBuilds` with the following code (not to fix this problem, but just to improve it).  Is anything missing? Is anything improvable?

```
fun createDelegatingToAllTask(delegateTaskName: String, groupName: String? = null, newTaskName: String = delegateTaskName + "All") {
	task(newTaskName) {
		group = groupName

		dependsOn(getTasksByName(delegateTaskName, true))

		val taskPath = ':' + delegateTaskName
		dependsOn(gradle.includedBuilds.map {it.task(taskPath)})
	}
}
```

**Comment by breskeby** [comment]
hey @rgoldberg,

don't get me wrong here. Your `passThroughTaskToIncludedBuilds` is totally valid. it's just that the detection for unsupported scenarios in the build scan plugin is broken. your build is just exposing this issue. 
the root cause is that you have an included build that is referenced as a plugin (see util plugin block) _AND_ explicitly in your build by adding a task dependency on it. in general your code looks legit. keep in mind though, that the java plugin already ships with a clean and a build task in case you want to apply that logic to a build with a java plugin in the root project.

**Comment by rgoldberg** [comment]
@breskeby Thanks for the insight.

My root project is just a "shell" composite to include all my other builds.

My composite doesn't have any source, so I didn't apply the `java` plugin to it, so there were no tasks named `build` or `clean` before I created them with `passThroughTaskToIncludedBuilds` (now I use `createDelegatingToAllTask ` to create `buildAll` and `cleanAll`, along with other `*All` delegating tasks).
