### ISSUE TITLE
Java executors fail with 'error=7, Argument list too long' with large classpaths

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#5754]
We semi-frequently see task execution failures due to:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:596)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/usr/lib/jvm/java-8-oracle-1.8.0.152/bin/java''
	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:226)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:204)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:349)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:85)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	... 3 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not start '/usr/lib/jvm/java-8-oracle-1.8.0.152/bin/java'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:67)
	... 4 more
Caused by: java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-oracle-1.8.0.152/bin/java" (in directory "/mnt/builds/slave/workspace/personalization-streaming-impressions-publish"): error=7, Argument list too long
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 6 more
Caused by: java.io.IOException: error=7, Argument list too long
	... 7 more
```

It's at it's worst when dealing with classpaths from Gradle configurations, as the individual jar paths are ~100 characters each.

### Expected Behavior
Gradle executors with classpaths, and JavaExec task execution should tolerate classpaths from Gradle configurations.

### Current Behavior
Long classpaths cause the build to fail.

### Context
Some examples of strategies IntelliJ uses to deal with this:

https://blog.jetbrains.com/idea/2017/10/intellij-idea-2017-3-eap-configurable-command-line-shortener-and-more/

Seems like generating a jar with the classpath in the manifest would be a simple and cheap solution and avoid ever running into this.

### Your Environment
Gradle 4.7

**Comment by simonschiller** [comment]
Any update on this? We recently encountered this issue in conjunction with Kotlin 1.3.50 on a Linux machine. Is there any workaround that works without IDEA?

**Comment by wesleyk** [comment]
+1, we're also seeing this in conjunction with Kotlin + Linux.

Is it possible to extend the same support for Windows onto Linux builds?

**Comment by lacasseio** [comment]
This will be fixed for Gradle 6.1, you can give it a try in the latest nightly.

**Comment by simonschiller** [comment]
Thanks for the fix/update, do we need to enable anything or is upgrading to the nightly enough?

**Comment by lacasseio** [comment]
We went with the assumption that if the command line is bigger than 2097152 bytes, we will create pathing Jar. It will be automatic. If there is any issue please open another issue. I believe, you will have to wait tomorrow for the new nightly.

**Comment by Typraeurion** [comment]
Daniel, 2 MB may be too large for some operating systems.  We’re running some gradle builds on MacOS where the maximum argument list length is only 256 KB.  You should be able to get the actual limit for any (POSIX-compliant) system with `getconf ARG_MAX`.
