### ISSUE TITLE
Could not determine java version from '10.0.1'[MAC OSX High Sierra]

### ISSUE THREAD

**Issue by racterub** [gradle/gradle#5764]
### Current Behavior
While I was compiling [jd-gui](https://github.com/java-decompiler/jd-gui), it returned a error messege:
`Could not determine java version from '10.0.1'`
![Error](https://i.imgur.com/CyBXOU9.png)

Here's the stacktrace:
```
* Exception is:
java.lang.IllegalArgumentException: Could not determine java version from '10.0.1'.
	at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:63)
	at org.gradle.api.JavaVersion.current(JavaVersion.java:72)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:32)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
```

### Steps to Reproduce (for bugs)
`Everything is done in commend-line`
Just follow readme file in jd-gui

./gradlew build

### Your Environment
PATH setting:
```
/opt/gradle/gradle-4.7/bin
```

Java(-version):
```
$ java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```
Java(--version):
```
$ java --version
java 10.0.1 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```

Gradle: (Tried on 4.7 and 4.8.1)(Manully build)
```
------------------------------------------------------------
Gradle 4.7
------------------------------------------------------------

Build time:   2018-04-18 09:09:12 UTC
Revision:     b9a962bf70638332300e7f810689cb2febbd4a6c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          10.0.1 ("Oracle Corporation" 10.0.1+10)
OS:           Mac OS X 10.13.4 x86_64
```

**Comment by melix** [comment]
The screenshot clearly shows you are using the gradle wrapper (which is a good idea), and not the version on PATH. So you are using gradle 2.4. Upgrading your wrapper version should work.

**Comment by melix** [comment]
(Btw using sudo doesn't sound like a great idea, are you sure you need this ?)

**Comment by marcphilipp** [comment]
Please use Gradle >= 4.7 as pointed out by @melix.

**Comment by racterub** [comment]
Hi, @melix I know it's not a good idea, just give it a try though.
@marcphilipp I've tried both as mentioned.
And after I follow [instruction](https://gradle.org/install/) from official docs, still got same error.

It looks like still a open issue to me :p.
![image](https://user-images.githubusercontent.com/20561837/41855095-5fefb718-78c4-11e8-9dcf-fa5b103819fb.png)

**Comment by melix** [comment]
You can't upgrade the wrapper version with a version of Gradle that doesn't support JDK 10.1 itself (bootstrapping problem). Either:

1. edit the `gradle/wrapper/gradle-wrapper.properties` file to select a different distribution
2. use a Gradle >= 4.7 version of Gradle to run the wrapper update task

**Comment by racterub** [comment]
@melix Thanks. It turns out jd-gui use ancient gradle build LOL
`distributionUrl=https\://services.gradle.org/distributions/gradle-2.4-all.zip`

**Comment by luisAzcuaga** [comment]
Hope I'm in not too late, but I fixed it by uninstalling that "10.0.1" version according to the [official documentation](https://docs.oracle.com/javase/8/docs/technotes/guides/install/mac_jdk.html#A1096903) (It's basically deleting some files found @ /Libraries)
and installing the one at [Oracle](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)

**Comment by Vsnegovik** [comment]
@racterub Thanks! It's work! I replaced
`distributionUrl=https\://services.gradle.org/distributions/gradle-2.4-all.zip`
by
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.8.1-bin.zip`

**Comment by leemengtaiwan** [comment]
@luisAzcuaga This really helps!

**Comment by fontenele** [comment]
Point your env ANDROID_HOME to jdk 8 lib dir if you have one

**Comment by blacksourcez** [comment]
In this case, Im currently have java 10 installed with brew cask and I just remove java 10 and downgrade into java8 using command below.

Uninstall java 10 that installed by brew cask.
```bash
brew cask uninstall java
```
Install java8 using brew cask.
```bash
brew tap caskroom/versions
brew cask install java8
```
Done.

**Comment by eassapn** [comment]
install JDK 8 its working  , remove higher version

**Comment by promixmart** [comment]
thanks guys , this really helped

**Comment by blacksourcez** [comment]
I think you can close this issue cause can solved by just install Java 8 sdk.

**Comment by smasseman** [comment]
If you have both java8 and java10 installed and want to keep them both, then you can run gradle like this:
PATH=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/:${PATH} gradle bootRun
