### ISSUE TITLE
Downloading resources via HTTPS fails on OpenJDK 11-ea+20

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#5850]
While Gradle worked with OpenJDK 11-ea+19, it fails with the latest version 11-ea+20.

I first discovered the issue in a JUnit build:
https://travis-ci.org/junit-team/junit5/jobs/399694216

It can easily be reproduced by using the JDK mentioned above and a simple `build.gradle.kts`:

```kotlin
plugins {
    id("com.gradle.build-scan") version "1.15"
}
```

Executing `./gradlew tasks --scan --stacktrace` results in:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/marc/Repositories/gradle/sandbox/download-test/build.gradle.kts' line: 0

* What went wrong:
Plugin [id: 'com.gradle.build-scan', version: '1.15'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.gradle.build-scan:com.gradle.build-scan.gradle.plugin:1.15')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'com.gradle.build-scan', version: '1.15'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.gradle.build-scan:com.gradle.build-scan.gradle.plugin:1.15')
  Searched in the following repositories:
    Gradle Central Plugin Repository
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:262)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.access$100(DefaultPluginRequestApplicator.java:63)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$1.transform(DefaultPluginRequestApplicator.java:91)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$1.transform(DefaultPluginRequestApplicator.java:88)
        at org.gradle.util.CollectionUtils.collect(CollectionUtils.java:204)
        at org.gradle.util.CollectionUtils.collect(CollectionUtils.java:199)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:88)
        at org.gradle.kotlin.dsl.provider.PluginRequestsHandler.handle(PluginRequestsHandler.kt:49)
        at org.gradle.kotlin.dsl.provider.KotlinScriptCompiler.applyPlugins(KotlinScriptCompiler.kt:209)
        at org.gradle.kotlin.dsl.provider.KotlinScriptCompiler.executePluginsBlock(KotlinScriptCompiler.kt:167)
        at org.gradle.kotlin.dsl.provider.KotlinScriptCompiler.access$executePluginsBlock(KotlinScriptCompiler.kt:69)
        at org.gradle.kotlin.dsl.provider.KotlinScriptCompiler$compile$1.invoke(KotlinScriptCompiler.kt:116)
        at org.gradle.kotlin.dsl.provider.KotlinScriptCompiler$compile$1.invoke(KotlinScriptCompiler.kt:69)
        at org.gradle.kotlin.dsl.provider.KotlinScriptPluginFactory$create$1.invoke(KotlinScriptPluginFactory.kt:55)
        at org.gradle.kotlin.dsl.provider.KotlinScriptPluginFactory$create$1.invoke(KotlinScriptPluginFactory.kt:32)
        at org.gradle.kotlin.dsl.provider.KotlinScriptPlugin.apply(KotlinScriptPlugin.kt:36)
        at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:61)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:58)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:41)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:66)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$100(LifecycleProjectEvaluator.java:37)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$ConfigureProject.run(LifecycleProjectEvaluator.java:125)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:52)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:677)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:138)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:60)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:41)
        at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuild.run(DefaultGradleLauncher.java:262)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.initialization.DefaultGradleLauncher.configureBuild(DefaultGradleLauncher.java:175)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:132)
        at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:115)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:77)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:74)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
        at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:38)
        at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:96)
        at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:74)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.run(RunAsBuildOperationBuildActionRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:43)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:50)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:46)
        at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:65)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:46)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:32)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:62)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)


* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**Comment by marcphilipp** [comment]
Seems to be caused by an NPE thrown in `sun.security.ssl.SSLSessionImpl` due to a bug in http://hg.openjdk.java.net/jdk/jdk11/annotate/68fa3d4026ea/src/java.base/share/classes/sun/security/ssl/SSLSessionImpl.java#l661.

**Comment by marcphilipp** [comment]
I created a bug report and will link it here as soon as it has been screened.

**Comment by sbrannen** [comment]
Nice detective work!

And... yeah... I'm guessing that's supposed to be `(localCerts == null || localCerts.length == 0)`. 😝

**Comment by marcphilipp** [comment]
JDK Bug: https://bugs.openjdk.java.net/browse/JDK-8206355

**Comment by Adyel** [comment]
@marcphilipp  I am sorry, but is this related to this bug? or I am having a different problem. 
```log
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.gradle.internal.reflect.JavaMethod (file:/usr/share/gradle/lib/gradle-base-services-3.4.1.jar) to method java.lang.ClassLoader.getPackages()
WARNING: Please consider reporting this to the maintainers of org.gradle.internal.reflect.JavaMethod
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

FAILURE: Build failed with an exception.

* Where:
Build file '/home/adyel/Desktop/Repo/ServerSam/build.gradle' line: 46

* What went wrong:
A problem occurred evaluating root project 'ServerSam'.
> Could not resolve all dependencies for configuration ':compile'.
   > Could not resolve org.jsoup:jsoup:1.11.2.
     Required by:
         project :
      > Could not resolve org.jsoup:jsoup:1.11.2.
         > Could not get resource 'https://repo1.maven.org/maven2/org/jsoup/jsoup/1.11.2/jsoup-1.11.2.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/org/jsoup/jsoup/1.11.2/jsoup-1.11.2.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
      > Could not resolve org.jsoup:jsoup:1.11.2.
         > Could not get resource 'https://jcenter.bintray.com/org/jsoup/jsoup/1.11.2/jsoup-1.11.2.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/jsoup/jsoup/1.11.2/jsoup-1.11.2.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
   > Could not resolve org.xerial:sqlite-jdbc:3.7.2.
     Required by:
         project :
      > Could not resolve org.xerial:sqlite-jdbc:3.7.2.
         > Could not get resource 'https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.7.2/sqlite-jdbc-3.7.2.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.7.2/sqlite-jdbc-3.7.2.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
      > Could not resolve org.xerial:sqlite-jdbc:3.7.2.
         > Could not get resource 'https://jcenter.bintray.com/org/xerial/sqlite-jdbc/3.7.2/sqlite-jdbc-3.7.2.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/xerial/sqlite-jdbc/3.7.2/sqlite-jdbc-3.7.2.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
   > Could not resolve com.google.code.gson:gson:2.8.2.
     Required by:
         project :
      > Could not resolve com.google.code.gson:gson:2.8.2.
         > Could not get resource 'https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.2/gson-2.8.2.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.2/gson-2.8.2.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
      > Could not resolve com.google.code.gson:gson:2.8.2.
         > Could not get resource 'https://jcenter.bintray.com/com/google/code/gson/gson/2.8.2/gson-2.8.2.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/google/code/gson/gson/2.8.2/gson-2.8.2.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
   > Could not resolve org.tinylog:tinylog:1.3.4.
     Required by:
         project :
      > Could not resolve org.tinylog:tinylog:1.3.4.
         > Could not get resource 'https://repo1.maven.org/maven2/org/tinylog/tinylog/1.3.4/tinylog-1.3.4.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/org/tinylog/tinylog/1.3.4/tinylog-1.3.4.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
      > Could not resolve org.tinylog:tinylog:1.3.4.
         > Could not get resource 'https://jcenter.bintray.com/org/tinylog/tinylog/1.3.4/tinylog-1.3.4.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/tinylog/tinylog/1.3.4/tinylog-1.3.4.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.051 secs
  ~/Desktop/Repo/ServerSam     development   gradle sync                                                                                                                                                                                1 ↵  243  08:29:51 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.gradle.internal.reflect.JavaMethod (file:/usr/share/gradle/lib/gradle-base-services-3.4.1.jar) to method java.lang.ClassLoader.getPackages()
WARNING: Please consider reporting this to the maintainers of org.gradle.internal.reflect.JavaMethod
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

FAILURE: Build failed with an exception.

* Where:
Build file '/home/adyel/Desktop/Repo/ServerSam/build.gradle' line: 46

* What went wrong:
A problem occurred evaluating root project 'ServerSam'.
> Could not resolve all dependencies for configuration ':compile'.
   > Could not resolve org.jsoup:jsoup:1.11.2.
     Required by:
         project :
      > Could not resolve org.jsoup:jsoup:1.11.2.
         > Could not get resource 'https://repo1.maven.org/maven2/org/jsoup/jsoup/1.11.2/jsoup-1.11.2.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/org/jsoup/jsoup/1.11.2/jsoup-1.11.2.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
      > Could not resolve org.jsoup:jsoup:1.11.2.
         > Could not get resource 'https://jcenter.bintray.com/org/jsoup/jsoup/1.11.2/jsoup-1.11.2.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/jsoup/jsoup/1.11.2/jsoup-1.11.2.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
   > Could not resolve org.xerial:sqlite-jdbc:3.7.2.
     Required by:
         project :
      > Could not resolve org.xerial:sqlite-jdbc:3.7.2.
         > Could not get resource 'https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.7.2/sqlite-jdbc-3.7.2.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.7.2/sqlite-jdbc-3.7.2.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
      > Could not resolve org.xerial:sqlite-jdbc:3.7.2.
         > Could not get resource 'https://jcenter.bintray.com/org/xerial/sqlite-jdbc/3.7.2/sqlite-jdbc-3.7.2.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/xerial/sqlite-jdbc/3.7.2/sqlite-jdbc-3.7.2.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
   > Could not resolve com.google.code.gson:gson:2.8.2.
     Required by:
         project :
      > Could not resolve com.google.code.gson:gson:2.8.2.
         > Could not get resource 'https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.2/gson-2.8.2.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.2/gson-2.8.2.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
      > Could not resolve com.google.code.gson:gson:2.8.2.
         > Could not get resource 'https://jcenter.bintray.com/com/google/code/gson/gson/2.8.2/gson-2.8.2.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/google/code/gson/gson/2.8.2/gson-2.8.2.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
   > Could not resolve org.tinylog:tinylog:1.3.4.
     Required by:
         project :
      > Could not resolve org.tinylog:tinylog:1.3.4.
         > Could not get resource 'https://repo1.maven.org/maven2/org/tinylog/tinylog/1.3.4/tinylog-1.3.4.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/org/tinylog/tinylog/1.3.4/tinylog-1.3.4.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
      > Could not resolve org.tinylog:tinylog:1.3.4.
         > Could not get resource 'https://jcenter.bintray.com/org/tinylog/tinylog/1.3.4/tinylog-1.3.4.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/tinylog/tinylog/1.3.4/tinylog-1.3.4.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED


```

**Comment by marcphilipp** [comment]
@Adyel Which JDK are you using?

**Comment by Adyel** [comment]
@marcphilipp  I am using `openjdk 10.0.1 2018-04-17`

![image](https://user-images.githubusercontent.com/4653623/42338453-b69ecf60-80ab-11e8-8a84-4f6487d38b9b.png)

**Comment by sormuras** [comment]
No, afair this is related to missing root certs in earlier OpenJDK distros. Either switching to Oracle JDK 10 or upgrade to JDK 11, should help, I guess.

See https://bugs.openjdk.java.net/browse/JDK-8191486 and related issues.

**Comment by Adyel** [comment]
I solved the issue by using the `-Djavax.net.ssl.trustStorePassword=changeit` flag for gradle. In case this helps someone in the future.

![image](https://user-images.githubusercontent.com/4653623/42389731-6e313f86-816b-11e8-8202-268fc7125a4d.png)

**Comment by marcphilipp** [comment]
This issue has been fixed in 11-ea+22.

**Comment by texadactyl** [comment]
@Adyel Also using an up-to-date Ubuntu 18.04.  Your suggestion got me past that issue but now I see:

```
10:01:44.849 [ERROR] [org.gradle.BuildExceptionReporter] 
10:01:44.860 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
10:01:44.867 [ERROR] [org.gradle.BuildExceptionReporter] 
10:01:44.868 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
10:01:44.868 [ERROR] [org.gradle.BuildExceptionReporter] Could not determine java version from '10.0.1'.
10:01:44.869 [ERROR] [org.gradle.BuildExceptionReporter] 
10:01:44.870 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
10:01:44.875 [ERROR] [org.gradle.BuildExceptionReporter] java.lang.IllegalArgumentException: Could not determine java version from '10.0.1'.
10:01:44.876 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:63)
10:01:44.877 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.JavaVersion.current(JavaVersion.java:72)
10:01:44.884 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:32)
10:01:44.885 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
10:01:44.886 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
10:01:44.887 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
10:01:44.888 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
10:01:44.889 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
10:01:44.889 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.Main.doAction(Main.java:33)
10:01:44.890 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
10:01:44.891 [ERROR] [org.gradle.BuildExceptionReporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:01:44.892 [ERROR] [org.gradle.BuildExceptionReporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:01:44.893 [ERROR] [org.gradle.BuildExceptionReporter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:01:44.894 [ERROR] [org.gradle.BuildExceptionReporter] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
10:01:44.895 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
10:01:44.896 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
10:01:44.897 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
10:01:44.898 [ERROR] [org.gradle.BuildExceptionReporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:01:44.899 [ERROR] [org.gradle.BuildExceptionReporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:01:44.900 [ERROR] [org.gradle.BuildExceptionReporter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:01:44.901 [ERROR] [org.gradle.BuildExceptionReporter] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
10:01:44.901 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
10:01:44.903 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
10:01:44.904 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
10:01:44.905 [ERROR] [org.gradle.BuildExceptionReporter] 
```
