### ISSUE TITLE
Gradle wrapper doesn't respect HTTP 301 and 302 redirects to HTTPS

### ISSUE THREAD

**Issue by reegnz** [gradle/gradle#6033]
### Expected Behavior
If distribution URL returns a 301 or 302 status code with a Location header, the wrapper should retry the request with the URL returned in the Location header.
Redirects should be followed recursively (until a reasonable upper bound in the count of redirects is reached).

### Current Behavior
If the configured distribution url returns a 301 or 302 the wrapper fails:
```
Downloading http://my-local-dist-mirror.example.com/gradle-4.8.1-all.zip

Could not unzip C:\Users\reegnz\.gradle\wrapper\dists\gradle-4.8.1-all\2fm1bdco840fg368obqx86w8g\gradle-4.8.1-all.zip to C:\Users\reegnz\.gradle\wrapper\dists\gradle-4.8.1-all\2fm1bdco840fg368obqx86w8g.
Reason: error in opening zip file
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.zip.ZipFile.<init>(ZipFile.java:169)
        at org.gradle.wrapper.Install.unzip(Install.java:218)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:75)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

### Context
We had the distribution available through http in the past.
Recently we changed the server to redirect all requests on port 80 to try again with https.

This broke the gradle wrapper downloads in our CI.

### Steps to Reproduce (for bugs)
1. Have a webserver that redirects from a specific url to the gradle wrapper location
2. Configure gradle wrapper with that url

**Comment by reegnz** [comment]
A possibly simple fix is to:
1. cast the used URLConnection to HttpURLConnection
2. set this flag to true: https://docs.oracle.com/javase/8/docs/api/java/net/HttpURLConnection.html#setFollowRedirects-boolean-

**Comment by reegnz** [comment]
Reading up on this a bit more, the issue is that java designers decided not to follow redirects across protocols, despite that flag being set (it's default is true anyways).
Eg. from http to https a redirect is not followed.
Context:
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4959149
https://bugs.java.com/view_bug.do?bug_id=4620571

**Comment by big-guy** [comment]
@reegnz I doubt we'll change this behavior based on the comments in those issues.

Can you change your wrapper URL to use https?

**Comment by reegnz** [comment]
Yupp, that was our workaround, no big deal.

A remaining issue though is that not following the redirect also breaks caching the wrapper zip -> gradle assumes the wrapper is downloaded already but fails to unzip.
This is because the body returned with the 302 is usually not a ZIP file.
Would it be possible to at least NOT cache the response if it's not an HTTP 200?

**Comment by reegnz** [comment]
Opened a separate bug for gracefully failing in case the response code is not 200 OK.
