### ISSUE TITLE
Failed resolution of: Ljava/beans/Introspector; while using ExtentReport library in Espresso Android test tool

### ISSUE THREAD

**Issue by pankajpat2014** [gradle/gradle#6061]
I am working on Espresso tool for Android app UI test automation using Android Studio.

Android Studio version : 3.1.3
Extent Reports library version : 2.4.0
Java version : 1.8.0.151
JAVA_OPTIONS: -Xmx512M

I am getting below issue everytime while running Espresso test.

Testing started at 15:13 ...

07/22 15:13:19: Launching test3_MV2PRCFAC_11_I...
$ adb push C:\User1\EspressoTest\app\build\outputs\apk\formation\debug\app-formation-debug-V0.4.4.apk /data/local/tmp/net.abc.pqr
$ adb shell pm install -t -r "/data/local/tmp/net.atos.profacteo"
	pkg: /data/local/tmp/net.atos.profacteo
Success

No apk changes detected since last installation, skipping installation of C:\User1\EspressoTest\app\build\outputs\apk\androidTest\formation\debug\app-formation-debug-androidTest.apk
Running tests

$ adb shell am instrument -w -r   -e debug false -e class 'net.abc.pqr.ui.TestScripts.test3' net.abc.pqr.test/android.support.test.runner.AndroidJUnitRunner
Client not ready yet..
Started running tests

java.lang.NoClassDefFoundError: Failed resolution of: Ljava/beans/Introspector;
at freemarker.ext.beans.ClassIntrospector.addBeanInfoToClassIntrospectionData(ClassIntrospector.java:306)
at freemarker.ext.beans.ClassIntrospector.createClassIntrospectionData(ClassIntrospector.java:274)
at freemarker.ext.beans.ClassIntrospector.get(ClassIntrospector.java:244)
at freemarker.ext.beans.ClassBasedModelFactory.getInternal(ClassBasedModelFactory.java:99)
at freemarker.ext.beans.ClassBasedModelFactory.get(ClassBasedModelFactory.java:47)
at freemarker.ext.beans._EnumModels.get(_EnumModels.java:28)
at com.relevantcodes.extentreports.HTMLReporter.start(HTMLReporter.java:80)
at com.relevantcodes.extentreports.Report.attach(Report.java:318)
at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:86)
at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:375)
at net.abc.pqr.ui.TestScripts.test3.test3(test3.java:53)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:527)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at android.support.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:101)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1984)
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.beans.Introspector" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/net.atos.profacteo.test-2/base.apk", zip file "/data/app/net.atos.profacteo-2/base.apk"],nativeLibraryDirectories=[/data/app/net.atos.profacteo.test-2/lib/arm, /data/app/net.atos.profacteo-2/lib/arm, /vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
... 41 more
Suppressed: java.lang.ClassNotFoundException: java.beans.Introspector
at java.lang.Class.classForName(Native Method)
at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
... 42 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

Tests ran to completion.

Testing started at 15:13 ...

07/22 15:13:19: Launching test3_MV2PRCFAC_11_I...
$ adb push C:\User1\EspressoTest\app\build\outputs\apk\formation\debug\app-formation-debug-V0.4.4.apk /data/local/tmp/net.abc.pqr
$ adb shell pm install -t -r "/data/local/tmp/net.abc.pqr"
	pkg: /data/local/tmp/net.abc.pqr
Success

No apk changes detected since last installation, skipping installation of C:\User1\EspressoTest\app\build\outputs\apk\androidTest\formation\debug\app-formation-debug-androidTest.apk
Running tests

$ adb shell am instrument -w -r   -e debug false -e class 'net.abc.pqr.ui.TestScripts.test3' net.abc.pqr.test/android.support.test.runner.AndroidJUnitRunner
Client not ready yet..
Started running tests

java.lang.NoClassDefFoundError: Failed resolution of: Ljava/beans/Introspector;
at freemarker.ext.beans.ClassIntrospector.addBeanInfoToClassIntrospectionData(ClassIntrospector.java:306)
at freemarker.ext.beans.ClassIntrospector.createClassIntrospectionData(ClassIntrospector.java:274)
at freemarker.ext.beans.ClassIntrospector.get(ClassIntrospector.java:244)
at freemarker.ext.beans.ClassBasedModelFactory.getInternal(ClassBasedModelFactory.java:99)
at freemarker.ext.beans.ClassBasedModelFactory.get(ClassBasedModelFactory.java:47)
at freemarker.ext.beans._EnumModels.get(_EnumModels.java:28)
at com.relevantcodes.extentreports.HTMLReporter.start(HTMLReporter.java:80)
at com.relevantcodes.extentreports.Report.attach(Report.java:318)
at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:86)
at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:375)
at net.abc.pqr.ui.TestScripts.test3.test3(test3.java:53)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:527)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at android.support.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:101)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1984)
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.beans.Introspector" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/net.abc.pqr.test-2/base.apk", zip file "/data/app/net.abc.pqr-2/base.apk"],nativeLibraryDirectories=[/data/app/net.abc.pqr.test-2/lib/arm, /data/app/net.abc.pqr-2/lib/arm, /vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
... 41 more
Suppressed: java.lang.ClassNotFoundException: java.beans.Introspector
at java.lang.Class.classForName(Native Method)
at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
... 42 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

Tests ran to completion.

**Comment by oehme** [comment]
Please report Android issues on the Android issue tracker. The introspector is probably not part of the Android SDK.

**Comment by reddyJagan** [comment]
I am working on Espresso tool for Android app UI test automation using Android Studio. I am getting below issue while running Espresso test. It is working in unit test but here getting error

class TestSample {
    var logger: ExtentTest? = null
    var extent: ExtentReports? = null
    var reporter: ExtentHtmlReporter? = null

    @Test
    fun loginTest() {
        extent = ExtentReports()
        extent!!.attachReporter(getHtmlReporter())
        extent!!.setSystemInfo("Host Name", "SoftwareTestingMaterial")
        extent!!.setSystemInfo("Environment", "Automation Testing")
        extent!!.setSystemInfo("User Name", "Test")

        logger = extent!!.createTest("Pass Test", "Login")
        logger!!.pass("Pass")
        extent!!.flush()

        logger = extent!!.createTest("FailTest", "Login")
        logger!!.fail("Fail")
        extent!!.flush()
    }

    fun getHtmlReporter(): ExtentHtmlReporter? {
        reporter =
            ExtentHtmlReporter(System.getProperty("user.dir") + "\\test-output/IndexReport.html")
        reporter!!.config().setDocumentTitle("QA Automation Report")
        reporter!!.config().setReportName("Test")
        reporter!!.config().setTheme(Theme.STANDARD)
        return reporter
    }

}


Output------

Testing started at 11:28 AM ...

06/17 11:28:59: Launching 'TestSample' on Nexus 5 API 29.
Running tests

$ adb shell am instrument -w -r    -e debug false -e class 'com.example.resports.TestSample' com.example.resports.test/androidx.test.runner.AndroidJUnitRunner
Connected to process 6413 on device 'Nexus_5_API_29 [emulator-5554]'.

Started running tests


java.lang.NoClassDefFoundError: Failed resolution of: Ljava/beans/Introspector;
at freemarker.ext.beans.ClassIntrospector.addBeanInfoToClassIntrospectionData(ClassIntrospector.java:320)
at freemarker.ext.beans.ClassIntrospector.createClassIntrospectionData(ClassIntrospector.java:287)
at freemarker.ext.beans.ClassIntrospector.get(ClassIntrospector.java:257)
at freemarker.ext.beans.ClassBasedModelFactory.getInternal(ClassBasedModelFactory.java:102)
at freemarker.ext.beans.ClassBasedModelFactory.get(ClassBasedModelFactory.java:49)
at freemarker.ext.beans._EnumModels.get(_EnumModels.java:31)
at com.aventstack.extentreports.reporter.BasicFileReporter.start(BasicFileReporter.java:103)
at com.aventstack.extentreports.ReportObservable.register(ReportObservable.java:192)
at com.aventstack.extentreports.-$$Lambda$KwTvtlGrkGeJO0VQOZeNSbK9Fg4.accept(Unknown Source:4)
at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:604)
at com.aventstack.extentreports.ExtentReports.attachReporter(ExtentReports.java:82)
at com.example.resports.TestSample.loginTest(TestSample.kt:18)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.beans.Introspector" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/com.example.resports.test-NYGwDx38SRTUbyIVvH8hQA==/base.apk", zip file "/data/app/com.example.resports-ntnaqD5IingZnr8mpe-FgQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.resports.test-NYGwDx38SRTUbyIVvH8hQA==/lib/x86, /data/app/com.example.resports-ntnaqD5IingZnr8mpe-FgQ==/lib/x86, /system/lib, /system/product/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 40 more

Tests ran to completion.
