### ISSUE TITLE
Unsafe multithread property read/write in DefaultExecHandle

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#6109]
### Context

Today we observed a build execution timeout and did some investigation. Here's the stack trace:

```
 "gradle-shutdown-hook" #18 prio=5 os_prio=0 tid=0x0000000055320800 nid=0x1b24 waiting on condition [0x000000005521e000]
 java.lang.Thread.State: WAITING (parking)
 	at sun.misc.Unsafe.park(Native Method)
 	- parking to wait for  <0x00000000feef70a0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
 	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
 	at org.gradle.process.internal.DefaultExecHandle.waitForFinish(DefaultExecHandle.java:300)
 	at org.gradle.process.internal.DefaultExecHandle.abort(DefaultExecHandle.java:289)
 	at org.gradle.process.internal.ExecHandleShutdownHookAction.run(ExecHandleShutdownHookAction.java:39)
 	at org.gradle.process.internal.shutdown.ShutdownHookActionRegister$GradleShutdownHook.run(ShutdownHookActionRegister.java:41)
 	at java.lang.Thread.run(Thread.java:748)
 
 "main" #1 prio=5 os_prio=0 tid=0x0000000000a3f000 nid=0xe34 in Object.wait() [0x0000000000c1e000]
 java.lang.Thread.State: WAITING (on object monitor)
 	at java.lang.Object.wait(Native Method)
 	- waiting on <0x00000000e07b4ee8> (a java.lang.Thread)
 	at java.lang.Thread.join(Thread.java:1252)
 	- locked <0x00000000e07b4ee8> (a java.lang.Thread)
 	at java.lang.Thread.join(Thread.java:1326)
 	at java.lang.ApplicationShutdownHooks.runHooks(ApplicationShutdownHooks.java:106)
 	at java.lang.ApplicationShutdownHooks$1.run(ApplicationShutdownHooks.java:46)
 	at java.lang.Shutdown.runHooks(Shutdown.java:123)
 	at java.lang.Shutdown.sequence(Shutdown.java:167)
 	at java.lang.Shutdown.exit(Shutdown.java:212)
 	- locked <0x00000000e0745ff0> (a java.lang.Class for java.lang.Shutdown)
 	at java.lang.Runtime.exit(Runtime.java:109)
 	at java.lang.System.exit(System.java:971)
 	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:68)
```

It's clear that this [`stateChanged.await()`](https://github.com/gradle/gradle/blob/67feaca3cd23f5f91465bc38c064753dd6111714/subprojects/core/src/main/java/org/gradle/process/internal/DefaultExecHandle.java#L300) hangs forever. It looks like that [`DefaultExecHandle.state`](https://github.com/gradle/gradle/blob/67feaca3cd23f5f91465bc38c064753dd6111714/subprojects/core/src/main/java/org/gradle/process/internal/DefaultExecHandle.java#L104) should be `volatile` but it's currently not. This might cause changed state invisible to another thread, and `waitForFinish` wait forever.

**Comment by wolfs** [comment]
I thought all the access of `state` happens under lock, so `volatile` would not be necessary. Am I missing something?

**Comment by blindpirate** [comment]
Yeah,  @wolfs you're right. I thought `Lock` only guarantee accessibility but not guarantee visibility. It turns out that `Lock` can guarantee visibility of non-volatile variable. Sorry for the noise.
