### ISSUE TITLE
Recursive Project.getAllTasks() and Project.getTasksByName() are disallowed in lazy task configuration blocks

### ISSUE THREAD

**Issue by tomdcc** [gradle/gradle#6124]
After https://github.com/gradle/gradle/pull/6003 was merged, projects that have the following sorts of constructs no longer work:

```
// root build.gradle.kts
tasks.register("foo") {
    dependsOn(getTasksByName("bar", true))
}
```

Root exception stack trace:

```
Caused by: org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator$IllegalCrossProjectConfigurationException: Project#allprojects(Action) on root project 'foo' cannot be executed in the current context.
        at org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator.createIllegalStateException(BuildOperationCrossProjectConfigurator.java:144)
        at org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator.assertCrossProjectConfigurationAllowed(BuildOperationCrossProjectConfigurator.java:124)
        at org.gradle.api.internal.project.DefaultProject.assertMethodExecutionAllowed(DefaultProject.java:1419)
        at org.gradle.api.internal.project.DefaultProject.allprojects(DefaultProject.java:649)
        at org.gradle.api.internal.project.DefaultProject.getTasksByName(DefaultProject.java:821)
        at org.gradle.kotlin.dsl.KotlinBuildScript.getTasksByName(KotlinBuildScript.kt)
        at Foo_gradle$$special$$inlined$invoke$lambda$4.execute(build.gradle.kts:122)
        at Foo_gradle$$special$$inlined$invoke$lambda$4.execute(build.gradle.kts:15)
        at org.gradle.internal.ImmutableActionSet$SetWithFewActions.execute(ImmutableActionSet.java:283)
        at org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator$6.execute(BuildOperationCrossProjectConfigurator.java:135)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:232)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:226)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.add(DefaultNamedDomainObjectCollection.java:113)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.access$2500(DefaultTaskContainer.java:75)
        at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider$1.run(DefaultTaskContainer.java:644)
        ... 66 more
```

I believe that this is an accidental bug rather than a deliberate decision. It's a side-effect of these methods using an `allprojects` call internally. It's fair enough to want to refer to other tasks in the project during one of these blocks, and we should be encouraging users to put more cases that force task resolution into such deferred blocks.

### Expected Behavior
Build passes, with task dependencies updated as designed (and as worked in 4.9).

### Current Behavior
Throws exception shown above

### Steps to Reproduce (for bugs)
Easy enough to trigger:
 - Create a deferred-creation task using `TaskContainer.register()` and attempt to call `Project.getTasksByName('anything', true)` or `Project.getAllTasks(true)` in its configuration block
 - Run any nightly build since https://github.com/gradle/gradle/pull/6003 merged, e.g. `4.10-20180730054456+0000`
 - Do anything to trigger creation of the task - call it directly, run `:tasks` etc. I first noticed it when syncing Gradle state in IDEA.

### Your Environment
Gradle master or nightly `4.10-20180730054456+0000`

**Comment by lacasseio** [comment]
PR pushed for this issue: https://github.com/gradle/gradle/pull/6125
