### ISSUE TITLE
ivy concurrent modification exception

### ISSUE THREAD

**Issue by yigit** [gradle/gradle#6175]
Since we've updated to gradle 4.9, we've started seeing an in-deterministic ConcurrentModificationException in Upload tasks.

Full error:
https://gist.github.com/yigit/4e5439ccfad5cc753e173f46b1fdc50e

### Context
Build fails with this error when we try to run a bunch of uploadArchives tasks.

### Steps to Reproduce (for bugs)
we cannot reproduce this properly, it just happens time to time. We've recently updated to 4.9 .
You can try checking out:
https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/README.md
And running:
./gradlew buildOnServer 

I'm seeing the error in this patch, might be related but i can't see how since anything added in this CL is practically no-op besides adding a `onlyIf` block to certain tasks :
https://android-review.googlesource.com/c/platform/frameworks/support/+/723896

### Your Environment
➜  gw --version
------------------------------------------------------------
Gradle 4.9
------------------------------------------------------------

Build time:   2018-07-16 08:14:03 UTC
Revision:     efcf8c1cf533b03c70f394f270f46a174c738efc

Kotlin DSL:   0.18.4
Kotlin:       1.2.41
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b04)
OS:           Linux 4.9.0-7-amd64 amd64

**Comment by liutikas** [comment]
Here are our gradle properties:
https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/gradle.properties

**Comment by big-guy** [comment]
@oehme seems like we could do something like in 
```
        return SystemProperties.getInstance().withSystemProperties(new Factory<Ivy>() {
            @Override
            public Ivy create() {
                // IvySettings iterates over System.getProperties() when initializing
                return Ivy.newInstance(new IvySettings());
            }
        });
```
in https://github.com/gradle/gradle/blob/19f4c9559e390c66d62a4e2dac5a4a25bd1e5d95/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultIvyContextManager.java#L75

Where `SystemProperties.getInstance().withSystemProperties` synchronizes around `System.getProperties`.

I think that would prevent anyone from changing system properties while creating an `IvySettings`. 

Reproducing it would be pretty hard...

**Comment by oehme** [comment]
Thanks for the hint Sterling, I'm gonna do that.

**Comment by oehme** [comment]
Note that we had to partially revert this, because it could lead to a deadlock. The new solution only coordinates our own access to system properties, but doesn't protect against user code mutating them. So if you need different system properties for a task, it needs to run out of process to be safe.

**Comment by yigit** [comment]
We are seeing this issue again:

```
------------------------------------------------------------
Gradle 4.10.1
------------------------------------------------------------

Build time:   2018-09-12 11:33:27 UTC
Revision:     76c9179ea9bddc32810f9125ad97c3315c544919

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b04)
OS:           Linux 4.17.0-3rodete2-amd64 amd64
```

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':concurrent:concurrent-futures:uploadArchives'.
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:105)
at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:79)
at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.artifacts.PublishException: Could not publish configuration 'archives'
at org.gradle.api.tasks.Upload.upload(Upload.java:67)
at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
... 33 more
Caused by: java.util.ConcurrentModificationException
at org.apache.ivy.core.settings.IvySettings.addAllVariables(IvySettings.java:585)
at org.apache.ivy.core.settings.IvySettings.addAllVariables(IvySettings.java:580)
at org.apache.ivy.core.settings.IvySettings.addSystemProperties(IvySettings.java:300)
at org.apache.ivy.core.settings.IvySettings.<init>(IvySettings.java:295)
at org.apache.ivy.core.settings.IvySettings.<init>(IvySettings.java:217)
at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager$1.create(DefaultIvyContextManager.java:100)
at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager$1.create(DefaultIvyContextManager.java:97)
at org.gradle.internal.SystemProperties.withSystemProperties(SystemProperties.java:148)
at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.createNewIvyInstance(DefaultIvyContextManager.java:97)
at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.getIvy(DefaultIvyContextManager.java:88)
at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:60)
at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:41)
at org.gradle.api.internal.artifacts.ivyservice.IvyContextualArtifactPublisher.publish(IvyContextualArtifactPublisher.java:40)
at org.gradle.api.tasks.Upload.upload(Upload.java:65)
... 47 more

```

**Comment by big-guy** [comment]
@oehme This might be fixed in 5.0 now that we've upgraded the version of Ivy we embed. It looks like there were changes upstream in Ivy to fix this.

**Comment by marcphilipp** [comment]
Indeed, it should be fixed in Ivy 2.3.0 which Gradle 5.0 will use: https://issues.apache.org/jira/browse/IVY-1250

**Comment by liutikas** [comment]
Is it possible to pull in a newer version of Ivy while using Gradle 4.10? It is as simple as pulling it into the classpath?

**Comment by oehme** [comment]
No, that's not possible.
