### ISSUE TITLE
gradle: java.lang.IllegalArgumentException: Could not determine java version from '10.0.2'.

### ISSUE THREAD

**Issue by papaworx** [gradle/gradle#6420]
I am trying to install gradle on Linux Mint 18.2 Cinnamon 64-bit; Kernel 4.15.0-32-generic.
I have Oracle java sdk 1.8-181 installed. Java 9 or 10 are not installed!
### Expected Behavior

after installation completed, I tried to enter 'gradle -v' and got the error message in the title.

as suggested, I did a stacktrace, but that didn't help:
* Exception is:
java.lang.IllegalArgumentException: Could not determine java version from '10.0.2'.
	at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:64)
	at org.gradle.api.JavaVersion.current(JavaVersion.java:73)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:32)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)

### Your Environment

 * Build scan URL:

**Comment by big-guy** [comment]
It looks like you're running JDK10 somehow.  You can check with `java -version` and looking at `echo $JAVA_HOME`

It also looks like the version of Gradle you're trying to run is at least a couple of years old (2.13 or older).  The latest version is 4.9.

You may want to try installing Gradle by downloading the archive from https://gradle.org/install/ or using sdkman.
