### ISSUE TITLE
Javadoc should use -doclet instead of -d

### ISSUE THREAD

**Issue by moaxcp** [gradle/gradle#6580]
I was trying out [@manoelcampos/javadoc-coverage](https://github.com/manoelcampos/javadoc-coverage) in gradle 4.10 and running the task had an error.

```
javadoc: error - invalid flag: -d
```

### Expected Behavior

The doclet should run without error

### Current Behavior

Running the task results in:

```
> Task :javadoc
javadoc: warning - You have not specified the version of HTML to use.
The default is currently HTML 4.01, but this will change to HTML5
in a future release. To suppress this warning, please specify the
version of HTML used in your documentation comments and to be
generated by this doclet, using the -html4 or -html5 options.
1 warning

> Task :javadocCoverageReport FAILED
javadoc: warning - The old Doclet and Taglet APIs in the packages
com.sun.javadoc, com.sun.tools.doclets and their implementations
are planned to be removed in a future JDK release. These
components have been superseded by the new APIs in jdk.javadoc.doclet.
Users are strongly recommended to migrate to the new APIs.
javadoc: error - invalid flag: -d
Usage: javadoc [options] [packagenames] [sourcefiles] [@files]
  -overview <file>                 Read overview documentation from HTML file
  -public                          Show only public classes and members
  -protected                       Show protected/public classes and members (default)
  -package                         Show package/protected/public classes and members
  -private                         Show all classes and members
  -help                            Display command line options and exit
  -doclet <class>                  Generate output via alternate doclet
  -docletpath <path>               Specify where to find doclet class files
  --module-source-path <path>      Specify where to find input source files for multiple modules
  --upgrade-module-path <path>     Override location of upgradeable modules
  --module-path <path>, -p <path>  Specify where to find application modules
  --add-modules <module>(,<module>)*
                                   Root modules to resolve in addition to the initial modules,
                                   or all modules on the module path if <module> is ALL-MODULE-PATH.
  --limit-modules <module>(,<module>)*
                                   Limit the universe of observable modules
  --source-path <path>             Specify where to find source files
  -sourcepath <path>               Specify where to find source files
  --class-path <path>              Specify where to find user class files
  -classpath <path>                Specify where to find user class files
  -cp <path>                       Specify where to find user class files
  -exclude <pkglist>               Specify a list of packages to exclude
  -subpackages <subpkglist>        Specify subpackages to recursively load
  -breakiterator                   Compute first sentence with BreakIterator
  -bootclasspath <path>            Override location of platform class files
                                   used for non-modular releases
  --system <jdk>                   Override location of system modules used
                                   for modular releases.
  -source <release>                Provide source compatibility with specified release
  --release <release>              Provide source compatibility with specified release
  -extdirs <dirlist>               Override location of installed extensions
  -verbose                         Output messages about what Javadoc is doing
  -locale <name>                   Locale to be used, e.g. en_US or en_US_WIN
  -encoding <name>                 Source file encoding name
  -quiet                           Do not display status messages
  -J<flag>                         Pass <flag> directly to the runtime system
  -X                               Print a synopsis of nonstandard options and exit


GNU-style options may use = instead whitespace to separate the name of an option
from its value.

1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':javadocCoverageReport'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/home/john/projects/graphs/build/tmp/javadocCoverageReport/javadoc.options'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 30s
3 actionable tasks: 3 executed
```

### Context

It appears this bug would prevent anyone from running a doclet.

### Steps to Reproduce (for bugs)

[gradle-example.tar.gz](https://github.com/gradle/gradle/files/2338494/gradle-example.tar.gz)

### Your Environment

 * Build scan URL:

**Comment by marcphilipp** [comment]
Gradle does in fact use `-doclet`. The error message originates from the custom doclet not supporting the `-d` (destination dir) parameter when executed on Java 10. The root cause is that the `Standard` doclet it delegates to has been removed from the JDK (see https://bugs.java.com/view_bug.do?bug_id=JDK-8177511).

Thus, when removing all options from the generated `javadoc.options` file except `-doclet` and `-docletpath`, you'll see the following error message:

```
$ javadoc @build/tmp/javadocCoverageReport/javadoc.options
javadoc: warning - The old Doclet and Taglet APIs in the packages
com.sun.javadoc, com.sun.tools.doclets and their implementations
are planned to be removed in a future JDK release. These
components have been superseded by the new APIs in jdk.javadoc.doclet.
Users are strongly recommended to migrate to the new APIs.
javadoc: error - In doclet class com.manoelcampos.javadoc.coverage.CoverageDoclet,  method validOptions has thrown an exception java.lang.reflect.InvocationTargetException
java.lang.NoSuchMethodError: com.sun.tools.doclets.standard.Standard.validOptions([[Ljava/lang/String;Lcom/sun/javadoc/DocErrorReporter;)Z
	at com.manoelcampos.javadoc.coverage.CoverageDoclet.validOptions(CoverageDoclet.java:122)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at jdk.javadoc/com.sun.tools.javadoc.main.DocletInvoker.invoke(DocletInvoker.java:332)
	at jdk.javadoc/com.sun.tools.javadoc.main.DocletInvoker.validOptions(DocletInvoker.java:260)
	at jdk.javadoc/com.sun.tools.javadoc.main.Start.parseAndExecute(Start.java:412)
	at jdk.javadoc/com.sun.tools.javadoc.main.Start.begin(Start.java:237)
	at jdk.javadoc/com.sun.tools.javadoc.main.Start.begin(Start.java:223)
	at jdk.javadoc/com.sun.tools.javadoc.Main.execute(Main.java:173)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:418)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:343)
	at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
	at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
1 error
```

**Comment by deepanjan90** [comment]
@marcphilipp 
Any resolution to tackle the problem.
I tried using `options.addStringOption("d", null)` to remove the pram
Which results in it complaining about not able to write to the `javadoc.options` file

**Comment by marcphilipp** [comment]
It's not just the `-d` option. You need to change the base class of your doclet to make it work on Java 10.

**Comment by deepanjan90** [comment]
Currently we had to extend the standard model to make it work.

**Comment by deepanjan90** [comment]
We managed to to patch up a version using jdk 10 that is working for us for now, but is inva very rudimentary stage.
