### ISSUE TITLE
Gradle tooling does not work on modular java 9

### ISSUE THREAD

**Issue by alexander-shustanov** [gradle/gradle#6726]
### Context
Simple snippet, that runs `help` task.
```java
public class Test {
    public static void main(String[] args) {
        GradleConnector.newConnector()
                .forProjectDirectory(new File("."))
                .connect()
                .newBuild()
                .setStandardError(System.err)
                .setStandardOutput(System.out)
                .setStandardInput(System.in)
                .forTasks("help")
                .run();
    }
}

### Current Behavior
After adding module-info.java and launching the app with module-path, it fails with:

```java
 [Connection worker] INFO org.gradle.internal.nativeintegration.services.NativeServices - Initialized native services in: /home/shustanov/.gradle/native
Exception in thread "main" org.gradle.tooling.GradleConnectionException: Could not create an instance of Tooling API implementation using the specified Gradle distribution 'https://services.gradle.org/distributions/gradle-4.8-bin.zip'.
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.loader.DefaultToolingImplementationLoader.create(DefaultToolingImplementationLoader.java:106)
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:44)
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(SynchronizedToolingImplementationLoader.java:43)
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(LazyConsumerActionExecutor.java:101)
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:83)
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
	at gradle.tooling.api@4.3.1/org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at gradle.tooling.api@4.3.1/org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at gradle.tooling.api@4.3.1/org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:844)
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.DefaultBuildLauncher.run(DefaultBuildLauncher.java:77)
	at gradle.tooling.test.main/com.haulmont.toolingtest.Test.main(Test.java:17)
Caused by: org.gradle.internal.service.ServiceLookupException: Could not configure services using ConnectionScopeServices.configure().
	at gradle.tooling.api@4.3.1/org.gradle.internal.service.DefaultServiceRegistry.applyConfigureMethod(DefaultServiceRegistry.java:205)
	at gradle.tooling.api@4.3.1/org.gradle.internal.service.DefaultServiceRegistry.findProviderMethods(DefaultServiceRegistry.java:180)
	at gradle.tooling.api@4.3.1/org.gradle.internal.service.DefaultServiceRegistry.addProvider(DefaultServiceRegistry.java:255)
	at org.gradle.internal.service.ServiceRegistryBuilder.build(ServiceRegistryBuilder.java:52)
	at org.gradle.tooling.internal.provider.DefaultConnection.initializeServices(DefaultConnection.java:123)
	at org.gradle.tooling.internal.provider.DefaultConnection.configure(DefaultConnection.java:106)
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.connection.AbstractPost12ConsumerConnection.configure(AbstractPost12ConsumerConnection.java:37)
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.loader.DefaultToolingImplementationLoader.createConnection(DefaultToolingImplementationLoader.java:111)
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.loader.DefaultToolingImplementationLoader.create(DefaultToolingImplementationLoader.java:89)
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:44)
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(SynchronizedToolingImplementationLoader.java:43)
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(LazyConsumerActionExecutor.java:101)
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:83)
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
	at gradle.tooling.api@4.3.1/org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
	at gradle.tooling.api@4.3.1/org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at gradle.tooling.api@4.3.1/org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at gradle.tooling.api@4.3.1/org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.gradle.internal.service.ServiceCreationException: Could not create service of type ClassLoaderRegistry using GlobalScopeServices.createClassLoaderRegistry().
	at gradle.tooling.api@4.3.1/org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:797)
	at gradle.tooling.api@4.3.1/org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:748)
	at gradle.tooling.api@4.3.1/org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectProvider.getInstance(DefaultServiceRegistry.java:574)
	at gradle.tooling.api@4.3.1/org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:623)
	at gradle.tooling.api@4.3.1/org.gradle.internal.service.DefaultServiceRegistry.applyConfigureMethod(DefaultServiceRegistry.java:199)
	at gradle.tooling.api@4.3.1/org.gradle.internal.service.DefaultServiceRegistry.findProviderMethods(DefaultServiceRegistry.java:180)
	at gradle.tooling.api@4.3.1/org.gradle.internal.service.DefaultServiceRegistry.addProvider(DefaultServiceRegistry.java:255)
	at gradle.tooling.api@4.3.1/org.gradle.internal.service.DefaultServiceRegistry$1.addProvider(DefaultServiceRegistry.java:236)
	at org.gradle.tooling.internal.provider.ConnectionScopeServices.configure(ConnectionScopeServices.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at gradle.tooling.api@4.3.1/org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at gradle.tooling.api@4.3.1/org.gradle.internal.service.ReflectionBasedServiceMethod.invoke(ReflectionBasedServiceMethod.java:35)
	at gradle.tooling.api@4.3.1/org.gradle.internal.service.DefaultServiceRegistry.applyConfigureMethod(DefaultServiceRegistry.java:203)
	... 22 more
Caused by: org.gradle.api.internal.classpath.UnknownModuleException: Cannot locate manifest for module 'gradle-core' in classpath: [/home/shustanov/workspace/gradle-tooling-test].
	at gradle.tooling.api@4.3.1/org.gradle.api.internal.classpath.DefaultModuleRegistry.loadModule(DefaultModuleRegistry.java:111)
	at gradle.tooling.api@4.3.1/org.gradle.api.internal.classpath.DefaultModuleRegistry.getModule(DefaultModuleRegistry.java:86)
	at org.gradle.api.internal.DynamicModulesClassPathProvider.allRequiredModulesOf(DynamicModulesClassPathProvider.java:61)
	at org.gradle.api.internal.DynamicModulesClassPathProvider.findClassPath(DynamicModulesClassPathProvider.java:38)
	at org.gradle.api.internal.DefaultClassPathRegistry.getClassPath(DefaultClassPathRegistry.java:34)
	at org.gradle.initialization.DefaultClassLoaderRegistry.<init>(DefaultClassLoaderRegistry.java:30)
	at org.gradle.internal.service.scopes.GlobalScopeServices.createClassLoaderRegistry(GlobalScopeServices.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at gradle.tooling.api@4.3.1/org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at gradle.tooling.api@4.3.1/org.gradle.internal.service.ReflectionBasedServiceMethod.invoke(ReflectionBasedServiceMethod.java:35)
	at gradle.tooling.api@4.3.1/org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:795)
	... 37 more
```

**Comment by marcphilipp** [comment]
Why do you need to run it using the module path?

**Comment by alexander-shustanov** [comment]
We are developing [CUBA CLI](https://github.com/cuba-platform/cuba-cli) and are going to add integration with Gradle. The CLI distributed with embedded jlink image. So it runs in modular way.

**Comment by alexander-shustanov** [comment]
Hi! Is there any updates?

**Comment by marcphilipp** [comment]
@alexander-shustanov I'm afraid not.

**Comment by jjohannes** [comment]
I looked into this a bit more because this came up again [here](https://github.com/jjohannes/gradle-tooling-api-as-module/pull/1).

The Tooling API **does** load things from the target distribution to adapt types that are shared between the Tooling API side, and the target Gradle side. 

Unfortunately, this is very tightly bound together and there is probably more shared than needs to be.

Bottom line is that currently the **Tooling API cannot run as Java module** similar to as Gradle itself cannot run as Java module.

It currently works like this:
- The Tooling API created a _tooling implementation classloader_, which gets the Gradle distribution as classpath. This loader [is then used](https://github.com/gradle/gradle/blob/af62817ea81d2d9c46e3e888686f231d38d49b1a/subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/loader/DefaultToolingImplementationLoader.java#L77) to setup the connection to the target Gradle.
- With the traditional classpath, all classes are now discovered by this classloader.
- But there is a lot of duplication. Classes exist both in that classloader and in the `tooling-api.jar`
- Now when we switch to the module world, the classes from the module are always preferred, so [starting here with instantiating a new ProtocolToModelAdapter](https://github.com/gradle/gradle/blob/af62817ea81d2d9c46e3e888686f231d38d49b1a/subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/loader/DefaultToolingImplementationLoader.java#L85) we now get the ProtocolToModelAdapter from the `tooling-api.jar` module rather than then one the implementation class loader should give us.

This can certainly be improved, which would also make the whole setup easier to understand. But it's not a simple change.

**Comment by swpalmer** [comment]
Is there any relatively easy workaround to using the Gradle Tooling API in a modular Java project?
