### ISSUE TITLE
compileTestScala fails with UncheckedIOException: java.io.FileNotFoundException

### ISSUE THREAD

**Issue by pgcortina** [gradle/gradle#6748]
Our builds are failing to compile scala after the upgrade to **4.10.1**.
We do not see this issue in 4.10
```
[09:18:24]org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':projectA:scala:compileTestScala'.
[09:18:24]	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
[09:18:24]
[09:18:24]	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
[09:18:24]	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
[09:18:24]	at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:105)
[09:18:24]	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
[09:18:24]	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
[09:18:24]	at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:79)
[09:18:24]	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
[09:18:24]	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
[09:18:24]	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
[09:18:24]	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
[09:18:24]	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
[09:18:24]	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
[09:18:24]	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
[09:18:24]	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
[09:18:24]	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
[09:18:24]	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
[09:18:24]	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
[09:18:24]	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
[09:18:24]	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
[09:18:24]	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
[09:18:24]	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
[09:18:24]	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
[09:18:24]	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
[09:18:24]	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
[09:18:24]	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
[09:18:24]	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
[09:18:24]	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
[09:18:24]	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
[09:18:24]	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
[09:18:24]	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
[09:18:24]	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
[09:18:24]	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
[09:18:24]	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[09:18:24]	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[09:18:24]	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
[09:18:24]	at java.lang.Thread.run(Thread.java:748)
[09:18:24]Caused by: org.gradle.api.UncheckedIOException: java.io.FileNotFoundException: ....build/classes/java/main (Is a directory)
[09:18:24]	at org.gradle.language.scala.tasks.AbstractScalaCompile.resolveAnalysisMappingsForOtherProjects(AbstractScalaCompile.java:167)
[09:18:24]	at org.gradle.language.scala.tasks.AbstractScalaCompile.configureIncrementalCompilation(AbstractScalaCompile.java:137)
[09:18:24]	at org.gradle.language.scala.tasks.AbstractScalaCompile.compile(AbstractScalaCompile.java:101)
[09:18:24]	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:18:24]	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:18:24]	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:18:24]	at java.lang.reflect.Method.invoke(Method.java:498)
[09:18:24]	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
[09:18:24]	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
[09:18:24]	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
[09:18:24]	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
[09:18:24]	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
[09:18:24]	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
[09:18:24]	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
[09:18:24]	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
[09:18:24]	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
[09:18:24]	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
[09:18:24]	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
[09:18:24]	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
[09:18:24]	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
[09:18:24]	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
[09:18:24]	... 36 more
[09:18:24]Caused by: java.io.FileNotFoundException: /.../build/classes/java/main (Is a directory)
[09:18:24]	at java.io.FileInputStream.open0(Native Method)
[09:18:24]	at java.io.FileInputStream.open(FileInputStream.java:195)
[09:18:24]	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[09:18:24]	at com.google.common.io.Files$FileByteSource.openStream(Files.java:126)
[09:18:24]	at com.google.common.io.Files$FileByteSource.openStream(Files.java:116)
[09:18:24]	at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:435)
[09:18:24]	at com.google.common.io.CharSource.getInput(CharSource.java:94)
[09:18:24]	at com.google.common.io.CharSource.getInput(CharSource.java:65)
[09:18:24]	at com.google.common.io.CharStreams.readLines(CharStreams.java:344)
[09:18:24]	at com.google.common.io.Files.readLines(Files.java:741)
[09:18:24]	at com.google.common.io.Files.readLines(Files.java:712)
[09:18:24]	at org.gradle.language.scala.tasks.AbstractScalaCompile.resolveAnalysisMappingsForOtherProjects(AbstractScalaCompile.java:163)```

**Comment by big-guy** [comment]
@pgcortina thanks! We're looking into issues with Scala and 4.10.1.

As a workaround, can you try:

```
compileTestScala {
   analysisFiles.setFrom(files())
}
```

**Comment by pgcortina** [comment]
@big-guy thanks! that seems to work.

**Comment by big-guy** [comment]
@pgcortina could you share how you're declaring the dependency between your projects?  Do you have something like:

```
dependencies {
   compile project(":someOtherProject")
}
```

**Comment by big-guy** [comment]
I suspect this is the same or some variant of https://github.com/gradle/gradle/issues/6735, I'm going to close this as a dupe.
