### ISSUE TITLE
gradle cannot decompress tar.bz2 compressed with pbzip2

### ISSUE THREAD

**Issue by andreya108** [gradle/gradle#6760]
When tar.bz2 is compressed with aim of 
tar -I pbzip2 -cf a.tar.bz2 *
gradle (tested on 4.10.1) cannot decompress the archive.

Here is stacktrace and error:
```
[14:39:57]
[Step 3/4]   The tar might be corrupted or it is compressed in an unexpected way.
[14:39:57]
[Step 3/4]   By default the tar tree tries to guess the compression based on the file extension.
[14:39:57]
[Step 3/4]   If you need to specify the compression explicitly please refer to the DSL reference.
[14:39:57]
[Step 3/4] 	at org.gradle.api.internal.file.archive.TarFileTree.visit(TarFileTree.java:98)
[14:39:57]
[Step 3/4] 	at org.gradle.api.internal.file.collections.FileTreeAdapter.visit(FileTreeAdapter.java:117)
[14:39:57]
[Step 3/4] 	at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTreeImpl.visit(AbstractFileTree.java:189)
[14:39:57]
[Step 3/4] 	at org.gradle.api.internal.file.CompositeFileTree.visit(CompositeFileTree.java:93)
[14:39:57]
[Step 3/4] 	at org.gradle.api.internal.file.copy.CopySpecActionImpl.execute(CopySpecActionImpl.java:39)
[14:39:57]
[Step 3/4] 	at org.gradle.api.internal.file.copy.CopySpecActionImpl.execute(CopySpecActionImpl.java:24)
[14:39:57]
[Step 3/4] 	at org.gradle.api.internal.file.copy.DefaultCopySpec$DefaultCopySpecResolver.walk(DefaultCopySpec.java:707)
[14:39:57]
[Step 3/4] 	at org.gradle.api.internal.file.copy.DefaultCopySpec$DefaultCopySpecResolver.walk(DefaultCopySpec.java:709)
[14:39:57]
[Step 3/4] 	at org.gradle.api.internal.file.copy.DefaultCopySpec.walk(DefaultCopySpec.java:513)
[14:39:57]
[Step 3/4] 	at org.gradle.api.internal.file.copy.DelegatingCopySpecInternal.walk(DelegatingCopySpecInternal.java:282)
[14:39:57]
[Step 3/4] 	at org.gradle.api.internal.file.copy.CopySpecBackedCopyActionProcessingStream.process(CopySpecBackedCopyActionProcessingStream.java:38)
[14:39:57]
[Step 3/4] 	at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator$1.process(DuplicateHandlingCopyActionDecorator.java:44)
[14:39:57]
[Step 3/4] 	at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator$1.process(NormalizingCopyActionDecorator.java:57)
[14:39:57]
[Step 3/4] 	at org.gradle.api.internal.file.copy.FileCopyAction.execute(FileCopyAction.java:35)
[14:39:57]
[Step 3/4] 	at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator.execute(NormalizingCopyActionDecorator.java:53)
[14:39:57]
[Step 3/4] 	at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator.execute(DuplicateHandlingCopyActionDecorator.java:42)
[14:39:57]
[Step 3/4] 	at org.gradle.api.internal.file.copy.CopyActionExecuter.execute(CopyActionExecuter.java:40)
[14:39:57]
[Step 3/4] 	at org.gradle.api.tasks.AbstractCopyTask.copy(AbstractCopyTask.java:179)
[14:39:57]
[Step 3/4] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
```

When compressing with 
tar -cjf a.tar.bz2 *
all is OK.

### Expected Behavior
gradle can decompress tar.bz2 compressed with pbzip2

### Current Behavior
The tar might be corrupted or it is compressed in an unexpected way.

### Context
Decompressing artifacts from dependencies with task:
```
task extractIvyContrib(type: Copy) {
    from { 
        configurations.contribIvy.collect {
            logger.lifecycle("Extracting contrib: ${it.name}")
            if (it.canonicalPath.endsWith('.zip')) {
                zipTree(it)
            } else if (it.canonicalPath.endsWith('.tar.bz2')) {
                tarTree(resources.bzip2(it))
            }
        }
    }
    into contribDir
}
```

### Steps to Reproduce (for bugs)
See above.

### Your Environment
Ubuntu Linux 16.04
OpenJDK 8

**Comment by marcphilipp** [comment]
We're using `CBZip2InputStream` from Ant to read the file. Could you check if it supports reading such files in its latest version?
