### ISSUE TITLE
'java.lang.IllegalArgumentException: value already present: 2' during dependency resolution

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#6823]
```
Caused by: java.lang.RuntimeException: Problems reading data from Binary store in /tmp/gradle1043549405105001590.bin (exist: true)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:130)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory$1.create(StreamingResolutionResultBuilder.java:171)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory$1.create(StreamingResolutionResultBuilder.java:168)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory$SimpleStore.load(CachedStoreFactory.java:99)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:168)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:145)
	at org.gradle.api.internal.artifacts.result.DefaultResolutionResult.getRoot(DefaultResolutionResult.java:43)
	at org.gradle.api.internal.artifacts.result.DefaultResolutionResult.getAllComponents(DefaultResolutionResult.java:81)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolutionResult.getAllComponents(ErrorHandlingConfigurationResolver.java:223)
	... 325 more
Caused by: java.lang.IllegalArgumentException: value already present: 2
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:238)
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:215)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.ComponentSelectionReasonSerializer.readDescriptionText(ComponentSelectionReasonSerializer.java:67)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.ComponentSelectionReasonSerializer.readDescriptions(ComponentSelectionReasonSerializer.java:49)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.ComponentSelectionReasonSerializer.read(ComponentSelectionReasonSerializer.java:40)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.ComponentResultSerializer.read(ComponentResultSerializer.java:49)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.deserialize(StreamingResolutionResultBuilder.java:208)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.access$400(StreamingResolutionResultBuilder.java:145)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory$1$1.read(StreamingResolutionResultBuilder.java:173)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory$1$1.read(StreamingResolutionResultBuilder.java:171)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:128)
	... 333 more
```

### Steps to Reproduce (for bugs)

- Unknown at this stage. Hope that the behavior points to an obvious bug (build `SITC-persons-build-master/501` if we need to revisit it internally)

### Your Environment
Gradle 4.10

**Comment by marcphilipp** [comment]
@gradle/dependency-management Any ideas?

**Comment by melix** [comment]
Thanks @DanielThomas . Is this recurring? We saw that once in the past, and failed to reproduce. I think there may be a race condition here.

**Comment by DanielThomas** [comment]
Yeah, saw it twice on the same build. Let me know if there's something specific that'd help you guys find the cause.

**Comment by emmanuelguerin** [comment]
Hello, we have a similar issue using gradle 4.7-rc1 up to 4.10.2. Rollbacking to 4.6 solves the issue.
Difficult to extract steps to reproduce from our source code, but this happens in a very systematic way.
Here is a build scan of the issue:
https://scans.gradle.com/s/5y2vqeoxllax2/
It doesn't seem to be related to parallelization. Happens with or without it.

In our case, it happens while executing a shadowJar task and resolving its dependencies.
Just running a `gradle dependencies` on the same configuration produces no error.

**Comment by emmanuelguerin** [comment]
I can also add that we reproduce on both Mac and Linux.
Removing a single dependency also stops the bug from occurring:
https://scans.gradle.com/s/z6p4fdo2sjzeq/
The 2 graphs:
  - working: https://scans.gradle.com/s/z6p4fdo2sjzeq/dependencies?toggled=W1sxXSxbMF0sWzEsOF1d
 - fail: https://scans.gradle.com/s/5y2vqeoxllax2/dependencies?toggled=W1sxXSxbMSw0XV0
Hope this helps a bit.

**Comment by melix** [comment]
Thanks, this is useful information. Is your project public, that I can try to reproduce?

**Comment by emmanuelguerin** [comment]
No, this is closed source.

**Comment by melix** [comment]
@emmanuelguerin Your error is actually different:

> Unexpected parent dependency id 447

Which should be fixed in later versions of Gradle (4.10), you're using 4.8.1.

**Comment by emmanuelguerin** [comment]
> Which should be fixed in later versions of Gradle (4.10), you're using 4.8.1.
@melix yes, we tried it with 4.10.2. I'm going to post build scans with that version in this case.
Do you prefer that I open a different issue?

**Comment by melix** [comment]
Yes, please.

**Comment by ljacomet** [comment]
This should have been fixed by recent changed.
