### ISSUE TITLE
Adding a project field to task ends in NPE

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#6880]
```groovy
    def "can declare project field in custom task"() {
        buildFile << """
            class CustomTask extends DefaultTask {
                Project project
                
                @TaskAction
                void execute() {
                    println "Hello"
                }
            }
            
            task test(type: CustomTask)
        """
        expect:
        succeeds "test"
    }
```

This fails with:

```text
Caused by: java.lang.NullPointerException
	at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:38)
	at org.gradle.api.internal.project.taskfactory.PropertyAssociationTaskFactory.create(PropertyAssociationTaskFactory.java:49)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory.create(AnnotationProcessingTaskFactory.java:44)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.createTask(DefaultTaskContainer.java:320)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.access$200(DefaultTaskContainer.java:77)
	at org.gradle.api.internal.tasks.DefaultTaskContainer$1.call(DefaultTaskContainer.java:146)
	... 158 more
```

**Comment by amatkivskiy** [comment]
@lptr  Facing the same issue 😞

**Comment by lptr** [comment]
@amatkivskiy what Gradle version are you using?

**Comment by amatkivskiy** [comment]
`4.10.1` but this issue disappeared when I moved to version `5.4.1`.

**Comment by lptr** [comment]
This problem was caused by a bug in the Groovy compiler (see https://issues.apache.org/jira/browse/GROOVY-8732). Gradle has upgraded to Groovy 2.5 in Gradle 5.0. Since then this problem does not occur.
