### ISSUE TITLE
gradle build failed with " failed to read class file" exception when working with JDK 11

### ISSUE THREAD

**Issue by jianyuanzh** [gradle/gradle#7059]
### Expected Behavior

./gradlew build should run the junit cases.
### Current Behavior

But exactly the test task failed. Here is the output
```
Execution failed for task ':test'.
> failed to read class file /Users/vincent/Lmwork/lmcodes/sitemonitor/build/classes/java/test/com/***
```
And here is the exception when running with --stacktrace:
```
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more
Caused by: java.lang.UnsupportedOperationException
        at org.objectweb.asm.ClassVisitor.visitNestMemberExperimental(ClassVisitor.java:248)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:651)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
        at org.gradle.api.internal.tasks.testing.detection.AbstractTestFrameworkDetector.classVisitor(AbstractTestFrameworkDetector.java:124)
        ... 67 more
```
Here is the gradle version:
```
------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          11 (Oracle Corporation 11+28)
OS:           Mac OS X 10.12.6 x86_64

```
And Notice, If I change the sourceCompatibility to JDK10, gradle build can pass. But when it is set to JavaVersion.VERSION_11, it fails.

### Context

This confused us when we are trying to upgrading JDK to 11.

### Steps to Reproduce (for bugs)

Add a test case in your gradle project with following code:
```
import org.junit.Assert;
import org.junit.Test;

public class TestHello {
    @Test
    public void testHello() {
        Runnable r = new Runnable() {
            @Override
            public void run() {

            }
        };
    }
}

```
And Make sure the sourceCompatibility is set JavaVersion.VERSION_11 in the build.gradle file:
```
sourceCompatibility = JavaVersion.VERSION_11
```

### Your Environment

```
------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          11 (Oracle Corporation 11+28)
OS:           Mac OS X 10.12.6 x86_64
```
 * Build scan URL:

**Comment by JornVernee** [comment]
Nest based access requires ASM API level 7:
```
@Deprecated
public void visitNestMemberExperimental(final String nestMember) {
    if (api < Opcodes.ASM7_EXPERIMENTAL) {
        throw new UnsupportedOperationException();
    }
```
and ClassWriter uses 6 by default in the current version used by gradle: 
```
public ClassWriter(final ClassReader classReader, final int flags) {
    super(Opcodes.ASM6);
```
This could be fixed by updating gradle to the 7.0-BETA version of ASM.

**Comment by marcphilipp** [comment]
Thanks for the bug report! This is already fixed in 5.0-milestone-1.

**Comment by asarkar** [comment]
+1 to what @daschneider said.

**Comment by lukasbradley** [comment]
+1 to @daschneider

**Comment by JoshMcCullough** [comment]
FWIW I had the same issue and it was due to forgetting to update the Gradle version in `./gradle/wrapper/gradle-wrapper.properties` when I updated it in `build.gradle`.
