### ISSUE TITLE
InaccessibleObjectException with jdk9 jigsaw b136

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#723]
From https://discuss.gradle.org/t/jigsaw-b136-gradle-problem/19580

> This is with gradle 3.0 and jdk9 jigsaw b136:

<details><summary>Stacktrace</summary>
[12:00:28][Gradle failure report] Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.Package[] java.lang.ClassLoader.getPackages() accessible: module java.base does not "exports private java.lang" to unnamed module @6ca18a14
[12:00:28][Gradle failure report]   at java.base/jdk.internal.reflect.Reflection.throwInaccessibleObjectException(Reflection.java:414)
[12:00:28][Gradle failure report]   at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:196)
[12:00:28][Gradle failure report]   at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:192)
[12:00:28][Gradle failure report]   at java.base/java.lang.reflect.Method.setAccessible(Method.java:186)
[12:00:28][Gradle failure report]   at org.gradle.internal.reflect.JavaMethod.<init>(JavaMethod.java:34)
[12:00:28][Gradle failure report]   at org.gradle.internal.reflect.JavaMethod.<init>(JavaMethod.java:38)
[12:00:28][Gradle failure report]   at org.gradle.internal.reflect.JavaReflectionUtil.method(JavaReflectionUtil.java:224)
[12:00:28][Gradle failure report]   at org.gradle.internal.classloader.FilteringClassLoader.<clinit>(FilteringClassLoader.java:49)[12:00:28][Gradle failure report]     ... 46 more
</details>

https://mail-archives.apache.org/mod_mbox/groovy-dev/201609.mbox/%3CCADQzvmn_NqB843%3DTVJFvZww7KDcEgxG2Xsr5dDHWkLtq_ZMXEg%40mail.gmail.com%3E

**Comment by adammurdoch** [comment]
On Java 9 we can now use the public `ClassLoader.getDefinedPackages()` instead of using reflection to get at the protected `ClassLoader.getPackages()`.

There's a quick hacky fix for this in this branch: https://github.com/gradle/gradle/tree/am-jigsaw-hacks

**Comment by McPringle** [comment]
A few weeks later there is still the same problem with OpenJDK 9 build 150 and Gradle 3.3-rc-1. Even more worse: I can't find any information about the actual status of Gradle and JRE 9 or a timeline. Gradle really needs to run on JRE 9 soon – we can be happy that Oracle had to postpone the release of JDK 9 once more…

**Comment by oehme** [comment]
This was fixed in 4.10.
