### ISSUE TITLE
SLF4J ClassCastException when testing with Java Jigsaw 9+

### ISSUE THREAD

**Issue by albsch** [gradle/gradle#7478]
Related to Issue #2657, using the latest SLF4j with any logging implementation makes the latest stable Gradle hang.

### Expected Behavior
`gradle test` should finish without an exception and logging one line to the console via logback/slf4j logger. If this exception is not related to Gradle and the problem lies within SLF4j, Gradle at least should not hang.

### Current Behavior
`gradle test` fails with following exception (No-op logger and logback logger):

```java
> Task :gl-core:test FAILED
java.lang.ClassCastException: class ch.qos.logback.classic.LoggerContext cannot be cast to class org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext (ch.qos.logback.classic.LoggerContext is in module ch.qos.logback.classic of loader 'app'; org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext is in unnamed module of loader java.net.URLClassLoader @42dafa95)
        at org.gradle.internal.logging.slf4j.Slf4jLoggingConfigurer.configure(Slf4jLoggingConfigurer.java:42)
        at org.gradle.internal.logging.config.LoggingSystemAdapter.startCapture(LoggingSystemAdapter.java:54)
        at org.gradle.internal.logging.services.DefaultLoggingManager$StartableLoggingSystem.start(DefaultLoggingManager.java:331)
        at org.gradle.internal.logging.services.DefaultLoggingManager.start(DefaultLoggingManager.java:80)
        at org.gradle.internal.logging.services.DefaultLoggingManager.start(DefaultLoggingManager.java:39)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:83)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:64)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:62)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:67)
```

### Context

I'm trying to get unit tests to work. Running test manually in Intellij Idea works fine.

### Steps to Reproduce

A sample project where `gradle test` fails can be found here: https://github.com/albsch/gradle-jigsaw-logging-bug

### Your Environment
JDK 11 (11.ea.28-open), gradle 4.10.2, Ubuntu 18.04
 * Build scan URL: `gradle build --scan` hangs and does not finish

**Comment by albsch** [comment]
It works with the latest nightly build of Gradle. Didn't get that this is fixed from the referenced thread. Thanks.
