### ISSUE TITLE
IMPROVED_POM_SUPPORT behaves different than 5.0-rc-1

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#7691]
I have a project where i needed the latest version of https://github.com/rodm/gradle-teamcity-plugin.git, so I decided to test the new source dependencies of Gradle to let it build the latest version.

I usually have in my projects `enableFeaturePreview 'IMPROVED_POM_SUPPORT'` switched on.
But this made the source-dependency build fail as I found out with a lot of trying.
If I heave the version of the project to Gradle 4.6 and enable the feature preview, it fails with the same error I see.
If I remove the feature preview and heave the version to 5.0-rc-1, it does not fail (there are two failing tests then, but before it failed at compiling already.

I guess this could make problems for people that enabled the feature preview to be prepared for 5.0 like me and expect the switch to be smooth as long as no deprecation warnings are shown, so i thought I report the difference in behavior. Feel free to close this ticket if you think you don't care. :-)

The error I see is
```
> Task :compileGroovy
startup failed:
General error during class generation: java.lang.NoClassDefFoundError: Unable to load class com.jetbrains.plugin.structure.teamcity.TeamcityPluginManager due to missing dependency org/jdom2/input/JDOMParseException

java.lang.RuntimeException: java.lang.NoClassDefFoundError: Unable to load class com.jetbrains.plugin.structure.teamcity.TeamcityPluginManager due to missing dependency org/jdom2/input/JDOMParseException
        at org.codehaus.groovy.control.CompilationUnit.convertUncaughtExceptionToCompilationError(CompilationUnit.java:1101)
        at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1079)
        at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:537)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:175)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:56)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:74)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:62)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerRunnable.run(AbstractDaemonCompiler.java:87)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:36)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:46)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:30)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:100)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Unable to load class com.jetbrains.plugin.structure.teamcity.TeamcityPluginManager due to missing dependency org/jdom2/input/JDOMParseException
        at org.codehaus.groovy.vmplugin.v5.Java5.configureClassNode(Java5.java:397)
        at org.codehaus.groovy.ast.ClassNode.lazyClassInit(ClassNode.java:280)
        at org.codehaus.groovy.ast.ClassNode.getInterfaces(ClassNode.java:375)
        at org.codehaus.groovy.ast.ClassNode.declaresInterface(ClassNode.java:981)
        at org.codehaus.groovy.ast.ClassNode.implementsInterface(ClassNode.java:961)
        at org.codehaus.groovy.ast.ClassNode.isDerivedFromGroovyObject(ClassNode.java:951)
        at org.codehaus.groovy.classgen.AsmClassGenerator.isGroovyObject(AsmClassGenerator.java:1052)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitAttributeExpression(AsmClassGenerator.java:1030)
        at org.codehaus.groovy.ast.expr.AttributeExpression.visit(AttributeExpression.java:40)
        at org.codehaus.groovy.classgen.asm.CallSiteWriter.prepareSiteAndReceiver(CallSiteWriter.java:235)
        at org.codehaus.groovy.classgen.asm.CallSiteWriter.prepareSiteAndReceiver(CallSiteWriter.java:224)
        at org.codehaus.groovy.classgen.asm.CallSiteWriter.makeCallSite(CallSiteWriter.java:272)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCachedCall(InvocationWriter.java:307)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCall(InvocationWriter.java:397)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCall(InvocationWriter.java:104)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeInvokeMethodCall(InvocationWriter.java:88)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.writeInvokeMethod(InvocationWriter.java:464)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitMethodCallExpression(AsmClassGenerator.java:771)
        at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:66)
        at org.codehaus.groovy.classgen.asm.CallSiteWriter.prepareSiteAndReceiver(CallSiteWriter.java:235)
        at org.codehaus.groovy.classgen.asm.CallSiteWriter.prepareSiteAndReceiver(CallSiteWriter.java:224)
        at org.codehaus.groovy.classgen.asm.CallSiteWriter.makeCallSite(CallSiteWriter.java:272)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCachedCall(InvocationWriter.java:307)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCall(InvocationWriter.java:397)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCall(InvocationWriter.java:104)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeInvokeMethodCall(InvocationWriter.java:88)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.writeInvokeMethod(InvocationWriter.java:464)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitMethodCallExpression(AsmClassGenerator.java:771)
        at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:66)
        at org.codehaus.groovy.classgen.asm.BinaryExpressionHelper.evaluateEqual(BinaryExpressionHelper.java:316)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitDeclarationExpression(AsmClassGenerator.java:637)
        at org.codehaus.groovy.ast.expr.DeclarationExpression.visit(DeclarationExpression.java:89)
        at org.codehaus.groovy.classgen.asm.StatementWriter.writeExpressionStatement(StatementWriter.java:613)
        at org.codehaus.groovy.classgen.asm.OptimizingStatementWriter.writeExpressionStatement(OptimizingStatementWriter.java:366)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitExpressionStatement(AsmClassGenerator.java:624)
        at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:42)
        at org.codehaus.groovy.classgen.asm.StatementWriter.writeBlockStatement(StatementWriter.java:85)
        at org.codehaus.groovy.classgen.asm.OptimizingStatementWriter.writeBlockStatement(OptimizingStatementWriter.java:159)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitBlockStatement(AsmClassGenerator.java:570)
        at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:71)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:104)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:115)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitStdMethod(AsmClassGenerator.java:434)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitConstructorOrMethod(AsmClassGenerator.java:387)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitMethod(ClassCodeVisitorSupport.java:126)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitMethod(AsmClassGenerator.java:511)
        at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1081)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:53)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitClass(AsmClassGenerator.java:233)
        at org.codehaus.groovy.control.CompilationUnit$17.call(CompilationUnit.java:825)
        at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1065)
        ... 32 more
```

**Comment by big-guy** [comment]
@oehme @ljacomet can this be closed?

**Comment by ljacomet** [comment]
There definitely was not a plan to have differences in behavior of `IMPROVED_POM_SUPPORT` and Gradle 5.0.
However two changes ended up happening from community feedback:
* BOM support now requires an explicit attribute and has DSL entry points with `platform` and `enforcedPlatform` instead of detecting the pom format. This was made to help users understand better their build files when looking at them.
* Maven optional dependencies are no longer brought in as constraints as this caused more harm than good and Maven simply ignores that information anyway.

If you can prove this breakage has a different cause, feel free to re-open with more details.

**Comment by Vampire** [comment]
I am aware of these differences, but I think they are not relevant for this.
Both would show themselves in the output of `dependencies` task, wouldn't they?

I set the gradle version of https://github.com/rodm/gradle-teamcity-plugin.git to 4.10.2 without the feature preview and run the task, then I enabled the feature preview and run the task and then I disabled the feature preview and set the gradle version to 5.0-rc-4 and run the task.

Between 4.10.2 without and with the feature preview, the difference was just that the runtime-scoped transitive dependencies vanished from the `compileClasspath` and `testCompileClasspath` as expected, no BOMs or optional dependencies involved.

Between 4.10.2 with feature preview and 5.0-rc-4 there was no difference (besides the JaCoCo change from 0.8.1 to 0.8.2 and its dependencies).

Yet if I call the `compileGroovy` task on 4.10.2 with feature preview it fails, if I call it with 5.0-rc-4 it succeeds.

The class `com.jetbrains.plugin.structure.teamcity.TeamcityPluginManager` it complains about is in the `org.jetbrains.intellij.plugins:structure-teamcity:3.9` artifact which is present in both cases.
The dependency it is missing `org.jdom2.input.JDOMParseException` is in the `org.jdom:jdom2:2.0.6` artifact which is present in the `compileClasspath` and `testCompileClasspath` for 4.10.2 without feature preview, but not present for 4.10.2 with feature preview or 5.0-rc-4. It is present of course anyway in the `runtimeClasspath` and `testRuntimeClasspath`.

Is this maybe a bug in the Groovy version 2.4.15 that is available in Gradle 4.10.2 vs. 2.5.4 that is available in Gradle 5.0-rc-4?

**Comment by Vampire** [comment]
@ljacomet

**Comment by ljacomet** [comment]
Thanks for the details, however I am not sure we can act on them at this point.

There is indeed a possibility that something else brings `org.jdom:jdom2:2.0.6` as indeed the `structure-teamcity` pom only has `runtime` dependencies.
Finding out where it is in the classpath could shed more light on this issue.

However, in our experience with the Jetbrains plugins, the separation of `compile` and `runtime` is causing issues for users as they were really relying on the mix-up Gradle was doing of both scopes.

**Comment by Vampire** [comment]
At least according to the `dependencies` output, both cases are identical and `jdom2` is only available in the runtime classpath. That's why I'm wondering why the compile works in 5.0 but not in 4.10.2 with preview.

I run both cases again with debug enabled and compared the compile classpaths.
The only differences are the `gradle-api`, `groovy-all` and `gradle-installation-beacon` JARs and to make sure I looked into those, none has the `org.jdom2.input.JDOMParseException` class inside.

**Comment by ljacomet** [comment]
This is intriguing indeed and I really would like to be sure there is not a nasty issue hiding behind.

@gradle/dependency-management Anything that jumps at you that I could have missed?

@Vampire Any chance you could craft a reproducer?

**Comment by Vampire** [comment]
Yep, that was also my thought, that a nasty bug could be hiding, that's why I reported. :-)

As reproducer just use https://github.com/rodm/gradle-teamcity-plugin.git as I described above.
Set it to 4.10.2 with the feature preview enabled or set it to 5.0-rc-4 with feature preview disabled and call the `compileGroovy` task.

**Comment by ljacomet** [comment]
So I had a look and I am going to blame / thank a change in the Groovy compiler.
The class `TeamcityPluginManager` only uses the `JDOMParseException` inside a method, not as part of its API. So technically, it should not be required for compilation of code using `TeamcityPluginManager`.

This means that the change in the classpath is _as expected_ but the consequence is mitigated by the Groovy upgrade in Gradle 5.0.
