### ISSUE TITLE
Gradle doesn't run on Bash On Ubuntu on Windows (WSL.exe)

### ISSUE THREAD

**Issue by donalmacc** [gradle/gradle#773]
Executing gradle projects fails with 

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine a usable local IP for this machine.
```

when running on the Windows Subsystem for Linux. 
### Expected Behavior

Executing `gradle projects` should output 

```
:projects

------------------------------------------------------------
Root project
------------------------------------------------------------

Root project 'XXXX'
No sub-projects

To see a list of the tasks of a project, run gradle <project-path>:tasks
For example, try running gradle :tasks

BUILD SUCCESSFUL

Total time: 1.884 secs
```
### Current Behavior

Executing `gradle projects` in home directory when using WSL fails with

```
donal@HOME:~$ gradle projects

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine a usable local IP for this machine.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```
### Steps to Reproduce (for bugs)
- Set up Windows subsystem for linux, on windows 10 - see [MSDN installation instructions](https://msdn.microsoft.com/en-gb/commandline/wsl/install_guide). 
- Install java and gradle. My steps:

```
sudo add-apt-repository ppa:openjdk-r/ppa
sudo add-apt-repository ppa:cwchien/gradle

sudo apt-get update

sudo apt-get install openjdk-8-jre
sudo apt-get install gradle-3.1
```
- execute any gradle command - e.g. `gradle projects` in any directory.

**Comment by eriwen** [comment]
This may be related: https://bugs.openjdk.java.net/browse/JDK-7032558

@donalmacc Could you please provide a stack trace from current `gradle projects`?

**Comment by donalmacc** [comment]
Sure, here's the first few lines, the full output is [attached - gradleProjects.txt](https://github.com/gradle/gradle/files/566229/GradleProjects.txt)

```
* Exception is:
java.lang.RuntimeException: Could not determine a usable local IP for this machine.
        at org.gradle.internal.remote.internal.inet.InetAddressFactory.getLocalBindingAddress(InetAddressFactory.java:89)
        at org.gradle.cache.internal.FileLockCommunicator.<init>(FileLockCommunicator.java:38)
        at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler.getCommunicator(DefaultFileLockContentionHandler.java:153)
        at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler.reservePort(DefaultFileLockContentionHandler.java:145)
        at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:80)
        at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:68)
        at org.gradle.cache.internal.OnDemandFileAccess.readFile(OnDemandFileAccess.java:36)
        at org.gradle.cache.internal.SimpleStateCache.get(SimpleStateCache.java:47)
        at org.gradle.cache.internal.FileIntegrityViolationSuppressingPersistentStateCacheDecorator.get(FileIntegrityViolationSuppressingPersistentStateCacheDecorator.java:31)
        at org.gradle.launcher.daemon.registry.PersistentDaemonRegistry.getAll(PersistentDaemonRegistry.java:69)
        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connect(DefaultDaemonConnector.java:107)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:122)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:80)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
```

**Comment by donalmacc** [comment]
Hi guys

I was interested in this and found it appears to be a known issue with the WSL and is fixed in the next update. See https://github.com/Microsoft/BashOnWindows/issues/850

**Comment by eriwen** [comment]
Excellent! Thanks for circling back @donalmacc.
