### ISSUE TITLE
Gradle 5.0-rc-* fails with OutOfMemoryError: GC overhead limit exceeded on multi-project build

### ISSUE THREAD

**Issue by daggerok** [gradle/gradle#7746]
Hello all,

Do you know why Gradle 5 (5.0-rc-1 as well as 5.0-rc-2) can fail with error:
`OutOfMemoryError: GC overhead limit exceeded`?
Gradle 4.10.2 worked fine on my Linux 13 GB machine. 
Are there some known memory leaks for Gradle 5th version ?

### Current Behavior
After gradle migration to 5.0.-rc-2 my multi-module project build is works on my windows laptop with 32 GB memory, but starts fail on CI linux machines with about 13 GB RAM. That runners was OK for success build by using Gradle 4.10.2

### Context

I just upgrade my multi-project build for spring-boot apps 4.10.2 -> 5.0-rc-* and nothing more

### Your Environment

 * Build scan URL: cannot provide because of NDA
RHEL 7 with OpenDJK 8 181
Gradle wrapper 5.0-rc-1 / 5.0-rc-2

```
# ...skipped
> Task :modules:data:testing:xxx-fixtures:discoverTestScriptsExtensions
> Task :modules:data:testing:xxx-fixtures:compileTestKotlin
Expiring Daemon because JVM Tenured space is exhausted
Expiring Daemon because JVM Tenured space is exhausted

> Task :modules:data:testing:xxx-fixtures:compileTestJava FAILED


The system is out of resources.
Consult the following stack trace for details.
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at java.lang.String.substring(String.java:1933)
	at com.sun.tools.javac.file.RelativePath$RelativeFile.basename(RelativePath.java:182)
	at com.sun.tools.javac.file.ZipFileIndex.getZipIndexEntry(ZipFileIndex.java:237)
	at com.sun.tools.javac.file.ZipFileIndexArchive.getFileObject(ZipFileIndexArchive.java:75)
	at com.sun.tools.javac.file.JavacFileManager.listArchive(JavacFileManager.java:308)
	at com.sun.tools.javac.file.JavacFileManager.listContainer(JavacFileManager.java:355)
	at com.sun.tools.javac.file.JavacFileManager.list(JavacFileManager.java:624)
	at javax.tools.ForwardingJavaFileManager.list(ForwardingJavaFileManager.java:76)
	at com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:2803)
	at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:2446)
	at com.sun.tools.javac.jvm.ClassReader.access$000(ClassReader.java:76)
	at com.sun.tools.javac.jvm.ClassReader$1.complete(ClassReader.java:240)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
	at com.sun.tools.javac.jvm.ClassReader.completeOwners(ClassReader.java:2458)
	at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:2435)
	at com.sun.tools.javac.jvm.ClassReader.access$000(ClassReader.java:76)
	at com.sun.tools.javac.jvm.ClassReader$1.complete(ClassReader.java:240)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1037)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.members(Symbol.java:978)
	at com.sun.tools.javac.jvm.ClassReader$AnnotationDeproxy.findAccessMethod(ClassReader.java:1769)
	at com.sun.tools.javac.jvm.ClassReader$AnnotationDeproxy.deproxyCompound(ClassReader.java:1759)
	at com.sun.tools.javac.jvm.ClassReader$AnnotationDeproxy.deproxyCompoundList(ClassReader.java:1748)
	at com.sun.tools.javac.jvm.ClassReader$AnnotationCompleter.run(ClassReader.java:1943)
	at com.sun.tools.javac.comp.Annotate.flush(Annotate.java:143)
	at com.sun.tools.javac.comp.Annotate.enterDone(Annotate.java:129)
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:512)
	at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:982)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.enterTrees(JavacProcessingEnvironment.java:1015)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':modules:data:testing:xxx-fixtures:compileTestJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':modules:data:testing:xxx-fixtures:compileTestJava'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:96)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:65)
	at org.gradle.api.internal.tasks.execution.ActionEventFiringTaskExecuter.execute(ActionEventFiringTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.TimeoutTaskExecuter.execute(TimeoutTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.SnapshotAfterExecutionTaskExecuter.execute(SnapshotAfterExecutionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:49)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:61)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:49)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:44)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:337)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:325)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:318)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:304)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:52)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:36)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:100)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:52)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
	at org.gradle.api.internal.tasks.compile.AnnotationProcessorDiscoveringCompiler.execute(AnnotationProcessorDiscoveringCompiler.java:51)
	at org.gradle.api.internal.tasks.compile.AnnotationProcessorDiscoveringCompiler.execute(AnnotationProcessorDiscoveringCompiler.java:37)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:39)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilerFactory$2.execute(IncrementalCompilerFactory.java:110)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilerFactory$2.execute(IncrementalCompilerFactory.java:106)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringCompiler.execute(IncrementalResultStoringCompiler.java:59)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringCompiler.execute(IncrementalResultStoringCompiler.java:43)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:152)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:117)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:106)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:85)
	... 38 more


* Get more help at https://help.gradle.org

BUILD FAILED in 30m 28s

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.0-rc-2/userguide/command_line_interface.html#sec:command_line_warnings
595 actionable tasks: 595 executed
Expiring Daemon because JVM Tenured space is exhausted
ERROR: Job failed: exit status 1
```

Thanks for any help...

---
Regards,
Maksim

**Comment by oehme** [comment]
Please make sure you have set enough memory in the project's `gradle.properties`. The default was changed to 512m in 5.0

**Comment by daggerok** [comment]
Thank you, @oehme fir pointing me into it
I found proper release notes (for 5.0-rc-1 version)

Do you know, if I should adjust something else except

```properties
org.gradle.jvmargs=-Xms1g
```

in gradle.propertoes file?

as far as I understand, this config is only for gradle daemon, but what settings gradle client has itself by default? should I also adjust JAVA_OPTS in additional to make sure gradle client will be happy? or It's enough to just take care about gradle daemons?

Thanks

**Comment by oehme** [comment]
Don't worry about the client, it doesn't need more memory since it only streams console output.

**Comment by daggerok** [comment]
Well, spend whole day... Many different combinations where used, but no get luck =(

Seems like some plugins we are using has memory leaks... 
Unfortunately I wasn't able to identify what actually caused problem, but full build works only with disabled gradle daemon and according JAVA_OPTS:

file: `Dockerfile`

```Dockerfile
FROM daggerok/e2e:ubuntu-xvfb-jdk8-firefox
WORKDIR 'my-project/'
ENV JAVA_OPTS="${JAVA_OPTS} -Xms4g -Xmx4g" \
    GRADLE_TASKS_ENV=${GRADLE_TASKS}
ENTRYPOINT start-xvfb && ./gradlew ${GRADLE_TASKS_ENV}
COPY . .
```

file: `.gitlab-ci.yaml`

```yaml
test all:
  stage: test
  tags:
  - docker
  before_script:
  - docker build --force-rm --no-cache
      --build-arg GRADLE_TASKS='test firefox build -S --no-daemon --warning-mode=summary'
      -t all-tests .
  script:
  - docker run --rm --name run-all-tests all-tests
```

any other combinations configurations in gradle.properties doesn't work... 

Nope this helps someone

---
Regards,
Maksim

**Comment by oehme** [comment]
> Many different combinations where used, but no get luck =(

You didn't show what you tried. If your build needs 4G, then you have to give it that in the gradle.properties. You should also attach a profiler to see if there is a memory leak, because 4G is a lot.

**Comment by daggerok** [comment]
Hello, @oehme 

Well, it wasn't clean since my last trying..
I just verified, that JAVA_OPTS with -Xms1g -Xmx1g is enough

Regards

**Comment by oehme** [comment]
Still, you shouldn't need no-daemon. I'll leave it up to you to investigate, I just wanted to clarify that `--no-daemon` should not be the solution.

**Comment by daggerok** [comment]
Well, otherwise it doesn't work (at least on CI RHEL 7 with 12? GB RAM)

I also would like to know what is the problem, but I spend a lot of time for that activity and cannot effort more at the moment.. What I can do, is only post here all plugins we are using in our project if it can help investigate a problem to someone else

This is my root `build.gradle` file:

```gradle
buildscript {
  ext {
    javaVersion = '1.8'
    vavrVersion = '0.9.2'
    jaksonVersion = '2.9.7'
    lombokVersion = '1.18.4'
    springBootVersion = '2.1.0.RELEASE'

    asciitableVersion = '0.3.2'
    retrofitVersion = '2.4.0'
    picocliVersion = '3.8.0'
    jansiVersion = '1.17.1'
    mapdbVersion = '3.0.7'

    jqeuryVersion = '3.3.1-1'
    materializeCssVersion = '0.100.2' // TOOD: 1.0.0 release is available, but migration must be done in a separate epic
    materialDesignIconsVersion = '3.0.1'

    hamcrestVersion = '1.4-atlassian-1'
    junitJupiterVersion = '5.3.1'
    selenideVersion = '5.0.1'
    assertkVersion = '0.10'
    allureVersion = '2.6.0'
    junit4Version = '4.12'
  }

  dependencies {
    classpath('org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.16')
    classpath('org.jruby:jruby-complete:9.2.4.0')
  }

  ext['kotlin.version'] = '1.3.10'
  ext['lombok.version'] = lombokVersion

  configurations.all {
    resolutionStrategy {
      force 'org.codehaus.groovy:groovy-all:2.5.3' /* don't ask, asciidoctor... */
    }
  }
}

plugins {
  id 'io.qameta.allure' version '2.5' apply false
  id 'com.jfrog.artifactory' version '4.8.1' apply false
  id 'org.jetbrains.kotlin.jvm' version '1.3.10' apply false
  id 'org.jetbrains.kotlin.plugin.jpa' version '1.3.10' apply false
  id 'org.jetbrains.kotlin.plugin.spring' version '1.3.10' apply false
  id 'io.spring.dependency-management' version '1.0.6.RELEASE' apply false
  id 'org.springframework.boot' version '2.1.0.RELEASE' apply false
  id 'com.github.johnrengelman.shadow' version '4.0.2' apply false
  id 'org.asciidoctor.convert' version '1.5.9.1' apply false
  id 'io.franzbecker.gradle-lombok' version '1.14' apply false
  id 'cn.bestwu.propdeps-maven' version '0.0.10' apply false
  id 'cn.bestwu.propdeps-idea' version '0.0.10' apply false
  id 'cn.bestwu.propdeps' version '0.0.10' apply false
  id 'com.github.ben-manes.versions' version '0.20.0'
}

wrapper {
  gradleVersion = '5.0-rc-3'
  distributionType = 'BIN'
}

// also in subprojects we are using plugins such as: idea, eclipse, maven, java, jacoco, findbugs
```

I can suspect gradle lombok plugin, but at the moment cannot removed it to check if it brings these issues...

Aslo I have my personal suspicious on `com.github.ben-manes.versions` gradle plugin, but any of it tasks are running during build.. maybe will check it next week

---
Regards,
Maksim

**Comment by tlinkowski** [comment]
Hi, I'd like to share my experiences with `OutOfMemoryError` when updating from 4.10.3 to 5.0 (in the hope that it might help someone).

In my case (a pretty large multi-project build with unit tests + integration tests), I "hit" the following [memory changes](https://docs.gradle.org/current/userguide/upgrading_version_4.html#rel5.0:default_memory_settings):
1. Gradle daemon:
    > The Gradle daemon now starts with 512MB of heap instead of 1GB.

    512BM was actually enough, although I observed many GCs so - just to make sure - I switched back to the old behavior using `gradle.properties` and `org.gradle.jvmargs=-Xmx1g` for now.
2. Gradle text executors:
    > All workers, including compilers and test executors, now start with 512MB of heap. The previous default was 1/4th of physical memory.

    For my integration tests, where I load some large ML models into memory, 512MB was definitely not enough. And since my machine has 16GB of RAM, I didn't notice that those tasks needed more RAM. I solved this by setting `maxHeapSize` property of the `Test` task:
    ```
    integrationTest {
      maxHeapSize = "4g"
    }
    ```

I want to emphasize that I actually like the changes - especially the second one because:
- now the build is easily repeatable on different environments,
- this change made me aware of the memory requirements that my build had,
- and it made me make those requirements explicit in `build.gradle`.

**Comment by Kevin-Li-ConnectedLab** [comment]
@daggerok did you find a solution to this? we are running into the same problem

**Comment by oehme** [comment]
@Kevin-Li-ConnectedLab Here's the rough process:

1. Make sure all daemons are killed
2. Run the build once - Does it succeed? If not, you simply have too little memory and need to increase it. If yes, see next step
3. Run a couple more builds, doing some changes in between (e.g. `buildSrc` or `build.gradle` changes). Attach a profiler like JProfiler/YourKit/JVisualVM and see if memory usage grows over time. If yes, you've found a memory leak. Most profilers have a feature like "Find duplicate classes" which will often uncover classloader leaks, which are the most common type of leak for a Gradle plugin.

**Comment by caseykulm** [comment]
I am running into this with Gradle 5.4.1, and `org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8` in my projects `gradle.properties`. With the gradle wrapper, gradle daemons, kotlin compile daemons, and gradle worker process all being spawned what should I look at profiling to help debug this?

**Comment by caseykulm** [comment]
Managed to get a heap dump that seems relevant, and am seeing this,

```
43,264 instances of "org.bouncycastle.jcajce.provider.asymmetric.x509.X509CertificateObject", loaded by "org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader @ 0x7a0062aa0" occupy 256,775,168 (54.34%) bytes. 

Keywords
org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader @ 0x7a0062aa0
org.bouncycastle.jcajce.provider.asymmetric.x509.X509CertificateObject
```

**Comment by daggerok** [comment]
I've got some experience with Gradle 5.+ last 6-7 months and found that usually that annoying OutOfMemory issues related to plugins. Sometimes its very hard to find a root cause, but random combination of different plugins due to some reasons can cause that error in different situations

My recommendation is 
1) avoid big mono repos if its possible. Otherwise managing big amount of modules which requires big amount of different plugins became a nightmare
2) if its impossible to split modules and you have to manage a lot of them in single monorepo, try apply specific plugin in as later as you can (bottom leaf of modules dependencies tree). cons: more code duplication, profs: less build time and memory consumption, faster gradle build configuration phase
3) use build scan for better analysis (probably it would be great if Gradle docs will have some good article about it, how effectively build scan can be used to make our build scripts better / faster)

**Comment by caseykulm** [comment]
Okay, yep this is a rather large project which isn't immediately avoidable. No daemon and no build cache don't seem to be able to prevent OOM for this build. I'm also running on my local machine at the moment with `Java(TM) SE Runtime Environment (build 1.8.0_152-b16)` which is working on previous 4.x versions of Gradle. I'm going to continue trying to profile/debug.

**Comment by oehme** [comment]
You can share the heap dump with us. If you find leaks in plugins, please report them to the plugin maintainers.

**Comment by gregriggins36** [comment]
> Managed to get a heap dump that seems relevant, and am seeing this,
> 
> ```
> 43,264 instances of "org.bouncycastle.jcajce.provider.asymmetric.x509.X509CertificateObject", loaded by "org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader @ 0x7a0062aa0" occupy 256,775,168 (54.34%) bytes. 
> 
> Keywords
> org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader @ 0x7a0062aa0
> org.bouncycastle.jcajce.provider.asymmetric.x509.X509CertificateObject
> ```
> 
> ```
> 416 instances of "okhttp3.internal.tls.BasicCertificateChainCleaner", loaded by "org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader @ 0x7a0062aa0" occupy 70,353,920 (14.89%) bytes. 
> 
> Keywords
> org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader @ 0x7a0062aa0
> okhttp3.internal.tls.BasicCertificateChainCleaner
> ```
> 
> ```
> 467 instances of "android.content.res.AssetManager", loaded by "org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader @ 0x7a0062aa0" occupy 47,748,928 (10.10%) bytes. 
> 
> Keywords
> org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader @ 0x7a0062aa0
> android.content.res.AssetManager
> ```

@caseykulm I'm seeing the same issue in our CI environment. Did you find any way around this?

**Comment by gregriggins36** [comment]
@caseykulm FYI, for me the issue was that I forgot to create TestApp class so we were loading the entire application (going through its onCreate method) for every tests.
I just added a TestApp and override all the methods called in onCreate to do nothing

**Comment by caseykulm** [comment]
@gregriggins36 Nice. We have not managed to figure this out yet, and decided to hold off on upgrading to 5.x for a while. We do have a TestApp for Robolectric with no-op, but maybe there's something related to that I could check out, thanks!

**Comment by eschlenz** [comment]
I have a fix that worked for us. Wanted to share.

The issue we (@caseykulm and I) were seeing was an OutOfMemoryError _**specifically during execution of our tests**_. I tried several things initially, but none of them worked. Then I noticed that the Gradle 5 documentation specifically mentions the following:

> All workers, including compilers and test executors, now start with 512MB of heap. The previous default was 1/4th of physical memory.

Our builds were failing on tests, so that _must_ be what needs to be configured to use more memory! We applied the following change in our root gradle script:

```
subprojects {
    tasks.withType(Test) {
        maxHeapSize = "3g"
    }
}
```

**This fixed the issue for us!**

**Comment by MoeMamdouh** [comment]
Add this line to gradle properties file
```
org.gradle.jvmargs=-Xms128m -Xmx1024m -XX:+CMSClassUnloadingEnabled
```

**Comment by ericntd** [comment]
Care to explain `-XX:+CMSClassUnloadingEnabled` @MoeMamdouh ?

**Comment by daggerok** [comment]
If you enable `CMSClassUnloadingEnabled`, then the GC will sweep PermGen, too, and remove classes which are no longer used.

**Comment by nileshteji** [comment]
I am facing this issue in Android Studio . Can anybody help with the proper Solution?

**Comment by bc67da8d** [comment]
If your computer's RAM enough, just increase:
From:
`org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
To bigger, in my case is 3GB (3072 Mb):
`org.gradle.jvmargs=-Xmx3072m -XX:MaxPermSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

Or you can use @MoeMamdouh suggestion, I think it is better:
`org.gradle.jvmargs=-Xms128m -Xmx1024m -XX:+CMSClassUnloadingEnabled

**Comment by jhyry-gcpud** [comment]
I was facing this issue and after flailing, I finally realized it was the wrapper process that was causing this.
After modifying gradlew.bat default JVM opts to have more memory and use a more efficient Collector, this stopped happening.
