### ISSUE TITLE
Custom Distributions cause the `maven install` task to fail.

### ISSUE THREAD

**Issue by johnrengelman** [gradle/gradle#7807]
When adding a custom distribution to a project per https://docs.gradle.org/current/userguide/distribution_plugin.html#example_adding_extra_distributions and using the `maven` plugin, the `install` task fails with:

```
> Task :customDistTar
> Task :customDistZip
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :jar
> Task :startScripts
> Task :distTar
> Task :distZip
> Task :install FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':install'.
> Could not publish configuration 'archives'
   > A POM cannot have multiple artifacts with the same type and classifier. Already have MavenArtifact maven:zip:zip:null, trying to add MavenArtifact maven:zip:zip:null.
```

Relevant stacktrace:
```
Caused by: org.gradle.api.InvalidUserDataException: A POM cannot have multiple artifacts with the same type and classifier. Already have MavenArtifact maven:zip:zip:null, trying to add MavenArtifact maven:zip:zip:null.
	at org.gradle.api.publication.maven.internal.DefaultArtifactPom.addArtifact(DefaultArtifactPom.java:65)
	at org.gradle.api.publication.maven.internal.DefaultArtifactPomContainer.addArtifact(DefaultArtifactPomContainer.java:55)
	at org.gradle.api.publication.maven.internal.deployer.AbstractMavenResolver.collectArtifact(AbstractMavenResolver.java:113)
	at org.gradle.api.publication.maven.internal.deployer.AbstractMavenResolver.publish(AbstractMavenResolver.java:104)
	at org.gradle.api.publication.maven.internal.deployer.BaseMavenInstaller.publish(BaseMavenInstaller.java:27)
	at org.gradle.internal.component.external.ivypublish.DefaultArtifactPublisher.publish(DefaultArtifactPublisher.java:76)
	at org.gradle.api.internal.artifacts.ivyservice.IvyContextualArtifactPublisher$1.execute(IvyContextualArtifactPublisher.java:43)
	at org.gradle.api.internal.artifacts.ivyservice.IvyContextualArtifactPublisher$1.execute(IvyContextualArtifactPublisher.java:40)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:133)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:63)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:41)
	at org.gradle.api.internal.artifacts.ivyservice.IvyContextualArtifactPublisher.publish(IvyContextualArtifactPublisher.java:40)
	at org.gradle.api.tasks.Upload.upload(Upload.java:65)
```

### Expected Behavior
`gradle install` should succeed.

### Current Behavior
`gradle install` errors with above message. 
Custom distribution shouldn't be automatically added to the `archives` scope or Distributions should provided a way to specify a `classifier`.

### Context

I am encountering this in Shadow plugin when uses apply `application`, `maven`, and `shadow` to a project.

The shadow plugin creates a custom distribution similar to the default java distribution but contains the shadow jar instead of the application jar and libraries.

The workaround is to specify the following in the build file:
```
shadowDistZip.classifier = 'shadow'
shadowDistTar.classifier = 'shadow'
```

Shadow could configure this when it creates the distribution, but this is very counter-intuitive as these tasks are created by adding the custom distribution.

It would seem that `DistributionSpec` should have a `classifier` setting that would propagate down to the resulting tasks, but it doesn't.

### Steps to Reproduce (for bugs)
```
apply plugin: 'java'
apply plugin: 'maven'
apply plugin: 'application'

version = "1.0"
group = 'shadow'

mainClassName = 'my.App'

distributions {
  custom {
    baseName = "custom"
    contents {
      from 'build.gradle'
    }
  }
}

dependencies {}  
```

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/gzcenyf7igakg

**Comment by marcphilipp** [comment]
Have you considered using the `maven-publish` plugin instead? If you only want a single distribution, you could clear `archives` before adding the `custom` distribution.

**Comment by johnrengelman** [comment]
It’s not my decision which plugin a user of my plugins uses. I’m trying to write shadow to support either since neither is deprecated afaik. 

I’m pointing this out because afaict the example of custom distributions in the docs fails when also applying the maven plugin like in the linked example.

**Comment by marcphilipp** [comment]
Sure, thanks for the clarification. I agree that adding a `classifier` property to `DistributionSpec` would be helpful in this scenario.
