### ISSUE TITLE
gradle daemon fail w/ OpenJDK9: add-opens unrecognized option

### ISSUE THREAD

**Issue by darkn3rd** [gradle/gradle#7829]
Starting gradle command (`gradle init --type groovy-library`) causes JVM error `Unrecognized option: --add-opens` on Ubuntu 16.04 with OpenJDK9. 

### Expected Behavior

I expected the initial build scripts and such would be created, and gradle command would not fail.

### Current Behavior

```
Starting a Gradle Daemon (subsequent builds will be faster)
Could not write standard input to Gradle build daemon.
java.io.IOException: Stream closed
        at java.lang.ProcessBuilder$NullOutputStream.write(java.base@9-internal/ProcessBuilder.java:443)
        at java.io.OutputStream.write(java.base@9-internal/OutputStream.java:116)
        at java.io.BufferedOutputStream.flushBuffer(java.base@9-internal/BufferedOutputStream.java:81)
        at java.io.BufferedOutputStream.flush(java.base@9-internal/BufferedOutputStream.java:142)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:66)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:51)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(java.base@9-internal/Thread.java:804)

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/4.10.2/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Unrecognized option: --add-opens
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

### Context

I am trying to get off the ground with a simple application, but I cannot get off the ground with getting started.  In the past, I did not have a problem with gradle 2.x and JDK8, but now with OpenJDK9 and Gradle 4.x, I cannot get started.  At work, I see some engineers using Gradle, and I wanted to support them, but given the very basics do not work, confidence is not high. 

### Steps to Reproduce (for bugs)

```bash
sudo apt-get purge gradle
curl -s "https://get.sdkman.io" | bash
source "/home/joaquin/.sdkman/bin/sdkman-init.sh"
sdk install gradle 4.10.2

mkdir -p src/main/groovy/

cat <<-'SCRIPT' > src/main/groovy/Service.groovy
import static spark.Spark.*

get('/', { req, res -> "Hello World!\n" })
get('/hello', { req, res -> "Hello World!\n" })
get('/hello/', { req, res -> "Hello World!\n" })
get("/hello/:name", { req, res -> "Why, Hello ${req.params(":name")}!\n" })
SCRIPT

gradle init --type groovy-library
```

### Your Environment

I cannot gradle to get started, so I cannot even get a build scan.

* Ubuntu 16.04
* OpenJDK 9 (`sudo apt-get install openjdk-9-jre-headless`)

```
------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          9-internal (Oracle Corporation 9-internal+0-2016-04-14-195246.buildd.src)
OS:           Linux 4.15.0-29-generic amd64
```

**Comment by darkn3rd** [comment]
Simple `gradle hello` fails as well with 

```groovy
task hello {
    doLast {
        println 'Hello Gradle'
    }
}

```

**Comment by marcphilipp** [comment]
You seem to be using some preview version of the JDK. It works with OpenJDK 9.0.4:

```
$ java --version
openjdk 9.0.4
OpenJDK Runtime Environment (build 9.0.4+11)
OpenJDK 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

Please upgrade to the latest 9.x version.
