### ISSUE TITLE
TestNG parallel test execution via Gradle fails with "Received a completed event for test with unknown id".

### ISSUE THREAD

**Issue by joshuamillsma** [gradle/gradle#7878]
The appears to relate to https://github.com/gradle/gradle/issues/6453, but for TestNG instead of JUnit.  I attempted some of the fixes described in that ticket (turn off parallel execution, use the testng serialized annotation), but nothing worked.  I ran into this bug on the 5.0 release, as well as a recent 5.1 build (gradle-5.1-20181128000036+0000-bin), so I do not think it is yet fixed.

### Expected Behavior
All tests are executed normally

### Current Behavior
Tests fail.

Stack:
`Received a completed event for test with unknown id '1.301'. Registered test ids: '[1.1, 1.33, 1.3, 1.35, :modules-offheap:test, 1.2, 1.229, 1.232, 1.31]'
java.lang.IllegalArgumentException: Received a completed event for test with unknown id '1.301'. Registered test ids: '[1.1, 1.33, 1.3, 1.35, :modules-offheap:test, 1.2, 1.229, 1.232, 1.31]'
        at org.gradle.api.internal.tasks.testing.results.StateTrackingTestResultProcessor.completed(StateTrackingTestResultProcessor.java:79)
        at org.gradle.api.internal.tasks.testing.results.AttachParentTestResultProcessor.completed(AttachParentTestResultProcessor.java:56)
        at jdk.internal.reflect.GeneratedMethodAccessor578.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:29)
        at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
        at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
        at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
        at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:834)`

### Context

I have been attempting to upgrade to Gradle 5 in order to switch to java 11 (see https://github.com/gradle/gradle/issues/7835) since there are no plans to backport ASM fixes into Gradle 4.10.  I was able to get past the other compatibility problems and got stymied by this bug.  I have disabled the offending tests for the time being, but I would like to turn them back on.

### Steps to Reproduce (for bugs)

I have not extracted a small project to reproduce this yet, but will do so if requested.  The test in question uses a "@DataProvider" and executes hundreds of very short running tests.

### Your Environment

OS	CentOS Linux release 7.4.1708
CPU cores	8 cores
Java version	openjdk version "11.0.1" 2018-10-16

**Comment by marcphilipp** [comment]
A small sample project would be very helpful. Could you please provide one?

Does this work with 4.10.2? Did you change anything else besides the Gradle version, e.g. the TestNG dependency version?

**Comment by joshuamillsma** [comment]
It works fine in gradle 4.10.2.  The only difference is that I switched to
gradle 5.
I'll put together a sample.

**Comment by joshuamillsma** [comment]
[testngfail.zip](https://github.com/gradle/gradle/files/2634686/testngfail.zip)

**Comment by joshuamillsma** [comment]
Required to break:
1. Gradle 5 and higher
2. testng 6.9.13 and higher (6.9.10 is not broken)
3. Test factory creating multiple of the same test class, and a test in the class depends on another test in that same class.

**Comment by joshuamillsma** [comment]
`import org.testng.annotations.Factory;
import org.testng.annotations.Test;

import org.testng.Assert;

public class TestNG7878
{
    @Factory
    public static Object[] createTests()
    {
        return new Object[]{ 
                new TestNG7878(), 
                new TestNG7878() 
        };
    }

    @Test
    public void runFirst() {}
    
    @Test(dependsOnMethods = "runFirst")
    public void testGet2()
    {
        Assert.assertEquals(true, true);
    }
}`

**Comment by joshuamillsma** [comment]
`> Task :test FAILED
Received a completed event for test with unknown id '1.9'. Registered test ids: '[1.1, 1.3, 1.2, 1.4, :test]'
java.lang.IllegalArgumentException: Received a completed event for test with unknown id '1.9'. Registered test ids: '[1.1, 1.3, 1.2, 1.4, :test]'
        at org.gradle.api.internal.tasks.testing.results.StateTrackingTestResultProcessor.completed(StateTrackingTestResultProcessor.java:79)
        at org.gradle.api.internal.tasks.testing.results.AttachParentTestResultProcessor.completed(AttachParentTestResultProcessor.java:56)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:29)
        at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
        at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
        at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
        at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:834)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> java.lang.NullPointerException (no error message)`

**Comment by marcphilipp** [comment]
Root cause: #6816.

**Comment by Pratish89** [comment]
@marcphilipp  how this can be resolved? i am having the same error. 

Gradle version: v6.3
testNG: v6.10

**Comment by marcphilipp** [comment]
@Pratish89 Please open a new issue and supply a reproducer.
