### ISSUE TITLE
MissingMethodException in jacocoTestReport

### ISSUE THREAD

**Issue by b1zzu** [gradle/gradle#7951]
### Expected Behavior
`gradle jacocoTestReport` should produce a jacoco report

### Current Behavior
```
14:26:20: Executing task 'jacocoTestReport --stacktrace'...


> Configure project :

> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :jacocoTestReport

FAILURE: Build failed with an exception.

* What went wrong:
Could not find method execute() for arguments [] on task ':reportJacoco' of type com.github.ksoichiro.console.reporter.ReportJacocoTask.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method execute() for arguments [] on task ':reportJacoco' of type com.github.ksoichiro.console.reporter.ReportJacocoTask.
	at org.gradle.internal.metaobject.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:179)
	at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:164)
	at com.github.ksoichiro.console.reporter.ReportJacocoTask_Decorated.invokeMethod(Unknown Source)
	at com.github.ksoichiro.console.reporter.ReportJacocoTask$_closure1$_closure2.doCall(ReportJacocoTask.groovy:35)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy59.afterExecute(Unknown Source)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:55)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:44)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:337)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:325)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:318)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:304)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)


* Get more help at https://help.gradle.org

BUILD FAILED in 3s
3 actionable tasks: 1 executed, 2 up-to-date
Could not find method execute() for arguments [] on task ':reportJacoco' of type com.github.ksoichiro.console.reporter.ReportJacocoTask.
14:26:23: Task execution finished 'jacocoTestReport --stacktrace'.
```

### Context
I'm trying to create jacoco reports.

### Steps to Reproduce (for bugs)
Execute `gradle jacocoTestReport`

### Your Environment
* Gradle: 5.0
* OpenJDK: 11

#### build.gradle:
```
plugins {
    id "java"
    id "eclipse"
    id "idea"
    id "jacoco"

    id "org.springframework.boot" version "2.1.0.RELEASE"
    id "io.spring.dependency-management" version "1.0.6.RELEASE"
    id "com.palantir.git-version" version "0.9.1"
    id "com.diffplug.gradle.spotless" version "3.9.0"
    id "com.github.ksoichiro.console.reporter" version "0.5.0"
    id "org.sonarqube" version "2.6.2"
    id "org.unbroken-dome.test-sets" version "1.5.1"
    id "com.github.ben-manes.versions" version "0.20.0"
}

group = "com.example.project"
version = gitVersion()
description = "Project"
sourceCompatibility = 11
targetCompatibility = 11

repositories {
    mavenCentral()
}

jacoco {
    toolVersion = "0.8.2"
}

testSets {
    integrationTest
}

test {
    useJUnitPlatform()
}

integrationTest {
    useJUnitPlatform()
}

ext {
    lombockVersion = "1.18.2"
    postgresVersion = "42.2.5"
    graphqlSpringBootVersion = "5.4"
    ibmMqVersion = "9.1.0.0"
    randomBeansVersion = "3.7.0"
    hamcrestVersion = "1.3"
    keycloakSpringBootVersion = "4.6.0.Final"
    apacheCommonsCodecVersion = "1.11"
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.session:spring-session-core")

    // Keycloak
    implementation("org.keycloak:keycloak-spring-boot-starter:$keycloakSpringBootVersion")

    // Apache Commons
    implementation("commons-codec:commons-codec:$apacheCommonsCodecVersion")

    // Liquibase
    implementation("org.liquibase:liquibase-core")

    // Postgresql
    runtimeOnly("org.postgresql:postgresql:$postgresVersion")

    // GraphQL
    implementation("com.graphql-java-kickstart:graphql-spring-boot-starter:$graphqlSpringBootVersion")
    implementation("com.graphql-java-kickstart:graphiql-spring-boot-starter:$graphqlSpringBootVersion")

    // IBM MQ Client
    implementation("com.ibm.mq:com.ibm.mq.allclient:$ibmMqVersion")

    // Lombok
    annotationProcessor("org.projectlombok:lombok:$lombockVersion")
    compileOnly("org.projectlombok:lombok:$lombockVersion")

    // Spring boot for Test
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.springframework.security:spring-security-test")

    // Lombok for Test
    testAnnotationProcessor("org.projectlombok:lombok:$lombockVersion")
    testCompileOnly("org.projectlombok:lombok:$lombockVersion")

    // Junit 5
    testImplementation("org.junit.jupiter:junit-jupiter-api")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")

    // Random Beans
    testImplementation("io.github.benas:random-beans:$randomBeansVersion")

    // Hamcrest
    testImplementation("org.hamcrest:hamcrest-all:$hamcrestVersion")
}
```

**Comment by big-guy** [comment]
The plugin `com.github.ksoichiro.console.reporter` is fundamentally broken.  This produced deprecations in 4.x and will now fail in 5.0:
https://github.com/ksoichiro/gradle-console-reporter/blob/v0.5.0/src/main/groovy/com/github/ksoichiro/console/reporter/ReportJacocoTask.groovy#L35

You can remove that plugin if you can live without its functionality.

**Comment by GurpreetSK95** [comment]
Hi, I cannot remove the plugin dependency. Is there a solution for such case?
