### ISSUE TITLE
com.sun.tools package prevents the use of less conventional java compiler's flags

### ISSUE THREAD

**Issue by alexjinghn** [gradle/gradle#8097]
### Expected Behavior
When I specify a compiler flags, I expect gradle to apply whatever I supplied instead of validating it for me. If it's not valid, I prefer to have the compiler to inform me.

### Current Behavior

If I specify a flag with `compileJava.options.compilerArgs.addAll(["-J-XX:+UseZingMXBeans"])` (This is a valid compiler flag for zing jvm compiler), I receive the following error
```
Caused by: java.lang.IllegalArgumentException: invalid flag: -J-XX:+UseZingMXBeans
        at com.sun.tools.javac.api.JavacTool.processOptions(JavacTool.java:206)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:156)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:107)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:64)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.createCompileTask(JdkJavaCompiler.java:67)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:49)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:36)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:86)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:47)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:33)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:40)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:27)
        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:161)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:146)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:118)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 30 more
```

If I also tried to specify the compiler to use with 

```
compileJava.options.fork=true
compileJava.options.forkOptions.executable="$JAVA_HOME/bin/javac"
compileJava.options.compilerArgs.addAll(["-J-XX:+UseZingMXBeans"])
```

I received a different error:
```
An exception has occurred in the compiler (1.8.0_72). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.AssertionError: the -J flag should be caught by the launcher.
        at com.sun.tools.javac.main.Option$20.process(Option.java:331)
        at com.sun.tools.javac.main.Main.processArgs(Main.java:260)
        at com.sun.tools.javac.main.Main.compile(Main.java:414)
        at com.sun.tools.javac.main.Main.compile(Main.java:381)
        at com.sun.tools.javac.main.Main.compile(Main.java:370)
        at com.sun.tools.javac.main.Main.compile(Main.java:361)
        at com.sun.tools.javac.Main.compile(Main.java:56)
        at com.sun.tools.javac.Main.main(Main.java:42)
```
Note that I used a hotspot compiler here. However, even if I use a zing compiler, the error is the same.
When I compile classes with zing compiler directly with this flag, I have no problem at all.

### Context

This prevents me from using a less conventional compiler to compile my classes.

### Steps to Reproduce (for bugs)

Using this demo: https://github.com/gradle/gradle/tree/master/subprojects/docs/src/samples/java/quickstart/groovy

add the following to build.gradle
```
tasks.compileJava {
        // uncomment to have the second type of error
        //options.fork=true
        //options.forkOptions.executable=$JAVA_HOME/bin/javac"
        options.compilerArgs.addAll(["-J-XX:+UseZingMXBeans"])
}
```

run
```
gradle wrapper
./gradlew build
```

### Your Environment

 * Build scan URL:

**Comment by oehme** [comment]
The `-J` args are not compiler arguments, but JVM arguments for the VM running the compiler. You can specify those by dropping the `-J` and adding them to the `jvmArgs` of the fork options.

```
tasks.compileJava {
        options.fork=true
        options.jvmArgs << "-XX:+UseZingMXBeans"
}
```

**Comment by alexjinghn** [comment]
Thanks @oehme,

`compileJava.options` does not have `jvmArgs` field

I got it to work with 

```
    compileJava.options.fork=true
    compileJava.options.forkOptions.jvmArgs << "-XX:+UseZingMXBeans"
```

Surprisingly, it even builds without `compileJava.options.fork=true`, which seems weird since I AM configuring for `forkOptions`.

Is there a way to configure this flag for compiler without having to enable `fork`?

Thanks!

**Comment by oehme** [comment]
> Is there a way to configure this flag for compiler without having to enable fork?

No, because what you are trying to do is enable a JVM option, which can only be done on a new JVM.
