### ISSUE TITLE
Java11 & Gradle 5.1 failed to create new project with `gradle init --type java-library`

### ISSUE THREAD

**Issue by michaelwan** [gradle/gradle#8176]
Java11 & Gradle 5.1 failed to create new project with `gradle init --type java-library`
### Expected Behavior
Expecting a gradle project skeleton setup by running command `gradle init --type java-library`.

### Current Behavior
Below is the screen copy:
```
➜  test gradle init --type java-library

FAILURE: Build failed with an exception.

* What went wrong:
Could not create an instance of type org.gradle.invocation.DefaultGradle_Decorated.
> Could not configure services using GradleScopeCompileServices.configure().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

And I have run with stacktrace:
```
➜  test gradle init --type java-library --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Could not create an instance of type org.gradle.invocation.DefaultGradle_Decorated.
> Could not configure services using GradleScopeCompileServices.configure().

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.reflect.ObjectInstantiationException: Could not create an instance of type org.gradle.invocation.DefaultGradle_Decorated.
        at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:53)
        at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
        at org.gradle.initialization.DefaultGradleLauncherFactory.doNewInstance(DefaultGradleLauncherFactory.java:136)
        at org.gradle.initialization.DefaultGradleLauncherFactory.newInstance(DefaultGradleLauncherFactory.java:81)
        at org.gradle.composite.internal.DefaultRootBuildState.<init>(DefaultRootBuildState.java:45)
        at org.gradle.composite.internal.DefaultIncludedBuildRegistry.createRootBuild(DefaultIncludedBuildRegistry.java:85)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:45)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:31)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:42)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:28)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(Continuou
....................
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.internal.service.ServiceLookupException: Could not configure services using GradleScopeCompileServices.configure().
        at org.gradle.internal.service.DefaultServiceRegistry.applyConfigureMethod(DefaultServiceRegistry.java:194)
        at org.gradle.internal.service.DefaultServiceRegistry.findProviderMethods(DefaultServiceRegistry.java:170)
        at org.gradle.internal.service.DefaultServiceRegistry.addProvider(DefaultServiceRegistry.java:244)
        at org.gradle.internal.service.DefaultServiceRegistry$1.addProvider(DefaultServiceRegistry.java:225)
        at org.gradle.api.internal.tasks.CompileServices.registerGradleServices(CompileServices.java:39)
        at org.gradle.internal.service.scopes.GradleScopeServices$1.execute(GradleScopeServices.java:117)
        at org.gradle.internal.service.scopes.GradleScopeServices$1.execute(GradleScopeServices.java:114)
        at org.gradle.internal.service.DefaultServiceRegistry.register(DefaultServiceRegistry.java:205)
        at org.gradle.internal.service.scopes.GradleScopeServices.<init>(GradleScopeServices.java:114)
        at org.gradle.internal.service.scopes.BuildScopeServiceRegistryFactory.createFor(BuildScopeServiceRegistryFactory.java:36)
        at org.gradle.invocation.DefaultGradle.<init>(DefaultGradle.java:88)
        at org.gradle.invocation.DefaultGradle_Decorated.<init>(Unknown Source)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:51)
        ... 52 more
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$PlatformClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$PlatformClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at org.gradle.initialization.DefaultJdkToolsInitializer.initializeJdkTools(DefaultJdkToolsInitializer.java:40)
        at org.gradle.api.internal.tasks.CompileServices$GradleScopeCompileServices.configure(CompileServices.java:50)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.internal.service.ReflectionBasedServiceMethod.invoke(ReflectionBasedServiceMethod.java:35)
        at org.gradle.internal.service.DefaultServiceRegistry.applyConfigureMethod(DefaultServiceRegistry.java:192)
        ... 67 more


* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

### Context

I am trying to setup a new project with latest Java and Gradle. I am running this in Mac 10.14.2 (18C54). With Java 11:
```
➜  test java -version
java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
```
And Gradle 5.1:
```
➜  test gradle -version

------------------------------------------------------------
Gradle 5.1
------------------------------------------------------------

Build time:   2019-01-02 18:57:47 UTC
Revision:     d09c2e354576ac41078c322815cc6db2b66d976e

Kotlin DSL:   1.1.0
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.1 (Oracle Corporation 11.0.1+13-LTS)
OS:           Mac OS X 10.14.2 x86_64

```

### Steps to Reproduce (for bugs)

I can't provide a project because I am not able to create one.
Steps:
1. create a new folder and change into it.
2. run `gradle init --type java-library`
### Your Environment

 * Build scan URL: 
I don't have a build scan url.
Mac 10.14.2 (18C54). With Java 11:
```
➜  test java -version
java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
```
And Gradle 5.1:
```
➜  test gradle -version

------------------------------------------------------------
Gradle 5.1
------------------------------------------------------------

Build time:   2019-01-02 18:57:47 UTC
Revision:     d09c2e354576ac41078c322815cc6db2b66d976e

Kotlin DSL:   1.1.0
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.1 (Oracle Corporation 11.0.1+13-LTS)
OS:           Mac OS X 10.14.2 x86_64

```
### Extra Information
Base on the stacktrace, this class `https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/initialization/DefaultJdkToolsInitializer.java` is doing a cast onto `URLClassLoader` on line 40.

According to [CodeFX](https://blog.codefx.org/java/java-11-migration-guide/#Casting-To-URL-Class-Loader) this is not compatible with Java 11.

**Comment by big-guy** [comment]
Hmm, something funky is going on here.  I have the same version of Java and don't see this failure on macOS.

That particular line shouldn't be executed with JDK 11 because JDK 9 and above no longer have a tools.jar.  Could you check if you somehow have a tools.jar in your JDK 11 installation?

**Comment by michaelwan** [comment]
Switched to another mac and installed JDK11 and gradle 5, not seeing this issue. Should be something with the particular mac.

**Comment by imnickvaughn** [comment]
getting this same problem

**Comment by dc0614** [comment]
@imnickvaughn Not sure if it matters to you anymore. But I was having the same issue for a week now when importing a new project. Found my version of Java 11 does include the tools.jar, I deleted and now gradle is building but running into another issue. Not sure if its specific to me removing tools.jar or not. But just thought I'd provide a possible solution for those still facing the issue.
