### ISSUE TITLE
Android nested build problem

### ISSUE THREAD

**Issue by MrshaoGx** [gradle/gradle#8208]
### Expected Behavior

Nested build, depends status : A -> B -> C
```
A: Android application
B: Android Library
C: Android Library
```
The `assembleRelease` work properly , and generated a new apk, seems can not run on my android device.
### Current Behavior

Here is the problem:
##### When i try to run the APK on my android device after run  `./gradlew assembleRelease`.

The error was throwed:
```java
     E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ua/mylib/TestB;
01-10 21:40:17.562 16203 16203 E AndroidRuntime: 	at com.ua.myapplication.MainActivity.onCreate(MainActivity.java:29)
01-10 21:40:17.562 16203 16203 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6706)
01-10 21:40:17.562 16203 16203 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
01-10 21:40:17.562 16203 16203 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
01-10 21:40:17.562 16203 16203 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
01-10 21:40:17.562 16203 16203 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
01-10 21:40:17.562 16203 16203 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
01-10 21:40:17.562 16203 16203 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-10 21:40:17.562 16203 16203 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-10 21:40:17.562 16203 16203 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
01-10 21:40:17.562 16203 16203 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-10 21:40:17.562 16203 16203 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
01-10 21:40:17.562 16203 16203 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:792)

```
 
### Context

Here is my build config.
Application settings.gradle:
```
 include ':app'
includeBuild('../MultiModuleLib'){
    dependencySubstitution {
        substitute module('com.ua.mylib:mylib') with project(':mylib')
    }
}
```
B settings.gradle:
```
includeBuild('../TestLib') {
    dependencySubstitution {
        substitute module('com.ua1.mylib:mylib') with project(':mylib')
    }
}
```
C doesn't have settings.gradle.

----
Module app's build.gradle
```
apply plugin: 'com.android.library'
android {
    compileSdkVersion 25
    buildToolsVersion '26.0.2'

    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 25
        versionCode 1
        versionName "1.0.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}
dependencies {
    ...
   api  ':B'
   ...
}
```
B's build.gradle
```
apply plugin: 'com.android.library'
android {
    compileSdkVersion 25
    buildToolsVersion '26.0.2'

    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 25
        versionCode 1
        versionName "1.0.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}
dependencies {
    ...
   api  ':C'
   ...
}
```
C doesn't have any dependencies  and have the same `android` tag as above. 

### Steps to Reproduce (for bugs)

And when i decompiled whole apk file that i find out the **B's classes** (except R.class) didn't compile into the dex file. 

### Your Environment

 * Build scan URL: 
Project type: Android. 
Gradle version: 4.10.3
Android Gradle Plugin: 3.1.0
Java version: 1.8.0 openJDK

Should i changed the jdk version?  the only gradle version i can use is 4.10.3. because the 5.1 have some compatible problems.

**Comment by AeDDD** [comment]
I am struggling with the same problem.. emergency pls !!!

**Comment by MrshaoGx** [comment]
## Attention: problem seems resovled

Problem from android gradle pulgin : https://issuetracker.google.com/issues?q=composite%20build
