### ISSUE TITLE
Gradle still fails with "Transformation hasn't been executed yet"

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#8250]
### Environment
Gradle 5.1.1

### Context
Extracted from https://github.com/gradle/gradle/issues/7950#issuecomment-454728517

### Steps to Reproduce
Use the sample project at https://github.com/gradle/gradle/issues/7950#issuecomment-454728517

Run `./gradlew clean :app:generateDebugSources :app:compileDebugSources --stacktrace`, the build fails with:

```
java.lang.IllegalStateException: Transformation hasn't been executed yet
        at org.gradle.api.internal.artifacts.transform.TransformationNode.getTransformedSubject(TransformationNode.java:67)
        at org.gradle.api.internal.artifacts.transform.TransformationNode.access$400(TransformationNode.java:39)
        at org.gradle.api.internal.artifacts.transform.TransformationNode$ChainedTransformationNode$1.describeSubject(TransformationNode.java:179)
        at org.gradle.api.internal.artifacts.transform.TransformationNode$ArtifactTransformationStepBuildOperation.description(TransformationNode.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.artifacts.transform.TransformationNode$ChainedTransformationNode.execute(TransformationNode.java:170)
        at org.gradle.api.internal.artifacts.transform.TransformationNodeExecutor.execute(TransformationNodeExecutor.java:37)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
```

### Expected Behavior
The root cause should be shown instead of the current message.

**Comment by wolfs** [comment]
Thank you for reporting. When the error happens, that means that something is wrong with our scheduling. I slighty changed the error message in #8274, so it would now show:
```
FAILURE: Build failed with an exception.

* What went wrong:
Transformation JetifyTransform has been scheduled and is now required, but did not execute, yet.
```

Is that good enough already? What other information would you expect?

**Comment by hungvietnguyen** [comment]
(Sorry, I was going to comment earlier.)

cc: @carlonzo

Ideally this bug should be resolved in the same way that https://github.com/gradle/gradle/issues/7950 was resolved: The root cause (why "transformation hasn't been executed yet") is shown to the user, so the user has some idea where the error comes from.

With the current message "transformation hasn't been executed yet" and even with your revised wording above, the user still has no idea what went wrong, and it will require more back-and-forth triaging between Gradle and the plugins to debug the issue.

That said, I also understand that this stacktrace is different from the one in https://github.com/gradle/gradle/issues/7950, and more debug info may not be available.

If you think this is the best debug info Gradle can give to users, then let's use that, but if there is more info available, please add it (after all, it's Gradle and plugin authors who will receive these bug reports right).

**Comment by wolfs** [comment]
@hungvietnguyen When the exception you have been seeing happens, we don't have much context except for knowing that something went wrong with scheduling and which transform type we try to execute. I the transform itself fails, the reporting is better.

**Comment by hungvietnguyen** [comment]
Yeah, I also guess that Gradle will unlikely run into this exception again now that the root cause of the exception has been fixed: https://github.com/gradle/gradle/issues/8253

**Comment by arundharmar** [comment]
I am seeing this error. Unfortunately the project i am on is not in latest gradle yet and there is no plans for upgrading gradle in anytime soon. Is there any other way to find out why it is failing? I am trying to import this dependency and fails only when I do that. I am in Gradle 4.10.3

`compile (group: 'com.aventstack', name: 'extentreports', version: 5.0.1) {}`

This seems to be working fine for newer gradle projects. But I am receiving the following error in this version(4.10.3). Any help in identifying the root cause would be helpful.
```* Exception is:
java.lang.IllegalStateException: Transformation hasn't been executed yet
        at org.gradle.api.internal.artifacts.transform.TransformInfo.getFailure(TransformInfo.java:88)
        at org.gradle.api.internal.artifacts.transform.TransformInfo.access$300(TransformInfo.java:48)
        at org.gradle.api.internal.artifacts.transform.TransformInfo$ChainedTransformInfo$ChainedArtifactTransformStepOperation.run(TransformInfo.java:235)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.artifacts.transform.TransformInfo$ChainedTransformInfo.execute(TransformInfo.java:217)
        at org.gradle.api.internal.artifacts.transform.TransformInfoExecutor.execute(TransformInfoExecutor.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
```
