### ISSUE TITLE
Possible concurrency issue with artifact transforms

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#8253]
### Environment
Gradle 5.1.1

### Context
Extracted from https://github.com/gradle/gradle/issues/7950#issuecomment-454728517

### Steps to Reproduce
1. Use the sample project at https://github.com/gradle/gradle/issues/7950#issuecomment-454728517

2. Run `./gradlew clean :app:generateDebugSources :app:compileDebugSources --stacktrace`, the build fails with:

```
java.lang.IllegalStateException: Transformation hasn't been executed yet
        at org.gradle.api.internal.artifacts.transform.TransformationNode.getTransformedSubject(TransformationNode.java:67)
        at org.gradle.api.internal.artifacts.transform.TransformationNode.access$400(TransformationNode.java:39)
        at org.gradle.api.internal.artifacts.transform.TransformationNode$ChainedTransformationNode$1.describeSubject(TransformationNode.java:179)
        at org.gradle.api.internal.artifacts.transform.TransformationNode$ArtifactTransformationStepBuildOperation.description(TransformationNode.java:200)
```

3. Run `./gradlew clean :app:generateDebugSources :app:compileDebugSources --stacktrace --max-workers=1` (adding `--max-workers=1`), the build succeeds. This suggests that there may be a concurrency issue with the transforms.

### Expected Behavior
Transforms should produce consistent results regardless of the number of Gradle workers.

**Comment by wolfs** [comment]
@hungvietnguyen Thank you for reporting and the reproducible example. This turned out to be caused by a bug in our work scheduling algorithm, when finalizers are involved. It didn't show up when executing the with only one worker, since the transformation then was executed only after the task which was finalized, causing the right dependencies to be required.

This should be fixed by https://github.com/gradle/gradle/pull/8274 and will be part of Gradle 5.2.

**Comment by hungvietnguyen** [comment]
Thank you for the quick fix! Also, I'd like to pass all the credits to @carlonzo! :)
