### ISSUE TITLE
Gradle 5.1.1 does not retry connection resets

### ISSUE THREAD

**Issue by jurriaan** [gradle/gradle#8264]
### Expected Behavior

On a connection reset Gradle retries to fetch the dependencies again on 'Connection reset' errors.

### Current Behavior
```
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all artifacts for configuration ':app:classpath'.
   > Could not download gradle.jar (io.fabric.tools:gradle:1.27.0)
      > Could not get resource 'http://artifactory-artifactory/artifactory/blendle/io/fabric/tools/gradle/1.27.0/gradle-1.27.0.jar'.
         > Connection reset
```

### Context

We have a network that sometimes produces these connection resets (which should be fixed on our side), but we thought that upgrading to Gradle 5.1.1 would help resolve most cases of this since #4547 is closed now.

### Steps to Reproduce (for bugs)

This is reproducible by having a flaky network that sometimes resets the connection.

### Your Environment

Gradle 5.1.1 running on Jenkins 2.160 in Kubernetes 1.10.4

**Comment by SDC2021** [comment]
I'm behind a corp proxy and can confirm this behavior. 

Even with the settings beneath, some of my builds are failing because of a `Connection reset`...

```
systemProp.org.gradle.internal.http.connectionTimeout=120000
systemProp.org.gradle.internal.http.socketTimeout=120000
 # the number of retries (initial included) (default 3)
systemProp.gradle.internal.repository.max.retries=20"
 # the initial time before retrying, in milliseconds (default 125)
systemProp.gradle.internal.repository.initial.backoff=500
```

**Comment by tomrom95** [comment]
@jurriaan @SDC2021 any update on solving this? My project is running into the same exact issues

**Comment by ljacomet** [comment]
If someone suffering from this issue could provide a build scan, that would be awesome. 
If that's not possible, a full exception stack trace when the problem occurs would be also welcome.

**Comment by tomrom95** [comment]
@ljacomet here is a stack trace, though it doesn't reveal much information - https://gist.github.com/tomrom95/f5a9eb2d10d34ff7dd01087c7475882e . I will try to provide full debug logs from the rest of the build, but I need to scrub confidential information from it.

**Comment by tomrom95** [comment]
@ljacomet additionally, locally I see some weirdness with the `org.gradle.internal.repository.max.retries` and `org.gradle.internal.repository.initial.backoff` properties. I tried setting each one to invalid values so that I would at least know that gradle is reading them. When I run `./gradlew  -Dorg.gradle.internal.repository.max.tentatives=-1 test`, the build fails as expected. When I run `./gradlew  -Dorg.gradle.internal.repository.initial.backoff=-1 test`, the build proceeds as normal, which seems to suggest that gradle isn't reading this property (or it isn't reading it correctly).

**Comment by ljacomet** [comment]
Thanks for the stack trace. So the issue is that initially when that dependency download retry feature was introduced, Gradle would retry way too often and, combined with repos having weird return codes, it caused issues like #7850.
So Gradle intentionally limited the cases where a retry was performed.
And it looks like a connection reset is not covered in [this code](https://github.com/gradle/gradle/blob/5d65d0b0a91aa50bd03af62b21d4c05d19f876cb/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/ErrorHandlingModuleComponentRepository.java#L280) as it appears as a simple `SocketException`.

**Comment by tomrom95** [comment]
@ljacomet since we get connection reset errors so often with `dl.google.com`, is there any way to adjust our gradle properties to retry more often on connection reset issues?

This is becoming a big flakiness issue in our CI system

**Comment by ljacomet** [comment]
Right now, no. Because as I said in my previous comment Gradle will _not_ retry on a simple `SocketException` which is the way a connection reset appears.

The code I linked above would need to be patched to handle connection reset and maybe other variations of a `SocketException` or maybe all of them.

However further work on this is not planned for the near future.

**Comment by AndreaGiardini** [comment]
Is adding something like `failure.getMessage().contains("Connection Reset")` an option?

**Comment by melix** [comment]
This is extremely weak. We don't know how stable this message is, or even if it's the same between JDKs or different vendor implementations

**Comment by tomrom95** [comment]
@ljacomet We've found that the connection reset issues are because of rate limiting on dl.google.com. We are sending around 300 requests/second during dependency resolution in our builds, and rate limit errors produce SocketExceptions. With no way to retry on a SocketException, is there a way to limit the speed of dependency resolution with some gradle option?

**Comment by melix** [comment]
300 requests/second is a lot, especially knowing that Gradle caches artifacts. Can you tell us more about your setup? In any case no there's no way to _slow down_ resolution (funny because people usually ask it to be faster, not slower ;)). You might want to consider having a local mirror to avoid rate limiting.

**Comment by tomrom95** [comment]
@melix Sorry, removed my previous comment because we found the right configuration right away.

Our setup is a CI server that runs some pretty large bazel-based builds. Because of some of the memory requirements of these builds and their tests, our server has 32 cores. This works well for Bazel builds. However, Gradle by default sets the number of parallel workers to the number of processors on the machine. So, Gradle was running 32 parallel dependency resolution threads, resulting in the extremely high request/second rate.

We now found that we can use the `max-workers` option when running gradle to limit the parallel resolvers. So, we run `./gradlew --max-workers=4 androidDependencies` to get around rate limit issues and then `./gradlew test` to run tests.

**Comment by learnerEvermore** [comment]
I don't have the solution for this but I did find a "partial mitigation". I did multiple things:

 1. I **_reduced_** the timeouts (to 5-10) seconds to account for the possibility that the misbehaving server or network appliance resets connections after some period of inactivity. This aims to have Gradle retry it as a timeout before it becomes a connection reset that Gradle cannot handle (yet).
 2. I increased the number of retries to account for short timeouts.
 3. To try to simulate retries even in case of resets I declared every repository multiple times. In fact I made this configurable (loop). The downside is that even "not founds" (404s) will be retried: `Integer.getInteger('repo.multiplication', 1).times { maven { name "someRepoId.${it}"; url 'https://some.repo.url' } }`

**Comment by melix** [comment]
There are now more options. If you hit rate limitations, it's likely you're reaching remote repositories again and again for the same dependencies. It's also likely that you're hitting remote repositories for dependencies you know wouldn't be found there.

There are a couple options for both use cases:

1. use a [shared dependency cache](https://docs.gradle.org/6.2.2/userguide/dependency_resolution.html#sub:ephemeral-ci-cache) to avoid re-downloading dependencies
2. use [repository content filtering](https://docs.gradle.org/6.2.2/userguide/declaring_repositories.html#sec:repository-content-filtering) to avoid hammering remote repositories with requests they won't handle

**Comment by learnerEvermore** [comment]
@melix: In my case we already have caching strategies in place and one/first repo will handle 99% of requests but we could optimize our caching.

Is there a way run gradle build to "seed" the shared dependency cache that is better than running essentially all tasks? That is - is it possible to run "dependency resolution" only and not actual tasks, a sort of extended "dry run"?

**Comment by medb** [comment]
Is it possible to add a property for Gradle to retry all exceptions during download? I understand that in some environments it leads to longer builds, but in other environments it will allow to avoid such hacks: https://github.com/grpc/grpc/issues/18892

Having an option to retry all exceptions will allow users to configure their build in the way that suits their environment best.

**Comment by MorganGeek** [comment]
We faced similar issue for a long time in our Jenkins Build ecosystem, whereas our dynamic jenkins agents, created from EC2 AMIs machine templates, would fail build with what looked like random Connection Reset issues when Gradle (v5.5, v6.3, ...) resolved some dependencies (I say some because it was often the same ones) from SonaType Nexus (v3.x) and we couldn't reproduce those issues locally. 

Anyway, after long running investigations, which led us to be suspicious about our NAT Gateway, we have simply avoided the problem at all by updating our AMI's + Jenkins agents EC2 templates with following changes to defeat the timeout / connection reset issue which was impacting almost 4% of our builds.

```
sudo sysctl -w net.ipv4.tcp_keepalive_time=180
sudo sysctl -w net.ipv4.tcp_keepalive_intvl=60
```

If you face similar issues, it might help at least, I hope. See also https://issues.jenkins-ci.org/browse/JENKINS-54317

**Comment by melix** [comment]
> Is it possible to add a property for Gradle to retry all exceptions during download?

We should very much avoid doing this. You certainly don't want to retry on some exceptions (NPE, OOM, or even other exceptions that we don't _know about_). The cure could be worse than the illness and Gradle could start hammering remote repositories retrying.

Instead we would encourage you to fix the infrastructure.

**Comment by medb** [comment]
@melix agree, I meant to say retry all SocketExceptions (https://github.com/gradle/gradle/issues/8264#issuecomment-470675055).

Regarding fixing infrastructure, in our multi-hours build we use multiple tools to download dependencies - wget, curl, sbt, Ant, Ivy, Maven and Gradle. And only Gradle can not handle `Connection Reset` exceptions and it causes virtually all build flakiness, even though it handles only 5-10% of the build, so I think the are a real issue with Gadle, not infrastructure (whole build runs on the same infrastructure).

Both, `curl` and `wget` have `--retry-connrefused` flag to retry some uncommon responses if necessary, it seems reasonable to ask Gradle to support a special option that allows to retry `SocketException` to improve user experience.

**Comment by melix** [comment]
I understand, but it's not _just_ a matter of retrying. It's also about correctness and reproducibility of the builds. We cannot really retry all exceptions without knowing what they _mean_. The real issue is that a "connection reset" is not strongly typed, and it's only the text of the error message which lets us know that we could retry.

We haven't done it because it's extremely weak. We _could_ add something here to check the message: https://github.com/gradle/gradle/blob/99728e5c97f10d2203ebef01e5c6d01771f87d48/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/transport/NetworkingIssueVerifier.java#L37

But I'm not super comfortable with this...

**Comment by medb** [comment]
Correct me if I'm wrong but my understanding is that Gradle 5.0 introduced retries to all (?) IOExceptions/SocketExceptions but it lead to increased build time in some environments (https://github.com/gradle/gradle/issues/7850) and that's why it was partially (?) reverted in https://github.com/gradle/gradle/pull/7864.

I assume that Gradle 5.0 retry behavior didn't suffer from the correctness and reproducibility issues.

So it seems like there are 2 use-cases:
1. interactive or time-sensitive builds in which excessive retries can significantly increase build time
2. long-running or reliability-sensitive builds in which build time almost doesn't matter and additional retries can increase stability and reliability of the build.

Current Gradle retry behavior addresses 1st use case, but not 2nd. And it looks like 2nd use case was addressed better with retry mechanism introduced in Gradle 5.0.

That's why I think that both use cases could be addressed reasonably well by introducing a flag that restores Gradle 5.0 retry behavior that will allow users to use it in 2nd use case when build time doesn't matter. I assumed that in Gradle 5.0 it was retrying all IOExceptions or SockerExceptions.

**Comment by melix** [comment]
The revert was done because capturing widely exceptions caused some errors to be misinterpreted as networking issues, while they were not (e.g, a 403). Depending on the error code, because Gradle interprets the error codes either as misses or errors, it _can_ lead to non-reproducible builds, but I agree this is not the pb you're trying to solve.

The pb with introducing such a flag "restoring" this behavior is that it was _wrong_. Errors _need_ to be interpreted to take the right decision, and typically not retry if it's a 403. It was a bug.

**Comment by medb** [comment]
Thank you for clarification, in this case seems like Gradle 5.0 retries were too broad, because HTTP 403 responses are not thrown as SocketExceptions.

Coming back to retrying all SocketExceptions, are there any examples of SocketExceptions that should not be retried? Judging from the [javadoc](https://docs.oracle.com/javase/8/docs/api/java/net/SocketException.html) it seems like it should be safe to retry all of them:
> Thrown to indicate that there is an error creating or accessing a Socket.

**Comment by melix** [comment]
It _looks_ like it would be safe. Unfortunately as far as I can tell, "connection reset" is not a `SocketException`. Is it?

**Comment by medb** [comment]
Yes, in my build failures the root cause is a `SoketException` (`java.net.SocketException: Connection reset`):
```
* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project '<REDACTED>'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:227)
	at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:232)
	at org.gradle.configuration.BuildOperationScriptPlugin$1$1.run(BuildOperationScriptPlugin.java:69)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)

. . .

Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'http://maven-central.storage-download.googleapis.com/maven2/org/apache/hive/hcatalog/hive-hcatalog-core/1.2.1/hive-hcatalog-core-1.2.1.jar'.
	at org.gradle.internal.resource.ResourceExceptions.failure(ResourceExceptions.java:74)
	at org.gradle.internal.resource.ResourceExceptions.getFailed(ResourceExceptions.java:57)
	at org.gradle.internal.resource.transfer.AccessorBackedExternalResource.withContentIfPresent(AccessorBackedExternalResource.java:146)
	at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$11.call(BuildOperationFiringExternalResourceDecorator.java:237)
	at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$11.call(BuildOperationFiringExternalResourceDecorator.java:229)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator.withContentIfPresent(BuildOperationFiringExternalResourceDecorator.java:229)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.copyToCache(DefaultCacheAwareExternalResourceAccessor.java:201)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.access$300(DefaultCacheAwareExternalResourceAccessor.java:55)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor$1.get(DefaultCacheAwareExternalResourceAccessor.java:90)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor$1.get(DefaultCacheAwareExternalResourceAccessor.java:82)
	at org.gradle.cache.internal.ProducerGuard$AdaptiveProducerGuard.guardByKey(ProducerGuard.java:97)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.getResource(DefaultCacheAwareExternalResourceAccessor.java:82)
	at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.downloadByCoords(DefaultExternalResourceArtifactResolver.java:135)
	at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.downloadStaticResource(DefaultExternalResourceArtifactResolver.java:99)
	at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.resolveArtifact(DefaultExternalResourceArtifactResolver.java:67)
	at org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver$RemoteRepositoryAccess.resolveArtifact(ExternalResourceResolver.java:483)
	... 27 more
Caused by: java.net.SocketException: Connection reset
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:198)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at org.gradle.internal.resource.transfer.AbstractProgressLoggingHandler$ProgressLoggingInputStream.read(AbstractProgressLoggingHandler.java:77)
	at com.google.common.io.CountingInputStream.read(CountingInputStream.java:63)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2314)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2270)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2291)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor$DownloadAction.execute(DefaultCacheAwareExternalResourceAccessor.java:252)
	at org.gradle.internal.resource.transfer.AccessorBackedExternalResource.withContentIfPresent(AccessorBackedExternalResource.java:137)
	... 47 more
```

**Comment by melix** [comment]
Interesting! So it would be a good option to add this one to the list of exceptions we catch. Would you be open to writing a PR for this? I'm not sure I'd be the reviewer but it looks interesting.

**Comment by medb** [comment]
Sure, send #13144 PR to add retries for SocketExceptions

**Comment by wraschke** [comment]
@medb why are you removing `org.apache.http.conn.HttpHostConnectException` from the conditional statement in `isLikelyTransientNetworkingIssue`?

**Comment by medb** [comment]
@wraschke Because `org.apache.http.conn.HttpHostConnectException` it extends `SocketException`: https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/conn/HttpHostConnectException.html
