### ISSUE TITLE
Tooling API throws StreamCorruptedException model loaded from faulty project with different Java

### ISSUE THREAD

**Issue by donat** [gradle/gradle#8285]
### Expected Behavior

The Tooling API model loading should always contain the exception when evaluating the build script throws an exception.

### Current Behavior

If a project has the following `build.gradle` file:

    apply plugin: 'java'
    apply plugin: 'eclipse'
    eclipse.classpath.file.whenMerged { cp -> throw new NullPointerException()}

And the Tooling API is configured to use a different Java version:

    File location = new File("/path/to/project");
    File javaHome = new File("/path/to/java/8");

    try (ProjectConnection connection = GradleConnector.newConnector().forProjectDirectory(location).connect()) {
        connection.model(EclipseProject.class).setJavaHome(javaHome).get();
    }

Then the execution with Java 9 fails with the following stacktrace:
```
Exception in thread "main" org.gradle.tooling.GradleConnectionException: Could not fetch model of type 'EclipseProject' using Gradle distribution 'https://services.gradle.org/distributions/gradle-5.0-bin.zip'.
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:55)
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:41)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:844)
	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
	at org.gradle.tooling.internal.consumer.DefaultModelBuilder.get(DefaultModelBuilder.java:50)
	at example.Main.main(Main.java:16)
Caused by: org.gradle.api.UncheckedIOException: java.io.StreamCorruptedException: invalid type code: 00
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:60)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
	at org.gradle.tooling.internal.provider.serialization.PayloadSerializer.deserialize(PayloadSerializer.java:66)
	at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:181)
	at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:122)
	at org.gradle.tooling.internal.provider.DefaultConnection.getModel(DefaultConnection.java:193)
	at org.gradle.tooling.internal.consumer.connection.CancellableModelBuilderBackedModelProducer.produceModel(CancellableModelBuilderBackedModelProducer.java:53)
	at org.gradle.tooling.internal.consumer.connection.PluginClasspathInjectionSupportedCheckModelProducer.produceModel(PluginClasspathInjectionSupportedCheckModelProducer.java:41)
	at org.gradle.tooling.internal.consumer.connection.AbstractConsumerConnection.run(AbstractConsumerConnection.java:59)
	at org.gradle.tooling.internal.consumer.connection.ParameterValidatingConsumerConnection.run(ParameterValidatingConsumerConnection.java:47)
	at org.gradle.tooling.internal.consumer.DefaultModelBuilder$1.run(DefaultModelBuilder.java:60)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:84)
	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.io.StreamCorruptedException: invalid type code: 00
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1613)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2346)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2240)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2078)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1585)
	at java.base/java.io.ObjectInputStream.readArray(ObjectInputStream.java:1984)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1579)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2346)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2240)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2078)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1585)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at org.gradle.tooling.internal.provider.serialization.PayloadSerializer.deserialize(PayloadSerializer.java:64)
	... 19 more
```

### Context

https://github.com/eclipse/buildship/issues/837

### Steps to Reproduce (for bugs)

[Sample project](https://github.com/gradle/gradle/files/2779244/gradle-corrupted-stream-demo.zip) (open in Eclipse)

**Comment by eskatos** [comment]
The same was observed while debugging IntelliJ Kotlin DSL script dependencies resolver issues. It added a level of troubleshooting pain. See https://youtrack.jetbrains.com/issue/KT-30974#focus=streamItem-27-3475548.0-0

**Comment by Vampire** [comment]
I'm getting the same exception with Java 8 in IJ 2019.2.1 with Gradle 5.4.1 here.
The build itself is fine, it works properly.
The `Build` tool window also shows that the project is green on doing Gradle import.
But the kts shows the red bar that the resolution failed and the resolver log that exception.

**Comment by nskvortsov** [comment]
@Tapchicoma do you have a reproducer for it?

**Comment by tbroyer** [comment]
Fwiw, just hit this in gradle-errorprone-plugin: Gradle 8.10.2 with JDK 21, using TestKit to run tests in Gradle 6.8 with JDK 8 ([github actions](https://github.com/tbroyer/gradle-errorprone-plugin/actions/runs/11498572564/job/32004807006), [build scan](https://scans.gradle.com/s/2wepudq4h4sng))

Other combinations run OK though:
* Tests using Gradle 8.10.2 with JDK 8 ([github actions](https://github.com/tbroyer/gradle-errorprone-plugin/actions/runs/11498572564/job/32004801184), [build scan](https://scans.gradle.com/s/b4clzb7jtj6ic))
* Tests using Gradle 6.8 with JDK 11 ([github actions](https://github.com/tbroyer/gradle-errorprone-plugin/actions/runs/11497889727/job/32002741630), [build scan](https://scans.gradle.com/s/5kps3ssdzbobc))

As pointed above, it seems to only happen when the build fails (and in my case is expected to fail).
