### ISSUE TITLE
Gradle 3.1 and Gretty with Jetty Artifacts

### ISSUE THREAD

**Issue by JimHolladay** [gradle/gradle#829]
I am adding gretty to a build file so that I can run the application on a local machine and I am getting a deprecation warning on gradle 2.14 and a build failure on gradle 3.1.

`> Cannot change strategy of configuration ':overlays' after it has been resolved.`

Any help with an explanation or solution to the issue would be appreciated as I am a novice. 
Thanks in advance.

Here is the buildscan link:
https://scans.gradle.com/s/hpklrbrwvf5ky/failure

Here is the build file pared down to help with reproducing the issue:

```groovey
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'org.akhikhl.gretty:gretty:1.4.0'
    }
}

apply plugin: 'java'
apply plugin: 'maven'
apply plugin: 'org.akhikhl.gretty'

version = '2'
archivesBaseName = 'service'

compileJava {
    sourceCompatibility = 1.8
    targetCompatibility = 1.8
}

configurations {
    overlays
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    overlays 'org.eclipse.jetty:jetty-distribution:9.3.9.v20160517@zip'
}

task overlayJetty(type: Copy) {
    def bundleRoot = 'build/bundle/project-' + project.version + '-bundle'
    def jettySrc = configurations.overlays.find {
        it.absolutePath.contains('jetty')
    }
    from zipTree(jettySrc)
    into bundleRoot
    includeEmptyDirs false
    exclude('**/README.TXT')
    exclude('**/VERSION.txt')
    exclude('**/license-eplv10-aslv20.html')
    exclude('**/notice.html')
    exclude('**/demo-base/**')
    exclude('**/webapps/**')
    exclude('**/start.ini')
    eachFile {
        def path = it.relativePath.pathString
        path = path.replaceFirst('jetty-distribution-9.3.9.v20160517/', '')
        it.setRelativePath(RelativePath.parse(it.relativePath.isFile(), path))
    }
}

task archiveBundle(type: Zip, dependsOn: overlayJetty) {
    from 'build/bundle'
    archiveName 'stream-service-' + project.version + '-bundle.zip'
}

task bundle(dependsOn: archiveBundle)
```

Here is the Exception:

```* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'service'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:79)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:74)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:573)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:125)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
	at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:151)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:148)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:33)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:112)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:92)
	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:79)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:51)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:59)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.HintGCAfterBuild.execute(HintGCAfterBuild.java:44)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:293)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.api.InvalidUserDataException: Cannot change strategy of configuration ':overlays' after it has been resolved.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.validateMutation(DefaultConfiguration.java:631)
	at org.gradle.api.internal.artifacts.ivyservice.resolutionstrategy.DefaultResolutionStrategy.eachDependency(DefaultResolutionStrategy.java:111)
	at org.gradle.api.internal.artifacts.ivyservice.resolutionstrategy.DefaultResolutionStrategy_Decorated.eachDependency(Unknown Source)
	at org.gradle.api.internal.artifacts.ivyservice.resolutionstrategy.DefaultResolutionStrategy_Decorated$eachDependency.call(Unknown Source)
	at org.akhikhl.gretty.SpringBootResolutionStrategy$_resolveDependencyVersions_closure3.doCall(SpringBootResolutionStrategy.groovy:82)
	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
	at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:117)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:122)
	at org.gradle.api.DomainObjectCollection$all.call(Unknown Source)
	at org.akhikhl.gretty.SpringBootResolutionStrategy.resolveDependencyVersions(SpringBootResolutionStrategy.groovy:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:151)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:206)
	at org.akhikhl.gretty.SpringBootResolutionStrategy.apply(SpringBootResolutionStrategy.groovy:30)
	at org.akhikhl.gretty.SpringBootResolutionStrategy$apply.call(Unknown Source)
	at org.akhikhl.gretty.GrettyPlugin.addConfigurationsAfterEvaluate(GrettyPlugin.groovy:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at org.akhikhl.gretty.GrettyPlugin.afterProjectEvaluate(GrettyPlugin.groovy:695)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at org.akhikhl.gretty.GrettyPlugin$_apply_closure63$_closure114.doCall(GrettyPlugin.groovy:799)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy15.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
	... 55 more```

**Comment by bmuschko** [comment]
Could you please provide the stack trace for the build failure you see with 3.1?

**Comment by bmuschko** [comment]
The error message you are seeing is unrelated to the Gretty plugin. You are iterating over the configuration during configuration time. You'll need to defer that to a later time. Try the following:

    task overlayJetty(type: Copy) {
        from { zipTree(configurations.overlays.find {
            it.absolutePath.contains('jetty')
        }) }
}

**Comment by JimHolladay** [comment]
That absolutely worked!  Thank you very much.

**Comment by jonatanloya** [comment]
Hi JimHolladay, I am having same issue, can you tell me how do you fixed that?

This is my build.gradle



plugins {
  id "org.akhikhl.gretty" version "1.4.0"
}

description = 'O&D REST Services'

allprojects {

    apply plugin: 'java'
    apply plugin: 'maven'

    configurations {
        buildScripts
    }

    repositories {
        maven {
            url 'http://pros-maven:8888/artifactory/repo'
        }
        mavenLocal()
    }

    dependencies {
        compile ('org.hibernate:hibernate-core:4.1.7.Final') { force = true }
        compile ('org.hibernate:hibernate-entitymanager:4.1.7.Final') { force = true }
     
        buildScripts 'rms.services:system-services:1.0-SNAPSHOT:build@zip'
        testCompile 'com.prosrm.rms.services:system-services-testsupport:0.8'
    }

    copy {
        configurations.buildScripts.each {
            from zipTree(it)
        }
        into 'gradle/plugins'
    }
	
    compileJava.options.compilerArgs << '-Xlint:unchecked' << '-Xlint:deprecation'

}

subprojects {
  
    project.ext.baseVersion = version
    project.ext.rootVersion = getRootProject().version

    if (!project.hasProperty('isRelease') || !isRelease.toBoolean()) {
        version += '-SNAPSHOT'
        rootVersion += '-SNAPSHOT'
    }

    configurations {
        testSchema
    }

    dependencies {
        testSchema "com.prosrm.oandd:oandd:5.28.0-SNAPSHOT:schema@zip"
    }

    task copyDeploy(type: Copy) {
        from 'src/deploy'
        into 'build'
    }

    compileJava.dependsOn 'copyDeploy'

    task zipDeploy(type: Zip) {
        from 'src/deploy'
    }

    artifacts {
        archives jar
    }
    
    uploadArchives {
        repositories.mavenDeployer {
            repository(url: "${repositoryURL}/libs-releases-local") {
                authentication(userName: repositoryUserName, password: repositoryUserPassword)
            }
            snapshotRepository(url: "${repositoryURL}/libs-snapshots-local") {
                authentication(userName: repositoryUserName, password: repositoryUserPassword)
            }
        }
    }

    project.ext.buildPath = buildDir.toString()
    System.setProperty('prosrm.install.home', buildPath)

    apply from: file(new File(projectDir, 'gradle/plugins/build-setup.gradle'))
    apply from: file(new File(projectDir, 'gradle/plugins/build-util.gradle'))
    apply from: file(new File(projectDir, 'gradle/plugins/build-services.gradle'))
    apply from: file(new File(projectDir, 'gradle/plugins/build-bdd.gradle'))
    apply from: file(new File(projectDir, 'gradle/plugins/build-quality.gradle'))

    createTestTables.dependsOn copyDeploy
    copyDeploy.mustRunAfter unzipTestSchema

}

task wrapper(type: Wrapper) {
    gradleVersion = '3.2'
    distributionUrl = "${repositoryURL}/plugins-releases/org/gradle/gradle/${gradleVersion}/gradle-${gradleVersion}-bin.zip"
}

install.enabled = false
uploadArchives.enabled = false

apply from: file(new File(projectDir, 'gradle/plugins/build-reports.gradle'))
