### ISSUE TITLE
Unpacking of a valid tar files fails

### ISSUE THREAD

**Issue by pedjak** [gradle/gradle#8314]
### Expected Behavior
Tar archive is valid and should be unpacked into the given directory.

### Current Behavior
Some perfectly valid tar files could not be unpacked by using the following snippet:

```
copy {
  from tarTree("/path/to/foo.tar")
  into "bar"
}
```
i.e. Gradle breaks with the following message:

```
Caused by: org.gradle.api.GradleException: Unable to expand TAR '/path/to/foo.tar'
  The tar might be corrupted or it is compressed in an unexpected way.
  By default the tar tree tries to guess the compression based on the file extension.
  If you need to specify the compression explicitly please refer to the DSL reference.
due to this error:

Caused by: java.io.IOException: failed to skip current tar entry
        at org.apache.tools.tar.TarInputStream.getNextEntry(TarInputStream.java:279)
        at org.apache.tools.tar.TarInputStream.paxHeaders(TarInputStream.java:419)
        at org.apache.tools.tar.TarInputStream.getNextEntry(TarInputStream.java:335)
        at org.gradle.api.internal.file.archive.TarFileTree.visitImpl(TarFileTree.java:103)
        at org.gradle.api.internal.file.archive.TarFileTree.visit(TarFileTree.java:85)
```

### Steps to Reproduce (for bugs)
[foo.zip](https://github.com/gradle/gradle/files/2787937/foo.zip) contains the minimal project that reproduce the issue with Gradle 5.1 or any older version. Run `gradle foo` to reproduce it.

PR that fixes the issue: https://github.com/gradle/gradle/pull/7901

**Comment by khurshidatcadre** [comment]
I had the same `Unable to expand TAR` issue with the tar archive that was actually created by `Tar` task with `compression = Compression.GZIP`. 

Version details: 
```
Gradle:       5.5.1
Kotlin:       1.3.31
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14
JVM:          11.0.3
OS:           Linux 5.0.0-20-generic amd64
```

**Comment by ivanstepanovftw** [comment]
Gradle 6.4, still not fixed

**Comment by jjohannes** [comment]
See discussion on #7901 for why this is not an easy fix.
