### ISSUE TITLE
Two Gradle builds running on a same machine, sharing the build cache location fails while running parallel

### ISSUE THREAD

**Issue by scicompth** [gradle/gradle#8375]
We have a worktree setup on top of a local git repository. Two different git branches(with minimal code diff) where checked out in git repo and worktree. Enabled the Build Cache for my gradle builds on both the branches. Also, location for the build cache(~/.gradle/caches/build-cache-1) is default. Upon triggering the builds on both the branches simultaneously, one of the gradle build fails with exception  org.gradle.cache.LockTimeoutException

### Expected Behavior
Both the builds should pass? If not, what is the recommendation for setting up the build cache on such setup? 

### Current Behavior
One of the build fails with org.gradle.cache.LockTimeoutException

### Context
Setting up worktrees is common use case for us to support working on parallel releases of the software. We were testing out this option before we rollout with recommendations for such setup. 

### Steps to Reproduce (for bugs)
1. Setup worktree on a local git repo
2. Checkout branches on them
3. Try running the gradle builds on both the branches

### Your Environment
Gradle: Version 5.0
Windows 7 SP1 ,	64-bit
GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx5g -Dorg.gradle.caching=true"

###Stacktrace
Caused by: org.gradle.cache.LockTimeoutException: Timeout waiting to lock Build cache (C:\Users\~\.gradle\caches\build-cache-1). It is currently in use by another Gradle instance.
Owner PID: 26448
Our PID: 17928
Owner Operation:
Our operation:
Lock file: C:\Users\~\.gradle\caches\build-cache-1\build-cache-1.lock
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.lock(DefaultFileLockManager.java:291)
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.<init>(DefaultFileLockManager.java:161)
        at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:107)
        at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.incrementLockCount(LockOnDemandCrossProcessCacheAccess.java:106)
        at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.withFileLock(LockOnDemandCrossProcessCacheAccess.java:88)
        at org.gradle.cache.internal.DefaultCacheAccess.withFileLock(DefaultCacheAccess.java:198)
        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.withFileLock(DefaultPersistentDirectoryStore.java:175)
        at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.withFileLock(DefaultCacheFactory.java:199)
        at org.gradle.caching.local.internal.DirectoryBuildCacheService.loadLocally(DirectoryBuildCacheService.java:94)
        at org.gradle.caching.internal.controller.service.DefaultLocalBuildCacheServiceHandle.load(DefaultLocalBuildCacheServiceHandle.java:49)
        at org.gradle.caching.internal.controller.DefaultBuildCacheController.load(DefaultBuildCacheController.java:115)
        ... 36 more

**Comment by leonard84** [comment]
Possibly related we also experience an issue when running parallel builds on CI

```
Exception is:
org.gradle.internal.service.ServiceCreationException: Could not create service of type FileHasher using GradleUserHomeScopeServices.createCachingFileHasher().
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:816)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:749)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:540)
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:597)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:762)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:748)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:540)
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:597)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:762)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:748)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:540)
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:597)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:762)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:748)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:540)
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:597)
	at org.gradle.internal.service.DefaultServiceRegistry.find(DefaultServiceRegistry.java:296)
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:280)
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:275)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:40)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:31)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:42)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:28)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:52)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:68)
	at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:38)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:37)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:26)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:60)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:32)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:41)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:48)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:32)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:50)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:81)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)

Caused by: org.gradle.cache.LockTimeoutException: Timeout waiting to lock file hash cache (/home/jenkins-slave/.gradle/caches/5.4.1/fileHashes). It is currently in use by another Gradle instance.
Owner PID: 85
Our PID: 42131
Owner Operation: 
Our operation: 
Lock file: /home/jenkins-slave/.gradle/caches/5.4.1/fileHashes/fileHashes.lock
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.lock(DefaultFileLockManager.java:291)
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.<init>(DefaultFileLockManager.java:161)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:107)
	at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.incrementLockCount(LockOnDemandCrossProcessCacheAccess.java:106)
	at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.acquireFileLock(LockOnDemandCrossProcessCacheAccess.java:168)
	at org.gradle.cache.internal.DefaultCacheAccess.onStartWork(DefaultCacheAccess.java:369)
	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:214)
	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:204)
	at org.gradle.cache.internal.DefaultCacheAccess.newCache(DefaultCacheAccess.java:299)
	at org.gradle.cache.internal.DefaultCacheAccess.newCache(DefaultCacheAccess.java:58)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.createCache(DefaultPersistentDirectoryStore.java:160)
	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.createCache(DefaultCacheFactory.java:184)
	at org.gradle.api.internal.changedetection.state.CrossBuildFileHashCache.createCache(CrossBuildFileHashCache.java:49)
	at org.gradle.api.internal.changedetection.state.CachingFileHasher.<init>(CachingFileHasher.java:46)
	at org.gradle.internal.service.scopes.GradleUserHomeScopeServices.createCachingFileHasher(GradleUserHomeScopeServices.java:137)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
	at org.gradle.internal.service.ReflectionBasedServiceMethod.invoke(ReflectionBasedServiceMethod.java:34)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:814)
	... 65 more
```

**Comment by lichuanxiao** [comment]
I have the same problem，how to solve it？

**Comment by mrk-han** [comment]
We're also seeing this when running multiple builds concurrently on Jenkins using multiple Executors

**Comment by artemy-osipov** [comment]
still actual

**Comment by gurvinderd** [comment]
We have similar issue. Two builds getting kicked off on same host with different branches. We see random errors.

**Comment by Mindbowser** [comment]
I think there is no straightforward solution to this, I am ending up with below workaround 

Another workaround to 
- have global cache directory under jenkins
- Before job starts copy to local docker cache directory 
- Finish job steps
- At the end copy this directory content to global again

in case of docker might need to mount that directory before doing copy.

**Comment by cocorossello** [comment]
Same problem here (not so frequent)

`
<html>
<body>
<div class="FailureItem__message" style="box-sizing: border-box; padding-top: 8px; font: 400 14px / 20px Inconsolata, Monaco, &quot;Courier New&quot;, monospace; white-space: pre; padding-left: 24px; color: rgb(2, 48, 58); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Failed to load cache entry for task ':tr2-web:compileKotlin'
&gt; Build cache entry fc9c9aed5c299ccd433fc1e9715d137f from local build cache is invalid
  &gt; Timeout waiting to lock Build cache (/var/jenkins_home/.gradle/caches/build-cache-1). It is currently in use by another Gradle instance.
    Owner PID: 733467
    Our PID: 750491
    Owner Operation: 
    Our operation: 
    Lock file: /var/jenkins_home/.gradle/caches/build-cache-1/build-cache-1.lock</div><div class="FailureItem__exception FailureItem__exception--single-item" style="box-sizing: border-box; padding: 32px 0px 0px; color: rgb(2, 48, 58); font-family: Lato, sans-serif; font-size: 13.5px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: nowrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="FailureItem__exception-header" style="box-sizing: border-box; line-height: 20px; margin-bottom: 8px; padding-left: 24px;"><span class="FailureItem__exception-title" style="box-sizing: border-box; font-weight: 500;">Exception</span></div><div class=" FailureException" style="box-sizing: border-box; font: 14px Inconsolata, Monaco, &quot;Courier New&quot;, monospace;"><div style="box-sizing: border-box;">

  | org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':tr2-web:compileKotlin'. |  
-- | -- | --


</div></div></div></div></div></div></div></div></div>
</body>
</html>
`

**Comment by tvalentyn** [comment]
We also frequently encounter a this issue in Apache Beam, see: https://github.com/gradle/gradle/issues/14693#issuecomment-1049838635. Looks like running two gradle builds on one machine causes unrecoverable cache corruption.

**Comment by sefaYavuz** [comment]
We are also facing this issue in our CI/CD environment. Running 2 builds using Kubernetes Pods (each build has its own pod) and use the gradle home directory as a PersistentVolume is causing issues:

```
Timeout waiting to lock journal cache (/home/buildagent/.gradle/caches/journal-1). It is currently in use by another Gradle instance.
Owner PID: 2402
Our PID: 1668
Owner Operation:
Our operation:
Lock file: /home/buildagent/.gradle/caches/journal-1/journal-1.lock
```

Any solution?

**Comment by christhomas** [comment]
This is also a problem for me too, I don't really understand why gradle needs to lock anything in the cache because it's just downloading packages, it shouldn't matter how many gradle instances are downloading into that directory since the "lock" should be project specific on a per project basis, not gradle specific in a global context.

**Comment by yunjizhong** [comment]
We resolved this by using different GRALD_USER_HOME for different processes.
Different processes do not know about each other, so they may download the same dependencies to the same cache location, I think this is why gradle daemon performs a "lock" on the cache.

**Comment by 95jinhong** [comment]
> This is also a problem for me too, I don't really understand why gradle needs to lock anything in the cache because it's just downloading packages, it shouldn't matter how many gradle instances are downloading into that directory since the "lock" should be project specific on a per project basis, not gradle specific in a global context.

Hi, @christhomas 
Have you solved the Gradle Cache Lock issue?
If you did, can you tell us how?

**Comment by mlopatkin** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

***

We do not plan to address cases where Gradle processes using the cache cannot communicate to each other (like sharing the cache over a network drive or with a Docker container).

We don't plan to change the locking protocol either (though we may consider an opt-in eager lock release mode).

What else we can do:
* Verify that Gradle doesn't hold locks longer than necessary, like when running user code
* Investigate potential lock-free approaches, like immutable workspaces
* Increase lock granularity

**Comment by liamjones** [comment]
I originally hit this because an Endpoint Protection product was blocking localhost network connections but I had to really dig to find that as the cause. Improving the documentation and/or error messaging around this kind of failure would be good too.

If the error had complained about being unable to open a network connection to 127.0.0.1:xxx that would have made the cause much more obvious.

If the docs around Gradle caching had mentioned that port xxx on the loopback interface needs to be open for lock management communication between processes that would have shortened my investigation too.

**Comment by mlopatkin** [comment]
To clarify, we still want to do something with these same-machine firewall issues.
