### ISSUE TITLE
Adding single file as source to Checkstyle task fails

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#8394]
When trying to add a single file to the checkstyle task like this:
```
checkstyleMain.source = project.file('build.gradle')
```

then the build fails with:
```
Caused by: java.lang.UnsupportedOperationException: Cannot convert org.gradle.api.internal.file.collections.DefaultSingletonFileTree@457af41c to local file system directories.
    at org.gradle.api.internal.file.collections.FileTreeAdapter.getAsFileTrees(FileTreeAdapter.java:81)
    at org.gradle.api.internal.file.CompositeFileCollection.getAsFileTrees(CompositeFileCollection.java:118)
    at org.gradle.api.internal.file.AbstractFileCollection.addAsFileSet(AbstractFileCollection.java:133)
    at org.gradle.api.internal.file.AbstractFileCollection.addToAntBuilder(AbstractFileCollection.java:122)
    at org.gradle.api.file.FileCollection$addToAntBuilder$2.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:143)
    at org.gradle.api.plugins.quality.internal.CheckstyleInvoker$_invoke_closure1$_closure4.doCall(CheckstyleInvoker.groovy:61)
    at org.gradle.api.plugins.quality.internal.CheckstyleInvoker$_invoke_closure1$_closure4.doCall(CheckstyleInvoker.groovy)
```

As a workaround, a file tree only matching the single file can be added:

```
checkstyleMain.source = project.fileTree(dir: '.', include: 'build.gradle')
```

**Comment by big-guy** [comment]
@wolfs do you know why you'd do 
```
checkstyleMain.source = project.file('build.gradle')
```
For a single file?  

Does something like this work?
```
checkstyleMain.source = []
checkstyleMain.source(project.file('build.gradle'))
```

**Comment by zegnus** [comment]
@wolfs I am having a similar problem but with this `exclude` example: 

```
        checkstyle {
            exclude project.android.sourceSets.test.java.srcDirs
        }
```

where `project.android.sourceSets.test.java.srcDirs` is `/Users/zegnus/Development/project/demo/src/test/java`
