### ISSUE TITLE
Nested scala objects cause TestEngine with ID 'junit-jupiter' failed to discover tests  java.lang.InternalError: Malformed class name

### ISSUE THREAD

**Issue by maxhillaert** [gradle/gradle#8432]
Creating 3-level nested object structure in the test folder will cause test discovery to fail:

object Foo {
  object Sub {
    object SubSub{
    }
  }
}

### Expected Behavior
Unrelated non-test object structures shouldn't really be discovered at all

### Current Behavior
JUnitPlatform seems to try and discover tests in my object structure and fail with:

Feb 06, 2019 2:31:13 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'junit-jupiter' failed to discover tests
java.lang.InternalError: Malformed class name 
t java.lang.Class.getSimpleName(Class.java:1330)
	at java.lang.Class.isAnonymousClass(Class.java:1411)
	at org.junit.jupiter.engine.discovery.predicates.IsPotentialTestContainer.test(IsPotentialTestContainer.java:43)
	at org.junit.jupiter.engine.discovery.TestContainerResolver.isPotentialCandidate(TestContainerResolver.java:92)
	at org.junit.jupiter.engine.discovery.TestContainerResolver.resolveElement(TestContainerResolver.java:40)
	at org.junit.jupiter.engine.discovery.JavaElementsResolver.tryToResolveWithResolver(JavaElementsResolver.java:208)
	at org.junit.jupiter.engine.discovery.JavaElementsResolver.lambda$resolve$9(JavaElementsResolver.java:195)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.junit.jupiter.engine.discovery.JavaElementsResolver.resolve(JavaElementsResolver.java:198)
	at org.junit.jupiter.engine.discovery.JavaElementsResolver.lambda$resolveForAllParents$5(JavaElementsResolver.java:164)
	at java.util.Collections$SingletonSet.forEach(Collections.java:4767)
	at org.junit.jupiter.engine.discovery.JavaElementsResolver.resolveForAllParents(JavaElementsResolver.java:164)
	at org.junit.jupiter.engine.discovery.JavaElementsResolver.resolveContainerWithParents(JavaElementsResolver.java:85)
	at org.junit.jupiter.engine.discovery.JavaElementsResolver.resolveClass(JavaElementsResolver.java:60)
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.lambda$resolve$3(DiscoverySelectorResolver.java:69)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolve(DiscoverySelectorResolver.java:68)
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:50)
	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:61)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:92)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$100(JUnitPlatformTestClassProcessor.java:77)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:73)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)

### Steps to Reproduce (for bugs)

1) Create gradle scala project with junit 5 dependencies
2)  Create nested structure in test folder
object Foo {
  object Sub {
    object SubSub{
    }
  }
}
3) Run gradle test

### Your Environment
gradle 4.10.3
scala 2.12.0
JDK 1.8

**Comment by maxhillaert** [comment]
This is related to the following scala issue with JDK 1.8

https://github.com/scala/bug/issues/2034
object A {
  object B {
    class C {

    }
  }
}

val c = new A.B.C()
c.getClass.getSimpleName() // Throws: java.lang.InternalError: Malformed class name

Fixed in JDK 1.9.   We are stuck on  1.8 for the moment, but  I upgraded in a virgin project and it fixed the issue.

Having said that, ,  the Intellij Junit Runner is able to run tests fine without triggering a call to getSimpleName.    Any chance of doing the same in the gradle runner?

**Comment by big-guy** [comment]
I think this might require a JUnit change, not a Gradle one.  @marcphilipp ?

**Comment by marcphilipp** [comment]
Yes, this would definitely require a change in JUnit, not in Gradle. However, safeguarding all calls to `Class` such as `Class.isAnonymousClass()` does not sound feasible to me. Since this has been fixed in Java 9, I think your best bet is to exclude such classes by configuring your `Test` task.

I haven't tried it, but sth. like the following should work:

```kts
tasks.withType<Test>().configureEach {
	useJUnitPlatform()
	exclude("**/*$$*$$*.class")
}
```

**Comment by maxhillaert** [comment]
This worked:
`
    useJUnitPlatform {
        exclude("**/*\$*\$*.class")
    }`
