### ISSUE TITLE
Gradle 5.2 play plugin route compile issue?

### ISSUE THREAD

**Issue by chendongzou** [gradle/gradle#8594]
### Expected Behavior

Upgrade from gradle 4.9 to 5.2 with play version 2.3. 

Gradle build resulted in the following error:

Caused by: java.lang.RuntimeException: Error invoking the Play routes compiler.
        at org.gradle.play.internal.routes.RoutesCompiler.compile(RoutesCompiler.java:72)
        at org.gradle.play.internal.routes.RoutesCompiler.execute(RoutesCompiler.java:58)
        at org.gradle.play.internal.routes.RoutesCompiler.execute(RoutesCompiler.java:29)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:86)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:74)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:42)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:38)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:111)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        ... 3 more
Caused by: java.lang.ClassNotFoundException: scala.collection.Seq
        at org.gradle.play.internal.routes.RoutesCompilerAdapterV23X.getCompileMethod(RoutesCompilerAdapterV23X.java:47)
        at org.gradle.play.internal.routes.RoutesCompiler.compile(RoutesCompiler.java:69)
        ... 15 more

### Current Behavior

It used to work with gradle 4.9.

### Your Environment

 * Build scan URL: https://scans.gradle.com/s/4di7oviq6k2tm/failure?openFailures=WzBd&openStackTraces=WzJd#top=0

**Comment by big-guy** [comment]
Hi @chendongzou - could you create a build scan for the build that worked with 4.9 too?

**Comment by chendongzou** [comment]
https://scans.gradle.com/s/cpmx7rfjhnqz6/dependencies?toggled=W1s4NF0sWzgzXV0

**Comment by samsieber** [comment]
I'd like to chime in and saw we got hit with the same exact error. The error is introduced between gradle 4.10.1 and 5.0. In my case however, I'm using the following play config:

```
model {
	components {
		play {
			platform play: '2.3.10', scala: '2.11', java: '1.8'
		}
	}
}```

**Comment by samsieber** [comment]
OK. So gradle 5+ did remove play 2.3 support (due to java 9, I think):

https://github.com/gradle/gradle/pull/5593
