### ISSUE TITLE
UnsupportedOperationException  with Gradle 5.2.1 - changed behavior

### ISSUE THREAD

**Issue by Jonatha1983** [gradle/gradle#8607]
Till gradle 5.2.1 we were able to edit the project properties Map at an init script.

### Expected Behavior
To be able to edit project properties during the init phase.

### Current Behavior
* What went wrong:
A problem occurred evaluating initialization script.
> java.lang.UnsupportedOperationException (no error message)

Caused by: java.lang.UnsupportedOperationException
        at com.google.common.collect.ImmutableMap.put(ImmutableMap.java:450)
        at java_util_Map$put.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
        at init_8x75gmn4kul3orqh1llrmpjrs$_run_closure1.doCall(F:\views\g\gradlePlayGround\init.gradle:17)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:411)
        at groovy.lang.Closure.call(Closure.java:427)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2296)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2281)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2322)
        at org.codehaus.groovy.runtime.dgm$186.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:246)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:55)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at init_8x75gmn4kul3orqh1llrmpjrs.run(F:\views\g\gradlePlayGround\init.gradle:3)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
        ... 112 more

### Context
We found a workaround to firstly get the Map  modify it and the set the entire map again. is this the right way to do it now ? 

### Steps to Reproduce (for bugs)
init.gradle
````
def lookFor = ["type", "filter"]

gradle.startParameter.taskRequests.each { TaskExecutionRequest r ->

    Iterator<String> it = r.args.iterator();

    while (it.hasNext()) {
        String arg = it.next();

        for (String pn : lookFor) {

            String pe = "--" + pn + "="

            if (arg.startsWith(pe)) {
                it.remove();

                gradle.startParameter.projectProperties.put(pn, arg.substring(pe.length()))

            }
        }
    }
}
````
create a build.gradle  file

and run gradle  help --init-script init.gradle  --type=atype

### Your Environment

https://scans.gradle.com/s/wkdt3kbretjhq/infrastructure

**Comment by big-guy** [comment]
I don't think we're going to go back on how this behaves (it looks like this was introduced in 4.7 at least).

I would avoid trying to create your own command-line flags like this. You're going to silently run into collisions with built-in Gradle options. I think the equivalent of what you're trying to do would be to use project properties directly: `-Ptype=atype` or `-Pfilter=afilter`.  This is the same as what you're doing now and doesn't require any special init scripts.
