### ISSUE TITLE
gradle >= 1.8: copy task fails when source file contains colon

### ISSUE THREAD

**Issue by jberkenbilt** [gradle/gradle#862]
This was https://issues.gradle.org/browse/GRADLE-3037. It was reported against 1.11 but still appears in gradle 3.2.

### Expected Behavior

The copy task should copy all files regardless of what characters appear in their names.

### Current Behavior

If a directory being copied contains a file whose name contains a colon, the copy fails.

### Context

Trying to copy arbitrary directories whose files may contain any character in their names.

### Steps to Reproduce (for bugs)

Use the following build.gradle:

```gradle
task setup {
  doLast {
    delete(file('from'))
    file('from').mkdirs()
    file('from/a:b').text = ''
  }
}

task bug(type: Copy, dependsOn: setup) {
  from('from')
  into('to')
}
```

Run `gradle -q bug` (with gradle 3.2 or whatever is latest). Output:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bug'.
> Cannot convert URL 'a:b' to a file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

### Your Environment

 * Build scan URL: 

This is Linux (Ubuntu 16.04). `gradle -version`:

```
------------------------------------------------------------
Gradle 3.2
------------------------------------------------------------

Build time:   2016-11-14 12:32:59 UTC
Revision:     5d11ba7bc3d79aa2fbe7c30a022766f4532bbe0f

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Linux 4.4.0-47-generic amd64
```

**Comment by jberkenbilt** [comment]
I'm trying to update the JIRA issue to indicate that it has been moved here, but I am not able to log into issues.gradle.org right now.

**Comment by eriwen** [comment]
@jberkenbilt Thank you for moving it here. I've updated the JIRA issue in your stead.

**Comment by datalorax** [comment]
(adding Jay's work around from here: https://discuss.gradle.org/t/gradle-1-8-copy-task-fails-when-source-file-contains-colon/1747/3)

Jay's workaround is to use this function:

def renameFiles(dir, pat, repl) {
  fileTree(dir).each { file ->
    def newfile = file.path.replaceAll(pat, repl)
    if (newfile != file.path) {
      file.renameTo(newfile)
    }
  }
}
to replace : with @@ before copying and replace @@ back with : after copying. My real code isn't doing just a straight copy. It is using an eachFile closure over the contents of the files.

**Comment by dmolesUC** [comment]
Just to confirm, this is still an issue with Gradle 6.0.1 on macOS. With the `war` plugin:

```
static def datestamp() {
    def now = ZonedDateTime.now(ZoneOffset.UTC).truncatedTo(ChronoUnit.SECONDS)
    return now.format(DateTimeFormatter.ISO_INSTANT)
}

war {
    archiveAppendix = datestamp()
}
```

running `./gradlew war --stacktrace` produces:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':war'.
> Cannot convert URL 'videoArchive-2019-12-06T18:35:34Z-0.2.0.war' to a file.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':war'.
        at org.gradle.execution.plan.LocalTaskNode.resolveMutations(LocalTaskNode.java:233)
        at org.gradle.execution.plan.DefaultExecutionPlan.getResolvedMutationInfo(DefaultExecutionPlan.java:652)
        at org.gradle.execution.plan.DefaultExecutionPlan.selectNext(DefaultExecutionPlan.java:566)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$executeNextNode$1(DefaultPlanExecutor.java:166)
        at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:155)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.api.InvalidUserDataException: Cannot convert URL 'videoArchive-2019-12-06T18:35:34Z-0.2.0.war' to a file.
        at org.gradle.api.internal.file.AbstractFileResolver.convertObjectToFile(AbstractFileResolver.java:108)
        at org.gradle.api.internal.file.AbstractBaseDirFileResolver.doResolve(AbstractBaseDirFileResolver.java:69)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:73)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:52)
        at org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedDirectory.file(DefaultFilePropertyFactory.java:109)
        at org.gradle.api.internal.file.DefaultFilePropertyFactory$DefaultDirectoryVar$4.map(DefaultFilePropertyFactory.java:370)
        at org.gradle.api.internal.file.DefaultFilePropertyFactory$DefaultDirectoryVar$4.map(DefaultFilePropertyFactory.java:367)
        at org.gradle.api.internal.provider.AbstractCombiningProvider.getOrNull(AbstractCombiningProvider.java:48)
        at org.gradle.api.internal.provider.AbstractReadOnlyProvider.get(AbstractReadOnlyProvider.java:27)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:50)
        at org.gradle.api.internal.provider.DefaultProperty.get(DefaultProperty.java:151)
        at org.gradle.util.DeferredUtil.unpack(DeferredUtil.java:40)
        at org.gradle.api.internal.tasks.properties.FileParameterUtils.resolveOutputFilePropertySpecs(FileParameterUtils.java:107)
        at org.gradle.execution.plan.LocalTaskNode$1.lambda$visitOutputFileProperty$1(LocalTaskNode.java:197)
        at org.gradle.execution.plan.LocalTaskNode.withDeadlockHandling(LocalTaskNode.java:274)
        at org.gradle.execution.plan.LocalTaskNode.access$000(LocalTaskNode.java:50)
        at org.gradle.execution.plan.LocalTaskNode$1.visitOutputFileProperty(LocalTaskNode.java:193)
        at org.gradle.api.internal.tasks.properties.annotations.AbstractOutputPropertyAnnotationHandler.visitPropertyValue(AbstractOutputPropertyAnnotationHandler.java:50)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode.visitProperties(AbstractNestedRuntimeBeanNode.java:59)
        at org.gradle.api.internal.tasks.properties.bean.RootRuntimeBeanNode.visitNode(RootRuntimeBeanNode.java:32)
        at org.gradle.api.internal.tasks.properties.DefaultPropertyWalker.visitProperties(DefaultPropertyWalker.java:41)
        at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:42)
        at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:32)
        at org.gradle.execution.plan.LocalTaskNode.resolveMutations(LocalTaskNode.java:190)
        ... 9 more
```

I'm guessing this has something to do with `:` historically being the HFS path separator, but I don't really know.

**Comment by dmolesUC** [comment]
The fundamental issue is in [`FileOrUriNotationConverter`](https://github.com/gradle/gradle/blob/v6.8.0-RC1/subprojects/file-collections/src/main/java/org/gradle/api/internal/file/FileOrUriNotationConverter.java#L107-L116), which assumes that pretty much anything with a `:` in it is a URI (see [`FileOrUriNotationConverter.URI_SCHEME`](https://github.com/gradle/gradle/blob/v6.8.0-RC1/subprojects/file-collections/src/main/java/org/gradle/api/internal/file/FileOrUriNotationConverter.java#L40)). It returns a (garbage) `URI`, and [`AbstractFileResolver`](https://github.com/gradle/gradle/blob/v6.8.0-RC1/subprojects/file-collections/src/main/java/org/gradle/api/internal/file/AbstractFileResolver.java#L105-L109) then complains that it's not a `File`.

I haven't tried this, but in some cases a workaround might be to use a `Path` or `File` object instead of a string. Unfortunately, that won't work for mine, because the `File` object is generated internally and the only accessible properties are strings.

One possible workaround would be for `FileOrUriNotationConverter` to use `java.net.URL`, which only allows known URL schemes, and then call `.toURI()` on the result before passing it back. I don't know to what side effects that might have, though, e.g. to what extent people often pass in URIs with custom or novel schemes. Alternatively, Gradle could maintain its own list of schemes, possibly based on the [IANA list](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml), but it would need to be updated fairly frequently.

**Comment by ov7a** [comment]
Fixed by
* #31902
