### ISSUE TITLE
Java NullPointerException 

### ISSUE THREAD

**Issue by amenkes319** [gradle/gradle#8633]
### Expected Behavior
Trying to run this command: gradle init --type basic in powershell

### Current Behavior
Receive this error:

`java.lang.NullPointerException
        at org.gradle.api.internal.classpath.DefaultModuleRegistry.loadExternalModule(DefaultModuleRegistry.java:100)
        at org.gradle.api.internal.classpath.DefaultModuleRegistry.getExternalModule(DefaultModuleRegistry.java:91)
        at org.gradle.api.internal.DefaultClassPathProvider.findClassPath(DefaultClassPathProvider.java:45)
        at org.gradle.api.internal.DefaultClassPathRegistry.getClassPath(DefaultClassPathRegistry.java:34)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:48)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)`

### Context
Trying to set up a spreadsheet quickstart from the API

### Steps to Reproduce (for bugs)
Any gradle command
https://github.com/amenkes319/7400-Scouting-Program

### Your Environment
Eclipse Neon
 * Build scan URL:  Same error when doing any gradle command, including grade build --scan

**Comment by big-guy** [comment]
Hi @amenkes319 

Do you know which version of Gradle you're using? This looks suspiciously like a corrupted installation.

Could you try downloading [Gradle 5.2.1 from here](https://gradle.org/releases/) and give it another try?
