### ISSUE TITLE
Test task and '-XstartOnFirstThread' makes gradle hang

### ISSUE THREAD

**Issue by nedtwigg** [gradle/gradle#864]
### Expected Behavior

When test has specified the following arguments:

```gradle
test {
    jvmArgs '-XstartOnFirstThread'
}
```

the JUnit test cases should be started on the first thread.

### Current Behavior

The tests do not start on the first thread.

### Context

This is required for SWT tests to run on mac.

As of [May 2016](https://issues.gradle.org/browse/GRADLE-3290?focusedCommentId=21024&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-21024), the Gradle test VM is started by `org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor` which uses `org.gradle.process.internal.worker.DefaultWorkerProcessBuilder` to create a `WorkerProcess` and start it.
All this is called from `org.gradle.api.internal.tasks.testing.detection.DefaultTestExecuter`.

### Steps to Reproduce (for bugs)

```
git clone https://github.com/diffplug/durian-swt
cd durian-swt
git checkout macGradleRepro
gradlew test
```

### Your Environment

Any version of macOS.

**Comment by fab1an** [comment]
Is there a way around this without having to introduce ant?

**Comment by fab1an** [comment]
I started the test using `./gradlew test --info` and got the following:

```
/* I inserted newlines for better readability */

Starting process 'Gradle Test Executor 1'. Working directory: <mydirectory> 
Command: /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin/java 
-Djava.awt.headless=true
-Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager 
-Xmx512m 
-Dfile.encoding=UTF-8 
-Duser.country=US 
-Duser.language=en 
-Duser.variant 
-ea 
-cp /Users/MyUser/.gradle/caches/2.14.1/workerMain/gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 1'
```

When I run this command manually, and press enter I get this:

```java
Error occurred during initialization of VM
java.lang.ExceptionInInitializerError
	at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1451)
	at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1436)
Caused by: java.lang.RuntimeException: Could not initialise system classpath.
	at worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager.checkPermission(BootstrapSecurityManager.java:81)
	at java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1294)
	at java.lang.System.getProperty(System.java:717)
	at sun.misc.Launcher.<clinit>(Launcher.java:59)
	at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1451)
	at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1436)
Caused by: java.io.IOException: Unexpected value 10 received. It seems the stream was not encoded correctly.
	at worker.org.gradle.process.internal.streams.EncodedStream$EncodedInput.hexToByte(EncodedStream.java:59)
	at worker.org.gradle.process.internal.streams.EncodedStream$EncodedInput.read(EncodedStream.java:49)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager.checkPermission(BootstrapSecurityManager.java:67)
	at java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1294)
	at java.lang.System.getProperty(System.java:717)
	at sun.misc.Launcher.<clinit>(Launcher.java:59)
	at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1451)
	at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1436)
```

**Comment by nedtwigg** [comment]
I submitted a PR which fixes this issue.

**Comment by ljacomet** [comment]
Re-opening since there is an PR open to fix this.
