### ISSUE TITLE
Support for mapped input files

### ISSUE THREAD

**Issue by netvl** [gradle/gradle#8646]
If you put an `@InputFiles` annotation on a map property in a task, for example:

```kotlin
open class ExampleTask : DefaultTask() {
    @get:InputFiles
    val inputs: MapProperty<String, File> = project.objects.mapProperty()

    @TaskAction
    fun run() {
        logger.quiet("Inputs: ${inputs.get()}")
    }
}

tasks.register<ExampleTask>("exampleTask") {
    inputs.set(mapOf("hello" to project.buildDir.resolve("hello.txt")))
}
```

then it will be impossible to run a task of this type, because Gradle would throw an exception:

```
Caused by: java.lang.IllegalArgumentException: Cannot resolve object of unknown type RegularImmutableMap to a Task.
```

Note that this is not related to Kotlin DSL, because I observe exactly the same behavior with Groovy DSL as well:

```groovy
class ExampleTask extends DefaultTask {
    @InputFiles
    MapProperty<String, File> inputFiles = project.objects.mapProperty(String, File)
    
    @TaskAction
    def run() {
        logger.quiet("Inputs: ${inputFiles.get()}")
    }
}

tasks.register("exampleTask", ExampleTask).configure {
    inputFiles.set hello: file("$buildDir/hello.txt")
}
```

### Expected Behavior

Tasks can have `@InputFiles` properties of map types, similarly to the `@OutputFiles` properties, which even mentions maps in the javadoc comment.

### Current Behavior

If such a property is defined in a task, Gradle throws the following exception:
```
org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':exampleTask'.
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:68)
        at org.gradle.execution.plan.TaskDependencyResolver.resolveDependenciesFor(TaskDependencyResolver.java:46)
        at org.gradle.execution.plan.LocalTaskNode.getDependencies(LocalTaskNode.java:106)
        at org.gradle.execution.plan.LocalTaskNode.resolveDependencies(LocalTaskNode.java:79)
        at org.gradle.execution.plan.DefaultExecutionPlan.addEntryTasks(DefaultExecutionPlan.java:167)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.addEntryTasks(DefaultTaskExecutionGraph.java:139)
        at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:57)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$200(DefaultBuildConfigurationActionExecuter.java:26)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$2.proceed(DefaultBuildConfigurationActionExecuter.java:63)
        at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:44)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:57)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$200(DefaultBuildConfigurationActionExecuter.java:26)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$2.proceed(DefaultBuildConfigurationActionExecuter.java:63)
        at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:47)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:57)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$200(DefaultBuildConfigurationActionExecuter.java:26)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.run(DefaultBuildConfigurationActionExecuter.java:43)
        at org.gradle.internal.Factories$1.create(Factories.java:25)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry.withLenientState(DefaultProjectStateRegistry.java:132)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry.withLenientState(DefaultProjectStateRegistry.java:124)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.select(DefaultBuildConfigurationActionExecuter.java:39)
        at org.gradle.initialization.DefaultGradleLauncher$CalculateTaskGraph.run(DefaultGradleLauncher.java:333)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.initialization.DefaultGradleLauncher.constructTaskGraph(DefaultGradleLauncher.java:218)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:155)
        at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:134)
        at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:58)
        at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:55)
        at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:82)
        at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:75)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:183)
        at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:40)
        at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:75)
        at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:55)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:31)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:58)
        at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
        at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:39)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:49)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:44)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:44)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:49)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:46)
        at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:78)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:46)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:31)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:42)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:28)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:52)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:68)
        at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:38)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:37)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:60)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:32)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:41)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:48)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:32)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:81)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.IllegalArgumentException: Cannot resolve object of unknown type RegularImmutableMap to a Task.
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:133)
        at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmpyEdges.getNodeValues(CachingDirectedGraphWalker.java:211)
        at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:121)
        at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:73)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:66)
        ... 105 more
```

### Context

I need to create a task which accepts a map with `java.io.File` values, and I would like the task to be considered outdated if the files in the map are modified/deleted/etc. I would also like to use lazy configuration, because that's what the future of Gradle tasks writing is (is it?). Unfortunately, combining these two things don't work properly now :)

### Steps to Reproduce (for bugs)

The above code snippets can be pasted to `build.gradle.kts` or `build.gradle` and then tested right away.

### Your Environment

Gradle 5.2.1

**Comment by thc202** [comment]
#8637 seems relevant.

**Comment by wolfs** [comment]
@netvl Thank you for reporting. As @thc202 pointed out, we wanted to deprecated the support for mapped inputs in #8637. We think that using `@Nested` with a rich property type better conveys the meaning.

Still, we are open to be convinced that it is a good idea to support `Map<String, File>` for inputs as well. What is your particular use-case you are trying to solve when using a `Map<String, File>`? What does the input represent?

**Comment by wolfs** [comment]
@netvl I am still struggling to find the semantic meaning of the `Map<String, File>` as the input from your description. Could you give an example what your task is doing so I better understand why the input is a `Map<String, File>` and nothing more?

**Comment by netvl** [comment]
@wolfs,

I have an internal deployment system which expects a certain format and naming of artifacts that it accepts. These artifacts are derived from the "regular" artifacts, e.g. JAR files, with some additional configuration pulled from the project file tree. This deployment system expects one "main" artifact, and a set of "auxiliary" artifacts corresponding to various deployment scenarios.

Additionally, the "main" artifact and one of the "auxiliary" artifacts could be combined (without using the deployment system) in a certain way to get another artifact, which the user can deploy manually, if it is needed.

Therefore, I have a task which generates a "main" artifact, and a set of "auxiliary" artifacts, where each auxiliary artifact is keyed by some identifier (which is supposed to be known to the user and make sense to them). The natural way to represent these auxiliary artifacts is a `Map<String, File>`, and there are no other things related to these auxiliary artifacts except the files themselves.

The set of identifiers, i.e. keys in the map, is not known statically and depends on the contents of the project that the plugin is applied to. I don't want the user to describe these keys in the build script either.

This task is supposed to be called by things like CICD, and it always generates all of the artifacts.

Then, there is another task which is supposed to be invoked by the user with a command line argument. This second task accepts one of the aforementioned identifiers, then takes the "main" artifact generated by the first task and one of the "auxiliary" artifacts (corresponding to the provided identifier), and then repackages them to produce another artifact, which the user would want to work with directly.

This second task is supposed to be run by the user, and it should not generate all of the artifacts corresponding to all of the identifiers, only the one which the user has specified.

Finally, in both of these tasks these identifiers are used not just for file naming, but they actually are used to perform the packaging of the artifacts, so logically they should be explicit and separate from file names.

**Comment by wolfs** [comment]
@netvl Thank you for your use case. I think it is a valid use-case for using mapped file inputs. We decided not to deprecate mapped output files and support mapped input files instead.

For your special case, you could just declare the main artifact and the auxiliary artifact as to separate input files. That would be enough, right?

**Comment by netvl** [comment]
Thank you very much!

> you could just declare the main artifact and the auxiliary artifact as to separate input files

The actual auxiliary artifact that the second task would use depends on the user input, i.e. a property passed through the command line:

```
$ ./gradlew packageForManualDeployment --env ENVKEY
```

This task should then take the appropriate artifact from the map using the provided key. Therefore, the task has two input properties, `@InputFiles MapProperty<String, File>` and `@Input @Option Property<String>`. I don't think there is a way to somehow turn this into a single `@InputFile File` property while keeping the same interface.

What I did now is I've created two wrapper classes:

```kotlin
data class WrappedInputFile(@get:InputFile val file: File)
data class WrappedOutputFile(@get:OutputFile val file: File)
```

then declared the `MapProperty<String, WrappedOutputFile>` and `MapProperty<String, WrappedInputFile>` on the tasks, and added a conversion from one type to another in the plugin:

```kotlin
fun computeAuxiliaryArtifacts(): Map<String, File> = ...

val firstTask = project.tasks.register<Task1>("task1") {
    auxiliaryArtifacts.set(computeAuxiliaryArtifacts().mapValues {
        WrappedOutputFile(it.value)
    })
}

val secondTask = project.tasks.register<Task2>("task2") {
    auxiliaryArtifacts.set(firstTask.flatMap { ft ->
        ft.auxiliaryArtifacts.map { m ->
            m.mapValues { WrappedInputFile(it.value.file) }
        }
    }
}
```

**Comment by wolfs** [comment]
Why can't you use the command line argument? Your task would look something like this:

```kotlin
abstract class SecondTask : DefaultTask() {
    @Input @Option("env")
    abstract val env: Property<String>

    @Internal
    abstract val artifacts: MapProperty<String, File>
      
    @InputFile
    val File primaryInput
        get() = artifacts.get().get("primaryArtifactName")

    @InputFile
    val File auxiliaryInput
        get() = artifacts.get().get(env.get())
}
```

**Comment by netvl** [comment]
Indeed, apparently I can do it. For some reason, it did not occur to me that I can re-expose `primaryInput` and `auxiliaryInput` as input properties on the second task. It does solve this particular issue, but it makes the interface of the task strange: it has an input property, but it is not possible to set it.
