### ISSUE TITLE
Gradle fails to detect version of OpenJDK 11.0.2 

### ISSUE THREAD

**Issue by maltalex** [gradle/gradle#8671]
### Expected Behavior
According to the release notes, Gradle 4.10.3 should work with OpenJDK 11
> Gradle runs on all major operating systems and requires only a Java JDK version 7 or higher to run.

### Current Behavior
When setting JAVA_HOME to openjdk _jdk-11.0.2+9_ (can be obtained [here](https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot)) gradle fails to detect the java version:

```
******* >gradlew --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.2'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.IllegalArgumentException: Could not determine java version from '11.0.2'.
        at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:72)
        at org.gradle.api.JavaVersion.current(JavaVersion.java:82)
        at org.gradle.internal.jvm.UnsupportedJavaRuntimeException.assertUsingVersion(UnsupportedJavaRuntimeException.java:42)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:32)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:246)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:182)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

* Get more help at https://help.gradle.org

```

### Context
I'm trying to run gradle.

### Steps to Reproduce (for bugs)
Try to run gradle with OpenJDK 11.0.2+9 Hotspot 

### Your Environment
Windows 10 64 bit
OpenJDK 11.0.2+9 Hotspot

**Comment by maltalex** [comment]
Looks like there's an open ticket for this bug, but for `ea` builds of Java 11 (#4591). 
But now Java 11 has been officially out for half a year, so it's not just early builds.

**Comment by oehme** [comment]
Please run `gradlew -version` and make sure you're actually using 4.10

**Comment by maltalex** [comment]
You're right. The wrapper task was configured to 4.10.3, but the wrapper itself was from 4.2.1.
Thanks.
