### ISSUE TITLE
BuildCache unpack and CleanupStaleOutputsExecuter fails on Windows with UnrecoverableUnpackingException due to file deletion fails

### ISSUE THREAD

**Issue by AndreasTu** [gradle/gradle#8684]
The BuildCache unpack operation fails sporadically on Windows machines with an `IOException`. 
The class `org.gradle.caching.internal.packaging.impl.PackerDirectoryUtil` tries to delete directories, which fails sporadically in windows machines.
See Stacktrace below.

The same issue happens in the class `org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter` which also uses the `org.apache.commons.io.FileUtils.forceDelete` method.
See Stacktrace below.

### Expected Behavior
The BuildCache should retry to delete the files. The file delete on Windows does not block until the files where deleted.
 
The class `org.gradle.api.internal.file.delete.Deleter` has already a fix for that issue in the method `handleFailedDelete()`. It would be best if the same code is called when tried to delete the Directories in 
`org.gradle.caching.internal.packaging.impl.PackerDirectoryUtil.ensureDirectoryForTree()`

The method `org.gradle.util.GFileUtils.forceDelete` should also be changed to use the same logic as the `Deleter`.

### Current Behavior
The `org.gradle.caching.internal.packaging.impl.PackerDirectoryUtil` class uses `org.apache.commons.io.FileUtils.cleanDirectory` but this does not handle the odd windows delete case correctly.

### Context
The JavaCompile task aborts when the issue occurs.
The expected Compile-Artifacts must be in a remote build cache, which are downloaded.

This does not fail every time due to the timing issue between Windows and the Gradle Java process.

### Steps to Reproduce (for bugs)
* Java-Project
* Remote-Build cache
* Publish the artifacts in the build cache
* Change the built artifacts of the JavaCompile task that it tries to clean them up
* Execute gradlew compileJava multiple times 

### Your Environment
Windows 7 6.1
Gradle 5.2.0
Java Project

### Exception stacktrace

**BuildCache:**
```
org.gradle.caching.internal.packaging.UnrecoverableUnpackingException: Failed to unpack trees for task ':project:compileJava', and then failed to
        at org.gradle.caching.internal.command.BuildCacheCommandFactory$LoadCommand.load(BuildCacheCommandFactory.java:134)
        at org.gradle.caching.internal.controller.DefaultBuildCacheController$Unpack$1.run(DefaultBuildCacheController.java:179)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.caching.internal.controller.DefaultBuildCacheController$Unpack.execute(DefaultBuildCacheController.java:175)
        at org.gradle.caching.internal.controller.DefaultBuildCacheController$1.execute(DefaultBuildCacheController.java:143)
        ... 152 more
Caused by: java.io.IOException: D:\path\to\folder
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1497)
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2223)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1595)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1488)
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2223)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1595)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1488)
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2223)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1595)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1488)
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2223)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1595)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1488)
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2223)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1595)
        at org.gradle.caching.internal.packaging.impl.PackerDirectoryUtil.ensureDirectoryForTree(PackerDirectoryUtil.java:30)
        at org.gradle.caching.internal.packaging.impl.TarBuildCacheEntryPacker.unpackTree(TarBuildCacheEntryPacker.java:239)
        at org.gradle.caching.internal.packaging.impl.TarBuildCacheEntryPacker.unpack(TarBuildCacheEntryPacker.java:198)
        at org.gradle.caching.internal.packaging.impl.TarBuildCacheEntryPacker.unpack(TarBuildCacheEntryPacker.java:158)
        at org.gradle.caching.internal.packaging.impl.GZipBuildCacheEntryPacker.unpack(GZipBuildCacheEntryPacker.java:49)
        at org.gradle.caching.internal.command.BuildCacheCommandFactory$LoadCommand.load(BuildCacheCommandFactory.java:103)
        ... 162 more
```

**Stale output:**
```
java.io.IOException: Unable to delete directory D:\path\to\folder.
at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1623)
at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2391)
at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721)
at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617)
at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2391)
at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721)
at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617)
at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2391)
at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721)
at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617)
at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2391)
at org.gradle.util.GFileUtils.forceDelete(GFileUtils.java:266)
at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter$1.run(CleanupStaleOutputsExecuter.java:80)
at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:74)
```

**Comment by wolfs** [comment]
I got the following information from @AndreasTu: 

> We cannot reproduce the problem consistently, yet.
> It happens only on some machines and even there only sporadically.
> 
> We know that it happens more often if there is more IO activity.
>
> We saw this phenomenon already with other Java programs trying to delete deep order structures.
> My suspicion is the following, see the Windows-API documentation:
>
> https://docs.microsoft.com/de-de/windows/win32/api/fileapi/nf-fileapi-removedirectorya
>
> Remarks
>
> The RemoveDirectory function marks a directory for deletion on close. Therefore, the directory is not removed until the last handle to the directory is closed.
> 
> 
> `Java.io.File.delete()` calls `WinNTFileSystem.delete()`.
>
> This is called from Java native code:
> 
> https://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/windows/native/java/io/WinNTFileSystem_md.c
>
```
JNIEXPORT jboolean JNICALL
Java_java_io_WinNTFileSystem_delete0(JNIEnv *env, jobject this, jobject file)
{
    jboolean rv = JNI_FALSE;
    WCHAR *pathbuf = fileToNTPath(env, file, ids.path);
    if (pathbuf == NULL) {
        return JNI_FALSE;
    }
    if (removeFileOrDirectory(pathbuf) == 0) {
        rv = JNI_TRUE;
    }
    free(pathbuf);
    return rv;
}
 

static int
removeFileOrDirectory(const jchar *path)
{
    /* Returns 0 on success */
    DWORD a;
 
    SetFileAttributesW(path, FILE_ATTRIBUTE_NORMAL);
    a = GetFileAttributesW(path);
    if (a == INVALID_FILE_ATTRIBUTES) {
        return 1;
    } else if (a & FILE_ATTRIBUTE_DIRECTORY) {
        return !RemoveDirectoryW(path);
    } else {
        return !DeleteFileW(path);
    }
}
``` 
>
> In the code which fails, `FileHandles` are used to traverse the directory contents to delete child files.

**Comment by lptr** [comment]
Let's use `Deleter` when cleaning outputs for the cache.

**Comment by lptr** [comment]
We also need https://github.com/gradle/gradle/issues/10227 and https://github.com/gradle/gradle/issues/10226 to close this.

**Comment by lptr** [comment]
@AndreasTu this should now be fixed on `master`. Can you please try if you can still reproduce the problem using the latest nightly Gradle version `5.7 20190815220048+0000`?

**Comment by AndreasTu** [comment]
@lptr thank you for the fixes. We will test it.

**Comment by lptr** [comment]
@AndreasTu I'm closing this as fixed now. Please reopen if your tests indicate that something's still not working.
