### ISSUE TITLE
ClassCastException when module metadata is present in specific case

### ISSUE THREAD

**Issue by fluidsonic** [gradle/gradle#8725]
I've published an example [Kotlin Multiplatform module](https://github.com/fluidsonic/kotlin-multiplatform-dummy) including Gradle 5.3 RC1 metadata.
Trying to use that module in a project results in a `ClassCastException` during project configuration.

### Expected Behavior
Module dependency should work just fine.

### Current Behavior
`ClassCastException` with this additional info on Java 11 (same on Java 8 but with less info)
```
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.DesugaredAttributeContainerSerializer.write(DesugaredAttributeContainerSerializer.java:74)
	at org.gradle.api.internal.artifacts.ivyservice.modulecache.ModuleMetadataSerializer$Writer.writeAttributes(ModuleMetadataSerializer.java:166)
	at org.gradle.api.internal.artifacts.ivyservice.modulecache.ModuleMetadataSerializer$Writer.writeVariants(ModuleMetadataSerializer.java:132)
	at org.gradle.api.internal.artifacts.ivyservice.modulecache.ModuleMetadataSerializer$Writer.write(ModuleMetadataSerializer.java:125)
	at org.gradle.api.internal.artifacts.ivyservice.modulecache.ModuleMetadataSerializer$Writer.write(ModuleMetadataSerializer.java:111)
	at org.gradle.api.internal.artifacts.ivyservice.modulecache.ModuleMetadataSerializer.write(ModuleMetadataSerializer.java:93)
	at org.gradle.api.internal.artifacts.ivyservice.modulecache.ModuleMetadataStore$1.execute(ModuleMetadataStore.java:76)
	at org.gradle.api.internal.artifacts.ivyservice.modulecache.ModuleMetadataStore$1.execute(ModuleMetadataStore.java:71)
	at org.gradle.internal.resource.local.DefaultPathKeyFileStore$1.execute(DefaultPathKeyFileStore.java:95)
```

### Context
- [Kotlin Multiplatform dummy - project](https://github.com/fluidsonic/kotlin-multiplatform-dummy) (the module being added as a dependency)
- [Kotlin Multiplatform dummy - Maven repository](https://github.com/fluidsonic/kotlin-multiplatform-dummy/tree/master/releases) (Maven repository containing the published module)
- [Kotlin JVM Example project](https://github.com/fluidsonic/kotlin-jvm-example) (example project which consumes that modules)

#### Observations

The problem does only occur if the following code is called in [`build.gradle.kts`, line 24](https://github.com/fluidsonic/kotlin-jvm-example/blob/master/build.gradle.kts#L24):
`configurations.runtimeClasspath.get().files`

The problem also does not occur if I use the `jvm` preset in Kotlin Multiplatform instead of `jvmWithJava`. The latter causes a different output in the module file which makes [this line](https://github.com/fluidsonic/kotlin-multiplatform-dummy/blob/master/releases/example/kotlin-multiplatform-dummy-jvm/0.9.0-SNAPSHOT/kotlin-multiplatform-dummy-jvm-0.9.0-20190309.003347-1.module#L24) a candidate for the `ClassCastException` from `Integer` to `String` because it only exists in the latter case.

### Steps to Reproduce (for bugs)
```
git clone git@github.com:fluidsonic/kotlin-jvm-example.git
cd kotlin-jvm-example
./gradlew clean
```

### Your Environment
Java 8: https://scans.gradle.com/s/rshehoskuoc2w
Java 11: https://scans.gradle.com/s/fuhxwfhyj3t6w

**Comment by ljacomet** [comment]
Thanks for the report. There was indeed a bug that will be fixed in Gradle 5.3 RC2.
See #8732 for details.
