### ISSUE TITLE
"Primary configuration failure" message is confusing, should not have stacktrace by default

### ISSUE THREAD

**Issue by ducrohet** [gradle/gradle#874]
This is a re-opening of [GRADLE-2617](https://issues.gradle.org/browse/GRADLE-2617). I just got the notification on it that I need to do something about it due to the migration and it's a perfect timing because while I opened the original bug for Gradle 1.3, I just got bitten by this bug again today on version 3.3 (nightly)!

### Expected Behavior
An exception raised during project configuration is shown via `--stacktrace`.

### Current Behavior
If the project has an `afterEvaluate` callback that fails with another exception (likely due to the exception that prematurely ended the configuration), then it is the exception thrown in the `afterEvaluate` callback that is displayed through `--stacktrace`

### Context
How has this issue affected me? Well, it makes for a very confusing troubleshooting experience :) The only way to realize what's happening is to go in the debugger and go step by step in the *configuration* code (and not the `afterEvaluate` code!) and realize that it throws something.

### Steps to Reproduce (for bugs)
A simple build.gradle file with this snippet will show the problem:
```
afterEvaluate {
	throw new RuntimeException("foo")
}

thrown new RuntimeException("bar")
```

This will fail on the command line with:
```
$ gradle
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.RuntimeException: foo
```

While this exception is indeed thrown it's not the root of the problem. I think that requiring that every user check the configuration state in all the `afterEvaluate` is not going to work. In all the years I've worked with Gradle I've never seen anyone actually do it.

**Comment by eriwen** [comment]
Thank you for the well-written issue @ducrohet. It will help us triage and address this issue much faster.

**Comment by oehme** [comment]
This is actually not the case. The primary exception is shown in the stacktrace. The secondary exception (inside the `afterEvaluate` hook) is logged as well. Reproduced with the example above.

**Comment by nedtwigg** [comment]
It is true that both the `configure` and `afterEvaluate` exceptions are shown, but Gradle's output makes it look as though the primary exception is the `afterEvaluate` exception, rather than the `configure` exception.  There might be a bigger picture that I'm missing, but it seems like exceptions thrown in `configure` will almost always be the root cause, and the `afterEvaluate` exception will be an effect of that cause.  In the issue linked above this post, we just spent a little time down the wrong rabbit hole because we were focused on the `afterEvaluate` rather than the `configure`.  I just confirmed this is still the behavior in Gradle 4.0.

**Comment by oehme** [comment]
The configuration exception is the one that is displayed next to the "Build Failed" message. You should always look at that final message to know what failed your build.

The afterEvaluate failure is only logged further up.

I took the exact same example as the original poster:

```
afterEvaluate {
	throw new RuntimeException("afterEvaluate failure")
}

throw new RuntimeException("configure failure")
```

And it prints 
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/oehme/git/foo/build.gradle' line: 5

* What went wrong:
A problem occurred evaluating root project 'foo'.
> configure failure
```
As intended.

**Comment by oehme** [comment]
I think users might be confused by the message " but primary configuration failure takes precedence". That message is saying: "What follows is the secondary failure, look further down for the primary failure", but it seems users mistake it for "This is the primary failure". So we might just want to reword that log message to explicitly say "Look at the end of your build log".

**Comment by nedtwigg** [comment]
Hmm, you must have different `gradle.properties` than me or something.  Here's the output I get for this example, verbatim:

````
cmd> gradlew tasks
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.RuntimeException: afterEvaluate failure
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
        at build_664ackrz1vh85b6dwwipfir43$_run_closure1.doCall(C:\Users\ntwigg\Documents\dev\durian-rx\build.gradle:2)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
        at groovy.lang.Closure.call(Closure.java:414)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:221)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:145)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:315)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:225)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:138)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:35)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy22.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:82)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:76)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:648)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:126)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:36)
        at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:207)
        at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:204)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:146)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:112)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:95)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\ntwigg\Documents\dev\durian-rx\build.gradle' line: 5

* What went wrong:
A problem occurred evaluating root project 'durian-rx'.
> configure failure

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

So I get the full stacktrace for the *secondary* exception, but I have to ask pretty-please to find the cause of the *primary* exception.  It naturally invites users to start digging through the secondary exception rather than the primary.  "Look down below for the real reason" would help, but not as much as just showing the real reason first.

I would expect any exception during configuration to kill the whole build - why does it continue?  I'm sure there's a bigger context that I'm missing.

**Comment by oehme** [comment]
> "Look down below for the real reason" would help, but not as much as just showing the real reason first.

The bottom of the output is the first thing a user sees, not the top. The top has already scrolled past. I agree that the secondary failure should not have a stacktrace by default.

**Comment by nedtwigg** [comment]
> The bottom of the output is the first thing a user sees

Ahhh, you're correct!  The stack trace for the secondary is so loud, I think it draws the user's attention and seems like it's the first thing, but I now agree with you that it belongs at the bottom where it is.

**Comment by jjohannes** [comment]
PR to improve this by respecting `--stacktrace` for the secondary failure: #2751
