### ISSUE TITLE
JUnit Platform runner classloading issue

### ISSUE THREAD

**Issue by bsideup** [gradle/gradle#8806]
If the user adds an implementation of JUnit Runner's `TestExecutionListener` to a `testRuntime` scope, the tests fail to start with:
```
Caused by: java.lang.NoClassDefFoundError: org/junit/platform/launcher/TestExecutionListener
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1209)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:60)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$100(JUnitPlatformTestClassProcessor.java:77)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:73)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	... 25 more
```

### Expected Behavior
The execution does not fail

### Current Behavior
It fails due to a classloading issue.

### Context
The [library we develop](https://github.com/reactor/BlockHound/tree/master/junit-platform) provides a listener, but we didn't want to have a hard dependency on `org.junit.platform:junit-platform-launcher` (it is defined as `compileOnly`, should be absolutely valid and *works with Maven*)

### Steps to Reproduce (for bugs)
1. add `maven { url 'http://repo.spring.io/snapshot' }` repository
2. add `testCompile 'io.projectreactor.tools:blockhound-junit-platform:1.0.0.BUILD-SNAPSHOT'` dependency
3. run the tests (with Gradle)

### Your Environment
Java 8/11
Gradle 4.10.2
JUnit 5.4.0

**Comment by bsideup** [comment]
Note that it doesn't matter if the tests are running for the same module or the library with `TestExecutionListener` added to another project

**Comment by blindpirate** [comment]
Hi @bsideup. I may not understand you correctly.

> remove https://github.com/reactor/BlockHound/blob/78103921decead3c944de6ec2300bb5bafae73bb/junit-platform/build.gradle#L30

If you remove runtime dependency on `junit-platform-launcher`, isn't it normal to fail with `NoClassDefFoundError: org/junit/platform/launcher/TestExecutionListener`?

> 3. run the tests

Run which tests? I tried run `JUnitPlatformDynamicIntegrationTest` and `JUnitPlatformIntegrationTest` but they all fail:

```
java.lang.AssertionError: 
Expecting actual not to be null
```

**Comment by blindpirate** [comment]
I also tried `./gradlew test` and it starts pulling some really huge docker image so I had to Ctrl-C.

**Comment by bsideup** [comment]
Hi @blindpirate,

>  isn't it normal to fail

It isn't (and, for instance, Maven does not fail) because `junit-platform-launcher` is what runs the thing, and loads the mentioned class. Just, for some reason, it loads the listener in a separate `ClassLoader`, and the class loader does not see the class.

**Comment by bsideup** [comment]
@blindpirate regarding the Docker image - true, sorry, I forgot that the build requires Docker. Let me create a simple demo project to reproduce it

**Comment by bsideup** [comment]
@blindpirate updated "steps to reproduce"

**Comment by blindpirate** [comment]
@bsideup You removed the repo url in the "steps to reproduce". Still that repository or you created a simple demo project?

 Which `build.gradle` to add? How to run the tests? By running `./gradlew test` in the project directory? Or run `./gradlew junit-platform:test`? Can you please elaborate on it?

**Comment by bsideup** [comment]
@blindpirate I did not include "create a Gradle project, use JUnit Platform"-like steps because I thought it is obvious from the issue's description (and applies to *any* Gradle project with JUnit Platform)

**Comment by blindpirate** [comment]
@bsideup I don't think it's obvious because I'm not you, who fully understand what yourself are doing. I'm a beginner when trying to understand your work - plus, you said "you will create a simple demo project", so I was waiting for that simple demo.

I really want to see a demo instead of being instructed to create an empty project, adding some dependencies, writing some `any Gradle project with JUnit Platform`.

Can you please give me a minimum demo project?

**Comment by message** [comment]
@bsideup ping? You still referencing this ticket from Blockhound readme.
