### ISSUE TITLE
Scan plugin fails with Overlapping ID assignment exception

### ISSUE THREAD

**Issue by sacchettom** [gradle/gradle#8849]
Build scan plugin 1.16 with Gradle 4.10.3 going to a gradle enterprise server.
The scan plugin and its configuration are  being applied through an internal plugin.
In one of our projects the scan consistently fails to generate and gives the following stacktrace:
```
build	22-Mar-2019 01:32:54	A build scan cannot be produced as an error occurred gathering build data.
build	22-Mar-2019 01:32:54	Please report this problem via https://REDACTED/help and include the following via copy/paste:
build	22-Mar-2019 01:32:54	
build	22-Mar-2019 01:32:54	----------
build	22-Mar-2019 01:32:54	Gradle version: 4.10.3
build	22-Mar-2019 01:32:54	Plugin version: 1.16
build	22-Mar-2019 01:32:54	
build	22-Mar-2019 01:32:54	java.lang.IllegalStateException: Overlapping ID assignment for com.gradle.scan.plugin.internal.a.f.e@3836329e (prev: -1870070182277941567)
build	22-Mar-2019 01:32:54		at com.gradle.scan.plugin.internal.e.a.a(SourceFile:19)
build	22-Mar-2019 01:32:54		at com.gradle.scan.plugin.internal.e.j.a(SourceFile:24)
build	22-Mar-2019 01:32:54		at com.gradle.scan.plugin.internal.e.h.<init>(SourceFile:10)
build	22-Mar-2019 01:32:54		at com.gradle.scan.plugin.internal.a.f.g$a.<init>(SourceFile:44)
build	22-Mar-2019 01:32:54		at com.gradle.scan.plugin.internal.a.f.g$1.a(SourceFile:58)
build	22-Mar-2019 01:32:54		at com.gradle.scan.plugin.internal.a.f.g$1.a(SourceFile:49)
build	22-Mar-2019 01:32:54		at com.gradle.scan.plugin.internal.i.d.a(SourceFile:23)
build	22-Mar-2019 01:32:54		at com.gradle.scan.plugin.internal.i.k.a(SourceFile:45)
build	22-Mar-2019 01:32:54		at com.gradle.scan.plugin.internal.i.k.a(SourceFile:39)
build	22-Mar-2019 01:32:54		at com.gradle.scan.plugin.internal.i.k.a(SourceFile:17)
build	22-Mar-2019 01:32:54		at com.gradle.scan.plugin.internal.i.o.a(SourceFile:33)
build	22-Mar-2019 01:32:54		at com.gradle.scan.plugin.internal.i.h.a(SourceFile:56)
build	22-Mar-2019 01:32:54		at com.gradle.scan.plugin.internal.i.i$c$1.started(SourceFile:33)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.notify.BuildOperationNotificationBridge$ReplayAndAttachListener.started(BuildOperationNotificationBridge.java:329)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.notify.BuildOperationNotificationBridge$Adapter.started(BuildOperationNotificationBridge.java:212)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.DefaultBuildOperationListenerManager$ProgressShieldingBuildOperationListener.started(DefaultBuildOperationListenerManager.java:115)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.DefaultBuildOperationListenerManager$1.started(DefaultBuildOperationListenerManager.java:44)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:167)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
build	22-Mar-2019 01:32:54		at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:524)
build	22-Mar-2019 01:32:54		at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:509)
build	22-Mar-2019 01:32:54		at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1800(DefaultConfiguration.java:123)
build	22-Mar-2019 01:32:54		at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationResolvableDependencies.assertArtifactsResolved(DefaultConfiguration.java:1270)
build	22-Mar-2019 01:32:54		at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationResolvableDependencies.access$3000(DefaultConfiguration.java:1159)
build	22-Mar-2019 01:32:54		at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationResolvableDependencies$LenientResolutionResult.resolve(DefaultConfiguration.java:1285)
build	22-Mar-2019 01:32:54		at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationResolvableDependencies$LenientResolutionResult.getAllDependencies(DefaultConfiguration.java:1304)
build	22-Mar-2019 01:32:54		at nebula.plugin.resolutionrules.AlignRules.selectedVersions(alignRule.kt:188)
build	22-Mar-2019 01:32:54		at nebula.plugin.resolutionrules.AlignRules.baselineAligns(alignRule.kt:115)
build	22-Mar-2019 01:32:54		at nebula.plugin.resolutionrules.AlignRules.apply(alignRule.kt:99)
build	22-Mar-2019 01:32:54		at nebula.plugin.resolutionrules.ResolutionRulesPlugin$apply$1$$special$$inlined$onResolve$1.execute(configurations.kt:22)
build	22-Mar-2019 01:32:54		at nebula.plugin.resolutionrules.ResolutionRulesPlugin$apply$1$$special$$inlined$onResolve$1.execute(configurations.kt)
build	22-Mar-2019 01:32:54		at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
build	22-Mar-2019 01:32:54		at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
build	22-Mar-2019 01:32:54		at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
build	22-Mar-2019 01:32:54		at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
build	22-Mar-2019 01:32:54		at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
build	22-Mar-2019 01:32:54		at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
build	22-Mar-2019 01:32:54		at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
build	22-Mar-2019 01:32:54		at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
build	22-Mar-2019 01:32:54		at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
build	22-Mar-2019 01:32:54		at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
build	22-Mar-2019 01:32:54		at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
build	22-Mar-2019 01:32:54		at com.sun.proxy.$Proxy27.beforeResolve(Unknown Source)
build	22-Mar-2019 01:32:54		at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.performPreResolveActions(DefaultConfiguration.java:582)
build	22-Mar-2019 01:32:54		at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$500(DefaultConfiguration.java:123)
build	22-Mar-2019 01:32:54		at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$5.run(DefaultConfiguration.java:531)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
build	22-Mar-2019 01:32:54		at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:524)
build	22-Mar-2019 01:32:54		at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:509)
build	22-Mar-2019 01:32:54		at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1800(DefaultConfiguration.java:123)
build	22-Mar-2019 01:32:54		at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationTaskDependency.visitDependencies(DefaultConfiguration.java:1514)
build	22-Mar-2019 01:32:54		at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:96)
build	22-Mar-2019 01:32:54		at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmpyEdges.getNodeValues(CachingDirectedGraphWalker.java:211)
build	22-Mar-2019 01:32:54		at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:121)
build	22-Mar-2019 01:32:54		at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:73)
build	22-Mar-2019 01:32:54		at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:64)
build	22-Mar-2019 01:32:54		at org.gradle.execution.taskgraph.TaskDependencyResolver.resolveDependenciesFor(TaskDependencyResolver.java:46)
build	22-Mar-2019 01:32:54		at org.gradle.execution.taskgraph.LocalTaskInfo.getDependencies(LocalTaskInfo.java:89)
build	22-Mar-2019 01:32:54		at org.gradle.execution.taskgraph.LocalTaskInfo.resolveDependencies(LocalTaskInfo.java:62)
build	22-Mar-2019 01:32:54		at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.addToTaskGraph(DefaultTaskExecutionPlan.java:168)
build	22-Mar-2019 01:32:54		at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.addTasks(DefaultTaskExecutionGraph.java:126)
build	22-Mar-2019 01:32:54		at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:47)
build	22-Mar-2019 01:32:54		at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
build	22-Mar-2019 01:32:54		at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
build	22-Mar-2019 01:32:54		at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
build	22-Mar-2019 01:32:54		at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:44)
build	22-Mar-2019 01:32:54		at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
build	22-Mar-2019 01:32:54		at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
build	22-Mar-2019 01:32:54		at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
build	22-Mar-2019 01:32:54		at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:47)
build	22-Mar-2019 01:32:54		at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
build	22-Mar-2019 01:32:54		at org.gradle.execution.DefaultBuildConfigurationActionExecuter.select(DefaultBuildConfigurationActionExecuter.java:36)
build	22-Mar-2019 01:32:54		at org.gradle.initialization.DefaultGradleLauncher$CalculateTaskGraph.run(DefaultGradleLauncher.java:305)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
build	22-Mar-2019 01:32:54		at org.gradle.initialization.DefaultGradleLauncher.constructTaskGraph(DefaultGradleLauncher.java:190)
build	22-Mar-2019 01:32:54		at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:145)
build	22-Mar-2019 01:32:54		at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:124)
build	22-Mar-2019 01:32:54		at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:77)
build	22-Mar-2019 01:32:54		at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:74)
build	22-Mar-2019 01:32:54		at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:154)
build	22-Mar-2019 01:32:54		at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:38)
build	22-Mar-2019 01:32:54		at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:96)
build	22-Mar-2019 01:32:54		at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:74)
build	22-Mar-2019 01:32:54		at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
build	22-Mar-2019 01:32:54		at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
build	22-Mar-2019 01:32:54		at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
build	22-Mar-2019 01:32:54		at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.run(RunAsBuildOperationBuildActionRunner.java:50)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
build	22-Mar-2019 01:32:54		at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
build	22-Mar-2019 01:32:54		at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45)
build	22-Mar-2019 01:32:54		at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
build	22-Mar-2019 01:32:54		at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
build	22-Mar-2019 01:32:54		at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:44)
build	22-Mar-2019 01:32:54		at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:79)
build	22-Mar-2019 01:32:54		at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:44)
build	22-Mar-2019 01:32:54		at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
build	22-Mar-2019 01:32:54		at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
build	22-Mar-2019 01:32:54		at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
build	22-Mar-2019 01:32:54		at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
build	22-Mar-2019 01:32:54		at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
build	22-Mar-2019 01:32:54		at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:62)
build	22-Mar-2019 01:32:54		at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34)
build	22-Mar-2019 01:32:54		at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
build	22-Mar-2019 01:32:54		at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
build	22-Mar-2019 01:32:54		at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
build	22-Mar-2019 01:32:54		at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
build	22-Mar-2019 01:32:54		at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
build	22-Mar-2019 01:32:54		at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
build	22-Mar-2019 01:32:54		at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
build	22-Mar-2019 01:32:54		at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
build	22-Mar-2019 01:32:54		at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46)
build	22-Mar-2019 01:32:54		at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
build	22-Mar-2019 01:32:54		at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:52)
build	22-Mar-2019 01:32:54		at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:207)
build	22-Mar-2019 01:32:54		at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:402)
build	22-Mar-2019 01:32:54		at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:375)
build	22-Mar-2019 01:32:54		at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:37)
build	22-Mar-2019 01:32:54		at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:23)
build	22-Mar-2019 01:32:54		at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:368)
build	22-Mar-2019 01:32:54		at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:298)
build	22-Mar-2019 01:32:54		at org.gradle.launcher.Main.doAction(Main.java:36)
build	22-Mar-2019 01:32:54		at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
build	22-Mar-2019 01:32:54		at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
build	22-Mar-2019 01:32:54		at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
build	22-Mar-2019 01:32:54		at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
build	22-Mar-2019 01:32:54		at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
build	22-Mar-2019 01:32:54		at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
build	22-Mar-2019 01:32:54		at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
build	22-Mar-2019 01:32:54	
```

**Comment by facewindu** [comment]
Hi @sacchettom 
Could you try this on recent build scan plugin / Gradle version ? Is this still happening ?

**Comment by sacchettom** [comment]
@facewindu we have the problem up to gradle 5.6.2 with plugin 2.3. Couldn't try more recent versions (I saw the changelog of 2.4.1 being related) as we're waiting for the update to 2.3 of our internal gradle enterprise server. We found the issue to happen when using resolution rules to perform dependencies versions alignment, as it occurred whenever such a rule happened to do some work - switching to using virtual platforms for the same purpose was the workaround for us.

**Comment by jjohannes** [comment]
@sacchettom Gradle 5.6.3 was just release and contains a backport of a fix that could be the root cause. Can you give it a try?

**Comment by sacchettom** [comment]
@jjohannes confirmed the issue still exists with 5.6.3 and scan plugin 2.3 (I can't try 2.4+ yet, sorry).
Tested this in the tests for an aggregator internal plugin that we use to set defaults for a number of internal libraries we produce, we had added a specific test to check this behaviour.
The test applies the nebula resolution plugin, with a set of rules specific to our projects that get translated into gradle resolution rules by the plugin. We then set 2 dependencies in the implementation configuration that will trigger one of the alignment rules (in our case we pass two different minors of some akka libraries).
I can confirm the issue still arises with the mentioned versions. The issue goes away when we set the system property `-Dnebula.features.coreAlignmentSupport=true`, which makes the nebula resolution rules plugin generate alignment rules as virtual platforms rather than normal resolution rules.

**Comment by sacchettom** [comment]
We finally had our internal gradle enterprise server updated to version 2019.3.2. Ran a test build with gradle 5.6.3 and plugin 2.4.2 with alignment rules set by the nebula resolution plugins. The issue with alignment rules (when not passed in as virtual platform) persists even if in a different form.

```
    |      ----------
    |      Gradle version: 5.6.3
    |      Plugin version: 2.4.2
    |
    |      java.lang.IllegalStateException: Attempt to dispose ID for 'com.gradle.scan.plugin.internal.a.e.g@74905a23' without previously assigning ID.
    |           at com.gradle.scan.plugin.internal.g.a.e(SourceFile:122)
    |           at com.gradle.scan.plugin.internal.g.f.c(SourceFile:28)
    |           at com.gradle.scan.plugin.internal.a.e.i.a(SourceFile:172)
    |           at com.gradle.scan.plugin.internal.j.a.f.a(SourceFile:12)
    |           at com.gradle.scan.plugin.internal.j.a$c.finished(SourceFile:154)
    |           at com.gradle.scan.plugin.internal.j.a.a(SourceFile:65)
    |           at com.gradle.scan.plugin.internal.j.i.a(SourceFile:58)
    |           at com.gradle.scan.plugin.internal.j.d.a(SourceFile:103)
    |           at com.gradle.scan.plugin.internal.j.f.a(SourceFile:48)
    |           at com.gradle.scan.plugin.internal.o.a$a.a(SourceFile:31)
    |           at com.gradle.scan.plugin.internal.o.a$a.a(SourceFile:20)
    |           at com.gradle.scan.plugin.internal.o.a.c(SourceFile:61)
```
