### ISSUE TITLE
Multiple buildSrc in different composite builds breaks the IntelliJ IDEA import

### ISSUE THREAD

**Issue by GFriedrich** [gradle/gradle#8920]
When having a root project with two included composite build projects and each of these projects uses a "buildSrc" folder, the import of the main project via IntelliJ IDEA fails.

### Expected Behavior
The import/sync should run without an issue.

### Current Behavior
The import/sync of the Gradle project fails.

### Steps to Reproduce 
Have a project A including two other composite build projects B and C.
B and C should have a buildSrc folder.
Importing/running sync in IntelliJ IDEA fails due to:
```
Caused by: java.lang.IllegalArgumentException: Duplicate root element buildSrc
	at org.gradle.plugins.ide.internal.configurer.HierarchicalElementDeduplicator$StatefulDeduplicator.deduplicate(HierarchicalElementDeduplicator.java:122)
	at org.gradle.plugins.ide.internal.configurer.HierarchicalElementDeduplicator$StatefulDeduplicator.calculateNewNames(HierarchicalElementDeduplicator.java:102)
	at org.gradle.plugins.ide.internal.configurer.HierarchicalElementDeduplicator$StatefulDeduplicator.getNewNames(HierarchicalElementDeduplicator.java:89)
	at org.gradle.plugins.ide.internal.configurer.HierarchicalElementDeduplicator$StatefulDeduplicator.access$100(HierarchicalElementDeduplicator.java:73)
	at org.gradle.plugins.ide.internal.configurer.HierarchicalElementDeduplicator.deduplicate(HierarchicalElementDeduplicator.java:67)
	at org.gradle.plugins.ide.internal.configurer.DefaultUniqueProjectNameProvider.getDeduplicatedNames(DefaultUniqueProjectNameProvider.java:44)
	at org.gradle.plugins.ide.internal.configurer.DefaultUniqueProjectNameProvider.getUniqueName(DefaultUniqueProjectNameProvider.java:34)
	at org.gradle.plugins.ide.idea.IdeaPlugin.configureIdeaModule(IdeaPlugin.java:265)
	at org.gradle.plugins.ide.idea.IdeaPlugin.onApply(IdeaPlugin.java:136)
```
As far as I can see, during the import/sync the IDEA plugin of Gradle gets included to all builds to gather the Gradle model for projects. But obviously the plugin can't handle multiple buildSrc folders.

### Your Environment
Gradle 5.3.1

**Comment by GFriedrich** [comment]
I great - I've found a workaroud:
Placing a `settings.gradle` file within the `buildSrc` folder to overwrite the `rootProject.name` fixes the issue. Hopefully this doesn't end up in new issues elsewhere. ;)

**Comment by big-guy** [comment]
@GFriedrich do you know if this used to work with an earlier version of Gradle or IDEA?

**Comment by GFriedrich** [comment]
@big-guy: No, otherwise I would have created a regression issue.

**Comment by JojOatXGME** [comment]
I could not reproduce it on Windows but a colleague had the same problem on Mac. I'm just wondering if the bug might be platform dependent. However, it would seem suspect to me if this behavior depends on the operating system. Anyway, did you encounter the issue on Windows or on another operating system?

**Comment by GFriedrich** [comment]
I've experienced the issue on Windows and Linux.

**Comment by JojOatXGME** [comment]
There was some leftover of a **buildSrc** on the Mac. After deleting it, the problem did not occur anymore. Interestingly, there are still multiple other **buildSrc** directories within the composite build which do not cause the problem.

**Comment by wayonEmes** [comment]
> Oh great - I've found a workaroud:
> Placing a `settings.gradle` file within the `buildSrc` folder to overwrite the `rootProject.name` fixes the issue. Hopefully this doesn't end up in new issues elsewhere. 😉

thanks . I don't know why, but it works.

**Comment by GFriedrich** [comment]
Just checked and at least with latest IntelliJ IDEA and Gradle 6.5.1 (or higher) this is not happening anylonger.
Therefore I'm closing the ticket...
