### ISSUE TITLE
Grudle deamon error

### ISSUE THREAD

**Issue by BDAinc** [gradle/gradle#9017]
Hello. I'm trying to solve the gradle launch problem for the second week and can't find a solution

gradle --stacktrace
```
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/4.4.1/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.ExceptionInInitializerError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org


* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleException: Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/4.4.1/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.ExceptionInInitializerError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

	at org.gradle.launcher.daemon.bootstrap.DaemonGreeter.parseDaemonOutput(DaemonGreeter.java:34)
	at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startProcess(DefaultDaemonStarter.java:152)
	at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startDaemon(DefaultDaemonStarter.java:135)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.doStartDaemon(DefaultDaemonConnector.java:210)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.startDaemon(DefaultDaemonConnector.java:204)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connect(DefaultDaemonConnector.java:128)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:138)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:92)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:291)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:264)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:33)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:257)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:191)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)


```

Whats problem? How solve?(((

**Comment by ljacomet** [comment]
Can you try running your build with `--no-daemon` and see what happens?
Could you be affected by #3117 or #7448?

**Comment by big-guy** [comment]
@BDAinc Can you run `gradle -version`?

**Comment by BDAinc** [comment]
> @BDAinc Can you run `gradle -version`?

------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------

Build time:   2012-12-21 00:00:00 UTC
Revision:     none

Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.10.5 compiled on August 27 2018
JVM:          1.8.0_201 (Oracle Corporation 25.201-b09)
OS:           Linux 4.20.11-042011-generic amd64

**Comment by BDAinc** [comment]
> Can you try running your build with `--no-daemon` and see what happens?
> Could you be affected by #3117 or #7448?

 
FAILURE: Build failed with an exception.

* What went wrong:
java.lang.ExceptionInInitializerError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
((((

**Comment by big-guy** [comment]
@BDAinc I think you're running into the same thing as here: https://github.com/gradle/gradle/issues/7831#issuecomment-442652048

You're using a version of Gradle that was built somewhere else and has custom patches to it. I suspect you're installing the default from Debian, which has this problem.

Please install Gradle from one of our official locations: https://gradle.org/install/

**Comment by BDAinc** [comment]
> @BDAinc I think you're running into the same thing as here: [#7831 (comment)](https://github.com/gradle/gradle/issues/7831#issuecomment-442652048)
> 
> You're using a version of Gradle that was built somewhere else and has custom patches to it. I suspect you're installing the default from Debian, which has this problem.
> 
> Please install Gradle from one of our official locations: https://gradle.org/install/

thx for you help

I unpacked the archive as specified in the installation instructions, run the command export PATH=$PATH:/opt/gradle/gradle-5.4/bin

gradle-v check still shows version 4.4.1

what's wrong?

**Comment by BDAinc** [comment]
> > @BDAinc I think you're running into the same thing as here: [#7831 (comment)](https://github.com/gradle/gradle/issues/7831#issuecomment-442652048)
> > You're using a version of Gradle that was built somewhere else and has custom patches to it. I suspect you're installing the default from Debian, which has this problem.
> > Please install Gradle from one of our official locations: https://gradle.org/install/
> 
> thx for you help
> 
> I unpacked the archive as specified in the installation instructions, run the command export PATH=$PATH:/opt/gradle/gradle-5.4/bin
> 
> gradle-v check still shows version 4.4.1
> 
> what's wrong?

so I changed it .bashrc adding export PATH=$PATH:/opt/gradle/gradle-5.4/bin

the version is still old

**Comment by pzygielo** [comment]
change order to
```
export PATH=/opt/gradle/gradle-5.4/bin:$PATH
```
otherwise (i.e for `PATH=$PATH:/opt/gradle/gradle-5.4/bin`) the first binary - if there is any in `$PATH` - is selected

**Comment by BDAinc** [comment]
> change order to
> 
> ```
> export PATH=/opt/gradle/gradle-5.4/bin:$PATH
> ```
> otherwise (i.e for `PATH=$PATH:/opt/gradle/gradle-5.4/bin`) the first binary - if there is any in `$PATH` - is selected

its work! but i see new problem

i run command cordova build and see

```
hecking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=/usr/lib/android-sdk (DEPRECATED)
Subproject Path: CordovaLib
Subproject Path: app
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :app
WARNING: The specified Android SDK Build Tools version (24.0.0) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.3.0.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '24.0.0'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Observed package id 'build-tools;24.0.0' in inconsistent location '/usr/lib/android-sdk/build-tools/debian' (Expected '/usr/lib/android-sdk/build-tools/24.0.0')
Already observed package id 'build-tools;24.0.0' in '/usr/lib/android-sdk/build-tools/24.0.0'. Skipping duplicate at '/usr/lib/android-sdk/build-tools/debian'
Observed package id 'build-tools;24.0.0' in inconsistent location '/usr/lib/android-sdk/build-tools/debian' (Expected '/usr/lib/android-sdk/build-tools/24.0.0')
Already observed package id 'build-tools;24.0.0' in '/usr/lib/android-sdk/build-tools/24.0.0'. Skipping duplicate at '/usr/lib/android-sdk/build-tools/debian'
Observed package id 'build-tools;24.0.0' in inconsistent location '/usr/lib/android-sdk/build-tools/debian' (Expected '/usr/lib/android-sdk/build-tools/24.0.0')
Already observed package id 'build-tools;24.0.0' in '/usr/lib/android-sdk/build-tools/24.0.0'. Skipping duplicate at '/usr/lib/android-sdk/build-tools/debian'
File /home/anonim/.android/repositories.cfg could not be loaded.
Checking the license for package Android SDK Build-Tools 28.0.3 in /usr/lib/android-sdk/licenses
Warning: License for package Android SDK Build-Tools 28.0.3 not accepted.
Checking the license for package Android SDK Platform 28 in /usr/lib/android-sdk/licenses
Warning: License for package Android SDK Platform 28 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;28.0.3 Android SDK Build-Tools 28.0.3
     platforms;android-28 Android SDK Platform 28
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
  
  Using Android SDK: /usr/lib/android-sdk

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 44s
/media/anonim/01D4C6F2C6169120/PROJECTS/PLANSTER/PRODUCTIONS/MOBILE/Planster31/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;28.0.3 Android SDK Build-Tools 28.0.3
     platforms;android-28 Android SDK Platform 28
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
  
  Using Android SDK: /usr/lib/android-sdk

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

```
