### ISSUE TITLE
Set permissions when creating files during unpacking

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#9138]
From https://github.com/gradle/task-output-cache/issues/42#issuecomment-319097203:

> Okay, so it _is_ possible to set file permissions when creating the file via Java 7 APIs, and it's fast:
> 
> ```groovy
> def attributes = PosixFilePermissions.asFileAttribute(permissions)
> Files.createFile(path, attributes)
> ```
> 
> ![image](https://user-images.githubusercontent.com/495366/28784244-1b41313c-7613-11e7-9d65-7ad885d4e36a.png)

However, Windows does not support doing this. :(

```text
java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
    at sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(WindowsSecurityDescriptor.java:358)
    at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:221)
    at java.nio.file.Files.newByteChannel(Files.java:317)
    at org.gradle.caching.internal.tasks.TarTaskOutputPacker.unpackPropertyEntry(TarTaskOutputPacker.java:342)
```

**Comment by lptr** [comment]
We should probably do this at some point.
