### ISSUE TITLE
Could not set the value of environment variable

### ISSUE THREAD

**Issue by William-HL1991** [gradle/gradle#9176]
my gradle version is 3.4.1
when i compile my andropid poject., received a failure:

`019-04-19 11:20:46 11:20:46.760 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientInputForwarder] Dispatching close input message: org.gradle.launcher.daemon.protocol.CloseInput@28c3c3fa
2019-04-19 11:20:46 11:20:46.760 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 28: dispatching class org.gradle.launcher.daemon.protocol.CloseInput
2019-04-19 11:20:46 11:20:46.778 [INFO] [org.gradle.launcher.daemon.client.DaemonClient] Received result Failure[value=net.rubygrapefruit.platform.NativeException: Could not set the value of environment variable 'AGILE_PIPELINE_NAME': could not convert string to current locale] from daemon DaemonInfo{pid=15358, address=[1d89bddd-4ed1-4f41-8fe5-03cd0a44e163 port:46553, addresses:[/127.0.0.1]], state=Busy, lastBusy=1555644046656, context=DefaultDaemonContext[uid=547c64e2-64e2-47ec-b944-5baacf2ed93e,javaHome=/usr/java/jdk1.8.0_51,daemonRegistryDir=/home/client/.gradle/daemon,pid=15358,idleTimeout=120000,daemonOpts=-XX:MaxPermSize=512m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx4096M,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be done).
2019-04-19 11:20:46 11:20:46.778 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: dispatching class org.gradle.launcher.daemon.protocol.Finished
2019-04-19 11:20:46 11:20:46.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2019-04-19 11:20:46 11:20:46.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
2019-04-19 11:20:46 11:20:46.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2019-04-19 11:20:46 11:20:46.783 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
2019-04-19 11:20:46 11:20:46.783 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Could not set the value of environment variable 'AGILE_PIPELINE_NAME': could not convert string to current locale
2019-04-19 11:20:46 11:20:46.783 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2019-04-19 11:20:46 11:20:46.783 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
2019-04-19 11:20:46 11:20:46.783 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] net.rubygrapefruit.platform.NativeException: Could not set the value of environment variable 'AGILE_PIPELINE_NAME': could not convert string to current locale
2019-04-19 11:20:46 11:20:46.784 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at net.rubygrapefruit.platform.internal.DefaultProcess.setEnvironmentVariable(DefaultProcess.java:71)
2019-04-19 11:20:46 11:20:46.784 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at net.rubygrapefruit.platform.internal.WrapperProcess.setEnvironmentVariable(WrapperProcess.java:84)
2019-04-19 11:20:46 11:20:46.784 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.nativeintegration.processenvironment.NativePlatformBackedProcessEnvironment.setNativeEnvironmentVariable(NativePlatformBackedProcessEnvironment.java:36)
2019-04-19 11:20:46 11:20:46.784 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.nativeintegration.processenvironment.AbstractProcessEnvironment.setEnvironmentVariable(AbstractProcessEnvironment.java:66)
2019-04-19 11:20:46 11:20:46.784 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.nativeintegration.processenvironment.AbstractProcessEnvironment.maybeSetEnvironment(AbstractProcessEnvironment.java:40)
2019-04-19 11:20:46 11:20:46.784 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:65)
2019-04-19 11:20:46 11:20:46.784 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
2019-04-19 11:20:46 11:20:46.784 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
2019-04-19 11:20:46 11:20:46.784 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
2019-04-19 11:20:46 11:20:46.784 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
2019-04-19 11:20:46 11:20:46.784 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
2019-04-19 11:20:46 11:20:46.784 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
2019-04-19 11:20:46 11:20:46.784 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2019-04-19 11:20:46 11:20:46.784 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2019-04-19 11:20:46 11:20:46.784 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.lang.Thread.run(Thread.java:745)
2019-04-19 11:20:46 11:20:46.784 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
`
The environment variable 'AGILE_PIPELINE_NAME' is 
AGILE_PIPELINE_NAME=????????????
the other environment variable mybe has chinese characters

**Comment by big-guy** [comment]
Is it possible for you to try a newer version of Gradle? We've fixed some environment variable locale handling problems in 5.3 and newer.

**Comment by William-HL1991** [comment]
> Is it possible for you to try a newer version of Gradle? We've fixed some environment variable locale handling problems in 5.3 and newer.

thanks，i will try。

**Comment by big-guy** [comment]
Hi @William-HL1991 - I'm going to close this.  Please reopen if you are able to reproduce this with a newer version of Gradle (5.3+)
