### ISSUE TITLE
Java/JUnit: category class not found when using includeCategories/excludeCategories

### ISSUE THREAD

**Issue by Mobe91** [gradle/gradle#9193]
It seems that the test classpath is not properly propagated to the test worker process. I am using junit categories to filter the executed tests but the test execution fails with a ClassNotFoundException on the custom category interface.
When inspecting the ClassLoader in use when the exception occurs, no application specific paths that would point to the category interface are contained but only JRE jars.

Relevant part of my gradle configuration:
```
test {
    useJUnit {
        excludeCategories 'my.CustomCategory'
    }
}
```
Exception:
```
org.gradle.api.InvalidUserDataException: Can't load category class [my.CustomCategory].
	at org.gradle.api.internal.tasks.testing.junit.CategoryFilter.loadClass(CategoryFilter.java:127)
	at org.gradle.api.internal.tasks.testing.junit.CategoryFilter.verifyCategories(CategoryFilter.java:58)
	at org.gradle.api.internal.tasks.testing.junit.CategoryFilter.shouldRun(CategoryFilter.java:45)
	at org.spockframework.runtime.JUnitFilterAdapter.matches(JUnitFilterAdapter.java:36)
	at org.spockframework.runtime.model.SpecInfo.filterFeatures(SpecInfo.java:308)
	at org.spockframework.runtime.Sputnik.filter(Sputnik.java:69)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:98)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: my.CustomCategory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.gradle.api.internal.tasks.testing.junit.CategoryFilter.loadClass(CategoryFilter.java:125)
	... 33 more
```

### Your Environment
Gradle 5.4
Junit 4.12

**Comment by Mobe91** [comment]
Sorry, my mistake - wrong class name 🤦‍♂️
