### ISSUE TITLE
Zip nesting regression in Gradle 5.1 and later

### ISSUE THREAD

**Issue by Lanchon** [gradle/gradle#9204]
nesting zips does not work since Gradle 5.1 (tried up to 5.4):

```
def zip1 = project.tasks.register('zip1', Zip) {
  // whatever
}

def zip2 = project.tasks.register('zip2', Zip) {
  // whatever
  it.duplicatesStrategy = DuplicatesStrategy.FAIL
  it.from(zip1)
}
```

zip2 fails with "Encountered duplicate path "[zip1_filename]" during copy operation configured with DuplicatesStrategy.FAIL".

if the `duplicatesStrategy = DuplicatesStrategy.FAIL` line is removed, zip2 produces a strange zipfile that contains two copies of zip1 with the same pathname.

the workaround is:

```
def zip2 = project.tasks.register('zip2', Zip) {
  // whatever
  it.duplicatesStrategy = DuplicatesStrategy.FAIL
  //it.from(zip1)
  it.dependsOn zip1
  it.from(zip1.get().archivePath)
}
```

**Comment by Lanchon** [comment]
if you have trouble reproducing this issue, here's a real world case:
https://github.com/DexPatcher/dexpatcher-gradle/commit/44d3a997ab8a47cc9b278100a18a66b21c19156d

as explained, without `DuplicatesStrategy.FAIL` zip2 ends up containing two copies of zip1.
here is such a zip2 file: [app-components.aar.zip](https://github.com/gradle/gradle/files/3111315/app-components.aar.zip)

**Comment by lacasseio** [comment]
To speed up the triage of this issue, it would be much more beneficial if a self-contained example could be provided.

**Comment by Lanchon** [comment]
i'll try to help you with this.

**Comment by Lanchon** [comment]
here is a repro `build.gradle`:

```
// Zip nesting bug repo

// The regular zip task nests fine:

def zip1 = project.tasks.register('zip1', Zip) {
    destinationDirectory.set layout.projectDirectory
    archiveBaseName.set 'zip1'
    from 'build.gradle'
}

// This extended zip task fails to nest, seemingly registering its output file twice:

class TestZipTask extends Zip {
    @Override @OutputFile File getArchivePath() {
        super.getArchivePath()
    }
}

def testZip1 = project.tasks.register('testZip1', TestZipTask) {
    destinationDirectory.set layout.projectDirectory
    archiveBaseName.set 'testZip1'
    from 'build.gradle'
}

// Run this task to get the error:

def zip2 = project.tasks.register('zip2', Zip) {
    destinationDirectory.set layout.projectDirectory
    archiveBaseName.set 'z2'
    duplicatesStrategy = DuplicatesStrategy.FAIL
    from zip1       // no error
    from testZip1   // DuplicateFileCopyingException: Encountered duplicate path "lazyZip1.zip" during copy operation configured with DuplicatesStrategy.FAIL
}
```

interestingly, for the zip task to somehow register its output twice, its `archivePath` getter has to be overridden.

FYI, here is the full stack trace:

```
$ gradle zip2 -s
> Task :zip2 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':zip2'.
> Encountered duplicate path "testZip1.zip" during copy operation configured with DuplicatesStrategy.FAIL

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':zip2'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:151)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:148)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:141)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:75)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.file.DuplicateFileCopyingException: Encountered duplicate path "testZip1.zip" during copy operation configured with DuplicatesStrategy.FAIL
        at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator$1$1.processFile(DuplicateHandlingCopyActionDecorator.java:53)
        at org.gradle.api.internal.file.copy.CopyFileVisitorImpl.processFile(CopyFileVisitorImpl.java:62)
        at org.gradle.api.internal.file.copy.CopyFileVisitorImpl.visitFile(CopyFileVisitorImpl.java:46)
        at org.gradle.api.internal.file.collections.AbstractSingletonFileTree.visit(AbstractSingletonFileTree.java:36)
        at org.gradle.api.internal.file.collections.FileTreeAdapter.visit(FileTreeAdapter.java:118)
        at org.gradle.api.internal.file.CompositeFileTree.visit(CompositeFileTree.java:93)
        at org.gradle.api.internal.file.copy.CopySpecActionImpl.execute(CopySpecActionImpl.java:39)
        at org.gradle.api.internal.file.copy.CopySpecActionImpl.execute(CopySpecActionImpl.java:24)
        at org.gradle.api.internal.file.copy.DefaultCopySpec$DefaultCopySpecResolver.walk(DefaultCopySpec.java:693)
        at org.gradle.api.internal.file.copy.DefaultCopySpec$DefaultCopySpecResolver.walk(DefaultCopySpec.java:695)
        at org.gradle.api.internal.file.copy.DefaultCopySpec.walk(DefaultCopySpec.java:499)
        at org.gradle.api.internal.file.copy.CopySpecBackedCopyActionProcessingStream.process(CopySpecBackedCopyActionProcessingStream.java:38)
        at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator$1.process(DuplicateHandlingCopyActionDecorator.java:44)
        at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator$1.process(NormalizingCopyActionDecorator.java:57)
        at org.gradle.api.internal.file.archive.ZipCopyAction$1.execute(ZipCopyAction.java:85)
        at org.gradle.api.internal.file.archive.ZipCopyAction$1.execute(ZipCopyAction.java:83)
        at org.gradle.internal.IoActions.withResource(IoActions.java:77)
        at org.gradle.api.internal.file.archive.ZipCopyAction.execute(ZipCopyAction.java:83)
        at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator.execute(NormalizingCopyActionDecorator.java:53)
        at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator.execute(DuplicateHandlingCopyActionDecorator.java:42)
        at org.gradle.api.internal.file.copy.CopyActionExecuter.execute(CopyActionExecuter.java:40)
        at org.gradle.api.tasks.AbstractCopyTask.copy(AbstractCopyTask.java:179)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:702)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:669)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:404)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:393)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:376)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:213)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:201)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:77)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:120)
        ... 35 more


* Get more help at https://help.gradle.org

BUILD FAILED in 0s
3 actionable tasks: 1 executed, 2 up-to-date
```

**Comment by Lanchon** [comment]
the zip subclass is there to provide needed laziness in a way that works with both Gradle 4.10 and 5.1+. take a look:
https://github.com/DexPatcher/dexpatcher-gradle/blob/v2/src/main/groovy/lanchon/dexpatcher/gradle/tasks/LazyZipTask.groovy

obviously i need to replace the `@OutputFile` annotation with `@Internal` and programmaticaly register `getArchivePath()` as output file only if running on Gradle < 5.1 so as to not break the task.

how do i go about reproducing the functionality of the `@OutputFile` annotation in code?

thanks!

**Comment by big-guy** [comment]
You don't need the annotation.  The output file annotation exists on `AbstractArchiveTask#getArchiveFile()`.  By adding it back to `getArchivePath`, you're saying there are _two_ outputs to the Zip task and that's why you're getting duplicates (they both point to the same file).

I'm not sure you need the custom Zip task at all. If you continued to use the old API, I think things would have still worked.  Extending the Zip task or using convention mapping is what causes https://github.com/gradle/gradle/issues/8401

**Comment by Lanchon** [comment]
for future tasks you might convert to the lazy API, it looks like the only way to provide forward and backward compatibility involving subclassing is to blacklist old fields through some mechanism that is not annotations, instead of simply changing the annotations.

even so, if somebody subclassed a task, purposely removing a property annotation and exposed its content through some other new annotated property, you again got a failure. so a blacklist is not foolproof.

**Comment by Lanchon** [comment]
> You don't need the annotation

yes i need it. `AbstractArchiveTask#getArchiveFile()` does not exist in Gradle <5.1. the whole point of subclassing Zip is, again, to provide needed laziness in a way that works with both Gradle 4.10 and 5.1+.

> I'm not sure you need the custom Zip task at all. If you continued to use the old API, I think things would have still worked.

the <5.1 zip api never worked for me, i needed laziness from the get go. so i subclassed the getters in 4.10 and everything was fine. when you converted the zip class to lazy in 5.1 you broke compatibility with users who subclassed. this is a well-known reported issue: #8401

so to work around the breakage in 5.1, and keep laziness AND compatibility with 4.10 and 5.1, i needed the contraption linked here:
https://github.com/DexPatcher/dexpatcher-gradle/blob/v2/src/main/groovy/lanchon/dexpatcher/gradle/tasks/LazyZipTask.groovy

this works around the reported breakage. **but there is a new breakage: the removal of annotations and its effect on subclassing.**

this has not been reported so far. Gradle developers need to be aware of this: this issue goes beyond the data wiring issues reported in #8401, they are breaking existing code in a way they are not currently aware by removing annotations when they convert API to lazy. 

i've done my part tracking this down. i recommend you create a new issue regarding this to alert your developers.

**Comment by Lanchon** [comment]
in essence, this is simple: you can't change annotations of non-final methods. if you do you are breaking backwards compatibility.

if your devs are going to do it anyway, they should be aware of the implications.

**Comment by Lanchon** [comment]
i fixed the workaround with this commit:
https://github.com/DexPatcher/dexpatcher-gradle/commit/4d1e1253146e80a18b6dd9b4f1054501ccea5a77
