### ISSUE TITLE
Gradle Incremental Compile' SourceToNameConverter.getClassName doesn't handle linux logical links

### ISSUE THREAD

**Issue by ThomasCraigNelson** [gradle/gradle#9216]
Say the com directory in a simple java project points is a logicial link.  i.e:
tnelson@bb7285:~/src/gradlebuild$ ls -l src/main/java
total 0
lrwxrwxrwx 1 tnelson tnelson 12 Apr 24 15:27 com -> ../../../com

Then gradlew clean build works, but if you then edit a simple java file it gives the following:

tnelson@bb7285:~/src/gradlebuild$ gradle build 
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Unable to find source java class: '/home/tnelson/src/gradlebuild/src/main/java/com/tom/Main.java' because it does not belong to any of the source dirs: '[/home/tnelson/src/gradlebuild/src/main/java]'

The stack fragment that will help you is here:
Caused by: java.lang.IllegalArgumentException: Unable to find source java class: '/home/tnelson/src/gradlebuild/src/main/java/com/tom/Main.java' because it does not belong to any of the source dirs: '[/home/tnelson/src/gradlebuild/src/main/java]'
        at org.gradle.api.internal.tasks.compile.incremental.recomp.SourceToNameConverter.getClassName(SourceToNameConverter.java:44)
        at org.gradle.api.internal.tasks.compile.incremental.recomp.JavaChangeProcessor.processChange(JavaChangeProcessor.java:34)
        at org.gradle.api.internal.tasks.compile.incremental.recomp.InputChangeAction.execute(InputChangeAction.java:47)
        at org.gradle.api.internal.tasks.compile.incremental.recomp.InputChangeAction.execute(InputChangeAction.java:26)
        at org.gradle.api.internal.changedetection.changes.ChangesOnlyIncrementalTaskInputs.doOutOfDate(ChangesOnlyIncrementalTaskInputs.java:43)
        at org.gradle.api.internal.changedetection.changes.StatefulIncrementalTaskInputs.outOfDate(StatefulIncrementalTaskInputs.java:32)
        at org.gradle.api.internal.tasks.compile.incremental.recomp.CurrentCompilation.visitChanges(CurrentCompilation.java:51)

### Expected Behavior

Should perform incremental compile
### Context

I'm trying to promote use of gradle in a legacy environment where they don't use the normal src/main/java
[gradlebug.tar.gz](https://github.com/gradle/gradle/files/3113940/gradlebug.tar.gz)

### Steps to Reproduce 

Attached, as simple as I can make it.  First unzip/untar, then run gradle build.  Then edit Main.java , then run gradle build again.

### Your Environment

Ubuntu linux, doubt this matters

Build scan URL:

**Comment by big-guy** [comment]
I think this is the same problem, closing as a dupe for the older issue: https://github.com/gradle/gradle/issues/9202

Instead of symlinking the directory under src/main/java, could you just configure Gradle to use the right path?

**Comment by ThomasCraigNelson** [comment]
Yes I see it is a duplicate, but no I can't just configure Gradle to use
the right path, I'm trying to adapt gradle use to a legacy situation where
the files are in the wrong place.  How hard can it be to follow the links?

Unfortunately my company did not start the right way. I'm trying to
introduce gradle without disrupting them.

Thanks,
Tom

**Comment by big-guy** [comment]
There's not really a "wrong place", you can configure Gradle to look where ever the source files actually are. Using symlinks is likely to be more disruptive because there are now two locations for the same source file and other tools may not like the symlinks (e.g., IDEs) and reports/errors may contain either the symlink path or the actual path or both.

**Comment by ThomasCraigNelson** [comment]
Idea eclipse and grade build all handle the link well. It is incremental
compile that doesn't. I'm inheriting the problematic com directory at top
of project
