### ISSUE TITLE
Gradle sync failed: Cause: delight/rhinosandox/internal/SafeClassShutter

### ISSUE THREAD

**Issue by Jeekai** [gradle/gradle#9295]
AndroidStudio3.4
gradle-wrapper 4.6+

```
Caused by: java.lang.NoClassDefFoundError: delight/rhinosandox/internal/SafeClassShutter
	at delight.rhinosandox.internal.RhinoSandboxImpl.<init>(RhinoSandboxImpl.java:229)
	at delight.rhinosandox.RhinoSandboxes.create(RhinoSandboxes.java:9)
	at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.setupEngine(JavaxPacScriptParser.java:51)
	at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.<init>(JavaxPacScriptParser.java:40)
	at com.github.markusbernhardt.proxy.selector.pac.PacProxySelector.selectEngine(PacProxySelector.java:76)
	at com.github.markusbernhardt.proxy.selector.pac.PacProxySelector.<init>(PacProxySelector.java:41)
	at com.intellij.util.net.IdeaWideProxySelector.select(IdeaWideProxySelector.java:75)
	at com.intellij.util.proxy.CommonProxy.select(CommonProxy.java:213)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1132)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
	at org.gradle.wrapper.Download.download(Download.java:51)
	at org.gradle.tooling.internal.consumer.DistributionInstaller$1.run(DistributionInstaller.java:128)
2019-04-26 09:51:39,859 [ thread 48]   WARN - nal.AbstractExternalSystemTask - Cause: delight/rhinosandox/internal/SafeClassShutter 
com.intellij.openapi.externalSystem.model.ExternalSystemException: Cause: delight/rhinosandox/internal/SafeClassShutter
	at com.android.tools.idea.gradle.project.sync.idea.ProjectImportErrorHandler.getUserFriendlyError(ProjectImportErrorHandler.java:73)
	at com.android.tools.idea.gradle.project.sync.idea.AndroidGradleProjectResolver.getUserFriendlyError(AndroidGradleProjectResolver.java:523)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:151)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:151)
	at org.jetbrains.plugins.gradle.service.project.JavaGradleProjectResolver.getUserFriendlyError(JavaGradleProjectResolver.java:94)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:151)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:151)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:742)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:721)
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.execute(GradleExecutionHelper.java:216)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:140)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:75)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.lambda$resolveProjectInfo$0(RemoteExternalSystemProjectResolverImpl.java:37)
	at com.intellij.openapi.externalSystem.service.remote.AbstractRemoteExternalSystemService.execute(AbstractRemoteExternalSystemService.java:58)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.resolveProjectInfo(RemoteExternalSystemProjectResolverImpl.java:37)
	at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemProjectResolverWrapper.resolveProjectInfo(ExternalSystemProjectResolverWrapper.java:45)
	at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:100)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:166)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:152)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:558)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$5.run(ExternalSystemUtil.java:663)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: delight/rhinosandox/internal/SafeClassShutter
	at delight.rhinosandox.internal.RhinoSandboxImpl.<init>(RhinoSandboxImpl.java:229)
	at delight.rhinosandox.RhinoSandboxes.create(RhinoSandboxes.java:9)
	at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.setupEngine(JavaxPacScriptParser.java:51)
	at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.<init>(JavaxPacScriptParser.java:40)
	at com.github.markusbernhardt.proxy.selector.pac.PacProxySelector.selectEngine(PacProxySelector.java:76)
	at com.github.markusbernhardt.proxy.selector.pac.PacProxySelector.<init>(PacProxySelector.java:41)
	at com.intellij.util.net.IdeaWideProxySelector.select(IdeaWideProxySelector.java:75)
	at com.intellij.util.proxy.CommonProxy.select(CommonProxy.java:213)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1132)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
	at org.gradle.wrapper.Download.download(Download.java:51)
	at org.gradle.tooling.internal.consumer.DistributionInstaller$1.run(DistributionInstaller.java:128)

2019-04-26 09:51:39,860 [ thread 48]   INFO - System.util.ExternalSystemUtil - External project [/Users/jikai/Documents/Weaver/android] resolution task executed in 9 ms. 
2019-04-26 09:51:39,860 [ thread 48]   WARN - ect.sync.idea.ProjectSetUpTask - Cause: delight/rhinosandox/internal/SafeClassShutter 
2019-04-26 09:51:39,899 [ thread 48]   INFO - e.project.sync.GradleSyncState - Gradle sync failed: Cause: delight/rhinosandox/internal/SafeClassShutter
```

**Comment by matrixyf** [comment]
> AndroidStudio3.4
> gradle-wrapper 4.6+
> 
> > Caused by: java.lang.NoClassDefFoundError: delight/rhinosandox/internal/SafeClassShutter
> > at delight.rhinosandox.internal.RhinoSandboxImpl.(RhinoSandboxImpl.java:229)
> > at delight.rhinosandox.RhinoSandboxes.create(RhinoSandboxes.java:9)
> > at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.setupEngine(JavaxPacScriptParser.java:51)
> > at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.(JavaxPacScriptParser.java:40)
> > at com.github.markusbernhardt.proxy.selector.pac.PacProxySelector.selectEngine(PacProxySelector.java:76)
> > at com.github.markusbernhardt.proxy.selector.pac.PacProxySelector.(PacProxySelector.java:41)
> > at com.intellij.util.net.IdeaWideProxySelector.select(IdeaWideProxySelector.java:75)
> > at com.intellij.util.proxy.CommonProxy.select(CommonProxy.java:213)
> > at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1132)
> > at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
> > at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
> > at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
> > at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
> > at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
> > at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
> > at org.gradle.wrapper.Download.download(Download.java:51)
> > at org.gradle.tooling.internal.consumer.DistributionInstaller$1.run(DistributionInstaller.java:128)
> > 2019-04-26 09:51:39,859 [ thread 48]   WARN - nal.AbstractExternalSystemTask - Cause: delight/rhinosandox/internal/SafeClassShutter
> > com.intellij.openapi.externalSystem.model.ExternalSystemException: Cause: delight/rhinosandox/internal/SafeClassShutter
> > at com.android.tools.idea.gradle.project.sync.idea.ProjectImportErrorHandler.getUserFriendlyError(ProjectImportErrorHandler.java:73)
> > at com.android.tools.idea.gradle.project.sync.idea.AndroidGradleProjectResolver.getUserFriendlyError(AndroidGradleProjectResolver.java:523)
> > at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:151)
> > at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:151)
> > at org.jetbrains.plugins.gradle.service.project.JavaGradleProjectResolver.getUserFriendlyError(JavaGradleProjectResolver.java:94)
> > at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:151)
> > at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:151)
> > at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:742)
> > at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:721)
> > at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.execute(GradleExecutionHelper.java:216)
> > at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:140)
> > at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:75)
> > at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.lambda$resolveProjectInfo$0(RemoteExternalSystemProjectResolverImpl.java:37)
> > at com.intellij.openapi.externalSystem.service.remote.AbstractRemoteExternalSystemService.execute(AbstractRemoteExternalSystemService.java:58)
> > at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.resolveProjectInfo(RemoteExternalSystemProjectResolverImpl.java:37)
> > at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemProjectResolverWrapper.resolveProjectInfo(ExternalSystemProjectResolverWrapper.java:45)
> > at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:100)
> > at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:166)
> > at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:152)
> > at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:558)
> > at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$5.run(ExternalSystemUtil.java:663)
> > at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
> > at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
> > at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
> > at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
> > at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
> > at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
> > at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
> > at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
> > at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> > at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> > at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> > at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> > at java.lang.Thread.run(Thread.java:745)
> > Caused by: java.lang.NoClassDefFoundError: delight/rhinosandox/internal/SafeClassShutter
> > at delight.rhinosandox.internal.RhinoSandboxImpl.(RhinoSandboxImpl.java:229)
> > at delight.rhinosandox.RhinoSandboxes.create(RhinoSandboxes.java:9)
> > at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.setupEngine(JavaxPacScriptParser.java:51)
> > at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.(JavaxPacScriptParser.java:40)
> > at com.github.markusbernhardt.proxy.selector.pac.PacProxySelector.selectEngine(PacProxySelector.java:76)
> > at com.github.markusbernhardt.proxy.selector.pac.PacProxySelector.(PacProxySelector.java:41)
> > at com.intellij.util.net.IdeaWideProxySelector.select(IdeaWideProxySelector.java:75)
> > at com.intellij.util.proxy.CommonProxy.select(CommonProxy.java:213)
> > at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1132)
> > at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
> > at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
> > at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
> > at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
> > at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
> > at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
> > at org.gradle.wrapper.Download.download(Download.java:51)
> > at org.gradle.tooling.internal.consumer.DistributionInstaller$1.run(DistributionInstaller.java:128)
> 
> 2019-04-26 09:51:39,860 [ thread 48] INFO - System.util.ExternalSystemUtil - External project [/Users/jikai/Documents/Weaver/android] resolution task executed in 9 ms.
> 2019-04-26 09:51:39,860 [ thread 48] WARN - ect.sync.idea.ProjectSetUpTask - Cause: delight/rhinosandox/internal/SafeClassShutter
> 2019-04-26 09:51:39,899 [ thread 48] INFO - e.project.sync.GradleSyncState - Gradle sync failed: Cause: delight/rhinosandox/internal/SafeClassShutter

I have the same problem with gradle-wrapper 5.1.1

**Comment by PollyGlot** [comment]
Got the same error this morning. I have no idea where to search the solution.

**Comment by HJLAllen** [comment]
I got this problem ,how can I solve this problem....

**Comment by blindpirate** [comment]
Can anyone please share a reproducible sample and steps to reproduce? The stacktrace doen't help much. 

Looking at the stacktrace, I believe it's due to the proxy configured in AS, especially users from China:

```
at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.setupEngine(JavaxPacScriptParser.java:51)
	at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.<init>(JavaxPacScriptParser.java:40)
	at com.github.markusbernhardt.proxy.selector.pac.PacProxySelector.selectEngine(PacProxySelector.java:76)
	at com.github.markusbernhardt.proxy.selector.pac.PacProxySelector.<init>(PacProxySelector.java:41)
	at com.intellij.util.net.IdeaWideProxySelector.select(IdeaWideProxySelector.java:75)

```

Can you please retry with proxy disabled? This does't seem to be a Gradle issue.
