### ISSUE TITLE
The cache is not actually pushed in retry

### ISSUE THREAD

**Issue by IronLung7** [gradle/gradle#9482]
We have the log here which indicates cache is already pushed, but cache is not actually pushed.

```
[2019-05-16 06:02:29] Packing task ':xxxxx:xxxxBuild'
[2019-05-16 06:12:45] I/O exception (java.net.SocketException) caught when processing request to {s}->https://artifactoryserver:443: Connection reset
[2019-05-16 06:12:45] Retrying request to {s}->https://artifactoryserver:443
[2019-05-16 06:12:45] Could not store entry fa4f8fbd4aa734645f48d222faff8f9e for task ':xxxxx:xxxxBuild' in remote build cache
[2019-05-16 06:12:45] java.lang.IllegalStateException: Build cache entry has already been stored
[2019-05-16 06:12:45] 	at org.gradle.caching.internal.controller.service.StoreTarget.writeTo(StoreTarget.java:42)
[2019-05-16 06:12:45] 	at org.gradle.caching.http.internal.HttpBuildCacheService$1.writeTo(HttpBuildCacheService.java:164)
[2019-05-16 06:12:45] 	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
[2019-05-16 06:12:45] 	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:160)
[2019-05-16 06:12:45] 	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
[2019-05-16 06:12:45] 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
[2019-05-16 06:12:45] 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
[2019-05-16 06:12:45] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
[2019-05-16 06:12:45] 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
[2019-05-16 06:12:45] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
[2019-05-16 06:12:45] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
[2019-05-16 06:12:45] 	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:148)
[2019-05-16 06:12:45] 	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:130)
[2019-05-16 06:12:45] 	at org.gradle.caching.http.internal.HttpBuildCacheService.store(HttpBuildCacheService.java:174)
[2019-05-16 06:12:45] 	at org.gradle.caching.internal.controller.service.BaseBuildCacheServiceHandle.storeInner(BaseBuildCacheServiceHandle.java:93)
[2019-05-16 06:12:45] 	at org.gradle.caching.internal.controller.service.OpFiringBuildCacheServiceHandle.access$001(OpFiringBuildCacheServiceHandle.java:35)
[2019-05-16 06:12:45] 	at org.gradle.caching.internal.controller.service.OpFiringBuildCacheServiceHandle$2.run(OpFiringBuildCacheServiceHandle.java:71)
[2019-05-16 06:12:45] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
[2019-05-16 06:12:45] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
[2019-05-16 06:12:45] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
[2019-05-16 06:12:45] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
[2019-05-16 06:12:45] 	at org.gradle.caching.internal.controller.service.OpFiringBuildCacheServiceHandle.storeInner(OpFiringBuildCacheServiceHandle.java:68)
[2019-05-16 06:12:45] 	at org.gradle.caching.internal.controller.service.BaseBuildCacheServiceHandle.store(BaseBuildCacheServiceHandle.java:86)
[2019-05-16 06:12:45] 	at org.gradle.caching.internal.controller.DefaultBuildCacheController$2.execute(DefaultBuildCacheController.java:218)
[2019-05-16 06:12:45] 	at org.gradle.caching.internal.controller.DefaultBuildCacheController$2.execute(DefaultBuildCacheController.java:208)
[2019-05-16 06:12:45] 	at org.gradle.caching.local.internal.DefaultBuildCacheTempFileStore.withTempFile(DefaultBuildCacheTempFileStore.java:46)
[2019-05-16 06:12:45] 	at org.gradle.caching.internal.controller.DefaultBuildCacheController.store(DefaultBuildCacheController.java:208)
[2019-05-16 06:12:45] 	at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:111)
[2019-05-16 06:12:45] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
[2019-05-16 06:12:45] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
[2019-05-16 06:12:45] 	at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:66)
[2019-05-16 06:12:45] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
[2019-05-16 06:12:45] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
[2019-05-16 06:12:45] 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
[2019-05-16 06:12:45] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
[2019-05-16 06:12:45] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
[2019-05-16 06:12:45] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
[2019-05-16 06:12:45] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
[2019-05-16 06:12:45] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
[2019-05-16 06:12:45] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
[2019-05-16 06:12:45] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
[2019-05-16 06:12:45] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
[2019-05-16 06:12:45] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
[2019-05-16 06:12:45] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
[2019-05-16 06:12:45] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
[2019-05-16 06:12:45] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
[2019-05-16 06:12:45] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
[2019-05-16 06:12:45] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
[2019-05-16 06:12:45] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
[2019-05-16 06:12:45] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
[2019-05-16 06:12:45] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
[2019-05-16 06:12:45] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
[2019-05-16 06:12:45] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
[2019-05-16 06:12:45] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
[2019-05-16 06:12:45] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
[2019-05-16 06:12:45] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
[2019-05-16 06:12:45] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2019-05-16 06:12:45] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2019-05-16 06:12:45] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
[2019-05-16 06:12:45] 	at java.lang.Thread.run(Thread.java:748)
[2019-05-16 06:12:46] :xxxxx:xxxxBuild (Thread[Task worker for ':',5,main]) completed. Took 33 mins 19.273 secs.
```

### Expected Behavior
Cache fa4f8fbd4aa734645f48d222faff8f9e  could be found at https://artifactoryserver:443 

### Current Behavior
Cache fa4f8fbd4aa734645f48d222faff8f9e  couldn't be found at https://artifactoryserver:443 

### Steps to Reproduce 
First cache publication is failed because of connection reset.

**Comment by paplorinc** [comment]
Hey @IronLung7, thanks for bringing it to our attention.
We have a test for that case explicitly https://github.com/gradle/gradle/blob/master/subprojects/build-cache-http/src/integTest/groovy/org/gradle/caching/http/internal/HttpBuildCacheServiceErrorHandlingIntegrationTest.groovy#L56, but it has a different stack trace than your build.
Could you please tell us the Gradle version you're using?

**Comment by IronLung7** [comment]
@paplorinc  This is the version information.
```

------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_141 (Oracle Corporation 25.141-b16)
OS:           Linux 3.10.0-514.26.2.el7.x86_64 amd64

```

**Comment by paplorinc** [comment]
Thanks.
This has been addressed since, the solution was to ignore the connection problem: the cache is meant to speed up the build, not to keep retrying.
Please upgrade to the [latest version](https://gradle.org/releases) and let us know if it happens again.
Closing the issue.

**Comment by IronLung7** [comment]
@paplorinc Did you see this pull request? https://github.com/gradle/gradle/pull/9483

**Comment by paplorinc** [comment]
Hey @IronLung7, yes, thanks for your contribution.
Since we've have disabled retries a while ago, we didn't see the need to change the code in that regard (would need extensive testing as well, we can't just change source without a failing test)
