### ISSUE TITLE
Automatic provider property implementation fails on parameterized parameter types.

### ISSUE THREAD

**Issue by trevjonez** [gradle/gradle#9506]
### Expected Behavior
tasks that define read only property of type `org.gradle.api.provider.ListProperty` that is parameterized with parameterized type should be supported.

IE: `ListProperty<Pair<String, String>>`

### Current Behavior
runtime class generation fails with class cast exception.

```
Caused by: org.gradle.api.tasks.TaskInstantiationException: Could not create task of type 'ComposerTask'.
	at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:70)
	at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:64)
	at org.gradle.util.GUtil.uncheckedCall(GUtil.java:459)
	at org.gradle.api.internal.AbstractTask.injectIntoNewInstance(AbstractTask.java:185)
	at org.gradle.api.internal.project.taskfactory.TaskFactory.create(TaskFactory.java:64)
	at org.gradle.api.internal.project.taskfactory.PropertyAssociationTaskFactory.create(PropertyAssociationTaskFactory.java:49)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory.create(AnnotationProcessingTaskFactory.java:46)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.createTask(DefaultTaskContainer.java:326)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.access$200(DefaultTaskContainer.java:78)
	at org.gradle.api.internal.tasks.DefaultTaskContainer$1.call(DefaultTaskContainer.java:152)
	... 148 more
Caused by: org.gradle.internal.instantiation.ClassGenerationException: Could not generate a decorated class for class com.trevjonez.composer.ComposerTask.
	at org.gradle.internal.instantiation.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:188)
	at org.gradle.internal.instantiation.AbstractClassGenerator.generate(AbstractClassGenerator.java:106)
	at org.gradle.internal.instantiation.AsmBackedClassGenerator.generate(AsmBackedClassGenerator.java:105)
	at org.gradle.internal.instantiation.Jsr330ConstructorSelector$1.transform(Jsr330ConstructorSelector.java:59)
	at org.gradle.internal.instantiation.Jsr330ConstructorSelector$1.transform(Jsr330ConstructorSelector.java:54)
	at org.gradle.cache.internal.DefaultCrossBuildInMemoryCacheFactory$DefaultCrossBuildInMemoryCache.get(DefaultCrossBuildInMemoryCacheFactory.java:121)
	at org.gradle.internal.instantiation.Jsr330ConstructorSelector.forType(Jsr330ConstructorSelector.java:54)
	at org.gradle.internal.instantiation.Jsr330ConstructorSelector.forParams(Jsr330ConstructorSelector.java:49)
	at org.gradle.internal.instantiation.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:45)
	at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:67)
	... 157 more
Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
	at org.gradle.internal.instantiation.AsmBackedClassGenerator$ClassBuilderImpl.lambda$applyReadOnlyManagedStateToGetter$0(AsmBackedClassGenerator.java:973)
	at org.gradle.internal.instantiation.AsmBackedClassGenerator$ClassBuilderImpl$7.add(AsmBackedClassGenerator.java:707)
	at org.gradle.internal.instantiation.AsmBackedClassGenerator$ClassBuilderImpl.addGetter(AsmBackedClassGenerator.java:725)
	at org.gradle.internal.instantiation.AsmBackedClassGenerator$ClassBuilderImpl.addLazyGetter(AsmBackedClassGenerator.java:696)
	at org.gradle.internal.instantiation.AsmBackedClassGenerator$ClassBuilderImpl.applyReadOnlyManagedStateToGetter(AsmBackedClassGenerator.java:950)
	at org.gradle.internal.instantiation.AbstractClassGenerator$ManagedTypeHandler.applyTo(AbstractClassGenerator.java:913)
	at org.gradle.internal.instantiation.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:169)
	... 166 more
```

### Context
Custom task input property, other non generic properties can be defined as abstract and automatically instantiated, generics require manual handling.

### Steps to Reproduce 
task with property such as:
```
  @get:[Optional Input]
  abstract override val instrumentationArguments: ListProperty<Pair<String, String>>
```

### Your Environment
Build scan URL: https://gradle.com/s/sgbry6ded2dtw

### Current workaround
```
  @Suppress("UNCHECKED_CAST")
  @get:[Optional Input]
  override val instrumentationArguments: ListProperty<Pair<String, String>> =
      project.objects.listProperty(Pair::class.java).empty() as ListProperty<Pair<String, String>>
```

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/9755
