### ISSUE TITLE
NullPointerException when excluding transitive dependency in dependency config

### ISSUE THREAD

**Issue by jacobwu** [gradle/gradle#951]
### Expected Behavior

Dependency resolution should succeed, the dependency included, and transitive dependency excluded.

Works in Gradle 3.1 and lower

### Current Behavior

In Gradle 3.2 and 3.2.1 it results in NPE
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':ideaModule'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:61)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
...
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
        at com.google.common.collect.SingletonImmutableSet.<init>(SingletonImmutableSet.java:47)
        at com.google.common.collect.ImmutableSet.of(ImmutableSet.java:94)
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:276)
        at org.gradle.internal.component.external.descriptor.DefaultExclude.<init>(DefaultExclude.java:45)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.DefaultExcludeRuleConverter.convertExcludeRule(DefaultExcludeRuleConverter.java:27)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.DefaultExcludeRuleConverter.convertExcludeRule(DefaultExcludeRuleConverter.java:23)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.AbstractIvyDependencyDescriptorFactory$1.transform(AbstractIvyDependencyDescriptorFactory.java:45)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.AbstractIvyDependencyDescriptorFactory$1.transform(AbstractIvyDependencyDescriptorFactory.java:42)
        at org.gradle.util.CollectionUtils.collect(CollectionUtils.java:189)
        at org.gradle.util.CollectionUtils.collect(CollectionUtils.java:184)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.AbstractIvyDependencyDescriptorFactory.convertExcludeRules(AbstractIvyDependencyDescriptorFactory.java:42)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.ExternalModuleIvyDependencyDescriptorFactory.createDependencyDescriptor(ExternalModuleIvyDependencyDescriptorFactory.java:44)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.DefaultDependencyDescriptorFactory.createDependencyDescriptor(DefaultDependencyDescriptorFactory.java:36)
        at org.gradle.api.internal.artifacts.ivyservice.clientmodule.ClientModuleResolver.addClientModuleDependencies(ClientModuleResolver.java:64)
        at org.gradle.api.internal.artifacts.ivyservice.clientmodule.ClientModuleResolver.resolve(ClientModuleResolver.java:53)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$ModuleVersionResolveState.resolve(DependencyGraphBuilder.java:608)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$ModuleVersionResolveState.getMetaData(DependencyGraphBuilder.java:619)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$DependencyEdge.calculateTargetConfigurations(DependencyGraphBuilder.java:274)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$DependencyEdge.attachToTargetConfigurations(DependencyGraphBuilder.java:247)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.traverseGraph(DependencyGraphBuilder.java:155)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:92)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:82)
        at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver$1.run(CacheLockingArtifactDependencyResolver.java:41)
        at org.gradle.internal.Factories$1.create(Factories.java:25)
        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:179)
        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:162)
        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:129)
        at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.useCache(DefaultCacheFactory.java:191)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultCacheLockingManager.useCache(DefaultCacheLockingManager.java:56)
        at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver.resolve(CacheLockingArtifactDependencyResolver.java:39)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolve(DefaultConfigurationResolver.java:97)
        at org.gradle.api.internal.artifacts.ivyservice.SelfResolvingDependencyConfigurationResolver.resolve(SelfResolvingDependencyConfigurationResolver.java:40)
        at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolve(ShortCircuitEmptyConfigurationResolver.java:62)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolve(ErrorHandlingConfigurationResolver.java:43)
        ... 92 more

```

### Context

In 3.2 `org.gradle.api.internal.artifacts.ivyservice.clientmodule.ClientModuleResolver#addClientModuleDependencies(ClientModule, MutableModuleComponentResolveMetadata)` switched from the deprecated `org.gradle.api.artifacts.ModuleDependency#getConfiguration()`, which always returned a non-null value, to `org.gradle.api.artifacts.ModuleDependency#getTargetConfiguration()`, which does return null when no explicit configuration is set.

### Steps to Reproduce (for bugs)

With an excluded transitive dependency like:
```
apply plugin: 'java'
apply plugin: 'idea'

repositories {
    jcenter()
}

dependencies {
    compile module('org.apache.xmlrpc:xmlrpc-client:3.1') {
        dependency('org.apache.xmlrpc:xmlrpc-common:3.1') {
            exclude module: 'junit'
        }
    }
}
```

Execute `gradle idea`

### Your Environment

 * Operating system:	Mac OS X 10.12.1
 * CPU cores:	8 cores
 * Max Gradle workers:	8 workers
 * Java runtime:	Oracle Java(TM) SE Runtime Environment 1.7.0_79-b15
 * Java VM:	Oracle Java HotSpot(TM) 64-Bit Server VM 24.79-b02 (mixed mode)

**Comment by eriwen** [comment]
@jacobwu Thank you for the detailed description and repro steps. Would you be willing to address this?

**Comment by jacobwu** [comment]
@eriwen Yes I can take a look at it

**Comment by jacobwu** [comment]
Pull request #1113 created

**Comment by bmuschko** [comment]
Internal review: https://code-review.gradle.org/cru/REVIEW-6428
