### ISSUE TITLE
How to import external plugin in a precompiled script plugin？

### ISSUE THREAD

**Issue by XhstormR** [gradle/gradle#9536]
According to the [Kotlin DSL documentation](https://docs.gradle.org/current/userguide/kotlin_dsl.html#kotdsl:precompiled_plugins), the script plugin can look like this:
```kotlin
// buildSrc/src/main/kotlin/java-library-convention.gradle.kts

plugins {
    `java-library`
    checkstyle
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

checkstyle {
    maxWarnings = 0
    // ...
}

tasks.withType<JavaCompile> {
    options.isWarnings = true
    // ...
}
```
When I introduce an external plugin and config become:
```kotlin
// buildSrc/src/main/kotlin/java-library-convention.gradle.kts

import com.google.cloud.tools.jib.plugins.common.PropertyNames

plugins {
    `java-library`
    checkstyle
    id("com.google.cloud.tools.jib") version "1.2.0"
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

checkstyle {
    maxWarnings = 0
    // ...
}

tasks.withType<JavaCompile> {
    options.isWarnings = true
    // ...
}

jib {
    from {
        image = "openjdk:latest"
    }
    to {
        image = "192.168.8.128:5100/root/erp:latest"
        auth {
            username = "root"
            password = "123"
        }
    }
    container {
        ports = listOf("8080")
        volumes = listOf("/app/data")
    }
    setAllowInsecureRegistries(true)

    /* For Gitlab CI Cache */
    val jibCacheDir = rootDir.resolve("jib-cache").path
    System.setProperty(PropertyNames.BASE_IMAGE_CACHE, jibCacheDir)
    System.setProperty(PropertyNames.APPLICATION_CACHE, jibCacheDir)
}
```
 the compiler gives an error:
```
> Task :buildSrc:generatePrecompiledScriptPluginAccessors
Failed to generate type-safe Gradle model accessors for the following precompiled script plugins:
 - src\main\kotlin\jib.gradle.kts

org.gradle.internal.exceptions.LocationAwareException: Precompiled script plugin 'D:\IdeaProjects\ERP\buildSrc\src\main\kotlin\jib.gradle.kts' line: 1
Plugin [id: 'com.google.cloud.tools.jib'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (plugin dependency must include a version number for this source)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:263)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.access$100(DefaultPluginRequestApplicator.java:63)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$1.transform(DefaultPluginRequestApplicator.java:91)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$1.transform(DefaultPluginRequestApplicator.java:88)
        at org.gradle.util.CollectionUtils.collect(CollectionUtils.java:205)
        at org.gradle.util.CollectionUtils.collect(CollectionUtils.java:200)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:88)
        at org.gradle.kotlin.dsl.provider.plugins.precompiled.tasks.SyntheticProjectSchemaBuilder.applyPluginsTo(GeneratePrecompiledScriptPluginAccessors.kt:382)
        at org.gradle.kotlin.dsl.provider.plugins.precompiled.tasks.SyntheticProjectSchemaBuilder.childProjectWith(GeneratePrecompiledScriptPluginAccessors.kt:343)
        at org.gradle.kotlin.dsl.provider.plugins.precompiled.tasks.SyntheticProjectSchemaBuilder.schemaFor(GeneratePrecompiledScriptPluginAccessors.kt:333)
        at org.gradle.kotlin.dsl.provider.plugins.precompiled.tasks.GeneratePrecompiledScriptPluginAccessors.projectSchemaImpliedByPluginGroups(GeneratePrecompiledScriptPluginAccessors.kt:256)
        at org.gradle.kotlin.dsl.provider.plugins.precompiled.tasks.GeneratePrecompiledScriptPluginAccessors.generateTypeSafeAccessorsFor(GeneratePrecompiledScriptPluginAccessors.kt:137)
................
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:81)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'com.google.cloud.tools.jib'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (plugin dependency must include a version number for this source)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:262)
        ... 256 more

> Task :buildSrc:compileKotlin FAILED
e: D:\IdeaProjects\ERP\buildSrc\src\main\kotlin\jib.gradle.kts: (1, 19): Unresolved reference: cloud
e: D:\IdeaProjects\ERP\buildSrc\src\main\kotlin\jib.gradle.kts: (7, 1): Unresolved reference: jib
e: D:\IdeaProjects\ERP\buildSrc\src\main\kotlin\jib.gradle.kts: (8, 5): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public inline fun <reified T : VersionControlSpec> VcsMapping.from(noinline configureAction: TypeVariable(T).() -> Unit): Unit defined in org.gradle.kotlin.dsl
@Incubating public inline fun <T : VersionControlSpec> VcsMapping.from(type: KClass<TypeVariable(T)>, configureAction: Action<in TypeVariable(T)>): Unit defined in org.gradle.kotlin.dsl
e: D:\IdeaProjects\ERP\buildSrc\src\main\kotlin\jib.gradle.kts: (9, 9): Unresolved reference: image
e: D:\IdeaProjects\ERP\buildSrc\src\main\kotlin\jib.gradle.kts: (12, 9): Unresolved reference: image
e: D:\IdeaProjects\ERP\buildSrc\src\main\kotlin\jib.gradle.kts: (13, 9): Unresolved reference: auth
e: D:\IdeaProjects\ERP\buildSrc\src\main\kotlin\jib.gradle.kts: (14, 13): Unresolved reference: username
e: D:\IdeaProjects\ERP\buildSrc\src\main\kotlin\jib.gradle.kts: (15, 13): Unresolved reference: password
e: D:\IdeaProjects\ERP\buildSrc\src\main\kotlin\jib.gradle.kts: (19, 9): Unresolved reference: ports
e: D:\IdeaProjects\ERP\buildSrc\src\main\kotlin\jib.gradle.kts: (20, 9): Unresolved reference: volumes
e: D:\IdeaProjects\ERP\buildSrc\src\main\kotlin\jib.gradle.kts: (22, 5): Unresolved reference: setAllowInsecureRegistries
e: D:\IdeaProjects\ERP\buildSrc\src\main\kotlin\jib.gradle.kts: (26, 24): Unresolved reference: PropertyNames
e: D:\IdeaProjects\ERP\buildSrc\src\main\kotlin\jib.gradle.kts: (27, 24): Unresolved reference: PropertyNames
```

My operating environment:
```
D:\IdeaProjects\ERP>ver

Microsoft Windows [版本 10.0.14393]

D:\IdeaProjects\ERP>gradlew.bat --version

------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          12.0.1 (Oracle Corporation 12.0.1+12)
OS:           Windows 10 10.0 amd64
```

I looked at the issue and stackoverflow, but the solution they provided failed.

So how to extract some of the configuration from the root build script to the outside, to avoid the root build script becoming too big, what is the right way? Thank you.

**Comment by gildor** [comment]
You should add dependency on this plugin to buildSrc, precompiled script plugins do not allow to set version directly, only use one from classpath

**Comment by XhstormR** [comment]
Thank you, I get it.
