### ISSUE TITLE
Cannot change dependencies of configuration after it has been resolved error triggers on access rather than mutation.

### ISSUE THREAD

**Issue by venantius** [gradle/gradle#957]
### Expected Behavior

I'm working on a Gradle plugin. 

If I'm iterating through project configurations and accessing their resolved configuration so that I can determine their resolved artifacts, I expect to be able to access and inspect those objects. This should also be true of dependency projects and their artifacts, and I shouldn't have to worry about the order with which I call `resolvedConfiguration`. 

### Current Behavior

Let's say you're invoking a task on a specific project. If you attempt to access the resolved configuration of a project dependency of that project before accessing the target project's resolved dependency, Gradle throws an exception `Cannot change dependencies of configuration ... after it has been resolved`.

This is surprising, because I'm not actually trying to change the dependencies - just access their metadata. I would only expect this exception if I was attempting a mutation. 

### Context

This has a fairly straightforward workaround in the case in which you're analyzing a specific project, but if I wanted to analyze lots of projects at once in a task I might have to fully construct the dependency graph and find the entrypoints in order to resolve them. That's sort of a pain in the neck and an un-necessary hoop to have to jump through given that all I want is to read data. 

### Your Environment

macOS Sierra, JDK 8, Gradle 3.2.1

**Comment by venantius** [comment]
This also applies to Gradle 3.3.

**Comment by venantius** [comment]
This seems specifically to be an issue that arises when we have a `transitive = false` declaration, e.g. something like the following:

```groovy
dependencies {
    compile ("com.amazonaws:dynamodb-streams-kinesis-adapter:1.0.2") {
        transitive = false
    }
}```

**Comment by venantius** [comment]
What a stacktrace looks like when we access the resolvedConfiguration for one of these configurations:

```
* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':projects:nebula:repository-metadata'.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:92)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:176)
        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:181)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:70)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:628)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:129)
        at org.gradle.api.internal.project.DefaultProjectAccessListener.evaluateProjectAndDiscoverTasks(DefaultProjectAccessListener.java:32)
        at org.gradle.api.internal.project.DefaultProjectAccessListener.beforeResolvingProjectDependency(DefaultProjectAccessListener.java:28)
        at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency.beforeResolved(DefaultProjectDependency.java:107)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.ProjectIvyDependencyDescriptorFactory.createDependencyDescriptor(ProjectIvyDependencyDescriptorFactory.java:39)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.DefaultDependencyDescriptorFactory.createDependencyDescriptor(DefaultDependencyDescriptorFactory.java:36)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.DefaultDependenciesToModuleDescriptorConverter.addDependencies(DefaultDependenciesToModuleDescriptorConverter.java:52)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.DefaultDependenciesToModuleDescriptorConverter.addDependencyDescriptors(DefaultDependenciesToModuleDescriptorConverter.java:43)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.DefaultConfigurationComponentMetaDataBuilder.addConfigurations(DefaultConfigurationComponentMetaDataBuilder.java:37)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.toRootComponentMetaData(DefaultConfiguration.java:682)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver$DefaultResolveContextToComponentResolver.resolve(DefaultArtifactDependencyResolver.java:138)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:93)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:85)
        at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver$1.run(CacheLockingArtifactDependencyResolver.java:43)
        at org.gradle.internal.Factories$1.create(Factories.java:25)
        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:187)
        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:170)
        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:129)
        at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.useCache(DefaultCacheFactory.java:191)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultCacheLockingManager.useCache(DefaultCacheLockingManager.java:56)
        at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver.resolve(CacheLockingArtifactDependencyResolver.java:41)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolveGraph(DefaultConfigurationResolver.java:119)
        at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveGraph(ShortCircuitEmptyConfigurationResolver.java:72)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:66)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$3.execute(DefaultConfiguration.java:443)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$3.execute(DefaultConfiguration.java:436)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:436)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:411)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:403)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:197)
        at org.gradle.internal.metaobject.BeanDynamicObject.getProperty(BeanDynamicObject.java:150)
        at org.gradle.internal.metaobject.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:55)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:60)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getProperty(Unknown Source)```

**Comment by venantius** [comment]
This does seem to be related to `org.gradle.configureondemand` -- setting it to false causes this issue to go away. This suggests something is probably wrong with our subproject configuration but the stacktrace makes it hard to figure out what, exactly.

**Comment by jlowen** [comment]
This also occurs on 2.14.1.

**Comment by ymwang1984** [comment]
This also happens on 2.13

**Comment by bigdaz** [comment]
Hi @venantius. I'm sorry for the long delay getting back to you on this: I'm currently processing the backlog of issues related to dependency management.

We definitely don't expect the behaviour you're seeing when accessing a Configuration that has already been resolved. However, there are many plugins that make modifications to Configurations just before resolution is requested. Unfortunately the stacktrace you linked does not provide the context of the exception you are reporting: `Cannot change dependencies of configuration ... after it has been resolved`. If you can provide the full stacktrace we'd be happy to investigate further.

@jlowen / @ymwang1984 We'd be happy to hear from either of you with a sample that we can use to reproduce this issue.

**Comment by jlowen** [comment]
I eventually tracked this behavior down to one of my organization's gradle
plugins. Once I debugged it, I found where it was modifying the
configuration. I made the necessary changes to the offending plugin to
resolve the issue.

**Comment by bigdaz** [comment]
Thanks for the follow-up: @jlowen

**Comment by venantius** [comment]
I'm afraid I've changed jobs and no longer have access to the codebase I was working on where this was an issue.

**Comment by bigdaz** [comment]
Thank @venantius, I'm going to close this issue for now as non-reproducible. I'm happy to re-open it if this proves to be an ongoing issue.

**Comment by idemax** [comment]
This also happens on 3.4.0, cannot find out a reproduce steps but still happening!
