### ISSUE TITLE
Circular dependencies inside the 'gradle' project itself 

### ISSUE THREAD

**Issue by scais** [gradle/gradle#960]
Hello,

  I found out that there is probably a circular dependency (https://issues.gradle.org/browse/GRADLE-3378) somewhere in the 'gradle' project itself. When I try to gather all dependencies from the configuration, I am getting 'java.lang.StackOverflowError (no error message)'.

When I run with '--stacktrace' option, I am getting (the last line is repeated many times):

```
Caused by: java.lang.StackOverflowError
        at com.google.common.base.Objects.hashCode(Objects.java:78)
        at org.gradle.internal.component.model.DefaultIvyArtifactName.hashCode(DefaultIvyArtifactName.java:79)
        at org.gradle.internal.component.external.model.DefaultModuleComponentArtifactIdentifier.hashCode(DefaultModuleComponentArtifactIdentifier.java:83)
        at org.gradle.api.internal.artifacts.DefaultResolvedArtifact.hashCode(DefaultResolvedArtifact.java:83)
        at org.gradle.api.internal.artifacts.DefaultResolvedDependency$ResolvedArtifactComparator.compare(DefaultResolvedDependency.java:207)
        at org.gradle.api.internal.artifacts.DefaultResolvedDependency$ResolvedArtifactComparator.compare(DefaultResolvedDependency.java:188)
        at org.gradle.api.internal.artifacts.DefaultResolvedDependency.sort(DefaultResolvedDependency.java:122)
        at org.gradle.api.internal.artifacts.DefaultResolvedDependency.getModuleArtifacts(DefaultResolvedDependency.java:101)
        at org.gradle.api.internal.artifacts.DefaultResolvedDependency.getAllModuleArtifacts(DefaultResolvedDependency.java:107)
        at org.gradle.api.internal.artifacts.DefaultResolvedDependency.getAllModuleArtifacts(DefaultResolvedDependency.java:109)
...
```
I checked the 'DefaultResolvedDependency.java' and found out that on line 109, the child dependencies are being added, i.e

```
...
allArtifacts.addAll(childResolvedDependency.getAllModuleArtifacts());
...
```

Unfortunately I was not able to identify the exact circular dependency, but got some results from my investigation. The problem occurs at least for the project **announce** when resolving dependency on **org.gradle:internalIntegTesting:3.3-20161202104347+0000** 

Can anyone please have a look?

### Expected Behavior
I should not get 'java.lang.StackOverflowError (no error message)' when going through the Gradle project dependencies.

### Context
I am working on a project which gathers information from gradle-based projects (dependencies, source files etc.) In order to retrieve only transitive dependencies from a configuration, I am using the 'resolvedDependency.getAllModuleArtifacts()' - 'resolvedDependency.getModuleArtifacts()' This works for 10+ open-source projects I tried (e.g. Mockito, hibernate-orm, caffeine etc.) but when used for Gradle itself, I am getting 'java.lang.StackOverflowError (no error message)'

### Steps to Reproduce (for bugs)
1. Clone gradle repository (https://github.com/gradle/gradle)
2. Add this task to the 'build.gradle' (of the root project)

```
task stackoverflow << {
	project.getConfigurations().each { configuration ->
		configuration.getResolvedConfiguration().getFirstLevelModuleDependencies().each { dependency ->
			dependency.getAllModuleArtifacts()
		}
	}
}
```	

3. Run _./gradlew stackoverflow_ 

### Your Environment
Windows 7 64B, Java 8 64B, no Java options specified, gradle deamon off

**Comment by eriwen** [comment]
From @bigdaz in the forums:

> Would you be interested in contributing a fix? I think the fix would be in DefaultResolvedDependency, and we'd need some unit test coverage in DefaultResolvedDependencySpec.

**Comment by bigdaz** [comment]
I just tried to reproduce with latest Gradle `master`, and the steps provided do not lead to any exception. Closing as not-reproducible.
