### ISSUE TITLE
Dependencies task fails with "Could not resolve all dependencies for configuration"

### ISSUE THREAD

**Issue by adecker89** [gradle/gradle#9645]
Calling `./gradlew :app:dependencies` fails with the following error in specific configurations

    > Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
       > A problem occurred configuring project ':myktslibrary'.
          > Cannot change strategy of configuration ':myktslibrary:classpath' after it has been resolved.

With the following stacktrace (full trace in scan)
```
Caused by: org.gradle.api.InvalidUserDataException: Cannot change strategy of configuration ':search:classpath' after it has been resolved.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.preventIllegalMutation(DefaultConfiguration.java:1067)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.validateMutation(DefaultConfiguration.java:1038)
        at org.gradle.api.internal.artifacts.ivyservice.resolutionstrategy.DefaultResolutionStrategy.eachDependency(DefaultResolutionStrategy.java:145)
        at org.gradle.kotlin.dsl.support.EmbeddedKotlinProvider.pinDependenciesOn$gradle_kotlin_dsl(EmbeddedKotlinProvider.kt:69)
        at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator.setupEmbeddedKotlinForBuildscript(KotlinScriptEvaluator.kt:139)
        at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator.access$setupEmbeddedKotlinForBuildscript(KotlinScriptEvaluator.kt:87)
        at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost.setupEmbeddedKotlinFor(KotlinScriptEvaluator.kt:176)
        at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.setupEmbeddedKotlinFor(Interpreter.kt:360)

```

### Expected Behavior

Dependencies should work without error

### Current Behavior

Fails with error as described above

### Context

Just trying to figure out what my dependencies are resolving to

### Steps to Reproduce 

Step-by-Step:
* Create an Android application in Android Studio
* set `org.gradle.configureondemand=true` in `gradle.properties`
* Create a directory `lib` with a empty `build.gradle.kts`, add `lib` to `settings.gradle`
* Add a project dependency from `app` to `lib`
* run `./gradlew :app:dependencies`

It also **might** be Mac OS X specific, I have not tested this thoroughly though.

This is the minimal configuration I can reproduce it in. Removing any of those factors results in a function dependencies task

### Your Environment

Build scan URL: https://scans.gradle.com/s/vtpbg76qx3etc

**Comment by realdadfish** [comment]
This emerged since we switched the first couple of `build.gradle` files to `build.gradle.kts`. The Gradle versions previously functioned without a flaw, but the Kotlin Script versions, albeit very similar (no functionality changed) do break with `configureondemand` set to `true`.

**Comment by guozchen-sh** [comment]
> This emerged since we switched the first couple of `build.gradle` files to `build.gradle.kts`. The Gradle versions previously functioned without a flaw, but the Kotlin Script versions, albeit very similar (no functionality changed) do break with `configureondemand` set to `true`. This is Gradle 5.6.4 on Windows 10 btw.

We have this issue too. `Gradle 6.5.1`, `Kotlin 1.3.72`, Mac 10.15.6

**Comment by jarekankowski** [comment]
I faced the same issue in our build and it looks like updating to `AGP 4.1.0` solved the problem. More details [on Google issue tracker](https://issuetracker.google.com/issues/165821826#comment4).

**Comment by mlopatkin** [comment]
In general, we [don't recommend](https://docs.gradle.org/current/userguide/kotlin_dsl.html#kotdsl:limitations) using configuration-on-demand with Kotlin DSL. It seems that this particular issue was resolved in the Android Gradle plugin though.
