### ISSUE TITLE
GPG tests not runnable on Windows

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#9656]
I tried to fix a bug in signing project.
Therefore I first wanted to write a failing test.
Therefore I first wanted to run a successful test.
So I tried to run `org.gradle.plugins.signing.SigningTasksIntegrationSpec#out-of-date when signatory changes`.
Unfortunately this test fails on Windows.
I have gpg2 available on my path, so the `@Requires` is satisfied.
But when the test tries to do `Files.createSymbolicLink` in `org.gradle.plugins.signing.GpgCmdFixture#prepareGnupgHomeSymlink` this fails with

```
java.nio.file.FileSystemException: C:\Users\bkautler\AppData\Local\Temp\tfy2p: Dem Client fehlt ein erforderliches Recht.

	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:581)
	at java.base/java.nio.file.Files.createSymbolicLink(Files.java:1058)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.plugins.signing.GpgCmdFixture.prepareGnupgHomeSymlink(GpgCmdFixture.groovy:77)
	at org.gradle.plugins.signing.GpgCmdFixture.setupGpgCmd(GpgCmdFixture.groovy:55)
	at org.gradle.plugins.signing.SigningIntegrationSpec.setupGpgCmd(SigningIntegrationSpec.groovy:64)
	at org.gradle.plugins.signing.SigningTasksIntegrationSpec.out-of-date when signatory changes(SigningTasksIntegrationSpec.groovy:111)
```

Probably because it cannot create symlinks.
Would be nice if this maybe could changed somehow do work-around the 108 characters limit in a different way than using symlinks, for example by copying the files to the directory instead of symlinking or similar.

Acutally, as my gpg2 is from Cygwin, the next problem then is, that an absolute Windows path is used, which also then will not work. :-(

**Comment by Vampire** [comment]
Same still happens in latest master

**Comment by ov7a** [comment]
Sorry for the late reply

Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.
