### ISSUE TITLE
Could not expand ZIP

### ISSUE THREAD

**Issue by cdietrich** [gradle/gradle#9673]
A build that works perfectly with Gradle 5.4.1 fails with 5.5.rc1

```
Execution failed for task ':org.eclipse.xtext.xbase.lib.gwt:copyGwtSources'.
> Could not expand ZIP '/data/xtext-master/git/xtext-lib/org.eclipse.xtext.xbase.lib/build/libs/org.eclipse.xtext.xbase.lib-2.19.0-SNAPSHOT-sources.jar'.
```
### Expected Behavior

Works as before
### Current Behavior

fails
```
Could not expand ZIP '/data/xtext-master/git/xtext-lib/org.eclipse.xtext.xbase.lib/build/libs/org.eclipse.xtext.xbase.lib-2.19.0-SNAPSHOT-sources.jar'.
> /data/xtext-master/git/xtext-lib/org.eclipse.xtext.xbase.lib.gwt/build/tmp/expandedArchives/org.eclipse.xtext.xbase.lib-2.19.0-SNAPSHOT-sources.jar_2378c489376e2ea2619ef5dece7d1da5/org/eclipse/xtend2/lib/StringConcatenationClient.java (Datei oder Verzeichnis nicht gefunden)

org.gradle.api.tasks.TaskExecutionException
: 
Execution failed for task ':org.eclipse.xtext.xbase.lib.gwt:copyGwtSources'.
Open stacktrace
Caused by: 
org.gradle.api.GradleException
: 
Could not expand ZIP '/data/xtext-master/git/xtext-lib/org.eclipse.xtext.xbase.lib/build/libs/org.eclipse.xtext.xbase.lib-2.19.0-SNAPSHOT-sources.jar'.
Open stacktrace
Caused by: 
java.io.FileNotFoundException
: 
/data/xtext-master/git/xtext-lib/org.eclipse.xtext.xbase.lib.gwt/build/tmp/expandedArchives/org.eclipse.xtext.xbase.lib-2.19.0-SNAPSHOT-sources.jar_2378c489376e2ea2619ef5dece7d1da5/org/eclipse/xtend2/lib/StringConcatenationClient.java (Datei oder Verzeichnis nicht gefunden)
Close stacktrace
at gwtProject$_run_closure2$_closure5.doCall(/data/xtext-master/git/xtext-lib/gradle/gwtProject.gradle:13)
at org.gradle.api.specs.internal.ClosureSpec.isSatisfiedBy(ClosureSpec.java:32)
at org.gradle.api.specs.OrSpec.isSatisfiedBy(OrSpec.java:47)
at org.gradle.api.specs.NotSpec.isSatisfiedBy(NotSpec.java:35)
at org.gradle.api.specs.AndSpec.isSatisfiedBy(AndSpec.java:47)
at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTreeImpl$1.visitFile(AbstractFileTree.java:197)
at org.gradle.api.internal.file.archive.ZipFileTree.visit(ZipFileTree.java:98)
at org.gradle.api.internal.file.collections.FileTreeAdapter.visit(FileTreeAdapter.java:118)
at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTreeImpl.visit(AbstractFileTree.java:189)
at org.gradle.api.internal.file.CompositeFileTree.visit(CompositeFileTree.java:93)
at org.gradle.api.internal.file.copy.CopySpecActionImpl.execute(CopySpecActionImpl.java:39)
at org.gradle.api.internal.file.copy.CopySpecActionImpl.execute(CopySpecActionImpl.java:24)
at org.gradle.api.internal.file.copy.DefaultCopySpec$DefaultCopySpecResolver.walk(DefaultCopySpec.java:698)
at org.gradle.api.internal.file.copy.DefaultCopySpec$DefaultCopySpecResolver.walk(DefaultCopySpec.java:700)
```
### Steps to Reproduce 

```
git clone git@github.com:eclipse/xtext-lib.git
cd xtext-lib
./1-install-bom.sh
./2-gradle-build.sh
```

### Your Environment

Build scan URL:
https://scans.gradle.com/s/hbk5xhbkvetog/failure?openFailures=WzBd&openStackTraces=WzJd#top=0

(with gradle 5.6 nightly i get NPEs and the same problem when calling "./gradlew clean build -x test)
https://scans.gradle.com/s/tghfpsm2n3qp4/failure?openFailures=WzBd&openStackTraces=WzFd#top=0
should i create an separate issue for that? done: https://github.com/gradle/gradle/issues/9674

**Comment by big-guy** [comment]
@cdietrich I've reproduced the failure in an integration test and I think I know what caused it.  We'll release a RC3 with a fix.

**Comment by cdietrich** [comment]
Our build works fine again with 5.5 RC3. Many Thanks
