### ISSUE TITLE
NPE in CachingTaskDependencyResolveContext.add

### ISSUE THREAD

**Issue by cdietrich** [gradle/gradle#9674]
our build that works fine with 5.5.rcx and 5.4.1 fails with 5.6 5.6-20190611000032+0000

### Expected Behavior

Build works fine
### Current Behavior

Build Fails with NPE
```
Caused by: 
java.lang.NullPointerException
: 
(No message provided)
Close stacktrace
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:890)
at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.add(CachingTaskDependencyResolveContext.java:83)
at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue$2.visitDependencies(AbstractNestedRuntimeBeanNode.java:103)
at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:111)
at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmptyEdges.getNodeValues(CachingDirectedGraphWalker.java:213)
at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:121)
at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:73)
```
### Steps to Reproduce 
```
git clone git@github.com:eclipse/xtext-core.git
cd xtext-core
./1-gradle-build.sh
```

### Your Environment

Build scan URL:
https://scans.gradle.com/s/btw2kfb6zf5k2/failure?openFailures=WzBd&openStackTraces=WzFd#top=0

**Comment by big-guy** [comment]
@adammurdoch can you take a look at this?

**Comment by cdietrich** [comment]
i created a much more simple example to reproduce

https://github.com/cdietrich/gradle_issue_9674

**Comment by big-guy** [comment]
Thanks @cdietrich 

@lptr @wolfs could one of you guys take a look at this regression in master?

```
class MyTask extends DefaultTask {
   @Input
   FileCollection classpath
}

task foo(type: MyTask)
```

`gradle foo` is enough to reproduce it.

**Comment by adammurdoch** [comment]
I can take a look when I get back. I only just noticed it was waiting for me to do something.

**Comment by bamboo** [comment]
With #9810 the NPE no longer occurs but the build still fails, this time with:

```
FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:classes
\--- :compileJava
     \--- :generateXtext
          \--- :classes (*)

(*) - details omitted (listed previously)
```

My guess is that now that properties carry task dependency information a previously hidden circular dependency might have been exposed. @cdietrich, does the new build failure ring any bells?

**Comment by cdietrich** [comment]
no this is new as well. @oehme do you have an idea (i assume you still have plenty insights of the plugin)? or is the circle intentional since we create java classes that might help to compile the java classes

**Comment by oehme** [comment]
generateXtext certainly shouldn't depend on the classes task. But we can take that issue over to the Xtext plugin issue tracker.

**Comment by cdietrich** [comment]
is there any command that helps me to find out where this dependency is coming from?

**Comment by cdietrich** [comment]
created https://github.com/xtext/xtext-gradle-plugin/issues/154 for the cycle problem
