### ISSUE TITLE
[BUG?] Gradle wrapper does not use proxy settings

### ISSUE THREAD

**Issue by hron84** [gradle/gradle#9744]
Gradle wrapper - with properly configured proxy settings - does not use proxy, tries to connect directly to services.gradle.org instead.

Given the following `gradle/wrapper/gradle-wrapper.properties`

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=http\://services.gradle.org/distributions/gradle-4.10.3-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists

systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=8123
http.proxyHost=127.0.0.1
http.proxyPort=8123
```

**NOTE:** I know downloading via HTTP instead of HTTPS is insecure, but even with HTTP it does not work. I tried it with HTTPS with same result, but to keep the report simple include outputs from this case. 

Wget and Curl can download the distibution zip properly with the settings above (adapted to their own config format, of course). 

### Expected Behavior

Gradle wrapper could download the distribution zip without any issue.

### Current Behavior

Currently Gradle wrapper tries to download the zip and timeouts after 12000 seconds as pictured below:

```
Downloading http://services.gradle.org/distributions/gradle-4.10.3-bin.zip

Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
        at org.gradle.wrapper.Download.download(Download.java:51)
        at org.gradle.wrapper.Install$1.call(Install.java:62)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```
### Context

This is an uncounted approach to make Gradle working in a difficult corporate proxy setup. We have a 3rdparty proxy and I have zero access to its log or it's configuration and I periodically get refused to make configuration changes in it, so letting Gradle to bypass the proxy is not an option. 

First I tried to accomplish the proxy setup with directly connecting to the corporate proxy but after I faced with this strange timeout error I guessed it fails somehow to understand the authentication and falls back to connecting directly. 

So I tried to setup a local tinyproxy that does not require authentication and handles it on its own with the corporate proxy. Since at this point I could access Tinyproxy and its output, I could finally see Gradle does not try even to connect to it, despite proxy is configured via its properties **and** via http_proxy environment variable. I tried to configure it only via the properites and via the environment variable, neither work.

Since I'm not a Java/Android/Groovy developer, maybe the problem is I do not know this tool enough and I try to configure it on wrong way. I read the documentation on Gradle website how to configure proxy setup, I tried to configure proxy values in `~/.gradle/gradle-wrapper.properties` too, but with same result as above. 

Also `http.proxyHost` values are the latest hopeless test to make it work since most Java application accept this property instead of `systemProps.http.proxyHost` to configure proxy. I tried it without these options, with same result.

### Steps to Reproduce 

Setup a proxy server, configure Gradle wrapper to use it and make sure Gradle wrapper is not able to download the distribution zip without accessing the proxy (make sure you refuse any outgoing HTTP communication except the proxy)

P.S: It would be also nice if Gradle wrapper could accept some debugging parameters / options to make it more verbose what it is trying to do, or just make error messages more descriptive to simplify troubleshooting errors on the ops side.

**Comment by sschuberth** [comment]
Seems to be related to https://github.com/gradle/gradle/issues/5052, except that the other issue says `http.proxyHost` and `http.proxyPort` to be in fact working, but `http.proxyUser` and `http.proxyPassword` are not.

**Comment by sschuberth** [comment]
I guess the misunderstanding here is that `systemProp.http.proxyHost` and `systemProp.http.proxyPort` should be configured in `~/.gradle/gradle.properties` and not in the `gradle-wrapper.properties` file. See the somewhat related docs on [Authenticated Gradle distribution download](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:authenticated_download) and [Accessing the web through a HTTP proxy](https://docs.gradle.org/current/userguide/build_environment.html#sec:accessing_the_web_via_a_proxy).

**Comment by hron84** [comment]
@sschuberth Yup, later i figured out how it works. However, you should express in the template of `gradle-wrapper.properties` that `gradlew` **do** read some settings from `~/.gradle/gradle.properties` because it maybe obvious for a developer like you but not for a sysadmin who have to fight with this like me.

**Comment by sschuberth** [comment]
@hron84 instead of adding a comment to the generated `gradle-wrapper.properties`, which is less trivial, I've improved the docs in the linked PR #10101.

**Comment by mayankkapoor** [comment]
I had the same misconception. Found this thread to be super useful. Thanks @hron84.
