### ISSUE TITLE
resolutionStrategy.componentSelection.all requires non intutive call to be used [kotlin]

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#987]
In order to configure `ComponentSelection` rules in kotlin you must use the following incantation:

```kotlin
val schemaLookup = configurations.create("customizations-schema-lookup") {
    it.resolutionStrategy
        .componentSelection
        .all(object : Action<ComponentSelection> {
            @Mutate
            override fun execute(selection : ComponentSelection) {
                println("Executing")
                println(selection)
            }
        })
}
```
This works!

### Expected Behavior

This should work to add a `componentSelection` rule.
```kotlin
val schemaLookup = configurations.create("customizations-schema-lookup") {
    it.resolutionStrategy
        .componentSelection
        .all({ selection : ComponentSelection ->
            println("Executing")
            println(selection)
        })
}
```

### Current Behavior

With the code in the Expected Behavour section you get this exception:
```
        ...
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.InvalidUserCodeException: The rule source provided does not provide a valid rule for 'ComponentSelectionRules'.
        at org.gradle.internal.rules.DefaultRuleActionAdapter.createFromRuleSource(DefaultRuleActionAdapter.java:57)
        at org.gradle.api.internal.artifacts.ivyservice.resolutionstrategy.DefaultComponentSelectionRules.all(DefaultComponentSelectionRules.java:101)
        at Project_gradle$schemaLookup$1.execute(Project.gradle.kts:107)
        at Project_gradle$schemaLookup$1.execute(Project.gradle.kts:7)
        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.create(AbstractNamedDomainObjectContainer.java:64)
        at Project_gradle.<init>(Project.gradle.kts:104)
        at org.gradle.script.lang.kotlin.provider.KotlinBuildScriptCompiler.executeScriptOf(KotlinBuildScriptCompiler.kt:147)
        at org.gradle.script.lang.kotlin.provider.KotlinBuildScriptCompiler.executeScriptWithContextClassLoader(KotlinBuildScriptCompiler.kt:141)
        at org.gradle.script.lang.kotlin.provider.KotlinBuildScriptCompiler.access$executeScriptWithContextClassLoader(KotlinBuildScriptCompiler.kt:38)
        at org.gradle.script.lang.kotlin.provider.KotlinBuildScriptCompiler$onePassScript$1.invoke(KotlinBuildScriptCompiler.kt:100)
        at org.gradle.script.lang.kotlin.provider.KotlinBuildScriptCompiler$onePassScript$1.invoke(KotlinBuildScriptCompiler.kt:38)
        at org.gradle.script.lang.kotlin.provider.KotlinScriptPlugin.apply(KotlinScriptPlugin.kt:40)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
        ... 64 more
Caused by: org.gradle.internal.rules.RuleActionValidationException: Type Project_gradle$schemaLookup$1$1 is not a valid rule source:
- Must have at exactly one method annotated with @org.gradle.model.Mutate
        at org.gradle.internal.rules.RuleSourceBackedRuleAction.create(RuleSourceBackedRuleAction.java:73)
        at org.gradle.internal.rules.DefaultRuleActionAdapter.createFromRuleSource(DefaultRuleActionAdapter.java:55)
        ... 79 more
```

### Context

I am trying to add a custom dependency resolution rule in Gradle Script Kotlin

### Steps to Reproduce (for bugs)

Just running a build with this code should demonstrate the problem:
```kotlin
val schemaLookup = configurations.create("customizations-schema-lookup") {
    it.resolutionStrategy
        .componentSelection
        .all({ selection : ComponentSelection ->
            println("Executing")
            println(selection)
        })
}
```

Then running this should expose the bug:
```
./gradlew dependencies
```

### Your Environment

As I'm writing a proprietary build system I won't provide a build scan.

Gradle version: `gradle-script-kotlin-3.3-20161123161139+0000-all`
Java version:
```
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
```

gradle.properties:
```
org.gradle.parallel=true
org.gradle.configureondemand=true
```

### Potential Cause

Looking at the decompiled code for `DefaultComponentSelectionRules` (decompiled by Intellij Ultimate) it looks like action and closures are handled differently:
```java
    public ComponentSelectionRules all(Action<? super ComponentSelection> selectionAction) {
        return this.addRule(this.createAllSpecRulesAction(this.ruleActionAdapter.createFromAction(selectionAction)));
    }

    public ComponentSelectionRules all(Closure<?> closure) {
        return this.addRule(this.createAllSpecRulesAction(this.ruleActionAdapter.createFromClosure(ComponentSelection.class, closure)));
    }
```

**Comment by bamboo** [comment]
Superseded by gradle/gradle-script-kotlin#196.
