### ISSUE TITLE
Extracting cache entry fails on non-UTF-8 system locale

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#9877]
When unpacking a cached result on a system with a non-UTF-8 encoding this can happen:

```text
Caused by: java.nio.charset.UnmappableCharacterException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:282)
        at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:816)
        at org.apache.commons.compress.archivers.zip.NioZipEncoding.decode(NioZipEncoding.java:133)
        at org.apache.commons.compress.archivers.tar.TarUtils.parseName(TarUtils.java:299)
        at org.apache.commons.compress.archivers.tar.TarArchiveEntry.parseTarHeader(TarArchiveEntry.java:1275)
        at org.apache.commons.compress.archivers.tar.TarArchiveEntry.parseTarHeader(TarArchiveEntry.java:1266)
        at org.apache.commons.compress.archivers.tar.TarArchiveEntry.<init>(TarArchiveEntry.java:404)
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:283)
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:552)
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.paxHeaders(TarArchiveInputStream.java:444)
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:318)
        at org.gradle.caching.internal.packaging.impl.TarBuildCacheEntryPacker.unpackDirectoryTree(TarBuildCacheEntryPacker.java:292)
        at org.gradle.caching.internal.packaging.impl.TarBuildCacheEntryPacker.unpackTree(TarBuildCacheEntryPacker.java:254)
        at org.gradle.caching.internal.packaging.impl.TarBuildCacheEntryPacker.unpack(TarBuildCacheEntryPacker.java:198)
        at org.gradle.caching.internal.packaging.impl.TarBuildCacheEntryPacker.unpack(TarBuildCacheEntryPacker.java:158)
        at org.gradle.caching.internal.packaging.impl.GZipBuildCacheEntryPacker.unpack(GZipBuildCacheEntryPacker.java:49)
        at org.gradle.caching.internal.command.BuildCacheCommandFactory$LoadCommand.load(BuildCacheCommandFactory.java:94)
        at org.gradle.caching.internal.controller.DefaultBuildCacheController$Unpack$1.run(DefaultBuildCacheController.java:178)
        at
```

**Comment by lptr** [comment]
Looks like this problem has been around for a long time. When we started setting the encoding for the TAR files that store the cached output when they were created, we apparently forgot to set it for when they were unpacked:

https://github.com/gradle/gradle/commit/ffdd4fcca3b56a72d3bc6b2c945f309ccff2ad56

**Comment by blindpirate** [comment]
I guess some files include non-ASCII code, thus they're affected by encoding.

**Comment by lptr** [comment]
Yes, though I'm having a hard time reproducing the problem.

The TAR implementation in `commons-io` has some workarounds to fix UTF-8 problems, which should be enabled:

https://github.com/apache/commons-compress/blob/master/src/main/java/org/apache/commons/compress/archivers/zip/NioZipEncoding.java#L163-L166

So I find it strange that an error pops up anyway.

Still, I [tried to reproduce](https://github.com/gradle/gradle/blob/c03f87f89d606a9def83e8143001b31ab0137d59/subprojects/core/src/integTest/groovy/org/gradle/caching/internal/packaging/BuildCacheEntryPackingIntegrationTest.groovy#L58-L70) with the following strings:

- `input-file.txt`
- `文件.txt`
- `равствуйте.txt`
- `zső.txt`
- `put file.txt`
- `put\u200cfile.txt`
- `input%<file>#2.txt`

With the following default encodings (setting `file.encoding` system property):

- `UTF-8`
- `USASCII`
- `ISO-8859-1`
- `ISO-8859-5`

(Couldn't get `GBK` to work for some other weird reason.)

My understanding is that the files get stored and loaded just fine despite the missing encoding definition.

**Comment by lptr** [comment]
See the test in PR https://github.com/gradle/gradle/pull/9880.

**Comment by lptr** [comment]
OK, we now have a good reproduction about this issue (thanks @wolfs). Strangely, the problem only occurs when the OS default encoding is set to some very specific encodings.

### Breaks

- `windows-1251` (Central/Eastern European),
- `windows-1252` (Legacy Latin)
- `windows-1253` (Greek)
- `windows-1254` (Turkish)
- `windows-1257` (Estonian, Latvian and Lithuanian)

### Works

- `windows-1250` (Western European)
- `ISO-8859-1` (Western European)
- `ISO-8859-2` (Central/Eastern European),
- `ISO-8859-4` (North European)
- `ISO-8859-5` (Cyrillic)
- `ISO-8859-9` (Turkish)
- `ISO-8859-13` (Baltic)

So it looks like some (but not all) single-byte Windows character sets are affected, while their ISO counterparts work without the fix.

In any case #9880 adds the fix and makes things work for all these Windows encodings as well.
