### ISSUE TITLE
Starting gradle build with ProcessBuilder (while redirecting input !) throws IOException

### ISSUE THREAD

**Issue by sutchark** [gradle/gradle#9953]
### Expected Behavior
No IOException

### Current Behavior
IOException

### Context
I start a gradle build from Java code using ProcessBuilder. When using processBuilder.redirectInput(ProcessBuilder.Redirect.INHERIT); it will throw this exception:

`[Execute]
	gradle -i cleanEclipse eclipse
Initialized native services in: /home/nemo/.gradle/native
Exception in thread "DisconnectableInputStream source reader" org.gradle.api.UncheckedIOException: java.io.IOException: Bad file descriptor
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:61)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
        at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:125)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Bad file descriptor
        at java.io.FileInputStream.readBytes(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:255)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:96)
        ... 1 more
`

The build still completes successfully. Turning off the Input-Redirect will also prevent the IOException

### Steps to Reproduce 
Write a minimal Java program and use ProcessBuilder to execute a Gradle build.
Add/Remove this line from the Java program:
processBuilder.redirectInput(ProcessBuilder.Redirect.INHERIT);

**Comment by dellgreen** [comment]
I think this is a wider problem, i can get the same error just by prefixing nohup before running the gradle wrapper.
And it was reported a while back before the move the github.

https://issues.gradle.org/browse/GRADLE-3535
